### ISSUE TITLE
DIIS does not use linearly independent basis

### ISSUE THREAD

**Issue by susilehtola** [pyscf/pyscf#1000]
The DIIS code in PySCF appears to use AO matrices. This is not recommended, see Pulay's work from the early 1980s, as the algorithm does not work in the presence of linear dependencies. 

A better alternative is to project the matrices into the orbital basis, as this eliminates the linear dependencies.

The following calculation (needs the changes from pull #999 to run)
```
from pyscf import gto, scf

mol = gto.Mole()
mol.verbose = 4
mol.atom = '''                                                                                                                                                                                
Ne 0 0 0                                                                                                                                                                                      
Ne 0 0 1e-3'''
mol.basis = 'unc-aug-cc-pvtz'
mol.symmetry = 0
mol.build()

mf = scf.RHF(mol)
mf = scf.addons.remove_linear_dep_(mf, threshold=1e-5, cholesky_threshold=1e-6, force_pivoted_cholesky=True)
mf.init_guess = '1e'
# This fails                                                                                                                                                                                  
mf.kernel()

# DIIS in PySCF does not work properly; turn it off                                                                                                                                           
mf.diis=None
# This converges in 13 iterations                                                                                                                                                             
mf.kernel()
```
is an extreme demonstration of the issue: the basis set orthogonalization eliminates 47 basis functions out of a total of 116, leaving only 69 basis functions; this is a calculation from my recent paper [Phys. Rev. A 101, 032504 (2020)](https://journals.aps.org/pra/abstract/10.1103/PhysRevA.101.032504).

When DIIS is enabled, the calculation diverges. Turning off DIIS the calculation converges in 13 iterations when started from the core guess; when started from the default guess, the calculation fails to converge.

In contrast, the same calculation in ERKALE started from the SAD guess and DIIS yields convergence in just 5 iterations.

**Comment by susilehtola** [comment]
In [Chem. Phys. Lett. 73, 393 (1980)](https://doi.org/10.1016/0009-2614(80)80396-4) Pulay writes
> An even better choice is the use of Fock matrix elements transformed to an orthonormal basis, such as `S^-1/2 F S^-1/2` where `S` is the overlap matrix. This takes into account that a charge shift from a basis function to another is less important physically if the two functions overlap strongly.

Obviously, `S^-1/2` can be simply replaced by the molecular orbital coefficients `C`.

**Comment by Majokux** [comment]
How does this work with SDF-FDS type DIIS? Simply replace it with DF-FD, both in MO basis?

**Comment by susilehtola** [comment]
> How does this work with SDF-FDS type DIIS? Simply replace it with DF-FD, both in MO basis?

The only thing you need to do is project SDF-FDS into the orthonormal basis: error matrix = X^T [SDF-FDS] X. Then you calculate the DIIS error.

**Comment by Majokux** [comment]
So you do the extrapolation in a different (AO) basis then how you define the error vector? Do you not also have to rotate your Fock matrix from AO to X before the update, and then rotate back after extrapolation?

**Comment by susilehtola** [comment]
The error vectors are computed in the orthonormal basis as instructed by Pulay, 1980: DIIS should only see the linearly independent part of the basis. This gives you the expansion coefficients.

Then, you build the extrapolated Fock matrix as you do now using these coefficients.

**Comment by susilehtola** [comment]
Yes, most codes implement DIIS using X, the orthogonalizing matrix. But this is not used in PySCF. An alternative is to use the first set of molecular orbitals as X, since they are essentially the same thing.

**Comment by susilehtola** [comment]
It turns out that it sufficed to modify `get_err_vec()` in `diis.py` to compute the error vector in the projected basis, and initialize the orthonormal basis in `hf.kernel()` by running the eigendecomposition of any matrix (I took the overlap `s`) and using those eigenvectors.

The linearly independent basis is built inside `mf.eig()` in PySCF, so this approach is completely method agnostic. If there's no linear dependency cleanup, `mf.eig()` returns a full-rank matrix so you lose nothing. If you use canonical orthogonalization or  partial Cholesky orthogonalization, then you get whatever eigenvectors you use also to diagonalize the Fock matrix.

With the changes in #1008, the first calculation now converges in 10 iterations.

**Comment by susilehtola** [comment]
Thanks @sunqm !

**Comment by pedrocor** [comment]
Hello @susilehtola !

I hope you are doing well, I know this is an old topic. I was creating some code and I would like to use DIIS for my convergence. I was wondering if the inputs for the "update(s,d,f,errvec)" function of the DIIS object should to be orthogonal -- as in  "update(s,d,ortho_f,ortho_errvec)", or does PySCF do that already? Also are the outputs orthogonal by default or should I orthogonalize the extrapolated Fock matrix? This is my test code currently:
`moltype, x, y, z, sim = inputSet.get_molecule_xyz("/home/pedro/QDFT/water.xyz")
quantSCF = qscf.QSCF()
quantSCF.buildGeometry(moltype,x,y,z)
quantSCF.initializeGuess()
quantSCF.qscf.max_cycle = 1
quantSCF.qscf.kernel()
n = quantSCF.qscf.make_rdm1()
F = quantSCF.fockMatrix(n)
orthoF = quantSCF.orthoFock(F)
errVec = quantSCF.X.T @ (F @ n @ quantSCF.S - quantSCF.S @ n @ F) @ quantSCF.X
quantSCF.diisObj.push_err_vec(errVec)
# Adds the error matrix to the DIIS object history
quantSCF.F = quantSCF.diisObj.update(quantSCF.S, n, F, errVec)
print(quantSCF.F)`

Thank you!
