### ISSUE TITLE
QM/MM for a Gamma-point  calculation? 

### ISSUE THREAD

**Issue by hungpham2017** [pyscf/pyscf#1001]
Dear PySCF developers,

I have two understanding questions: 
(1) if QM/MM is run using a Gamma-point mean-field as the QM and the qmmm module for molecule, does it mean V_{nuc-MM} and V_{elec-MM} are simply between the interaction between **one** unit cell and the MM cluster? In other words, there is no periodic long-range interaction here that needs Ewald summation?

(2) If (1) is True, is there any equivalent qmmm module for a Gamma-point mean-field? Or is it this even a thing?

Thank you
Hung

**Comment by tberkel** [comment]
Hi Hung,

(1) I'm not sure what the default behavior of a periodic qmmm calculation
would be without digging into that code, but my guess is that you are
correct.

(2) The closest sensible thing I know of off-hand is the periodic
electrostatic embedded cluster method, first described here:
https://aip.scitation.org/doi/abs/10.1063/1.3123527 -- given the existing
infrastructure in PySCF, I can't imagine this (or something similar) would
be too hard to implement.

**Comment by hungpham2017** [comment]
@tberkel  Thank you very much for your explanation and the paper. Indeed, embedding a QM cluster in a periodic array of point charges is common. I was, just out of curiosity, wondering about embedding a QM layer of unit cells (within PBC) in/on top of a periodic array of point charges. It is worth the effort to put in PySCF only if this approximation has a physical meaning and applicability. Thanks again.

**Comment by tberkel** [comment]
I don't think there's much use in retaining QM PBCs "in the direction" of
the MM point charges, i.e. across a boundary of MM point charges. However,
this could certainly be useful for surfaces, for example, where you could
have a layer of QM atoms on top of MM point charges and maintain QM PBCs in
the lateral directions.

**Comment by hungpham2017** [comment]
the application you suggested was actually how my question started. I tag a colleague, @mitra054 who may be interested in looking into this in further detail.
