### ISSUE TITLE
A error related to h5py

### ISSUE THREAD

**Issue by swillow** [pyscf/pyscf#1003]
One student found out the following error:
ValueError: Using default_file_mode other than 'r' is no longer supported. Pass the mode to h5py.File().
And she fixed this error by installing h5py again as follows:
pip install h5py==2.10.0

---
It seems to me that h5py released version 3.3.0 now. I wonder whether pyscf can run a job with h5py=3.3.0.

**Comment by m-i-w** [comment]
I had this same errror, python 3.9.5 & pyscf 1.7.6. From the source code it looks like this is fixed by removing lines 45 and 46 from `lib/misc.py`.

**Comment by fishjojo** [comment]
This has been fixed in Pyscf v2.0.0.a, although it's not on Pypi yet.

**Comment by ValentinS4t1qbit** [comment]
@fishjojo This error has been nagging us for a bit, and I realize with your comment that on my side, pip still installs pyscf v.1.7.6. (for both Mac and linux). Could it be we are very overdue for an update on peppy ?

**Comment by fishjojo** [comment]
Pyscf 2.0 has been released. Please try it out.

**Comment by verena-neufeld** [comment]
Hi @swillow , has this been resolved?

**Comment by swillow** [comment]
Sorry. I did not know I had to say that this has been resolved. Yes, it had been solved.
