### ISSUE TITLE
GKS calculations for PBE and BP86 differs for XCFun and Libxc

### ISSUE THREAD

**Issue by hoshishin** [pyscf/pyscf#1004]
Dear dev Dear PySCF developers,

I calculate Li atom, using both Libxc and XCFun, the Exc differs. And the same problem occurs, when using BP86, but not for BLYP.

`molu = gto.Mole()
molu.verbose = 6
molu.atom = "Li 0 0 0" ###
molu.spin=1 # ^ Spin
molu.basis = "sto-3g" # ^ Basis
molu.max_memory = 5000
molu.build()

mftot_nr = dft.GKS(molu)
mftot_nr.xc = "BP86" # ^ functional
mftot_nr.max_cycle = 0 # ^ max cycle
mftot_nr.kernel()
`

Now, I can't understand why this could happen, thanks a lot!

**Comment by Haskiy** [comment]
I met the similar question. And I try my best to solve it , however, I failed.

**Comment by hoshishin** [comment]
@Haskiy Thank you for your reply,  did the calculation you did has a very conspicuous results,  like mo energy or SCF energy?

**Comment by fishjojo** [comment]
The implementations of the functionals in the two libraries are different. I checked the converged energies, which differ at the order of 1e-6, which seems ok.

**Comment by susilehtola** [comment]
Yes, differences of one microhartree are definitely okay. For identical functionals you can typically get agreement to 1e-7, 1e-8 or even 1e-9 by using very tight integration grids like (450, 974).

**Comment by hoshishin** [comment]
Thank you for your kindly replys. When using BDF of XCFun and Libxc, it gives the SCF energy agreement to 1e-10 (only 10 digits have been printed.), thus, I expect PySCF would give the same agreement.

**Comment by susilehtola** [comment]
You probably need to use tighter convergence thresholds and possibly a larger DFT grid in PySCF to get that level of agreement.

**Comment by hoshishin** [comment]
Well, I have use the grids.level = 9, but inagreement also occurs.

**Comment by susilehtola** [comment]
```
from pyscf import gto, dft

molu = gto.Mole()
molu.verbose = 5
molu.atom = "Li 0 0 0" ###                                                                                                                                                                    
molu.spin = 1 # ^ Spin                                                                                                                                                                        
molu.basis = "sto-3g" # ^ Basis                                                                                                                                                               
molu.max_memory = 5000
molu.build()

mftot_nr = dft.UKS(molu)
mftot_nr._numint.libxc = dft.xcfun
#mftot_nr.xc = "gga_x_b88,gga_c_p86" # libxc BP86                                                                                                                                             
#mftot_nr.xc = "gga_x_b88,gga_c_p86_ft" # libxc BP86 with more accurate value for pi                                                                                                          
mftot_nr.xc = "BP86" # ^ functional                                                                                                                                                           
mftot_nr.max_cycle = 1000 # ^ max cycle                                                                                                                                                       
mftot_nr.grids.prune = None
mftot_nr.grids.atom_grid = (250, 974)
mftot_nr.conv_tol=1e-10
mftot_nr.conv_tol_grad=1e-9
mftot_nr.kernel()
```
This gives me the following energies

| Calculation | E | 
|---------------|----|
|xcfun, BP86|-7.3588935900943|
|libxc, BP86|-7.35785493641659|

However, P86 has two variants in libxc

| Calculation | E | 
|---------------|----|
|libxc: gga_x_b88,gga_c_p86|-7.35886721558911|
|libxc: gga_x_b88,gga_c_p86_ft|-7.35889315990209|

The converged energies agree to 4.3e-7 Hartree, if you look at the XCFun value and the `gga_x_b88,gga_c_p86_ft` calculation.

**Comment by susilehtola** [comment]
Back to your example, I get `-7.3377174511778` with libxc (`gga_x_b88,gga_c_p86_ft`) vs `-7.33771799839656` with xcfun, which is a difference of 5.47e-7 Hartree. Perhaps BP86 in PySCF should be more consistent between the two implementations; however, I doubt this will have any effect on chemistry

**Comment by hoshishin** [comment]
Thank you so much, susilehtola. Can I just conclude that the implementations of the functionals in the  XCFun and LIBxc are different, and it's reasonable to have some different results, which are not so apparent?

**Comment by susilehtola** [comment]
Yes, this is the case with some of the older functionals, especially, which have been originally implemented in a variety of fashions in different codes. Of course, the problem is that most papers describing new density functionals don't even include sufficient raw data to verify new implementations of the functional!

Common discrepancies are varying numbers of decimals, e.g. the difference between `gga_c_p86` and `gga_c_p86_ft` is that the former uses the numerical factor `1.745` as in the original paper while the latter uses a more accurate numerical value for `(9*pi)^(1/6) = 1.745415...`. These tend to affect absolute energies, but typically don't affect properties that much...

**Comment by hoshishin** [comment]
Thank you so much, susilehtola. I have a more deeper understanding of this problem. Many thanks.

**Comment by sunqm** [comment]
You can inspect the error with a small script, e.g.

```
rho = np.array([[0.001, 0, -0.0001, -0.0001]])
print(dft.libxc.eval_xc(',p86', rho))
print(dft.xcfun.eval_xc(',p86', rho))
```

**Comment by hoshishin** [comment]
Thank you, sunqm! Use dft.libxc.eval_xc and dft.xcfun.eval_xc for a single grid can truly see the difference between those 2 implementation.
