### ISSUE TITLE
Open shell singlet UHF/UKS calculations

### ISSUE THREAD

**Issue by leochaussy** [pyscf/pyscf#1005]
Hello, 
I am trying to perform open-shell UHF calculation on H2. I try to force this solution by imposing symmetry and spin to each spinorbital (one alpha electron in A1g and one beta electron in A1u) with the irrep_nelec method. However, this directive seems to be ignored and we return to the ground state closed shell singlet after execution.

Is it possible to obtain this kind of open shell singlet solution with symmetry and spin restriction only at the HF (or DFT) level. I am probably missing something here. 

`#H2 Singlet open shell
h2_s2 = gto.Mole()
h2_s2.verbose = 4
h2_s2.atom = [
    ["H", (0., 0.,  2.5)],
    ["H", (0., 0., -2.5)],]
h2_s2.spin = 0
h2_s2.symmetry = True
h2_s2.irrep_nelec = {'A1g':(1,0), 'E1gx': (0, 0), 'E1gy': (0, 0),'A1u' : (0,1),'E1uy': (0, 0),'E1ux': (0, 0)}
h2_s2.basis = 'cc-pvdz'
h2_s2.build()

#UHF Singlet
mf = scf.uhf_symm.SymAdaptedUHF(h2_s2)
mf.kernel()

mf.get_irrep_nelec()`

**Comment by sunqm** [comment]
```
h2_s2 = gto.Mole()
h2_s2.verbose = 4
h2_s2.atom = [
["H", (0., 0., 2.5)],
["H", (0., 0., -2.5)],]
h2_s2.spin = 0
h2_s2.symmetry = True
h2_s2.basis = 'cc-pvdz'
h2_s2.build()
mf = h2_s2.UHF()
mf.irrep_nelec = {'A1g':(1,0), 'E1gx': (0, 0), 'E1gy': (0, 0),'A1u' : (0,1),'E1uy': (0, 0),'E1ux': (0, 0)}
mf.kernel()
```

**Comment by leochaussy** [comment]
Thank you !
