### ISSUE TITLE
pip install failed in conda environment on apple silicon M1

### ISSUE THREAD

**Issue by PKUfjh** [pyscf/pyscf#1012]
I install Miniforge3-MacOSX-arm64.sh on my new M1 MacBook Air, then pip install pyscf leads to error
<img width="947" alt="截屏2021-07-12 上午12 54 36" src="https://user-images.githubusercontent.com/32134282/125203624-be01b500-e2ab-11eb-893d-296e5c042f5f.png">

installing Miniforge3-MacOSX-x86_64.sh then pip install pyscf works, but pyscf can not be imported properly.

Any help or suggestions are appreciated.

**Comment by sunqm** [comment]
There is no pip wheel compiled for M1 chip. You will need to compile from source code for the moment

**Comment by PKUfjh** [comment]
> There is no pip wheel compiled for M1 chip. You will need to compile from source code for the moment

Sorry...but how to compile from the source code?

**Comment by JoelHBierman** [comment]
@PKUfjh The instructions for compiling from source code are given here:https://pyscf.org/install.html. Let me know if you have any success with this. I have been trying for quite some time now without success.

**Comment by gkc1000** [comment]
Currently we are not yet support M1 natively. For development it should work to install under a Rosetta Terminal see e.g. https://www.courier.com/blog/tips-and-tricks-to-setup-your-apple-m1-for-development. That is how I am working with pyscf!

I will close for now, re-open if there are issues with Rosetta.

**Comment by jwnys** [comment]
Would it be possible to make this work through miniforge (which most people with MacOS M1 are using)?

**Comment by jwnys** [comment]
Just wondering what the main issue is? Personally, I was able to now build with pip from github in a conda environment (after searching for quite a bit, and having all the issues I've seen here) by using first:
```console
conda install -c conda-forge openmpi-mpicc
```
So, not Rosetta needed.

**Comment by jamesETsmith** [comment]
@jwnys, that's good to know, thanks for sharing what worked! The original post here was trying to install a pre-built wheel with pip (which didn't exist), which I though you were also trying to do, apologies if I misunderstood. There were some other challenges on M1 machines when building with the native macos clang compiler.

For other people who get directed here in the future, the detailed discussion (which it sounds like you've already found) is [here](https://github.com/pyscf/pyscf/issues/1096#issuecomment-963569958).
