### ISSUE TITLE
Multiple Installation issues for macosx-arm64

### ISSUE THREAD

**Issue by JoelHBierman** [pyscf/pyscf#1015]
### Informations

- **Python version**: 3.9.5
- **Operating system**: MacOS 11.4

### What is the current behavior?

I have tried two methods of building pyscf for platform macOS-arm64 (Apple silicon): 1. `pip install pyscf` and 2. Following the install instructions given at https://pyscf.org/install.html for compiling from source. Both methods run into multiple errors to the point where trying to install it is a convoluted mess. This error seems to be specific  to this platform because `pip install pyscf` works fine for macosx-x86_64. I know it should be possible to build for this platform because someone else has already done it in issue #979. The simplest way to do it is not at all clear to me. If anyone has any insight how to do this or why these errors are popping up, it would be greatly appreciated. 

### Steps to reproduce the problem

Initialize a conda environment native to macosx-arm64 by running the following terminal commands:

`$ CONDA_SUBDIR=osx-arm64 conda create -n <env-name> numpy -c conda-forge`

Next, run:

`$ conda env config vars set CONDA_SUBDIR=osx-arm64`

Deactivate the environment and reactivate it, then run:

`$ conda install h5py -c conda-forge`

The next steps depend on which method you try:

`pip install pyscf` method:

Pyscf will not build if you simply run `pip install` because it will say it cannot find `libcint` as shown in 
[build3.log](https://github.com/pyscf/pyscf/files/6797564/build3.log). First you must install `libcint` as per the instructions at http://orbkit.github.io/dev/integrals/install.html:

```
$ git clone http://github.com/sunqm/libcint.git
$ cd libcint
$ mkdir build; cd build
$ cmake -DCMAKE_INSTALL_PREFIX:PATH=$HOME/libcint/ ..
$ make install
$ export PATH=$PATH:$HOME/libcint
$ run `export PYSCF_INC_DIR=$PATH:$HOME/libcint`
$ pip install pyscf
```

Then you get the error as given in :
[build4.log](https://github.com/pyscf/pyscf/files/6797566/build4.log)

Method 2: Compile from source:

```
$ git clone https://github.com/pyscf/pyscf.git
$ cd pyscf
$ cd pyscf/lib
$ mkdir build
$ cd build
$ cmake ..
```

Because just running `make` like this will lead to the error given in 
[build.log](https://github.com/pyscf/pyscf/files/6797579/build.log)

you need to go to the directory `path/to/pyscf/pyscf/lib/build/config.h` and change the line that says `#include <omp.h>` to `#include "/opt/homebrew/opt/libomp/include/omp.h"`. (or wherever you have `libomp` installed.)

Then because of issue #940 you need to make the changes to the file `/path/to/pyscf/pyscf/lib/CMakeLists.txt` outlined there. If you do this and run `make`, again, CMake will sometimes undo the changes you made to the `config.h` file. If it does, just redo the changes and run it again. Then you run into the error given in 
[build4.log](https://github.com/pyscf/pyscf/files/6797582/build4.log).

### What is the expected behavior?

Pyscf builds and installs.

If anyone has any insights or knows a simple way to run pyscf natively on this platform, it would be greatly appreciated.

**Comment by JoelHBierman** [comment]
Hi @DuckTigger. My apologies for the late reply. I got a bit frustrated with this problem so I thought it best to step away from this for a while to focus on other things. Thank you for the helpful instructions! I have gotten to the point where the build seems to finish after running the `make` command, but if I try to import the package in a python shell, I get the following error related to h5py:

```
>>> import pyscf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/joelbierman/pyscf/pyscf/__init__.py", line 113, in <module>
    from pyscf import lib
  File "/Users/joelbierman/pyscf/pyscf/lib/__init__.py", line 24, in <module>
    from pyscf.lib import numpy_helper
  File "/Users/joelbierman/pyscf/pyscf/lib/numpy_helper.py", line 27, in <module>
    from pyscf.lib import misc
  File "/Users/joelbierman/pyscf/pyscf/lib/misc.py", line 31, in <module>
    import h5py
  File "/Users/joelbierman/miniforge3/envs/pyscf-build-test/lib/python3.9/site-packages/h5py/__init__.py", line 25, in <module>
    from . import _errors
ImportError: dlopen(/Users/joelbierman/miniforge3/envs/pyscf-build-test/lib/python3.9/site-packages/h5py/_errors.cpython-39-darwin.so, 2): Library not loaded: @rpath/libhdf5.103.dylib
  Referenced from: /Users/joelbierman/miniforge3/envs/pyscf-build-test/lib/python3.9/site-packages/h5py/_errors.cpython-39-darwin.so
  Reason: image not found
```

Have you run into the same issue as well?

**Comment by JoelHBierman** [comment]
Update: I got it to work building from the GitHub branch for 1.7. There seem to be some problems with 2.0. Thank you so much for your help @DuckTigger!

**Comment by DuckTigger** [comment]
Good to know -  do you have the same issues as in https://github.com/pyscf/pyscf/issues/979#issue-919174791 ?
I haven't checked in a while but I did have that issue (thankfully for my purposes I don't rely on those calculations)

**Comment by JoelHBierman** [comment]
I have not tested that as of right now. My only use of pyscf to date as been to obtain molecular data to generate second quantization electronic structure Hamiltonians for use in quantum computation packages like Qiskit, which I have been running natively for some time now. The way I've worked around pyscf not running natively in the past is to set up an x86 environment, run pyscf and save the data to a file which is read out by other packages in an M1 environment. My main motivation for running pyscf natively is to just avoid that hassle.
