### ISSUE TITLE
S can have negative eigenvalues in pyscf/pbc

### ISSUE THREAD

**Issue by btglau** [pyscf/pyscf#1017]
I discovered a bug where a certain orientation of lattice vectors will result in a non-positive definite S that will crash the first call to `eigh` in the SCF cycle. The issue arises when I use a FCC lattice with vectors defined in the quantum-espresso convention (all x-coordinates are negative, i.e. a flip in the yz plane) with a supercell where the atoms are placed using a more 'conventional' choice of lattice vectors (all vectors in the positive octant), as I show in more detail in the MWE attached.

[negS_mwe.txt](https://github.com/pyscf/pyscf/files/6810813/negS_mwe.txt)

I have not exhaustively tested the scenarios in which S shows a negative eigenvalue, but here are some scenarios:
1. 333 supercell and larger (smaller ones are OK)
2. Also shows in diamond
3. GTH-DZVP, but not GTH-SZV

While I'm not sure if the error in the calculation of S is as intended or something more difficult to track down, I would suggest that a check on the positive-definiteness of S be implemented prior to the initialization of any DF tensors, as I was notified of this error only after pyscf spent a day building a GDF tensor!

@verena-neufeld and @hongzhouye helped in this investigation, thanks!

**Comment by hongzhouye** [comment]
Adding to what Bryan said, `lib.cond`, which is currently used by the SCF module to check the condition number for the AO overlap matrix ([this line](https://github.com/pyscf/pyscf/blob/master/pyscf/scf/hf.py#L135)), cannot detect negative eigenvalues. It calculates the cond number roughly as `abs(ev).max() / abs(ev).min()` afaict where `ev` is the array of eigenvalues of the AO overlap matrix.

**Comment by fishjojo** [comment]
You need to make sure that all atoms are within the cell, i.e., the cell defined by cell.a.

**Comment by susilehtola** [comment]
> You need to make sure that all atoms are within the cell, i.e., the cell defined by cell.a.

Should this not be checked by the initialization routine...?

**Comment by tberkel** [comment]
I agree this should be checked on startup and the atoms could be
translated into the unit cell (not sure if this would mess up any user's
effort to do visualization after the fact).

**Comment by sanshar** [comment]
Does the translation of atoms into the unit cell actually make a difference
from the computational point of view? The actual origin of the unit cell is
never used (or I don't see why it should ever appear). The lattice vectors,
as far as I know, are only used to generate lattice translations, never to
assign a basis function or atom to a particular unit cell.

Sandeep.

**Comment by fishjojo** [comment]
`cell.get_lattice_Ls` will be affected depending on whether the atoms are inside the unit cell or not.

**Comment by sunqm** [comment]
Bug fixed in PR 1044
