### ISSUE TITLE
Document ordering of GTOs

### ISSUE THREAD

**Issue by antoine-levitt** [pyscf/pyscf#1023]
Hi, and very nice project!

I'm struggling a bit interfacing with an external tool because I need to know the order in which the GTOs are constructed from the basis. Eg will a p gaussian give (m=-1, m=0, m=1), or (px, py, pz), or some other ordering? I was not able to find this in the documentation or reverse engineer it from the matrices. Apologies if I missed somewhere obvious.

**Comment by hebrewsnabla** [comment]
Just print `mol.ao_labels()`, the order is very clear.

**Comment by antoine-levitt** [comment]
Thanks! I actually got around to it through https://github.com/sunqm/libcint/blob/master/doc/program_ref.pdf, which appears to match.

I had a bit of trouble figuring out the pattern, comparing to https://en.wikipedia.org/wiki/Table_of_spherical_harmonics#Real_spherical_harmonics. Is it right that they match, except for the fact that the l=1 are relabellings of the usual ones? I also had a bit of trouble because of the fact that the m=0 for l>=2 appear to differ, but if I understand correctly this is just convention and what pyscf calls "z^2" is actually "2z^2-x^2-y^2"?

**Comment by shivupa** [comment]
Yeah the libcint manual is helpful. I believe the ordering for l=1 is (1,-1,0) rather than the standard [CCA](https://github.com/evaleev/libint/wiki/using-modern-CPlusPlus-API#solid-harmonic-gaussians-ordering-and-normalization) ordering, which would be (-1,0,1). 

I am not sure the answer to your "z^2" question.

**Comment by antoine-levitt** [comment]
Yes, that's what I see as well for the l=1 case. I believe the z^2 is indeed (very confusing, to me at least) "shorthand" for 2z^2-x^2-y^2: if it was not, then that orbital would have a non-zero overlap with the s, which is not the case.

**Comment by sunqm** [comment]
Except l=1, other spherical GTOs follow the convention of
https://en.wikipedia.org/wiki/Table_of_spherical_harmonics#Real_spherical_harmonics

dz^2 is the orbital of l=2, m=-2. The overlap between d_{-2} and s_0 should be
zero regardless of convention. You may find error of ~1e-18. They are numerical
round off error.

**Comment by antoine-levitt** [comment]
> dz^2 is the orbital of l=2, m=-2

You mean m=0, right? Yes I agree, my confusion was that "dz^2" does not mean z^2/r^2 but rather (2z^2-x^2-y^2)/r^2. I suppose it's "standard", but still confusing.

**Comment by sunqm** [comment]
You are correct. dz^2 is m=0, short for (2z^2-x^2-y^2)/r^2

**Comment by antoine-levitt** [comment]
Thank you, that's very helpful! It could be nice to document this somewhere - I saw a dev docs is planned, that could be a nice place for it. I'm closing this issue.
