### ISSUE TITLE
pbc with multigrid DF benchmark

### ISSUE THREAD

**Issue by pedersor** [pyscf/pyscf#1025]
Hi PySCF team,

I am attempting to run some larger-scale DFT calculations within the pbc/df module. Specifically, I am hoping to reproduce some benchmarks in the 2020 paper (https://aip.scitation.org/doi/pdf/10.1063/5.0006074) Table II. It appears that pyscf/examples/2-benchmark/fock_multigrid.py sets up this benchmark. However, I ran into a few problems/questions:

1) For the nao = 2560 water box, using LDA and 96 threads @ 2.00GHz I get a Fock matrix build time of 100s (see line 546 of attached output) which seems quite off from the paper result (20 sec with 32 threads (?) @ 2.3 GHz). 

2) Attempting to run a full DFT calculation, I run out of memory (tries to allocate a 470gb array! see end of attached file). 

3) In Table II, it is explained that "Integral screening and lattice summation cutoff were controlled by an overall threshold of 10^−6 a.u.". I assume setting `precision = 1e-6` does exactly this? Or do I need to set the integral screening separately?

For reproduceability, I ran the calculation within the latest Docker image (pyscf/pyscf:latest). 

[multigrid_test.txt](https://github.com/pyscf/pyscf/files/6871637/multigrid_test.txt)

**Comment by fishjojo** [comment]
You may try manually compiling pyscf with MKL. Using [qcint](https://pyscf.org/install.html#using-optimized-integral-library) will also speed up the calculation a little bit. 
The memory issue needs a fix though.
Yes, `cell.precision=1e-6` was used for generating the time data in the paper.
[test.txt](https://github.com/pyscf/pyscf/files/6873125/test.txt)

**Comment by pedersor** [comment]
Apologies for the delayed response. Yes, linking with intel MKL I get the reported performance with 
[32 threads](https://github.com/pyscf/pyscf/files/6897907/water_test_32thread.txt). Using my full node (
[96 threads](https://github.com/pyscf/pyscf/files/6897916/water_test_96thread.txt) ) the timings actually get worse which is puzzling to me.

**Comment by jamesETsmith** [comment]
As you go to a larger number of threads sometimes the overhead cost of parallelization can slow things down especially as you get to more than 80 threads. A lot of factors, like the problem size and CPU type, can affect this. If you're interesting in finding the most performant settings on your hardware, I'd suggest trying several different values for the number of threads to find what's best for you.

**Comment by fishjojo** [comment]
@pedersor, we have a temporary fix for the memory issue in [here](https://github.com/fishjojo/pyscf/tree/patch1), but we still need to optimize the performance. Following is the current timings for an LDA calculation with ~20000 basis functions.
[water_cluster_mfft.kernel.txt](https://github.com/pyscf/pyscf/files/6911749/water_cluster_mfft.kernel.txt)

**Comment by pedersor** [comment]
Thanks James and Xing! I'll try out the fix.
