### ISSUE TITLE
feature request: spherical averaged dft

### ISSUE THREAD

**Issue by binghuang2018** [pyscf/pyscf#1028]
Is it possible to run spherically-averaged DFT, much the same as for spherically-averaged HF using the current implementation of PySCF? Or I have to modify the relevant code for HF to suit my purpose?

**Comment by binghuang2018** [comment]
[from Q. Sun's reply by email]

Is it an atomic calculation? pyscf/scf/atom_hf.py can handle spherically
averaged HF calculations. It does not support DFT. Extending this module is not
difficult. You would like pseudo code as below
```
class SphericalDFT(rks.RKS, atom_hf.AtomSphericAverageRHF):
    def __init__(self, mol, *args, **kwargs):
        atom_hf.AtomSphericAverageRHF.__init__(self, mol)
        rks.RKS.__init__(self, mol, *args, **kwargs)

    eig = atom_hf.AtomSphericAverageRHF.eig

    get_occ = atom_hf.AtomSphericAverageRHF.get_occ

    get_grad = atom_hf.AtomSphericAverageRHF.get_grad
```

For molecules, there are some functions to manipulate the occupancy for SCF in
pyscf/scf/addons.py e.g. frac_occ_ allows to assign fractional occupancies for
degenerated orbitals. Some helper functions have examples in examples/scf.

**Comment by susilehtola** [comment]
This would be useful to have in PySCF.
