### ISSUE TITLE
IBOs localization

### ISSUE THREAD

**Issue by DanielBajac** [pyscf/pyscf#1032]
When I localize occupied molecular orbitals with the IBOs procedure, I get good localized orbitals. But when I do the same with virtual MOs, the results are bad, compared to other localization methods (e.g. PM with different charge methods, Boys, E-R) 
There is something I can change in the Pyscf code, or in my program, to improve the IBOs localization in the virtual space? 

###ocuppied
lmo_coeff = lo.ibo.ibo(mol, mf.mo_coeff[:, mf.mo_occ > 0], locmethod='IBO', exponent=2)
 
### virtuals
lmo_coeff = lo.ibo.ibo(mol, mf.mo_coeff[:, mf.mo_occ == 0], locmethod='IBO', exponent=2)

**Comment by susilehtola** [comment]
As far as I recall, the IBO method is fundamentally restricted to only core and valence orbitals.

**Comment by shivupa** [comment]
You might consider using valence virtual orbitals which are [available in pyscf ](https://github.com/pyscf/pyscf/blob/master/pyscf/lo/vvo.py)

**Comment by susilehtola** [comment]
Indeed; the derivation for VVOs follows the construction of IBOs/IAOs, and they're a good choice for choosing active spaces in CASSCF calculations. @DanielBajac what application did you have in mind for the localized virtuals?

**Comment by DanielBajac** [comment]
Thanks for your advices. 
I tried the _livvos_, but I only get 3 virtual localized molecular orbitals, when I need all the localized.

I need localize all the virtual orbitals, because we are studying the entanglemente between MOs excitations. https://aip.scitation.org/doi/full/10.1063/5.0027545 
So, I need localize the occupied and the virtual space. 

I've been getting good results with PM (meta-lowdin, becke, lowdin, mulliken), but I wish to keep trying other localization methods.

**Comment by shivupa** [comment]
Yeah I see the vvo/livvo approach won't give you what you need. It will only give you the "chemically relevant" virtuals.

You can use Pipek-Mezey localization with the virtual orbitals, but this may not be the best solution? After quickly searching I found [this paper which sounded relevant](https://onlinelibrary.wiley.com/doi/abs/10.1002/jcc.23281)
```
from pyscf import gto, scf, lo

mol = gto.Mole()
mol.verbose = 0
#mol.output = 'out_h2o'
mol.atom = '''
O 0 0      0
H 0 -2.757 2.587
H 0  2.757 2.587'''
mol.basis = 'augccpvdz'
mol.symmetry = 0
mol.build()

mf = scf.RHF(mol)
mf.kernel()
print(mf.mo_coeff.shape)

orbitals = mf.mo_coeff
pm = lo.PM(mol, orbitals, mf)
pm.pop_method = 'mulliken'
local_orbs = pm.kernel()
print(local_orbs.shape)
```
This gives the expected shape
```
(41, 41)
(41, 41)
```

**Comment by susilehtola** [comment]
@shivupa however, that paper is based on the Mulliken or Löwdin population analyses, which are mathematically ill-defined as they lack a basis set limit. Our generalized Pipek-Mezey analysis described in [J. Chem. Theory Comput. 2014, 10, 2, 642–649](https://doi.org/10.1021/ct401016x) might do better; it is available in PySCF as the `becke` method. I have been wondering whether our real-space method would yield better localized virtual orbitals for many years.

Note, however, that there is an issue in orbital localization methods in PySCF based on the CIAH algorithm: the localization does not always converge to a minimum; instead, saddle point convergence has been observed in many cases (#820). This may also affect your results.

**Comment by DanielBajac** [comment]
@shivupa It is important to localize the occupied and virtual space separately. Because only the separated spaces are invariant under unitary transformations. 

@susilehtola I read several times that article, it was very helpful.

There is some Pyscf-function to know if a localization calculation converge to a saddle point or a minumum point?

**Comment by sunqm** [comment]
> @shivupa It is important to localize the occupied and virtual space separately. Because only the separated spaces are invariant under unitary transformations.
> 
> @susilehtola I read several times that article, it was very helpful.
> 
> There is some Pyscf-function to know if a localization calculation converge to a saddle point or a minumum point?

The localization algorithm in pyscf is basically Newton algorithm. It can always converge to the minimum point although no guarantee for global minimum.
