### ISSUE TITLE
Transition state search with quadratic steepest descent method

### ISSUE THREAD

**Issue by pablomazo** [pyscf/pyscf#1035]
I have an implementation of a quadratic steepest descent search of transitions states based on J. Chem. Phys., 101, 2157, 1994; 10.1063/1.467721.
I would be very happy to contribute to PySCF with this code. I have it working and ready for PR.

According to the guidelines in https://pyscf.org/contributing.html I'll PR it when a repo https://github.com/pyscf/qsdopt is created, where we'll be able to discuss the required changes to become part of PySCF.

**Comment by sunqm** [comment]
Repo https://github.com/pyscf/qsdopt is created

**Comment by pablomazo** [comment]
I made a PR in that repo.

**Comment by pablomazo** [comment]
Would it be interesting to write an interface so that optimizations are executed in the same way as PyBerny and geomeTRIC?

And, should I also write in the manual the usage of qsdopt?

**Comment by sunqm** [comment]
@pablomazo Can we mark this issue solved?

**Comment by pablomazo** [comment]
Sure, it is indeed solved.
