### ISSUE TITLE
symmetry of 2rdm

### ISSUE THREAD

**Issue by binghuang2018** [pyscf/pyscf#1037]
Hi, pyscf users/developers,

It seems that CISD 2rdm (denoted as `D` hereafter) satisfies only `numpy.all(D == D.transpose([2,3,0,1]))`, while the assumed permutational symmetry due to anticommulation relations between the creation/annihilation operators, i.e., `D[p,q,r,s] = <0|p^\dagger r^\dagger s q|0> = D_{pqrs} = -D_{rqps} = -D_{psrq} = D_{rspq}`, seems to be missing. Could someone explain this to me?

**Comment by sunqm** [comment]
Is the density matrix in your test the spin-traced density matrix or the full density matrix based on spin orbitals?

**Comment by binghuang2018** [comment]
@sunqm It's the spin-traced rdm2. If the permutational symmetries exist for the full rdm2 based on spin orbitals, why the spin-traced one, i.e., as summation of the 4 components: d_{pa,qa,ra,sa}, {pb,qb,rb,sb}, {pa,qa,rb,sb}, {pb,qb,ra,sa} (a: alpha, b: beta), loses part of the symmetries?

**Comment by sunqm** [comment]
spin-traced density matrix is the integrals of e operator, `dm[p,q,r,s] = <|e_prqs|> = <|E_{pq} E_{rs} - \delta_{rq} E_{ps}|>` and `E_{pq} = p_a^\dagger q_a + p_b^\dagger q_b` . The e operator may have different permutation symmetry
