### ISSUE TITLE
Is the garbage collection sweep in Mole.build() really necessary?

### ISSUE THREAD

**Issue by glowthrower** [pyscf/pyscf#1038]
When profiling some code I've written that uses pyscf, I've noticed that a massive and disproportionate chunk of time is spent in [pyscf.gto.Mole.build()](https://github.com/pyscf/pyscf/blob/ff52062a88e90bbb6a909eaf80856364f68b2d67/pyscf/gto/mole.py#L2274). The particular culprit is the call to `gc.collect()` that occurs as the first line in this function.

I assume that there was some kind of a memory leak at some point that caused this line to be added. (A quick look through git suggests that it goes back to 2014 at least.) But is it truly still necessary?

I guess it's unremarkable enough if `build()` is called once inside a one-shot calculation script, but I'm using it repeatedly for thousands of molecules, in the context of a much larger program with many, many other things in memory. The calls to `gc.collect()` are extremely(!) expensive for such a case and can easily run into seconds each.

Just to test, I've disabled the call to `gc.collect()` and rerun my code. The performance difference is huge, and I see no obvious memory leakage, despite ten or twenty thousand calls to `build()`, each for a totally different molecule. My understanding of the Python garbage collection system is far from complete, but I believe (according to my reading of the [documentation](https://docs.python.org/3/library/gc.html)) that `gc.collect()` just triggers the next sweep of the GC, which would have happened at some point anyway. In other words, I don't think it does anything that wouldn't be done automatically, it just does it sooner. Even if there are circular references somewhere caused by dynamically renaming methods (which appears to have been the original reason for this being added), is there a real case where such (temporary) memory leakage is really so bad that these calls are necessary to keep it under control?

**Comment by sunqm** [comment]
Circular reference exists in a few pieces of code. For example the code in scf/addons.py https://github.com/pyscf/pyscf/blob/master/pyscf/scf/addons.py#L264 , mf object cannot be automatically released by gc. mf object caches the 2-electron integrals. It consumes a large mount of memory.  I can add a flag in __config__ to control whether to call gc.collect

**Comment by glowthrower** [comment]
Thanks for the quick reply and for the example! You're right, of course, that there's a circular reference being built there (`mf.__dict__` references `get_occ`, and `get_occ.__closure__` references `mf`). Is there another one in that function that I've missed?

If I understand this properly, your concern is then that when `mf` drops out of scope somewhere in calling code, that it won't be automatically collected due to that circular reference. And indeed, it won't be collected in the "standard" way, i.e. due to a reference count going to zero. But to my understanding, the Python GC is completely capable of resolving this without any manual intervention -- the `gc.collect()` call simply forces that to happen "right now", rather than "at some point in the future when the GC threshold is exceeded". I can certainly see cases where this would be necessary (such as the one you mentioned, with a massive cache of integrals which really need to be cleaned up immediately), but I wonder if there might not be a better/cleaner solution...

Perhaps a case like this is a candidate for the use of [weak references](https://docs.python.org/3/library/weakref.html)? It's late here and I'm tired, but I think that if you put something like `weak_mf = weakref.ref(mf)` at line 281, and referred to that throughout the closure rather than `mf`, that the circular reference would go away and standard reference counting would cause `mf` to be reaped whenever it dropped out of scope. Then there would be no need for GC, either automatic or manual, and a performance gain and more predictable memory usage as well. But perhaps this doesn't work in all the cases throughout the code.

Even if a call to `gc.collect` were necessary, though, I'm not clear why it should be in `Mole.build()` specifically. Any further call to `mf.build()` after your example wouldn't result in that reference being collected -- because `mf` would by definition still be in scope in order for `build` to be called. The only way I see this being useful would be the case when multiple `Mole` instances were being constructed and built, one after the other in sequence, when each call to `.build()` would be effectively "cleaning up" the previous. Is that right?

Finally, although I really appreciate the offer of a fix(!), if the weakref approach doesn't work for whatever reason, I feel like it would be simpler to just add a default parameter to `Mole.build()` directly. Perhaps something like `do_gc=True`? If the default value was consistent with the existing behaviour, I don't think that would break existing code...? 

(Just as a comment, I don't use the config file functionality at all. I use PySCF (and libcint) as just one of many libraries, rather than as a standalone tool. So it's not really possible for me to manage/deploy a config file for PySCF specifically, any more than it would be possible to do the same for a config file for numpy, scipy, etc. I guess my use case is not the "standard" one, but the fact that I can do exactly this -- have tens of thousands of molecules and calculations existing simultaneously as pure Python objects, without having to conform to the standard run-oriented model in most QC codes -- is the main reason why PySCF is so useful! :) But it's also why I'm so concerned about this, since the cost of those calls to `gc.collect` is directly proportional to the amount of objects in memory *across the whole of my system*, which breaks the neat abstraction...)

**Comment by sunqm** [comment]
Technically, rewriting scf/addons.py to remove circular reference of mf object is not difficult. mf is the most commonly referred object in practice. It's easily to implement a code that self-refers mf object in a complicated  reference chain. Then it becomes a problem to automatically release the integral cache in mf object. gc.collect will be needed called either explicitly in users code or somewhere int pyscf library. For reasons I don't remember, I decided to call it in mol.build method than mf.build method or other methods. I don't know gc.collect would be so expensive in extreme cases.

I tend to keep the explicit call to gc.collect by default in the code. There are many implementations on top of pyscf without careful consideration of memory leaks. Calling gc.collect in mol.build may not be a perfect solution but at lease reduce the possibility of memory issue. 

The settings of `__config__` will be exported to a global variable in the pyscf.gto.mole module. So as a temporary solution, disabling gc right after import pyscf.gto module should be able to mute the gc.collect call globally. Hope it can solve the problem in your calculation for the moment.

**Comment by glowthrower** [comment]
In general, though, what patterns are leading to these reference chains? Are they all similar to the example given -- dynamic method patching -- or are there more complicated patterns somewhere as well? If the latter, would you mind giving another example?

If the former, then why not just patch in dynamically bound instance methods directly and avoid the reference cycle problem completely? It's not, I think, very well documented, but you can do this using `types.MethodType`. It's far cleaner than my earlier suggestion using weakrefs. It also works with closures:

```python
import types

class Thing:
    def __init__(self, x: float):
        self.x = x

    def do_something(self, y: float):
        return self.x + y

def patch_method(t: Thing, foo: float):
    z = foo
    def closure(self, y):
        return self.x + y + z
    t.do_something = types.MethodType(closure, t)

t = Thing(10)
print(t.do_something(5))  # Prints "15"

patch_method(t, 2)
print(t.do_something(5))  # Prints "17"
```

To be clear, I know that it's fairly easy to introduce circular references, but it's also usually possible to avoid them. If there is a different pattern in the solver hierarchy that really really needs them, I'd be interested to see it, just out of curiosity! Because at the end of the day, peppering the code with speculative calls to `gc.collect()` feels to me like an anti-pattern... :smile:

> The settings of __config__ will be exported to a global variable in the pyscf.gto.mole module. So as a temporary solution, disabling gc right after import pyscf.gto module should be able to mute the gc.collect call globally. Hope it can solve the problem in your calculation for the moment.

Perhaps I misunderstand you, but if you're suggesting that I disable GC throughout the whole of my working environment, that's a non-starter, unfortunately. I can't make any assumptions about other libraries which may rely on the GC working properly... 

If you mean adding some extra lines after each call to `import pyscf`, that's also a bit gnarly, since I do that in many source files and it's difficult to predict or enforce which will get hit first. 

Currently, I've just commented out the `gc.collect()` calls completely wherever I've found them. That's a completely fine solution for me in the short term, especially if gradually removing the problematic code with circular references is something that you guys were to put on your list of "Stuff to fix when there's time." :smile: (I'd happily help with this myself, but I'm not in a position to do that for a couple of months...)

**Comment by glowthrower** [comment]
Also, just as an example of at least one `gc.collect()` that can surely be avoided... In [sacasscf.py](https://github.com/pyscf/pyscf/blob/1de8c145abb3e1a7392df9118e8062e6fe6bde00/pyscf/grad/sacasscf.py#L172), there are two calls to `gc.collect()` inside a tight loop over blocks of basis functions. 

I guess the first call is speculative, to make sure that any old `mf` instances are tidied up, but that could surely be done just once before the start of the loop, and then removed completely once/if the underlying problem is fixed.

The second call can only be intended (again, unless I fundamentally misunderstand something) to clean up `eri1` and `dm2_ao` after they've been nulled out. Since they're both ndarrays, I think ref-counting will do that automatically, but if you wanted to be really sure about it, you could explicitly do
```python
del eri1
del dm2_ao
eri1 = dm2_ao = None
...
```
and avoid the second call to `gc.collect()` completely.

**Comment by sunqm** [comment]
Your proposed solutions are definitely good methods to solve circular reference problem. Actually, some addons were refactored to an implementation free of circular reference. It's not a technical problem to remove circular reference objects in pyscf and it's also my plan to refactor these implementations in the future.

The call to `gc.collect()` is slightly different. There are many places holding expensive resources, e.g. mf._eri array. When developing new models, it's common to get circular referenced objects and observe large memory overhead. How to allow users trying ideas without worrying about recycling these resource-greedy resources? Calling `gc.collect()` seems the simplest one, if the relevant objects were not used but still alive. Given these considerations, the question becomes where to trigger the call of gc.collect and how to turning on/off it. I considered to call it in Mole.build, in SCF.build and other places before. I finally chose Mole.build because I guess regular calculations would not need to construct new Mole object many times and it can be distinguished to the scenario of method development.

As a temp solution in your case, is it possible in your code to add an interface layer to import pyscf, in which you can put all configures and modules? Then you can use the code `from local_pyscf import xxx` to replace `from pyscf import xxx` whenever you need to use pyscf  modules.

**Comment by verena-neufeld** [comment]
Hi @glowthrower , has this been resolved?

**Comment by sunqm** [comment]
`gc.collect` has been removed since pyscf-2.4
