### ISSUE TITLE
Localized molecular orbitals energy

### ISSUE THREAD

**Issue by DanielBajac** [pyscf/pyscf#1049]
Hi all, 

There is a way to obtain the energy of each molecular orbitals after locating it with some method, like Pipek Mezey, Foster Boys or Edminston Ruedemberg ?   

Best regards,

Daniel

**Comment by tberkel** [comment]
Because localized molecular orbitals do not diagonalize the Fock/KS matrix,
they cannot be assigned an energy.

**Comment by DanielBajac** [comment]
Ok. Thank you!
