### ISSUE TITLE
Excitation energy by ADC(2)

### ISSUE THREAD

**Issue by proexcuse** [pyscf/pyscf#1056]
Hi,

I'd like to compute excitation energy by ADC(2). 
But can't find out how to do it. (Only found about IP or EA ADC)
Could anyone tell me how? Just a simple example will do.

**Comment by mfherbst** [comment]
You can use pyscf in combination with the adcc package, see https://adc-connect.org and https://adc-connect.org/v0.15.7/calculations.html for example usage of adcc in combination with pyscf.

**Comment by proexcuse** [comment]
Thanks for your help and great package.
