### ISSUE TITLE
lib.logger module overwrites time.time and time.clock

### ISSUE THREAD

**Issue by adamgoldfeld** [pyscf/pyscf#1057]
In pscf version 1.7.6,  pyscf.lib.logger line 82-85
`
if sys.version_info >= (3,6):
    time.clock = time.process_time
    if sys.version_info >= (3,8):
        time.time = time.perf_counter
`

Notice, the logger module is imported whenever you import pyscf.
This changes the base functionality of the python time module and interferes with other packages which rely on time module and functionality which is not good... 
A simple solution is to create a local module named time which alias functions from python time.

**Comment by fishjojo** [comment]
This has been fixed in pyscf v2.0, and there will be a release soon.
