### ISSUE TITLE
kpt DF integral generation creating huge tempfiles

### ISSUE THREAD

**Issue by Simonsays095** [pyscf/pyscf#1058]
I just recently started doing band structure calculations using PySCF's KKS class, but I'm getting very large tempfiles (larger than 800 gb!). For this specific example, I'm doing a calculation on NiTTFtt (Nickel tetrathiafulvalene), which I read using an extension I made to read .cif-formatted files (which I can't share, unfortunately - maybe this could be a feature request? But that's beside the point). I have included the .cif file if that helps.

As far as I understand, because I'm doing a calculation which only has 1 periodic dimension (it's a chain), I have to use density fitting - this is required for any non-3D PBC calculations. However, using DF generates massive temp and _cderi files. How do you suggest I go about doing these calculations, since this file size seems to be far larger than necessary for this type of calculation?

I saw the notes in pyscf/pbc/df/df.py about the 3-integral files being large, but there's no recommendation for how to get around this issue when they're simply too large, other than dumping DF integral intermediates to a separate temp file - which I don't know how to do, or how that fixes the problem.

Script:
```py
## NiTTFtt.py
import numpy as np
from pyscf.pbc import dft
from local.mol_tools import load_from_cif

kmesh = [9,1,1]

cell = load_from_cif('NiTTFtt_monomer.cif')  # Just loads cell.a, cell.unit, and cell.atom from the .cif file.
cell.basis = '6-31g'
cell.charge = 2 * np.prod(kmesh)
cell.verbose = 6
cell.dimension = 1
cell_lengths = [np.linalg.norm(vec) for vec in cell.a]
cell.mesh = np.asarray([int(np.ceil(8*d)) for d in cell_lengths])
cell.build()

kpts = cell.make_kpts(kmesh)

mf = dft.KKS(cell, kpts=kpts, xc='B3PW91').density_fit()
mf.kernel()

band_lines = cell.make_kpts([50,1,1])
np.save('band_kpts.npy', band_lines)
band_e, band_c = mf.get_bands(band_lines)
np.save('band_energies.npy', band_e)
```

Example files part-way through a calculation (`python NiTTFtt.py > NiTTFtt.out`):
![image](https://user-images.githubusercontent.com/47613665/134418640-78bbe71e-288a-4765-b5ad-f086adbff570.png)

.cif file used in the script (changed to .txt so I could upload it to github):
[NiTTFtt_monomer.txt](https://github.com/pyscf/pyscf/files/7213690/NiTTFtt_monomer.txt)

Thank you very much in advance for any help,
Simon

**Comment by zhcui** [comment]
You may use gdf.build(j_only=True) for DFT calculations to avoid the full build of density fitting integral.

**Comment by Simonsays095** [comment]
Does this setting affect the convergence or accuracy of the calculation, or
is it negligible for most systems?

**Comment by zhcui** [comment]
No. For normal DFT, it is the same as the full integral.

**Comment by Simonsays095** [comment]
I set `mf.with_df._j_only = True` before running the kernel, and sure enough the tempfile sizes went down to ~33gb in my case - still large, but at least manageable. However, the tempfiles grow again to >500gb after kernel, during the following steps, especially `mf.get_bands`. It looks like the `_j_only` argument is getting carried through to this step, but the files are still massive.

For now, I'm going to split up my call to `get_bands` to only get the energy for a few kpts at a time and then concatenate them, but if you have another idea to avoid large files without this extra step, I'd appreciate it.

**Comment by tberkel** [comment]
It sounds like this could be easily fixed in the code. But the benefit of
get_bands is that you don't have to redo the SCF. So, while this fix is not
optimal, you could instead redo the SCF at each kpt needed for your band
structure (by passing a `scaled_center` kwarg to `cell.make_kpts()`) .
Calculating the band structure will be a lot more expensive (in time), but
you will only ever need the tempfiles associated with a single SCF
calculation.

**Comment by Simonsays095** [comment]
I have a few questions about the `get_bands` function, but I submitted a new issue (#1063) to keep this one on-topic.

The really large file is the one generated in `_make_j3c`, which is unlinked at:
https://github.com/pyscf/pyscf/blob/09834c8f5a4f5320cdde29d285b6ccd89b3263e0/pyscf/pbc/df/df.py#L169

The unlinking changes the name to a `.nfs...` file, which stays around until the script closes - is that why you suggest performing an SCF calculation on each k-point rather than letting `get_bands` get the energies for the extra ones? I would like it if, instead of unlinking this large file and letting it stick around until the script closes, it's deleted and discarded at the end of the get_bands function call, since it's no longer needed. As it stands, my DFT calculations take several days to run with just 9 k-points, so I would like to stay away from using more k-points if possible.

**Comment by tberkel** [comment]
Before addressing the large files: are you sure you can use `_j_only = True`? You are using a hybrid functional with nonlocal exchange (B3PW91). @zhcui what do you think?

**Comment by Simonsays095** [comment]
I am indeed using a hybrid functional - I set the `_j_only=True` argument based off of the recommendation by @zhcui to set `gdf.build(j_only=True)`. Since the kernel and get_bands functions call `gdf.build` in them, setting `_j_only=True` seems like the easiest/only way to set the `j_only` argument in these functions without rewriting them.

That being said, it looks like my kernel results using `_j_only=True` are identical to the kernel results without setting this option. I'm not sure yet about the results of `get_bands`, since the script crashes due to lack of memory space before finishing.

**Comment by zhcui** [comment]
Sorry, I did not see that you are using functional with non-local exchange. In that case, j and k are both required (and you can't use j_only=True). Thanks @tberkel for reminding this.

**Comment by Simonsays095** [comment]
Alright, so we're back to square one - is there another way to reduce these file sizes? I could try switching over to a functional that doesn't use nonlocal exchange and set `_j_only=True`, but the file sizes were still very large when actually computing the band structure with `get_bands`. Would it help if I were to use a different basis more suited for PBC calculations, or use an ECP or pseudopotential? I'm not very familiar with either of those in practice, but I could learn if it helps reduce the file sizes to something more manageable.

**Comment by fishjojo** [comment]
You may try using the [GTH pseudopotentials](https://github.com/pyscf/pyscf/blob/master/pyscf/pbc/gto/pseudo/gth-pbe.dat) and the corresponding [basis sets](https://github.com/pyscf/pyscf/tree/master/pyscf/pbc/gto/basis) to see if it reduces the size of your problem (number of basis functions). The size of the tmp file increases at the `get_bands` call because the k points for band calculation are not included in the SCF calculation so the program will recompute the integrals for all the needed k points. You may generate the integrals for whatever k points you need and save them on the disk so that you don't need to regenerate them each time, e.g.,
```
from pyscf.pbc imort df, dft
mydf = df.GDF(cell)
mydf.kpts = kpts
mydf.kpts_band = kpts_band
mydf._cderi_to_save="ints.h5"
mydf.build()

mf = dft.KKS(cell).density_fit(with_df=mydf)
mf.kernel()
mf.get_bands(kpts_band)
```
In the future, I think we could add the option to compute these integrals for different k points on-the-fly.

**Comment by sunqm** [comment]
The parameter j_only is automatically assigned for pure DFT functionals. For hybrid functionals, there is no simple way to reduce the size of temporary files. I will close the issue for the moment.
