### ISSUE TITLE
Overlap between two MOs 

### ISSUE THREAD

**Issue by DanielBajac** [pyscf/pyscf#1059]
Hello Pyscf Community,

I want to calculate the overlap between two specific localized molecular orbitals, but have not found the way. How can I do this?

I've tried with `pyscf.tools.mo_mapping.mo_map`  , but I think that only gives me the overlap between the atomic orbital overlap.

**Comment by zhcui** [comment]
You can try C1.T @ S @ C2 for the overlap between two sets of MOs, where S is the AO overlap matrix.

**Comment by tberkel** [comment]
Just to confirm: if they are localized molecular orbitals from a single SCF
calculation, and the localization procedure is just a unitary rotation,
then the localized orbitals will still be orthogonal.

**Comment by DanielBajac** [comment]
I tried the Zhihao recommendation, with H2O2 (the 6-31G** basis) localized molecular orbital with Pipek-Mezey, (Meta-Lowdin) charge from a single SCF calculation. I check visually that the localization are well done.

```
S = mol.intor('int1e_ovlp')
overlap = reduce(np.dot, (mo1.T, overlap, mo2))

```
with `mo1` a O-H ligant, (for example, in my case, the 5th MO), and `mo2` variable in all the possible (38) MOs and the results are:

`
2.949029909160572e-16
-5.4155898515650946e-17
-3.04851850733123e-17
1.218046021672696e-17
1.4953316362920077e-15
**1.0000000000000124**
-1.457167719820518e-15
-1.5439038936193583e-15
1.3877787807814457e-16
5.35682609381638e-15
-4.263256414560601e-14
3.608224830031759e-15
2.020605904817785e-14
4.996003610813204e-16
1.8918894229003058e-14
-2.6978419498391304e-14
1.9872992140790302e-14
8.923417560424696e-15
3.1564831439297214e-17
-1.0408340855860843e-15
2.1611067491963258e-18
-1.1657341758564144e-15
-1.4849232954361469e-15
2.7136888358011714e-18
-2.489096230039346e-17
8.038708587676524e-15
1.1685097334179773e-14
8.326672684688674e-17
-4.27799637909534e-17
0.0
-5.162537064506978e-15
-2.8681512701129188e-18
-2.5779407075662948e-17
-1.0477729794899915e-15
-6.59225046651771e-17
4.996003610813204e-16
9.381384558082573e-15
-4.2327252813834093e-16

`  
note that the overlap of `mo1` is 1, and all the other overlap are very small! I think that this is not allright. 
For example, if a choose a MO in the same region of `mo1`,  and other MO in a different region, both overlaps with `mo1` are in the same magnitude order.

**Comment by tberkel** [comment]
This is for the reason I said. Even before localization, molecular orbitals
are orthogonal to one another (they have zero overlap), even though they
can be in similar regions. Most orbital localization procedures are simply
unitary rotations of the original molecular orbitals, and thus, the
localized molecular orbitals are still orthogonal after localization.

**Comment by DanielBajac** [comment]
Thank you for the clear explanation!
