### ISSUE TITLE
Input issue for Gaussian Basis Sets

### ISSUE THREAD

**Issue by HenryMakowitz** [pyscf/pyscf#1062]
How do I request that a Gaussian basis set such as the Pople  " 6-311++G(2d,2p) "
be used in your DFT module of PyScf  ?? Not clear from the documentation...I  have
been told its an input parameter ??  HM

**Comment by xwang862** [comment]
PySCF can properly parse Pople basis with diffuse and polarization functions. Can you try the following input and check the printed basis set?
```
from pyscf import gto

mol = gto.Mole()
mol.atom = 'H 0 0 0; F 0 0 1.1'  # in Angstrom
mol.basis = '6-311++G(2d,2p)' 
mol.verbose = 5
mol.build()

mf = mol.KS()
mf.xc = 'b3lyp'
mf.kernel()
```

**Comment by fishjojo** [comment]
see [here](https://pyscf.org/user/gto.html#basis-set)
