### ISSUE TITLE
Question: How to transform calcaulted hamiltonian/fock, overlap, MO coeff matrix if input geometry is rotated?

### ISSUE THREAD

**Issue by KirillShmilovich** [pyscf/pyscf#1064]
Say for a particular geometry `r` I have already calculated the Fock matrix `F`, overlap matrix `S`, and molecular orbital coefficients `C`. If I apply a simple rotation matrix `R` to the input geometry `r* = R.dot(r)` is there functionality built into PySCF that would allow me to compute a matrix related to `R` that can be used to transform the original Fock `F*`, overlap `S*`, and molecular orbital coefficient matrix `C*` to be commensurate with newly rotated geometry?

**Comment by sunqm** [comment]
https://github.com/pyscf/pyscf/blob/master/pyscf/symm/basis.py#L151  This function generates rotation matrix for each angular momentum given new axes. You can then transform the integrals with the generated D matrices.

**Comment by KirillShmilovich** [comment]
Got this to work by constructing a block diagonal matrix based on the outputs from `_ao_rotation_matrices` as follows:
```
mats = _ao_rotation_matrices(mol, R)
mat_list = [mats[i] for i in mol._bas[:, 1]]
M = scipy.linalg.block_diag(*mat_list)
```
Then `M` can be used to transform, for example, the Fock matrix if the input geometry is rotated by `R` with: `F' = M.T @ F @ M`

Thanks all!
