### ISSUE TITLE
Question: Spin Orbit Coupling Matrix Elements

### ISSUE THREAD

**Issue by pcalio** [pyscf/pyscf#1066]
Hello, 

I'm interested in computing spin orbit coupling matrix elements using PySCF. Is this doable in PySCF?

**Comment by sunqm** [comment]
There is no black-box functions for SOC. Depending on the methods you are interested, you may need to write some code to compute SOC integrals (like examples/gto/20-soc_ao_integrals.py), the excited states (examples/tddft, examples/mcscf) and their transition density matrices (examples/mcscf/15-transition_dm.py)

**Comment by portega-usal** [comment]
Hello, I'm updating this issue, I have just opened a similar question on spin-orbit coupling matrices, #1483 

Maybe a guide about how to obtain the matrices (for example between a singlet and triplet state calculated with CASSCF) would be really useful for more people. I don't know if a simple black box implementation could be easily achieved either.

Best regards

**Comment by sunqm** [comment]
More discussions can be found in #1483
