### ISSUE TITLE
nuclear-gradients of integrals in AO basis

### ISSUE THREAD

**Issue by jcandane** [pyscf/pyscf#1067]
Hi,

I noticed perhaps a similar issue (#620) however, I did not find a solution.
I have used PSI4 before, but new to PySCF,
I am wondering how one would compute the nuclear gradient of AO integrals (both 1e and 2e). In PSI4, I my compute, say derivative of overlap, dS_ixAB 
("A,B" being AO basis indices, 
"i" being the atomic index, & 
"x" being the Cartesian index rep. {x,y,z}).

In PySCF using: <mol.intor('int1e_ipovlp', comp=3)>, I get something of shape dS_xAB (3, N, N), hence I'm missing the atomic index.
So my question is how do I obtain dS_ixAB in PySCF?

Thanks for your help,
Julio

**Comment by fishjojo** [comment]
`int1e_1povlp` computes <dp/dr|q>, where p and q are two AOs and r is the electron coordinate. To get the nuclear derivatives, you will need to assemble these integral pieces (as you know, <dp/dR|q> = -<dp/dr|q>, where R is the nuclear center of p). [This  piece of code](https://github.com/pyscf/pyscf/blob/09834c8f5a4f5320cdde29d285b6ccd89b3263e0/pyscf/grad/rhf.py#L61-L69) may give you some idea of how to do it.

**Comment by jcandane** [comment]
@fishjojo Thanks very much, I figured it out!

**Comment by jamesETsmith** [comment]
@jcandane, I'm going to close this since your question seems to be answered. If you still have questions, feel free to reopen!

**Comment by HungHsuanLin** [comment]
Hi @jcandane, could you share how you obtain the derivative of overlap? I would like to obtain the same quantity. However, I have a trouble in implementing the code. Many thanks.

**Comment by jcandane** [comment]
Sorry I saw your comment a while ago, then I had something else to do and forgot about the comment. Here is what I did to end up figuring it out myself given a pyscf mol object try:

```
def S_deriv(atom_id, S_xAB, mol):
    shl0, shl1, p0, p1 = (mol.aoslice_by_atom())[atom_id]

    vrinv = np.zeros(S_xAB.shape)
    vrinv[:, p0:p1, :] += S_xAB[:, p0:p1, :]
    
    return vrinv + vrinv.swapaxes(1,2)

S_xAB    = -mol.intor('int1e_ipovlp', comp=3)
dS_pyscf = np.zeros(((len(mol.aoslice_by_atom()),) + S_xAB.shape))
for i in range(len(mol.aoslice_by_atom())):
          dS_pyscf[i] = S_deriv(i, S_xAB, mol)
```

**Comment by HungHsuanLin** [comment]
@jcandane thanks a ton!

**Comment by jcandane** [comment]
Hi @Emieeel , I have a worked out example on my github, https://github.com/jcandane/HF_Gradient/blob/main/PySCF_Gradients.ipynb (or https://github.com/jcandane/HF_Gradient)

**Comment by Emieeel** [comment]
Thank you @jcandane! That is very helpful, exactly what I was looking for. Only for the ERI derivatives, I need to add a minus sign to match them up with psi4.

**Comment by FabioTarocco** [comment]
Hi! I'm trying to figure out how to implement the gradients wrt the nuclear coordinate of the one-body and two-body integrals in the MO basis. Which is the correct way and place to convert gradients defined in the AO into MOs in the working example shown above by @jcandane? (I'm not a quantum chemist so maybe I'm asking something trivial and I just need a basis change before everything)
