### ISSUE TITLE
Contributors for 2.0.0 release

### ISSUE THREAD

**Issue by sunqm** [pyscf/pyscf#1083]
PySCF 2.0.0 has improvements in the features, project layout, code release pipeline, and documentation. In this release, based on the git log history since the release 1.7.0, we found the contributors listed below. If you made contributions to the project after PySCF-1.7.0 (2020-01-01) but didn't find your name in the list, please reply to this post. Please also take a look at the file https://github.com/pyscf/pyscf/blob/master/NOTICE . This file records all contributors to the project. But some contributors are not  included in the file and some affiliations are incorrect. Please reply to this post if you find any changes that should be made in the file.

Abdelrahman Ahmed
Alexander Sokolov
Bryan Lau
Eric Hermes
Garnet Chan
Henrik R. Larsson
Hongzhou Ye
Huanchen Zhai
Hung Pham
James E. T. Smith
Jan Hermann
Janus Juul Eriksen
Kevin Focke
Kevin Gasperich
Lucas K. Wagner
Marc Barbry
Mark Williamson
Matthew Chan
Matthew R. Hermes
Matthew Treinish
Matthias Degroote
Max Nusspickel
Maximilian Scheurer
Muhammad Firmansyah Kasim
Nikolay Bogdanov
Ollie Backhouse
Peter Pinski
Qiming Sun
Samragni Banerjee
Sandeep Sharma
Shiv Upadhyay
Simon Ewing
Susi Lehtola
Terrence Stahl
Tianyu Zhu
Timothy Berkelbach
Verena Neufeld
Xiao Wang
Xing Zhang
Yang Gao
Yixiao Chen
Zhenyu Zhu
Zhihao Cui

Contributors for the documentation https://pyscf.org/user.html :

Alexander Sokolov
Chong Sun
Garnet Chan
Hongzhou Ye
Huanchen Zhai
James E. T. Smith
Jan Hermann
Janus Juul Eriksen
Kyle Bystrom
Ollie Backhouse
Peter Pinski
Qiming Sun
Samragni Banerjee
Sebastian Ehlert
Seunghoon Lee
Susi Lehtola
Tianyu Zhu
Timothy Berkelbach
Verena Neufeld
Xing Zhang
Xubo Wang
Yang Gao
Zhihao Cui

**Comment by susilehtola** [comment]
2.0.0 has been released; should this ticket be closed?
