### ISSUE TITLE
Version 2.0.0 incompatible with Google co-lab pip install

### ISSUE THREAD

**Issue by jdwhitfield** [pyscf/pyscf#1093]
The new update fails to pip install on Google co-lab:

```
...
  Building wheel for pyscf (setup.py) ...   Destination directory: /tmp/pip-wheel-2ntur_3d
  Running command /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pjqr_jb0/pyscf_55ed2d6694074776a124d95f1e592c38/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pjqr_jb0/pyscf_55ed2d6694074776a124d95f1e592c38/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-2ntur_3d
  running bdist_wheel
  running build
  running build_ext
  Configuring extensions
  cmake -S/tmp/pip-install-pjqr_jb0/pyscf_55ed2d6694074776a124d95f1e592c38/pyscf/lib -Bbuild/temp.linux-x86_64-3.7
  CMake Error: The source directory "" does not exist.
  Specify --help for usage, or press the help button on the CMake GUI.
  error: command 'cmake' failed with exit status 1
error
  ERROR: Failed building wheel for pyscf
...
```

The full verbose output is here:
[pip_output.txt](https://github.com/pyscf/pyscf/files/7454633/pip_output.txt)

**Comment by jamesETsmith** [comment]
@jdwhitfield, thanks for bringing this to our attention! When I tinkered around with this it seems that the default `cmake` in the Google Colab (mine was version 3.12.0) doesn't support the `-S` option that's now in PySCF's `setup.py` file, see below:

https://github.com/pyscf/pyscf/blob/304c4eb6cb513c21576c551289cd739b879ee0aa/setup.py#L87

Running `!pip install cmake==3.21.0` before installing `pyscf==2.0.0` fixes your problem, but then leads to another.

```
!pip install cmake==3.21.0
!cmake --version
!pip install pyscf==2.0.0 --verbose
```

Results in:

```
....
    cmake -S/tmp/pip-install-wdcvklqn/pyscf_50629a7bad874efaac804d1a96963c74/pyscf/lib -Bbuild/temp.linux-x86_64-3.7
    CMake Error: The source directory "/tmp/pip-install-wdcvklqn/pyscf_50629a7bad874efaac804d1a96963c74/pyscf/lib" does not appear to contain CMakeLists.txt.
    Specify --help for usage, or press the help button on the CMake GUI.
    error: command 'cmake' failed with exit status 1
    Running setup.py install for pyscf ... error
....
```

Replacing the last line in the commands above with 
```
pip install git+https://github.com/pyscf/pyscf --verbose
```

Makes it farther in the build process but gets killed for some reason I can't figure out right now. I'll keep looking at this and get back to you (hopefully) soon with a full solution.

**Comment by jamesETsmith** [comment]
As a temporary workaround (if you can do without DFT), you can run the following:

```
!pip install cmake==3.21.0
!CMAKE_CONFIGURE_ARGS="-DENABLE_XCFUN=OFF -DENABLE_LIBXC=OFF" pip install git+https://github.com/pyscf/pyscf --verbose
```

The `CMAKE_CONFIGURE_ARGS` flag tells PySCF not to build XCFUN and LIBXC from scratch.

I think the real problem here is that pip is building PySCF from scratch rather installing a wheel. I don't know about the status of the wheels for 2.0.0, but I imagine they should show up on pip in the near future. @sunqm or @fishjojo do you know their status?

**Comment by sunqm** [comment]
The pipeline to build pip wheel was killed by the github actions. PR #1092 was to fix the issue. pip wheels will be uploaded soon

**Comment by jamesETsmith** [comment]
Gotcha, I hadn't looked at that PR closely enough, thanks @sunqm!

**Comment by jamesETsmith** [comment]
@jdwhitfield , the new wheels for 2.0.0 are on pip so you should be good to go! Let us know if you have any more problems

**Comment by sunqm** [comment]
More wheels were built for pyscf v2.1 . Very likely there's no need to compile from source code
