### ISSUE TITLE
Difference between `setup.py` cmake and manual cmake

### ISSUE THREAD

**Issue by BastianZim** [pyscf/pyscf#1098]
Hi,

the `setup.py` file calls CMake and builds the extensions here: https://github.com/pyscf/pyscf/blob/2968e746139aee54dd61f588c96a79aa0f06cca5/setup.py#L141

The docs also list a manual installation using CMake here: https://pyscf.org/install.html#compiling-from-source-code

In which scenario would I use which?

Thanks!

**Comment by sunqm** [comment]
Both compiling method work. setup.py calls the cmake script almost the same way that the manual compilation does. Unless you need to tune cmake configures with the ".inc" file, most likely calling setup.py is enough

**Comment by BastianZim** [comment]
Ok, thanks for the clarification. I will need to supply some CMake flags but I think they're supported through the `CMAKE_CONFIGURE_ARGS` env variable correct?

Is there a special format I need for the variable or just standard format?

**Comment by sunqm** [comment]
For example `CMAKE_CONFIGURE_ARGS="-DBLA_VENDOR=Intel_lp64 -DENABLE_XCFUN=OFF -DWITH_F12=OFF"`
You need to quote the standard cmake flags then assign to CMAKE_CONFIGURE_ARGS

**Comment by BastianZim** [comment]
Awesome, thanks for the help!
