### ISSUE TITLE
Core dumped when executing `rhf_h2o.kernel()`

### ISSUE THREAD

**Issue by Spazierganger** [pyscf/pyscf#1100]
I tried to run the quickstart examples here https://pyscf.org/quickstart.html, 
but when I executed `e_h2o = rhf_h2o.kernel()` my jupyter notebook always had core dumped.
The same happened if I execute things in Ubuntu terminal.

Does anyone know what's wrong with it?

**Comment by sunqm** [comment]
What is `pyscf.__versoin__` ?

**Comment by Spazierganger** [comment]
> What is `pyscf.__versoin__` ?

It's 2.0.0

**Comment by sunqm** [comment]
The pip wheels for 2.0.0 used an old version of openblas library which has a bug. You can run `pip install pyscf==2.0.1`

**Comment by Spazierganger** [comment]
> The pip wheels for 2.0.0 used an old version of openblas library which has a bug. You can run `pip install pyscf==2.0.1`

It indeed helped me, thank you so much!
