### ISSUE TITLE
Temporarily allow MKL/OPENBLAS threading?

### ISSUE THREAD

**Issue by btglau** [pyscf/pyscf#1102]
I noticed this Issue #317 and its associated fix:
https://github.com/pyscf/pyscf/blob/e064645ee08728c64412ed9bc8e7ffe45fc8e1f4/pyscf/__init__.py#L42

Suppresses MKL and OPENBLAS threading for the entire pyscf calculation. With @hongzhouye's RSDF (#1034) speedup over GDF, calls to scipy `solve_triangular` become a bottleneck in the process, e.g. https://github.com/pyscf/pyscf/blob/8a4d973aeab9f7f3adb08cf1d15ba73a05fc7c17/pyscf/pbc/df/df.py#L362 which appears to be single threaded due to the aforementioned setting.

I wonder if there is a way to temporarily allow BLAS/LAPACK multithreading for these calls to `solve_triangular`? They only show in df modules.

**Comment by Majokux** [comment]
As for OpenBLAS, I believe `OPENBLAS_NUM_THREADS` is only used when using posix threads.
For OpenMP-parallelized applications, the [FAQ](https://github.com/xianyi/OpenBLAS/wiki/Faq#how-can-i-use-openblas-in-multi-threaded-applications) recommends building with `USE_OPENMP = 1`.
That should then only inspect `OMP_NUM_THREADS`  and the scipy calls should be parallel according to that environment variable, I think?
OpenMP by default serializes nested parallel regions, so I would hope that calls to OpenBLAS@OMP within an OpenMP parallel region would still be serial.

**Comment by btglau** [comment]
I compile pyscf with MKL, so `MKL_NUM_THREADS=1` will turn off any threading within scipy/numpy (our cluster uses a "flexiblas" system that loads whatever BLAS module into the back of scipy/numpy). Enabling a temporary multithreaded MKL environment would be beneficial for `solve_triangular` within df routines, as those now take up a majority of the SCF calculation (you might see a trend in my comments/pr with trying to handle large systems :^) )

Also, within MKL, pyscf seems to inconsistently use einsum from `numpy` or `lib`, where `numpy` would then be hamstrung by serialized MKL but `lib` benefits from OMP, although I wouldn't be surprised if Qiming carefully considered the pros and cons of their use for each contraction.

**Comment by Majokux** [comment]
I don't use MKL, but I believe it also uses OMP for multithreading?
What happens if you export `MKL_NUM_THREADS = <ncore>` before importing PySCF, do you run into
a "nested  threads" issue as mentioned in #317 ?

**Comment by btglau** [comment]
Thanks for the information, it does look like MKL uses OMP, but pyscf's philosophy is to turn off MKL multithreading as MKL is called in a multithreaded context in pyscf. I will do some tests soon - I still think a neater hypothetical way is to enable scipy/numpy threading within a specific context. MKL threading is also turned off in quantum espresso by default (although that is to avoid clashing with MPI, as I understand)

**Comment by jamesETsmith** [comment]
@btglau I'm 99% sure `scipy.linalg.solve_triangular` should not be parallelized across threads. That function calls the LAPACK function `trtrs`, see the SciPy source here: https://github.com/scipy/scipy/blob/47bb6febaa10658c72962b9615d5d5aa2513fa3a/scipy/linalg/basic.py#L349.

The MKL [docs](https://www.intel.com/content/www/us/en/develop/documentation/onemkl-linux-developer-guide/top/managing-performance-and-memory/improving-performance-with-threading/openmp-threaded-functions-and-problems.html) don't list `trtrs` as a function that's parallelized with threads. I've tried out using `scipy.linalg.solve_triangular` on it's own (with MKL and several OpenBLAS versions as the SciPy backend) and none show threading dependence while other methods like `scipy.linalg.solve` do (see the mini-benchmark [here](https://github.com/jamesETsmith/pyscf_benchmark/tree/main/solve_triangular)).

**Comment by fishjojo** [comment]
You may try the [threadpoolctl](https://github.com/joblib/threadpoolctl) package, which allows to set BLAS threading dynamically.
