### ISSUE TITLE
Test fails due to not provided implementation of kxc in Slater exchange

### ISSUE THREAD

**Issue by BastianZim** [pyscf/pyscf#1103]
Hi, I'm currently in the process of bringing pyscf to [conda-forge](https://conda-forge.org) and get the following error when running the tests:

```zsh
test_lda (test_libxc.KnownValues) ... Functional 'Slater exchange' does not provide an implementation of kxc
```

My question here is:
1. Is it appropriate to run the tests under _.github/workflows/run_tests.sh_ or is there a better approach? I just want to make sure that everything works so also happy to only run a subset.
2. If yes, what could explain the failure above?

PR (Still WIP because there is a OSX failure that I haven't been able to fix yet): https://github.com/conda-forge/staged-recipes/pull/16742
Logs: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=408661&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=4957

**Comment by susilehtola** [comment]
which libxc are you using? The problem appears to be that the tests are trying to access third derivatives but they have not been compiled into the version of libxc you're using.

**Comment by BastianZim** [comment]
I'm using version 5.1.7 as specified here: https://github.com/pyscf/pyscf/blob/679be14c4bd2ce47688fb17ce19c807329c515c4/pyscf/lib/CMakeLists.txt#L184

The libxc is from conda-forge which is compiled here: https://github.com/conda-forge/libxc-feedstock/blob/master/recipe/build.sh

**Comment by susilehtola** [comment]
> The libxc is from conda-forge which is compiled here: https://github.com/conda-forge/libxc-feedstock/blob/master/recipe/build.sh

Yeah, that recipe is insufficient for pyscf and needs to add `-DDISABLE_KXC=OFF` to the cmake command to enable compilation of third derivatives.

**Comment by BastianZim** [comment]
Ok, will open an issue there. Thanks for your help!

**Comment by susilehtola** [comment]
> Ok, will open an issue there. Thanks for your help!

My general recommendation is that general distributions also enable fourth derivatives with `-DDISABLE_LXC=OFF`. The compile time may be several hours but then the library is full-fledged.

**Comment by BastianZim** [comment]
Ok will also add that to the issue. The conda-forge CI has a timeout of 6h so we'll have to check if it stays below that but otherwise it should be possible to add that.

**Comment by BastianZim** [comment]
Will close the issue for now, thanks for your help!
