### ISSUE TITLE
References about CASSCF

### ISSUE THREAD

**Issue by martinanibbi** [pyscf/pyscf#1104]
Hello everyone, I have a really basic question about CASSCF.
Within my thesis project I have to build a home-made version of the Orbital Relaxation algorithm (starting from Head-Gordon and Pople's equations) and until now I have been comparing my code's results with the CASSCF's ones from the pySCF library.
The first tests went well with small active spaces and basis, but by increasing the size of the problems I am now getting some significant differences from the two programs' results and I would like to find out what's different between my technique and the pySCF's one.
Is there any reference that explains in details how you built your CASSCF algorithm? 

I also struggle to find the correct location of the CASSCF class here on github, as I expected to see it in the mcscf folder but I can only find CASCI and second-order CASSCF. 

For the sake of clarity, I would need information such as:
- What kind of optimization do you do during the macro optimization? Is it gradient based (or even Hessian based)? 
- How did you deal with the rdms' sparsity and symmetries?  
and so on.

Thank you very much in advance, and I apologize if this is not the right place for such a question.

**Comment by zhcui** [comment]
You may find the reference here:
https://www.sciencedirect.com/science/article/pii/S0009261417302166

the CASSCF module is called mc1step and mc2step.

The algorithm is gradient and hessian based (using the augmented hessian method).

No symmetry / sparsity is considered.

**Comment by martinanibbi** [comment]
Thank you very much @zhcui!
