### ISSUE TITLE
Confusion about SA-CASSCF optimization

### ISSUE THREAD

**Issue by FreemanTheMaverick** [pyscf/pyscf#1106]
Hi
When reading the example of `pyscf/examples/geomopt/12-mcscf_excited_states.py`, I wondered what object is SA-CASSCF optimization for. 

`# 2. Geometry optimization over an averaged state.`
`# Note the state-averaged gradients are optimized.`
`#`
`mc = mcscf.CASCI(mf, 4,4)`
`mc.state_average_([0.25, 0.25, 0.25, 0.25])`
`excited_grad = mc.nuc_grad_method().as_scanner()`
`mol1 = excited_grad.optimizer().kernel()`

`mc = mcscf.CASSCF(mf, 4,4)`
`mc.state_average_([0.25, 0.25, 0.25, 0.25])`
`excited_grad = mc.nuc_grad_method().as_scanner()`
`mol1 = excited_grad.optimizer().kernel()`

For the code above, when the optimization converges, what will the resulted geometry mean? Will it mean 1) a point where the average energy of the four states reaches a minimum or 2) a point where the energy of the fourth state reaches a minimum?

**Comment by xubwa** [comment]
The average energy of the four states reaches a minimum.

**Comment by MatthewRHermes** [comment]
Note that, by contrast, the last two examples in that file describe geometry optimizations which minimize the energy of individual states within a SA-CASSCF model space.
