### ISSUE TITLE
Installation problem with conda

### ISSUE THREAD

**Issue by ppinski-hqs** [pyscf/pyscf#1115]
I installed pyscf via conda from the pyscf channel.

While the installation procedure worked out without reporting any errors, I was not able to import pyscf. The reason appears to be that pyscf is installed under `lib/python3.7/site-packages`, even if the python version is actually different.

Downgrading my python version in that environment from 3.10 to 3.7 fixed the problem.

**Comment by jamesETsmith** [comment]
@pinskip, can you give us a few more details about your system? It's tough to diagnose the problem now, but if I had to guess this seems like an anaconda problem.  This might be happening if you created an anaconda environment, installed PySCF in the conda base environment, and then loaded the conda environment with python 3.10.

**Comment by fishjojo** [comment]
We only released pyscf on conda for python 3.7. You can use pip to install pyscf for other python versions.

**Comment by mloutis** [comment]
PySCF can't be launched in anaconda navigator windows version because of linux dependencies for quantum calculations.
However, if you install it with pip in ubuntu you will see that the installation will go through without problem.

**Comment by sunqm** [comment]
pyscf-2.2 was released for python 3.6 - python 3.11 . There is one thing to note: conda has multiple versions of mkl. The pyscf-2.2 conda releases were built on top of mkl-2. That requires to install mkl-2023 first before installing pyscf
```
conda install mkl>=2023
conda install -c pyscf pyscf
```
