### ISSUE TITLE
User defined functionals

### ISSUE THREAD

**Issue by pwborthwick** [pyscf/pyscf#1116]
There is a function _libxc.define_xc__ which according to the documentation allows the user to define his own custom functional [pyscf documentation](https://pyscf.org/user/dft.html). I wanted to check on the definitions of some functionals by using this routine to simulate the _libxc (xcfun)_ values. Choosing the simplest model H<sub>2</sub>O with STO-3G basis, default grid and SLATER, VWN3 functional. Running the following code
```
h2o = gto.Mole()
    h2o.verbose = 3
    h2o.output = None
    h2o.atom = [
        ['O' , (0. , 0.     , 0.)],
        ['H' , (0. , -0.757 , 0.587)],
        ['H' , (0. , 0.757  , 0.587)] ]
    h2o.basis = 'sto-3g'
    h2o.build()
  
    from pyscf.dft import rks

    #user defined functional  
    def eval_xc(xc_code, rho, spin=0, relativity=0, deriv=0, verbose=3):

        rho[rho == 0] = 1e-200

        #slater exchange
        alpha =  2/3
        Cx = -(9/8)*alpha*pow(3/np.pi,1/3)
        ex = Cx*pow(rho,1/3)
        vx = 4*ex/3

        #vwn 3
        A= 0.0310907 ; x0=-0.409286 ; b= 13.0720 ; c = 42.7198
        rs = pow( 3.0 / ( 4.0 * np.pi * rho ) , 1.0/3.0 )
        zeta = 0.0
        x = np.sqrt(rs)
        X = lambda y: y*y + b*y + c
        Q = np.sqrt(4*c - b*b)

        ec = A * ( np.log( pow(x,2.0) / X(x) ) + 2.0 * b * np.arctan( Q/(2.0*x + b) ) * pow(Q,-1.0) -\
                  b * x0 * ( np.log( pow(x-x0,2.0) / X(x) ) + 2.0 * (b + 2.0 * x0) * np.arctan( Q/(2.0*x + b) ) * \
                  pow(Q,-1.0) ) * pow(X(x0),-1.0) ) 
        
        vc = ec - (A/3) * (c * (x-x0) - b*x*x0)/((x-x0)*(x*x + b*x + c))

        fxc = None
        kxc = None

        return ex+ec, vx+vc, fxc, kxc

    mf = dft.RKS(h2o)
    mf.init_guess = '1e'
 
    mf.grids = dft.Grids(h2o)
    mf.grids.level = 3
    mf.grids.build()
    from pyscf.dft import libxc
    libxc.define_xc_(mf._numint, eval_xc, xctype='LDA')
    e = mf.kernel()
    print('user definition ',e)

    mf = dft.RKS(h2o)
    mf.grids.build()
    mf.xc = 'LDA,VWN3'
    e = mf.kernel()
    print('libxc definition ',e)
```
This gives the following results:
user definition  -74.85426740764039
libxc definition  -74.92835585398142
I can see by trying LDA,   and  ,VWN3 seperately that neither components agree with libxc. I have checked as much as possible that my definitions of the functionals are correct but it's difficult to see from libxc code how they are defined and there's no documentation only references to the original papers. The following has definitions of the functionals [here](https://faculty.fiu.edu/~mebela/chm5586_dft.pdf). 
  So either
[1] I've misunderstood the operation or use of _libxc.define_xc__.
[2] There's a bug in my code (I have checked several times so not to waste anyones time).
[3] The formulae I've programmed are wrong. Again I've checked with several sources but the libraries themselves are black-boxes to all intents and purposes.

I'd love to resolve this and if someone could help I'd be really grateful. It might also provide a more meaningful example of __libxc.define_xc___ which is useful to provide checks on what is being provided for a given functional.

**Comment by fishjojo** [comment]
`vxc` is a tuple which has the form as explained [here](https://github.com/pyscf/pyscf/blob/dbd34ad7f2306658077df23eea53d36144f9469b/pyscf/dft/libxc.py#L1399-L1405).
So your `eval_xc` function should return something like:
```
exc = ex + ec
vxc = vx + vc
return exc, (vxc, None, None, None), fxc, kxc
```

**Comment by susilehtola** [comment]
With the original code I get
```
converged SCF energy = -74.8542674076465
user definition  -74.85426740764652
converged SCF energy = -74.9283558539815
libxc definition  -74.92835585398147
```
with @fishjojo's change
```
converged SCF energy = -74.9283558539818
user definition  -74.9283558539818
converged SCF energy = -74.9283558539815
libxc definition  -74.92835585398149
```

**Comment by pwborthwick** [comment]
Thank you @fishjojo and @susilehtola . I'm sorry to have wasted your time I should have seen that. All good now, thanks again.
