### ISSUE TITLE
Divergence caused by density fit and cartesian basis in PBC

### ISSUE THREAD

**Issue by ley61** [pyscf/pyscf#1117]
Dear contributors,
For some reason, I need to use Cartesian gaussian basis for rock salt LiH crystal. Below are my code (pyscf==2.0.1)
```python
L = 4
cell = gto.Cell()
cell.atom = f'Li 0 0 0; H {L/2} {L/2} {L/2}'
cell.a = (np.ones([3, 3]) - np.eye(3)) * L / 2
cell.unit = 'A'
cell.exp_to_discard = 0.1
cell.cart = True
cell.verbose=4
cell.basis='sto3g'
cell.build()

kmf = scf.KRHF(cell, kpts=cell.make_kpts([1,1,1]), exxdiv='ewald').density_fit()
kmf.kernel()
```
The energy will diverge if I use the default density fit. And the result will be cured if mix_density_fit() is used but efficiency is also slowed down(spherical basis also helps, but I need to use cartesian). 
I'm curious about the reason for the divergence and how to fix it using the density_fit option, thanks.

**Comment by sunqm** [comment]
Fixed by PR #1142
