### ISSUE TITLE
Please rename aux.py

### ISSUE THREAD

**Issue by cvjjm** [pyscf/pyscf#1119]
Unfortunately Microsoft OneDrive has [completely absurd restrictions](https://www.minitool.com/news/onedrive-name-or-type-isnt-allowed.html) on file/folder names. In particular it does not allow files containing the character sequence "aux." in their filename.

PySCF contains one file that conflicts with this restriction, namely the file `pyscf/agf2/aux.py`.

This leads to the situation that when someone clones/copies the pyscf source to some folder on their PC that is synced with OneDrive. The sync completely stop.

Now, I agree that this should be considered a bug in OneDrive and be fixed there, but this is unfortunately incredibly unlikely. 

So I please as the PySCF developers to slightly change the name of `pyscf/agf2/aux.py`, to maybe to `pyscf/agf2/aux_space.py`.

**Comment by obackhouse** [comment]
Pretty awesome bug, submitted a PR to address this (#1120).

**Comment by TNTworks** [comment]
> Now, I agree that this should be considered a bug in OneDrive and be fixed there

No, this is not a bug, but a feature. This is a well-known limitation of NTFS. AUX is forbidden filename with any extension.

**Comment by bruceburge** [comment]
Here is the list of documented restriction on file and folder names on windows, specifically related to the reserved names. 
_**Do not use the following reserved names for the name of a file:

CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt is not recommended.**_

[Source](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN)

**Comment by harryvederci** [comment]
Maybe send a patch to the OneDrive repo? Oh waaait... That's not how Microsoft operates, is it?

**Comment by cvjjm** [comment]
#1120  looks like a good solution to me.

**Comment by TaiAurori** [comment]
Windows + NTFS always leads to a few fun ways to break things!

**Comment by waffletower** [comment]
> > Now, I agree that this should be considered a bug in OneDrive and be fixed there
> 
> No, this is not a bug, but a feature. This is a well-known limitation of NTFS. AUX as a filename with any extension is forbidden by design.

Yes, collectively causing thousands of lost works hours to support a legacy code smell should be considered, in rigid binary fashion, an intended feature and not a bug.  🤦‍♂️

**Comment by SadPersonn** [comment]
windows moment

**Comment by barcharcraz** [comment]
This isn't a limitation of NTFS _at all_, it's a limitation of the windows API, that said it's not just onedrive, checking out the repository on windows may result in ... interesting results since accessing aux.py without being very careful to escape things will result in accessing the legacy AUX device, which wasn't what was intended.

I actually think this _is_ arguably a bug in onedrive; onedrive can good and well support the correct escaping to make this work, and it's not its business if my apps can too (it does this with even more annoying patters like leading spaces, which afaik isn't even a windows API limitation but a _shell_ limitation, so almost all apps can handle them just fine).

**Comment by vyv03354** [comment]
By the way, Windows 11 fixed this long-standing "bug". `aux.py`, `.\aux`, and `NUL.txt` are usable on Windows 11. But `.\nul` is not usable yet. Probably because too many .bat files are using `if exist <path to dir>\nul` hack to check existence of a directories.
