### ISSUE TITLE
Feature Request: hessian/thermo.py 

### ISSUE THREAD

**Issue by swillow** [pyscf/pyscf#1127]
When I would like to estimate the zero-point energy of D2O, I have to provide the mass of Deuterium (Heavy Hydrogen).
Hence please add the mass into one of arguments as follows:
```python
def harmonic_analysis (mol, hess, mass=None, ...):
  ...
   if mass is None:
      mass= mol.atom_mass_list(isotope_avg=True)
  ...
```

**Comment by sunqm** [comment]
Fixed in PR #1398
