### ISSUE TITLE
Errors with irrep_nelec with linear molecules

### ISSUE THREAD

**Issue by susilehtola** [pyscf/pyscf#1128]
There appears to be a problem in the Hartree-Fock symmetry code with linear molecules. Please find below two inputs that crash with the master branch of PySCF
```
from pyscf import gto, scf, symm

mol = gto.M(
    verbose = 4,
    atom = '''                                                                                                  
Cu 0 0 0                                                                                                        
Cu 0 0 2.0''',
    basis = 'pc-1',
    symmetry = True
)
# fails due to "wrong number of electrons"
irrep_nelec = {'A1g': 14, 'E1gx': 4, 'E1gy': 4, 'A1u': 10, 'E1uy': 8, 'E1ux': 8, 'E2gx': 4, 'E2gy': 4, 'E3gx': 0, 'E3gy': 0, 'E2uy': 1, 'E2ux': 1, 'E3uy': 0, 'E3ux': 0}                                                      
# fails due to tuple//int mismatch
#irrep_nelec = {'A1g': (7, 7), 'E1gx': (2.0, 2.0), 'E1gy': (2.0, 2.0), 'A1u': (4, 4), 'E1uy': (4.0, 4.0), 'E1ux': (4.0, 4.0), 'E2gx': (2.0, 2.0), 'E2gy': (2.0, 2.0), 'E3gx': (0, 0), 'E3gy': (0, 0), 'E2uy': (1.0, 1.0), 'E2ux': (1.0, 1.0), 'E3uy': (0, 0), 'E3ux': (0, 0)}

mf = scf.RHF(mol)
mf.irrep_nelec = irrep_nelec
Econf = mf.kernel()
```
The inputs have a single electron in some of the symmetry groups, but the calculations should still run, no?

**Comment by sunqm** [comment]
Input1 would lead to 30 spin-up electrons and 28 electrons spin-down. mol.spin should be set to 2 in this case.

For input 2, irrep_nelec must be integer

**Comment by susilehtola** [comment]
But the molecular RHF code runs even if the number of electrons is wrong? You just get a warning like
```
WARN: Invalid number of electrons 7 for RHF method.
```
IMHO it would be logical if the symmetry code would also use fractional occupations in this case.

**Comment by sunqm** [comment]
Supporting fractional occupations for individual irreducible representations can be a special treatment for the symmetry adapted HF code. But supporting this special case will make the program unnecessarily complicated. It's better to develop a plugin to handle this feature and that should be put in pyscf plugins.
