### ISSUE TITLE
Log4j vulnerability

### ISSUE THREAD

**Issue by mariomotta** [pyscf/pyscf#1129]
Greetings,

Recently a vulnerability in log4j was reported.
Does PySCF have any instances of log4j or have programs that depend on log4j?

Thanks,
Mario

**Comment by sunqm** [comment]
No dependency to log4j so far.

On Mon, Dec 13, 2021 at 09:03:18AM -0800, mariomotta wrote:
> Greetings,
> 
> Recently a vulnerability in log4j was reported.
> Does PySCF have any instances of log4j or have programs that depend on log4j?
> 
> Thanks,
> Mario
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyscf/pyscf/issues/1129

--

**Comment by mariomotta** [comment]
many thanks for the feedback, Qiming!
