### ISSUE TITLE
CUTENSOR for einsum?

### ISSUE THREAD

**Issue by jeffhammond** [pyscf/pyscf#1132]
TBLIS is great, but is only for CPUs.  NVIDIA has CUTENSOR, which does similar things on GPUs.  (Disclosure: I work for NVIDIA.)

One can use CUTENSOR without much effort by using [CuPy](https://cupy.dev/), which is a fairly completely Numpy clone that supports CUDA platforms under the hood.  CuPy implements its `einsum` operator using CUTENSOR (https://github.com/cupy/cupy/blob/master/cupy/linalg/_einsum.py). 

I've been using CUTENSOR directly in NWChem CCSD(T) and it works really well, so my optimism is not without some basis.

A simple test of your `einsum` example indicates that CuPy might be useful.  This is on a laptop GPU card that has mediocre FP64 performance.  The performance on big GPUs (e.g. A100) would be much better.

I'm not very good at Python but I am decent at other things.  Maybe somebody is willing to work with me on this and see how it works in coupled-cluster?

Thanks!

```
jhammond@nuclear:~/pyscf$ python3 examples/tools/12-einsum.py
Time for np.einsum 15.95 s
Time for pyscf lib.einsum 1.07 s
Difference between two einsum function 5.6843e-12
Time for cp.einsum 0.21 s
Difference between two einsum function 5.6843e-12
```

```
jhammond@nuclear:~/pyscf$ cat examples/tools/12-einsum.py
#!/usr/bin/env python

'''
An efficient einsum function using BLAS or TBLIS (https://github.com/devinamatthews/tblis)
as the tensor contraction engine. By default, pyscf.lib.einsum calls BLAS gemm
functions for tensor contraction. If tblis is available (see the installation
instruction http://pyscf.org/install.html#tblis), pyscf.lib.einsum calls
TBLIS library at the end. The main advantage of TBLIS library is its small
memory overhead.
'''

import time
import numpy as np
import cupy as cp
from pyscf import lib

a = np.random.random((25,120,20,115))
b = np.random.random((115,83,25,40))

#a2 = cp.zeros((25,120,20,115))
#b2 = cp.zeros((115,83,25,40))
a2 = cp.asarray(a)
b2 = cp.asarray(b)

t0 = time.time()
np_results = np.einsum('xaby,ycxd->cadb', a, b)
print('Time for np.einsum %.2f s' % (time.time() - t0))

t0 = time.time()
pyscf_results = lib.einsum('xaby,ycxd->cadb', a, b)
print('Time for pyscf lib.einsum %.2f s' % (time.time() - t0))

print('Difference between two einsum function %.5g' % abs(pyscf_results - np_results).max())

t0 = time.time()
cp_results = cp.einsum('xaby,ycxd->cadb', a, b)
print('Time for cp.einsum %.2f s' % (time.time() - t0))

print('Difference between two einsum function %.5g' % abs(pyscf_results - cp.asnumpy(cp_results)).max())
```

**Comment by jamesETsmith** [comment]
Hi @jeffhammond, thanks for sharing this, I've been thinking about this for a little and put together some (admittedly crude) code to test it out a few weeks back. I stopped when I started running out memory on the GPU and needed to start thinking more carefully about memory management. I'm definitely still interested in thinking about (and working on) this and would be up to talk about it more.

If you're interested, `rccsd_gpu.py`  is a the crude implementation of RCCSD for the GPU (`RCCSD_CPU`) and `cc_test.py` is a minimal working example to test the speed of `RCCSD_GPU` vs `RCCSD` (i.e. parallelized on just the CPU).

Here are the files:
[rccsd_gpu.py.txt](https://github.com/pyscf/pyscf/files/7712823/rccsd_gpu.py.txt)
[cc_test.py.txt](https://github.com/pyscf/pyscf/files/7712824/cc_test.py.txt)

**Comment by jamesETsmith** [comment]
@jeffhammond, is this something you're still interested in working on?

**Comment by jeffhammond** [comment]
Yeah, for sure. I just time-slice across a bunch of things and haven't revisited this yet.  I also have problems getting Python working right on all the machines, which apparently isn't unusual.

**Comment by jamesETsmith** [comment]
Great, I'll take a crack at improving the gpu memory management in my `rccsd_gpu` code above. Would it be easier to move this discussion to email (or another medium)?

**Comment by jeffhammond** [comment]
yes, email is good.  mine is on my profile, or is otherwise all over the internet.

**Comment by jeffhammond** [comment]
I am sorry I haven't been able to follow through here.  I am trying to get back to it and maybe get some help.

**Comment by sunqm** [comment]
Please continue discussion in gpu4pyscf https://github.com/pyscf/gpu4pyscf/issues/94
