### ISSUE TITLE
OpenMP error when `lib.dot` is called from a thread spawned by `lib.call_in_background` on Cray compilers

### ISSUE THREAD

**Issue by obackhouse** [pyscf/pyscf#1138]
I am running into some problems on a cluster where I am using Cray compilers (CCE 11.0.4 and LibSci 21.04.1.1), see the following example:

```
from pyscf import lib
import numpy as np

n = 100
a = np.random.random((n, n))
b = np.random.random((n, n))
c = np.zeros((n, n))

def update_c_numpy():
    c[:] += np.dot(a, b)

def update_c_pyscf():
    c[:] += lib.dot(a, b)

for i in range(2):
    with lib.call_in_background(update_c_numpy, sync=False) as update_c:
        update_c()
    print("np.dot pass %d" % i, flush=True)

for i in range(2):
    with lib.call_in_background(update_c_pyscf, sync=False) as update_c:
        update_c()
    print("lib.dot pass %d" % i, flush=True)
```

This pattern is encountered in PySCF in a number of places, for example `update_wVooV` in `cc.CCSD`. This outputs:

```
np.dot pass 0
np.dot pass 1
lib.dot pass 0
CCE OpenMP fatal error: OpenMP parallel attempted from non-OpenMP thread
```

This suggests that the OpenMP parallel code in `libnp_helper` does not like to be called from a non-OpenMP thread, i.e. the one spawned by `lib.call_in_background`. Setting `__config__.ASYNC_IO = False` (and indeed `__config__.cc_ccsd_CCSD_async_io = False`) fixes this particular pattern, but there are other patterns which run into similar problems for example `lib.map_with_prefetch`. Should there be a global option for disabling any Python-side threading?

**Comment by sunqm** [comment]
There are two possible ways. One is to explicitly disable the async feature by setting the module level parameter
```
import pyscf
pyscf.lib.misc.ASYNC_IO = False
```
This parameter was not placed at the beginning of that module https://github.com/pyscf/pyscf/blob/master/pyscf/lib/misc.py#L774

The other option is to use a global setting file
```
$ cat ~/.pyscf_conf.py
ASYNC_IO = False
```
Settings in this file will be read by the relevant modules when importing pyscf. More details can be found in the manual  https://pyscf.org/code-rule.html#global-configurations
