### ISSUE TITLE
AIMD Availability for pyscf ?

### ISSUE THREAD

**Issue by HenryMakowitz** [pyscf/pyscf#1148]
Is anyone aware of AIMD software availability for pyscf DFT, TD-DFT etc.

**Comment by jamesETsmith** [comment]
@HenryMakowitz, I think [`libra-code`](https://github.com/Quantum-Dynamics-Hub/libra-code/search?q=pyscf) can use PySCF to do AIMD, but I'm not 100% sure. The [MolSSI Driver interface](https://github.com/MolSSI-MDI/MDI_Library) (MDI) is another option, but that would take a little work to connect PySCF to MDI.

**Comment by matthew-hennefarth** [comment]
@HenryMakowitz AIMD with NVE or NVT ensembles are available in PySCF. Take a look at [`examples/md/00-simple_nve.py`](https://github.com/pyscf/pyscf/blob/master/examples/md/00-simple_nve.py).
