### ISSUE TITLE
aug-cc-pCVXZ type basis sets not available

### ISSUE THREAD

**Issue by kshitij-05** [pyscf/pyscf#1151]
Although one can take these basis sets from https://www.basissetexchange.org/ and use them as a custom basis set in Pyscf, it would be user-friendly if one could use the keyword like 'augccpcvtz' directly. 
Also, I am currently using Pyscf for some relativistic calculations using the Dirac-Hartree-Fock module, and I found that some relativistic basis sets like dyall.acv3z, dyall.ae3z, etc are also not available in Pyscf. 

Regards,
Kshitij

**Comment by jamesETsmith** [comment]
@kshitij-05, I'd suggest using MolSSI's basis set exchange (BSE) Python API in combination with PySCF, see the example here 

https://github.com/pyscf/pyscf/blob/a7ce16fd7e13e8323cb146b3b8bdc016fb0078eb/examples/gto/31-basis_set_exchange.py#L17-L33

I know that it's a few more lines than specifying a "built-in" basis set, but I don't think we want to keep adding basis sets to PySCF when you can get them from the BSE (see the discussion in #898).
