### ISSUE TITLE
KRKS with MDF fails to converge

### ISSUE THREAD

**Issue by hebrewsnabla** [pyscf/pyscf#1154]
I'm trying to run `examples/pbc/21-k_points_all_electron_scf.py`, but the KRHF job with MDF fails to converge. Then I tried KRKS with 6-31gs and three different DFs, and found that only KRKS with MDF fails, while GDF and RSDF works well.
My input looks like
```
 lib.num_threads(28)

cell = gto.M(
    a = numpy.eye(3)*3.5668,
    atom = '''C     0.      0.      0.
              C     0.8917  0.8917  0.8917
              C     1.7834  1.7834  0.
              C     2.6751  2.6751  0.8917
              C     1.7834  0.      1.7834
              C     2.6751  0.8917  2.6751
              C     0.      1.7834  1.7834
              C     0.8917  2.6751  2.6751''',
    basis = '6-31gs',
    verbose = 4,
)

nk = [4,4,4]  # 4 k-poins for each axis, 4^3=64 kpts in total
kpts = cell.make_kpts(nk)

# Mixed density fitting
#
kmf = scf.KRKS(cell, kpts).mix_density_fit()
# In the MDF scheme, modifying the default mesh for PWs to reduce the cost
# The default mesh for PWs is a very dense-grid scheme which is automatically
# generated based on the AO basis. It is often not necessary to use dense grid
# for MDF method.
kmf.xc = 'bp86'
kmf.with_df.mesh = [10,10,10]
kmf.kernel()

# Density fitting
#
kmf = dft.KRKS(cell, kpts).density_fit(auxbasis='weigend')
kmf.xc = 'bp86'
kmf.kernel()

# Range-separated density fitting (RSDF)
# RSDF uses the same amount of memory & disk as GDF and achieves a similar
# accuracy as GDF but is often 5~10x faster than GDF in the DF initialization
# step. The following run should give an energy very close to the one above.
# see '35-range_separated_density_fitting.py' for more details of RSDF.
#
kmf = dft.KRKS(cell, kpts).rs_density_fit(auxbasis='weigend')
kmf.xc = 'bp86'
kmf.kernel()
```
The last part of output of MDF:
```
cycle= 48 E= -303.852099067206  delta_E= 0.000118  |g|= 5.63  |ddm|= 3.24
HOMO = 0.503518440799  LUMO = 0.650701422235
cycle= 49 E= -303.852167596699  delta_E= -6.85e-05  |g|=  5.6  |ddm|= 0.882
HOMO = 0.503541680834  LUMO = 0.650693150238
cycle= 50 E= -303.852098370327  delta_E= 6.92e-05  |g|= 5.63  |ddm|= 1.12
SCF not converged.
SCF energy = -303.852098370327
```
while GDF and RSDF both converges to an energy around -304.914.
I'm using version d096d6f.

**Comment by sunqm** [comment]
MDF may break the symmetry between k-points. For example, integrals `(i_k1,j_k2|k_k2,l_k1)` should be conjugated to `(i_k2,j_k1|k_k1,l_k2)`. If they are computed with GDF or regular FT, we can find the symmetry. This symmetry is not strictly held in MDF. It may produce large errors when computing KHF exchange . It should not affect integrals in pure DFT. I'm not clear why bp86 shows such big numerical error. So the best solution for the moment is to use GDF only in your calculations

**Comment by jamesETsmith** [comment]
Should we add a warning about this, e.g. when someone wants to do MDF with KHF or any DFT that requires KHF exchange?

**Comment by hebrewsnabla** [comment]
> Should we add a warning about this, e.g. when someone wants to do MDF with KHF or any DFT that requires KHF exchange?

I agree. And example pbc/21 should also be modified because it contains a KRHF-MDF job. 
But, the numerical error of BP86 with MDF is still unsolved. I'm not sure whether it's my mistake or anyone can reproduce this.

**Comment by sunqm** [comment]
PR #1168 largely solves the numerical issue in MDF. This system can be converged with MDF

**Comment by hebrewsnabla** [comment]
Hi Qiming, 
I pulled the latest master and re-ran this example, but MDF looks terrible
```
cycle= 1 E= 20400.2011177092  delta_E= 2.07e+04  |g|= 1.59e+06  |ddm|= 5.82e+04
cycle= 2 E= 6349227.6994518  delta_E= 6.33e+06  |g|= 3.32e+07  |ddm|= 8.63e+04
cycle= 3 E= 2906280.16576458  delta_E= -3.44e+06  |g|= 1.65e+07  |ddm|= 3.15e+04
cycle= 4 E= 7983883.36850945  delta_E= 5.08e+06  |g|= 3.71e+07  |ddm|= 5.06e+04
cycle= 5 E= 5027186.51047931  delta_E= -2.96e+06  |g|= 3.44e+07  |ddm|= 6.39e+04
cycle= 6 E= 4475985.59712399  delta_E= -5.51e+05  |g|= 3.19e+07  |ddm|= 5.41e+04
```
So did GDF. But RSGDF has no problem.

**Comment by sunqm** [comment]
You may need to clean c extensions in lib and recompile the c libraries again.

**Comment by hebrewsnabla** [comment]
Re-compiling doesn't help. Using 2.1.0 whl from pip still gives such divergence.

**Comment by hebrewsnabla** [comment]
After pulling #1402, there's no problem for GDF. But MDF still cannot converge,
```
cycle= 45 E= -303.85210079551  delta_E= 3.63e-05  |g|= 5.63  |ddm|=  0.7
cycle= 46 E= -303.852077607401  delta_E= 2.32e-05  |g|= 5.64  |ddm|= 1.53
cycle= 47 E= -303.85221789706  delta_E= -0.00014  |g|= 5.58  |ddm|= 2.67
cycle= 48 E= -303.852075261412  delta_E= 0.000143  |g|= 5.64  |ddm|= 3.29
cycle= 49 E= -303.85216038947  delta_E= -8.51e-05  |g|= 5.61  |ddm|= 1.09
cycle= 50 E= -303.852100570743  delta_E= 5.98e-05  |g|= 5.63  |ddm|= 1.01
```
looks like the condition I met at the beginning of this issue.

**Comment by hebrewsnabla** [comment]
Pulling #1429 (and using odd number of mesh) resolves this problem. Thanks!
