### ISSUE TITLE
Error in the DFT tutorial of the User Guide

### ISSUE THREAD

**Issue by bookcherry** [pyscf/pyscf#1156]
I had some error in the [DFT tutorial of the User Guide](https://pyscf.org/user/dft.html). I am going to state the one of them.

My Python version is 3.8.8. I have already upgraded pyscf to the latest version.

The code is like this.

  > def eval_xc(xc_code, rho, spin=0, relativity=0, deriv=1, verbose=None):
      # A fictitious functional to demonstrate the usage
      rho0, dx, dy, dz = rho
      gamma = (dx ** 2 + dy ** 2 + dz ** 2)
      exc = .01 * rho0 ** 2 + .02 * (gamma + .001) ** .5
      vrho = .01 * 2 * rho0
      vgamma = .02 * .5 * (gamma + .001) ** (-.5)
      vlapl = None
      vtau = None
      vxc = (vrho, vgamma, vlapl, vtau)
      fxc = None # 2nd-order functional derivative
      kxc = None # 3rd-order functional derivative
      return exc, vxc, fxc, kxc
  dft.libxc.define_xc_(mf_hf._numint, eval_xc, xctype='GGA')
  mf_hf.kernel()

The  error is like this.

> ---------------------------------------------------------------------------
      TypeError                                 Traceback (most recent call last)
      /tmp/ipykernel_324380/2056802826.py in <module>
           13     return exc, vxc, fxc, kxc
           14 dft.libxc.define_xc_(mf_hf._numint, eval_xc, xctype='GGA')
      ---> 15 mf_hf.kernel()
      
      ~/.local/lib/python3.8/site-packages/pyscf/soscf/newton_ah.py in kernel(self, mo_coeff, mo_occ, dm0)
          708         self.converged, self.e_tot, \
          709                 self.mo_energy, self.mo_coeff, self.mo_occ = \
      --> 710                 kernel(self, mo_coeff, mo_occ, dm0, conv_tol=self.conv_tol,
          711                        conv_tol_grad=self.conv_tol_grad,
          712                        max_cycle=self.max_cycle,
      
      ~/.local/lib/python3.8/site-packages/pyscf/soscf/newton_ah.py in kernel(mf, mo_coeff, mo_occ, dm, conv_tol, conv_tol_grad, max_cycle, dump_chk, callback, verbose)
          529     for imacro in range(max_cycle):
          530         u, g_orb, kfcount, jkcount, dm_last, vhf = \
      --> 531                 rotaiter.send((mo_coeff, mo_occ, dm, vhf, e_tot))
          532         kftot += kfcount + 1
          533         jktot += jkcount + 1
      
      ~/.local/lib/python3.8/site-packages/pyscf/soscf/newton_ah.py in _rotate_orb_cc(mf, h1e, s1e, conv_tol_grad, verbose)
          364         ikf = 0
          365 
      --> 366         for ah_end, ihop, w, dxi, hdxi, residual, seig \
          367                 in ciah.davidson_cc(h_op, g_op, precond, x0_guess,
          368                                     tol=ah_conv_tol, max_cycle=mf.ah_max_cycle,
      
      ~/.local/lib/python3.8/site-packages/pyscf/soscf/ciah.py in davidson_cc(h_op, g_op, precond, x0, tol, xs, ax, max_cycle, lindep, dot, verbose)
          228     if nx == 0:
          229         xs.append(x0)
      --> 230         ax.append(h_op(x0))
          231     else:
          232         for i in range(1, nx+1):
      
      ~/.local/lib/python3.8/site-packages/pyscf/soscf/newton_ah.py in h_op(x)
          105         d1 = reduce(numpy.dot, (orbv, x*2, orbo.conj().T))
          106         dm1 = d1 + d1.conj().T
      --> 107         v1 = vind(dm1)
          108         x2 += reduce(numpy.dot, (orbv.conj().T, v1, orbo))
          109         if with_symmetry and mol.symmetry:
      
      ~/.local/lib/python3.8/site-packages/pyscf/scf/_response_functions.py in vind(dm1)
           79                     v1 = numpy.zeros_like(dm1)
           80                 else:
      ---> 81                     v1 = ni.nr_rks_fxc(mol, mf.grids, mf.xc, dm0, dm1, 0, hermi,
           82                                        rho0, vxc, fxc, max_memory=max_memory)
           83                 if hybrid:
      
      ~/.local/lib/python3.8/site-packages/pyscf/dft/numint.py in nr_rks_fxc(ni, mol, grids, xc_code, dm0, dms, relativity, hermi, rho0, vxc, fxc, max_memory, verbose)
         1234             for i in range(nset):
         1235                 rho1 = make_rho(i, ao, mask, 'GGA')
      -> 1236                 wv = _rks_gga_wv1(rho, rho1, vxc0, fxc0, weight)
         1237                 #:aow = numpy.einsum('npi,np->pi', ao, wv, out=aow)
         1238                 aow = _scale_ao(ao, wv, out=aow)
      
      ~/.local/lib/python3.8/site-packages/pyscf/dft/numint.py in _rks_gga_wv1(rho0, rho1, vxc, fxc, weight)
         1378 def _rks_gga_wv1(rho0, rho1, vxc, fxc, weight):
         1379     vgamma = vxc[1]
      -> 1380     frho, frhogamma, fgg = fxc[:3]
         1381     # sigma1 ~ \nabla(\rho_\alpha+\rho_\beta) dot \nabla(|b><j|) z_{bj}
         1382     sigma1 = numpy.einsum('xi,xi->i', rho0[1:4], rho1[1:4])
      
      TypeError: 'NoneType' object is not subscriptable
      ---------------------------------

Do you have any idea how to solve this problem? Thank you for in advance.

**Comment by fishjojo** [comment]
To use the second order SCF,  you also need to define fxc.

**Comment by bookcherry** [comment]
OK, thank you, but I don't know how to define fxc. Could you tell me the example of that?
