### ISSUE TITLE
k2gamma assertion error: complex MO coefficients

### ISSUE THREAD

**Issue by Simonsays095** [pyscf/pyscf#1161]
There are several points in the k2gamma code (specifically in the `mo_k2gamma` function) where there are assertions with no description of what causes the issue or how to resolve it. Mostly these are related to matrices that should be real, having significant imaginary components. When I come across one of these assertion errors, what should I do to reduce the errors so that my system/calculation can pass the assertion?

Here is an example that triggers an assertion error:
```
from pyscf.pbc import scf
from pyscf.pbc.gto import Cell
import numpy as np


# ----- Construct a 1-dimensional O2 chain unit cell ----- #
cell = Cell()
cell.atom = [
    ["O", (0,0,0)],
    ["O", (2,0,0)]
]

cell.dimension = 1
cell.basis = '6-31g'
cell.a = np.eye(3)*[4,10,10]
cell.verbose = 4
cell.unit = 'A'
cell.build()

kpts = cell.make_kpts([3,1,1])

# -------- KHF calculation ------- #
mf = scf.KRHF(cell, kpts).density_fit()
e_hf = mf.kernel()


from pyscf.pbc.tools.k2gamma import mo_k2gamma
mo_k2gamma(cell, mf.mo_energy, mf.mo_coeff, mf.kpts, kmesh=None)
```

**Comment by Majokux** [comment]
I and @obackhouse  have been struggling with this issue for a while, and would like to know the answer as well.
It also happens for 3D materials, especially if the band gap is small and/or the point group symmetry of the unit cell high.
In principle one should always be able to find a real set of orbitals at the Gamma-point, but the routine in `k2gamma` does not seem to be robust in this respect. Maybe @zhcui can help?

**Comment by zhcui** [comment]
Hi all,

This issue comes from the degeneracy of the system. The mo occupation patterns are different for different k points:

[[2. 2. 2. 2. 2. 2. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 2. 2. 2. 2. 2. 2. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

The patterns break the symmetry of the phases among different k points. So the MO's cannot be realized.

Best,
Zhihao

**Comment by Majokux** [comment]
Hi Zhihao, many thanks for your response.
I would love to understand this; are you saying that in this case there doesn't exist a set of real orbital in the supercell, which would describe the same occupied space?

Obviously you could always perform the supercell calculation directly (with  6 O-atoms in this case) which would have real orbitals. Would this be a different solution in this case?

**Comment by zhcui** [comment]
Hi Max,

There exists a set of orbitals in the supercell describing the same occupied space, but cannot be realized.

I think we can always get a set of real orbitals from a supercell calculation, but that solution would be different from the one from the above k-point calculation.

**Comment by Majokux** [comment]
Okay that very interesting!
I naively assumed that since the supercell calculation is more "flexible" (has fewer symmetry translations assumed), any k-point solution could also be exactly translated to a supercell solution. But I guess this is only true if you leave the orbitals complex.
Thanks a lot

**Comment by tberkel** [comment]
Hi all, Another way to say Zhihao's point: at the noninteracting level,
this system is a metal (it's equally-spaced O atoms). An RHF calculation of
the supercell that Max suggested probably doesn't converge. The converged
k-point solution, which breaks lattice symmetry as Zhihao said, is a CDW
insulator.

**Comment by Majokux** [comment]
Thanks Tim for the insight!
I gave it a quick try: the supercell does indeed not converge, both with real and complex orbitals, if started from the default initial guess.
If the final k-point DM is folded to the supercell (but left complex), and used as a starting point for a complex supercell calculation, the HF gradient disappears and the calculation is converged immediately. A bit unfortunate that this solution is not being found from the default initial guess.

**Comment by Simonsays095** [comment]
Hi Zhihao and Tim,

Thank you very much for your responses and clarifications. In cases such as these where the k-point results cannot be mapped to a gamma point calculation, can we at least map the results to an unconverged gamma-point system? Regardless of what an RHF calculation would produce (or be unable to produce), it still seems like there should always be an equivalent real-valued gamma-point MO coefficient matrix for any given k-point calculation.

More specifically, the k-point to gamma-point transformation is a unitary transformation. What about the symmetry of a system and its metallic/insulating behaviour causes the gamma-point MO coefficients to be complex? Is it possible to predict when this will occur, or does it boil down to the specifics of the final results of the k-point calculation? Typically, static (gamma-point/aperiodic, at least) systems can be represented using real-valued MO coefficients - is there a property of k-point calculations what gives us a more general form of the system that requires complex-valued MO coefficients, or is it just difficult to transform between the two?

I guess my main question at this point is this: is it _impossible_ to convert these systems to a real-valued equivalent gamma-point system, or does it just require a more complex transformation (than rediagonalizing degenerate MOs) that currently isn't implemented?

**Comment by tberkel** [comment]
Thanks Max for testing and reporting!
> A bit unfortunate that this solution is not being found from the default initial guess.
This is just like RHF/UHF. If you do UHF but start from a guess that doesn't break spin symmetry, you'll get the RHF solution. There's so many possible symmetry-broken phases in solids, it's hard to automate (and possibly dangerous, if the user is not looking for CDW, SDW, etc.). But in principle, we could add some kwargs analogous to `init_guess_breaksym` in UHF.

**Comment by zhcui** [comment]
> Hi Zhihao and Tim,
> 
> Thank you very much for your responses and clarifications. In cases such as these where the k-point results cannot be mapped to a gamma point calculation, can we at least map the results to an unconverged gamma-point system? Regardless of what an RHF calculation would produce (or be unable to produce), it still seems like there should always be an equivalent real-valued gamma-point MO coefficient matrix for any given k-point calculation.
> 
> More specifically, the k-point to gamma-point transformation is a unitary transformation. What about the symmetry of a system and its metallic/insulating behaviour causes the gamma-point MO coefficients to be complex? Is it possible to predict when this will occur, or does it boil down to the specifics of the final results of the k-point calculation? Typically, static (gamma-point/aperiodic, at least) systems can be represented using real-valued MO coefficients - is there a property of k-point calculations what gives us a more general form of the system that requires complex-valued MO coefficients, or is it just difficult to transform between the two?
> 
> I guess my main question at this point is this: is it _impossible_ to convert these systems to a real-valued equivalent gamma-point system, or does it just require a more complex transformation (than rediagonalizing degenerate MOs) that currently isn't implemented?

I think it is impossible to convert such a symmetry-breaking solution to real (not because of implementation).

**Comment by tberkel** [comment]
Yes, if the k-point solution breaks the symmetry between k and -k, then I think it's impossible to map to a supercell determinant with real orbitals. Schematically, you can imagine that the attempted orbital transformation does things like C(k)e^{ik} +/- C(-k)e^{-ik}, which is not purely real/imaginary if C(k) != C(-k).

**Comment by Simonsays095** [comment]
Ok, that makes sense. As a final question, I've seen in the literature that the +/- k-point symmetry is related to time-reversal symmetry. Is that the underlying theory that I can use to predict when a system will fail at k2gamma, or is there some other way to predict when this will happen? I'm not very familiar with time-reversal symmetry, so apologies if I'm way off base.

**Comment by zhcui** [comment]
If the time-reversal symmetry is not obeyed, the realization will fail. I think the converse is not true, it can be other k-point symmetry is broken.
