### ISSUE TITLE
Obtaining correct CASSCF energies for Co 2+ ion.

### ISSUE THREAD

**Issue by Rajatshubhro** [pyscf/pyscf#1167]
Hello, I have been trying to generate state averaged CASSCF energies for Co(II) ion but it seems like my energies are getting messed up. I am using DFT-b3lyp orbitals for Co(3-) calculation as my initial guess orbitals for Co(II) SA-CASSCF calculations using the d-orbitals as my active space.  All calculations were performed using def2-TZVP basis set. The number of roots I am requesting for is 50. I am pasting below my input. It'd be great if I could get some guidance. Thank you.

import numpy as np
import math
import pyscf.gto
import pyscf.scf
import pyscf.mcscf
import pyscf.fci

np.set_printoptions(linewidth=150, edgeitems=10, suppress=True)

basis = 'def2-tzvp'
#print ("Basis set: %s" % basis)

mol = pyscf.gto.Mole()
mol.verbose = 4
mol.atom = [
['Co', ( 0., 0.    , 0.0)],
]
mol.basis = basis
mol.symmetry = False
mol.spin = 0
mol.charge = -3
mol.build()

mf = pyscf.scf.KS(mol)
mf.xc = 'b3lyp'
mf.conv_tol = 1e-12

ehf = mf.scf()
mf.analyze()
mo_init_guess = mf.mo_coeff
print ("SCF energy: %f\n" % ehf)

mol2 = pyscf.gto.Mole()
mol2.verbose = 4
mol2.atom = [
['Co', ( 0., 0.    , 0.0)],
]
mol2.basis = basis
mol2.symmetry = False
mol2.spin = 3
mol2.charge = 2
mol2.build()

mf = pyscf.scf.ROHF(mol2)
mf.conv_tol = 1e-12
#mf.xc = 'b3lyp'

ehf = mf.scf()
mf.analyze()

# Run SA-CASSCF
nroots = 50
ncas = 5
nelecas = 7
weight_same = (1.0/nroots, ) * nroots
solver1 = pyscf.fci.direct_spin1.FCI(mol2)
solver1.spin = 3
solver1 = pyscf.fci.addons.fix_spin(solver1, ss=3.75)
solver1.nroots = 10
weight1 = [1.0/(2*solver1.nroots), ] * solver1.nroots
solver2 = pyscf.fci.direct_spin1.FCI(mol2)
solver2.spin = 1
solver2 = pyscf.fci.addons.fix_spin(solver2, ss=0.75)
solver2.nroots = 40
weight2 = [1.0/(2*solver2.nroots), ] * solver2.nroots
weight_diff = tuple(weight1 + weight2)

mc = pyscf.mcscf.CASSCF(mf, ncas, nelecas)
mo = pyscf.mcscf.project_init_guess(mc, mo_init_guess)
mc = pyscf.mcscf.state_average_mix_(mc, [solver1, solver2], weight_diff)
mc.conv_tol = 1e-10
mc.conv_tol_grad = 5e-7
mc.max_cycle_macro = 100
mc.davidson_only = False
mc.pspace_size = 6000

emc = mc.mc1step(mo)[0]
mc.analyze()

**Comment by xubwa** [comment]
Hi, providing an output file will be more useful for people to figure out your problem.

**Comment by Rajatshubhro** [comment]
******** <class 'pyscf.dft.rks.RKS'> ********
method = RKS-RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-12
SCF conv_tol_grad = None
SCF max_cycles = 100
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /scratch/local/tmpc82us55s
max_memory 4000 MB (current use 64 MB)
XC library pyscf.dft.xcfun version 2.1.1
    XCFun DFT library Copyright 2009-2020 Ulf Ekstrom and contributors.
See http://dftlibs.org/xcfun/ for more information.

This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE. For details see the documentation.
Scientific users of this library should cite
U. Ekstrom, L. Visscher, R. Bast, A. J. Thorvaldsen and K. Ruud;
J.Chem.Theor.Comp. 2010, DOI: 10.1021/ct100117s

XC functionals = b3lyp
radial grids:
    Treutler-Ahlrichs [JCP 102, 346 (1995); DOI:10.1063/1.469408] (M4) radial grids

becke partition: Becke, JCP 88, 2547 (1988); DOI:10.1063/1.454033
pruning grids: <function nwchem_prune at 0x7f8b80819ea0>
grids dens level: 3
symmetrized grids: False
atomic radii adjust function: <function treutler_atomic_radii_adjust at 0x7f8b80819e18>
cycle= 12 E= -1381.78868884077  delta_E= -1.49  |g|= 0.549  |ddm|= 1.81
  HOMO = 0.602474910606381  LUMO = 0.766650202012564
cycle= 13 E= -1381.81369620053  delta_E= -0.025  |g|= 0.345  |ddm|= 0.384
  HOMO = 0.593238355052027  LUMO = 0.763271192854558
cycle= 14 E= -1381.82649954913  delta_E= -0.0128  |g|= 0.0475  |ddm|= 0.122
  HOMO = 0.591461704364517  LUMO = 0.762352167298805
cycle= 15 E= -1381.82675970033  delta_E= -0.00026  |g|= 0.00224  |ddm|= 0.0253
  HOMO = 0.591410786949229  LUMO = 0.762347225857483
cycle= 16 E= -1381.82676024757  delta_E= -5.47e-07  |g|= 2.65e-05  |ddm|= 0.0016
  HOMO = 0.591410934482258  LUMO = 0.762346759907528
cycle= 17 E= -1381.82676024764  delta_E= -7.41e-11  |g|= 1.03e-06  |ddm|= 2.22e-05
  HOMO = 0.591410967930839  LUMO = 0.762346771512445
cycle= 18 E= -1381.82676024764  delta_E= 2.27e-13  |g|= 1.05e-08  |ddm|= 9.89e-07
  HOMO = 0.591410964313635  LUMO = 0.762346770103791
Extra cycle  E= -1381.82676024764  delta_E= -1.36e-12  |g|= 1.01e-07  |ddm|= 4.39e-08
converged SCF energy = -1381.82676024764
**** SCF Summaries ****
Total Energy =                       -1381.826760247641460
Nuclear Repulsion Energy =               0.000000000000000
One-electron Energy =                -1938.838750810812144
Two-electron Coulomb Energy =          616.734310350798296
DFT Exchange-Correlation Energy =      -59.722319787627590
**** MO energy ****
MO #1   energy= -276.677418397401  occ= 2
MO #2   energy= -31.9592012391781  occ= 2
MO #3   energy= -27.6060688244335  occ= 2
MO #4   energy= -27.6060688244335  occ= 2
MO #5   energy= -27.6060688244335  occ= 2
MO #6   energy= -2.83988495926878  occ= 2
MO #7   energy= -1.52460019854002  occ= 2
MO #8   energy= -1.52460019854001  occ= 2
MO #9   energy= -1.52460019854001  occ= 2
MO #10  energy= 0.452384106467204  occ= 2
MO #11  energy= 0.591410964313627  occ= 2
MO #12  energy= 0.59141096431363   occ= 2
MO #13  energy= 0.59141096431363   occ= 2
MO #14  energy= 0.591410964313633  occ= 2
MO #15  energy= 0.591410964313635  occ= 2
MO #16  energy= 0.762346770103791  occ= 0
MO #17  energy= 0.764131925858702  occ= 0
MO #18  energy= 0.764131925858702  occ= 0
MO #19  energy= 0.76413192585871   occ= 0
MO #20  energy= 0.804024199416955  occ= 0
MO #21  energy= 0.804024199416964  occ= 0
MO #22  energy= 0.804024199416967  occ= 0
MO #23  energy= 0.804024199416968  occ= 0
MO #24  energy= 0.804024199416969  occ= 0
MO #25  energy= 1.73324981108308   occ= 0
MO #26  energy= 1.73324981108309   occ= 0
MO #27  energy= 1.73324981108309   occ= 0
MO #28  energy= 1.7332498110831    occ= 0
MO #29  energy= 1.7332498110831    occ= 0
MO #30  energy= 2.61978763645989   occ= 0
MO #31  energy= 2.6197876364599    occ= 0
MO #32  energy= 2.61978763645992   occ= 0
MO #33  energy= 3.60157581908288   occ= 0
MO #34  energy= 4.62969776934204   occ= 0
MO #35  energy= 4.62969776934205   occ= 0
MO #36  energy= 4.62969776934205   occ= 0
MO #37  energy= 4.62969776934206   occ= 0
MO #38  energy= 4.62969776934206   occ= 0
MO #39  energy= 5.71673163390673   occ= 0
MO #40  energy= 5.71673163390674   occ= 0
MO #41  energy= 5.71673163390675   occ= 0
MO #42  energy= 5.71673163390675   occ= 0
MO #43  energy= 5.71673163390675   occ= 0
MO #44  energy= 5.71673163390676   occ= 0
MO #45  energy= 5.71673163390676   occ= 0
 ** Mulliken pop on meta-lowdin orthogonal AOs  **
 ** Mulliken pop  **
pop of  0 Co 1s        1.99999
pop of  0 Co 2s        1.99979
pop of  0 Co 3s        1.99931
pop of  0 Co 4s        1.62756
pop of  0 Co 5s        0.21126
pop of  0 Co 6s        0.16210
pop of  0 Co 2px       1.99997
pop of  0 Co 2py       1.99997
pop of  0 Co 2pz       1.99997
pop of  0 Co 3px       1.99976
pop of  0 Co 3py       1.99976
pop of  0 Co 3pz       1.99976
pop of  0 Co 4px       0.00021
pop of  0 Co 4py       0.00021
pop of  0 Co 4pz       0.00021
pop of  0 Co 5px       0.00006
pop of  0 Co 5py       0.00006
pop of  0 Co 5pz       0.00006
pop of  0 Co 3dxy      1.81908
pop of  0 Co 3dyz      1.81908
pop of  0 Co 3dz^2     1.81908
pop of  0 Co 3dxz      1.81908
pop of  0 Co 3dx2-y2    1.81908
pop of  0 Co 4dxy      0.09645
pop of  0 Co 4dyz      0.09645
pop of  0 Co 4dz^2     0.09645
pop of  0 Co 4dxz      0.09645
pop of  0 Co 4dx2-y2    0.09645
pop of  0 Co 5dxy      0.06233
pop of  0 Co 5dyz      0.06233
pop of  0 Co 5dz^2     0.06233
pop of  0 Co 5dxz      0.06233
pop of  0 Co 5dx2-y2    0.06233
pop of  0 Co 6dxy      0.02214
pop of  0 Co 6dyz      0.02214
pop of  0 Co 6dz^2     0.02214
pop of  0 Co 6dxz      0.02214
pop of  0 Co 6dx2-y2    0.02214
pop of  0 Co 4f-3      0.00000
pop of  0 Co 4f-2      0.00000
pop of  0 Co 4f-1      0.00000
pop of  0 Co 4f 0      0.00000
pop of  0 Co 4f 1      0.00000
pop of  0 Co 4f 2      0.00000
pop of  0 Co 4f 3      0.00000
 ** Mulliken atomic charges  **
charge of  0Co =     -3.00000
Dipole moment(X, Y, Z, Debye):  0.00000, -0.00000,  0.00000
SCF energy: -1381.826760

******** <class 'pyscf.mcscf.addons._state_average_mcscf_solver.<locals>.StateAverageMCSCF'> ********
CAS (5e+2e, 5o), ncore = 9, nvir = 31
max_cycle_macro = 100
max_cycle_micro = 4
conv_tol = 1e-10
conv_tol_grad = 5e-07
orbital rotation max_stepsize = 0.02
augmented hessian ah_max_cycle = 30
augmented hessian ah_conv_tol = 1e-12
augmented hessian ah_linear dependence = 1e-14
augmented hessian ah_level shift = 1e-08
augmented hessian ah_start_tol = 2.5
augmented hessian ah_start_cycle = 3
augmented hessian ah_grad_trust_region = 3
kf_trust_region = 3
kf_interval = 4
ci_response_space = 4
ci_grad_trust_region = 3
with_dep4 0
natorb = False
canonicalization = True
sorting_mo_energy = False
ao2mo_level = 2
chkfile = /scratch/local/tmpzvzcp481
max_memory 4000 MB (current use 150 MB)
internal_rotation = False
******** <class 'pyscf.mcscf.addons.state_average_mix.<locals>.FakeCISolver'> ********
max. cycles = 50
conv_tol = 1e-08
davidson only = False
linear dependence = 1e-10
level shift = 0.001
max iter space = 12
max_memory 4000 MB
nroots = 50
pspace_size = 400
spin = None
CASCI E = -1376.98874154399  S^2 = 2.4750000
macro iter 1 (21 JK  4 micro), CASSCF E = -1378.84808171965  dE = -1.8593402  S^2 = 2.4750000
               |grad[o]|= 3.75  |grad[c]|= None  |ddm|=0.00654
macro iter 2 (21 JK  4 micro), CASSCF E = -1379.66385919315  dE = -0.81577747  S^2 = 2.4750000
               |grad[o]|= 2.07  |grad[c]|= None  |ddm|=0.0215
macro iter 3 (21 JK  4 micro), CASSCF E = -1379.91103191956  dE = -0.24717273  S^2 = 2.4750000
               |grad[o]|=0.926  |grad[c]|= None  |ddm|=0.0191
macro iter 4 (21 JK  4 micro), CASSCF E = -1379.95354584406  dE = -0.042513925  S^2 = 2.4750000
               |grad[o]|=0.328  |grad[c]|= None  |ddm|=0.0119
macro iter 5 (12 JK  3 micro), CASSCF E = -1379.95609843452  dE = -0.0025525905  S^2 = 2.4750000
               |grad[o]|=0.0753  |grad[c]|= None  |ddm|=0.00437
macro iter 6 (9 JK  3 micro), CASSCF E = -1379.95611001581  dE = -1.1581288e-05  S^2 = 2.4750000
               |grad[o]|=0.011  |grad[c]|= None  |ddm|=0.000242
macro iter 7 (7 JK  2 micro), CASSCF E = -1379.95619089773  dE = -8.0881916e-05  S^2 = 2.4750000
               |grad[o]|=0.00222  |grad[c]|= None  |ddm|=0.00549
macro iter 8 (7 JK  2 micro), CASSCF E = -1379.95635792594  dE = -0.00016702821  S^2 = 2.4750000
               |grad[o]|=0.00468  |grad[c]|= None  |ddm|=0.00733
macro iter 9 (15 JK  4 micro), CASSCF E = -1379.95656265479  dE = -0.00020472885  S^2 = 2.4750000
               |grad[o]|=0.00698  |grad[c]|= None  |ddm|=0.0127
macro iter 10 (12 JK  3 micro), CASSCF E = -1379.95660802538  dE = -4.5370586e-05  S^2 = 2.4750000
               |grad[o]|=0.00866  |grad[c]|= None  |ddm|=0.00411
macro iter 11 (8 JK  2 micro), CASSCF E = -1379.9566113838  dE = -3.3584249e-06  S^2 = 2.4750000
               |grad[o]|=0.00214  |grad[c]|= None  |ddm|=0.00094
macro iter 12 (16 JK  4 micro), CASSCF E = -1379.95661831571  dE = -6.9319071e-06  S^2 = 2.4750000
               |grad[o]|=0.00129  |grad[c]|= None  |ddm|=0.00232
macro iter 13 (17 JK  4 micro), CASSCF E = -1379.9566186686  dE = -3.5288849e-07  S^2 = 2.4750000
               |grad[o]|=0.000847  |grad[c]|= None  |ddm|=0.000353
macro iter 14 (14 JK  4 micro), CASSCF E = -1379.9566186718  dE = -3.2066509e-09  S^2 = 2.4750000
               |grad[o]|=2.21e-05  |grad[c]|= None  |ddm|=5.42e-05
macro iter 15 (32 JK  3 micro), CASSCF E = -1379.95661867181  dE = -6.3664629e-12  S^2 = 2.4750000
               |grad[o]|=1.27e-06  |grad[c]|= None  |ddm|=2.28e-06
macro iter 16 (1 JK  1 micro), CASSCF E = -1379.95661867181  dE = 9.094947e-13  S^2 = 2.4750000
               |grad[o]|=6.23e-07  |grad[c]|= None  |ddm|=1.66e-15
macro iter 17 (17 JK  1 micro), CASSCF E = -1379.95661867181  dE = -4.5474735e-13  S^2 = 2.4750000
               |grad[o]|=6.47e-07  |grad[c]|= None  |ddm|=7.05e-16
macro iter 18 (1 JK  1 micro), CASSCF E = -1379.95661867181  dE = 0  S^2 = 2.4750000
               |grad[o]|=6.47e-07  |grad[c]|= None  |ddm|=1.41e-15
macro iter 19 (1 JK  1 micro), CASSCF E = -1379.95661867181  dE = 2.2737368e-13  S^2 = 2.4750000
               |grad[o]|=6.47e-07  |grad[c]|= None  |ddm|=1.07e-15
macro iter 20 (1 JK  1 micro), CASSCF E = -1379.95661867181  dE = -2.2737368e-13  S^2 = 2.4750000
               |grad[o]|=6.47e-07  |grad[c]|= None  |ddm|=1.88e-15
macro iter 21 (1 JK  1 micro), CASSCF E = -1379.95661867181  dE = 0  S^2 = 2.4750000
               |grad[o]|=6.47e-07  |grad[c]|= None  |ddm|=7.21e-16
macro iter 22 (1 JK  1 micro), CASSCF E = -1379.95661867181  dE = 0  S^2 = 2.4750000
               |grad[o]|=6.47e-07  |grad[c]|= None  |ddm|=1.53e-15
macro iter 23 (1 JK  1 micro), CASSCF E = -1379.95661867181  dE = 0  S^2 = 2.4750000
               |grad[o]|=6.47e-07  |grad[c]|= None  |ddm|=1.1e-15
macro iter 24 (1 JK  1 micro), CASSCF E = -1379.95661867181  dE = -4.5474735e-13  S^2 = 2.4750000
               |grad[o]|=6.47e-07  |grad[c]|= None  |ddm|=9.51e-16
macro iter 25 (1 JK  1 micro), CASSCF E = -1379.95661867181  dE = 0  S^2 = 2.4750000
               |grad[o]|=6.47e-07  |grad[c]|= None  |ddm|=1.02e-15
macro iter 26 (1 JK  1 micro), CASSCF E = -1379.95661867181  dE = 4.5474735e-13  S^2 = 2.4750000
               |grad[o]|=6.47e-07  |grad[c]|= None  |ddm|=8.63e-16
macro iter 27 (1 JK  1 micro), CASSCF E = -1379.95661867181  dE = -4.5474735e-13  S^2 = 2.4750000
               |grad[o]|=6.47e-07  |grad[c]|= None  |ddm|=1.04e-15
macro iter 28 (1 JK  1 micro), CASSCF E = -1379.95661867181  dE = 0  S^2 = 2.4750000
               |grad[o]|=6.47e-07  |grad[c]|= None  |ddm|=1.9e-15
macro iter 29 (1 JK  1 micro), CASSCF E = -1379.95661867181  dE = 4.5474735e-13  S^2 = 2.4750000
               |grad[o]|=6.47e-07  |grad[c]|= None  |ddm|=1.53e-15
macro iter 30 (1 JK  1 micro), CASSCF E = -1379.95661867181  dE = -4.5474735e-13  S^2 = 2.4750000
               |grad[o]|=6.47e-07  |grad[c]|= None  |ddm|=8.34e-16
macro iter 31 (1 JK  1 micro), CASSCF E = -1379.95661867181  dE = 4.5474735e-13  S^2 = 2.4750000
               |grad[o]|=6.47e-07  |grad[c]|= None  |ddm|=1.24e-15
macro iter 93 (1 JK  1 micro), CASSCF E = -1379.95661867181  dE = -2.2737368e-13  S^2 = 2.4750000
               |grad[o]|=6.47e-07  |grad[c]|= None  |ddm|=8.08e-16
macro iter 94 (1 JK  1 micro), CASSCF E = -1379.95661867181  dE = 0  S^2 = 2.4750000
               |grad[o]|=6.47e-07  |grad[c]|= None  |ddm|=7.1e-16
macro iter 95 (1 JK  1 micro), CASSCF E = -1379.95661867181  dE = 0  S^2 = 2.4750000
               |grad[o]|=6.47e-07  |grad[c]|= None  |ddm|=1.45e-15
macro iter 96 (1 JK  1 micro), CASSCF E = -1379.95661867181  dE = 4.5474735e-13  S^2 = 2.4750000
               |grad[o]|=6.47e-07  |grad[c]|= None  |ddm|=8.07e-16
macro iter 97 (1 JK  1 micro), CASSCF E = -1379.95661867181  dE = -2.2737368e-13  S^2 = 2.4750000
               |grad[o]|=6.47e-07  |grad[c]|= None  |ddm|=5.5e-16
macro iter 98 (1 JK  1 micro), CASSCF E = -1379.95661867181  dE = 0  S^2 = 2.4750000
               |grad[o]|=6.47e-07  |grad[c]|= None  |ddm|=1.06e-15
macro iter 99 (1 JK  1 micro), CASSCF E = -1379.95661867181  dE = 2.2737368e-13  S^2 = 2.4750000
               |grad[o]|=6.47e-07  |grad[c]|= None  |ddm|=1.14e-15
macro iter 100 (1 JK  1 micro), CASSCF E = -1379.95661867181  dE = -2.2737368e-13  S^2 = 2.4750000
               |grad[o]|=6.47e-07  |grad[c]|= None  |ddm|=1.18e-15
1-step CASSCF not converged, 100 macro (334 JK 135 micro) steps
CASSCF canonicalization
Density matrix diagonal elements [1.32503139 1.4073666  1.4053916  1.42616209 1.43604832]
CASSCF energy = -1379.95661867181
CASCI E = -1379.95661867181  E(CI) = -27.5870408162682  S^2 = 2.4750000
CASCI state-averaged energy = -1379.95661867181
CASCI energy for each state
  State 0 weight 0.05  E = -1380.23549109516 S^2 = 3.7500000
  State 1 weight 0.05  E = -1380.2109773823 S^2 = 3.7500000
  State 2 weight 0.05  E = -1380.2109773823 S^2 = 3.7500000
  State 3 weight 0.05  E = -1380.17351265936 S^2 = 3.7500000
  State 4 weight 0.05  E = -1380.17350816135 S^2 = 3.7500000
  State 5 weight 0.05  E = -1380.09313035479 S^2 = 3.7500000
  State 6 weight 0.05  E = -1379.73259889663 S^2 = 3.7500000
  State 7 weight 0.05  E = -1379.73259578021 S^2 = 3.7500000
  State 8 weight 0.05  E = -1379.69608975185 S^2 = 3.7500000
  State 9 weight 0.05  E = -1379.69608974896 S^2 = 3.7500000
 State 10 weight 0.0125  E = -1380.28773406277 S^2 = 0.7500000
  State 11 weight 0.0125  E = -1380.2877340609 S^2 = 0.7500000
  State 12 weight 0.0125  E = -1380.20820721204 S^2 = 0.7500000
  State 13 weight 0.0125  E = -1380.20331897594 S^2 = 0.7500000
  State 14 weight 0.0125  E = -1380.20331196376 S^2 = 0.7500000
  State 15 weight 0.0125  E = -1380.18368945665 S^2 = 0.7500000
  State 16 weight 0.0125  E = -1380.18368945665 S^2 = 0.7500000
  State 17 weight 0.0125  E = -1380.16954764477 S^2 = 0.7500000
  State 18 weight 0.0125  E = -1380.16954764477 S^2 = 0.7500000
  State 19 weight 0.0125  E = -1380.15420654194 S^2 = 0.7500000
  State 20 weight 0.0125  E = -1380.14624174782 S^2 = 0.7500000
  State 21 weight 0.0125  E = -1380.1462372567 S^2 = 0.7500000
  State 22 weight 0.0125  E = -1380.11778272731 S^2 = 0.7500000
  State 23 weight 0.0125  E = -1380.11778068561 S^2 = 0.7500000
  State 24 weight 0.0125  E = -1380.0803929032 S^2 = 0.7500000
  State 25 weight 0.0125  E = -1380.0803929032 S^2 = 0.7500000
  State 26 weight 0.0125  E = -1380.06586820537 S^2 = 0.7500000
  State 27 weight 0.0125  E = -1380.01002056964 S^2 = 0.7500000
  State 28 weight 0.0125  E = -1380.01002056922 S^2 = 0.7500000
  State 29 weight 0.0125  E = -1379.93549109516 S^2 = 3.7500000
  State 30 weight 0.0125  E = -1379.9109773823 S^2 = 3.7500000
  State 31 weight 0.0125  E = -1379.9109773823 S^2 = 3.7500000
  State 32 weight 0.0125  E = -1379.89449898935 S^2 = 0.7500000
  State 33 weight 0.0125  E = -1379.87351265936 S^2 = 3.7500000
  State 34 weight 0.0125  E = -1379.87350816135 S^2 = 3.7500000
  State 35 weight 0.0125  E = -1379.79313035479 S^2 = 3.7500000
  State 36 weight 0.0125  E = -1379.66312461787 S^2 = 0.7500000
  State 37 weight 0.0125  E = -1379.66312461787 S^2 = 0.7500000
  State 38 weight 0.0125  E = -1379.6563490684 S^2 = 0.7500000
  State 39 weight 0.0125  E = -1379.65634906524 S^2 = 0.7500000
  State 40 weight 0.0125  E = -1379.63513799544 S^2 = 0.7500000
  State 41 weight 0.0125  E = -1379.63513723074 S^2 = 0.7500000
  State 42 weight 0.0125  E = -1379.62564374214 S^2 = 0.7500000
  State 43 weight 0.0125  E = -1379.62564374214 S^2 = 0.7500000
  State 44 weight 0.0125  E = -1379.60280500634 S^2 = 0.7500000
  State 45 weight 0.0125  E = -1379.60280367814 S^2 = 0.7500000
 State 45 weight 0.0125  E = -1379.60280367814 S^2 = 0.7500000
  State 46 weight 0.0125  E = -1379.58813361842 S^2 = 0.7500000
  State 47 weight 0.0125  E = -1379.58813361842 S^2 = 0.7500000
  State 48 weight 0.0125  E = -1379.57470114061 S^2 = 0.7500000
  State 49 weight 0.0125  E = -1379.57470113857 S^2 = 0.7500000
Natural occ [1.44222921 1.44222539 1.39525859 1.39525858 1.32502823]

**Comment by Rajatshubhro** [comment]
I have pasted the output above. My input file states it to give me 10 states with S^2 = 3.75 and 40 states with S^2 = 0.75. Also, comparing the CASSCF energies for the 50 states, I do not see any degeneracy that I expect for Co(II) ion.

**Comment by xubwa** [comment]
I don't know what kind of degeneracy are you expecting exactly, but there are still a good amount of degenray states right?

**Comment by Rajatshubhro** [comment]
Yes, it shows some. But the Co(II) has 4F term as its ground state, so it should be showing a 7-fold degenerate states and then there are 4P, 2G states which I'd expect to show their respective degeneracies. That's why I was thinking of how to get the CASSCF states accounted for.

**Comment by susilehtola** [comment]
However, the PySCF calculations are restricted to the m_s subshell specified by the spin; it doesn't reproduce the multiplets. Also, the basis functions are real spherical harmonics, not complex spherical harmonics, which might also affect the results.

**Comment by 1234zou** [comment]
I simply use the UHF natural orbitals (UNO) as the initial guess for SA-CASSCF calculations, and find the results look normal, i.e. 7 lowest states with S^2 = 3.75, then 3 states with S^2 = 3.75, 9 states with S^2 = 0.75, etc. Here is my calcualtions:

Step 1. Get UNO using Gaussian program
(I do not know how to easily obtain UNO using PySCF, maybe someone can show a simple example to me)
The Co2+.gjf file is
```
%chk=Co2+.chk
#p UHF/def2TZVP nosymm int=nobasistransform stable=opt

title

2 4
Co   0.0   0.0   0.0

--Link1--
%chk=Co2+.chk
#p UHF chkbasis guess(read,only,save,NaturalOrbitals) geom=allcheck nosymm int=nobasistransform
```
After computation finished, we obtain Co2+.chk. Now run
```
formchk Co2+.chk Co2+.fch
fch_u2r Co2+.fch
bas_fch2py Co2+_r.fch
```
I use the utility fch_u2r to delete Beta MO information in Co2+.fch file, since Gaussian has a tiny bug in storing UNOs into fch file (useless Beta MO information). Then the utility bas_fch2py is used to generate Co2+_r.py for following PySCF computation. Two utilities fch_u2r and bas_fch2py can be freely download at [MOKIT](https://gitlab.com/jxzou/mokit).

Step 2. Simply modify the .py script
Append SA-CASSCF keywords in Co2+_r.py
```
from pyscf import mcscf
(not shown for brevity)
mc = mcscf.CASSCF(mf, 5, (5,2))
mc.verbose = 5
mc = mc.state_average_([1e0/7e0,1e0/7e0,1e0/7e0,1e0/7e0,1e0/7e0,1e0/7e0,1e0/7e0])
mc.kernel()
ave_mo = mc.mo_coeff.copy()

mc = mcscf.CASCI(mf, 5, (5,2))
mc.verbose = 5
mc.fcisolver.spin = 1
mc.fcisolver.nroots = 20
mc.kernel(ave_mo)
```

Step 3. Perform SA-CASSCF and multi-root CASCI calculations
The results are
```
CASCI converged
CASCI state 0  E = -1380.57046582305  E(CI) = -28.5798780998521  S^2 = 3.7500000
CASCI state 1  E = -1380.57046563871  E(CI) = -28.5798779155066  S^2 = 3.7500000
CASCI state 2  E = -1380.57046559792  E(CI) = -28.5798778747167  S^2 = 3.7500000
CASCI state 3  E = -1380.5704653852  E(CI) = -28.5798776619949  S^2 = 3.7500000
CASCI state 4  E = -1380.5704653081  E(CI) = -28.5798775849005  S^2 = 3.7500000
CASCI state 5  E = -1380.57046523822  E(CI) = -28.5798775150186  S^2 = 3.7500000
CASCI state 6  E = -1380.57046508628  E(CI) = -28.5798773630788  S^2 = 3.7500000
CASCI state 7  E = -1380.48411707858  E(CI) = -28.4935293553769  S^2 = 3.7500000
CASCI state 8  E = -1380.48411669018  E(CI) = -28.4935289669734  S^2 = 3.7500000
CASCI state 9  E = -1380.48411626282  E(CI) = -28.4935285396195  S^2 = 3.7500000
CASCI state 10  E = -1380.48363169675  E(CI) = -28.4930439735474  S^2 = 0.7500000
CASCI state 11  E = -1380.48363169337  E(CI) = -28.4930439701666  S^2 = 0.7500000
CASCI state 12  E = -1380.48363162956  E(CI) = -28.4930439063585  S^2 = 0.7500000
CASCI state 13  E = -1380.48363160211  E(CI) = -28.493043878904  S^2 = 0.7500000
CASCI state 14  E = -1380.48363154527  E(CI) = -28.4930438220661  S^2 = 0.7500000
CASCI state 15  E = -1380.4836315179  E(CI) = -28.4930437946973  S^2 = 0.7500000
CASCI state 16  E = -1380.48363151635  E(CI) = -28.4930437931473  S^2 = 0.7500000
CASCI state 17  E = -1380.48363147359  E(CI) = -28.4930437503831  S^2 = 0.7500000
CASCI state 18  E = -1380.48363146284  E(CI) = -28.4930437396395  S^2 = 0.7500000
CASCI state 19  E = -1380.45484898172  E(CI) = -28.4642612585196  S^2 = 0.7500000
```

**Comment by hebrewsnabla** [comment]
@1234zou , your procedure can be simply done with PySCF as follows (I skipped the stability check for simplicity, which can also be done by PySCF)
```
from pyscf import lib, gto, scf, mcscf

lib.num_threads(8)

mol = gto.Mole(atom='''Co 0.0 0.0 0.0''', basis='def2-tzvp', charge=2, spin=3).build()

mf = scf.UHF(mol).kernel()

noon,uno = mcscf.addons.make_natural_orbitals(mf)

mc = mcscf.CASSCF(mf, 5, (5,2))
mc.mo_coeff = uno
mc.verbose = 5
mc = mc.state_average_([1e0/7e0,1e0/7e0,1e0/7e0,1e0/7e0,1e0/7e0,1e0/7e0,1e0/7e0])
mc.kernel()
ave_mo = mc.mo_coeff.copy()

mc = mcscf.CASCI(mf, 5, (5,2))
mc.verbose = 5
mc.fcisolver.spin = 1
mc.fcisolver.nroots = 20
mc.kernel(ave_mo)
```

**Comment by Rajatshubhro** [comment]
Thank you so much for the help. The spatial degeneracy has been restored using the natural orbitals as my guess orbitals for the CASSCF calculations.

**Comment by susilehtola** [comment]
So the problem with the original input file was just that it used UB3LYP orbitals, while ROB3LYP would have worked? I.e. replace `KS` with `ROKS`.

**Comment by hebrewsnabla** [comment]
> So the problem with the original input file was just that it used UB3LYP orbitals, while ROB3LYP would have worked? I.e. replace `KS` with `ROKS`.

I don't think so. In the original input, the `mo_init_guess` came from a RB3LYP of Co with -3 charge, which is closed shell. In my and jxzou's solution, UHF natural orbitals (UNO) are used. There's no ROHF/ROKS orbital used in the above discussion, although UNO is quite close to ROHF orbital in this case.

**Comment by susilehtola** [comment]
Oh, okay. I guess the answer in that case is that the states used for the state average didn't have the correct symmetry..?

In any case, if you're doing atomic CASSCF, I would recommend skipping the initial SCF and just starting CASSCF from the atomic guess since those are fractionally occupied, spin-restricted orbitals that should be relatively close to the multi-determinant Hartree-Fock solution.
