### ISSUE TITLE
state specific CASSCF for C2 Sigma_g^+ hard to converge

### ISSUE THREAD

**Issue by hebrewsnabla** [pyscf/pyscf#1174]
I'm trying to obtain some CASSCF results for C2 at bond length 1.8 angstrom. 
It's easier if I enable the symmetry, like
```
xyz = '''C 0.0 0.0 0.0; C 0.0 0.0 1.8'''
mol = gto.M(atom=xyz, basis='cc-pvtz',symmetry='D2h').build()

mf = scf.RHF(mol)
mf.verbose = 4
mf.kernel()

mc = mcscf.CASSCF(mf, 8, (4,4))
mc.fcisolver.wfnsym = 'Ag'
mc.fix_spin_(ss=0)
mc = mc.state_average_([1.0/3, 1.0/3, 1.0/3])
mc.run()

mc2 = mcscf.CASSCF(mf, 8, (4,4))
mc2.fcisolver.wfnsym = 'Ag'
mc2.fix_spin_(ss=0)
mc2 = mc2.state_average_([0.0, 0.0, 1.0])
mc2.verbose = 4
mc2.kernel(mc.mo_coeff, ci0=mc.ci)
```
The state averaged job converges very quickly, while the state specific one takes 27 macro cycles to converge. The third root has occupation pattern `22022000` (in other word, sigma_2s, sigma_2s*, pi_2px, pi_2py are occupied in main configuration) and energy `-75.4849`.

When I try to run without symmetry, the state averaged job converges as expected, but state specific one for the third Sigma_g^+(root 6 here) cannot.
```
xyz = '''C 0.0 0.0 0.0; C 0.0 0.0 1.8'''
mol = gto.M(atom=xyz, basis='cc-pvtz')

mf = scf.RHF(mol)
mf.verbose = 4
mf.kernel()

mc = mcscf.CASSCF(mf, 8, (4,4))
mc.fix_spin_(ss=0)
mc = mc.state_average_([1.0/6, 1.0/6, 1.0/6, 1.0/6, 1.0/6, 1.0/6, 0.0, 0.0])
mc.run()

mc2 = mcscf.CASSCF(mf, 8, (4,4))
mc2.fix_spin_(ss=0)
mc2 = mc2.state_average_([0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0])
mc2.kernel(mc.mo_coeff, ci0=mc.ci)
```
It seems the second job was quite close to the right energy at first 2 macro cycle, but it jumped away soon.
```
macro iter 1 (15 JK  4 micro), CASSCF E = -75.4844144116585  dE = -0.0024025259  S^2 = 0.0000000
               |grad[o]|=0.0817  |grad[c]|= None  |ddm|=0.587
--
macro iter 2 (9 JK  4 micro), CASSCF E = -75.4844628107864  dE = -4.8399128e-05  S^2 = 0.0000000
               |grad[o]|=0.029  |grad[c]|= None  |ddm|=0.442
--
macro iter 3 (12 JK  4 micro), CASSCF E = -75.4820358288044  dE = 0.002426982  S^2 = 0.0000000
               |grad[o]|=0.0296  |grad[c]|= None  |ddm|= 1.09
--
macro iter 4 (21 JK  4 micro), CASSCF E = -75.4822614648497  dE = -0.00022563605  S^2 = 0.0000000
               |grad[o]|=0.0629  |grad[c]|= None  |ddm|= 1.49
--
macro iter 5 (20 JK  4 micro), CASSCF E = -75.480513680048  dE = 0.0017477848  S^2 = 0.0000000
               |grad[o]|=0.0594  |grad[c]|= None  |ddm|= 1.68
--
macro iter 6 (20 JK  4 micro), CASSCF E = -75.4832984933388  dE = -0.0027848133  S^2 = 0.0000000
               |grad[o]|=0.0671  |grad[c]|= None  |ddm|=  1.3
```
I've tried adjusting stepsize and max_cycle_micro, which makes the condition a little better but still unconverged.

**Comment by bogdanoff** [comment]
There are problems in this issue:
1) no convergence in the case of no symmetry enforced.
2) slow convergence of state-specific calculation with symmetry

Problem 1) is fundamental and can't be solved, as there is a root flipping between state 6 and degenerate states 4 and 5. Once orbitals are optimized for the state 6 (`22022000`), its energy goes below states 4 and 5, and it becomes state 4, while the optimization continues for the new state 6, which is former state 5. This can be remedied by use of more complex state-averaging (`weights=[0.0, 0.0, 0.0, 0.15, 0.15, 0.7]`) or by implementing the root tracing based on the wavefunction.

Problem 2) is technical and related to loose default trust region thresholds. With `mc2.ah_grad_trust_region = 1.0` the state-specific calculation with symmetry converges in just 4 iterations. Are there any drawback of reducing the trust region thresholds?

**Comment by bogdanoff** [comment]
I don't think, that `follow_state=True` option is for root tracing, it is there for the stability of Davidson solver.

**Comment by verena-neufeld** [comment]
Hi @hebrewsnabla , thanks for your question. Has it been resolved now?

**Comment by hebrewsnabla** [comment]
Yes.
