### ISSUE TITLE
Inconsistent spin and electron number in KUHF/KUKS

### ISSUE THREAD

**Issue by awhite862** [pyscf/pyscf#1178]
KUHF for ferromagnetic systems is inconsistent in its treatment of electron number and spin. For example, at `kuhf.py:395`

    cell = self.cell
    nkpts = len(self.kpts)
    ne = cell.tot_electrons(nkpts)
    nalpha = (ne + cell.spin) // 2
    nbeta = nalpha - cell.spin

The number of electrons is the total number of electrons in the BvK supercell associated with the k-point calculation, but the spin is the spin of the primitive cell. In practice this issue can be bypassed by setting the spin of the `cell` to be equal to the desired spin of the as-yet-unspecified supercell, but then the attributes of the the `cell` object will be inconsistent.

**Comment by Majokux** [comment]
Yes this is confusing - You have to set the spin to the supercell value, but the k-points are not an attribute of the cell object itself (arguably they could be...). This then will still print you a warning `Electron number %d and spin %d are not consistent in unit cell\n' % (ne, self.spin))`, but the calculation will still run.

The biggest issue with this is that unaware users will possible converge solutions with the wrong symmetry, without realizing.
For example, someone may calculate a 2D system with an odd number of electrons in the unit cell.
For a Gamma-point calculation, one may use `cell.spin = 1`.
If they performed a 2x2 k-point sampling instead, the calculation cannot run, and the user will realized that something is wrong
(they need to set `cell.spin = 4`)
However, if they went straight to a 3x3 sampling, the calculation will run with `cell.spin = 1` and possibly converge,
not realizing that this is not the (probably) intended `spin = 9` solution.
