### ISSUE TITLE
Missing SPHERIC_GTO_PARITY_ODD entries for l-functions and higher

### ISSUE THREAD

**Issue by glowthrower** [pyscf/pyscf#1181]
I'm trying to run some calculations with an octuple-zeta basis set, which contains functions with angular momentum up to and including 8 (i.e. l-functions, if we follow the sometimes-convention of skipping j and enumerating as s, p, d, f, g, h, i, k, l). Point-group symmetry would be highly desirable for these calculations, but I'm seeing a crash whenever I try to enable it.

The issue seems to be that there is no appropriate entry in [`pyscf.symm.params.SPHERIC_GTO_PARITY_ODD`](https://github.com/pyscf/pyscf/blob/77802c036da043e18ac900c86bd52b37c06160b3/pyscf/symm/param.py#L174-L199), which only supports up to what I know as k-functions (but labeled j in the comments, so I guess there is some disagreement on naming conventions :wink: ).

If someone has time, would it be possible to add these entries for functions with angular momentum 9, and possibly 10 and/or 11? Thanks very much in advance!

**Comment by susilehtola** [comment]
The table should be extended to `L=15` which I believe is the maximum order supported in PySCF at the moment. I would imagine that the array could be generated automatically...? The array appears to just document the partial inversion symmetry of the solid harmonics.

**Comment by susilehtola** [comment]
The connection between the `(l,m)` indexing and the cartesian components has been discussed by Schlegel and Frisch in [Int. J. Quantum Chem. 54, 83 (1995)](https://doi.org/10.1002/qua.560540202) and the equations are also shown in in https://en.wikipedia.org/wiki/Solid_harmonics#Real_form. It should be quite straightforward to pick out the parity with respect to x, y, and z from these equations.

**Comment by glowthrower** [comment]
Actually, while it's under discussion, it looks like [`pyscf.symm.basis._SO3_SYMB2ID`](https://github.com/pyscf/pyscf/blob/1de8c145abb3e1a7392df9118e8062e6fe6bde00/pyscf/symm/basis.py#L249) needs to be updated as well.

**Comment by ndattani** [comment]
@glowthrower is everything working now? I just created an issue in the `qcint` repository because I'm still getting errors with an 8z basis set for the O atom. Are you using `qcint` or `libcint`?
