### ISSUE TITLE
PySCF 2.0 eval_xc segfault

### ISSUE THREAD

**Issue by mbarbry** [pyscf/pyscf#1183]
Dear PySCF developers,

After updating PySCF to version 2.0, I'm getting a segfault in the eval_xc function

Here you can see a screenshot of the error (left panel with PySCF version 2.0) while the right panel calls the same script with PySCF 1.7.6 works fine. (Each panel uses a different conda environment)

![image](https://user-images.githubusercontent.com/14218658/152520439-def9bf9f-bbbf-434f-af7f-96ddf207ad38.png)

Both PySCF installations were done via conda in separate environments

    conda install -c pyscf pyscf=1.7.6

and

    conda install -c pyscf pyscf=2.0

The script I used is the following (attached with the required inputs, [test_failing_eval_xc.zip](https://github.com/pyscf/pyscf/files/8002590/test_failing_eval_xc.zip) )

    import numpy as np
    import pyscf
    import pyscf.dft.libxc as libxc

    rho = np.load("rho_20220204.npy")
    xc_code = "LDA,PZ"
    spin = 0
    deriv = 2

    print("pyscf version: ", pyscf.__version__)
    print("pyscf path: ", pyscf.__path__)

    try:
        print("libxc version: ", libxc.libxc_version())
    except:
        print("libxc version not available via pyscf")

    exc, vxc, fxc, kxc = libxc.eval_xc(xc_code, rho, spin=spin, deriv=deriv)

    print("succeed")

Since the function `libxc_version` is not implemented in version 1.7.6, I looked at the libxc library installed in the environment (see screenshot). It seems it uses libxc version 5.3.4

Any idea what could bring such segfault in PySCF 2.0? I guess libxc library is at blame here.

**Comment by jamesETsmith** [comment]
Hi @mbarbry, I tried your example with pyscf 2.0.1 (and libxc 5.1.7) and things work without a problem. Have you tried building from source?

**Comment by susilehtola** [comment]
"Illegal instruction" usually means that the library has been built for a specific processor architecture which doesn't match where it is run. Where did you get libxc?

**Comment by susilehtola** [comment]
Sounds like the conda package has been compiled wrong. File a ticket with the conda package.

**Comment by mbarbry** [comment]
Indeed, installing from source solves the issue

![image](https://user-images.githubusercontent.com/14218658/152633547-d8bbffba-0c9c-4ab4-aeb1-c23a98c78a26.png)


Thanks a lot for your help. I will fill a ticket to the conda package.
