### ISSUE TITLE
Recovering the shell of any element of a Cartesian basis set as a triplet

### ISSUE THREAD

**Issue by ilygatsika** [pyscf/pyscf#1184]
Dear all,

I was wondering if there is a more direct way to obtain the shell of any basis function in triplet format (lx,ly,lz), than the one described below. I'm interested in basis sets of (generally contracted) Cartesian GTOs. My current code to achieve this is

```
from pyscf import gto
atom = 'H 0 0 0'
basis = 'aug-cc-pvtz'
mol = gto.M(atom=atom, basis=basis, spin=1, cart=True)
sid = 0
for ib in range(mol.nbas):
    
    # obtain angular momentum, exp and coef
    l = mol.bas_angular(ib)
    es = mol.bas_exp(ib)
    cs = mol._libcint_ctr_coeff(ib)

    # obtain shell
    ia = mol.bas_atom(ib)
    nb_ch = (l+1)*(l+2)//2
    for i_cntr in range(nb_ch):
        k = sid + i_cntr
        shell = mol.cart_labels(ia)[k]
        print(k,shell)
    sid += nb_ch
```
from where the shell of the k-basis function is recovered in str-of-xyz-notation. The next step (not included in the above code) is to convert to the desired format, for example dyy is (0,2,0), etc (we can define a dictionary that maps every xyz notation to its triplet).

Thank you in advance for any suggestions.

**Comment by sunqm** [comment]
Maybe you just need to cache the triplet notation first similar to this https://github.com/pyscf/pyscf/blob/master/pyscf/gto/mole.py#L1548 , then indexing the notation according to the angular momentum of specific shell Id. I guess it does not need any new methods of Mole class .
