### ISSUE TITLE
Large Scale CCSD Calculation Running Out of Memory 

### ISSUE THREAD

**Issue by ieva-liep** [pyscf/pyscf#1188]
I am trying to run large scale CCSD calculations with nmo = 678 orbitals (cc-pvqz basis set), but the calculation is crashing with the following error message: 'No space left on device'

It seems based in Table I of https://arxiv.org/pdf/2002.12531.pdf that PySCF can do CCSD calculations with many more orbitals.
Can anyone help me understand the error message above, and run large-scale CCSD calculations?

Thank you very much in advance for your time and help, 
Ieva

**Comment by verena-neufeld** [comment]
Hi Ieva, how many active electrons do you have in that system?

**Comment by tberkel** [comment]
The feasible system sizes also depend on your resources. You're probably
running out of space on disk. The integrals for CCSD with 678 orbitals
might need almost 1 TB of disk space.

**Comment by ieva-liep** [comment]
Thank you very much for your responses! I am trying to simulate a 52 electron system. The disk space is going at about 1GB/sec

**Comment by verena-neufeld** [comment]
Thanks for that info! I might be mistaken but I believe what is meant is that you need enough space on your disk to save all the integrals for example, not the speed of saving, but I might have completely missed your point?

**Comment by ieva-liep** [comment]
I just learned that my machine has more RAM right now (6TB) than disk space. Is there a way to tell pyscf not to use temp files, and to use memory instead?

**Comment by verena-neufeld** [comment]
I'd recommend telling pyscf that you have a lot of memory available by setting `max_memory` (e.g. see `gto/00-input_mole.py` in examples and `https://pyscf.org/code-rule.html?highlight=max_memory` in documentation). There is also the `incore_anyway` keyword for coupled cluster calculations (e.g. see `cc/15-incore_mo_ccsd_t.py` in examples). 
Does this work?

**Comment by sunqm** [comment]
You can try the AO-direct algorithm `cc.direct = True`, for example
https://github.com/pyscf/pyscf/blob/master/examples/cc/10-ao_direct_ccsd.py
