### ISSUE TITLE
UKS multithreaded instability

### ISSUE THREAD

**Issue by jackweber1296** [pyscf/pyscf#1189]
I think this is an install-dependent issue, but it also seems technical on the PySCF side so I'm posting it here. 

I've been trying to converge some DFT calculations on the expanse cluster, and have run into some issues with instabilities on the order of 10^4 Ha whenever I use multiple threads, but not one thread:

$ grep delta_E output_multithreads | tail -n 5
cycle= 496 E= -11204.5830156062  delta_E= -1.11e+04  |g|= 1.12  |ddm|= 5.09
cycle= 497 E= -2082.10137962068  delta_E= 9.12e+03  |g|=    5  |ddm|= 12.4
cycle= 498 E= -14124.085430189  delta_E= -1.2e+04  |g|= 1.37  |ddm|= 28.8
cycle= 499 E= -123.357030392281  delta_E= 1.4e+04  |g|= 1.26  |ddm|=   25
cycle= 500 E= -2506.89860727146  delta_E= -2.38e+03  |g|= 0.999  |ddm|= 13.7

$ grep delta_E output_1thread | tail -n 5
cycle= 4 E= -40.4495128365791  delta_E= -1.07e-06  |g|= 0.000221  |ddm|= 0.00195
cycle= 5 E= -40.4495128858331  delta_E= -4.93e-08  |g|= 6.18e-05  |ddm|= 0.000355
cycle= 6 E= -40.4495128914606  delta_E= -5.63e-09  |g|= 6.89e-06  |ddm|= 0.000159
cycle= 7 E= -40.4495128915077  delta_E= -4.72e-11  |g|= 6.75e-07  |ddm|= 1.22e-05
Extra cycle  E= -40.4495128915083  delta_E= -5.97e-13  |g|= 1.77e-07  |ddm|= 1.15e-06

This is true for the PySCF that they installed, v 1.7.3, and the git master fd83d9e which I compiled myself.

I tested a small system out on my local computer, and it seems that multithreading doesn't have the same issue there. Does this look familiar to anyone? It only happens for DFT; UHF, RHF, and CASSCF converge just fine, so maybe it's related to something that is only called for DFT? I reached out to the cluster maintenance as well.

Thanks,
Jack

**Comment by jamesETsmith** [comment]
@jackweber1296, thanks for letting us know. Could you share a minimum working example that reproduces your error?

**Comment by jackweber1296** [comment]
It looks like the issue was me just oversubscribing threads! Thanks anyways :)
