### ISSUE TITLE
Hydrogen mo_occ

### ISSUE THREAD

**Issue by frobnitzem** [pyscf/pyscf#1190]
When I run ROKS calculations with hydrogen, the resulting `mf.mo_occ` and `mf.mo_coeff` attributes have a different shape than with other elements.

I would expect this result to depend on whether I use RKS, ROKS, or UKS, but not on changing the element.
I can't tell what the expected behavior of ROKS is supposed to be -- separate occupancies per spin, or a combined sum of occupancies.  However one of the following is an error:

```
>>> from pyscf import gto, dft, scf
>>> dft.ROKS(gto.M(atom=[('H',0,0,0)], spin=1)).run().mo_occ
converged SCF energy = -0.435670232836857  <S^2> = 0.75  2S+1 = 2
array([[1.],
       [0.]])
>>> dft.ROKS(gto.M(atom=[('Li',0,0,0)], spin=1)).run().mo_occ
converged SCF energy = -7.22130164963362
NPArrayWithTag([2., 1., 0., 0., 0.])
```

Here's a list of output shapes across a range of methods:
```
>>> v = []
>>> for elem in ["H", "Li"]:
...   for method in [scf.HF, scf.RHF, scf.UHF, dft.KS, dft.RKS, dft.ROKS, dft.UKS]:
...     v.append(method(gto.M(atom=[(elem,0,0,0)], spin=1)).run().mo_occ.shape)
... 
>>> v[:7]
[(1,), (1,), (2, 1), (2, 1), (2, 1), (2, 1), (2, 1)]
# HF   RHF   UHF     KS      RKS     ROKS    UKS
>>> v[7:]
[(2, 5), (5,), (2, 5), (2, 5), (5,), (5,), (2, 5)]
# HF     RHF   UHF     KS      RKS   ROKS  UKS
```

**Comment by sunqm** [comment]
Fixed in PR #1270
