### ISSUE TITLE
About the efficiency of tblis from PySCF

### ISSUE THREAD

**Issue by Lancashire3000** [pyscf/pyscf#1192]
Hi,

  I discussed the performance about `tblis` at `opt-einsum` github. The developer suggested a benchmark of tensor contraction, to check `PySCF`'s `tblis` implementation: "abcd,cdef->abef" and "acbd,cdef->abef".

  It seems the result is not as expected. 
https://github.com/dgasmith/opt_einsum/issues/180

  Could it be an issue in my installation of `tblis`?

**Comment by sunqm** [comment]
opt-einsum calls numpy.tensordot by default. numpy.tensordot uses openblas dgemm function for tensor operation. It looks reasonable and acceptable to me that TBLIS delivers about 90% of openblas performance.
