### ISSUE TITLE
quite large memory requiement for G0W0 calculation with screened functionals

### ISSUE THREAD

**Issue by LinyaoZhang** [pyscf/pyscf#1193]
I am trying to do G0W0 calculations for crystal with different initial orbitals. But, I get an numpy.core._exceptions.MemoryError when using screened functionals as initial orbital. It seems the G0W0 calculations for crystals with these range-separated functionals requires huge memory, but this does not happen for global-hybrid functionals.

I am wondering is it possible to use screened functionals for crystal G0W0 calculations with less memory?

Thank you!
Linyao

The following are the input and error message

`from pyscf.pbc.tools import pyscf_ase
from pyscf.pbc import gto, dft, df
from pyscf.pbc.gw.krgw_ac import KRGWAC
from ase.build import bulk

c = bulk('AlP', 'zincblende', a=5.451)
nk = [4, 4, 4]

cell = gto.Cell()
cell.atom = pyscf_ase.ase_atoms_to_pyscf(c)
cell.a = c.cell
cell.basis = 'cc-pvtz'
cell.verbose = 5
cell.max_memory = 120000
cell.output = 'AlP.log'
cell.build()

kpts = cell.make_kpts(nk, scaled_center=[0,0,0])
gdf = df.GDF(cell, kpts)

mf = dft.KRKS(cell, kpts).density_fit()
mf.with_df = gdf
mf.with_df.auxbasis = "cc-pvtz-ri"
mf.xc = 'HYB_GGA_XC_HSE06'
mf.grids.level = 5
mf.kernel()

gw = KRGWAC(mf)
gw.linearized = False
gw.fc = False
nocc = gw.nocc
gw.kernel(orbs=range(0, nocc + 3))
print(gw.mo_energy)`

`WARNING!
  Very diffused basis functions are found in the basis set. They may lead to severe
  linear dependence and numerical instability.  You can set  cell.exp_to_discard=0.1
  to remove the diffused Gaussians whose exponents are less than 0.1.

output file: AlP.log
Traceback (most recent call last):
  File "AlP.py", line 26, in <module>
    mf.kernel()
  File "xxx/pyscf/pyscf/lib/misc.py", line 638, in aliased_fn
    return getattr(self, fname)(*args, **kwargs)
  File "xxx/pyscf/pyscf/scf/hf.py", line 1667, in scf
    kernel(self, self.conv_tol, self.conv_tol_grad,
  File "xxx/pyscf/pyscf/scf/hf.py", line 127, in kernel
    vhf = mf.get_veff(mol, dm)
  File "xxx/pyscf/pyscf/pbc/dft/krks.py", line 104, in get_veff
    vklr = ks.get_k(cell, dm, hermi, kpts, kpts_band, omega=omega)
  File "xxx/pyscf/pyscf/pbc/scf/khf.py", line 625, in get_k
    return self.get_jk(cell, dm_kpts, hermi, kpts, kpts_band,
  File "xxx/pyscf/pyscf/pbc/scf/khf.py", line 638, in get_jk
    vj, vk = self.with_df.get_jk(dm_kpts, hermi, kpts, kpts_band,
  File "xxx/pyscf/pyscf/pbc/df/df.py", line 731, in get_jk
    return _sub_df_jk_(mydf, dm, hermi, kpts, kpts_band,
  File "xxx/pyscf/pyscf/pbc/df/aft.py", line 628, in _sub_df_jk_
    return rsh_df.get_jk(dm, hermi, kpts, kpts_band, with_j, with_k,
  File "xxx/pyscf/pyscf/pbc/df/aft.py", line 523, in get_jk
    vk = aft_jk.get_k_kpts(self, dm, hermi, kpts, kpts_band, exxdiv)
  File "xxx/pyscf/pyscf/pbc/df/aft_jk.py", line 169, in get_k_kpts
    make_kpt(kptj-kpti)
  File "xxx/pyscf/pyscf/pbc/df/aft_jk.py", line 158, in make_kpt
    vkcoulG = mydf.weighted_coulG(kpt, exxdiv, mesh)
  File "xxx/pyscf/pyscf/pbc/df/aft.py", line 285, in weighted_coulG
    coulG = tools.get_coulG(cell, kpt, exx, mydf, mesh, Gv)
  File "xxx/pyscf/pyscf/pbc/tools/pbc.py", line 359, in get_coulG
    coulG[G0_idx] += Nk*cell.vol*madelung(cell, kpts)
  File "xxx/pyscf/pyscf/pbc/tools/pbc.py", line 461, in madelung
    Gv, Gvbase, weights = ecell.get_Gv_weights(ecell.mesh)
  File "xxx/pyscf/pyscf/pbc/gto/cell.py", line 644, in get_Gv_weights
    Gv = np.dot(lib.cartesian_prod(Gvbase), b)
  File "xxx/pyscf/pyscf/lib/numpy_helper.py", line 945, in cartesian_prod
    out = numpy.ndarray(dims, dtype, buffer=out)
numpy.core._exceptions.MemoryError: Unable to allocate 12.8 TiB for an array with shape (3, 8376, 8376, 8376) and data type float64`

**Comment by fishjojo** [comment]
You may try using pseudo potentials and the corresponding basis sets. As you are using an all-electron basis set, the default kinetic energy cutoff will give a very big uniform grid.

**Comment by LinyaoZhang** [comment]
> You may try using pseudo potentials and the corresponding basis sets. As you are using an all-electron basis set, the default kinetic energy cutoff will give a very big uniform grid.

Does this also apply for global hybrid functional? Currently only the screened functionals show this problem.
Thank, you.

**Comment by gkc1000** [comment]
This happens because it is switching to a different kind of DF with screened functionals that should be more efficient computationally, but in this basis set is very memory intensive. Try setting

LONGRANGE_AFT_TURNOVER_THRESHOLD=0.0

see line 724 in pbc/df/df.py

**Comment by sunqm** [comment]
It might need a new implementation of outcore or runtime integral generation algorihtms. @zhutianyu1991 how do you think it can be studied in the near future?

**Comment by zhutianyu1991** [comment]
@zhcui and I are working on an outcore version of current GW codes, which will reduce the memory requirement from O(N_k N_AO^2 N_aux) to O(N_AO^2 N_aux). Not sure if this can fix the range-separated functional issues.

**Comment by verena-neufeld** [comment]
Hi @LinyaoZhang , thanks for your question. Just to keep these issues here organized, are there any updates, @zhutianyu1991 ?

**Comment by simonganne01** [comment]
> @zhcui and I are working on an outcore version of current GW codes, which will reduce the memory requirement from O(N_k N_AO^2 N_aux) to O(N_AO^2 N_aux). Not sure if this can fix the range-separated functional issues. Current GW implementations only support GDF integrals (as it's a density-fitting GW algorithm). It seems range-separated functionals would also require AFTDF. I'm not sure how feasible it is to adapt current codes to AFTDF.

What is the specific reason GW cannot be used with other auxiliary basis functions like plane waves or mixed?

**Comment by sunqm** [comment]
I guess there is no theoretical problem, just no one currently working on using different fitting functions. Please feel free to reopen the issue if you want to continue the discussion.
