### ISSUE TITLE
HDF5 issue for ccsd_t_lambda?

### ISSUE THREAD

**Issue by nesquik91** [pyscf/pyscf#1194]
Dear developers,

Hi, I'm trying to generate uccsd(t) density matrix with the ccsd_t_lambda module but seems like a bigger-sized eri with HDF5 doesn't have .conj().
I think this issue is very similar to this one >> https://github.com/pyscf/pyscf/issues/113.

My full input is like below.

from pyscf import gto, scf, dft, mp, ao2mo, cc, lib
from pyscf.tools import molden, cubegen
from pyscf.cc import uccsd_t_lambda as ccsd_t_lambda
from pyscf.cc import uccsd_t_rdm    as ccsd_t_rdm
from pyscf.cc import uccsd_t

lib.num_threads(40)

# 0.911, 2.100 Angs.

mol = gto.M(
verbose = 0,
atom = '''
Si      0.0000  0.0000  0.0000
H       0.0000  0.0000  -1.5141
H       0.0000  1.5132  0.0528
''',
charge     = 0,
spin       = 2,
basis      = 'aug-cc-pvqz',
max_memory = 10000,
)

myhf = scf.UHF(mol)
myhf.conv_tol = 1e-8
Ehf = myhf.kernel()
Dhf = myhf.make_rdm1()

mycc = cc.UCCSD(myhf)
mycc.kernel()

eris = mycc.ao2mo()
conv, l1, l2 = ccsd_t_lambda.kernel(mycc, eris, mycc.t1, mycc.t2)
Dccsdt_mo = ccsd_t_rdm.make_rdm1(mycc, mycc.t1, mycc.t2, l1, l2, eris=eris)

**Comment by sunqm** [comment]
Fixed in PR #1269
