### ISSUE TITLE
Different results comes out by RHF and SCF using customizing hamiltonian method.

### ISSUE THREAD

**Issue by beimojiguang** [pyscf/pyscf#1200]
I tried to test the `scf` module by following the example in `pyscf/examples/scf/40-customizing_hamiltonian.py`.
The testing molecule is C ring built by following code:
```
import pyscf
from pyscf import gto
def C_ring(bd, C_num):
    theta = 2 * np.pi / C_num
    R = (bd / 2.0) / math.sin(theta / 2)
    C_ring = [('C', (R * math.cos(i * theta), R * math.sin(i * theta), 0)) for i in range(C_num)]

    print(C_ring)
    mol = gto.Mole()  
    mol.atom = C_ring 
    mol.basis = "ccpvdz"  
    mol.charge = 0 
    mol.spin = 0 
    mol.build() 

    return mol
```
The normal RHF has been done by following code:
```
mol = C_ring(1.5, 20)
mf = mol.RHF()
mf.kernel() # mf.e_tot = -755.54924848588
print(mf.converged) # True
```
And the SCF using customizing hamiltonian gives a different result with following code:
```
mol = C_ring(1.5, 20)
mol_fake = gto.Mole()
mol_fake.build(verbose=0)
mol_fake.nelectron = mol.nelectron

eri = mol.intor('int2e', aosym='s4')
oei = mol.intor('cint1e_kin_sph') + mol.intor('cint1e_nuc_sph')
ovlp = mol.intor('cint1e_ovlp_sph')

mf2 = scf.RHF(mol_fake)
mf2.get_hcore = lambda *args: oei
mf2.get_ovlp = lambda *args: ovlp
mf2._eri = eri
mf2.init_guess = '1e'
mf2.kernel()
print(mf2.converged) # True
print(mf2.e_tot + mol.energy_nuc()) # -755.3813226867234
```
But, if I only feed `eri` to `mf2._eri` and without feeding `oei` and `ovlp`, the result will be the same with the first situation:
```
mol = C_ring(1.5, 20)

eri = mol.intor('int2e', aosym='s4')

mf3 = scf.RHF(mol)
mf3._eri = eri
mf3.kernel()
print(mf3.converged) # True
print(mf3.e_tot) # -755.5492484858659
```

Why?

I am looking forward to your reply~！

Best wish.

**Comment by Majokux** [comment]
Have you tried starting the first calculation with `init_guess = '1e'`, as well?
A C20-ring has very high symmetry and high symmetry systems often have a lot of extremal- and saddle points in their optimization surface, such that you can easily converge to a different (not minimal energy!) solution. Second order optimization, using `mf = mf.newton()` can potentially help, as well as a good starting guess and working in a symmetry adapted basis.

**Comment by hebrewsnabla** [comment]
1. starting the first calculation with init_guess = '1e' will produce wrong energy, also, as stated by Max.
2. one workaround is to read an init guess from previous calculation, like
```
mol = C_ring(1.5, 20)
mol.verbose = 4
mf = mol.RHF()
mf.kernel()

mol_fake = gto.Mole()
mol_fake.build(verbose=4)
mol_fake.nelectron = mol.nelectron

eri = mol.intor('int2e', aosym='s4')
oei = mol.intor('cint1e_kin_sph') + mol.intor('cint1e_nuc_sph')
ovlp = mol.intor('cint1e_ovlp_sph')

mf2 = scf.RHF(mol_fake)
mf2.get_hcore = lambda *args: oei
mf2.get_ovlp = lambda *args: ovlp
mf2.energy_nuc = mol.energy_nuc
mf2._eri = eri
mf2.kernel(dm0=mf.make_rdm1())
```
P.S. i suggest setting `mf2.energy_nuc = mol.energy_nuc`, thus we don't need to manually add that into e_tot.
