### ISSUE TITLE
Nonstandard point-group symmetry labels for C2v

### ISSUE THREAD

**Issue by dariopicozzi** [pyscf/pyscf#1201]
I have the following code to print the symmetry labels for the water molecule (C2v point group) in minimal basis:

```
from pyscf import gto, scf, symm

mol = gto.M(atom = 'O 0 0 0.1197; H 0 0.7616 -0.4786; H 0 -0.7616 -0.4786', symmetry = True, basis = 'sto-3g')
mf = scf.RHF(mol)
mf.kernel()
label_orb_symm = symm.label_orb_symm(mol, mol.irrep_name, mol.symm_orb, mf.mo_coeff)
print(label_orb_symm)
```

It outputs the labels as:
```
['A1' 'A1' 'B1' 'A1' 'B2' 'A1' 'B1']
```

The standard convention (see [here](http://iopenshell.usc.edu/resources/howto/symmetry)) is that the x-axis is the one perpendicular to the plane of the molecule, and that the B1 representation is symmetric with respect to the reflection σ(xz) and antisymmetric with respect to  σ(yz) (and the opposite for B2). 

This would give:
```
['A1' 'A1' 'B2' 'A1' 'B1' 'A1' 'B2']
```
(i.e. with the B1 and B2 labels swapped with respect to the code output)

Would it be possible to align the labelling convention used in PySCF to the standard convention?

**Comment by bogdanoff** [comment]
I believe PySCF just searches for the highest possible point group and uses the axes framework in could find.
#1209 makes  possible to keep user-defined axes if you define the expected point group, `symmetry = "C2v"` in your case.
