### ISSUE TITLE
active space - 1&2 electron integrals

### ISSUE THREAD

**Issue by schusteritsch** [pyscf/pyscf#1202]
This is a question about how to do something in PySCF not a code issue:

I am trying to get the 1 and 2 electron integrals based on an active space from a Hartree Fock (HF) calculation. I am able to do this without active space for all orbitals using fcidum:

```
mol = gto.Mole(
    verbose=4,
    atom='''
C    0.000000000000     1.398696930758     0.000000000000
C    0.000000000000    -1.398696930758     0.000000000000
C    1.211265339156     0.699329968382     0.000000000000
C    1.211265339156    -0.699329968382     0.000000000000
C   -1.211265339156     0.699329968382     0.000000000000
C   -1.211265339156    -0.699329968382     0.000000000000
H    0.000000000000     2.491406946734     0.000000000000
H    0.000000000000    -2.491406946734     0.000000000000
H    2.157597486829     1.245660462400     0.000000000000
H    2.157597486829    -1.245660462400     0.000000000000
H   -2.157597486829     1.245660462400     0.000000000000
H   -2.157597486829    -1.245660462400     0.000000000000''',
    basis='ccpvdz',
    symmetry='D2h')
mol.build()
mf = scf.RHF(mol)
mf.kernel()
fcidump.from_scf(mf, 'fcidump.all')
```

But I haven't been able to figure out how to do this for only a subset of orbitals in the active space?

I tried something based on just selecting some orbitals and then using fcidump.from_mo - but this then just cuts the integrals:

```
pz_pop = mo_mapping.mo_comps('C 2pz', mol, mf.mo_coeff)
cas_list = pz_pop.argsort()[-6:]
mo_act=mf.mo_coeff[:, cas_list[cas_list.argsort()]]
fcidump.from_mo(mol, 'fcidump.CAS', mo_act)
```

However I am trying to not just discard the inactive orbitals but to get it to appropriately recalculate the 1 electron integrals of the active space (e.g. like this http://pybest.fizyka.umk.pl/pybest-v1.0.2/user_hamiltonian_activespace.html#dumping-the-active-space-hamiltonian-to-disk) - is there in-built functionality in PySCF to do this based on HF calculations or would I need to recalculate this based on the 2 body terms?

Any help appreciated.

**Comment by jamesETsmith** [comment]
Hi @schusteritsch, here are some steps that should help you accomplish what you're looking for.

## Step-by-step
You can create an `mcscf.CASCI` object with the active space you want, then use the `get_h1eff` member function to calculated the effective 1-body integrals for your active space.

https://github.com/pyscf/pyscf/blob/885d9ad641cec9d633cc661e3ec54165624f258f/pyscf/mcscf/casci.py#L884-L885

Once you have that, you can calculate the 2-body integrals for your active space with the `get_h2eff` member function.

https://github.com/pyscf/pyscf/blob/885d9ad641cec9d633cc661e3ec54165624f258f/pyscf/mcscf/casci.py#L853-L854

Then you can write them to an fcidump file with `fcidump.from_integrals`

https://github.com/pyscf/pyscf/blob/885d9ad641cec9d633cc661e3ec54165624f258f/pyscf/tools/fcidump.py#L150-L152

## Pseudo Code

Combined, it should look something like this:
```python
mc = mcscf.CASCI(mf, ncas, nelecas)
fcidump.from_integrals("cas_integrals.fcidump", mc.get_h1eff(), mc.get_h2eff(), mc.ncas, mc.nelecas)
```

## Things to keep in mind
* Note that sometimes mc.nelecas is a tuple. If it is, make sure you pass an integer to `fcidump.from_integrals` not the tuple.
* This doesn't require actually running a CASCI calculation (i.e. we have't run `mc.kernel()`) we're just using some of the tools of the CASCI class.

Hope this helps!

**Comment by schusteritsch** [comment]
Hi @jamesETsmith, thank you very much for this! I hadn't realized you could do this without running CASCI.

I tried this using the additional change you suggest about ``mc.nelacas`` being a tuple to read:
```
mc = mcscf.CASCI(myhf, ncas, nelecas)
fcidump.from_integrals("cas_integrals.fcidump", mc.get_h1eff()[0], mc.get_h2eff(), mc.ncas, mc.nelecas[0])
```
I also notice there is an additional argument in fcidump.from_integrals called ``nuc`` - I am assuming this is to give it the new core energy, so I actually used 
```
fcidump.from_integrals("cas_integrals.fcidump", mc.get_h1eff()[0], mc.get_h2eff(), mc.ncas, mc.nelecas[0], nuc=mc.get_h1eff()[1])
```

This seems to indeed recalculate the 1-electron integrals as well as the core energy. What confuses me a little bit is that it also seems to recalculate the 2-electron integrals in comparison to just  outputting all from:
```
fcidump.from_scf(mf, 'fcidump.all')
```

I had thought that the 2 electron integrals should remain the same, or is there a basis change happening that I don't completely follow?

I tried to see what ``fcidump.from_scf(mf, 'fcidump.all')`` does vs using ``get_h2eff()``, but in the end they both seem to call ``ao2mo.full()``. It's likely I am getting my thinking/maths wrong somewhere...?

Many thanks for the help!

**Comment by schusteritsch** [comment]
Hi @jamesETsmith - thanks for the reply! And sorry for the confusion - I made a mistake comparing the output for the full space with that of the smaller active space... they are indeed the same... human error, sorry about that. It all seems to work fine now and I corrected my previous comment/question.

**Comment by jamesETsmith** [comment]
@schusteritsch, glad things are working now!

**Comment by buttercutter** [comment]
> ```python
> mc = mcscf.CASCI(mf, ncas, nelecas)
> fcidump.from_integrals("cas_integrals.fcidump", mc.get_h1eff(), mc.get_h2eff(), mc.ncas, mc.nelecas)
> ```

@jamesETsmith What should be passed into the variable `ncas` and `nelecas` respectively for `mc = mcscf.CASCI(mf, ncas, nelecas)` ?

**Comment by jamesETsmith** [comment]
@buttercutter, `ncas` is the number of active space orbitals and `nelecas` is the number of active space electrons. `ncas` is an integer and `nelecas` can be an integer or a tuple.

https://github.com/pyscf/pyscf/blob/0df2ead0cc9b80a1b8bf0f26b5d1755baf1a472f/pyscf/mcscf/casci.py#L683-L686

For more help choosing an active space, check out the [MCSCF docs here.](https://pyscf.org/user/mcscf.html#picking-an-active-space)

We also have quite a few examples for active space calculations, you can check them out [here](https://github.com/pyscf/pyscf/tree/master/examples/mcscf).

**Comment by emamars95** [comment]
@jamesETsmith, I have a quick follow up on this thread. How the h1eff and h2eff are computed in a pbc calculation? 

I have used, as effective one-particle term the following expression: 
h'_ij = h_ij + sum_v 2 * g_vvij - g_vjiv 
where i, j are active indices and v is core index of spatial orbitals over which I sum the Coulomb (g_vvij) and Exchange (g_vjiv) integrals. This works for non-PBC system, i.e. is equivalent to the implementation in PySCF. However, for PBC system, it differs from the results I get once I use the build-in function get_h1eff(). 

I have considered that, in my case, I extract the 1e and 2e integrals in AO basis as: 
mol.pbc_intor("int1e_kin") + mol.pbc_intor("int1e_nuc")
mol.intor('int2e', aosym='s1')
I may suspect that the int2e are wrong, which may give rises to the discrepancies between my method and the implementation in PySCF.
