### ISSUE TITLE
How to get matrix associated with generic second-quantization operator?

### ISSUE THREAD

**Issue by mariomotta** [pyscf/pyscf#1205]
Greetings,

The example
https://github.com/pyscf/pyscf/blob/master/examples/fci/15-FCI_hamiltonian.py
shows how to compute the matrix H(a,b) = <a|H|b> associated with the Hamiltonian H in a space of Slater determinants.
Is there an analogous command to obtain the matrix X(a,b) = <a|X|b> associated with a generic operator X,
such as the CCSD operator T (restricted, unrestricted, or generalized)?
One could use cre_* and des_* as in https://github.com/pyscf/pyscf/blob/master/examples/fci/31-apply_2nd_quantized_op.py
but this would be rather slow, and I would be grateful if a more efficient solution could be identified.

Thanks for the attention,
Mario

**Comment by gkc1000** [comment]
Other than using the cre_ and des_ functions, if it is a 1e or 2e operator and it is hermitian, then you can use contract_1e and contract_2e in the fci module. If the operator is not hermitian, e.g. T2, you can use the contract_1e and contract_2e functions in fci_slow.py, which do not assume the integrals are symmetric. See e.g. line 42 and line 66 in those files. Then e.g. you can set the integrals to be the T2 values. You will have to do this every Slater determinant, to get X|b> for { |b> }, then dot the results for { |a> }.

**Comment by sunqm** [comment]
https://github.com/pyscf/pyscf/blob/master/examples/fci/36-determinants_basis_matrix.py this is an example of computing matrix in determinant basis for a general operator X
