### ISSUE TITLE
Spatial2Spin for EOM-RCCSD?

### ISSUE THREAD

**Issue by gayverjr** [pyscf/pyscf#1208]
Hello,
I noticed that there are functions in [cc.addons](https://github.com/pyscf/pyscf/blob/1de8c145abb3e1a7392df9118e8062e6fe6bde00/pyscf/cc/addons.py#L19) and [eom_uccsd](https://github.com/pyscf/pyscf/blob/1de8c145abb3e1a7392df9118e8062e6fe6bde00/pyscf/cc/eom_uccsd.py#L78) for converting between spatial and spin orbital representations of coupled cluster amplitudes. The latter does not work with EOM-RCCSD amplitudes, at least out of the box. Is there a way one could hack it together to make it work? I know there is also EOM-GCCSD, which does things in the spin orbital representation, but it is quite a bit slower, and it would be nice to just make the conversion from EOM-RCCSD instead. Here is a snippet of my code:

```python
from pyscf import gto, scf, cc
from pyscf.cc import ccsd
from pyscf.cc.addons import spatial2spin,spin2spatial
from pyscf.cc.eom_uccsd import spatial2spin_ip,spatial2spin_ea

mol = gto.M(
            atom = '    N 0.0000000000 0.0000000000 0.548756750;\
            N 0.0000000000 0.0000000000 -0.548756750;',
            basis = 'cc-pvdz' )
mol.verbose = 4
mol.build()
mf = mol.RHF().run()

mycc = ccsd.CCSD(mf)
mycc.kernel()
t1 = mycc.t1
t2 = mycc.t2

t1_spin = spatial2spin(t1)
t2_spin = spatial2spin(t2)

nstates = 5
myeom = mycc.eomea_method()
e_r, r_eom = mycc.eaccsd(nroots=nstates)
e_l, l_eom = mycc.eaccsd(nroots=nstates,left=True)

r1,r2 = myeom.vector_to_amplitudes(r_eom[0],myeom.nmo,myeom.nocc)
#r1,r2 = spatial2spin_ea(r1,r2)
# yields ValueError: too many values to unpack (expected 2)
```

**Comment by sunqm** [comment]
In PR #1426 spatial2spin methods were added to all EOM objects. The required transformation can be obtained in two steps.
```
r1 = myeom.spatial2spin(r1)
r2 = myeom.spatial2spin(r2)
```
