### ISSUE TITLE
Fock matrix with localized molecular orbitals

### ISSUE THREAD

**Issue by DanielBajac** [pyscf/pyscf#1210]
Hi all,

I'm interested in calculating the Fock matrix with (previously localized) localized molecular orbitals. 
I'm gonna need the core Hamiltonian, but this is implemented for the AO basis only. 
Do you have idea of how can I calculate the core Hamiltonian for previously localized LMO (or any molecular orbitals)?
On the other hand, for the two electron part of the Fock matrix, I think I can use the "ao2mo" module ... Is this the best way to do it?

Thanks in advance,

Daniel

**Comment by tberkel** [comment]
Hi Daniel,

This is just a change of basis, which you can do with ***@***.***@C`, where
either:
- the columns of `C` are your localized MOs in terms of canonical MOs and
`fock` is a diagonal matrix of MO energies
- the columns of `C` are your localized MOs in terms of AOs and `fock` is
the fock matrix in the AO basis

**Comment by DanielBajac** [comment]
Hi Timothy, thank you for your fast answer. 
I'm glad to hear that it is just a change in basis. 
However, I don't fully understand your answer,  what do you mean with ***@***.***@C ? 

On the other hand, the LMO (e.g Pipek-Mezey, Boys, etc..) obtained by defect in the PySCF are in term of AOs?

**Comment by Majokux** [comment]
Hi Daniel,

The two ways Tim described are either:
1:
```
c_lo = Boys(mol).kernel(mf.mo_coeff).mo_coeff                          # LOs in terms of AOs
c_lo = np.linalg.multi_dot((mf.mo_coeff.T, mf.get_ovlp(), c_lo))       # LOs in terms of MOs
fock_lo = np.einsum('ix,i,iy->xy', c_lo, mf.mo_energy, c_lo)
```

2:
```
c_lo = Boys(mol).kernel(mf.mo_coeff).mo_coeff                          # LOs in terms of AOs
fock_lo = np.einsum('ax,ab,by->xy', c_lo, mf.get_fock(), c_lo)
```

(Note that these will only be the same for converged Hartree-Fock calculations)

As for your second question, the Fock matrix represents a one-electron operator and doesn't have a "two-electron part".
The best way to get the two-electron integrals of the ab-initio Hamiltonian depends on the kind of system, but generally you could use
```
c_lo = Boys(mol).kernel(mf.mo_coeff).mo_coeff                          # LOs in terms of AOs
nmo = len(mf.mo_energy)
eris = ao2mo.kernel(mol, c_lo, compact=False).reshape([nmo]*4)
```
To get the integrals in the LO basis.

**Comment by DanielBajac** [comment]
Hi Max,

Thanks for the explanation! It was very helpul. Of course, I was confused about the two-electron part of the Fock matrix.

Thanks again to Tim for his answer. 

Best wishes

**Comment by tberkel** [comment]
If you're using PySCF's Boys functionality, then you should definitely use
option 2, as shown cleanly by Max. No need to go into the canonical MO
basis first. Just to add: my use of @ was because it is the matrix
multiplication operator as of Python 3.5, so Max's final line could be
replaced by:
`fock_lo = ***@***.******@***.***_lo`

**Comment by shivupa** [comment]
I think when @tberkel is replying by email something is obfuscating matrix multiplies because they look like email addresses.

What I think was intended is that 
`fock_lo = np.einsum('ax,ab,by->xy', c_lo, mf.get_fock(), c_lo)`
could be replaced by
`fock_lo = c_lo.T @ mf.get_fock() @ c_lo`

**Comment by tberkel** [comment]
Wow you're absolutely right, thanks for catching that. Sorry for the confusion. I've edited my replies just so that they're clear in the future.
