### ISSUE TITLE
Boys localization not unitary

### ISSUE THREAD

**Issue by jackweber1296** [pyscf/pyscf#1214]
Hi,

I'm having trouble with localization functions not being orthogonal to the original mo_coeff's from which they were formed. Here is a minimal example:

-----------------------------------------------------------------------------------------                                                                     
import numpy                                                                               
from pyscf.lo import Boys                                                                  
from functools import reduce                                                               
from pyscf import scf, gto                                                                 
                                                                                           
atoms     = '''                                                                            
C      3.935503   -2.328117   -0.000001                                                    
H      3.477949   -1.583295   -0.617078                                                    
H      3.577308   -2.229235    1.003403                                                    
H      3.689104   -3.300459   -0.372478                                                    
H      4.997653   -2.199480   -0.013850                                                    
'''                                                                                        
basis     = 'sto3g'                                                                        
chrg      = 0                                                                              
spn       = 0                                                                              
sym       = 'c1'                                                                           
                                                                                           
mol          = gto.Mole()                                                                                                                                                                                   
mol.atom     = atoms                                                                       
mol.charge   = chrg                                                                        
mol.spin     = spn                                                                         
mol.basis    = basis                                                                       
mol.symmetry = sym                                                                         
mol.unit     = 'Ang'                                                                       
mol.build()                                                                                
                                                                                           
mf = scf.RHF(mol)                                                                          
mf.kernel()                                                                                
S = mol.intor('int1e_ovlp')                                                                
X_loc = Boys(mol).kernel(mf.mo_coeff)                                                      
test = reduce(numpy.dot, (X_loc.T, S, mf.mo_coeff))                                        
print(test)                                                                                
exit()      
--------------------------------------------------------------

The resulting "test" matrix is not identity. Am I doing (or expecting) something wrong here? The PySCF version is 2.0.1 with numpy version 1.19.2 and scipy version 1.5.2, and it also occurs when I use PySCF v1.7.3.

Thanks,
Jack

**Comment by Majokux** [comment]
Hi Jack,
your matrix `test` is representing the overlap <x|i> between Boys orbitals x and MOs i - you would not expect this to be
the identity, as this which would mean that the Boys orbitals are identical to the MOs.

To check for orthonormality, evaluate `reduce(numpy.dot, (X_loc.T, S, X_loc))` instead.
