### ISSUE TITLE
PBE SCF not converged for periodic ZnO with cc-pVDZ

### ISSUE THREAD

**Issue by minyez** [pyscf/pyscf#1218]
Dear PySCF developers,

We tried to converge the ground state of ZnO using PBE and cc-pVDZ basis. With the two diffuse s/p functions, the energy drops from -1821 Ha to -4180 Ha in the first interaction, and never comes back. Without the two functions, the calculation damps around -1830.24 Ha.

By noting that increasing `cell.precision` could solve this problem, energy decomposition is done with converged density matrix and different `precision` (please see table below). The result implies a wrong XC energy with the default cell precision.

|   prec(power) |                  T |                 N-e |              Coul |                  XC |            Elec Tot |
|---------------|--------------------|---------------------|-------------------|---------------------|---------------------|
|            -8 | 1851.8056739261958 | -3903.8518468353077 | 554.4545421051466 | -46.664207918601086 | -1544.2558387225665 |
|            -9 | 1851.8056739261963 |  -3903.851846835481 | 554.4545419637523 |  -79.50524098426659 | -1577.0968719297991 |
|           -10 | 1851.8056739261963 | -3903.8518468353004 | 554.4545419448124 |  -79.50524098426658 | -1577.0968719485581 |

The error seems to come from the cut-off determination by `_estimate_rcut` in `eval_gto`, specifically the lines
https://github.com/pyscf/pyscf/blob/1c6f530131d1f254fa877daee37873d39558b67c/pyscf/pbc/gto/eval_gto.py#L177-L179
Somehow `nan` exists in `r` when a small precision is used. To fix, one can filter them out before taking the max, or add 1 after `es`, similarly to what [`_estimate_rcut` of `cell`](https://github.com/pyscf/pyscf/blob/1c6f530131d1f254fa877daee37873d39558b67c/pyscf/pbc/gto/cell.py#L476-L485) does. Both give much improved XC energy, and SCF can converge in several loops.

|   prec(power) |                  T |                 N-e |              Coul |                  XC |            Elec Tot |
|---------------|--------------------|---------------------|-------------------|---------------------|---------------------|
| -8(~isnan) | 1851.8056739261958 | -3903.8518468353077 | 554.4545421051273 |  -79.50524098426683 | -1577.0968717882515 |
|    -8(p1) | 1851.8056739261958 | -3903.8518468353077 | 554.4545421051436 |  -79.50524098426672 | -1577.0968717882354 |
|   -8(filter<1) | 1851.8056739261958 | -3903.8518468353077 | 554.4545421051258 |  -79.50524098426683 | -1577.0968717882533 |

Edit: add the result after filtering with `r[r<1]=1`

Before sending a PR with one of the fixes, I would like to ask if anything else I may take care of, e.g. test cases. Thanks!

The commit used for the calculations is f1ec3c1, but the issue persists in the latest one 1c6f530131d

Finally tag and thanks @hongzhouye since he found the problem when helping me with GW and analyzed the possible source of error.

<details>
<summary>test script</summary>

```python
from pyscf.pbc import gto, scf, dft, df
from pyscf import lib
import numpy as np

if __name__ == '__main__':
    atom = [['Zn', [0., 0., 0.]], ['O', [1.14599992, 1.14599992, 1.14599992]]]
    a = np.array([[0.       ,  2.29199984, 2.29199984],
                  [2.29199984, 0.        , 2.29199984],
                  [2.29199984, 2.29199984, 0.        ]])
    basis = 'ccpvdz'
    pseudo = None
    cell = gto.Cell(atom=atom, a=a, basis=basis, pseudo=pseudo)
    cell.verbose = 6
    cell.precision = 1e-12  # adjust
    cell.build()

    nk = 4
    kmesh = [nk] * 3
    kpts = cell.make_kpts(kmesh)
    mydf = df.RSDF(cell, kpts)
    mydf.build()

    mf = dft.KRKS(cell, kpts=kpts).rs_density_fit()
    mf.xc = 'pbe'
    mf.with_df = mydf

    ### for SCF
    mf.chkfile = 'mf.chk'
    mf.conv_tol = 1e-8
    mf.max_cycle = 20
    mf.kernel()

    ### for energy decomposition
    dm = mf.from_chk(chk='mf_dz_444_nodis_1em12.chk')

    t = lib.asarray(mf.cell.pbc_intor('int1e_kin', 1, 1, mf.kpts))
    ke = 1.0 / len(mf.kpts) * np.einsum('kij,kji', t, dm)
    nuc = lib.asarray(mf.with_df.get_nuc(mf.kpts))
    enuc = 1.0 / len(mf.kpts) * np.einsum('kij,kji', nuc, dm)
    vxc = mf.get_veff(cell, dm)
    print(ke.real, enuc.real, vxc.ecoul, vxc.exc)
```

</details>

**Comment by hongzhouye** [comment]
I *think* that the `nan` occurs because of large exponents in the contracted basis functions, which make `r < 1` after the first iteration and lead to negative numbers in the sqrt in the second iteration.

**Comment by sunqm** [comment]
The estimate_rcut was developed for smooth functions in which the contributions from the factor  `r^l` needs to be considered. I forgot to test the basis with large exponent. For the basis with `rcut < 1`, the factor `r^l` may not be needed. In your PR adding 1 to r^2 may give a `rcut` too close to 1 for large exponents. I think we can leave the first pass with initial guess `r = 5` as it is. Before second pass, a statement to filter r by doing `r[r<1] = 1` can solve the problem. The impact of `r^l` can be removed for steep basis while smooth basis is not affected.

**Comment by minyez** [comment]
Thanks, this treatment sounds more reasonable. I have added test result for this. XC then is same as `~isnan~` treatment, though Coul slightly differs.
