### ISSUE TITLE
cache in function 'intor'

### ISSUE THREAD

**Issue by qw-nb** [pyscf/pyscf#1221]
I found in nr_direct.c, there is a variable named 'cache' in integral function pointer '*intor', but in libcint there isn't this variable in int2e. So what's this variable used for. Is it important for SCF calculation. I use libcint to achieve a SCF, but its effiency is much lower then pyscf.  May I ask are there anything i should take care to achieve a SCF.

**Comment by sunqm** [comment]
`cache` is passed to int2e function `https://github.com/sunqm/libcint/blob/master/src/cint2e.c#L1141` . It is used to remove the `malloc` statement in integral code. malloc has non-negligible impacts on the efficiency of omp threading parallelism
