### ISSUE TITLE
NMR shielding a spin-spin coupling

### ISSUE THREAD

**Issue by eronca** [pyscf/pyscf#1224]
In the previous versions of Pyscf there was the possibility to calculate NMR spectra using prop.nmr.
It seems that this feature has been removed from version 2.0. 
Is it still possible running NMR?
If yes could you please give me some instructions to do that and point me to the file where it is implemented in the code?

thank you in advance for the reply.

bests

Enrico

**Comment by fishjojo** [comment]
The property module has been moved to [here](https://github.com/pyscf/properties) as an addon of pyscf.
