### ISSUE TITLE
About dfmp2_native and dfump2_native

### ISSUE THREAD

**Issue by hy00yu** [pyscf/pyscf#1225]
Hello, 
I found some new dfmp2 codes updated in 2.0.1,
and would like to ask some questions. 

According to the pyscf doc, 
mp.dfmp2_native module is the native implementation of DF-MP2.
What does it mean by "native implementation" and where can I find the reference?
Does mp2, dfmp2, and dfmp2_native give the same (similar, trustable) results?
(In other words, is it safe to replace mp2 with dfmp2_native?)

Also, I would  like to use density fitting in UMP2,
but it seems that the dfump2_native module is not implemented in mp/__init__.py
and so when I try running mp.dfump2_native.DFMP2(mf), 
it raises an AttributeError: module 'pyscf.mp' has no attribute 'dfump2_native'.
Is there any purpose you haven't yet added in __init__.py?

Thank you in advance.

**Comment by fishjojo** [comment]
dfmp2 is equivalent to dfmp2_native. In addition, dfmp2_native provide spin-component scaling and unrelaxed density matrix. We plan to refactor the MP2 code in the future and to merge the original implementation in dfmp2 and the new implementation.

**Comment by hebrewsnabla** [comment]
> dfmp2 is equivalent to dfmp2_native. In addition, dfmp2_native provide spin-component scaling and relaxed density matrix. We plan to refactor the MP2 code in the future and to merge the original implementation in dfmp2 and the new implementation.

btw, do you plan to add spin-component scaling for pbc mp2?

**Comment by tberkel** [comment]
Our group has a version of periodic SCS MP2. We'll submit a PR soon!
