### ISSUE TITLE
cubegen and molden

### ISSUE THREAD

**Issue by johTin** [pyscf/pyscf#1228]
Hello everyone.
I am new in PySCF, I have already worked with gaussian and orca..
gaussian generates a log and chk file that we use to visualize the orbitals and energy properties, but with PySCF it's not the same thing, I saw that you have to generate a Cubegen or molden file, I tried but its didn't go well.
possible a hand to understand this procedure?
Thanks.

**Comment by hebrewsnabla** [comment]
I think the cubegen tool works fine. I can generate a cube (like [examples/tools/05-cubegen.py](https://github.com/pyscf/pyscf/blob/master/examples/tools/05-cubegen.py) and render it into picture with VMD.

Could you describe your "didn't go well"?

**Comment by johTin** [comment]
hebrewsnabla thanks for replay 
for exemple there is an error when i use the code below 

from pyscf import gto
from pyscf import dft
from pyscf import lo
from pyscf.tools import molden
from pyscf.tools import cubegen
import os  
os.OMP_NUM_THREADS=6 

methane = gto.Mole()
methane.atom = """H 0.000000000000 0.000000000000 0.000000000000
                  C 0.000000000000 0.000000000000 1.087900000000
                  H 1.025681956337 0.000000000000 1.450533333333
                  H -0.512840978169 0.888266630391 1.450533333333
                  H -0.512840978169 -0.888266630391 1.450533333333"""

methane.basis = 'def2-qzvp'
methane.verbose = 4
methane.max_memory=12000
methane.output = '/home/dev/Documents/My Jobs/Methane/Methane.log'
methane.build()

carbon = gto.Mole()
carbon.atom = 'C 0.0 0.0 0.0'
carbon.basis = 'def2-qzvp'
carbon.spin = 2
carbon.verbose = 4
carbon.max_memory=12000
carbon.output = '/home/dev/Documents/My Jobs/Methane/carbon.log'
carbon.build()

hydrogen = gto.Mole()
hydrogen.atom = 'H 0.0 0.0 0.0'
hydrogen.basis = 'def2-qzvp'
hydrogen.spin = 1
hydrogen.verbose = 4
hydrogen.max_memory=12000
hydrogen.output = '/home/dev/Documents/My Jobs/Methane/hydrogen.log'
hydrogen.build()
energies = []

for mol in [methane, carbon, hydrogen]:
  if mol.spin == 0:
    mf = dft.RKS(mol)
  else:
    mf = dft.UKS(mol)
  
  mf.xc = 'B3LYP'
  mf.max_memory=12000
  mf.chkfile = '/home/dev/Documents/My Jobs/Methane/Methane_B3LYP.chk'
  mf.run()
  dm0 = mf.make_rdm1()

# I use this code for generate cube files
cubegen.density(methane, '/home/dev/Documents/My Jobs/Methane/Methan_den.cube', dm0())
cubegen.mep(methane, '/home/dev/Documents/My Jobs/Methane/Methan_pot_mep.cube', dm0())
cubegen.orbital(methane, '/home/dev/Documents/My Jobs/Methane/Methan_mo1_orb.cube', mf.mo_coeff[:,0])

I get this Error when begin generate cube file:
exception  : ValueError
operands could not be broadcast together with shapes (2,30,30) (30,30,2) 
  File "[/home/dev/Documents/My]() Jobs[/Methane/Methane-try.py]()", line 55, in <module>
    cubegen.density(methane, '[/home/dev/Documents/My]() Jobs[/Methane/Methan_den.cube]()', dm0())

**Comment by hebrewsnabla** [comment]
dm0 is an array, not a function. So `dm0()` should be ewplaced with `dm0`

**Comment by johTin** [comment]
the same problem
even with this: cubegen.density(methane, '/home/dev/Documents/My Jobs/Methane/Methan_den.cube', mf.make_rdm1())
I think the problem comes from the loop.
tahnks [hebrewsnabla](https://github.com/hebrewsnabla)

**Comment by hebrewsnabla** [comment]
If you call density in the loop, you should do `cubegen.density(mol, ......)`

**Comment by johTin** [comment]
resolved

i try this
mylist = ["methane", "carbon", "hydrogen"]
x=0
for mol in [methane, carbon, hydrogen]:
  str=mylist[x]
  if mol.spin == 0:
    mf = dft.RKS(mol)
  else:
    mf = dft.UKS(mol)
  
  mf.xc = 'B3LYP'
  mf.max_memory=12000
  mf.chkfile = '/home/dev/Documents/My Jobs/Methane/Methane_B3LYP.chk'
  mf.run()
  dm0 = mf.make_rdm1()
  # I use this code for generate cube files
  cubegen.density(mol, '/home/dev/Documents/My Jobs/Methane/' + str + '_dens.cube', mf.make_rdm1()) #makes total density
  cubegen.mep(mol, '/home/dev/Documents/My Jobs/Methane/' + str + '_pot_mep.cube', mf.make_rdm1())
  cubegen.orbital(mol, '/home/dev/Documents/My Jobs/Methane/' + str + '_mo1_orb.cube', mf.mo_coeff[:,0])
  x=x+1

it work for molecule

thanks [hebrewsnabla](https://github.com/hebrewsnabla) for your helpful
