### ISSUE TITLE
About “CPU time for initialize scf”

### ISSUE THREAD

**Issue by qw-nb** [pyscf/pyscf#1230]
In output file, it shows CPU time for initialize scf. This process seems take longger time than all cycles. What does pyscf do in initilze scf?

**Comment by fishjojo** [comment]
> > Usually, the overhead comes from computing the initial guess of the density matrix, overlap matrix, and the one electron operators, i.e., kinetic energy, nuclear attraction or pseudo potential. If you use gaussian density fitting for pbc calculation, it may also include the time to build the 3 center integrals if they are not built before running the scf kernel.
> 
> Thanks for your answer. But as I know one-electron integrals take little time and in some case, normal one is faster then use denisty fitting. Does PySCF calculate two-electron integral in this step and stroe them in memory?

If you have enough memory, then yes. Otherwise, the 2 eri is computed on the fly and directly contracted with the density matrix.

**Comment by verena-neufeld** [comment]
@qw-nb , has this been resolved?
