### ISSUE TITLE
PySCF wheels for Python 3.10

### ISSUE THREAD

**Issue by soranjh** [pyscf/pyscf#1231]
The current PySCF wheels on PyPI are for Python 3.6 - 3.9. It will be very helpful to have Python 3.10 wheels on PyPI as well. Is there any plan to upload them?

**Comment by sunqm** [comment]
python 3.10 is adding to test pipeline (PR #1249). It will be added to release pipeline next step. Wheels for python 3.10 shall be available in 2.1 release

**Comment by sunqm** [comment]
Available in pyscf 2.1
