### ISSUE TITLE
PySCF annual developer's meeting

### ISSUE THREAD

**Issue by fishjojo** [pyscf/pyscf#1232]
Dear PySCF developer community,

Thank you for your interest in PySCF and all your contributions to this software tool. The community has grown tremendously in the last few years to the point that many of us have never met! **To this end, we will be hosting the 1st annual PySCF developer conference July 28-29 2022 in Pasadena, California.** 
Please refer to the conference [website](https://sites.google.com/view/1stannualpyscfdevmtg/home) for the schedules and locations. The zoom link for remote participants is [here](https://caltech.zoom.us/j/86205544645?pwd=UnVncEpaaEovbkVjRW5KQWRvTi9SZz09).

best wishes,

The PySCF board

**Comment by susilehtola** [comment]
I'd love to come but I've already made plans to be in Europe at that time :frowning_face:

**Comment by fishjojo** [comment]
@1QB-Information-Technologies
@Maxprofs
@squareinc
@aasthan4
@acastanedam
@adityanandy
@ajz34
@akakcolin
@AlejandroE-SanchezV
@alexhuangweijie
@AliciaRaeWelden
@Alpha-Librae
@alxvov
@alzhang99
@amandadumi
@ambmax00
@Andersen98
@andrea22-diddl
@andyzynlove
@ares201005
@WeiLiweili
@armunoz
@AspirinCode
@awhite862
@baopengbp
@basilib
@baumeier
@bbusemeyer
@beebo021
@belmarca
@berkelbach-group
@berquist
@bgpeyton
@binghuang2018
@biruce-fm
@Bismarrck
@bkesk
@black-walker
@blink8099
@bogdanoff
@BoothGroup
@brianz98
@BritneyW
@brugar
@btglau
@c40zAtGitHub
@carlos-pereyra
@cchandler2015
@cesaray10
@cfm-mpc

**Comment by fishjojo** [comment]
@KMCzajkowski
@masmansouri
@changsuc
@chaoxianhu
@charnley
@chelleorc
@cherishyli
@chjacob-tubs
@chrinide
@chs040701
@cirosantilli
@cnyeh
@crisely09
@cyniu220
@CyrusUmrigar
@danclaudino
@danjodc
@dcyang
@ddcr
@dithillobothrium
@DominikLindorfer
@eemackintosh
@ehermes
@ElectronicStructureUdeM
@elekezem
@Eling486
@ElkeF
@ElviraRS
@emi-aimy
@EMinsight
@Enhydra-xun
@EricaCMitchell
@ericmjonas
@eronca
@esskyiss
@estfw-blte
@etaffet
@ethanvo
@europj
@fabijan5
@FanGuozheng
@fdmalone
@felipelewyee
@fieldplay
@fishjojo
@MoleOrbitalHybridAnalyst
@yangdatou
@Flowdawan
@fockeke
@frankhan91

**Comment by fishjojo** [comment]
@FrederikKjeldal
@fuulish
@gayverjr
@GeorgeRussev
@gkc1000
@ncrubin
@gkclab
@Global19
@Global19-atlassian-net
@gmwang18
@gnibeil
@godotalgorithm
@grinisrit
@h-larsson
@halvarsu
@hczhai
@hebrewsnabla
@hengma1001
@hewg2008
@highlight0112
@hirnimeshrampuresoftware
@hkbluesky
@hkuramochi
@hongzhouye
@Paul-St-Young
@hoshishin
@hshi
@hungpham2017
@iliya-s
@imin-95
@insaan12
@jamcas
@jamesETsmith
@januseriksen
@jcartus
@jdmcclain47
@jdwhitfield
@jemiryguo
@JezsMartinez
@JFurness1
@holy0213
@jhrmnn
@jiachenchem
@jjakowski
@jl2922
@jodyburksphd
@jtkrogel
@Justin318
@kayahans
@kcbhamu

**Comment by fishjojo** [comment]
@kevinsmia1939
@kgasperich
@khadev
@kingscolour
@kkyusuke
@kylebystrom
@laichaoo
@langerest
@lanieleung
@larsbratholm
@latrix
@lazycrazyowl
@lcyyork
@LDongWang
@leeping
@Leticia-maria
@lichen5
@likun1212
@lilyechoC
@lishchgithub
@Liublgit
@lkwagner
@lsyh366
@lukw00heck
@luna-component
@LuoshuTheBest
@m-i-w
@magicrchen
@Majokux
@manassharma07
@matk86
@matt-chan
@mattchan-tencent
@matthew-hennefarth
@MatthewRHermes
@mattwelborn
@maxscheurer
@mbarbry
@mdav2
@mdd31
@meitnerium
@mfdgroot
@mfherbst
@mfkasim1
@mibumi
@MihailBogojeski
@minyez
@mitra054
@mjw99
@mohuangrui

**Comment by fishjojo** [comment]
@molguin-qc
@mrauha
@MShaffar19
@msmerlak
@mtreinish
@mussard
@nhoffma5
@nickjbrowning
@niudake
@njustcodingjs
@nkrivoshchapov
@nmardirossian
@npoirie1
@nunoedgarhubsoftphotoflow
@nush-1qb
@NuturesH
@obackhouse
@obrien951
@odidev
@pablo-b
@pablomazo
@pauljprobinson
@pckiller2008
@pedersor
@pengdl
@penglinq
@petrichorcode
@pinskip
@plin1112
@PrakashQM
@premprabhat
@psychodevil
@pubgsaber
@pulkin
@Python-Repository-Hub
@q2kuhn
@qc-prog
@qfizik
@qiangzhongwork
@qize
@quansilong
@QuESt-Calculator
@r-imai-quantum
@r-peng
@rajarshitiwari
@raybrad
@raymound
@robertodr
@ronaldosc
@RoundBottomFlask

**Comment by fishjojo** [comment]
@rtransformation
@ruiyiQM
@RulingF
@RuochengHan
@rvexiau
@sapatha2
@sarminh
@shaobin
@shengg
@shivupa
@shufay
@shunsunsun
@silentforest89
@snsunx
@sokolov-group
@Solertis
@ssh2
@sspaino
@ssthurai
@St-Maxwell
@stjordanis
@sunchong137
@sunqm
@christinadanielphysics
@DanSGraham
@ddhawan11
@FermiQ
@gharib85
@ghb24
@GQI7FS6
@John-zzh
@lantrann
@LeonOtis
@smgarner229
@LeeQY1996
@mettlyz
@nongnongyang
@pavanell
@sailfish009
@stevendengue
@triabolical
@vonDonnerstein
@willwheelera
@xmujiali
@zwgsyntax
@zzy2014
@SuperFace
@susilehtola
@Suzukazole
@swillow

**Comment by fishjojo** [comment]
@sxjscience
@takafumi-shiraogawa
@TApplencourt
@tberkel
@tepl
@the-hktran
@theonov13
@theorychemyang
@zc62
@ThePrez
@tktan90
@tmash
@toddtao2019c
@tonycmooz
@trollchu
@tyanderson176
@tzyii
@umamibeef
@UncleWang05
@UnixJunkie
@ushnishray
@utmcontent
@v1j4y
@v2quan89
@v3op01
@varunrishi
@verena-neufeld
@vibinabraham
@vigneshwarajpuresoftware
@vijaymocherla
@Warlocat
@lzypotato
@wen-xl
@wesley-stone
@williamli-sci
@wirawan0
@wmizukami
@wqnow
@wsyxbcl
@wwjCMP
@xiaoamero
@xiaochungong
@XiaoLiu161147
@xielm12
@xinxing02
@xjz980322
@xlzan
@xphileprof
@xu-xi
@xubwa

**Comment by fishjojo** [comment]
@xwang862
@y-yao
@y1xiaoc
@yangcal
@yfyh2013
@Yi-FanLi
@yidapa
@yonghaogu
@yoshida-lab
@yudongcao
@Yuya-O-Nakagawa
@yzhu09203
@ZhaoYilin
@zhcui
@zhendongli2008
@zhjiang-1
@zhutianyu1991
@zishengz
@zwang123

**Comment by belmarca** [comment]
@rodrigobogossian

**Comment by verena-neufeld** [comment]
I'm really looking forward to this meeting! Do we have any details yet and are the dates confirmed? Thanks :) Verena

**Comment by gkc1000** [comment]
Another announcement will be made later this week. But dates are confirmed
as in previous post.

**Comment by mibumi** [comment]
Will it be on zoom as well?

**Comment by dithillobothrium** [comment]
Finally, the meeting. Maybe my issues will be considered?

**Comment by fishjojo** [comment]
Please register by the end of this week if you are interested in attending the meeting.
https://sites.google.com/view/1stannualpyscfdevmtg/home

**Comment by fishjojo** [comment]
> Will it be on zoom as well?

I think at least the talks can be on zoom.

**Comment by hebrewsnabla** [comment]
> > Will it be on zoom as well?
> 
> I think at least the talks can be on zoom.

Does attending by zoom requires registering?
