### ISSUE TITLE
selecting AOs of specific atoms in AVAS method

### ISSUE THREAD

**Issue by schusteritsch** [pyscf/pyscf#1241]
Hi PySCF Team,

I was wondering if it's possible to select AOs of specific atoms in the AVAS method? As far as I can tell the implementation allows you to select AO's in the form of for instance ['Fe 3d'] - is it possible to target the AO's of specific atoms and not all atoms of a specific species. E.g. if there is more than one transition metal atom or if you are interested in including AO's of other species around a transition metal atom but not all atoms of that type in the whole structure?

Many thanks,
Georg

**Comment by jamesETsmith** [comment]
Hi @schusteritsch, PySCF allows you to decorate atom symbols and AVAS can see those. Here's a minimal example, where I label one iron atom with `!`:

```python
from pyscf import gto, scf, mcscf
from pyscf.mcscf import avas

mol = gto.M(atom="!Fe 0 0 0; Fe 0 0 1", basis="def2tzvp", verbose=5)
mf = scf.RHF(mol).run()

ao_labels = ['!Fe 3d']
norb, ne_act, orbs = avas.avas(mf, ao_labels, canonicalize=False)
```

Here's an excerpt from the output showing that it's only trying to match again a single atoms AOs:
```
reference AO indices for minao ['!Fe 3d']: [10 11 12 13 14]
```

**Comment by schusteritsch** [comment]
Hi @jamesETsmith 
Thanks for this - I didn't realize you could decorate atoms this way. This works exactly the way I had hoped!

**Comment by jamesETsmith** [comment]
Happy to help! Closing the issue now, but feel free to reopen if you have more questions about this.

**Comment by Meowrium** [comment]
> Hi @schusteritsch, PySCF allows you to decorate atom symbols and AVAS can see those. Here's a minimal example, where I label one iron atom with `!`:
> 
> ```python
> from pyscf import gto, scf, mcscf
> from pyscf.mcscf import avas
> 
> mol = gto.M(atom="!Fe 0 0 0; Fe 0 0 1", basis="def2tzvp", verbose=5)
> mf = scf.RHF(mol).run()
> 
> ao_labels = ['!Fe 3d']
> norb, ne_act, orbs = avas.avas(mf, ao_labels, canonicalize=False)
> ```
> 
> Here's an excerpt from the output showing that it's only trying to match again a single atoms AOs:
> 
> ```
> reference AO indices for minao ['!Fe 3d']: [10 11 12 13 14]
> ```

If I have several different atoms like carbon atoms in pyradine, how can I identify them in ao label?
