### ISSUE TITLE
pip install addons will install pyscf 1.7.6

### ISSUE THREAD

**Issue by fishjojo** [pyscf/pyscf#1243]
For example, `pip install pyscf[dmrgscf]` will install pyscf 1.7.6, but 1.7.6 has no such extra, so the extra will not be installed.

**Comment by mfdgroot** [comment]
I can confirm.
Overall the install behavior of the extra packages is very erratic.
Some of the packages listed by first definition of the dictionary EXTRAS in `config.py` do not install correctly when used in the bracket way and should be installed by hand. 
This command is a combination of installs that work through the EXTRAS and then the manual ones:
`pip install pyscf[geomopt,doci,properties,cppe,pyqmc] git+https://github.com/pyscf/dmrgscf git+https://github.com/pyscf/dftd3 git+https://github.com/pyscf/icmpspt git+https://github.com/pyscf/semiempirical git+https://github.com/pyscf/shciscf git+https://github.com/pyscf/nao git+https://github.com/pyscf/cornell-shci git+https://github.com/pyscf/naive-hci`
This should get you most (all of the working) extensions.

**Comment by sunqm** [comment]
Fixed in 2.1.0 release
