### ISSUE TITLE
Errors when on create cubgen and molden files

### ISSUE THREAD

**Issue by johTin** [pyscf/pyscf#1245]
Hello 
I have some errors after run dft calcul on creating cube and molden files
here is the code
from pyscf import gto
from pyscf import dft
from pyscf.tools import cubegen
from pyscf.tools import molden
import os  
os.OMP_NUM_THREADS=6 

strfile='C6Ge6H6'
strpath= '/home/dev/Documents/New Job 5-5-22/Cation/' + strfile +'/B3lyp/'
strpath_xyz= '/home/dev/Documents/My Jobs/' + strfile + '/'
Mol_C= gto.Mole()

Mol_C.atom ="""H 0.000000000000 0.000000000000 0.000000000000
                  C 0.000000000000 0.000000000000 1.087900000000
                  H 1.025681956337 0.000000000000 1.450533333333
                  H -0.512840978169 0.888266630391 1.450533333333
                  H -0.512840978169 -0.888266630391 1.450533333333"""

Mol_C.basis = 'def2-qzvp'
Mol_C.verbose = 5
Mol_C.charge = 1
Mol_C.spin = 1
Mol_C.max_memory=12000
Mol_C.output = strpath + strfile + '_B3lyp.log'
Mol_C.build()

mf = dft.UKS(Mol_C)
mf.xc = 'B3LYP'
mf.chkfile = strpath + strfile  + '_B3lyp.chk'
mf.run()
energy = mf.kernel(mf.make_rdm1())
cubegen.orbital(Mol_C, strpath + strfile + '_B3lyp_mo1_orb.cube', mf.mo_coeff[:,0])
cubegen.density(Mol_C, strpath + strfile + '_B3lyp_dens.cube', mf.make_rdm1())
cubegen.mep(Mol_C, strpath + strfile + '_B3lyp_pot_mep.cube', mf.make_rdm1())
  
with open(strpath + strfile + 'mo' + '.molden', 'w') as f1:
 molden.header(Mol_C, f1)
 molden.orbital_coeff(Mol_C, f1, mf.mo_coeff, ene=mf.mo_energy, occ=mf.mo_occ)
    
print({strfile: energy})

error for cube 
shapes (8000,177) and (2,177) not aligned: 177 (dim 1) != 2 (dim 0)
error for molden
IndexError: index 2 is out of bounds for axis 0 with size 2

can some body helps please?

**Comment by hebrewsnabla** [comment]
Since you are doing a UKS job, you should know that the shape of mf.mo_coeff is (2, nao, nao). Thus, `mf.mo_coeff[0][:,0]` is the first alpha MO, `mf.mo_coeff[1][:,0]` is the first beta MO.
Same for the density. `mf.make_rdm1()[0]` gives alpha density. If you want total density, you need to sum alpha and beta density.

**Comment by hebrewsnabla** [comment]
For molden dump, `molden.orbital_coeff` only allow dumping alpha OR beta orbitals. Dumping alpha orbitals can be `molden.orbital_coeff(Mol_C, f1, mf.mo_coeff[0], ene=mf.mo_energy[0], occ=mf.mo_occ[0], spin='Alpha')`.

However, it seems more convenient to use the `molden.dump_scf` function. It will automatically check RKS/UKS and dump 2 sets of orbitals for UKS.

**Comment by johTin** [comment]
hello 
thanks for all its work fine
