### ISSUE TITLE
Natural orbitals occupations for each state

### ISSUE THREAD

**Issue by gaurabganguly1989** [pyscf/pyscf#1250]
Hi,
I am a new PySCF user. I wish to print the natural orbital occupations for all individual states involved in a state-averaged CASSCF/SHCISCF calculation in order to understand the nature of the states. In the output file, the density matrix diagonal elements are printed which, I believe, are averaged over all states. How to print them for each state?

thanks,
Gaurab

**Comment by bogdanoff** [comment]
Hi Gaurab,
The way to go is to run state-specific CASCI calculation for each state using orbitals optimized in state-averaged CASSCF.

**Comment by gaurabganguly1989** [comment]
Hi Nikolay:
Many thanks for the suggestion. What about the SHCISCF then? Should I run a state-specific SHCI calculation using orbitals optimized in state-averaged SHCISCF?

**Comment by gaurabganguly1989** [comment]
Thanks so much!
