### ISSUE TITLE
REAL_SPHERIC order of p labels

### ISSUE THREAD

**Issue by tillhanke** [pyscf/pyscf#1251]
Dear PYSCF Team, I was just going through some of the methods provided in the Mole class and got confused by the order of sph_labels.
It looks like the order of ml for p shell orbitals is `1, -1, 0` or as its printed `x, y, z` while the order for d shells is (much more sensible) `-2, -1, 0, 1, 2` printed as `xy, yz, z^2, xz, x2-y2`.

Not sure if this is deliberately or unintentional but it seems a bit confusing to me.

**Comment by bogdanoff** [comment]
It is the order used, indeed. That was recently discussed in #1023.

**Comment by tillhanke** [comment]
Thanks
