### ISSUE TITLE
two electron integral for each k point for pbc.khf

### ISSUE THREAD

**Issue by kirti215** [pyscf/pyscf#1254]
Hello
I am trying to calculate the two electron integrals for each k points I used the example file but the integrals that i get from the example file does not give the same J matrix as by get_j command. Then I get the two electron integrals from the following command
eri=gdf.get_eri([gdf.kpts[1],gdf.kpts[1],gdf.kpts[1],gdf.kpts[1]]) for each k point separately But these integrals give me the correct j matrix but not giving the K (exchange matrix) as can be get by get_k . Aslo these integrals for zeroth k point giving me 9 integrals for 2 basis set as it should be 2^4 integrals. As I am new to pyscf and python as well can somebody tell me the correct way to get those integrals.

Thank you
KIRTI

**Comment by hebrewsnabla** [comment]
Could you provide a minmal working example for your question?

**Comment by kirti215** [comment]
[example.txt](https://github.com/pyscf/pyscf/files/8706363/example.txt)
Hi this is the example file through which I am calculating the eri for different points after that I am using a fortran code as I don't know Python to calculate J and K matrices . I am just multiplying the density matrix with these integrals(ij|kl) and summing up over the (kl). For example for elements of  K matrix for each k point
K_kpt_ij = dm_kpt_ij*(ik|jl)_kpt
and for J matrix elements for each k point
J_kpt_ij = dm_kpt_ij*(ij|kl)_kpt
Please have a look and what is the correct way to do the same
Thanks in advance
KIRTI

**Comment by Majokux** [comment]
Hi Kirti,

The K- and J-matrices in periodic HF are not "k-point local", which (I think) you are assuming here.
Have a look at Eqs. 10,11 in https://arxiv.org/pdf/2012.07929.pdf

**Comment by hebrewsnabla** [comment]
> Aslo these integrals for zeroth k point giving me 9 integrals for 2 basis set as it should be 2^4 integrals. 

You can read the comments in df/df_ao2mo.py
When there's no kpts given, i.e. `gdf.get_eri()`, the kpt will be gamma point and the program believes the integral is real and with s4 symmetry, so eri is of shape (nao_pair, nao_pair), which is (3,3) in this case.
Otherwise, the eri shape is (nao*nao, nao*nao)

**Comment by kirti215** [comment]
Hi Majokux 

First of all thanks for the reply I tried and codded the equations 10,11 and still I am getting the same problem the J matrix is coming correct upto 2-3 decimal place but not the K matrix. Correctness means the similarity with the J and K matrix collected from get_j and get _k commands . 

Thanks in advance

**Comment by Majokux** [comment]
2-3 decimal places is not a great agreement - are you using the same density fitting object as the HF? You can access is as `kmf.with_df` (in the example above you create a new GDF object with possibly a different auxiliary basis).

The exchange has an integrable divergence for PBC and is only very slowly convergent with number of k-points; for this reason
a correction is applied, see [here](https://github.com/pyscf/pyscf/blob/ac65240b006f2c050ce4cdd1bfb17c050f9b6312/pyscf/pbc/df/df_jk.py#L230).
You can disable the correction by setting `kmf.exxdiv = None` and see if you get agreement in the K-matrix. If yes, you can try to add the correction to your own K-matrix build and see if you get agreement with `exxdiv = 'ewald'`.

**Comment by kirti215** [comment]
@Majokux I agree that 2-3 decimal place is not a great agreement . I used the same density fitting object and also take care of the correction but still the result is not coming correct . I am attaching the file for reference.

Thanks in advance 
[test.txt](https://github.com/pyscf/pyscf/files/8837757/test.txt)

**Comment by sunqm** [comment]
> Hi Majokux
> 
> First of all thanks for the reply I tried and codded the equations 10,11 and still I am getting the same problem the J matrix is coming correct upto 2-3 decimal place but not the K matrix. Correctness means the similarity with the J and K matrix collected from get_j and get _k commands .
> 
> Thanks in advance

"J matrix is correct up to 2-3 decimal place", what do you compare to? Your sample code does not show how you check the correctness

**Comment by kirti215** [comment]
@sunqm I am writing a fortran code externally and calculating the J matrix using two electron and density matrix and summing over all kpoints.

**Comment by sunqm** [comment]
Since it is related to an external Fortran program, seems not much to do in pyscf. If that requires testing or debuging pyscf k-point module, we will need some test systems or your test code @kirti215

**Comment by rejanir803** [comment]
Hi, I am actually experiencing this same issue, and I have coded everything in pyscf using EQ 10 and 11. I can success fully replicate J as in pyscf but not K. I include my code and its output below:

# Get density matrix:
dm = mf.make_rdm1()
print("Density matrix shape: ", dm.shape)

# Compute Coulomb (J) and Exchange (K) matrices
J, K = mf.get_jk(cell,dm, hermi=1, kpts=kpts)

print("Exchange matrix K shape:", K.shape)
# print(K.real)

# Performing Check:
# Checking K
eri_K =  []
for i in range(len(kpts)):
    kpts_ijkl = np.array([kpts[0], kpts[i], kpts[i], kpts[0]])
    eri_K.append(restore(1, df_pbc.get_ao_eri(kpts=kpts_ijkl), ncellao).real)
    
eri_K  = np.array(eri_K)
print("ERI tensor shape: ", eri_K.shape)

K_manual = np.einsum("ivk,imvkl->ml", dm, eri_K)/len(kpts)
print("Exchange matrix K shape:", K.shape)
print(K[0].real)
print("Exchange matrix K_manual shape:", K_manual.shape)
print(K_manual.real)


# Checking J
eri_J =  []
for i in range(len(kpts)):
    kpts_ijkl = np.array([kpts[0], kpts[0], kpts[i], kpts[i]])
    eri_J.append(restore(1, df_pbc.get_ao_eri(kpts=kpts_ijkl), ncellao).real)
    
eri_J  = np.array(eri_J)
print("ERI tensor shape: ", eri_J.shape)

J_manual = np.einsum("ilk,imvkl->mv", dm, eri_J)/len(kpts)
print("Coulomb matrix J shape:", J.shape)
print(J[0].real)
print("Coulomb matrix J_manual shape:", J_manual.shape)
print(J_manual.real)

Output:
ERI tensor shape:  (8, 2, 2, 2, 2)
Exchange matrix K shape: (8, 2, 2)
[[1.32785734 0.96272785]
 [0.96272785 1.32785734]]

Exchange matrix K_manual shape: (2, 2)
[[0.70717413 0.34204464]
 [0.34204464 0.70717413]]

ERI tensor shape:  (8, 2, 2, 2, 2)
Coulomb matrix J shape: (8, 2, 2)
[[0.15077507 0.02435146]
 [0.02435146 0.15077507]]

Coulomb matrix J_manual shape: (2, 2)
[[0.15077507 0.02435146]
 [0.02435146 0.15077507]]

Could someone explain why K cannot be replicated, or what I am doing wrong?

**Comment by fishjojo** [comment]
@rejanir803, the following script should give you the expected result. The key is to turn off the divergence correction for the exchange energy by setting `exxdiv=None`.
```
import numpy as np
from pyscf.pbc import gto, scf

cell = gto.Cell()
cell.atom = """
H 0 0 0
H 0 0 1
"""
cell.basis ='sto-3g'
cell.a = np.eye(3)*3
cell.verbose = 4
cell.build()

kpts = cell.make_kpts([2,2,2])
mf = scf.KRHF(cell, kpts=kpts, exxdiv=None)
mf.kernel()

dm = mf.make_rdm1()
J, K = mf.get_jk(cell,dm, hermi=1, kpts=kpts)

#Performing Check:
#Checking K
df_pbc = mf.with_df
nao = cell.nao
eri_K = []
for i in range(len(kpts)):
    kpts_ijkl = np.array([kpts[0], kpts[i], kpts[i], kpts[0]])
    eri_K.append(df_pbc.get_ao_eri(kpts=kpts_ijkl, compact=False).reshape(nao,nao,nao,nao))

eri_K = np.array(eri_K)
print("ERI tensor shape: ", eri_K.shape)

K_manual = np.einsum("ivk,imvkl->ml", dm, eri_K)/len(kpts)
print("Exchange matrix K shape:", K.shape)
print(K[0].real)
print("Exchange matrix K_manual shape:", K_manual.shape)
print(K_manual.real)

#Checking J
eri_J = []
for i in range(len(kpts)):
    kpts_ijkl = np.array([kpts[0], kpts[0], kpts[i], kpts[i]])
    eri_J.append(df_pbc.get_ao_eri(kpts=kpts_ijkl, compact=False).reshape(nao,nao,nao,nao))

eri_J = np.array(eri_J)
print("ERI tensor shape: ", eri_J.shape)

J_manual = np.einsum("ilk,imvkl->mv", dm, eri_J)/len(kpts)
print("Coulomb matrix J shape:", J.shape)
print(J[0].real)
print("Coulomb matrix J_manual shape:", J_manual.shape)
print(J_manual.real)
```
