### ISSUE TITLE
Allow fci.transform_ci to change number of electrons

### ISSUE THREAD

**Issue by maxnus** [pyscf/pyscf#1259]
As far as I can tell, `pyscf.fci.addons.transform_ci` accepts non-square orbital rotation matrices, `u`,
but it assumes that the number of electrons remains the same in the old and new basis.
How difficult would it be to implement a change of the electron number?
I'm mainly interested in projecting down a FCI WF onto a subspace,
but I guess the case of padding in (uncorrelated) electrons could also be of interest.

**Comment by sunqm** [comment]
transform_ci function is based on the overlap between two determinants. The requirement for det-overlap is that the number of electrons in bra and ket are identical. It is not clear to me how to define the determinant overlap between wavefunction of different number of electrons. I guess you'll need to freeze certain orbitals and treat the wavefunction as a CASCI wavefunction. Then the projection can be carried out in the active space
