### ISSUE TITLE
Positive electronic energy in pyscf.pbc.scf.KRHF

### ISSUE THREAD

**Issue by auroraustc** [pyscf/pyscf#1268]
Greetings. I encountered a problem that the `pyscf.pbc.scf.KRHF` gives positive electronic energies. Is this a normal behaviour?

Code to reproduce:
```python
import pyscf.pbc

geometry = [
        ["C", [0.0, 0.0, 0.0]],
        ["C", [1.261124849, 0.728110850, 0.514852166]],
    ]
lattice_vec = [
        [2.5222499371, 0.0, 0.0],
        [1.2611248231, 2.1843326041, 0.0],
        [1.2611248231, 0.7281108121, 2.0594085488],
    ]
nks = [1, 1, 1]
basis: str = "gth-szv"
pseudo: str = "gth-pade"
cell = pyscf.pbc.gto.M(
        atom=geometry,
        a=lattice_vec,
        basis=basis,
        pseudo=pseudo,
        spin=0
    )
kpts = cell.make_kpts(nks, scaled_center=[0, 0, 0], wrap_around=True)
kmf = pyscf.pbc.scf.KRHF(cell, kpts, exxdiv=None).run()
print("Energy elec: ", kmf.energy_elec()[0])
```
The output is:
```python
Energy elec:  5.369956760779578
```

Changing the basis set to gth-dzvp or nks to [2, 2, 2] / [3, 3, 3] still gives positive electronic energies.

This is the geometry of the input cell:
![image](https://user-images.githubusercontent.com/45780667/171194373-f4a927a4-a0aa-48a7-bf6b-909e8c964984.png)

**Comment by sunqm** [comment]
It is normal that energy_elec() function returns a positive value. This value is not comparable to the electronic energy obtained in molecular system. In PBC calculations, an infinite number corresponding to the diverged Coulomb interactions is always added to the electronic energy to remove divergence. You should read kmf.e_tot for the total HF energy
