### ISSUE TITLE
Unclear how to uninstall from source.

### ISSUE THREAD

**Issue by MarcoBarroca** [pyscf/pyscf#1273]
Not sure if this is a relevant issue, but it seems unclear how one would uninstall pyscf if they installed by compiling it from source using the documentation: https://pyscf.org/install#cmake-options-and-compiling-flags

I'm actually trying to do this right now. Is this as simple as deleting the cloned repo?

`make uninstall` doesn't seem to work.

**Comment by hebrewsnabla** [comment]
Suppose "install" refers to `cmake .. && make`, then if you want to undo `make`, you can `make clean`(this will also delete the auto-download dependencies like libcint). If you want to undo `cmake ..`, as far as i know the only way is to remove everything in `build`.

**Comment by jamesETsmith** [comment]
Adding on to @hebrewsnabla's comments, my usual steps for a totally clean build are:

```bash
# from the pyscf/pyscf/lib directory
rm -rf deps build *.so
```

This means that you'll have to recompile `libcint`, `xcfun`, and `libxc` (on top of all of PySCF). You don't have to delete the PySCF repo.

**Comment by MarcoBarroca** [comment]
Thanks for the replies, it seems easier than I expected. I'll close this issue!
