### ISSUE TITLE
How the symmetry in tensor contraction in CCSD(T) was utilized?

### ISSUE THREAD

**Issue by Lancashire3001** [pyscf/pyscf#1278]
Hi,

  Out of curiosity, may I know how the tensor contraction in CCSD(T) utilized symmetry? https://github.com/CrawfordGroup/ProgrammingProjects/tree/master/Project%2306
  The equations include contractions between T2 and two-electron integrals, which have symmetries.

  In https://github.com/pyscf/pyscf/blob/1e45505a94f23198d0ec464107c12d29d4d9aa16/pyscf/cc/uccsd_t.py#L170
  I found ` def contract(et_sum, a0, a1, b0, b1, cache):`, but was unable to further understand how the symmetry was used. From what I understood, there is few support for symmetry in the einsum. So I would like to know how it was done in PySCF?

  If I searched for ccsd, I found
https://github.com/pyscf/pyscf/blob/1e45505a94f23198d0ec464107c12d29d4d9aa16/pyscf/lib/numpy_helper.py#L805

  `  _np_helper.NPdgemm(ctypes.c_char(trans_b.encode('ascii')),`
  Does `PySCF` adopt sort of cython to load `DGEMM`?

**Comment by sunqm** [comment]
a>b>c was utilized in the t3 tensor (ijkabc) for the permutation symmetry in contraction. The permutation algorithm was implemented in the c code pyscf/lib/cc/ccsd_t.c and pyscf/lib/cc/uccsd_t.c.

pyscf uses ctypes library to call c functions.
