### ISSUE TITLE
Obtaining <r^n> expectation values

### ISSUE THREAD

**Issue by szgoger** [pyscf/pyscf#1289]
Hello,

This is more of a question than an issue, but I saw some other technical questions being answered here so I've decided to try asking mine - sorry if this is not the proper channel for it.

I want to be able to calculate the expectation value of the (scalar) operator r^n with arbitrary power. So far I came up with the following code, that supposedly numerically integrates the operator with the electron density on a real space grid

````
from pyscf import gto, scf, cc, dft
import numpy as np

mol = gto.M(
            atom = 'H 0 0 0',  # in Angstrom
            basis = 'aug-cc-pvqz',
            spin = 1
                    )
mf = scf.UHF(mol).run()
mycc = cc.UCCSD(mf)
mycc.kernel()
print('CCSD total energy', mycc.e_tot)

grid = dft.gen_grid.Grids(mol)
grid.level = 8
grid.build()

r = np.linalg.norm(grid.coords, axis=1)
rn = np.power(r,2)

combined = grid.weights * rn

dm1 = mycc.make_rdm1()[0] + mycc.make_rdm1()[1]
ao_value =  dft.numint.eval_ao(mol, grid.coords, deriv=0)

rho = dft.numint.eval_rho(mol, ao_value, dm1)

integral = np.dot(rho.T, combined.T)
print(integral)
````

I've taken hydrogen as an example since the result is known analytically - even though coupled cluster doesn't make too much sense here, but I want to have a general code. So the number that I am getting for <r^2> is very far from the known result of 3, so there's clearly something wrong. If I set the power from 2 to 0, that is, I evaluate <r^0> I get the number of electrons correctly, so I assume my densities are correct, and I am making a mistake in discretizing the operator somehow.

Could someone, who has some experience in evaluating similar expectation values, point me to the right direction?

**Comment by hebrewsnabla** [comment]
Because CC's make_rdm1 is in MO-basis, while SCF's make_rdm1 is in AO-basis

**Comment by szgoger** [comment]
That's an important distinction that I've glossed over, thank you. However I don't think that explains why the current code doesn't work.

**Comment by hebrewsnabla** [comment]
> That's an important distinction that I've glossed over, thank you. However I don't think that explains why the current code doesn't work.

`rho = dft.numint.eval_rho(mol, ao_value, dm1)` indicates that dm1 is in AO-basis. If you transform it into AO-basis, everything works fine (I've tested that).

**Comment by susilehtola** [comment]
Note that for even values of `n` you should also be able to evaluate the expectation values analytically, since e.g. `<r^2> = <x^2> + <y^2> + <z^2>` and the three expectation values on the right-hand side are just the diagonal of the second moment matrices, which I assume can be found in `libcint`.

**Comment by szgoger** [comment]
> > That's an important distinction that I've glossed over, thank you. However I don't think that explains why the current code doesn't work.
> 
> `rho = dft.numint.eval_rho(mol, ao_value, dm1)` indicates that dm1 is in AO-basis. If you transform it into AO-basis, everything works fine (I've tested that).

Could you point me to the right functions that one would use to have everything in a consistent (AO) Basis so that the matrix element would be evaluated directly? I'm having a hard time navigating the manual for this issue.

**Comment by Majokux** [comment]
Try `mol.intor_symmetric('int1e_r2')`
You can find a list of available integrals here: https://github.com/pyscf/pyscf/blob/master/pyscf/gto/moleintor.py

**Comment by szgoger** [comment]
> Try `mol.intor_symmetric('int1e_r2')` You can find a list of available integrals here: https://github.com/pyscf/pyscf/blob/master/pyscf/gto/moleintor.py

That looks like a nice solution for n=2. Do you think it's simple to generalize to any n?

**Comment by hebrewsnabla** [comment]
> > > That's an important distinction that I've glossed over, thank you. However I don't think that explains why the current code doesn't work.
> > 
> > 
> > `rho = dft.numint.eval_rho(mol, ao_value, dm1)` indicates that dm1 is in AO-basis. If you transform it into AO-basis, everything works fine (I've tested that).
> 
> Could you point me to the right functions that one would use to have everything in a consistent (AO) Basis so that the matrix element would be evaluated directly? I'm having a hard time navigating the manual for this issue.

Hi, a simple way is
```
dm1s = mycc.make_rdm1(ao_repr=True)
dm1 = dm1s[0] + dm1s[1]
```
or, manual transformation is also ok, as this example do (but this one is RCCSD. For UCCSD, two spin conponents both need to be transformed) 
https://github.com/pyscf/pyscf/blob/b43166583a4f609e48ef9f61b8e6d60d8205adbb/examples/cc/01-density_matrix.py#L22
https://github.com/pyscf/pyscf/blob/b43166583a4f609e48ef9f61b8e6d60d8205adbb/examples/cc/01-density_matrix.py#L38-L40
