### ISSUE TITLE
Error in the df-MP2 code

### ISSUE THREAD

**Issue by Schneckhammer** [pyscf/pyscf#1292]
If I am not wrong, there is a slight mistake in the dfmp2_native.py code in the mp module. If using SCS-MP2 and calculating Gamma, it uses this line (line 579 in dfmp2_native.py as is on the master branch):
```
TCijab_scal = 4.0 * (pt + pt) * tbatch[jj] - 4.0 * pt * tbatch[jj].T
```

I believe, it should go as
```
TCijab_scal = 4.0 * (pt + ps) * tbatch[jj] - 4.0 * pt * tbatch[jj].T
```
instead.

**Comment by hongzhouye** [comment]
I think so. The amplitude for SCS is `(pss + pos) t_ijab - pss t_ijba` which matches the proposed new formula.
