### ISSUE TITLE
Tests are flaky

### ISSUE THREAD

**Issue by BastianZim** [pyscf/pyscf#1295]
Hi,

this is for the conda-forge distribution.

I am running the tests here and they are quite flaky. It would be nice to have an environment variable that would allow me to only run deterministic tests only or would it be possible to add more leeway to the tests?

Logs of one run: https://github.com/conda-forge/pyscf-feedstock/pull/5

**Comment by sunqm** [comment]
Tests were cleaned up. Except Mac OS on which the pipeline sometimes crashes with reasons unclear, tests on linux should be more stable than before

**Comment by BastianZim** [comment]
Thanks!
