### ISSUE TITLE
Meaning of extra integer in dyall's set and faegre set

### ISSUE THREAD

**Issue by xubwa** [pyscf/pyscf#1298]
Hi all, 
I'm recently using some dyall's set that is not already in pyscf. When I check the internal provided dyall's set structure, I noticed that there is an extra integer in the dyall's set data.
The internal format of pyscf basis should looks like [ang_momentem, [primitive, contr_coeffs, ...]], but the uncontracted dyall's set looks like [ang_momentem, 0, [primitive, 1]], and meanwhile, in the faegre set, that number is not always 0, but can sometimes be -1. Anyone know about what that extra parameter is used for in those basis sets?
Best,
Xubo

**Comment by sunqm** [comment]
It's "kappa" which has the value  -l-1 (~ j=l+1/2) or l (~ j=l-1/2) or 0. Certain relativistic basis sets have different basis for  j=l+1/2 and j=l-1/2 spinors. When kappa is set to 0, the default case for most basis functions, j=l+1/2 and j=l-1/2 use the same basis

**Comment by xubwa** [comment]
So if the Dyall's contraction for different j was used then the kappa should be labeled, if as in my recent pull request for Dyall's set #1300 , since only primitives are included in the basis set files, then it should be okay to just leave the kappa to be 0 right?

**Comment by sunqm** [comment]
No problem to put 0 there. For s type basis, only kappa=-1 (s_{1/2} basis} will be generated. So value 0 and -1 have the same output
