### ISSUE TITLE
How Can use Fe with basis 6-311+g(d,p) ?

### ISSUE THREAD

**Issue by johTin** [pyscf/pyscf#1299]
Hello,
I do a DFT calculation for a molecule with iron atoms, but there is an error using the basis 6-311+g(d,p) " Basis not found for  Fe"
but it works for the other atoms 
how can i correct this?
thanks

**Comment by jamesETsmith** [comment]
@johTin, as a general comment, you can use PySCF's interface with the Basis Set Exchange (BSE) to get the basis sets that aren't contained in PySCF. See the example:

https://github.com/pyscf/pyscf/blob/98eb8dacc12d43371c988123bb4cdf38f5a3ebbc/examples/gto/31-basis_set_exchange.py#L17-L33

However, after some searching on BSE's [website](https://www.basissetexchange.org/), it looks like they don't have that basis for iron either so it looks like you're out of luck unless you can find the basis set files somewhere else.

**Comment by johTin** [comment]
thank you for your reply [jamesETsmith](https://github.com/jamesETsmith)
