### ISSUE TITLE
How can I obtain and plot the UV-VIS , IR and NMR spectrum

### ISSUE THREAD

**Issue by johTin** [pyscf/pyscf#1302]
Hello every body,
I do some jobs using Pyscf and I want to trace some spectrums, how can i do?
 or is there any soft or programs to extract them from log or chk files ?

thanks

**Comment by hebrewsnabla** [comment]
For IR and NMR, see https://github.com/pyscf/properties/tree/master/examples.
For UV-VIS, see https://github.com/pyscf/pyscf/blob/master/examples/tddft/00-simple_tddft.py.
These examples only output the spectrum data but no spectrum graph. You need to plot it by yourself (with matplotlib, etc.) or with some programs, like Multiwfn.

**Comment by johTin** [comment]
[hebrewsnabla](https://github.com/hebrewsnabla) Thank you for answering

**Comment by jamesETsmith** [comment]
To add to @hebrewsnabla's answer, [here's a rudimentary example](https://github.com/jamesETsmith/2022_simons_collab_pyscf_workshop/blob/main/demos/05_Excited_States.ipynb) of how one could plot the electronic excitation spectra after running TD-DFT in PySCF.

**Comment by hebrewsnabla** [comment]
Maybe there should be a pyscf/plot extension to hold the plotting scripts :rofl:

**Comment by hebrewsnabla** [comment]
I forgot one thing: plotting IR requires IR intensity, which has not been merged yet in properties: https://github.com/pyscf/properties/pull/1
See also #678 .

**Comment by AMDALI** [comment]
Hello  [jamesETsmith](https://github.com/jamesETsmith) the exemple use in this https://github.com/pyscf/pyscf/issues/1302#issuecomment-1165848792 interests me, but the my problem that i use VS code for my work and the py3dmol work with notebook, 
is ther any way is there a way to do it for VS code ?
THANKS
