### ISSUE TITLE
ECP Numerical Accuracy

### ISSUE THREAD

**Issue by JonathonMisiewicz** [pyscf/pyscf#1303]
I'm a Psi4 developer. We recently received a report of differences between scalar ECP matrix elements of Psi4 and PySCF, in the seventh decimal place. I am not an ECP specialist but would like to know the origin of this disagreement, to rule out a bug in our external ECP library. On Psi's side, when we increase our numerical integration grid for ECPs, we do see changes in our matrix elements, but several orders of magnitude smaller than the observed discrepancy, which has me looking to PySCF.

When I call `mol.intor('ECPscalar')`, what accuracy should I expect of the resulting integrals? Is there a way to increase the accuracy, for benchmark purposes? While I've found an ECP section [in the documentation](https://pyscf.org/pyscf_api_docs/pyscf.gto.html#module-pyscf.gto.ecp), I'm unable to even tell if these integrals are computed numerically or using some analytic formula.

**Comment by sunqm** [comment]
In https://github.com/pyscf/pyscf/blob/master/pyscf/lib/gto/nr_ecp.c#L57
You can set LEVEL0 to 11 and LEVEL_MAX to a larger number . The number of grids on radial part was increased from 2^LEVEL0 to 2^LEVEL_MAX .

**Comment by verena-neufeld** [comment]
@JonathonMisiewicz , has this been resolved?

**Comment by JonathonMisiewicz** [comment]
> @JonathonMisiewicz , has this been resolved?

The remainder of this week is devoted to a grant, so I'll run the last set of checks next Monday. Thanks for the reminder - I empathize with wanting to cull the issue backlog.

**Comment by JonathonMisiewicz** [comment]
I'm attempting to run those final checks, but I'm encountering a different error. The following script:
```
from pyscf import gto

geom = """Fe     0.000000    0.000000    0.000000
C      0.000000    1.811939    0.000000
C      1.569185   -0.905970    0.000000
C     -1.569185   -0.905970    0.000000
C      0.000000    0.000000    1.814011
C      0.000000    0.000000   -1.814011
O      0.000000    2.977582    0.000000
O      2.578662   -1.488791    0.000000
O     -2.578662   -1.488791    0.000000
O      0.000000    0.000000    2.976843
O      0.000000    0.000000   -2.976843"""
geom = geom.replace("\n", ";")
mol = gto.Mole()
mol.build(
    atom = geom,  # in Angstrom
    basis = 'lanl2dz',
    symmetry = False,
)
mol.charge = 1
print(mol.intor('ECPScalar'))
```
gives me `pyscf/lib/libcgto.so: undefined symbol: ECPScalar_sph` using Pyscf 2.2.1 via pip on LInux. What am I missing?

**Comment by sunqm** [comment]
`mol.intor('ECPscalar')`

**Comment by JonathonMisiewicz** [comment]
Thanks for the assistance so far.

> In https://github.com/pyscf/pyscf/blob/master/pyscf/lib/gto/nr_ecp.c#L57 You can set LEVEL0 to 11 and LEVEL_MAX to a larger number . The number of grids on radial part was increased from 2^LEVEL0 to 2^LEVEL_MAX .


When I try increasing LEVEL_MAX to a larger number (such as 12), I get the warning:
```/home/jonathon/bin/pyscf/pyscf/lib/gto/nr_ecp.c: In function 'ECPscalar_optimizer':
/home/jonathon/bin/pyscf/pyscf/lib/gto/nr_ecp.c:6407:52: warning: iteration 2048 invokes undefined behavior [-Waggressive-loop-optimizations]
                         r2 = rs_gauss_chebyshev2047[i]*rs_gauss_chebyshev2047[i];
                              ~~~~~~~~~~~~~~~~~~~~~~^~~
/home/jonathon/bin/pyscf/pyscf/lib/gto/nr_ecp.c:6406:17: note: within this loop
                 for (i = 0; i < (1 << LEVEL_MAX); i++) {
```

Is this something I should worry about?

**Comment by sunqm** [comment]
The quadrature roots and weights https://github.com/pyscf/pyscf/blob/72b045a791086017f1d406476d2a02db7bff640e/pyscf/lib/gto/nr_ecp.c#L3638
https://github.com/pyscf/pyscf/blob/72b045a791086017f1d406476d2a02db7bff640e/pyscf/lib/gto/nr_ecp.c#L4050
should be regenerated for more grids. For example, you can call `dft.radi.gauss_chebyshev(4096)` to generate them.
