### ISSUE TITLE
Cubegen same problem when use unstricted KS

### ISSUE THREAD

**Issue by AMDALI** [pyscf/pyscf#1305]
Hi
I always have a the same problem with cubegen when I use UKS  **can only concatenate str (not "type") to str**
Here is my used code :
mf = dft.UKS(Mol)
mf.xc = 'B3LYP'
mf.run()

for Apha
cubegen.density(Mol_Fe3a, strpath + str + '_B3LYP_Alpha_dens.cube', mf.make_rdm1()[0])
cubegen.mep(Mol_Fe3a, strpath +str + '_B3LYP_Alpha_pot_mep.cube', mf.make_rdm1()[0])
cubegen.orbital(Mol_Fe3a, strpath + str + '_B3LYP_Alpha_mo1_orb.cube', mf.mo_coeff[0][:,0])
For beta
cubegen.density(Mol_Fe3a, strpath + str + '_B3LYP_Beta_dens.cube', mf.make_rdm1()[1])
cubegen.mep(Mol_Fe3a, strpath +str + '_B3LYP_Beta_pot_mep.cube', mf.make_rdm1()[1])
cubegen.orbital(Mol_Fe3a, strpath + str + '_B3LYP_Beta_mo1_orb.cube', mf.mo_coeff[1][:,0])
Ihave take this code from this issue: Errors when on create cubgen and molden files #1245

can some one help ?

**Comment by susilehtola** [comment]
You have not included the definitions of `strpath` or `str` in your excerpt. The problem is probably in the second argument to `cubegen`: [`str` is a Python text sequence type](https://docs.python.org/3/library/stdtypes.html#str).

**Comment by AMDALI** [comment]
thanks [susilehtola](https://github.com/susilehtola), this one ESCAPED ME, I think I manipulate too many variables, it's stupid .
thanks
