### ISSUE TITLE
pyscf 2.0.1 requires cmake 3.22.1 (or at least, does not build with 3.10.2)

### ISSUE THREAD

**Issue by chetmurthy** [pyscf/pyscf#1307]
building in the usual way ("pip install ."), I got
```
  Ã python setup.py bdist_wheel did not run successfully.
  â exit code: 1
  â°â> [8 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Configuring extensions
      cmake -S/home/chetsky/Hack/IBMQ/src/pyscf/pyscf/lib -Bbuild/temp.linux-x86_64-3.10
      CMake Error: The source directory "" does not exist.
      Specify --help for usage, or press the help button on the CMake GUI.
      error: command '/usr/bin/cmake' failed with exit code 1
```
with cmake version 3.10.2.  I then added a build of cmake 4.22.1 to my path, and the same command proceeds without problem.

This older version of cmake was found on Ubuntu 18.04.  I don't know if there's a way to make a requirement for this, but I figured I should report it.

**Comment by sunqm** [comment]
The "-B" and "-S" flags were supported by quite old version of cmake, probably 2.6 or 2.8. I'm not sure why the cmake command from ubuntu 18.04 does not support the two. The pip setup script will not be updated for this particular cmake version.
