### ISSUE TITLE
Wrong examples of eval_xc function

### ISSUE THREAD

**Issue by ruthenium96** [pyscf/pyscf#1309]
Hello!

At function https://github.com/pyscf/pyscf/blob/f985dde7358409e4e71095575172327af795a6cb/pyscf/dft/libxc.py#L1669 there is an example of implementation of eval_xc function: https://github.com/pyscf/pyscf/blob/f985dde7358409e4e71095575172327af795a6cb/pyscf/dft/libxc.py#L1701-L1707

One can think, based on this example, that vrho is derivative from exc with respect to rho.

So I've tried to reproduce LDA_X functional for water:
```
water = """
O        0.000000000      0.000000000      0.000000000;
H        0.000000000      1.434938863      1.126357947;
H        0.000000000     -1.434938863      1.126357947
"""
mol = pyscf.gto.M(atom = water, basis="6-31G", unit="Bohr")
```

```
from math import pi

factor = -3.0/4.0 * (3.0 / pi)**(1.0/3.0)
power = 4.0/3.0

def my_eval_xc(a,p):    
    def eval_xc(xc_code, rho, *args, **kwargs):
        exc = a * rho ** p
        vrho = a * p * rho ** (p-1.0)
        vxc = (vrho, None, None, None)
        fxc = None  # 2nd order functional derivative
        kxc = None  # 3rd order functional derivative
        return exc, vxc, fxc, kxc
    return eval_xc

mf = pyscf.dft.RKS(mol)
mf = mf.define_xc_(my_eval_xc(factor,power), 'LDA')
mf.kernel()
```
Result: `-311.0600889240157`
Let's compare with pre-defined LDA functional:
```
ks = dft.RKS(mol)
ks.xc = "lda,"
ks.kernel()
```
Result: `-75.15470534035704`.
The results is not the same. The reason is simple -- actually, vrho is NOT derivative from exc with respect to rho, but from exc*rho. Correct reproducing of LDA is:
```
def my_eval_xc_correct(a,p):    
    def eval_xc(xc_code, rho, *args, **kwargs):
        exc = a * rho ** (p-1.0)
        vrho = a * p * rho ** (p-1.0)
        vxc = (vrho, None, None, None)
        fxc = None  # 2nd order functional derivative
        kxc = None  # 3rd order functional derivative
        return exc, vxc, fxc, kxc
    return eval_xc

mf_correct = pyscf.dft.RKS(mol)
mf_correct = mf_correct.define_xc_(my_eval_xc_correct(factor,power), 'LDA')
mf_correct.kernel()
```
And results: `-75.154705340357`.
So for functional from example `exc = 0.01 * rho**2` leads to `vrho = 0.01 * 3 * rho**2`

The same error occurs in https://github.com/pyscf/pyscf/blob/f985dde7358409e4e71095575172327af795a6cb/examples/dft/24-define_xc_functional.py#L28-L47

Could you, please, fix it?

**Comment by fishjojo** [comment]
You are right, `exc` is the XC energy density. The example in the docstring need to be fixed.
