### ISSUE TITLE
MC-PDFT module in PySCF

### ISSUE THREAD

**Issue by MatthewRHermes** [pyscf/pyscf#1312]
Hello,

I've made a [PySCF extension module](https://github.com/MatthewRHermes/mcpdft) project containing the multiconfiguration pair-density functional theory and multiconfiguration density-coherence functional theory (MC-PDFT and MC-DCFT) implementations originally developed in the [*mrh*](https://github.com/MatthewRHermes/mrh) research code package, following the [instructions](https://pyscf.org/contributing.html) on the pyscf.org website and with the consent of all contributors to the *mrh* code. This module stands on its own without any dependencies on *mrh*. It includes all of the features reported in [*JPCL* **2020**, *11*, 10158](http://dx.doi.org/10.1021/acs.jpclett.0c02956), [*JCP* **2020**, *153*, 014106](http://dx.doi.org/10.1063/5.0007040), [*JCTC* **2021**, *17*, 7586](http://dx.doi.org/10.1021/acs.jctc.1c00915), and [*JCTC* **2021**, *17*, 2775](http://dx.doi.org/10.1021/acs.jctc.0c01346). Could this be hosted on github.com/pyscf as an official extension module? Is there anything else we need to do to facilitate this?

I look forward to the upcoming PySCF developers' conference later this month and I hope I get a chance to speak about these developments there.

Thanks in advance,
- MRH

cc: @thaiscott @Dayou-Zhang @aolykhin

(Edited 07/13/2022: fix one mixed up one citation.)

**Comment by MatthewRHermes** [comment]
Can I reopen this issue now that v2.1 is out? Would the maintainers be willing to host this module on github.com/pyscf, or would they prefer I make a pull request against pyscf-forge? Or would they be willing to host MC-PDFT as a core module?

**Comment by sunqm** [comment]
@MatthewRHermes can we mark this issue resolved for the moment as MC-PDFT is now available on pyscf-forge?

**Comment by MatthewRHermes** [comment]
yes
