### ISSUE TITLE
PBC-kHF fock operator for MP2 residual

### ISSUE THREAD

**Issue by zltemp** [pyscf/pyscf#1316]
Hi everyone. I'm trying to obtain the PBC-MP2 residual, which is:
![Screenshot from 2022-07-04 21-12-34](https://user-images.githubusercontent.com/87129615/177162266-2bed9110-c652-41a6-85a9-c96d20acef10.png)
(I know it is the non-PBC residual equation. I put it here only as an example.)
But when doing so, I noticed that the fock operators (f_{ac} / f_{cb} or f_{ik} / f_{kj} ) are not explicitly provided by Pyscf's PBC-kHF calculation. (Correct me if I'm wrong.) I wonder if there is a way to obtain this term? Or it is just not available?
Thank you!

**Comment by Majokux** [comment]
You can get the Fock matrix elements by calling `mf.get_fock()` - for HF with k-points this will return a `(Nk, Nao, Nao)`
array, with the first dimension corresponding to the k-points, and the latter two to the crystalline Gaussian basis functions.

**Comment by Majokux** [comment]
The Fock matrix is diagonal in k-space - if the k-points are different, the Fock matrix is zero.

**Comment by zltemp** [comment]
> The Fock matrix is diagonal in k-space - if the k-points are different, the Fock matrix is zero.

I see. Thank you for your swift reply. I will try it.
