### ISSUE TITLE
Command $ pip install pyscf[all] will downgrade pyscf

### ISSUE THREAD

**Issue by APerfectDayElise** [pyscf/pyscf#1324]
Hi,
    I just found an issue here, after installing pyscf 2.0 using command:

    > $ pip install pyscf

then use the following command to install all extension modules:

    > $ pip install pyscf[all]

the command above will downgrade pyscf from 2.0 to 1.7.6 which can be seen as follows:

> Requirement already satisfied: pyscf[all] in ./.conda/envs/PYSCF/lib/python3.8/site-packages (2.0.1)
> Requirement already satisfied: numpy!=1.16,!=1.17,>=1.13 in ./.conda/envs/PYSCF/lib/python3.8/site-packages (from pyscf[all]) (1.22.3)
> Requirement already satisfied: scipy!=1.5.0,!=1.5.1 in ./.conda/envs/PYSCF/lib/python3.8/site-packages (from pyscf[all]) (1.6.2)
> Requirement already satisfied: h5py>=2.7 in ./.conda/envs/PYSCF/lib/python3.8/site-packages (from pyscf[all]) (3.6.0)
> Collecting pyberny>=0.6.2
>   Downloading pyberny-0.6.3-py3-none-any.whl (27 kB)
> Collecting pyscf-doci
>   Downloading pyscf-doci-0.1.0.tar.gz (9.0 kB)
>   Preparing metadata (setup.py) ... done
> Collecting pyscf[all]
>   Downloading pyscf-2.0.0-cp38-cp38-manylinux1_x86_64.whl (40.9 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 MB 6.9 MB/s eta 0:00:00
>   Downloading pyscf-1.7.6.post1-cp38-cp38-manylinux1_x86_64.whl (29.7 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.7/29.7 MB 7.2 MB/s eta 0:00:00
> WARNING: pyscf 1.7.6.post1 does not provide the extra 'all'
> Installing collected packages: pyscf
>   Attempting uninstall: pyscf
>     Found existing installation: pyscf 2.0.1
>     Uninstalling pyscf-2.0.1:
>       Successfully uninstalled pyscf-2.0.1
> Successfully installed pyscf-1.7.6.post1

**Comment by hebrewsnabla** [comment]
This has been mentioned in #1243 . Hope this can be fixed soon.
