### ISSUE TITLE
Question about eval_xc

### ISSUE THREAD

**Issue by bookcherry** [pyscf/pyscf#1328]
In the function pyscf.dft.libxc.eval_xc(), we use ex, vxc. fxc, kxc.
What do these variables mean? 
The explanation of API is as follows, but I didn't understand this. Furthermore, for example
The description says vxc = (vrho, vsigma, vlapl, vtau), but what does each element represent?
If there is a pdf or site that explains them in detail, I would appreciate it if you could let me know.
```
Returns:
ex, vxc, fxc, kxc

where

vxc = (vrho, vsigma, vlapl, vtau) for restricted case

vxc for unrestricted case | vrho[:,2] = (u, d) | vsigma[:,3] = (uu, ud, dd) | vlapl[:,2] = (u, d) | vtau[:,2] = (u, d)

fxc for restricted case: (v2rho2, v2rhosigma, v2sigma2, v2lapl2, vtau2, v2rholapl, v2rhotau, v2lapltau, v2sigmalapl, v2sigmatau)

fxc for unrestricted case: | v2rho2[:,3] = (u_u, u_d, d_d) | v2rhosigma[:,6] = (u_uu, u_ud, u_dd, d_uu, d_ud, d_dd) | v2sigma2[:,6] = (uu_uu, uu_ud, uu_dd, ud_ud, ud_dd, dd_dd) | v2lapl2[:,3] | vtau2[:,3] | v2rholapl[:,4] | v2rhotau[:,4] | v2lapltau[:,4] | v2sigmalapl[:,6] | v2sigmatau[:,6]

kxc for restricted case: (v3rho3, v3rho2sigma, v3rhosigma2, v3sigma3)

kxc for unrestricted case: | v3rho3[:,4] = (u_u_u, u_u_d, u_d_d, d_d_d) | v3rho2sigma[:,9] = (u_u_uu, u_u_ud, u_u_dd, u_d_uu, u_d_ud, u_d_dd, d_d_uu, d_d_ud, d_d_dd) | v3rhosigma2[:,12] = (u_uu_uu, u_uu_ud, u_uu_dd, u_ud_ud, u_ud_dd, u_dd_dd, d_uu_uu, d_uu_ud, d_uu_dd, d_ud_ud, d_ud_dd, d_dd_dd) | v3sigma3[:,10] = (uu_uu_uu, uu_uu_ud, uu_uu_dd, uu_ud_ud, uu_ud_dd, uu_dd_dd, ud_ud_ud, ud_ud_dd, ud_dd_dd, dd_dd_dd)

see also libxc_itrf.c
```

**Comment by hebrewsnabla** [comment]
See https://www.tddft.org/programs/libxc/manual/libxc-5.1.x/#lda
or https://github.com/pyscf/pyscf/blob/master/pyscf/lib/dft/libxc_itrf.c

**Comment by bookcherry** [comment]
Thank you for introducing the website! It was very helpful!

**Comment by bookcherry** [comment]
Thank you for introducing the website! It was very helpful!

**Comment by scohenjanes5** [comment]
> See https://www.tddft.org/programs/libxc/manual/libxc-5.1.x/#lda

This site got domain squatted and is now a list of casinos, but there is thankfully an archive: https://web.archive.org/web/20240221151259/https://www.tddft.org/programs/libxc/manual/libxc-5.1.x/#lda

**Comment by susilehtola** [comment]
> > See https://www.tddft.org/programs/libxc/manual/libxc-5.1.x/#lda
> 
> This site got domain squatted and is now a list of casinos, but there is thankfully an archive: https://web.archive.org/web/20240221151259/https://www.tddft.org/programs/libxc/manual/libxc-5.1.x/#lda

The list of functionals is still online in libxc upstream https://libxc.gitlab.io/functionals/
