### ISSUE TITLE
Save iteration count (cycle) to CCSD object

### ISSUE THREAD

**Issue by kfyharukz** [pyscf/pyscf#1330]
Hi,
In the current codes, the iteration count of CCSD isn't saved; however, it's useful, for example, to judge how complex the target problem is.
I think it's not difficult and can be enabled by small changes [like this code](https://github.com/kfyharukz/pyscf/compare/master...save-cycle-count).

So, can I send a PR?

**Comment by Majokux** [comment]
I personally think it's a good idea and it also applies to all other iterative methods, SCF, CASSCF, etc

However, I think it would be good to bundle such results up a bit more to avoid too many return values and stateful output attributes in the calculation object.
This could be done similar to the [OptimizeResult](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.OptimizeResult.html#scipy.optimize.OptimizeResult) object in SciPy; I would suggest somthing akin to
```
class IterationResults(typing.NamedTuple):
    converged: bool = False
    cycle: int = 0
    status: Optional[str] = None
```
which can be instantiated on CCSD/SCF/....`.__init__` and updated in the respective kernel.

**Comment by kfyharukz** [comment]
It seems good.  I'll prepare PR that way. 😃

**Comment by sunqm** [comment]
Using PR #1351, you can now access the .cycles attribute of the CCSD object to obtain the iteration count.
