### ISSUE TITLE
Selecting orbitals in CASCI with spin!=0

### ISSUE THREAD

**Issue by AlexandreF-1qbit** [pyscf/pyscf#1331]
Hello pyscf developers and users, I have a problem regarding CASCI/CASSCF calculation with `spin!=0`.

## Description
The problem appears when trying to select an active space without the orbitals with occ=1. from an ROHF mean-field (output from `print(myhf.mo_occ)`, should be orbitals=8,9 with base=1). The energy from CASCI is higher than the Hartree-Fock energy (-111.723322367153 > -112.275444059104 in the example below), which is not expected. This is not happening when switching to `spin=0` or selecting an active space containing orbitals 8 and 9.

## Minimal example
```python
from pyscf import gto, scf, mcscf

xyz ="""
C 0. 0. -0.52900402
H 0. 0.93762420 -1.12377976
H 0. -0.93762420 -1.12377976
O 0. 0. 0.67769796
"""

mol = gto.M(
    atom = xyz,
    basis = "sto3g",
    spin=2
    )

myhf = scf.RHF(mol)
myhf.kernel()

active = [7, 10]
mycas = mcscf.CASCI(myhf, 2, 2)
mo = mycas.sort_mo(active)
mycas.kernel(mo)
```

```
converged SCF energy = -112.275444059104
CASCI E = -111.723322367153  E(CI) = -0.843243057452625  S^2 = 2.0000000
```

## More information
Performing the same trick with CCSD is giving consistent results, at least versus the HF energy.

```python
from pyscf import cc
ccsd = cc.CCSD(myhf, frozen=[i for i in range(12) if i+1 not in active])
ccsd.ccsd()
```

```
E(UCCSD) = -112.275526525089  E_corr = -8.246598538875619e-05
```

**Comment by xubwa** [comment]
Hi, the sort_mo function itself takes 1-based orbital indices. So in your minimal example, only if you choose the active space to be (8,9) will you be able to get the energy equal to rohf since this is a triplet state, not the (7,10) that you expected.

**Comment by AlexandreF-1qbit** [comment]
@xubwa Yes this is the case if I am choosing [8, 9], I am getting the ROHF energy. The point is that I am expecting to get an energy a little bit lower than the ROHF energy when choosing [7, 10], not 0.552 Hartree higher (or at least equals to the ROHF if 7 and 10 are not correlated at all).

**Comment by hebrewsnabla** [comment]
triplet CAS(2,2) for [7,10] will be equivalent to another solution of ROHF, have you checked the energy of that?
I think the current result is reasonable. The ROHF solution with SOMO [8,9] should be the lowest CAS(2,2) triplet root, unless the ROHF solution is unstable.

**Comment by xubwa** [comment]
For ccsd, you are still starting from the HF determinant, the hilbert space still contains the HF determinant with a few extras, that's why you are still getting a similar to HF but lower energy. In CASCI, it's like you remove the two active electrons from the hf det and repopulate them in your new active space. Hope this helps you understand where the different comes from.

**Comment by verena-neufeld** [comment]
Hi @AlexandreF-1qbit , thanks for your question. Has it been answered and can this issue be closed?

**Comment by AlexandreF-1qbit** [comment]
Yes, thank you!
