### ISSUE TITLE
Calculate transition dipole moments with CASCI

### ISSUE THREAD

**Issue by jon-392** [pyscf/pyscf#1333]
Hello, I am trying to calculate some transition dipole moments between different the triplet and quintet O2 states but am encountering an error of (assert(ciket.size == na*nb)) when constructing the tRDM. Please advise, many thanks.

My input below:

```
mol = gto.M(
    atom = '''
      8  0  0  0
      8  0  0  1.1''',
    basis = 'ccpvdz',
    spin = 2,
)
mf = scf.RHF(mol)
mf.kernel()

mc = mcscf.CASCI(mf,6,6)
mc.fix_spin_(ss=6)
mc.kernel(mf.mo_coeff)
ci0 = mc.ci

mc.fix_spin_(ss=2)
mc.kernel(mf.mo_coeff)
ci1 = mc.ci

t_dm1 = mc.fcisolver.trans_rdm1(ci1, ci2, mc.ncas, mc.nelecas)
```

**Comment by xubwa** [comment]
There shouldn't be a nonzero trdm between two states of different spins without spin orbit couplings.

**Comment by jon-392** [comment]
But more fundamentally, why does it give an error instead of all zeros?

**Comment by xubwa** [comment]
Well though it may not be clear from the output, this error message is because the size of these two civectors don't match.

**Comment by jon-392** [comment]
Hmm ok.. so even if the trdm is nonzero pyscf will not be able to compute it because of mismatch in civector size

**Comment by xubwa** [comment]
No, if you there is a nonzero trdm, then the spin must match and the size of the ci vector would also match.

**Comment by hebrewsnabla** [comment]
I think there is a workaround to compute this "zero" (although it's meaningless as stated by Xubo):
```
mc = mcscf.CASCI(mf,6,(5,1))
mc.kernel(mf.mo_coeff) # energy of lowest quintet

mc = mcscf.CASCI(mf,6,(5,1))
mc.fcisolver.spin=2
mc.fcisolver.nroots = 10
mc.kernel(mf.mo_coeff) # energy of triplets, quintets, ...
ci1 = mc.ci
# check the output you can find lowest triplet is root 0 and lowest quintet is root 7

t_dm1 = mc.fcisolver.trans_rdm1(ci1[0], ci1[7], mc.ncas, mc.nelecas)
import numpy as np
print(np.linalg.norm(t_dm1))
```
The trick is that you can take roots with different <S^2> from one fcisolver. Then there's no problem with the assertion.

**Comment by sunqm** [comment]
For transition dipole moments, the two CI wave-functions must follow spin conservation and particle number conservation. The transition between states of different spin is forbidden, thus you always get zeros in the transition matrix.  Assuming you are interested in SOC-type of coupling, to compute transition matrix between states of different spin or electron numbers, https://github.com/pyscf/pyscf/blob/master/examples/fci/35-transition_density_matrix.py is a relevant example.
