### ISSUE TITLE
electron density by CCSD and FCI

### ISSUE THREAD

**Issue by bookcherry** [pyscf/pyscf#1334]
How can we get the electron density from CCSD and FCI?
dft.numint.eval_rho() has the density matrix argument, but CCSD and FCI have several density matrices like 1-particle density matrix and 2-particle density matrix.
Can't we use dft.numint.eval_rho() for evaluating the electron density of CCSD and FCI?

**Comment by hebrewsnabla** [comment]
CCSD unrelaxed density matrix is available, see https://github.com/pyscf/pyscf/blob/master/examples/cc/01-density_matrix.py, L40

`mycc.make_rdm1(ao_repr=True)` will give the same result, i think.

FCI density matrix is also available, see https://github.com/pyscf/pyscf/blob/master/examples/fci/14-density_matrix.py . But it's MO-based, you need to transform it into AO basis.

**Comment by hebrewsnabla** [comment]
#1289 may help you, also.

**Comment by yangdatou** [comment]
In order to evaluate the density at specific coordinate, you need the density matrix in AO basis. For example,

```
import numpy
from pyscf import gto, dft
from pyscf import scf, cc
from pyscf.dft import numint

mol = gto.M(
    verbose = 0,
    atom = '''
    o    0    0.       0.
    h    0    -0.757   0.587
    h    0    0.757    0.587''',
    basis = 'sto3g'
)

mf = scf.RHF(mol)
mf.kernel()

mycc  = cc.CCSD(mf).run()
dm_ao = mycc.make_rdm1(ao_repr=True)
```

And then use `numint.eval_rho` 
```
# Use Lebdev grid from RKS object, or use any coords you want to evaluate
mf = dft.RKS(mol)
mf.xc = "LDA"
mf.kernel()

coords   = mf.grids.coords
ao_value = numint.eval_ao(mol, coords, deriv=0)
rho      = numint.eval_rho(mol, ao_value, dm_ao, xctype='LDA')
```
as @hebrewsnabla mentioned, you need to convert FCI density matrix to AO basis by yourself.

If you want to visualize the density,
```
# Use cubic grid to generate cube file
from pyscf.tools import cubegen
cubegen.density(mol, 'h2o_cc_den.cube', dm_ao)
```

**Comment by bookcherry** [comment]
Very helpful! Thank you very much!!
