### ISSUE TITLE
How to get 2 body density matrix after a dft calculation?

### ISSUE THREAD

**Issue by hh2110** [pyscf/pyscf#1337]
Hi all, after running a dft calculation, it is possible to use the `make_rdm1()` method to get the reduced 1 body density matrix, but I cannot seem to get the two body density matrix too - so `get_rdm2()` does not seem to be implemented. Can anyone help me in getting this 2 body density matrix after a dft calculation?

**Comment by Majokux** [comment]
I actually submitted a PR for the HF classes recently [here](https://github.com/pyscf/pyscf/pull/1287)
If this gets accepted, the `make_rdm2` method should also be available for DFT, via inheritance.
In the meantime you can check out the additions in the PR to see how to build it from the 1-DM.
Note that in practice you probably don't need to build the 2-DM in a mean-field method, but simply contract your operator with the product of 1-DMs directly.

**Comment by hh2110** [comment]
Thanks @Majokux  - this helps. One other query please: I need to have the reduced 1 and 2 body density matrices in the molecular orbital basis. As far as I understand, the make_rdm<i> methods return density matrices in the atomic orbtial basis. I understand how to change the basis of the rdm1 but am struggling to figure out how to change the basis of the rdm2 - any chance you can help please?

```
      # get dm's in atomic orbital basis
      rdm1 = self.mean_field.make_rdm1()
      rdm2 = self.mean_field.make_rdm2()
      # need to rotate to molecular orbital basis
      atomic_coeff_matrix = self.mean_field.mo_coeff
      transformed_rdm1 = (
          atomic_coeff_matrix.T
          @ rdm1
          @ atomic_coeff_matrix
      )
      transformed_rdm2 = ?
```

**Comment by Majokux** [comment]
This transformation you show for the 1-RDM is not correct, you need to consider the AO-overlap matrix which you can get from
`mf.get_ovlp()`:
```
dm1_ao = mf.make_rdm1()
r = np.dot(mf.mo_coeff.T, mf.get_ovlp())
dm1_mo = np.linalg.multi_dot((r, dm1_ao, r.T))
```
For the 2-DM you can use the `numpy.einsum` function:
```
dm2_ao = mf.make_rdm2()
r = np.dot(mf.mo_coeff.T, mf.get_ovlp())
dm2_mo = numpy.einsum("abcd,ia,jb,kc,ld->ijkl", dm2_ao, r, r, r, r)
```

Note however that in the MO basis the DMs are very simple and diagonal, and can be build directly:

```
dm1_mo = np.zeros((norb, norb))
for i in range(nocc):
    dm1_mo[i,i] = 2
```
and
```
dm2_mo = np.zeros((norb, norb, norb, norb))
for i in range(nocc):
    for j in range(nocc):
        dm2_mo[i,i,j,j] += 4
        dm2_mo[i,j,j,i] -= 2
```

This is all for restricted spin-symmetry

**Comment by hh2110** [comment]
Thank you for correcting me. Could you please give me a little background or links to the background of how you know that the rotation matrix needs to be `r = np.dot(mf.mo_coeff.T, mf.get_ovlp())`

**Comment by Majokux** [comment]
>Thank you for correcting me. Could you please give me a little background or links to the background of how you know that the rotation matrix needs to be r = np.dot(mf.mo_coeff.T, mf.get_ovlp())
I don't have a good suggestion, maybe Modern Quantum Chemistry by Szabo & Ostlund, but it doesn't cover DFT.
Maybe someone else can chip in

**Comment by tberkel** [comment]
Here's an answer to the same question from StackExchange a year ago:
https://mattermodeling.stackexchange.com/questions/6401/convert-reduced-density-matrix-from-m-o-to-a-o-basis

**Comment by Majokux** [comment]
Thanks Tim for the link.

I guess another way to argue is that the Fock matrix, like the overlap matrix S, is a covariant tensor, whereas
density matrices transform like S^-1 (in particular hole-DM1 + particle-DM1 = S^-1), which must thus be contravariant.
For this reason, an energy like trace(F * DM1) is invariant to basis transformations.
