### ISSUE TITLE
Symmetry-adapted molecular (crystalline) orbitals

### ISSUE THREAD

**Issue by Exferro** [pyscf/pyscf#1339]
Hi everyone!
Could you please tell if there is any way to construct a symmetry-adapted combination of molecular (or crystalline) orbitals and, say, obtain the corresponding change of basis matrix? (from MOs to symmetry-adapted MOs?)

I am asking because I am interested in obtaining a second-quantised Hamiltonian for post-HF calculations in a way which utilizes the largest abelian group of symmetries for the molecular (or, again, crystalline) system — in particular, I would like every MO to belong to a particular irrep, which would allow me to assign a particular irrep to every Slater determinant and thus, for example, limit the set of SDs which can contribute to the ground state.

NB: I am not looking for a way to use symmetries during SCF or any other sort of calculations: I know it's already possible for molecular systems and @fishjojo have replied to me in another thread that this would be available for crystalline systems in the near future, and that'd be great, but for now I'll be happy with just a procedure to obtain the set of symmetry-adapted orbitals — which I believe should be possible regardless of whether SCF accounts for it or not.

I suspect that symm.basis module should have a handful of related functions, but I can't quite figure out how to use them for molecular orbitals (given, say, that I know AO->MO transition matrix and the overlap matrix for AOs) — I would be glad to have any hints or directions.

Thanks!

**Comment by sunqm** [comment]
mol.symm_orb or cell.symm_orb stores all coefficients of the AO to symmetry-adapted orbitals (SO). To construct matrix elements on SO, here is an example
https://github.com/pyscf/pyscf/blob/master/pyscf/scf/hf_symm.py#L309
To create these SO coefficients, you need to specify symmetry=True when creating the `mol` object, such as pyscf/examples/scf/13-symmetry.py . For crystalline SOs at k-points , you need to manually call `cell._build_symmetry(kpts)` . Relevant example is pyscf/examples/pbc/20-k_points_scf_ksymm.py

**Comment by verena-neufeld** [comment]
Hi @Exferro , thanks for your question. Has it been answered?

**Comment by Exferro** [comment]
Hi @verena-neufeld, yes, it seems so; sorry, I haven't seen this reply!
