### ISSUE TITLE
Implement Brueckner coupled cluster (BCCD, aka. BD) or orbital-optimized CC

### ISSUE THREAD

**Issue by TiborGY** [pyscf/pyscf#1343]
As the title says, these methods are currently not available in pyscf.

**Comment by sunqm** [comment]
Not available in current version. This feature can be included in the discussion plan during the developers' meeting #1260

**Comment by gkc1000** [comment]
@zhcui has an implementation of this -- open PR?

**Comment by zhcui** [comment]
> @zhcui has an implementation of this -- open PR?

Yes, we do have both BCCD and OO-CCD. I will open a PR.

**Comment by zhcui** [comment]
Here is an implementation:
https://github.com/pyscf/pyscf/pull/1497
