### ISSUE TITLE
What is the difference when we use cell.dimesnsion=1 for 1D system ?

### ISSUE THREAD

**Issue by Jila66** [pyscf/pyscf#1344]
Hi everyone!

I'm working on 1D and 2D chains using PyScf.

You know setting a larger vacuum size for 1D systems has the high computational cost especially in calculations such as  DMET. 
Could you please tell if there is a way to set the optimal vacuum size or the other helpful way to reduce the computational costs ?

I see there is a keyword dimension that we can set it to 1 for 1D systems . But what is the difference when we set the cell.dimension = 1 for 1D chain of molecule or not ?
For example suppose we have a 1D Hydrogen chain (kpt: [1 1 4] ) in a cell box with 20 A vacuum in X and Y direction. 

Thanks!

**Comment by sunqm** [comment]
If ` cell.dimension = 1` was set, the lattice parameters you specified in Y and Z directions will be ignored by the program.

**Comment by Jila66** [comment]
Thanks Qiming,
Yeah I see that.  But if we set the gdf_mesh manually then what?

**Comment by sunqm** [comment]
This means a larger number of mesh may be needed to converge integrals for Y and Z directions. dimension=1 only excludes the repeated cell images in Y and Z . A large number of mesh points are still required to compute integrals.

**Comment by Jila66** [comment]
Thanks,
