### ISSUE TITLE
How to convert a PYSCF .chk file into a GAUSSIAN readable .chk file?

### ISSUE THREAD

**Issue by zhangshu2058** [pyscf/pyscf#1345]
Hi everyone!

How to convert a PYSCF .chk file into a GAUSSIAN readable .chk file?

Thanks!

**Comment by hebrewsnabla** [comment]
No, you can't.

**Comment by 1234zou** [comment]
The Gaussian .chk file is in binary format, which is not readable. It is the .fch(k) file which is readable.

Although a direct/simple file conversion does not exist currently, a workaround (through .fch file) does exist. For example, one can first run a Gaussian calculation to obtain a .chk or .fch file (usually takes seconds):
```
%chk=h2o_cc-pVDZ.chk
%nprocshared=1
%mem=1GB
#p RHF/cc-pVDZ nosymm int=nobasistransform guess(only,save)

title

0 1
O   0.12555391    0.14032496    0.0
H   1.08555391    0.14032496    0.0
H  -0.19490068    1.04526079    0.0

```

then generate the .py file, i.e. run
```
bas_fch2py h2o_cc-pVDZ.chk
```
where you can also use the fch file. Next you modify the .py file to perform your desired calculations in PySCF. Finally, export MOs into fch file via the `py2fch` module. For example,
```
# lines not changed above
dm = mf.make_rdm1()
mf.max_cycle = 10
mf.kernel(dm)

py2fch('h2o_cc-pVDZ.fch',nbf,nif,mf.mo_coeff,'a',mf.mo_occ,True)
```

You may wonder why not directly use `py2fch`. This is because `py2fch` cannot create a fch file from scratch. It can only export MOs and density currently.

**Comment by zhangshu2058** [comment]
Thank you very much, so I can't use the wavefunction generated by the Pyscf as the guess of Gaussian. Thanks again for your reply.



***@***.***
 
Thank you again for your answer
From: jxzou
Date: 2022-07-25 22:06
To: pyscf/pyscf
CC: zhangshu2058; Author
Subject: Re: [pyscf/pyscf] How to convert a PYSCF .chk file into a GAUSSIAN readable .chk file? (Issue #1345)
The Gaussian .chk file is in binary format, which is not readable. It is the .fch(k) file which is readable.
Although a direct/simple file conversion does not exist currently, a workaround (through .fch file) does exist. For example, one can first run a Gaussian calculation to obtain a .chk or .fch file (usually takes seconds):
%chk=h2o_cc-pVDZ.chk
%nprocshared=1
%mem=1GB
#p RHF/cc-pVDZ nosymm int=nobasistransform guess(only,save)
title
0 1
O   0.12555391    0.14032496    0.0
H   1.08555391    0.14032496    0.0
H  -0.19490068    1.04526079    0.0

then generate the .py file, i.e. run
bas_fch2py h2o_cc-pVDZ.chk

where you can also use the fch file. Next you modify the .py file to perform your desired calculations in PySCF. Finally, export MOs into fch file via the py2fch module. For example,
# lines not changed above
dm = mf.make_rdm1()
mf.max_cycle = 10
mf.kernel(dm)
py2fch('h2o_cc-pVDZ.fch',nbf,nif,mf.mo_coeff,'a',mf.mo_occ,True)

You may wonder why not directly use py2fch. This is because py2fch cannot create a fch file from scratch. It can only export MOs and density currently.

**Comment by 1234zou** [comment]
That's not true. You can use the wave function generated by the PySCF as the guess of Gaussian. More specifically, you can use the molecular orbitals (MOs) generated by the PySCF as the guess of Gaussian.

The example shown in my first reply, where `py2fch` is used, it is an example of exporting MOs into fch file, and then you can run an RHF calculation in Gaussian using this updated fch file (note that fch->chk conversion can be accomplished by the `unfchk` utility of Gaussian). You'll find that RHF will converge in 1 cycle, which means that you successfully use the MOs generated by the PySCF.

Similarly, you can export DFT orbitals, MP2 natural orbitals, etc, in this way. Let me further show a somewhat advanced example: first perform CASSCF in PySCF, then export CASSCF orbitals to fch file, and perform OVB-MP2 in Gaussian. (OVB-MP2 is a MRPT2 method based on the CASSCF reference). Files are attached.
[h2o_cc-pVDZ_CAS44.zip](https://github.com/pyscf/pyscf/files/9182892/h2o_cc-pVDZ_CAS44.zip)

in which the files `h2o_cc-pVDZ_rhf_gvb2_CASSCF.py` and `h2o_cc-pVDZ_rhf_gvb2_CASSCF_OVBMP2.gjf` might interests you most.

**Comment by hebrewsnabla** [comment]
Hi @zhangshu2058 , 
Recently @1234zou and me developed a straightforward pyscf-to-fchk interface in [MOKIT](https://gitlab.com/jxzou/mokit). Now, instead of complicated steps metioned by [this comment]( https://github.com/pyscf/pyscf/issues/1345#issuecomment-1194094495 ), you can dump a fch file with only 2 lines of code:
```
from py2fch_direct import fchk
fchk(mf, 'xxx.fch')
```
See example 07 [here](https://gitlab.com/jxzou/mokit/-/blob/master/examples/utilities/readme.txt) for more information.
Feel free to open an issue in MOKIT repo or contact me if you have any question using this utility!

**Comment by changsuc** [comment]
One way I know is to dump a `molden` file in pyscf and convert 'molden' to 'fchk' format. Multiwfn can do it.

**Comment by hebrewsnabla** [comment]
> One way I know is to dump a `molden` file in pyscf and convert 'molden' to 'fchk' format. Multiwfn can do it.

Different programs may have different conventions for molden file. Multiwfn developer has managed to make their molden parser compatible to a few programs. But PySCF is not in their supported list.

Our fchk dump function in [MOKIT](https://gitlab.com/jxzou/mokit), as mentioned above, is native for PySCF and has been tested in various cases.

**Comment by zhangshu2058** [comment]
Thank you very much.



***@***.***
 
From: jxzou
Date: 2022-07-26 00:02
To: pyscf/pyscf
CC: zhangshu2058; Author
Subject: Re: [pyscf/pyscf] How to convert a PYSCF .chk file into a GAUSSIAN readable .chk file? (Issue #1345)
That's not true. You can use the wave function generated by the PySCF as the guess of Gaussian. More specifically, you can use the molecular orbitals (MOs) generated by the PySCF as the guess of Gaussian.
The example shown in my first reply, where py2fch is used, it is an example of exporting MOs into fch file, and then you can run an RHF calculation in Gaussian using this updated fch file (note that fch->chk conversion can be accomplished by the unfchk utility of Gaussian). You'll find that RHF will converge in 1 cycle, which means that you successfully use the MOs generated by the PySCF.
Similarly, you can export DFT orbitals, MP2 natural orbitals, etc, in this way. Let me further show a somewhat advanced example: first perform CASSCF in PySCF, then export CASSCF orbitals to fch file, and perform OVB-MP2 in Gaussian. (OVB-MP2 is a MRPT2 method based on the CASSCF reference). Files are attached.
h2o_cc-pVDZ_CAS44.zip
in which the files h2o_cc-pVDZ_rhf_gvb2_CASSCF.py and h2o_cc-pVDZ_rhf_gvb2_CASSCF_OVBMP2.gjf might interests you most.

**Comment by ndattani** [comment]
@zhangshu2058 I wonder if you think this issue needs to stay "open"? The workaround by hebrewsnabla was designed to allow users to run Gaussian calculations with the information that would normally be in a PySCF `.chk` file.

**Comment by sunqm** [comment]
MOKIT provides a pretty clean solution to parse and manage the Gaussian chk file as well as SCF data of other packages, see for example https://mattermodeling.stackexchange.com/questions/9474/interface-between-pyscf-and-molpro . This library seems enough to solve the current issue
