### ISSUE TITLE
SCF not converged for nitric oxide

### ISSUE THREAD

**Issue by bookcherry** [pyscf/pyscf#1352]
DFT calculation by LDA of NO (nitric oxide) does not converge. I used the following xyz file for the calculation.
```
2
145068
O          0.58250        0.00000        0.00000
N         -0.58250        0.00000        0.00000
```
The setting of the calculation is as as follows.
```
no = gto.M(
        atom = './xyz_dir/NO.xyz',  # in Angstrom
        basis = '6-31G',
        symmetry = True,
        spin = 1
    )
mfl_no.xc='lda'
mfl_no = dft.UKS(no)
mfl_no.kernel()
```
I got this error.
```
SCF not converged.
SCF energy = -128.779691046606 after 50 cycles  <S^2> = 0.76829769  2S+1 = 2.0182147
-128.7796910466055
```
If I use the hybrid functional and comment out "symmetry = True", SCF converged. Why doesn't LDA calculation  converge for nitric oxide?

**Comment by hebrewsnabla** [comment]
First, 'mfl_no.xc = xxx' should be set after mfl_no initialized, otherwise you will get an error.
To solve the convergence problem, just set `mfl_no.level_shift = 0.2`.

**Comment by bookcherry** [comment]
Thank you very much!

**Comment by verena-neufeld** [comment]
This looks resolved.
