### ISSUE TITLE
Overlap matrix (and other 1e integrals) from PySCF and direct calculations do not correspond to each other.

### ISSUE THREAD

**Issue by m-kulichenko** [pyscf/pyscf#1353]
Hello,
I am using a non-orthonormal AO basis for H2 molecule. Then I am extracting the overlap matrix and the diagonal elements are all ones.
```python
mol = gto.Mole()
mol.unit = "Bohr"
mol.build(
    atom = [['H',(0, 0, 0)], ['H',(0.0, 0, 1.)]],
    
    basis = {'H': '''
H    S
     13.00        1.0

H    S
      1.96        1.0
      
H    S
      0.28        1.0
'''},
    charge = 0,
    spin = 0,
)
mf = scf.RHF(mol)
mf.kernel()

Ovr = mol.intor("int1e_ovlp")
np.round(Ovr, 4)
```
Out:
Overlap matrix: 
 [[1.       0.554  0.154  0.002  0.101  0.117]
 [0.554  1.        0.538  0.101  0.375  0.421]
 [0.154  0.538  1.        0.117  0.421  0.869]
 [0.002  0.101  0.117  1.        0.554  0.154]
 [0.101  0.375  0.421  0.554  1.        0.538]
 [0.117  0.421  0.869  0.154  0.538  1.   ]]

However, calculating the overlap matrix elements directly with the formula for s-AO 
![image](https://user-images.githubusercontent.com/67025892/182232068-88b0723a-b043-4f77-8c86-0984d734f67c.png)
gives the following result:
[[ 0.042  0.096   0.115     0.        0.018   0.087]
 [ 0.096  0.717   1.661     0.018  0.269   1.3  ]
 [ 0.115  1.661   13.287   0.087  1.3       11.552]
 [ 0.        0.018   0.087     0.042  0.096   0.115]
 [ 0.018  0.269   1.3         0.096  0.717   1.661]
 [ 0.087  1.3       11.552   0.115  1.661   13.287]]

The same situation is with other 1e and 2e integrals.
Can you please explain what underlying transformations in PySCF code are causing this behavior?

**Comment by fishjojo** [comment]
By default, the GTOs are normalized.
https://github.com/pyscf/pyscf/blob/c6f9b462fca8dcaab633d7306fa6f5121a07c907/pyscf/gto/mole.py#L834-L836
You may turn off the normalization for contracted orbitals, but not for the primitive Gaussians unless you modify the code above.

**Comment by susilehtola** [comment]
> However, calculating the overlap matrix elements directly with the formula for s-AO ![image](https://user-images.githubusercontent.com/67025892/182232068-88b0723a-b043-4f77-8c86-0984d734f67c.png) gives the following result: 

The equation is wrong. Basis functions are defined in terms of normalized primitives.

**Comment by Physfock** [comment]
I resolved the size issue following your advice. However, the problem with calculating the overlap persists, as there is no ci.cisd.overlap class available for GCISD.
