### ISSUE TITLE
Does the HF method support multi-threading?

### ISSUE THREAD

**Issue by frankwswang** [pyscf/pyscf#1360]
Hi! I was testing out `scf.RHF` for its multi-threading performance. I could only find one function `lib.num_threads` in the documentation which seems relevant for the global control of multi-threading in PySCF. 

I tried to increase the value of it, but it didn't seem to improve the speed of the function although I was testing it on a 10-core CPU. Is this the correct parameter to adjust, or is `scf.RHF`'s computation always single-threaded? Thank you!

**Comment by fishjojo** [comment]
you can modify the environment variable OMP_NUM_THREADS to control the number of threads used. If your system is too small, you may not see much difference of speed.

**Comment by frankwswang** [comment]
> you can modify the environment variable OMP_NUM_THREADS to control the number of threads used. If your system is too small, you may not see much difference of speed.

The [documentation](https://pyscf.org/pyscf_api_docs/pyscf.lib.html?highlight=lib+num_threads#pyscf.lib.misc.num_threads) says `lib.num_threads` sets  the OMP thread number like what `OMP_NUM_THREADS` does. Assuming it works, I don't need to modify `OMP_NUM_THREADS` again, correct? 

Also, is this the only parameter I need to modify to get the benefit of multi-threading from PySCF? If so, maybe it is because of the molecular system I tested wasn't big enough.

**Comment by jamesETsmith** [comment]
That's correct, `lib.num_threads` and `OMP_NUM_THREADS` should do the same thing. If `OMP_NUM_THREADS` isn't set, OpenMP should grab all available threads so in practice many users don't ever deal with threads explicitly. A system with several hundred orbitals should be big enough to see the difference.

**Comment by frankwswang** [comment]
> That's correct, `lib.num_threads` and `OMP_NUM_THREADS` should do the same thing. If `OMP_NUM_THREADS` isn't set, OpenMP should grab all available threads so in practice many users don't ever deal with threads explicitly. A system with several hundred orbitals should be big enough to see the difference.

Sounds great! Thank you!
