### ISSUE TITLE
KRCCSD no longer includes ewald correction in total energy

### ISSUE THREAD

**Issue by awhite862** [pyscf/pyscf#1364]
The changes in 5e7fa85f8c8fef25121cbabc9e75b14bf842aef8 make it so that the `e_tot` attribute of KRCCSD does not include the ewald correction as it did in previous versions.

**Comment by verena-neufeld** [comment]
Hi Alec, thanks for your comment! That is correct and is being addressed in PR #1357.

**Comment by verena-neufeld** [comment]
This should be resolved now. Please let me know if not/you run into problems.
