### ISSUE TITLE
ke_guess from estimate_ke_cutoff_for_eta too low

### ISSUE THREAD

**Issue by maxnus** [pyscf/pyscf#1366]
In the PBC calculation below the nuclear potential has an imaginary part at k-points which are self-conjugated (i.e. k = G-k) for some inverse lattice vector G). At these k-points the nuclear potential should be real.

This is however not the case, even with a `cell.precision` of `1e-11`. To remove the imaginary part one has to use `1e-12`, which seems really quite low.  

It seems that the kinetic energy cutoff [here](https://github.com/pyscf/pyscf/blob/2bd16d760ddcbbcec4ca5d7b7b480b953743459b/pyscf/pbc/df/aft.py#L160) is not estimated conservatively enough.

This may be related to the fact that the unit cell below us quite "sharp", with lattice vectors far from being orthogonal (I don't know if a cubic cell was assumed for the ke estimate, just a guess).

```
import numpy as np
import pyscf
import pyscf.pbc
import pyscf.pbc.df
import pyscf.lib


cell = pyscf.pbc.gto.Cell()
a  = 4.1705
cell.a = a * np.asarray([
    [1, 0.5, 0.5],
    [0.5, 1, 0.5],
    [0.5, 0.5, 1.0]])
cell.atom = [
        ['Ni', [0, 0, 0]],
        ['Ni', [a, a, a]]]
cell.basis = 'def2-svp'
cell.output = 'pyscf.txt'
cell.verbose = 10
cell.exp_to_discard = 0.1
cell.precision = 1e-10
#cell.precision = 1e-12
cell.build()

kmesh = [2,1,1]
kpts = cell.make_kpts(kmesh)

df = pyscf.pbc.df.GDF(cell, kpts)
vnuc = pyscf.lib.asarray(df.get_nuc(kpts))
for k in range(len(kpts)):
    im = np.linalg.norm(vnuc[k].imag)
    print("Imaginary part of V(nuc) at kpt= %3d:  %.3e" % (k, im))
```

**Comment by maxnus** [comment]
Similarly, the Ewald parameters used for the nuclear-nuclear energy [here](https://github.com/pyscf/pyscf/blob/2bd16d760ddcbbcec4ca5d7b7b480b953743459b/pyscf/pbc/gto/cell.py#L758-L759)
are not well converged with `precision = 1e-8` for this system.

**Comment by sunqm** [comment]
With the updates in PR #1402 #1429 , the required accuracy can be reached.
