### ISSUE TITLE
Why the overlap for AOs differ from direct calculation?

### ISSUE THREAD

**Issue by sunnowrun** [pyscf/pyscf#1369]
I run the below code and get the overlap matrix for AOs
`import pyscf.gto
molecule = pyscf.gto.M(
    atom = 'H 0 0 0; H 0 0 2',
    basis = "sto-3g",
)
print(molecule.intor('int1e_ovlp'))
`
the result
[[1.         0.11921653]
 [0.11921653 1.        ]]

Then I directly calculate the overlap between two 1s basis for two H with 2A distance (using the mathematica software), code is below, the STO-3G exponent and coefficient is from basis-set-exchange website and identical to the PySCF's (using `pyscf.gto.basis.parse_nwchem.convert_basis_to_nwchem('H', pyscf.gto.load('sto3g', 'H'))` verified)
`Clear["Global`*"]
a1 = 3.425250914;
c1 = 0.1543289673;
a2 = 0.6239137298;
c2 = 0.5353281423;
a3 = 0.1688554040;
c3 = 0.4446345422;
\[Phi][x_, y_, z_] := 
 c1 ((2 a1)/\[Pi])^(3/4) E^(-a1 (x^2 + y^2 + z^2)) + 
  c2 ((2 a2)/\[Pi])^(3/4) E^(-a2 (x^2 + y^2 + z^2)) + 
  c3 ((2 a3)/\[Pi])^(3/4) E^(-a3 (x^2 + y^2 + z^2))

Integrate[\[Phi][x, y, z] \[Phi][x - 2, y, 
   z], {x, -\[Infinity], \[Infinity]}, {y, -\[Infinity], \
\[Infinity]}, {z, -\[Infinity], \[Infinity]}]`
result is `0.462778 - 1.43876*10^-16 I`

I don't know why.

**Comment by sunnowrun** [comment]
sorry, here is the mathematica code
![1660384199504](https://user-images.githubusercontent.com/46165443/184478643-185147ed-4724-41d8-a4cc-1223adff2c61.png)

**Comment by hebrewsnabla** [comment]
Because the default unit for atom coordinates is angstrom. If you set `unit='bohr'` in `gto.M()`, the mma result can be reproduced.

**Comment by sunnowrun** [comment]
I also want to ask, how PySCF deal with the infinite Coulomb and exchange series in PBC-HF calculation, are there some reference to learn this?

**Comment by sunnowrun** [comment]
Thank you very much!
