### ISSUE TITLE
How PBC HF is performed?

### ISSUE THREAD

**Issue by sunnowrun** [pyscf/pyscf#1370]
I really confused how PBC HF is implemented.
At first, I don't know why energy_nuc give me negative energy, as array of cores should give me infinite large repulsion energy. Then, I know it's calculated with uniform background negative charges. Then, using the Bloch Atomic Orbital, I know that the overlap matrix S can be obtained easily. I guess the hcore is also easy to calculate, while the electron-nuclear interaction matrix should also calculated by place nuclear array in background charges.
But to the calculation of J and K, I don't know how to deal with the divergent, I don't know if I need to add some background charges to make matrix element finite.
And I don't know why here add some negative background, there add some positive background, we can get the correct result.
And I don't know, when implement single k-point calculation, what I am doing. The system have infinite number of electrons, why I only have finite number of COs? And how PBC make sense?
And I don't know how EOM-EA/IP make sense. With PBC, doesn't it means add or remove a electron in each unit cell?
Also, when I use single and double particle integral to generate second quantized Hamiltonian, diagonal it, I get a lowest eigenvalue with particle number less than it should be (for diamond, only keep 4 electrons, COs generated by single k-point HF).

I know these questions may be so stupid, but confused me so much.
Give me some advice please, may some comprehensive reference is nice. (I only know _Quantum Chemistry of Solids: The LCAO First Principles Treatment of Crystals_)

**Comment by hebrewsnabla** [comment]
"compensating background" is used when deriving the formulas needed in PBC SCF (Martin Chap 13.1 Appendix F.2), which has been implemented in PySCF, you do not need to treat them manually.

**Comment by tberkel** [comment]
A description of an early implementation of periodic HF in PySCF (as well
as CC and IP/EA EOM-CC) is described in this paper:
https://pubs.acs.org/doi/full/10.1021/acs.jctc.7b00049

But many of your questions (especially about background charge densities)
are not unique to PySCF, and apply to all periodic electronic structure
calculations. Standard books (such as Martin's Electronic Structure,
suggested by @Shirong_Wang) or articles about periodic DFT should be
helpful.

**Comment by sunnowrun** [comment]
OK, thank you, I will keep learning!
