### ISSUE TITLE
issues on installing PySCF on macOS

### ISSUE THREAD

**Issue by bsonghao** [pyscf/pyscf#1373]
I meet some problem to install PySCF on macOS

When typing the command 
`pip install pyscf`

It returns the following error message:
  CMake Error: The source directory "/private/var/folders/5p/b3ktcws11wj9n121wr0880_m0000gn/T/pip-install-x07nj3w5/pyscf_c92bd6e624a54c1db03f02801a043128/pyscf/lib" does not appear to contain CMakeLists.txt.

Anyone meets the similar problem and know how to solve this problem?

**Comment by jamesETsmith** [comment]
@bsonghao, problems installing PySCF on macOS have been seen before. See #1096 and #1012. 

I'd suggesting use pip with git (see the [docs](https://pyscf.org/install.html) for more details):
```
pip install git+https://github.com/pyscf/pyscf
```

If you're running on an arm-based mac, you'll also probably need to use gcc rather than the default clang to compile PySCF. See a detailed breakdown of this solution [here](https://github.com/pyscf/pyscf/issues/1096#issuecomment-963569958).

**Comment by bsonghao** [comment]
Thanks for your responds. From the links I have learned that the current PySCF does not support apply silicon M1/M2 machines? Unfortunately, I am the users of these machines and https://github.com/pyscf/pyscf/issues/1012#issuecomment-924438491 does not solve the problem.

**Comment by jamesETsmith** [comment]
@bsonghao, PySCF does work on M1/M2 chips, you just need to install from the source for the moment (which you can do with pip as I suggested above). [Here are the instructions](https://github.com/pyscf/pyscf/issues/1096#issuecomment-963569958) to install pyscf on apple arm (M1/M2). Pre-built wheels for M1 should be out before too long, I'd keep an eye on #1281.

**Comment by bsonghao** [comment]
> @bsonghao, PySCF does work on M1/M2 chips, you just need to install from the source for the moment (which you can do with pip as I suggested above). [Here are the instructions](https://github.com/pyscf/pyscf/issues/1096#issuecomment-963569958) to install pyscf on apple arm (M1/M2). Pre-built wheels for M1 should be out before too long, I'd keep an eye on #1281.
Thanks for the comment and I followed the instruction but meet another error as follow:

  ERROR: Failed cleaning build dir for scipy
Successfully built pyscf
Failed to build scipy
Installing collected packages: scipy, pyscf
  Attempting uninstall: scipy
    Found existing installation: scipy 1.9.0
    Uninstalling scipy-1.9.0:
      Successfully uninstalled scipy-1.9.0
    Running setup.py install for scipy ... error

Seems to be associated with scipy?

**Comment by bsonghao** [comment]
I resolve the problem. Following the instruction in the PySCF documentation https://pyscf.org/install.html#compile-c-extensions

But currently PySCF does not support pre-build for arm64 Macs and the only way to compile is to compile from the source code which is inconvenient for Mac users.

**Comment by jamesETsmith** [comment]
@bsonghao I'm glad you were able to figure things out. Like I said earlier the pre-built pip wheels are already in the works for arm-based macs and should be available sometime in the near future (see #1281). I'm going to close the issue, but feel free to reopen it if you still have problems.

**Comment by bsonghao** [comment]
@jamesETsmith  After recent update of my python package, I meet another when running PySCF. 
For ruunning `import pyscf`, it returns me this error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pauliebao/pyscf/pyscf/__init__.py", line 113, in <module>
    from pyscf import lib
  File "/Users/pauliebao/pyscf/pyscf/lib/__init__.py", line 24, in <module>
    from pyscf.lib import numpy_helper
  File "/Users/pauliebao/pyscf/pyscf/lib/numpy_helper.py", line 39, in <module>
    _np_helper = misc.load_library('libnp_helper')
  File "/Users/pauliebao/pyscf/pyscf/lib/misc.py", line 62, in load_library
    return numpy.ctypeslib.load_library(libname, libpath)
  File "/Users/pauliebao/opt/anaconda3/lib/python3.9/site-packages/numpy/ctypeslib.py", line 149, in load_library
    return ctypes.cdll[libpath]
  File "/Users/pauliebao/opt/anaconda3/lib/python3.9/ctypes/__init__.py", line 457, in __getitem__
    return getattr(self, name)
  File "/Users/pauliebao/opt/anaconda3/lib/python3.9/ctypes/__init__.py", line 452, in __getattr__
    dll = self._dlltype(name)
  File "/Users/pauliebao/opt/anaconda3/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/pauliebao/pyscf/pyscf/lib/libnp_helper.dylib, 0x0006): tried: '/Users/pauliebao/pyscf/pyscf/lib/libnp_helper.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

I think it is another bug associate arm64 architecture?
