### ISSUE TITLE
How to access specific two-electron-integral

### ISSUE THREAD

**Issue by lela2011** [pyscf/pyscf#1375]
Hi. I wasn't sure whether it's allowed to ask such questions here but I've seen a similar type of question while doing my research. The title basically says it all. I am trying to build my own Restricted HF program and need the two-electron-integrals for the construction of the Fock matrix. For more context please have a look at [this question ](https://mattermodeling.stackexchange.com/q/9567/5707)  on stackexchange.

**Comment by tberkel** [comment]
Two-electron integrals in the AO basis can be obtained with
`eri = mol.intor('int2e') # a 4-index tensor`

See more examples of AO integral access here:
https://github.com/pyscf/pyscf/blob/master/examples/gto/20-ao_integrals.py

**Comment by lela2011** [comment]
Thanks. But I still can't quite understand how to access for example this integral with the indices i,j,k,l where i and k are functions of r_1 and j and l are functions of r_2. Let's assume I'm looking for this specific integral:
(i=2   j=4 | h_2 | k=0   l=3)
Would that be I[2][4][0][3] or something similar?

**Comment by tberkel** [comment]
Yes, the ordering is (r1r1|r2r2), sometimes called "chemists' notation" in textbooks. The returned `eri` object is a 4-index numpy array, which you can check with some statements:
```
print(type(eri))
# <class 'numpy.ndarray'>
print(eri.shape)
# (5, 5, 5, 5)
```
So you index into such a numpy tensor with `eri[2,4,0,3]`. If you're interested in the ordering of the atomic orbital basis functions (i.e., which index corresponds to which orbital type), this is described on the PySCF website here:
https://pyscf.org/user/gto.html#ordering-of-basis-functions

**Comment by lela2011** [comment]
Perfect. Thank you. That is exactly what I needed to find out.
