### ISSUE TITLE
Support for more Abelian symmetry groups

### ISSUE THREAD

**Issue by mkrompiec** [pyscf/pyscf#1377]
Is it true that "Currently, PySCF supports linear molecular symmetries D∞h (labelled as Dooh in the program) and C∞v (labelled as Coov), the D2h group and its subgroups"?
Would it be possible to support e.g. C3 symmetry in the SCF?
Currently, if I try running a HF calculation of a C3-symmetric system, I get this message:
`point group symmetry = C3, use subgroup C1`

**Comment by sunqm** [comment]
This feature was provided by PR #1477 .
