### ISSUE TITLE
What does "see MH" mean in pbc module？

### ISSUE THREAD

**Issue by changsuc** [pyscf/pyscf#1378]
Hi, 
I found in pbc module there are some comments like "see MH (3.8)", "See MH Eq.(4.80)". I guess it is a very famous textbook in first principle calculation but not aware of which it is. Would anyone mind telling me which reference it indicates?
Thanks a lot.

**Comment by tberkel** [comment]
Ab Initio Molecular Dynamics, by Marx and Hutter.

**Comment by changsuc** [comment]
Thank you. It helps a lot.
