### ISSUE TITLE
Real MOs from k-space calculations

### ISSUE THREAD

**Issue by januseriksen** [pyscf/pyscf#1381]
Hi all,

At the recent developers' meeting, I heard talk of an open code that could handle (exact) mean-field transformations from k-space back into a set of real MOs defined for a supercell? Does anyone know of such a code? Perhaps those working on local CC for periodic systems? @hongzhouye @tberkel & others?

Thanks in advance,
Janus

**Comment by januseriksen** [comment]
Appears to be so, thanks. It works for k-space KS-DFT as well as HF, right?

**Comment by hongzhouye** [comment]
Yes! @januseriksen

**Comment by januseriksen** [comment]
Beautiful, thanks @hongzhouye!
