### ISSUE TITLE
Loading converged newton chkfile doesn't converge immediately (ROHF)

### ISSUE THREAD

**Issue by HehnLukas** [pyscf/pyscf#1382]
Hi,

I ran into a problem running ROHF calculations when loading form checkpointfiles, namely that they dont necessarily converge if the checkpointfile was generated using the newton solver. I have never experienced this with UHF calculations. Is there some way to work around this? the checkpointfile loads at the correct energy, but quickly moves away from it. Loading the calculation with the newton solver also doesn't work, as it seems to require the mo occs, and doesnt even start at the correct energy. In this example it converges eventually, but I have had it happen that it doesnt at all, and anyways, the point of the checkfile is that it should converge immediately.

Output converged calculation:
```
******** <class 'pyscf.scf.rohf.ROHF'> ********
method = ROHF-RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-09
SCF conv_tol_grad = None
SCF max_cycles = 50
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /scratch/pbs.10443105.pbsp1/tmpyisw5v4s
max_memory 124800 MB (current use 59 MB)
num. doubly occ = 88  num. singly occ = 10
******** <class 'pyscf.scf.rohf.ROHF'> Newton solver flags ********
SCF tol = 1e-09
conv_tol_grad = None
max. SCF cycles = 50
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = mycalcu.chk
max_cycle_inner = 12
max_stepsize = 0.05
ah_start_tol = 1e+09
ah_level_shift = 0
ah_conv_tol = 1e-12
ah_lindep = 1e-14
ah_start_cycle = 1
ah_max_cycle = 40
ah_grad_trust_region = 2.5
kf_interval = 4
kf_trust_region = 5
canonicalization = True
max_memory 124800 MB (current use 59 MB)
Set conv_tol_grad to 3.16228e-05
  HOMO = 0.196080249529342  LUMO = 0.198290366722021
Initial guess E= -5042.81328857241  |g|= 7.21051
macro= 0  E= -5061.33016863715  delta_E= -18.5169  |g|= 4.4096  3 KF 15 JK
macro= 1  E= -5064.92095558613  delta_E= -3.59079  |g|= 1.20585  3 KF 15 JK
...
macro= 7  E= -5067.45852758876  delta_E= -9.09495e-12  |g|= 1.06889e-05  1 KF 2 JK
Canonicalize SCF orbitals
macro X = 8  E=-5067.45852758876  |g|= 1.06889e-05  total 24 KF 114 JK
converged SCF energy = -5067.45852758876
```

Output loading chkfile with regular DIIS solver:
```
******** <class 'pyscf.scf.rohf.ROHF'> ********
method = ROHF-RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-09
SCF conv_tol_grad = None
SCF max_cycles = 50
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = mycalcu2.chk
max_memory 124800 MB (current use 68 MB)
num. doubly occ = 88  num. singly occ = 10
Set gradient conv threshold to 3.16228e-05
init E= -5067.45852758876
  HOMO = 0.0133370717400251  LUMO = 0.368475797798632
cycle= 1 E= -5067.1519123146  delta_E= 0.307  |g|= 0.669  |ddm|= 1.16
  HOMO = 0.347780659894127  LUMO = 0.369982276221523
cycle= 2 E= -5067.05322859862  delta_E= 0.0987  |g|= 0.827  |ddm|= 1.69
  HOMO = 0.0997359103853067  LUMO = 0.367524383837868
cycle= 3 E= -5067.27909060523  delta_E= -0.226  |g|= 0.36  |ddm|= 1.59
  HOMO = 0.121403356551538  LUMO = 0.366718730668985
...
cycle= 49 E= -5067.35556761976  delta_E= -0.00259  |g|= 0.0492  |ddm|= 0.163
  HOMO = 0.176526385039504  LUMO = 0.369148356132135
cycle= 50 E= -5067.35976137654  delta_E= -0.00419  |g|= 0.0427  |ddm|= 0.227
SCF not converged.
SCF energy = -5067.35976137654
```

Output loading chkfile with newton solver:
```

WARN: Newton solver expects mo_coeff with mo_occ as initial guess but mo_occ is not found in the arguments.
      The given argument is treated as density matrix.





******** <class 'pyscf.scf.rohf.ROHF'> ********
method = ROHF-RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-09
SCF conv_tol_grad = None
SCF max_cycles = 50
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /scratch/pbs.10445895.pbsp1/tmpgkn31jn9
max_memory 124800 MB (current use 68 MB)
num. doubly occ = 88  num. singly occ = 10
******** <class 'pyscf.scf.rohf.ROHF'> Newton solver flags ********
SCF tol = 1e-09
conv_tol_grad = None
max. SCF cycles = 50
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = mycalcu2.chk
max_cycle_inner = 12
max_stepsize = 0.05
ah_start_tol = 1e+09
ah_level_shift = 0
ah_conv_tol = 1e-12
ah_lindep = 1e-14
ah_start_cycle = 1
ah_max_cycle = 40
ah_grad_trust_region = 2.5
kf_interval = 4
kf_trust_region = 5
canonicalization = True
max_memory 124800 MB (current use 68 MB)
Set conv_tol_grad to 3.16228e-05
  HOMO = 0.0133370717400164  LUMO = 0.368475797798456
Initial guess E= -5067.1519123146  |g|= 0.669447
macro= 0  E= -5067.35095969342  delta_E= -0.199047  |g|= 0.174804  3 KF 18 JK
macro= 1  E= -5067.38135979111  delta_E= -0.0304001  |g|= 0.198993  3 KF 18 JK
macro= 2  E= -5067.38867358759  delta_E= -0.0073138  |g|= 0.0287193  3 KF 14 JK
macro= 3  E= -5067.39033956209  delta_E= -0.00166597  |g|= 0.0164971  4 KF 19 JK
macro= 4  E= -5067.39216442683  delta_E= -0.00182486  |g|= 0.0150984  3 KF 15 JK
macro= 5  E= -5067.40321761048  delta_E= -0.0110532  |g|= 0.0264307  3 KF 15 JK
macro= 6  E= -5067.44205990108  delta_E= -0.0388423  |g|= 0.109014  3 KF 19 JK
macro= 7  E= -5067.4560614644  delta_E= -0.0140016  |g|= 0.0628615  2 KF 8 JK
macro= 8  E= -5067.45852758741  delta_E= -0.00246612  |g|= 0.000171927  4 KF 16 JK
macro= 9  E= -5067.45852758876  delta_E= -1.34423e-09  |g|= 3.09563e-05  1 KF 4 JK
macro= 10  E= -5067.45852758877  delta_E= -1.45519e-11  |g|= 1.08349e-05  1 KF 2 JK
Canonicalize SCF orbitals
macro X = 11  E=-5067.45852758877  |g|= 1.08349e-05  total 31 KF 160 JK
converged SCF energy = -5067.45852758877
```

**Comment by sunqm** [comment]
With the ROHF wavefunction obtained by second order algorithm (newton solver) certain MO energies of occupied orbitals can be higher than MO energies of some virtual orbitals. In regular SCF, orbitals are sorted from low energy to high energy. It does not allow occupation flipped. In this case, there is no way to make SCF and newton solver fully consistent. You can add a level shift in regular ROHF-SCF solver. Then only one SCF iteration is needed to converge. However, the result obtained from regular SCF will still be different to what you obtained from newton solver.In SCF code there is an extra iteration at the end in which level-shift is explicitly excluded.

**Comment by HehnLukas** [comment]
In this case, are the results just not comparable and basically different methods? In UHF, I was under the impression that the different solvers both try to find the minimal energy in the same space, and if one finds a lower energy, that is then correct for both (although both can miss the global minimumof course). Is this not correct for ROHF? (Is it even correct for UHF?)

If they are different, which is the better to use as a reference calculation for post HF methods, like CAS or CCSD? The lowest energy, or is there some other metric?

**Comment by sunqm** [comment]
Regular SCF does not minimize energy. It tries to minimize the gradients for orbital rotation but that can be a saddle point. In this sense second order methods are more reliable. It guarantees local minimum. Theoretically regular SCF or second order SCF should have no difference for CASSCF. They just provide an initial guess. CASSCF itself is a second order method that can converge to a local minimum near the initial guess. CCSD only depends on appropriate occupied space and virtual space. You can even start with DFT orbitals if they are appropriate.

For other post-HF methods, some may need to freeze certain core orbitals or virtual orbitals. Some may need canonical SCF orbitals. Some may rely on the specific occupied orbitals and virtual orbitals. There probably not exists a general rule which SCF reference is "better".

**Comment by HehnLukas** [comment]
Okay, thanks a lot for the responses, that is very helpful.

One question I still have is, however, is there no way to save a newton solver result in a checkfile that will then converge immediately if loaded and used with another newton solver? Maybe by also saving and loading mo_occ?

**Comment by sunqm** [comment]
For second order scf, you can load the chkfile and call `run()` method
```
mf = mol.RHF().newton()
mf.update("chkfile_name")
mf.run()
```
The orbitals from chkfile are automatically read in as the initial guess of soscf solver.

I'll close the issue since the original question for ROHF convergence is solved.
