### ISSUE TITLE
Confusing about user defined basis set

### ISSUE THREAD

**Issue by Geositta2000** [pyscf/pyscf#1385]
From https://pyscf.org/user/gto.html
```
mol.basis = {'O': gto.basis.parse('''
C    S
     71.6168370              0.15432897
     13.0450960              0.53532814
      3.5305122              0.44463454
C    SP
      2.9412494             -0.09996723             0.15591627
      0.6834831              0.39951283             0.60768372
      0.2222899              0.70011547             0.39195739
''')}
```

Does the above code define basis function for oxygen ` {'O': gto.basis` or carbon `C    S
     71.6168370              0.15432897` ?

**Comment by sunqm** [comment]
This defines a basis for "O". The parameters are taken from the basis for "C" . It is more clear how this happens if you print(mol.basis)
