### ISSUE TITLE
doc submodule is missing

### ISSUE THREAD

**Issue by rittneje** [pyscf/pyscf#1392]
The .gitmodules file references a "doc" submodule. However it is in some weird state such that the submodule itself is missing, so `git submodule update --init` does not do anything.

**Comment by fishjojo** [comment]
The doc has been moved to [here](https://github.com/pyscf/pyscf.github.io).

**Comment by rittneje** [comment]
@fishjojo Is it supposed to be a submodule of this repo?

If it is then it actually needs to appear in the repo at the path mentioned in .gitmodules.

If not then you need to remove it from .gitmodules. (And actually you can delete the whole file.)

**Comment by fishjojo** [comment]
It's no longer a submodule. We can delete the file.
