### ISSUE TITLE
Why EOM-EE for Hydrogen give wired result?

### ISSUE THREAD

**Issue by sunnowrun** [pyscf/pyscf#1400]
I run the following EOM-EE code for $H_2$ in sto-3g basis in Code 1.
For $H_2$ in this basis, it should have 5 EE states, but I don't know why it only return me 2 (I already set the nroots=4).
I find the function `eeccsd` in `pyscf.cc.eom_rccsd` set `nroots = min(nroots, spinvec_size)`, and `spinvec_size` is obtained from the function below
`def vector_size(self):`
`        '''size of the vector based on spin-orbital basis'''`
`        nocc = self.nocc`
`        nvir = self.nmo - nocc`
`        return nocc*nvir + nocc*nocc*nvir*nvir`
I don't know why this setting.

Then, I notice that `eeccsd` just run `EOMEESinglet`, `EOMEETriplet`, `EOMEESpinFlip` separately, I run the Code 2, but a new bug appeared. In the result from `EOMEETriplet`, a eigenvalue (refer to the energy difference between the excited state and the ground state) is zero. I also try to change the bond length, but the zero is always there, I confused.

Code 1:
`import pyscf`
`import pyscf.cc`
`geom = 'H 0 0 0; H 0 0 0.7'`
`basis = "sto-3g"`

`mol = pyscf.gto.M(atom = geom, basis = basis)`
`mf = pyscf.scf.RHF(mol).run()`
`mycc = pyscf.cc.CCSD(mf).run()`

`eomee_cc = pyscf.cc.eom_rccsd.EOMEE(mycc)`
`res = eomee_cc.kernel(nroots = 4)`
`print(res)`

Result 1:
`converged SCF energy = -1.11734903499028`
`E(CCSD) = -1.136189572437634  E_corr = -0.01884053744735377`
`(array([0.65773652, 0.65773652]), [array([1.]), None])`

Code 2:
`import pyscf`
`import pyscf.cc`
`geom = 'H 0 0 0; H 0 0 0.7'`
`basis = "sto-3g"`

`mol = pyscf.gto.M(atom = geom, basis = basis)`
`mf = pyscf.scf.RHF(mol).run()`
`mycc = pyscf.cc.CCSD(mf).run()`

`eomee_cc = pyscf.cc.eom_rccsd.EOMEESinglet(mycc)`
`res = eomee_cc.kernel(nroots=4)`
`print('------------------')`
`print(res)`

`eomee_cc = pyscf.cc.eom_rccsd.EOMEETriplet(mycc)`
`res = eomee_cc.kernel(nroots=4)`
`print('------------------')`
`print(res)`

`eomee_cc = pyscf.cc.eom_rccsd.EOMEESpinFlip(mycc)`
`res = eomee_cc.kernel(nroots=4)`
`print('------------------')`
`print(res)`

Result 2:
`converged SCF energy = -1.11734903499028`
`E(CCSD) = -1.136189572437634  E_corr = -0.01884053744735377`
`------------------`
`(array([1.01573767, 1.71950379]), [array([1., 0.]), array([-2.54723987e-16,  1.00000000e+00])])`
`------------------`
`(array([0.        , 0.65773652]), [array([-2.72550039e-16,  1.00000000e+00]), array([1., 0.])])`
`------------------`
`(0.6577365165979016, array([1.]))`

**Comment by pwborthwick** [comment]
You are using rccsd which is the spin-restricted version. As $H_2$ in STO-3G has only 2 basis functions - 1 doubly occupied and 1 virtual, the EOM Hamiltonian is of dimension  (occupied x virtual ) + (occupied  x virtual x occupied x virtual) and so of size 1+1=2. You will only get 2 roots from a Hamitonian which is a square matrix of dimension 2. You cannot get a triplet with only 2 roots. If you use ```verbose=7``` you can see the line ```CCSD nocc = 1, nmo = 2``` at the start of the computation.
   There are spin-unrestricted and mixed-spin versions (uccsd and gccsd) or use a non-minimal basis maybe if you require more roots.

**Comment by sunnowrun** [comment]
> You are using rccsd which is the spin-restricted version. As H2 in STO-3G has only 2 basis functions - 1 doubly occupied and 1 virtual, the EOM Hamiltonian is of dimension (occupied x virtual ) + (occupied x virtual x occupied x virtual) and so of size 1+1=2. You will only get 2 roots from a Hamitonian which is a square matrix of dimension 2. You cannot get a triplet with only 2 roots. If you use `verbose=7` you can see the line `CCSD nocc = 1, nmo = 2` at the start of the computation. There are spin-unrestricted and mixed-spin versions (uccsd and gccsd) or use a non-minimal basis maybe if you require more roots.

Thank you, change to uccsd/gccsd solved the problem.
