### ISSUE TITLE
PySCF 2.1.0 wheels for MacOS and python > 3.7 don't install

### ISSUE THREAD

**Issue by manoelmarques** [pyscf/pyscf#1405]
The pyscf 2.1.0 distribution for MacOS changed the scipy requirements from scipy (!=1.5.0,!=1.5.1) to scipy (<=1.1.0).
However there is no scipy (<=1.1.0) distribution for python > 3.7 under MacOS.
For the MacOS, under python 3.8, it reverts to pyscf 2.0.1 and works, however for python 3.10, it can't install the only wheel existent for python 3.10 and fails.

Scipy <= 1.1.0 is very old and while there are wheels for python <=3.7, there aren't any for python > 3.7

So it seems to me that the current MacOS wheels for python > 3.7 don't work.

**Comment by sunqm** [comment]
scipy dependency check is removed in pyscf-2.2
