### ISSUE TITLE
pbc gdf API changed, j3c-kptij is missing

### ISSUE THREAD

**Issue by zhcui** [pyscf/pyscf#1408]
Dear all,

I noticed that the pbc gdf api changes recently.
Many old code like libdmet, fcdmft and other embedding codes need 'j3c-kptij' in the gdf file.
I think we may keep this quantity for compatibility.
What do you think?

Best,
Zhihao

**Comment by ssh2** [comment]
Hi Zhihao,

It is relatively easy to change your code to work with the new API. Here's an example: https://github.com/sokolov-group/pyscf/commit/2f82167dc5a20ff2009f49cfe22a2ebb82cd8722

**Comment by zhcui** [comment]
Thanks, Alex!
