### ISSUE TITLE
PBC HF energy does not converge？

### ISSUE THREAD

**Issue by zltemp** [pyscf/pyscf#1409]
Hi all,

I just updated to pyscf 2.1 and tried some calculation. I soon noticed that some HF calculations do not converge (e.g. for C3H8 in def2tzvp basis set the khf energy is -10^+5 or more), and for some HF calculations the Coulomb integrals may not converge (e.g. for Si2H6 Coulomb energy has imaginary part 1.3894814953528291e-07). Did I do something wrong?
I have my calculation detail attached, thank you so much.

Best,
Zili
[c3h8.txt](https://github.com/pyscf/pyscf/files/9503145/c3h8.txt)

[si2h6.txt](https://github.com/pyscf/pyscf/files/9503086/si2h6.txt)

**Comment by zltemp** [comment]
> Can you achieve convergence and agreement with v2.0 results, if you reduce `cell.precision`?

I will try and let you know the result soon. So far I'm still using v2.0.1, which will always converge.

**Comment by zltemp** [comment]
> Can you achieve convergence and agreement with v2.0 results, if you reduce `cell.precision`?
[c2h4o_newpyscf.txt](https://github.com/pyscf/pyscf/files/9562142/c2h4o_newpyscf.txt)
Hi Max,
I tries reducing cell.precision to 1e-15, but the SCF still not converge. You may see as attached.

**Comment by maxnus** [comment]
OK thanks. I was trying to see if this is related to #1422 (it might still be).
If you have the same output file for v2.0 and/or a smaller example (smaller basis, fewer k-points),
it could help the developers fixing this.

**Comment by zltemp** [comment]
> OK thanks. I was trying to see if this is related to #1422 (it might still be). If you have the same output file for v2.0 and/or a smaller example (smaller basis, fewer k-points), it could help the developers fixing this.

Hi. I have the same output file for v2.0.1. I did not try a smaller example with v2.1 before. I will try it and update my result here once obtained the result.
[c2h4o_old_pyscf.txt](https://github.com/pyscf/pyscf/files/9575514/c2h4o_old_pyscf.txt)

**Comment by zltemp** [comment]
Hi. I obtained the result with smaller basis and fewer k points with v2.1. These results are all converged even without reducing cell.precision. 
[c2h4o_small_basis.txt](https://github.com/pyscf/pyscf/files/9580038/c2h4o_small_b
[c2h4o_222.txt](https://github.com/pyscf/pyscf/files/9580156/c2h4o_222.txt)
asis.txt)
[c2h4o_321.txt](https://github.com/pyscf/pyscf/files/9580178/c2h4o_321.txt)

**Comment by zltemp** [comment]
I also noticed that for some systems the Coulomb integrals in v2.1 HF calculation may not converge, while in v2.0.1 the Coulomb integrals will converge. I wonder if it is a problem related or what. 
[c2nh3_new_pyscf.txt](https://github.com/pyscf/pyscf/files/9581626/c2nh3_new_pyscf.txt)
[c2nh3_old_pyscf.txt](https://github.com/pyscf/pyscf/files/9582368/c2nh3_old_pyscf.txt)

**Comment by verena-neufeld** [comment]
Hi @zltemp, thanks for opening this issue. Has it been resolved now?

**Comment by sunqm** [comment]
This issue is caused by the errors in integral computation. The integral computation accuracy is improved in the new versions.
