### ISSUE TITLE
error running m062x calculation for Hydrogen atom

### ISSUE THREAD

**Issue by lucienwb** [pyscf/pyscf#1413]
Hi, below is a simple calculation, but I got an error said "array must not contain infs or NaNs".
Does anyone know how can I fix this. Thanks!

############################
mol = gto.M(
    atom = '''
        H    0.0    0.0    0.0
            ''',
    unit='B',
    basis='ccpvtz',
    spin=1,
)
mol.cart=False
mol.symmetry=False
mol.build()

myrks=dft.RKS(mol)
myrks.xc='0.54*HF + M062XX + M062XC'
myrks.grids.level=5
myrks.kernel()
############################

**Comment by jamesETsmith** [comment]
@lucienwb, thanks for letting us know. I can't reproduce your error with v2.1.0 or the latest on the master branch. When I try to run your script I see the following error:
```shell
'Unknown compound XC functional  M062XX'
```

Could you provide us with: 1) a full script, 2) an error trace, and 3) your version and system information?

**Comment by pwborthwick** [comment]
@jamesETsmith The error can be reproduced using ```dft.numint.NumInt.libxc = dft.xcfun```. Apparently M062XX is only available (at least with that name) in xcfunc library. Ironically it's the chkfinite array which is causing the error!

**Comment by lucienwb** [comment]
Hi, @jamesETsmith below is the full script, I am using an old version which is 2.0.1 I will try the latest version later. I got this error only when I trying to calculation the Hydrogen atom, for other atoms or molecules the code runs smoothly. Operating system is MacOS with the m1 arm chip.

The Error Trackback is:
######Error trace######
ValueError                                Traceback (most recent call last)
/Users/my/path/to/script/test.ipynb Cell 1 in <cell line: 18>()
     [16](vscode-notebook-cell:/Users/my/path/to/script/test.ipynb#W0sZmlsZQ%3D%3D?line=15) myrks.xc='0.54*HF + M062XX + M062XC'
     [17](vscode-notebook-cell:/Users/my/path/to/script/test.ipynb#W0sZmlsZQ%3D%3D?line=16) myrks.grids.level=5
---> [18](vscode-notebook-cell:/Users/my/path/to/script/test.ipynb#W0sZmlsZQ%3D%3D?line=17) myrks.kernel()

File /opt/my/python/path/envs/py39/lib/python3.9/site-packages/pyscf/lib/misc.py:638, in alias.<locals>.aliased_fn(self, *args, **kwargs)
    637 def aliased_fn(self, *args, **kwargs):
--> 638     return getattr(self, fname)(*args, **kwargs)

File /opt/my/python/path/envs/py39/lib/python3.9/site-packages/pyscf/scf/hf.py:1666, in SCF.scf(self, dm0, **kwargs)
   1661 self.build(self.mol)
   1663 if self.max_cycle > 0 or self.mo_coeff is None:
   1664     self.converged, self.e_tot, \
...
--> 488     raise ValueError(
    489         "array must not contain infs or NaNs")
    490 return a

ValueError: array must not contain infs or NaNs
######End######

######full script######
from pyscf import scf,gto,dft

mol = gto.M(
atom = '''
H 0.0 0.0 0.0
''',
unit='B',
basis='ccpvtz',
spin=1,
)
mol.cart=False
mol.symmetry=False
mol.build()

myrks=dft.RKS(mol)
myrks.xc='0.54*HF + M062XX + M062XC'
myrks.grids.level=5
myrks.kernel()
######End######

**Comment by pwborthwick** [comment]
@lucienwb Try  running `myrks.xc='0.54*HF + M06_2X'`. M06_2X is shorthand for HYB_MGGA_X_M06_2X,MGGA_C_M06_2X', which is I think what you wanted. This runs OK. I'm not sure what was causing the crash with the M062XX name but perhaps some internal confusion with libraries and codes leading to a Hamiltonian full of inf's.

**Comment by susilehtola** [comment]
> @lucienwb Try running `myrks.xc='0.54*HF + M06_2X'`. M06_2X is shorthand for HYB_MGGA_X_M06_2X,MGGA_C_M06_2X', which is I think what you wanted. This runs OK. I'm not sure what was causing the crash with the M062XX name but perhaps some internal confusion with libraries and codes leading to a Hamiltonian full of inf's.

That runs Libxc; the issue with NaNs may still be present in XCFun. (Which would not surprise me, given that we are talking about Minnesota functionals...)

**Comment by pwborthwick** [comment]
> > @lucienwb Try running `myrks.xc='0.54*HF + M06_2X'`. M06_2X is shorthand for HYB_MGGA_X_M06_2X,MGGA_C_M06_2X', which is I think what you wanted. This runs OK. I'm not sure what was causing the crash with the M062XX name but perhaps some internal confusion with libraries and codes leading to a Hamiltonian full of inf's.
> 
> That runs Libxc; the issue with NaNs may still be present in XCFun. (Which would not surprise me, given that we are talking about Minnesota functionals...)

It is still present with XCfunc.

**Comment by lucienwb** [comment]
Thanks for you comments @susilehtola @pwborthwick! I upgraded pyscf to the latest version and using Debian to run the code with myrks.xc='0.54*HF + M06_2X' but I still got an error with a new error message (see below).
Further I tried some other mGGA functionals and I again got the same error. So I wonder if this error only happens for mGGA calculation of Hydrogen atom? Since for LDA and GGA, this job went well.

###### Error message######
File ~/miniconda3/envs/py39/lib/python3.9/site-packages/pyscf/scf/hf.py:1692, in SCF.scf(self, dm0, **kwargs)
   1687 self.build(self.mol)
   1689 if self.max_cycle > 0 or self.mo_coeff is None:
   1690     self.converged, self.e_tot, \
   1691             self.mo_energy, self.mo_coeff, self.mo_occ = \
-> 1692             kernel(self, self.conv_tol, self.conv_tol_grad,
   1693                    dm0=dm0, callback=self.callback,
   1694                    conv_check=self.conv_check, **kwargs)
   1695 else:
   1696     # Avoid to update SCF orbitals in the non-SCF initialization
   1697     # (issue #495).  But run regular SCF for initial guess if SCF was
   1698     # not initialized.
   1699     self.e_tot = kernel(self, self.conv_tol, self.conv_tol_grad,
   1700                         dm0=dm0, callback=self.callback,
   1701                         conv_check=self.conv_check, **kwargs)[1]
...
-> 1489 assert (rho_u.dtype == numpy.double)
   1490 assert (rho_d.dtype == numpy.double)
   1492 if rho_u.ndim == 1:

AssertionError: 
######End######

**Comment by pwborthwick** [comment]
@lucienwb I'm running PySCF version 2.0.1 and with
```
from pyscf import gto, dft

mol = gto.M(
atom = '''
H 0.0 0.0 0.0
''',
unit='B',
basis='ccpvtz',
spin=1,
verbose=7
)
mol.cart=False
mol.symmetry=False
mol.build()

myrks=dft.KS(mol)

myrks.xc='0.54*HF + M06_2X'
myrks.grids.level=5
myrks.kernel()
```
I get 
```
converged SCF energy = -0.680336812533105  <S^2> = 0.75  2S+1 = 2
```
without any problems! Does your input match mine?

**Comment by kleinZhf** [comment]
> @lucienwb I'm running PySCF version 2.0.1 and with
> 
> ```
> from pyscf import gto, dft
> 
> mol = gto.M(
> atom = '''
> H 0.0 0.0 0.0
> ''',
> unit='B',
> basis='ccpvtz',
> spin=1,
> verbose=7
> )
> mol.cart=False
> mol.symmetry=False
> mol.build()
> 
> myrks=dft.RKS(mol)
> 
> myrks.xc='0.54*HF + M06_2X'
> myrks.grids.level=5
> myrks.kernel()
> ```
> 
> I get
> 
> ```
> converged SCF energy = -0.68033598050488  <S^2> = 0.75  2S+1 = 2
> ```
> 
> without any problems! Does your input match mine?

I am confused with this result, it is quite diffrent from the energy got from 'b3lyp' xc or other typical xcs, is the form '0.54*HF + M06_2x' correct for the using of m06_2x xc?

**Comment by susilehtola** [comment]
> ```myrks.xc='0.54*HF + M06_2X'```

This is wrong: you are running M06-2X with an additional 54% of Hartree-Fock exchange. The correct usage is `myrks.xc  = 'M06-2X'`

**Comment by lucienwb** [comment]
@susilehtola Yes, the above input is correct. And regarding my old issue, the problem was solved by manually compiling the PySCF code (for MacOS), so that PySCF will first use Libxc library. As mentioned in #1415 the default xc library is xcfun, which has that numerical problem, if I install PySCF using pip install. (I think this issue has already been fix now). I will close this issue then.
