### ISSUE TITLE
Is nonadiabatic couplings available?

### ISSUE THREAD

**Issue by PoloTier** [pyscf/pyscf#1414]
Is nonadiabatic couplings available?

**Comment by pwborthwick** [comment]
Same as #496

**Comment by matthew-hennefarth** [comment]
SA-CASSCF NACs are currently available! Take a look at [`examples/nac/01-sacasscf_nac.py`](https://github.com/pyscf/pyscf/blob/master/examples/nac/01-sacasscf_nac.py).
