### ISSUE TITLE
Maintainer and Date should be add to the license

### ISSUE THREAD

**Issue by Anselmoo** [pyscf/pyscf#1421]
https://github.com/pyscf/pyscf/blob/12989b399b0eddfab3709c7e70dd55a45129dce9/LICENSE#L189

**Comment by sunqm** [comment]
Please refer to the copyright claim at https://github.com/pyscf/pyscf/blob/master/NOTICE#L1

**Comment by Anselmoo** [comment]
https://github.com/pyscf/pyscf/blob/9c83d8a25ca7e03b7db57d1aacec304be49cc8ed/NOTICE#L1

- Shouldn't it be 2024? 
- And why not <<**`2024`  `The PySCF Developers`**>>
