### ISSUE TITLE
cell.precision for 2D systems changed in 2.1

### ISSUE THREAD

**Issue by maxnus** [pyscf/pyscf#1422]
We have some tests failing downstream since 2.1, which seem to suddenly require a much lower `cell.precision` to pass.
This affects a 3x2x1 supercell of a square lattice of He atoms (example script below).

With version 2.0 the results are:
```
k-HF:  converged=  True  E=-2.855155880475
G-HF:  converged=  True  E=-2.855155880468
```

With version 2.1 the results are:

```
k-HF:  converged=  True  E=-2.855155880613
G-HF:  converged= False  E=-2.855140202195
```
with the following warning for the Gamma-point supercell calculation:

> WARN: 0.008379 error found in overlap integrals. cell.precision  or  cell.rcut  can be adjusted to improve accuracy.

Only when lowering `cell.precision` to `1e-15` will this warning dissappear, and I get

```
k-HF:  converged=  True  E=-2.855155880468
G-HF:  converged=  True  E=-2.855155880468
```

It appears that some truncation or resolution parameter is now underestimated in this 2D supercell system, since we shouldn't need to go to such a low precision.
 
This doesn't appear to be an issue when using 3D PBC.
(edit: although possibly related to #1409)
 
 Script:
 [run.py.txt](https://github.com/pyscf/pyscf/files/9557081/run.py.txt)

**Comment by verena-neufeld** [comment]
Hi @maxnus , thanks for opening this issue. Has it been resolved now?

**Comment by sunqm** [comment]
Pyscf-2.6 and newer have a tighten threshold on integral precision. The gamma point and kpoints calculation should both provide `E=-2.855155881`
