### ISSUE TITLE
Integral over four atomic orbitals

### ISSUE THREAD

**Issue by wmkirby1** [pyscf/pyscf#1423]
I want to be able to get the tensor whose entries are

![equation](https://latex.codecogs.com/svg.image?\int&space;d\vec{r}\phi_i^*(\vec{r})\phi_j(\vec{r})\phi_k^*(\vec{r})\phi_l(\vec{r})) 

where the phi_i are atomic orbitals in a basis that I can choose. I have checked the integrals that are available via [pyscf.gto.moleintor.py](https://github.com/pyscf/pyscf/blob/12989b399b0eddfab3709c7e70dd55a45129dce9/pyscf/gto/moleintor.py), but unless I am misunderstanding them I don't think any of these are quite what I'm looking for. Can someone please assist? Thanks in advance.

**Comment by fishjojo** [comment]
You may try `mol.intor('int4c1e_ovlp')`.

**Comment by tberkel** [comment]
I’m pretty sure that accessing 4c1e integrals requires the latest version
of libcint, but @sunqm can correct me.

**Comment by wmkirby1** [comment]
Thanks @fishjojo and @tberkel! @tberkel, I am currently on pyscf 2.0.1, and `mol.intor('int4c1e_ovlp')` does raise `AttributeError: dlsym(0x21bb136a0, int4c1e_ovlp_optimizer): symbol not found`, as you suggested it might. Unfortunately, due to [#1405](https://github.com/pyscf/pyscf/issues/1405#issue-1363408586) I cannot install pyscf 2.1.0 right now. Otherwise I am not sure how to change the version of libcint since this seems to be happening through the library pyscf/lib/libcgto (I don't have a separate installation of libcint right now). Any guidance?

**Comment by maxnus** [comment]
@wmkirby1 
You should be able to modify the version of libcint that PySCF installs in the CMakeLists.txt file here:
https://github.com/pyscf/pyscf/blob/cf8ba042e613287bdb905dacb9076c48ee06f8d2/pyscf/lib/CMakeLists.txt#L168

**Comment by wmkirby1** [comment]
Thanks @maxnus! Do you know how to do the same thing in pyscf 2.0.1 (the version that will install on macs right now -- see my previous comment)?

**Comment by maxnus** [comment]
Version 2.0.1 has the same line in the CMakeLists.txt: https://github.com/pyscf/pyscf/blob/e064645ee08728c64412ed9bc8e7ffe45fc8e1f4/pyscf/lib/CMakeLists.txt#L148
Which you can update to the current release

**Comment by sunqm** [comment]
The integral was implemented in libcint long time ago. However, it is not enabled by pyscf cmake. You can add an option "-DWITH_4C1E=ON" around L175 of the pyscf/lib/CMakeLists.txt , clear up the pyscf/lib/deps folder, then recompile pyscf extensions

**Comment by sunqm** [comment]
Feel free to reopen the issue if the problem persists

**Comment by SylviaJoy1** [comment]
I followed @sunqm's CMakeLists.txt suggestion, but I am getting this error with PySCF 2.2.1:

/moto/berkelbach/users/sjb2225/sTDA/pyscf_4c1e/pyscf/pyscf/gto/moleintor.py:259: UserWarning: Function int4c1e_ovlp_sph not found.  Set its comp to 1
  warnings.warn('Function %s not found.  Set its comp to 1' % intor_name)
Traceback (most recent call last):
  File "SS.py", line 8, in <module>
    s = mol.intor('int4c1e_ovlp')
  File "/moto/berkelbach/users/sjb2225/sTDA/pyscf_4c1e/pyscf/pyscf/gto/mole.py", line 3488, in intor
    shls_slice, comp, hermi, aosym, out=out)
  File "/moto/berkelbach/users/sjb2225/sTDA/pyscf_4c1e/pyscf/pyscf/gto/moleintor.py", line 241, in getints
    aosym, ao_loc, cintopt, out)
  File "/moto/berkelbach/users/sjb2225/sTDA/pyscf_4c1e/pyscf/pyscf/gto/moleintor.py", line 648, in getints4c
    cintopt = make_cintopt(atm, bas, env, intor_name)
  File "/moto/berkelbach/users/sjb2225/sTDA/pyscf_4c1e/pyscf/pyscf/gto/moleintor.py", line 813, in make_cintopt
    foptinit = getattr(libcgto, intor+'_optimizer')
  File "/moto/opt/anaconda3-5.3.1/lib/python3.7/ctypes/__init__.py", line 369, in __getattr__
    func = self.__getitem__(name)
  File "/moto/opt/anaconda3-5.3.1/lib/python3.7/ctypes/__init__.py", line 374, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /moto/berkelbach/users/sjb2225/sTDA/pyscf_4c1e/pyscf/pyscf/lib/libcgto.so: undefined symbol: int4c1e_ovlp_optimizer

when I try to run

```
from pyscf import gto

mol = gto.M(
    verbose = 0,
    atom = 'C 0 0 0; O 0 0 1.5',
    basis = 'ccpvdz'
)
s = mol.intor('int4c1e_ovlp')
```
