### ISSUE TITLE
Character table of C2v group seems incorrect

### ISSUE THREAD

**Issue by fishjojo** [pyscf/pyscf#1430]
In [here](https://github.com/pyscf/pyscf/blob/78cd85863fe17c1281d2fc28403451083cf9001b/pyscf/symm/param.py#L121-L122), it seems B1 and B2 need to be swapped.

**Comment by pwborthwick** [comment]
From Housecroft 'Introduction to Molecular Symmetry' 
![image](https://user-images.githubusercontent.com/73105740/190847432-2d7f0095-85b8-4f2c-b7fc-ad587cd916da.png)

A quick look at other sources confirms that you are right and the table in pyscf is wrong.

**Comment by sunqm** [comment]
sx in the code means the plane perpendicular to x axis. So it is consistent with your table. I've added some comments in param.py .

**Comment by verena-neufeld** [comment]
@fishjojo , thanks for raising this issue. Has it been resolved?

**Comment by sunqm** [comment]
Using the testing script from #1464 , it's not hard to see that the px orbitals of the oxygen atom is assigned to B1 symmetry, and py orbitals are assigned to B2 symmetry. I believe the irreps are correctly labelled. I'll mark this issue as solved for the moment. Feel free to reopen the issue to continue the discussion.
