### ISSUE TITLE
Example give errors.

### ISSUE THREAD

**Issue by sunnowrun** [pyscf/pyscf#1431]
I run 1-advanced)/030-transition_dipole but give below error.

Traceback (most recent call last):
  File "usage_mole.py", line 1063, in <module>
    mc.kernel(mo)
  File "/home/zjsun/anaconda3/lib/python3.8/site-packages/pyscf/mcscf/mc1step_symm.py", line 71, in kernel
    _kern(self, mo_coeff,
  File "/home/zjsun/anaconda3/lib/python3.8/site-packages/pyscf/mcscf/mc1step.py", line 352, in kernel
    e_tot, e_cas, fcivec = casscf.casci(mo, ci0, eris, log, locals())
  File "/home/zjsun/anaconda3/lib/python3.8/site-packages/pyscf/mcscf/mc1step.py", line 864, in casci
    e_tot, e_cas, fcivec = casci.kernel(fcasci, mo_coeff, ci0, log,
  File "/home/zjsun/anaconda3/lib/python3.8/site-packages/pyscf/mcscf/casci.py", line 577, in kernel
    e_tot, fcivec = casci.fcisolver.kernel(h1eff, eri_cas, ncas, nelecas,
TypeError: kernel() got multiple values for argument 'ci0'

**Comment by hebrewsnabla** [comment]
Replace `mc.fcisolver = mcscf.state_average_mix(mc, [solver_ag,solver_b2u], [.5,.5])` by
`mc = mcscf.state_average_mix(mc, [solver_ag,solver_b2u], [.5,.5])`

**Comment by sunnowrun** [comment]
> Replace `mc.fcisolver = mcscf.state_average_mix(mc, [solver_ag,solver_b2u], [.5,.5])` by `mc = mcscf.state_average_mix(mc, [solver_ag,solver_b2u], [.5,.5])`

Thank you, this works.
And I want to ask, can I get integral over momentum operator?
And I also want to ask, what 'cint1e_r_sph' means?
And I confused about lots of the intor_name, can more details can be given? (such as “int1e_ia01p”, I confused the expression '(#C(0 1) | nabla-rinv | cross p)')

**Comment by sunqm** [comment]
Integral function for derivatives `\nabla` is `int1e_ip`. `ip` means `1j * p`.
cint1e_r_sph is the integral over position operator `r`.
`#C(0 1)` means `1j` in python. `nabla-rinv cross p` = `\nabla 1/r \times p`

**Comment by sunnowrun** [comment]
> Integral function for derivatives `\nabla` is `int1e_ip`. `ip` means `1j * p`. cint1e_r_sph is the integral over position operator `r`. `#C(0 1)` means `1j` in python. `nabla-rinv cross p` = `\nabla 1/r \times p`

Thank you very much.
