### ISSUE TITLE
Scf with minao and atom init guess yields different output with the same input.

### ISSUE THREAD

**Issue by haakoek** [pyscf/pyscf#1433]
When I run the following example, using the minao initial guess, I get different scf energies just by running the code repeatedly. The same happens if the atom initial guess is used. However, using the 1e or hcore init guess yields the same energy every time. I have checked the output from the scf module I get if mol.verbose=4, and it looks like the setup is exactly the same, however, the energy in the first scf energy and then the converged energy, differ at random. Is there a reasonable explanation for this behavior? 
```
from pyscf import gto, scf
import numpy as np

theta1 = np.pi / 4
theta2 = -theta1
theta3 = theta1+np.pi
theta4 = -theta3

#Place H atoms on a circle with radius R=3.284 bohr (a0)
#theta1 = np.pi / 4 yields a square arrangement
r = 3.284 
x1, y1 = r*np.cos(theta1), r*np.sin(theta1)
x2, y2 = r*np.cos(theta2), r*np.sin(theta2)
x3, y3 = r*np.cos(theta3), r*np.sin(theta3)
x4, y4 = r*np.cos(theta4), r*np.sin(theta4)

geometry = f"""
H {x1} {y1} 0.0; 
H {x2} {y2} 0.0;
H {x3} {y3} 0.0;
H {x4} {y4} 0.0
"""

basis = "dzp"

for i in range(10):

	mol = gto.M(unit="bohr")
	mol.verbose = 3
	mol.build(atom=geometry, basis=basis)

	mf = scf.RHF(mol)
	mf.init_guess = "minao"
	mfe = mf.kernel()

#Output

#converged SCF energy = -1.72853543133655
#RHF/RKS wavefunction is stable in the internal stability analysis

#converged SCF energy = -1.72853543134011
#RHF/RKS wavefunction is stable in the internal stability analysis

#converged SCF energy = -1.72853543134037
#RHF/RKS wavefunction is stable in the internal stability analysis

#converged SCF energy = -1.72853543134037
#RHF/RKS wavefunction is stable in the internal stability analysis

#converged SCF energy = -1.67532890965391
#RHF/RKS wavefunction has an internal instability

#converged SCF energy = -1.67532891000723
#RHF/RKS wavefunction has an internal instability

#converged SCF energy = -1.72853543134037
#RHF/RKS wavefunction is stable in the internal stability analysis

#converged SCF energy = -1.72853543133454
#RHF/RKS wavefunction is stable in the internal stability analysis

#converged SCF energy = -1.67532890957889
#RHF/RKS wavefunction has an internal instability

#converged SCF energy = -1.72853543134037
#RHF/RKS wavefunction is stable in the internal stability analysis 
```

**Comment by jamesETsmith** [comment]
Hi @haakoek, thanks for posting your question. Since PySCF doesn't use symmetry by default you're finding a solution that breaks the symmetry of the problem. That's why you're calculations that yield a higher energy all show an "internal instability". If you want the symmetric solution just use `symmetry=True` when you initialize your molecule. See the modified input below:

```python
from pyscf import gto, scf
import numpy as np

theta1 = np.pi / 4
theta2 = -theta1
theta3 = theta1+np.pi
theta4 = -theta3

#Place H atoms on a circle with radius R=3.284 bohr (a0)
#theta1 = np.pi / 4 yields a square arrangement
r = 3.284 
x1, y1 = r*np.cos(theta1), r*np.sin(theta1)
x2, y2 = r*np.cos(theta2), r*np.sin(theta2)
x3, y3 = r*np.cos(theta3), r*np.sin(theta3)
x4, y4 = r*np.cos(theta4), r*np.sin(theta4)

geometry = f"""
H {x1} {y1} 0.0; 
H {x2} {y2} 0.0;
H {x3} {y3} 0.0;
H {x4} {y4} 0.0
"""
basis = "dzp"

for i in range(10):

    mol = gto.M(unit="bohr")
    mol.verbose = 3
    mol.build(atom=geometry, basis=basis, symmetry=True)

    mf = scf.RHF(mol)
    mf.init_guess = "minao"
    mfe = mf.kernel()
    mf.stability()
```

Will yield output like:
```shell
converged SCF energy = -1.6753289095632
<class 'pyscf.scf.hf_symm.SymAdaptedRHF'> wavefunction is stable in the internal stability analysis

...
...
```

**Comment by haakoek** [comment]
Thank you for the quick reply @jamesETsmith. 

It solves the issue of the minao initial guess yielding different energies, but, it yields the energy that was flagged as unstable before. The lower energy state, which was marked as stable when symmetry is not explicitly set to True is then "lost".  

However, I am still bewildered by the fact that I can get two different results with the exact same input, as long as there is no randomness involved in selecting the initial guess.

**Comment by fishjojo** [comment]
If you use only 1 thread, you will get the same results. If you look at the first iteration, you will find HOMO==LUMO, and there are two ways to occupy the electrons. So you get two solutions depending on the round-off errors in multithreaded calculations.

**Comment by jamesETsmith** [comment]
@haakoek, it's not that the solution is "lost" it's just inaccessible from the symmetric manifold. The lower energy solution is likely on a non-symmetric manifold.

The inconsistencies you see are likely due to small numerical instabilities (e.g. when using multiple threads as @fishjojo suggests) that break the symmetry. When this happens you often see big jumps in energy because you've found a solution on a **different** **manifold**.

**Comment by haakoek** [comment]
I can confirm that adding the following lines of code (and not setting symmetry=True in mol object), 
```
from pyscf import lib
lib.num_threads(1)
```
as suggested by @fishjojo, to the previously posted code resolves the issue of getting different solutions with the same input. In particular, I get the lowest energy solution converged SCF energy = -1.7285354313403.

**Comment by susilehtola** [comment]
And the reason for the many outputs is that this is a system with strong correlation where one can find many Hartree-Fock solutions, and the one that any calculation will converge to may be chaotic and depend on numerical noise.
