### ISSUE TITLE
Symmetry Breaking when using HF molecular orbitals for CASSCF calculation

### ISSUE THREAD

**Issue by bavramidis** [pyscf/pyscf#1437]
Hello - when trying to run a HF calculation on a dication, then using those molecular orbitals to run a CASSCF on the same molecule but neutral charge, it seems as though the calculation runs successfully when symmetry is turned off for both molecules, or when symmetry is turned on for one and off for the other, but not when symmetry is turned on for both.

Take water as the example. The following code:

from pyscf import gto, scf, lo, mcscf
import numpy as np

#initialize dication

cation_mol = gto.Mole()
cation_mol.verbose = 9

cation_mol.atom = '''
O 0 0      0
H 0 -2.757 2.587
H 0  2.757 2.587'''
cation_mol.basis = 'augccpvdz'
cation_mol.symmetry = True
cation_mol.charge=2
cation_mol.build()

myhf = cation_mol.ROHF().run()

MOs = myhf.mo_coeff

#initialize neutral

neutral_mol = gto.Mole()
neutral_mol.verbose=9

neutral_mol.atom = '''
O 0 0      0
H 0 -2.757 2.587
H 0  2.757 2.587'''
neutral_mol.basis = 'augccpvdz'
neutral_mol.symmetry = True
neutral_mol.charge=0
neutral_mol.build()

mycas = mcscf.CASSCF(neutral_mol,2,2)
mycas.run(mo_coeff=MOs)
mycas.analyze()

Produces the following error at the CASSCF step:

******** <class 'pyscf.mcscf.mc1step_symm.SymAdaptedCASSCF'> ********
CAS (1e+1e, 2o), ncore = 4, nvir = 35
max_cycle_macro = 50
max_cycle_micro = 4
conv_tol = 1e-07
conv_tol_grad = None
orbital rotation max_stepsize = 0.02
augmented hessian ah_max_cycle = 30
augmented hessian ah_conv_tol = 1e-12
augmented hessian ah_linear dependence = 1e-14
augmented hessian ah_level shift = 1e-08
augmented hessian ah_start_tol = 2.5
augmented hessian ah_start_cycle = 3
augmented hessian ah_grad_trust_region = 3
kf_trust_region = 3
kf_interval = 4
ci_response_space = 4
ci_grad_trust_region = 3
with_dep4 0
natorb = False
canonicalization = True
sorting_mo_energy = False
ao2mo_level = 2
chkfile = /scratch/slurm-6884099/tmpjllprnr7
max_memory 4000 MB (current use 88 MB)
internal_rotation = False
******** <class 'pyscf.fci.direct_spin1_symm.FCISolver'> ********
max. cycles = 50
conv_tol = 1e-08
davidson only = True
linear dependence = 1e-10
level shift = 0.001
max iter space = 12
max_memory 4000 MB
nroots = 1
pspace_size = 0
spin = None
CI wfn symmetry = None
Active space irreps [0 2]
Traceback (most recent call last):
  File "/ihome/kjordan/bea60/Desktop/C20/PySCF/Dication/CAStest/test/new/watertest/test.py", line 37, in <module>
    mycas.run(mo_coeff=MOs)
  File "/bgfs/kjordan/shu8/miniconda3/lib/python3.9/site-packages/pyscf/lib/misc.py", line 512, in run
    self.kernel(*args)
  File "/bgfs/kjordan/shu8/miniconda3/lib/python3.9/site-packages/pyscf/mcscf/mc1step_symm.py", line 67, in kernel
    mo_coeff = self.mo_coeff = casci_symm.label_symmetry_(self, mo_coeff, ci0)
  File "/bgfs/kjordan/shu8/miniconda3/lib/python3.9/site-packages/pyscf/mcscf/casci_symm.py", line 132, in label_symmetry_
    s = reduce(numpy.dot, (cas_orb.conj().T, mc._scf.get_ovlp(), mc._scf.mo_coeff))
  File "<__array_function__ internals>", line 180, in dot
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

Is there a way around this so that symmetry can be used for both the HF calculation of the MOs as well as the CASSCF calculation? We also observe this for other molecules using the same approach, not just water.

Thank you,
Ben

**Comment by sunqm** [comment]
The line to create mycas
```
mycas = mcscf.CASSCF(neutral_mol,2,2)
```
should be
```
mycas = mcscf.CASSCF(neutral_mol.RHF().run(),2,2)
```
