### ISSUE TITLE
Different MP2 energies from PySCF and MRCC in HeH+ calculation

### ISSUE THREAD

**Issue by Geositta2000** [pyscf/pyscf#1438]
Hi,

for the following input
```
from pyscf import gto,scf,dft,cc,tools
mol = gto.Mole()
mol.verbose = 8
mol.output = 'heh_sto3g.log'

mol.atom = '''
He 0. 0. 0.
H  0. 0. 1.4632
'''
mol.unit = 'B'


mol.charge = 1
mol.spin = 0

mol.symmetry = False
mol.basis = 'sto-3g'
mol.build()


mf = scf.RHF(mol)

mf.conv_tol = 1e-16
mf.kernel()
mf.analyze()

mf = mol.RHF().run()
mf.MP2().run()

mycc = cc.CCSD(mf)
mycc.frozen = 0
mycc.kernel()
```

I got
```
**** SCF Summaries ****
Total Energy =                          -2.841836499287377
...
transform (ia|jb) incore
    CPU time for Integral transformation      0.00 sec, wall time      0.00 sec
E(MP2) = -2.84907480881668  E_corr = -0.00723830953495431
...
******** <class 'pyscf.cc.ccsd.CCSD'> ********
CC2 = 0
CCSD nocc = 1, nmo = 2
frozen orbitals 0
max_cycle = 50
direct = 0
conv_tol = 1e-07
conv_tol_normt = 1e-05
diis_space = 6
diis_start_cycle = 0
diis_start_energy_diff = 1e+09
max_memory 4000 MB (current use 71 MB)
total FLOPs 60.0
E1 = -5.151801185145456  E_coul = 0.9430975453497925
    CPU time for CCSD integral transformation      0.00 sec, wall time      0.00 sec
Init t2, MP2 energy = -2.84907482620493  E_corr(MP2) -0.00723832692320699
    CPU time for init mp2      0.00 sec, wall time      0.00 sec
```
Why the MP2 energy from MP2 and CCSD are different beyond the SCF convergence threshold?  -0.00723830953495431 vs -0.00723832692320699  

If I use MRCC and modify its basis set as print out in PySCF, I got from
```
basis=sto-3g
calc=ccsd
scftype=RHF
scfmaxit=128
scftol=15
mem=900MB
mult=1
core=0
ccsdthreads=1
ptthreads=1
cctol=12
verbosity=3
dens=2
ovltol=0
symm=off

unit=bohr
geom=xyz
2

H 0.000000 0.000000 0.00000
He 0. 0. 1.4632
```

```
***FINAL HARTREE-FOCK ENERGY:     -2.8418364992873730 [AU] 
    Total MP2 energy [au]:               -2.849074766057
```
I got -0.007238266769627, actually the third number

**Comment by obackhouse** [comment]
Try adding `dfbasis_cor=none` to your MRCC script? Looks like the default option is `auto`, so MRCC may be using RI to calculate the MP2 energies.

**Comment by Geositta2000** [comment]
Thanks. I add `dfbasis_cor=none`, still get 
` Total MP2 energy [au]:               -2.849074766057`

**Comment by pwborthwick** [comment]
If you remove theredundant line `mf = mol.RHF().run()` and run the code you should get from MP2 module  -0.007,238,266,770,12286 and from CCSD module as an iniial $T_2$ guess -0.007,238,266,770,19319 which agree better than 1e-12. They also agree better than 1e-11 with MRCC.

**Comment by Geositta2000** [comment]
> If you remove the redundant line `mf = mol.RHF().run()` and run the code you should get from MP2 module -0.007,238,266,770,12286 and from CCSD module as an iniial T2 guess -0.007,238,266,770,19319 which agree better than 1e-12. They also agree better than 1e-11 with MRCC.

Thanks. It works. Though why `mf = mol.RHF().run()` it leads to this difference? does it use default the convergence threshold?

**Comment by pwborthwick** [comment]
@Geositta2000 , That's a good question 'why the difference?'. From the first SCF 
`
SCF conv_tol = 1e-16
SCF conv_tol_grad = None
SCF max_cycles = 50
direct_scf = True
direct_scf_tol = 1e-13
`
and from the second if you have `mf = mol.RHF().run()` in
`SCF conv_tol = 1e-09
SCF conv_tol_grad = None
SCF max_cycles = 50
direct_scf = True
direct_scf_tol = 1e-13
`
so yes the **SCF conv_tol** if reduced from 1e-16 to 1e-9.
