### ISSUE TITLE
Inconsistent MOs on linux vs macos

### ISSUE THREAD

**Issue by harrkee** [pyscf/pyscf#1449]
I'm running into inconsistent behaviour when running a simple HF calculation on linux. See the below test which gets the one-electron integrals in the MO basis twice, and checks for consistency:
```
def test():
    mol = gto.Mole().build(
        atom="He 0 0 0; He 0 0 1",
        basis="ccpvdz",
        verbose=0,
    )
    mf1 = scf.RHF(mol)
    mf2 = scf.RHF(mol)
    mf1.kernel()
    mf2.kernel()
    h1_1 = mf1.get_hcore()
    h1_2 = mf2.get_hcore()
    h1_1_mo = numpy.einsum('ki,kl,lj->ij', mf1.mo_coeff, h1_1, mf1.mo_coeff)
    h1_2_mo = numpy.einsum('ki,kl,lj->ij', mf2.mo_coeff, h1_2, mf2.mo_coeff)
    assert numpy.allclose(h1_1_mo, h1_2_mo)
```
This test consistently passes on macos with pyscf v2.0.1; both mf objects converge to the same ground state with identical MO coefficients. 

On linux however, the energy of the two ground states are always in agreement, but the MOs are not. Sometimes it passes, sometimes it fails. I've tested this on three different linux systems, and on pyscf versions 1.7.6, 2.0.1, and 2.1.1, and the inconsistency persists.

It is my understanding that the HF solution is not unique, but I don't see how I could be finding two different solutions with the code above. Or why they should be different on linux compared to macos.

Thanks

**Comment by pwborthwick** [comment]
The eigensolution is not unique with respect to phase. I think the assert is failing because of an occasional sign difference between solutions. For example one run fails the assertion because (looking at np.allclose) the values -4.68461519e-01 and 4.68461519e-01 produce False.

**Comment by harrkee** [comment]
I think you are right @pwborthwick. My main concern is that, on macos, we consistently converge to the solution with the same phase, but on linux it is seemingly picks one at random. It is not clear to me where this randomness comes from.

**Comment by pwborthwick** [comment]
It's down to rounding errors in the diagonalisation procedure I believe, which will differ slightly with operating environment. Some programs attempt to ensure consistency and this is discussed eg [here](https://stackoverflow.com/questions/52958436/eigenvector-ambiguity-how-to-enforce-a-specific-sign-convention#:~:text=Ensure%20the%20first%20coefficient%20of%20each%20eigenvector%20is,the%20first%20coefficient%20of%20largest%20magnitude%20is%20positive.) and issue was raised in pyscf #580. This sign difference comes out in the wash when calculating physical (observables) quantities.

**Comment by obackhouse** [comment]
> I think you are right @pwborthwick. My main concern is that, on macos, we consistently converge to the solution with the same phase, but on linux it is seemingly picks one at random. It is not clear to me where this randomness comes from.

The randomness is likely coming from threading. The operations required for diagonalization are not guaranteed to commute in finite precision, so threading can result in non-deterministic behaviour. If you set `OMP_NUM_THREADS=1`, you should get deterministic behaviour.

**Comment by pwborthwick** [comment]
@obackhouse don't think it's related to threads. I've tried adding
 ```
import os
os.environ['OMP_NUM_THREADS'] = '1'
```
which returns with
```
import threading
print('Number of threads = ', threading.active_count()
```
the value
```
Number of threads = 1
```
and this make no difference as I still get random assertion errors.

**Comment by susilehtola** [comment]
> It's down to rounding errors in the diagonalisation procedure I believe, which will differ slightly with operating environment. Some programs attempt to ensure consistency and this is discussed eg [here](https://stackoverflow.com/questions/52958436/eigenvector-ambiguity-how-to-enforce-a-specific-sign-convention#:~:text=Ensure%20the%20first%20coefficient%20of%20each%20eigenvector%20is,the%20first%20coefficient%20of%20largest%20magnitude%20is%20positive.) and issue was raised in pyscf #580. This sign difference comes out in the wash when calculating physical (observables) quantities.

Well, another way to say it is that the wave function is arbitrary to a phase factor; for real functions this means a sign.

This also applies to any eigenproblems: Mv = ev is arbitrary to a sign of the eigenvectors, and therefore any comparisons of the eigenvectors should be done in a manner that is invariant to changes in the phase.

**Comment by susilehtola** [comment]
This is also not a Linux vs MacOS issue. Threading can cause small roundoff differences in the matrices, and change the sign of the solution. Different linear algebra libraries on the same platform can also yield different signs.

**Comment by pwborthwick** [comment]
@harrkee to sum up

1. There was nothing wrong with the behaviour of your original code. The ```assert``` was correctly noting the arbitrary nature of the wavefunction phase as I noted in my first post  
> The eigensolution is not unique with respect to phase

and expanded on by susilehota. The computed values are all correct.

2. The arbitrary nature is due to 
> the operating environment

in general and , as susilehota has pointed out, not a difference between macos and linux (both unix based OS's) in particular.

3. obackhouse has elucidated the reason for the sign differences as being the multi-threading

>The randomness is likely coming from threading

this is confirmed by adding the lines 
```
from pyscf import lib
lib.num_threads(1)
```
after which I get ```assert=True``` consistently.  (Perhaps add 
```
from pyscf import lib
print('Active threads = ', lib.num_threads())
```
to satisfy yourself that macos **is** multi-threading and the consistency that you're getting with it isn't because macos is already only using a single thread)

4. If you want to employ multi-threading and **still** want to get a consistent sign then you will have to use some convention to fix the sign of the eigenvectors as alluded to in the post I referenced earlier.

5. From the ```num_threads``` documentation
>It’s recommended to call this function to set OMP threads than “os.environ[‘OMP_NUM_THREADS’] = int(n)”. This is because environment variables like OMP_NUM_THREADS were read when a module was imported. They cannot be reset through os.environ after the module was loaded.

Which explains why my attempt to use OMP_NUM_THREADS didn't work.

**Comment by obackhouse** [comment]
> If you want to employ multi-threading and still want to get a consistent sign then you will have to use some convention to fix the sign of the eigenvectors as alluded to in the post I referenced earlier.

PySCF actually has a convention

https://github.com/pyscf/pyscf/blob/6f7f0a8145d7240a5f95b2d3837cd4c35c80c985/pyscf/scf/hf.py#L1166-L1167

but it does not deterministically handle the phase of coefficients corresponding to degenerate MOs

**Comment by susilehtola** [comment]
> > If you want to employ multi-threading and still want to get a consistent sign then you will have to use some convention to fix the sign of the eigenvectors as alluded to in the post I referenced earlier.
> 
> PySCF actually has a convention
> 
> https://github.com/pyscf/pyscf/blob/6f7f0a8145d7240a5f95b2d3837cd4c35c80c985/pyscf/scf/hf.py#L1166-L1167
> 
> but it does not deterministically handle the phase of coefficients corresponding to degenerate MOs

Degenerate eigenvectors are harder since they can be rotated arbitrarily amongst each other and the only mathematically valid check is if they span the same subspace...
