### ISSUE TITLE
Be able to dump CI wave function to file

### ISSUE THREAD

**Issue by susilehtola** [pyscf/pyscf#145]
pyscf appears to have a pretty powerful CI solver that appears to be able to routinely handle hundreds of millions of configurations.

It would be nice to be able to dump CASSCF/FCI/HCI vector(s) from pyscf in the format used by ClusterDec, i.e.

ndets norb nalpha nbeta
coeff(1) conf(1)
coeff(2) conf(2)
....
coeff(ndets) conf(ndets)

where ndets is the length of the CI expansion,  norb is the number of active orbitals, and nalpha and nbeta the number of active alpha and beta electrons. The configurations are written in ASCII strings with '0' for unoccupied, 'u' for spin-up, 'd' for spin-down and '2' for closed-shell orbital occupation.

Here's an example output

10 44 25 25
-8.884577612344385e-01 22222222222222222222222220000000000000000000
 2.509202814110464e-01 22222222222222222222222202000000000000000000
 1.107152188104699e-01 22222222222222222222222020200000000000000000
-1.043172296590339e-01 22222222222222222222222dudu00000000000000000
-1.043137239596927e-01 22222222222222222222222udud00000000000000000
-6.319335030557863e-02 22222222222222222222222dduu00000000000000000
-6.318729861701712e-02 22222222222222222222222uudd00000000000000000
-5.095537907595309e-02 22222222222222222222222002200000000000000000
-3.919265294855768e-02 22222222222222222222222uddu00000000000000000

**Comment by jparkhill** [comment]
Susi - 
  Actually the CI code dumps nearly exactly that. 

try:

cis = direct_spin0.FCISolver(mol)
norb = m.mo_coeff.shape[1]
nelec = mol.nelectron
h1e = reduce(numpy.dot, (m.mo_coeff.T, m.get_hcore(), m.mo_coeff))
eri = ao2mo.incore.general(m._eri, (m.mo_coeff,)*4, compact=False)
e, c = cis.kernel(h1e, eri, norb, nelec)
print(e - -15.9977886375)
print(norb,nelec,c.shape)
print("Num Strings: ", cistring.num_strings(norb,nelec/2))
for alpha_addr in range(c.shape[0]):
	for beta_addr in range(c.shape[0]):
		print("String a,b,weight:",bin(cistring.addrs2str(norb,nelec/2,[alpha_addr])[0]),bin(cistring.addrs2str(norb,nelec/2,[beta_addr])[0]),c[alpha_addr,beta_addr])

**Comment by gkc1000** [comment]
Indeed, the FCI code is designed to hit the theoretical peak of the machine.

The algorithm uses the standard alpha/beta string convention, and the CI vector is stored in a matrix of shape [nalphastr, nbetastr]. The relevant functions to manipulate strings are in cistring.py.

**Comment by sunqm** [comment]
Here is another relevant example https://github.com/sunqm/pyscf/blob/master/examples/fci/11-large_ci.py.  This example outputs the indices of occupied alpha orbitals and beta orbitals for each determinant.  It should not be hard to modify this example to output the CI coefficients in ClusterDec format.

**Comment by susilehtola** [comment]
So is it so that the CI code doesn't store the determinant strings, number of alpha and electrons, nor the number of orbitals? I'd like to avoid having to pass those around. Especially as the above examples don't really make it clear what happens if na!=nb.

**Comment by sunqm** [comment]
The number of orbitals, electrons, or strings are not saved in the FCI module.  In the selected CI module, strings are saved with the coefficients.  The FCI module may be refactored in the future in the similar style to include more information.  For now, you have to pass these parameters to the "large_ci" function.  When na!=nb, nelec can be a tuple,
```
mc.fcisolver.large_ci(mc.ci, ncas, (na,nb), tol=.05, return_strs=False)
```

**Comment by sunqm** [comment]
> Susi - Actually the CI code dumps nearly exactly that.
> 
> try:
> 
> cis = direct_spin0.FCISolver(mol) norb = m.mo_coeff.shape[1] nelec = mol.nelectron h1e = reduce(numpy.dot, (m.mo_coeff.T, m.get_hcore(), m.mo_coeff)) eri = ao2mo.incore.general(m._eri, (m.mo_coeff,)*4, compact=False) e, c = cis.kernel(h1e, eri, norb, nelec) print(e - -15.9977886375) print(norb,nelec,c.shape) print("Num Strings: ", cistring.num_strings(norb,nelec/2)) for alpha_addr in range(c.shape[0]): for beta_addr in range(c.shape[0]): print("String a,b,weight:",bin(cistring.addrs2str(norb,nelec/2,[alpha_addr])[0]),bin(cistring.addrs2str(norb,nelec/2,[beta_addr])[0]),c[alpha_addr,beta_addr])

Although pyscf does not provide functions to write out CI coefficients in the requested format, it should not be too difficult to write a script to dump CI wfn based on this code example .
