### ISSUE TITLE
Multigrid currently doesn't work for gamma-point DFT

### ISSUE THREAD

**Issue by awhite862** [pyscf/pyscf#1454]
This behavior can be seen in the multigrid example (`examples/pbc/27-multigrid.py`)

**Comment by fishjojo** [comment]
You may try this [example](https://github.com/fishjojo/pyscf/blob/patch1/examples/pbc/27-multigrid2.py) in this [branch](https://github.com/fishjojo/pyscf/tree/patch1). There are some cleanups needed to merge the code into the main branch.

**Comment by sunqm** [comment]
Duplicated to issue #1356
