### ISSUE TITLE
Overriding nested functions

### ISSUE THREAD

**Issue by jonas-greiner** [pyscf/pyscf#1457]
Hi everyone,

I am trying to construct modified `FCISolver` classes in `fci/direct_spin0.py` and `fci/direct_spin1.py` by changing the `hop` function within the kernel functions `kernel_ms0` and `kernel_ms1`. Since these are nested functions that to my knowledge cannot easily be overridden I currently have to copy the whole kernel function into an inherited class. This requires me to update these functions whenever they are modified in the PySCF source code. Is there any way clever and less invasive way this type of thing is meant to be done in the current PySCF infrastructure?

Thanks in advance!
Jonas

**Comment by fishjojo** [comment]
I guess hop can be defined outside the kernel function and passed into kernel as an argument.

**Comment by jonas-greiner** [comment]
Thank you for the response! This does not currently work but could be possible if these arguments were added to `kernel_ms0` and `kernel_ms1`, correct? Can I submit a pull request?

**Comment by fishjojo** [comment]
yes, please feel free to submit a PR.
