### ISSUE TITLE
Molecular orbital coefficient for degenerate state

### ISSUE THREAD

**Issue by ytlee3** [pyscf/pyscf#1458]
Hi everyone, 

I am doing the calculation on HF molecule and I just realized when I change the position of the HF molecule, the corresponding mo_coeff will change. I just assume that the degenerate state could arbitrarily rotate and It shouldn't affect the result of any observable. However, the sign of the mo_coeff will also change.

`mol = gto.M(atom ='H 0 0 0; F 0 0 0.91', basis='sto-3g', symmetry=True)`
`mf = scf.RHF(mol).run()`
`print(np.round(mf.mo_coeff,8))`

<img width="653" alt="Screen Shot 2022-10-11 at 17 30 34" src="https://user-images.githubusercontent.com/95592637/195210214-3c52bda1-cc2b-4d1f-8990-604b3c9f8583.png">

When I shifted to (3,0) 
`mol = gto.M(atom ='H 3 0 0; F 3 0 0.91', basis='sto-3g', symmetry=True)`
`mf = scf.RHF(mol).run()`
`print(np.round(mf.mo_coeff,8))`

<img width="650" alt="Screen Shot 2022-10-11 at 17 31 50" src="https://user-images.githubusercontent.com/95592637/195210368-b23d797f-8ee5-442c-a276-3ce12d83fb16.png">

The 4th and 5th column are degenerate states. the observables won't change if we just switch the information of the 4th and 5th row. However, the sign did change, which could cause different results when I calculate the interaction between 2 HF molecules. I am wondering what's the reason for this sign flip and could we manually set it to the positive value ?  (since there is no physical meaning for wave function )

By the way, even if I turned off the symmetry, there is still a sign-flipped problem. it doesn't matter if I impose symmetry or not in this case. 

I am also wondering how pyscf deal with the mo_coeff of degenerate states 

Thank you so much!

Best, 

Yi-Ting

**Comment by xubwa** [comment]
This sign is arbitrary and there are many related discussion on these two issues on how this randomness of phase is dealt with https://github.com/pyscf/pyscf/issues/1449 and https://github.com/pyscf/pyscf/issues/580

**Comment by ytlee3** [comment]
Hi xubwa, 

I did check those two posts before. Even though I used a single thread, there is still a sign issue. The sign problem is on degenerate states, so it's slightly different from the previous issues. But I agree that it could somehow come from the round-off error, or there are some errors for the 1e/2e integral of degenerate states when it is not at the origin.

Actually, I did use GAMESS to check it again and there is no sign-flipped thing. Either have to manually adjust the result from PySCF (don't like it) or just use the result from GAMESS.

**Comment by xubwa** [comment]
Hi, Yi-Ting
Based on the discussion here, the mo_coeffs actually should be handled properly in terms of sign. But it's only handled once when the eigenvalue solver is called. So I doubt that if you have turned off symmetry when you say you also observe this sign flip when symmetry is off. I tested that several time, the leading value in mo_coeff is always positive.

For your case, the sign flip is actually not a random thing, but rather deterministically when the matrix to transform ao to symmetrized ao is generated https://github.com/pyscf/pyscf/blob/7b91b3ce5a00947654c9057bdf1a22499278b2bf/pyscf/symm/basis.py#L61. It should relate to what happened during this function. Maybe you can add some like this to get a consistent phase. https://github.com/pyscf/pyscf/blob/6f7f0a8145d7240a5f95b2d3837cd4c35c80c985/pyscf/scf/hf.py#L1166-L1167
> > If you want to employ multi-threading and still want to get a consistent sign then you will have to use some convention to fix the sign of the eigenvectors as alluded to in the post I referenced earlier.
> 
> PySCF actually has a convention
> 
> https://github.com/pyscf/pyscf/blob/6f7f0a8145d7240a5f95b2d3837cd4c35c80c985/pyscf/scf/hf.py#L1166-L1167
> 
> but it does not deterministically handle the phase of coefficients corresponding to degenerate MOs

**Comment by susilehtola** [comment]
> The 4th and 5th column are degenerate states. the observables won't change if we just switch the information of the 4th and 5th row. However, the sign did change, which could cause different results when I calculate the interaction between 2 HF molecules. I am wondering what's the reason for this sign flip and could we manually set it to the positive value ? (since there is no physical meaning for wave function )

Gauge transformations to orbitals do not change any physics and will not affect any observables such as interactions between molecules. The sign of an orbital is a special case of a gauge transformation. As the sign is arbitrary, you can assign a sign convention if you want to, but this should not matter to the end result.

**Comment by ytlee3** [comment]
Thanks for @xubwa  and @susilehtola. Update: I just used the latest PySCF (2.1.1) and everything is fine after I turned off the symmetry. (I used 1.7.6 before) I think I will either perform non-symmetry calculation or impose convention on symmetry one. Thank you guys so much !!
