### ISSUE TITLE
numerical instability in MDF make_j3c

### ISSUE THREAD

**Issue by fishjojo** [pyscf/pyscf#1459]
Running the test `pbc/df/test/test_mdf_builder.py` with multiple threads can fail. The failing tests are those involving MDF make_j3c with `aosym='s1'`. It seems to me that some code may be not thread-safe.

**Comment by verena-neufeld** [comment]
Has PR #1622 fixed this?

**Comment by sunqm** [comment]
Please feel free to reopen.
