### ISSUE TITLE
Difference between chgcar.density and cubegen.density

### ISSUE THREAD

**Issue by tillhanke** [pyscf/pyscf#1460]
Hey there, I am currently wondering why the cubegen density function [calls numint.eval_rho](https://github.com/pyscf/pyscf/blob/7b91b3ce5a00947654c9057bdf1a22499278b2bf/pyscf/tools/cubegen.py#L100) and the chgcar is directly computing the einsum via [lib.einsum](https://github.com/pyscf/pyscf/blob/7b91b3ce5a00947654c9057bdf1a22499278b2bf/pyscf/tools/chgcar.py#L93)

What is the benefit of calling eval_rho?
Thanks in advance for any explanation.

**Comment by hebrewsnabla** [comment]
`eval_rho` is a little faster than naive einsum. And `numint.eval_rho2` would be faster.

**Comment by tillhanke** [comment]
ah so nothing more than speed.
Wouldn't it be better to call `eval_rho` in `chgcar.density` as well?
