### ISSUE TITLE
Can I get the number of valid integrals during direct SCF calculations?

### ISSUE THREAD

**Issue by aniki514** [pyscf/pyscf#1463]
Hi, everyone.
If I use the function "scf._vhf.direct" to get the coulomb and exchange integrals(J/K), can I get the number of integrals which are actually used during the calculation?
Thanks in advance for any explanation.

**Comment by hebrewsnabla** [comment]
No, unless you modify nr_direct.c to count the nonzero integrals ( by shell ).

**Comment by aniki514** [comment]
> 



> No, unless you modify nr_direct.c to count the nonzero integrals ( by shell ).

Okay, I get it. Thanks for your explanation.
