### ISSUE TITLE
geomeTRIC release v1.0

### ISSUE THREAD

**Issue by leeping** [pyscf/pyscf#1465]
Hello there,

I released version 1.0 of geomeTRIC 2 days ago.  The software hadn't had a release in more than 2 years, despite a fair bit of development over that time period.  There are some new features such as transition state optimization.  It would be good if you could confirm this new version doesn't cause errors in PySCF, and/or I could help to resolve any issues that arise.  You can also modify your user interface to take advantage of the new features.

Thanks,

- Lee-Ping

**Comment by gkc1000** [comment]
@fishjojo could you try this out?

**Comment by fishjojo** [comment]
It works well.
