### ISSUE TITLE
Comparing CCSD and HF 1RDM?

### ISSUE THREAD

**Issue by szgoger** [pyscf/pyscf#1472]
I've been experimenting with calculating some matrix elements for free atoms with both HF and CCSD methods, expecting that the results change somewhat due to the correlation, but not completely.

I am using the following code

import numpy as np
import pyscf
from pyscf import gto, scf, tools, dft, ao2mo, cc

````
#######################################################################
# Initialize the molecule and the calculation
#######################################################################
def setup_system():
    mol = gto.M( # Change atom here
        atom = [["He", (0.0, 0.0, 0.0)]],
        basis = {'He': 'aug-cc-pvqz'},
        spin=0,
        charge=0,
        verbose=0,
        symmetry="SO3"
    )
    mol.build()

    mf0 = scf.ROHF(mol)
    e0 = mf0.kernel()


    mycc = cc.CCSD(mf0)
    e0 = mycc.kernel()

#    return mol, mycc, e0
    return mol, mf0,  e0

#######################################################################
# Main calculations
#######################################################################
molecule, calculator, e0 = setup_system() # setting up the calculation

dm1 = np.asarray(calculator.make_rdm1())
nao = molecule.nao

rr = molecule.intor('int1e_rr').reshape(3,3,nao,nao)

#Quadrupole matrix
print(np.sum( dm1 * rr[0,0,:,:] ))
````
To my understanding, the code should work with both HF and CCSD calculators, which I manually switch by commenting and un-commenting the return of the function `setup_system()`.

What I see is that in practice, the result is highly sensitive to which calculator I am using.

I am certain that this is due to the fact that `dm1` differs wildly between the two methods (in fact, CCSD even returns a tuple for some reason, which is why I have a `numpy` conversion in the code - but the result is the same without this extra conversion).

What is the reason of the large difference between the 1RDM calculated by HF and with CCSD? I'm almost certain the reason is technical, and I am missing a step somewhere in getting a CCSD density matrix that's directly comparable to the HF density - what is this step?

**Comment by tberkel** [comment]
I agree it's confusing, but the reason is because HF make_rdm1 returns the
RDM in the AO basis, and CC make_rdm1 returns the RDM in the MO basis. You
have to change the basis from AO to MO (or vice versa) to compare them
directly.

**Comment by hebrewsnabla** [comment]
for CC, `.make_rdm1(ao_repr=True)` will give you the dm in AO basis.
