### ISSUE TITLE
conda-forge channel installation

### ISSUE THREAD

**Issue by alpinnovianus** [pyscf/pyscf#1473]
Instead of pyscf conda channel
`conda install -c pyscf pyscf`

is it okay to install from conda-forge channel?
`conda install -c conda-forge pyscf`

and if it is alright, could you also upload the version 2.1.1 in conda-forge? 
There, only version 2.0.1 from 8 months ago is available.

While in PyPI, it's already version 2.1.1.

**Comment by sunqm** [comment]
Once this PR passed, pyscf-2.2 will be available on conda forge. https://github.com/conda-forge/pyscf-feedstock/pull/9

**Comment by verena-neufeld** [comment]
@alpinnovianus, has this been resolved?

**Comment by alpinnovianus** [comment]
@verena-neufeld It doesn't seem to be resolved yet.

I still only see 2.0.1:
https://anaconda.org/conda-forge/pyscf/files

and I do not know if or when the abovementioned PR is going to pass...

**Comment by awvwgk** [comment]
Just updated the package on cf today.

**Comment by Raghav-Bell** [comment]
As per [Anaconda website](https://anaconda.org/search?q=platform%3Awin-64+pyscf) there are no pyscf installation files for windows 64 bit . Above discussion works only for OSx

**Comment by sunqm** [comment]
PySCF has never been released for Windows, so this is not an issue specific to the Conda release. I'll close this issue since the conda-forge installation channel for pyscf is available now.
