### ISSUE TITLE
About small components in a DHF calculation

### ISSUE THREAD

**Issue by DanielBajac** [pyscf/pyscf#1478]
Hi all, I was seeing the dhf.py file in the scf module, but I'm not quit sure that the DHF calculation uses the RKB balance in order to generate the small components of the molecular orbitals. 

So, if I do a calculation like:

from pyscf import gto, scf

mol = gto.M(atom='''
O        0.0000000000            0.0000000000           -0.0409868122
H1       0.0000000000            0.7567917171            0.5640254210
H2       0.0000000000           -0.7567917171            0.5640254210
''', basis='6-31g')

mf = scf.DHF(mol)
mf.scf()
n4c, nmo = mf.mo_coeff.shape
n2c = n4c // 2

Are small components of electronic and positronic molecular orbitals (mf.mo_coeff[ n2c:,:]) kinetically balanced with large components?

Thank you very much in advance,

Daniel

**Comment by sunqm** [comment]
Yes, small components are handled using RKB basis.
