### ISSUE TITLE
Unintuitive behavior using dmrgscf (block) and fcisolver attributes

### ISSUE THREAD

**Issue by HehnLukas** [pyscf/pyscf#1479]
If you want to change block settings, such as the maxM value, there are two ways to do so:
1.
```
mc = dmrgscf.DMRGSCF(mf,norb,nelec)
mc.fcisolver = dmrgscf.DMRGCI(mol)
mc.fcisolver.maxM = 50
mc.kernel()
```
2.
```
mc = dmrgscf.DMRGSCF(mf,norb,nelec)
mc.fcisolver = dmrgscf.DMRGCI(mol,maxM = 50)
mc.kernel()
```
However, these lead to different behavior: method 1 only sets the maxM attribute, while leaving scheduleMaxMs = [200, 400, 800, 1000, 1000, 1000, 1000, 1000], which is the default. Method 2 also updates scheduleMaxMs according to the selected maxM: scheduleMaxMs          = [50, 50, 50, 50, 50]

In my opinion, it makes much more sense for the method 2 behavior to always happen, but either way, it is not clear as a user whether you are updating just the one value or also the scheduler behavior.

**Comment by sunqm** [comment]
This problem will be solved in another repo https://github.com/pyscf/dmrgscf/pull/9
