### ISSUE TITLE
Non-deterministic result for direct_uhf.FCISolver with fix_spin_ addon

### ISSUE THREAD

**Issue by maxnus** [pyscf/pyscf#1482]
I'm getting non-deterministic results when using the `fix_spin_` addon with a `direct_uhf` FCI solver (example below).

@sunqm Is the function to evaluate S^2 |CI> ,`spin_op.contract_ss` (which the `direct_uhf` version inherits via `direct_spin1`),  supposed to work for UHF orbitals?

Note that the result is deterministic within a Python interpreter session, but not between sessions. I get variations of multiple mHartree.

[example.py.txt](https://github.com/pyscf/pyscf/files/9854257/direct_uhf_fcisolver_fix_spin.py.txt)

**Comment by obackhouse** [comment]
Determinism within a session but not between sessions makes it sound like it may be due to the hash seed. Often that can result in non-determinism when iterating over `set`s or `dict`s without first casting to a sorted container, c.f. https://github.com/pyscf/pyscf/pull/1242

**Comment by maxnus** [comment]
OK, but the non-determinism is only part of the problem - the solution should not differ by mHa for slightly different order of FLOPS etc.

If the mf is instead converged as a ROHF and then converted to UHF before being passed to the FCISolver, the problem disappears, which makes me believe that the `fix_spin_` addon does not support UHF orbitals.

**Comment by sunqm** [comment]
Your guess is right. fix_spin addon does not support UHF orbitals. The contract_ss function requires orthogonality among spatial orbitals.

**Comment by sunqm** [comment]
I will close the issue for the moment. Feel free to reopen the issue and add the label "feature_request".

**Comment by bganoe92** [comment]
If this is an open offer, UHF support (or even GHF, but I am unsure how tenable that is) for `spin_op.contract_ss` is a feature I'd be incredibly interested in. I am figuring I ran into a similar issue as maxnus.
