### ISSUE TITLE
State-interaction calculations and spin-orbit coupling

### ISSUE THREAD

**Issue by portega-usal** [pyscf/pyscf#1483]
Greetings,

I have just posted a question at ResearchGate (https://www.researchgate.net/post/Spin-orbit_coupling_and_zero-field_splitting_between_triplets_and_singlets_in_Intersystem_Crossings_how_to_calculate_them) which explains the issue in a more broadly way, but I have a related technical question, about the availability of this type of calculations in PySCF.

Let's say I have a triplet and a singlet states and I want to calculate their spin-orbit coupling matrix elements, in a similar way as the output in Molcas or Molpro (Equation 20 in https://onlinelibrary.wiley.com/doi/full/10.1002/qua.25124). I have only found a couple of examples about spin-orbit coupling in PySCF, but they are not about state-interaction, they only include spin-orbit coupling terms in a RHF calculation (as it should be required, for example, for a heavy metal atom system). 

On the other hand, I have found this repository, which is closely related to what I want to do, but I think it's not integrated in any way in PySCF (https://github.com/hczhai/fci-siso). Sadly, I wasn't able to use it for my own system, I think it's not very flexible in the calculation options and maybe it's not even finished. 

My question here would be: Is there any way to obtain the zero-field splitting energy (H_so) for a triplet state interacting with a singlet state? This would be a pseudo-code example of my spin-free CASSCF calculations (my computing cluster is down right now, so I don't have the exact input):

```
from pyscf import gto, scf, mcscf

mol = gto.Mole()
mol.build()  ## add geometry, basis set, etc. spin = 0

mf = scf.RHF(mol).run()
mc = mcscf.CASSCF(mf, 4, 6)
mo = mcscf.sort_mo()  ## I chose some orbitals from a Molden file 
mc.kernel(mo)

## same for triplet, but spin = 2
```

Also, is there any point in considering all this theory outside of the MECP region? For example, taking spin-orbit coupling when triplet-singlet gap is still 20-30 kcal/mol. I think that all the non-adiabatic transition state theory (NA-TST) only applies to the close region to the MECP, especially for weak couplings as in this case. Some people in my group wanted to provide a Landau-Zenner hopping probability outside of MECP region, but I was quite sure that would not make sense, the hopping can only happen right at the MECP.

Best regards and thanks in advance!
Pablo

**Comment by hczhai** [comment]
Hi, There should be no problem of using https://github.com/hczhai/fci-siso for computing SOC splitting between triplets and singlets. If you simply need an example for the usage, I have added a few more examples in that repo. [This](https://github.com/hczhai/fci-siso/blob/master/tests/10-si-casscf.py) is an example for state interaction between triplets and singlets.

**Comment by sunqm** [comment]
https://github.com/pyscf/pyscf/blob/master/examples/fci/35-transition_density_matrix.py shows an example to compute the transition density matrix between singlet and triplet states
