### ISSUE TITLE
A potential type bug in pyscf/lib/pbc/fill_ints_sr.c 

### ISSUE THREAD

**Issue by ywlds** [pyscf/pyscf#1484]
void PBCsr3c_bvk_kk_drv(int (*intor)(), void (*fill)(), double *out,
                        int nkpts_ij, int nkpts,
                        int comp, int nimgs, int bvk_nimgs,
                        double *Ls,
                        double complex *expkL,
                        int *kptij_idx,
                        int *shls_slice, int *ao_loc,
                        CINTOpt *cintopt,
                        int *cell_loc_bvk, int8_t *shlpr_mask,
                        int *refuniqshl_map, int *auxuniqshl_map,
                        int nbasauxuniq, double *uniqexp,
                        double *uniq_dcut2s, double dcut_binsize,
                        double *uniq_Rcut2s, int *uniqshlpr_dij_loc,
                        int *atm, int natm, int *bas, int nbas, double *env,
                        int nenv)

In the about function out is double*, while in other place as shown in the figure, it should be double complex* out.
It should all "double complex* out" @hongzhouye @sunqm 
![oFt37tK5Io](https://user-images.githubusercontent.com/14145559/197946043-cd37f5fc-d408-408a-b160-30c584f64f96.jpg)
![ucRyT4G56A](https://user-images.githubusercontent.com/14145559/197946079-acfea347-5e48-48e9-afef-2d31147ead1e.jpg)

**Comment by sunqm** [comment]
double complex array can be viewed as double array that alternatively stores the real and imaginary parts. `out` array here can be a real array for integrals at gamma point or a complex array for other k-points. It may be not a good practice in the sense of software engineering to mix two different data types here. The code should work without any problems.
