### ISSUE TITLE
Broken symbolic link to libxc library (pip installed on Mac)

### ISSUE THREAD

**Issue by godotalgorithm** [pyscf/pyscf#1490]
I've noticed that libxc isn't active right now on the pip-installed version of PySCF on a Mac. I tracked the problem down to a broken symbolic link in `lib/libxc_itrf.dylib` that is trying to connect with `lib/deps/libxc.9.dylib`, but the library is actually named `lib/deps/libxc.dylib`. I'm not familiar enough with PyPI to suggest what might be causing this packaging problem, and I don't know if it might also affect other OS's.

**Comment by verena-neufeld** [comment]
Hi @godotalgorithm , thank you for posting! Has it been resolved now?

**Comment by godotalgorithm** [comment]
Yes, I just did a fresh install with the latest version of `pyscf`, and the symbolic link looks good now. The `libxc` library version number and path have changed a bit since I reported this issue, but everything is consistent.
