### ISSUE TITLE
How to get electrostatic field at specific points?

### ISSUE THREAD

**Issue by aizvorski** [pyscf/pyscf#1491]
I'm looking for a PySCF way to get the electrostatic field at a list of specific provided points.  This would be something equivalent to the GRID_ESP option in Psi4 https://psicode.org/psi4manual/master/oeprop.html#sec-oeprop-grid  

I looked through the documentation and the closest thing to that I could find was `pyscf.tools.cubegen.mep()` which makes a cube of the electrostatic potential, but doesn't have a way to select only specific points. 

The reason to have something like this (besides speed) is to sample specific points that can be used for fitting partial charges; a lot of the methods to do that require points on a surface around the atoms, not a cube. 

If this doesn't exist already, is it possible to add it?

**Comment by hebrewsnabla** [comment]
See https://github.com/swillow/pyscf_esp

**Comment by aizvorski** [comment]
@hebrewsnabla That's a really nice code, thanks for pointing me to it!

Would it make sense to add the esp_esp() part of that somewhere in core pyscf?  maybe pyscf.tools.mep or something like that - it's not quite "cubegen" ;)

**Comment by hebrewsnabla** [comment]
> @hebrewsnabla That's a really nice code, thanks for pointing me to it!
> 
> Would it make sense to add the esp_esp() part of that somewhere in core pyscf? maybe pyscf.tools.mep or something like that - it's not quite "cubegen" ;)

Yeah, adding it as tools.mep is a good idea. But you need to ask the code owner @swillow if he want to open a PR.

**Comment by swillow** [comment]
I opened a PR today. I added my code as tools.esp.

**Comment by sunqm** [comment]
https://github.com/pyscf/pyscf/blob/master/examples/1-advanced/031-MEP.py this example is also related.
