### ISSUE TITLE
Cn amplitudes from FCI

### ISSUE THREAD

**Issue by ghb24** [pyscf/pyscf#1492]
Is there a way to extract the arbitrary-order "C" amplitudes from a FCI wave function? 

In the cisd functionality, there is a simple function to extract the C1 and C2 amplitudes, but is there any code (either in pyscf, or privately that people are willing to share) to extend this to (say) C3 and C4 amplitudes?

Thanks in advance.

**Comment by gkc1000** [comment]
We should have this code from eCC. @yangdatou @seunghoonlee89 do you have such code? It could be committed as an example or some type of fci addon.

**Comment by seunghoonlee89** [comment]
Hi all, I extracted C1, C2, C3, C4 amplitudes from FCI.
You can check this at exCC repo at: https://github.com/seunghoonlee89/excc/blob/da684700aa3fce664fa1bcbdc2163603cef856db/excc/exccsd_fci_slow.py#L537
I will add fci addon for arbitrary rank of amplitudes.

**Comment by ghb24** [comment]
Many thanks @seunghoonlee89. I actually managed this myself in the end, but useful as an independent check, and could be useful for others. Thanks again.
