### ISSUE TITLE
MO_coeff for unhybridized P orbital

### ISSUE THREAD

**Issue by ytlee3** [pyscf/pyscf#1493]
Hi all, 

I found that the mo_coeff for unhybridized p orbital will be different depending on the version of PySCF and symmetry conditions. (not the sign issue).
I run the following code in different version (single thread) 
``mol = gto.M(atom ='H 0 0 0; F 0 0 0.91', basis='sto3g')``
``mf = scf.RHF(mol).run()``
``mo = mf.mo_coeff``
``print(np.round(mo,7))``

The basis order (row) should be H1s, F2s, F2s, F2x, F2y, F2z.
for 2.0.1  without symmetry 
<img width="596" alt="Screen Shot 2022-10-31 at 15 57 14" src="https://user-images.githubusercontent.com/95592637/199109117-9ebf3636-0d02-421d-914f-e5e95c3dad23.png">

for 2.1.1  without symmetry
<img width="523" alt="Screen Shot 2022-10-31 at 16 01 09" src="https://user-images.githubusercontent.com/95592637/199109751-fd1ec938-4db3-4513-b1af-64e175aa11fa.png">

Based on the Molecular Orbital theory, the Px and Py orbital from F ion should be unhybridized, which means that they shouldn't mix with other basis (column 4 and 5 should be 000100 (100% Fpx) or 000010 (100% Fpy)). However, the result from 2.0.1 doesn't seem like they are unhybridized and Px and Py mix with each other (like rotate). I am wondering if this problem comes from the round off error when the older PySCF constructs and diagonalizes the Hamiltonian containing degenerate states. I don't think it's really the linear combination of degenerate state (i.e. the Px and Py can rotate arbitrarily) since they are unhybridized. 

For the result from 2.1.1, it seems like a round off error. 
(P.S. there is no such an issue when I applied symmetry, but still want to know why this happened) 

Thanks for your help!!

**Comment by tberkel** [comment]
Without symmetry, degenerate orbitals can be freely mixed without changing
the solution. Which mixture is found at convergence depends on details like
the initial guess, eigenvalue algorithm, and possibly hardware details.

**Comment by ytlee3** [comment]
Hi @tberkel  Thanks for your response. Another question is: Can we use the result from non-symmetry calculations ? Is this error or the nature of degenerate states ? I know we definitely can use linear combinations to mix a degenerate state, but these two degenerate orbitals won't freely mix in real life I think. (i.e remain 100% Px and 100% Py). For different mixing conditions, the observable for a single molecule won't change for sure . However,  Coulomb interaction between molecules will change because of this freely mixture of Px and Py for each molecule.  (If I impose symmetry, everything is fine )

**Comment by tberkel** [comment]
It is not an error in the sense that no *observable* property will be
incorrectly calculated due to this mixing, even though non-observable
quantities like matrix elements will be different. The only issue would
arise when you want to *label* states according to the eigenvalues of an
operator that commutes with the Hamiltonian, such as angular momentum. If
this is of interest to a user, then it is appropriate to turn on symmetry.

**Comment by ytlee3** [comment]
Got it. Thank you so much!
