### ISSUE TITLE
Issue generating Brueckner orbitals from CCSD

### ISSUE THREAD

**Issue by zww-4855** [pyscf/pyscf#1495]
Hi

I am trying to build a program to generate Brueckner orbitals in PySCF via CCSD. However, my PySCF results do not align with ACES2 results starting at the second iteration. At this point, I start to see slight deviations in the energy that increase in magnitude as I continue to iterate, my T1 norms stop decreasing, and the second order amplitudes yield an MP2 energy that is appreciably different than ACES2.  All that to say ACES2 converges, while my implementation does not. 

After I rotate the occupied and virtual orbitals with T1, I orthogonalize the set of C, construct a DM, feed that into the SCF class without iteration to rebuild the Fock matrix, re-transform 2 e- integrals, and then finally re-run CCSD.  I  feel like there is something that I am not seeing in my PySCF implementation, or there is something in my code I am overlooking.  I was hoping someone could lend me some help. 

Disclaimer that there is a related  request open at  #1343, but I have not been able to track down any implementation to compare my code to. Perhaps you can direct me in this regard, @zhcui ? To conserve space, I have only posted the functions that drive the brueckner routine, which rotates orbitals and orthogonalize them., but will attach the entire python script for reference. 

```
def orthogonalizeMO(mf,C):
    ovrlap=mf.get_ovlp()
    ovrlapMO=(C.T@ovrlap)@C
    roots,vecs=np.linalg.eigh(ovrlapMO)
[bruecknerCCSD.py.zip](https://github.com/pyscf/pyscf/files/9913594/bruecknerCCSD.py.zip)
[bruecknerCCSD.py.zip](https://github.com/pyscf/pyscf/files/9913596/bruecknerCCSD.py.zip)

    indx = roots.argsort()
    vecs = vecs[:, indx]
    roots=roots[indx]
    newroots=np.zeros((len(roots),len(roots)))
    for i in range(len(roots)):
        newroots[i][i]=1.0/np.sqrt(roots[i])

    X=(vecs@newroots)@vecs.T
    orthog_C=C@X
    print('Verify C^tSC==1',np.allclose((orthog_C.T@ovrlap)@orthog_C,np.eye(X.shape[0])))
    return orthog_C


# Performs Brueckner rotation on occ/virt orbitals
def T1rotate(coeff,t1):
    newcoeff=coeff
    nocc,nvirt=t1.shape

    C_occ=coeff[:,:nocc]
    C_virt=coeff[:,nocc:]
    C_virtold=C_virt

    C_virt=C_virt-C_occ@t1
    C_occ=C_occ+C_virtold@t1.T

    newcoeff=np.zeros(coeff.shape)
    newcoeff[:,:nocc]=C_occ
    newcoeff[:,nocc:]=C_virt

    return newcoeff


def run_brueckner(mf,t1,coeff,nocc,mo_occ,t1TOL=10E-4):
    t1norm=np.linalg.norm(t1)
    newC=coeff
    for i in range(4):
        print('Norm of t1:',t1norm)
        newC=T1rotate(newC,t1)
        newC=orthogonalizeMO(mf,newC)

        # Rebuild Fock matrix
        mf=scf.RHF(mol)
        dm1=mf.make_rdm1(newC,mo_occ)
        mf.init_guess=dm1
        mf.run(max_cycle=0)

        # Converge CCSD eqns & extract new T1
        mycc=cc.CCSD(mf)
        eris=mycc.ao2mo()
        mycc.kernel(eris=eris)
        t1=mycc.t1

        print('max of t1: ',np.max(np.abs(t1)))
        t1norm=np.linalg.norm(t1)

    return mf,dm1
```

**Comment by susilehtola** [comment]
Hi Zach, I've never tried to implement Brueckner but the first thing that came to my mind is that the straightforward attempt to rotate the orbitals by T1 may suffer from the same problem as SCF calculations with the original Roothaan method, that is, the wave function changes too much and the solution blows up. Maybe one needs some sort of damping or DIIS?

Note that the link to your file got pasted twice in the code section; the link should be in the text part as 
[bruecknerCCSD.py.zip](https://github.com/pyscf/pyscf/files/9913594/bruecknerCCSD.py.zip)

**Comment by maxnus** [comment]
I did this some time ago. I think @susilehtola is right, that it needs dampening or DIIS.
Try DIIS on the T1 amplitudes, with the error vector being T1 itself, as it should be zero at convergence.
Alternatively, you can try DIIS on the mean-field density-matrix. the problem beeing that mixtures of idempotent matrices won't be idempotent: You could look into PC-DIIS (J. Chem. Theory Comput. 2017, 13, 11, 5458–5467) or have a "purificication step" a la projected DMET, where you diagonalize the non-idempotent DM and use the eigenvectors of the nocc largest eigenvalues as your new occupied orbitals.

**Comment by pwborthwick** [comment]
Hi,
   There is a repo [Here](https://github.com/gustavojra/Methods/blob/master/Coupled_Cluster/BCC/RBCCD.py)  think it's a spin-restricted treatment but it might help.

**Comment by zww-4855** [comment]
I really appreciate your suggestions and insight, @susilehtola, @maxnus, and @pwborthwick. I will look into incorporating DIIS into my algorithm to see if this changes anything. I was originally of the mindset that I have made a mistake somewhere, since ACES converges so rapidly and seemingly without trouble. ACES similarly does not use DIIS to converge Brueckner, so I figured I would be in the clear. Also, @susilehtola: I tried damping T1 rotation by factor of 0.5 with no impact to the convergence behavior.

@pwborthwick I looked at the psi4 implementation, and it looks like they are choosing to rotate orbitals with T1 every CC iteration; is my understanding correct? 

I will report back when I find out more. Thanks

**Comment by zhcui** [comment]
Hi,

Sorry for the delay.
I just commit a PR for a BCCD implementation:
https://github.com/pyscf/pyscf/pull/1497

Could you test whether it works for your system and the reference number from ACES?

Best,
Zhihao

**Comment by pwborthwick** [comment]
The BCC algorithm is
+ Update non-singles amplitudes $t^{ij..}_{ab...}$
+ Update the singles amplitudes $t^i_a$
+ Build your orbital rotation matrix eg $\boldsymbol{U}=e^({\boldsymbol{T}  - \boldsymbol{T^\dagger})}$ with $\boldsymbol{T}=t^i_a$
+ **do the rotation $\boldsymbol{C^\prime} = \boldsymbol{CU}$**
+ Transform all integral (1 and 2 body) to the new spin orbital basis using $\boldsymbol{C}$
+ If $||t^i_a|| != 0$ or other $t^{ij...}_{ab...}$ amplitudes are not converged then return to first step.

So yes the rotation is performed at each step.

**Comment by maxnus** [comment]
I guess there are two differences then- the first one is the iteration scheme (rotate every iteration vs converge for given mean-field and rotate in an outer loop). I would think that in many cases these two schemes should have the same fix-point though? The second is the rotation itself, I think @zww-4855 you only "rotate" with (1+U), the expansion of exp(U) to linear order?

**Comment by zww-4855** [comment]
I agree, @maxnus . I will mention that the algorithm I am familiar with rotates the coefficients with T1 (and so on) only after the CCSD residuals have converged. This is how I wrote my code and is how ACES2 is written as well. It looks like @zhcui algorithm also follows this logic. But I feel this is not the only way to converge toward the fixed point, and clearly there isn't a unique algorithm since Psi4 implementation ala @pwborthwick is different. So I then suppose convergence behavior for different Brueckner algorithms has not been investigated. very interesting.

**Comment by pwborthwick** [comment]
From Bartlett & Shavitt 'Many Body Methods in Chemistry and Physics: MBPT and Coupled-Cluster Theory' pg 419 

> Brueckner orbitals can be defined, within a given one-electron Hilbert space, by either of two equivalent conditions on the orbitals occupied in the reference determinant: (a) the requirement that single-excitation contributions to the exact wave
 function vanish (Nesbet 1958) or (b) the requirement that the reference determinant has maximum overlap with the 
exact wavefunction (Löwdin 1962b). The equivalence of these conditions can be seen by considering the overlap 
between |Φ B >, the Brueckner reference determinant, and the exact wave function |Ψ>.

In Shavitt & Bartlett they explain an approach in which
 >The transformed orbitals are orthonormalized, and the process is repeated by re-solving the CCSD doubles equations for T̂ 2

There are then two equivalent methods I'm sorry if I confused things by pointing you in the direction of the psi4 repo which did things in a different way to how you were trying. I guess it's down to which way is most efficient  or convenient.

**Comment by zww-4855** [comment]
No problems at all, @pwborthwick , I have learned something new. 

@maxnus I missed this comment earlier: We have found that including nonlinear terms in the series do appreciably impact convergence rate. So in practice, we truncate the expansion at (1+T1). 

I tested @zhcui implementation, where both ACES2 and pySCF converge toward the same CCSD energy. One thing I found interesting is that  his implementation also rotates the initial T1 and T2 amplitudes at each Brueckner iteration.  To my knowledge, ACES does no such thing. I have not been able to convincingly explain why my python implementation fails; I am assuming I have overlooked some formal technicality in python and/or PySCF. I will gradually look more into this. 

In the end, this implementation converges faster than ACES for H2O. I expect this to generally be the case for arbitrary systems as well, since ACES does not employ DIIS for Brueckner. 

I appreciate the commentary everyone. Take care.

Zack

**Comment by maxnus** [comment]
>We have found that including nonlinear terms in the series do appreciably impact convergence rate. So in practice, we truncate the expansion at (1+T1).

Do you mean it does *not* impact convergence rate?

**Comment by zww-4855** [comment]
@maxnus YES!! That was a bad typo to make. Expanding the exp beyond 1+T1 *does not* appreciably impact performance.

**Comment by zhcui** [comment]
Good to know the implementations agree with each other. The DIIS of BCC orbitals indeed may influence the convergence rate. Please update with us after you have more tests or information.

**Comment by pwborthwick** [comment]
@zhcui , I'm curious why you have a custom *logm* routine rather than using *scipy.linalg.logm*? As far as I can see there is no difference to speed or numerical accuracy when using scipy. You also use $e^{(-\boldsymbol{U} +\boldsymbol{U^\dagger}) }$ rather than e^{(\boldsymbol{U} - \boldsymbol{U^\dagger}) } which I've seen elsewhere, and the former seem to lead to better convergence, why is this? 
          Peter

**Comment by zhcui** [comment]
> @zhcui , I'm curious why you have a custom _logm_ routine rather than using _scipy.linalg.logm_? As far as I can see there is no difference to speed or numerical accuracy when using scipy. Peter

Hi Peter,

scipy's logm may return a complex matrix.

Best,
Zhihao

**Comment by pwborthwick** [comment]
> > @zhcui , I'm curious why you have a custom _logm_ routine rather than using _scipy.linalg.logm_? As far as I can see there is no difference to speed or numerical accuracy when using scipy. Peter
> 
> Hi Peter,
> 
> scipy's logm may return a complex matrix.
> 
> Best, Zhihao

np.real
  Best Peter

**Comment by zhcui** [comment]
> > > @zhcui , I'm curious why you have a custom _logm_ routine rather than using _scipy.linalg.logm_? As far as I can see there is no difference to speed or numerical accuracy when using scipy. Peter
> > 
> > 
> > Hi Peter,
> > scipy's logm may return a complex matrix.
> > Best, Zhihao
> 
> You could use np.real(scipy.linalg.logm) save you a subroutine. Best Peter
Try la.logm(np.eye(2) * -1)

**Comment by pwborthwick** [comment]
> > > > @zhcui , I'm curious why you have a custom _logm_ routine rather than using _scipy.linalg.logm_? As far as I can see there is no difference to speed or numerical accuracy when using scipy. Peter
> > > 
> > > 
> > > Hi Peter,
> > > scipy's logm may return a complex matrix.
> > > Best, Zhihao
> > 
> > 
> > You could use np.real(scipy.linalg.logm) save you a subroutine. Best Peter
> 
> Try la.logm(np.eye(2) * -1)

Sorry not to get back sooner - it was night on this side of the Atlantic. Before I try np.eye(2)*-1 what I expect is since $ln(\boldsymbol{A})$ is diagonal if and only if $\boldsymbol{A}$ is diagonal I expect scipy to produce a diagonal matrix with diagonal elements ln(-1) = ln( $e^{i \pi}$ ) = $i\pi$. The real part of which is a matrix entirely of zeros.,,this is exactly what it produces (with some numerical noise). However, the original matrix has negative real eigenvalues so there doesn't exist a principal logarithm and the logarithm is not unique. Your algorithm is better as it finds a non-zero matrix among the possible solutions (determinant still zero), which is essentially lemma 2 from [Sherif and Morsy](http://www.m-hikari.com/ija/ija-password-2008/ija-password1-4-2008/morsyIJA1-4-2008.pdf) I take your point then that there are (pathalogical?) situations that can occur where scipy will fail and your (rather neat) algorithm will not. Thank you for pointing out the potential problems with the scipy logm - When I find a case in practice where scipy fails I'll report back.

**Comment by zhcui** [comment]
> > > > > @zhcui , I'm curious why you have a custom _logm_ routine rather than using _scipy.linalg.logm_? As far as I can see there is no difference to speed or numerical accuracy when using scipy. Peter
> > > > 
> > > > 
> > > > Hi Peter,
> > > > scipy's logm may return a complex matrix.
> > > > Best, Zhihao
> > > 
> > > 
> > > You could use np.real(scipy.linalg.logm) save you a subroutine. Best Peter
> > 
> > 
> > Try la.logm(np.eye(2) * -1)
> 
> Sorry not to get back sooner - it was night on this side of the Atlantic. Before I try np.eye(2)*-1 what I expect is since ln(A) is diagonal if and only if A is diagonal I expect scipy to produce a diagonal matrix with diagonal elements ln(-1) = ln( eiπ ) = iπ. The real part of which is a matrix entirely of zeros.,,this is exactly what it produces (with some numerical noise). However, the original matrix has negative real eigenvalues so there doesn't exist a principal logarithm and the logarithm is not unique. Your algorithm is better as it finds a non-zero matrix among the possible solutions (determinant still zero), which is essentially lemma 2 from [Sherif and Morsy](http://www.m-hikari.com/ija/ija-password-2008/ija-password1-4-2008/morsyIJA1-4-2008.pdf) I take your point then that there are (pathalogical?) situations that can occur where scipy will fail and your (rather neat) algorithm will not. Thank you for pointing out the potential problems with the scipy logm - When I find a case in practice where scipy fails I'll report back.
> 
> PS. The most 'pathalogical' case I've found so far is H2 in STO-3G where the initial rotation matrix is I2 and both scipy and your algorithm return a 2x2 matrix of zeros. The iterations converge after 1 iteration to the same value as with diis switched off.

Ok, sounds great.
