### ISSUE TITLE
how to speed up ao2mo in pyscf

### ISSUE THREAD

**Issue by lucienwb** [pyscf/pyscf#1496]
Hi, are there any tricks to improve the speed of ao2mo in pyscf.
1. Suppose I have big memory space and I want to store the moeri. Then which of the following method should be faster in general:
```
moeri = mol.ao2mo(mo_coeff) # outcore
moeri = ao2mo.incore.full(eri, mo_coeff) # incore
```
2. For outcore method can we further improve its speed by changing the block size or max memory
3. Does ao2mo use PYSCF_MAX_MEMORY, OMP_NUM_THREADS, MKL_NUM_THREADS as defined in the commit script for parallelism? If not can we run it in parallel.

**Comment by sunqm** [comment]
Both the ao2mo incore and outcore implementations use PYSCF_MAX_MEMORY, OMP_NUM_THREADS, MKL_NUM_THREADS automatically. The bottleneck in outcore is IO which often limits the overall threading level speed-up up to 10x no matter how many threads you assigned to the task. Tuning block size and max memory may bring small improvement to outcore code but I guess the improvement will not be more than 10%. If you have enough memory to hold the entire ERI tensor, the incore code should be faster.

**Comment by verena-neufeld** [comment]
Hi @lucienwb , thanks for opening this issue. Has it been resolved?
