### ISSUE TITLE
Bad workspace sizes for DF-UMP2 w/o beta electrons

### ISSUE THREAD

**Issue by godotalgorithm** [pyscf/pyscf#1500]
Fully spin-polarized calculations have workspace sizing problems with DF-UMP2. A minimal example of the problem is:

```
from pyscf.gto import Mole
from pyscf.scf import UHF
from pyscf.mp.dfump2_native import DFUMP2

mol = Mole()
mol.atom = '''
H   0.0   0.0   0.0
H   0.0   0.0   0.8
'''
mol.basis = 'cc-pVDZ'
mol.spin = 2
mol.build()

mf = UHF(mol).run()
DFUMP2(mf).run()
```

I tinkered with some quick fixes that avoided the sections causing the errors, but it doesn't seem like a completely trivial problem to fix.

**Comment by maxnus** [comment]
Replacing `nmo1` with `max(nmo1, 1)` in [line 345](https://github.com/pyscf/pyscf/blob/1246b3da89c585064dafee1c06a00a3b163ab4da/pyscf/mp/dfmp2_native.py#L345) could fix it
