### ISSUE TITLE
ksymm KRHF mismatches when exxdiv=None 

### ISSUE THREAD

**Issue by changsuc** [pyscf/pyscf#1507]
Greetings,
The recently implemented k-symm scf in PySCF greatly enhances its efficiency. Somehow I found the calculation of graphene with exxdiv=None fails when enable k-symm.
In the following is my script:
```
from pyscf.pbc import scf, gto
cell = gto.Cell()
cell.atom = 'C 0 0 0; C 0 2.67303283 0'
cell.a = [[4.6298286730500005, 0.0, 0.0], [-2.3149143365249993, 4.009549246030899, 0.0], [0.0, 0.0, 10]]
cell.basis = 'gth-szv-molopt-sr'
cell.pseudo = 'gth-pade'
cell.verbose = 7
cell.build()

kmesh = [3,3,1]
kpts = cell.make_kpts(kmesh, space_group_symmetry=True, time_reversal_symmetry=True, symmorphic=True)
#kpts = cell.make_kpts(kmesh)

kmf = scf.KRHF(cell, kpts, exxdiv=None).density_fit()
kmf.kernel()
```
Then the results are:
1. If we adopt k-symm SCF, then the calculation will fail to converge even after the default 50 cycles.
2. If we use non-symm by uncommenting `kpts = cell.make_kpts(kmesh)`, then the calculation converges quickly after 11 cycles.
3.  When using the default `exxdiv='ewald'`, both calculations with or without k-symm converge at 5th cycle.

I wonder whether there is something not correct or not safe when we use `exxdiv=None` together with k-symm？

**Comment by fishjojo** [comment]
Can you please try this [branch](https://github.com/pyscf/pyscf/tree/kpoint_symm) to see if there is still a problem .

**Comment by changsuc** [comment]
Hi Xing, 
Thank you. I tried this branch. The calcualtion with k-symm converges but seems to different states.
With k-symm:       e_tot = -9.438474078632321 a.u.; HOMO 0.319423519381 == LUMO 0.319423519381
Without k-symm: e_tot = -9.744905986849524 a.u.; HOMO = 0.107598236994  LUMO = 0.132304858581

**Comment by maxnus** [comment]
It's possible that there is a degeneracy at the Fermi level, which can only be lifted by breaking the symmetry. I faintly remember this being the case for graphene with n x n k-point meshes where n % 3 == 0. In the TDL, graphene should have a vanishing gap either way.

**Comment by tberkel** [comment]
The lower energy is consistent with symmetry breaking. Using ewald is like
having a level shift that opens up a gap, probably explaining why they
agree in that case.

**Comment by changsuc** [comment]
Thank you for your replies. They help a lot. I will use k-symm with caution, especially for the potentially symmetry-broken cases. Similar mismatches were found in AFM transition metal oxide and metallic systems. It should be safer to use k-symm for the semi-conductors or insulators.
