### ISSUE TITLE
PBC code in pyscf 2.1.1 not reproducing that in pyscf 2.0.1

### ISSUE THREAD

**Issue by hongzhouye** [pyscf/pyscf#1515]
# The problem

We (me, @welltemperedpaprika, and @tberkel) are writing to report that the PBC code in the new version
```
PySCF version 2.1.1
GIT HEAD 0b06bee37b62a5e36f69538584cc449ff86b271c
```
does not reproduce that in an old version
```
PySCF version 2.0.1 
GIT HEAD 13bc8f9c1e98add7743bdf1c5e86c18557a66fb1
```
for some systems, which is caused by differences in **both the 1e and the 2e (i.e., density-fitting) integrals**.

# Numerical evidence

A minimal working example we found is the PBE calculation of the ethyl carbamate ("ethcar") molecular crystal at Gamma point (script provided at the end). The tests we did are summarized in the table below

| version | density-fitting | PBC SCF energy (Ha) | cohesive energy per molecule* (kJ/mol) |
| ---- | ------ | ---- | --- |
| old | GDF | -646.824672894704 | -36.2 |
| old | RSGDF | -646.824672894676 | -36.2 |
| new | GDF | -646.973208903372 | -231.1 (unphysical) |
| new | RSGDF | -646.966905209418 | -222.9 (unphysical) |

*cohesive energy is computed by subtracting the single molecule energy `-323.398566988734` -- on which both versions of code agree with each other -- from the PBC energy (each unit cell has 2 ethcar molecules).

## 2e (density-fitting) integrals
The following two observations suggest that **the 2e (i.e., density-fitting) integrals from the new code may be inaccurate**:
- The two density-fitting methods don't agree with each other in the new code (differ by 6 mHa, which is not small) while they agree to nHa level with the old code.
- The old and new SCF energy differ by 0.15 Ha, making physical observables like the cohesive energy acquire an unphysical value with the new code.

## 1e integrals
We also verified that **the PBC 1e integrals `h1e` computed with the two versions are different**,
```
abs(h1e_old - h1e_new).max()
```
gives about `0.03 a.u`. This is caused purely by the difference in `vnuc` as we verified that the two codes agree on `vkin`.

# Minimal working example
```Python
from pyscf.pbc import gto, scf

if __name__ == '__main__':
    atom = '''
H     4.0836000000    5.7004000000    2.8565000000
H     0.5680000000    0.0959000000    4.2174000000
H     0.4706000000    4.7743000000    3.5510000000
H     4.1810000000    1.0221000000    3.5229000000
H     5.5721000000    5.5874000000    1.8926000000
H    -0.9205000000    0.2090000000    5.1813000000
H     3.6634000000    3.2554000000    2.5858000000
H     0.9883000000    2.5410000000    4.4882000000
H     3.8348000000    4.0111000000    0.9795000000
H     0.8169000000    1.7853000000    6.0944000000
H     2.2233000000    1.3148000000    1.1084000000
H     2.4284000000    4.4816000000    5.9655000000
H     1.1776000000    0.0925000000    0.4060000000
H     3.4740000000    5.7038000000    6.6679000000
C     4.9118000000    5.0368000000    2.5738000000
C    -0.2601000000    0.7596000000    4.5001000000
C     4.3583000000    3.7872000000    1.9184000000
C     0.2934000000    2.0092000000    5.1555000000
C     0.2055000000    1.7291000000    1.1016000000
C     4.4462000000    4.0673000000    5.9723000000
N     1.2856000000    0.9479000000    0.9570000000
N     3.3661000000    4.8484000000    6.1169000000
O     0.4858000000    2.9010000000    1.7096000000
O     4.1659000000    2.8953000000    5.3644000000
O     4.0663000000    1.4269000000    0.6702000000
O     0.5854000000    4.3694000000    6.4037000000
'''
    a = '''
5.0086286000 0.0185048000 -0.0702152000
1.6302437000 6.7597213000 0.0645321000
-1.9871993000 -0.9818778000 7.0796037000
'''
    basis = 'cc-pvdz'

    cell = gto.Cell(atom=atom, a=a, basis=basis)
    cell.verbose = 6
    cell.precision = 1e-12
    cell.build()

    mf = scf.RKS(cell).density_fit()
    # mf = scf.RKS(cell).rs_density_fit()

    mf.xc = 'pbe'
    mf.conv_tol = 1e-8

    mf.kernel()
```

**Comment by verena-neufeld** [comment]
No worries if not, I was just wondering whether there are more ideas now what could be causing this bug?

**Comment by verena-neufeld** [comment]
I've just used both options of your minimal example, GDF and RSGDF (though I'm aware the type of df might have been altered a little), and I get -646.824673860959 and -646.824673860943 ha which seems consistent with the old version you mention here?

**Comment by sunqm** [comment]
The PBC integral code has been refactored in pyscf-2.3, and the precision of integrals is largely improved during these updates. Please feel free to reopen the issue if errors are encountered in the new versions.
