### ISSUE TITLE
ERI index corresponding to the two-electron integrals

### ISSUE THREAD

**Issue by Eureka10shen** [pyscf/pyscf#1519]
After the Hartree-Fock calculation, we can get the one and two-electron integrals from
```
h1e = reduce(np.dot, (mf.mo_coeff.T, mf.get_hcore(), mf.mo_coeff)) # (C^T)HC
eri = ao2mo.kernel(mol, mf.mo_coeff, compact=False)
```
I wanted to use them to calculate the Hartree-Fock energy with the formula as 

$$E_{HF} = \langle\Phi_0 | \hat{H} | \Phi_0\rangle =  \sum_i^N [i|\hat{h}|i] + \sum_{i>j}^N  \left([ii|jj] - [ij|ji]\right)$$

and my code reads
```
import numpy as np
from pyscf import gto, scf, ao2mo
atoms_CH4 = [ # CH4
    ['H',    0.0000,    0.9870,    0.0000],
    ['C',    1.0390,    0.9870,    0.0000],
    ['H',    1.0390,    1.9740,    0.0000],
    ['H',    1.0390,    0.0000,    0.0000],
    ['H',    2.0260,    0.9870,    0.0000]]
mol = gto.Mole()
mol.atom = atoms_CH4
mol.basis = 'sto-3g'
mol.verbose = 0
mol.build()
mf = scf.RHF(mol)
mf.kernel()
from functools import reduce
h1e = reduce(np.dot, (mf.mo_coeff.T, mf.get_hcore(), mf.mo_coeff)) # (C^T)HC
eri = ao2mo.kernel(mol, mf.mo_coeff, compact=False)
eri = eri.reshape((mol.nao,mol.nao,mol.nao,mol.nao))

hf_str = np.array([1,1,1,1,1,0,0,0,0])
first_part = np.sum(np.diag(hf_str) * h1e)
second_part = 0
for i in range(1,5):
    for j in range(0,i):
        second_part += eri[i][i][j][j]-eri[i][j][j][i]
print('HF energy    = ', mf.e_tot-mol.energy_nuc())
print('my_HF energy = ', first_part+second_part)
```
but the result reads 
```
HF energy    =  -54.05508294707886
my_HF energy =  -35.712483622065726
```
I'm wondering if the indexes of eris I used are wrong???
Thank you very much!!!

**Comment by hebrewsnabla** [comment]
The problem is that your formula is based on spin-orbitals (Szabo 2.111) but the MO integrals in pyscf are integrals of spatial orbitals. So you need to derive an RHF energy formula on spatial orbitals (Szabo 2.177) and adjust the code.

**Comment by Eureka10shen** [comment]
> The problem is that your formula is based on spin-orbitals (Szabo 2.111) but the MO integrals in pyscf are integrals of spatial orbitals. So you need to derive an RHF energy formula on spatial orbitals (Szabo 2.177) and adjust the code.

It works, Thanks you very much !!! ❤❤❤
