### ISSUE TITLE
Incorrect electron numbers when applying k-symm

### ISSUE THREAD

**Issue by changsuc** [pyscf/pyscf#1520]
Greetings,
I found that the total electron number is not correctly counted if the number of electrons in each k-point is not equal when applying k-symm function in PySCF.
Here is a simplified case for demonstration,
```
from pyscf.pbc import scf, gto
cell = gto.Cell()
cell.atom = 'C 0.0 0.0 2.0;O 0.0 0.0 3.48; Ti 0.0 0.0 0.0; Ti 3.0 0.0 0.0;Ti 0.0 3.0 0.0;Ti 3.0 3.0 0.0;'
cell.a = [[6, 0.0, 0.0],[0.0, 6, 0.0], [0.0,0.0,10]]
cell.basis = 'gth-szv-molopt-sr'
cell.pseudo = 'gth-pade'
cell.verbose = 5
cell.build()

kmesh = [3,3,1]
kpts = cell.make_kpts(kmesh, space_group_symmetry=True, time_reversal_symmetry=True, symmorphic=True)
#kpts = cell.make_kpts(kmesh)

kmf = scf.KRHF(cell, kpts, exxdiv=None).density_fit()
kmf.max_cycle = 20
kmf.kernel()
```
There are 9 kpoints ranging from k0 to k9,
| k7 | k1 | k4 |
|----|----|----|
| k6 | k0 | k3 |
| k8 | k2 | k5 |.

The number of electrons in each unit cell is 58 and the total number is 58*9 = 522.

When turning on the k-symm, only three are computed,
| -- | -- | -- |
|----|----|----|
| k6 | k0 | -- |
| k8 | -- | -- |.

The electron number (`kmf.mo_occ`) in each k-point is shown below,
| -- | -- | -- |
|----|----|----|
| 58 | 60 | -- |
| 56 | -- | -- |.

However, it is not a correct assignment since the weight is not considered.
After `kmf_nosymm = kmf.to_khf()`, then it becomes
| 56 | 58 | 56 |
|----|----|----|
| 58 | 60 | 58 |
| 56 | 58 | 56 |.

If we set 58 as the reference, it becomes
| -2 | 0 | -2 |
|----|----|----|
| 0 | 2 | 0 |
| -2 | 0 | -2 |.

The electron number is six less than the correct one. When performing calculations with k-symm, I think the weight should also be considered to get the correct assignment of electron occupation.

**Comment by changsuc** [comment]
I made a test on `kpoint_symm` branch. The problem is fixed.

**Comment by ghb24** [comment]
I'm guessing this is the same issue as #1470 .

**Comment by changsuc** [comment]
Yes, thank you for your reminder. I will close this issue then.
