### ISSUE TITLE
Is it possible to obtain the ERI tensor in spin orbital basis from UHF calculations?

### ISSUE THREAD

**Issue by BenchenH** [pyscf/pyscf#1521]
Hi,

I'm trying to derive the ERI tensor in spin orbital basis from UHF calculations. However, I didn't find an easy way to do it. I will use the hydrogen molecule (0.75 Angstrom) as an example, and my strategy is the following:

1. Define molecular structure and perform a standard UHF calculation (the UHF calculation is performed using method suggested in https://github.com/pyscf/pyscf.github.io/blob/master/examples/scf/56-h2_symm_breaking.py):
```
atom = 'H 0 0 0; H 0 0 0.75'
mol = pyscf.M(atom=atom, basis='sto-3g')
nuclear_repulsion = mol.energy_nuc()

hf = scf.RHF(mol).run()
uhf = scf.UHF(mol)
uhf.kernel(init_guess_mixed(mol, hf))

h1e = mol.intor("int1e_kin") + mol.intor("int1e_nuc")
h2e = mol.intor("int2e")
scf_c = uhf.mo_coeff
```
2. Derive the ERI tensor (aaaa, aabb, bbaa, bbbb) in spatial orbital basis:
```
h2e_aaaa = np.einsum('ijkl, ia, jb, kc, ld->abcd', h2e, scf_c[0,:], scf_c[0,:], scf_c[0,:], scf_c[0,:])
h2e_aabb = np.einsum('ijkl, ia, jb, kc, ld->abcd', h2e, scf_c[0,:], scf_c[0,:], scf_c[1,:], scf_c[1,:])
h2e_bbaa = np.einsum('ijkl, ia, jb, kc, ld->abcd', h2e, scf_c[1,:], scf_c[1,:], scf_c[0,:], scf_c[0,:])
h2e_bbbb = np.einsum('ijkl, ia, jb, kc, ld->abcd', h2e, scf_c[1,:], scf_c[1,:], scf_c[1,:], scf_c[1,:])
```

I'm currently stuck at step 2, because the integral sign I obtained is not expected. The h2e_aaaa is:
```
array([[[[ 0.6728, -0.    ],
         [-0.    ,  0.662 ]],

        [[-0.    ,  0.1818],
         [ 0.1818,  0.    ]]],


       [[[-0.    ,  0.1818],
         [ 0.1818,  0.    ]],

        [[ 0.662 ,  0.    ],
         [ 0.    ,  0.6958]]]])
```
And the h2e_aabb is:
```
array([[[[ 0.6728,  0.    ],
         [ 0.    ,  0.662 ]],

        [[ 0.    , -0.1818],
         [-0.1818, -0.    ]]],


       [[[ 0.    , -0.1818],
         [-0.1818, -0.    ]],

        [[ 0.662 , -0.    ],
         [-0.    ,  0.6958]]]])
```

Since at 0.75 Angstrom, UHF and RHF are almost identical, these two ERI tensors should also be identical. However I don't know why the sign of some elements in h2e_aabb is different, e.g., h2e_aabb[0,1,0,1]. Is this because I'm not using some of the functions correctly, or did I miss interpreting some of the quantities?

And if there exist other ways to achieve the same goal that I'm not aware of, please let me know. And I appreciate your help in advance!
Benchen

**Comment by fishjojo** [comment]
MOs can have a phase difference, that's why your h2e_aaaa and h2e_aabb have a sign difference. But this won't affect any physical observables. You can also fix the phase if you wish.

**Comment by BenchenH** [comment]
> MOs can have a phase difference, that's why your h2e_aaaa and h2e_aabb have a sign difference. But this won't affect any physical observables. You can also fix the phase if you wish.

How can I fix the phase of MOs?
