### ISSUE TITLE
how to get fci wavefunctions after pyscf.fci.FCI

### ISSUE THREAD

**Issue by yuhanzheng1** [pyscf/pyscf#1522]
Hello, all! 
I want to get fci wavefunctions after pyscf.fci.FCI, and I refer to '#1293'
'example/ci/20-from_fci.py' to get cis_a, cis_b, cid_aa and so on . I let the amplitues multiply the corresponding operator, and then use |FCI>=|HF>+sum(i)cis_a[i]*op_a[i]+sum（i)*op_b[i]+sum(i)cis_aa[i]+sum(i)cid_aa[i]*op_aa[i]+... to get fci wavefunctions.
However I still can‘t get wavefunctions correctly.(maybe I didn't do it the right way ). Does anyone know how to get them after getting cis_a, cis_b, cid_aa ...refering to'#1293'. If you have code, can you share me?

**Comment by hebrewsnabla** [comment]
What do you mean by "can‘t get wavefunctions correctly"?

**Comment by verena-neufeld** [comment]
Hi @yuhanzheng1, has this been resolved?

**Comment by yuhanzheng1** [comment]
> Hi @yuhanzheng1, has this been resolved?

yes. I find another way to get fci wavefunctions.
