### ISSUE TITLE
Inconsistent results for pbc DFT calculations with the example.

### ISSUE THREAD

**Issue by MarcoBarroca** [pyscf/pyscf#1525]
Hello, I've been using PySCF to run some pbc DFT calculations on a bcc Li cell. You can see more about the structure [here](https://materialsproject.org/materials/mp-135#surface_energies).

One of the issues I'm running into is that according to the reference values for the Materials Project database I should expect a value of about -1.90 eV/atom. Unfortunately, I'm getting -7.5 Ha/atom = -204.0 eV/atom with PySCF.

In order to double-check this result I ran the same calculation on VASP which returned the expected -1.9eV/atom result.

below is a code sample to run the calculation based on the pbc example available in the repo

```
from pyscf.pbc import gto, scf, dft
import numpy

cell = gto.Cell()
# .a is a matrix for lattice vectors.
cell.a = '''
3.43  0       0
0       3.43 0
0       0       3.43'''
cell.atom           = [
                       [ " Li " , ( 0 , 0 , 0 ) ] ,
                       #[ " Li " , ( 0.0, 0.0, 3.426817894 ) ] ,
                       #[ " Li " , ( 0.0, 3.426817996,  0.0 ) ] ,
                       #[ " Li " , ( 0.0,  3.426817996,  3.426817894) ] ,
                       #[ " Li " , ( 0.0, 6.853635992, 0.0 ) ] ,
                       #[ " Li " , ( 0.0, 6.853635992, 3.426817894 ) ] ,
                       #[ " Li " , ( 3.426817996, 0.0, 0.0 ) ] ,
                       #[ " Li " , ( 3.426817996, 0.0, 3.426817894 ) ] ,
                       #[ " Li " , ( 3.426817996, 3.426817996, 0.0  ) ] ,
                       #[ " Li " , ( 3.426817996, 3.426817996, 3.426817894 ) ] ,
                       #[ " Li " , ( 3.426817996, 6.853635992, 0.0 ) ] ,
                       #[ " Li " , ( 3.426817996, 6.853635992, 3.426817894 ) ] ,
                       #[ " Li " , ( 6.853635992, 0.0, 0.0 ) ] ,
                       #[ " Li " , ( 6.853635992, 0.0, 3.426817894 ) ] ,
                       #[ " Li " , ( 6.853635992, 3.426817996, 0.0  ) ] ,
                       #[ " Li " , ( 6.853635992, 3.426817996, 3.426817894 ) ] ,
                       #[ " Li " , ( 6.853635992, 6.853635992, 0.0  ) ] ,
                       #[ " Li " , ( 6.853635992, 6.853635992, 3.426817894 ) ] ,
                       [ " Li " , ( 1.713408998, 1.713408998, 1.713408947 ) ] ,
                      # [ " Li " , ( 1.713408998, 1.713408998, 5.140226841 ) ] ,
                       #[ " Li " , ( 1.713408998, 5.140226841, 1.713408947 ) ] ,
                       #[ " Li " , ( 1.713408998, 5.140226841, 5.140226841 ) ] ,
                       #[ " Li " , ( 1.713408998, 8.567044531, 1.713408947 ) ] ,
                       #[ " Li " , ( 1.713408998, 8.567044531, 5.140226841 ) ] ,
                       #[ " Li " , ( 5.140226841, 1.713408998, 1.713408947 ) ] ,
                       #[ " Li " , ( 5.140226841, 1.713408998, 5.140226841 ) ] ,
                       #[ " Li " , ( 5.140226841, 5.140226841, 1.713408947 ) ] ,
                       #[ " Li " , ( 5.140226841, 5.140226841, 5.140226841 ) ] ,
                       #[ " Li " , ( 5.140226841, 8.567044531, 1.713408947) ] ,
                       #[ " Li " , ( 5.140226841, 8.567044531, 5.140226841) ] ,
                       #[ " Li " , ( 8.567044531, 1.713408998, 1.713408947) ] ,
                       #[ " Li " , ( 8.567044531, 1.713408998, 5.140226841 ) ] ,
                       #[ " Li " , ( 8.567044531, 5.140226841, 1.713408947 ) ] ,
                      #[ " Li " , ( 8.567044531, 5.140226841, 5.140226841  ) ] ,
                       #[ " Li " , ( 8.567044531, 8.567044531, 1.713408947 ) ] ,
                       #[ " Li " , ( 8.567044531, 8.567044531, 5.140226841) ] 
                       ] 
cell.basis = 'gth-szv'
cell.pseudo = 'gth-pade'
cell.precision = 5.2e-18
cell.verbose = 4
cell.build()

mf = scf.RHF(cell)
ehf = mf.kernel()
print("HF energy (per unit cell) = %.17g" % ehf)

mf = dft.RKS(cell)
mf.xc = 'pbe,pbe'
edft = mf.kernel()
print("DFT energy (per unit cell) = %.17g" % edft)

```

I've also taken the liberty to run the [example](examples/pbc/10-gamma_point_scf.py) to check if it would match the reference values on the Materials Project for [diamond](https://materialsproject.org/materials/mp-66#thermodynamic_stability).

PySCF returns -5.48 Ha/atom = -149.1525 eV/atom vs the -9.089 eV/atom in the reference. Note that the reference shares the same structure as the example.

I'm unsure about where the issue is. PySCF seems consistent with itself and reports the same values for bigger cells but it differs from the reference and the VASP calculations. Any help would be appreciated, I've been at this for a while and can't seem to figure out the reason for these discrepancies.

Below are the images from the Materials Project page for the reference energies.

<img width="498" alt="image" src="https://user-images.githubusercontent.com/6553024/205093177-d498fd98-77c9-4ac9-aa6c-7ca163e82269.png">

<img width="496" alt="image" src="https://user-images.githubusercontent.com/6553024/205093432-a94b196b-5303-429c-aa8e-46dcac6aa580.png">

**Comment by tberkel** [comment]
The total energy of any system can depend strongly on the employed
pseudopotential, so comparing total energies is usually quite difficult. If
you calculate the energy of a single atom using the same PP (here, GTH
type) in PySCF, you should find a number that is similarly "large" in
magnitude, but the difference (the formation energy) can be directly
compared across different PPs.

**Comment by MarcoBarroca** [comment]
Hey, sorry it took me a while to respond. I'm a bit unfamiliar with formation energy. From what I read it should be calculated somewhat like this: $\frac{E_{formation}}{atom}=\frac{(E_n -n\times E_1)}{n}$ where $n$ is the number of atoms and $E_1$ the total energy of 1 atom inside the cell while $E_n$ is the total energy for $n$ atoms in the cell. Does that seem correct?

That still doesn't agree with the expected value of the Materials Project.

For the Lithium bcc: $\frac{-15.10-(2\times (-7.43))}{2}=-0.145$ Ha/atom $=-3.95$ eV/atom $\neq -0.005$ eV/atom

For Diamond: $\frac{-43.85-(8\times (-5.32))}{8}=-0.161$ Ha/atom $=-4.38$ eV/atom $\neq -0.161$ eV/atom

The energy values for one atom were calculated using the same cells with just one atom in the middle. Is that the correct procedure? Thanks for the help!

**Comment by verena-neufeld** [comment]
Hi @MarcoBarroca , has your question been answered?

**Comment by MarcoBarroca** [comment]
Hi! Yes, sorry about leaving the issue open. I'll close it now!
