### ISSUE TITLE
The Visual Studio Code debugger does not show source-compiled Pyscf code, but can execute the library functions line by line

### ISSUE THREAD

**Issue by PabloAMC** [pyscf/pyscf#1526]
I am having trouble using the Visual Code debugger with a [source-compiled version of the Pyscf library](https://pyscf.org/install.html#compiling-from-source-code) on a MacBook with Apple Metal chip. Specifically, the debugger does not show the python code while executing, but I can still control it line by line, and see the variable values and number line being executed.

While it says "The editor could not be opened because the file was not found", I can still execute the file line by line, not being able to see the code though. 

<img width="1470" alt="VScode_Debuger" src="https://user-images.githubusercontent.com/20182937/205130175-328410eb-38da-4017-9b98-ffbb1dddc3b5.png">

Screenshot of the debugger executing a `mf.get_init()` function from pyscf.

The configuration I implemented was to add the pyscf path to the option Extra Paths in the configuration of Visual Studio. This allows me to freely open and see the library files, which are located on my Developer folder in my Mac, as long as I am not in debugger mode.

**Comment by sunqm** [comment]
I cannot reproduce the problem. It might be due to certain local configurations or environments. If someone also faces the similar problem, please reopen the issue.
