### ISSUE TITLE
Concatenate two mol with opposite spin

### ISSUE THREAD

**Issue by hebrewsnabla** [pyscf/pyscf#1527]
I'm trying to concatenate two mol with opposite spin, as a step of constructing breaksym wavefunction
```
>>> from pyscf import gto
>>> mol0 = gto.M(atom = 'H 0.0 0.0 0.0', spin=1).build()
>>> mol1 = gto.M(atom = 'F 0.0 0.0 2.0', spin=-1).build()
>>> mol = gto.conc_mol(mol0, mol1)
>>> mol.nelec
(6, 4)
```
But I found that the total spin is not a direct sum of frags', as the source code indicates
https://github.com/pyscf/pyscf/blob/91ff78377d6cc5c4b062051b4846df1c1ffd4a7c/pyscf/gto/mole.py#L794

So I guess that's an auto spin-flip for concatenate two doublets into a singlet. That's reasonable. But would it be more reasonable and intuitive if 
```
mol3.spin = mol1.spin + mol2.spin
```
Thus one can, in a more straightforwad way, get triplet (1+1) or spin-flipped singlet (1+(-1)) when concatenate two doublets.

Or, add an option to prevent such spin-flip?

**Comment by sunqm** [comment]
Due to the complexity in spin, I guess there is no simple way to control the spin concatenation with a single option. The most safe way is to manually check and set spin after calling mol1 + mol2.

**Comment by hebrewsnabla** [comment]
Yah, I agree.
