### ISSUE TITLE
How can I calculate orbital overlap?

### ISSUE THREAD

**Issue by Emilioerc** [pyscf/pyscf#1530]
Dear all,

I am trying to calculate the overlas between the orbitals at two different geometries. One of the geometries is at one side of a conical intersection and the other geometry at the other side, so I expect a flip in the orbital space for two roots. I have been trying but with no success. Do anyone have an idea of how to proceed?

Thank you in advance!

**Comment by fishjojo** [comment]
You can try [mole.intor_cross](https://github.com/pyscf/pyscf/blob/91ff78377d6cc5c4b062051b4846df1c1ffd4a7c/pyscf/gto/mole.py#L817).

**Comment by Emilioerc** [comment]
> You can try [mole.intor_cross](https://github.com/pyscf/pyscf/blob/91ff78377d6cc5c4b062051b4846df1c1ffd4a7c/pyscf/gto/mole.py#L817).

Thank you very much! And is it possible to get the atomic orbitals in different arrays, without performing the overlap?

**Comment by fishjojo** [comment]
If you want to compute the AOs on a grid, you can use mole.eval_gto, otherwise, the information of the AOs is stored in the mole.Mole object, and there are some functions to return this, such as mole.Mole.bas_exps and mole.Mole.bas_ctr_coeff.
