### ISSUE TITLE
fxc intergral evaluation

### ISSUE THREAD

**Issue by lucienwb** [pyscf/pyscf#1539]
Hello, how can I get the fxc value of

$$ 
 \delta^2 E_{xc} / \delta \rho(r) \delta \rho(r')
$$
 
<img width="324" alt="Screenshot 2022-12-12 at 17 12 41" src="https://user-images.githubusercontent.com/71210890/207096326-b37c67fe-adf7-43c2-aaab-044a88bd57dc.png">

for GGA and m-GGA level of theory, not simply get the LDA level from 'v2rho2' tab of libxc. I think PySCF has implemented inside probably in TDDFT.

**Comment by sunqm** [comment]
Please check the function `eval_xc` https://github.com/pyscf/pyscf/blob/master/pyscf/dft/libxc.py#L1261
