### ISSUE TITLE
Possible fencepost error in cubegen's grid generation?

### ISSUE THREAD

**Issue by mjw99** [pyscf/pyscf#154]
https://github.com/sunqm/pyscf/blob/master/pyscf/tools/cubegen.py#L36

Should these be:
`xs = numpy.arange(nx) * (box[0]/(nx - 1))`
`ys = numpy.arange(ny) * (box[1]/(ny - 1))`
`zs = numpy.arange(nz) * (box[2]/(nz - 1))`

**Comment by sunqm** [comment]
I can understand this is to put the grids on the edge.  Do you know whether it's the convention all other softwares used?

**Comment by mjw99** [comment]
Hi Qiming,

Many thanks for the reply and looking into this. The only reference example I have
is what is done in NWChem:

https://github.com/nwchemgit/nwchem/blob/master/src/property/prop_grid.F#L37

With the current code, if one creates a cube in the following way:
```
...
grid_points = 5
cubegen.density(h2o, 'water_den.cube', dm, nx=grid_points, ny=grid_points, nz=grid_points)
...
```
adds some debugging statements in cubegen.py (I will add a formal logging mechanism to this soon)
```
...
    print box

    print xs
    print ys
    print zs
...
```

One sees the following:
```
[6.         8.87828343 7.13145651]

[0.  1.2 2.4 3.6 4.8]
[0.         1.77565669 3.55131337 5.32697006 7.10262675]
[0.         1.4262913  2.8525826  4.27887391 5.70516521]
```

Given the first line is the grid's maximum in all dimension, one would expect the respective final elements of xs, ys, zs to have the same value as this?

I am working on a variant of this whereby I fix this and also have the option of setting a symmetric padding, instead of the two values of 6 and 3 in the current code.
