### ISSUE TITLE
Custom FCI coefficients - seniority zero wavefunctions

### ISSUE THREAD

**Issue by jjkirsopp** [pyscf/pyscf#1541]
I was hoping someone could point me towards a means for performing CI with only pair-double excitations in such a way I can evaluate the spin-dependent 1- and 2-RDMs. I'm aware I can evaluate the RDMs I need from an fci object, but my problem requires that the wavefunction is seniority zero, or I need access to 3- and 4-RDMs which are not spin-traced.

The simplest way to proceed seems to be to constrain some fci coefficients to be zero and handle the optimization myself, but any pointers would be much appreciated.

Thanks a bunch in advance.

**Comment by jjkirsopp** [comment]
Hi, 

Yeah, I'm talking about seniority zero in general. Thanks for the link, I'll check it out.

To be honest I'd be satisfied with directions to an explanation of how best to construct alpha and beta strings which I can just plug in and get non spin traced RDMs and an energy from :) 

Cheers

**Comment by sunqm** [comment]
DOCI wfn can be converted to FCI wavefunction with
```
fci_wfn = np.diag(doci_wfn)
```
Then the rdm3 and rdm4 functions provided by pyscf.fci.rdm module can be used to compute the high-order density matrices.

**Comment by verena-neufeld** [comment]
Hi @jjkirsopp , has your question been answered?

**Comment by jjkirsopp** [comment]
Yeah, this can be closed
