### ISSUE TITLE
Jax support

### ISSUE THREAD

**Issue by SamTov** [pyscf/pyscf#1547]
I have seen some mentions of Jax in the repo as well as the PySCFAD package. Is there a plan to move computations over to Jax and in doing so support the advanced hardware and auto-diff functionality?

**Comment by fishjojo** [comment]
Due to the complexity of quantum chemistry code and the limitations of Jax, it may be hard to move all components of PySCF over to Jax. But certainly a portion of the python code can be accelerated using Jax, and I'm testing it right now.

**Comment by verena-neufeld** [comment]
Hi @SamTov , thanks for your question. @SamTov has your question been answered? Are there further updates @fishjojo ?

**Comment by SamTov** [comment]
Hi @verena-neufeld thanks for the check in. I guess the initial question is answered, yes. I was working on some differentiable DFT projects and so was hoping this package would support it as it is heavily built on numpy. I think it would be a really cool thing to have and would make the project in general more maintainable into the future. But I am happy to close the issue as it has been answered.
