### ISSUE TITLE
AssertionError 

### ISSUE THREAD

**Issue by MohammedObies** [pyscf/pyscf#1551]
Hi, 
Any help would be appreciated. I am trying to ran mcscf.CASSCF but got this error:

Traceback (most recent call last):
  File "/data/chem-metal-wire-transport/lina2773/ali/cluster/avas/doublet-aufe.inp", line 32, in <module>
    mycas.kernel(orbs)
  File "/apps/system/easybuild/software/PySCF/2.1.1-foss-2021a/pyscf/mcscf/mc1step.py", line 837, in kernel
    self.check_sanity()
  File "/apps/system/easybuild/software/PySCF/2.1.1-foss-2021a/pyscf/mcscf/casci.py", line 835, in check_sanity
    ncore = self.ncore
  File "/apps/system/easybuild/software/PySCF/2.1.1-foss-2021a/pyscf/mcscf/casci.py", line 791, in ncore
    assert ncorelec % 2 == 0
AssertionError

My input is:

from functools import reduce
import numpy
from pyscf import gto
from pyscf import scf
from pyscf import mcscf
from pyscf import fci
from pyscf.mcscf import avas
from pyscf.tools import molden

mol = gto.Mole()
mol.atom = '''
   Fe      6.63858        5.02951        7.47626
   Au      5.25270        6.39423        6.10266
'''
mol.basis = 'def2-svpd'
mol.spin = 1
mol.build()

mf = scf.RHF(mol)
mf.kernel()

ao_labels = ['Fe 3d', 'Au 6s']
norb, ne_act, orbs = mcscf.avas.avas(mf, ao_labels, canonicalize=False)

mycas = mcscf.CASSCF(mf, 7, 6)
mycas.chkfile ='doublet-aufe.chk'
mycas.verbose = 4
mycas.kernel(orbs)

avas_obj = mcscf.avas.AVAS(mf, ao_labels)
avas_obj.kernel()
print(avas_obj.occ_weights)
print(avas_obj.vir_weights)
print(avas_obj.ncas)
print(avas_obj.nelecas)
print(avas_obj.mo_coeff.shape)

with open('doublet-aufe.molden', 'w') as f1:
    molden.header(mol, f1)
    molden.orbital_coeff(mol, f1, mf.mo_coeff, ene=mf.mo_energy, occ=mf.mo_occ)

**Comment by jamesETsmith** [comment]
@MohammedObies, your system has an odd number of electrons so when you select only 6 for your active space, you leave an odd number for your core orbitals. CAS calculations have to have an even number of core electrons, so I'd try adjusting your active space.

**Comment by MohammedObies** [comment]
Dear James, thank you for your answer. That solves the error.
