### ISSUE TITLE
visualise orbitals  

### ISSUE THREAD

**Issue by MohammedObies** [pyscf/pyscf#1552]
Hello,
I am trying to do CASSCF calculations using AVAS to select the active space but I do not know how to visualise the orbitals resulting from AVAS. Could you help me with that, please? 
My input is;

from functools import reduce
import numpy
from pyscf import gto
from pyscf import scf
from pyscf import mcscf
from pyscf import fci
from pyscf.mcscf import avas

mol = gto.Mole()
mol.atom = '''
   Fe      6.63858        5.02951        7.47626
   Au      5.25270        6.39423        6.10266
'''
mol.basis = 'cc-pVTZ-DK'
mol.spin = 1
mol.build().x2c()

mf = scf.RHF(mol)
mf.kernel()

ao_labels = ['Fe 3d', 'Au 6s']
norb, ne_act, orbs = mcscf.avas.avas(mf, ao_labels, canonicalize=False)

mycas = mcscf.CASSCF(mf, 6, 7)
mycas.max_cycle_macro = 200
mycas.chkfile ='doublet-aufe.chk'
mycas.verbose = 4
mycas.kernel(orbs)

avas_obj = mcscf.avas.AVAS(mf, ao_labels)
avas_obj.kernel()
print(avas_obj.occ_weights)
print(avas_obj.vir_weights)
print(avas_obj.ncas)
print(avas_obj.nelecas)
print(avas_obj.mo_coeff.shape)

**Comment by tberkel** [comment]
You can output in the molden file format, see for example
`pyscf/examples/tools/02-molden.py`
