### ISSUE TITLE
How to do BSSE calculation with pyscf?

### ISSUE THREAD

**Issue by DiracMD** [pyscf/pyscf#1554]
Dear developer, recently I want to use pyscf to do Basis Set Superposition Error (BSSE) calculation. I find the manual have no any information about bsse? where can I find it?

**Comment by tberkel** [comment]
Accounting for BSSE requires performing calculations with ghost atoms that
carry the basis functions of the original atoms. To make ghost atoms, you
can prefix the atom name with "ghost" when specifying the geometry. You can
find examples here:
https://github.com/pyscf/pyscf/blob/master/examples/gto/03-ghost_atom.py

**Comment by DiracMD** [comment]
OKay, Thank you. I'll test with your link
