### ISSUE TITLE
Matrix elements of hamiltonian between different determinants

### ISSUE THREAD

**Issue by insaan12** [pyscf/pyscf#1556]
Hello everyone,
I am trying to calculate the matrix elements such as these <S|H|D> and  <D|H|D> etc where  H is the full electronic hamiltonian and |S> and |D> refer to singly and doubly excited determinants from a Kohn Sham or Hartree Fock reference ground state. I was wondering if Pyscf offers a way to do that.
thanks

**Comment by Dawood234** [comment]
>

**Comment by fishjojo** [comment]
The fci module has some functions that you can modify to compute these, see e.g. fci.fci_slow.contract_2e.

**Comment by Dawood234** [comment]
Thank you for the response. I am not very familiar with the FCI part of the code. Is there a way this can be done within the HF or KS part of the code? Thanks.

**Comment by insaan12** [comment]
Thank you for the response. I am not very familiar with the FCI part of the code. Is there a way this can be done within the HF or KS part of the code? Thanks.

**Comment by hebrewsnabla** [comment]
You can manually derive the expression of <S|H|D> in terms of MO integrals, and then only scf and ao2mo is needed. Such expression will be not so simple for <D|H|D> and others.
If you have lots of kinds of matrix elements to do, manual derivation is not a good idea. Using fci_slow.contract_2e will be much easier.
