### ISSUE TITLE
The number of electrons is different from initial number when smearing of occupation numbers is used

### ISSUE THREAD

**Issue by alxvov** [pyscf/pyscf#1560]
Hello,

I'm running DFT calculations with Fermi-Dirac smearing applied to occupation numbers. When I calculate the energy of Al atom, I noticed that the number of electrons is not kept the same during SCF and by the end of SCF I get 12 electrons instead of 13. I don't get such results when I run calculations with other DFT software such as GPAW, the number of electrons is always kept the same during SCF when smearing is applied. Is the loss of electrons expected behaviour? (See input and output files below). Let me know if I do something wrong.

Many thanks,
Aleksei 

```python3
from pyscf import scf, gto
from ase.units import Ha

atom = gto.M(
    atom="Al 0 0 0",
    basis='sto-3g',
    verbose=5,
    spin=1,
    output="output.txt",
)
mf = scf.UKS(atom)
mf = scf.addons.smearing_(mf, sigma=0.025 / Ha, method="fermi")
mf.xc = "pbe"
mf.grids.level = 9
mf.max_cycle = 333
mf.kernel()
```
#INFO: ******************** input file end ********************
Python 3.9.13 (main, Jun 24 2022, 15:32:51) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
numpy 1.23.5  scipy 1.9.3
Date: Wed Jan  4 21:12:21 2023
PySCF version 2.1.1

[CONFIG] conf_file None
[INPUT] verbose = 5
[INPUT] max_memory = 4000 
[INPUT] num. atoms = 1
[INPUT] num. electrons = 13
[INPUT] charge = 0
[INPUT] spin (= nelec alpha-beta = 2S) = 1
[INPUT] symmetry False subgroup None
[INPUT] Mole.unit = angstrom
[INPUT] Symbol           X                Y                Z      unit          X                Y                Z       unit  Magmom
[INPUT]  1 Al     0.000000000000   0.000000000000   0.000000000000 AA    0.000000000000   0.000000000000   0.000000000000 Bohr   0.0
[INPUT] ---------------- BASIS SET ---------------- 
[INPUT] l, kappa, [nprim/nctr], expnt,             c_1 c_2 ...
[INPUT] Al
[INPUT] 0    0    [3    /1   ]  351.4214767       0.1543289673
                                64.01186067       0.5353281423
                                17.32410761       0.4446345422
[INPUT] 0    0    [3    /1   ]  18.89939621       -0.09996722919
                                4.391813233       0.3995128261
                                1.42835397        0.7001154689
[INPUT] 0    0    [3    /1   ]  1.395448293       -0.219620369
                                0.3893265318      0.2255954336
                                0.1523797659      0.900398426
[INPUT] 1    0    [3    /1   ]  18.89939621       0.155916275
                                4.391813233       0.6076837186
                                1.42835397        0.3919573931
[INPUT] 1    0    [3    /1   ]  1.395448293       0.01058760429
                                0.3893265318      0.5951670053
                                0.1523797659      0.462001012

nuclear repulsion = 0
number of shells = 5
number of NR pGTOs = 27
number of NR cGTOs = 9
basis = sto-3g
ecp = {}
CPU time:         0.22

******** <class 'pyscf.dft.uks.UKS'> ********
method = UKS
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-09
SCF conv_tol_grad = None
SCF max_cycles = 333
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /ScratchArray/tmpah1tu7on
max_memory 4000 MB (current use 78 MB)
number electrons alpha = 7  beta = 6
XC library pyscf.dft.libxc version 5.2.0
    S. Lehtola, C. Steigemann, M. J. Oliveira, and M. A. Marques, SoftwareX 7, 1 (2018)
XC functionals = pbe
    J. P. Perdew, K. Burke, and M. Ernzerhof, Phys. Rev. Lett. 77, 3865 (1996)
    J. P. Perdew, K. Burke, and M. Ernzerhof, Phys. Rev. Lett. 78, 1396 (1997)
    J. P. Perdew, K. Burke, and M. Ernzerhof, Phys. Rev. Lett. 77, 3865 (1996)
    J. P. Perdew, K. Burke, and M. Ernzerhof, Phys. Rev. Lett. 78, 1396 (1997)
radial grids: 
    Treutler-Ahlrichs [JCP 102, 346 (1995); DOI:10.1063/1.469408] (M4) radial grids
    
becke partition: Becke, JCP 88, 2547 (1988); DOI:10.1063/1.454033
pruning grids: <function nwchem_prune at 0x7f2866de5f70>
grids dens level: 9
symmetrized grids: False
atomic radii adjust function: <function treutler_atomic_radii_adjust at 0x7f2866de5e50>
small_rho_cutoff = 1e-07
Overwritten attributes  get_grad get_occ energy_tot  of <class 'pyscf.dft.uks.UKS'>
Set gradient conv threshold to 3.16228e-05
atom Al rad-grids = 200, ang-grids = [  50   50   50   50   50   50   50   50   50   50   50   50   50   50
   50   50   50   50   50   50   50   50   50   50   50   50   50   50
   50   50   50   50   50   50   50   50   50   50   50   50   50   50
   50   50   50   50   50   50   50   50   50   50   50   50   50   50
   50   50   50   50   50   50   50   86   86   86   86   86   86   86
   86   86   86   86   86   86   86   86   86   86   86   86   86   86
   86   86   86   86   86   86   86   86   86   86   86   86   86   86
 1202 1202 1202 1202 1202 1202 1202 1202 1202 1202 1202 1202 1202 1202
 1202 1202 1202 1202 1202 1202 1202 1202 1202 1202 1454 1454 1454 1454
 1454 1454 1454 1454 1454 1454 1454 1454 1454 1454 1454 1454 1454 1454
 1454 1454 1454 1454 1454 1454 1454 1454 1454 1454 1454 1454 1454 1454
 1454 1454 1454 1454 1454 1454 1454 1454 1454 1454 1454 1454 1454 1454
 1454 1202 1202 1202 1202 1202 1202 1202 1202 1202 1202 1202 1202 1202
 1202 1202 1202 1202 1202 1202 1202 1202 1202 1202 1202 1202 1202 1202
 1202 1202 1202 1202]
tot_boxes 729, boxes in each direction [7 7 7]
Padding 0 grids
tot grids = 140608
    CPU time for setting up grids     44.80 sec, wall time      0.34 sec
nelec by numeric integration = [6.31507527 6.31507527]
    CPU time for vxc    163.96 sec, wall time      0.77 sec
E1 = -334.641353131647  Ecoul = 114.11435264001344  Exc = -18.499285868473816
init E= -239.026286360107
cond(S) = 2.431356964640719
    CPU time for initialize scf    251.11 sec, wall time      1.32 sec
    Fermi level 0.0601232  Sum mo_occ_kpts = 12.0  should equal nelec = 13
    sigma = 0.000918733  Optimized mu = -0.184302212473  entropy = -0
  alpha mo_energy/mo_occ
  [-54.622392  -3.692127  -2.235233  -2.235233  -2.235233  -0.229202
   0.060123   0.060123   0.060123]
  [1. 1. 1. 1. 1. 1. 0. 0. 0.]
  beta  mo_energy/mo_occ
  [-54.622392  -3.692127  -2.235233  -2.235233  -2.235233  -0.229202
   0.060123   0.060123   0.060123]
  [1. 1. 1. 1. 1. 1. 0. 0. 0.]
nelec by numeric integration = [6. 6.]
    CPU time for vxc    229.12 sec, wall time      1.07 sec
E1 = -329.7177689282676  Ecoul = 108.67401774509713  Exc = -18.105657095071813
    Total E(T) = -239.149408278242  Free energy = -239.149408278242  E0 = -239.149408278242
cycle= 1 E= -239.149408278242  delta_E= -0.123  |g|= 0.125  |ddm|= 0.495
    CPU time for cycle= 1    238.23 sec, wall time      1.11 sec
    Fermi level -0.200917  Sum mo_occ_kpts = 12.0  should equal nelec = 13
    sigma = 0.000918733  Optimized mu = -0.445342162829  entropy = -0
  alpha mo_energy/mo_occ
  [-55.199844  -4.13547   -2.681454  -2.681454  -2.681454  -0.486169
  -0.200917  -0.200917  -0.200917]
  [1. 1. 1. 1. 1. 1. 0. 0. 0.]
  beta  mo_energy/mo_occ
  [-55.199844  -4.13547   -2.681454  -2.681454  -2.681454  -0.486169
  -0.200917  -0.200917  -0.200917]
  [1. 1. 1. 1. 1. 1. 0. 0. 0.]
nelec by numeric integration = [6. 6.]
    CPU time for vxc    225.75 sec, wall time      1.03 sec
E1 = -330.29073247060654  Ecoul = 109.3181457555893  Exc = -18.180604893324524
    Total E(T) = -239.153191608342  Free energy = -239.153191608342  E0 = -239.153191608342
cycle= 2 E= -239.153191608342  delta_E= -0.00378  |g|= 0.034  |ddm|= 0.0733
    CPU time for cycle= 2    236.30 sec, wall time      1.08 sec
    Fermi level -0.194239  Sum mo_occ_kpts = 12.0  should equal nelec = 13
    sigma = 0.000918733  Optimized mu = -0.438664432958  entropy = -0
  alpha mo_energy/mo_occ
  [-55.121727  -4.095974  -2.64082   -2.64082   -2.64082   -0.480409
  -0.194239  -0.194239  -0.194239]
  [1. 1. 1. 1. 1. 1. 0. 0. 0.]
  beta  mo_energy/mo_occ
  [-55.121727  -4.095974  -2.64082   -2.64082   -2.64082   -0.480409
  -0.194239  -0.194239  -0.194239]
  [1. 1. 1. 1. 1. 1. 0. 0. 0.]
nelec by numeric integration = [6. 6.]
    CPU time for vxc    228.10 sec, wall time      1.04 sec
E1 = -330.17242187830874  Ecoul = 109.18387365534034  Exc = -18.16494280526951
    Total E(T) = -239.153491028238  Free energy = -239.153491028238  E0 = -239.153491028238
cycle= 3 E= -239.153491028238  delta_E= -0.000299  |g|= 7.93e-05  |ddm|= 0.0157
    CPU time for cycle= 3    238.08 sec, wall time      1.09 sec
Linear dependence found in DIIS error vectors.
    Fermi level -0.194224  Sum mo_occ_kpts = 12.0  should equal nelec = 13
    sigma = 0.000918733  Optimized mu = -0.438649712339  entropy = -0
  alpha mo_energy/mo_occ
  [-55.121664  -4.095922  -2.640768  -2.640768  -2.640768  -0.480395
  -0.194224  -0.194224  -0.194224]
  [1. 1. 1. 1. 1. 1. 0. 0. 0.]
  beta  mo_energy/mo_occ
  [-55.121664  -4.095922  -2.640768  -2.640768  -2.640768  -0.480395
  -0.194224  -0.194224  -0.194224]
  [1. 1. 1. 1. 1. 1. 0. 0. 0.]
nelec by numeric integration = [6. 6.]
    CPU time for vxc    228.12 sec, wall time      1.05 sec
E1 = -330.172309178593  Ecoul = 109.18374608443335  Exc = -18.164927935144142
    Total E(T) = -239.153491029304  Free energy = -239.153491029304  E0 = -239.153491029304
cycle= 4 E= -239.153491029304  delta_E= -1.07e-09  |g|= 4.76e-05  |ddm|= 1.48e-05
    CPU time for cycle= 4    238.10 sec, wall time      1.09 sec
Linear dependence found in DIIS error vectors.
    Fermi level -0.194218  Sum mo_occ_kpts = 12.0  should equal nelec = 13
    sigma = 0.000918733  Optimized mu = -0.438643402109  entropy = -0
  alpha mo_energy/mo_occ
  [-55.121637  -4.095899  -2.640745  -2.640745  -2.640745  -0.480389
  -0.194218  -0.194218  -0.194218]
  [1. 1. 1. 1. 1. 1. 0. 0. 0.]
  beta  mo_energy/mo_occ
  [-55.121637  -4.095899  -2.640745  -2.640745  -2.640745  -0.480389
  -0.194218  -0.194218  -0.194218]
  [1. 1. 1. 1. 1. 1. 0. 0. 0.]
nelec by numeric integration = [6. 6.]
    CPU time for vxc    228.04 sec, wall time      1.06 sec
E1 = -330.1722608667522  Ecoul = 109.18369139783735  Exc = -18.16492156068287
    Total E(T) = -239.153491029598  Free energy = -239.153491029598  E0 = -239.153491029598
cycle= 5 E= -239.153491029598  delta_E= -2.94e-10  |g|= 3.4e-05  |ddm|= 6.34e-06
    CPU time for cycle= 5    237.60 sec, wall time      1.10 sec
Linear dependence found in DIIS error vectors.
    Fermi level -0.194214  Sum mo_occ_kpts = 12.0  should equal nelec = 13
    sigma = 0.000918733  Optimized mu = -0.43863989486  entropy = -0
  alpha mo_energy/mo_occ
  [-55.121622  -4.095887  -2.640733  -2.640733  -2.640733  -0.480386
  -0.194214  -0.194214  -0.194214]
  [1. 1. 1. 1. 1. 1. 0. 0. 0.]
  beta  mo_energy/mo_occ
  [-55.121622  -4.095887  -2.640733  -2.640733  -2.640733  -0.480386
  -0.194214  -0.194214  -0.194214]
  [1. 1. 1. 1. 1. 1. 0. 0. 0.]
nelec by numeric integration = [6. 6.]
    CPU time for vxc    228.59 sec, wall time      1.05 sec
E1 = -330.172234014532  Ecoul = 109.18366100251217  Exc = -18.164918017698866
    Total E(T) = -239.153491029719  Free energy = -239.153491029719  E0 = -239.153491029719
cycle= 6 E= -239.153491029719  delta_E= -1.21e-10  |g|= 2.65e-05  |ddm|= 3.52e-06
    CPU time for cycle= 6    238.52 sec, wall time      1.10 sec
    Fermi level -0.194201  Sum mo_occ_kpts = 12.0  should equal nelec = 13
    sigma = 0.000918733  Optimized mu = -0.438626192136  entropy = -0
  alpha mo_energy/mo_occ
  [-55.121552  -4.095835  -2.640681  -2.640681  -2.640681  -0.480373
  -0.194201  -0.194201  -0.194201]
  [1. 1. 1. 1. 1. 1. 0. 0. 0.]
  beta  mo_energy/mo_occ
  [-55.121552  -4.095835  -2.640681  -2.640681  -2.640681  -0.480373
  -0.194201  -0.194201  -0.194201]
  [1. 1. 1. 1. 1. 1. 0. 0. 0.]
nelec by numeric integration = [6. 6.]
    CPU time for vxc    228.08 sec, wall time      1.04 sec
E1 = -330.1721143875188  Ecoul = 109.18352559134695  Exc = -18.164902233719403
    Total E(T) = -239.153491029891  Free energy = -239.153491029891  E0 = -239.153491029891
Extra cycle  E= -239.153491029891  delta_E= -1.72e-10  |g|= 7.24e-06  |ddm|= 1.57e-05
    CPU time for scf_cycle   1915.78 sec, wall time      8.96 sec
    CPU time for SCF   1915.78 sec, wall time      8.96 sec
converged SCF energy = -239.153491029891  <S^2> = -1.7763568e-15  2S+1 = 1

**Comment by fishjojo** [comment]
`sigma` is too small in your example. Bigger numbers such as 0.002 should work.

**Comment by susilehtola** [comment]
Running the calculation with `sigma = 0.2 / 27.2114` I see `nelec by numeric integration = [6.5 6.5]` which is the wrong spin state?

**Comment by susilehtola** [comment]
Maybe the problem is that the smearing code just straight-away uses the **k** points version from pbc, where **k** points are summed over for occupations, which should not be done in the molecular case

**Comment by fishjojo** [comment]
There is an argument `fix_spin`, which can be set to True for PBC calculations to fix the spins. A patch is needed to make it work also for molecules.

**Comment by sunqm** [comment]
The fix_spin parameter has been added to the smearing code for molecules since the 2.5 release.
