### ISSUE TITLE
Generating CHGCAR when there are multi-k-points

### ISSUE THREAD

**Issue by changsuc** [pyscf/pyscf#1564]
Hi, 
The example in `pyscf/examples/tools/06-chgcar.py` shows how to generate CHGCAR file by PySCF.  In this case, only a gamma point calculation is performed. I wondered how shall we generate CHGCAR when more than gamma point is included in pbc calculation.

Shall we first use `k2gamma` module to transfer MO coefficients/DM to R-space (while the previous small unit cell is replaced by a larger supercell)?

If we want to preserve the small unit cell, is it correct to simply feed the coefficients at gamma point to `chgcar.orbital()`? For example, `chgcar.orbital(cell, 'test.chgcar', kmf.mo_coeff[0])`

Or we should transform the coefficients to R-space first and then feed the coefficients at R0 to `chgcar.orbital()`?

Thank you in advance!

**Comment by fishjojo** [comment]
You may try to transform the MOs to Wannier orbitals at the reference cell, like
$W_{\mu i} (R_0) = \frac{1}{N_k} \sum_k C_{\mu i} (k) e^{-i k \cdot R_0}$
but this is probably not a good idea for delocalized MOs.
The supercell MOs given by `k2gamma` are equivalent to the k-sampling MOs.

**Comment by changsuc** [comment]
Thank you Xing. It helps a lot!
