### ISSUE TITLE
Internal compiler error, probably a GCC bug

### ISSUE THREAD

**Issue by hebrewsnabla** [pyscf/pyscf#1571]
Compile latest master branch with GCC 8.3 causes this error
```
[  8%] Built target np_helper
Scanning dependencies of target cgto
[  9%] Building C object gto/CMakeFiles/cgto.dir/fill_int2c.c.o
/share/home/srwang/pyscf2/pyscf/lib/gto/fill_int2c.c: In function ‘GTOoverlap_cond’:
/share/home/srwang/pyscf2/pyscf/lib/gto/fill_int2c.c:204:17: internal compiler error: Illegal instruction
                 min_cceij = 1e9;
                 ^~~~~~~~~~
0xa2f08f crash_signal
        ../../gcc/toplev.c:325
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
make[2]: *** [gto/CMakeFiles/cgto.dir/fill_int2c.c.o] Error 1
make[1]: *** [gto/CMakeFiles/cgto.dir/all] Error 2
make: *** [all] Error 2
```
Switching to ICC 2019 or GCC 12 resolve this issue. The github actions use GCC 9, I guess, and it goes fine. So probably this is a bug of GCC 8. 

This line of code was introduced in https://github.com/pyscf/pyscf/commit/76d0c006170aa92a614cbc538a7eddafe900c5c5 (Aug 2022) so the versions before that compile fine with GCC 8.

However, I can't find a way to circumvent this by adjusting the code. Maybe we should add a note to prevent users using GCC 8?

**Comment by jamesETsmith** [comment]
@hebrewsnabla, I wasn't able to reproduce this error with GCC version 8.3.0 for the master branch (c0c4dbcb97b5725b5bbec3257b78f18c63663c76). It may be a problem with your gcc compiler setup rather than a bug in the compiler itself. If you're on your own system, I'd suggest you reinstall gcc or if you're on a managed cluster, I'd reach out to the system administrator.

**Comment by hebrewsnabla** [comment]
Yeah, I cannot reproduce this with GCC 8.3.1 in docker, so this issue maybe a problem with gcc build on certain machine. Thank you for the test!
