### ISSUE TITLE
Parallelization issues

### ISSUE THREAD

**Issue by lanieleung** [pyscf/pyscf#1573]
I'm trying to run FCI but am having some difficulty doing so in parallel on a cluster. I would appreciate any suggestions for correcting my approach. Here are a few things that I have tried:
- Using `mpirun -n 128` gives me 128 copies of the same first calculation rather than correctly parallelizing the calculations.
- Installation of mpi4pyscf fails on both my local machine and on the cluster. I receive the error ```File "/tmp/pip-install-wuzy0yyl/mpi4pyscf_158d5063bd3d46fa9f1393f9a5faec66/setup.py", line 15, in <module>
          with open(os.path.join(topdir, 'requirements.txt'), 'r') as f:
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-wuzy0yyl/mpi4pyscf_158d5063bd3d46fa9f1393f9a5faec66/requirements.txt'```

Thanks in advance for your time.

**Comment by hebrewsnabla** [comment]
pyscf itself do not support MPI. Parallelization of pyscf is achieved by openMP. You can set `OMP_NUM_THREADS` to enable a nulti-thread job.

And, there's no fci module in mpi4pyscf at all, as far as I know.

**Comment by verena-neufeld** [comment]
Hi @lanieleung , has your question been answered?

**Comment by lanieleung** [comment]
Yes, this solves the problem. Thank you both.
