### ISSUE TITLE
How to get one body integral and two body integral for MCSCF method?

### ISSUE THREAD

**Issue by anbonimus** [pyscf/pyscf#1583]
I checked the code but all those integrals are calculated on hartree fock level. Is there a way to return those integrals in MCSCF level?

**Comment by jamesETsmith** [comment]
@anbonimus, I'm not sure what you mean by "checked the code but all those integrals are calculated on HF level". Could you be more specific about what you're looking for and/or show us what you've tried with a minimal working example?

If you're just looking for the integrals after MCSCF, you could try the following:
```python
import numpy
from pyscf import gto, scf, mcscf

mol = gto.M(
    atom = 'N 0 0 0; N 0 0 1.2',
    basis = 'ccpvdz')
myhf = scf.RHF(mol)
myhf.kernel()

norb = 6
nelec = 6
mycas = mcscf.CASSCF(myhf, norb, nelec)
mycas.kernel()
h1e_cas, ecore = mycas.get_h1eff() # 1-body integrals and energy of the core
h2e_cas = mycas.get_h2eff()        # 2-body integrals
```

See the source for more details
https://github.com/pyscf/pyscf/blob/7bcae2e3044bf4259f1c6e6b03829912ce0ae1a0/pyscf/mcscf/casci.py#L43
https://github.com/pyscf/pyscf/blob/7bcae2e3044bf4259f1c6e6b03829912ce0ae1a0/pyscf/mcscf/mc1step.py#L974

**Comment by anbonimus** [comment]
I see. Thank you so much for the help! Does similar features exists for
other methods like ccsd?

Ruiren

**Comment by jamesETsmith** [comment]
@anbonimus, CCSD uses the Hartree Fock molecular orbitals so you can use `ao2mo` to get those integrals. See the [example here](https://github.com/pyscf/pyscf/blob/master/examples/ao2mo/00-mo_integrals.py)

**Comment by anbonimus** [comment]
Thank you so much!

Ruiren
