### ISSUE TITLE
Truncated CI

### ISSUE THREAD

**Issue by Exarctus** [pyscf/pyscf#159]
I’m a new user to PySCF and I’m looking for quite specific functionality - Is it possible to perform truncated CI through specifying the determinant expansion by predefined sets of 1,2,3...n-tuple excitations? Key is here that beyond singly-excited determinants I only wish to include a predefined subset of n-tuply excited determinants...

Any advice would be greatly appreciated!

**Comment by sunqm** [comment]
There is no such a function in the source code. The excitation levels can be accessed by a few lines of coding. CI coefficients are stored in a 2D array, where row corresponds to alpha occupation pattern and colum corresponds to beta occupation pattern.  You can filter the overall excitation level based on the excitation levels of alpha and beta determinants.  The code below can give the alpha and beta excitations.
```
from pyscf import fci
alpha_occs = fci.cistring._gen_occslst(range(norb), neleca)
alpha_excitations = (alpha_occs >= neleca).sum(axis=1)
beta_occs = fci.cistring._gen_occslst(range(norb), neleca)
beta_excitations = (alpha_occs >= neleca).sum(axis=1)
```

**Comment by Exarctus** [comment]
Thanks for the code snippet!

Is it technically possible to modify the code such that this is possible, though? - or is there some implementation limitation preventing this?

**Comment by tberkel** [comment]
It's easy to modify the code to do truncated CI _at FCI cost_, by regularly zeroing out any elements corresponding to higher-level determinants.  Using the snippet from @sunqm , you could modify the `kernel()` of, for example, `fci_slow.py`, as follows (untested, but should be close to correct):
```
def kernel(h1e, g2e, norb, nelec, ecore=0):

    h2e = absorb_h1e(h1e, g2e, norb, nelec, .5)

    na = cistring.num_strings(norb, nelec//2)
    ci0 = numpy.zeros((na,na))
    ci0[0,0] = 1

    # new code here
    neleca = nelecb = nelec//2
    nb = na
    ci_level = 3 # e.g. CISDT; make this kwarg if desired
    alpha_occs = fci.cistring._gen_occslst(range(norb), neleca)
    alpha_excitations = (alpha_occs >= neleca).sum(axis=1)
    beta_occs = fci.cistring._gen_occslst(range(norb), nelecb)
    beta_excitations = (beta_occs >= nelecb).sum(axis=1)
    a_idx, b_idx = numpy.array([
        [a,b] for a in alpha_excitations for b in beta_excitations if a+b > ci_level ]).T

    def hop(c):
        hc = contract_2e(h2e, c, norb, nelec)
        # new code here
        hc = hc.reshape(na,nb)
        hc[a_idx,b_idx] = 0
        return hc.reshape(-1)
    hdiag = make_hdiag(h1e, g2e, norb, nelec)
    # new code here
    hdiag = hdiag.reshape(na,nb)
    hdiag[a_idx,b_idx] = 0
    hdiag = hdiag.reshape(-1)
    precond = lambda x, e, *args: x/(hdiag-e+1e-4)
    e, c = lib.davidson(hop, ci0.reshape(-1), precond)
    return e+ecore
```

**Comment by Exarctus** [comment]
Thanks for the reply! Doing it at FCI cost defeats the purpose a bit.

Presumably, PySCF has some generalized functions for calculating 1- and 2-electron integrals given the choice of basis? This way I can run a standard UHF calculation and expand the multi-configurational wavefunction in this determinant basis, by constructing the coefficient matrices corresponding to the excitations I want. A bit brute-force, but a better than doing things at FCI cost...

If you have any samples or advice, would be mighty handy - I'm not very familiar yet with the internals of PySCF.

**Comment by sunqm** [comment]
Some relevant examples:

https://github.com/sunqm/pyscf/blob/master/examples/ao2mo/00-mo_integrals.py
https://github.com/sunqm/pyscf/blob/master/examples/mcscf/44-mcscf_active_space_hamiltonian.py

**Comment by gkc1000** [comment]
It sounds like you are really looking to do some form of selected CI, but
are looking to change the selection procedure. PySCF has a version of
heat-bath CI implemented in the HCI module that uses
the underlying alpha/beta string methodology. This is not the most
efficient implementation but should not be too hard to play around with. A
different, more efficient, implementation of HCI can be found in the DICE
program, which has an interface with PySCF and can be obtained from Sandeep
Sharma's group.
