### ISSUE TITLE
ao2mo for spinor integrals ends in segmentation fault

### ISSUE THREAD

**Issue by martinanibbi** [pyscf/pyscf#1590]
Hello everyone,

My problem concerns the use of ao2mo for the 1 and 2-body matrices with the 'spinor' label.
At first I calculate the atomic integrals through the code:
```
atom = '''H 0 0 0; H 0 0 0.735'''
basis = 'sto-6g'
charge = 0
spin = 0
verbose = 0
mol = gto.Mole()
mol.build(atom = atom,
                  basis = basis,
                  charge = charge,
                  spin = spin,
                  verbose = verbose)

h1 = np.kron(self.mol.get_hcore(), np.identity(2))
h2 = mol.intor('int2e_spinor')
```
I noted that there's no label 'int1e_kin_spinor' and so I figured the solution above for the 1-body term, can you confirm to me if it's correct?

Secondly, I do an HF calculation and I would like to calculate the new integrals in the MO basis:
```
myhf = scf.RHF(mol)
myhf.kernel()
coeff = myhf.mo_coeff
```
The problem is that the following line gives a segmentation fault error:
```
mol_2body_mo = ao2mo.kernel(mol, coeff, intor = 'int2e_spinor', compact=False)
```
and by transforming directly h2 I  still get an error message:
```
File "/work/ge84jaj/miniconda3/envs/qib_support_env_p3.10/lib/python3.10/site-packages/pyscf/ao2mo/__init__.py", line 471, in kernel
    return full(eri_or_mol, mo_coeffs, erifile, dataname, intor, *args, **kwargs)
  File "/work/ge84jaj/miniconda3/envs/qib_support_env_p3.10/lib/python3.10/site-packages/pyscf/ao2mo/__init__.py", line 145, in full
    return incore.full(eri_or_mol, mo_coeff, *args, **kwargs)
  File "/work/ge84jaj/miniconda3/envs/qib_support_env_p3.10/lib/python3.10/site-packages/pyscf/ao2mo/incore.py", line 65, in full
    return general(eri_ao, (mo_coeff,)*4, verbose, compact)
  File "/work/ge84jaj/miniconda3/envs/qib_support_env_p3.10/lib/python3.10/site-packages/pyscf/ao2mo/incore.py", line 134, in general
    eri1 = half_e1(eri_ao, mo_coeffs, compact)
  File "/work/ge84jaj/miniconda3/envs/qib_support_env_p3.10/lib/python3.10/site-packages/pyscf/ao2mo/incore.py", line 213, in half_e1
    raise NotImplementedError
NotImplementedError
```

For the 1-body part I figured a similar solution as before:
```
  mol_1body_mo = np.kron(ao2mo.kernel(mol, coeff, intor = 'int1e_nuc') + ao2mo.kernel(mol, coeff, intor = 'int1e_kin'), 
                         np.identity(2))
```
but I can't find a similar strategy for the 2-body matrix.

Could you please tell me if I am doing something wrong here and do you have any suggestion about how to get the spin-orbital 2-body matrix starting from the space-orbital one by hand?
Thanks in advance!

**Comment by sunqm** [comment]
The orbital coefficients have wrong size. It needs to be an array of shape (2N,2N)

**Comment by martinanibbi** [comment]
Hi, thank you very much for your answer.
Could you please confirm me that in order to have the correct coefficient matrix for spin-orbitals I just have to make again a product tensor with a 2-D identity?
`coeff = np.kron(myhf.mo_coeff, np.identity(2))`

Thanks in advance!

**Comment by sunqm** [comment]
The shape is correct. However, the coefficients from RHF calculation may not
make too much sense for the integrals of spinor basis. You probably need to
transform the spherical basis to spinor basis with the transformation matrix
mol.sph2spinor_coeff()

**Comment by martinanibbi** [comment]
Thank you very much for your answer, but it's not really clear to me how to use this transformation.
Should I just use it to transform the coefficient matrix like:
```
ca, cb = mol.sph2spinor_coeff()
coeff = myhf.mo_coeff
coeff_spin = ca.T.dot(coeff).dot(ca)
coeff_spin += cb.T.dot(coeff).dot(cb)
```
Or should I also apply it to the 2 body integral? And if so, could you kindly tell me how am I supposed to do it?
I tried to look on the examples here on Github but I haven't found anything specific to the molecular and spin-orbital eri...

Thank you very much for your time and your patience!

**Comment by xubwa** [comment]
This do the transformation for j-adapted spinors and is complex. If you want to obtain the real valued integral for ghf style spin orbitals, you may have a look at this function https://github.com/xubwa/socutils/blob/87ae36eabf7122cd98f57276a01a283488f4e77f/fcidump_rel.py#L93 where I implemented real valued and complex valued ghf integral transformation while the complex valued ghf uses a function I wrote in this pull request https://github.com/pyscf/pyscf/pull/1411.

**Comment by verena-neufeld** [comment]
Hi @martinanibbi , thanks for opening this issue. Has it been resolved?

**Comment by martinanibbi** [comment]
Hello @verena-neufeld , thanks for your question, actually the project was left on stand-by and I would still need a functioning example.

Right now my code looks like this: 
```
atom = '''H 0 0 0; H 0 0 0.735'''
basis = 'sto-6g'
unit = 'angstrom'
charge = 0
spin = 0
verbose = 0

mol = gto.Mole()
mol.build(atom    = atom,
          basis   = basis,
          charge  = charge,
          spin    = spin,
          unit    = unit,
          verbose = verbose)

# spin-orbital integrals
h1 = np.kron(mol.get_hcore(), np.identity(2))
h2 = mol.intor('int2e_spinor')

# HF calculation
mf = scf.RHF(mol)
mf.kernel()
coeff = mf.mo_coeff

# molecular orbitals
spin_coeff = np.kron(coeff, np.identity(2))
h1_mo = np.einsum('ji,jk,kl->il', spin_coeff.conj(), h1, spin_coeff)
h2_mo = np.einsum('pqrs,pi,qj,rk,sl->ijkl', h2, spin_coeff, spin_coeff, spin_coeff, spin_coeff)
```

would this be correct or am I missing something? Referring to:
> The shape is correct. However, the coefficients from RHF calculation may not make too much sense for the integrals of spinor basis. You probably need to transform the spherical basis to spinor basis with the transformation matrix mol.sph2spinor_coeff()
this method could be wrong, but I couldn't find any example of how to use mol.sph2spinor_coeff() in this specific case.

Thank you very much!

**Comment by sunqm** [comment]
Looks what you need is integrals in spin-orbital basis, than the spinors. It's not necessary to expand the dimension of the orbitals using `np.kron`. Instead, you can transform integrals in spatial orbital first, then assign them to the relevant blocks of the spin-orbital integrals, such as
```
# HF calculation
mf = scf.RHF(mol)
mf.kernel()
coeff = mf.mo_coeff
n = coeff.shape[1]
h1_mo = np.zeros((n*2, n*2)) 
h1_mo[:n,:n] = h1_mo[n:,n:] = np.einsum('pi,pq,qj->ij', coeff, mf.get_hcore(), coeff)

h2_mo = np.zeros((n*2,n*2,n*2, n*2)) 
h2_mo[:n,:n,:n,:n] = h2_mo[n:,n:,:n,:n] = h2_mo[:n,:n,n:,n:] = h2_mo[n:,n:,n:,n:] = np.einsum('pqrs,pi,qj,rk,sl->ijkl', mol.intor('int2e'), coeff, coeff, coeff, coeff)
```

However, the recommended method is to use the feature provided by #1411 .

If you have more questions, feel free to reopen the issue.
