### ISSUE TITLE
Is that possible to perform BCCD(T) on pyscf?

### ISSUE THREAD

**Issue by AssoliLan** [pyscf/pyscf#1591]
I saw there is some discussion for BCCD https://github.com/pyscf/pyscf/issues/1343
is that possible to do (T), e.g., by passing double amplitudes to (T) correction? I am not familiar with PySCF syntax, so ask this question. Thank you very much

**Comment by tberkel** [comment]
Yes, that's easily doable. The calculation of (T) won't know or care where
the T2 amplitudes came from, and will just use them to evaluate the (T)
expression.

**Comment by AssoliLan** [comment]
Thank you so much for your comment. I am super grateful to have an example for it. I can also try to make one.

**Comment by tberkel** [comment]
You should be able to just do the following:
```
mycc = bccd_kernel_(mycc, ... )
et = mycc.ccsd_t()
print('BCCD(T) correlation energy =', mycc.e_corr + et)
```

**Comment by AssoliLan** [comment]
Thanks a lot. I modified the example from https://github.com/pyscf/pyscf/blob/master/pyscf/cc/bccd.py 
as
```
import pyscf
from pyscf import cc
import numpy as np

np.set_printoptions(3, linewidth=1000, suppress=True)
mol = pyscf.M(
    atom = 'H 0 0 0; F 0 0 1.1',
    basis = 'ccpvdz',
    verbose = 7,
    spin = 0,
)

myhf = mol.HF()
myhf.conv_tol = 1e-12
myhf.kernel()
E_ref = myhf.e_tot
rdm1_mf = myhf.make_rdm1()

mycc = cc.CCSD(myhf, frozen=None)
mycc.kernel()
mycc.conv_tol = 1e-12

mycc = cc.bccd.bccd_kernel_(mycc, diis=True, verbose=4)
e_r = mycc.e_tot

#print (la.norm(mycc.t1))
#assert la.norm(mycc.t1) < 1e-5

myhf = mol.UHF()
myhf.kernel()
myucc = cc.CCSD(myhf, frozen=None)
myucc.frozen = [0]
myucc.kernel()

mybcc = cc.bccd.bccd_kernel_(myucc)
e_u = mybcc.e_tot

mygcc = cc.addons.convert_to_gccsd(mycc)
mybcc = cc.bccd.bccd_kernel_(mycc)
e_g = mybcc.e_tot

print('rug',e_r,e_u,e_g)
print (abs(e_g - e_r))
assert abs(e_g - e_r) < 1e-6

et = mybcc.ccsd_t()
print(et)
print('BCCD(T) correlation energy =', mybcc.e_corr + et)
``` 

and got 
```
rug -100.20352109765885 -100.20167083138682 -100.20352109584711
1.8117418676411035e-09
-0.002623751065813703
BCCD(T) correlation energy = -0.2202261008366449
```

I tried to compare PSI4 1.7
```
molecule hf {
    h      0.0000        0.0000        0.0000
    f      0.0000        0.0000        1.1000
}

set {
   basis cc-pvdz
   r_convergence 12
   e_convergence 12
   d_convergence 12
}

energy('bccd(t)')
```
the result is
```
 Wave function   =    BCCD_T
    Reference wfn   =      RHF

    Nuclear Rep. energy (wfn)                =    4.329631723663637
    SCF energy          (wfn)                = -100.203521097406082
    Reference energy    (file100)            =  -99.985918770738792
    CCSD energy         (file100)            =   -0.217602326668616
    Total CCSD energy   (file100)            = -100.203521097407403

    Number of ijk index combinations:               35
    Memory available in words               :        65536000
    Approx. words needed per explicit thread:            1372
    Number of threads for explicit ijk threading:    1

    MKL num_threads set to 1 for explicit threading.

    (T) energy                                =   -0.002625521337000
      * CCSD(T) total energy                  = -100.206146618744413
```
the BD part agree with PSI4 1.7 about 10^-10
and (T) part differs 10^-6. 

questions: 
1. why ucc differs rcc? The system is still within the Coulson-Fischer point. Does unrestricted cc affect earlier than hf level?
2. why (T) differs 10^-6 than BCCD level?

**Comment by tberkel** [comment]
In your pyscf script, the UCCSD calculation is being done with a frozen
core. Not sure why the (T) differs at 1e-6.

**Comment by AssoliLan** [comment]
Thank you so much. Comment out `myucc.frozen = [0]` makes the agreement much better 
```
rug -100.20352109767049 -100.20352105347644 -100.20352109281896
```

**Comment by zhcui** [comment]
The difference in BCCD(T) energy is due to the semicanonicalization in the Psi4.
My guess is that we should use semicanonicalized orbitals for non-HF reference. What do you think? @tberkel 

If you want to give the same number in pyscf, here is a simple example (I will probably submit a PR later):

```
import pyscf
from pyscf import cc
import numpy as np

np.set_printoptions(3, linewidth=1000, suppress=True)
mol = pyscf.M(
    atom = 'H 0 0 0; F 0 0 1.1',
    basis = 'ccpvdz',
    verbose = 7,
    spin = 0,
)

myhf = mol.HF()
myhf.conv_tol = 1e-12
myhf.kernel()
E_ref = myhf.e_tot
rdm1_mf = myhf.make_rdm1()

mycc = cc.CCSD(myhf, frozen=None)
mycc.kernel()
mycc.conv_tol = 1e-8

mycc = cc.bccd.bccd_kernel_(mycc, diis=True, verbose=4)
e_r = mycc.e_tot

# BCCD (T)
from scipy import linalg as la
dm = mycc._scf.make_rdm1(mycc.mo_coeff, mycc.mo_occ)
vhf = mycc._scf.get_veff(mycc.mol, dm) 
fockao = mycc._scf.get_fock(vhf=vhf, dm=dm)
fock = mycc.mo_coeff.conj().T @ fockao @ mycc.mo_coeff
# semicanonicalize fock
foo = fock[:mycc.nocc, :mycc.nocc]
fvv = fock[mycc.nocc:, mycc.nocc:]
ew_o, ev_o = la.eigh(foo)
ew_v, ev_v = la.eigh(fvv)
umat = la.block_diag(ev_o, ev_v)

myhf.mo_coeff = mycc.mo_coeff @ umat
myhf.e_tot = myhf.energy_tot()
t1 = cc.bccd.transform_t1_to_bo(mycc.t1, umat)
t2 = cc.bccd.transform_t2_to_bo(mycc.t2, umat)
mycc.__init__(myhf)
mycc.t1 = np.array(t1, order='C')
mycc.t2 = np.array(t2, order='C')
e_t = mycc.ccsd_t() # -0.00262555585518526

```

**Comment by tberkel** [comment]
Thanks for the fix @zhcui, I agree that semicanonicalization makes sense here. With this much maturity, you should consider upgrading BCCD to a proper class. What do you think?

**Comment by zhcui** [comment]
> Thanks for the fix @zhcui, I agree that semicanonicalization makes sense here. With this much maturity, you should consider upgrading BCCD to a proper class. What do you think?

Hi Tim,

My first thought was to have a wrapper like the "FNOCCSD". But I agree, it would be good to have a class to make it easier to use.

Best,
Zhihao

**Comment by tberkel** [comment]
I like that idea too ... really anything that "looks like" a normal method
to the user, rather than needing to import a `kernel_` method, which
instead looks like a special feature for experts. Anything that allows
`cc.BCCD(mf)` is good, in my opinion.

**Comment by verena-neufeld** [comment]
Hi @AssoliLan , thanks for opening this issue! @AssoliLan @tberkel @zhcui , has it been resolved?
