### ISSUE TITLE
Error in calculation of excited states using module TDDFT

### ISSUE THREAD

**Issue by huangjianhuster** [pyscf/pyscf#1593]
I am tring to go through the tutorial of TDDFT calculation on the website (https://pyscf.org/user/tddft.html).
I made a script (**excited_state.py**, which is basically adoptted from the above link) to calculate excited state of any given xyz file.

all files could be found in the following zip file.
[benzene.zip](https://github.com/pyscf/pyscf/files/10614082/benzene.zip)

The example on the website works fine for me. and the next I want to try other organic molecules. 
I made two cases: **ethene.xyz** and **benzene.xyz**.

the first case: ethene.xyz
`python excited_state.py ethene.xyz`
it worked perfectly and output everything it intended to.

however, when I ran the benzene.xyz
`python excited_state.py benzene.xyz`
It complained an error: (pls see **benzene.log** for details)
Traceback (most recent call last):
...
  File "/home/jianhuang/miniconda3/envs/qm/lib/python3.9/site-packages/pyscf/dft/numint.py", line 2850, in _gen_rho_evaluator
    dms = lib.hermi_sum(dms, axes=(0,2,1)) * .5
  File "/home/jianhuang/miniconda3/envs/qm/lib/python3.9/site-packages/pyscf/lib/numpy_helper.py", line 656, in hermi_sum
    raise NotImplementedError('input array is not C-contiguous)
NotImplementedError: input array is not C-contiguous

I also tried to use different basis sets and functionals. The result below is list below:
basis = "sto-3g"; functional = "b3lyp"  --> succeeded!
basis = "631g"; functional = "b3lyp"    --> failed with the above-mentioned error.
basis = "sto-3g"; functional = "CAMB3LYP"    --> succeeded!
at this moment, I guessed there might somthing wrong with the basis set; I tried the following and all failed with the same error.
631++g, def2svp

**My environment**
python: 3.8.16
pyscf: 2.1.1
(you can also see pip.list in the above zip file)

**Comment by fishjojo** [comment]
This is the same problem as #1537, and should be fixed in the recent updates. Please try the latest commit.
