### ISSUE TITLE
How to store two-electron integral to disk?

### ISSUE THREAD

**Issue by WenkaiChen** [pyscf/pyscf#1598]
Dear pyscf developers,

I want to obtain the two-electron integral via pyscf for a C60 molecule at 6-31G* basis set.
However, It needs at least 3.62 TiB memory, which is not affordable for my machine.

How can I save this integral to the disk?
The code and coordinates are listed. Thanks.

### Code: 
#! /usr/bin/env python3
from pyscf import gto
import numpy as np

mol=gto.M(atom='c60.xyz')
mol.basis='6-31G*'
mol.build()
eri=mol.intor('int2e')
print(eri.shape)
np.save('eri.npy',X=eri,fmt='%20.10e')
###

### c60.xyz
60

C       -1.238472092      0.000000000     -4.157066277
C       -0.457951730      1.143470464     -3.872490729
C        0.804956744      0.706703611     -3.412037822
C        0.804956744     -0.706703611     -3.412037822
C       -0.457951730     -1.143470464     -3.872490729
C       -1.065152062     -2.293777808     -3.298224986
C       -2.449263848     -2.293777808     -3.011947947
C       -3.234450989     -1.143470464     -3.298224984
C       -2.630859568      0.000000000     -3.869077569
C       -3.234450989      1.143470464     -3.298224984
C       -2.449263848      2.293777808     -3.011947947
C       -1.065152062      2.293777808     -3.298224986
C       -0.405835009      3.000481413     -2.266919495
C        0.864624475      2.561103110     -1.803713519
C        1.468215899      1.417632648     -2.374566102
C        2.127532946      0.710929034     -1.343260615
C        2.127532946     -0.710929034     -1.343260615
C        1.468215899     -1.417632648     -2.374566102
C        0.864624475     -2.561103110     -1.803713519
C       -0.405835009     -3.000481413     -2.266919495
C       -1.382466445     -3.437248260     -1.343260611
C       -2.645374921     -3.000481413     -1.803713516
C       -3.627845698     -2.561103110     -0.874532023
C       -4.408366063     -1.417632648     -1.159107567
C       -4.211082422     -0.706703611     -2.374566098
C       -4.211082422      0.706703611     -2.374566098
C       -4.408366063      1.417632648     -1.159107567
C       -3.627845698      2.561103110     -0.874532023
C       -2.645374921      3.000481413     -1.803713516
C       -1.382466445      3.437248260     -1.343260611
C       -1.094477738      3.437248269      0.049126860
C        0.168430735      3.000481414      0.509579760
C        1.150901506      2.561103104     -0.419601733
C        1.931421865      1.417632641     -0.135026189
C        1.734138238      0.706703610      1.080432343
C        1.734138238     -0.706703610      1.080432343
C        1.931421865     -1.417632641     -0.135026189
C        1.150901506     -2.561103104     -0.419601733
C        0.168430735     -3.000481414      0.509579760
C       -1.094477738     -3.437248269      0.049126860
C       -2.071109174     -3.000481414      0.972785739
C       -3.341568652     -2.561103104      0.509579760
C       -3.945160071     -1.417632641      1.080432341
C       -4.604477130     -0.710929034      0.049126858
C       -4.604477130      0.710929034      0.049126858
C       -3.945160071      1.417632641      1.080432341
C       -3.341568652      2.561103104      0.509579760
C       -2.071109174      3.000481414      0.972785739
C       -1.411792122      2.293777797      2.004091219
C       -0.027680340      2.293777797      1.717814181
C        0.757506799      1.143470461      2.004091220
C        0.153915377      0.000000000      2.574943800
C        0.757506799     -1.143470461      2.004091220
C       -0.027680340     -2.293777797      1.717814181
C       -1.411792122     -2.293777797      2.004091219
C       -2.018992452     -1.143470461      2.578356965
C       -3.281900928     -0.706703610      2.117904067
C       -3.281900928      0.706703610      2.117904067
C       -2.018992452      1.143470461      2.578356965
C       -1.238472091      0.000000000      2.862932505
###

**Comment by fishjojo** [comment]
I guess it's better to use density fitting here?
Otherwise, you can compute a subset of the shells at a time and save them on the disk.

**Comment by WenkaiChen** [comment]
> I guess it's better to use density fitting here? Otherwise, you can compute a subset of the shells at a time and save them on the disk.

@fishjojo I want to get the two-electron integral for calculating coupling for excitation energy transfer, while the interested system may have more than 1000 atomic orbital/basis set. Thus, density fitting is not a good solution.

Thank you for the advise of subset of shells, I will try.

**Comment by ndattani** [comment]
Incidentally, I'm currently working with Deyan Mihaylov on a solution to this problem using `mpi4py` and the `Parallel HDF5` library. This will make the integrals file much smaller than 3TB, and will also speed-up the reading and writing of it significantly. A few years ago when I was writing 3TB checkpoint files in NECI (for the number of FCIQMC walkers on each determinant, with more than 100 billion determinants), it took 12 hours to write the file, but with parallel HDF5 this became just a few minutes.

**Comment by stefanvuckovic1** [comment]
> Incidentally, I'm currently working with Deyan Mihaylov on a solution to this problem using `mpi4py` and the `Parallel HDF5` library. This will make the integrals file much smaller than 3TB, and will also speed-up the reading and writing of it significantly. A few years ago when I was writing 3TB checkpoint files in NECI (for the number of FCIQMC walkers on each determinant, with more than 100 billion determinants), it took 12 hours to write the file, but with parallel HDF5 this became just a few minutes. I can try to let you know when this is done, or you can ping me back for an update later!

This is very interesting! Do you by chance have an update on achieving this with  `mpi4py` ?
