### ISSUE TITLE
Calculate 2c2e and 3c2e integrals w/o any screening

### ISSUE THREAD

**Issue by eljost** [pyscf/pyscf#1599]
Dear developers,

when calculating 2-center-2-electron and 3-center-2-electron (density fitting) integrals via `mol.intor`, does `pyscf` use screening methods to accelerate the calculations? To me it seems, some kind of screening is activated in this line of code:

https://github.com/pyscf/pyscf/blob/8b3fef8cf18f10d430261d4a8bea21fadf19bb1f/pyscf/gto/moleintor.py#L487

If this activates integral screening, is it also somehow possible to deactivate it?

All the best
Johannes

**Comment by fishjojo** [comment]
The default screening in libcint is quite conservative, which shouldn't affect the results very much. It can be set at the compilation time as follows. Bigger value means less screening.
https://github.com/pyscf/pyscf/blob/8b3fef8cf18f10d430261d4a8bea21fadf19bb1f/pyscf/lib/CMakeLists.txt#L176
To get more screening, you can also use the function below.
https://github.com/pyscf/pyscf/blob/8b3fef8cf18f10d430261d4a8bea21fadf19bb1f/pyscf/gto/mole.py#L2992

**Comment by eljost** [comment]
Thanks for the quick reply. I'll take a look at the lines you provided.

 I made the misassumption that screening will change the integral values, but if done correctly it obviously should have only a negligible effect on the results.
