### ISSUE TITLE
minao for PBC simulations with ECP

### ISSUE THREAD

**Issue by januseriksen** [pyscf/pyscf#1600]
Hi,

Using the default `MINAO` basis for generating IAOs prompts the following warning when used in combination with an ECP (as in, e.g., `examples/local_orb/05-ibo_periodic_diamond_cubegen.py`):

`WARN: ECP/PP is used. MINAO is not a good reference AO basis in IAO.`

What other choice of minao is generally recommended in this case?

Cheers,
Janus

**Comment by zhcui** [comment]
One possible choice is to use the smaller gth basis set.
For example, for gth-dzv, you may use gth-szv as the minao.
