### ISSUE TITLE
PySCF interface with pDynamo library for hybrid QM/MM calculations

### ISSUE THREAD

**Issue by garantes** [pyscf/pyscf#1602]
Dear PySCF users/devs.,

We would like to announce that PySCF has been interfaced with the pDynamo
library [1,2]. This is an open source program library designed for molecular
simulations and is mostly used for studying biomolecules with hybrid QM/MM
potentials.

[1] https://github.com/pdynamo/pDynamo3
[2] https://sites.google.com/site/pdynamomodeling/home

The interface is currently capable of electrostatic embedding QM/MM
calculations for energies with most PySCF methods (mean-field and post-HF) and 
for gradients with mean-field (R/U)(HF/KS) methods. It has been tested and
works for both previous (1.7) and current (2.1.1) stable PySCF versions.

Hope you find it useful, and pls let us know of any suggestions.

Cheers,

Guilherme

--

Prof. Dr. Guilherme Menegon Arantes

Instituto de Química
Universidade de São Paulo
Av. Prof. Lineu Prestes, 748 
São Paulo          05508-000
Brasil
Fone: 55-11-30913848       
http://gaznevada.iq.usp.br/
___________________________________

**Comment by ndattani** [comment]
I'm not sure how long this "issue" will remain open, but if you want to announce new interfaces, the [Community Promotion Board](https://mattermodeling.meta.stackexchange.com/q/261/5) at Matter Modeling Stack Exchange could be a good option for you. There's currently 5600+ registered users, [4 threads related to pDynamo](https://mattermodeling.stackexchange.com/questions/tagged/pdynamo), and [43 threads related to PySCF](https://mattermodeling.stackexchange.com/questions/tagged/pyscf).

**Comment by sunqm** [comment]
Thank you for sharing this feature with the PySCF community! It's great to see PySCF interfaced with the pDynamo library, enabling new QM/MM capabilities. If you have any further suggestions or want to continue the discussion, please feel free to reopen the issue.
