### ISSUE TITLE
PM orbitals with IAOs as population method, using ANO as minao basis?

### ISSUE THREAD

**Issue by luna-component** [pyscf/pyscf#1603]
I want to localize orbitals, using Pipek Mezey localization based on IAO populations, specifically using ANO as a reference basis for IAOs.
(My test system is a AlAs (2,2,2)-supercell at gamma point, using gth-szv basis set with gth-pbe pseudopotentials and pbe exchange-correlation functional)

To my knowledge, ANO is not among the choices of population methods in PM module, so I have, for starters, naively tried to pass the minao argument when computing iao coefficients. The calculation crashes (attaching the screenshot), and my understanding is that the overlap matrix computed in this basis is not positive definite.

I'm new to these methods, so my questions are: 
a) is it possible to do this with the current iao code? 
b) am I missing something re:the error message that I'm getting?

<img width="897" alt="Screenshot 2023-02-13 at 15 31 22" src="https://user-images.githubusercontent.com/28507277/218487735-1004cdc2-5476-4710-b381-d50a04bd78f1.png">

<img width="723" alt="Screenshot 2023-02-13 at 15 47 44" src="https://user-images.githubusercontent.com/28507277/218490194-9de3eb0b-5326-4f6b-a5f9-ead5f0b9cc45.png">

**Comment by fishjojo** [comment]
You may first try to remove the linear dependence of your ANO basis before using it as the minimal basis for IAO calculations.

**Comment by susilehtola** [comment]
Is the ANO basis minimal? Linear dependencies would suggest it isn't.

If I look at `pyscf/gto/basis/ano.dat`, the H basis reads
```
#BASIS SET: (8s,4p,3d,1f) -> [6s,4p,3d,1f]
```
which is far from a minimal basis; this is a polarized quadruple-zeta basis set!

**Comment by bogdanoff** [comment]
Properly chopped version would work. Should the `ANO-RCC-MB` available at BSE added to pyscf for this purpose?

**Comment by luna-component** [comment]
Thank you all for prompt replies and help.
Downloading the ANO-RCC-MB as we speak :)
@susilehtola Thank you for pointing this out!
@bogdanoff That would be very much desirable/appreciated.

**Comment by verena-neufeld** [comment]
Hi @luna-component , thanks for opening this issue, has it been resolved?
