### ISSUE TITLE
What is the difference between kernel and run?

### ISSUE THREAD

**Issue by AssoliLan** [pyscf/pyscf#1604]
Hi,

  This question is more about documentation and my incompetence of searching. 

  I often saw `run` and `kernel` in input files of `pyscf`. In this example, https://github.com/pyscf/pyscf/blob/master/examples/scf/00-simple_hf.py 
 if I replace `myhf.kernel()` as `myhf.run()`, I got similar results (except the last digit differs by 1).

 What is the difference between `kernel` and `run`? I am sorry that I did not find it in the quick start/user guide.

**Comment by tberkel** [comment]
PySCF has three "stream" functions, called `.set()`, `.run()`, and `.apply()`. The one you're asking about, `.run()`, calls the `.kernel()` function. It passes all arguments along to `kernel()` and it sets any passed kwargs as attributes of the class first. For example,
```
mf = scf.RHF(mol).run(dm_init, conv_tol=1e-5)
```
is identical to three steps
```
mf = scf.RHF(mol)
mf.conv_tol=1e-5
mf.kernel(dm_init)
```

**Comment by jamesETsmith** [comment]
Another important difference is that `run` returns the method object (e.g. `scf.RHF` object), while the `kernel` method returns the result of the calculation (often an energy value, but sometimes other things like gradients).

**Comment by AssoliLan** [comment]
Thank you so much!

**Comment by hebrewsnabla** [comment]
Another small difference: `mf.run(dm0=dm_init)` does not pass the dm_init to kernel but `mf.kernel(dm0=dm_init)` always works. The reason is that dm0 is neither a positional argument nor an attribute of the class.
