### ISSUE TITLE
zero point energy 

### ISSUE THREAD

**Issue by AMDALI** [pyscf/pyscf#1606]
Hello..
can some one tell me how can i get zero point  energy and the other properties please ..! I use this code for exemple.
from pyscf import gto
from pyscf import dft

My_Mol = gto.Mole()
My_Mol.atom = """H 0.000000000000 0.000000000000 0.000000000000
                  C 0.000000000000 0.000000000000 1.087900000000
                  H 1.025681956337 0.000000000000 1.450533333333
                  H -0.512840978169 0.888266630391 1.450533333333
                  H -0.512840978169 -0.888266630391 1.450533333333"""
My_Mol.basis = 'def2-qzvp'
My_Mol.verbose = 3
My_Mol.build()
mf = dft.RKS(My_Mol)
mf.xc = 'B3LYP'
mf.kernel()

mf.dump_scf_summary()
mf.analyze()
mf.spin_square() 

Thanks

**Comment by tberkel** [comment]
Frequency analysis requires a Hessian calculation. See the example here:
https://github.com/pyscf/pyscf/blob/master/examples/hessian/10-thermochemistry.py

**Comment by johTin** [comment]
[tberkel](https://github.com/tberkel) thank you

**Comment by AMDALI** [comment]
[tberkel](https://github.com/tberkel) thank you
