### ISSUE TITLE
Atoms in molecules calculations

### ISSUE THREAD

**Issue by SamTov** [pyscf/pyscf#1607]
Is there a simple way of doing atom in molecule or energy partitioning computations in pyscf? Alternatively, are any of the developers doing something like this?

**Comment by hebrewsnabla** [comment]
As far as I know there's no AIM partition code in pyscf. But, instead, it's easy to implement a fuzzy partition (hirshfeld or becke) with pyscf.

I'm not sure what your "energy partitioning" refers to. After some quick search, it looks like Istvan Mayer's energy partition (based on AIM or fuzzy) is easy to implement in PySCF.

**Comment by SamTov** [comment]
Hi, thank you for the quick answer. By energy partitioning I mean exactly what is mention in Mayers paper, commuting energies of atoms such that:

$$E_{DFT} = \sum_{i} \epsilon_{i}$$

where $I$ sums over the atoms in the system.

Do you have some reference to where people have implemented this fuzzy approach? I am not as familiar with PySCF as I am with other ab-initio codes but would love to keep the whole workflow in Python. If you have a starting point it would be greatly appreciated.

**Comment by januseriksen** [comment]
Hi Sam,

I've implemented a few such models here:

https://github.com/januseriksen/decodense

Code is still under some development, but please don't hesitate to reach out by email if you have questions or require literature references.

**Comment by SamTov** [comment]
Hi Janus, 

This is exactly what I am looking for thank you!  I will contact you personally if I have some issues.

**Comment by SamTov** [comment]
@hebrewsnabla @januseriksen Unless the PySCF as a team wants to include this functionality into the package I am happy to close the issue.
