### ISSUE TITLE
Issue with x2c and using cc-pCVXZ basis sets in at least PySCF 1.7.6 and newer

### ISSUE THREAD

**Issue by iliamazin** [pyscf/pyscf#1609]
Hi all,

I've come across what I believe to be a bug when trying to run a relativistic exact two-component PySCF calculation using a core-valence correlation consistent basis set (cc-pCVDZ) at the SCF/mean-field level. I have included two input files that do (c6h4_load.py) and do not (c6h4_parse.py) have the bug I describe below:

When running a calculation in which I request to use the cc-pCVDZ basis set, the output file lists the correct number of primitive GTOs, and the initial energy in the SCF procedure is reasonable (approx. -230 a.u.), but then the first step of the SCF cycle has an energy that is two orders of magnitude greater (approx. -50000 a.u.) and the SCF procedure does not converge.

The issue only occurs if I load the cc-pCVDZ basis set as it is defined within PySCF. Two actions fix this problem:
1) Switching to the non-core-valence variant (cc-pCVDZ -> cc-pVDZ); SCF converges normally without any complications.

2) If I manually specify the SAME cc-pCVDZ basis set and use the 'parse' function from the 'gto' module, the same exact x2c mean-field calculation no longer produces these massive energy errors in the SCF energy and convergence is smooth and quick.

The exact same input files provided below, run in PySCF 1.5.3 (compiled) and PySCF 1.6.2 (compiled), DO NOT have this issue. So it seems like something that could have been introduced around version 1.7?

The versions of PySCF I have found to be displaying this behavior:
PySCF 1.7.6 (conda)
PySCF 2.0.0a (compiled)
PySCF 2.0.1 (conda)
PySCF 2.1.1 (conda)
PySCF 2.1.1 (compiled)
PySCF 2.1.1 (compiled w/ OMP_NUM_THREADS=1)

Please let me know if you need any additional info from me! Thanks in advance.

Best,
Ilia Mazin

[x2c_basis_set_test.zip](https://github.com/pyscf/pyscf/files/10818364/x2c_basis_set_test.zip)

**Comment by ndattani** [comment]
Without downloading your .zip file (and extracting it, etc.), my questions are:
 - were you uncontracting the basis sets? For X2C calculations the basis sets are meant to be uncontracted (although there's also basis sets with names like cc-pVDZ-X2C which are contracted specifically for X2C).
 - With verbose=9 are you able to check the basis set exponents and contraction coefficients in the output files for the cases in which you manually added the cc-pCVDZ basis set to your input script, and the one in which you loaded it from a file?
- Have you checked the `ccpcvdz.dat` file and compared it with the data that you entered manually into your input script?

**Comment by sunqm** [comment]
This bug is fixed in PR #1620 . pyscf-2.2.1 should give you correct results.

**Comment by verena-neufeld** [comment]
Hi @iliamazin , thanks for opening this issue, has it been resolved?
