### ISSUE TITLE
Extremely slow CCSD(T) with bfdvqz

### ISSUE THREAD

**Issue by Kaminoatowo** [pyscf/pyscf#1611]
Dear pySCF Developers,

I'm using pySCF to compute nuclear gradients on a relatively small system at the CCSD(T) level of theory and using the BFD pseudopotential and related quadruple basis.
Such calculation is taking extremely long time. 

As comparison, I have also run the same calculation but using the ccECPs from Guangming Wang et al. [Journal of Chemical Physics (2022)](https://doi.org/10.1063/5.0087300), using a quadruple basis also in this case. 
For this I can get force estimates after roughly 18 hours.

In order to understand if the problem were due to the ecp, I tried to run a CCSD(T) calculation using BFD pseudopontential and the triple basis. Once again, I get the force estimates.

I would expect that the calculation I am interested in would take roughly as long as the ccECP calculation with the quadruple basis, but it seems that it stops before or meanwhile it is computing the forces.
May this be a memory issue?

This is the python script I am using for such calculation:

from pyscf import gto, scf, cc
mol = gto.M(
    atom = 'O   1.22520738   -0.21650657    0.04277212; C   0.03942994    0.52121543   -0.03089438; C  -1.34340326   -0.22371652    0.00907995; H   0.04225681    1.03774241   -1.02015154; H   0.01612195    1.21927174    0.82976456; H  -1.44160977   -0.74743328    0.98179758; H  -2.20561747    0.4641463    -0.07024415; H  -1.45401358   -1.01139134   -0.73696312; H   1.12411869   -1.06848808   -0.40328728',
    basis = {'O':'bfdvqz', 'C':'bfdvqz', 'H' : gto.parse('''
H   S    
 11.01022135 0.01821000
  2.77443788 0.07780336
  0.82691074 0.23903932
H   S
  0.28143479 1.00000000
H   S
  0.09602379 1.00000000
H   S
  0.02051762 1.00000000
H   P
  1.38496419 1.00000000
H   P
  0.38097910 1.00000000
H   P
  0.09335818 1.00000000
H   D
  1.44902431 1.00000000
H   D
  0.39472904 1.00000000
H   F
  1.44358442 1.00000000
        ''')},
ecp = {'H': gto.basis.parse_ecp('''
H nelec 0
H ul 
1  25.000000000000  1.000000000000
2   9.368618758833  -8.228005709676  
3  10.821821902641  25.000000000000 
    '''),
    'O': gto.basis.parse_ecp('''
O nelec 2
O ul
1  9.29793903   6.00000000
2  8.62925665   -38.81978498
3  8.86492204   55.78763416  
O s
2  8.71924452   38.41914135 
    '''),
    'C': 'bfd'},
    symmetry = False,
            )
mf = scf.HF(mol).run()
mycc = cc.CCSD(mf).run()
print('CCSD total energy', mycc.e_tot)
et = mycc.ccsd_t()
print('CCSD(T) total energy', mycc.e_tot + et)
mygrad = mycc.nuc_grad_method().run()
print('CCSD(T) nuclear gradients')
print(mygrad)

and this is the output:

converged SCF energy = -30.3244637083321
E(CCSD) = -31.00044843864965  E_corr = -0.6759847303174139
CCSD total energy -31.000448438649645
CCSD(T) correction = -0.0256932312492028
CCSD(T) total energy -31.02614166989885

Can you please help me?

**Comment by jamesETsmith** [comment]
@Kaminoatowo memory is likely playing a big role here. By default PySCF uses only 4 GB of memory. You can set the memory using the `max_memory` keyword when you initialize your `gto.Mole` object. See the [docs here](https://pyscf.org/user/gto.html#other-parameters) for more details.

**Comment by Kaminoatowo** [comment]
Thank you @jamesETsmith, increasing the maximum memory helped me.
