### ISSUE TITLE
Understand example 30-read_molpro_orb, how to utilize mo to do post-HF calculations

### ISSUE THREAD

**Issue by AssoliLan** [pyscf/pyscf#1616]
Hi,

  I am practicing https://github.com/pyscf/pyscf/blob/1de8c145abb3e1a7392df9118e8062e6fe6bde00/examples/gto/30-read_molpro_orb.py
  the molpro input in the docstring will generate `orb.matrop`

  I replace `            basis={'N':parse_molpro.load('path/to/molpor/basis_name.libmol', 'N')},` into `basis='ccpvdz',`
  and I got
```
[1.00130818 0.91351912 0.88206144 4.38181173 3.5835958  1.012233
 1.         1.         1.0073456  2.33337508 1.01055623 1.0073456
 2.33337508 1.01055623 1.         1.000716   1.09620128 1.26540282
 2.84680953 3.71171591 1.         1.3968978  0.87388432 2.64633764
 1.00457643 0.87388432 2.64633764 1.00457643]
```
how to proceed further, e.g., use this orbital to do a CCSD(T) calculation?

**Comment by tberkel** [comment]
The line involving `basis = ... parse_molpro ... ` is simply the
instruction to load the exact same atomic orbital basis set as used in
molpro. The following lines show how to load the molpro molecular orbital
coefficients dumped into a file `orb.matrop`.

**Comment by AssoliLan** [comment]
Thanks for your reply. Seems I need to contact my cluster administrator to see the location of molpro `.libmol` files. Looks like by using  `basis='ccpvdz'` it works. 

If this is true, may I know how to further utilize the `mo` information to do post-HF calculations?

**Comment by jamesETsmith** [comment]
It's a bit hacky, but this should work @AssoliLan:

```python
from pyscf import gto, scf, cc

mol = gto.M(atom="""O          0.00000        0.00000        0.11779
H          0.00000        0.75545       -0.47116
H          0.00000       -0.75545       -0.47116""", basis="ccpvdz", verbose=3)
mf = scf.RHF(mol).run()

fake_mf = scf.RHF(mol)
fake_mf.mo_coeff = mf.mo_coeff # Use your MOLPRO orbs here
fake_mf.mo_occ = mf.mo_occ     # Use your MOLPRO mo occupation here

mycc = cc.CCSD(fake_mf).run()
```

**Comment by AssoliLan** [comment]
Thanks a lot. I found another solution of my problem though. Let me close this issue.
