### ISSUE TITLE
Issue with 2-particle density matrix antisymmetry condition

### ISSUE THREAD

**Issue by FilipKul** [pyscf/pyscf#1618]
Hi,

I was exploring the capabilities of PySCF and I have faced the issue concerning reduced density matrix (example available at https://pyscf.org/user/ci.html FCI properties section or https://github.com/pyscf/pyscf/blob/master/examples/fci/14-density_matrix.py) that I cannot figure out. It seems that the 2-particle density matrix dm2 (obtained with `dm1, dm2 = cisolver.make_rdm12(fcivec, norb, (nelec_a,nelec_b))`) and its spin parts dm2aa and dm2bb (`(dm1a, dm1b), (dm2aa,dm2ab,dm2bb) = cisolver.make_rdm12s(fcivec, norb, (nelec_a,nelec_b))`) do not fulfill the antisymmetry condition dm2_ijkl=-dm2_jikl (in convention of i,k -> electron 1, and j,l -> electron 2) which in case of the exemplary code should be `dm2[i,k,j,l]=-dm2[j,k,i,l]`. Can you help me to figure out why? I would be very grateful for any help. 

Function reorder did not help. The symmetry conditions are fulfilled.

Below I attach the code (based on the example)
````python
import numpy
from pyscf import gto, scf, fci

mol = gto.Mole()
mol.build(
    atom = 'H 0 0 0; F 0 0 1.1',
    basis = '6-31g',
    spin = 0,
)
myhf = scf.RHF(mol)
myhf.kernel()

cisolver = fci.FCI(mol, myhf.mo_coeff)
e, fcivec = cisolver.kernel()

norb = myhf.mo_coeff.shape[1]

nelec_a = 5
nelec_b = 5

dm1, dm2 = cisolver.make_rdm12(fcivec, norb, (nelec_a,nelec_b))

(dm1a, dm1b), (dm2aa,dm2ab,dm2bb) = cisolver.make_rdm12s(fcivec, norb, (nelec_a,nelec_b))
assert(numpy.allclose(dm2aa+dm2ab+dm2ab.transpose(2,3,0,1)+dm2bb, dm2))
assert(numpy.allclose(dm1a+dm1b, dm1))

for i in range(dm2.shape[0]):
    for j in range(dm2.shape[1]):
        for k in range(dm2.shape[2]):
            for l in range(dm2.shape[3]):
                assert(numpy.allclose(dm2[i,k,j,l],dm2[k,i,l,j]))
                assert(numpy.allclose(dm2[j,k,i,l],dm2[i,l,j,k]))
                assert(numpy.allclose(dm1[i,j],dm1[j,i]))
                assert(numpy.allclose(dm2[i,k,j,l],-dm2[j,k,i,l]))
````
and the output
````python
converged SCF energy = -99.9593211672818
AssertionErrorTraceback (most recent call last)
<ipython-input-4-f94e81e0701b> in <module>
     32                 assert(numpy.allclose(dm2[j,k,i,l],dm2[i,l,j,k]))
     33                 assert(numpy.allclose(dm1[i,j],dm1[j,i]))
---> 34                 assert(numpy.allclose(dm2[i,k,j,l],-dm2[j,k,i,l]))

AssertionError:
````

**Comment by susilehtola** [comment]
The example reads
```
#
# Spin-traced 1 and 2-particle density matrices
#
dm1, dm2 = cisolver.make_rdm12(fcivec, norb, (nelec_a,nelec_b))
```
If the 2-PDM is spin-traced, then it should come as no surprise that it is not antisymmetric.

**Comment by FilipKul** [comment]
Stupid mistake :) Thank you for the answer!
