### ISSUE TITLE
How to get the Spectroscopic notation?

### ISSUE THREAD

**Issue by sunnowrun** [pyscf/pyscf#1634]
Hello, PySCF developers!
I want to get the Spectroscopic notation of a electronic state, so I need to get the expectation of state over Z component of orbital angular momentum operator.
Here in PySCF I found two intor_name seems to give me the integral over Lz operator. But I don't know the difference between 'int1e_cg_irxp' and 'int1e_giao_irjxp' [here](https://pyscf.org/pyscf_api_docs/pyscf.gto.html?highlight=intor#module-pyscf.gto.moleintor). What does rc mean in (#C(0 1) \| rc cross p\)?
And I use the mol.intor('int1e_giao_irjxp') get the Lz matrix, then use it to calculate the expectation over FCI state. But I get 0 for all the FCI states, I don't the reason, I don't why it's all 0 Lz value.
Could you help me? Thanks in advance!

**Comment by sunnowrun** [comment]
By the way, I do the calculate for simple linear molecules, such as $LiH$ $N_2$ $H_2$ in STO-3G basis

**Comment by sunqm** [comment]
cg in `int1e_cg_irxp` means common gauge. This integral should be used in your case.

**Comment by sunnowrun** [comment]
Thank you.
I used `int1e_cg_irxp` to get the `Lz` integral, and get the expectation over FCI states, and I found they're all zeros. And I found non-zero off-diagonal term between degenerate states. It seems like that FCI don't give the `Lz` eigenstates, but I can recombine these degenerate states to get `Lz` eigenstates.
Thank you for response!

**Comment by verena-neufeld** [comment]
Hi @sunnowrun , has this been answered?

**Comment by sunnowrun** [comment]
> Hi @sunnowrun , has this been answered?

**Comment by sunnowrun** [comment]
yes, solved
