### ISSUE TITLE
Potentially wrong FB cost function

### ISSUE THREAD

**Issue by wangenau** [pyscf/pyscf#1636]
While playing around with the Foster-Boys localization method I found some oddities about the cost function, i.e., the calculated orbital variances of the method.

If one does a simple calculation and prints the cost function, everything is fine at first
```python
from pyscf import dft, gto, lo

mol = gto.Mole()
mol.atom = 'Ne 0 0 0'
mol.build()
mf = dft.RKS(mol)
mf.run()

loc = lo.Boys(mol, mf.mo_coeff[:, mf.mo_occ > 0])
print(f'Orbital variances: {loc.cost_function()}')
```
with the resulting output
```bash
converged SCF energy = -126.151957753138
Orbital variances: 3.6970139543423888
```

Now, if one displaces the system one gets a completely different result, e.g., with
```python
mol.atom = 'Ne 10 0 0'

```
I get the following result
```bash
converged SCF energy = -126.151957753138
Orbital variances: -287467.0214680728
```

I would expect that the variances do not change, independent of the systems placement/orientation.
Taking a look into the code I found two possible errors that could have caused this.
1. While the dipole integral sets a charge center for the integral evaluation
https://github.com/pyscf/pyscf/blob/b6682d1877b79e28c36ea930649281ed4c2ea5ad/pyscf/lo/boys.py#L109-L112
the r2 integral can have a different center
https://github.com/pyscf/pyscf/blob/b6682d1877b79e28c36ea930649281ed4c2ea5ad/pyscf/lo/boys.py#L295
2. It appears to me that the charge center evaluation seems to be missing the weighting factor by dividing by the sum of charges
https://github.com/pyscf/pyscf/blob/b6682d1877b79e28c36ea930649281ed4c2ea5ad/pyscf/lo/boys.py#L109

I would assume that this does not affect the localization procedure, but it would be nice to display the actual orbital variances in the procedure.

I opened a pull request with my proposed changes to make it easier to see where I think something needs changing https://github.com/pyscf/pyscf/pull/1635. After applying the patch I get the same cost of the Neon calculation at the origin, independent of the displacement. The known value in test_edmiston probably needs to be changed to pass the unit test.

Best wishes,
Wanja

PS: Out of curiosity, do you know where the factor 2 comes from in the following expression? I just can't wrap my head around it.
https://github.com/pyscf/pyscf/blob/b6682d1877b79e28c36ea930649281ed4c2ea5ad/pyscf/lo/boys.py#L297

**Comment by wangenau** [comment]
After some more testing I have the feeling that something else is not yet correct since I get negative costs/variances for the localized orbitals, which should not be possible.
Here is a simple example for benzene
```python
from pyscf import dft, gto, lo

mol = gto.Mole()
mol.atom = '''
C   0.0000   1.3970   0.0000
C   1.2098   0.6985   0.0000
C   1.2098  -0.6985   0.0000
C   0.0000  -1.3970   0.0000
C  -1.2098  -0.6985   0.0000
C  -1.2098   0.6985   0.0000
H   0.0000   2.4810   0.0000
H   2.1486   1.2405   0.0000
H   2.1486  -1.2405   0.0000
H   0.0000  -2.4810   0.0000
H  -2.1486  -1.2405   0.0000
H  -2.1486   1.2405   0.0000
'''
mol.build()
mf = dft.RKS(mol)
mf.run()
```

If I calculate it with the original, unmodified cost function and localize it with
```python
loc = lo.Boys(mol, mf.mo_coeff[:, mf.mo_occ > 0])
print(f'Orbital variances (KS): {loc.cost_function()}')
loc.kernel()
print(f'Orbital variances (FB): {loc.cost_function()}')
```
I get
```bash
Orbital variances (KS): 226.32408949101406
Orbital variances (FB): -136.45047273487967
```
Here, the localized FB orbitals give a negative variance. The modified version will give the same result since the charge center is at the origin.

And for completion, if I displace the molecule with z+=1 I get
```bash
Original:
Orbital variances (KS): -251823.00238479354
Orbital variances (FB): -252185.77694701956
Modified:
Orbital variances (KS): 226.32408949101364
Orbital variances (FB): -136.4504727349132
```

**Comment by wangenau** [comment]
After trying to compare the cost function with different implementations I was able to calculate some similar values with ERKALE. After comparing the cost functions from both codes, it seems that the factor 2 from
https://github.com/pyscf/pyscf/blob/b6682d1877b79e28c36ea930649281ed4c2ea5ad/pyscf/lo/boys.py#L297
produces a difference between both codes. Removing it will give basically the same results between ERKALE and PySCF, and the orbital variances are also positive definite.

For the same benzene geometry as above I get the following results
| | ERKALE  | PySCF (fix) | PySCF (old) |
| -| -: | -: | -: |
| Energy | -227.26285  |-227.26291 | -227.26291 |
| J_FB| 44.93676 | 44.93691 | -136.45020 |

Because of this, I think the factor 2 should be removed. Also, I updated my PR accordingly: https://github.com/pyscf/pyscf/pull/1635.

For posterity, here are my ERKALE input scripts for the SCF
```bash
System benzene.xyz
Method lda_x-lda_c_vwn
Basis STO-3G
Guess Core
SaveChk run.chk
```
and the localization
```bash
LoadChk run.chk
Method FB
```
The PySCF calculation is the same as above, while using the same grid settings as ERKALE, by setting
```python
mf.grids.atom_grid = (50, 194)
```

**Comment by sunqm** [comment]
Thanks for debugging the code. The incorrect factor 2 was accidentally added long time ago. It was `(r2 - np.einsum('xii,xii', dip, cip) * 2` and the parenthesis was removed in a commit. Your version is correct. Thank you for fixing this bug in PR #1635.
