### ISSUE TITLE
How to compute the IP,EA,EE of 2-D MoS2

### ISSUE THREAD

**Issue by taoyx23** [pyscf/pyscf#1637]
Hi, pyscf developers,

I have some problem when using eom_kccsd_rhf.EOMEESinglet, eom_kccsd_rhf.EOMEA and eom_kccsd_rhf.EOMIP to compute the energy of EE, EA and IP of 2-D MoS2. I use basis "gth-dzvp-molopt-sr" and pseudo "gth-pade", and use LUMO and HOMO orbitals as active space. The kshift is [1/3, 1/3, 0].

When k-grid is 3 * 3 * 1, the value of LUMO - HOMO obtained from RHF is 7.39eV, and the values of EE energy and IP - EA are 2.94eV and 3.50eV, respectively. When k-grid is 6 * 6 * 1, these three values are 5.85eV, 3.68eV, 7.28eV. The 5.85eV of LUMO - LUMO is agree with the results of QE and FHI-aims. However, the results of EE and IP - EA are both too large, which should be around 2.0eV. And it seems that the larger k-grid, the worse the results.

The following is the input file, and hope to get your help, thank you very much.
```
import numpy as np
import pyscf
from pyscf.pbc import gto, scf, cc
from pyscf.pbc.cc import eom_kccsd_rhf

geometry = [
        ["Mo", [0.000004452, 1.834413215, 15.000000000]],
        ["S", [1.588648350, 0.917206443, 16.564816833]],
        ["S", [1.588648350, 0.917206443, 13.435182273]],
    ]
lattice_vec = [
        [3.1772919094252723, 0.0000039897606482, 0.0],
        [-1.5886424985939058, 2.7516174959332282, 0.0],
        [0.0, 0.0, 30.0],
    ]

cell = gto.Cell()
cell.dimension = 2
cell.atom = geometry
cell.a = lattice_vec
cell.basis = "gth-dzvp-molopt-sr"
cell.pseudo = "gth-pade"
cell.exp_to_discard = 0.1
cell.verbose = 4
cell.build()

n_orb_mo = cell.nao_nr()
n_orb_occ_mo = sum(cell.nelec) // 2
nk = [6,6,1]
kshift = [1/3, 1/3, 0]
kpts = cell.make_kpts(nk,scaled_center=kshift)
# KRHF
kmf = scf.KRHF(cell, kpts).density_fit()
print("Running KRHF...")
energy_KRHF = kmf.kernel()
# frozen mo orbitals unitcell
act_mo_orb = [1, 1]
frozen_list = [i for i in range(n_orb_occ_mo - act_mo_orb[0])] + \
                  [i for i in range(n_orb_occ_mo + act_mo_orb[1], n_orb_mo)]
act_list = [i for i in range(n_orb_occ_mo - act_mo_orb[0], n_orb_occ_mo + act_mo_orb[1])]
print("Active space (mo) =", act_list)
# KCCSD
kmf_cc = cc.KCCSD(kmf, frozen=frozen_list)
print("Running KCCSD...")
e_corr, t1, t2 = kmf_cc.kernel()
num_roots = 5
# EOM-EE-KCCSD
kmf_eomee = eom_kccsd_rhf.EOMEESinglet(kmf_cc)
print("Running EOMEE...")
eee, vee = kmf_eomee.kernel(nroots = num_roots)
#EOM-EA-KCCSD
kmf_eomea = eom_kccsd_rhf.EOMEA(kmf_cc)
print("Running EOMEA...")
eea, vea = kmf_eomea.kernel(nroots = num_roots)
#EOM-IP-KCCSD
kmf_eomip = eom_kccsd_rhf.EOMIP(kmf_cc)
print("Running EOMIP...")
eip, vip = kmf_eomip.kernel(nroots = num_roots)
```

**Comment by taoyx23** [comment]
Thanks for your attention. I'm going to apply a larger active space.

**Comment by tberkel** [comment]
This paper might help you benchmark your IP-EA calculations on MoS2:
https://journals.aps.org/prb/abstract/10.1103/PhysRevB.101.241113

**Comment by verena-neufeld** [comment]
Hi @taoyx23 , has this been answered?

**Comment by sunqm** [comment]
This discussion has been quiet for a while, so I’ll go ahead and close it. If you need to revisit the issue, feel free to reopen it.
