### ISSUE TITLE
Calculating One-Index Hartree Potential with PySCF

### ISSUE THREAD

**Issue by stefanvuckovic1** [pyscf/pyscf#1649]
Dear PySCF developers,

I'm trying to calculate the electrostatic (Hartree) potential corresponding to a single (auxiliary) GTO:

$$v_i({\bf r}) = \int d{\bf r}_2~ \frac{\phi_i ({\bf r}_2)}{r_{12}}$$

[Please note that $\phi_i$ is not squared]. I need this object to simplify the evaluation of my density functional.

I have been using the 'fake_mol' delta function trick to calculate the Hartree potential over two GTOs:

$$v_{ij}({\bf r})= \int d{\bf r}_2 \frac{\phi_i({\bf r}_2) \phi_j({\bf r}_2)}{r_{12}}$$

by using this code:
```
from pyscf import gto, scf, dft, lib, ao2mo
from pyscf import df, lib
import numpy as np
mol = gto.M(atom = 'Ne 0.00 0.000 0.00')
mol.basis = 'def2tzvp'
mol.cart = True
mol.build()
mf = dft.RKS(mol).density_fit()
mf.run()
Amol = df.addons.make_auxmol(mol, 'def2tzvpjkfit')


coords = mf.grids.coords #coordinates on a grid
fakemol = gto.fakemol_for_charges(coords);
v_ij = df.incore.aux_e2(Amol, fakemol);
```

v_ij[i, j, p] represents:

$$v_{ij}(r_1) = \int d{\bf r}_2 \frac{\phi_i({\bf r}_2) \phi_j({\bf r}_2)}{r_{12}}$$ 

at r_1 = coords[p] and thus is of shape (naux, naux, len(coords)).

However, I would like to calculate 

$$v_i ({\bf r_1} )= \int d{\bf r}_2 \frac{\phi_i({\bf r}_2)}{r_{12}}$$

at r_1 = coords[p]. Since $\phi_i$ is not squared, this object is not just v_ij [i, i,p] 
Any ideas on how can I achieve this with PySCF?

**Comment by sunqm** [comment]
```
mol1 = fakemol + Amol
mat = mol1.intor('int2c2e', shls_slice=(0,fakemol.nbas,fakemol.nbas,mol1.nbas))
```

**Comment by verena-neufeld** [comment]
Hi @stefanvuckovic1 , has this been answered?
