### ISSUE TITLE
rys_root fail for heavy element containing system when contracted basis is used for light element

### ISSUE THREAD

**Issue by xubwa** [pyscf/pyscf#1657]
I'm not sure whether it's better to put this issue here or libcint, since it's an error from libcint/src/rys_root.c. Below is a minimal example that can reproduce the problem
```
from pyscf import gto, scf, dft

mol = gto.M(atom='''Hg 0 0 0;
Cl 2.278334 0 0;
Cl -2.278334 0 0;
''',
symmetry=False,
verbose=4,
basis={'Hg':'dyallv3z','Cl':'ccpvtzdk'})

mf = dft.RKS(mol,'m06l')
mf.kernel()
```
During each scf iteration, a good amount of error information like this 
```ROOT NUMBER 1 WAS NOT FOUND FOR POLYNOMIAL OF ORDER 4
rys_roots fails: nroots=6 x=1.06795e+37
```
was thrown, and if I switch the basis set for chlorine to a `unc-ccpvtzdk` which is merely the original basis set's uncontracted version, the problem went away. Is there a good reason why this happen?

**Comment by xubwa** [comment]
I recompiled everything on the master branch，this error information is introduced on a Feb 10th commit of libcint.
________________________________

**Comment by sunqm** [comment]
This warning exists in all versions. It should have negligible impacts on the integral accuracy. In libcint 5.2.0, I added more checks and dumped the error messages. You can ignore the warnings and keep running your calculations. This warning will be properly handled in future libcint releases.

**Comment by xubwa** [comment]
Good to know that, thanks qiming!
