### ISSUE TITLE
Installation question: error: call to 'cbrt' is ambiguous

### ISSUE THREAD

**Issue by TariniHardikar** [pyscf/pyscf#166]
Hello!

I'm trying to build pyscf on a MacOS, with Clang as my C/CXX compilers and gfortran as my fortran compiler. I get the error that "call to 'cbrt' is ambiguous" when I run ``make``. ``cmake ..`` runs okay. I have attached a screenshot of the error which shows all the instances of 'cbrt' being called.

I really appreciate suggestions!
![screen shot 2018-03-13 at 16 03 00](https://user-images.githubusercontent.com/9437433/37366957-6377b982-26d8-11e8-8141-f184ee0fcfcb.png)

Thanks!

**Comment by tberkel** [comment]
Please see our recently closed issue #158 -- this has to do with the xcfun library, and the linked discussion includes some temporary solutions.
