### ISSUE TITLE
Example scf/05-breit_gaunt.py and scf/04-dirac_hf.py fail due to AttributeError

### ISSUE THREAD

**Issue by verena-neufeld** [pyscf/pyscf#1663]
`AttributeError: module 'pyscf.gto' has no attribute 'uncontract_basis'`

I think in commit 4175ad4f6035ea00e0b11573231ece149812b7cc the name was changed to `uncontracted_basis`?

**Comment by verena-neufeld** [comment]
Thanks, scf/05-breit_gaunt.py is fixed. I guess the fix for scf/04-dirac_hf.py looks the same?

**Comment by sunqm** [comment]
Thanks for checking the examples and fixing the example. Yes, the example for briet Hamiltonian got the similar problem as diract_hf.py.
