### ISSUE TITLE
Memory management for ERIs

### ISSUE THREAD

**Issue by manassharma07** [pyscf/pyscf#1667]
How does PySCF manage the memory for ERIs evaluation for DFT calculations?

When I run a DFT calculation with `PYSCF_MAX_MEMORY` environment variable set to 120Gigs, and `direct_scf=False` , the calculation crashes if the integrals are still too big to fit in 120 Gigs of Memory. If I set `direct_scf=True`, then PySCF hardly uses any of the 120 Gigs of the memory (it barely uses 1-2 Gigs). 

Is it not possible for PySCF to make use of some amount of memory to avoid recalculating the integrals again at each iteration in the case of `direct_scf`? 

Here is the code I am using:
```
import os
# Set the max memory for PySCF
os.environ["PYSCF_MAX_MEMORY"] = str(120000)

from pyscf import gto, dft

#LDA
funcx = 1
funcc = 7
funcidpyscf = str(funcx)+','+str(funcc)

basis_set_name = 'def2-SVP'

xyzFilename = 'Tetracontane_C40H82.xyz'

# ---------PySCF---------------
molPySCF = gto.Mole()
molPySCF.atom = xyzFilename
molPySCF.basis = basis_set_name
molPySCF.cart = True
# molPySCF.incore_anyway = True # Keeps the PySCF ERI integrals incore
molPySCF.build()
#print(molPySCF.cart_labels())

print('\n\nPySCF Results\n\n')
mf = dft.RKS(molPySCF)
mf.xc = funcidpyscf
mf.verbose = 4
mf.direct_scf = True
mf.init_guess = 'minao'
dmat_init = mf.init_guess_by_minao(molPySCF)
mf.max_cycle = 30
mf.conv_tol = 1e-7
mf.grids.level = 5
energyPyscf = mf.kernel(dm0=dmat_init)
print('Nuc-Nuc PySCF= ', molPySCF.energy_nuc())
print('One electron integrals energy',mf.scf_summary['e1'])
print('Coulomb energy ',mf.scf_summary['coul'])
print('EXC ',mf.scf_summary['exc'])
```

**Comment by fishjojo** [comment]
Without AO direct algorithm, the memory cost is roughly N^4/8*8/1e9 Gb, where N is the number of AOs. If you have enough memory, you can try that. Otherwise, the AO direct algorithm is needed to perform the SCF calculation. Or you may also try density fitting.

**Comment by manassharma07** [comment]
Yeah, this is what I noticed too. It would have been better if PySCF could do a hybrid of the two approaches. That is, keep some portion of the integrals (as permitted by the max memory) in memory and only recalculate the remaining integrals. Otherwise, we are not making use of the hardware available to us with the current all-or-nothing approach. 

Since you mention density fitting. I noticed that when using density fitting, the `direct_scf=False` doesn't make any difference. It basically takes as long as `direct_scf=True` and also doesn't seem to take advantage of the available memory even if all the integrals can be fit into the memory.

**Comment by xubwa** [comment]
In density fitty, whether incore or outcore algorithm is used is triggered by a variable "df_outcore_max_memory" and is controlled via the config file. You may have a look at this line https://github.com/pyscf/pyscf/blob/4a4b9e2173b523649c854acc3ab51b7829feb7f5/pyscf/df/incore.py#L30

**Comment by manassharma07** [comment]
@xubwa Thanks! I just tried this, however, it doesn't make any difference in the memory used or time taken either. 

Furthermore, I went ahead and tried to use the precomputed 3c2e integrals based on this example (https://github.com/pyscf/pyscf/blob/master/examples/df/40-precompute_df_integrals.py) https://github.com/pyscf/pyscf/blob/4a4b9e2173b523649c854acc3ab51b7829feb7f5/examples/df/40-precompute_df_integrals.py#L49

I used the following script:

```
import os
# Set the max memory for PySCF
os.environ["PYSCF_MAX_MEMORY"] = str(25000)

from pyscf import gto, dft

#LDA
funcx = 1
funcc = 7
funcidpyscf = str(funcx)+','+str(funcc)

basis_set_name = 'def2-SVP'

xyzFilename = 'Icosane_C20H42.xyz'

# ---------PySCF---------------
molPySCF = gto.Mole()
molPySCF.atom = xyzFilename
molPySCF.basis = basis_set_name
molPySCF.cart = True
# molPySCF.incore_anyway = True # Keeps the PySCF ERI integrals incore
molPySCF.build()
#print(molPySCF.cart_labels())

print('\n\nPySCF Results\n\n')
mf = dft.RKS(molPySCF)
mf.xc = funcidpyscf
mf.verbose = 4
mf.direct_scf = False
mf.with_df.max_memory = 25000
# Calculate 3c2e integrals before hand
int3c = df.incore.cholesky_eri(molPySCF, auxbasis=auxbasis_pyscf)
print('Size of 3c2e ERIs in GB: ', int3c.nbytes/1e9)
# Use the pre-calculated 3c2e ERIs
mf.with_df._cderi = int3c
mf.init_guess = 'minao'
dmat_init = mf.init_guess_by_minao(molPySCF)
mf.max_cycle = 30
mf.conv_tol = 1e-7
mf.grids.level = 5
energyPyscf = mf.kernel(dm0=dmat_init)
print('Nuc-Nuc PySCF= ', molPySCF.energy_nuc())
print('One electron integrals energy',mf.scf_summary['e1'])
print('Coulomb energy ',mf.scf_summary['coul'])
print('EXC ',mf.scf_summary['exc'])
```

With the above script, I noticed that while calculating int3c it takes up a good amount of memory as expected. For example, the final array for the Icosane alkane should be around 1.7 Gigs. So during the calculation of int3c it temporarily takes around 2x of that value which is expected and mentioned in the source code. Then the final array is around 1.7 Gigs. 

However, using this precomputed int3c array makes no difference to the final DFT calculation time. It still takes the same amount of time. This makes me wonder if it is the density fitting procedure that is the bottle neck here or there is a bug somewhere.

**Comment by manassharma07** [comment]
Okay, so I finally found the reason why DF was not making use of the available memory. 
I needed to add `mf.with_df.build()` before `mf.kernel()`.

With this change, the memory consumption seems to be as expected (provided `PYSCF_MAX_MEMORY` is high enough to accommodate them). 

Surprisingly, now I don't even need to specify the max memory for df via the config file or `mf.with_df.max_memory`.

I still wonder as to why I need to do `mf.with_df.build()` for the proper memory utilization? Is it a bug @fishjojo ? since none of the examples show this.

**Comment by manassharma07** [comment]
Unfortunately, despite storing the `cderi `in memory (as reflected by the memory consumption) there is a very small gain in the performance. I am gaining hardly 20 seconds, which is strange as the time taken by `mf.with_df.build()` is around 40 seconds for tetracontane (basis: def2-SVP, auxbasis: weigend). Not sure what is the issue anymore :(

**Comment by xubwa** [comment]
In density fitting, if the 3c2e array does not fit in memory, then it will be stored on disk. Thus the amount you save is just the io time, not the time consumed by `mf.with_df.build()`.

**Comment by manassharma07** [comment]
But like I said, I have 120 Gigs memory. The 3c2e array needed 13 Gigs in one of the cases I mentioned. Yet the memory usage was  just 1-2 Gigs even though I had set the max memory. Why is that the case? Only when I included mf.with_df.build() was the memory usage as expected.

**Comment by manassharma07** [comment]
Here is the XYZ file for the script I originally provided. You can check that it does not use 13 Gigs of memory even if you have more than double of the required memory (in my case 120 GB).

```122

C40H82
 C   -0.624000   -0.442600    0.000000
 C   -1.874500    0.438900    0.000000
 C   -3.122400   -0.446400    0.000000
 C   -4.373000    0.435100    0.000000
 C   -5.620900   -0.450100    0.000000
 C   -6.871500    0.431400    0.000000
 C   -8.119400   -0.453900    0.000000
 C   -9.370000    0.427600    0.000000
 C  -10.617900   -0.457600    0.000000
 C  -11.868400    0.423800    0.000000
 C  -13.116300   -0.461400    0.000000
 C  -14.366900    0.420100    0.000000
 C  -15.614800   -0.465100    0.000000
 C  -16.865400    0.416300    0.000000
 C  -18.113300   -0.468900    0.000000
 C  -19.363899    0.412600    0.000000
 C  -20.611799   -0.472600    0.000000
 C  -21.862301    0.408800    0.000000
 C  -23.110201   -0.476400    0.000000
 C  -24.360800    0.405100    0.000000
 C    0.624000    0.442600    0.000000
 C    1.874500   -0.438900    0.000000
 C    3.122400    0.446400    0.000000
 C    4.373000   -0.435100    0.000000
 C    5.620900    0.450100    0.000000
 C    6.871500   -0.431400    0.000000
 C    8.119400    0.453900    0.000000
 C    9.370000   -0.427600    0.000000
 C   10.617900    0.457600    0.000000
 C   11.868400   -0.423800    0.000000
 C   13.116300    0.461400    0.000000
 C   14.366900   -0.420100    0.000000
 C   15.614800    0.465100    0.000000
 C   16.865400   -0.416300    0.000000
 C   18.113300    0.468900    0.000000
 C   19.363899   -0.412600    0.000000
 C   20.611799    0.472600    0.000000
 C   21.862301   -0.408800    0.000000
 C   23.110201    0.476400    0.000000
 C   24.360800   -0.405100    0.000000
 H   -0.623000   -1.071900    0.890000
 H   -0.623000   -1.071900   -0.890000
 H   -1.875500    1.068200    0.890000
 H   -1.875500    1.068200   -0.890000
 H   -3.121500   -1.075700   -0.890000
 H   -3.121500   -1.075700    0.890000
 H   -4.373900    1.064400    0.890000
 H   -4.373900    1.064400   -0.890000
 H   -5.620000   -1.079400   -0.890000
 H   -5.620000   -1.079400    0.890000
 H   -6.872400    1.060700    0.890000
 H   -6.872400    1.060700   -0.890000
 H   -8.118400   -1.083200   -0.890000
 H   -8.118400   -1.083200    0.890000
 H   -9.370900    1.056900    0.890000
 H   -9.370900    1.056900   -0.890000
 H  -10.616900   -1.086900   -0.890000
 H  -10.616900   -1.086900    0.890000
 H  -11.869400    1.053200    0.890000
 H  -11.869400    1.053200   -0.890000
 H  -13.115400   -1.090700   -0.890000
 H  -13.115400   -1.090700    0.890000
 H  -14.367800    1.049400    0.890000
 H  -14.367800    1.049400   -0.890000
 H  -15.613900   -1.094400   -0.890000
 H  -15.613900   -1.094400    0.890000
 H  -16.866301    1.045600    0.890000
 H  -16.866301    1.045600   -0.890000
 H  -18.112301   -1.098200   -0.890000
 H  -18.112301   -1.098200    0.890000
 H  -19.364799    1.041900    0.890000
 H  -19.364799    1.041900   -0.890000
 H  -20.610800   -1.102000   -0.890000
 H  -20.610800   -1.101900    0.890000
 H  -21.863300    1.038100    0.890000
 H  -21.863300    1.038100   -0.890000
 H  -23.109301   -1.105700   -0.890000
 H  -23.109301   -1.105700    0.890000
 H  -24.361799    1.034400    0.890000
 H  -24.361799    1.034400   -0.890000
 H  -25.249800   -0.225600    0.000000
 H    0.623000    1.071900   -0.890000
 H    0.623000    1.071900    0.890000
 H    1.875500   -1.068200    0.890000
 H    1.875500   -1.068200   -0.890000
 H    3.121500    1.075700   -0.890000
 H    3.121500    1.075700    0.890000
 H    4.373900   -1.064400    0.890000
 H    4.373900   -1.064400   -0.890000
 H    5.620000    1.079400   -0.890000
 H    5.620000    1.079400    0.890000
 H    6.872400   -1.060700    0.890000
 H    6.872400   -1.060700   -0.890000
 H    8.118400    1.083200   -0.890000
 H    8.118400    1.083200    0.890000
 H    9.370900   -1.056900    0.890000
 H    9.370900   -1.056900   -0.890000
 H   10.616900    1.086900   -0.890000
 H   10.616900    1.086900    0.890000
 H   11.869400   -1.053200    0.890000
 H   11.869400   -1.053200   -0.890000
 H   13.115400    1.090700   -0.890000
 H   13.115400    1.090700    0.890000
 H   14.367800   -1.049400    0.890000
 H   14.367800   -1.049400   -0.890000
 H   15.613900    1.094400   -0.890000
 H   15.613900    1.094400    0.890000
 H   16.866301   -1.045600    0.890000
 H   16.866301   -1.045600   -0.890000
 H   18.112301    1.098200   -0.890000
 H   18.112301    1.098200    0.890000
 H   19.364799   -1.041900    0.890000
 H   19.364799   -1.041900   -0.890000
 H   20.610800    1.102000   -0.890000
 H   20.610800    1.101900    0.890000
 H   21.863300   -1.038100    0.890000
 H   21.863300   -1.038100   -0.890000
 H   23.109301    1.105700   -0.890000
 H   23.109301    1.105700    0.890000
 H   24.361799   -1.034400    0.890000
 H   24.361799   -1.034400   -0.890000
 H   25.249800    0.225600    0.000000
```

**Comment by xubwa** [comment]
After going over your input and going through the pyscf density fitting module, what I said about the density fitting max memory to be only 2000MB was wrong.  You just need to specify the max_memory when you are constructing the molecule. The way you set the PYSCF_MAX_MEMORY through os.environ is indeed wrong, this variable is read from the pyscf config file as described here
> PYSCF_CONFIG_FILE is a Python file that can be used to predefine and override several default parameters in the program: you may already have noticed statements like getattr(__config__, “FOOBAR”) many places in the source code. These global parameters are defined in PYSCF_CONFIG_FILE and loaded when the pyscf module is imported. By default, this environment variable points to ~/.pyscf_conf.py
So in your case, your calculation is still only set up to use 4000MB of memory by default. If you set the mol.max_memory to close to your system memory, then you should observe some difference in memory usage even without the complicated df build thing,

**Comment by xubwa** [comment]
I did and it was as expected using around 20gb of memory.
________________________________

**Comment by manassharma07** [comment]
PS: Even if I don't set `mol.max_memory`, the output shows this

`max_memory 120000 MB (current use 223 MB)`

> I did and it was as expected using around 20gb of memory.

But I really don't understand, why the memory usage is not correct for me. Perhaps it is due to how I install it. I install it via pip.

Thanks for your help debugging anyway! @xubwa 
I just wish I could solve this issue.

**Comment by xubwa** [comment]
That current use is before any integral is constructed, you should top it to see the actual memory usage during your calculation or set verbose to 5, and whether density fitting construction of jk is split into several steps can give you an idea whether it's incore or outcore.
________________________________

**Comment by verena-neufeld** [comment]
Hi @manassharma07 , thanks for your questions! Have they been answered and can the issue be closed?
