### ISSUE TITLE
Computing variance and higher (raw) moments of PySCF FCI wavefunctions

### ISSUE THREAD

**Issue by Chiffafox** [pyscf/pyscf#1669]
Is it possible to natively calculate (raw) moments or cumulants of FCI wavefunctions in PySCF? After consulting the documentation and surveying the available methods in the package, I could not find a method of doing so, but perhaps I missed it.

The wavefunction for FCI / CASCI calculations is returned as a 2D array with CI coefficients arranged in a particular pattern corresponding to cistring-based ordered excitations (others, such as CISD / CCSD ones could also be brought to this form). Presumably there are also tools to build the Hamiltonian matrix, although I could not locate those explicitly. 

Would computing the moments be then a matter of doing some kind of dot product psi @ H^k psi, minding the alpha/beta rostering of the CI coefficients?

The use case is to compare the energy probability distributions corresponding to states obtained from various methods -- one way to characterize the energy probability distribution without computing the entire thing directly is to look at <H^k>-like moments.

**Comment by obackhouse** [comment]
It is definitely possible, I have a snippet to do this [here](https://gist.github.com/obackhouse/49fd802e63590a79ba9d8e25d5950c52) which calculates the hole and particle moments for a restricted reference using PySCF.

My package [dyson](https://github.com/BoothGroup/dyson) includes this functionality, though I have only just added it, so I have no examples or tests yet - your use case sounds very relevant to the solvers I work on in this code.

**Comment by Chiffafox** [comment]
Thanks so much @obackhouse, I took a look and indeed it looks very relevant! Just a couple of follow-up questions

- Are moments available for any k? In your `fci_moments` routine it seems like the loop over moments is in `apply_hamiltonian`, correct?
-  In the code snippet you linked, you are interested in Green's functions and so your `ci_vecs` has length $= N_{\text{orb}}$. In general, `ci_vecs` could be quite long, depending on the number of determinants in the $N$-electron wavefunction -- it has length = $N_{\text{orb}}$ choose $N_{\text{elec}}$. Do you think the code could handle something like H2 / H4 in the cc-PVDZ basis (5 orbitals per H atom)?

**Comment by verena-neufeld** [comment]
Hi @Chiffafox , has this been answered?

**Comment by sunqm** [comment]
Thanks @obackhouse for implementing this functionality. I’ll go ahead and close it. Feel free to reopen the issue if needed.
