### ISSUE TITLE
No x86_64 wheel for Python 3.11 for `pyscf==2.2.0`

### ISSUE THREAD

**Issue by sphuber** [pyscf/pyscf#1671]
`pyscf==2.2.0` provides wheels for generic Linux x86_64 for Python 3.6 through Python 3.10, but for Python 3.11 only the archlinux wheel is provided (see https://pypi.org/project/pyscf/2.2.0/#files). Is there a particular reason for this? Would it be possible to add the generic Linux wheel?

**Comment by sunqm** [comment]
pyscf-2.2.1 provided a wheel for python 3.11

**Comment by sphuber** [comment]
Fantastic, thanks a lot
