### ISSUE TITLE
UHF solution for fixed spin

### ISSUE THREAD

**Issue by ghost** [pyscf/pyscf#1698]
Hello,

I know that for the FCI it is possible to find the minimum energy while fixing or freezing the spin. Is it possible to do the same for a UHF calculation? 

I'm interested in studying the dissociation of H2 for a fixed spin component. Thank you.

**Comment by susilehtola** [comment]
I don't think so, since UHF does not give a spin eigenfunction.

**Comment by JJJuanjo** [comment]
> I don't think so, since UHF does not give a spin eigenfunction.

@susilehtola thank you for your reply. That makes sense. I'm trying to calculate the lowest energy singlet state for the hydrogen molecule beyond the CF point using a non-orthogonal configuration. I would appreciate any guidance

**Comment by mkrompiec** [comment]
A fixed-spin UHF is R(O)HF, isn't it? See https://doi.org/10.1002/qua.560460502

**Comment by susilehtola** [comment]
Yes, the only way to maintain a singlet state in a one-determinant picture is to employ RHF, which gives you a spin eigenfunction.

**Comment by verena-neufeld** [comment]
Hi @JJJuanjo , does this answer your question?

**Comment by sunqm** [comment]
This discussion has been inactive for a while, so I’ll close it. Feel free to reopen the issue.
