### ISSUE TITLE
A question about parallelization techniques in PySCF

### ISSUE THREAD

**Issue by AssoliLan** [pyscf/pyscf#1701]
Hi,
 
  I found `PySCF` used `mpi4py` techniques for parallelization. I am very new to this technique. I did not find any specific syntax like `openmp` on loop in e.g., https://pyscf.org/_modules/pyscf/mp/mp2.html   For example, in blas ~ einsum, I may choose split row/column of matrix to given threads. 
  Does `mpi4py` do everything automatically? (I checked https://mpi4py.readthedocs.io/en/stable/tutorial.html, it looks complicated), though this is not an issue strictly speaking

**Comment by shivupa** [comment]
This was split out to https://github.com/pyscf/mpi4pyscf
