### ISSUE TITLE
MO values at particular points

### ISSUE THREAD

**Issue by FilipKul** [pyscf/pyscf#1710]
Hi,

I'm performing FCI calculations with PySCF and I was wondering whether there is a possibility to obtain the values of molecular orbitals at particular point?
It would also be very useful for me to get 1- and 2-RDMs expressed in natural orbitals. 
I would be very grateful for any suggestions and clues.

**Comment by fishjojo** [comment]
What kind of point are you referring to? If it is about MOs evaluated on grid points, you could try `gto.eval_ao` to compute the AOs' value on the grid and then contract it with MO coefficients.
RMDs in natural orbitals can be obtained by a unitary transformation from the RDMs in canonical orbitals.

**Comment by FilipKul** [comment]
> If it is about MOs evaluated on grid points, you could try `gto.eval_ao` to compute the AOs' value on the grid and then contract it with MO coefficients.

This may do the trick, thank you a lot! I will check it out as soon as possible (I am a bit busy right now - sorry) and close the topic.

**Comment by fishjojo** [comment]
They are the same function...
