### ISSUE TITLE
[Question] CISD root energies depend on number of roots 

### ISSUE THREAD

**Issue by davidsousarj** [pyscf/pyscf#1713]
Hi. I am trying to perform CISD calculations using PySCF. However I have realized that the CISD eigenvalues (roots) are different depending on the maximum number of roots you set in the program. For example, for the water molecule:
```
>>> import pyscf
>>> import pyscf.ci
>>> mol = pyscf.gto.M(atom="O  0.  0.  0.; H  0.7586  0.  0.5043; H  0.7586  0.  -0.5043", basis='ccpvdz', unit='A')
>>> mf = pyscf.scf.RHF(mol)
>>> mf.kernel()
converged SCF energy = -75.9735547152141
-75.97355471521414
>>> cisolver = pyscf.ci.CISD(mf)
>>> cisolver.kernel()
E(RCISD) = -76.18002490695925  E_corr = -0.2064701917451073
...
>>> len(cisolver.ci)
9121
>>> cisolver.nroots=2
>>> cisolver.kernel()
RCISD root 0  E = -76.18002490693753
*RCISD root 1  E = -75.75577941455246*
...
>>> cisolver.nroots=10
>>> cisolver.kernel()
RCISD root 0  E = -76.18002484762471
RCISD root 1  E = -76.09494286359235
RCISD root 2  E = -76.01690057780159
RCISD root 3  E = -75.98256091537711
RCISD root 4  E = -75.97379231235347
RCISD root 5  E = -75.96085798744552
RCISD root 6  E = -75.75577941456064
RCISD root 7  E = -75.65203146458322
RCISD root 8  E = -75.60210800798626
RCISD root 9  E = -75.54948934267235
...
>>> cisolver.nroots=30
>>> cisolver.kernel()
RCISD root 0  E = -76.1812715139815
RCISD root 1  E = -76.14771261428022
RCISD root 2  E = -76.07773950112671
RCISD root 3  E = -76.02974007125015
RCISD root 4  E = -76.02560566675831
RCISD root 5  E = -75.98894312911897
RCISD root 6  E = -75.98865280776617
RCISD root 7  E = -75.97545188894506
RCISD root 8  E = -75.97523657954764
RCISD root 9  E = -75.97364038222931
...
```

My question is why changing the number of roots changes the values of the roots themselves. In my understanding, the CI hamiltonian matrix has the same size independently of the value of `cisolver.nroots`. If the CI expansions has N determinants, the CI matrix will be N x N and it will have N eigenvalues. If I want to know the first 10 or the first 30 eigenvalues, those values should not be different.

**Comment by jamesETsmith** [comment]
@davidsousarj CISD (and many other chemistry methods) use Davidson's method to iteratively diagonalize the CISD hamiltonian. This means that it's approximate and eigenvalues can change depending on how many "trial vectors" you use during the algorithm (which is related to how many roots you want). 
Some quick background on Davidson's method:
- https://mattermodeling.stackexchange.com/questions/6563/what-are-the-advantages-of-the-davidson-diagonalization-method-over-other-sparse
- https://gqcg-res.github.io/knowdes/the-davidson-diagonalization-method.html

For a more comprehensive discussion see section 3.2.1 in [The Configuration Interaction Method: Advances in Highly Correlated Approaches](https://www.sciencedirect.com/science/article/abs/pii/S0065327608605328)

That said, something else is probably going on because the eigenvalues shouldn't be changing as much as what you're seeing. My guess is that it's something with the basis set, `cc-pVDZ` is probably not the best for this problem since you're not doing frozen core. A brief test with `def2svp` and `def2tzvp` show a lot less instability.

**Comment by davidsousarj** [comment]
Thank you, @jamesETsmith !

**Comment by davidsousarj** [comment]
By changing basis to `def2svp` and keeping 1 MO frozen I still get a considerable difference in the roots:

`nroots=1`:

`E(RCISD) = -76.11155492151835`

`nroots=2`:

```
RCISD root 0  E = -76.11155492149641
RCISD root 1  E = -75.68947629643735
```
`nroots=10`:

```
RCISD root 0  E = -76.11155492090644
RCISD root 1  E = -75.97346995979132
RCISD root 2  E = -75.94506406685697
RCISD root 3  E = -75.93360232589821
RCISD root 4  E = -75.90837407755912
RCISD root 5  E = -75.68947629643127
RCISD root 6  E = -75.58294059985093
RCISD root 7  E = -75.53791405965974
RCISD root 8  E = -75.483284887775
RCISD root 9  E = -75.41088910248848
```
`nroots=30`:

```
RCISD root 0  E = -76.11155492176937
RCISD root 1  E = -75.96495268554071
RCISD root 2  E = -75.95043598425397
RCISD root 3  E = -75.94959853933695
RCISD root 4  E = -75.92820163867768
RCISD root 5  E = -75.91837173495959
RCISD root 6  E = -75.90957111723139
RCISD root 7  E = -75.90850265757679
RCISD root 8  E = -75.90842209958664
RCISD root 9  E = -75.90819719886278
RCISD root 10  E = -75.90748116602069
RCISD root 11  E = -75.90747408664689
RCISD root 12  E = -75.90747173709151
RCISD root 13  E = -75.90746886801439
RCISD root 14  E = -75.90725824854336
RCISD root 15  E = -75.90649664920682
RCISD root 16  E = -75.90544838029862
RCISD root 17  E = -75.904793754121
RCISD root 18  E = -75.90178322833893
RCISD root 19  E = -75.90045358521009
RCISD root 20  E = -75.90004693996026
RCISD root 21  E = -75.88910605464402
RCISD root 22  E = -75.65890171903727
RCISD root 23  E = -75.57825364840554
RCISD root 24  E = -75.52967410070447
RCISD root 25  E = -75.50880571349985
RCISD root 26  E = -75.40656007771749
RCISD root 27  E = -75.37702456615862
RCISD root 28  E = -75.1915898053975
RCISD root 29  E = -75.08638649537168
```

**Comment by davidsousarj** [comment]
In fact, the system I am trying to calculate is a H4 chain with atoms separated by 1.6 Angstrom, it does not have core orbitals. When I change `nroots` from `10` to `30`even the first root changes significantly.

```
>>> import pyscf
>>> import pyscf.ci
>>> 
>>> N = 4
>>> r = 1.6
>>> mol = pyscf.gto.M(atom=";". join( f"H 0. 0. {i*r}" for i in range(N)),
...                   basis='ccpvdz',
...                   unit='A')
>>> 
>>> mf = pyscf.scf.RHF(mol)
>>> mf.kernel()
converged SCF energy = -1.97049116705226
-1.9704911670522578
>>> 
>>> cisolver = pyscf.ci.CISD(mf)
>>> cisolver.nroots=10
>>> cisolver.kernel()
RCISD root 0  E = -2.090345177754872
RCISD root 1  E = -1.954323763266944
RCISD root 2  E = -1.813226743225274
RCISD root 3  E = -1.688665466573999
RCISD root 4  E = -1.659024043427916
RCISD root 5  E = -1.648803395042629
RCISD root 6  E = -1.632977699393685
RCISD root 7  E = -1.584594647914082
RCISD root 8  E = -1.505256722445274
RCISD root 9  E = -1.460681478784449
...
>>> cisolver.nroots=30
>>> cisolver.kernel()
RCISD root 0  E = -2.139498177274701
RCISD root 1  E = -2.109191476144022
RCISD root 2  E = -2.090971742845202
RCISD root 3  E = -2.044488370029328
RCISD root 4  E = -2.021929315198687
RCISD root 5  E = -2.007593735654122
RCISD root 6  E = -1.99696944312991
RCISD root 7  E = -1.994300424064787
RCISD root 8  E = -1.983051977167759
RCISD root 9  E = -1.973071149505779
RCISD root 10  E = -1.971652393023533
RCISD root 11  E = -1.971236532622284
RCISD root 12  E = -1.971072639761181
RCISD root 13  E = -1.970427898877222
RCISD root 14  E = -1.969768497897318
RCISD root 15  E = -1.968964285845773
RCISD root 16  E = -1.967431740531393
RCISD root 17  E = -1.966256333931135
RCISD root 18  E = -1.963960730946837
RCISD root 19  E = -1.961171397223901
RCISD root 20  E = -1.939235504067384
RCISD root 21  E = -1.92566335538767
RCISD root 22  E = -1.918833372538093
RCISD root 23  E = -1.855715332085046
RCISD root 24  E = -1.841966052863622
RCISD root 25  E = -1.79930011896223
RCISD root 26  E = -1.683111172159693
RCISD root 27  E = -1.650362665103143
RCISD root 28  E = -1.644215311451193
RCISD root 29  E = -1.638985854121408
```

**Comment by tberkel** [comment]
You should also check if the roots are all converged (I suspect they are
not). You can check `cisolver.converged` which is a list of bools telling
you which roots are believed to be converged.

**Comment by tberkel** [comment]
`print(cisolver.converged)`

**Comment by davidsousarj** [comment]
@tberkel I ameant how can I make the roots converge. I am reading the documentation now, I suppose I have to increase `max_cycle` or something like that.

**Comment by tberkel** [comment]
Oh yes, sorry. Increasing the max number of cycles is probably the
simplest. Obtaining *many* roots by Davidson can be tricky. You can tune
the number of roots you request (fewer is simpler to converge, but you may
converge to higher-lying roots with a small space, as James said), or you
can also provide one or more guesses for the solution vectors.

**Comment by jamesETsmith** [comment]
I agree with all of @tberkel's comments on this and unless you have to limit the size of your basis I would suggest using a larger one for the H-chain calculations. See the demo [here](https://colab.research.google.com/drive/15gJIWMQj3CQi3KLz4mgSjT6X_FK_aA10?usp=sharing)

**Comment by verena-neufeld** [comment]
Hi @davidsousarj , thanks for your question, has it been answered?
