### ISSUE TITLE
Different MO coefficients when symmetry is OFF

### ISSUE THREAD

**Issue by lucienwb** [pyscf/pyscf#1717]
Hi all,

May I here ask a simple question about the symmetry of PySCF. I did a calculation on CH4 using keyword “mol.symmetry = True” or “False” I can get the same converged SCF energy and same molecular energies, where the top three MOs their energies are the same.
However, when “symmetry = False” is used the MOs are different, but also I find different MO coefficients each time I re-start the calculation. For example, the AO coefficients for the 3rd MO (which is one of the degenerated orbitals for CH4 molecule) are:

First run:
[ 8.20021408e-17 -7.93851527e-16 -4.72882826e-16 -4.16015875e-02
  4.24168213e-01  1.43530136e-01 -1.85028054e-02  1.88653904e-01
  6.38367506e-02  2.04123751e-01  1.72999922e-01 -9.27453436e-02
 -7.86039699e-02  1.25027892e-01  1.05964227e-01 -2.36406300e-01
 -2.00360179e-01]

Second run:
[ 1.59811632e-16 -3.02923196e-15  9.08140839e-15  3.94996482e-01
 -1.64380398e-01 -1.38589788e-01  1.75679426e-01 -7.31101547e-02
 -6.16394713e-02  3.57058896e-02  3.02616235e-02 -1.43250620e-01
 -1.21408440e-01 -1.63263958e-01 -1.38370238e-01  2.70808689e-01
  2.29517054e-01]

Third run:
[ 1.19134965e-15  2.83827922e-15 -2.32346205e-14  3.49355181e-01
  2.60269433e-01  1.11629049e-01  1.55379910e-01  1.15757954e-01
  4.96483592e-02  2.79843964e-01  2.37174673e-01 -1.93220583e-01
 -1.63759217e-01 -7.78766573e-02 -6.60023909e-02 -8.74672398e-03
 -7.41306465e-03]

But if I turn on the symmetry for my calculation each time I run it the MO coefficients have the same value, again for example, the AO coefficients for the 3rd MO:

Each run:
  [ 0.          0.          0.          0.          0.          0.44972243
  0.          0.          0.20001945  0.17449077  0.14788524  0.17449077
  0.14788524 -0.17449077 -0.14788524 -0.17449077 -0.14788524]

So, it seems there is a randomness inside PySCF if not turning on the symmetry constrain. And what could possibly be the reason that with “symmetry = False” each time the MOs are different? And how can I reduce this changing of MOs with “symmetry = False”

Thank you!

**Comment by tberkel** [comment]
This is only because the MOs are degenerate. For degenerate eigenvalues of
any matrix, linear combinations of their eigenvectors are also
eigenvectors, and so, without symmetry, the particular linear combination
returned each time is “random”.

**Comment by lucienwb** [comment]
@tberkel Thank you for your answer! May I have two more questions about it:
1. Where does this “randomness” first appears when executing the code for system with degenerated MOs.
2. For reproducibility, If I want to retrieve each time the same MOs should I always turn on the symmetry for my calculation. (I guess the answer is YES).
Many thanks for your kind help in advance!

**Comment by tberkel** [comment]
1. In general, it depends on many things, including the algorithm used to
find eigenvectors and eigenvalues. Numerical precision or hardware
differences could be enough to cause randomness.
2. That's one solution. Alternatively, you can try to choose your own
"convention" of how to resolve degeneracies. Note that a simpler ambiguity
exists even without degeneracies: the sign of an eigenvector is not unique.
See this thread for an example discussion about choosing a convention to
resolve this sign (including a comment highlighting that the problem is
even worse for degeneracies:
https://stackoverflow.com/questions/52958436/eigenvector-ambiguity-how-to-enforce-a-specific-sign-convention

**Comment by lucienwb** [comment]
@tberkel Thank you for your kind reply! I will close it now.
