### ISSUE TITLE
How to get the number of SCF iterations?

### ISSUE THREAD

**Issue by frankwswang** [pyscf/pyscf#1718]
I'd like to get the total iteration number of the SCF procedure of an HF method, assuming that it does not exceed `max_cycles`. Is there a convenient way to do so? Thanks!

**Comment by fishjojo** [comment]
At the moment, you can only get this from the output. You will need to set `mol.verbose`>=4.

**Comment by frankwswang** [comment]
I found that I can assign a function to `mol.callback` before running the SCF procedure to extract the iteration number at each cycle, similar to what this [example](https://github.com/pyscf/pyscf/blob/master/examples/scf/24-callback.py) shows. Thanks for trying to help!
