### ISSUE TITLE
[Question] Start a CI calculation from HF/DFT chkfile

### ISSUE THREAD

**Issue by davidsousarj** [pyscf/pyscf#1719]
I am trying to perform a CISD calculation in PySCF using the starting orbitals from an old DFT result.

The DFT result was saved on a chkfile, `mf.hdf5`. The code that generate this file is the following:

```
import pyscf.gto, pyscf.dft

bz_geom="""\
C    -1.21225309     0.69989455     0.00000000;
C    -1.21225309    -0.69989455     0.00000000;
C    -0.00000000    -1.39978909     0.00000000;
C     1.21225309    -0.69989455     0.00000000;
C     1.21225309     0.69989455     0.00000000;
C     0.00000000     1.39978909     0.00000000;
H    -2.15365863     1.24341536     0.00000000;
H    -2.15365863    -1.24341536     0.00000000;
H    -0.00000000    -2.48683071     0.00000000;
H     2.15365863    -1.24341536     0.00000000;
H     2.15365863     1.24341536     0.00000000;
H     0.00000000     2.48683071     0.00000000"""

mol = pyscf.gto.M(atom=bz_geom, basis='bfd_vtz', ecp='bfd')
mf  = pyscf.dft.RKS(mol)
mf.xc='b3lyp'
mf.chkfile="mf.hdf5"
mf.kernel()
```

It was very difficult to me finding documentation about how to load information from a chkfile. I came across with the following function:

`mf = pyscf.scf.chkfile.load_scf('mf.hdf5')`

But when I try to perform the CI calculation, I get an error:

```
# CISD calculation
cisolver = pyscf.ci.CISD(mf)
cisolver.kernel()
```

The full error message is:

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/tmp/ipykernel_20980/4228492657.py in <module>
     22 
     23 # CISD calculation
---> 24 cisolver = pyscf.ci.CISD(mf)
     25 cisolver.kernel()
     26 

~/.local/lib/python3.10/site-packages/pyscf/ci/__init__.py in CISD(mf, frozen, mo_coeff, mo_occ)
     31         return UCISD(mf, frozen, mo_coeff, mo_occ)
     32     else:
---> 33         return RCISD(mf, frozen, mo_coeff, mo_occ)
     34 CISD.__doc__ = cisd.CISD.__doc__
     35 

~/.local/lib/python3.10/site-packages/pyscf/ci/__init__.py in RCISD(mf, frozen, mo_coeff, mo_occ)
     38 
     39     if isinstance(mf, newton_ah._CIAH_SOSCF) or not isinstance(mf, scf.hf.RHF):
---> 40         mf = scf.addons.convert_to_rhf(mf)
     41 
     42     if getattr(mf, 'with_df', None):

~/.local/lib/python3.10/site-packages/pyscf/scf/addons.py in convert_to_rhf(mf, out, remove_df)
    692     from pyscf import scf
    693     from pyscf import dft
--> 694     assert (isinstance(mf, hf.SCF))
    695 
    696     logger.debug(mf, 'Converting %s to RHF', mf.__class__)

AssertionError: 
```
It seems to me that the error is because the mf object is from a DFT calculation and not from a HF calculation. I get a similar error before (if I try to start the CI calculation directly from the DFT `mf` object, instead of with the chkfile). In that case, I got a helpful error message:

```
RuntimeError: CISD Warning: The first argument mf is a DFT object. CISD calculation should be initialized with HF object.
DFT object can be converted to HF object with the code below:
    mf_hf = scf.RHF(mol)
    if getattr(mf_dft, "with_x2c", False):
        mf_hf = mf_hf.x2c()
    mf_hf.__dict__.update(mf_dft.__dict__)
```

So I should try to do something similar with the `mf` object obtained from `pyscf.scf.chkfile.load_scf`. The problem is I do not have the `mol` object in that case.

I probably am doing something wrong. What is the correct procedure to start a CI calculation from a previous chkfile from a DFT or HF calculation?

**Comment by jamesETsmith** [comment]
@davidsousarj, thanks for reaching out. The `load_scf` function returns two things: 1) a mol object and 2) a HF/KS object. Since you're capturing both of them with a single variable (`mf`), things get messed up. See the source here: https://github.com/pyscf/pyscf/blob/7000be6e0abc4c3d4edc8d314bcb5304e666ef0f/pyscf/scf/chkfile.py#L24-L25

If you capture it with two variables, then you can convert the DFT object to HF and run CI like I show below.

```python
# Run DFT calculation before this
mol, mf_dft = pyscf.scf.chkfile.load_scf('mf.hdf5')

# Convert DFT to HF (if necessary)
mf_hf = scf.RHF(mol)
if getattr(mf_dft, "with_x2c", False):
    mf_hf = mf_hf.x2c()
mf_hf.__dict__.update(mf_dft.__dict__)

# CISD calculation
cisolver = pyscf.ci.CISD(mf_hf)
cisolver.kernel()
```

In addition to using the `load_scf` function, you could also load saved data like this:
https://github.com/pyscf/pyscf/blob/7000be6e0abc4c3d4edc8d314bcb5304e666ef0f/examples/scf/14-restart.py#L63-L64

**Comment by davidsousarj** [comment]
Thank you for the answer @jamesETsmith 

If I do not convert DFT to HF, the same `Assertion Error` is raised, so I think that the conversion is necessary.

By the way, in the conversion code I should use `mf_hf = pyscf.scf.RHF(mol)` because of the way how I imported the module.

However, I am still getting the following error with your code:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_12049/2937000999.py in <module>
     12 if getattr(mf_dft, "with_x2c", False):
     13     mf_hf = mf_hf.x2c()
---> 14 mf_hf.__dict__.update(mf_dft.__dict__)
     15 
     16 # CISD calculation

AttributeError: 'dict' object has no attribute '__dict__'
```
It seems like the `load_scf` does not return directly the `mf` object, but it returns a dictionary of the scf data.

How can I fix that?

**Comment by jamesETsmith** [comment]
@davidsousarj, sorry about that, I should have tested the code I sent. Here's a complete script (that I just ran without issue):

```python
import pyscf.gto, pyscf.dft
from pyscf import scf, ci

bz_geom="""\
C    -1.21225309     0.69989455     0.00000000;
C    -1.21225309    -0.69989455     0.00000000;
C    -0.00000000    -1.39978909     0.00000000;
C     1.21225309    -0.69989455     0.00000000;
C     1.21225309     0.69989455     0.00000000;
C     0.00000000     1.39978909     0.00000000;
H    -2.15365863     1.24341536     0.00000000;
H    -2.15365863    -1.24341536     0.00000000;
H    -0.00000000    -2.48683071     0.00000000;
H     2.15365863    -1.24341536     0.00000000;
H     2.15365863     1.24341536     0.00000000;
H     0.00000000     2.48683071     0.00000000"""

mol = pyscf.gto.M(atom=bz_geom, basis='bfd_vtz', ecp='bfd', verbose=4)
mf  = pyscf.dft.RKS(mol)
mf.xc='b3lyp'
mf.chkfile="mf.hdf5"
mf.kernel()

# Run DFT calculation before this
mol, dft_dict = pyscf.scf.chkfile.load_scf('mf.hdf5')

# Convert DFT to HF
mf_hf = scf.RHF(mol)
if getattr(dft_dict, "with_x2c", False):
    mf_hf = mf_hf.x2c()
mf_hf.__dict__.update(dft_dict)

# CISD calculation
cisolver = ci.CISD(mf_hf)
cisolver.verbose = 4
cisolver.kernel()
```

[Here's a demo on google colab](https://colab.research.google.com/drive/1KdGISNx2RlQWKRUf-ecKud2jVgaQO7zA?usp=sharing) (with a smaller basis to make things run faster)

**Comment by davidsousarj** [comment]
Thank you. I was already testing another solution while you sent me the answer. This also worked:

```
import pyscf.scf, pyscf.ci

mol = pyscf.scf.chkfile.load_mol('mf.hdf5')
mf = pyscf.scf.RHF(mol) 
mf.__dict__.update(pyscf.scf.chkfile.load('mf.hdf5', 'scf')) 

cisolver = pyscf.ci.CISD(mf)
cisolver.kernel()
```

**Comment by jamesETsmith** [comment]
Awesome, I'm glad that worked for you! Are you ok if I close this issue?

**Comment by ndattani** [comment]
I'll point out that this was also cross-posted on MMSE (actually it was asked there 1 day before it was asked here): https://mattermodeling.stackexchange.com/q/10802/5
