### ISSUE TITLE
Question about implementation in MCSCF

### ISSUE THREAD

**Issue by lijiachen417** [pyscf/pyscf#1724]
Hi, I'm reading the code in pyscf/mcscf/mc1step.py line 86

https://github.com/pyscf/pyscf/blob/7000be6e0abc4c3d4edc8d314bcb5304e666ef0f/pyscf/mcscf/mc1step.py#L86

I have two questions:
1. why the eri transformation for p1aa and paa1 is coded in this way, instead of rotating four indexes one by one? I'm not sure the benefit from the current implementation.
2. in line 116, the comment says "# 0000 + 1000 + 0100 + 0010 + 0001 + 1100 + 1010 + 1001  (missing 0110 + 0101 + 0011)". Will the missing term be recovered by some following operations, or their contributions are just ignored?

Thank you in advance!

**Comment by verena-neufeld** [comment]
Hi @lijiachen417 , thank you for your questions. To better answer question 1, can you please give an example for question 1 showing what you mean by rotating four indexes one by one?

**Comment by lijiachen417** [comment]
@verena-neufeld thanks for replying! It has been a quiet long time since last time I read this part code. I will read it again and reply to you here soon.

**Comment by lijiachen417** [comment]
@verena-neufeld Thanks for your help, I will close this issue.
