### ISSUE TITLE
Subset of 3-center integral tensor for density fitting

### ISSUE THREAD

**Issue by stefanvuckovic1** [pyscf/pyscf#1729]
To obtain density fitting (DF) coefficients, I compute the 3-center integral tensor (ij|P) as explained [here ](https://github.com/pyscf/pyscf/blob/master/examples/df/10-access_df_integrals.py). For large systems, this tensor is too large to fit in memory, so I would like to compute only a necessary part of it needed for a given batch.
```
from pyscf import gto, scf, dft, lib, df

#mol, Amol
mol = gto.M(atom='Ar 0 0 0', basis='def2-qzvp'); Amol = df.addons.make_auxmol(mol, 'def2universaljkfit')
#3c2e needed for DF is of shape (mol.nao, mol.nao, Amol.nao)
ints_3c2e = df.incore.aux_e2(mol, Amol, intor="int3c2e")
```

I would like to compute a piece of "ints_3c2e" directly without computing the whole tensor, since I only need a specific subset of the tensor for a given batch when calculating DF coefficients. For example, how can I compute the following piece directly?

```
i1 = 0; i2 = 5; j1 = 5; j2 = 10
piece_ints3c2e = ints_3c2e[i1:i2, j1:j2, :]
```

**Comment by fishjojo** [comment]
You could modify the shell slices here
https://github.com/pyscf/pyscf/blob/7000be6e0abc4c3d4edc8d314bcb5304e666ef0f/pyscf/df/incore.py#L54
In the future, I think it's better to expose it as an argument.
