### ISSUE TITLE
The meaning of `.direct_scf` in SCF object.

### ISSUE THREAD

**Issue by frankwswang** [pyscf/pyscf#1730]
Could someone explain to me what this attribute controls? I couldn't find an explanation in the documentation. Thanks!

**Comment by hebrewsnabla** [comment]
To some extent, it is confusing. The SCF scheme is direct by default and will switch to incore when memory is enough, but in this case `.direct_scf` is still True.

Another effect it controls is that the incremental fock will be applied when direct_scf is True. Maybe that's the only use of disabling direct_scf?

**Comment by frankwswang** [comment]
> To some extent, it is confusing. The SCF scheme is direct by default and will switch to incore when memory is enough, but in this case `.direct_scf` is still True.
> 
> Another effect it controls is that the incremental fock will be applied when direct_scf is True. Maybe that's the only use of disabling direct_scf?

Thank you for the explanation! Could you elaborate more on what you meant by the "incremental fock"? Do you mean the fock matrix generated at each cycle will all be stored? Thank you!

**Comment by hebrewsnabla** [comment]
https://github.com/pyscf/pyscf/blob/063af4c6ab1b85a345b3bf73f5f998a600b0fa6e/pyscf/scf/hf.py#L1765-L1777

incremental means the fock is obtained from fock (last cycle) + fock (dm - dm_last)

**Comment by frankwswang** [comment]
Thank you for directing the source code! I can see that by using the change of density matrix to calculate `vj` and `vk`, some integrals no longer need to be calculated on the fly due to the near-zero values of (dm-dm_last), thus improving the efficiency of building the Fock matrix. I do wonder if this will slow down the convergence of SCF.
