### ISSUE TITLE
CAS-CI excited state energies

### ISSUE THREAD

**Issue by missymetrum** [pyscf/pyscf#1732]
Hello,

to my understanding in CAS-CI, as in FullCI, as the result of the diagonalization, one obtains gs as well as excited state energy eigenvalues. Is there a way to extract these excited state energies from a CAS-CI calculation in pySCF?

Best, M.

**Comment by jamesETsmith** [comment]
@missymetrum checkout out this example https://github.com/pyscf/pyscf/blob/063af4c6ab1b85a345b3bf73f5f998a600b0fa6e/examples/mcscf/15-state_specific.py#L32-L45

**Comment by missymetrum** [comment]
Thanks, I will look into it!

**Comment by verena-neufeld** [comment]
Hi @missymetrum , thanks for posting the issue here. Has it been answered?

**Comment by sunqm** [comment]
Feel free to reopen the issue.
