### ISSUE TITLE
Inconsistent UHF conversion functions in open- and periodic boundary conditions 

### ISSUE THREAD

**Issue by chrislzhao** [pyscf/pyscf#1737]
Hi, 

I found an issue when converting to UHF object in the MP2 function. For both periodic systems at Gamma point and molecular systems, it is the molecular MP2 function that will be used when doing a MP2 calculation. When the SCF object is, say ROHF, it will be converted to UHF by the `to_uhf` function. However, the implementation of the `to_uhf` function is not consistent with molecular SCF v.s. periodic SCF, in which the latter requires an input of a SCF object while the former does not. Due to this problem, the code will fail when one tries to do a PBC-MP2 with PBC-ROHF, as when it calls `to_uhf` it complains about the missing argument.

**Comment by sunqm** [comment]
The conversion function is messy in the main branch. I have them refactored in a development branch https://github.com/sunqm/pyscf/tree/mcfun-pbc . You can try this branch if you need the fix for now. The fix depends on PR #1622. So it may take some time to merge that branch

**Comment by verena-neufeld** [comment]
Hi @chrislzhao , thanks! Has this been solved now by PR #1859 ?

**Comment by sunqm** [comment]
#1859 has unified the conversion functions between SCF methods.
