### ISSUE TITLE
Question on Brueckner orbitals

### ISSUE THREAD

**Issue by vvp-nsk** [pyscf/pyscf#1743]
Hi!

Recently, the UBCCD(T) method has been released within the PySCF package. I wonder whether would it be possible to access the resulted Brueckner orbitals (MO coefficients) and dump to checkpoint file? Would be great if one can provide a working example on how to do so, indeed. 

Thank you in advance!

With best regards, 
Victor

**Comment by zhcui** [comment]
Hi Victor,

When doing (T) calculations, other softwares (like PSI4) recommend to use the semicanonicalized BCC orbitals.
I just pulled a request for such a feature.
To get the same (T) behavior as other software, please it.

Best,
Zhihao

**Comment by vvp-nsk** [comment]
Hi Zhihao, 

It looks like support of semi-canonical orbitals breaks compatibility with triples in an open-shell case: 

import pyscf
import numpy as np
from pyscf import cc
from bccd  import *

np.set_printoptions(3, linewidth=1000, suppress=True)

mol = pyscf.M(
    atom = 'H 0 0 0; F 0 0 1.1',
    basis = 'ccpvdz',
    verbose = 4,
    spin = 1,
    charge = 1
)

myuhf = mol.UHF()
myuhf.kernel()
E_ref = myuhf.e_tot
rdm1_mf = myuhf.make_rdm1()

myucc = cc.UCCSD(myuhf, frozen=None)
myucc.kernel()
myucc.conv_tol = 1e-3

myucc = bccd_kernel_(myucc, diis=True, verbose=4)
e_r = myucc.e_tot
e_ccsd_t = myucc.ccsd_t()

...
SemiCanonical/bccd.py:304: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  mycc.t1 = np.asarray(t1, order='C')
SemiCanonical/bccd.py:305: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  mycc.t2 = np.asarray(t2, order='C')
**Traceback (most recent call last):
  File "SemiCanonical/test.py", line 27, in <module>
    e_ccsd_t = myucc.ccsd_t()
  File "lib/python3.10/site-packages/pyscf/cc/uccsd.py", line 635, in ccsd_t
    return uccsd_t.kernel(self, eris, t1, t2, self.verbose)
  File "lib/python3.10/site-packages/pyscf/cc/uccsd_t.py", line 129, in kernel
    assert (t2ab.flags.c_contiguous)
AssertionError**
~                                          


Could you please take a look at testbed given above and reproduce a problem, if any?

Thank you in advance!

With best regards, 
Victor
