### ISSUE TITLE
cell.a does not equal to lattice vector?

### ISSUE THREAD

**Issue by zltemp** [pyscf/pyscf#1749]
Hi all. 
I was doing some PBC calculations with the latest version of pyscf (2.2.1) and found something strange. 
According to the introduction on pyscf manual website (https://pyscf.org/user/pbc/gto.html), the cell parameter "a" refers to the lattice vectors in a PBC calculation. However, in my calculation result, the lattice vectors a1 to a3 are almost twice as much as the parameter 'cell.a' I just input. For example, if I set 'cell.a' as [[4 0 0][0 4 0][0 0 4]], the actual lattice vectors in the output files are [[7.55 0 0][0 7.55 0][0 0 7.55]]. 
For me, it looks like a unit transformation from Angstrom to Bohr. Is it actually the case? If so, why do pyscf output it like this? And what is the unit that is used in the following calculations, Angstrom or Bohr? 
The output file is attached. Looking forward to your reply.

[test_h2o.txt](https://github.com/pyscf/pyscf/files/11589549/test_h2o.txt)

**Comment by hebrewsnabla** [comment]
The input unit is angstrom by default. 7.55 should be in a.u..
