### ISSUE TITLE
[Question] Using frozen core approximation with CISD and FCI

### ISSUE THREAD

**Issue by JoelHBierman** [pyscf/pyscf#1751]
I have two closely related questions about using the frozen core approximation with CISD and FCI.

1. Is it possible in pyscf to perform an FCI problem on the active space? (_i.e._ freeze a certain subset of orbitals and perform an FCI calculation over the rest.) From the [CI documentation](https://pyscf.org/user/ci.html?highlight=frozen) it appears that this functionality exists for CISD, but I do not see the corresponding frozen core functionality for FCI.

2. For CISD/FCI calculations, is it possible to separate the results into the frozen and active space contributions? It looks like only the sum of these two energy contributions is returned.

**Comment by xubwa** [comment]
You may just do casci for frozen core full ci. In casci, if you use a pretty high verbose level, the active space energy is printed as E(CI), and you may obtain the frozen core energy by taking the difference between total energy and CI energy. For cisd part of the question, I don't have enough experience with cisd.

**Comment by JoelHBierman** [comment]
Thanks! Is there a way to return multiple roots from CASCI? This functionality is not evident to me from [the documentation](https://pyscf.org/pyscf_api_docs/pyscf.mcscf.html?highlight=casci#module-pyscf.mcscf.casci).

**Comment by tberkel** [comment]
Yes:
```
mc = mcscf.CASCI(mf, 4, 4)
mc.fcisolver.nroots = 4
```
See `examples/15-state_specific.py`

**Comment by JoelHBierman** [comment]
Thanks!
