### ISSUE TITLE
order of spherical harmonics in pyscf and molpro

### ISSUE THREAD

**Issue by binghuang2018** [pyscf/pyscf#1752]
Hi,

I'm trying to do some conversion between Pyscf and Molpro. I tried this example script https://github.com/pyscf/pyscf/blob/master/examples/gto/30-read_molpro_orb.py and found it indeed works. However, switching to a basis such as vtz (or other molecule such as h2o, sticking to vdz basis) fails the normalization test. It seems to me that the examplified script works just by chance due to symmetry. My first guess is that the spherical harmonics used by molpro and pyscf are in different order. Any clue?

Best,
Bing

**Comment by 1234zou** [comment]
I'm not sure that whether the module [py2molpro](https://gitlab.com/jxzou/qcinstall/-/blob/main/%E5%88%A9%E7%94%A8MOKIT%E4%BB%8EPySCF%E5%90%91%E5%85%B6%E4%BB%96%E9%87%8F%E5%8C%96%E7%A8%8B%E5%BA%8F%E4%BC%A0%E8%BD%A8%E9%81%93.md#5-pyscf%E4%BC%A0%E8%BD%A8%E9%81%93%E7%BB%99molpro) in [MOKIT](https://gitlab.com/jxzou/mokit) meets you needs. It correctly takes care the order of spherical harmonics and Cartesian-type basis functions. This can be simply used by
```
from mokit.lib.py2molpro import py2molpro

mf = scf.RHF(mol).run()
py2molpro(mf, 'h2o.com')
```

**Comment by verena-neufeld** [comment]
Hi @binghuang2018 , thanks for asking. Has this been answered?

**Comment by binghuang2018** [comment]
> Hi @binghuang2018 , thanks for asking. Has this been answered?

I found the right order from the source code of molpro:

#  // Spherical component order (Molpro/Molcas):
#  // L=0: s0
#  // L=1: p1+ p1- p0
#  // L=2: d0  d2- d1+ d2+ d1-
#  // L=3: f1+ f1- f0  f3+ f2- f3- f2+
#  // L=4: g0  g2- g1+ g4+ g1- g2+ g4- g3+ g3-
#  // L=5: h1+ h1- h2+ h3+ h4- h3- h4+ h5- h0  h5+ h2-
#  // L=6: i6+ i2- i5+ i4+ i5- i2+ i6- i3+ i4- i0  i3- i1- i1+
#  // L=7: k0  k1- k1+ k2- k2+ k3- k3+ k4- k4+ k5- k5+ k6- k6+ k7- k7+
