### ISSUE TITLE
obtain orbital average kinetic energy?

### ISSUE THREAD

**Issue by FrancescoMBianchi98** [pyscf/pyscf#1753]
This might be more of a physics question than a strictly pyscf related issue, in which case I'm sorry! Just getting started in this field.

I am trying to compute ionization cross sections of heavy atoms (e.g. Xe, I) using a BEB method. To do so, I need occupancy number, binding energy and **average kinetic energy** of each occupied orbital. The first two I can easily obtain with pyscf (I used an HF calculation), however it is not entirely clear to me how I could go about obtaining the latter. Is it possible to obtain with the SCF methods included in pyscf? If so, how would I go about doing that?
Thanks in advance!

**Comment by susilehtola** [comment]
You can compute the orbital kinetic energy by contracting the orbital coefficients `C = mf.mo_coeff` with the kinetic energy matrix `T = mol.intor_symmetric('int1e_kin')`. For example
```
import pyscf

mol = pyscf.M(
    atom = 'H 0 0 0; F 0 0 1.1',  # in Angstrom                                                                                                                                               
    basis = 'ccpvdz',
    symmetry = True,
)

mf = mol.HF()
mf.kernel()

occs = mf.mo_occ
C = mf.mo_coeff
T = mol.intor_symmetric('int1e_kin')
for icol, occ in enumerate(occs):
    if occ>0.0:
	print(f'Orbital {icol+1} kinetic energy {C[:,icol].T @ T @ C[:,icol]}')
```
prints out
```
$ python 00-simple_hf.py 
converged SCF energy = -99.9873974403488
Orbital 1 kinetic energy 37.254262161040366
Orbital 2 kinetic energy 3.8278166626243366
Orbital 3 kinetic energy 2.462086461589103
Orbital 4 kinetic energy 3.1640185085938737
Orbital 5 kinetic energy 3.1640185085938737
```

**Comment by FrancescoMBianchi98** [comment]
This is exactly what I was looking for, thank you!
