### ISSUE TITLE
Semicanonicalization of the BCCD orbitals (#1744) breaks perturbative triples correction in the case of open-shell

### ISSUE THREAD

**Issue by vvp-nsk** [pyscf/pyscf#1757]
Hi!

The commit #1744 introduces an incompatibility with ccsd_t():

```
import pyscf
from pyscf import cc
from bccd  import *

"""
ubccd_t.py
"""

np.set_printoptions(3, linewidth=1000, suppress=True)
mol = pyscf.M(
    atom = 'H 0 0 0; F 0 0 1.1',
    basis = 'ccpvdz',
    verbose = 4,
    spin = 1,
    charge = 1 
)

myhf = mol.UHF()
myhf.kernel()
E_ref = myhf.e_tot
rdm1_mf = myhf.make_rdm1()

mycc = cc.CCSD(myhf, frozen=None)
#mycc.frozen = [0]
mycc.kernel()
mycc.conv_tol = 1e-3

mycc = bccd_kernel_(mycc, diis=True, verbose=4,canonicalization=False)
e_r = mycc.e_tot
e_ccsd_t = mycc.ccsd_t()

myhf = mol.UHF()
myhf.kernel()
E_ref = myhf.e_tot
rdm1_mf = myhf.make_rdm1()

mycc = cc.CCSD(myhf, frozen=None)
#mycc.frozen = [0]
mycc.kernel()
mycc.conv_tol = 1e-3

mycc = bccd_kernel_(mycc, diis=True, verbose=4,canonicalization=True)
e_r = mycc.e_tot
e_ccsd_t = mycc.ccsd_t()
```

The first UBCCD(T) w/o semi-canonicalization works fine while the second one just fails:

Traceback (most recent call last):
  File "h2o_cation/ubccd_t.py", line 40, in <module>
    e_ccsd_t = mycc.ccsd_t()
  File ".venv/lib/python3.10/site-packages/pyscf/cc/uccsd.py", line 635, in ccsd_t
    return uccsd_t.kernel(self, eris, t1, t2, self.verbose)
  File ".venv/lib/python3.10/site-packages/pyscf/cc/uccsd_t.py", line 129, in kernel
    assert (t2ab.flags.c_contiguous)

Is it something wrong with my input?

Thank you in advance!

With best regards,
Victor

**Comment by zhcui** [comment]
Thanks for catching this. It is fixed in PR #1759

**Comment by vvp-nsk** [comment]
Thanks for the fix!

However, the perturbative triples energy correction differs from PSI4 now:

| Frozen-core  |  PySCF w/o canonicalization | PySCF w/ canonicalization | PSI4 (semi-canonical) |
| -------------- | ---------------------------- | ------------------------- | ---------------------- |
|  Yes  |   -0.00194884941644244 |   -0.0019333182189602 |   -0.001950635468171 |
|  No  |   -0.00197072480463062 | -0.00197276616437818 |  -0.001972536858517 | 

Apparently, something is going wrong when the core electrons kept frozen. Could you please take a look at it?

Just in case, below please find the UBCCD total energies:

| Frozen-core  |  PySCF w/o canonicalization | PySCF w/ canonicalization | PSI4 (semi-canonical) |
| -------------- | ---------------------------- | ------------------------- | ---------------------- |
|  Yes  |  -99.6610122062838 | -99.66101220628371  |  -99.661012419479661 |
|  No  |  -99.6627622587803 | -99.66276225878036  |  -99.662762475033034  | 

Thank you in advance!

With best regards, 
Victor

**Comment by vvp-nsk** [comment]
Thank you!

Now it works out. The results are consistent compared to PSI4, and TM.  The issue can be closed.

With best regards, 
Victor
