### ISSUE TITLE
printing CC wavefunction into FCI format

### ISSUE THREAD

**Issue by davidecast** [pyscf/pyscf#1766]
Hello,

I am trying to understand if it is possible in pyscf to convert cluster amplitudes to ci amplitudes. My final goal would be printing the cc wavefunction in FCI format, perhaps similar to #327.

Thank you for your help!

Davide

**Comment by fishjojo** [comment]
I don't have a good solution to this, but you may try to apply the T operator repeatedly onto the Slater determinant to get the CI wavefuntion.

**Comment by verena-neufeld** [comment]
Hi @davidecast , thanks for asking, has this been answered?

**Comment by Eureka10shen** [comment]
> @davidecast If you're still interested, [this](https://github.com/jorgecga/pyscf/blob/88a1324a7ac1bf80ff079ab5f3a13976b355f0ff/pyscf/cc/cc2ci.py) may help.

Hello,
Can the fci_coefs function be accelerated ?
It seems that it is twwo slow even for CH4 with STO-3G basis set.

**Comment by jorgecga** [comment]
@Eureka10shen, check it out now. It should be 60x faster.

**Comment by sunqm** [comment]
Many thanks to @jorgecga for offering this feature.
