### ISSUE TITLE
valgrind raises memory leak in  optimizer.c

### ISSUE THREAD

**Issue by sspaino** [pyscf/pyscf#1769]
Hello!

when I referenced the code of optimizer.c , I found valgrind raised memory leak in function of "CVHFinit_optimizer". maybe it's better opt0=NULL after *opt = opt0 in 45 of optimizer.c.

**Comment by fishjojo** [comment]
If you made the change, would valgrind not raise memory leak?
`opt0` itself is a local variable on the stack and it should go out of scope when the function returns. So it seems to me no memory leak here.
The `CVHFOpt` object is freed in `CVHFdel_optimizer`.

**Comment by sspaino** [comment]
yes，I made the change,and valgrind didn't raise memory leak. actually, CVHFOpt is freed in CVHFdel_optimizer, I guess valgrind is  regarded opt0 as loss record.you can test it.

**Comment by sunqm** [comment]
Some objects in PySCF are not released due to the `__del__` method. This is a known issue. It only affects a few specific places and does not involve unmanaged memory. I think this is acceptable. However, feel free to reopen the issue if you have any concerns.
