### ISSUE TITLE
cannot import name 'gto' from 'pyscf' (unknown location)

### ISSUE THREAD

**Issue by Lost-Volt** [pyscf/pyscf#1772]
Hi, I recently installed pyscf on windows using GitHub repository (I have some problem with the pip install pyscf). But whenever I am trying to use the pyscf it's showing an error named "cannot import name 'gto' from 'pyscf' (unknown location)". I then added the top pyscf directory to PYTHONPATH but the ipython in terminal showing a new issue named "module 'os' has no attribute 'sysconf'". Another one is that the notebook is not reflecting the change I have made to the Path. All screenshots are attached. I am stuck with these for 1 week; need urgent help.

Thank You
Himadri  

![Screenshot (132)](https://github.com/pyscf/pyscf/assets/137344605/c2961469-8696-4cb4-860a-cc104a5d0fd7)
![Screenshot (133)](https://github.com/pyscf/pyscf/assets/137344605/5b7580b7-c9ac-43e4-b2a8-b6eab58fb140)
![Screenshot (134)](https://github.com/pyscf/pyscf/assets/137344605/d74b06b3-5a9c-4072-b405-7f9aa147829e)
![Screenshot (135)](https://github.com/pyscf/pyscf/assets/137344605/0355f26d-159a-414c-95fd-c3bfea30ce5f)

**Comment by fishjojo** [comment]
PySCF does not support windows systems at the moment, you may use the windows subsystem for linux.
The `os.sysconf` error is because it doesn't exist on windows. You may try comment out the line `CLOCK_TICKS = os.sysconf("SC_CLK_TCK")`, and replace the line `PAGESIZE = os.sysconf("SC_PAGE_SIZE")` with `PAGESIZE = mmap.PAGESIZE`. But there may be other errors.

**Comment by Lost-Volt** [comment]
> PySCF does not support windows systems at the moment, you may use the windows subsystem for linux. The `os.sysconf` error is because it doesn't exist on windows. You may try comment out the line `CLOCK_TICKS = os.sysconf("SC_CLK_TCK")`, and replace the line `PAGESIZE = os.sysconf("SC_PAGE_SIZE")` with `PAGESIZE = mmap.PAGESIZE`. But there may be other errors.

I see. Can you please point out why the updated path is not showing in the notebook?

**Comment by Lost-Volt** [comment]
> Maybe [this](https://stackoverflow.com/questions/12204981/ipython-has-different-sys-path-than-python-and-does-not-use-pythonpath) is related.

Thanks. It worked.

**Comment by verena-neufeld** [comment]
Hi @Lost-Volt , thanks for posting the issue here. Has it been answered? Then the issue can be closed.

**Comment by Lost-Volt** [comment]
> Hi @Lost-Volt , thanks for posting the issue here. Has it been answered? Then the issue can be closed.

Yes the issue has been resolved. Can be closed now.
