### ISSUE TITLE
Higher Hartree Fock energy in the latest version

### ISSUE THREAD

**Issue by sk888ks** [pyscf/pyscf#1774]
Hello,
HF calculation behavior is different up to ver 2.1.1 and after 2.2.0, where we checked ver 2.0.1, 2.1.0, 2.1.1, 2.2.0, and 2.2.1, and pyscf is installed with pip.

HF calculations were performed on a planar model with four hydrogens.
```
from pyscf import gto, scf
import numpy as np
mol = gto.M(atom = '"H 0.0 0.0 0.0 ;H 1.34 0.0 0.0 ;H 0.0 1.34 0.0 ;H 1.34 1.34 0.0 "', basis = 'sto-3g', spin=0)
mf = scf.RHF(mol).run()
print("mo coeff\n", np.round(mf.mo_coeff,3))
```

Here are the results.
```
ver 2.1.0
converged SCF energy = -1.75914707282045
mo coeff
 [[ 0.374 -0.54   0.54  -0.708]
 [ 0.374 -0.54  -0.54   0.708]
 [ 0.374  0.54   0.54   0.708]
 [ 0.374  0.54  -0.54  -0.708]]
```
```
ver 2.2.0
converged SCF energy = -1.67708182393442
mo coeff
 [[ 0.409  0.    -0.763 -0.689]
 [ 0.339 -0.763 -0.     0.725]
 [ 0.339  0.763  0.     0.725]
 [ 0.409 -0.     0.763 -0.689]]
```
Compared to the ver. 2.1.0 results, the ver. 2.2.0 results show a localized MO and higher HF energy. GAMESS-US also produced results corresponding to those of ver. 2.1.0. Therefore, ver 2.1 appears to be more consistent with our chemical intuition.

We expect that the way to determine the axis of symmetry in the xy-plane has changed between ver 2.1.1 and 2.2.0. One of the reasons is that the behavior was reproduced in GAMESS-US when the symmetry axis was rotated by 45 degrees. Also, in pyscf ver 2.1.0, when HF calculation was run 10 times with the atomic coordinates rotated by 45 degrees, MO localization occurred 3 times (this kind of randomness also sometimes occurs in other systems, is this a feature?) 

I am currently pending an update of pyscf due to this behavior, but I am wondering if there is a way to manage it.

Thanks,
Shu

**Comment by verena-neufeld** [comment]
I have just tested with the latest pyscf version on here (git hash 485098119e4879acebfedc3f17d956a0c0377124 ) and I get -1.75914707282022. This could of course be system dependent.

**Comment by sk888ks** [comment]
Thank you for your response. As you've suggested, there seems to be a system-dependent variability in the output. Specifically, I've observed different results just by translating or rotating the atomic coordinates of input. Moreover, I noticed different behaviors when installing via pip and conda. Furthermore, other members running the same code have reported different outcomes as well.

In my current environment (WSL2, Ubuntu 20.04.5, Python 3.9.13, PySCF 2.1.0), the output is stable for specific inputs, but I cannot guarantee that this will remain the case if the software is updated. In my research, I frequently call this software from external software, specifically OpenFermion, and Qiskit. If the output is sensitively dependent on the system and changes with every call, it becomes difficult to benchmark my experiments.

Do you have any suggestions for handling this issue? Currently, I'm considering using pickle to save the Hamiltonian data when lower HF energy is produced, but this approach may not work well for more complex systems.

**Comment by verena-neufeld** [comment]
Yes this behaviour with the differing HF solutions is not ideal. Can you try running stability analysis after the HF calculation and then restart if not stable to find a more stable solution, see e.g. examples/scf/17-stability.py ? To save the molecular coefficients etc from the SCF calculation, you can save them to a chkfile if you like, see scf/14-restart.py .

**Comment by susilehtola** [comment]
You are running HF in square planar H4 at a bond length of 1.34 Å. This system is strongly correlated, and HF has a plethora of local solutions; the solution you land on may depend even on numerical roundoff errors.

**Comment by sk888ks** [comment]
Thank you for the information.

> Yes this behaviour with the differing HF solutions is not ideal. Can you try running stability analysis after the HF calculation and then restart if not stable to find a more stable solution, see e.g. examples/scf/17-stability.py ? 

 I got better a result by using stability analysis.
"""
from pyscf import gto, scf
import numpy as np
mol = gto.M(atom = '"H 0.0 0.0 0.0 ;H 1.34 0.0 0.0 ;H 0.0 1.34 0.0 ;H 1.34 1.34 0.0 "', basis = 'sto-3g', spin=0)
mf = scf.RHF(mol).run()
print("mo coeff\n", np.round(mf.mo_coeff,3))

from pyscf.lib import logger

def stable_opt_internal(mf):
    log = logger.new_logger(mf)
    mo1, _, stable, _ = mf.stability(return_status=True)
    cyc = 0
    while (not stable and cyc < 1000):
        log.note('Try to optimize orbitals until stable, attempt %d' % cyc)
        dm1 = mf.make_rdm1(mo1, mf.mo_occ)
        mf = mf.run(dm1)
        mo1, _, stable, _ = mf.stability(return_status=True)
        cyc += 1
    if not stable:
        log.note('Stability Opt failed after %d attempts' % cyc)
    return mf

print('loop example')
mf2 = stable_opt_internal(mf)
print("mo coeff\n", np.round(mf2.mo_coeff,3))
"""

Here is a result in pyscf ver 2.2.1.
"""
converged SCF energy = -1.67708182393441
mo coeff
 [[ 0.409 -0.    -0.763 -0.689]
 [ 0.339  0.763 -0.     0.725]
 [ 0.339 -0.763  0.     0.725]
 [ 0.409  0.     0.763 -0.689]]
loop example
<class 'pyscf.scf.hf.RHF'> wavefunction has an internal instability
Try to optimize orbitals until stable, attempt 0
converged SCF energy = -1.75914707280783
<class 'pyscf.scf.hf.RHF'> wavefunction is stable in the internal stability analysis
mo coeff
 [[ 0.374 -0.54  -0.54   0.708]
 [ 0.374  0.54  -0.54  -0.708]
 [ 0.374 -0.54   0.54  -0.708]
 [ 0.374  0.54   0.54   0.708]]
"""
I will also try restart mode.



> You are running HF in square planar H4 at a bond length of 1.34 Å. This system is strongly correlated, and HF has a plethora of local solutions; the solution you land on may depend even on numerical roundoff errors.

While electron correlation would affect the result as you said, the MO localization happens even when the bond length is 0.7 angstrom. From the reproduction of this issue by GAMESS in the first comment, I think that this higher energy comes from the rotation of the symmetry axis. Specifically, when the atoms are arranged in the square $\square$ like the input, low energy is obtained, but due to the symmetry axis search, when the arrangement is rotated by 45 degrees and becomes rhombic $\diamond$, the hydrogen atoms are placed on the symmetry axis, which affects the symmetry operation, and high energy is obtained.

**Comment by sk888ks** [comment]
The conclusion is that we should include a stability analysis in each Hartree-Fock calculation, right?
Thanks for the suggestions. I will close the issue if there are no other suggestions or comments.

**Comment by verena-neufeld** [comment]
I think especially in systems with many HF solutions being close together, like this one as @susilehtola mentioned, it is not a bad idea. Good luck!
