### ISSUE TITLE
How can we get the mulliken analyze in KUCCSD calculation?

### ISSUE THREAD

**Issue by Jila66** [pyscf/pyscf#1776]
Hi

I'm using pyscf to do kuccsd calculation. now I need to have the mulliken analyze.
In uhf calculation for example we can use the mulliken_pop_uhf function. 
Is the such a function defined for this case?

Thanks

@sunqm

**Comment by fishjojo** [comment]
You can use pbc/cc/kuccsd_rdm.py to compute the 1-rdm, and use it to compute the Mulliken charge.

**Comment by verena-neufeld** [comment]
Hi @Jila66 , thanks for asking, has this been answered?

**Comment by Jila66** [comment]
> Hi @Jila66 , thanks for asking, has this been answered?

Hi
Sorry for late reply.

You must import some function first to it works

from pyscf.pbc.cc import KUCCSD
from pyscf.pbc.cc import kuccsd_rdm
from pyscf.pbc.cc.kuccsd_rdm import _gamma1_intermediates
from pyscf.pbc.cc.kuccsd_rdm import make_rdm1


Then it works. but I don't know how to use it to compute the Mulliken charge

**Comment by Jila66** [comment]
> > Hi @Jila66 , thanks for asking, has this been answered?
> 
> Hi Sorry for late reply.
> 
> You must import some function first to it works
> 
> from pyscf.pbc.cc import KUCCSD from pyscf.pbc.cc import kuccsd_rdm from pyscf.pbc.cc.kuccsd_rdm import _gamma1_intermediates from pyscf.pbc.cc.kuccsd_rdm import make_rdm1
> 
> Then it works. but I don't know how to use it to compute the Mulliken charge

Hi, 
Can anybody help me by this?
