### ISSUE TITLE
Incompatibility with latest scipy release (v1.11.0)

### ISSUE THREAD

**Issue by 1tnguyen** [pyscf/pyscf#1777]
Scipy version 1.11.0 removed `sym_pos` keyword of `scipy.linalg.solve` : https://docs.scipy.org/doc/scipy/release/1.11.0-notes.html#expired-deprecations

This caused an issue for this `cho_solve` method:
https://github.com/pyscf/pyscf/blob/485098119e4879acebfedc3f17d956a0c0377124/pyscf/lib/linalg_helper.py#L1464C16-L1464C34

**Comment by verena-neufeld** [comment]
Is this fixed by pull request #1771 ?

**Comment by 1tnguyen** [comment]
Yea, it is. Looking forward to getting the fix!
