### ISSUE TITLE
Scipy.linalg.solve -- sym_pos flag is deprecated and has been removed in scipy 1.11.0

### ISSUE THREAD

**Issue by chillenb** [pyscf/pyscf#1779]
https://github.com/pyscf/pyscf/blob/485098119e4879acebfedc3f17d956a0c0377124/pyscf/lib/linalg_helper.py#L1464

Scipy recommends replacing `sym_pos=True` with `assume_a='pos'`

**Comment by verena-neufeld** [comment]
Looks related to #1771

**Comment by chillenb** [comment]
You're right! Thanks
