### ISSUE TITLE
CCSD with localized orbitals

### ISSUE THREAD

**Issue by SoulokeSen** [pyscf/pyscf#1782]
Dear PYSCF developers,

I had a question about using localized orbitals as input in a CCSD calculation. When using the localized orbital (rotation amongst occupied-occupied and virtual-virtual orbitals) basis the Fock matrix  is not diagonal. So does the CC code implementation takes care of these off-diagonal Fock matrix elements ? The CCSD energy should in principle be invariant to unitary rotations among occupied and/or virtual orbitals.

Thank you for your help.

Souloke

**Comment by fishjojo** [comment]
CCSD works for noncanonical orbitals.

**Comment by SoulokeSen** [comment]
OK. Thanks.

**Comment by verena-neufeld** [comment]
Hi @SoulokeSen , thanks for posting the issue here. Has it been answered?

**Comment by SoulokeSen** [comment]
Hi, yes the CCSD implementation in PYSCF is invariant to occupied-occupied and virtual-virtual orbital rotations

**Comment by verena-neufeld** [comment]
Great, thanks! I think @SoulokeSen , @fishjojo , @sunqm , this issue can be closed then.
