### ISSUE TITLE
scipy 1.11 conflict

### ISSUE THREAD

**Issue by harrkee** [pyscf/pyscf#1783]
The latest scipy version removes the `sym_pos` keyword arg from `scipy.linalg.solve`, which causes problem for even the simplest of pyscf calculations, eg:
```
from pyscf.scf import RHF
from pyscf.gto import Mole

mol = Mole().build(
    atom="H 0 0 0; H 1 0 0",
    basis="sto3g"
)
RHF(mol).kernel()
```
returns:
```  
File "/Users/newuser/.pyenv/versions/py-inquanto-3.9/lib/python3.9/site-packages/pyscf/lib/linalg_helper.py", line 1465, in cho_solve
    return scipy.linalg.solve(a, b, sym_pos=True)
TypeError: solve() got an unexpected keyword argument 'sym_pos'
```
Produced with pyscf v2.2.1.

Scipy provide some warning of this change in their 1.10.1 docs [here](https://docs.scipy.org/doc/scipy-1.10.1/reference/generated/scipy.linalg.solve.html):

<img width="623" alt="Screenshot 2023-07-03 at 14 36 22" src="https://github.com/pyscf/pyscf/assets/102385244/935e926e-09fd-4c40-960a-0b424341cbd2">

**Comment by mkrompiec** [comment]
addressed by https://github.com/pyscf/pyscf/pull/1771 ?

**Comment by zc62** [comment]
Try current git HEAD, not a released version, should already be gone.

**Comment by harrkee** [comment]
Thanks @zc62, when do you expect the fix to be available with PyPI?

**Comment by fishjojo** [comment]
v2.3 has been released, which fixes the problem.
