### ISSUE TITLE
cannot handle scientific notation in DFT.xc

### ISSUE THREAD

**Issue by moolawooda** [pyscf/pyscf#1787]
When setting the `DFT.xc` attribute, the proportion of each component is stored in a string, for example, `ks.xc = f'{HF_X:} * HF + {LDA_X:} * LDA + {B88_X:} * B88, {LYP_C:} * LYP + {VWN_C:} * VWN'`. However, if the proportion is too small, Python will print it as the scientific notation format like `9.999e-5` in that string. Pyscf cannot handle this type of input and will crash.

**Comment by susilehtola** [comment]
> A fix on the userend would be to force the string to be generated as a float such as:
> 
> ```
> ks.xc = f'{HF_X:.10f} * HF + {LDA_X:.10f} * LDA + {B88_X:.10f} * B88, {LYP_C:.10f} * LYP + {VWN_C:.10f} * VWN'
> ```
> 
> where we are using only 10 decimal places.

Generally a better choice is scientific notation, use `{:.10e}` instead of `{:.10f}`.

**Comment by matthew-hennefarth** [comment]
> Generally a better choice is scientific notation, use `{:.10e}` instead of `{:.10f}`.

I agree that it is better, but that won't fix the problem in the current master branch since the xc parser has an issue with scientific notation numbers. PR #1788 allows scientific notation to be used tho.

**Comment by moolawooda** [comment]
When using libxc, this problem also exists.
