### ISSUE TITLE
Which coordinate dose the nabla operator respect to in moleintor?

### ISSUE THREAD

**Issue by Fadelis98** [pyscf/pyscf#1798]
I'm trying to understand the behavior of the nuclear grad calculation, but I found it a little bit confusing. In the moleintor, I see "int1e_kin" means (.5 \| p dot p\) , and p equals to $-i\nabla$, So the $\nabla$ here should be applied on the electron coordinates $r$.

However, in pyscf/grad/rhf.py those ints are used tho calculate the nuclear grad. For example,  get_hcore uses 'int1e_ipkin' and 'int1e_ipnuc', where 'ip' equals to $\nabla$, so the $\nabla$ contributed by 'ip' is applied to the atom coordinates.

Is there a general rule to determin the rule of the operator?

**Comment by MoleOrbitalHybridAnalyst** [comment]
I don't think either \nabla really acts on nuclear coordinates. The reason it is used in nuclear gradient is that applying \nabla_r on an atom-centered orbital \phi(r-R) is the same as -\nabla_R.

**Comment by Fadelis98** [comment]
> I don't think either \nabla really acts on nuclear coordinates. The reason it is used in nuclear gradient is that applying \nabla_r on an atom-centered orbital \phi(r-R) is the same as -\nabla_R.

Get it.
