### ISSUE TITLE
Turning off normalization for primitives

### ISSUE THREAD

**Issue by marvinfriede** [pyscf/pyscf#1800]
I have a special basis, in which I want to avoid this normalization of the primitive Gaussians:

https://github.com/pyscf/pyscf/blob/c6f9b462fca8dcaab633d7306fa6f5121a07c907/pyscf/gto/mole.py#L834

Is this possible? From https://github.com/pyscf/pyscf/issues/1353#issuecomment-1201660636 it does not seem like it.

<br>
<details>
<summary>Explanation: Why turn off normalization for primitives?</summary>

I am working with the basis set of GFN1-xTB. Here, the Hydrogen has a 1s and a 2s function. As the 2s function should imitate a polarization function, it is explicitly orthonormalized against the 1s function. So the 1s and 2s have zero overlap. The normalization in pyscf destroys this setup.

</details>

**Comment by sunqm** [comment]
```
from pyscf import gto
gto.NORMALIZE_GTO = False
```
or put this setting in `~/.pyscf_conf.py`
```
NORMALIZE_GTO = False
```

**Comment by sunqm** [comment]
This is required by the integral library. You need to modify the `mol._env` data directly, with code like
```
for bas_id in special_basis_list:
    adr = mol._bas[bas_id, gto.PTR_COEFF]
    nprim = mol.bas_nprim(bas_id)
    mol._env[adr:adr+nprim] = custom_contraction_coef
```

**Comment by marvinfriede** [comment]
Thanks for pointing me in the right direction. I had to include the sorting from [here](https://github.com/pyscf/pyscf/blob/88266d5eec783752c75615728978f4bfbd5b855f/pyscf/gto/mole.py#L918) to make it work.
I attached my final code, in case someone runs in the same issue.

<details>
<summary>Code</summary>

```python
bas_id = 0
for basis_add in mol.basis.values():
    for b in basis_add:
        b_coeff = np.array(sorted(list(b[1:]), reverse=True))
        expnts = b_coeff[:, 0]
        coeffs = b_coeff[:, 1]

        e_adr = mol._bas[bas_id, gto.PTR_EXP]
        c_adr = mol._bas[bas_id, gto.PTR_COEFF]
        nprim = mol.bas_nprim(bas_id)

        mol._env[e_adr : e_adr + nprim] = expnts
        mol._env[c_adr : c_adr + nprim] = coeffs

        bas_id += 1
```

</details>
