### ISSUE TITLE
Can't pickle PySCF object?

### ISSUE THREAD

**Issue by sunnowrun** [pyscf/pyscf#1801]
I want to save the PySCF variables to the file, but I when I run the code below, I got error and don't know how to solve it.
`import pyscf`
`import pickle`

`geom = 'Li 0 0 0; H 0 0 1'`
`basis = 'sto-3g'`
`mol = pyscf.gto.M(atom = geom, basis = basis)`

`with open ('filename', 'wb') as f:`
`	pickle.dump(mol, f)`
Error:
`Traceback (most recent call last):`
`  File "pyscf_usage.py", line 12, in <module>`
`    pickle.dump(mol, f)`
`TypeError: cannot pickle '_io.TextIOWrapper' object`

**Comment by hebrewsnabla** [comment]
You can use `pyscf.lib.chkfile.save_mol` to save mol object to a hdf5 file.

**Comment by sunnowrun** [comment]
But I also want to save mf and other results.
If I separately save these different type objects, the saved results will become very messy.
I want to save them in a consistent way, can I modified the mol/mf object make it suitable to pickle?

**Comment by hebrewsnabla** [comment]
> But I also want to save mf and other results. If I separately save these different type objects, the saved results will become very messy. I want to save them in a consistent way, can I modified the mol/mf object make it suitable to pickle?

`pyscf.scf.chkfile.dump_scf` saves the mol and some scf's arrays into one hdf5 file. This hdf5 file is interoperable so you can dump any other arrays into it with `lib.chkfile.save('chkfile', {'array_name': array})`

**Comment by sunnowrun** [comment]
> > But I also want to save mf and other results. If I separately save these different type objects, the saved results will become very messy. I want to save them in a consistent way, can I modified the mol/mf object make it suitable to pickle?
> 
> `pyscf.scf.chkfile.dump_scf` saves the mol and some scf's arrays into one hdf5 file. This hdf5 file is interoperable so you can dump any other arrays (or dict) into it with `lib.chkfile.save('chkfile', 'array_name', array)`

Why so inconvenient?

**Comment by hebrewsnabla** [comment]
I think that's convenient enough. Usually `dump_scf` is enough for dumping a scf object. Do you have anything else to be dumped?

**Comment by sunnowrun** [comment]
> I think that's convenient enough. Usually `dump_scf` is enough for dumping a scf object. Do you have anything else to be dumped?

For a LiH system, I want to calculate FCI results in different bond lengths, for benchmarks. I need to save mol, mf and FCI energy and vectors for different bond lengths.

**Comment by hebrewsnabla** [comment]
So you need one call to `dump_scf` and two calls to `lib.chkfile.save`. Three lines of code altogether.

**Comment by sunnowrun** [comment]
> So you need one call to `dump_scf` and two calls to `lib.chkfile.save`. Three lines of code altogether.

OK, I will try it. Thank you!

**Comment by sunqm** [comment]
> > > But I also want to save mf and other results. If I separately save these different type objects, the saved results will become very messy. I want to save them in a consistent way, can I modified the mol/mf object make it suitable to pickle?
> > 
> > 
> > `pyscf.scf.chkfile.dump_scf` saves the mol and some scf's arrays into one hdf5 file. This hdf5 file is interoperable so you can dump any other arrays (or dict) into it with `lib.chkfile.save('chkfile', 'array_name', array)`
> 
> Why so inconvenient?

pickle serialization is platform dependent, not transferable between different systems. Mole object can be serialized to a  json string `mol.dumps()`, which can be deserialized to an almost identical Mole object using `gto.loads(mol.dumps())`. dumps and loads function for other classes were not implemented. They can be added in the future.

**Comment by sunnowrun** [comment]
> > > > But I also want to save mf and other results. If I separately save these different type objects, the saved results will become very messy. I want to save them in a consistent way, can I modified the mol/mf object make it suitable to pickle?
> > > 
> > > 
> > > `pyscf.scf.chkfile.dump_scf` saves the mol and some scf's arrays into one hdf5 file. This hdf5 file is interoperable so you can dump any other arrays (or dict) into it with `lib.chkfile.save('chkfile', 'array_name', array)`
> > 
> > 
> > Why so inconvenient?
> 
> pickle serialization is platform dependent, not transferable between different systems. Mole object can be serialized to a json string `mol.dumps()`, which can be deserialized to an almost identical Mole object using `gto.loads(mol.dumps())`. dumps and loads function for other classes were not implemented. They can be added in the future.

OK, thank you!

**Comment by chillenb** [comment]
This problem can be fixed by defining `__getstate__` and `__setstate__` for `Mole` objects, preferably using the existing `loads` and `dumps` methods. I will make a PR with this solution for everyone to consider.
