### ISSUE TITLE
Selected CI gives wrong results for a CAS of (2,2)

### ISSUE THREAD

**Issue by ashutoshvt** [pyscf/pyscf#1808]
Dear developers,

I was trying to use selected CI as my CASCI solver by looking at the following example: https://github.com/pyscf/pyscf.github.io/blob/master/examples/mcscf/50-casscf_with_selected_ci.py

However, the selected CI results were wrong when I choose a CAS of (2,2):
```
from pyscf import gto, scf, mcscf, fci

b = 1.2
mol = gto.M(
    atom = 'N 0 0 0; N 0 0 %f'%b,
    basis = 'cc-pvdz',
)
mf = scf.RHF(mol).run()
mc = mcscf.CASCI(mf, 2, 2).run()

#
# Use SCI (Selected CI) to replace fcisolver
#
mc = mcscf.CASCI(mf, 2, 2)
mc.fcisolver = fci.SCI(mol)
mc.kernel() 
```

Here are the results. I am using pyscf version `2.1.1`
```
converged SCF energy = -108.914051975052

CASCI E = -108.94356411985  E(CI) = -1.71486588690826  S^2 = 0.0000000

CASCI E = -108.914051975052  E(CI) = -1.68535374211038  S^2 = 0.0000000
```
The selected CI seems to have only the doubly occupied determinant and misses the other doubly excited determinant. I know this is an edge case but thought of bringing this to your attention nevertheless. Thanks!

**Comment by sunqm** [comment]
Bug fixed in #1845
