### ISSUE TITLE
CASSCF orbital energies for both spin channel

### ISSUE THREAD

**Issue by kaitrepte** [pyscf/pyscf#1809]
Dear PySCF developers,

I am trying to obtain the orbital energies for an O atom from CASSCF, 
see minimal example below

from pyscf import gto, mcscf
mol = gto.M(
    atom = 'O 0 0 0',
    basis = 'pc-1',
    spin = 2
)
myhf = mol.UHF()
myhf.kernel()
mycas = mcscf.CASSCF(myhf, 13, (5,3))
mycas.kernel()
print(mycas.mo_energy)

However, upon printing the mo_energy I always only end up with the spin-up channel (5 occupied orbitals).
[-20.67136201  -1.2503043   -0.27449597  -0.27449597  -0.56553371
   1.01464001   1.01464001   1.00839961   1.433521     2.45877544
   2.45877545   2.47128126   2.47128126   2.462906  ]

Is there any way to get the orbital energies of the other spin channel?

Best,
Kai

**Comment by JangidBhavnesh** [comment]
I think these orbital energies correspond to molecular orbital energies [not spin up/spin down]. You are starting with UHF, where you will see the spin-up & down orbital energies and occupancy. Using UHF as the initial guess in CASSCF, PYSCF is taking one of spin as the initial guess, but CASSCF will produce results in the MO basis. 

**You can use the " mycas.nat_orb = True " to see the occupancy of orbital, which might be helpful as that will tell you which orbitals are doubly/singly occupied.**

**Comment by kaitrepte** [comment]
I see. Thank you for your comment.
It appears that -20.67136201 -1.2503043 -0.56553371 are double-occupied, and  -0.27449597 -0.27449597 are single-occupied.
Now I am just wondering how "good" these orbital energies really are.

Looking at the highest occupied Hartee-Fock orbitals, it has an 
energy of about -14.2 eV (reasonably close to the ionization potential of O, which is 13.6 eV).
However, according to the MO energies from CASSCF we get a highest occupied orbital of -7.5 eV,
much worse than Hartree-Fock. Would one expect the orbital energies in CASSCF to be "better" than Hartree-Fock?

Or can we not make such an assessement due to the fact that CASSCF only uses one of the spin-channels?

**Comment by JangidBhavnesh** [comment]
The IP for O atom which is around -14.2 eV at UHF is based on Koopman's theorem.  However I am not sure how applicable is this theorem for  CASSCF orbitals or Multi-reference orbitals, because these orbitals are being optimized under different condition. 
In case if you are interested in calculating the IP using CASSCF you have to do two calculations
O  and O+ ion and difference of that will be the IP.

**Comment by hebrewsnabla** [comment]
CASSCF doesn't have "orbital energies". The `mo_energy` acquired from CASSCF object is just the expectation values of fock operator of MOs, not really orbital energies.

**Comment by kaitrepte** [comment]
Ok thank you for clarifying.
