### ISSUE TITLE
Full-CI energies for larger basis sets

### ISSUE THREAD

**Issue by kaitrepte** [pyscf/pyscf#1810]
Dear PySCF developers,

I tried calculating the energy of the H atom
using full CI, see example below. 
```
import pyscf
for basis in ['aug-pc-0','aug-pc-1','aug-pc-2','aug-pc-3','aug-pc-4']:
    mol = pyscf.M(
        atom = 'H 0 0 0',  # in Angstrom
        basis = basis,
        spin = 1,
        verbose = 0
    )
    myuhf    = mol.UHF().run()
    cisolver = pyscf.fci.FCI(myuhf)
    cisolver.kernel()
    print(f'{basis}  E(UHF) = {myuhf.e_tot:15.12f} E_h  E(FCI) = {cisolver.e_tot:15.12f} E_h')
```
The energy
should be the same as the underlying HF calculation.
However, going to large basis sets (here: aug-pc-4),
the full CI energy deviates drastically from HF.

aug-pc-0  E(UHF) = -0.496368027479 E_h  E(FCI) = -0.496368027479 E_h
aug-pc-1  E(UHF) = -0.498645346213 E_h  E(FCI) = -0.498645346213 E_h
aug-pc-2  E(UHF) = -0.499884212754 E_h  E(FCI) = -0.499884212754 E_h
aug-pc-3  E(UHF) = -0.499997292927 E_h  E(FCI) = -0.499997292927 E_h
**aug-pc-4  E(UHF) = -0.499999573300 E_h  E(FCI) = -0.609830900422 E_h**

Best,
Kai

**Comment by sunqm** [comment]
Thanks for reporting the bug. It is fixed in the latest commit
