### ISSUE TITLE
Incorrect dimension of ERI tensor in PBC calculations

### ISSUE THREAD

**Issue by WenkaiChen** [pyscf/pyscf#1811]
Dear pyscf developers and users,

I want to obtain the two-electron integral in PBC calculations via pyscf.
I found that there is an example file in [https://github.com/pyscf/pyscf/blob/88266d5eec783752c75615728978f4bfbd5b855f/examples/pbc/30-ao_integrals.py](url)

However, when I run this part of the example, 

`‘’‘`
`In PBC, 2e integrals are all computed with 3-ceter integrals, ie from`
`density fitting module.  Without kpts argument, the DF gives gamma point AO`
`2e-integrals.  Permutation symmetry is not considered`
`’‘’`
`mydf = df.FFTDF(cell)`
`eri = mydf.get_eri()`
`print('ERI shape (%d,%d)' % eri.shape)`

the shape of eri returns (528,528)

To my knowledge, the dimension of 2e-integral is (32,32,32,32), which is not (528,528).

where am I wrong? How can I obtain the 2e-integral in PBC calculations (in particular at GAMMA point)?

Additionally, I have encountered memory issues with large systems where the dimension of the ERI tensor becomes too huge to be saved in memory. In such cases, is it possible to calculate only a specific part of the ERI tensor? If so, how can I specify the four indices (ij|kl) of the ERI tensor?

I apologize for any inconvenience and thank you all for your assistance!

**Comment by zhcui** [comment]
The integral at Gamma has 4-fold symmetry, ij are the lower triangular part, so it has dimension nao*(nao+1)//2. You can use ao2mo.restore(1, eri, nao) to get the 1-fold symmetry ERI.

If you can get ERI at arbitrary k, you can use Fourier transform to get some part of the supercell integral.
For example, in the embedding codes, the unit cell ERI can be constructed like this:
https://github.com/gkclab/libdmet_preview/blob/6089d5600fde7e51c432bd94270f88a067e7f54a/libdmet/basis_transform/eri_transform.py#L87

**Comment by WenkaiChen** [comment]
> The integral at Gamma has 4-fold symmetry, ij are the lower triangular part, so it has dimension nao*(nao+1)//2. You can use ao2mo.restore(1, eri, nao) to get the 1-fold symmetry ERI.
> 
> If you can get ERI at arbitrary k, you can use Fourier transform to get some part of the supercell integral. For example, in the embedding codes, the unit cell ERI can be constructed like this: https://github.com/gkclab/libdmet_preview/blob/6089d5600fde7e51c432bd94270f88a067e7f54a/libdmet/basis_transform/eri_transform.py#L87

Thanks for your reply, ao2mo.restore works well!
However, the size of eri is huge when the number of basis set becomes large. Can I just calculate part of the eri (ij|kl) with specific i,j,k,l in PBC calculations? The function df.get_eri() could not use the keyword shls_slice. Thanks again!

**Comment by zhcui** [comment]
Unfortunately, I don't think the PBC code supports slicing over shells. One possible way is that you may truncate the basis when you set up the cell and then generate integrals.

**Comment by verena-neufeld** [comment]
Hi @WenkaiChen , thanks for your question. Has it been answered?

**Comment by WenkaiChen** [comment]
> Hi @WenkaiChen , thanks for your question. Has it been answered?

Actually not.  Nevertheless, the system I am interested in is only considered Gamma point, thus, I have obtained the ERI from non-periodic version from pyscf. Thus, the problem has been solved. I will close this issue. Thanks for your attention.
