### ISSUE TITLE
Enforcing symmetry of T2 cluster operator

### ISSUE THREAD

**Issue by jorgecga** [pyscf/pyscf#1812]
After running an RCCSD calculation, the T2 operator doesn't look like what one would expect. Specifically, the arrays t2[i, i, :, :] have several non-negligible elements. Moreover, computing the c_n coefficients corresponding to the FCI expansion yields quite different results than FCI itself, even for very small systems.

 Is there a way to make RCCSD enforce the expected 8fold symmetry on the T2 amplitudes, or at least a way to transform the provided T2 into the expected one? 

I assumed that the latter could be accomplished with 'amplitudes_to_vector' followed by 'vector_to_amplitudes_s4', but this approach only truncates the array trivially; thus, the soution loses plenty of meaningful information.

**Comment by verena-neufeld** [comment]
Hi @jorgecga thanks for posting your question. Can you try running your calculation with the class in pyscf/cc/rccsd.py not pyscf/cc/ccsd.py ? That stores the t2 in a four Index array and should respect those symmetries (for non complex systems).

**Comment by jorgecga** [comment]
Hi @verena-neufeld. Thank you for your response.
I've tried 'cc.RCCSD' with multiple systems, yet the 't2' array keeps looking wrong.
It has the symmetry t2[i, j, a, b] == t2[j, i, b, a], but that's pretty much it.

**Comment by verena-neufeld** [comment]
Sorry, what I said wasn’t quite true. For spin orbital gccsd implantation, you do have t[ijab] = -t[jiab] etc. However, in the spatial rccsd implantation, the first and third Index share the same spin, say spin up, and the second and fourth index are then spin down. Since t[i_up j_down a_up b_down] != t[j_up i_down a_up b_down] in general, you don’t have that symmetry anymore.

**Comment by verena-neufeld** [comment]
Hi @jorgecga , did this answer your question?

**Comment by jorgecga** [comment]
> Hi @jorgecga , did this answer your question?

Hi, it didn't. But I realized I needed something different at the end.

**Comment by sunqm** [comment]
Please feel free to reopen the issue.
