### ISSUE TITLE
Is there any FCI solver in the pyscf for spin-Hamiltonian?

### ISSUE THREAD

**Issue by JangidBhavnesh** [pyscf/pyscf#1816]

**Comment by sunqm** [comment]
The FCI module supports two types of Hamiltonian: spin restricted (module `fci.direct_spin1` and `fci.direct_nosym`) and spin unrestricted (the `fci.direct_uhf` module). The spin restricted code requires a matrix of one-electron integrals and a tensor of two-electron integrals as input. The spin unrestricted code requires two matrices (h1aa, h1bb) for the one-electron interaction and three tensors (h2aaaa, h2aabb, h2bbbb) for the two-electron part. If you can formulate the spin-Hamiltonian to either case, it can be solved by the FCI solver in pyscf

**Comment by JangidBhavnesh** [comment]
Got it.

Thanks
