### ISSUE TITLE
CCSD excitation energies for H atom

### ISSUE THREAD

**Issue by kaitrepte** [pyscf/pyscf#1822]
Dear PySCF developers,

I am trying to calculate the excitation energies for a H atom using EOM-CCSD
```python
import pyscf
mol = pyscf.M(
    atom = 'H 0 0 0',
    basis = 'aug-pc-1',
    spin = 1)
mf    = mol.UHF().run()
mycc  = mf.CCSD().run()
E_exc = mycc.eeccsd(nroots=1)[0]
```
However, I obtain the following error:
```md
Traceback (most recent call last):
  File "/data/calculations/pyscf_calcs/wavefunction_stuff/ccsdt_excitation.py", line 8, in <module>
    E_exc = mycc.eeccsd(nroots=1)[0]
  File "/home/kai/.local/lib/python3.10/site-packages/pyscf/cc/uccsd.py", line 714, in eeccsd
    return eom_uccsd.EOMEE(self).kernel(nroots, koopmans, guess, eris)
  File "/home/kai/.local/lib/python3.10/site-packages/pyscf/cc/eom_uccsd.py", line 915, in eeccsd
    if imds is None: imds = eom.make_imds(eris)
  File "/home/kai/.local/lib/python3.10/site-packages/pyscf/cc/eom_uccsd.py", line 1847, in make_imds
    imds.make_ee()
  File "/home/kai/.local/lib/python3.10/site-packages/pyscf/cc/eom_uccsd.py", line 2478, in make_ee
    for p0, p1 in lib.prange(0, nvirb, noccb):
  File "/home/kai/.local/lib/python3.10/site-packages/pyscf/lib/misc.py", line 300, in prange
    for i in range(start, end, step):
ValueError: range() arg 3 must not be zero
```

Any idea how to resolve this?
Best,
Kai

**Comment by susilehtola** [comment]
H atom states and excitation energies can, of course, be obtained by diagonalizing the core Hamiltonian, but it is a good thing to torture the code!

H atom is a one-electron system, and it has no doubles amplitudes. I assume this is the issue. The H atom is also fully spin polarized; there are no beta electrons. Running triplet He will reveal if this is another issue.

**Comment by kaitrepte** [comment]
Hi.
That makes sense. I assumed it has something to do with the fact that the down channel is unoccupied. 
And yes, there can be no double excitations. 
Any way to only calculate single excitations only?

**Comment by 1234zou** [comment]
You can use the CASCI or CIS method to calculate the excitation energies. The CASCI input is
```
from pyscf import gto, scf, mcscf

mol = gto.M(atom='H 0.0 0.0 0.0',spin=1,basis='aug-pc-1')

mf = scf.ROHF(mol)
mf.verbose = 4
mf.kernel()

mc = mcscf.CASCI(mf, 9, (1,0))
mc.fcisolver.nroots = 9
mc.kernel()
```
When `aug-pc-1` is used, there are 9 MOs in total, so the CASCI(9o1,e) is equal to Full CI for H atom. Moreover, you will obtain electronic energies of all 9 doublets.

The CIS example can be found in [31-energy_transfer_coupling_matrix.py](https://github.com/pyscf/pyscf/blob/master/examples/tddft/31-energy_transfer_coupling_matrix.py). However, this example seems not to work for an atom with no beta electrons. Maybe PySCF developers would like to look into it in detail.
