### ISSUE TITLE
Handling of the divergent terms of the local part of the pseudopotential and Hartree potential in PBC DFT calculation?

### ISSUE THREAD

**Issue by luna-component** [pyscf/pyscf#1825]
I hope it is ok that I ask this question here.
I have been running periodic DFT calculations using GTH pseudopotentials and PW density fitting, and need to know where/how the divergent terms are handled in the code.

I have been reading this paper:
McClain, James, et al. "Gaussian-based coupled-cluster theory for the ground-state and band structure of solids." Journal of chemical theory and computation 13.3 (2017): 1209-1218.

The authors, i.a., briefly discuss handling of the divergent terms (at G=0) of the local part of the psudopotential and Hartree potential in periodic HF calculations. My understanding is that this is done by adding and subtracting a uniform background charge, which is handled by the additional matrix element:
V^{L+J}_{\mu\nu}(k) = S_{\mu\nu}(k) / \Omega  \sum_I \alpha_I        (eq. 19 in the aforementioned paper)
where S is the overlap matrix, Omega is the cell volume and the ion-specific parameter alpha_I = \int dr (v^L_I + Z_I e^2 / r), where v^L_I  is the local part of the pseudopotential coming from ion I.

My question is: where exactly in the code this term is handled?
Is it computed when calculating the electron-nuclear attraction term only?
Or split between the nuclear-attraction term and Coulomb term?
So far it looks to me as if the former is done, but I'm definitely not 100% sure..
I appreciate if someone can advice me on this/give some pointers.

Cheers
./Luna

**Comment by luna-component** [comment]
@pablomazo MAybe you could  I hope it is okay to tag you in this.

**Comment by luna-component** [comment]
@tberkel Hope it is ok to tag you here. 
In the meantime, I think I figured out this is handled in the nuclear-electron term of total energy, at least when the PW density fitting is used for ERIs. Is it handled in nuclear-electron attraction term only when Gaussian density fitting is done as well?

**Comment by tberkel** [comment]
Hi, no problem. Yes, within DFT, the el-nuc and the Hartree el-el interactions are separately divergent, but their sum is not, by charge neutrality. Equivalently, you can think of this as adding a positive and negative uniform charge density (which cancel one another) and using them separately to make the el-nuc and el-el terms non-divergent.

With pseudopotentials, the functional form of the short-range part differs from a bare Coulomb potential, which produces the alpha terms or V^{L+J}. In PySCF, this term is always handled in the el-nuc interaction, so it shows up in `get_nuc` which enters `hcore`.

To find where this is treated in the code, you can follow the `get_pp` functions for the various DF options.

For FFTDF, it is treated here: https://github.com/pyscf/pyscf/blob/master/pyscf/pbc/gto/pseudo/pp_int.py#L61
which is called from here (after passing through a couple other functions): https://github.com/pyscf/pyscf/blob/master/pyscf/pbc/df/fft.py#L74

For GDF, I think it is treated here: https://github.com/pyscf/pyscf/blob/master/pyscf/pbc/df/gdf_builder.py#L575

**Comment by luna-component** [comment]
Thanks sm for confirming this! It was, in the end, the GDF handling of these that I was unsure of.

**Comment by luna-component** [comment]
@tberkel 
 P.S. Just to make sure I understand correctly: 
 (what would correspond to) the adding of a positive and negative charge densities (to treat the divergent terms in el-el and el-nuc) is handled collectively in the el-nuc part of the code only (get_nuc)? 
I.e. there's nothing equivalent in the el-el part of the code?

**Comment by tberkel** [comment]
The equivalent part in the el-el part of the code is that the G=0 term is completely neglected in the Hartree energy. As a reminder, if not for the pseudopotential, then all we would have to do is neglect G=0 in both the Hartree and el-nuc energies, i.e., their divergences would exactly cancel one another. But because the pseudopotential isn't exactly 1/r, the divergences only cancel up to a constant, and we choose to put that constant into the el-nuc energy.

**Comment by luna-component** [comment]
Thank you!
