### ISSUE TITLE
Unphysical energy in multicollinear dft

### ISSUE THREAD

**Issue by xubwa** [pyscf/pyscf#1832]
Hi, I tried out the multicollinear functional in pyscf interfaced with mcfun recently. The energy I got for a few simple systems deviates from their conventional dft energy by tens to hunders of Hartree as described in mcfun's repository https://github.com/Multi-collinear/MCfun/issues/4. All tests related to mcfun gks also failed. It's not reflected in pyscf's ci/cd process probably due to if mcfun is not installed then these test will be skipped.

**Comment by Haskiy** [comment]
We have tested the mcfun package you provided at a docker image somewhere, and we can not represent the problem you clarified. It should be noted that we used the python 3.7 base image rather than the slim image.

**Comment by sunqm** [comment]
Related to #1878 . Should be fixed with new MCfun.
