### ISSUE TITLE
python implementation for calculating link indexes in FCI calculation

### ISSUE THREAD

**Issue by SoulokeSen** [pyscf/pyscf#1836]
Dear PYSCF developers,

Is there any existing python implementation for calculating the link index table for each of the CI strings (alpha or beta) in an CI calculation ?

thanks,
Souloke

**Comment by sunqm** [comment]
Here is an example https://github.com/pyscf/pyscf/blob/master/pyscf/fci/test/test_cistring.py#L53

**Comment by SoulokeSen** [comment]
@sunqm  thank you for the example.

**Comment by verena-neufeld** [comment]
Hi @SoulokeSen , thanks for asking. Has your question been answered?

**Comment by sunqm** [comment]
Feel free to reopen
