### ISSUE TITLE
Differences in energies of Carbon atom with and without symmetry enabled

### ISSUE THREAD

**Issue by IgorSawicki** [pyscf/pyscf#1837]
Hello!
When conducting my research I accidently found that energies of Carbon atom differ from each other when run with and without symmetry enabled. I tested a few other restricted and unrestricted cases and put them in the table down below. I have run the calculations for Carbon on two different verions of pyscf, the results do not change much. The difference is small but significant since it is around 1 kcal/mol.
![obraz_2023-08-17_164036709](https://github.com/pyscf/pyscf/assets/142509046/a70e8b86-f5ea-41e8-9b8c-57d56b666a96)

Here is an example of code I used for Carbon atom.
```python
from pyscf import gto, scf, mp

mol = gto.M(atom=f'''
C  .000000  .000000   .000000

''',
spin=2,
charge=0,
basis="cc-pVTZ", cart=False, symmetry=True)

mol.build()
mol.verbose = 4

uhf_mf = scf.UHF(mol)

uhf_mf.scf()
Escf = uhf_mf.e_tot

mp.UMP2(uhf_mf).run()

print("HF energy:", Escf)
``` 

I will be greatful for any information on the issue. Maybe it is something silly that I don't see?

**Comment by susilehtola** [comment]
The reason you see differences is symmetry breaking. In contrast, nitrogen and neon have (half)closed shells and do not cause issues. The single-determinant description used in PySCF is a bad approximation to the real atom whose wave function contains many determinants.

**Comment by IgorSawicki** [comment]
> 

Okay I understand what You mean but why would it matter if in both cases we calculate the energy for one particular configuration. When the same calculation is done via PSI4, in both cases the energy is the same (as it should be in my opinion). Any additional determinants are not added there also.

**Comment by tberkel** [comment]
With symmetry=True, the SCF won't converge, for the reason Susi mentions:
there is no way to place 2 electrons into 3 orbitals while maintaining
spherical symmetry. So the energy you're analyzing shouldn't be trusted. I
can't speak to what Psi4 is doing in this case.

**Comment by tberkel** [comment]
Note that my response assumes spherical basis functions. If you use `cart=True`, it seems to converge and the symmetric and non-symmetric UHF calculations agree.

**Comment by susilehtola** [comment]
OK so PySCF gives -37.6879204880635 with symmetry and -37.6915691727568 without. Psi4 gives -37.69156917270058 both with and without symmetry.

However, Psi4 does not have atomic symmetry; it only uses D2h symmetry. If you set `symmetry = 'D2h'` in the input, you get the same energy as without symmetry.

My assumption is that the calculation just converges onto the wrong occupations. Atomic and diatomic calculations are really hard in this respect.

**Comment by verena-neufeld** [comment]
Hi @IgorSawicki , thanks for raising this issue. Has it been resolved?

**Comment by sunqm** [comment]
Feel free to reopen
