### ISSUE TITLE
strange behavior of init_guess_breaksym

### ISSUE THREAD

**Issue by theonov13** [pyscf/pyscf#1839]
Hi, 

I'm wondering if the breaking symmetry option 

https://github.com/pyscf/pyscf/blob/master/pyscf/scf/uhf.py#L29
https://github.com/pyscf/pyscf/blob/master/pyscf/scf/uhf.py#L773

works as it is supposed to do. 
I would propose not to turn on the option by default 
for the initial density matrix methods. 
For augmented basis sets, e.g., aug-pc-n (n=1,2..), 
the number of electrons in the beta channel explodes 
using MINAO with `init_guess_breaksym=True`. 
The problem is reproducible with all 2.X.Y PySCF versions. 
For benzene, this leads already to significant convergence issues. 

Please see the attached script to check to problem yourself. 

**Tab. 1 initial_guess_dm=True, PySCF version: 2.3.0**
| basis| N$`_{elec}`$(from initial guess) = (N$`_{\alpha}`$, N$`_{\beta}`$)  |
| :--: | :-----------------: |
| pc-0 | (20.951768099569655, 20.91592508353395) |
| pc-1 | (20.992586040795963, 22.024225871340562) | 
| pc-2 | (20.99925998574021, 20.614775142071956) | 
| aug-pc-0 | (20.964939403069046, 24.754095109846062) | 
| aug-pc-1 | (20.996679459866204, 39.278482611398196) | 
| aug-pc-2 | (20.99947479330699, 352.8876628321081)| 

**Tab. 2 initial_guess_dm=False, PySCF version: 2.3.0**
| basis| N$`_{elec}`$(from initial guess) = (N$`_{\alpha}`$, N$`_{\beta}`$)  |
| :--: | :-----------------: |
| pc-0 | (20.951768099569655, 20.951768099569655)| 
| pc-1 | (20.992586040795963, 20.992586040795963) | 
| pc-2 | (20.99925998574021, 20.99925998574021) |
| aug-pc-0 | (20.964939403069046, 20.964939403069046)| 
| aug-pc-1 | (20.996679459866204, 20.996679459866204)| 
| aug-pc-2 | (20.99947479330699, 20.99947479330699) | 

```python=
import pyscf
from pyscf import gto, scf


def dft(basis="pc-0",init_guess_breaksym=True):
    mol = gto.M(atom='''
C       0.000000000000000      1.391976000000000      0.000000000000000
C       1.205486000000000      0.695988000000000      0.000000000000000
C       1.205486000000000     -0.695988000000000      0.000000000000000
C       0.000000000000000     -1.391976000000000      0.000000000000000
C      -1.205486000000000     -0.695988000000000      0.000000000000000
C      -1.205486000000000      0.695988000000000      0.000000000000000
H       0.000000000000000      2.472230000000000      0.000000000000000
H       2.141014000000000      1.236115000000000      0.000000000000000
H       2.141014000000000     -1.236115000000000      0.000000000000000
H       0.000000000000000     -2.472230000000000      0.000000000000000
H      -2.141014000000000     -1.236115000000000      0.000000000000000
H      -2.141014000000000      1.236115000000000      0.000000000000000
''')

    mol.verbose = 9
    mol.basis = basis
    mol.output = "dft.log"
    mol.build()
    mf = scf.UKS(mol)
    mf.init_guess_breaksym = init_guess_breaksym
    mf.max_cycle = 0
    mf.xc = "spw92"
    mf.conv_tol = 1e-8
    mf.grids.level = 7
    mf.grids.prune = None
    mf.grids.build()
    # mf.init_guess = "vsap"
    edft = mf.kernel()

def main():
    print(f"PySCF version: {pyscf.__version__}")
    dft(basis="aug-pc-1",init_guess_breaksym=True)

if __name__ == '__main__':
    main()

```

Best, 
Wanja, Kai, and Sebastian

**Comment by susilehtola** [comment]
The problem is just that the density matrix spin symmetry breaking code is.. not very smart.

https://github.com/pyscf/pyscf/blob/4c0acff4a74a9b25c16c4c0714b60d29876d51f5/pyscf/scf/uhf.py#L124

```
def _break_dm_spin_symm(mol, dm):
    dma, dmb = dm
    # For spin polarized system, no need to manually break spin symmetry
    if mol.spin == 0 and abs(dma - dmb).max() < 1e-2:
        #remove off-diagonal part of beta DM
        dmb = numpy.zeros_like(dma)
        for b0, b1, p0, p1 in mol.aoslice_by_atom():
            dmb[...,p0:p1,p0:p1] = dma[...,p0:p1,p0:p1]
    return dma, dmb
```
What this code does is remove all interatomic blocks of the beta density matrix, which unsurprisingly leads to terrible results especially in augmented basis sets. A better option is to simply rescale the alpha and beta density matrices, which has the same effect of breaking the spin symmetry while not utterly destroying the quality of the guess.

**Comment by sunqm** [comment]
A new symmetry breaking initial guess is available. Setting the `init_guess_breaksym = 2` for UHF object will use the initial guess proposed by @susilehtola  (#1841 ). It can be configured globally, by adding the line
```
scf_uhf_init_guess_breaksym = 2
```
in the `pyscf_conf.py` (see https://pyscf.org/design.html#global-configurations ).

This initial guess treatment can be set to default in the future release.
