### ISSUE TITLE
Performing 1 SCF step of a B3LYP calculation

### ISSUE THREAD

**Issue by AdamCoxson** [pyscf/pyscf#1847]
Hi,

I want to take a density matrix, give it to the DFT.SCF driver to perform **one** cycle of SCF, not the whole run, and then return the Fock matrix. Shown below is the equivalent HF calculation to what I want, found in the [source code](https://pyscf.org/_modules/pyscf/scf/hf.html):

```
# Skip SCF iterations. Compute only the total energy of the initial density
if mf.max_cycle <= 0:
    fock = mf.get_fock(h1e, s1e, vhf, dm)  # = h1e + vhf, no DIIS
    mo_energy, mo_coeff = mf.eig(fock, s1e)
    mo_occ = mf.get_occ(mo_energy, mo_coeff)
    return scf_conv, e_tot, mo_energy, mo_coeff, mo_occ
```
But I want to do this for a B3LYP calculation where I provide a geometry and a density matrix. I have performed B3LYP/3-21G* calculations via Gaussian 16 and saved all the density and Fock matrices for all steps of SCF, so I can use these to compare. For the below tests, I set my input density matrix to the dm from the 1st SCF cycle of my g16 data. So the Fock matrix I calculate from PySCF should be similar to the Fock matrix for the 2nd step of the G16 data.

This is what I currently have:

```
import pyscf
from pyscf import dft, scf, gto

# input_density_matrix = dm in AO basis from previous calculations via G16
# geom= Elements and geometry from G16

mol = gto.M(
    atom = geom,  # in Angstrom
    basis = '3-21g',
    symmetry = False,
    unit = 'Angstrom')

mf = dft.RKS(mol) # Perform a single step of SCF for given dm via kernel driver
mf.xc = 'b3lyp'
mf.max_cycle=0
mf.kernel(dm0=input_density_mat)
F1=mf.get_fock()

mf2 = dft.RKS(mol) # Perform a single step of SCF for given dm via scf.get_fock()
mf2.xc = 'b3lyp'
F2=mf2.get_fock(dm=input_density_mat)

mf3 = dft.RKS(mol) # Perform full SCF for given dm
mf3.xc = 'b3lyp'
mf3.conv_tol=1e-12
mf3.kernel(dm0=input_density_mat)
F3=mf3.get_fock()
```

When I set the input_density_matrix to the density matrix from the 1st SCF cycle of my G16 data, I hoped that I could perform one step using the above PySCF functions and get a Fock matrix that matches the Fock matrix for the 2nd SCF cycle of my G16 data. However, F1 and F2 are very different, which I don't understand. Don't they both calculate the Fock matrix for the given dm using one cycle of B3LYP? Or does get_fock() inherit from the base SCF class in a strange way?

Furthermore, F3 should match or at least be similar to the converged Fock matrix from my G16 data, but it differs by a significant margin (Unless I haven't set the tolerances right, G16 uses dm RMS tolerance of 1e-6 whereas PySCF uses total energy devation tolerance of 1e-10). I suppose there would be discrepancies between how PySCF and G16 perform the convergence calculations (algorithms used to speed up convergence and whatnot) and hence get two different, but equally viable, converged Fock matrices. 

If anyone can spot something I've got wrong with the code or explain the different mechanics behind F1 and F2, I would greatly appreciate it.

Kind regards,
Adam

**Comment by MoleOrbitalHybridAnalyst** [comment]
F1 does a Fock build with the density after one diagonalization while F2 builds Fock using your input density.
Could you please check if using b3lypg gives you the same converged Fock as Gaussian? I believe Gaussian uses a different implementation from PySCF, and b3lypg is how you trigger to use the same as Gaussian.

**Comment by hebrewsnabla** [comment]
> Furthermore, F3 should match or at least be similar to the converged Fock matrix from my G16 data, but it differs by a significant margin (Unless I haven't set the tolerances right, G16 uses dm RMS tolerance of 1e-6 whereas PySCF uses total energy devation tolerance of 1e-10). I suppose there would be discrepancies between how PySCF and G16 perform the convergence calculations (algorithms used to speed up convergence and whatnot) and hence get two different, but equally viable, converged Fock matrices.

Gaussian and PySCF have different convention in basis function order, so if you pass Gaussian's dm to PySCF directly, the calculated Fock is meaningless -- but it may be occasionally right since 3-21g is very small.

**Comment by hebrewsnabla** [comment]
> F1 does a Fock build with the density after one diagonalization while F2 builds Fock using your input density. Could you please check if using b3lypg gives you the same converged Fock as Gaussian? I believe Gaussian uses a different implementation from PySCF, and b3lypg is how you trigger to use the same as Gaussian.

Since version 2.3.0, b3lyp is the same as b3lypg. In previous versions they are different.

**Comment by susilehtola** [comment]
I am not sure I am following, however...

> But I want to do this for a B3LYP calculation where I provide a geometry and a density matrix. I have performed B3LYP/3-21G* calculations via Gaussian 16 and saved all the density and Fock matrices for all steps of SCF, so I can use these to compare. For the below tests, I set my input density matrix to the dm from the 1st SCF cycle of my g16 data. So the Fock matrix I calculate from PySCF should be similar to the Fock matrix for the 2nd step of the G16 data.

you seem to be assuming that Gaussian does a pure Roothaan step, without any EDIIS+DIIS acceleration or the use of level shifts.

**Comment by susilehtola** [comment]
Do you get full agreement with Hartree-Fock?

**Comment by AdamCoxson** [comment]
@hebrewsnabla 

`Gaussian and PySCF have different convention in basis function order, so if you pass Gaussian's dm to PySCF directly, the calculated Fock is meaningless -- but it may be occasionally right since 3-21g is very small.`

Not entirely sure what you mean by this, but is there a way to format the G16 density matrix to have the same convention as PySCF?

@susilehtola I figured there are loads of different options that I would need to set to make the PySCF calculation consistent with Gaussian, just not entirely sure which options those include, plus there is another disconnect as I'm not providing previous Fock matrices for any extrapolation-type algorithms that Gaussian would perform in a full SCF procedure. I'll give Hartree Fock a go and see if the two softwares are similar.

**Comment by hebrewsnabla** [comment]
> but is there a way to format the G16 density matrix to have the same convention as PySCF?

Yes. MOKIT (https://gitlab.com/jxzou/mokit) is a toolkit to do that. It provides a utility `bas_fch2py` to generate a PySCF input which could read MOs from Gaussian fch file (and convert it into PySCF order). There's no utility to convert dm yet, but it's easy to get dm with MOs. See documentation at https://jeanwsr.gitlab.io/mokit-doc-mdbook/chap4-5.html#453-bas_fch2py for more information.

**Comment by AdamCoxson** [comment]
> Why do you need such 1-step fock matrix with PySCF?

For the full context of what I'm trying to do. I have neural networks that were trained on B3LYP converged density matrices to predict the converged B3LYP Fock matrix, which they do fairly well. I can give the networks an unconverged density matrix and they can also predict this Fock matrix. But diagonalising this F to get a new D and cycling this process to emulate SCF doesn't work; the Fock matrices diverge. This is obviously due to ML overfitting to converged B3LYP density/fock matrices.

To address this, we want to expand our training set with unconverged Fock matrices, this can be achieved by taking a converged F, adding Gaussian noise to the diagonals (lets call this F_noisy), diagonalising to get the new, unconverged D (lets call this _D'_) and then performing one step of a QC calculation to get the following unconverged F (_F'_). This means that I can replicate a Fock matrix as many times as I want, build up a lot of (_D'_, _F'_) pairs for a given molecule and hence have more varied training data that includes unconverged density matrices, where I can directly control the degree of non-convergence. I will also add the D and F from all the G16 SCF steps and Harris/Huckel/Core guesses to this training data. After training, the network _should_ have seen unconverged and converged density matrices and be better at modelling an SCF run. So thats why I need a 1-step fock matrix, to go from _D'_ to _F'_ via a desired choice of QC method (B3LYP in this case).

G16 is installed on my Uni computer cluster. There is a lot of overhead of going from my python scripts to G16 input files on the cluster, to performing a single iteration using G16, then reading all that information back in (from python to G16 then back to Python). I only care about the step of going from _D'_ to _F'_, so I want to stay pythonic and I figured PySCF can allow me to do that. I specifically want a B3LYP calculation; if I was dealing with simple RHF data, I could code the  _D'_ to _F'_ step explicitly in a function, but explicitly coding B3LYP doesn't look as straightforward to me. 

The question I had earlier this week: What is more faff, fiddling with the python-G16-python route or figurring out PySCF. In hindsight, both are probably as time-consuming...

Back to the above advice, I tried HF density matrices:
```
mf = scf.hf.SCF(mol)
mf.verbose = 1
mf.max_cycle = 0 # I compared both the full SCF convergence and cycle=0
data=mf.kernel(dm0=input_density_mat)
F4=mf.get_fock()
```
This also gives a different Fock matrix to the one calculated via G16, however, I think @hebrewsnabla is right with the basis set conventions and thats why we see a difference. In the below screenshot are the first 9 elements of a PySCF HF Fock matrix (top) and a G16 Fock matrix (bottom). The index row=0,1 and col=0,1 blocks are consistent but row,col=2 is where they differ. For example, in the top block row 2 col 0 is -2.38914 h, whereas this has moved to row 5, col 0 on the bottom image. G16 Atomic orbital ordering [for 3-21G] is 1s, 2s, 2p-xyz, 3s, 3p-xyz. So I can see that for PySCF the convention is 1s, 2s, 3s, 2p, 3p. This didn't even cross my mind before.

![Screenshot 2023-09-01 135711](https://github.com/pyscf/pyscf/assets/54117679/b6ce0896-47e0-41cd-b7ca-0560148932dc)

I'll have a play around with MOKIT and the AO basis set ordering and see if it solves the problem. Or what is more likely is that I'll come back here when I inevitably run into another silly error I overlooked haha :) 

So watch this space

Kind regards,
Adam

**Comment by hebrewsnabla** [comment]
> The question I had earlier this week: What is more faff, fiddling with the python-G16-python route or figurring out PySCF. In hindsight, both are probably as time-consuming...

What about using PySCF to get all the D and F matrices (i.e. no Gaussian used in the workflow)? That does not require any convertion or heavy coding. 

If you insist on converting matrices back and forth with MOKIT, you also need a utility to do fock matrix convertion. You may need to ask the MOKIT developers to implement that for you. Feel free to open issues in the MOKIT repo.

**Comment by AdamCoxson** [comment]
I found the PySCF documentation on [basis set ordering](https://pyscf.org/user/gto.html#ordering-of-basis-functions) to confirm what I assumed in my last post. I then wrote a function that can reorder a matrix according to G16 or PySCF basis set formatting. I reordered my input_density_matrix, passed it into dft.RKS, obtained the Fock matrix (F) and then reordered it to the Gaussian basis order (F_new).

This input density matrix was from the 1st SCF step of my G16 calculation. The final Fock converged at the 12th step. 
The converged PySCF F_new matrix is identical to the corresponding converged Fock matrix from G16.

```
# input_density_matrix = dm in AO basis from previous calculations via G16
# geom= Elements and geometry from G16

# convert dm from 1st step of SCF to PySCF basis ordering
new_dm, new_orbs, idx = convert_matrix_basis_order(input_density_matrix, input_orbitals, new_order_idx=[0,1,5,2,3,4,6,7,8]) 

mol = gto.M(
    atom = geom,  # in Angstrom
    basis = '3-21g',
    symmetry = False,
    unit = 'Angstrom')
    
mf = dft.RKS(mol)
mf.xc = 'b3lypg'
mf.max_cycle=50
E=mf2.kernel(dm0=new_dm)
F=mf2.get_fock()
print("Converged:", mf.converged)

F_new, F_orbs, idx = convert_matrix_basis_order(F, new_orbs, new_order_idx=[0,1,3,4,5,2,6,7,8]) # convert back to G16
```
There is a little bit of hardcoding in my function but for now it works for my specific purposes. 
So the actual issue was just simple basis set ordering. I can move onto the training data generation now!

Thanks for all the help! :)

**Comment by 1234zou** [comment]
Unfortunately, basis order is just one of the problems. But for 3-21G basis set, it is probably that this is the only problem. For a general basis set, there are many factors to be considered. See my answer to [a similar question](https://mattermodeling.stackexchange.com/questions/11562/comparison-between-the-ordering-of-molecular-orbital-coefficients-between-gaussi).

**Comment by AdamCoxson** [comment]
Thanks to everyone for the help, it saved me a lot of trouble :)

I'm closing this issue.
