### ISSUE TITLE
Spin-density from FCI wavefunction

### ISSUE THREAD

**Issue by ManishMitharwall** [pyscf/pyscf#1848]
Hi, I have performed the FCI calculation for my given one and two electron integrals. I want the spin density from this calculation. Is it possible to get the spin density from the many-body wavefunction (like people usually do with DMRG)?

**Comment by fishjojo** [comment]
You can try `fci.direct_spin1.make_rdm1s`

**Comment by verena-neufeld** [comment]
Hi @ManishMitharwall, thanks for posting this issue here. Has it been resolved?
