### ISSUE TITLE
Import error when using geometric optimizer

### ISSUE THREAD

**Issue by Fadelis98** [pyscf/pyscf#1849]
![image](https://github.com/pyscf/pyscf/assets/43640976/90ce55c0-15e2-4ef7-806e-6a8898352e63)

the environment is python3.10.12+pyscf 2.3.0

**Comment by jamesETsmith** [comment]
You need to install the `geomeTRIC` package, which you can do with `pip install geometric`. See their docs [here](https://geometric.readthedocs.io/en/latest/) for more info about the package.

**Comment by verena-neufeld** [comment]
Hi @Fadelis98 , thanks for posting this issue here. Has it been resolved?
