### ISSUE TITLE
Using to_fcivec() function after a CCSD calculation

### ISSUE THREAD

**Issue by Sumitcy21d079** [pyscf/pyscf#1850]
Hi,

Is there any way to use to_fcivec() function after a CCSD calculation?

Thanks in advance!

**Comment by verena-neufeld** [comment]
Might be similar to issue #1766 . Does that help?

**Comment by Sumitcy21d079** [comment]
Thanks for replying!
Yes, it is similar to issue #1766.

**Comment by verena-neufeld** [comment]
Hi @Sumitcy21d079 , thanks for having posted this issue here. Has it been resolved?

**Comment by Sumitcy21d079** [comment]
Hi Verena,

Actually i could not use this function for CCSD as I am able to use this
function for CISD. Thanks for your help and support.

Best regards,
Sumit

**Comment by sunqm** [comment]
Please refer to the discussion in #1766
