### ISSUE TITLE
(PBC) SCF not converging for BaTiO3, using SO solver? (PySCF 2.1) [Not using SO solver does not converge, + unphysical energies]

### ISSUE THREAD

**Issue by luna-component** [pyscf/pyscf#1853]
I'm trying to converge SCF for BaTiO3, for several reasons using PySCF version 2.1. 
I have tried different start and different space sizes for DIIS, but it does not seem to be passed when using the second order solver? I.e. it always uses the default values (tried setting `diis_start_cycle` and `diis_space` before and after requesting SO solver).
Any help would be greatly appreciated.

MWE:

```
from pyscf import scf as mol_scf
from pyscf.pbc import dft, gto

cell = gto.Cell()
cell.unit = 'Bohr'
cell.atom = '''
Ba  7.643372194672   7.626085433619   7.660733089681
Ti  3.720284319458   3.711870276093   3.728734456591
O   0.165717548281   3.896783227711   3.906001500719
O   3.905615561953   3.896783208814   0.174579400045
O   3.897149929066   0.156894549287   3.906001500719
'''
cell.a = [
[7.622764278, 0.002230425, 0.019531926],
[0.019487064, 7.622738445, 0.019531907],
[0.002237247, 0.002230444, 7.622788202]
]
cell.basis = 'gth-dzvp-molopt-sr'
cell.pseudo = 'gth-pbe'
cell.verbose = 4
cell.build()

kmesh = [2, 2, 2]
kpts = cell.make_kpts(kmesh)

kmf = dft.KRKS(cell, kpts).density_fit().apply(mol_scf.addons.remove_linear_dep_)
kmf.with_df.auxbasis = "weigend"
kmf.xc = 'pbesol'
kmf = kmf.newton()
kmf.max_cycle = 100
edft = kmf.kernel()
```

**Comment by hebrewsnabla** [comment]
There's no DIIS used in second order solver.

**Comment by luna-component** [comment]
> There's no DIIS used in second order solver.

I see. When the calculation is run, the DIIS class, space, start cycle etc. are still printed in the output, hence the confusion.
Any tips on what can be tried when trying to converge an SCF calculation using second order solver?
If I'm not using it, the SCF does not only not converge, it goes to unphysical energies..

**Comment by hebrewsnabla** [comment]
I suggest updating to pyscf 2.3 first. There's quite a lot of bugfix and improvements between 2.1-2.3. Probably your problem has already been resolved in latest version.

**Comment by luna-component** [comment]
Thanks, will try it out today.

**Comment by sunqm** [comment]
Feel free to reopen the issue if the new pyscf releases do not solve the problem.
