### ISSUE TITLE
error when installing pyscf on windows

### ISSUE THREAD

**Issue by Marsmmz** [pyscf/pyscf#1857]
I have faced same issue while installing environment for [qiskit textbook](https://github.com/Qiskit/textbook#setting-up) which uses `pyscf==2.0.1` on Windows 11,64-bit, Anaconda virtual env
so far i have tried majority of fixes but nothing worked , following are the fixes and error that i encoutered :
`pip install --prefer-binary pyscf` or  `pip install pyscf` or `pip install git+https://github.com/pyscf/pyscf`
ERROR: Could not build wheels for pyscf, which is required to install pyproject.toml-based projects.
`pip install cmake` or `pip install wheel`
`pip install pyscf`
ERROR: Could not build wheels for pyscf, which is required to install pyproject.toml-based projects
`pip install –prefer-binary pyscf`
ERROR: Invalid requirement: '–prefer-binary'
`conda install -c pyscf pyscf` or `conda install pyscf` or `conda install -c conda-forge pyscf`
PackagesNotFoundError: The following packages are not available from current channels:
 pyscf..
`pipwin install pyscf`
Package `pyscf` not found
Please help me out to install pyscf.

_Originally posted by @Raghav-Bell in https://github.com/pyscf/pyscf/issues/1684#issuecomment-1595827111_

**Comment by Raghav-Bell** [comment]
`pyscf` is not supported on windows. You can try with `WSL2`

**Comment by Raghav-Bell** [comment]
My personel suggestion is not to  try with `pip` as you will need `cmake` so, `conda` installation is preferable ([conda-forge](https://anaconda.org/conda-forge/pyscf)).

**Comment by verena-neufeld** [comment]
Thanks for raising this issue! Seems to be related to issue #910 and issue #750 . Maybe we should include this in the documentation.

**Comment by Marsmmz** [comment]
Thanks a lot!@Raghav-Bell I'll try it on linux.
Adding it to documentation will be helpful@verena-neufeld ,thanks!
