### ISSUE TITLE
Density on a grid calculation using density coefficients

### ISSUE THREAD

**Issue by mforstenhaeusler** [pyscf/pyscf#1860]
Hi, I am new to using pyscf and have a question on how to proceed.
I am trying to calculate the density on a grid given a set of density coefficients using the following relation. 
$$\rho(\vec{r}) = \sum_P^{N_{aux}}d_P\chi_P(\vec{r})$$
I generate the density coefficients using the density fitting procedure. As basis set I use def2-tzvp and def2-universal-jfit as auxiliary basis set.

Is there a way to compute the density as described in the above formula using pyscf methods to generate an output where I get the density on a 3-dimensional grid? 

Thank you in advance for the help.

**Comment by fishjojo** [comment]
`gto.eval_gto.eval_gto` can be used to compute the AO values on a grid.

**Comment by mforstenhaeusler** [comment]
Thanks for help. How am I able to pass the my coefficients to this method? Each of my value in the coefficient array  corresponds to a certain angular momentum and a corresponding basis set coefficient and exponent? How can I ensure to use to right coefficient and exponent of the basis set?

**Comment by fishjojo** [comment]
I'm not sure what exactly you wanted to compute, but can you write your basis in the form of contracted Gaussian basis functions? If so, then you could construct a `gto.Mole` object which contains your custom basis functions and pass it to the `eval_gto` function.

**Comment by mforstenhaeusler** [comment]
I think I figure it out. I can just do 
`
aux_ao = auxmol.eval_gto('GTOval', coords)
rho = lib.einsum('ij, j -> i', ao, d_coeff)
` 
to get the all the grid points.

**Comment by susilehtola** [comment]
Just be careful about the basis function normalization; I don't know where that takes place in PySCF. Typically the auxiliary functions are normalized to unit Coulomb overlap

$$ (A|A) = 1,\  A=1,\dots,N_\text{aux} $$

while usual basis functions are normalized to unit overlap

$$ (\mu|\mu) = 1,\  \mu=1,\dots,N_\text{orb} $$

**Comment by mforstenhaeusler** [comment]
Thanks for the input, I was not aware of this :)

**Comment by verena-neufeld** [comment]
Hi @mforstenhaeusler , thanks for having posted this issue here. Has it been resolved?

**Comment by mforstenhaeusler** [comment]
Yes it has been resolved.
