### ISSUE TITLE
modify the center of the GTOs

### ISSUE THREAD

**Issue by RodrigoAVargasHdz** [pyscf/pyscf#1863]
Hi,

I wanted to know if it is possible to modify the coordinate (vector) where each GTO is centered `mol.bas_coord(bas_id)`. 

Cheers,

**Comment by sunqm** [comment]
No, you cannot directly modify the positions of GTOs. They are bound to atoms. To change their positions, you have to modify the coordinates of atoms.

**Comment by verena-neufeld** [comment]
Hi @RodrigoAVargasHdz , thanks for posting this issue. Has it been resolved?

**Comment by changsuc** [comment]
Maybe add some ghost atoms, then it should work equally as modify the coordinate of GTO centers.

**Comment by sunqm** [comment]
Please see the example `https://github.com/pyscf/pyscf/blob/master/examples/gto/03-ghost_atom.py` for adding ghost atoms. Then you can changing the coordinates of the ghost atoms by code below
```
ptr_coord = mol._atm[mol.bas_atom(bas_id), 1]
mol._env[ptr_coord:ptr_coord+3] = new_coordinates
```
