### ISSUE TITLE
Removing VWN-RPA warning

### ISSUE THREAD

**Issue by julenl** [pyscf/pyscf#1864]
I am running PySCF version 2.3.0.

Every time I call it (from qiskit-nature) I keep getting this warning:

   ```
 /home/user/.local/lib/python3.10/site-packages/pyscf/dft/libxc.py:772: UserWarning: Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, the same to the B3LYP functional in Gaussian and ORCA (issue 1480). To restore the VWN5 definition, you can put the setting "B3LYP_WITH_VWN5 = True" in pyscf_conf.py
  warnings.warn('Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, '
```
I have tried to set the `B3LYP_WITH_VWN5` globally to `True` in `~/.pyscf_conf.py` and I can confirm that is properly set by:

``` python
>>> from pyscf import __config__
>>> print(getattr(__config__, 'B3LYP_WITH_VWM5'))
True
```
But the warning keeps appearing every time I call PySCF from PySCFDriver of qiskit-nature.

Any idea of why is the global variable not being recognized?

**Comment by sunqm** [comment]
https://github.com/pyscf/pyscf/blob/master/pyscf/__config__.py#L22 Here is the search order to load `.pyscf_conf.py`. When any of the config file is matched, configurations in other paths are ignored. Please check if you have set the environment variable `PYSCF_CONFIG_FILE` and if you have the config file in your working directory.

**Comment by verena-neufeld** [comment]
Hi @julenl , thanks for posting this issue. Has it been resolved?

**Comment by julenl** [comment]
Hi @verena-neufeld, not really...

Here is how to reproduce it:

``` python
>>> from pyscf import dft
/home/user/.local/lib/python3.10/site-packages/pyscf/dft/libxc.py:771: UserWarning: Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, corresponding to the original definition by Stephens et al. (issue 1480) and the same as the B3LYP functional in Gaussian. To restore the VWN5 definition, you can put the setting "B3LYP_WITH_VWN5 = True" in pyscf_conf.py
  warnings.warn('Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, '
```
More information:
``` python
>>> import pyscf
>>> pyscf.__version__
'2.4.0'
>>> from pyscf import __config__
>>> print(getattr(__config__, 'B3LYP_WITH_VWM5'))
True
```

**Comment by sunqm** [comment]
VWN5 not VWM5

**Comment by julenl** [comment]
Oh... You are totally right!
The warnings are finally gone. Thank you very much!
