### ISSUE TITLE
I have no clue what is happening (installation issue with wheel)

### ISSUE THREAD

**Issue by onhole** [pyscf/pyscf#1866]
I've been trying to install pyscf for hours and it just keeps giving me this error.  I have wheel and cmake installed.

<img width="961" alt="problem" src="https://github.com/pyscf/pyscf/assets/121628985/24f06227-76e2-47bf-ae35-afa86f89f93c">

**Comment by verena-neufeld** [comment]
Hi @onhole , thanks for raising this issue. What operating system are you using?

**Comment by onhole** [comment]
64-bit operating system, x64-based processor

**Comment by onhole** [comment]
> Hi @onhole , thanks for raising this issue. What operating system are you using?

64-bit operating system, x64-based processor

**Comment by verena-neufeld** [comment]
Is this windows by any chance? If yes, please see issues #1857 , issue #910 and issue #750 .

**Comment by onhole** [comment]
> Is this windows by any chance? If yes, please see issues #1857 , issue #910 and issue #750 .

Yes I have a windows.  Is pyscf not supported for windows?

**Comment by verena-neufeld** [comment]
That is my impression. From reading the past issues, you can try wsl and install it there.

**Comment by onhole** [comment]
Thank you for your quick responses.  I installed pyscf on wsl but still cant seem to use it in Jupyter notebook.  I opened my jupyter notebook with anaconda prompt.

<img width="959" alt="image" src="https://github.com/pyscf/pyscf/assets/121628985/654b035f-e6dc-4b17-96ec-27feec3d3345">
<img width="640" alt="image" src="https://github.com/pyscf/pyscf/assets/121628985/1e7de509-39bc-43cb-95c1-16a000139b44">

**Comment by verena-neufeld** [comment]
What happens if you just do "import pyscf" in the notebook?

**Comment by onhole** [comment]
This is what happens: 

![image](https://github.com/pyscf/pyscf/assets/121628985/72b2ab7e-a0ac-4dde-a5ca-1c936a0b3f9a)

**Comment by verena-neufeld** [comment]
On the wsl, I assume you can do "python" and then when the python console opens, you can say "import pyscf" and it works? Is your notebook running on the wsl?

**Comment by onhole** [comment]
> On the wsl, I assume you can do "python" and then when the python console opens, you can say "import pyscf" and it works? Is your notebook running on the wsl?

i got it to work.  I just opened up ubuntu application and reinstalled qiskit.  I don't have anaconda python on the Ubuntu wsl though.  Will that be a problem?

**Comment by verena-neufeld** [comment]
I'm not entirely sure. To get started, I'd recommend running simple python programs on the wsl, running pyscf tests, and maybe reading more on python on wsl. Good luck, thanks for trying out pyscf! Feel free to post further questions.

**Comment by ChrisJazz** [comment]
Question to follow up. I am also trying to access qiskit_nature via the PySCF driver. I have followed most of those steps to achieve a PySCF installation through wsl on ubuntu. How do you then get VS code to recognize the wsl environment as a kernel to run a jupyter notebook through?
