### ISSUE TITLE
One test is sometimes failing for python 3.8

### ISSUE THREAD

**Issue by verena-neufeld** [pyscf/pyscf#1871]
`FAILED pyscf/solvent/test/test_ddcosmo_tdscf_grad.py::KnownValues::test_b3lyp_tda - NotImplementedError: complex density matrix`

Do you have tips on how to debug this most easily? From reading the error message my guess would be that the imaginary parts are basically zero but I might be wrong as not the whole matrix is shown. Is it ok to add a check if the imaginary part is very small and if yes, convert to non complex data types?

**Comment by sunqm** [comment]
The initial guess in TDA introduces imaginary part https://github.com/pyscf/pyscf/blob/master/pyscf/tdscf/rhf.py#L743 .
@hongzhouye Why do you introduce this function to modify initial guess?

**Comment by hongzhouye** [comment]
Thanks for finding the source @sunqm!
In my initial tests, I found that pbc tdscf with the original guess (without this subspace diagonalization) would easily miss roots. I can check it again to see if any later changes I made makes this function unnecessary.

**Comment by verena-neufeld** [comment]
We now seem to be getting this failure (in addition?): 
`FAILED pyscf/solvent/test/test_ddcosmo_tdscf_grad.py::KnownValues::test_rhf_tda - AssertionError: -0.5088712151177788 != -0.5099315650920767 within 6 places (0.001060349974297936 difference)` failing for 3.7.
In the latest commit the previous failure (I think) happens for the macOS test.

**Comment by verena-neufeld** [comment]
Thanks @sunqm and @hongzhouye , seems like this can be closed.
