### ISSUE TITLE
Convergence issue when importing torch on linux

### ISSUE THREAD

**Issue by mforstenhaeusler** [pyscf/pyscf#1873]
Hi, I recently noticed that when I run a simple dft calculation on linux and import torch into the same script, the dft fails to convergence. Upon removal of the torch import, 
the code worked as expected.

Has anyone else also encounter this?

**Comment by sunqm** [comment]
Probably related to this issue https://github.com/pytorch/pytorch/issues/109446

**Comment by verena-neufeld** [comment]
Hi @mforstenhaeusler , thanks for posting this issue. Has it been resolved?
