### ISSUE TITLE
Controlling "`'j_only'`" density fitting builds for non-hybrid functionals

### ISSUE THREAD

**Issue by obackhouse** [pyscf/pyscf#1879]
I am running post-mean-field calculations via my own code using PySCF mean-field objects. For my calculations, I require density fitted integrals at all k-points pairs, even if the reference is a non-hybrid XC where the mean-field only needs `ki==kj` combinations.

I am trying to write examples for my code using i.e. a PBE reference, and I can't work out how to control this behaviour reliably. For example:

```
import numpy as np
from pyscf.pbc import gto, scf, df

cell = gto.Cell()
cell.atom = "He 0 0 0; He 1 1 1"
cell.basis = "6-31g"
cell.a = np.eye(3) * 3
cell.verbose = 0
cell.build()

kpts = cell.make_kpts([3, 1, 1])

def test(with_df):
    try:
        for ki in range(len(kpts)):
            for kj in range(len(kpts)):
                for _ in with_df.sr_loop((ki, kj)):
                    pass
        print("Passed")
    except Exception as e:
        print(f"Failed on {ki}, {kj}: {e}")

print("Manual:")
with_df = df.DF(cell)
with_df.build(j_only=False)
test(with_df)

print("\nPBE, with kernel, specify _j_only:")
mf = scf.KRKS(cell, xc="pbe", kpts=kpts)
mf = mf.density_fit()
mf.with_df._j_only = False
mf.kernel()
test(mf.with_df)

print("\nPBE, without kernel, do not specify _j_only:")
mf = scf.KRKS(cell, xc="pbe", kpts=kpts)
mf = mf.density_fit()
test(mf.with_df)

print("\nPBE, without kernel, specify _j_only:")
mf = scf.KRKS(cell, xc="pbe", kpts=kpts)
mf = mf.density_fit()
mf.with_df._j_only = False
test(mf.with_df)

print("\nB3LYP:")
mf = scf.KRKS(cell, xc="b3lyp", kpts=kpts)
mf = mf.density_fit()
test(mf.with_df)
```

produces the output:

```
Manual:
Failed on 0, 1: 'Key j3c/1 not found'

PBE, with kernel, specify _j_only:
Failed on 0, 1: 'Key j3c/1 not found'

PBE, without kernel, do not specify _j_only:
Failed on 0, 1: 'Key j3c/1 not found'

PBE, without kernel, specify _j_only:
Passed

B3LYP:
Passed
```

Can someone clarify this behaviour for me, and suggest how to set up my examples to make sure that the full `cderi` is built regardless of the `xc`?

**Comment by verena-neufeld** [comment]
In the first example, you can specify the kpts, i.e. do `with_df = df.DF(cell, kpts=kpts)`. 

You can build DF first, pass it to the mean field object instance, and then do kernel (thanks to @hongzhouye for pointing this out in the past to me):

```
with_df = df.DF(cell, kpts=kpts)
with_df.build(j_only=False)
mf = scf.KRKS(cell, xc="pbe", kpts=kpts)
mf.with_df = with_df
mf.kernel()
test(mf.with_df)
```

**Comment by obackhouse** [comment]
Thanks @verena-neufeld - I had missed the fact that I forgot the `kpts` parameter there, my bad. That's good enough for my case, though I do think the behaviour with mean-field calculations is quite unintuitive still.

**Comment by sunqm** [comment]
To hide the configurations like "j_only", new designs are necessary to improve the functionality of pbc DF. Please feel free to reopen the issue and add an "enhancement" label.
