### ISSUE TITLE
definition of CIS coefficients and transition dipoles in TD-DFT

### ISSUE THREAD

**Issue by humeniuka** [pyscf/pyscf#1881]
Dear pyscf developers,
There seems to be an inconsistency in the definition of the CIS coefficients that are used to compute the transition dipole moments. According to [Casida 1995](https://tddft.org/TDDFT2004/PracticalSessions/papers/casida_1996.ps) the excited state "wavefunctions" are obtained from the excitation and deexcitation coefficients X and Y as
```math
C_{ia} = \sqrt{\omega} \sum_{jb} (A-B)^{-1/2}_{ia,jb} (X_{jb}+Y_{jb})
```
where i,j are occupied and a,b are virtual orbitals.
With this definition the CIS coefficients of different excited states m,n are orthonormal,
```math
\sum_{i,a} C^{(m)}_{ia} C^{(n)}_{ia} = \delta_{m,n}
```
pyscf, on the other hand, uses the definition
```math
C_{ia} = 2 (X_{ia} + Y_{ia})
```
to evaluate the transition dipoles between the ground and excited states (see https://github.com/pyscf/pyscf/blob/master/pyscf/tdscf/rhf.py#L523). These CIS coefficients are not orthonormal and the resulting transition dipoles are (slightly) different. The attached script illustrates this for the water molecule.
Would it be possible to use the first definition of the CIS coefficients? For non-hybrid functionals the inversion of (A-B) is trivial.
Thank you.

[tddft_transition_dipoles.py.txt](https://github.com/pyscf/pyscf/files/12774428/tddft_transition_dipoles.py.txt)

**Output of the script:**
1) transition dipoles with CIS = sqrt(w) (A-B)⁻¹ᐟ² (X+Y)
overlap of CIS states, |Overlap-Id|= 4.560838223149519e-16
[[ 1.80471886e-16 **-4.13905590e-02**  1.97871470e-16]
 [ 3.33522840e-18  6.21724894e-15  8.36209572e-17]
 [ **4.45225913e-01**  3.19182284e-17  3.19883009e-15]]
2) transition dipoles with CIS = 2*(X+Y)
overlap of CIS states, |Overlap-Id|= 1.510040901767948
[[ 2.99947624e-16 **-5.57393605e-02**  2.66467268e-16]
 [ 2.52146661e-17  7.68829445e-15  1.16264801e-16]
 [ **5.44358372e-01**  4.48592235e-17  4.27435864e-15]]
3) pyscf's built-in transition dipoles
[[ 2.91939929e-16 **-5.57393605e-02**  2.66467268e-16]
 [ 2.32572219e-17  7.62296447e-15  1.16264801e-16]
 [ **5.44358372e-01**  4.48592235e-17  4.26194943e-15]]

`

**Comment by sunqm** [comment]
Transition dipole in TDDFT is computed as `trace(DM, dipole_integral)` . The density matrix DM is computed roughly as `X*X + Y*Y`. There is no such an intermediate C to simplify the computation of density matrix. Casida formula can simplify the non-hermitian eigenvalue problem, but the intermediates C has nothing to do with the wavefunction coefficients. You have to transform them back to the regular X, Y coefficients, and compute density matrix in the normal way.

**Comment by verena-neufeld** [comment]
Hi @humeniuka , thanks for raising this issue. Has it been resolved now?

**Comment by humeniuka** [comment]
Dear Verena,

Yes, my question has been answered.

Thanks

Am Di., 24. Okt. 2023 um 19:44 Uhr schrieb Verena Neufeld <
***@***.***>:
