### ISSUE TITLE
AO-overlap between two molecular conformers/molecules

### ISSUE THREAD

**Issue by ettenhup** [pyscf/pyscf#1887]
Hi pyscf-community,

I have been trying to find an easy solution for calculating the AO overlap between two different molecules (well, two different conformers of the same molecule) without any luck. Is there a simple solution for that or do I need to dig down deep into the weeds of pyscf/implement it myself?

Thank you for your help,
Patrick

**Comment by januseriksen** [comment]
Hi Patrick,

Is this along the lines of what you need?

https://github.com/pyscf/pyscf/blob/master/pyscf/gto/mole.py#L742
https://github.com/pyscf/pyscf/blob/master/pyscf/gto/mole.py#L836

Best wishes,
Janus

**Comment by ettenhup** [comment]
Hi Janus,

Thanks this looks perfect. I will check it out and come back to you if it resolves my question.

All the best,
Patrick

**Comment by ettenhup** [comment]
Works as expected, thanks Janus.
