### ISSUE TITLE
Import pyscf.grad w/ installed mpi4py package initializes MPI

### ISSUE THREAD

**Issue by eljost** [pyscf/pyscf#1888]
Dear developers,

importing `pyscf.grad` when the `mpi4py` package is available seems to initialize MPI. Please see the script and output below:

```python
import os

print("before pyscf import")
print(os.system("env | grep PMIX"))

print("after pyscf.grad import")
import pyscf.grad

# This has the same effect
# print("after MPI import from mpi4py")
# from mpi4py import MPI

print(os.system("env | grep PMIX"))
```
produces
```bash
 2023-10-04 11:26:42 ⌚  notebook in ~/tmp/577_pyscf_grad
○ → python ps.py 
before pyscf import
256
after pyscf.grad import
/home/johannes/.pyenv/versions/pyscf_grad/lib/python3.11/site-packages/pyscf/dft/libxc.py:772: UserWarning: Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, the same to the B3LYP functional in Gaussian and ORCA (issue 1480). To restore the VWN5 definition, you can put the setting "B3LYP_WITH_VWN5 = True" in pyscf_conf.py
  warnings.warn('Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, '
PMIX_MCA_mca_base_component_show_load_errors=1
PMIX_HOSTNAME=notebook
PMIX_SECURITY_MODE=native
PMIX_GDS_MODULE=ds21,ds12,hash
PMIX_SYSTEM_TMPDIR=/tmp
PMIX_SERVER_URI41=1800273920.0;tcp4://127.0.0.1:44791
PMIX_BFROP_BUFFER_TYPE=PMIX_BFROP_BUFFER_NON_DESC
PMIX_DSTORE_21_BASE_PATH=/tmp/ompi.notebook.1000/pid.320935/pmix_dstor_ds21_320935
PMIX_VERSION=4.2.6
PMIX_MCA_psec=native
PMIX_RANK=0
PMIX_SERVER_URI2=1800273920.0;tcp4://127.0.0.1:44791
PMIX_SERVER_URI3=1800273920.0;tcp4://127.0.0.1:44791
PMIX_SERVER_URI4=1800273920.0;tcp4://127.0.0.1:44791
PMIX_SERVER_URI21=1800273920.0;tcp4://127.0.0.1:44791
PMIX_DSTORE_ESH_BASE_PATH=/tmp/ompi.notebook.1000/pid.320935/pmix_dstor_ds12_320935
PMIX_SERVER_TMPDIR=/tmp/ompi.notebook.1000/pid.320935
PMIX_NAMESPACE=1800273921
0
```

When the `mpi4py` package is not installed in the python environment MPI is not initialized.

Is this intended behavior and if so, can the MPI initalization be disabled somehow? For me, the unintended MPI initalization breaks a few things, e.g., I can't execute subprocesses with `mpirun`. I run into the same issues as described in this [StackOverflow post](https://stackoverflow.com/a/60070753).

The problem occurs on the following system
```
Linux notebook 5.10.194-1-MANJARO #1 SMP PREEMPT Sat Sep 2 20:55:57 UTC 2023 x86_64 GNU/Linux

mpirun --version
  mpirun (Open MPI) 4.1.5

Python 3.11.5 (freshly compiled via pyenv)

python -m pip freeze (pyscf installation from PyPI)
  h5py==3.9.0
  mpi4py==3.1.5
  numpy==1.26.0
  pyscf==2.3.0
  scipy==1.11.3
```

As far as I can tell the MPI functionality of PySCF lives in a different package, which I did not install. So the MPI initialization is quite unexpected for me.

All the best
Johannes

**Comment by verena-neufeld** [comment]
Hi Johannes, thanks for investigating this. PySCF does seem to use MPI in parts of its core modules, e.g. in https://github.com/pyscf/pyscf/blob/master/pyscf/cc/momgfccsd.py and I'm under the impression that when loading some submodule of pyscf, it can depend on submodules that use MPI. I wonder whether we should separate this more/make it easier to disable. @sunqm @fishjojo what do you think?

**Comment by sunqm** [comment]
Agree, the dependency to MPI should be removed in the future. I can first remove the automatic initialization in momgfccsd

**Comment by sunqm** [comment]
The import dependence to MPI has been removed in PR #2059.
