### ISSUE TITLE
CASCI upto double excitations

### ISSUE THREAD

**Issue by SoulokeSen** [pyscf/pyscf#1890]
Dear PYSCF developers,

Is there any way to restrict the  number of determinants upto doubles in the CAS space for a CASCI calculation ?

thank you in advance,
Souloke

**Comment by tberkel** [comment]
At least one solution is to just do a CISD calculation with frozen core and
virtual orbitals.

**Comment by bogdanoff** [comment]
It should also be possible to modify the selected CI code to keep track of number of electrons in different orbital spaces.

**Comment by SoulokeSen** [comment]
thanks @tberkel .This solution worked. Another suggestion that could be useful also thanks @bogdanoff

**Comment by verena-neufeld** [comment]
Thanks @SoulokeSen for raising this issue. If it has been resolved, feel free to close when you have time.
