### ISSUE TITLE
wave function CIS

### ISSUE THREAD

**Issue by GmPoint** [pyscf/pyscf#1892]
Hello, 

I'm new to pyscf and quantum chemistry. However, I'm trying to do a KCIS calculation for a solid with above 90 electrons cc-pvdz basis at the gamma point. 

I'm trying to get a guess or starting point to understand which single excitation are important for this system.  Since using the 1st excitation from the HOMO to LUMO seems not a good guess for. 

However, I don't have idea how to get a string of the occupations of the determinants and how this is related to the output that CIS gave me. 

I tried to follow and adapt the example here for CISD: 

https://github.com/pyscf/pyscf/issues/327

I also tried to run CISD on this system, but already run out of memory for a large amount, so it seems impossible to perform with computational resources for us.  But, the KCIS runs and I just need to understand better  how to get the wave function and understand this output. 

Adapting the example, below the portion of my script I consider important. However, I see it the strings prints the HF occupation, and other doubles excitation I think. Then, using **ci0** and the **loop from 327** to get the strings with the occupations seems wrong. 

I'm not sure if I understand properly the CIS method. But, what I understood is that CIS doesn't should print the c0 Hartree Fock amplitude?, also I'm not sure ci0 is given me all the singles amplitudes? 

This, I dont understand yet, how the amplitudes in ci0 are related to the energy in e_vals? How I can choose the excitation from the CIS?

I would appreciated if you can provide any help with this issues. 

best, 

Randy

----code---
 
mcis=ci.kcis_rhf.KCIS(mf, frozen=FM, mo_coeff=mf.mo_coeff, mo_occ=mf.mo_occ)
e_vals, ci_coeff= mcis.kernel()
ci_coeff_arr=np.asarray(np.squeeze(ci_coeff))
ci0=mcis.vector_to_amplitudes(ci_coeff_arr)

data=[]
for ia in range(na):
    for ib in range(nb):
        #if(np.abs(cisdWFN[ia,ib])>1e-4):
        #print('raw xa ia', ia, cistring.addr2str(nmo,neleca,ia))
        #print('raw xb ib', ib, cistring.addr2str(nmo,nelecb,ib))
        
        xa = excitation_str(cistring.addr2str(nmo,neleca,ia))
        xb = excitation_str(cistring.addr2str(nmo,nelecb,ib))

        print('exci xa ia', ia, xa)
        print('exci xb ib', ib, xb)
        
        #wfd=str(ci0[ia,ib])+' '+string(xa,xb)
        #print(wfd)
        wfd=str(ci0[ia,ib])+' '+xa+'        '+xb
        data.append(wfd)

**Comment by tberkel** [comment]
You can use the TDA method (which is the same as CIS when you used HF for the ground state). An example for a periodic calculation of carbon diamond at the Gamma point is below, with some analysis at the end to show you how to analyze the CIS amplitudes:
```
from pyscf.pbc import gto
from pyscf.pbc import scf
from pyscf.pbc import tdscf

cell = gto.Cell()
cell.unit = 'B'
cell.atom = '''
C  0.          0.          0.
C  1.68506879  1.68506879  1.68506879
'''
cell.a = '''
0.          3.37013758  3.37013758
3.37013758  0.          3.37013758
3.37013758  3.37013758  0.
'''
cell.basis = 'gth-szv'
cell.pseudo = 'gth-pade'
cell.build()
mf = scf.RHF(cell)
ehf = mf.kernel()

td = tdscf.TDA(mf)
td.nstates = 5
td.verbose = 5
e, xy = td.kernel()

print(len(xy)) # 5 = td.nstates
for n in range(td.nstates):
    print("E =", e[n]*27.21139, "eV")
    xn, yn = xy[n]
    print(xn.shape) # (4,4) = (nocc, nvir)
    print("x[homo,lumo] =", xn[3,0])
```

**Comment by GmPoint** [comment]
Hi, 

Thanks for your quick answer. It encourage me to try to understand TDA and  its relationship to CIS which is well described at https://pubs.acs.org/doi/10.1021/cr0505627 .

Hopefully, I can understand it better now. However, I have some extra questions regarding my goals to use Pyscf.   

1- Begun your comment at https://github.com/pyscf/pyscf/issues/327 then if you want to use a RHF reference, then each single excitation is a singlet the amplitudes  that TDA gives at **xn**  correct?.  If yes,  when using the amplitudes given **xn**  Do I need to scale these amplitudes by any factor to write the singlet?. 

2- I tried to compare directly against the KCIS calculation, I guess the number of roots is the same that setting nstates=5.  However, the energies (roosts) as well the amplitudes ci0 matrix doesn't match the TDA calculation. Do I miss something to do the comparison?.  

3-  It is very likely the excitation I want to study is localized in real space.  I try to follow a pm localization orbitals example and then localize occupied and virtual orbitals. I understand the localization is a unitary rotation, the HF energy should be same, but the TDA or CIS should be also the same that without localization?.  I want to reduce the size of the expansion generated by the CIS. Probably, I'm missing something here too. 

I copied below my enlarged version of your nice example, trying to test these things. I really appreciated if you can provide me some feedback , so far it is has been very helpful for me. 

best, 

Randy

----code-------



from pyscf.pbc import gto
from pyscf.pbc import scf
from pyscf.pbc import tdscf
from pyscf import ci as mci
from pyscf.pbc import ci
from pyscf import lo
import numpy as np 


cell = gto.Cell()
cell.unit = 'B'
cell.atom = '''
C  0.          0.          0.
C  1.68506879  1.68506879  1.68506879
'''
cell.a = '''
0.          3.37013758  3.37013758
3.37013758  0.          3.37013758
3.37013758  3.37013758  0.
'''
cell.basis = 'gth-szv'
cell.pseudo = 'gth-pade'
cell.verbose=5
cell.build()

#mf = scf.KRHF(cell)
mf = scf.RHF(cell)
mf.verbose=5
ehf = mf.kernel()

print("rhf energy",ehf)

td = tdscf.TDA(mf)
td.nstates = 5
td.verbose = 5
e, xy = td.kernel()

print("pass td calcualtion")

print("mo occ",mf.mo_occ)


print(len(xy)) # 5 = td.nstates
for n in range(td.nstates):
    print("E =", e[n]*27.21139, "eV")
    xn, yn = xy[n]
    print("xn shape",xn.shape) # (4,4) = (nocc, nvir)
    print("xn",xn)
    print("yn",yn)
    #print("yn shape",yn.shape) # (4,4) = (nocc, nvir)
    print("x[homo,lumo] =", xn[3,0])

#krhf object for KCIS calculation   
kmf=scf.KRHF(cell)    
kmf.kernel()    
mcis=ci.kcis_rhf.KCIS(kmf, mo_coeff=kmf.mo_coeff, mo_occ=kmf.mo_occ)
mcis.verbose = 5
#e_vals, ci_coeff= mcis.kernel()
e_vals, ci_coeff= mcis.kernel(nroots=5)

#to compare against TDA excitation energies
print("evals",np.asarray(e_vals)*27.21139, "eV")
print("evals**2",(np.asarray(e_vals)**2)*27.21139, "eV")

#print("\n ci_coeff.shape \n", ci_coeff.shape)


ci_coeff_arr=np.squeeze(np.asarray(ci_coeff[0][0]))
print("ci arr", ci_coeff_arr)

ci0=mcis.vector_to_amplitudes(ci_coeff_arr)

#to compare against xn
print("ci0",ci0)


#compute pm localized with Mulliken criteria
nocc = 4
loc_occ = lo.PM(cell, mf.mo_coeff[:,:nocc],mf)
loc_occ.pop_method="mulliken"
lmo_occ = loc_occ.kernel()
# localize the virtual orbitals separately
loc_virt = lo.PM(cell, mf.mo_coeff[:,nocc:],mf)
loc_virt.pop_method="mulliken"
lmo_virt = loc_virt.kernel()
# merge the MO coefficients in one matrix
lmo = np.hstack((lmo_occ, lmo_virt))

# HF calculation check with the localized orbitals
mf2 = scf.RHF(cell)
mf2.verbose=5
mf2.chkfile = "RHF_pm_mu.chk"               
dm = mf.make_rdm1(mo_coeff =lmo,mo_occ = mf.mo_occ)
mf2.max_cycle = 0                                                           
ehf2 = mf2.kernel(dm0 = dm)

print("rhf energy 2",ehf2)

td2 = tdscf.TDA(mf2)
td2.nstates = 5
td2.verbose = 5
e2, xy2 = td2.kernel()

print("pass td2 calculation")

print("mo occ loc",mf2.mo_occ)

print(len(xy)) # 5 = td.nstates
for n in range(td.nstates):
    print("E =", e2[n]*27.21139, "eV")
    print("E+HF =", (e2[n]+ehf2)*27.21139, "eV")
    xn2, yn2 = xy2[n]
    print("xn2 shape",xn2.shape) # (4,4) = (nocc, nvir)
    print("xn2",xn)
    print("yn2",yn)
    #print("yn shape",yn.shape) # (4,4) = (nocc, nvir)
    print("x2[homo,lumo] =", xn2[3,0])

**Comment by sunqm** [comment]
TDA and CIS in pyscf differ by a complex conjugation, as pointed out by #2246 . The A tensor in the TDDFT [A, B, -B, -A] tensor obtained by TDA, $A[i,a,j,b] = <ib||aj> = (ia|bj) - (ij|ba)$, is a complex conjugated to that in CIS, $<aj||ib>$ . For more comparison between TDA and CIS in pyscf, please follow the discussion in #2246
