### ISSUE TITLE
Update on Fermi Smearing for Molecules?

### ISSUE THREAD

**Issue by stefanvuckovic1** [pyscf/pyscf#1899]
Referring to the previous discussion on Fermi Smearing for molecules [#1560: [https://github.com/pyscf/pyscf/issues/1560] I am curious if there have been any updates or resolutions (it is my understanding that it works only for PBC). 

Thank you,
Stefan

**Comment by sunqm** [comment]
It supports the molecular SCF models too. You can find the `smearing` function in `addons.py` https://github.com/pyscf/pyscf/blob/ceea353b1ac07b0f10de480220ed9b27ee1eeb41/pyscf/scf/addons.py#L38

**Comment by verena-neufeld** [comment]
Hi @stefanvuckovic1 , thanks for asking. Has your question been answered?
