### ISSUE TITLE
FCI example 36-determinants_basis_matrix.py is not showing correct result

### ISSUE THREAD

**Issue by ManishMitharwall** [pyscf/pyscf#1907]
I am trying to build the CAS Hamiltonian by the method illustrated in example 36. "[36-determinants_basis_matrix.py](https://github.com/pyscf/pyscf/blob/master/examples/fci/36-determinants_basis_matrix.py)" I found that the difference in the hamiltoninan is not zero.

**Comment by sunqm** [comment]
I cannot reproduce the error using v2.4. It would be helpful if you can provide a docker image to show the error. Otherwise, please post your environment, such as the Python version, and how you install pyscf.
