### ISSUE TITLE
Specifying functional from libxc

### ISSUE THREAD

**Issue by pkozlows** [pyscf/pyscf#1917]
I want to run a DFT calculation with the pbc module. I want to use the B3PW91 functional. I see that in the libxc it gives this by the code HYB_GGA_XC_B3PW91. However, I am getting a non descriptive error for this block (I think):
```
# dft calculation
kmf = pbcdft.KRKS(cell, cell.make_kpts([3,3,3]))
kmf.xc = 'HYB_GGA_XC_B3PW91'
kmf.kernel()
```
As an aside, I am pretty sure that this is not the place to ask syntax questions like this for pyscf, but I don't know where else :)

**Comment by fishjojo** [comment]
Please try `kmf.xc = 'b3pw91'`

**Comment by susilehtola** [comment]
What is the error?

**Comment by susilehtola** [comment]
> Please try `kmf.xc = 'b3pw91'`

This is a workaround, which doesn't solve any potential bug. PySCF should be able to use Libxc functionals as-is

**Comment by fishjojo** [comment]
> > Please try `kmf.xc = 'b3pw91'`
> 
> This is a workaround, which doesn't solve any potential bug. PySCF should be able to use Libxc functionals as-is

Yes, the script seems fine. Please post a runnable script which can reproduce the error.
