### ISSUE TITLE
potential energy surfaces for polyatomic molecules using CASSCF

### ISSUE THREAD

**Issue by rw1511** [pyscf/pyscf#1919]
I am trying to generate the "excited state PES" for large molecules (usually 100 atoms) using CASSCF calculations, however the PES is not smooth and at some points the energy has a lot of fluctuations. Generally, in ORCA, I would use the CASSCF optimized orbitals of one calculation as initial guess for next calculation and  PES is very smooth. However, a similar process in PySCF yields different PES.

I've checked the examples for HF, Cr2 and BeH2  scan given in PySCF, however, the similar calculations for large molecules could not generate smooth PES for me. 

I am using a state-averaged CASSCF for 2 singlet and 1 triplet states.

###############################################################################

import numpy
from pyscf import scf, gto, lib, fci, mcscf, mrpt
from pyscf.lib import chkfile

coord = '1.2.txt'

mol = gto.M()
mol.atom = coord
mol.basis = '6-31G'
mol.spin = 0
mol.verbose = 4
mol.build()

mf = scf.RHF(mol)
with lib.with_omp_threads(48):
 mf.kernel()

weights = numpy.ones(3)/3
solver1 = fci.addons.fix_spin(fci.direct_spin1.FCI(mol), ss=2) # <S^2> = 2 for Triplet
solver1.spin = 2
solver1.nroots = 1
solver2 = fci.addons.fix_spin(fci.direct_spin1.FCI(mol), ss=0) # <S^2> = 0 for Singlet
solver2.spin = 0
solver2.nroots = 2

mycas = mcscf.CASSCF(mf, 2, 2)
mcscf.state_average_mix_(mycas, [solver1, solver2], weights)
mycas.max_cycle_macro = 25
mycas.max_cycle_micro = 3
mycas.fcisolver.conv_tol = 1e-10
mycas.conv_tol = 1e-10
mycas.conv_tol_grad = 1e-6
mycas.ci_grad_trust_region = 2
mycas.verbose = 4
with lib.with_omp_threads(48):
 mycas.kernel()

**Comment by ecbrown** [comment]
This sounds a lot like intruder states.  In my experience, the larger the molecule, the more likely it is for some state order flipping to occur.  

Unfortunately, increasing the number of states solved for tends to reach into other even higher states which can also cross, and causes non-smooth PES's to be generated.

**Comment by rw1511** [comment]
Hi @matthew-hennefarth 
sorry for late reply and thank you very much for your help. The _as_scanner_ is really useful. It solves my problem.

**Comment by verena-neufeld** [comment]
Hi @rw1511 , thanks for your question. Has it been resolved? If yes, this issue can be closed. Thanks!

**Comment by rw1511** [comment]
Hi Verena, this was solved. Thank you very much.

R

*-----------------------------------------------*
Rajat Walia, Ph.D.
*Postdoctoral Fellow*
City University of Hong Kong
