### ISSUE TITLE
eph_fd to calculate el-ph couplings

### ISSUE THREAD

**Issue by bkhoutom** [pyscf/pyscf#1920]
Hi, I have a question related to eph_fd, in particular, this function:

```
def get_vmat(mf, mfset, disp):
    vmat=[]
    mygrad = mf.nuc_grad_method()
    ve = mygrad.get_veff() + mygrad.get_hcore() + mf.mol.intor("int1e_ipkin")
    RESTRICTED = (ve.ndim==3)
    aoslice = mf.mol.aoslice_by_atom()
    for ki, (mf1, mf2) in enumerate(mfset):
        atmid, axis = np.divmod(ki, 3)
        p0, p1 = aoslice[atmid][2:]
        vfull1 = mf1.get_veff() + mf1.get_hcore() - mf1.mol.intor_symmetric('int1e_kin')  # <u+|V+|v+> getting potential
        vfull2 = mf2.get_veff() + mf2.get_hcore() - mf2.mol.intor_symmetric('int1e_kin')  # <u-|V-|v->
        vfull = (vfull1 - vfull2)/disp  # (<p+|V+|q+>-<p-|V-|q->)/dR
        if RESTRICTED:
            vfull[p0:p1] -= ve[axis,p0:p1]
            vfull[:,p0:p1] -= ve[axis,p0:p1].T
        else:
            vfull[:,p0:p1] -= ve[:,axis,p0:p1]
            vfull[:,:,p0:p1] -= ve[:,axis,p0:p1].transpose(0,2,1)
        vmat.append(vfull)

    return np.asarray(vmat)
```

This function should give me a coupling matrix in the nuclear basis. My question is what is "ve" variable? I thought vfull is the electron-nuclear couplings by finite difference, so why do we need to calculate vfull -= ve? A related question is are we calculate <p|dV/dR|q> or <p|dV|q>/dR.
Thanks a lot for the help!

**Comment by sunqm** [comment]
@yangcal , need your help to clarify the purpose of ve

**Comment by bkhoutom** [comment]
> @yangcal , need your help to clarify the purpose of ve

Thanks Qiming for forwarding this message!

**Comment by yangcal** [comment]
Hello, it's been a while since I last touched the code, sorry for the poor documentation.

It appears `vfull=d<p|V|q>/dR` and `ve=<dp|V|q>/dR`. Therefore `vmat = vfull-ve-ve.T = d<p|V|q>/dR-<dp|V|q>/dR-<p|V|dq>/dR=<p|dV|q>/dR`.

**Comment by bkhoutom** [comment]
Hi @yangcal , thank you very much for the clarification! Now I get it.

**Comment by verena-neufeld** [comment]
Hi @bkhoutom , thanks for your question. Has it been answered?

**Comment by bkhoutom** [comment]
> Hi @bkhoutom , thanks for your question. Has it been answered?

Yes! Sorry, I forgot to close this.
