### ISSUE TITLE
Accessing source code for pyscf.pbc.lib.chkfile

### ISSUE THREAD

**Issue by pkozlows** [pyscf/pyscf#1924]
I am getting a 404 error when I click on this link.

https://pyscf.org/_modules/pyscf/pbc/lib/chkfile.html#load_cell

I am computing expensive band structure calculations on a cluster, so what I what really want is to be able to load my data from a chkfile in order to plot them locally. Also, I was looking through the examples page, and I couldn't find an example of how to do this.

**Comment by tberkel** [comment]
All source files can be found on the github page, for example:
https://github.com/pyscf/pyscf/blob/master/pyscf/pbc/lib/chkfile.py
