### ISSUE TITLE
scf.KUKS(cell, kpts).getbands() has problems with symmetry 

### ISSUE THREAD

**Issue by simonganne01** [pyscf/pyscf#1925]
Hello, 

I am using the scf.KUKS object to accelerate my simulations. But when I want to plot the band diagram, it has a problem with the length of different arrays in the KNumInt.eval_rho2 function. ao_kpts has a length of 27 (3x3x3) while mo_coeff_kpts and mo_occ_kpts both have a length of 4 due to symmetry. Am I doing something wrong or is it a bug in the pySCF code? 

```kmesh = [3, 3, 3]
kpts = cell.make_kpts(kmesh, space_group_symmetry=True, time_reversal_symmetry=True)

run_scf = True

if run_scf:
    PBE = scf.KUKS(cell, kpts)
    PBE = scf.addons.smearing_(PBE, sigma=.1, method='fermi')
    PBE.xc = 'PBE'
    PBE.verbose = 4
    PBE.init_guess_breaksym=False
    PBE.init_guess = "1e"
    PBE.chkfile = 'SrVO3_PBE.chk'
    PBE.run();

## Calculate PBE bands non-selfconsistently
run_bands = True

# Define high-symmetry k-paths:
hspoints = {
  "G": [0.0, 0.0, 0.0],
  "X": [0.5, 0.0, 0.0],
  "M": [0.5, 0.5, 0.0],
  "R": [0.5, 0.5, 0.5]}

G = hspoints['G']
X = hspoints['X']
M = hspoints['M']
R = hspoints['R']
kpath = [G, X, M, G, R, X]
band_kpts, kpath, sp_points = get_bandpath(kpath, cell.a, npoints=50);
# band_kpts = libkpts.make_kpts(cell, band_kpts, space_group_symmetry=True, time_reversal_symmetry=True)
# band_kpts = cell.get_scaled_kpts(band_kpts, kpts_in_ibz=True)
band_kpts = cell.get_abs_kpts(band_kpts);

print(band_kpts)


# nscf along high-symmetry path:
if run_bands:
    nscf = scf.KUKS(cell, kpts)
    nscf.__dict__.update(chkfile.load("SrVO3_PBE.chk", 'scf'))
    E_nk = nscf.get_bands(np.array(band_kpts), kpts = kpts)[0] #the error occurs at this line
    E_F = nscf.get_fermi()
```

**Comment by simonganne01** [comment]
The following text file contains the entire error message. 




[IndexError.txt](https://github.com/pyscf/pyscf/files/13205395/IndexError.txt)

**Comment by pkozlows** [comment]
Are you using the matplotlib, or something similar, to plot your band structures? If so, would you be willing to share your plotting script? I am doing something similar. I want to learn how to save my data with the chkfile when I am running periodic calculations on a cluster, and then plotting the data locally.

**Comment by pkozlows** [comment]
And then I am confused by this warning
>/groups/wag/pkozlows/miniconda3/envs/pyscf/lib/python3.11/site-packages/ase/dft/kpoints.py:357: UserWarning: Please do not use (kpts, x, X) = bandpath(...).  Use path = bandpath(...) and then kpts = path.kpts and (x, X, labels) = path.get_linear_kpoint_axis().
  warnings.warn('Please do not use (kpts, x, X) = bandpath(...).  '

Even though this kind of syntax is in the [band_ase example](https://github.com/pyscf/pyscf/blob/master/examples/pbc/09-band_ase.py)

**Comment by tberkel** [comment]
Dear @pkozlows, please ask different questions in a new issue or re-open issue #1924 if you have further questions about that topic.

**Comment by simonganne01** [comment]
I dont know if I should make a new issue for this, but when I update to the newest version of pySCF I get this error when using the function gto.basis.parse("""..."""): 
 File ~/Thesis/quantum/lib/python3.10/site-packages/pyscf/gto/basis/__init__.py:496, in parse(string, symb, optimize)
    494         return parse_cp2k_pp.parse(string, symb)
    495     else:
--> 496         return parse_cp2k.parse(string, symb, optimize)
    497 else:
    498     return parse_nwchem.parse(string, symb, optimize)

TypeError: parse() takes from 1 to 2 positional arguments but 3 were given

**Comment by fishjojo** [comment]
@simonganne01 can you please provide a script that can reproduce your error? Thanks

**Comment by fishjojo** [comment]
This is a bug. A simple fix is to modify the line
https://github.com/pyscf/pyscf/blob/14d88828cd1f18f1e5358da1445355bde55322a1/pyscf/gto/basis/__init__.py#L496
as
```return parse_cp2k.parse(string, optimize)```
