### ISSUE TITLE
Computing bands

### ISSUE THREAD

**Issue by pkozlows** [pyscf/pyscf#1928]
I am struggling with the following block of code

```
kpts, kpath, sp_points = get_bandpath([L, G, X, W, K, G], ase_cell.cell, npoints=50) # assuming default cell dimensions
# path = get_bandpath([L, G, X, W, K, G], ase_cell.cell, npoints=50)
# kpts = path.kpts
# kpath, sp_points, labels = path.get_linear_kpoint_axis()


print(kpts.shape)
# Calculate bands
kpts = cell.get_abs_kpts(kpts)
e_kn_2 = kmf.get_bands(kpts)[0]
```
First of, I am getting the following error, even though this was the syntax mentioned in [the example](https://github.com/pyscf/pyscf/blob/master/examples/pbc/09-band_ase.py)
>/Users/patrykkozlowski/anaconda3/envs/pyscf_env/lib/python3.8/site-packages/ase/dft/kpoints.py:357: UserWarning: Please do not use (kpts, x, X) = bandpath(...).  Use path = bandpath(...) and then kpts = path.kpts and (x, X, labels) = path.get_linear_kpoint_axis().
  warnings.warn('Please do not use (kpts, x, X) = bandpath(...).  '

And then I am getting the following message
>Exception has occurred: LinAlgError
0-dimensional array given. Array must be at least two-dimensional
  File "/Users/patrykkozlowski/caltech/classes/caltech/f23/ch121b/si/trotting.py", line 43, in <module>
    kpts = cell.get_abs_kpts(kpts)
numpy.linalg.LinAlgError: 0-dimensional array given. Array must be at least two-dimensional

even though I have
>kpt.shape = (50,3)

**Comment by tberkel** [comment]
The "error" about bandpath is only a warning. The code should still run fine. It's raised because the get_bandpath() function is now deprecated in ASE. If you want to use the preferred syntax for ASE, you have to use `bandpath` not `get_bandpath`, as the warning shows. Specifically, you want:
```
path = bandpath([L, G, X, W, K, G], ase_cell.cell, npoints=50) # note change to bandpath
kpts = path.kpts
kpath, sp_points, labels = path.get_linear_kpoint_axis()
```
