### ISSUE TITLE
support range-separation for semi-local exchange

### ISSUE THREAD

**Issue by moolawooda** [pyscf/pyscf#1929]
PySCF has a excellent feature that we can customize our own exchange-correlation functional in `ks.xc` attribute. However, the range-separation operators `'RSH'`, `'LR_HF'`, `'SR_HF'` are only for HF exchange. The range-separation for semi-local exchange (including LDA, GGA and meta-GGA exchange) are also needed.

For example, the LC-BLYP may be written as `'LR_HF(0.33) + SR_B88(0.33), LYP'`.

**Comment by sunqm** [comment]
I'm not clear what is `SR_B88` functional. For libxc supported RSH functionals, their omega value will be set to the same one, the one you specified in the XC description string. If you don't specify omega in the xc string, another place to specify the omega parameter is the attribute `mf._numint.omega`, as @susilehtola  pointed out.

**Comment by verena-neufeld** [comment]
Hi @moolawooda , thanks for your question. Has it been answered?
