### ISSUE TITLE
Hyperpolarizability tensor

### ISSUE THREAD

**Issue by petermiedaner** [pyscf/pyscf#1933]
Hi. I need to compute hyperpolarizabilities for some organic molecules (and I don't have a license to Gaussian). In the latest paper on pySCF, it states that this type of calculation is possible, however I am having a hard time figuring out how to do. Is it possible to include a simple example for this type of calculation?

Thanks a lot

**Comment by fishjojo** [comment]
We probably don't have hyperpolarizability implemented. The polarizability is implemented for mean-field methods. https://github.com/pyscf/properties/blob/master/pyscf/prop/polarizability/rks.py

**Comment by petermiedaner** [comment]
In this code there are some functionals titled hyperpolarizability. Are these incomplete, or are they implemented fully?

Thanks again!
Pete

**Comment by petermiedaner** [comment]
Also, I don't see the Prop module in the most up to date version of pySCF. Is it deprecated? Will this only work with an earlier version?

**Comment by fishjojo** [comment]
You are right, hyperpolarizabilities are also available for mean-field methods. The `prop` module is now an extension to the PySCF core code base. You can follow the instructions here https://pyscf.org/install.html#extension-modules to install extension modules.

**Comment by petermiedaner** [comment]
Thanks so much! Could you point me to which extension module the polarizability function is contained in?

**Comment by shivupa** [comment]
It should be https://github.com/pyscf/properties/
Seems to have been missed on that list in the docs

**Comment by susilehtola** [comment]
If you're interested in hyperpolarizabilities, I would also suggest you have a look at [Veloxchem](https://gitlab.com/veloxchem/veloxchem) which is an open source code specialized in computing response properties.

**Comment by petermiedaner** [comment]
> If you're interested in hyperpolarizabilities, I would also suggest you have a look at [Veloxchem](https://gitlab.com/veloxchem/veloxchem) which is an open source code specialized in computing response properties.

Thanks for the suggestion. Veloxchem does not have a hyperpolarizability function implemented. Only linear response!

**Comment by susilehtola** [comment]
> Thanks for the suggestion. Veloxchem does not have a hyperpolarizability function implemented. Only linear response!

Oh ok, my bad, sorry! However, Dalton, which is nowadays also open source and is the program which pioneered many of these techniques, does appear to have first and second hyperpolarizability for coupled-cluster wave functions

https://daltonprogram.org/features/

**Comment by verena-neufeld** [comment]
Hi @petermiedaner , thanks for your question. Has it been answered?

**Comment by petermiedaner** [comment]
Yes it has,

Thanks!

On Dec 11, 2023, at 12:23 AM, Verena Neufeld ***@***.***> wrote:



Hi @petermiedaner<https://github.com/petermiedaner> , thanks for your question. Has it been answered?
