### ISSUE TITLE
Flipped signs in electron repulsion integrals 

### ISSUE THREAD

**Issue by mafaldaramoa** [pyscf/pyscf#1935]
Hello,

I am using pyscf to produce 1- and 2-electron integrals, but the latter have some signs flipped from run to run.

Code:
```
> from pyscf import scf, ao2mo, gto
> from openfermion.ops.representations import get_tensors_from_integrals
> import numpy as np

> mol = gto.Mole()
> mol.build(atom = f'''H 0 0 0; H  0 0 1.5; H 0 0 3; H 0 0 4.5''',basis = 'sto-3g')

> rhf = scf.RHF(mol)
> rhf.kernel()

> hcore_ao = mol.intor_symmetric('int1e_kin') + mol.intor_symmetric('int1e_nuc')
> hcore_mo = np.einsum('pi,pq,qj->ij', rhf.mo_coeff, hcore_ao, rhf.mo_coeff)

> eri_ao = mol.intor('int2e_sph', aosym=1)
> eri_mo = ao2mo.incore.full(eri_ao, rhf.mo_coeff)
```

Here are the last lines of `print(eri_mo)` for two different executions:

```
         [[ 4.21342964e-01, -1.80411242e-16, -6.99445514e-02,
           1.11022302e-16],
         [-1.94289029e-16,  3.77123524e-01, -1.38777878e-16,
          -7.46194315e-02],
         [-6.99445514e-02, -1.38777878e-16,  3.85050730e-01,
          -2.49800181e-16],
         [ 8.32667268e-17, -7.46194315e-02, -3.05311332e-16,
           4.51241395e-01]]]])
```

```
        [[ 4.21342964e-01,  4.99600361e-16, -6.99445514e-02,
           0.00000000e+00],
         [ 4.85722573e-16,  3.77123524e-01,  3.60822483e-16,
           7.46194315e-02],
         [-6.99445514e-02,  3.88578059e-16,  3.85050730e-01,
          -3.05311332e-16],
         [ 2.77555756e-17,  7.46194315e-02, -2.91433544e-16,
           4.51241395e-01]]]])
```

The fourth element in the second row and the second element in the last row flipped signs. 

I have checked that `eri_ao` is always the same (up to rounding variations). The variation seems to stem from `rhf.mo_coeff`. Here are two outputs for `print(rhf.mo_coeff)`:

```
array([[ 0.34443364, -0.53384112,  0.64274991,  0.50668998],
       [ 0.48057281, -0.39332566, -0.43858754, -0.75752626],
       [ 0.48057281,  0.39332566, -0.43858754,  0.75752626],
       [ 0.34443364,  0.53384112,  0.64274991, -0.50668998]])
```

```
array([[ 0.34443364, -0.53384112,  0.64274991, -0.50668998],
       [ 0.48057281, -0.39332566, -0.43858754,  0.75752626],
       [ 0.48057281,  0.39332566, -0.43858754, -0.75752626],
       [ 0.34443364,  0.53384112,  0.64274991,  0.50668998]])
```

In this case, the fourth column has the signs flipped. This happens to the second column sometimes, too. In some runs both of these columns flip signs at a time, in other runs only one of them does.

**Version: 2.4.0**

**Comment by tberkel** [comment]
Molecular orbitals are eigenvectors and thus only defined up to an overall
sign.

**Comment by mafaldaramoa** [comment]
Thank you for the response. Is there a way to make this deterministic? Because as the Hamiltonian is different (signs flipped) across different runs, the same state might have different energies for the exact same molecule definition. This is problematic for my application (variational quantum eigensolver).

**Comment by susilehtola** [comment]
You can enforce a sign convention to the molecular orbitals by computing the norms of the negative and positive coefficients, and multiplying the orbital by -1 if the negative part has a larger norm than the positive part.

**Comment by tberkel** [comment]
I was actually a bit surprised this happens, because PySCF tries to enforce
a sign convention here:
https://github.com/pyscf/pyscf/blob/master/pyscf/scf/hf.py#L1203
but I guess that for symmetric systems, multiple AO coefficients will have
the same magnitude but opposite sign, and which one's idx gets selected by
argmax is non-deterministic.

**Comment by mafaldaramoa** [comment]
Thank you!

I imagined there was a sign convention because this never happened with other molecules, I've used LiH, HF, BeH2, etc and outputs are deterministic for them. Additionally I think a deterministic behaviour would be expected/desirable.

Using the norms of the sums of the positive and negative coefficients to decide when to flip signs doesn't work either. In the columns where `argmax` is ambiguous for the maximum magnitude, it is ambiguous for the maximum (positive/negative) norm.

I'm not sure I understand why not go for something simpler, like multiply the column by -1 based on the sign of its first entry? Something like `c[:,c[0,:]>0] *= -1` instead of the [lines 1202, 1203 of the `eig` function](https://github.com/pyscf/pyscf/blob/master/pyscf/scf/hf.py#L1202-L1203). Is there something wrong with this?

It would be useful to see this ambiguity removed from pyscf, especially because in some situations the user has no control over this. E.g. using the `run_pyscf` function on the OpenFermion-PySCf plug-in, the output is a molecule whose Hamiltonian will have some signs flipped. It's harder to make it consistent at that point.

**Comment by mafaldaramoa** [comment]
My program is single-threaded so that can't be the source of the variations.

The indeterminism is fine for e.g. variational methods, because then it is absorbed by the variational parameter and the output energy is the same. But for fixed coefficients, the energy will be different across different runs. This is inconvenient because the parameters that define the ground state are not well defined. So I can't find the ground state variationally and store the coefficients to use later, unless I also store the Hamiltonian (which I don't want to).

**Comment by obackhouse** [comment]
I would check your environment for sources of non-determinism that aren't directly related to PySCF -- your script is deterministic on my machine in the absence of threading.

**Comment by mafaldaramoa** [comment]
Hello,

I have tried running it in two different machines (Ubuntu distribution of Linux, releases 18.04 and 20.04) and in both of them the output varies. I have no clue as to what could be causing this. I'm handling it with `rhf.mo_coeff[:,rhf.mo_coeff[0,:]>0] *= -1` which assures deterministic behaviour.

Personally, I feel like it would be desirable for the output to be consistent - even in the presence of threading. There being an easy fix, I would suggest incorporating it in the source code.

**Comment by sunqm** [comment]
@mafaldaramoa Phase is handled in the `eig` function of `pyscf/scf/hf.py` . However, determining phase is not as obvious as you think, after considering the symmetry, the numerical noises. I'll close this issue as the phase in eigenvalue problem is a well-known issue.
