### ISSUE TITLE
df is slow because there is no dm.mo_coeff recently.

### ISSUE THREAD

**Issue by baopengbp** [pyscf/pyscf#1936]
No libtag in hf.kernel recently

**Comment by baopengbp** [comment]
Add self.direct_scf = False    in   pyscf.df.df.__init__     will solve the problem.

Or add    mf.direct_scf = False      in your script.

**Comment by sunqm** [comment]
Do you have an example to demonstrate the issue? dm should be tagged in each make_rdm1 function. Therefore I removed the tag statement in hf kernel function.

**Comment by baopengbp** [comment]
#!/usr/bin/env python

import time
from pyscf import gto, scf, dft, lib
lib.logger.TIMER_LEVEL = 0

mol = gto.M(atom='''C 2.16778 -0.44918 -0.04589
C 1.60190 0.33213 -1.23844
C 0.12647 -0.01717 -1.47395
C -0.77327 0.24355 -0.24682
C 1.32708 -0.12314 1.19439
C -0.15779 -0.45451 0.98457
C 3.64976 -0.11557 0.18351
O -0.82190 -0.04249 2.15412
C -2.23720 -0.18449 -0.53693
C -3.19414 0.02978 0.65049
C -2.83291 0.54586 -1.75716
H -0.78551 -0.74689 2.78026
H 3.79206 0.96776 0.40070
H 4.06333 -0.69236 1.04258
H 4.26160 -0.36608 -0.71348
H -2.98219 -0.66492 1.49356
H -3.14394 1.07829 1.02340
H -4.25233 -0.17395 0.36759
H -2.76237 1.65099 -1.63614
H -2.33431 0.26367 -2.71114
H -3.90769 0.29147 -1.90369
H -2.23894 -1.27795 -0.76804
H -0.76619 1.34209 -0.04759
H -0.29859 -1.55818 0.89954
H 1.70030 1.42806 -1.05330
H 2.19423 0.10028 -2.15602
H -0.21377 0.58584 -2.34721
H 0.04969 -1.09183 -1.76338
H 1.71426 -0.69369 2.07216
H 1.43065 0.96079 1.43691
H 2.08462 -1.54360 -0.25842''',
            basis='ccpvtz')

Jtime=time.time()
mf = scf.RHF(mol).density_fit('ccpvtz-jkfit')
mf.verbose = 4
mf.kernel()
print( "Took this long for direct_scf: ", time.time()-Jtime)

Jtime=time.time()
mf = scf.RHF(mol).density_fit('ccpvtz-jkfit')
mf.direct_scf = False
mf.verbose = 4
mf.kernel()
print( "Took this long for direct_scf = False: ", time.time()-Jtime)

**Comment by baopengbp** [comment]
/home/baop/anaconda3/envs/my3.7/lib/python3.7/site-packages/pyscf/gto/mole.py:124: RuntimeWarning: divide by zero encountered in true_divide
  return scipy.special.gamma(n1) / (2. * alpha**n1)


******** <class 'pyscf.df.df_jk.density_fit.<locals>.DensityFitting'> ********
method = DensityFitting-RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-09
SCF conv_tol_grad = None
SCF max_cycles = 50
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /tmp/baop/tmpxgy6jb1j
max_memory 192000 MB (current use 123 MB)
Set gradient conv threshold to 3.16228e-05
<class 'pyscf.df.df.DF'> does not have attributes  direct_scf
    CPU time for cholesky_eri     22.64 sec, wall time      3.75 sec
    CPU time for df vj and vk     52.13 sec, wall time      5.69 sec
/home/baop/anaconda3/envs/my3.7/lib/python3.7/site-packages/pyscf/gto/mole.py:1476: RuntimeWarning: divide by zero encountered in true_divide
  e = numpy.einsum('i,ij,j->', charges, 1./rr, charges) * .5
init E= -467.329039752645
    CPU time for initialize scf     54.36 sec, wall time      5.87 sec
  HOMO = -0.268694558843362  LUMO = 0.0873526544329479
    CPU time for df vj and vk     29.53 sec, wall time      1.85 sec
cycle= 1 E= -465.18444297919  delta_E= 2.14  |g|= 0.718  |ddm|= 3.41
    CPU time for cycle= 1     30.34 sec, wall time      1.90 sec
  HOMO = -0.374452939498159  LUMO = 0.117389637445272
    CPU time for df vj and vk     29.38 sec, wall time      1.84 sec
cycle= 2 E= -465.316210644668  delta_E= -0.132  |g|= 0.346  |ddm|= 0.752
    CPU time for cycle= 2     30.31 sec, wall time      1.90 sec
  HOMO = -0.391911066241472  LUMO = 0.132035106803558
    CPU time for df vj and vk     29.25 sec, wall time      1.83 sec
cycle= 3 E= -465.338459585724  delta_E= -0.0222  |g|= 0.11  |ddm|= 0.284
    CPU time for cycle= 3     30.20 sec, wall time      1.89 sec
  HOMO = -0.395558643097438  LUMO = 0.132627520093074
    CPU time for df vj and vk     29.29 sec, wall time      1.84 sec
cycle= 4 E= -465.341627871979  delta_E= -0.00317  |g|= 0.0137  |ddm|= 0.106
    CPU time for cycle= 4     30.20 sec, wall time      1.89 sec
  HOMO = -0.397575845392436  LUMO = 0.132358668152121
    CPU time for df vj and vk     29.28 sec, wall time      1.84 sec
cycle= 5 E= -465.341686675512  delta_E= -5.88e-05  |g|= 0.00379  |ddm|= 0.0208
    CPU time for cycle= 5     30.26 sec, wall time      1.90 sec
  HOMO = -0.397546937232921  LUMO = 0.13249845869163
    CPU time for df vj and vk     29.16 sec, wall time      1.83 sec
cycle= 6 E= -465.341691808999  delta_E= -5.13e-06  |g|= 0.0012  |ddm|= 0.00628
    CPU time for cycle= 6     30.08 sec, wall time      1.89 sec
  HOMO = -0.397628688931146  LUMO = 0.132518573830223
    CPU time for df vj and vk     29.15 sec, wall time      1.83 sec
cycle= 7 E= -465.341692372379  delta_E= -5.63e-07  |g|= 0.00031  |ddm|= 0.00246
    CPU time for cycle= 7     30.00 sec, wall time      1.88 sec
  HOMO = -0.397678097220983  LUMO = 0.132515845403825
    CPU time for df vj and vk     29.20 sec, wall time      1.83 sec
cycle= 8 E= -465.341692418598  delta_E= -4.62e-08  |g|= 0.0001  |ddm|= 0.000877
    CPU time for cycle= 8     30.04 sec, wall time      1.88 sec
  HOMO = -0.397671525088357  LUMO = 0.132519798425087
    CPU time for df vj and vk     29.30 sec, wall time      1.84 sec
cycle= 9 E= -465.341692422852  delta_E= -4.25e-09  |g|= 2.53e-05  |ddm|= 0.000224
    CPU time for cycle= 9     30.24 sec, wall time      1.90 sec
  HOMO = -0.397673232094026  LUMO = 0.132519696430785
    CPU time for df vj and vk     29.22 sec, wall time      1.83 sec
cycle= 10 E= -465.341692423157  delta_E= -3.04e-10  |g|= 6.5e-06  |ddm|= 6.5e-05
    CPU time for cycle= 10     30.26 sec, wall time      1.90 sec
  HOMO = -0.397672921639294  LUMO = 0.132519614379087
    CPU time for df vj and vk     29.19 sec, wall time      1.83 sec
Extra cycle  E= -465.341692423178  delta_E= -2.09e-11  |g|= 3.06e-06  |ddm|= 1.17e-05
    CPU time for scf_cycle    386.26 sec, wall time     26.68 sec
    CPU time for SCF    386.28 sec, wall time     26.68 sec
converged SCF energy = -465.341692423178
Took this long for direct_scf:  26.683485984802246


******** <class 'pyscf.df.df_jk.density_fit.<locals>.DensityFitting'> ********
method = DensityFitting-RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-09
SCF conv_tol_grad = None
SCF max_cycles = 50
direct_scf = False
chkfile to save SCF result = /tmp/baop/tmpec_km5gf
max_memory 192000 MB (current use 488 MB)
Set gradient conv threshold to 3.16228e-05
    CPU time for cholesky_eri     21.80 sec, wall time      3.85 sec
    CPU time for df vj and vk     49.59 sec, wall time      5.67 sec
init E= -467.329039752645
    CPU time for initialize scf     51.62 sec, wall time      5.80 sec
  HOMO = -0.268694558843362  LUMO = 0.087352654432952
    CPU time for df vj and vk     11.17 sec, wall time      0.70 sec
cycle= 1 E= -465.184442979191  delta_E= 2.14  |g|= 0.718  |ddm|= 3.41
    CPU time for cycle= 1     11.85 sec, wall time      0.74 sec
  HOMO = -0.374452939498158  LUMO = 0.117389637445177
    CPU time for df vj and vk     11.15 sec, wall time      0.70 sec
cycle= 2 E= -465.316210644668  delta_E= -0.132  |g|= 0.346  |ddm|= 0.752
    CPU time for cycle= 2     12.00 sec, wall time      0.75 sec
  HOMO = -0.391911066241448  LUMO = 0.132035106803479
    CPU time for df vj and vk     11.03 sec, wall time      0.69 sec
cycle= 3 E= -465.338459585725  delta_E= -0.0222  |g|= 0.11  |ddm|= 0.284
    CPU time for cycle= 3     11.89 sec, wall time      0.75 sec
  HOMO = -0.395558643097467  LUMO = 0.132627520092987
    CPU time for df vj and vk     11.15 sec, wall time      0.70 sec
cycle= 4 E= -465.34162787198  delta_E= -0.00317  |g|= 0.0137  |ddm|= 0.106
    CPU time for cycle= 4     11.95 sec, wall time      0.75 sec
  HOMO = -0.397575845392428  LUMO = 0.132358668152056
    CPU time for df vj and vk     11.24 sec, wall time      0.70 sec
cycle= 5 E= -465.341686675511  delta_E= -5.88e-05  |g|= 0.00379  |ddm|= 0.0208
    CPU time for cycle= 5     12.03 sec, wall time      0.75 sec
  HOMO = -0.397546937232936  LUMO = 0.132498458691555
    CPU time for df vj and vk     11.12 sec, wall time      0.70 sec
cycle= 6 E= -465.341691808999  delta_E= -5.13e-06  |g|= 0.0012  |ddm|= 0.00628
    CPU time for cycle= 6     12.11 sec, wall time      0.76 sec
  HOMO = -0.397628688931178  LUMO = 0.132518573830205
    CPU time for df vj and vk     11.17 sec, wall time      0.70 sec
cycle= 7 E= -465.341692372382  delta_E= -5.63e-07  |g|= 0.00031  |ddm|= 0.00246
    CPU time for cycle= 7     12.05 sec, wall time      0.76 sec
  HOMO = -0.397678097221026  LUMO = 0.132515845403849
    CPU time for df vj and vk     11.05 sec, wall time      0.69 sec
cycle= 8 E= -465.3416924186  delta_E= -4.62e-08  |g|= 0.0001  |ddm|= 0.000877
    CPU time for cycle= 8     11.85 sec, wall time      0.74 sec
  HOMO = -0.397671525088403  LUMO = 0.132519798425013
    CPU time for df vj and vk     11.03 sec, wall time      0.69 sec
cycle= 9 E= -465.341692422851  delta_E= -4.25e-09  |g|= 2.53e-05  |ddm|= 0.000224
    CPU time for cycle= 9     11.83 sec, wall time      0.74 sec
  HOMO = -0.397673232093987  LUMO = 0.132519696430709
    CPU time for df vj and vk     11.02 sec, wall time      0.69 sec
cycle= 10 E= -465.341692423155  delta_E= -3.04e-10  |g|= 6.5e-06  |ddm|= 6.5e-05
    CPU time for cycle= 10     11.82 sec, wall time      0.74 sec
  HOMO = -0.3976729216393  LUMO = 0.13251961437895
    CPU time for df vj and vk     11.07 sec, wall time      0.69 sec
Extra cycle  E= -465.341692423181  delta_E= -2.61e-11  |g|= 3.06e-06  |ddm|= 1.17e-05
    CPU time for scf_cycle    182.69 sec, wall time     14.01 sec
    CPU time for SCF    182.72 sec, wall time     14.02 sec
converged SCF energy = -465.341692423181
Took this long for direct_scf = False:  14.021318435668945

**Comment by baopengbp** [comment]
Then I think adding the default self.direct_scf = False in pyscf.df.df.init will be better.

**Comment by baopengbp** [comment]
It is not the problem of libtag. it is the problem of the setting of direct_scf. 
Sometimes I forgot this setting.

**Comment by sunqm** [comment]
I see. Without disabling direct_scf, density fitting will evaluate the K matrix with the slow contraction branch `einsum('pij,pkl,jk->il', cderi, cderi, dm)`. Disabling direct_scf will also bring the information of orbital coefficients, which allows the contraction first transform one index to occupied MO.

It has been taken into account in PR #1882. The 2.4 version should work the same with or without setting direct_scf

**Comment by baopengbp** [comment]
It will be so convenient and efficient to do df-j and df-jk efficiently in new version.

**Comment by baopengbp** [comment]
It will be so convenient and efficient to do df-j and df-jk efficiently in new version.

**Comment by sunqm** [comment]
Issue solved since pyscf-2.4
