### ISSUE TITLE
Energy terms in periodic DFT using the 1-RDM, ERIs and `h1e`

### ISSUE THREAD

**Issue by jackbaker1001** [pyscf/pyscf#1937]
I am trying to calculate the one-body (`e1`) and coulomb term (`coul`) in the DFT total energy where the main variables are the 1-particle reduced density matrix (`rdm1`), the electron repulsion integrals (ERIs) and the PySCF variable `h1e`. I need this for one of my projects and i'm struggling with how to do this for a periodic system: especially the `coul` term.

This is clear to me for an isolated molecular system (and indeed a $\Gamma$-point only periodic calculation) but in the case of multiple k-points and sampling over the 1BZ I just can't seem to get my `coul` to match `coul` reported by `mf.scf_summary`. Before we get to the periodic BZ sampling case, let me just show the (working) version in open boundary conditions.

## Open boundary conditions and $\Gamma$-point only PBC

In open boundary conditions, the one-particle energy (kinetic + external; `e1`) is given by:

$$
E_{1e} = \sum_{p, q}D_{pq}H^{1e}_{pq}
$$

and Coulomb energy as

$$
E_{C} = \frac{1}{2}\sum_{p, q, r, s} D_{pq} (pq|rs)D_{rs}
$$

where $D_{ij}$ is a 1-RDM matrix element, $H^{1e}_{ij}$ is "1e Hamiltonian" (`h1e`) matrix element and $(pq|rs)$ is an electron repulsion integral.

These can be verified fairly easily by running a simple calculation in PySCF can comparing the output of both formulas with `mf.scf_summary`. In code:

```python
from pyscf import gto, scf
import numpy as np

mol = gto.M(
    atom = """H     0.0  0.0  0.0
              H     1.4   0.0   0.0""",
    basis = 'sto-3g',
)

mf = scf.RKS(mol)
mf.max_cycle = 5
mf.xc = "LDA"
mf = mf.run()

# Directly from PySCF
print('e1 from PySCF is', mf.scf_summary['e1'])
print('coul from PySCF is', mf.scf_summary['coul'])

# Calculated directly using other output from PySCF
rdm1 = mf.make_rdm1()
h1e = mf.get_hcore()
eri = mol.intor("int2e")
e1_calc = np.einsum("pq,pq->", rdm1, h1e)
coul_calc = np.einsum("pq,pqrs,rs->", rdm1, eri, rdm1)/2
print('e1 from direct calculation is', e1_calc)
print('coul from direct calculation is', coul_calc)
```

which has output:

```bash
converged SCF energy = -0.897130609627569
e1 from PySCF is -1.8842831028481113
coul from PySCF is 1.1296374521092152
e1 from direct calculation is -1.8842831028481115
coul from direct calculation is 1.1296374521092152
```

You can also verify that the same things works for Hydrogen in a box in PBCs using only the $\Gamma$-point in the 1BZ sampling by simply adding another index k to the `np.einsum`'s or `np.squeeze`'ing the redundant k-point dimension out of the 1RDM, ERI (use the density fitted version)  using the existing `np.einsum`'s. For brevity, I have not included this.

## PBC's with multi-k-point 1BZ sampling 

In periodic boundary conditions with multi-k-point 1BZ samping, the one-particle energy (kinetic + external; `e1`) is given by:

$$
E_{1e} = \frac{1}{N_{\mathbf{k}}}\sum_{\mathbf{k}}\sum_{p, q}D_{pq}(\mathbf{k})H^{1e}_{pq}(\mathbf{k})
$$

for some finite number of k-points ($N_{\mathbf{k}}$) in the 1BZ typically given by a Monkhorst-Pack grid. The coulomb energy (**which I hope is correct, please check this, it may be why I get this wrong**) is given by

```math
E_{C} = \frac{1}{2N_{k_{conserve}}}  \sum_{\mathbf{k}_p, \mathbf{k}_q, \mathbf{k}_r, \mathbf{k}_s} \sum_{p, q, r, s} D_{pq}(\mathbf{k}_p) (p\mathbf{k}_pq\mathbf{k}_q|r\mathbf{k}_rs\mathbf{k}_s)D_{rs}(\mathbf{k}_r)
```

In code, you can easily verify $E_{1e}$ is correct similarly to before:

```python

from pyscf.pbc import gto, scf
import numpy as np

cell = gto.M(
    a = np.eye(3)*3.8,
    atom = """H     0.0  0.0  0.0
              H     1.4   0.0   0.0""",
    basis = 'sto-3g',
    space_group_symmetry=False,
    symmorphic=False,
)

kmf = scf.KRKS(cell, kpts=cell.make_kpts([2, 2 , 2])).density_fit()
kmf.max_cycle = 5
kmf.xc = "LDA"
kmf = kmf.run()

print('e1 from PySCF is', kmf.scf_summary['e1'])

rdm1 = kmf.make_rdm1()
h1e = kmf.get_hcore()

e1_calc = (np.einsum("kpq,kpq->", rdm1, h1e)/kmf.kpts.shape[0]).real
print('e1 from direct calculation is', e1_calc)
```

which has output:

```bash
converged SCF energy = -0.895777407152987
e1 from PySCF is -0.4359114777571714
e1 from direct calculation is -0.4359114777571713
```

**Now, this is where things go wrong. This is my attempt at $E_C$ in code:**

```python
from pyscf.pbc.lib.kpts_helper import get_kconserv
from itertools import product
from pyscf.pbc import df

# get crystal momentum conserving k-point quartet indices
kpts = kmf.kpts
s_con = get_kconserv(kmf.cell, kpts=kpts)
all_3tuple_idx = product(range(kpts.shape[0]), repeat=3)
k4_indices = np.asarray([[p, q, r, s_con[p, q, r]] for p, q, r in all_3tuple_idx])

# Get the DF ERI for each quartet, accumulate coulomb energy
density_fitter = df.DF(kmf.cell, kpts=kpts)
nao = rdm1.shape[1]
coulomb_energy = 0
for i, k4_idx in enumerate(k4_indices):
    k_quartet = kpts[k4_idx]
    kp_idx = k4_idx[0]
    kr_idx = k4_idx[2]
    eri = density_fitter.get_eri(compact=False, kpts=k_quartet).reshape(nao, nao, nao, nao)
    energy_contribution = np.einsum(
        "pq,pqrs,rs->", rdm1[kp_idx], eri, rdm1[kr_idx]
    )
    coulomb_energy += energy_contribution
    
coul_calc = (coulomb_energy/(2*k4_indices.shape[0])).real


print('coul from direct calculation is', coul_calc)
print('coul from PySCF is', kmf.scf_summary['coul'])
```

which has the (wrong) output:

```bash
coul from direct calculation is 0.7471970466302482
coul from PySCF is 0.4265132388975059
```

I would be really grateful if anybody here could make sense of this. I've been playing with this for some time and can't figure out the problem... I don't know if this is a bug in PySCF or me being silly. Anyways, thank you for reading! 

Any thoughts?

**Comment by jackbaker1001** [comment]
Perhaps this is something to do with the inclusion of the $\Gamma$-point on the Monkhorst-Pack grid? Indeed, I have just noticed that the periodic $E_{1e}$ is also wrong if the Monkhorst-Pack grid **does not** include the $\Gamma$-point.

**Comment by tberkel** [comment]
The 1e energy is the trace of the matrix product (note the order of pq/qp),

$$ E_{1e} = \sum_{p, q}D_{pq}H^{1e}_{qp} $$

In open boundary conditions, your results are still correct bc of symmetry of the matrices. With k-points, the matrices can be complex, and the order matters. If you change to
`e1_calc = (np.einsum("kpq,kqp->", rdm1, h1e)/kmf.kpts.shape[0]).real`
then your e1 will agree with PySCF's, even when the kpt mesh does not include Gamma (which is when the matrices are complex for 2 k-points).

Haven't looked closely at the moment, but possibly a similar issue with your 2e energy.

**Comment by jackbaker1001** [comment]
Thanks @tberkel. You are correct about the 1e energy. Flipping the indices of one matrix fixes things in PBC. Still struggling with the coulomb energy! Please do let me know if you have any insights there.

**Comment by jackbaker1001** [comment]
hmm @tberkel if you choose to only be diagonal in k for the ERI's rather than check every momentum conserving quartet, you can get the right `coul` for meshes **without** the gamma point:

```python
kpts = kmf.kpts

# Get the DF ERI for each quartet, accumulate coulomb energy
density_fitter = df.DF(kmf.cell, kpts=kpts)
nao = rdm1.shape[1]
coulomb_energy = 0
for i, kpt in enumerate(kpts):
    k4_idx = np.array([i for j in range(4)])
    k_quartet = kpts[k4_idx]
    eri = density_fitter.get_eri(compact=False, kpts=k_quartet).reshape(nao, nao, nao, nao)
    energy_contribution = np.einsum(
            "qp,pqrs,rs->", rdm1[i], eri, rdm1[i].conj()
        )
    coulomb_energy += energy_contribution
    
coul_calc = (coulomb_energy/(2*kpts.shape[0])).real


print('coul from direct calculation is', coul_calc)
print('coul from PySCF is', kmf.scf_summary['coul'])
``` 

am I missing come subtley when gamma is on the mesh becuase some RDM1's are complex while others are real? (non-gamma versus gamma)

**Comment by tberkel** [comment]
Indeed, I think you had too many kpts in your first expression. The Coulomb energy can also be written as the trace of the product of the RDM with the Hartree/Coulomb matrix J. The following two versions should work, one uses the `get_j` function of PySCF as a comparison.

```
nk = len(kpts)

# version 1, test
j = kmf.get_j()
coul_calc_1 = 0.5*(np.einsum("kpq,kqp->", rdm1, j)/nk).real

# version 2, build j from eri
coulomb_energy = 0
for ki,kpt in enumerate(kpts):
    j_k = 0
    for qj,qpt in enumerate(kpts):
        eri = density_fitter.get_eri(compact=False, kpts=[kpt,kpt,qpt,qpt]).reshape(nao, nao, nao, nao)
        j_k += np.einsum("pqrs,sr->pq", eri, rdm1[qj])/nk
    coulomb_energy += np.einsum("pq,qp", rdm1[ki], j_k)

coul_calc_2 = (coulomb_energy/(2*nk)).real
print('coul from direct calculation 1 is', coul_calc_1)
print('coul from direct calculation 2 is', coul_calc_2)
print('coul from PySCF is', kmf.scf_summary['coul']
```

**Comment by verena-neufeld** [comment]
Thanks for posting this question @jackbaker1001. Is it resolved now?

**Comment by jackbaker1001** [comment]
Hi @verena-neufeld . Yes. This question has been answered. As pointed out by @tberkel , I simply was using the wrong formula for the Coublomb energy of the periodic system. Instead of summing over all possible crystal momenta conserving k-quartets, I needed to considered all possible pairs of k or the MP mesh.
