### ISSUE TITLE
Obtaining unconverged density matrices for intermediate steps in a DFT calculation

### ISSUE THREAD

**Issue by jc-umana-FI** [pyscf/pyscf#1939]
Howdy!

My colleagues and I are trying to get density matrices for each step in our SCF calculations prior to convergence. For context, we're developing a dataset to train a neural network not unlike that which was mentioned in [Issue #1847](https://github.com/pyscf/pyscf/issues/1847).

We are fully aware that we could set the max_cycles to the desired steps prior to convergence to obtain the final density matrix for the step that we went up to, but this seems quite tedious. Also, we're trying to stay working within pySCF rather than pulling the density matrices from another package such as Gaussian or the like. 

So, we are wondering if there is a way to obtain the density matrices for each step in a single DFT calculation of _n_ steps natively in pySCF. If so, how do we do it?

Please let me know, I appreciate any help with the matter, and I look forward to your response!

**Comment by fishjojo** [comment]
see https://github.com/pyscf/pyscf/blob/master/examples/scf/24-callback.py
The callback function is called at the end of each SCF iteration.

**Comment by verena-neufeld** [comment]
Hi @jc-umana-FI , thanks for posting your question. Has it been resolved now?

**Comment by jc-umana-FI** [comment]
Hi, thank you for the hint -- the issue has been resolved! I've linked a Colab Notebook that goes through recovering unconverged density matrices from a KS-DFT calculation [here](https://colab.research.google.com/drive/1tHwIx8degyC1U-8Xaye1TnrNxZeQs6-w?usp=sharing).

Closing the issue now.
