### ISSUE TITLE
Why can't obtain target state when set symmetry=True?

### ISSUE THREAD

**Issue by sunnowrun** [pyscf/pyscf#1940]
When I run following code, I get energies `[-15.48174107 -15.19355188 -15.19355188 -15.17933966]`

	from pyscf import gto, scf, fci
	mol = gto.M(atom='Be 0 0 0; H 0 0 1; H 0 0 -1', basis='sto-3g')
	m = scf.RHF(mol)
	m.kernel()
	norb = m.mo_energy.size
	fs = fci.FCI(mol, m.mo_coeff)
	e, c = fs.kernel(nroots = 4)
	print(e)

But when I set `symmetry=True`, I can't obtain the state with energy `-15.19355188`

	from pyscf import gto, scf, fci
	mol = gto.M(atom='Be 0 0 0; H 0 0 1; H 0 0 -1', basis='sto-3g', symmetry=True)
	m = scf.RHF(mol)
	m.kernel()
	norb = m.mo_energy.size
	for wfnsym in mol.irrep_name:
		fs = fci.FCI(mol, m.mo_coeff)
		fs.wfnsym = wfnsym
		e, c = fs.kernel(nroots = 8)
		print(e)

Why can't I obtain that state? Thank you in advance!

**Comment by sunqm** [comment]
`mol.irrep_name` labels the symmetry of orbitals. The symmetry of FCI wavefunction is the product of orbitals irreps. It can be the irrep not available in orbital symmetry. You can try E2ux, E2gx, etc. for wfnsym

**Comment by sunnowrun** [comment]
Thank you, I iterate through the whole symmetry and got that state

	from pyscf import gto, scf, fci
	import pyscf

	mol = gto.M(atom='Be 0 0 0; H 0 0 1; H 0 0 -1', basis='sto-3g', symmetry="D2h")
	m = scf.RHF(mol)
	m.kernel()
	norb = m.mo_energy.size

	group_dict = pyscf.symm.param.IRREP_ID_TABLE[mol.groupname]
	elems = group_dict.keys()


	for wfnsym in elems:
		fs = fci.FCI(mol, m.mo_coeff)
		fs.wfnsym = wfnsym
		e, c = fs.kernel(nroots = 4)
		for i in range(len(e)):
			print('E = %.12f  2S+1 = %.7f' % (e[i], fs.spin_square(c[i], norb, mol.nelec)[1]))
		print()
