### ISSUE TITLE
TDA for XES / negative eigenvalues?

### ISSUE THREAD

**Issue by t-fransson** [pyscf/pyscf#1952]
Dear developers,

It seems to me that the current TDA implementation removes any negative states when calculating excited states, which makes sense for most applications. However, there is an approach in which X-ray emission spectra (XES) are calculated by first constructing a core-hole reference state (using the maximum overlap approach or some similar approach), and then computing the excited states with TDA (see, e.g., https://wires.onlinelibrary.wiley.com/doi/full/10.1002/wcms.1527 and references therein). The first few negative eigenstates then correspond to (de)excitations into the core-hole.

PySCF has a very nice MOM-implementation, but the requirement of positive states means that XES cannot be considered. Would it be possible to extend the TDA implementation to also be capable of dealing with such situations?

**Comment by tberkel** [comment]
The TDSCF classes have an attribute `self.positive_eig_threshold` whose default is 1e-3. (It can also be set in config as `tdscf_rhf_TDDFT_positive_eig_threshold`). So if you wanted to allow negative excitation energies, you could do something like
```
mytd.positive_eig_threshold = -1e10
```

**Comment by t-fransson** [comment]
That worked perfectly! Thank you for the rapid reply!
