### ISSUE TITLE
Get the PySCF input file 

### ISSUE THREAD

**Issue by DeepDevIA** [pyscf/pyscf#1957]
Hi there
I'm newer on PySCF and I found a paper about DFT correction energy https://doi.org/10.1126/science.abj6511 for my work I do some calculations but i have some problems to create a B3LYP input file pyscf for this type of calculation (see the image )
can get help please to do this ??
thanks
 
![image](https://github.com/pyscf/pyscf/assets/150791151/e8fe06be-6d36-4b60-972c-6852358bcaf2)

**Comment by tberkel** [comment]
The PySCF developers were not involved in the paper you linked, so we can't easily provide you with an input file for that calculation. I'll note that doing DFT calculations with fractional occupation is not a standard calculation that PySCF supports, and one has to modify some of the functions themselves.

**Comment by DeepDevIA** [comment]
thank you for your comments

**Comment by verena-neufeld** [comment]
Hi @DeepDevIA , thanks for the question. Has it been answered?
