### ISSUE TITLE
Re-ordering basis functions introduces mismatch

### ISSUE THREAD

**Issue by kevfocke** [pyscf/pyscf#1961]
#1620 introduced ordering basis functions if they are not ordered correctly. When using `molden.load` to load molecules from molden files, the MO coefficients are not ordered accordingly, which leads to a mismatch and therefore wrong results. 
One example would be the minimally augmented basis sets (like ma-def2-SVP) from ORCA, which have some s-type AOs appended after the p-type AOs from the standard def2-SVP.

The code has changed significantly since #1620, which makes fixing the problem a bit harder.

**Comment by hebrewsnabla** [comment]
I tested an example with aug-cc-pvtz using pyscf 2.2.0, which is released before 1620, and it shows that the basis is still re-ordered. So I guess this re-ordering is not a feature introduced in recent versions but much earlier?

**Comment by verena-neufeld** [comment]
Hi @kevfocke , thanks! Has it been fixed now and can this issue be closed?

**Comment by kevfocke** [comment]
@verena-neufeld Yes, sure, thank you!
