### ISSUE TITLE
Excessive difference in energies obtained by Gaussian and PySCF

### ISSUE THREAD

**Issue by moolawooda** [pyscf/pyscf#1976]
The following shows the input files and results of a water molecule at the level b3lyp/6-31g(d) computed by PySCF and Gaussian. The difference in energy calculated by the two software is about 1.2 kcal/mol, which seems too large that I don't know which one is correct.

**H2O.py**
```
from pyscf import gto, dft

mol = gto.M(
    atom = '''
O                  0.00000000    0.00000000    0.11972000
H                  0.00000000   -0.76156200   -0.47888000
H                  0.00000000    0.76156200   -0.47888000
''',
    unit = 'angstrom',
    spin = 0,
    charge = 0,
    basis = '6-31g(d)'
)

ks = dft.KS(mol)
ks.xc = 'b3lypg'  # same as Gaussian
eng = ks.kernel()
print(eng)
```

**H2O.gjf**
```
%mem=1GB
%nprocshared=4
%chk=H2O.chk
#p b3lyp/6-31g(d)

Title Card Required

0 1
 O                  0.00000000    0.00000000    0.11972000
 H                  0.00000000   -0.76156200   -0.47888000
 H                  0.00000000    0.76156200   -0.47888000


```

**results**
```
+ PySCF:    -76.4070229747664 Hartree
+ Gaussian: -76.4089539664    Hartree
+ diff:       0.001930992     Hartree // 1.211715 kcal/mol
```

**Software information**
+ Python 3.11.3
+ PySCF 2.2.1
+ Gaussian 16 A.03

**Comment by xis19** [comment]
Note you are using DFT and the result is impacted by the density of the integral grids. Which version of Gaussian are you using? Different version of Gaussian has different default grid size.

I have no idea about the grid PySCF is using.

Maybe try to compare \delta E rather than absolute E.

**Comment by moolawooda** [comment]
> Note you are using DFT and the result is impacted by the density of the integral grids. Which version of Gaussian are you using? Different version of Gaussian has different default grid size.
> 
> I have no idea about the grid PySCF is using.
> 
> Maybe try to compare \delta E rather than absolute E.

Both PySCF and Gaussian are using the default setting of grid level. However, they should not have such a large deviation in default setting. Otherwise it means that some default values are not properly setted.


**Software information**
+ Python 3.11.3
+ PySCF 2.2.1
+ Gaussian 16 A.03

**Comment by hebrewsnabla** [comment]
The reason is that By Gaussian's default, it uses 6D 7F for 6-31g(d) which is quite strange. Common QC program uses pure cartesian or pure spheric (like pyscf) by default. If you add "5D 7F" in your Gaussian input, you will get -76.4070230765, which has an acceptable deviation.

**Comment by moolawooda** [comment]
> The reason is that By Gaussian's default, it uses 6D 7F for 6-31g(d) which is quite strange. Common QC program uses pure cartesian or pure spheric (like pyscf) by default. If you add "5D 7F" in your Gaussian input, you will get -76.4070230765, which has an acceptable deviation.

Thanks for reply. I understand it now.

**Comment by susilehtola** [comment]
> The reason is that By Gaussian's default, it uses 6D 7F for 6-31g(d) which is quite strange. 

It is not strange: this is what the 6-31G series Pople basis sets use. The solution is to not use Pople basis sets. They are obsolete and should not be used.
