### ISSUE TITLE
Analytical expressions for analytical nuclear gradients

### ISSUE THREAD

**Issue by KirillKulaev** [pyscf/pyscf#1977]
Hi, I'm trying to understand how analytic nuclear gradients are calculated in DFT.
I have read the original article about pyscf and the documentation in detail, but did not find any direct links to the equations to calculate them.
Can you provide mathematical equations or links to articles where this is explained please? For my research I need equations for the functions grad.grad_rhf.grad_elec(), grad.grad_rks.get_vxc(), grad.grad_rks.get_vxc(), grad.grad_rks.get_veff(), grad.grad_rks._make_dR_dao_w()

Thank you in advance!

**Comment by susilehtola** [comment]
See [Chem. Phys. Lett. 199, 557 (1992)](https://doi.org/10.1016/0009-2614(92)85009-Y) for the equations for up to GGA functionals. Meta-GGAs are handled analogously.

**Comment by verena-neufeld** [comment]
Hi @KirillKulaev , thank you for your question. Has it been answered?
