### ISSUE TITLE
Problems in running the SCF for large system

### ISSUE THREAD

**Issue by JangidBhavnesh** [pyscf/pyscf#1978]
I am trying to get the HF for a system with ~300 atoms; this has around ~5000 basis functions. I am running this calculation on 32 processors with 300GB of memory. Still, it is failing and showing a segmentation fault error.

**Am I missing anything for input when handling a large system?**

**** Input file***
mol = gto.Mole()
mol.atom = 'mymolecule.xyz'
mol.basis = '6-31G'
mol.max_memory = 300000
mol.build()

mf = scf.RHF(mol).density_fit()
mf.kernel()

@sunqm

**Comment by jamesETsmith** [comment]
@JangidBhavnesh, PySCF's max memory setting isn't exact (or at least that used to be the case). I would suggest setting the max memory to 275GB or even 250GB for your system to give you some cushion in case PySCF uses slightly more than your limit. If you could post a snippet of the log that shows the error, that would be helpful.

**Comment by JangidBhavnesh** [comment]
Here is the last print before it gave this error
/var/spool/slurm/d/job10901452/slurm_script: line 23: 1284079 Segmentation fault      (core dumped) 

******** <class 'pyscf.df.df_jk.density_fit.<locals>.DensityFitting'> ********
method = DensityFitting-RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-09
SCF conv_tol_grad = None
SCF max_cycles = 50
direct_scf = True
direct_scf_tol = 1e-13
max_memory 300000 MB (current use 120 MB)
Set gradient conv threshold to 3.16228e-05
Initial guess from minao.

******** <class 'pyscf.df.df.DF'> ********
auxbasis = None
max_memory = 300000
_cderi_to_save = /usr/home/tmp7xhcb4ky
Default auxbasis def2-svp-jkfit is used for H STO-3G
Default auxbasis def2-svp-jkfit is used for C STO-3G
Default auxbasis def2-svp-jkfit is used for O STO-3G
Default auxbasis def2-svp-jkfit is used for N STO-3G
Default auxbasis def2-svp-jkfit is used for Ca STO-3G
Default auxbasis def2-svp-jkfit is used for S STO-3G
num shells = 25022, num cGTOs = 75726
size of aux basis 75726
    CPU time for 2c2e    225.83 sec, wall time     19.41 sec

**Comment by jamesETsmith** [comment]
@JangidBhavnesh, could you try running the job again with the smaller value of max memory and see if the problem persists?

**Comment by JangidBhavnesh** [comment]
What is rational for using smaller memory?

Although, with smaller value it did crash at same point, except it took longer to reach that point.

So error still persist!

**Comment by jamesETsmith** [comment]
@JangidBhavnesh the rationale for using smaller memory is that PySCF's `max_memory` is not a hard limit to the amount of memory it will use and at times PySCF will use more than that amount. What smaller value did you use? Do you have exclusive access to the node you're using or are you sharing it with other users?

**Comment by hebrewsnabla** [comment]
How much memory do you have in your machine or node?

**Comment by JangidBhavnesh** [comment]
> @JangidBhavnesh the rationale for using smaller memory is that PySCF's `max_memory` is not a hard limit to the amount of memory it will use and at times PySCF will use more than that amount. What smaller value did you use? Do you have exclusive access to the node you're using or are you sharing it with other users?

I have tried with 100 GB and I'm using shared node.
