### ISSUE TITLE
Initial total energy lower than converged total energy in DFT

### ISSUE THREAD

**Issue by ftsong22** [pyscf/pyscf#1979]
I ran a pretty standard DFT on a small organic molecule, and found that the initial total energy is lower than the converged total energy. Here is the log of the SCF iterations:
```
init E= -235.129705659357
  HOMO = -0.473834908452196  LUMO = -0.203178833165964
cycle= 1 E= -233.64335737808  delta_E= 1.49  |g|= 1.63  |ddm|= 3.07
  HOMO = -0.0189700803285997  LUMO = 0.0871806710098338
cycle= 2 E= -232.434237416965  delta_E= 1.21  |g|= 2.56  |ddm|=  5.9
  HOMO = -0.238161069287656  LUMO = -0.00914466996393746
cycle= 3 E= -234.220876654802  delta_E= -1.79  |g|= 0.667  |ddm|=  5.5
  HOMO = -0.253915548314279  LUMO = -0.00495335040147796
cycle= 4 E= -234.294785861471  delta_E= -0.0739  |g|= 0.437  |ddm|= 0.588
  HOMO = -0.240757459717686  LUMO = 0.00133166920680861
cycle= 5 E= -234.338587190355  delta_E= -0.0438  |g|= 0.121  |ddm|= 0.248
  HOMO = -0.233236076746694  LUMO = 0.00474631548934805
cycle= 6 E= -234.341951457138  delta_E= -0.00336  |g|= 0.0273  |ddm|= 0.0863
  HOMO = -0.234736970897919  LUMO = 0.00372345004566818
cycle= 7 E= -234.342132045565  delta_E= -0.000181  |g|= 0.00481  |ddm|= 0.0194
  HOMO = -0.234951747233484  LUMO = 0.00354041461106272
cycle= 8 E= -234.342137046506  delta_E= -5e-06  |g|= 0.00186  |ddm|= 0.00455
  HOMO = -0.234864590630961  LUMO = 0.00359992229673973
cycle= 9 E= -234.342137883496  delta_E= -8.37e-07  |g|= 0.000514  |ddm|= 0.00153
  HOMO = -0.234877386626167  LUMO = 0.00359663026472105
cycle= 10 E= -234.342137948347  delta_E= -6.49e-08  |g|= 9.93e-05  |ddm|= 0.000363
  HOMO = -0.234876872621642  LUMO = 0.00359877138108272
cycle= 11 E= -234.34213795068  delta_E= -2.33e-09  |g|= 3.67e-05  |ddm|= 0.000105
  HOMO = -0.23487369228104  LUMO = 0.00359884251461179
Extra cycle  E= -234.342137950122  delta_E= 5.58e-10  |g|= 5.89e-05  |ddm|= 6.52e-05
converged SCF energy = -234.342137950122
```

It's clear that the init E is lower than the converged energy, while in other iterations the energy are all higher than the converged energy. As my settings were quite conventional, I assume this is not a bug, but I am still very curious and have only some speculations.

In my understanding, the total energy in each iteration (including the initial guess) is obtained in the following way: First the Fock matrix $\mathbf{F}$ is constructed using the density matrix $\mathbf{D}$, and the total energy is computed by something like $E  = \sum_{ij} D_{ij} F_{ij}$. In this way, we define an energy functional $E[\mathbf{D}]$, and my first question is that is this definition consistent with the energy functional defined in Hohenberg-Kohn theorem? And what makes the initial density matrix so different; is it because it is not a solution from the Kohn-Sham equation?

**Comment by susilehtola** [comment]
Not a bug. The issue is that the guess density matrix is not idempotent.

**Comment by ftsong22** [comment]
@susilehtola Thank you! This is very clear. Problem solved.
