### ISSUE TITLE
[QUESTION] Get `mean_field` from Geometry Optimization?

### ISSUE THREAD

**Issue by JacksonBurns** [pyscf/pyscf#1994]
Is it possible to extract the `mean_field`/`mf` from the last iteration of a geometry optimization to avoid having to recompute the wavefunction after finding the optimized coordinates?

Currently I am doing this:
```python
mean_field = HF(mol)
...
mol_eq = mean_field.Gradients().optimizer(solver="geomeTRIC").kernel(optimizer_parameters)
mean_field_eq = HF(mol_eq).kernel()  # <- isn't this just the last iteration from the above line?
```
but can I instead do this somehow?
```python
mean_field_eq = mean_field.Gradients().optimizer(solver="geomeTRIC").kernel().something_else...
```

**Comment by sunqm** [comment]
The mean_field object will not be updated during the geometry optimization. You can apply the `optimizer` for a scanner of the Gradients object, which will be updated by the optimizer.
```
g_scan = mean_field.Gradients().as_scanner()
g_scan.optimizer(solver='goemTRIC').run()
mean_field_scanner = g_scan._scf
mean_field_eq = mean_field_scanner.undo_scanner()
```

**Comment by JacksonBurns** [comment]
This works great, thanks!
