### ISSUE TITLE
gccsd error when using an ERI with size (nmo, nmo, nmo, nmo)

### ISSUE THREAD

**Issue by zhcui** [pyscf/pyscf#2002]
Hi all,

I found a possible bug in the gccsd.ao2mo:

https://github.com/pyscf/pyscf/blob/e3ea7d1a095c6b7329bb64ddf9feb4cc567f87df/pyscf/cc/gccsd.py#L364

which missed a reshape:
` 
    if eri.size == nmo**4:  # if mycc._scf._eri is a complex array

        eri = eri.reshape(nmo**2, nmo**2)
    
        sym_forbid = (orbspin[:,None] != orbspin).ravel()`

Otherwise, the following `sym_forbid` mask would not work.

Best,
Zhihao

**Comment by verena-neufeld** [comment]
Hi Zhihao, thanks for posting this. Just to check: the `shape` of `eri` is (nmo,nmo,nmo,nmo) not (nmo**2,nmo**2)? I just read some ao2mo kernel examples which seem to give out 2D arrays. Do you have a small example?
Thanks!

**Comment by zhcui** [comment]
> Hi Zhihao, thanks for posting this. Just to check: the `shape` of `eri` is (nmo,nmo,nmo,nmo) not (nmo^2,nmo^2)? I just read some ao2mo kernel examples which seem to give out 2D arrays. Do you have a small example? Thanks!

https://github.com/pyscf/pyscf/blob/0bc590ffddec98eec5d2513a3d85274b7a791bc6/pyscf/ao2mo/incore.py#L126

This gives the shape of ijkl

**Comment by verena-neufeld** [comment]
I think this is a larger issue than adding a `reshape` in `pyscf/pyscf/cc/gccsd.py`. The docstrings in the `ao2mo` functions indicate that a 2D array is array. So I think the return of https://github.com/pyscf/pyscf/blob/0bc590ffddec98eec5d2513a3d85274b7a791bc6/pyscf/ao2mo/incore.py#L126 should be changed or the docstrings have to be updated. I'll see what other returns of ao2mo there are.

For complex GCCSD, there is also the wrapper ao2mo in https://github.com/pyscf/pyscf/blob/0bc590ffddec98eec5d2513a3d85274b7a791bc6/pyscf/pbc/cc/ccsd.py#L107 which does have a reshape actually, but I think we should make sure the output of ao2mo is consistent.

**Comment by verena-neufeld** [comment]
I agree that a reshape is needed. I'm suggesting adding it after line https://github.com/pyscf/pyscf/blob/0bc590ffddec98eec5d2513a3d85274b7a791bc6/pyscf/ao2mo/incore.py#L125 but I don't know whether the 4D array was left on purpose or whether this would break behaviour. @sunqm ? @fishjojo ?

**Comment by sunqm** [comment]
> I agree that a reshape is needed. I'm suggesting adding it after line
> 
> https://github.com/pyscf/pyscf/blob/0bc590ffddec98eec5d2513a3d85274b7a791bc6/pyscf/ao2mo/incore.py#L125
> 
> but I don't know whether the 4D array was left on purpose and whether this would break behaviour. @sunqm ? @fishjojo ?

Yes. The _eri attribute of the mean field object can be 4D tensor. For instance, the custom calculations for the Hubbard model. This attributed is passed to the ao2mo transformation function by some post-HF methods.

**Comment by verena-neufeld** [comment]
Hi @sunqm , thanks for having a look and clarifying! I'll put updating that docstring on my todo list.

**Comment by verena-neufeld** [comment]
@sunqm @zhcui this is resolved now I think?

**Comment by verena-neufeld** [comment]
Thanks!!!

**Comment by zhcui** [comment]
> @sunqm @zhcui this is resolved now I think?

Yes, I think so.
