### ISSUE TITLE
Spin-Density calculate

### ISSUE THREAD

**Issue by DeepDevIA** [pyscf/pyscf#2003]
Hi there
help please
how can I calculate spin density of  unstricted dft calculation and visualized it or plot it ?
Thank you

**Comment by sunqm** [comment]
You can dump the density in cube format, and use visualization tools like vmd, jmol to view the density. In the example folder, you can find an example for writing cube format, in tools/05-cubegen.py

**Comment by DeepDevIA** [comment]
thanks [sunqm](https://github.com/sunqm)
