### ISSUE TITLE
plotting spin density

### ISSUE THREAD

**Issue by DeepDevIA** [pyscf/pyscf#2007]
Hi,
please is there anyone give a code to plot the total spin density along the z-axis according to this equation nσ(z)=∫ρσ(r) dxdy  ? 
Thanks

**Comment by sunqm** [comment]
The cubegen module probably closes to your needs. https://github.com/pyscf/pyscf/blob/master/pyscf/tools/cubegen.py#L58

You can define your own mesh grids than the `get_coords` method provided by the Cube class. Then calling the similar script to calculate the density for spin-up density matrix and spin-down density matrix. After that, tracing the grids along x and y directions and scaling the results with the area (= dx * dy of your mesh), that would give you an approximate spin density on z-axis, subject to some small errors near the core of each atom.

**Comment by verena-neufeld** [comment]
Hi @DeepDevIA , thanks for your question. Has it been resolved now and can this issue be closed?
