### ISSUE TITLE
optimisation method

### ISSUE THREAD

**Issue by johTin** [pyscf/pyscf#2008]
Hi 
how can i do dft calcultion using quasi newton method please?

**Comment by tberkel** [comment]
There is not a unique quasi-Newton method. DIIS, which is used by default in PySCF's SCF convergence, can be viewed a quasi-Newton method. PySCF also has the exact second-order Newton method (`mf.newton()`). But you'll have to be more specific about which quasi-Newton method you want to use.

**Comment by verena-neufeld** [comment]
Hi @johTin , thanks for your question. Has it been answered? If yes, this issue can probably be closed.
