### ISSUE TITLE
Are reduced RMDs available from CI/MP?

### ISSUE THREAD

**Issue by szgoger** [pyscf/pyscf#2012]
My question is partly motivated by [an old issue](https://github.com/pyscf/pyscf/issues/420), where an user was expecting the MP2 2RDM to be relaxed, but it wasn't. In the question, however, it is strongly implied that they were able to obtain relaxed CI/FCI RDMs that appeared to be relaxed. I'm interested in obtaining these reduced matrices myself.

The CI manual explicitly states that the ''simple'' CI 1RDM and 2RDM is unrelaxed, but no such statement is claimed about the FCI matrices. Does this mean that the FCI matrices are relaxed, or, alternatively, can a relaxed pRPM be obtained somehow from an unrelaxed (p+1)RPM somehow? I admit I am quite unfamiliar with this.

In any case, I have checked the trace for a simple helium atom with the following code

```

from pyscf import gto, scf, fci
import numpy as np


# Defining the calculation
mol = gto.Mole()
mol.build(
    atom = 'He 0 0 0',  # in Angstrom
    basis = 'ccpvqz',
    spin = 0,
)
myhf = scf.RHF(mol)
myhf.kernel()

norb = myhf.mo_coeff.shape[1]

nelec_a = 1
nelec_b = 1


cisolver = fci.FCI(mol, myhf.mo_coeff)
e, fcivec = cisolver.kernel()

dm1, dm2 = cisolver.make_rdm12(fcivec, norb, (nelec_a,nelec_b))

#testing
print(dm2.shape)

trc1, trc2 = 0, 0
for ii in range(norb):
    trc2 += dm2[ii,ii,ii,ii]
    trc1 += dm1[ii,ii]
print(trc1)
print(trc2)
```

This code returns 2.000 for the 1RDM trace and 1.995 for the 2RDM trace. I can not judge whether being off by 0.005 on the 2RDM trace is acceptable numerically, or does it signal that the matrix is indeed unrelaxed (or maybe I calculate the trace wrong... it's always a possibility).

Could it be clarified whether any method, if all, can produce relaxed RDMs, and, if yes, how?

**Comment by sunqm** [comment]
Relaxed or unrelaxed density matrices describe whether the response of the reference orbitals are included in the density matrices. FCI density matrices are computed as the outer product of wavefunction. If you transform the FCI density matrices to AO basis representation, it does not depend on how you choose the reference orbitals. There is no such need to consider the orbital relax problems in FCI density matrix.

The trace of 2RDM in your code doesn't make much sense IMO. The trace for 2RDM should be `einsum('iijj->', rdm2)`

**Comment by szgoger** [comment]
I see, thank you! Does this also mean that only unrelaxed RDMs are available for non-full CI calculations?

**Comment by gkc1000** [comment]
There are a lot of methods in pyscf, but in my memory, we never compute the orbital response for the RDM methods for any of them. So, the density matrices are unrelaxed.
