### ISSUE TITLE
hcore and fock in dft

### ISSUE THREAD

**Issue by computative** [pyscf/pyscf#2013]
I have used the documentation, but it still unclear for me what get_hcore and get_fock provides in the following script.

```
import pyscf
mol = pyscf.M(
    atom = 'C 0 0 0; C 0 0 1.1',  # in Angstrom
    basis = 'sto-3g',
    symmetry = True)
mf = mol.KS()
mf.xc = 'b3lyp'
mf.kernel()

mf.get_hcore()
mf.get_fock()
```

- I have the impression that hcore is the kinetic energy plus the ionic potential. 
- I have the impression that fock is hcore plus coulomb potential + xc potential.

But I am not sure of this because i have the impression that get_fock is inherited from pyscf.scf.hf.SCF, and in that documentation it is defined as F = h^{core} + V^{HF} [(ref)](https://pyscf.org/pyscf_api_docs/pyscf.scf.html#pyscf.scf.hf.SCF.get_fock)

If you could clarify the definitions, it would be much appreciated.

**Comment by tberkel** [comment]
Your original guess is correct. For DFT, get_fock is hcore plus Coulomb plus XC. The method `get_fock()` actually calls `mf.get_veff()`, which is Coulomb plus XC for DFT classes.
See here: https://github.com/pyscf/pyscf/blob/master/pyscf/scf/hf.py#L968
and here: https://github.com/pyscf/pyscf/blob/master/pyscf/dft/rks.py#L37

**Comment by verena-neufeld** [comment]
Hi @computative , thanks for your question! Has it been answered and can this issue be closed?

**Comment by computative** [comment]
Yes

På mandag 15. januar 2024 kl. 04:31, Verena Neufeld ***@***.***> skrev:
