### ISSUE TITLE
Supercell GDF memory problem

### ISSUE THREAD

**Issue by lijiachen417** [pyscf/pyscf#2017]
Hi, I had a memory problem when generating supercell GDF for 4*4*4 Diamond with cc-pVDZ basis set using 30G memory.
The pyscf script is
```
from pyscf.pbc import gto, df
from pyscf.pbc.tools import k2gamma

cell = gto.Cell()
cell.build(unit='angstrom',
           a='''
            0.000000     1.783500     1.783500
            1.783500     0.000000     1.783500
            1.783500     1.783500     0.000000
           ''',
           atom='C 1.337625 1.337625 1.337625; C 2.229375 2.229375 2.229375',
           dimension=3,
           max_memory=30000,
           verbose=5,
           basis='ccpvdz')
kmesh = [4, 4, 4]
kpts = cell.make_kpts(kmesh)
scell, phase = k2gamma.get_phase(cell, kpts)

gdf = df.GDF(scell)
gdf.auxbasis = "cc-pvdz-ri"
gdf._cderi_to_save = 'gdf_ints.h5'
gdf.build()
```
The error message is 
> Traceback (most recent call last):
>   File "/home/jl710/job/debug/gamma-pseudo/diamond/input.py", line 25, in <module>
>     gdf.build()
>   File "/home/jl710/program/pyscf/pyscf/pbc/df/df.py", line 262, in build
>     self._make_j3c(self.cell, self.auxcell, None, cderi)
>   File "/home/jl710/program/pyscf/pyscf/pbc/df/df.py", line 289, in _make_j3c
>     dfbuilder.make_j3c(cderi_file, j_only=j_only, dataname=self._dataname,
>   File "/home/jl710/program/pyscf/pyscf/pbc/df/rsdf_builder.py", line 926, in make_j3c
>     fswap = self.outcore_auxe2(cderi_file, intor, aosym, comp, j_only,
>   File "/home/jl710/program/pyscf/pyscf/pbc/df/rsdf_builder.py", line 468, in outcore_auxe2
>     self._outcore_dd_block(fswap, intor, aosym, comp, j_only,
>   File "/home/jl710/program/pyscf/pyscf/pbc/df/rsdf_builder.py", line 637, in _outcore_dd_block
>     aopair = np.empty((nao**2, ngrids))
> numpy.core._exceptions._ArrayMemoryError: Unable to allocate 98.9 GiB for an array with shape (262144, 50653) and data type float64

However, when I used older version pyscf, for example commit 5bfe7d1f96f9705c3b69a6da1ff148924e15ae4c , I can generate the GDF  file with 30G memory.

**Comment by fishjojo** [comment]
This can be improved, however, with such big basis, you won't be able to store the density matrix either.

**Comment by fishjojo** [comment]
This should be improved.

**Comment by lijiachen417** [comment]
@fishjojo I can do SCF calculation for this system with older version pyscf. The memory issue only happens in the latest pyscf.

**Comment by sunqm** [comment]
try the RSGDF class
```
from pyscf.pbc.df import rsdf
df = rsdf.RSGDF(scell)
```
It may require less memory.

**Comment by lijiachen417** [comment]
@sunqm Thanks! RSDF doesn't not have this memory problem. However, GDF has this problem that is not found in older PySCF versions. Should I close this issue?

**Comment by sunqm** [comment]
The PBC df modules were updated several times to improve performance. There are several algorithms available to compute the GDF integral tensors. Some of them are efficient but use more memory. The GDF algorithm in certain old versions is slow but not eager for memory.

Yes, please close the issue if you find a proper DF module to solve the problem you got.
