### ISSUE TITLE
Evaluation of ECP integrals with mol.intor()

### ISSUE THREAD

**Issue by simulak1** [pyscf/pyscf#2018]
I am trying to evaluate integrals over ECP potential operators. With a molecule object "mol", I can get a matrix of integrals with 

<ecp_matrix>=mol.intor("ECPscalar")

I was wondering, does this approach give integrals between orbitals i and j over the full ECP operator 

V_ECP=V_lmax + sum_l V_l sum_m |lm><lm|, 

so that 

<ecp_matrix>=<i|V_ECP|j>,

or does this approach produce integrals over only the scalar parts of the ECP operator, i.e., over the V_l terms, ignoring the sum over spherical harmonics in the integration?

Another thing that is not so clear is what is evaluated when one is using ECPs, but is evaluating the matrix

hnuc=mol.intor("int1e_nuc").

Does this produce integrals evaluated for the operator 1/|r_e - r_nuc| (with valence orbitals obtained with the ECP potential), or are the integrals evaluated over the local component of the ECP operator? It would suit my needs to evaluate the e-p interaction matrices separately for the local and nonlocal parts of the ECP.

**Comment by simulak1** [comment]
Thank you very much for your answer. So basically mol.intor('ECPscalar') evaluates integrals of the type

<n|V_ECP|m>, with V_ECP=sum_lm V_l(r) |lm><lm|.

Is the ECP cutoff accounted for in these integrals? The ECPs should act only below some cutoff radius from the atom cores. A standard <n|O|m> integral can be evaluated over a radial grid that extends to distances from atoms larger than the ECP cutoff radius, so is <n|V_ECP|m> evaluated on a reduced grid, or is V_ECP inherently zero outside of the cutoff radius, giving zero contribution to the overall integral over the grid?

**Comment by susilehtola** [comment]
I think `ECPscalar` also includes the purely radial terms, without the angular momentum projection.

The ECP radial potentials are expanded in terms of Gaussians, which become vanishingly small far away from the nucleus. I think some of the terms are evaluated analytically, but the one containing the angular momentum projection is evaluated seminumerically on a radial grid. In any case, the integrals are formally over all space.

**Comment by simulak1** [comment]
So ECPscalar includes also the local component of V_ecp, i.e.,

<n|V_ECP|m> = <n|V_local + sum_lm V_l |lm><lm|  |m>?

In that case mol.intor('int1e_nuc') should be the integral over Z/|r-R_nuc|, i.e., the Coulombic nuclear attraction term, by why then does calling that function give different matrices for the same Molecule object with and without ECP included?

**Comment by susilehtola** [comment]
OK, if `int1e_nuc` gives different results with and without the ECP, then the difference in the nuclear charge $\Delta Z = Z - n_{\rm core}$ is taken into account there. Since C has 6 electrons, two of which are on the 1s core orbital, the ratio of the two matrices should be 6/4 = 1.5.

**Comment by simulak1** [comment]
OK, thanks, this is indeed the ratio that I found. 

Now I would like to ask about get_hcore(mol) function you copied above with ECPs: 

```
     if mol._pseudo: 
         # Although mol._pseudo for GTH PP is only available in Cell, GTH PP 
         # may exist if mol is converted from cell object. 
         from pyscf.gto import pp_int 
         h += pp_int.get_gth_pp(mol) 
     else: 
         h+= mol.intor_symmetric('int1e_nuc') 
  
     if len(mol._ecpbas) > 0: 
         h += mol.intor_symmetric('ECPscalar') 
     return h 
```

What happens in my case when I use ECPs is that both 

`h+= mol.intor_symmetric('int1e_nuc') `

and

`h += mol.intor_symmetric('ECPscalar') `

are evaluated. However, this means that  both 

`V_eff=-Z_eff/r`

and 

`V_ECP_local`

 are included in the 1-body hamiltonian. Shouldn't there be only `V_ECP_local` for the local ionic potential, at least under the cutoff radius of the ECP? I believe in longer distances `V_ECP_local` should act like `V_eff` anyway.

**Comment by susilehtola** [comment]
I am not sure I understand your question. What is the "local ionic potential"?

Yes, far away from the nucleus you only see the point charge potential, since the ECP is local.

**Comment by simulak1** [comment]
Sorry if I'm confusing you. By local ionic potential I meant the local ionic potential felt by the valence electrons, i.e., the combined potential 

`-Z/r + V^ECP_local`.

The `V^ECP_local` is significant only below the ECP cutoff radius, above it we just have the potential of the effective ion core. 

I now understand how PYSCF evaluates the molecular integrals with ECPs. I am working currently with PYSCF and another code, that evaluates the "local ionic potential" and "nonlocal ionic potential" energies separately, and the former contains also the contribution of V^ECP_local. PYSCF evaluates the molecular integrals so that integrals over only  `-Z_eff/r` are evaluated by mol.intor('int1e_nuc'), and integrals over the whole ECP operator are evaluated by mol.intor('ECPscalar'). Therefore it is not straightforward to compare components of core potential energies between the two codes, and hence my confusion. Now it's all clear, thank you very much for helping to sort things out. 

Just out of interest, what would be required to implement an integral to PYSCF that evaluates integrals over `V^ECP_local` and `sum_lm V_l |lm><lm|` separately?

**Comment by susilehtola** [comment]
> Just out of interest, what would be required to implement an integral to PYSCF that evaluates integrals over `V^ECP_local` and `sum_lm V_l |lm><lm|` separately?

I think the integrals come straight out of libcint/qcint, so you would need to modify the code there...

**Comment by simulak1** [comment]
Ok, so it is a bit involved. Alternatively, one can manually set the local ECP provided to PYSCF to zero. Thank you again for help!

**Comment by sunqm** [comment]
> > Just out of interest, what would be required to implement an integral to PYSCF that evaluates integrals over `V^ECP_local` and `sum_lm V_l |lm><lm|` separately?
> 
> I think the integrals come straight out of libcint/qcint, so you would need to modify the code there...

The ECP integrals are implemented in pyscf C extensions, here 
https://github.com/pyscf/pyscf/blob/master/pyscf/lib/gto/nr_ecp.c#L5999

the `part1` function evaluates `ECP_local` and the `part2` function evaluates the ECP angular dependent part

**Comment by verena-neufeld** [comment]
Hi @simulak1 , thanks for your question. Has it been resolved now and can this issue be closed?

**Comment by simulak1** [comment]
Sorry for my silence. Yes, I indeed got enough information to go forward, thank you very much for @susilehtola and @sunqm for the kind help!
