### ISSUE TITLE
calculate charge for molecular dynamics

### ISSUE THREAD

**Issue by Clarkszw** [pyscf/pyscf#2020]
To prepare the input for molecular dynamics, one of the key parameters is the charge assigned to each atom in the system. 
Mulliken charge can be obtained by 
```python
from pyscf import gto, dft
mol= gto.M(atom = 'H 0 0 0; F 0 0 1.1', basis = 'ccpvdz', symmetry = True)
mf = dft.RKS(mol)
mf.xc = 'b3lyp'
mf.kernel()
mf.analyze()
```

I am looking for another implementation for calculating the charge, for example Lowdin charge.
I have read the page for [local orbitals](https://pyscf.org/user/lo.html). But I am not able to get the charge following the instruction.

Could someone help me with this? Any doc that I can read or any other function that can provide me the charge other than Mulliken charge?

**Comment by tberkel** [comment]
I'm pretty sure that by default, PySCF is actually calculating (meta) Lowdin charges when you run `analyze()`. To calculate pure Mulliken charges, you can turn off a default kwarg, `mf.analyze(with_meta_lowdin=False)`.

Hopefully the source is not too bad to read, and you can find more details [here](https://github.com/pyscf/pyscf/blob/master/pyscf/scf/hf.py#L1051), [here](https://github.com/pyscf/pyscf/blob/master/pyscf/scf/hf.py#L1153), and [here](https://github.com/pyscf/pyscf/blob/master/pyscf/scf/hf.py#L1114).

**Comment by Clarkszw** [comment]
@tberkel , Thanks a lot! I will read and try it out.
