### ISSUE TITLE
Convergence/Wrong number of occupied orbitals

### ISSUE THREAD

**Issue by ironhide210** [pyscf/pyscf#2024]
Dear Developers,
I am getting extra occupied orbitals for a DHF calculation of YbF molecule. Also I am getting a singularity condition which says my scf might be inaccurate. Can anyone explain how does it happen and how can I avoid it?
The basis  I have used is dyall.ae2z basis set generated from DIRAC19 software and I have already discarded the positron-states, i.e. under no-pair approximation. So whatever you can see in the output file is just the electronic states.
 
[YbF_problem.txt](https://github.com/pyscf/pyscf/files/13935992/YbF_problem.txt)

**Comment by sunqm** [comment]
Try this trick to eliminate linear dependency https://github.com/pyscf/pyscf/blob/master/examples/scf/42-remove_linear_dep.py#L71 . Please note that removing the linear dependency in basis can also introduce errors. Errors can be controlled by the threshold of that function. You can try different thresholds until reaching a reasonable accuracy.

**Comment by verena-neufeld** [comment]
Hi @ironhide210 , thanks for the question. Has this been resolved now and can this issue be closed?
