### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by computative** [pyscf/pyscf#2025]
I want to do some dft calculations on my laptop to try out pyscf. But I continue being unable to do anything because the small basis I use causes it to fail to find enough memory. I'm just a beginner with pyscf, so it is likely my mistake. But I believe I am trying to calculate 8 carbon atoms using restricted kohn sham and a small STO-basis. Pyscf wants to allocate 40 GB of memory for an array with shape (8, 689, 689, 689) and data type complex128. I've been able to calculate 50 atoms using other dft software, so I am trying to understand whether 

1. I am doing something wrong; or is
2. This is the best memory efficiency I could hope for using pyscf.

Therefore I have the following question. Can you look at this script and say what are the main determinants of the memory usage? If I could get information about which settings costs what in terms of memory, I can find out where I might change the settings to use less memory and hopefully execute a calculation.

```
from pyscf.pbc import gto, scf, dft

cell = gto.Cell()
# .a is a matrix for lattice vectors.
cell.a = '''
3.5668  0       0
0       3.5668  0
0       0       3.5668'''
cell.atom = '''C     0.      0.      0.    
              C     0.8917  0.8917  0.8917
              C     1.7834  1.7834  0.    
              C     2.6751  2.6751  0.8917
              C     1.7834  0.      1.7834
              C     2.6751  0.8917  2.6751
              C     0.      1.7834  1.7834
              C     0.8917  2.6751  2.6751'''
cell.basis = 'sto6g'
cell.verbose = 4
cell.build()
mf=pbcdft.RKS(cell)
mf.kernel()
```

**Comment by tberkel** [comment]
The memory issue has to do with two combined issues: 1. you have not indicated a pseudopotential, and 2. you are using the default density fitting scheme. The default density fitting scheme uses plane waves, and if there is no pseudopotential, it requires an enormous number of plane waves to resolve the core electrons. So you can solve this in two ways, depending on your interests:
1. Specify a pseudopotential (and an associated basis set), e.g., `cell.pseudo = 'gth-lda'; cell.basis = 'gth-szv'`
2. Use the Gaussian density fitting method, which can handle core electrons: `mf = pbcdft.RKS(cell).density_fit()`

Solution 1 is cheaper, and the use of a pseudopotential is quite common in periodic calculations performed with other codes.

**Comment by tberkel** [comment]
You shouldn't use all-electron basis sets for calculations with a pseudopotential, and you shouldn't use pseudopotential basis sets for calculations without a pseudopotential. This is why your calculation doesn't converge if you use the GTH-SZV basis set without specifying the GTH pseudopotential. So you should pick whether you want to use a pseudopotential *or* the STO basis sets, but not both.

**Comment by computative** [comment]
Thanks. That solves my issue. Before closing the thread, can you say how I find out the radial function that is used for a given basis set?

**Comment by verena-neufeld** [comment]
You can find basis sets that you haven't downloaded yourself but use directly in pyscf, e.g. gth-szv in the pyscf/pbc/gto/basis folder. The GTH file format is explained on the CP2K website (telling you what are numbers correspond to coefficients, exponents and what angular momentum is used for example). Other basis sets are/can be in other formats but should also contain similar information I think.

**Comment by susilehtola** [comment]
>  I believe I am trying to calculate 8 carbon atoms using restricted kohn sham and a small STO-basis

Your calculation includes an infinite number of atoms, since you have a periodic system. To calculate a cluster of 8 atoms, run a non-periodic calculation.

**Comment by tberkel** [comment]
I assume @computative means a calculation of carbon diamond using the 8-atom unit cell, which is the smallest cubic unit cell.
