### ISSUE TITLE
Can CCSD or CCSD(T) relaxed rdm2 be extracted?

### ISSUE THREAD

**Issue by stefanvuckovic1** [pyscf/pyscf#2027]
From a simple code below I was able to extract rdm2 from ccsd and ccsd(t). As noted [here](https://github.com/pyscf/pyscf/blob/712f792c0c80539a24fa78fec49d9b7787dcafb7/doc_legacy/source/cc.rst#L154), there are both un-relaxed and relaxed rdm's from non-variational wavefunctions. I assume that the "rdm2_cc" and "rdm2_cct" I obtain in the code below are un-relaxed. Is there a way to obtain the corresponding relaxed: "rdm2_cc" and "rdm2_cct"?

```
from pyscf import gto, scf, cc
from pyscf.cc import ccsd_t_rdm_slow

# Define your molecule; for example, a beryllium atom
mol = gto.M(atom='He 0 0 0', basis='def2-svp')

# Perform a Hartree-Fock calculation
mf = scf.RHF(mol)
mf.kernel()

# CCSD
mycc = cc.CCSD(mf)
mycc.kernel()

# Get CCSD RDM2 in the MO basis
rdm2_cc = mycc.make_rdm2()
# Compute the CCSD(T) energy correction
e_ccsd_t = mycc.ccsd_t()

# Get the amplitudes and intermediates necessary for RDM calculations
t1, t2 = mycc.t1, mycc.t2
l1, l2 = mycc.l1, mycc.l2
eris = mycc.ao2mo()
rdm2_cct = ccsd_t_rdm_slow.make_rdm2(mycc, t1, t2, l1, l2, eris)
```

**Comment by sunqm** [comment]
The function of relaxed density matrix was not exposed to CC module. You can refer to the gradients code like https://github.com/pyscf/pyscf/blob/master/pyscf/grad/ccsd.py#L267   and extract the _response_dm1 function there.

**Comment by stefanvuckovic1** [comment]
Thanks @sunqm!
