### ISSUE TITLE
UserWarning: Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, corresponding to the original definition by Stephens et al. (issue 1480) and the same as the B3LYP functional in Gaussian. To restore the VWN5 definition, you can put the setting "B3LYP_WITH_VWN5 = True" in pyscf_conf.py

### ISSUE THREAD

**Issue by willwheelera** [pyscf/pyscf#2029]
Every time I run pyscf I am getting this warning, even when not using B3LYP. Am I supposed to be setting a parameter differently to avoid generating this warning message?

**Comment by tberkel** [comment]
This warning is printed anytime a DFT calculation is run. But you're not the first person to be confused by this. To the other developers, I suggest we print this warning only when B3LYP is selected.

**Comment by willwheelera** [comment]
Just to add some information, it seems that the warning is generated when pyscf.pbc is imported. Nothing needs to actually be run to trigger the warning.

```Python 3.12.0 | packaged by Anaconda, Inc. | (main, Oct  2 2023, 12:29:27) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyscf.pbc
/opt/anaconda3/envs/pyqmc/lib/python3.12/site-packages/pyscf/dft/libxc.py:771: UserWarning: Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, corresponding to the original definition by Stephens et al. (issue 1480) and the same as the B3LYP functional in Gaussian. To restore the VWN5 definition, you can put the setting "B3LYP_WITH_VWN5 = True" in pyscf_conf.py
  warnings.warn('Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, '```

Would it be possible to provide an option that can be set explicitly to suppress the warning? I find it confusing to get warnings if I am using everything as intended.

**Comment by tberkel** [comment]
The origin is actually pyscf.dft, not pyscf.pbc (you can check `import pyscf.dft`). The warning is raised when libxc is setup. In the meantime, you can turn off the warning by adding `B3LYP_WITH_VWN5 = False` to the PySCF config. A few ways to do this:
```
from pyscf import __config__
__config__.B3LYP_WITH_VWN5 = False
from pyscf import dft
```
or add `B3LYP_WITH_VWN5 = False` to a `.pyscf_config.py` file, which can be placed in the working directory, your home directory, or a directory specified with the environment variable `PYSCF_CONFIG_FILE`.

**Comment by willwheelera** [comment]
Ok, thanks for the clarification

**Comment by verena-neufeld** [comment]
Thanks @willwheelera . Does this work now with PR https://github.com/pyscf/pyscf/pull/2040 merged and can this be closed?
