### ISSUE TITLE
Unintuitive mean-field object tranformation in k2gamma

### ISSUE THREAD

**Issue by mkakcl** [pyscf/pyscf#2030]
Hi,

I was hoping to get some clarification regarding the `k2gamma` function in `pyscf/pbc/tools/k2gamma.py`

Based on the documentation I read along with my intuition associated with the function, I assumed that whatever mean-field object I passed to `k2gamma`, I would receive back the same object at the gamma-point as a supercell. However, when a `pyscf.pbc.dft.krks.KRKS` object is inputted, a `pyscf.pbc.scf.hf.RHF` object is returned. I have attached an example of this based on `examples/pbc/42-k2gamma.py`. In that example, an independently constructed mean-field object used to check the result has the `pyscf.pbc.dft.rks.RKS` class, which is the class I would have expected from `k2gamma`.

I was hoping to get some clarification if this was the intended behaviour of this function? If not, then I wanted to bring it to your attention.

Many thanks,
Marcus

Example code:
[k2gamma_behaviour.py.txt](https://github.com/pyscf/pyscf/files/13982411/k2gamma_behaviour.py.txt)

**Comment by fishjojo** [comment]
You are right, the current design should be improved.

**Comment by verena-neufeld** [comment]
Thanks @mkakcl ! Has this been solved now due to the recent fix?

**Comment by mkakcl** [comment]
Thank you for the commit! It has solved this issue.
