### ISSUE TITLE
Geometry Optimisation - Stopping at Max Step 99 and no indication of convergence success or failure

### ISSUE THREAD

**Issue by calvinp0** [pyscf/pyscf#2031]
Hi, I am incredibly new to using PySCF and so I am trying to get a handle of it.

I am not sure if I am doing something incorrectly but I have been trying to optimise a molecule geometry with the following properties:

```
  C      -2.20544237   -0.10475244    0.78733348
  C      -1.06751415    0.30004822   -0.08826793
  C       0.26132473   -0.26058593    0.40983533
  C       1.41143017    0.13964494   -0.50481827
  O       2.63519975   -0.37726950    0.00114672
  H      -3.20629755   -0.16689652    0.37450934
  H      -2.09080260   -0.13641348    1.86539279
  H      -1.02441123    1.39415167   -0.12708266
  H      -1.26222318   -0.05703565   -1.10596794
  H       0.47018039    0.09112070    1.42851009
  H       0.21399614   -1.35522618    0.47745202
  H       1.26625001   -0.24487246   -1.51951531
  H       1.50415982    1.22871327   -0.56078007
  H       2.55040040   -1.34524038    0.04220965

Restricted: False
Method: wb97xd
Basis: def2tzvp
Spin: 1
Charge: 0
```
I have attempted to follow the User Guide on the PySCF website and while this is not my whol code - this is what I essentially end up doing:

```python
from pyscf.geomopt.geometric_solver import optimize
from pyscf import gto, scf, dft

molecule = 'C      -2.20544237   -0.10475244    0.78733348\nC      -1.06751415    0.30004822   -0.08826793\nC       0.26132473   -0.26058593    0.40983533\nC       1.41143017    0.13964494   -0.50481827\nO       2.63519975   -0.37726950    0.00114672\nH      -3.20629755   -0.16689652    0.37450934\nH      -2.09080260   -0.13641348    1.86539279\nH      -1.02441123    1.39415167   -0.12708266\nH      -1.26222318   -0.05703565   -1.10596794\nH       0.47018039    0.09112070    1.42851009\nH       0.21399614   -1.35522618    0.47745202\nH       1.26625001   -0.24487246   -1.51951531\nH       1.50415982    1.22871327   -0.56078007\nH       2.55040040   -1.34524038    0.04220965'

basis = 'def2tzvp'
spin = 1
charge = 0
unit = 'ANG'

mol = gto.Mole(atom=molecule, basis=basis, charge=charge, spin=spin, unit=unit).build()
mf = dft.UKS(mol)

mf.conv_tol = 1e-12
mf.conv_tol_grad = 1e-8
mf.direct_scf_tol = 1e-13
mf.init_guess = 'minao'
mf.max_cycle = 100
mf.xc='WB97XD'
mf.grids.level = 3
mf.diis= True

mol_opt = optimize(mf)
```

Now, it reqaches the 99th Max Step (and obvisoulsy it starts from Max Step 0) but then it stops without informing me if the convergance was unsuccessful. I figure it wasn't but I also figured it would let me know. Or am I mistaken?

Also, when I query `mol_opt.e_tot` it is `0`.

One additional question - I installed `pyscf` through `pip` as it is done in the instructions - and then I even attempted to compile PySCF against a Intel's MKL from OneAPI. Yet, the optimisation of the molecule is still incredibly slow. I would say on my system it takes over an hour at least. Is this to be expected? This is my system specs:

```
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  20
  On-line CPU(s) list:   0-19
Vendor ID:               GenuineIntel
  Model name:            12th Gen Intel(R) Core(TM) i7-12700KF
    CPU family:          6
    Model:               151
    Thread(s) per core:  2
    Core(s) per socket:  12
    Socket(s):           1
    Stepping:            2
    CPU max MHz:         5000.0000
    CPU min MHz:         800.0000

RAM Mem: 32GB (DDR4)
```

Apologies if I missed something

**Comment by fishjojo** [comment]
Your script is correct, and you can use the returned `mol_opt` object to continue to run another geometry optimization. 
Or you can increase the number of optimization steps: `mol_opt = optimize(mf, maxsteps=200)`. 
Using density fitting should make the calculation faster:  `mf = dft.UKS(mol).density_fit()`.

**Comment by calvinp0** [comment]
Thanks @fishjojo, I will give the `density_fit()` a try.

Regarding the `mol_opt`, and I will try not to bore you with too much of the details, but our group writes a software called [ARC](https://github.com/ReactionMechanismGenerator/ARC). Our software is intended to calculate the rates of a reaction.

So we begin with optimising the geometry of the reactants/products. To do this we employ software, such a Gaussian, QChem etc. We are now also looking to use OSS like PySCF. Thus currently I am writing an 'adapter' of sorts where our software engages with PySCF to run the optimisation of a molecule, all done automatically without user intervention. Now what I am trying to solve that if there is no convergence and it reaches `maxsteps`, is there a way for PySCF to report this so that when our software parses the `output.log` of the PySCF job, it recognises it failed to converge due to (the possibility of) insuffiecient steps.

Sorry for the lengthy explanation. And apologies if this is not already obvious in the documentation.

**Comment by hebrewsnabla** [comment]
There should be info in stdout like `Geometry optimization is not converged in 10 iterations`, although it does not look like an error message.

By the way, it may be not correct to use wb97xd in this way since there's no implementation of DFTD2 in pyscf.

**Comment by calvinp0** [comment]
[output.log](https://github.com/pyscf/pyscf/files/14008899/output.log)
[output_opt_optim.log](https://github.com/pyscf/pyscf/files/14008905/output_opt_optim.log)

I have attached both my output logs - one from capturing the stdout of PySCF and also getting Geometric's output passing the prefix kwarg. These are my results and as far as I can see there wasn't a message about non-convergance. 

Regarding the `WB97XD` format, thanks for pointing that out! I will make the adjustments.

**Comment by hebrewsnabla** [comment]
I can see the not-converged info with running your input with maxsteps=10. So I don't know why you can't see it.

**Comment by hebrewsnabla** [comment]
> By the way, it may be not correct to use wb97xd in this way since there's no implementation of DFTD2 in pyscf.

By this I mean there's no way to use wb97xd in pyscf. Setting xc=wb97xd only means part of wb97xd.

**Comment by tberkel** [comment]
I'd also like to add, as described on the [Geometry Optimization](https://pyscf.org/user/geomopt.html) page of the User Guide, the geometry optimization isn't *really* a product of PySCF, but rather the geometric and pyberny packages. PySCF only implements derivatives that are used in the algorithms of those packages via an interface. So aside from simple usage questions or questions about the interface in PySCF, you could consider directing optimization questions to the developers of those packages.

**Comment by hebrewsnabla** [comment]
@tberkel  I think the NotConvergedError and its message is raised by pyscf side according to current code
https://github.com/pyscf/pyscf/blob/009f1d3899fbdd809fb4d73c9b06a7ab7b4b5e56/pyscf/geomopt/geometric_solver.py#L69-L72

https://github.com/pyscf/pyscf/blob/009f1d3899fbdd809fb4d73c9b06a7ab7b4b5e56/pyscf/geomopt/geometric_solver.py#L159-L166

Although geomeTRIC may through its own error (named as OptNotConvergedError), it's probably not catched by pyscf's `except`.

**Comment by calvinp0** [comment]
> @tberkel I think the NotConvergedError and its message is raised by pyscf side according to current code
> 
> https://github.com/pyscf/pyscf/blob/009f1d3899fbdd809fb4d73c9b06a7ab7b4b5e56/pyscf/geomopt/geometric_solver.py#L69-L72
> 
> https://github.com/pyscf/pyscf/blob/009f1d3899fbdd809fb4d73c9b06a7ab7b4b5e56/pyscf/geomopt/geometric_solver.py#L159-L166
> 
> Although geomeTRIC may throw its own error (named as GeomOptNotConvergedError), it's probably not catched by pyscf's `except`.

Thanks mate, cause of this I realised what was the issue. I had set the verbose level to 0, and since PySCF was reporting convergence success at this level, I figured it would report failure to converge as well. It seems that is not the case - I need to ensure verbosity is level 4.

However, this leads me to another question. In the documents, https://pyscf.org/pyscf_api_docs/pyscf.dft.html#module-pyscf.dft.rks, I see that one of the saved results is `converged`
```
Saved results:

    converged bool

        SCF converged or not
```
But what I did notice is that whether my molecule converges or not, the boolean remains False. Am I misunderstanding what this result means? Or the behaviour of it?

**Comment by hebrewsnabla** [comment]
@calvinp0 that's SCF convergence. It has nothing to do with GeomOpt convergence. And you can only query `mf.converged` but not `mol_opt.converged`, because mol_opt is not a SCF object.

**Comment by hebrewsnabla** [comment]
With
```
g_scan = mf.Gradients().as_scanner()
opt = g_scan.optimizer(solver='geomeTRIC').run()
```
you can query `opt.converged`.

**Comment by calvinp0** [comment]
> With
> 
> ```
> g_scan = mf.Gradients().as_scanner()
> opt = g_scan.optimizer(solver='geomeTRIC').run()
> ```
> 
> you can query `opt.converged`, which is the boolean for GeomOpt convergence.

Thank you so much :)

**Comment by verena-neufeld** [comment]
Hi @calvinp0 , thanks for the question. Has it been resolved and can this issue be closed?
