### ISSUE TITLE
numpy.distutils deprecation

### ISSUE THREAD

**Issue by verena-neufeld** [pyscf/pyscf#2034]
When running some tests in pyscf using pytest, I get this warning:

```
    `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
    of the deprecation of `distutils` itself. It will be removed for
    Python >= 3.12. For older Python versions it will remain present.
    It is recommended to use `setuptools < 60.0` for those Python versions.
```
I'm using numpy 1.24.3

**Comment by sunqm** [comment]
pyscf does not use any functions from the `numpy.distutlis` module. This is likely caused by an indirect dependency to numpy.distutils. I guess it is caused by the `numpy.ctypeslib` module. We don't need to worry about this warning. I think the numpy developers will solve this issue at some point.

**Comment by verena-neufeld** [comment]
Thanks for taking the time to have a look @sunqm . I'm closing this issue.
