### ISSUE TITLE
TD-DFT convergence options

### ISSUE THREAD

**Issue by szgoger** [pyscf/pyscf#2037]
I am trying to run a TD-DFT calculation for a (comparably) large organic molecule, but I am failing to reach convergence. As far as I can tell, the only ''natural'' parameter to control a TD-DFT calculation is the number of states included in the calculation - apart from simply choosing a different basis set/functional, I don't know what other parameter I could fiddle with. Changing the initial SCF guess probably does not change the TD-DFT convergence since the SCF cycle is already optimized, is that correct?

If so, is there anything at all I chould try to achieve convergence?

For reference, I am attaching the output of one such calculation.
[tddft_2047344.txt](https://github.com/pyscf/pyscf/files/14036159/tddft_2047344.txt)

**Comment by tberkel** [comment]
To the TDDFT `kernel()` function, you can pass an initial guess for your excited state(s): `kernel(x0=guess)`. The default initial guess is a single electron excitation with the lowest orbital energy difference. Adding noise to this can sometimes help convergence. You can also set the parameters `max_space` and `max_cycle`, which are used in the Davidson algorithm.

**Comment by szgoger** [comment]
@tberkel Do you maybe have an example script on how to add a noise to the initial guess? I am not familiar at all with this part of the code.

**Comment by tberkel** [comment]
Sure, I think this should work:
```
td = tdscf.TDDFT(mf)
td.verbose = 5
x0 = td.init_guess(mf)
noise = 1e-2 # can make this bigger or smaller
print(x0.shape)
for x in x0:
    x += np.random.uniform(-noise, noise, x.size)
td.kernel(x0=x0)
```

**Comment by szgoger** [comment]
Yes, it works, and together with the Davidson settings, it _should_ be enough for most purposes. It might probably be also a good idea to add mentions of these options to the manual.
