### ISSUE TITLE
FCI for pbc

### ISSUE THREAD

**Issue by whopezx** [pyscf/pyscf#2038]
Hello,
I want to use FCI to calculate some small periodic systems. I found that there is CI in pbc, but there is no FCI. And I can not find an example.
Thank you.

**Comment by sunqm** [comment]
You may have to use the APIs to build Hamiltonian, then call the molecular FCI functions.
The integrals for PBC systems can be found here:
https://github.com/pyscf/pyscf/blob/master/examples/pbc/30-mo_integrals.py
You may also need to call the `mf.get_hcore()` to get 1-electron integrals and `mf.energy_nuc()` for the nuclear energy. Then there should be enough examples in the fci folder you can refer to for an FCI calculation.

**Comment by WangHB0** [comment]
I understand. Thank you so much for the responses.

**Comment by whopezx** [comment]
Hello, 
Thanks again for your answer, I encountered a problem that confused me.
I am using FCI to calculate that the ground state energy of Si at the gamma point is higher than the ground state energy calculated using CCSD. Why does this happen?
I used the **"gth-szv"** basis set and **"gth-pade"** pseudopotential. When the basis set is changed to **"gth-dzv"**, the calculation results are as expected. The following is my code:
```
#!/usr/bin/env python
import numpy as np

import pyscf.pbc.gto as pbcgto
import pyscf.pbc.scf as pbchf
import pyscf.pbc.cc as pbccc
import pyscf.fci as fci

from functools import reduce
import ase.build as build
import pyscf.pbc.tools.pyscf_ase as pyscf_ase

a = 5.431
si = build.bulk(
    name="Si",
    crystalstructure="diamond",
    a=a
)

cell = pbcgto.Cell(
    atom=pyscf_ase.ase_atoms_to_pyscf(si),
    a=si.cell,
    # basis='gth-szv',
    basis='gth-dzv',
    pseudo='gth-pade',
    verbose=1
)
cell.incore_anyway = True
cell.build()

mf = pbchf.RHF(cell, exxdiv=None)
erhf = mf.kernel()

mcc = pbccc.RCCSD(mf)
ercc, t1, t2 = mcc.kernel()

nuc_energy = mf.energy_nuc()
h1e = reduce(np.dot, (mf.mo_coeff.T, mf.get_hcore(), mf.mo_coeff))
eri = mf.with_df.ao2mo(mf.mo_coeff)

cisolver = fci.direct_spin1.FCI(cell)
cisolver.max_cycle = 100
cisolver.conv_tol = 1e-10
nmo = mf.mo_coeff.shape[1]
e, fcivec = cisolver.kernel(h1e, eri, nmo, 8, ecore=nuc_energy)

print("HF energy: {}".format(erhf))
print("CCSD energy: {}".format(mcc.e_tot))
print("FCI energy: {}".format(e))

```

**Comment by tberkel** [comment]
CCSD is not variational.

**Comment by whopezx** [comment]
Yes, you're right. Thanks for your answer. I understand why CCSD is lower than FCI.
And I use FCI calculate the ground state energy of other k-points, because other k-points' `mf.mo_coeff` is complex, the one- and two-electron integral calculated using `mf.mo_coeff` is also complex. I referenced [example](https://github.com/pyscf/pyscf/blob/master/examples/fci/03-given_complex_h1e_h2e.py) used `fci.fci_dhf_slow.FCI()` solver, and I made the following adjustments to the code above:
- Specify point k
```
mf = pbchf.RHF(cell, exxdiv=None)
->
kpt = cell.make_kpts([1,1,1], scaled_center=[0.5, 0.5, 0.5])
mf = pbchf.RHF(cell, kpt=kpt, exxdiv=None)
```
- Reshape eri (because I use **gth-szv** basis, there are 8 orbitals)
```
eri = mf.with_df.ao2mo(mf.mo_coeff)
->
eri = mf.with_df.ao2mo(mf.mo_coeff)
eri = eri.reshape([8] * 4)
```
- Change fci solver
```
cisolver = fci.direct_spin1.FCI(cell)
->
cisolver = fci.fci_dhf_slow.FCI(cell)
```
I find that the other k-points are much lower than the HF's ground state energy. I wonder my one- and two-electron integral calculations are wrong or I shouldn't choose `fci.fci_dhf_slow.FCI()` solver? but other solver seem do not support complex one- and two-electron integral. And I use following code to examine the complex two-electron integral whether have 8 permutation symmetry (True):
```
assert np.allclose(h2, h2.transpose(2, 3, 0, 1), atol=1e-10, rtol=1e-10) and \
                   np.allclose(h2, h2.transpose(1, 0, 3, 2).conj(), atol=1e-10, rtol=1e-10) and \
                   np.allclose(h2, h2.transpose(3, 2, 1, 0).conj(), atol=1e-10, rtol=1e-10), \
                "double electron integral does not have 8-fold permutation symmetry"
```
For example, I want to calculate the ground state energy of the diamond structure Si at point (0.5, 0.5, 0.5), which is -5.995 using HF, -6.042 using CCSD, and -7.048 using FCI, all in units of hartree. The result of FCI is definitely lower than the result of HF, but it shouldn't be so much lower than that! In other k-points, the error is much bigger.

**Comment by xubwa** [comment]
The dhf fci solver shouldn't be used here. You are trying to do some kind of complex valued full ci but still based on restricted spatial orbital integrals, fci_dhf_slow is designed for complex valued spin orbital integrals. PySCF might not have a fci solver that matches your purpose.

**Comment by tberkel** [comment]
And you can’t just do FCI for a bunch of different k points independently,
unless you’re trying to do something like twist averaging.

**Comment by whopezx** [comment]
Thanks to everyone's replies! I unstandard.
