### ISSUE TITLE
FCI Solver with Spinor Orbitals 

### ISSUE THREAD

**Issue by mclothier00** [pyscf/pyscf#2057]
I'm currently working on a project that requires CI coefficients in a spin-orbital basis. I need a FCI solver that does not assume alpha/beta degeneracy (like direct_uhf) and does not require a hermitian Hamiltonian (like direct_nosym). Is there something in PySCF that can do this? If not, would it be easy with PySCF's current framework to create a new hybrid solver combining direct_uhf and direct_nosym?

Thank you!

**Comment by sunqm** [comment]
No, there is no such modules in the current implementation. If there is no coupling between the "spin-up" and "spin-down" orbitals, like the Kramers-restricted spinor orbitals, you probably can create a function like the direct_uhf kernel https://github.com/pyscf/pyscf/blob/master/pyscf/lib/mcscf/fci_contract.c#L459 in the `fci_contract_nosym.c` file. If you are dealing with a set of arbitrary spinor orbitals, you can modify the current `fci_contract_nosym.c` , in which you can remove all operations for beta orbitals (function name with suffix `_b`)

**Comment by xubwa** [comment]
I think the fci_dhf_slow handles such case. It's just slow.

________________________________

**Comment by mclothier00** [comment]
fci_dhf_slow is exactly what I need, thank you!
