### ISSUE TITLE
Adding a contribution of new feature in exchange-correlation functional to analytic nuclear gradients

### ISSUE THREAD

**Issue by KirillKulaev** [pyscf/pyscf#2066]
Hello, I'm trying to test a new exchange correlation functional in a geometry optimization problem, a functional that I'm testing is MGGA-like, but it also depends on other input features. What should I add to the function **pyscf.grad.rks.get_vxc()** to contribute to the gradients from these new features? I see that the contribution from gamma and tao is calculated here:
![image](https://github.com/pyscf/pyscf/assets/139176905/fd64443f-b555-4ba9-bf88-abb7e0021731)
but how can I modify this code to take into account the contribution of the new features if I have part of the potential dExc/df(r) yet?

Thank you in advance!

**Comment by sunqm** [comment]
The MGGA code supports only the density, density gradients, and tau as the parameters. Specifically, the `eval_xc_eff` only supports the derivatives wrt the three features. If you need to compute integrals for a new feature, you need to modify the `eval_xc_eff` method of `NumInt` class, to include the additional derivatives, then add integral code in the get_vxc function.
