### ISSUE TITLE
AO makeup of each MO

### ISSUE THREAD

**Issue by HehnLukas** [pyscf/pyscf#2067]
Hello,

I want to generate a population analysis that tells me how much of each atomic orbital makes up each molecular orbital. So far I have been doing this:

```
orbital_types = [' 1s    ', ' 2s    ', ' 3s    ', ' 4s    ', ' 5s    ', ' 6s    ', ' 7s    ', ' 2px   ', ' 2py   ', ' 2pz   ', ' 3px   ', ' 3py   ', ' 3pz   ', ' 4px   ', ' 4py   ', ' 4pz   ', ' 5px   ', ' 5py   ', ' 5pz   ', ' 6px   ', ' 6py   ', ' 6pz   ', ' 3dxy  ', ' 3dyz  ', ' 3dz\^2 ', ' 3dxz  ', ' 3dx2-y2', ' 4dxy  ', ' 4dyz  ', ' 4dz\^2 ', ' 4dxz  ', ' 4dx2-y2', ' 5dxy  ', ' 5dyz  ', ' 5dz\^2 ', ' 5dxz  ', ' 5dx2-y2', ' 6dxy  ', ' 6dyz  ', ' 6dz\^2 ', ' 6dxz  ', ' 6dx2-y2', ' 4f ', ' 5f ', ' 6f ', ' 5g  ']

orbitals = len(mo_coeff[0])
atoms = []
labels = []
    
for i in range(mol.natm):
    atoms.append(str(i) + ' ' + str(mol.atom_symbol(i)))
a = np.empty((len(orbital_types)*len(atoms) , orbitals))
    
i = 0

for atom in atoms:
    for orb in orbital_types:
        labels.append(atom + orb)
        mapp = mo_mapping.mo_comps(labels[i], mol, mo_coeff)
        a[i] = np.array(mapp)
        i += 1
```

after some string formatting, I can then use the values from a to give me output like this (for eg. an oxygen molecule):

Makeup of MO 4:

1   O  2s         0.42487
2   O  2s         0.35480
2   O  2pz        0.13725
1   O  2pz        0.08136

This is what I want, however, the double loop over each atom and each orbital type and calling mo_comps each time is very inefficient.  Is there some faster way to do this?

**Comment by xubwa** [comment]
You may obtain the labels through mol.ao_labels().

**Comment by HehnLukas** [comment]
That is helpful, thanks. I don't think that saves much computing time, unfortunately.

**Comment by sunqm** [comment]
Checking the implementation of the `mo_comps` function https://github.com/pyscf/pyscf/blob/b556049b8104c9fb4735149fa65665f62443565e/pyscf/tools/mo_mapping.py#L103 , the slow operation is the orthogonalization  `lao = lo.orth.orth_ao(mol, orth_method, s=s)` . You can put your double loop after the orthogonalization, like:
```
    with lib.temporary_env(mol, cart=cart):
        assert (mo_coeff.shape[0] == mol.nao)
        s = mol.intor_symmetric('int1e_ovlp')
        lao = lo.orth.orth_ao(mol, orth_method, s=s)

        for atom in atoms:
            for orb in orbital_types:
                labels.append(atom + orb)
                idx = gto.mole._aolabels2baslst(mol, labels[i])
                mo1 = reduce(numpy.dot, (lao[:,idx].T, s, mo_coeff))
                mapp = np.einsum('ki,ki->i', mo1, mo1)
                a[i] = np.array(mapp)
                i += 1
```
