### ISSUE TITLE
Unsure How Best To Employ ωB97X-D Functional

### ISSUE THREAD

**Issue by corinwagen** [pyscf/pyscf#2069]
Hey folks, I'm a bit perplexed about how to use ωΒ97X-D with PySCF. 

To select the functional, you can say [``xc=WB97X_D``](https://github.com/pyscf/pyscf/blob/master/pyscf/dft/libxc.py#L522) or [``xc=WB97X-D``](https://github.com/pyscf/pyscf/blob/master/pyscf/dft/libxc.py#L1251) - but the external dftd3 library doesn't parse either of these names. Instead, dftd3 seems to expect ``xc`` to be called [``wb97x``](https://github.com/dftd3/simple-dftd3/blob/main/src/dftd3/param.f90#L202), which [maps to a different functional in PySCF](https://github.com/pyscf/pyscf/blob/master/pyscf/dft/libxc.py#L521). 

Part of the issue here is that calling ``dftd3.pyscf.energy()`` [automatically builds the xc name from the PySCF object](https://github.com/dftd3/simple-dftd3/blob/main/python/dftd3/pyscf.py#L305C5-L311C6), with no way to override.

Here's an example script that dies:
```
import pyscf
import dftd3.pyscf as disp

xyz = """C                 -0.71618036    2.71883299    0.00000000
C                  0.67897964    2.71883299    0.00000000
C                  1.37651764    3.92658399    0.00000000
C                  0.67886364    5.13509299   -0.00119900
C                 -0.71596136    5.13501499   -0.00167800
C                 -1.41356236    3.92680899   -0.00068200
H                 -1.26593936    1.76651599    0.00045000
H                  1.22848764    1.76631999    0.00131500
H                  2.47619764    3.92666399    0.00063400
H                  1.22906364    6.08723599   -0.00125800
H                 -1.26608336    6.08729599   -0.00263100
H                 -2.51316636    3.92699199   -0.00086200"""

mol = pyscf.M(
    atom=xyz,
    basis="6-31G(d)",
    charge=0,
    spin=0,
    symmetry=True
)

mf = pyscf.scf.KS(mol)
mf.xc = "WB97X_D"

mf = disp.energy(mf)

energy = mf.kernel()
```

And here's the error message that I get:

```
Traceback (most recent call last):
  File "/Users/cwagen/business_code/pyscf/wb97xd.py", line 30, in <module>
    energy = mf.kernel()
             ^^^^^^^^^^^
  File "<string>", line 2, in kernel
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/pyscf/scf/hf.py", line 1718, in scf
    kernel(self, self.conv_tol, self.conv_tol_grad,
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/pyscf/scf/hf.py", line 125, in kernel
    e_tot = mf.energy_tot(dm, h1e, vhf)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/pyscf/scf/hf.py", line 295, in energy_tot
    nuc = mf.energy_nuc()
          ^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/dftd3/pyscf.py", line 272, in energy_nuc
    enuc += self.with_dftd3.kernel()[0]
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/dftd3/pyscf.py", line 171, in kernel
    param = _damping_param[self.version](
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/dftd3/interface.py", line 218, in __init__
    DampingParam.__init__(self, **kwargs)
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/dftd3/interface.py", line 188, in __init__
    self._param = self.load_param(**kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/dftd3/interface.py", line 223, in load_param
    return library.load_rational_damping(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/dftd3/library.py", line 142, in load_rational_damping
    error_check(lib.dftd3_load_rational_damping)(method, atm), _delete_param
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/aimnet2/lib/python3.11/site-packages/dftd3/library.py", line 69, in handle_error
    raise RuntimeError(ffi.string(_message).decode())
```

It's probably possible to directly override the xc name by constructing a ``dftd3.pyscf.DFTD3Dispersion`` object, but it's nice to have a unified API for different objects, which the ``dftd3.pyscf.energy()`` function does nicely. (It's possible that #1916 fixes this, and that this will all be a moot point in the next release.)

Am I doing something wrong here, or is there a better way to approach this?

**Comment by hebrewsnabla** [comment]
If you combine wB97X with D3, you get neither wB97XD nor wB97X-D3 nor wB97X-D3BJ. wB97XD requires wB97X_D from libxc and DFTD2 (looks like simple-dftd3 does not provide that) while wB97X-D3 requires the combination of wB97X_D3 from libxc and its D3zero parameter, wB97X-D3BJ requires wB97X_V from libxc and its D3BJ parameter.

I guess the parameter for wB97X-D3 and wB97X-D3BJ in simple-dftd3 is right but the interface for pyscf should be modified to accept the correct functional name.

**Comment by corinwagen** [comment]
Ah, good point. ωB97X-D3 / ωB97X-D3BJ are both good enough, no special attachment to the D2 dispersion correction. Seems like the name mismatch issues still apply here?

**Comment by wxj6000** [comment]
In PySCF 2.5 (just released), you should be able to do this
```
mf.xc='wb97x'
mf.disp='d3bj'
```
for wb97x-D3BJ
A unified wrapper to further integrate libxc and dftd3 xc functional names would be useful.

**Comment by hebrewsnabla** [comment]
> In PySCF 2.5 (just released), you should be able to do this
> 
> ```
> mf.xc='wb97x'
> mf.disp='d3bj'
> ```
> 
> for wb97x-D3BJ A unified wrapper to further integrate libxc and dftd3 xc functional names would be useful.

I don't think so. wb97x-d3bj does not equal to wb97x plus d3bj. If you try some calculations with orca, you will find that the SCF part of wb97x-d3bj is different from wb97x's but the same as wb97x-v's. 

So the correct way for wb97x-d3bj in current pyscf is tricky: first set mf.xc = 'wb97x_v', then remove the VV10 part, and add the D3BJ part.
To make it simpler, we need to do: define a 'wb97x-d3bj' in pyscf which is wb97x-v without vv10; and make simple-dftd3 accept that.

**Comment by wxj6000** [comment]
You are right. @hebrewsnabla The functional name is misleading. You can try the following trick. It was a solution for gpu4pyscf. But the API should be same as PySCF. You can simply change the 'gpu4pyscf' to 'pyscf' whenever it appears. 
https://github.com/pyscf/gpu4pyscf/issues/95

**Comment by hebrewsnabla** [comment]
Yeah, that's the exactly same trick I've used to turn off nlc. Hope there could be a more decent way to turn off nlc, or implement a native definition of wB97X-D3BJ instead of turning nlc on and off.

**Comment by sunqm** [comment]
These dispersion related XC functionals can be handled properly now, thanks to PR #2084

**Comment by corinwagen** [comment]
thanks all!
