### ISSUE TITLE
Has the "WARN: len(magmom) != natm. Set magmom to zero" issue been fixed?

### ISSUE THREAD

**Issue by EvGeGr** [pyscf/pyscf#2070]
Hello,

I wonder if the headed issue has been fixed?
(There was a post regarding this issue recently: https://github.com/pyscf/pyscf/issues/2055 )

Kind regards,
Evgeniy

**Comment by verena-neufeld** [comment]
Hi @EvGeGr, I think so but do you have an example that still gives that warning?
