### ISSUE TITLE
MakeAngularGrid with nPoints = 1

### ISSUE THREAD

**Issue by tkoeppe** [pyscf/pyscf#2073]
At https://github.com/pyscf/pyscf/blob/6f8ce439fbe0c26ec4d226e2225b28c7f668f922/pyscf/lib/dft/CxLebedevGrid.c#L5094, should `case 0:` be `case 1:`? It seems like this is the case of "1 point", and we set `N = 1` just below.

**Comment by sunqm** [comment]
Fixed in #2076
