### ISSUE TITLE
I want to calculate CCSD energies between a pair of orbitals

### ISSUE THREAD

**Issue by prasanta13** [pyscf/pyscf#2074]
Hello, I am trying to calculate the CCSD correlation energy between each pair of orbitals. In this small test system,
```
from pyscf import gto, scf, ao2mo, cc
from pyscf.gto import mole

# Define your molecule
mol = gto.Mole()
mol.atom = '''
    O  0.0000000, 0.0000000, 0.0000000
    H  0.757606,  0.586006,  0.0000000
    H -0.757606,  0.586006,  0.0000000'''
mol.basis = 'sto-3g'
mol.charge = 0
mol.spin = 0
mol.build()

# Perform SCF calculation
mf = scf.RHF(mol)
mf.kernel()

# Get MO coefficient matrix
mo_coeff = mf.mo_coeff

# Obtain the CCSD energy from canonical
mcc = cc.CCSD(mf)
ecc,t1,t2 = mcc.kernel()
print("CCSD correlation energy = ",mcc.e_corr)
print("Total CCSD energy = ",mcc.e_tot)
```
The correlation energy is -0.0494284459751351 Hartree. Now, this calculation takes all HF orbitals and occupancies as arguments to the CCSD function. If I know correctly, I can calculate the CCSD correlation energies between each pair of MO (of course, one orbital should be doubly occupied, and the other should be vacant) and sum them up to obtain the total correlation energy. To do this, I take a pair of orbitals (one from doubly occupied and another from vacant MO) and run the CCSD calculation for each pair. So, for water molecules with a sto-3g basis, the MO coefficient matrix is 7*7, and the occupancy is a numpy array [2.0,2.0,2.0,2.0,2.0,0.0,0.0]. So I obtained the MO columns using this (just for testing and without any beautiful coding)
```
import numpy as np
coeff_0 = mf.mo_coeff[:,0]; coeff_1 = mf.mo_coeff[:,1]; coeff_2 = mf.mo_coeff[:,2]; coeff_3 = mf.mo_coeff[:,3]
coeff_4 = mf.mo_coeff[:,4]; coeff_5 = mf.mo_coeff[:,5]; coeff_6 = mf.mo_coeff[:,6]
```
Then, I merged the pairs for occupied and virtual MOs. In the case of the MO coefficient matrix, columns 0-4 are occupied, and columns 5-6 are virtual. So, for each occupied column, there will be two virtual columns. I merged the columns as,
```
mo_coeff05 = np.column_stack((coeff_0,coeff_5));mo_coeff06 = np.column_stack((coeff_0,coeff_6))
mo_coeff15 = np.column_stack((coeff_1,coeff_5));mo_coeff16 = np.column_stack((coeff_1,coeff_6))
mo_coeff25 = np.column_stack((coeff_2,coeff_5));mo_coeff26 = np.column_stack((coeff_2,coeff_6))
mo_coeff35 = np.column_stack((coeff_3,coeff_5));mo_coeff36 = np.column_stack((coeff_3,coeff_6))
mo_coeff45 = np.column_stack((coeff_4,coeff_5));mo_coeff46 = np.column_stack((coeff_4,coeff_6))
```
And at last, I run the CCSD for each merged MO coefficient matrix.
```
mcc.mo_occ = np.array([2.0,0.0])
mcc.mo_coeff = mo_coeff05
mcc.kernel()[0]
mcc.mo_coeff = mo_coeff06
mcc.kernel()[0]
mcc.mo_coeff = mo_coeff15
mcc.kernel()[0]
mcc.mo_coeff = mo_coeff16
mcc.kernel()[0]
mcc.mo_coeff = mo_coeff25
mcc.kernel()[0]
mcc.mo_coeff = mo_coeff26
mcc.kernel()[0]
mcc.mo_coeff = mo_coeff35
mcc.kernel()[0]
mcc.mo_coeff = mo_coeff36
mcc.kernel()[0]
mcc.mo_coeff = mo_coeff45
mcc.kernel()[0]
mcc.mo_coeff = mo_coeff46
mcc.kernel()[0]
```
What I expected that if I sum all the correlation energies, I will get the total CCSD correlation energy, but some of the correlation energy are even higher than the total system.
```
E(CCSD) = -51.47188187443665  E_corr = -0.0003962543997611398
E(CCSD) = -51.47149476545477  E_corr = -9.145417883697846e-06
E(CCSD) = -6.483145580303841  E_corr = -1.059192232873223
E(CCSD) = -5.424905601367101  E_corr = -0.0009522539364820224
E(CCSD) = -2.90788145525101  E_corr = -0.002489550153102168
E(CCSD) = -5.339446749364194  E_corr = -2.434054844266286
E(CCSD) = -4.937559682283515  E_corr = -0.9363818461883874
E(CCSD) = -4.003003233876766  E_corr = -0.001825397781638726
E(CCSD) = -4.845351104114307  E_corr = -0.0003760041376774681
E(CCSD) = -4.84514723864436  E_corr = -0.0001721386677304669
```
Also, the SCF + CCSD energy defined by this, E(CCSD) = is very different.

**Is my approach wrong?**

**Comment by tberkel** [comment]
There will probably be an easier way to do what you want, but first: the CCSD correlation energy contributions depend on *two* occupied and *two* unoccupied simultaneously,

$$
E_c = \sum_{ijab} E_{ijab}
$$

so I'm not sure exactly what you would like to calculate.

**Comment by tberkel** [comment]
You don't want to re-run the `kernel()` function, because that implies re-solving the CC amplitude equations. Here's a version that should work for you (though I admit I'm not 100% sure if this is what you want):
```
import numpy

def get_eijab(mcc, i, j, a, b, eris=None):
    if eris is None:
        eris = mcc.ao2mo()

    eris_iabj = eris.ovvo[i,a,b,j]
    tau_ijab = t2[i,j,a,b] + t1[i,a]*t1[j,b]
    tau_jiab = t2[j,i,a,b] + t1[j,a]*t1[i,b]
    eijab = (2*tau_ijab-tau_jiab)*eris_iabj

    return eijab

eris = mcc.ao2mo()

nocc, nvir = t1.shape

# Get an individual contribution
i = 0
j = 1
a = 4 - nocc
b = 5 - nocc
eijab = get_eijab(mcc, i, j, a, b)

# Sum all contributions
e_corr = 0.0
for i in range(nocc):
    for j in range(nocc):
        for a in range(nvir):
            for b in range(nvir):
                e_corr += get_eijab(mcc, i, j, a, b, eris=eris)
print("Summed Ecorr =", e_corr)
```

**Comment by prasanta13** [comment]
Thank you very much for your help. It is partially what I want. This code takes the t1 and t2 amplitudes for the whole system, so I have to solve ccsd for the entire system. This "solving ccsd for the entire system"  is the part I do not want. Suppose I have a huge chemical system, and CCSD can not be run for the entire molecule. So, I take the orbitals, obtain the t1 and t2 amplitudes, and run the code you kindly provided. How can it be done? 
This is a slightly modified version of the code that I was trying to run.

```
from pyscf import gto, scf, ao2mo, cc
from pyscf.gto import mole

# Define your molecule
mol = gto.Mole()
mol.atom = '''
    O  0.0000000, 0.0000000, 0.0000000
    H  0.757606,  0.586006,  0.0000000
    H -0.757606,  0.586006,  0.0000000'''
mol.basis = 'sto-3g'
mol.charge = 0
mol.spin = 0
mol.build()

# Perform SCF calculation
mf = scf.RHF(mol)
mf.kernel()

# Get MO coefficient matrix
mo_coeff = mf.mo_coeff
orbshape = mo_coeff.shape[0]
# Obtain the CCSD energy from canonical
mcc = cc.CCSD(mf)
#ecc,t1,t2 = mcc.kernel()
#print("CCSD correlation energy = ",mcc.e_corr)
#print("Total CCSD energy = ",mcc.e_tot)
"""
converged SCF energy = -74.9630018480883
E(CCSD) = -75.01243029406339  E_corr = -0.04942844597513516
CCSD correlation energy =  -0.04942844597513516
Total CCSD energy =  -75.01243029406339
"""

import numpy

def get_eijab(mcc, i, j, a, b, eris=None):
    if eris is None:    
        eris = mcc.ao2mo()

    eris_iabj = eris.ovvo[i,a,b,j]
    tau_ijab = t2[i,j,a,b] + t1[i,a]*t1[j,b]
    tau_jiab = t2[j,i,a,b] + t1[j,a]*t1[i,b]
    eijab = (2*tau_ijab-tau_jiab)*eris_iabj
    return eijab

eris = mcc.ao2mo()

ne = mole.tot_electrons(mol)
print(" Total number of electrons is ", ne)

# The number of doubly occupied orbitals...assumes closed-shell
neby2 = ne/2
ineby2 = int(neby2)   
# The number of virtual/empty orbitals
nvir = orbshape - ineby2
nocc = ineby2
#nocc, nvir = t1.shape
print("nocc, nvir \n",nocc,nvir)

# Sum all contributions
e_corr = 0.0
steps = 0
for i in range(nocc):
    for j in range(nocc):
        for a in range(nvir):
            for b in range(nvir):
                e_corr += get_eijab(mcc, i, j, a, b, eris=eris)
print("Summed Ecorr =", e_corr*2625.5)
```
This shows error,
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[8], line 7
      5 b = 5 - nocc
      6 print("i,j,a,b \n",i,j,a,b)
----> 7 eijab = get_eijab(mcc, i, j, a, b)
      8 print("eijab",eijab)
      9 # Sum all contributions

Cell In[2], line 8, in get_eijab(mcc, i, j, a, b, eris)
      5     eris = mcc.ao2mo()
      7 eris_iabj = eris.ovvo[i,a,b,j]
----> 8 tau_ijab = t2[i,j,a,b] + t1[i,a]*t1[j,b]
      9 tau_jiab = t2[j,i,a,b] + t1[j,a]*t1[i,b]
     10 eijab = (2*tau_ijab-tau_jiab)*eris_iabj

NameError: name 't2' is not defined
```

**Comment by tberkel** [comment]
Sorry, but what you want to do won't work. You can't just solve the amplitude equations for one orbital or orbital pair at a time. They have to be coupled to the other orbitals in the system. It sounds like you want to do something like cluster-in-molecule (CIM), but that requires more coding. Our group has implemented CIM-CC in PySCF and will add it to the codebase in the coming months.

**Comment by prasanta13** [comment]
Thank you, @tberkel, for pointing this out. Otherwise, I would have tried and failed repeatedly. I was trying to implement the method provided here, J. Chem. Phys. 133, 014107 (2010). Thank you very much for your precious time and kind information.

**Comment by prasanta13** [comment]
Please close this issue. It has been solved.
Thank you very much
Prasanta
