### ISSUE TITLE
Number of basis (AO) an the size of the MO(molecular orbitals)

### ISSUE THREAD

**Issue by Sanarmy** [pyscf/pyscf#2079]
Hello,
I'm trying to obtain the number of basis of a dimer of antracene in pyscf, in orca i obtain 492 (the basis are in cartesian coordinates) in gaussian i obtain 520(the basis are in spherical coordinates), but in pyscf i obtain 228, anyone knows why? Coulde be because of the symmetry of some basis? If its because of that how can avoid it, to obtain the real number of basis, the real shape of the molecular orbitals and the real shape of the overlap matrix (as its sizes are nbasis x nbasis).

**Comment by Sanarmy** [comment]
mol = gto.Mole()
mol.atom='''
C        4.090450209      0.000000000     -2.975791115
C        4.090450209     -0.024480048     -1.546049996
C        4.090450209     -1.220811387     -0.818082650
C        4.090450209      1.232364750     -0.832756148
C        4.090450209      1.220811314      0.567605107
C        4.090450209      0.024479976      1.295572453
C        4.090450209     -1.232364823      0.582278605
C        4.090450209      1.186342134     -3.660187692
C        4.090450209      2.447291412     -1.586886209
H        4.090450209      2.166796306      1.104477500
C        4.090450209     -0.000000072      2.725313572
C        4.090450209     -2.447291484      1.336408666
C        4.090450209     -2.426560063      2.705852546
C        4.090450209     -1.186341337      3.409710642
H        4.090450209      0.946412073      3.259778050
H        4.090450209     -3.391428230      0.797934867
H        4.090450209     -3.357304899      3.265464250
H        4.090450209     -1.189538840      4.495730862
C        4.090450209      2.426559991     -2.956330089
H        4.090450209     -0.946412146     -3.510255593
H        4.090450209     -2.166796378     -1.354955043
H        4.090450209      1.189538768     -4.746208405
H        4.090450209      3.391428158     -1.048412410
H        4.090450209      3.357304826     -3.515941793
C        0.090450209      0.000000000     -2.975791115
C        0.090450209     -0.024480048     -1.546049996
C        0.090450209     -1.220811387     -0.818082650
C        0.090450209      1.232364750     -0.832756148
C        0.090450209      1.220811314      0.567605107
C        0.090450209      0.024479976      1.295572453
C        0.090450209     -1.232364823      0.582278605
C        0.090450209      1.186342134     -3.660187692
C        0.090450209      2.447291412     -1.586886209
H        0.090450209      2.166796306      1.104477500
C        0.090450209     -0.000000072      2.725313572
C        0.090450209     -2.447291484      1.336408666
C        0.090450209     -2.426560063      2.705852546
C        0.090450209     -1.186341337      3.409710642
H        0.090450209      0.946412073      3.259778050
H        0.090450209     -3.391428230      0.797934867
H        0.090450209     -3.357304899      3.265464250
H        0.090450209     -1.189538840      4.495730862
C        0.090450209      2.426559991     -2.956330089
H        0.090450209     -0.946412146     -3.510255593
H        0.090450209     -2.166796378     -1.354955043
H        0.090450209      1.189538768     -4.746208405
H        0.090450209      3.391428158     -1.048412410
H        0.090450209      3.357304826     -3.515941793
'''
mol.basis='631g**'
mol.symmetry = False
mol.build()
mf = dft.RKS(mol)
mf.xc = 'B3LYP'

#mytd = tddft.TDA(mf)
mytd = tddft.TDDFT(mf)
mytd.nstates = 30
mf.kernel()
mytd.kernel()
mytd.analyze()

natm = mol.natm
nelec = sum(mol.nelec)
nbasis = mol.nbas
MO = mf.mo_coeff
This is my input

**Comment by hebrewsnabla** [comment]
`mol.nbas` is the number of shells. `mol.nao` is the number of basis functions. By default (mol.cart = False), PySCF uses spherical basis.

**Comment by verena-neufeld** [comment]
Hi @Sanarmy , thanks for your question. Has it been resolved?

**Comment by Pauarsan** [comment]
Yes, it been solved satisfactorily. It works.
