### ISSUE TITLE
RuntimeError('Using k-point symmetry now requires cell to be built with space group symmetry info:\n cell.space_group_symmetry = True\n cell.symmorphic = False\n cell.build()')  in pbc/gto/cell.py

### ISSUE THREAD

**Issue by yuanshunyue** [pyscf/pyscf#2081]
Does this error message mean using k-point symmetry requires both `cell.space_group_symm=True` and `cell.symmorphic=False`? Why? But as long as I set `cell.space_group_symm=True`, it does not report an error when `cell.symmorphic=True`. 

https://github.com/pyscf/pyscf/blob/e1dedd25c7787433b8988e4b7ab11a4a23f38bc3/pyscf/pbc/gto/cell.py#L738-L745

Thanks!

**Comment by fishjojo** [comment]
No, these are just the default settings. You can set `symmorphic` to `True`. Maybe a better error message should be raised.

**Comment by yuanshunyue** [comment]
I see thanks!
