### ISSUE TITLE
TD-SCF states doesn't converge

### ISSUE THREAD

**Issue by shashankku414** [pyscf/pyscf#2083]
I want to find the excited states and transition dipole moments of CO2 using TDDFT. Below is my code,

`mol = gto.Mole()
mol.build(
    atom = 'C 0 0 0; O 0 0 1.1637; O 0 0 -1.1637',  # in Angstrom
    # basis = '631g',
    basis='ccpvdz',
    unit = 'B',
    symmetry = True,
    symmetry_subgroup = 'D2h',
    verbose = 4,
)

mf = dft.RKS(mol)
mf.xc = 'camb3lyp'
mf.newton()
mf.kernel()

mytd = tddft.TDDFT(mf)
mytd.nstates = 10
mytd.kernel()
mytd.analyze()`

However, in the 110 line of the output file : TD-SCF states [0, 2, 3, 5, 7, 9] not converged. I have tried different functionals, but the issue remains. Also the the excited energies doesn't look right. Can you help me with this issue? I have also attached the full output text file.

[output.txt](https://github.com/pyscf/pyscf/files/14313864/output.txt)

**Comment by John-zzh** [comment]
Hi Shashank, 

Try this,
https://github.com/John-zzh/TDDFT_Davidson
