### ISSUE TITLE
Density fitting method in periodic hcore computation

### ISSUE THREAD

**Issue by dchung0741** [pyscf/pyscf#2086]
In periodic system, [`get_hcore`](https://github.com/pyscf/pyscf/blob/e1dedd25c7787433b8988e4b7ab11a4a23f38bc3/pyscf/pbc/scf/hf.py#L76-L100) computation sometime causes memory error. I found that this can be fixed by replacing the density fitting method in the `get_nuc` function [here](https://github.com/pyscf/pyscf/blob/e1dedd25c7787433b8988e4b7ab11a4a23f38bc3/pyscf/pbc/scf/hf.py#L95-L100) to `RSGDF` or other density fitting method. Is it possible that there is an option in the `get_hcore` function for choosing the density fitting method?
Thanks!

**Comment by fishjojo** [comment]
Usually, one would call the `get_hcore` method of the mean-field object:
```
mf = pbc.scf.KRHF(cell, kpts)  # FFTDF
mf = pbc.scf.KRHF(cell, kpts).density_fit()  # GDF
mf = pbc.scf.KRHF(cell, kpts).rs_density_fit()  # RS-GDF
mf = pbc.scf.KRHF(cell, kpts).mix_density_fit()  # MIXED-GDFT
hcore = mf.get_hcore()
```

**Comment by verena-neufeld** [comment]
Hi @dchung0741 , thanks for your question. Has it been resolved and can this issue be closed?

**Comment by dchung0741** [comment]
Hi! Thank you for the reply and sorry for my late response. I think I should ask again:
Is changing [this function](https://github.com/pyscf/pyscf/blob/e1dedd25c7787433b8988e4b7ab11a4a23f38bc3/pyscf/pbc/scf/hf.py#L95-L100) to other density fitting function equivalent to the suggested code above?
Thank you!

**Comment by sunqm** [comment]
No. The `get_nuc` method will be called in the iteration than the module level `get_nuc` function. https://github.com/pyscf/pyscf/blob/e1dedd25c7787433b8988e4b7ab11a4a23f38bc3/pyscf/pbc/scf/hf.py#L625 . The `with_df` attribute in this method corresponds to different DF methods.
