### ISSUE TITLE
Missing includes

### ISSUE THREAD

**Issue by susilehtola** [pyscf/pyscf#2089]
The PySCF `__init__.py`, https://github.com/pyscf/pyscf/blob/master/pyscf/__init__.py,  is only including a small subset of directories:

```
from pyscf import __config__
from pyscf import lib
from pyscf import gto
from pyscf import scf
from pyscf import ao2mo
```

This causes some problems for Julia, since e.g. `geomopt` can't be used since it hasn't been imported in the interface. I am wondering if this is a conscious design: is there a reason why all subdirectories aren't imported in init?

**Comment by sunqm** [comment]
This is by design. Some C extensions may not be properly compiled. They can cause some modules fail to import. Only a few necessary modules are imported in the `__init__`. It allows you to use pyscf without compiling everything.

**Comment by verena-neufeld** [comment]
Hi @susilehtola , thanks! Has this answered the issue or do you think this should stay open?

**Comment by susilehtola** [comment]
`import pyscf.__all__` seems like a good fix, thanks
