### ISSUE TITLE
Geomopt Example file not working

### ISSUE THREAD

**Issue by valay1** [pyscf/pyscf#2090]
Hi, 
The example file - `examples/geomopt/01-geomeTRIC.py` does not run. I get the error
```
Traceback (most recent call last):
  File "01-geomeTRIC.py", line 8, in <module>
    from pyscf.geomopt.geometric_solver import optimize
  File "/home/valay/LG_Lab/pyscf/pyscf/geomopt/geometric_solver.py", line 24, in <module>
    import geometric
ModuleNotFoundError: No module named 'geometric'

**Comment by xubwa** [comment]
geometric is a external package instead of part of pyscf, therefore it needs to be installed separately. It can be installed by simply run `pip install geometric` or follow other ways of installation listed on their manual [https://geometric.readthedocs.io/en/latest/](url)

**Comment by valay1** [comment]
Yes.
