### ISSUE TITLE
Ewald eta?

### ISSUE THREAD

**Issue by luna-component** [pyscf/pyscf#2094]
Is there a way to control Ewald eta parameter for MF simulations using (GTH) pseudopotentials, when computing nuclear-electron attraction or nuclear-nuclear repulsion?
So far it looks to me as it can be indirectly set by setting cell.precision.

Also: is the Ewald eta same for all the atom species in a unit cell? 
For example: if I recall correctly CP2K Ewald eta is different for different atomic species.

**Comment by tberkel** [comment]
It's a bit hacky, but you could overwrite the `cell.get_ewald_params()` function, whose signature and content is here: https://github.com/pyscf/pyscf/blob/master/pyscf/pbc/gto/cell.py#L648

**Comment by tberkel** [comment]
I'm not sure, maybe @sunqm or @fishjojo knows.

**Comment by fishjojo** [comment]
As far as I know, the nuclear-electron interaction is computed analytically with GDF. The short-range part of the local potential and the non-local potential are computed with real-space analytic integrals. The long-range part of the local potential is computed either by analytic Fourier transform or in similar ways as computing the Coulomb potential, depending on the underlying density fitting method.

**Comment by verena-neufeld** [comment]
Hi @luna-component , thanks! Has your question been answered or should this issue stay open?

**Comment by sunqm** [comment]
As shown by this line https://github.com/pyscf/pyscf/blob/e3e369fc75fcd6f9278acf05a4ab6c6ec4709880/pyscf/pbc/df/rsdf_builder.py#L144, GDF determines the short-range Coulomb parameter `omega` automatically, the energy cutoff for the `omega` is then estimated.  There is no need to specify ewald eta.
