### ISSUE TITLE
Initial guess 'atom' does not work in PySCF 2.4.0

### ISSUE THREAD

**Issue by liam3935** [pyscf/pyscf#2103]
Hi, I'm running a simple DFT calculation of a CO molecule in PBC. However, if I use 'atom' as the initial guess, the following error occurs:

> IndexError: boolean index did not match indexed array along dimension 1; dimension is 28 but corresponding boolean dimension is 14

I'm using PySCF 2.4.0 and Python 3.9.12. Below is my script for the calculation:

```
from pyscf.pbc import gto, dft, scf, df
from pyscf.pbc.lib import chkfile
import os

cell = gto.Cell()
cell.build(unit = 'angstrom',
           a = [[10.0729742049999995, 0.0, 0.0], [0.0, 8.7234516144000001, 0.0], [0.0, 0.0, 40.0]],
           atom = '''
           C    5.036482    4.360231    7.027104
           O    5.036476    4.360919    8.184654
           ''',
           dimension = 3,
           max_memory = 48000,
           verbose = 5,
           basis='def2-svp',
           precision = 1e-10)

from pyscf.pbc.tools import k2gamma
kpts = cell.make_kpts([1,1,1])
cell, phase = k2gamma.get_phase(cell, kpts)

kmf = dft.RKS(cell).rs_density_fit(auxbasis='def2-svp-ri')
kmf.xc = 'pbe'
kmf.chkfile = 'co.chk'
kmf.init_guess = 'atom'
kmf.kernel() 
```

I've also tested the earlier version (2.0.1) of PySCF, which did not give this error. 

Could anyone help to fix this issue? Thanks!

**Comment by fishjojo** [comment]
The latest master branch should work.
