### ISSUE TITLE
minimization method used in SCF procedure

### ISSUE THREAD

**Issue by Jila66** [pyscf/pyscf#2110]
Hi

I use PySCF to run SCF calculation on some solids.
Now I have a question about the methods that used in code.

For SCF procedure :
1- We first have an initial guess for the orbitals. then solve the Fock equation to find the initial energy.
2- Now for the SCF procedure it needs to obtain another set of orbitals, and then solving the Schrödinger equation again with theses until the results converge.

My question is:
By using which minimization method select the best energy or best orbitals ?

Thanks

**Comment by tberkel** [comment]
The specific SCF convergence algorithm used by default is DIIS, and more details are on the User Guide: https://pyscf.org/user/scf.html#converging-scf-iterations

**Comment by Jila66** [comment]
> It is the same thing: the best orbitals are the ones that minimize the energy.

Yeah, I know.
I mean we use the initial guess for initial orbitals, but in the next iteration how the orbitals select?

**Comment by Jila66** [comment]
> The specific SCF convergence algorithm used by default is DIIS, and more details are on the User Guide: https://pyscf.org/user/scf.html#converging-scf-iterations

Thanks,

**Comment by shivupa** [comment]
When you diagonalize the Fock operator, you get a new set of orbitals (eigenvectors) and orbital energies (eigenvalues). For the next iteration you occupy the lowest energy orbitals (by orbital energy).

There  are some special cases where you don't occupy the lowest orbital energy orbitals, mainly when you are doing an excited state SCF or something along those lines, but those are a special exception.

**Comment by verena-neufeld** [comment]
Hi @Jila66 , thanks! Has your question been answered or should this stay open?

**Comment by Jila66** [comment]
> When you diagonalize the Fock operator, you get a new set of orbitals (eigenvectors) and orbital energies (eigenvalues). For the next iteration you occupy the lowest energy orbitals (by orbital energy).
> 
> There are some special cases where you don't occupy the lowest orbital energy orbitals, mainly when you are doing an excited state SCF or something along those lines, but those are a special exception.
> 
> [This tutorial](https://github.com/psi4/psi4numpy/blob/master/Tutorials/03_Hartree-Fock/3a_restricted-hartree-fock.ipynb) may also be of interest to you

Thank you a lot. It's useful for me.

**Comment by Jila66** [comment]
> Hi @Jila66 , thanks! Has your question been answered or should this stay open?

Hi, Yes I got it. I closed this question
