### ISSUE TITLE
dipole moment of Full CI

### ISSUE THREAD

**Issue by okunoyukihiro2** [pyscf/pyscf#2111]
Dear PySCF users. 

I want to calculate dipole moment of small molecule by Full CI.

For CASCI

 cas = mc.run()
 dm = mc.make_rdm1(ao_repr=True) # relaxed density                                        
 dip = scf.hf.dip_moment(mol=mol,dm=dm)

we can get dipole moment.

However,  when we use fci.FCI, how to calculate dipole moment ? 

Sincerely, 

Yukihiro Okuno.

**Comment by sunqm** [comment]
You can call FCISolver.make_rdm1() to get 1-particle density matrix in MO basis, then transform them back to AO basis using the `mf.mo_coeff`. Then, calling the scf.hf.dip_moment function can give you the dipole for FCI.

**Comment by okunoyukihiro2** [comment]
Thank you for reply.
I can get dipole moment as below. 

dm = fcisolver.make_rdm1(fcivec,mol.nao_nr(),nelectron)  # fcivec CI vector 
dm_ao = reduce(np.dot,(mo_coeff,dm,mo_coeff.T))  # back to atomic represantation 

dip = scf.hf.dip_moment(mol=mol,dm=dm_ao)

Sincerely.
