### ISSUE TITLE
Code for mcscf forces (gradients) at a single point

### ISSUE THREAD

**Issue by EvGeGr** [pyscf/pyscf#2116]
Hello,

I am interested just in calculating forces (energy gradients) at a single geometry (without complete geometry optimization) at the mcscf level. What would be the code in such a case? Thanks!

Kind regards,
Evgeniy

**Comment by tberkel** [comment]
`gradients = mc.Gradients().kernel()`
See more examples in `pyscf/examples/grad/`

**Comment by EvGeGr** [comment]
OK, thanks!!!

**Comment by verena-neufeld** [comment]
Hi @EvGeGr , thanks! Can this issue be closed?
