### ISSUE TITLE
Numerical hessian

### ISSUE THREAD

**Issue by JunHyeong1** [pyscf/pyscf#2126]
Hello, I am wondering whether PySCF supports numerical hessian calculations. It seems to me that PySCF SCF calculations direct to their corresponding analytic one when computing the hessian matrix?

**Comment by JunHyeong1** [comment]
@tberkel Thanks for your reply. I am interested in the numerical hessian for vibrational frequencies.

**Comment by tberkel** [comment]
I don't think there's anything black box for numerical hessians, but you
can calculate them yourself by doing numerical first derivatives of
analytical gradients or numerical second derivatives from single-point
calculations (but these might be numerically unstable).

**Comment by JunHyeong1** [comment]
Thank you very much for your reply :)
