### ISSUE TITLE
Total energy pyscf

### ISSUE THREAD

**Issue by computative** [pyscf/pyscf#2130]
Hello.

For some time, I've tried to find out how pyscf dft calculates total energy and particle number. I'm trying to take the trace of the product of density matrix with hamiltonian and trace of the square of the density matrix.

I have found some information on this topic, but it seems that whatever I do, I get the wrong answer. For example [this issue](https://github.com/pyscf/pyscf/issues/1404). It looks like the author says to take the trace of the product of pyscf.pbc.dft.rks.RKS.make_rdm1() with the sum of pyscf.pbc.dft.rks.RKS.get_fock() and pyscf.pbc.dft.rks.RKS.get_hcore(). See for example this example.

```
from pyscf.pbc import gto, dft
import numpy as np
import pyscf.symm
import ase
import pyscf.pbc.gto as pbcgto
from pyscf.pbc.tools import pyscf_ase
import pyscf.pbc.dft as pbcdft

n = 4 # num atoms
 
# making random atomic coordinates and unit cell of unit Ångstrøm-volume
d_min = 0
d_max = 100
while d_min<1.5 or d_max > 3.567:
    arr_R = 3*n**(1/3)*np.random.rand(n,3)
    d = [ [ np.linalg.norm(arr_R[j] - arr_R[i])  for j in range(n) if j != i ] for i in range(n)]
    d_min = np.min(d)
    d_max = np.max(d)

arr_cell = (3.567/2)*n**(1/3)*np.eye(3)
atoms = ase.Atoms(n*'C', positions=arr_R, cell=np.diag(arr_cell), pbc=[1,1,1])


cell = atoms.cell[:]
atoms.set_cell(np.array([np.dot(T, a) for a in cell]),scale_atoms=True)
cell = pbcgto.Cell()
cell.verbose = 5
cell.atom=pyscf_ase.ase_atoms_to_pyscf(atoms)
cell.a=atoms.cell
cell.basis = 'gth-szv'
cell.pseudo = 'gth-lda'
cell.build()
mf=pbcdft.RKS(cell)

mf.kernel()

print(f"E = { np.trace(np.dot(mf.make_rdm1(), mf.get_fock() + mf.get_hcore())) }" )
print(f"n = { np.trace( np.dot(mf.make_rdm1(),mf.make_rdm1()) ) }" )
```

I'm getting the impression it's not me that's the problem because it seems I have tried to change everything in random ways (even in ways that I would not expect it to work) hoping that it would work eventually. But as I have the impression that pyscf can indeed calculate these quantities, can you say what's wrong?

**Comment by fishjojo** [comment]
The electronic part of the energy is defined [here](https://github.com/pyscf/pyscf/blob/4150f854ff293c89ce3bb1907c9d0710a960e66d/pyscf/dft/rks.py#L222-L251), which is the standard implementation of the KS-DFT energy. The exchange-correlation (XC) energy in DFT is a functional of the density, density gradients, Laplacians, etc., which is not equal to the product of the XC potential and the density matrix.
