### ISSUE TITLE
bug in parse_token

### ISSUE THREAD

**Issue by hebrewsnabla** [pyscf/pyscf#2134]
https://github.com/pyscf/pyscf/blob/d3f622d46eef5d9b8702fa6f4577babfb6c2ccfe/pyscf/dft/libxc.py#L1182-L1188

Looks like this should be `x_id` instead of `func_id`. There will be a "local variable 'x_id' referenced before assignment" error if any functional is queried from libxc directly, like gga_x_pbe_gaussian.

**Comment by sunqm** [comment]
Yes, this is a bug. Thanks for catching it. Can you please create a PR to fix this bug?
