### ISSUE TITLE
ump2 typo?

### ISSUE THREAD

**Issue by fishjojo** [pyscf/pyscf#2135]
Is this a typo?
https://github.com/pyscf/pyscf/blob/d3f622d46eef5d9b8702fa6f4577babfb6c2ccfe/pyscf/mp/__init__.py#L57-L58
should be
```
if not istype('UHF'):
```

**Comment by verena-neufeld** [comment]
I also think it is a typo. This was introduced in fbd9220aecc53a2997342881d8376ce03b6b2cf8 where 
`-    if isinstance(mf, newton_ah._CIAH_SOSCF) or not isinstance(mf, scf.uhf.UHF):
+    mf = mf.remove_soscf()
+    if mf.istype('UHF'):`
This change happened.

**Comment by mkrompiec** [comment]
This causes ROHF + MP2 to fail:
```
from pyscf import gto, scf, mp
mol = gto.M(
    atom = 'O 0 0 0; O 0 0 1.2',  # in Angstrom
    basis = 'ccpvdz',
    spin = 2
)
mf = scf.ROHF(mol).run() 
mymp = mp.MP2(mf).run() 
print('UMP2 total energy = ', mymp.e_tot)
```
```
in _ChemistsERIs._common_init_(self, mp, mo_coeff)
    471     raise RuntimeError('mo_coeff, mo_energy are not initialized.\n'
    472                        'You may need to call mf.kernel() to generate them.')
    474 mo_idx = mp.get_frozen_mask()
--> 475 mo_a = mo_coeff[0][:,mo_idx[0]]
    476 mo_b = mo_coeff[1][:,mo_idx[1]]
    477 self.mo_coeff = (mo_a, mo_b)

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

Calling to_uhf() explicitly: `mymp = mp.MP2(mf.to_uhf()).run()`  works fine

**Comment by mkrompiec** [comment]
btw it seems to show that ROHF followed by MP2 isn't tested by the unit tests
