### ISSUE TITLE
Question about User Guide

### ISSUE THREAD

**Issue by sehun1618** [pyscf/pyscf#2138]
Hello. Thanks for developing such a great program!

I was reading the user guide and had a question.

On the homepage of [A](https://pyscf.org/user/dft.html), it says: 'For hybrid and meta-GGA calculations, PySCF uses the generalized KS formalism [20], in which the so-called generalized KS equations minimize the total energy with respect to the orbitals themselves.'

I was wondering if by meta-GGA you mean a hybrid meta-GGA or a regular meta-GGA like SCAN functional.

**Comment by susilehtola** [comment]
This applies to both meta-GGA functionals in specific, as well as all hybrid functionals including LDAs and GGAs. Both classes involve a generalized KS equation.

**Comment by verena-neufeld** [comment]
Hi @sehun1618 , thanks! Has your question been answered and can this issue be closed?

**Comment by sehun1618** [comment]
> Hi @sehun1618 , thanks! Has your question been answered and can this issue be closed?

Sure. Thanks for your effort.
