### ISSUE TITLE
how to use hf exchange in eval_xc() function?

### ISSUE THREAD

**Issue by moolawooda** [pyscf/pyscf#2142]
I followed the instruction in `24-define_xc_functional.py`：https://github.com/pyscf/pyscf/blob/d3f622d46eef5d9b8702fa6f4577babfb6c2ccfe/examples/dft/24-define_xc_functional.py#L28-L58

It is said that I can add existing functionals to my self-defined functional. However, when I try to add HF exchange to my functional, the energy result seems different from the built-in HF method. Here's an example (to make the question simpler, only HF exchange is used in this example):

```python
from pyscf import dft, gto

mol = gto.M(
    atom="""
    He  0.0   0.0   0.0
    He  1.5   0.0   0.0""",
    basis="6-31g",
    spin=1,
    charge=1,
)


def eval_xc(
    xc_code, rho, spin, relativity=0, deriv=1, omega=None, verbose=None
):
    """involve hf exchange in self-defined functional"""

    hf_xc = dft.libxc.eval_xc(
        "HF,", rho, spin, relativity, deriv, verbose
    )

    ex = hf_xc[0]
    # vrho_a = hf_xc[1][0][:,0].T
    # vrho_b = hf_xc[1][0][:,1].T

    vrho = hf_xc[1][0]
    vgamma = vlapl = vtau = None

    vx = (vrho, vgamma, vlapl, vtau)

    # second and third derivative of energy
    fx = None
    kx = None

    return ex, vx, fx, kx


if __name__ == "__main__":
    mf_1 = dft.UKS(mol)
    mf_1 = mf_1.define_xc_(eval_xc, "LDA")
    mf_1.verbose = 0
    eng_1 = mf_1.kernel()

    mf_2 = dft.UKS(mol)
    mf_2.xc = "hf,"
    mf_2.verbose = 0
    eng_2 = mf_2.kernel()

    print("-" * 80)
    print("Energy from defined xc function: ", eng_1)
    print("Energy from builtin xc function: ", eng_2)
    print("Difference between two energies: ", eng_1 - eng_2)
    print("Unit of energy: Hartree")
```

and the result is:
```
Energy from defined xc function:  -3.4990802886357173
Energy from builtin xc function:  -4.881498881292491
Difference between two energies:  1.3824185926567738
Unit of energy: Hartree
```

Why did this happened? What's the mistake in my code when I try to add a HF exchange in `eval_xc()` function?

**Comment by susilehtola** [comment]
There is no exact exchange in `eval_xc`, as it is not a density functional approximation. To evaluate a hybrid functional, you need to add in exact exhange with `get_jk`.

**Comment by susilehtola** [comment]
See
https://github.com/pyscf/pyscf/blob/d3f622d46eef5d9b8702fa6f4577babfb6c2ccfe/pyscf/dft/rks.py#L106-L117

**Comment by moolawooda** [comment]
Thanks for your reply, I will read these code carefully.
