### ISSUE TITLE
Ordering of ao integrals with more than one component

### ISSUE THREAD

**Issue by xubwa** [pyscf/pyscf#2146]
Hi all,
I'm recently working with the gaunt and breit integral in spherical basis, 'int2e_(breit)_ssp1sps2', for example. These integrals can have 16 components, but the ordering manner of these 16 components is unclear. I'm curious is it documented anywhere? The ordering of integrals with more than one component such as integral of derivatives are also not documented in pyscf.org, but I've found some documentation at libcint's repo. It might be nice to add them to pyscf's documentation as well, I guess, as part of issue #1862 .

**Comment by sunqm** [comment]
https://github.com/sunqm/libcint/blob/8d13863ff481cea27efea5e56c9e4d352cdb8f80/include/cint.h.in#L74 this is the order of the 16 components . I can add documents for them later.

**Comment by xubwa** [comment]
Thanks for explaining.
