### ISSUE TITLE
Question about the ERIs generated by the density-fitting method with and without PBC

### ISSUE THREAD

**Issue by lzwlewis** [pyscf/pyscf#2148]
Dear developers,

I am trying to generate the ERIs with the density-fitting method by following the instructions in [https://github.com/pyscf/pyscf/blob/master/examples/df/10-access_df_integrals.py](url)

```python
import numpy, scipy
from pyscf import ao2mo, lib
from pyscf import df
from pyscf.pbc import df as pbcdf
from pyscf.pbc import gto as pgto

cell = pgto.Cell()
cell.atom='''
C 0.000000000000   0.000000000000   0.000000000000
C 1.685068664391   1.685068664391   1.685068664391
'''
cell.basis = 'ccpvdz'
cell.a = '''
0.000000000, 3.370137329, 3.370137329
3.370137329, 0.000000000, 3.370137329
3.370137329, 3.370137329, 0.000000000'''
cell.unit = 'B'
cell.build()

# ERIs without PBC
mol = cell.to_mol()
auxmol = df.make_auxmol(mol, df.aug_etb(mol, beta=1.2))
nao = mol.nao
naux = auxmol.nao
ints_3c2e = df.incore.aux_e2(mol, auxmol, intor='int3c2e')
ints_2c2e = auxmol.intor('int2c2e')
df_coef = scipy.linalg.solve(ints_2c2e, ints_3c2e.reshape(nao*nao, naux).T)
df_coef = df_coef.reshape(naux, nao, nao)
df_eri = lib.einsum('ijP,Pkl->ijkl', ints_3c2e, df_coef)
mydf = df.GDF(mol)
mydf.auxbasis = df.aug_etb(mol, beta=1.2)
mydf.build()
print(abs(ao2mo.restore(1, mydf.get_ao_eri(), nao) - df_eri).max())

# ERIs with PBC
auxcell = pbcdf.make_auxcell(cell, pbcdf.aug_etb(cell, beta=1.2))
ncellao = cell.nao
ncellaux = auxcell.nao
ints_3c2e_pbc = pbcdf.incore.aux_e2(cell, auxcell, intor='int3c2e').reshape(ncellao, ncellao, ncellaux)
ints_2c2e_pbc = pbcdf.incore.fill_2c2e(cell, auxcell)
df_coef_pbc = scipy.linalg.solve(ints_2c2e_pbc, ints_3c2e_pbc.reshape(ncellao*ncellao, ncellaux).T)
df_coef_pbc = df_coef_pbc.reshape(ncellaux, ncellao, ncellao)
df_eri_pbc = lib.einsum('ijP,Pkl->ijkl', ints_3c2e_pbc, df_coef_pbc)
mydf_pbc = pbcdf.GDF(cell)
mydf_pbc.auxbasis = pbcdf.aug_etb(cell, beta=1.2)
mydf_pbc.build()
print(abs(ao2mo.restore(1, mydf_pbc.get_ao_eri(), ncellao) - df_eri_pbc).max())
```

Here are the outputs:

```python
1.9090577996899727e-08
817.1450320194576
```

The ERIs without PBC generated by 3c2e and 2c2e integrals, give a very small error when being compared to those generated directly by `get_ao_eri()` function, which is consistent with the result in _examples/df/10-access_df_integrals.py_. However, the error for the ERIs with PBC is rather large. I'm wondering what leads to such a difference.

Thank you in advance!

**Comment by fishjojo** [comment]
You may read this paper https://doi.org/10.1063/1.4998644
The real space Coulomb integral in the PBC setting diverges, so one needs to remove the net charges of the density. There are also other tricks applied to accelerate the lattice summation convergence.

**Comment by lzwlewis** [comment]
> You may read this paper https://doi.org/10.1063/1.4998644 The real space Coulomb integral in the PBC setting diverges, so one needs to remove the net charges of the density. There are also other tricks applied to accelerate the lattice summation convergence.

Thanks for your explanation! It seems that `aux_e2` function in the PBC module does not remove the divergent G=0 contribution, and I need to remove this divergence manually.
