### ISSUE TITLE
DFT calculation with quasi-Newton method (BFGS)

### ISSUE THREAD

**Issue by DeepDevIA** [pyscf/pyscf#2158]
Hi every one
In pyscf doc i havnt found how to perform a DFT calculation using  a quasi-Newton method (BFGS) 
is there any simple to do this please?
thanks

**Comment by hebrewsnabla** [comment]
Quasi-newton for orbital optimization (i.e. SCF) or geometry optimization?

**Comment by DeepDevIA** [comment]
thank"s [hebrewsnabla](https://github.com/hebrewsnabla) for replay 
Quasi-newton for orbital optimization

**Comment by hebrewsnabla** [comment]
See https://github.com/pyscf/pyscf/blob/master/examples/scf/22-newton.py . There's no BFGS but a more precise Newton method.

**Comment by DeepDevIA** [comment]
thanks I will try this method

**Comment by DeepDevIA** [comment]
[hebrewsnabla](https://github.com/hebrewsnabla)  have you an example for geomOpt using BFGS please ?

**Comment by tberkel** [comment]
PySCF doesn’t have a BFGS option for orbital optimization. It has the
Newton method that was already linked, and DIIS, which is quasi-newton. In
principle, you could try to make your own version by using the scipy
minimize function, but there are no examples of this to share.

**Comment by tberkel** [comment]
For geometry optimization, PySCF only provides gradients and hessians, and
the optimization is performed by interfacing to other packages, like
geometric or pyberny.

**Comment by DeepDevIA** [comment]
I got it
Thanks a lot for the clarifications.
