### ISSUE TITLE
How do the variables in the G0W0 program correspond with the paper?

### ISSUE THREAD

**Issue by simonganne01** [pyscf/pyscf#2159]
I am adapting the G0W0 code to wite code for my masters thesis. But I am confused by the implementation. The names of the parameters in the paper (See T. Zhu and G.K.-L. Chan, arxiv:2007.03148 (2020)) do not match with those in the program. What does Lij for example mean? And what does the sr-loop do?

**Comment by tberkel** [comment]
Lpq are the density fitting tensors with shape (naux, nmo, nmo). And you can think of sr_loop as the function that calculates these tensors for systems with k-points.

**Comment by simonganne01** [comment]
ok and how do they relate to the variables in the paper?

**Comment by simonganne01** [comment]
For example is it true that in order to calculate four center integrals I just do this?:

`Vmn_a = einsum('Pmn, Pop -> mnop', (Lij[0,km][:,orbs,:])[:,:,orbs].conj(), (Lij[0, kp][:,orbs,:])[:,:,orbs])`

**Comment by chillenb** [comment]
Not sure about _conc_mos, and I'm not familiar with the periodic code yet. Bearing that in mind,
`pyscf.ao2mo._ao2mo.nr_e2` ([here](https://github.com/pyscf/pyscf/blob/d57f1d6c89c723e11a7f0933380a6139ba372554/pyscf/ao2mo/_ao2mo.py#L154)) transforms the 3-index ERIs `(P | pq)` from AO to MO basis: `L = einsum('Ppq, pi, qj -> Pij', cderi, mo_coeff, mo_coeff)`

In that paper, L and its analogues for k-point calculations are written as v.

The four-center MO-eris are `einsum('Pij, Pkl->ijkl', L, L)`
[reference](http://vergil.chemistry.gatech.edu/notes/df.pdf). See this in action [here](https://github.com/pyscf/pyscf/blob/d57f1d6c89c723e11a7f0933380a6139ba372554/pyscf/cc/dfccsd.py#L164) where it's used in density fitting CCSD

**Comment by simonganne01** [comment]
> Not sure about _conc_mos, and I'm not familiar with the periodic code yet. Bearing that in mind, and leaving aside symmetry, `pyscf.ao2mo._ao2mo.nr_e2` ([here](https://github.com/pyscf/pyscf/blob/d57f1d6c89c723e11a7f0933380a6139ba372554/pyscf/ao2mo/_ao2mo.py#L154)) transforms the 3-index ERIs `(P | pq)` from AO to MO basis: `L = einsum('Ppq, pi, qj -> Pij', cderi, mo_coeff, mo_coeff)`
> 
> In that paper, L and its analogues for k-point calculations are written as v.
> 
> The four-center MO-eris are `einsum('Pij, Pkl->ijkl', L, L)` [reference](http://vergil.chemistry.gatech.edu/notes/df.pdf). See this in action [here](https://github.com/pyscf/pyscf/blob/d57f1d6c89c723e11a7f0933380a6139ba372554/pyscf/cc/dfccsd.py#L164) where it's used in density fitting CCSD

shouldn't one of the L's be conjugate? for the four center eris?

**Comment by simonganne01** [comment]
And do you know what the _conc_mos function does? @tberkel

**Comment by simonganne01** [comment]
And can I calculate the eris between different spin states in the unrestricted case in an analogous way?

**Comment by tberkel** [comment]
The `_conc_mos` function just concatenates two molecular orbital coefficient matrices to yield all MO pairs, and it does some symmetry handling in case the MO matrices are identical, such that there are only N*(N+1)/2 unique pairs. 

For unrestricted calculations in the periodic GW context, you can look at the unrestricted periodic GW code [here](https://github.com/pyscf/pyscf/blob/master/pyscf/pbc/gw/kugw_ac.py).

**Comment by simonganne01** [comment]
Yes, I know there is an unrestricted version but they don't calculate the eri between orbitals with a different spin (<nsigma, n'sigma'|1/r|msigma, m'sigma'>. How can I do that. do I just give the mo_coeff of the different spins in the conc_mos function? and calculate the Lij the same as in the other cases?

**Comment by tberkel** [comment]
The unrestricted code *does* calculate ERIs between orbitals with different spin. The `a` or `b` labels (and `0` or `1` indices) correspond to the different spins. For example, see the code around [this line](https://github.com/pyscf/pyscf/blob/master/pyscf/pbc/gw/kugw_ac.py#L307).

**Comment by simonganne01** [comment]
yes but they treat them seperately, they calculate eris for spin up and they calculate eris for spin down but not 4 center eris where the two spins are combined. Orr do I understand the code wrong?

**Comment by tberkel** [comment]
Maybe it's better to tell us what you want to do. Is it GW-related or do you just want periodic ERIs? In the GW approximation, the self-energy for each spin only depends on exchange-like integrals which is why they have the spin structure you're describing, i.e.,

$$
\Sigma_{p\sigma,q\sigma} \sim \sum_i (p\sigma, i | i, q\sigma)
$$

But note that within GW, the response function function has contributions from both spins (see [here](https://github.com/pyscf/pyscf/blob/master/pyscf/pbc/gw/kugw_ac.py#L200)), so that there is implicitly coupling between different spin sectors when the screened exchange integrals are compiled. These integrals just have to "begin" and "end" with the same spin.

**Comment by simonganne01** [comment]
It is GW related but I want to calculate 4center eris for wannier orbitals. I have a matrix to do the transformation to wannier but this is a summation over different kpoints. The results this far are wrong. I think it is because i use Lij's at different kpoints and for diferent energies without taking the metric into account. But  dont know how to take into account the metric. certainly not for different kpoints

**Comment by tberkel** [comment]
Integral transformations (including AO to MO) rarely need to worry about the metric. Moreover, the Wannier transformation is unitary, so you can transform integrals from MO to Wannier orbitals straightforwardly,

$$
(w_1 k_1, w_2 k_2 | w_3 k_3, w_4 k_4) = \sum_{pqrs} U_{pw_1}^*(k_1) U_{qw_2}(k_2) U_{rw_3}(k_3) U_{sw_4}(k_4)
(pk_1, q k_2 | r k_3, s k_4)
$$

where $U_{pw}(k)$ is the matrix of coefficients of Wannier orbitals $w$ in the basis of MOs $p$ with k-point $k$.

**Comment by simonganne01** [comment]
Do I need to add something when all momenta are different (ofcourse with taking into account the momentum conservation)? because my results are still wrong.

**Comment by tberkel** [comment]
When all k-points are different, the DF expression for ERIs is Eq (14) in the paper you referenced. If you don't care about the implementation details, see `examples/pbc/30-mo_integrals.py` to get the ERIs at arbitrary k-points.
