### ISSUE TITLE
Can I force the block_loop function to always give me the entire grid at once?

### ISSUE THREAD

**Issue by KirillKulaev** [pyscf/pyscf#2160]
Hello, I am writing a code that works with rho inside the function `pyscf.grad.uks` and I would like to know how inside this function to make block_loop give me the whole grid and its weights at once instead of dividing it into parts, because my code works well only when I have the whole electron density and its weights at once. So what parameters can I enter for this or is it better to replace block_loop with something else in this part of the code? 
I am about this part of code `pyscf.grad.uks.get_vxc`:

```
  elif xctype == 'GGA':
        ao_deriv = 2
        for ao, mask, weight, coords \
                in ni.block_loop(mol, grids, nao, ao_deriv, max_memory):
            rho_a = make_rho(0, ao[:4], mask, xctype)
            rho_b = make_rho(1, ao[:4], mask, xctype)
            vxc = ni.eval_xc_eff(xc_code, (rho_a,rho_b), 1, xctype=xctype)[1]
            wv = weight * vxc
            wv[:,0] *= .5
            rks_grad._gga_grad_sum_(vmat[0], mol, ao, wv[0], mask, ao_loc)
            rks_grad._gga_grad_sum_(vmat[1], mol, ao, wv[1], mask, ao_loc)

```

Thank you very much for the answers!

**Comment by fishjojo** [comment]
The grid point coordinates and weights can be obtained as follows
```
from pyscf.dft import rks
ks = rks.RKS(mol)
ks.initialize_grids(mol, dm=None)
coords = ks.grids.coords
weights = ks.grids.weights
```

**Comment by xubwa** [comment]
It should be done by setting a really large max memory so that it fits into one block loop.

**Comment by fishjojo** [comment]
`mask = ks.grids.make_mask()`
Note that `block_loop` sets an upper bound for the block size of `1200*56` internally even with enough memory.
