### ISSUE TITLE
CCSD k-points mesh 

### ISSUE THREAD

**Issue by arshamsam** [pyscf/pyscf#217]
Hi, 

I've been looking at CCSD energy as function of k-mesh size for a simple periodic system which contains 4 hydrogen atoms located in a tetragonal cell with a=b=2.29366 and c=5.8438888. 
The CCSD calculations only converged for some k-meshes, including (1,1,1), (3,3,2), and (3,3,3). 
For k-meshes of (2,2,1), (2,2,2), (4,4,2), (4,4,4), and (4,4,3) it stops due to: 
"AssertionError: Must have occupied orbitals!"

Here is the input:
================================
import numpy as np
from pyscf import scf
from pyscf import cc
from pyscf import qmmm
from pyscf.pbc import df as pdf
from pyscf.pbc import scf as pbchf
from pyscf.pbc import gto as  pbcgto
from pyscf.pbc import tools 
from pyscf.pbc import cc as pbcc

cell = pbcgto.Cell()
cell.atom = [['H', (0.000000000,   0.000000000 , 0.000000000 )],
            ['H', (0.000000000 ,  0.500000000  , 0.250000000)],
            ['H', (0.500000000 ,  0.500000000 ,  0.500000000)],
            ['H',(0.500000000  , 0.000000000 ,  0.750000000)]]
cell.unit = 'Bohr'
cell.a = [[2.293668126,0.,0.],[0.,2.293668126,0],[0,0,5.843888814]]
#cell.mesh = [14,14,64]
#cell.ke_cutoff = 300
cell.verbose = 7
#cell.precision = 5e-8
cell.spin = 0
cell.charge = 0
#cell.basis = 'dzp'
cell.basis = 'gth-szv'
cell.pseudo = 'gth-pade'
cell.max_memory = 50000
for i in range(len(cell.atom)):
    cell.atom[i][1] = tuple(np.array(cell.atom[i][1][0])*np.array(cell.a[0]) + 
            np.array(cell.atom[i][1][1])*np.array(cell.a[1]) + 
            np.array(cell.atom[i][1][2])*np.array(cell.a[2]))
cell.build()
#supcell = tools.super_cell(cell,[2,1,1])
#supcell.build()

#mf = pbchf.KRHF(cell).density_fit(auxbasis='weigend')
kmf = pbchf.KRHF(cell).density_fit(auxbasis='weigend')
#mf.with_df.mesh = [10,10,20]
kmf.kpts = cell.make_kpts([2,2,1])
e = kmf.kernel()

dmR=np.einsum("kij->ij",kmf.make_rdm1())

mycc = pbcc.KCCSD(kmf)
mycc.kernel()
print("KRCCSD energy (per unit cell) = ", mycc.e_tot)
===========================================

would you let me know your opinion?

Best, 
Sam

**Comment by gkc1000** [comment]
This assertion is flagged if there are no occupied orbitals at one of the k-points. In principle this could occur in a metal. @jdmcclain47 can you take a look?

**Comment by jdmcclain47** [comment]
@gkc1000 my guess is something to do with metallic behavior. I will take a look into this.

**Comment by jdmcclain47** [comment]
Just a quick update - the problem is related to the metallicity of the system.  One can reproduce the problems above with a minimal example setting

`kmf.kpts = cell.make_kpts([2,1,1], scaled_center=[0.5,0.5,0.0])`

For these two k-points, one has zero occupied orbitals for one k-point and zero virtual orbitals for the other.  Right now post hartree fock methods are built on the assumption that there is at least one occupied orbital and one virtual orbital per k-point.  I'll work on changing this.

**Comment by arshamsam** [comment]
Yes, the system is a metal. That's why having an estimation of energy gain due to a denser k-mesh would be useful.
