### ISSUE TITLE
freeze certain atom's coordinates during optimization

### ISSUE THREAD

**Issue by Haskiy** [pyscf/pyscf#2176]
Is there any method in pyscf to freeze certain atom's coordinates during optimization?

**Comment by hebrewsnabla** [comment]
duplicate with #1666.

**Comment by Haskiy** [comment]
It can not work. I tried to do that by modified dump_mol_geometry() fucntion in geomopt.addons.py, where I added "new_coords[:2] = old_coords[:2]" between "new_coords = numpy.asarray(new_coords)" and "dx = new_coords - old_coords". At the same time, I set the gradients at the first two atoms zero.

**Comment by Haskiy** [comment]
However, I think it isn't theoretically rigorous.

**Comment by hebrewsnabla** [comment]
What did you mean by "it cannot work"? I believe the constraints param works.

**Comment by Haskiy** [comment]
I means that the coordinates of the frozen atoms still changes during optimization.

**Comment by hebrewsnabla** [comment]
Here's an example in which we can see the distance between atom 1 and 2 unchanged.

```
mol = gto.M(atom='''
C       1.1879  -0.3829 0.0000
C       0.0000  0.5526  0.0000
O       -1.1867 -0.2472 0.0000
H       -1.9237 0.3850  0.0000
H       2.0985  0.2306  0.0000
H       1.1184  -1.0093 0.8869
H       1.1184  -1.0093 -0.8869
H       -0.0227 1.1812  0.8852
H       -0.0227 1.1812  -0.8852
            ''', basis='3-21g'
, verbose=4).build()

print(gto.inter_distance(mol))

mf = mol.RKS(xc='pbe,pbe')
params = {"constraints": "cons.txt"} # freeze 1 2
mol1 = optimize(mf, **params)

print(gto.inter_distance(mol1))
```

**Comment by hebrewsnabla** [comment]
> The third numbers in [[0. 2.85734255 4.49466488 ...] and [[0. 2.85734255 4.48597837 ...] are different.

Yeah, because I freezed "1 2" in cons.txt so only the distance between atom 1 and 2 is fixed.

**Comment by Haskiy** [comment]
I write a cons.txt file as

$freeze
distance 1,2

, and I use that like this：

with open('cons.txt','r') as f:
    cons = f.read()
params = {"constraints": cons}

It can not freeze the two atoms.

**Comment by hebrewsnabla** [comment]
By "freeze the two atoms" you mean freeze the distance between them or freeze all of their cartesian coordinates?

**Comment by Haskiy** [comment]
yes

**Comment by hebrewsnabla** [comment]
The script I provided above should work. It should be `distance 1 2` instead of `distance 1,2` in txt I think.

**Comment by Haskiy** [comment]
There is something wrong still. The calculation results 
![image](https://github.com/pyscf/pyscf/assets/86696701/a12723f2-642a-4903-ac8e-d4a607b754e9)

**Comment by hebrewsnabla** [comment]
probably the `cons` can only be a filename instead of file content.

**Comment by Haskiy** [comment]
I tried that and the result was the same as the picture above. Can you repeat that example?

**Comment by Haskiy** [comment]
Thanks for your help. I repeat the reasonable result. The different optimizers,  "from pyscf.geomopt.geometric_solver import optimize" and "from pyscf.geomopt.berny_solver import optimize", were used by you and me, respectively. The geomopt.berny_solver may not surpport this function for the optimization at the constrains.

**Comment by Haskiy** [comment]
And the geometric_solver supports that.

**Comment by verena-neufeld** [comment]
Hi @Haskiy , thanks for your question. Has it been resolved?

**Comment by Haskiy** [comment]
Yes. However, this can be done by geometric_solver as hebrewsnabla said.
