### ISSUE TITLE
How to obtain 2-electron integrals with PySCF

### ISSUE THREAD

**Issue by neutronengas** [pyscf/pyscf#2179]
As far as my understanding goes I can calculate the 4-dimensional tensor eri_{pq,rs} via the command mol.intor("int2e"), which is related to the 2-electron integrals (pq|rs) via the formula given in the attached screenshot. I was wondering whether there is a command to directly calculate the terms (pq|rs)? 
<img width="608" alt="Bildschirmfoto 2024-04-17 um 11 12 12" src="https://github.com/pyscf/pyscf/assets/40839256/ea25a925-3131-4199-9b19-0136d0225e89">

**Comment by tberkel** [comment]
No, `mol.intor('int2e')` is just $(pq|rs)$.

**Comment by neutronengas** [comment]
Thanks for the reply! But how can I reconcile that with the above equation $eri_{pr, qs} = (pq|rs) - (.5 / Nelec) [\sum_q (pq|rs) + \sum_p (pq|rp)]$?

**Comment by tberkel** [comment]
I don't know where you got that equation from, but that is not the usual meaning of the ERIs in PySCF (or anywhere else, as far as I know). In other words, your h2e expression is not the common way to write the two-body part of the Hamiltonian.

**Comment by neutronengas** [comment]
I obtained it from the PySCF docs: https://pyscf.org/pyscf_api_docs/pyscf.fci.html#pyscf.fci.direct_nosym.contract_2e

and validated it by calculating the Hartree-Fock energy with the PySCF-calculated 1- and 2-RDMs

**Comment by tberkel** [comment]
Unless you're really interested in full CI, you can ignore that (the language is a warning that the expected argument to this FCI function is not the "usual" ERI, which would be (pq|rs), but rather a slightly different tensor). The quantity returned by `mol.intor('int2e')` is just the "usual" ERI tensor $(pq|rs)$ where the indices are AOs (not MOs).

**Comment by neutronengas** [comment]
I see, thank you!
