### ISSUE TITLE
Spin-non-traced 2RDM?

### ISSUE THREAD

**Issue by neutronengas** [pyscf/pyscf#2180]
Is there any way to obtain the 2RDM where the spin is not traced out?

**Comment by tberkel** [comment]
At what level of theory? For FCI, yes, see `examples/fci/14-density_matrix.py`.

**Comment by neutronengas** [comment]
I actually would need it for Hartree-Fock level. I am trying to reconstruct it but so far without success. I was wondering what the formula is by which the HF 2-RDM is calculated? Is it $dm2 = <p^+ q^+ r s>?

**Comment by bganoe92** [comment]
The independent subblocks of the UHF spin-untraced 1- and 2-RDM may be obtained with:
`mf = scf.UHF(mol)`
`mf.kernel()`
`(dm1aa, dm1bb) = mf.make_rdm1()`
`(dm2aaaa, dm2abab, dm2bbbb) = mf.make_rdm2()`
from which the full 2-RDM may be constructed. Like the FCI example, the convention is dm2[p,q,r,s] = <p^+ q r^+ s>.

**Comment by verena-neufeld** [comment]
Hi @neutronengas , thanks for your question. Has it been resolved?
