### ISSUE TITLE
Error with multigrid and hybrid functionals

### ISSUE THREAD

**Issue by lkwagner** [pyscf/pyscf#219]
The attached calculation errors with the following error.

Thanks!

Lucas

/share/apps/miniconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "srcuo2_multigrid.py", line 178, in <module>
    print('E =',m.kernel())
  File "/home/lkwagner/pyscf/pyscf/scf/hf.py", line 1473, in kernel
    return self.scf(dm0, **kwargs)
  File "/home/lkwagner/pyscf/pyscf/scf/hf.py", line 1467, in scf
    conv_check=self.conv_check, **kwargs)
  File "/home/lkwagner/pyscf/pyscf/scf/hf.py", line 143, in kernel
    vhf = mf.get_veff(mol, dm)
  File "/home/lkwagner/pyscf/pyscf/pbc/dft/kuks.py", line 86, in get_veff
    vxc += vj - vk * hyb
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

import sys
import pyscf
import numpy
from pyscf.pbc import gto,scf
from pyscf.pbc.scf import KRHF as RHF
from pyscf.pbc.scf import KUHF as UHF
from pyscf.pbc.dft import KRKS as RKS
from pyscf.pbc.dft import KUKS as UKS
from pyscf.pbc.dft import multigrid
basis={
'Sr':pyscf.gto.basis.parse('''
Sr s
  0.2 0.688519195726
  0.4 -1.12060079327
  0.8 0.667777052063
  1.6 -0.264303359332
  3.2 0.107893172552
  6.4 -0.0467092058199
  12.8 0.0190367620017
  25.6 -0.00656798101781
  51.2 0.0015551383896
  102.4 -0.000192791210535
Sr p
  0.2 0.316372269218
  0.4 -0.465851775006
  0.8 0.226987549209
  1.6 -0.066094426312
  3.2 0.0162954710475
  6.4 -0.00365084618826
  12.8 0.000705426577439
  25.6 -0.00017848079055
  51.2 3.06496147379e-05
  102.4 -2.71611465382e-06
Sr d
  0.119806 1.000000
Sr f
  0.164546 1.000000
Sr s
0.2 1.0
Sr s
0.6000000000000001 1.0
Sr p
0.2 1.0
Sr p
0.6000000000000001 1.0
  '''),
'O':pyscf.gto.basis.parse('''
O s
  0.2 0.215448374976
  0.4 0.351884869096
  0.8 0.395141155066
  1.6 0.179458356356
  3.2 -0.0432052834993
  6.4 -0.105221770065
  12.8 0.0197823639914
  25.6 -0.00197386728468
  51.2 0.000387842127399
  102.4 -5.57569955803e-05
O p
  0.2 0.283073445696
  0.4 0.205849797904
  0.8 0.303195415412
  1.6 0.218836382326
  3.2 0.136227390096
  6.4 0.0710086636515
  12.8 0.027416273511
  25.6 0.00161138147606
  51.2 1.51410458608e-05
  102.4 -2.8165242665e-06
O d
  0.669340 1.000000
O f
  1.423104 1.000000
O s
0.2 1.0
O s
0.6000000000000001 1.0
O p 
0.2 1.0
O p
0.6000000000000001 1.0
'''),
'Cu':pyscf.gto.basis.parse('''
Cu s
  0.2 0.0286878866897
  0.4 -0.0364413530365
  0.8 0.358763832032
  1.6 0.474343247928
  3.2 0.498447510592
  6.4 -0.270094109886
  12.8 -0.19207249392
  25.6 0.0629633270568
  51.2 -0.00853551842135
  102.4 0.000812242437275
Cu s
  0.2 2.20172386547
  0.4 -2.28170595665
  0.8 1.46285008448
  1.6 -1.09989311533
  3.2 0.296788655986
  6.4 -0.12153417324
  12.8 0.117898710111
  25.6 -0.0341363112541
  51.2 0.00595066976203
  102.4 -0.00071519088395
Cu p 
  18.594006 0.003652
  14.303011 -0.037076
  5.63142 0.21712
  2.683011 0.440973
  1.258573 0.358723
  0.574084 0.114846
  0.20923 0.007316
Cu d
  0.2 0.279289473482
  0.4 -0.117221524191
  0.8 0.420466340314
  1.6 0.166556512124
  3.2 0.31519384244
  6.4 0.201127125456
  12.8 0.128021225822
  25.6 0.00894474569825
  51.2 -0.00051734713442
  102.4 2.47330807683e-05
Cu f
  1.6923298836 1.00000
Cu s
0.2 1.0
Cu s
0.6000000000000001 1.0
Cu p
0.2 1.0
Cu p
0.6000000000000001 1.0
Cu d
0.2 1.0
Cu d
0.6000000000000001 1.0
'''),
}
mol=gto.M(verbose=4,
atom=''' 
       Sr    0.0000     0.0000     1.7169    
       Sr    0.0000     3.9278     1.7169 
       Sr   -3.9278     0.0000     1.7169  
       Sr   -3.9278     3.9278     1.7169  
       Cu   -1.9639    -1.9639     0.0000  
       Cu   -1.9639     1.9639     0.0000 
       Cu    1.9639    -1.9639     0.0000 
       Cu    1.9639     1.9639     0.0000 
       O    0.0000    -1.9639     0.0000 
      O    0.0000     1.9639     0.0000  
      O   -3.9278    -1.9639     0.0000  
      O   -3.9278     1.9639     0.0000  
      O   -1.9639     0.0000     0.0000  
      O   -1.9639     3.9278     0.0000  
      O    1.9639     0.0000     0.0000  
      O    1.9639     3.9278     0.0000 
''',
a='''
      7.856     0.000     0.000
      0.000     7.856     0.000
      0.000     0.000     3.434 ''',
basis=basis, spin=0, ecp='bfd')
mol.charge=0
kpts=mol.make_kpts([2, 2, 2])
m=UKS(mol,kpts)
m.max_cycle=50
m.xc="pbe0"
import time
start=time.time()
def gettime(envs):
  endt=time.time()
  print("Total elapsed time",endt-start)
m.callback=gettime
m.with_df=multigrid.MultiGridFFTDF(mol, kpts)

print('E =',m.kernel())
end=time.time()
print("time ",end-start)

**Comment by sunqm** [comment]
Multigrid algorithm does not support HF exchange. The exchange part is computed by the FFT exchange code. It will be quite slow.

**Comment by lkwagner** [comment]
OK. I also get an error when doing this calculation with Gaussian density fitting; see other issue.
