### ISSUE TITLE
Question about Becke grid partition code

### ISSUE THREAD

**Issue by UpanJC** [pyscf/pyscf#2190]
I've been looking through source code for grid generation and checking the reference articles, yet I cannot find why the following code from pyscf.dft.gen_grid is the way it is

```python
def gen_grid_partition(coords):
            ngrids = coords.shape[0]
            grid_dist = numpy.empty((mol.natm,ngrids))
            for ia in range(mol.natm):
                dc = coords - atm_coords[ia]
                grid_dist[ia] = numpy.sqrt(numpy.einsum('ij,ij->i',dc,dc))
            pbecke = numpy.ones((mol.natm,ngrids))
            for i in range(mol.natm):
                for j in range(i):
                    g = 1/atm_dist[i,j] * (grid_dist[i]-grid_dist[j])
                    if f_radii_adjust is not None:
                        g = f_radii_adjust(i, j, g)
                    g = becke_scheme(g)
                    pbecke[i] *= .5 * (1-g)
                    pbecke[j] *= .5 * (1+g)
            return pbecke
``` 
Why is pbecke[j] multiplied by 0.5*(1+g)?

Don't know where else I can ask this if its not appropriate for here.

**Comment by fishjojo** [comment]
I think it's because the i, j loop is lower triangular, and when updating p_j, there is a minus sign of g.

**Comment by susilehtola** [comment]
Yes, the routine builds weights for the atom pair `i` and `j`; this is equation (21) in Becke's 1988 paper.

**Comment by verena-neufeld** [comment]
Hi @UpanJC , thanks for your question. Has it been answered?
