### ISSUE TITLE
UCCSD(T) density matirx example

### ISSUE THREAD

**Issue by sehun1618** [pyscf/pyscf#2191]
I'm trying to get the density matrix of UCCSD(T) by following example code pycsf/examples/cc/01-density_matrix.py

It works in RCCSD(T), but not in UCCSD(T).

The error occurred in 

Traceback (most recent call last):
  File "/home/ksh/gmtkn55_ccsd/SIE4x4.py", line 202, in <module>
    conv, l1, l2 = ccsd_t_lambda.kernel(mycc, eris, mycc.t1, mycc.t2)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksh/miniconda3/lib/python3.11/site-packages/pyscf/cc/ccsd_t_lambda_slow.py", line 36, in kernel
    return ccsd_lambda.kernel(mycc, eris, t1, t2, l1, l2, max_cycle, tol,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksh/miniconda3/lib/python3.11/site-packages/pyscf/cc/ccsd_lambda.py", line 51, in kernel
    imds = fintermediates(mycc, t1, t2, eris)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksh/miniconda3/lib/python3.11/site-packages/pyscf/cc/ccsd_t_lambda_slow.py", line 40, in make_intermediates
    imds = ccsd_lambda.make_intermediates(mycc, t1, t2, eris)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ksh/miniconda3/lib/python3.11/site-packages/pyscf/cc/ccsd_lambda.py", line 82, in make_intermediates
    nocc, nvir = t1.shape
                 ^^^^^^^^
AttributeError: 'tuple' object has no attribute 'shape'

How can I get UCCSD(T) density?

**Comment by tberkel** [comment]
You have to import the unrestricted versions of the `lambda` and `rdm` modules:
```python
from pyscf.cc import uccsd_t_lambda, uccsd_t_rdm
eris = mycc.ao2mo()
conv, l1, l2 = uccsd_t_lambda.kernel(mycc, eris, mycc.t1, mycc.t2)
dm1 = uccsd_t_rdm.make_rdm1(mycc, mycc.t1, mycc.t2, l1, l2, eris=eris)
dm2 = uccsd_t_rdm.make_rdm2(mycc, mycc.t1, mycc.t2, l1, l2, eris=eris)
```

**Comment by sehun1618** [comment]
> You have to import the unrestricted versions of the `lambda` and `rdm` modules:
> 
> ```python
> from pyscf.cc import uccsd_t_lambda, uccsd_t_rdm
> eris = mycc.ao2mo()
> conv, l1, l2 = uccsd_t_lambda.kernel(mycc, eris, mycc.t1, mycc.t2)
> dm1 = uccsd_t_rdm.make_rdm1(mycc, mycc.t1, mycc.t2, l1, l2, eris=eris)
> dm2 = uccsd_t_rdm.make_rdm2(mycc, mycc.t1, mycc.t2, l1, l2, eris=eris)
> ```

Thank you so much!
