### ISSUE TITLE
CC density matrices in AO and MO 

### ISSUE THREAD

**Issue by d0d00** [pyscf/pyscf#2193]
Hello everyone,

I found several issues around this topic but couldn't work out my problem.
I am looking for a way to generate CCSD and CCSD(T) density profiles by evaluating density matrices on a grid. However, due to big discrepancies in the resulting density profiles I dug into it.
To keep it simple, I only mention the CCSD calculations of the density matrices here:
The 1-particle density matrices seem to **integrate to the number of electrons** in the system **only if they're in MO basis.** In AO basis, I can't reproduce the result. Shouldn't both representations be normalised or am I missing something?

I added the code to reproduce my calculations. Note, I tried the built-in transformation (ao_repr=True) and a manual transformation. They agree but don't match the number of electrons in the system (4) as the modm does...

`import numpy as np
from pyscf import gto, scf, cc. # pyscf version 2.5.0

mol = gto.M(
    atom = 'Li 0.0000 0.0000 0.0000; H 0.0000 0.0000 3.0139',
    basis = 'pc-4',
    spin=0,
    charge=0)

mf = scf.HF(mol).run()

mycc = cc.CCSD(mf).run()

modm = mycc.make_rdm1()

aodm = mycc.make_rdm1(ao_repr=True)
manual_aodm = np.dot(mf.mo_coeff, np.dot(modm, mf.mo_coeff.T))

print("Trace of modm (MO basis):", np.trace(modm))
print("Trace of aodm (AO basis, built-in):", np.trace(aodm))
print("Trace of aodm (AO basis, manual):", np.trace(manual_aodm))`

**Comment by tberkel** [comment]
The AO basis is not orthonormal. In the AO basis, the number of electrons is given by Tr(PS), where S is the overlap matrix.

**Comment by verena-neufeld** [comment]
Hi @d0d00 , thanks for your question. Has it been answered?

**Comment by sunqm** [comment]
Feel free to reopen
