### ISSUE TITLE
Support for Calculating Surface Area Using Implicit Solvation Models in PySCF

### ISSUE THREAD

**Issue by ORCAaAaA-ui** [pyscf/pyscf#2197]
Hello,

I am currently conducting DFT calculations using ORCA, utilizing implicit solvation models such as CPCM and SMD. In ORCA, when using these solvation models, the .cpcm file provides values for surface points' charges and areas.

I am interested in performing similar calculations using PySCF and **would like to know if PySCF supports these functionalities**. **Specifically, I am looking for information on whether it's possible to calculate and extract surface area values using implicit solvation models in PySCF.**

Below is an example of what the .cpcm file looks like in ORCA:

![image](https://github.com/pyscf/pyscf/assets/112508198/c8adfbd1-a897-42f1-80eb-686c0f730e41)

Any guidance on how to set up and use such features in PySCF would be greatly appreciated.

Thank you!

**Comment by wxj6000** [comment]
The question is answered in https://github.com/pyscf/gpu4pyscf/issues/144. Please note there is a bug in PCM models. We are fixing it in https://github.com/pyscf/pyscf/pull/2173. This bug does not appear in GPU4PySCF.

**Comment by ORCAaAaA-ui** [comment]
@wxj6000 Thank you so much.
