### ISSUE TITLE
Custom hybrid functional using define_xc()

### ISSUE THREAD

**Issue by KirillKulaev** [pyscf/pyscf#2211]
Hello, I would like to define a hybrid functional for DFT with custom eval_xc() using define_xc() and also use HF exchange energy in it. What is the best way for me to do this? Can I make a range separated functional using custom xc functional defined via eval_xc()? Is there a possible way to get after calculation with hybrid functional a separate value of HF exchange energy also SR and LR energies after calculation with RSH functional?

**Comment by sunqm** [comment]
Hybrid ans RSH functionals can be customized through the `define_xc` function , see https://github.com/pyscf/pyscf/blob/7d94887d2ca817287226c51371845037f4469325/pyscf/dft/libxc.py#L1720 .
The example `examples/dft/24-define_xc_functional.py` shows how to customize RSH part. I believe it's not difficult to enable HF part following that example.

HF exchange, or SR, LR values are not stored in the program. You have to create a function to manually compute them. Alternatively, you can follow the `get_veff` function in dft/rks.py, adding more information in its return, a "tagged" numpy array. Then you can all mf.get_veff function to compute the vxc matrix, and access the required energies there.
