### ISSUE TITLE
Evaluate (|r dot nabla|) with pyscf.gto.moleintor.getints

### ISSUE THREAD

**Issue by suyupilemao** [pyscf/pyscf#2213]
I am evaluating the matrix (i| r dot nabla|j), where |i) stands for the i-th atomic orbital, r is the coordinate vector, and nabla is the corresponding gradient operation. In pyscf, I sort to the pyscf.gto.moleintor.getints module. However, I do not find the function to directly evaluate the item I want. 

So I am writing to ask how to customize the function to achieve my goal.

**Comment by sunqm** [comment]
Suppose the operator r has a common origin, you can consider to use `mol.intor('int1e_irp')` to get an array of shape (9, N, N). Then summing over the [0, 4, 8] th components, you can get  (i| r dot nabla|j) .

If you prefer to add new integral functions for a direct evaluation of this integral, it involves several steps. In short,

1. download https://github.com/sunqm/libcint and edit the src/scripts/auto_intor.cl file.
2. Install a Lisp interpreter, such as CLISP on ubuntu, and execute the lisp script there.
3. compile the integral library
4. Compile pyscf according to the offline installation instruction https://pyscf.org/install.html#installation-without-network
