### ISSUE TITLE
Energy of AVAS MOs

### ISSUE THREAD

**Issue by rw1511** [pyscf/pyscf#2220]
Hi PySCF team, I am trying to generate AVAS orbitals in the following way:

mf = scf.RHF(mol)
mf.chkfile = 'RHF.chk'
mf.kernel()

ao_labels = ['C 2pz', 'B 2pz', 'N 2pz']
norb, ne_act, orbs = avas.avas(mf, ao_labels, canonicalize=False)

From the RHF object, I can get the energy of MOs using mf.mo_energy ; I am wondering how to get the energy of AVAS MOs as the orbitals and their numbering must have changed? Thank you!

**Comment by tberkel** [comment]
Any orbitals other than the canonical ones do not have an “energy”. You
could use the diagonal elements of the Fock operator in the AVAS basis, but
the matrix has off-diagonal elements reflecting the coupling between
localized orbitals. If you want this, then you can just transform the
diagonal matrix of MO energies using the change-of-basis matrix from
canonical MOs to AVAS orbitals.

**Comment by rw1511** [comment]
Thank you! This solves the issue I am having.

**Comment by verena-neufeld** [comment]
Hi @rw1511 , thanks for your comments. It seems like this issue can be closed?

**Comment by rw1511** [comment]
Thank you @verena-neufeld, it can be closed now.
