### ISSUE TITLE
How to save the molecular structure optimized with pyscf？

### ISSUE THREAD

**Issue by LijieZhong** [pyscf/pyscf#2227]
How to save the molecular structure optimized with Pyscf, such as XYZ file

**Comment by fishjojo** [comment]
Please see https://github.com/pyscf/pyscf/blob/master/examples/geomopt/01-geomeTRIC.py
`print(mol_eq.atom_coords())` should give you the coordinates.

**Comment by LijieZhong** [comment]
> Please see https://github.com/pyscf/pyscf/blob/master/examples/geomopt/01-geomeTRIC.py `print(mol_eq.atom_coords())` should give you the coordinates.
Thanks for your reply, I'll try the function

**Comment by sunqm** [comment]
There is also the `mol.tofile()` method https://github.com/pyscf/pyscf/blob/a64f740c978eb6cc10eec53f0c50098fc4f543b2/pyscf/gto/mole.py#L2096

**Comment by aris1978** [comment]
Is there an example of writing cube files in addition to writing the coordinate file?  I tried to append cubegen.orbital(mol, 'file.cub', mf.mo_coeff[:2]), but I get the error "'NoneType' object is not subscriptable".
