### ISSUE TITLE
Parallel Processing in Multicollinear SCF

### ISSUE THREAD

**Issue by Shunsum** [pyscf/pyscf#2232]
The derivatives of MCfun up to 4th order are needed for my recent work. So I have to build PySCF from source and lift the restriction of $l_\text{xc}$ in `libxc` and `xcfun`. However, it gets frozen every time I perform with the self-compiled PySCF a multicollinear SCF calculation, for which only the first two derivatives of MCfun are necessary.

```python
>>> from pyscf import gto
>>> mol = gto.M(atom='1', basis='sto3g', spin=1)
>>> mf = mol.GKS()
>>> mf.collinear = 'mcol'
>>> mf.kernel()
```

But if I set the number of threads to 1, this will become alive and give the expected output. The problem may lie in the parallel processing in [`eval_xc`](https://github.com/Haskiy/MCfun/blob/c96985a40a7b3117c146dfea67820d3afde62564/mcfun/eval_xc.py#L76-L95) of MCfun. It could be avoided by rolling back PySCF to a previous version such as v2.4.0.

**Comment by sunqm** [comment]
This is an issue in the MCfun library. You can reinstall MCfun after the problem fixed there.

**Comment by verena-neufeld** [comment]
Hi @Shunsum , thanks for your comment! Has it been resolved now?

**Comment by sunqm** [comment]
This needs a new version of mcfun. There is no need for any fixes in pyscf

**Comment by Shunsum** [comment]
@verena-neufeld Yes. It's mcfun to blame. But there has not been a new release of mcfun in PYPI. You need to git clone from [https://github.com/Multi-collinear/MCfun.git](https://github.com/Multi-collinear/MCfun.git)
