### ISSUE TITLE
Convention of ipccsd and eaccsd results

### ISSUE THREAD

**Issue by rhkim79** [pyscf/pyscf#2235]
Hi, I have one quick question about return value convention of eom-ccsd in pyscf. For the following code,
```
eip,cip = mycc.ipccsd(nroots=nroots)
eea,cea = mycc.eaccsd(nroots=nroots)
eee,cee = mycc.eeccsd(nroots=nroots)

```
do the return values mean
eip = E_+ - E_0
eea = E_- - E_0
and
eee : neutral excitation?

Thanks!

**Comment by tberkel** [comment]
Yes to all three!
