### ISSUE TITLE
GDF is running on single thread only.

### ISSUE THREAD

**Issue by JangidBhavnesh** [pyscf/pyscf#2237]
I am running the KRHF with GDF. Although I am using 32 threads, the GDF is running on single thread only.

I got the same problem with RSGDF

Here is my input.

cell = read_poscar("./POSCAR")
cell.spin = 0
cell.basis   = 'gth-szv'
cell.pseudo  = 'gth-pade'
cell.verbose = 4
cell.precision = 1e-10
cell.max_memory = 150000
cell.exxdiv = None
cell.build()

nk = [1, 1, 5]
kpts = cell.make_kpts(nk)

kmf = scf.KRHF(cell, kpts).density_fit()
kmf.max_cycles=1000
kmf.kernel()

After this 

******** <class 'pyscf.pbc.df.rsdf_builder._RSGDFBuilder'> ********
mesh = [51 51 11] (28611 PWs)
ke_cutoff = 9.676669184747139
omega = 0.3683681197608171
exclude_d_aux = True
exclude_dd_block = True
j2c_eig_always = False
has_long_range = True

it is using single thread only.
@sunqm

**Comment by sunqm** [comment]
There are certain parts in GDF that are not parallelized. Do you mind to post the full input . It's hard to tell which problem it might be from your output log.

**Comment by JangidBhavnesh** [comment]
Here is the POSCAR file and complete input.

H  C  N                                 
    1.000000000000000     
    18.5422602515169892    0.4062216704206150    3.5104914667700755
     7.9570659231274279   17.1259895601345278   -0.6327002380977442
     0.6906694384485083   -0.4807817965177863    3.6217361023907690
   H    C    N 
    16    34    10
Direct
  0.3358425441014981  0.0627489775006707  0.4923489471587141
  0.5403540704702657  0.1069563833423322  0.5100551597338686
  0.0841303082721775  0.5676202261441651  0.3774113647011375
  0.0210725343914930  0.3767531499074073  0.6077777146052072
  0.5494646883890033  0.3666316677054634  0.4821041640128807
  0.3336815698465364  0.5807073406313306  0.5177226211510366
  0.6284078836632553  0.4454032562425095  0.4809906420866354
  0.4127533686497281  0.6593970460961913  0.5151849837060163
  0.2720744217115283  0.1799705299499113  0.4830673963280723
  0.1493024829181404  0.3036423648209584  0.4722525700776942
  0.6871445466411639  0.8481742029242274  0.5218676981837862
  0.8106435424185284  0.7247604859130264  0.5311086631587492
  0.8767021568929529  0.4607097553683297  0.6244187264995797
  0.9396128837068716  0.6516280460384760  0.3942721060182653
  0.6238511378243602  0.9643915736867370  0.5075391929504388
  0.4193226490681564  0.9201438210058563  0.4902801030377620
  0.3054435553868722  0.2144821122341499  0.4883743055076104
  0.2647597889925496  0.2960479804635298  0.4836464803082974
  0.1834752041551320  0.3373309955088621  0.4778670541442830
  0.3861179762556236  0.1807771739272360  0.4980328602651753
  0.3904172161944618  0.3017572125182683  0.4954349433910544
  0.3911260727236406  0.4230238747360355  0.4955879035261528
  0.2709907874085453  0.4222950443162440  0.4810712235628274
  0.1495195248718745  0.4189667291091664  0.4798326067465460
  0.4326140178709802  0.0953206333128357  0.5022600016643102
  0.3987028012956988  0.0420747482291942  0.4987653230658293
  0.5146548010148917  0.0653085773998456  0.5041870072131203
  0.0631981614573684  0.4665250197773608  0.4875735857488356
  0.0378944819421350  0.5450866249910350  0.4336781935359839
  0.0042903219625838  0.4365745286076232  0.5551911391719770
  0.4371027789572210  0.4692438828156482  0.4998355013652766
  0.5204358252454128  0.4306898074056741  0.4885921269506105
  0.3980920790418774  0.5519978145109918  0.5106847091202033
  0.5640690856117180  0.4740505052984413  0.4871694960373553
  0.4417564796921890  0.5953370857333146  0.5087866122224518
  0.5251077671112993  0.5567775364483635  0.4972762905168458
  0.5708345177943973  0.6032351652248361  0.5010664725421157
  0.5706331181594061  0.7248925747679220  0.5022946002722908
  0.6904981273779639  0.6048117781877951  0.5167547146060609
  0.5738832780878959  0.8463681859097338  0.5022326997950766
  0.6956057123246551  0.7316123045980011  0.5174668880621586
  0.8113592546950655  0.6090146662285033  0.5208936397624797
  0.6543933224219945  0.8131830239156116  0.5137923402931761
  0.7768705429239708  0.6907116354935904  0.5241878934047020
  0.8976464546828882  0.5617720396587609  0.5138955896864952
  0.9229132722681477  0.4832614445916369  0.5682224526882278
  0.9564868821606533  0.5917785837275921  0.4467638541100059
  0.5271000818770120  0.9317738647280805  0.4979765160507560
  0.5609821089157416  0.9850373505536938  0.5013750704942537
  0.4450160009984379  0.9617966172495828  0.4964240709016207
  0.3142494391309112  0.4626272635715101  0.4817913419761556
  0.4302389196414503  0.3451842928044854  0.5050446795818799
  0.1936765504655157  0.4596770474025021  0.4758464185857953
  0.3083670242870733  0.3395599904003355  0.4859090837293252
  0.4269995999258706  0.2243719792124602  0.5025697336579862
  0.5313308139615883  0.6810435289431508  0.4916914909536650
  0.6477658079106524  0.5639861774123747  0.5145321880566839
  0.5335886271449464  0.8023015896883098  0.4955065234568926
  0.6525989500597107  0.6875820605817784  0.5129575732098780
  0.7677386566262875  0.5678427905263899  0.5226917166477628




** INPUT File **

import os, sys
import numpy as np
import scipy.linalg as la

from pyscf.pbc.lib import chkfile
from pyscf.pbc import scf, gto, df, dft, tools
from libdmet.utils.misc import read_poscar

cell = read_poscar("./POSCAR")
cell.spin = 0
cell.basis   = 'gth-szv'
cell.pseudo  = 'gth-pade'
cell.verbose = 5
cell.max_memory = 150000
cell.exxdiv = None
cell.build()

nk = [2, 2, 10]  
kpts = cell.make_kpts(nk)

kmf = scf.KRHF(cell, kpts).density_fit()
kmf.max_cycles=1000
kmf.exxdiv=None
kmf.kernel()

**Comment by sunqm** [comment]
This calculation requires some memory operations and disk operations. You may observe that the process is often in the "D" state using the "top" command. That means the program is blocked by IO, unable to utilize all CPUs. The threading parallelism is not super efficient. However, it still runs in parallel.
