### ISSUE TITLE
gto_evaluate for spinor basis

### ISSUE THREAD

**Issue by juanjoaucar** [pyscf/pyscf#2239]
Dear pyscf developers,

I'm having some trouble to understand some basics about the gto_evaluate function. I'm performing some tests with the very simple H2 molecule with the contracted STO-3G basis set (only 2 s-type AOs).

First, I get the coefficients of the molecular orbitals through 
```
mf_rel = scf.DHF(mol)
mf_rel.kernel()
mf_rel.mo_coeff
```
and I extract from there only the coefficients corresponding to the L (from large) block and then extracting only the occupied orbitals of positive energy:

```
n4c, nmo = mf_rel.mo_coeff.shape
n2c = n4c // 2
nNeg = nmo // 2  # molecular orbitals of negative energy
nocc = mol.nelectron

mo_pos_l = mf_rel.mo_coeff[:n2c, nNeg:]
Lo = mo_pos_l[:, :nocc]
```

Then, I want to get the overlap matrix in spinor basis, evaluated at a certain coordinate (so in fact is not the overlap matrix but correspond to let's say its counterpart).

The point is that when calling to gto.eval_gto I get:

- if "str" is "GTOval_sph": a tensor of shape (1,2)
- if "str" is "GTOval_spinor": a tensor of shape (2,1,4)

I cannot fully understand the last one. I was expecting to get something of shape (1,4)

Afterwards, I need to get the expectation value of a "fermi-contact" type operator. If I proceed as follows, I get the correct result (but I need help on understanding what I've pointed out).

```
from numpy import matmul as mm
from numpy import transpose as tp


ao_spinor = gto.eval_gto(mol,"GTOval_spinor",coords,comp=1)
ao_spinor_L1_column = ao_spinor[0,0,:].reshape(1,-1)
ao_spinor_L2_column = ao_spinor[1,0,:].reshape(1,-1)

ao_fc_spinor_L1 = np.einsum('ip,iq->pq', ao_spinor_L1_column.conjugate(), ao_spinor_L1_column) 
ao_fc_spinor_L2 = np.einsum('ip,iq->pq', ao_spinor_L2_column.conjugate(), ao_spinor_L2_column)

L1_sum=0
L2_sum=0
for k in range(ocupacion):
   L1_term = mm(mm(tp(Lo).conjugate(), ao_fc_spinor_L1), Lo)[k, k]
   L2_term = mm(mm(tp(Lo).conjugate(), ao_fc_spinor_L2), Lo)[k, k]
   L1_sum =L1_sum + L1_term
   L2_sum = L2_sum + L2_term
correct_result = L1_sum + L2_sum
```
   
The last thing I'd like to point out is that if I call to dhf.get_ovlp I get a (8x8) matrix, so that the up-left block correspond to the L integrals and its shape is (4x4) - what I'm trying to construct is that block but no performing the integrals but evaluating the atomic functions at a certain coordinate.

Any clarification about this all would be very helpfull

Thanks in advance,

Juan J. Aucar

**Comment by sunqm** [comment]
The leading dimension in  shape (2,1,4) for GTOval_spinor means the spin-up and spin-down parts in the spinor. The DFT numerical integration code https://github.com/pyscf/pyscf/blob/master/pyscf/dft/r_numint.py#L108 is an example of the data structure

**Comment by juanjoaucar** [comment]
Dear Qiming Sun,

Thanks for the very quick reply.

Can you please clarify why if I call to 
`dhf.get_ovlp`
I get a 8x8 (array) while for
` eval_gto("GTOval_spinor")`
 
 I get that (2,1,4) array? I mean... in the latter case I get 8 coefficients related to the large components while for the first case the large block contains only 4 related coefficients (so that we get a 4x4 block)
 
 Thanks!
