### ISSUE TITLE
Band Structure calculation for certain band points

### ISSUE THREAD

**Issue by asingal14** [pyscf/pyscf#2245]
Hi, I am trying to calculate the energy and molecular orbitals for certain k-points non-self-consistently after performing a self-consistent calculation with a sparse k-grid. In this, an issue that I am facing is that certain band k-points work relatively well, but certain others take forever to calculate.

My code is:

```
import pyscf.pbc.gto as pbcgto
import pyscf.pbc.dft as pbcdft
import psutil
import numpy as np
max_memory = psutil.virtual_memory().available/(2**20)*.9

cell = pbcgto.M(
        a = [[2.715, 2.715, 0. ], [0., 2.715, 2.715], [2.715, 0., 2.715]],
        atom = '''Si 0. 0. 0.     
        Si 1.3575 1.3575 1.3575''',
        basis = {'Si': 'cc-pvdz'},
        cart = True,
        verbose = 4,
        output = 'pyscf_Si_outfile.txt',
        ecp = None,
        precision = 1e-9,
        space_group_symmetry = True,
        max_memory = max_memory
        )
rcut = pbcgto.cell.estimate_rcut(cell, precision=cell.precision)
cell.rcut = rcut
cell.max_memory = max_memory
cell.build()

kpts = cell.make_kpts([4, 4, 4], wrap_around = True, space_group_symmetry = True, with_gamma_point = True)
kmf = pbcdft.KRKS(cell, kpts).density_fit()
kmf.xc = 'pbe'
kmf.kernel()
```

After converging this, I employ:
```
q = np.array([[0.02, 0.00, 0.00]])
kmf.get_bands(q)
```
This works perfectly well. However I wish to also employ:
```
q = np.array([[0.01, 0.01, 0.01]])
kmf.get_bands(q)
```
which seems to get lost in `pyscf.pbc.symm.geom.search_space_group_ops` and not come out within a reasonable amount of time (should be ~ a few minutes at most on a 96-core node with over 128 GB ram). It seems to happen while building symmetry operations for the supercell while calculating the core contribution to the Fock matrix. Specifically, the kmesh calculated for the first band k-point is [11, 1, 11], while that for the second band point is [11, 11, 11]. Is this expected behavior?  If so, is it much more desirable to input multiple band k-points instead of one at a time to speed up the calculations?

Thanking You and Best Regards,
Aman Singal

EDIT: RESOLVED. Multiple band kpts at once seem to not have this issue, i.e., the supercell costs are determined by the worst supercell cost for all k-points if I give multiple band kpts. 

Thank You!

**Comment by tberkel** [comment]
I don't know if this is the actual system you're interested in, or just a test case. 444 Si with PBE in a DZ basis should be pretty fast *without* space group symmetry. So that makes me think this is an issue with the space group symmetry, and maybe @fishjojo has thoughts.

**Comment by asingal14** [comment]
This is indeed just a test case to build a platform for calculating the RPA dielectric function with local field effects, except using analytical solutions to the transition amplitude <ik | e^{iqr} | j(k+q)>. We plan to use this with larger materials, like HgCdTe, PbS, GaAs etc, with a denser k-grid (for Si, I am aiming to get to 10x10x10 if needed with TZ basis). Indeed, it takes less than 5 minutes on Apple M3 chipset running on one thread to compute the electronic structure for the test case without symmetry. However, we have a gigantic number of q vectors that must be considered (~15000) as we plan to look at all-electron effects visible at smaller scales in the dielectric function.
