### ISSUE TITLE
Complex conjugation bug in tdscf?

### ISSUE THREAD

**Issue by tberkel** [pyscf/pyscf#2246]
I think that the tdscf codes in PySCF return the complex conjugate of the eigenvector of the "conventional" CIS/TDHF matrix (equivalently, they calculate the left eigenvector or the eigenvector of the matrix conjugate transpose). Of course, the eigenvalues are fine, and this only affects methods with complex orbitals—including, but not limited to, periodic calculations. Assuming that this is *not* intentional, then ...

I think that the problem is in the transformation of the pseudodensity matrix to the AO basis and the reverse transformation of the Fock-like matrix back to the MO basis.

I have only been able to test this easily in periodic calculations. For `pbc/tdscf/krhf.py`, I think the following change is necessary:
```
133                     dmov[i,k] = reduce(numpy.dot, (orbo[k].conj(), dm1, orbv[k].T)).T  # changed
134                     #dmov[i,k] = reduce(numpy.dot, (orbo[k], dm1, orbv[k].conj().T))

143                     v1vo = reduce(numpy.dot, (orbv[k].conj().T, v1ao[i,k], orbo[k])).T  # changed
144                     #v1vo = reduce(numpy.dot, (orbo[k].conj().T, v1ao[i,k], orbv[k]))
```
This produces an eigenvector `x` that is the complex conjugate of the eigenvector returned without these changes. Two checks suggest that this change is correct:

- When comparing to a supercell calculation with all real orbitals, only this modified version (with k-point sampling and complex orbitals) agrees.
- This modified version agrees with the eigenvector of the more explicit periodic CIS code in `pbc/ci/kcis_rhf.py`

If this is a correct bug report, I think that the analogous change needs to be made throughout PySCF, for example [L97-99](https://github.com/pyscf/pyscf/blob/master/pyscf/tdscf/rhf.py#L97-L99) of molecular `pyscf/tdscf/rhf.py`, etc.

I welcome any corrections, thoughts, or suggestions for further testing.

This problem was found with @SylviaJoy1, and anecdotally supported by @hongzhouye in a different context.

**Comment by sunqm** [comment]
I carefully checked the implementation. The `gen_vind` function is consistent with the A, B tensors defined in the `get_ab` function, https://github.com/pyscf/pyscf/blob/71d265c95fbef7c9ca4ff6e91b613f2d226959a8/pyscf/tdscf/rhf.py#L138 . I compared the A, B tensors against the TDDFT literature, like https://doi.org/10.1016/0009-2614(96)00440-X , they are equivalent. I tried to derive them using first order orbitals, which gives me the A tensor `A[i,a,j,b] = (ia|bj) - (ij|ab) + delta_ij delta_ab (e_a - e_i) ` and the B tensor `B[i,a,j,b] = (ia|jb) - (ib|ja)`. They are consistent with the literature too.

Your proposed change is incorrect IMO. It corresponds to defining A tensor as `A[i,a,j,b] = (ia|jb) - (ib|ja) + ...` . This expression breaks the Hermitian symmetry of the A tensor, which should obey `A[i,a,j,b] = A[j,b,i,a].conj()` .

The `kcis_rhf` module implements the A tensor as `A[a,i,b,j] = (ai|jb) - (ji|ba)` . Its a complex conjugation of the TDDFT A tensor. The X coefficient obtained in the TDDFT code will not be equal to the CIS eigenvectors. They should be complex conjugated to each other.

**Comment by tberkel** [comment]
Thanks for looking into this. My proposed change doesn't break Hermiticity, it's just the complex conjugate of the current version (it matches the `kcis_rhf` module definition) ... maybe you missed the `.T` at the end of the lines.

> The X coefficient obtained in the TDDFT code will not be equal to the CIS eigenvectors. They should be complex conjugated to each other.

I think this is the main issue. Should the X coefficient of a TDDFT code be equal to the CIS eigenvector? Surely, in CIS,

$$
\langle\Phi_i^a | H_2 | \Phi_j^b\rangle = \langle aj||ib\rangle = (ai|jb) - (ab|ji)
$$

but this is the complex conjugate of the A matrix implemented throughout PySCF.

**Comment by sunqm** [comment]
In the linear response theory, the A tensor can be defined as <ib||aj> or <aj||ib> . The eigenvalues of the two are equivalent and the eigenvectors can be transformed between the two. The TDDFT in PySCF takes the first definition, which is unfortunately inconsistent with the CIS wavefunction coefficients.

All code in the TDDFT are implemented consistent with this definition. If the `.T` is applied at the end of those lines, the remaining part need to be modified too. For example, the next transformation `reduce(dot, (orbo[k].T.conj(), v1ao[i,k], orbv[k]))` would need to be changed to `reduce(dot, (orbv[k].T.conj(), v1ao[i,k], orbo[k]))`.

I agree it's better to define the X matrix of TDDFT the same way as the CIS coefficients. However, when TDDFT was implemented initially, the other convention was used. The PBC TDDFT and TDDFT with other complex integrals then follow the initial implementation. If changing to the other convention, many relevant modules (tdscf, grad, pbc/tdscf) need to be updated. I think it can be done in a minor version release.

**Comment by tberkel** [comment]
I'm glad we agree, and that sounds good, we can try to reconcile CIS and TDDFT at a later time. Thanks.
