### ISSUE TITLE
Properties location?

### ISSUE THREAD

**Issue by n00b-0K** [pyscf/pyscf#2251]
Since updating from version 2.5, I am unable to use "pyscf.prop"

Checking the code, I cannot find it or the rest of the properties that the module had. 
It migrated somewhere else that I cannot find.?

I would appreciate any help with this 😊

**Comment by tberkel** [comment]
It is now a PySCF extension: https://github.com/pyscf/properties

**Comment by n00b-0K** [comment]
thanks
