### ISSUE TITLE
Rescaling p basis separately

### ISSUE THREAD

**Issue by lanieleung** [pyscf/pyscf#2254]
Hi,

Let's say we have a carbon atom in minimal basis. The basis can be rescaled by changing the values of `mol.bas_exp(aocontr_idx)[prim_idx]` and `mol._libcint_ctr_coeff(aocontr_idx)[prim_idx]`. The 2px, 2py, and 2pz share `aocontr_idx=2`. Is there any way that I can rescale the 2s, 2px, 2py, and 2pz separately?

**Comment by sunqm** [comment]
No. The three Cartesian functions are treated as a "shell" that share the exponents and contraction coefficients. They are evaluated simultaneously when computing integrals. If you need to utilize different p orbitals for different Cartesian components, you probably need to make a bunch of modifications to the current code. In short, it requires creating three shells with different exponents/coeffcients, each for one Cartesian component. Then modify the get_hcore, get_ovlp, get_jk code to filter the matrices, assuming you are doing HF methods.

**Comment by lanieleung** [comment]
Thanks for answering, that's clear.
