### ISSUE TITLE
Exporting an object of type pyscf.pbc.dft.rks.RKS

### ISSUE THREAD

**Issue by computative** [pyscf/pyscf#2258]
Hello,

I want to export a fit to use it later. The only way I knew to try was to use pickle put the interpreter raises `TypeError: cannot pickle '_io.TextIOWrapper' object`

```
from pyscf.pbc import gto, dft
import pickle

cell = gto.Cell()
a = 3.5668
cell.a = f'''
{a}     0       0
0       {a}     0
0       0       {a}'''
cell.atom = '''C     0.      0.      0.    
              C     0.8917  0.8917  0.8917
              C     1.7834  1.7834  0.    
              C     2.6751  2.6751  0.8917
              C     1.7834  0.      1.7834
              C     2.6751  0.8917  2.6751
              C     0.      1.7834  1.7834
              C     0.8917  2.6751  2.6751'''
cell.basis = 'gth-szv'
cell.pseudo = 'gth-lda'
cell.build()

mf = dft.RKS(cell)
mf.kernel()

with open('mf.pkl', 'wb') as outp:
    pickle.dump(mf, outp, pickle.HIGHEST_PROTOCOL)
```

Can I somehow store a RKS-fit on disk for later use?

**Comment by sunqm** [comment]
I'd recommend to use the chkfile to save the results. Before calling the mf.kernel function, you can specify
`mf.chkfile = 'mf.chk'` . This will save cell and mf objects to the `'mf.chk'` file. You can restore the two objects by
```
cell, mf = pyscf.pbc.scf.chkfile.load_scf('mf.chk')
```

**Comment by computative** [comment]
> I'd recommend to use the chkfile to save the results. Before calling the mf.kernel function, you can specify `mf.chkfile = 'mf.chk'` . This will save cell and mf objects to the `'mf.chk'` file. You can restore the two objects by
> 
> ```
> cell, mf = pyscf.pbc.scf.chkfile.load_scf('mf.chk')
> ```

If I do that, then the object referenced by `mf` isn't actually of type `pyscf.pbc.dft.rks.RKS`. It is of type `dict`. Can you say the appropriate line to convert it to type `pyscf.pbc.dft.rks.RKS?`

**Comment by sunqm** [comment]
I forgot the return type of the load_scf function. You can use it to overwrite an `mf` object. That is to say you have to create the mean field object yourself. Please note that mf_dic only saves the SCF results. You need to assign attributes of mf, like `xc`, `exxdiv` manually.
```
cell, mf_dic = pyscf.pbc.scf.chkfile.load_scf('mf.chk')
mf = cell.RKS()
mf.__dict__.update(mf_dic)
```
See also
https://github.com/pyscf/pyscf/blob/master/examples/scf/14-restart.py#L64
