### ISSUE TITLE
DFT-D2 Update

### ISSUE THREAD

**Issue by jfreeze95** [pyscf/pyscf#2267]
Hi Devs,

I'm going to need to use the wb97x-d functional for some of my research so I wanted to find out if the DFT-D2 dispersion correction fix is already underway or going to be an upcoming fix in the near future (~ 1 month) or if I should start working on a solution for it? 

Thanks,
Jess

**Comment by awvwgk** [comment]
D2 is available with https://github.com/pyscf/dftd3, however I did not reimplement the D2 dispersion in https://github.com/dftd3/simple-dftd3, therefore it is not available with the `dftd3.pyscf` module.

**Comment by sunqm** [comment]
DFT-D2 is not planned for implementation in PySCF core branch.
