### ISSUE TITLE
How to imply twist-averaged boundary conditions (TABC) to KS-DFT/HF calculation in Pyscf?

### ISSUE THREAD

**Issue by ustcwdd** [pyscf/pyscf#2281]
Γ point calculations are known to converge slowly and non-monotonically to the thermodynamic limit of infinite system size at zero temperature. To achieve better convergence, twist-averaged boundary conditions (TABC) as a general bloch boundary condition of periodic boundary conditions (PBC) is an economical alternative to full Brillouin zone sampling, but it usually be implied to quantum Monte Carlo(QMC) algorithms. So, how to imply twist-averaged boundary conditions (TABC) to KS-DFT/HF calculation in Pyscf?

**Comment by tberkel** [comment]
The `cell.make_kpts()` function optionally takes a kwarg `scaled_center` that is a shift of the k-point mesh off of the Gamma point, e.g.,
```
cell.make_kpts([3,3,3], scaled_center=[0.25, 0.25, 0.25])
```
See the function and docstring [here](https://github.com/pyscf/pyscf/blob/master/pyscf/pbc/gto/cell.py#L815).

This is one calculation with a "twisted" boundary condition. In twist-averaging, calculations are averaged over many possible twist angles, and you can script this yourself, depending on the twist averaging procedure you want to use.

**Comment by ustcwdd** [comment]
Dear therkel:

Thank you for your response. It is very helpful for me.

In averaging procedure of DFT, the expectation value of an operator B is averaged over a mesh of Nk points ki in the Brillouin zone. In my understanding, Pyscf's calculation of energy itself is already carried out in this way. So, I just need to adjust the scaled center with [a1, a2, a3] and ensure ai*ki=di. Here, i is the dimision, k is the kpts, d is lattice constant of unitcell. Is it right? 

Looking forward for your reply.

**Comment by tberkel** [comment]
Not quite, there are two separate averages. The first averaging occurs in all DFT calculations over the k-point mesh in the Brillouin zone. A second (optional) averaging is to additionally average over the shift of a k-point mesh, i.e., over many different twist angles (e.g., see Eq (6) of [this paper](https://arxiv.org/pdf/cond-mat/0101339)). In pseudocode, you could do something like
```
e_tabc = 0
for scaled_center in scaled_centers:
    kpts = cell.make_kpts([nk,nk,nk], scaled_center=scaled_center)
    kmf = scf.KRKS(cell, kpts)
    e_tabc += kmf.kernel()
print("TABC energy =", e_tabc/len(scaled_centers)
```

**Comment by ustcwdd** [comment]
Dear therkel:

Thanks for your patient answers. The second averaging procedure is not my requirement. I want to converge gamma point DFT calculation and compare the energy result with DFT calculation done by VASP. Also, I need to get kohn-sham orbitals from DFT calculations implied by Pyscf. Actually, when we use general twist boundary condition, converged energy is not equal to PBC calculation in gamma point. And I have tried set scaled center to [1, 1, 1] to shift from first brillouin zone completely. Of course, this energy is equal to PBC calculation in gamma point center. In my opinion, this procedure can be considered as TABC use the first averaging procedure, but when I apply this to large period system, it also can't be converged. Am I wrong in my thinking or does Pyscf have another way to promote convergence at the center of the brillouin point(gamma point) used PBC. I have used density fitting method with GTO to save memory.

I have also tried the second averaging method yet like this way with four-point calculations between 0 and π and this means total 64 DFT calculations  of 3D materials, but the result is not good:

import numpy as np
from pyscf.pbc import gto,scf,cc

lattice_vectors = [
    [2.0, 0.0, 0.0],
    [0.0, 2.0, 0.0],
    [0.0, 0.0, 2.0]
]
cell=gto.Cell()
cell.atom='''H 0 0 0; H 1 1 1'''
cell.basis = "gth-szv"
cell.pseudo = "gth-pade"
cell.a = lattice_vectors
cell.symmetry = True
cell.spin=0
cell.nelectron=None
cell.build()
list=[]
for i in range(2, 10, 2):
    for j in range(2, 10, 2):
        for k in range(2, 10, 2):
            kshift=[0.1*i, 0.1*j, 0.1*k]
            kpts=cell.make_kpts([1,1,1], scaled_center=kshift, wrap_around=True)
            kmf = scf.KRHF(cell, kpts=kpts,  exxdiv=None).run()
            list.append(kmf.e_tot)

print(np.mean(list))  
 
The result is -0.2254583267975458 hartree. And energy result is -1.05997758681315 without shift.

**Comment by tberkel** [comment]
Sorry, I don't understand what you want to do. What I described is twist-averaged boundary conditions. If all you want is a gamma point calculation, this is performed simply by using `make_kpts([1,1,1])` (or using `scf.RHF(cell)` which is the same result, but should run faster). The normal way to eliminate finite-size effects is to increase the number of k-points with `make_kpts([2,2,2])`, then `make_kpts([3,3,3])`, and so on.

What is the answer you are expecting, and why do you expect you should get this answer?

**Comment by ustcwdd** [comment]
Dear tberkel:
I want to converge gamma point calculation with twist-averaged boundary condition, because the gamma point calculation of large period system is not converged. But when I use the kwarg scaled_center, energy is different from that without shift. For example, 1D-H-chain is test with two conditions:

###test: if we change scaled center, result is equal or unequal
from pyscf.pbc import gto,scf,cc
lattice_vectors = [
    [10.0, 0.0, 0.0],
    [0.0, 10.0, 0.0],
    [0.0, 0.0, 2.0]
]
cell=gto.Cell()
cell.atom='''H 0 0 0; H 0 0 1.0'''
cell.basis = "gth-szv"
cell.pseudo = "gth-pade"
cell.a = lattice_vectors
cell.symmetry = True
cell.spin=0
cell.nelectron=None
cell.build()
kshift=[0., 0., 0.25]  ##scaled_center are set to 0 and 0.25
kpts=cell.make_kpts([1,1,1], scaled_center=kshift, with_gamma_point=False)
kmf = scf.KRHF(cell, kpts=kpts,  exxdiv=None).run() 

Two converged energies are -1.40167705434167 and -1.24987034964638 with scaled_center 0 and 0.25 respectively, energy values are different. So, Am I right in thinking that the absolute energy of convergence does not matter, it is the relative energy that matters.

**Comment by ustcwdd** [comment]
Dear tberkel:

I want to converge gamma point calculation with twist-averaged boundary condition, because the gamma point calculation with PBC of large period system is not converged. But when I use the kwarg scaled_center, energy is different from that without shift. For example, 1D-H-chain is test with two conditions:

###test: if we change scaled center, result is equal or unequal
from pyscf.pbc import gto,scf,cc
lattice_vectors = [
[10.0, 0.0, 0.0],
[0.0, 10.0, 0.0],
[0.0, 0.0, 2.0]
]
cell=gto.Cell()
cell.atom='''H 0 0 0; H 0 0 1.0'''
cell.basis = "gth-szv"
cell.pseudo = "gth-pade"
cell.a = lattice_vectors
cell.symmetry = True
cell.spin=0
cell.nelectron=None
cell.build()
kshift=[0., 0., 0.25] ##scaled_center are set to 0 and 0.25
kpts=cell.make_kpts([1,1,1], scaled_center=kshift, with_gamma_point=False)
kmf = scf.KRHF(cell, kpts=kpts, exxdiv=None).run()

Two converged energies are -1.40167705434167 and -1.24987034964638 with scaled_center 0 and 0.25 respectively, energy values are different. So, Am I right in thinking that the absolute energy of convergence does not matter, it is the relative energy that matters.

**Comment by tberkel** [comment]
The energy with different shifts *should* be different (otherwise, there would be nothing to average). Note that using a small unit cell with Gamma point sampling and TABCs does not guarantee exact convergence to the thermodynamic limit. It only aims to provide a better approximation than a single Gamma point calculation. Here's a quick example for carbon diamond (this hasn't been carefully tested, use at your own risk):
```
from pyscf.pbc import gto, dft
import numpy as np

a = 3.37013733
cell = gto.M(
    unit = 'b',
    a = [[0,a,a],[a,0,a],[a,a,0]],
    atom = f'''C     0.      0.      0.
               C    {a/2}   {a/2}   {a/2}''',
    basis = 'gth-szv',
    pseudo = 'gth-pade',
    verbose = 4,
)

nks = [1,2,3,4]
energies = list()

for nk in nks:
    kpts = cell.make_kpts([nk,nk,nk])

    kmf = dft.KRKS(cell, kpts).density_fit()
    e = kmf.kernel()
    energies.append(e)

nshifts_per_direction = [3,5]

energies_tabc = list()
for n in nshifts_per_direction:
    energies_tabc_n = list()
    kshifts = np.linspace(-1,1, num=n, endpoint=False)
    for ka in kshifts:
        for kb in kshifts:
            for kc in kshifts:
                kpts = cell.make_kpts([1,1,1], wrap_around=True, scaled_center=[ka,kb,kc])
                kmf = dft.KRKS(cell, kpts).density_fit()
                e = kmf.kernel()
                energies_tabc_n.append(e)
    energies_tabc.append(np.mean(energies_tabc_n))

print("Regular BZ sampling")
for nk,e in zip(nks,energies):
    print(nk, e)

print("Twist averaged boundary conditions")
for n,e in zip(nshifts_per_direction,energies_tabc):
    print(n, e)
```
This should print
```
Regular BZ sampling
1 -10.231185742377637
2 -11.244108896556664
3 -11.340699661622246
4 -11.355668312675796  <-- best estimate from regular BZ sampling
Twist averaged boundary conditions
3 -11.333154502799502
5 -11.352541937398323  <-- quite close to the best estimate from 444 sampling
```

**Comment by ustcwdd** [comment]
Dear tberkel: 

Got it, thanks a lot for your detailed explanation and examples! These really very helpful for me!

**Comment by ustcwdd** [comment]
Dear tberkel: 

Got it, thanks a lot for your detailed explanation and examples! These really very helpful for me!
