### ISSUE TITLE
“OSError "libcint.so.5" can not open...” when update to Pyscf version 2.6.2 in conda

### ISSUE THREAD

**Issue by chrinide** [pyscf/pyscf#2283]
In a Linux conda enviorment， when update the pyscf version to the newest 2.6.2, and at the same time libcint version will also be updated to the newest version 6.1.2. 

However, if you run a any simple test at this newest versions, you will get:

`OSError: libcint.so.5: cannot open shared object file: No such file or directory`

This could be sovled by just create a soft link "libcint.so.5" to the newest libcint version 6.1.2.

**Comment by chillenb** [comment]
What's the output of `conda list -c` and `conda info` in the affected environment?

**Comment by chrinide** [comment]
> What's the output of `conda list -c` and `conda info` in the affected environment?

`conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
conda-forge/linux-64::_openmp_mutex-4.5-2_kmp_llvm
conda-forge/noarch::annotated-types-0.6.0-pyhd8ed1ab_0
conda-forge/noarch::anyio-4.2.0-pyhd8ed1ab_0
pypi/pypi::appdirs-1.4.4-pypi_0
conda-forge/noarch::argcomplete-3.2.1-pyhd8ed1ab_0
conda-forge/noarch::argon2-cffi-23.1.0-pyhd8ed1ab_0
conda-forge/linux-64::argon2-cffi-bindings-21.2.0-py311h459d7ec_4
conda-forge/noarch::arrow-1.3.0-pyhd8ed1ab_0
conda-forge/noarch::ase-3.22.1-pyhd8ed1ab_1
pypi/pypi::asteval-0.9.31-pypi_0
conda-forge/noarch::asttokens-2.4.1-pyhd8ed1ab_0
conda-forge/noarch::async-lru-2.0.4-pyhd8ed1ab_0
conda-forge/linux-64::attr-2.5.1-h166bdaf_1
conda-forge/noarch::attrs-23.2.0-pyh71513ae_0
conda-forge/noarch::babel-2.14.0-pyhd8ed1ab_0
conda-forge/noarch::backcall-0.2.0-pyh9f0ad1d_0
conda-forge/noarch::backports-1.0-pyhd8ed1ab_3
conda-forge/noarch::backports.functools_lru_cache-2.0.0-pyhd8ed1ab_0
pypi/pypi::basis-set-exchange-0.9.1-pypi_0
pypi/pypi::basisopt-1.0.0-pypi_0
conda-forge/noarch::beautifulsoup4-4.12.2-pyha770c72_0
defaults/linux-64::blas-1.0-mkl
conda-forge/noarch::bleach-6.1.0-pyhd8ed1ab_0
defaults/linux-64::bottleneck-1.3.7-py311hf4808d0_0
defaults/linux-64::brotli-1.0.9-he6710b0_2
conda-forge/linux-64::brotli-python-1.1.0-py311hb755f60_1
defaults/noarch::bs4-4.12.2-py38hd3eb1b0_0
conda-forge/linux-64::bzip2-1.0.8-hd590300_5
conda-forge/linux-64::c-ares-1.24.0-hd590300_0
defaults/linux-64::ca-certificates-2024.3.11-h06a4308_0
conda-forge/noarch::cached-property-1.5.2-hd8ed1ab_1
conda-forge/noarch::cached_property-1.5.2-pyha770c72_1
conda-forge/noarch::castepxbin-0.1.0-pyhd8ed1ab_0
pypi/pypi::ccinput-1.10.3-pypi_0
defaults/linux-64::certifi-2024.6.2-py311h06a4308_0
conda-forge/linux-64::cffi-1.16.0-py311hb3a22ac_0
conda-forge/noarch::charset-normalizer-3.3.2-pyhd8ed1ab_0
pypi/pypi::chemtools-0.9.2-pypi_0
conda-forge/linux-64::chimes-calculator-1.0.2-h0c14de7_0
defaults/linux-64::click-8.1.7-py311h06a4308_0
conda-forge/noarch::colorama-0.4.6-pyhd8ed1ab_0
pypi/pypi::colorlog-6.8.2-pypi_0
conda-forge/noarch::colormath-3.0.0-py_2
conda-forge/noarch::comm-0.2.1-pyhd8ed1ab_0
defaults/linux-64::contourpy-1.2.0-py311hdb19cb5_0
conda-forge/linux-64::cppe-0.3.1-py311he7fe448_9
defaults/linux-64::cuda-cudart-12.4.127-h99ab3db_0
defaults/noarch::cuda-cudart_linux-64-12.4.127-hd681fbe_0
defaults/linux-64::cuda-nvrtc-12.4.127-h99ab3db_1
defaults/linux-64::cuda-nvtx-12.4.127-h6a678d5_1
defaults/noarch::cuda-version-12.4-hbda6634_3
conda-forge/linux-64::cudnn-8.9.7.29-h092f7fd_3
pypi/pypi::cycler-0.12.1-pypi_0
conda-forge/linux-64::debugpy-1.8.0-py311hb755f60_1
conda-forge/noarch::decorator-5.1.1-pyhd8ed1ab_0
conda-forge/noarch::defusedxml-0.7.1-pyhd8ed1ab_0
conda-forge/linux-64::dftbplus-24.1-mpi_openmpi_ha0c50f8_0
pypi/pypi::dftd3-0.7.0-pypi_0
conda-forge/linux-64::dftd4-3.6.0-hf49bc11_0
conda-forge/linux-64::dkh-1.2-hd59d2e7_0
conda-forge/linux-64::eigen-3.4.0-h00ab1b0_0
conda-forge/linux-64::elpa-2021.11.001-mpi_openmpi_haf9840c_3
conda-forge/linux-64::elsi-2.9.1-mpi_openmpi_h4d0b366_0
conda-forge/noarch::entrypoints-0.4-pyhd8ed1ab_0
conda-forge/noarch::exceptiongroup-1.2.0-pyhd8ed1ab_0
conda-forge/noarch::excitingtools-1.2.0-pyhd8ed1ab_0
pypi/pypi::execnet-2.0.2-pypi_0
conda-forge/noarch::executing-2.0.1-pyhd8ed1ab_0
conda-forge/linux-64::fftw-3.3.10-nompi_hc118613_108
conda-forge/noarch::filelock-3.13.1-pyhd8ed1ab_0
defaults/linux-64::flask-2.2.5-py311h06a4308_0
pypi/pypi::fonttools-4.47.2-pypi_0
conda-forge/noarch::fqdn-1.5.1-pyhd8ed1ab_0
defaults/linux-64::freetype-2.12.1-h4a9f257_0
conda-forge/noarch::fsspec-2023.12.2-pyhca7485f_0
defaults/linux-64::future-0.18.3-py311h06a4308_0
conda-forge/linux-64::gau2grid-2.0.7-h0b41bf4_2
conda-forge/linux-64::gawk-5.3.0-ha916aea_0
defaults/linux-64::gdbm-1.18-hd4cb3f1_4
conda-forge/noarch::geometric-1.0-pyhd8ed1ab_1
conda-forge/linux-64::gettext-0.21.1-h27087fc_0
conda-forge/linux-64::gmp-6.3.0-h59595ed_0
conda-forge/linux-64::gmpy2-2.1.2-py311h6a5fa03_1
pypi/pypi::greenlet-3.0.3-pypi_0
conda-forge/linux-64::gromacs-2023.1-nompi_h76c6bb2_102
defaults/linux-64::gsl-2.7.1-h6e86dc7_1
conda-forge/linux-64::gtest-1.14.0-h00ab1b0_1
conda-forge/linux-64::h5py-3.11.0-nompi_py311h439e445_101
conda-forge/linux-64::hdf5-1.14.3-nompi_h4f84152_100
defaults/noarch::html5lib-1.1-pyhd3eb1b0_0
conda-forge/linux-64::icu-73.2-h59595ed_0
conda-forge/noarch::idna-3.6-pyhd8ed1ab_0
pypi/pypi::imageio-2.33.1-pypi_0
conda-forge/noarch::importlib-metadata-7.0.1-pyha770c72_0
defaults/noarch::importlib-resources-6.1.1-pyhd3eb1b0_1
conda-forge/noarch::importlib_metadata-7.0.1-hd8ed1ab_0
conda-forge/noarch::importlib_resources-6.1.1-pyhd8ed1ab_0
conda-forge/noarch::iniconfig-2.0.0-pyhd8ed1ab_0
defaults/linux-64::intel-openmp-2023.1.0-hdb19cb5_46306
conda-forge/noarch::ipykernel-6.28.0-pyhd33586a_0
conda-forge/noarch::ipython-8.19.0-pyh707e725_0
defaults/linux-64::ipywidgets-8.1.2-py311h06a4308_0
conda-forge/noarch::isoduration-20.11.0-pyhd8ed1ab_0
defaults/noarch::itsdangerous-2.0.1-pyhd3eb1b0_0
conda-forge/noarch::jedi-0.19.1-pyhd8ed1ab_0
conda-forge/noarch::jinja2-3.1.2-pyhd8ed1ab_1
defaults/linux-64::joblib-1.2.0-py311h06a4308_0
defaults/linux-64::jpeg-9e-h5eee18b_1
conda-forge/noarch::json5-0.9.14-pyhd8ed1ab_0
conda-forge/linux-64::jsonpointer-2.4-py311h38be061_3
conda-forge/noarch::jsonschema-4.20.0-pyhd8ed1ab_0
conda-forge/noarch::jsonschema-specifications-2023.12.1-pyhd8ed1ab_0
conda-forge/noarch::jsonschema-with-format-nongpl-4.20.0-pyhd8ed1ab_0
conda-forge/noarch::jupyter-lsp-2.2.1-pyhd8ed1ab_0
conda-forge/noarch::jupyter_client-8.6.0-pyhd8ed1ab_0
conda-forge/linux-64::jupyter_core-5.6.1-py311h38be061_0
conda-forge/noarch::jupyter_events-0.9.0-pyhd8ed1ab_0
conda-forge/noarch::jupyter_server-2.12.1-pyhd8ed1ab_0
conda-forge/noarch::jupyter_server_terminals-0.5.1-pyhd8ed1ab_0
conda-forge/noarch::jupyterlab-4.0.11-pyhd8ed1ab_0
pypi/pypi::jupyterlab-mol-visualizer-0.3.0-pypi_0
conda-forge/noarch::jupyterlab_pygments-0.3.0-pyhd8ed1ab_0
conda-forge/noarch::jupyterlab_server-2.25.2-pyhd8ed1ab_0
defaults/linux-64::jupyterlab_widgets-3.0.10-py311h06a4308_0
conda-forge/linux-64::keyutils-1.6.1-h166bdaf_0
pypi/pypi::kiwisolver-1.4.5-pypi_0
pypi/pypi::kmap-3.2.0-pypi_0
conda-forge/linux-64::krb5-1.21.2-h659d440_0
conda-forge/noarch::lark-parser-0.12.0-pyhd8ed1ab_0
conda-forge/noarch::latexcodec-2.0.1-pyh9f0ad1d_0
pypi/pypi::lazy-loader-0.3-pypi_0
defaults/linux-64::lcms2-2.12-h3be6417_0
conda-forge/linux-64::ld_impl_linux-64-2.40-h41732ed_0
defaults/linux-64::lerc-3.0-h295c915_0
conda-forge/linux-64::lfortran-0.29.0-hfc55251_0
defaults/linux-64::libabseil-20240116.2-cxx17_h6a678d5_0
conda-forge/linux-64::libaec-1.1.2-h59595ed_1
conda-forge/linux-64::libblas-3.9.0-20_linux64_mkl
conda-forge/linux-64::libboost-1.84.0-hba137d9_3
conda-forge/linux-64::libcap-2.69-h0f662aa_0
conda-forge/linux-64::libcblas-3.9.0-20_linux64_mkl
conda-forge/linux-64::libcbor-0.10.2-hcb278e6_0
conda-forge/linux-64::libcint-6.1.2-h4ab18f5_0
conda-forge/linux-64::libclang-cpp15-15.0.7-default_hb11cfb5_4
defaults/linux-64::libcublas-12.4.5.8-h99ab3db_1
defaults/linux-64::libcufft-11.2.1.3-h99ab3db_1
defaults/linux-64::libcurand-10.3.5.147-h99ab3db_1
conda-forge/linux-64::libcurl-8.5.0-hca28451_0
defaults/linux-64::libcusolver-11.6.1.9-h99ab3db_1
defaults/linux-64::libcusparse-12.3.1.170-h99ab3db_1
defaults/linux-64::libdeflate-1.17-h5eee18b_1
conda-forge/linux-64::libdlfind-0.0.3-py311h6e7c271_3
conda-forge/linux-64::libecpint-1.0.7-h3ecfda7_10
conda-forge/linux-64::libedit-3.1.20191231-he28a2e2_2
conda-forge/linux-64::libev-4.33-hd590300_2
conda-forge/linux-64::libexpat-2.6.2-h59595ed_0
defaults/linux-64::libffi-3.4.4-h6a678d5_0
conda-forge/linux-64::libfido2-1.14.0-h4446dcb_0
conda-forge/linux-64::libgcc-ng-13.2.0-h807b86a_3
conda-forge/linux-64::libgfortran-3.0.0-1
conda-forge/linux-64::libgfortran-ng-13.2.0-h69a702a_3
conda-forge/linux-64::libgfortran5-13.2.0-ha4646dd_3
conda-forge/linux-64::libgomp-13.2.0-h807b86a_3
conda-forge/linux-64::libhwloc-2.9.1-nocuda_h7313eea_6
conda-forge/linux-64::libiconv-1.17-hd590300_2
conda-forge/linux-64::libint-2.9.0-h9bbc0ff_0
conda-forge/linux-64::liblapack-3.9.0-20_linux64_mkl
conda-forge/linux-64::liblapacke-3.9.0-20_linux64_mkl
conda-forge/linux-64::libllvm13-13.0.1-hf817b99_2
conda-forge/linux-64::libllvm15-15.0.7-h5cf9203_3
conda-forge/linux-64::libllvmspirv15-15.0.0-h0cdce71_1
conda-forge/linux-64::libmagma-2.7.2-h173bb3b_2
conda-forge/linux-64::libmagma_sparse-2.7.2-h173bb3b_3
conda-forge/linux-64::libmbd-0.12.8-mpi_openmpi_hcecb6a8_0
conda-forge/linux-64::libnegf-1.1.3-mpi_openmpi_h4d0b366_0
conda-forge/linux-64::libnghttp2-1.58.0-h47da74e_1
conda-forge/linux-64::libnsl-2.0.1-hd590300_0
defaults/linux-64::libnvjitlink-12.4.127-h99ab3db_1
conda-forge/linux-64::libomm-1.0.0-mpi_openmpi_hbbb7b4b_2
conda-forge/linux-64::libopenblas-0.3.27-openmp_h2e9423c_0
conda-forge/linux-64::libpcm-1.2.3-h4175798_8
defaults/linux-64::libpng-1.6.39-h5eee18b_0
defaults/linux-64::libprotobuf-4.25.3-he621ea3_0
conda-forge/linux-64::libsodium-1.0.18-h36c2ea0_1
conda-forge/linux-64::libsqlite-3.44.2-h2797004_0
conda-forge/linux-64::libssh2-1.11.0-h0841786_0
conda-forge/linux-64::libstdcxx-ng-13.2.0-h7e041cc_3
defaults/linux-64::libtiff-4.5.1-h6a678d5_0
conda-forge/linux-64::libtorch-2.3.1-cuda120_h2b0da52_300
conda-forge/linux-64::libudev1-255-h3f72095_0
conda-forge/linux-64::libuuid-2.38.1-h0b41bf4_0
conda-forge/linux-64::libuv-1.48.0-hd590300_0
defaults/linux-64::libwebp-base-1.3.2-h5eee18b_0
conda-forge/linux-64::libxc-6.2.2-cpu_h22af20a_4
conda-forge/linux-64::libxc-c-6.2.2-cpu_h1b64f48_4
conda-forge/linux-64::libxcrypt-4.4.36-hd590300_1
conda-forge/linux-64::libxml2-2.11.6-h232c23b_0
conda-forge/linux-64::libxslt-1.1.37-h0054252_1
conda-forge/linux-64::libzlib-1.2.13-hd590300_5
conda-forge/linux-64::llvm-openmp-18.1.7-ha31de31_0
conda-forge/linux-64::llvm-spirv-15-15.0.0-h0cdce71_1
pypi/pypi::llvmlite-0.42.0-pypi_0
pypi/pypi::lmfit-1.2.2-pypi_0
pypi/pypi::look4bas-0.3.1-pypi_0
conda-forge/linux-64::lxml-4.9.3-py311h1a07684_3
macroqc/linux-64::macroqc-1.0.7-linux64
conda-forge/linux-64::markupsafe-2.1.3-py311h459d7ec_1
pypi/pypi::matplotlib-3.8.2-pypi_0
defaults/linux-64::matplotlib-base-3.8.0-py311ha02d727_0
conda-forge/noarch::matplotlib-inline-0.1.6-pyhd8ed1ab_0
conda-forge/linux-64::matrixswitch-1.0.0-mpi_openmpi_hbbb7b4b_2
pypi/pypi::mcfun-0.2.3-pypi_0
conda-forge/linux-64::mctc-lib-0.3.1-h74f4db8_0
conda-forge/noarch::mechanize-0.4.9-pyhd8ed1ab_0
pypi/pypi::mendeleev-0.9.0-pypi_0
conda-forge/noarch::mistune-3.0.2-pyhd8ed1ab_0
conda-forge/linux-64::mkl-2023.2.0-h84fe81f_50496
defaults/linux-64::mkl-service-2.4.0-py311h5eee18b_1
defaults/linux-64::mkl_fft-1.3.8-py311h5eee18b_0
defaults/linux-64::mkl_random-1.2.4-py311hdb19cb5_0
pypi/pypi::mlatom-3.6.0-pypi_0
mokit/linux-64::mokit-1.2.6rc34-py3.11_1234567_2
pypi/pypi::monty-2022.9.9-pypi_0
conda-forge/linux-64::mopac-22.1.1-hf49bc11_0
conda-forge/linux-64::mpc-1.3.1-hfe3b2da_0
conda-forge/linux-64::mpfr-4.2.1-h9458935_0
conda-forge/linux-64::mpi-1.0-openmpi
conda-forge/linux-64::mpi4py-3.1.5-py311h4267d7f_0
conda-forge/linux-64::mpifx-1.5-mpi_openmpi_he434663_1
conda-forge/noarch::mpmath-1.3.0-pyhd8ed1ab_0
conda-forge/linux-64::mrchem-1.1.4-nompi_h40f8cdf_100
conda-forge/linux-64::mrcpp-1.5.0-nompi_ha515ca3_100
conda-forge/linux-64::msgpack-python-1.0.7-py311h9547e67_0
veloxchem/linux-64::multipsi-0.5-py311hcb96c0e_126
defaults/noarch::munkres-1.1.4-py_0
conda-forge/noarch::nbclient-0.8.0-pyhd8ed1ab_0
conda-forge/noarch::nbconvert-core-7.14.0-pyhd8ed1ab_0
conda-forge/noarch::nbformat-5.9.2-pyhd8ed1ab_0
defaults/linux-64::nccl-2.21.5.1-ha515578_0
conda-forge/linux-64::ncurses-6.4-h59595ed_2
conda-forge/noarch::nest-asyncio-1.5.8-pyhd8ed1ab_0
conda-forge/noarch::networkx-3.2.1-pyhd8ed1ab_0
conda-forge/noarch::nglview-3.1.2-pyh15ce09e_0
conda-forge/linux-64::ninja-1.11.1-h924138e_0
conda-forge/noarch::notebook-shim-0.2.3-pyhd8ed1ab_0
pypi/pypi::nptyping-2.5.0-pypi_0
conda-forge/linux-64::ntpoly-2.7.1-mpi_openmpi_h113680b_1
pypi/pypi::numba-0.59.1-pypi_0
defaults/linux-64::numexpr-2.8.7-py311h65dcdc2_0
defaults/linux-64::numpy-1.25.2-py311h08b1b3b_0
defaults/linux-64::numpy-base-1.25.2-py311hf175353_0
conda-forge/linux-64::nwchem-7.2.2-py311_mpi_ts_h16b6749_1005
conda-forge/linux-64::ocl-icd-2.3.1-h7f98852_0
conda-forge/linux-64::ocl-icd-system-1.0.0-1
conda-forge/linux-64::oclgrind-21.10-hd56c0c9_0
conda-forge/linux-64::openblas-0.3.27-openmp_h82c68e4_0
defaults/linux-64::openjpeg-2.4.0-h3ad879b_0
conda-forge/linux-64::openmpi-4.1.6-hc5af2df_101
conda-forge/linux-64::openssh-9.6p1-h2d3b35a_0
conda-forge/linux-64::openssl-3.3.1-h4ab18f5_0
conda-forge/noarch::optking-0.2.1-pyhd8ed1ab_0
conda-forge/noarch::overrides-7.4.0-pyhd8ed1ab_0
conda-forge/noarch::packaging-23.2-pyhd8ed1ab_0
defaults/noarch::palettable-3.3.0-pyhd3eb1b0_0
pypi/pypi::pandas-1.5.3-pypi_0
conda-forge/noarch::pandocfilters-1.5.0-pyhd8ed1ab_0
conda-forge/noarch::parso-0.8.3-pyhd8ed1ab_0
pypi/pypi::patsy-0.5.6-pypi_0
conda-forge/noarch::pcmsolver-1.2.3-py_8
pypi/pypi::periodictable-1.7.0-pypi_0
conda-forge/noarch::pexpect-4.8.0-pyh1a96a4e_2
conda-forge/linux-64::phonopy-2.22.0-py311h1f0f07a_0
conda-forge/noarch::pickleshare-0.7.5-py_1003
defaults/linux-64::pillow-10.2.0-py311h5eee18b_0
conda-forge/noarch::pint-0.23-pyhd8ed1ab_0
conda-forge/noarch::pip-23.3.2-pyhd8ed1ab_0
conda-forge/noarch::pkgutil-resolve-name-1.3.10-pyhd8ed1ab_1
conda-forge/noarch::platformdirs-4.1.0-pyhd8ed1ab_0
defaults/linux-64::plotly-5.19.0-py311h92b7b1e_0
conda-forge/noarch::pluggy-1.3.0-pyhd8ed1ab_0
conda-forge/linux-64::plumed-2.9.0-mpi_openmpi_h7b2badc_0
conda-forge/linux-64::pocl-4.0-h03a6ac1_0
conda-forge/linux-64::pocl-core-4.0-h311816e_0
conda-forge/linux-64::pocl-cpu-4.0-h3e62441_0
conda-forge/linux-64::pocl-cpu-minimal-4.0-h3e62441_0
conda-forge/linux-64::pocl-cuda-4.0-hbf37380_0
conda-forge/noarch::prometheus_client-0.19.0-pyhd8ed1ab_0
conda-forge/noarch::prompt-toolkit-3.0.42-pyha770c72_0
conda-forge/noarch::prompt_toolkit-3.0.42-hd8ed1ab_0
conda-forge/linux-64::psi4-1.9.1-py311hed31b30_1
conda-forge/linux-64::psutil-5.9.7-py311h459d7ec_0
conda-forge/noarch::ptyprocess-0.7.0-pyhd3deb0d_0
conda-forge/linux-64::pugixml-1.14-h59595ed_0
conda-forge/noarch::pure_eval-0.2.2-pyhd8ed1ab_0
pypi/pypi::py-1.11.0-pypi_0
conda-forge/noarch::py-cpuinfo-9.0.0-pyhd8ed1ab_0
pypi/pypi::pybest-2.0.0-pypi_0
pypi/pypi::pybind11-2.10.4-pypi_0
conda-forge/noarch::pybind11-abi-4-hd8ed1ab_3
conda-forge/noarch::pybtex-0.24.0-pyhd8ed1ab_2
conda-forge/noarch::pycparser-2.21-pyhd8ed1ab_0
conda-forge/noarch::pydantic-2.5.3-pyhd8ed1ab_0
conda-forge/linux-64::pydantic-core-2.14.6-py311h46250e7_1
ifilot/noarch::pydft-0.6.0-pyh4f56d60_0
pypi/pypi::pyfiglet-0.8.post1-pypi_0
conda-forge/noarch::pygments-2.17.2-pyhd8ed1ab_0
pypi/pypi::pyh5md-1.0.0-pypi_0
pypi/pypi::pylatexenc-2.10-pypi_0
ifilot/noarch::pylebedev-1.1.0-pyh4f56d60_0
conda-forge/linux-64::pymatgen-2024.3.1-py311h1f0f07a_0
pypi/pypi::pyopengl-3.1.7-pypi_0
pypi/pypi::pyparsing-3.1.1-pypi_0
ifilot/linux-64::pyqint-0.17.1-py311h410524c_0
pypi/pypi::pyqmc-0.6.0-pypi_0
pypi/pypi::pyqtgraph-0.13.3-pypi_0
conda-forge/linux-64::pyscf-2.6.2-py311hf06716a_0
pypi/pypi::pyscf-dispersion-1.0.2-pypi_0
pypi/pypi::pyside6-6.6.1-pypi_0
pypi/pypi::pyside6-addons-6.6.1-pypi_0
pypi/pypi::pyside6-essentials-6.6.1-pypi_0
conda-forge/noarch::pysocks-1.7.1-pyha2e5f31_6
ifilot/linux-64::pytessel-1.2.0-py311he53d0f1_0
conda-forge/noarch::pytest-7.4.4-pyhd8ed1ab_0
pypi/pypi::pytest-durations-1.2.0-pypi_0
pypi/pypi::pytest-forked-1.6.0-pypi_0
pypi/pypi::pytest-xdist-2.5.0-pypi_0
conda-forge/linux-64::python-3.11.7-hab00c5b_1_cpython
conda-forge/noarch::python-dateutil-2.8.2-pyhd8ed1ab_0
conda-forge/noarch::python-fastjsonschema-2.19.1-pyhd8ed1ab_0
conda-forge/noarch::python-json-logger-2.0.7-pyhd8ed1ab_0
defaults/noarch::python-tzdata-2023.3-pyhd3eb1b0_0
conda-forge/linux-64::python_abi-3.11-4_cp311
conda-forge/linux-64::pytorch-2.3.1-cuda120_py311hf6aebf0_300
conda-forge/noarch::pytz-2023.3.post1-pyhd8ed1ab_0
conda-forge/linux-64::pyyaml-6.0.1-py311h459d7ec_1
conda-forge/linux-64::pyzmq-25.1.2-py311h34ded2d_0
conda-forge/noarch::qcelemental-0.27.1-pyhd8ed1ab_0
conda-forge/noarch::qcengine-0.29.0-pyhd8ed1ab_0
ifilot/noarch::quantumsculpt-0.2.0-pyhac7e3b6_0
conda-forge/linux-64::readline-8.2-h8228510_1
conda-forge/noarch::referencing-0.32.0-pyhd8ed1ab_0
conda-forge/linux-64::regex-2023.12.25-py311h459d7ec_0
conda-forge/noarch::requests-2.31.0-pyhd8ed1ab_0
conda-forge/noarch::rfc3339-validator-0.1.4-pyhd8ed1ab_0
conda-forge/noarch::rfc3986-validator-0.1.1-pyh9f0ad1d_0
conda-forge/linux-64::rpds-py-0.16.2-py311h46250e7_0
defaults/linux-64::ruamel.yaml-0.17.21-py311h5eee18b_0
defaults/linux-64::ruby-3.2.2-h2d74bed_0
conda-forge/linux-64::scalapack-2.2.0-h67de57e_1
conda-forge/linux-64::scalapackfx-1.2-mpi_openmpi_hcecb6a8_0
pypi/pypi::scikit-image-0.22.0-pypi_0
conda-forge/linux-64::scipy-1.13.0-py311h517d4fd_1
conda-forge/noarch::seekpath-2.1.0-pyhd8ed1ab_0
conda-forge/noarch::send2trash-1.8.2-pyh41d4057_0
conda-forge/noarch::setuptools-65.3.0-pyhd8ed1ab_1
conda-forge/noarch::setuptools-scm-6.3.2-pyhd8ed1ab_0
conda-forge/noarch::setuptools_scm-6.3.2-hd8ed1ab_0
pypi/pypi::shiboken6-6.6.1-pypi_0
conda-forge/linux-64::simple-dftd3-1.0.0-hd59d2e7_0
conda-forge/noarch::six-1.16.0-pyh6c4a22f_0
conda-forge/linux-64::sleef-3.5.1-h9b69904_2
conda-forge/noarch::sniffio-1.3.0-pyhd8ed1ab_0
conda-forge/noarch::soupsieve-2.5-pyhd8ed1ab_1
conda-forge/linux-64::spglib-2.3.1-py311hf7cfcf7_0
pypi/pypi::sqlalchemy-1.4.52-pypi_0
conda-forge/linux-64::sqlite-3.44.2-h2c6b66d_0
conda-forge/noarch::stack_data-0.6.2-pyhd8ed1ab_0
pypi/pypi::statsmodels-0.14.2-pypi_0
conda-forge/noarch::sumo-2.3.8-pyhd8ed1ab_0
conda-forge/noarch::sympy-1.12-pypyh9d50eac_103
defaults/linux-64::tabulate-0.9.0-py311h06a4308_0
conda-forge/linux-64::tbb-2021.9.0-hf52228f_0
conda-forge/linux-64::tblite-0.3.0-hf49bc11_1
defaults/linux-64::tenacity-8.2.2-py311h06a4308_0
conda-forge/noarch::terminado-0.18.0-pyh0d859eb_0
pypi/pypi::tifffile-2023.12.9-pypi_0
conda-forge/noarch::tinycss2-1.2.1-pyhd8ed1ab_0
conda-forge/linux-64::tk-8.6.13-noxft_h4845f30_101
conda-forge/linux-64::toml-f-0.4.2-hd8f1df9_0
conda-forge/noarch::tomli-2.0.1-pyhd8ed1ab_0
conda-forge/linux-64::torchani-2.2.4-cuda120py311h9a49aa5_8
conda-forge/linux-64::tornado-6.3.3-py311h459d7ec_1
defaults/linux-64::tqdm-4.65.0-py311h92b7b1e_0
conda-forge/noarch::traitlets-5.14.1-pyhd8ed1ab_0
conda-forge/noarch::types-python-dateutil-2.8.19.14-pyhd8ed1ab_0
pypi/pypi::typing-3.7.4.3-pypi_0
conda-forge/noarch::typing-extensions-4.9.0-hd8ed1ab_0
conda-forge/noarch::typing_extensions-4.9.0-pyha770c72_0
conda-forge/noarch::typing_utils-0.1.0-pyhd8ed1ab_0
conda-forge/noarch::tzdata-2023d-h0c530f3_0
conda-forge/noarch::uncertainties-3.1.7-pyhd8ed1ab_0
conda-forge/noarch::unidecode-1.3.7-pyhd8ed1ab_0
conda-forge/noarch::uri-template-1.3.0-pyhd8ed1ab_0
conda-forge/noarch::urllib3-2.1.0-pyhd8ed1ab_0
veloxchem/linux-64::veloxchem-1.0rc3-py311hcb96c0e_141
pypi/pypi::versioneer-0.29-pypi_0
conda-forge/linux-64::votca-2024-py311h3e0a565_0
conda-forge/noarch::wcwidth-0.2.12-pyhd8ed1ab_0
conda-forge/noarch::webcolors-1.13-pyhd8ed1ab_0
conda-forge/noarch::webencodings-0.5.1-pyhd8ed1ab_2
conda-forge/noarch::websocket-client-1.7.0-pyhd8ed1ab_0
defaults/linux-64::werkzeug-2.3.8-py311h06a4308_0
conda-forge/noarch::wheel-0.42.0-pyhd8ed1ab_0
defaults/linux-64::widgetsnbextension-4.0.10-py311h06a4308_0
conda-forge/linux-64::xcfun-2.1.1-h64516f0_7
conda-forge/linux-64::xeus-3.0.5-hac2b420_1
conda-forge/linux-64::xeus-zmq-1.0.3-h0541b36_0
conda-forge/linux-64::xtb-6.6.1-hf49bc11_0
defaults/linux-64::xz-5.4.5-h5eee18b_0
conda-forge/linux-64::yaml-0.2.5-h7f98852_2
conda-forge/linux-64::zeromq-4.3.5-h59595ed_0
conda-forge/noarch::zipp-3.17.0-pyhd8ed1ab_0
conda-forge/linux-64::zlib-1.2.13-hd590300_5
conda-forge/linux-64::zstd-1.5.6-ha6fb4c9_0

         conda version : 24.5.0
    conda-build version : not installed
         python version : 3.11.7.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=zen4
                          __conda=24.5.0=0
                          __cuda=12.4=0
                          __glibc=2.38=0
                          __linux=6.9.3=0
                          __unix=0=0
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
               platform : linux-64
             user-agent : conda/24.5.0 requests/2.31.0 CPython/3.11.7 Linux/6.9.3-76060903-generic pop/22.04 glibc/2.38 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.7
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
`

**Comment by chillenb** [comment]
There really shouldn't be `libcint.so.5` anywhere in your environment, since it doesn't belong to any of those packages! Would you mind pasting the output from `ls $CONDA_PREFIX/lib`?

**Comment by chrinide** [comment]
> There really shouldn't be `libcint.so.5` anywhere in your environment, since it doesn't belong to any of those packages! Would you mind pasting the output from `ls -alh $CONDA_PREFIX/lib`?

pyscf version 2.5 use libcint 5, I updated pyscf from version 2.5 to version 2.6.2, during the updation, the conda env also updated pyscf version 2.5 corresponding libcint5 to libcint6.

So, this is could be a possible reason?

if  I use a clean conda env, install pyscf 2.6.2 directly, there is no issue

**Comment by chillenb** [comment]
I tried reproducing this bug by installing pyscf 2.5 from conda-forge and upgrading it to 2.6.2, but there were no problems whatsoever. Everything worked as expected.

If you do `ls -alh $CONDA_PREFIX/lib`, you might get useful info about why there is a symlink to the wrong libcint in your environment.

**Comment by chrinide** [comment]
> ls -alh $CONDA_PREFIX/lib

Thanks so much for your information.

I have created a new conda env, then install pyscf 2.5 than updated to 2.6.2, there is no issue.

It seems  that, this is a my conda-env-own related
