### ISSUE TITLE
How to calculate localized orbital values in real-space grids?

### ISSUE THREAD

**Issue by ustcwdd** [pyscf/pyscf#2294]
We can use methods in 'lo' module like Pipek-Mezey method to transfer delocalized molecular orbitals to localized orbitals and it returns a 2D-array with coefficients of orbitals. But how can we calculate localized orbital values in real-space grids?
Is this correct to calculate as the code in pyscf.tools.chgcar.orbital?  Assuming we have performed the PM calculation and get coefficients of localized orbitals :

```
coords = numpy.random.random((100,3))
ngrids = 1e6
nx, ny, nz = 100, 100, 100
blksize = min(8000, ngrids)
orb_on_grid = numpy.empty(ngrids)
for ip0, ip1 in lib.prange(0, ngrids, blksize):
      ao = cell.pbc_eval_gto('GTOval', coords[ip0:ip1])
      orb_on_grid[ip0:ip1] = numpy.dot(ao, coeff)
orb_on_grid = orb_on_grid.reshape(nx,ny,nz)

```
Looking forward from responses.

**Comment by fishjojo** [comment]
You are right, please refer to 
https://pyscf.org/pyscf_api_docs/pyscf.gto.html#module-pyscf.gto.eval_gto for molecular calculations and 
https://pyscf.org/pyscf_api_docs/pyscf.pbc.gto.html#module-pyscf.pbc.gto.eval_gto for solid calculations

**Comment by ustcwdd** [comment]
Dear fishjojo:

Thanks a lot for your confirmation!
