### ISSUE TITLE
scipy version comparison line behavior

### ISSUE THREAD

**Issue by MatthewRHermes** [pyscf/pyscf#2309]
https://github.com/pyscf/pyscf/blob/beb7b1bcb40dec578392322d20126826f2d3e6ad/pyscf/grad/lagrange.py#L195

This evaluates to "True" if the scipy version is between 1.2 and 1.10, which seems like not the desired behavior. Is there a reason these aren't casted to integers for the comparison?

**Comment by sunqm** [comment]
This is a bug. Could you create a PR to fix this?

**Comment by MatthewRHermes** [comment]
sure
