### ISSUE TITLE
Automatic (guess at) frozen core

### ISSUE THREAD

**Issue by lavroffrob13** [pyscf/pyscf#2312]
To my knowledge, the number of frozen orbitals for a correlated calc needs to always be specified manually in pySCF. If it aligns philosophically with the program, could a guess at the frozen core - based on number of the different elements in the molecule/solid - be added, either as a flag or default? A reordered guess could also be tried if there are mixed light and heavy elements where core orbitals of one and valence of the other may be close in energy (ORCA does this). 

Without the light/heavy feature, this would be a straightforward implementation that I'd be happy to write myself - I just want to make sure it hasn't been ruled out previously for some reason, or that I wasn't thorough enough and it already exists.

Thanks,

Rob

**Comment by hebrewsnabla** [comment]
See #1311.

**Comment by lavroffrob13** [comment]
Thank you!
