### ISSUE TITLE
DF grid mesh for PBC Gaussian density fitting

### ISSUE THREAD

**Issue by caperott** [pyscf/pyscf#2317]
In a PBC Gaussian density fitting calculation, the mesh grid in _RSNucBuilder differs from the one for _RSGDFBuilder, this last being equal to the grid defined in the input file using with_df.mesh. Should the mesh grids in _RSNucBuilder and _RSGDFBuilder be equal (and as given in the input file using with_df.mesh)?

Here is the input file,

from pyscf.pbc import gto, scf, cc, df

cell = gto.Cell()
cell.atom='''
C 0.000000000000   0.000000000000   0.000000000000
C 1.685068664391   1.685068664391   1.685068664391
'''
cell.basis = 'gth-dzv'
cell.pseudo = 'gth-pade'
cell.a = '''
0.000000000, 3.370137329, 3.370137329
3.370137329, 0.000000000, 3.370137329
3.370137329, 3.370137329, 0.000000000'''
cell.unit = 'B'
cell.verbose = 5
cell.build()

mf = scf.RHF(cell).density_fit()
mf.with_df.mesh = [21, 21, 21] 
mf.kernel()

and the extracts from the output file,

******** <class 'pyscf.pbc.df.rsdf_builder._RSNucBuilder'> ********
mesh = [9 9 9] (729 PWs)
ke_cutoff = 13.90351249895356
omega = 0.4833923954850985

******** <class 'pyscf.pbc.df.df.GDF'> ********
mesh = [21, 21, 21] (9261 PWs)

******** <class 'pyscf.pbc.df.rsdf_builder._RSGDFBuilder'> ********
mesh = [21 21 21] (9261 PWs)
ke_cutoff = 86.89695311845975
omega = 1.1431917494104598

**Comment by fishjojo** [comment]
Usually the pseudo potential integrals need less dense grid than the ERIs. But I'm not very sure if this is intended in the GDF code.

**Comment by caperott** [comment]
Thanks for the comment!
It seems, however, that class 'pyscf.pbc.df.rsdf_builder._RSNucBuilder' is called upon even in all-electron calculations.

from pyscf.pbc import gto, scf, df

cell = gto.Cell()
cell.atom='''
C 0.000000000000 0.000000000000 0.000000000000
C 1.685068664391 1.685068664391 1.685068664391
'''
cell.basis = 'gth-dzv'
####cell.pseudo = 'gth-pade'
cell.a = '''
0.000000000, 3.370137329, 3.370137329
3.370137329, 0.000000000, 3.370137329
3.370137329, 3.370137329, 0.000000000'''
cell.unit = 'B'
cell.verbose = 5
cell.build()

mf = scf.RHF(cell).density_fit()
mf.with_df.mesh = [21, 21, 21]
mf.kernel()

******** <class 'pyscf.pbc.df.rsdf_builder._RSNucBuilder'> ********
mesh = [9 9 9] (729 PWs)
ke_cutoff = 13.90351249895356
omega = 0.4833923954850985
