### ISSUE TITLE
CCSD doesn't clean up temporary files

### ISSUE THREAD

**Issue by kevinsung** [pyscf/pyscf#2318]
**Steps to reproduce**

1. Create `repro.py`:
```python
import pyscf
import pyscf.cc

mol = pyscf.gto.Mole()
mol.build(
    atom=[("H", (0, 0, 0)), ("H", (1, 0.0, 0.0))], basis="sto-6g", symmetry="Dooh"
)
scf = pyscf.scf.RHF(mol).run()
ccsd = pyscf.cc.RCCSD(scf).run()
```
2. Run it with the temporary directory set to the current directory.
```bash
TMPDIR="." python repro.py
```
3. Observe your current directory being filled with temporary files, even after the program has exited. E.g.
```
% ls
4yuc0gzd  6gm1i18c  bitvow4s  jfn4rd0w  lhuqcsi6  ny3jxku8  qthivsd4  repro.py  riuvukmw  rqan75l7
```

**Comment by chillenb** [comment]
I am sorry--this bug is something I introduced accidentally. The patch in #2320 should resolve it. (It works with your repro.py)

Best,
Chris
