### ISSUE TITLE
Spin-separated 3-RDMs?

### ISSUE THREAD

**Issue by brianz98** [pyscf/pyscf#2326]
Is there an easy way to access spin-separated 3-RDMs?

Spin-separated 1 and 2 RDMs are supported through the `make_rdm12s` method in the `direct_spin1` fcisolver. However, only spin-traced 3/4-RDMs are available through `fci.rdm.make_dm123(4)`. 

From what I can gather this is due to a lack of spin-separated RDM kernels for 3/4 RDMs, but spin-separated intermediates (t1/t2) seem to be available, so it might be trivial to implement the spin-separated kernels. However the RDM library is a little too opaque for me to get a PR started. Any help on this would be appreciated!

**Comment by MatthewRHermes** [comment]
A "hack" for this is to "map to the spinless representation", which is the phrase I use to describe pretending that the spin-down spinorbitals are actually just another set of spatial orbitals, and that all electrons are spin-up. If you can transpose and reshape the CI vector accordingly, then you can just use the spin-summed functions 3/4-RDM functions and then various diagonal blocks of the output will correspond to the various spin components. I have a [function](https://github.com/MatthewRHermes/mrh/blob/master/my_pyscf/lassi/op_o0.py#L54-L168) for the CI vector manipulations in [mrh](https://github.com/MatthewRHermes/mrh), which should be detachable:
```
from mrh.my_pyscf.lassi.op_o0 import civec_spinless_repr
# Assuming you have only one ci vector
ci_spinless = civec_spinless_repr ([ci,], norb, [(neleca,nelecb),])
```

In `ci_spinless`, the first `norb` orbitals are the up-spinorbitals, and the next `norb` are the down-spinorbitals. So for instance, for the 2-RDM:

```
# Look carefully at where the colons are
dm2_aa = dm2_spinless[:norb, :norb, :norb, :norb]
dm2_ab = dm2_spinless[:norb, :norb, norb:, norb:]
dm2_bb = dm2_spinless[norb:, norb:, norb:, norb:]
```

**Comment by brianz98** [comment]
Thank you so much @MatthewRHermes! I've tried the code and it's working for my test case. Seeing that there currently isn't a way to get spin-separated 3/4 RDMs (and that there's no major demand for an optimized way to get these quantities), do you think your code, as it stands, should go into PySCF proper? If so I'm happy to help with a PR if you're time-constrained.

**Comment by MatthewRHermes** [comment]
If you want to make a PR out of it, go ahead.
