### ISSUE TITLE
HF numerical stability problem for H4 square

### ISSUE THREAD

**Issue by dcyang** [pyscf/pyscf#2327]
Hi,

I've followed the [docs on FCI](https://pyscf.org/user/ci.html#full-configuration-interaction-fci) and (based on the examples) have tried FCI runs for the H4 square (so-called Paldus test) over a range of H-H distances $L$. I'm having difficulties reproducing the potential energy curves in [this JCTC paper](https://pubs.acs.org/doi/10.1021/acs.jctc.3c00038) from 2023, figures 1 and 2.

I was expecting a crossing between lowest energy states depending on the spin configuration -- triplet (3+1e) being lower for $L < 2.45 a_0$ and singlet (2+2e) lower for $L > 2.45 a_0$. But the energy curve for the singlet state comes out jagged, even from the RHF stage. Some of these jumps smooth out in the FCI stage but many of them carry over. So I'm thinking this is a numerical stability issue in the HF solvers. Can someone help get smooth, correct HF and FCI energies?

<img src="https://github.com/user-attachments/assets/e5edabbb-a36a-4561-a9ba-2a9e65728faa" width="300" />

Just to be thorough, I have tried this under different settings and environments.

* processors: i7-9700K, i7-13700K, Xeon Gold 6448Y
* single vs multiple threads
* different basis sets: DZVP, cc-pVDZ, cc-pVTZ
* SCF initial guesses: minao, 1e, atom, huckel, vsap (all except chk)

The Hückel guess seems to give fewer jumps, but doesn't remove them entirely. The problem otherwise is present in all of the above settings, with pyscf-2.6.2. Here's my script:

```python
from pyscf import gto, scf, fci

N_occA = 2
N_occB = 2

dL = 0.02
bsetName = "cc-pvdz"

with open("gh-issue.dat", "w") as f:
    print("# L    E_FCI       E_HF")
    f.write("# L\tE_FCI\tE_HF\n")

    L_bond = 1.5
    while L_bond <= 5.01:
        mol = gto.M(
                atom = [("H", (L_bond/2, L_bond/2, 0.0)), 
                        ("H", (-L_bond/2, L_bond/2, 0.0)), 
                        ("H", (-L_bond/2, -L_bond/2, 0.0)), 
                        ("H", (L_bond/2, -L_bond/2, 0.0))],
                basis = bsetName,
                verbose = 0,
                spin = N_occA - N_occB,
                unit = "Bohr")
        myhf = scf.RHF(mol)
        myhf.init_guess = "vsap"
        myhf.chkfile = "scf.chk"
        e_hf = myhf.kernel()

        # cisolver = fci.FCI(mol, myhf.mo_coeff)
        cisolver = fci.FCI(myhf)
        e_fci = cisolver.kernel()[0]

        # print('E(FCI) = %.12f' % cisolver.kernel()[0])
        print('{:.4f} {:.8f} {:.8f}'.format(L_bond, e_fci, e_hf))
        f.write("{:.4f}\t{:.8f}\t{:.8f}\n".format(L_bond, e_fci, e_hf))

        L_bond += dL
```
Any help will be greatly appreciated.

**Comment by dcyang** [comment]
Ok I was able to [pivot around](https://gist.github.com/dcyang/a6553e98137c2d3af506fa90f29faf4e) most of the RHF internal instabilities with `pyscf.scf.stability.rhf_internal()`.
But now the FCI solutions all converge to the triplet ground states instead of the singlet ground state (occasional downward jumps of "FCI singlet" in the plot above). Any help here?
<img src="https://github.com/user-attachments/assets/c8cd6982-ea5e-4fd0-9714-48d8f9a34285" width="300" />

**Comment by tberkel** [comment]
For any bond scan, you probably want to reuse the solution from a nearby
bond length. If you start this process from a limit where convergence is
easy, like equilibrium or perhaps fully dissociated, then you’ll get smooth
curves that track a single state. See examples/scf/16-h2_scan.py and
30-scan_pes.py

**Comment by dcyang** [comment]
Exactly what I needed. Thanks @tberkel !
