### ISSUE TITLE
Is it possible to calculate 1e-int between two basis sets?

### ISSUE THREAD

**Issue by FreemanTheMaverick** [pyscf/pyscf#2329]
Pyscf supports the 1e-int within one molecule. But is it possible to calculate the integrals between two basis sets from two molecules? That is to say, the rows and columns of the 1e-int matrix correspond to bases from two basis sets.

I know this can be done by combining the two molecules into one "super molecule" and using pyscf to calculate the super molecule's 1e-int matrix. The int I want will be at the off-diagonal block. Something like
```
1e-int  |  molA  |  molB
----------------------------
molA    | xxxxx    yyyyy
molB    | yyyyy    zzzzz
```
and `yyyyy` is the int between the two basis sets. But I wonder if there is any elegant way to achieve the same goal. Thanks for any clue!

**Comment by ilygatsika** [comment]
You can use the `shls_slice` argument of the `mole.intor` function in order to avoid calculating the entire super-molecule integral matrix. To calculate the off-diagonal block (molA|molB) only you will need to set the shell range as `shls_slice=(0, nA, nA, nB+nA)`, where `n=mol.nbas` for A and B.

**Comment by hebrewsnabla** [comment]
See
https://github.com/pyscf/pyscf/blob/8be06f819750812220b474d88c88b8d6fb32cec0/pyscf/gto/mole.py#L896-L926

**Comment by FreemanTheMaverick** [comment]
> You can use the `shls_slice` argument of the `mole.intor` function in order to avoid calculating the entire super-molecule integral matrix. To calculate the off-diagonal block (molA|molB) only you will need to set the shell range as `shls_slice=(0, nA, nA, nA+nB)`, where `n=mol.nbas` for A and B.

Thank you. :D

**Comment by FreemanTheMaverick** [comment]
> See
> 
> https://github.com/pyscf/pyscf/blob/8be06f819750812220b474d88c88b8d6fb32cec0/pyscf/gto/mole.py#L896-L926

谢谢。你的办法更简洁一些。
