### ISSUE TITLE
Lattice energy of molecular crystal

### ISSUE THREAD

**Issue by aizvorski** [pyscf/pyscf#2331]
I'm trying to calculate the lattice energy of a molecular crystal, here using benzene as an example.  The code below calculates one energy for the whole unit cell and another for a monomer in a much larger cell (still periodic though), using TPSS-D3/def2-TZVP and using RS-GDF density fitting; no k-point sampling, no pseudopotentials.

This runs without errors, and pretty fast.  The lattice energy comes out as 0.0044 (11.6 kJ/mol) which seems way out of whack for benzene (experiment 54.8 kJ/mol).

This is the first larger periodic calculation I've tried to do in PySCF so I don't know if I'm doing this right.  Could you please give some guidance about the appropriate settings, and what may be the reason for the large discrepancy with the expected result?

Possible issues I can think of:
- need k-point sampling and/or need to converge to thermodynamic limit (extrapolate as 1/Nk from eg 2x2x2 and 3x3x3 k-points)
- need a finer grid for density fitting, and/or need a different kind of density fitting method (eg FFT)
- need to calculate the monomer in a *much* larger periodic box, or in a non-periodic system
- need to minimize/relax both the crystal and the monomer
- wrong functional for this type of problem (I've tried a few others, the results are similar roughly 10-20 kJ/mol)
- D3 dispersion not implemented correctly (the sample code in the pyscf docs doesn't work, I had to copy a bit from the simple-dftd3 docs)
- numeric issue, eg finer DFT grids, tighter SCF convergence, etc

Any suggestions would be greatly appreciated - Thank you!

***UPDATE***

I changed the code to use KRKS from RKS, and tried some other functionals, and up to 3x3x3 k-points grid.

Here are the results:
PBE-D3 / def2-SVP, k-points 1 x 1 x 1: E_latt = -28.1 kJ/mol
PBE-D3 / def2-SVP, k-points 2 x 2 x 2: E_latt = -27.3 kJ/mol
PBE-D3 / def2-SVP, k-points 3 x 3 x 3: E_latt = -27.3 kJ/mol
PBE-D3 / def2-TZVP, k-points 1 x 1 x 1: E_latt = -19.6 kJ/mol
PBE-D3 / def2-TZVP, k-points 2 x 2 x 2: E_latt = -18.5 kJ/mol
PBE-D3 / def2-TZVP, k-points 3 x 3 x 3: E_latt = -18.5 kJ/mol

The difference between 2x2x2 and 3x3x3 is small, < 0.005 kJ/mol in every case tested.  The difference between SVP and TZVP basis is significant, ~9 kJ/mol but the larger basis produces a smaller lattice energy. For all settings, the lattice energy is less than expected.

Code:

```
from pyscf.pbc import gto, scf, dft
import dftd3.pyscf as disp

xc = 'TPSS'
basis =  'def2-TZVP'
kpts_num = [1,1,1]
hartree_to_kJ_mol = 2625.4996395

cell = gto.M(
    atom='''
        C  -0.4233   1.3245  -0.0373
        C  -0.9932   0.4393   0.8746
        C   0.5758   0.8833  -0.8961
        H  -0.7261   2.3368  -0.1224
        H  -1.7922   0.7582   1.5348
        H   1.0200   1.5576  -1.5999
        C  -0.5758  -0.8833   0.8961
        C   0.9932  -0.4393  -0.8746
        C   0.4233  -1.3245   0.0373
        H  -1.0200  -1.5576   1.5999
        H   1.7922  -0.7582  -1.5348
        H   0.7261  -2.3368   0.1224
        C   4.7132  -0.4393   4.3346
        C   2.7267   0.4393   2.5853
        C   3.1441  -0.8833   2.5638
        C   4.2958   0.8833   4.3561
        H   4.4461  -2.3368   3.3375
        H   2.9938   2.3368   3.5824
        H   5.5123  -0.7582   4.9948
        H   1.9277   0.7582   1.9251
        H   2.6999  -1.5576   1.8601
        H   4.7400   1.5576   5.0598
        C   3.2966   1.3245   3.4973
        C   4.1433  -1.3245   3.4226
        C   0.9932   5.2143   2.5853
        C  -0.9932   4.3357   4.3346
        C  -0.5758   5.6583   4.3561
        C   0.5758   3.8916   2.5638
        H   0.7261   7.1118   3.5824
        H  -0.7261   2.4381   3.3375
        H   1.7922   5.5332   1.9251
        H  -1.7922   4.0167   4.9948
        H  -1.0200   6.3326   5.0598
        H   1.0200   3.2174   1.8601
        C  -0.4233   3.4504   3.4226
        C   0.4233   6.0995   3.4973
        C   2.7267   4.3357  -0.8746
        C   4.7132   5.2143   0.8746
        C   4.2958   3.8916   0.8961
        C   3.1441   5.6583  -0.8961
        H   2.9938   2.4381   0.1224
        H   4.4461   7.1118  -0.1224
        H   1.9277   4.0167  -1.5348
        H   5.5123   5.5332   1.5348
        H   4.7400   3.2174   1.5999
        H   2.6999   6.3326  -1.5999
        C   4.1433   6.0995  -0.0373
        C   3.2966   3.4504   0.0373
        ''',
    a=[[7.44, 0,    0  ],
       [0,    9.55, 0  ],
       [0,    0,    6.92]],
    basis = basis,
)
cell.verbose = 4
kpts = cell.make_kpts(kpts_num)
mf = dft.KRKS(cell, kpts, xc=xc).rs_density_fit().run()
e_disp = float(disp.DFTD3Dispersion(cell, xc=xc, version="d3bj").kernel()[0])
e_whole_cell = mf.e_tot + e_disp
print('e_disp_whole_cell', e_disp)
print('e_whole_cell', e_whole_cell)

cell = gto.M(
    atom='''
        C  -0.4233   1.3245  -0.0373
        C  -0.9932   0.4393   0.8746
        C   0.5758   0.8833  -0.8961
        H  -0.7261   2.3368  -0.1224
        H  -1.7922   0.7582   1.5348
        H   1.0200   1.5576  -1.5999
        C  -0.5758  -0.8833   0.8961
        C   0.9932  -0.4393  -0.8746
        C   0.4233  -1.3245   0.0373
        H  -1.0200  -1.5576   1.5999
        H   1.7922  -0.7582  -1.5348
        H   0.7261  -2.3368   0.1224
        ''',
    a=[[30, 0, 0],
       [0, 30, 0],
       [0, 0, 30]],
    basis = basis,
)
cell.verbose = 4
kpts = cell.make_kpts(kpts_num)
mf = dft.KRKS(cell, kpts, xc=xc).rs_density_fit().run()
e_disp = float(disp.DFTD3Dispersion(cell, xc=xc, version="d3bj").kernel()[0])
e_monomer = mf.e_tot + e_disp
print('e_disp_monomer', e_disp)
print('e_monomer', e_monomer)

n_molecules = 4

e_latt = e_whole_cell / n_molecules - e_monomer
print('e_latt', e_latt)
```

Versions: pyscf=2.6.2 simple-dftd3=1.0.0 both from conda-forge

**Comment by tberkel** [comment]
This looks pretty good to me on a skim, so maybe it's just a finite size effect (k-point mesh too small). Even just doing 2x2x2 will tell you if it's going in the right direction. There's a fair bit of data on DFT cohesive energies of molecular crystals (e.g., see the X23 dataset), so I'd suggest picking a functional that has results reported in the literature, so that you know what to expect.

A small suggestion: to eliminate basis set superposition error, you should actually calculate the single molecule energy surrounded by the ghost basis functions of the other molecules in the crystal. You can also do this as a molecular calculation instead of a periodic one with a big box. But correcting for BSSE will only maker your cohesive energy smaller (in magnitude) so it won't bring you closer to experiment.

**Comment by aizvorski** [comment]
@tberkel Thanks for looking it over!

I found a paper that benchmarks DFT on X23 using settings that can be reproduced in PySCF: Stein & Heimstaat 2019 https://doi.org/10.3390/cryst9120665 They use Turbomole with a periodic DFT calculation with GTOs, PBE-D3/def2-TZVP and a 3x3x3 k-points grid.  Their result for benzene is E_latt = -58.41 kJ/mol.

I updated the code above to use KRKS and tried to reproduce that.

Results:
PBE-D3 / def2-SVP, k-points 1x1x1: E_latt = -28.1 kJ/mol
PBE-D3 / def2-SVP, k-points 2x2x2: E_latt = -27.3 kJ/mol
PBE-D3 / def2-SVP, k-points 3x3x3: E_latt = -27.3 kJ/mol
PBE-D3 / def2-TZVP, k-points 1x1x1: E_latt = -19.6 kJ/mol
PBE-D3 / def2-TZVP, k-points 2x2x2: E_latt = -18.5 kJ/mol
PBE-D3 / def2-TZVP, k-points 3x3x3: E_latt = -18.5 kJ/mol

PBE gives a bit higher numbers than TPSS, but both are still very low compared to what is expected. Larger basis set also gives lower numbers.

What am I doing wrong?

**Comment by aizvorski** [comment]
One possible clue: the D3 dispersion correction is *exactly* the same for any number of k-points.  Is it possible that it is calculating the dispersion for a non-periodic system with the same atoms?

**Comment by tberkel** [comment]
That's a good guess. As you see, `dftd3` is developed outside of PySCF and I forget about its PBC support. You can do a molecular calculation of the unit cell atoms to confirm if it's the same number.

If you want to check your workflow, you could do periodic HF (a bit more expensive than semilocal DFT) without any D3. In [this paper](https://pubs.acs.org/doi/full/10.1021/acs.jctc.2c00640), we show data for the HF cohesive energy of benzene (and Fig. 2 has the convergence with Nk).

**Comment by aizvorski** [comment]
@tberkel Yep, that was it, D3 gives same results for periodic and non-periodic systems:

non-periodic D3 dispersion
e_disp_whole_cell -0.0601768700590702
e_disp_monomer -0.011005613704864196

periodic D3 dispersion (number of k-points doesn't matter)
e_disp_whole_cell -0.0601768700590702
e_disp_monomer -0.011005613704864197

`import dftd3.pyscf as disp` pulls in simple-dftd3=1.0.0.  Is this the correct library?

The library itself does seem to support periodic systems via `dftd3.interface.Structure(..., lattice=...)` ([link](https://dftd3.readthedocs.io/en/latest/api/python.html#dftd3.interface.Structure)) but perhaps the pyscf interface to it doesn't pass the info about the periodic box?

**Comment by aizvorski** [comment]
Opened issue in the other project here: https://github.com/dftd3/simple-dftd3/issues/73

**Comment by sunqm** [comment]
> @tberkel Yep, that was it, D3 gives same results for periodic and non-periodic systems:
> 
> non-periodic D3 dispersion e_disp_whole_cell -0.0601768700590702 e_disp_monomer -0.011005613704864196
> 
> periodic D3 dispersion (number of k-points doesn't matter) e_disp_whole_cell -0.0601768700590702 e_disp_monomer -0.011005613704864197
> 
> `import dftd3.pyscf as disp` pulls in simple-dftd3=1.0.0 ([link](https://github.com/dftd3/simple-dftd3/blob/main/python/dftd3/pyscf.py)). Is this the correct library?
> 
> The library itself does seem to support periodic systems via `dftd3.interface.Structure(..., lattice=...)` ([link](https://dftd3.readthedocs.io/en/latest/api/python.html#dftd3.interface.Structure)) but perhaps the pyscf interface to it doesn't pass the info about the periodic box?

simple-dftd3 is the correct one. However, its pyscf interface does not implement the PBC code

**Comment by aizvorski** [comment]
@tberkel "A small suggestion: to eliminate basis set superposition error, you should actually calculate the single molecule energy surrounded by the ghost basis functions of the other molecules in the crystal."

Thanks!  Now I'm wondering which is better for the single molecule calculation: periodic with same size cell and ghost basis functions (for everything else in the cell), or periodic with large cell and no ghost basis functions, or non-periodic with ghost basis functions?

If non-periodic, how to select how many/which ghost atoms?  Do they have to be complete molecules?

Do you usually calculate just one monomer, or repeat that for every monomer? (they don't always have identical geometries)

**Comment by tberkel** [comment]
The best choice (I think) is non-periodic with ghost basis functions. [You could also do a large periodic (super)cell with all ghosts except one molecule but this is probably more expensive than the non-periodic version without much benefit.]

We usually select ghost atoms to belong to complete molecules based on their distance from the central molecule (i.e., adding ghosts in "shells") and try to monitor for convergence with respect to number of ghost molecules or number of shells. In principle, they don't have to be complete molecules.

You should probably do this calculation for all unique monomers (in the case where they have different geometries). And if you're also including the energy of the geometry change of an isolated monomer (a "relaxation energy"), then you'll have only a single optimized geometry of the isolated monomer, but different relaxation energies for each different monomer geometry in the crystal. (Hope that made sense ...)
