### ISSUE TITLE
Getting exact diagonalize eigenvalues in MCSCF

### ISSUE THREAD

**Issue by bsonghao** [pyscf/pyscf#2332]
Hello, 

     May I ask is there a way to get all energy eigenvalues for exact diagonalization in the MCSCF module? 

Thanks.

**Comment by jamesETsmith** [comment]
@bsonghao this example does what you're looking for:

https://github.com/pyscf/pyscf/blob/bf0b1db22556a3c1b4c34426ea8627e636c1b096/examples/fci/15-FCI_hamiltonian.py#L31-L32

**Comment by bsonghao** [comment]
> @bsonghao this example does what you're looking for:
> 
> https://github.com/pyscf/pyscf/blob/bf0b1db22556a3c1b4c34426ea8627e636c1b096/examples/fci/15-FCI_hamiltonian.py#L31-L32

Hello, 

   Thanks for you response. In this example, may I ask how to determine the total number of determinant? 
I though for (8e,7orb) should be 14!/(8!(14-8!)) = 3003 not 1225? Where is the number 1225 comes from?

Thanks.

**Comment by bsonghao** [comment]
> @bsonghao this example does what you're looking for:
> 
> https://github.com/pyscf/pyscf/blob/bf0b1db22556a3c1b4c34426ea8627e636c1b096/examples/fci/15-FCI_hamiltonian.py#L31-L32

Hello, 

    I figure it our, the number of alpha electrons and number of beta electrons should be fixed the total number of determinants should be:
``
Alpha_config = factorial(norb) / (factorial(nelec_alpha) * factorial(norb - nelec_alpha))
Beta_config =  factorial(norb) / (factorial(nelec_beta) * factorial(norb - nelec_beta))
np = Alpha_config * Beta_config
``

Thanks again
