### ISSUE TITLE
Getting dE_k/dk from SCF pbc module

### ISSUE THREAD

**Issue by zyt329** [pyscf/pyscf#2335]
Dear developer,

I'm recently struggling to get the derivative $$dE_k/dk$$ of the band energy $$E_k$$ with respect to k. I wonder if there's a method in the pbc module that can do this easily. One method I thought of is to calculate $$E_k$$ on different k mesh and do finite differentiation, but that sounds very costly and inaccurate. 

Another method I have in mind is to calculate $$dE_k/dk$$ through the velocity(momentum) operator. To do this, I need to evaluate the momentum operator integral between all the basis functions. And would also need the wave function after the SCF calculation. Are those attributes easily obtained in PySCF?

Please let me if you know of a better method as well! 

I'm new to PySCF and I'm sorry if the questions is obvious. And thank you so much for your help in advance!

Best,
zyt_329

**Comment by tberkel** [comment]
I don't think there's anything super automated to do this. However, you can use the `get_bands()` function to do a non-self-consistent evaluation of the band energies, which should significantly lower the cost of doing finite differences. This is how one would normally calculate a smooth band structure. See for example https://github.com/pyscf/pyscf/blob/master/examples/pbc/09-band_ase.py

**Comment by zyt329** [comment]
Thank you so much, that's extremely helpful!
