### ISSUE TITLE
Unrestricted selected CI

### ISSUE THREAD

**Issue by stefabat** [pyscf/pyscf#2338]
Is it possible to use the builtin SCI implementation with unrestricted MOs?
I have tried to pass to the `kernel()` function of the `SCI` object one- and two-electron integrals with shapes `h1e.shape == (2, norb, norb)` and `h2e.shape = (3, norb, norb, norb, norb)` without success.

Maybe there is another way?

**Comment by sanshar** [comment]
Which module/branch are you using in pyscf. Maybe you can share the
relevant parts of the input file.

Sandeep.

**Comment by stefabat** [comment]
Hi Sandeep,

Sorry, it was an issue opened with a lot of rush.
I am using pyscf 2.6.2 installed with pip, within a miniconda environment based on python 3.11.8.

I just modified the code in https://github.com/pyscf/pyscf/blob/master/examples/fci/02-selected_ci_mol.py
to an unrestricted HF calculation and adapted the 1- and 2-electron Hamiltonians. 
```python
mol = gto.Mole()
mol.atom = "H 0 0 0; H 0 0 1.2; H 0 0 2.4; H 0 0 3.6"
mol.unit='angstrom'
mol.basis = "631g"
mol.build()

mf = scf.UHF(mol)
mf.kernel()

# Rotate the Hamiltonians
norb = mol.nao
nelec = mol.nelectron
mo_coeff = mf.mo_coeff
h1e = mf.get_hcore()
eri = mf._eri

h1e_mo = np.zeros((2, norb, norb))
h1e_mo[0] = mo_coeff[0].T @ h1e @ mo_coeff[0]
h1e_mo[1] = mo_coeff[1].T @ h1e @ mo_coeff[1]

eri_mo = np.zeros((3, norb, norb, norb, norb))
eri_mo[0] = ao2mo.kernel(eri, mo_coeff[0], compact=False).reshape(norb, norb, norb, norb)
eri_mo[1] = ao2mo.kernel(eri, mo_coeff[0], mo_coeff[0], mo_coeff[1], mo_coeff[1], compact=False).reshape(norb, norb, norb, norb)
eri_mo[2] = ao2mo.kernel(eri, mo_coeff[1], compact=False).reshape(norb, norb, norb, norb)

e_nuc = mf.energy_nuc()

# Run SCI
scisolver = fci.SCI()
scisolver.max_cycle = 100
scisolver.conv_tol = 1e-8
scisolver.nroots = 1
e, civec = scisolver.kernel(h1e_mo, eri_mo, norb, (2,2))
e_sci = e + e_nuc # add nuclear energy
print("Selected CI energy: {}".format(e_sci))
```
running this code results in the following error:
```python
{
	"name": "RuntimeError",
	"message": "eri.size = 12288, norb = 8",
	"stack": "---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[5], line 33
     31 scisolver.conv_tol = 1e-8
     32 scisolver.nroots = 1
---> 33 e, civec = scisolver.kernel(h1e_mo, eri_mo, norb, (2,2))
     34 e_sci = e + e_nuc # add nuclear energy
     35 print(\"Selected CI energy: {}\".format(e_sci))

File ~/Miniconda/lib/python3.11/site-packages/pyscf/fci/selected_ci.py:377, in kernel_float_space(myci, h1e, eri, norb, nelec, ci0, tol, lindep, max_cycle, max_space, nroots, davidson_only, max_memory, verbose, ecore, **kwargs)
    374         myci.check_sanity()
    376     nelec = direct_spin1._unpack_nelec(nelec, myci.spin)
--> 377     h2e = direct_spin1.absorb_h1e(h1e, eri, norb, nelec, .5)
    378     h2e = ao2mo.restore(1, h2e, norb)
    380 # TODO: initial guess from CISD

File ~/Miniconda/lib/python3.11/site-packages/pyscf/fci/direct_spin1.py:186, in absorb_h1e(h1e, eri, norb, nelec, fac)
    184 if not isinstance(nelec, (int, numpy.number)):
    185     nelec = sum(nelec)
--> 186 h2e = ao2mo.restore(1, eri.copy(), norb)
    187 f1e = h1e - numpy.einsum('jiik->jk', h2e) * .5
    188 f1e = f1e * (1./(nelec+1e-100))

File ~/Miniconda/lib/python3.11/site-packages/pyscf/ao2mo/addons.py:188, in restore(symmetry, eri, norb, tao)
    185         return eri.reshape(npair,norb,norb)
    187 else:
--> 188     raise RuntimeError('eri.size = %d, norb = %d' % (eri.size, norb))

RuntimeError: eri.size = 12288, norb = 8"
}
```

Notice that if I define `fcisolver = fci.direct_uhf.FCI()` instead of `scisolver`, the same piece of code works.

I looked a bit in the code, and instantiating the `SCI` object from either `fci.direct_spin1` or `fci.direct_uhf` is not possible. In the `restore` function (and also in `absorb_h1e`) it appears that there is no logic implemented for the case in which the `eri` numpy array passed has 3 dimensions, with the first one of size 3 accounting for the MOs combinations `aaaa` `aabb` `bbbb`.
Hence, I feel that unrestricted SCI is currently not supported.

However, it seems to me that in the SCI solver the alpha and beta components are treated explicitly, such that supporting unrestricted MOs should not be too difficult to implement?

Thanks,
Stefano

**Comment by sanshar** [comment]
HI Stefano,

  I think it is correct that the SCI does not support UHF but like you
mentioned that it should not be too difficult to do so.
  One thing to note is that this SCI is not the standard selected CI that
people use. In this selectedCI one has a subset of alpha {alpha_i} and beta
string {beta_i} and then one form a dense CI matrix that contains all
possible pairs |alph_i> |beta_j>. In the usual selectedCI the selection
process is not done on the alpha or the beta strings but on the entire
determinant. This version of SCI will perhaps be a bit less efficient than
the usual SCI versions like CIPSI, HCI etc.

  If you are interested in using HCi then the code that supports it right
now is Dice. It is not part of the pyscf package and does not support UHF.
But it does support GHF integrals. So one can just use a GHF hamiltonian
where the underlying orbitals are actually UHF.

Hope this helps,
Sandeep.

**Comment by stefabat** [comment]
I see, thank you for clarifications. I'll see what to do.

Cheers,
Stefano
