### ISSUE TITLE
Help to reproduce HSE06 functional using the tools to customize RSH functionals

### ISSUE THREAD

**Issue by rodrigoaramendes** [pyscf/pyscf#2341]
Dear @susilehtola or any expert among PySCF developers, 

Since we are interested in RSH functionals that include HF exchange only in the short-range part, I am attempting to reproduce the HSE06 functional using the available tools to customize RSH functionals.

The closest I have come using the "HYB_GGA_XC_HSE06" (converged SCF energy = -76.3869601455738 for H2O) flag is as follows:

0.25 * SR_HF(0.11) + 0.0 * LR_HF(0.11) + .75 * PBE, PBE * 1.0 
(converged SCF energy = -74.1826256469055 for H2O)

Certainly, this is wrong. So, I would appreciate any help.

Sincerely, 
Rodrigo.

**Comment by susilehtola** [comment]
What do you mean by "reproducing" HSE06? As we have recently discussed in

S. Lehtola and M. A. L. Marques, [Reproducibility of density functional approximations: how new functionals should be reported](https://doi.org/10.1063/5.0167763), J. Chem. Phys. 159, 114116 (2023). doi:10.1063/5.0167763

the HSE family is the worst case of (un)reproducibility: various codes implement completely different functionals under the names HSE03 and HSE06.

If you want to know what is inside the Libxc functional, just look at the Libxc source. Alternatively, you can extract data from "mixed" functionals like HYB_GGA_XC_HSE06 using the functions
```
/* Gets the IDs of the auxiliary functions */
void xc_aux_func_ids(const xc_func_type *p, int *ids);
/* Gets the weights of the auxiliary functions */
void xc_aux_func_weights(const xc_func_type *p, double *weights);
```
which tell you which functions are used by the implementation. Of course, you also need to plug in the right hybrid part.

Glancing at your trial, you have long-range HF exchange while there is none in HSE, and also you have the wrong exchange functional: you need to use (one of the many) range-separated PBE exchange functional(s). The correct exchange functional is `XC_GGA_X_WPBEH`.

**Comment by rodrigoaramendes** [comment]
Thanks @susilehtola. I certainly read your paper. I'm not trying to reproduce HSE06 from other codes. Instead, I'm trying to run "HYB_GGA_XC_HSE06" from PySCF/LibXC and then get the same results using an equation similar to the one I wrote in the previous email.

That's why I chose HYB_GGA_XC_HSE06. Since HSE03 has different omega values for the HF and DFT parts. Yes, you are right, I also read the HSE source code inside LibXC and saw it uses XC_GGA_X_WPBEH. I also tried this option. It is not giving me the same answer. After getting HSE06 right, the idea is to make our own functional. About the long-range, I thought that multiplying by zero was the right way to "turn it off."

Sincerely,
Rodrigo

**Comment by susilehtola** [comment]
The issue is probably that you also need to set the range separation parameter in `gga_x_wpbeh` like Libxc does, while I think PySCF may not yet have this functionality. I do remember some pull request in this direction, though...

**Comment by susilehtola** [comment]
>About the long-range, I thought that multiplying by zero was the right way to "turn it off."

Oh, I didn't notice you had a zero factor. Regardless, you shouldn't need that at all.

**Comment by rodrigoaramendes** [comment]
Thank you very much.
