### ISSUE TITLE
Custom hcore for UHF

### ISSUE THREAD

**Issue by Physfock** [pyscf/pyscf#2350]
How do I create a custom Hamiltonian (hcore) for UHF calculations and different alpha and beta blocks? They are usually the same.

mf = scf.UHF(mol)

mf.get_hcore = lambda *args: F_new (I want my new F to be different for alpha and beta, but I don't know how to do it.)
mf.get_ovlp  = lambda *args: S_new
mf._eri      = ao2mo.restore(1, eri_new, mol.nao) 

mf.kernel()

**Comment by fishjojo** [comment]
Does the following work?
`mf.get_hcore =lambda *a, **ka: np.asarray([ha, hb])`

**Comment by sunqm** [comment]
Please refer to the example https://github.com/pyscf/pyscf/blob/3ca5a34288fca6217177a094000cfc1eb51dd67f/examples/scf/40-customizing_hamiltonian.py#L60 

Feel free to reopen the issue if you have more questions regarding the UHF customization
