### ISSUE TITLE
How to convert SMILES to 3D coordinates?

### ISSUE THREAD

**Issue by anny0316** [pyscf/pyscf#2351]
Hello, great work. 
now, I want to convert SMILES to 3D Cartesian coordinates. By reading some papers I got the following ideas. The idea is to complete the conversion of SMILES to 3D coordinates in 3 steps:
1. We first used RDkit to parse SMILES string and built the Cartesian coordinates with MMFF94 force field optimization. 
2. The second pass employed the HF/STO3G theory (incorporate quantum mechanical effects) to generate a preliminary geometry. 
3. In the final pass of geometry relaxation, we used the B3LYP/6-31G(2df,p) model with the density fitting approximation for electron repulsion integrals. 

I have finished the first step, can you give me some advice about the second and the third steps? Thanks a lot.

**Comment by JangidBhavnesh** [comment]
It sounds like you're planning a geometry optimization, first with a smaller basis set and then using that geometry to reoptimize with a larger basis set for even better results.

For a guide on geometry optimization and the theory you're interested in, check out this
https://github.com/pyscf/pyscf/tree/master/examples/geomopt
https://github.com/pyscf/pyscf/tree/master/examples/dft

Just a suggestion: you can explore other open-source codes like orca for geometry optimization as well.

**Comment by susilehtola** [comment]
> Just a suggestion: you can explore other open-source codes like orca for geometry optimization as well.

ORCA is definitely not open-source, it is a commercial program.

**Comment by JangidBhavnesh** [comment]
> > Just a suggestion: you can explore other open-source codes like orca for geometry optimization as well.
> 
> ORCA is definitely not open-source, it is a commercial program.

Yes. I meant academically freely available.

**Comment by anny0316** [comment]
Thanks to JangidBhavnesh and susilehtola, now I am interested in geometry optimization, let me try it. Thank you.

**Comment by anny0316** [comment]
Many thanks to jamesETsmith. That helps me a lot. Thank you very much.

**Comment by jamesETsmith** [comment]
@anny0316, I'm going to close the issue since it seems like your initial questions have been answered. Feel free to reopen if you disagree or open another issue if you run across something new!
