### ISSUE TITLE
UCCSD calculation starting from UKS orbitals.

### ISSUE THREAD

**Issue by Jila66** [pyscf/pyscf#2365]
Hi,

I want to do the KUCCSD calculation on MnO crystal which the initial reference state for the CC calculations was generated from unrestricted  Kohn-Sham density functional calculations.

So first I put the dft.KUKS calculation in the input file befor the CCSD one.
But the CCSD calculation should be initialized with HF object, and we must convert the DFT object can be converted to HF object.

How we should do it?

This is a part of calculation : 

kmf = dft.KUKS(cell, kpts, exxdiv=exxdiv).density_fit()
kmf.xc = 'pbe'
kmf.with_df = gdf
kmf.with_df._cderi = gdf_fname
kmf.conv_tol = 1e-8
kmf.chkfile = chkfname

kmf.max_cycle = 300
kmf.kernel()

mycc = cc.KUCCSD(kmf)
mycc.conv_tol = 5e-5
mycc.conv_tol_normt = 1e-3
mycc.direct = True
mycc.kernel()

Thanks

**Comment by sunqm** [comment]
You can manually convert the KS object to an HF object.
```
mycc = cc.KUCCSD(kmf.to_hf())
```

**Comment by Jila66** [comment]
Thank you but, it gives an error:


File "/.nput.py", line 140, in <module>
    mycc = cc.KUCCSD(kmf.to_hf())
  File "/.../python3.10/site-packages/pyscf/dft/rks.py", line 411, in to_hf
    elif isinstance(self, scf.hf.UHF):
AttributeError: module 'pyscf.scf.hf' has no attribute 'UHF'. Did you mean: 'RHF'?

**Comment by Jila66** [comment]
Yes, You are right.
the problem is the PySCF version. It was 2.2. I upgrade it to V-2-6, now it works.

Another way for this issue is to create a new KUHF object and set the mo_coeff and mo_occ to the one from HF, something like the following after dft calculation is done:

kmf = scf.KUHF(cell, kpts=kpts, exxdiv=None).density_fit()
kmf.with_df = mydft.with_df
kmf.mo_coeff = mydft.mo_coeff
kmf.mo_occ = mydft.mo_occ

It worked for me too.
