### ISSUE TITLE
Question about HFX in examples/dft/31-xc_value_on_grid.py

### ISSUE THREAD

**Issue by sehun1618** [pyscf/pyscf#2375]
Hello! Thanks for great effort for great program.

I'm trying to reproduce some examples and I found something that confuse me.

In examples/dft/31-xc_value_on_grid.py

```
mf = mol.RHF().run()
dm = mf.make_rdm1()
vj, vk = mf.get_jk(dm)
print('Analytical HFX:', .5 * np.einsum('pq,qp->', vk, dm))

>>> Analytical HFX: 17.904382108498805
```

and I also run code below to check value of HFX

```
mf = mol.RKS()
mf.xc = 'HF'
mf.run()
mf.dump_scf_summary()

>>>**** SCF Summaries ****
Total Energy =                         -75.983948498105377
Nuclear Repulsion Energy =               9.188258417746113
One-electron Energy =                 -122.967473332490258
Two-electron Coulomb Energy =           46.747457470888172
DFT Exchange-Correlation Energy =       -8.952191054249402
```

The value of HFX was 8.952191054249402, which was half of the value of 17.904382108498805 in above example codes.

I'm confused which one is right.

**Comment by matthew-hennefarth** [comment]
> My guess is that the example script doesn't have the correct factor: you get 1/2 from writing the exchange energy as a sum over all orbitals `ij` instead of `i<j`, but you also need to account for the fact that the spin-restricted density contains a spin factor that doesn't occur in the exchange energy. The total factor should be `0.25` instead of `0.5` in the example.

Can confirm having looked back at some of my notes. The example code should have a factor of 0.25.
