### ISSUE TITLE
SO(3)-symmetry and 2e integrals for atom.

### ISSUE THREAD

**Issue by me-groshev** [pyscf/pyscf#2394]
I try to construct a secondary quantized hamiltonian of the atom. For this purpose, I want to use SO(3) symmetry of AOs. But I've found out something unexpected for me, and unfortunately couldn't find any explanation of this. 
The choice of SO(3) symmetry is provided by the following lines:
```
atom = M(atom='He 0 0 0',
             charge=0,
             spin=0,
             basis='ccpvdz',
             unit='b',
             symmetry=True,
             symmetry_subgroup='SO3')
atom.build()
```

**Q1:** When I calculate 2e integrals using `h2e_ao = atom.intor(intor='int2e', aosym='s1')` it is expected to get 

$$(pq|rs) = \int d^3\vec{r} \int d^3\vec{r}\prime
\chi_p^{\*}(\vec{r})
\chi_q(\vec{r})
\frac{1}{|\vec{r}-\vec{r}\prime|}
\chi^\*_r(\vec{r}\prime)
\chi_s(\vec{r}\prime)$$

with $\chi_{a}$ being atomic spatial orbitals, which are supposed to have (due to the chosen SO(3) symmetry group) orbital angular momentum $l_a$ and its $z$-projection $m_a$. From 
```
orb_symm = symm.label_orb_symm(mol=atom, 
    irrep_name=atom.irrep_name, 
    symm_orb=atom.symm_orb, 
    mo=np.eye(atom.nao)).tolist()
```
I get `['s+0', 's+0', 'p+1', 'p-1', 'p+0']`, so $$AO(№0)$$ has $$l_0=0, m_0=0$$, $$AO(№1)$$ has $$l_1=0, m_1=0$$, etc.

What is the order of indices in `h2e_ao`? I mean, is it exactly `h2e_ao[p][q][r][s]` $$= (pq|rs)$$?

**Q2:** If it's correct, then it's supposed to find some selection rules for $$(pq|rs)$$. Since 

$$\frac{1}{|\vec{r}-\vec{r}\prime|} = \sum_{l,m} c_{lm} Y_{lm}^{\*}(\vec{r}/r) Y_{lm}(\vec{r}\prime/r\prime),$$

then it's expected to see $$(pq|rs) = 0$$ if $m_p + m_r \neq m_s + m_q$. But printing `h2e_ao[0][2]` I see that $(02|02)\neq 0$, which contradicts $0+0 = m_0 + m_0 \neq m_2 + m_2 = +1 +1$:
```
[[0.         0.         0.17730745 0.         0.        ]
 [0.         0.         0.14252355 0.         0.        ]
 [0.17730745 0.14252355 0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]]
```
Do these selection rules work, or am I misunderstanding something?

**Comment by sunqm** [comment]
Q1: almost yes. They are the real spherical harmonic functions, not exactly the spherical harmonics

Q2: no. Real spherical harmonics do not have these symmetry selection rules.
