### ISSUE TITLE
Integrals of exchange correlation potential

### ISSUE THREAD

**Issue by computative** [pyscf/pyscf#2405]
Hello there,

I'm studying a crystal using dft and need to calculate an integral of the exchange correlation contribution to the effective potential. LDA,VWN is a completely acceptable functional for my application in gth-szv and gth-pade. The integral I study is the third term from the right in this equation from Mike Finnis book p 74: 
![eqn](https://github.com/user-attachments/assets/fa7f347b-076a-498b-ac2f-fb23da83e64f)

It's the integral that reads $\int \rho V_{xc} dr$. According to Finnis, he has defined $V_{xc} = \delta E_{xc}/ \delta \rho$. The application I need it for, is to changing the density matrix, and then see how the value of that integral changes.

I'm sure pyscf can do something in the way of this. Can you say what combination of functions seem to be a natural way to study this application using pcb dft in pyscf?

**Comment by sunqm** [comment]
https://github.com/pyscf/pyscf/blob/3dc4547e518f06223f239ad57cbd21ad3f6f570f/pyscf/pbc/dft/numint.py#L360

`rho` is the density on grids. The `excsum` variable in the same function is the value of the integral. You can remove other part of the code and just compute the exc energy only.

**Comment by computative** [comment]
- **I notice that scf_summary["e_xc"] is equal to excsum.** If (1) that is your desired behavior, and (2) excsum also is the intergral $\int \rho V_{ex}$ from the equation above, then can you say how to print out the term called $E_xc$ in that formula?

**Comment by computative** [comment]
- **I notice that scf_summary["e_xc"] is equal to excsum.** If (1) that is your desired behavior, and (2) excsum also is the intergral $\int \rho V_{ex}$ from the equation above, then can you say how to print out the term called $E_xc$ in that formula?

**Comment by computative** [comment]
I believe that I have found the answer. It's actually the term called `vxc` that is related to the integral by the method _vxc_mat. It transforms `vxc` into vmat. I was able to get the integral by calculating numpy.trace(numpy.dot(vmat, dm)) where dm = mf.make_rdm1().

**Comment by susilehtola** [comment]
Yes, 

$$ v^\sigma_{\rm xc} = \frac {\partial E_{\rm xc}} {\partial n_\sigma({\bf r})} $$

where $E_{\rm xc}({\bf r})$ is the **xc energy density** which is given by

$$ E_{\rm xc}({\bf r}) = n({\bf r}) \epsilon_{\rm xc}({\bf r}) $$

where $\epsilon_{\rm xc}({\bf r})$ is the **xc energy density per electron**.
