### ISSUE TITLE
Issues with memory allocation and calculation crashes in sCI 

### ISSUE THREAD

**Issue by NastaMauger** [pyscf/pyscf#2412]
Hello,

I am running SCI with different basis sets on methane. Using the _cc-pVDZ_ basis set with a very small `selec_cutoff = 5e-9`  does not result in any memory issues (and used approximately 70 GB). However, when using the _cc-pVTZ_ basis set with a `selec_cutoff = 5e-1`, the calculation crashes very early (`Segmentation fault (core dumped)`), even though it should involve only a few determinants.

I understand that my MO space is larger with the _cc-pVTZ_ basis set, but since I have allocated 250 GB of memory (which is the maximum I can set) and used a `selec_cutoff `that should result in only 1 or 2 determinants, I would expect the calculation to succeed.

Is there something specific to SCI memory management that I might have missed? Or is it expected that this kind of calculation would fail even with 250 GB of memory, considering the system has only 10 electrons?

Thank you for your time and assistance.

**Comment by gkc1000** [comment]
I'm guessing that the cutoff is so large that some array size is 0, causing the segfault (not an out of memory issue). Are you using DICE vis PySCF?

**Comment by NastaMauger** [comment]
Hello,

No I am not using DICE. I was using native sCI

Best
