### ISSUE TITLE
How to calculate virtual-virtual or occupied-occupied density matrix after MP2 calculation?

### ISSUE THREAD

**Issue by ustcwdd** [pyscf/pyscf#2416]
I want to calculate virtual-virtual or occupied-occupied density matrix after MP2 calculation, how to get 2e-intergals with different orbital indices and fock-matrix?
The formula of virtual-virtual density matrix is:
![image](https://github.com/user-attachments/assets/19488adb-e276-4c3f-950d-89d390e8b95a)
![image](https://github.com/user-attachments/assets/2562598d-f622-4731-aa42-13bf2ee26607)
where i, j, ... are general occupied orbitals and a, b, ... are general virtual orbitals, εa, . . . , εj, . . .  are diagonal elements of the Fock
matrix, 〈ac||ij〉is the anti-symmetrized 2e-intergal, respectively. The formula originates from 'A general-order local coupled-cluster method based on the cluster-in-molecule approach', specifically equations (7) and (8).

**Comment by ssh2** [comment]
There is a function already available to calculate the MP2 density matrix, see [link](https://github.com/pyscf/pyscf/blob/3dc4547e518f06223f239ad57cbd21ad3f6f570f/pyscf/mp/mp2.py#L151). If you run it right after the MP2 energy calculation you will get the density matrix with non-zero virtual-virtual and occupied-occupied blocks. Looking at the source code, the matrix will be in the MO basis by default, which is what you want, as far as I understand.

**Comment by tberkel** [comment]
It sounds like you're still pursuing local natural orbitals as discussed in #2398. As @ssh2 points out, there is code in PySCF to calculate the total MP2 density matrix (summed on i). If you want, you can try to modify that code to make LNOs.

**Comment by ustcwdd** [comment]
Thank a lot, this is exactly what I was looking for.
