### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by noyerx** [pyscf/pyscf#242]
when trying to run a uhf calculation:
```
...
mf = pbcscf.UHF(cell).density_fit()
print(mf.kernel())
...
e_kn = mf.get_bands(band_kpts)[0]
...

```
the following error was obtained:

> Traceback (most recent call last):
>   File "c_uhf_gdf.py", line 47, in <module>
>     e_kn = mf.get_bands(band_kpts)[0]
>   File "/export/zgid/yanbing/pyscf/pyscf/pbc/scf/uhf.py", line 151, in get_bands
>     focka, fockb = fock + self.get_veff(cell, dm, kpt=kpt, kpts_band=kpts_band)
> ValueError: too many values to unpack

**Comment by tberkel** [comment]
I can also reproduce this error, and note that it only happens for unrestricted mean-field calculations with density fitting.
