### ISSUE TITLE
init_amps for UCCSD and GCCSD

### ISSUE THREAD

**Issue by rhkim79** [pyscf/pyscf#2430]
I'm testing a system with complex integral with CCSD. For RCCSD, it works without an issue. But when I move to the UCCSD and GCCSD, there were some warning messages says:

```
Init t2, MP2 energy = -0.0372943314534773

WARN: Non-zero imaginary part found in UCCSD energy (-0.037294331453726896-0.0014504250553546913j)

Init E_corr(UCCSD) = -0.0372943314537269
(0.004900285022016054+0.00011510531173885308j)

WARN: Non-zero imaginary part found in UCCSD energy (-0.08887160221645246+0.0006010709694078048j)
```

I checked the code and it seems to miss conjugations for t2 amplitudes in `init_amps` . Following is the comparison between UMP2 and cc.init_amps. 

```
(Pdb) mymp2 = mp.UMP2(uhf_mol)
(Pdb) e_mp2, t_mp2 = mymp2.kernel()
E(UMP2) = -74.5807280862504  E_corr = -0.0869402776487616
E(SCS-UMP2) = -74.5809728837498  E_corr = -0.0871850751481068
(Pdb) mycc = cc.UCCSD(uhf_mol)
(Pdb) e_cc, t1_cc, t2_cc = mycc.init_amps()
(Pdb) la.norm(t2_cc[0]-t_mp2[0])
0.11996319010338435
(Pdb) la.norm(t2_cc[0].conj()-t_mp2[0])
5.7972155622559106e-09
```

I think the same issue appears in GCCSD but both in t2 and emp2 calculation part. 

I would appreciate it if you could check it.

**Comment by sunqm** [comment]
Thank you for identifying and tracking this bug. Could you please open a pull request to fix it? Thank you!

**Comment by rhkim79** [comment]
I made a pull request for this issue 
https://github.com/pyscf/pyscf/pull/2501

**Comment by Physfock** [comment]
Still exist WARN: Non-zero imaginary part found in UCCSD energy
