### ISSUE TITLE
PySCF does not converge for Heme-B molecule

### ISSUE THREAD

**Issue by jamesmalmeida** [pyscf/pyscf#2433]
Dear developers and users,

I am new to PySCF, although with experience in other DFT codes.
I am trying to run a Heme-B molecule, but despite trying different basis-sets, charges and mutiplicities I am unable to converge the calculation.
Maybe I am missing something basic because of the syntax, but I could not find it.
The molecule in question was previously relaxed with ORCA, and it worked fine with def2tzvp and b3lyp.

Thank you in advance for any help provided.

The code I am running is:
mol = gto.M(atom="heme.xyz", verbose = 4, charge = -2, spin = 0) #Tryed with different charge/spin configurations.
mol.basis = 'def2tzvp' #Tryed also sto-3g, sto-6g, and some other I do not remember.
mol.build()
dft_mol = dft.RKS(mol).newton() #Also tried without newton.
dft_mol.level_shift = 0.2 #Tryed without level_shift also.
dft_mol.xc = 'b3lyp'
dft_mol.max_cycle = 100
dft_mol.kernel()

The xyz file contents is:
75

  O      6.986519    2.147141   -1.510298
  O      6.363397   -3.423292   -1.762640
  O      6.876512    2.729818    0.653378
  O      6.391959   -3.339967    0.478916
  N     -2.375107    1.700230   -0.088000
  N     -2.636502   -1.127488    0.030976
  N      0.432241    1.447875    0.284824
  N      0.175866   -1.372998    0.309877
  C      2.550937    2.353238    0.558939
  C      2.105741   -2.642320    0.527751
  C      1.756477    1.144051    0.457413
  C      1.681738    3.397127    0.439613
  C      1.537396   -1.310325    0.448260
  C      1.060500   -3.513517    0.441403
  C      0.366082    2.818305    0.267413
  C     -0.136294   -2.708330    0.314299
  C     -2.063950    3.035763   -0.071161
  C     -3.968072   -0.814812   -0.096453
  C     -2.581878   -2.490474    0.119815
  C     -3.729840    1.632687   -0.283117
  C      4.036621    2.408271    0.751856
  C      3.564686   -2.959028    0.663281
  C      2.270175   -0.139253    0.527507
  C     -3.244228    3.839703   -0.264590
  C     -4.781528   -2.006506   -0.074215
  C     -4.289460    2.967894   -0.427347
  C     -3.914788   -3.064482    0.051425
  C     -0.791126    3.553851    0.103470
  C     -1.414327   -3.226633    0.233407
  C     -4.470504    0.465864   -0.251182
  C      1.975862    4.862900    0.473355
  C      4.821041    2.332229   -0.564361
  C      4.292102   -3.018883   -0.686208
  C      1.088395   -5.008193    0.470282
  C     -3.267879    5.333165   -0.320536
  C     -6.273709   -2.035959   -0.136742
  C     -5.676607    3.336479   -0.689223
  C     -4.195823   -4.488836    0.148491
  C      6.314256    2.429210   -0.367257
  C      5.773093   -3.275732   -0.551398
  C     -6.555379    2.701619   -1.468544
  C     -5.257076   -5.142906   -0.334051
  H      4.365687    1.599577    1.407730
  H      4.310629    3.329167    1.267837
  H      3.691025   -3.915219    1.173778
  H      4.060254   -2.223971    1.299606
  H      3.337334   -0.235154    0.670313
  H     -0.695492    4.630736    0.107608
  H     -1.507250   -4.302591    0.259369
  Fe    -1.101322    0.161783    0.135050
  H     -5.540327    0.568656   -0.342682
  H      1.366276    5.378692    1.219703
  H      3.021139    5.051538    0.717361
  H      1.773294    5.337624   -0.491254
  H      4.528847    3.145389   -1.236323
  H      4.603228    1.412157   -1.111434
  H      3.868799   -3.794610   -1.329507
  H      4.168463   -2.084385   -1.241475
  H      2.098137   -5.382546    0.638022
  H      0.731281   -5.436685   -0.470602
  H      0.454775   -5.408030    1.266509
  H     -2.809455    5.776498    0.567211
  H     -4.286885    5.711228   -0.392260
  H     -2.720870    5.710959   -1.189423
  H     -6.637291   -2.175381   -1.160076
  H     -6.712300   -1.112143    0.240736
  H     -6.667283   -2.861546    0.458907
  H     -6.006400    4.255347   -0.211375
  H     -3.451061   -5.077416    0.676153
  H     -7.561411    3.082276   -1.589838
  H     -6.300892    1.810954   -2.028282
  H     -5.362152   -6.209406   -0.182325
  H     -6.034423   -4.656700   -0.907176
  H      7.931695    2.249671   -1.315238
  H      7.308554   -3.572766   -1.601096

**Comment by jamesmalmeida** [comment]
The problem was indeed simple to solve, it converged by adding smearing, as the HOMO and LUMO were very close.
The smearing was added with the following line:
dft_mol = scf.addons.smearing_(dft_mol, sigma=.01, method='fermi')

**Comment by susilehtola** [comment]
Hi, I just tried out your calculation in Psi4 and it converged without problems, although it took 54 iterations to reach convergence.

However, I notice that the converged calculation features 6 orbitals with **positive orbital energies**. You are calculating a double anion, but have not used a basis set with diffuse functions that are necessary to describe anionic species.

Switching to the def2-TZVPD basis set also does not solve this issue: six orbital energies remain positive. You may be interested in reading [J. Chem. Theory Comput. 20, 6652 (2024)](https://doi.org/10.1021/acs.jctc.4c00712).
