### ISSUE TITLE
Exact exchange energy of DFT (Exx)

### ISSUE THREAD

**Issue by sehun1618** [pyscf/pyscf#2439]
Dear pyscf developers,

I'm looking for codes for exact exchange energy from ks orbitals to get exact-exchange only dft energy.

I already checked /examples/dft/31-xc_value_on_grid.py but there are codes exchange energy for HF, not KS one.

How can I get Exx?

**Comment by matthew-hennefarth** [comment]
What do you mean by "exact-exchange"? The "exact-exchange" for a single Slater determinant is given by the HF exchange. Are you referring to only computing the exchange contribution from some specific KS-DFT functional? If so take a look at these [lines](https://github.com/pyscf/pyscf/blob/410d9608a73ad3a507b3008a6f68549288ebfc33/examples/dft/31-xc_value_on_grid.py#L34-L40).

**Comment by sehun1618** [comment]
No. I just want to get the energy of exact-exchange (Hartree-Fock exchange in KS orbitals) only DFT energy.

**Comment by susilehtola** [comment]
You can get the exact exchange energy by getting building the exchange matrix with a Hartree-Fock object, using a spin density matrix from DFT. Then you just trace the exchange matrix with the density matrix and divide by two.

**Comment by sehun1618** [comment]
Thanks for reply.

Is there another way to do exact-exchange only self-consistent DFT calculation?

**Comment by matthew-hennefarth** [comment]
> Is there another way to do exact-exchange only self-consistent DFT calculation?

Do you want to do a DFT calculation using the exact HF exchange? If so, take a look at [`example/dft/24-custom_xc_functional.py`](https://github.com/pyscf/pyscf/blob/master/examples/dft/24-custom_xc_functional.py). Specifically, look at:

```python
#
# DFT can parse the custom XC functional, following the rules:
# * The given functional description must be a one-line string.
# * The functional description is case-insensitive.
# * The functional description string has two parts, separated by ",".  The
#   first part describes the exchange functional, the second is the correlation
#   functional.
#   - If "," was not presented in string, the entire string is treated as a
#     compound XC functional (including both X and C functionals, such as b3lyp).
#   - To input only X functional (without C functional), leave the second part
#     blank. E.g. description='slater,' for pure LDA functional.
#   - To neglect the X functional (only input C functional), leave the first
#     part blank. E.g. description=',vwn' means pure VWN functional
#   - If compound XC functional is specified, no matter whehter it is in the X
#     part (the string in front of comma) or the C part (the string behind
#     comma), both X and C functionals of the compound XC functional will be
#     used.
# * The functional name can be placed in arbitrary order.  Two names needs to
#   be separated by operators + or -.  Blank spaces are ignored.
#   NOTE the parser only reads operators + - *.  / is not supported.
# * A functional name can have at most one factor.  If the factor is not
#   given, it is set to 1.  Compound functional can be scaled as a unit. For
#   example '0.5*b3lyp' is equivalent to
#   'HF*0.1 + .04*LDA + .36*B88, .405*LYP + .095*VWN'
# * String "HF" stands for exact exchange (HF K matrix).  It is allowed to
#   put "HF" in C (correlation) functional part.
# * String "RSH" means range-separated operator. Its format is
#   RSH(omega, alpha, beta).  Another way to input RSH is to use keywords
#   SR_HF and LR_HF: "SR_HF(0.1) * alpha_plus_beta" and "LR_HF(0.1) *
#   alpha" where the number in parenthesis is the value of omega.
# * Be careful with the libxc convention on GGA functional, in which the LDA
#   contribution has been included.

mf = dft.RKS(mol)
# B3LYP can be constructed
mf.xc = 'HF*0.2 + .08*LDA + .72*B88, .81*LYP + .19*VWN'
e1 = mf.kernel()
print('E = %.15g  ref = -76.3832244350081' % e1)
```

So if you want the HF exchange only, self-consistent DFT, you would do something like

```python
mf = dft.RKS(mol)
mf.xc = 'HF'
e1 = mf.kernel()
print('E = %.15g  ref = -76.3832244350081' % e1)
```

You can also do HF exchange with LYP correlation as 

```python
mf.xc = 'HF,LYP'
```

**Comment by sehun1618** [comment]
@matthew-hennefarth 

Thank you.

I tried below code.

```python
from pyscf import scf, dft, gto

mol = gto.M(
atom = '''
H 0 0 -0.37
H 0 0 0.37''',
basis = 'augccpvtz',
charge = 0,
spin = 0,
verbose=9
)

myhf = scf.RHF(mol)
myhf.kernel()

mydft = dft.RKS(mol)
mydft.xc = 'HF,'
mydft.kernel()

print(myhf.scf_summary)
print(mydft.scf_summary)
``` 
and then, result energies of myhf & mydft are same.

>>> myhf.scf_summary
{'nuc': 0.7151043390810812,
 'e1': -2.5069511987894746,
 'e2': 0.6588128832760521}
 
 >>> mydft.scf_summary
 {'nuc': 0.7151043390810812,
 'e1': -2.5069514050046777,
 'coul': 1.3176261789829717,
 'exc': -0.6588169230676698}
 
 So I'm wondering if setting mydft.xc = ‘HF’ is just running a Hartree-Fock calculation, rather than an exact exchange ony DFT calculation.

**Comment by matthew-hennefarth** [comment]
> So I'm wondering if setting mydft.xc = ‘HF’ is just running a Hartree-Fock calculation, rather than an exact exchange ony DFT calculation.

Yes, it is likely just doing a HF calculation but with the DFT solver (which should just be HF). That is how HF exchange is calculated in almost all DFT software since it is (I believe at the moment) not possible to construct an effective potential which is a functional of the density which corresponds to the exact HF exchange.

When you say "exact exchange only DFT calculation" do you mean using the equation from the following [stack exchange post](https://mattermodeling.stackexchange.com/questions/347/is-there-any-dft-code-or-software-that-has-the-option-to-use-this-exact-exchange)? If so, I do not believe PySCF implements that formulation for an exchange function as it uses either [libxc](https://libxc.gitlab.io/functionals/) or [xcfun](https://xcfun.readthedocs.io/en/latest/functionals.html) to do the exchange-correlation evaluation.

**Comment by sehun1618** [comment]
Thank you so much.

I'll have to look up more information and learn about it.
