### ISSUE TITLE
PySCF 2.7.0 tests failing for conda-forge build

### ISSUE THREAD

**Issue by awvwgk** [pyscf/pyscf#2440]
Two tests of `pyscf.scf` are failing in the conda-forge build for version 2.7.0

````
FAILED pyscf/scf/test/test_addons.py::KnownValues::test_dynamic_level_shift - AssertionError: np.float64(-71.60729129573505) != -71.6072956194109 within 7 places (np.float64(4.3236758529019426e-06) difference)
FAILED pyscf/scf/test/test_h2o.py::KnownValues::test_scanner - AssertionError: np.float64(-76.27305140503903) != -76.27305227410365 within 7 places (np.float64(8.690646211562125e-07) difference)
````

Run: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1037971&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=6d4b912b-175d-51da-0fd9-4d30fe1eb4e7
PR: https://github.com/conda-forge/pyscf-feedstock/pull/37?notification_referrer_id=NT_kwDOAbV1IrQxMjU4ODIyMzczNzoyODY2OTIxOA

**Comment by sunqm** [comment]
This is likely related to the bugfix for the default DFT integral grids (issue #2186 and #2178) . The tolerance of the two tests may need to be adjusted. Could you please create a PR to update the relevant tests? Thank you.
