### ISSUE TITLE
Calculate exchange-correlation energy with pyscf pbc dft

### ISSUE THREAD

**Issue by computative** [pyscf/pyscf#2443]
Hello there,

Is pyscf pcb dft is able to output exchange correlation energy? I'm talking about the term $E_{xc}$ in the wikipeida article of [Kohn-Sham equations](https://en.wikipedia.org/wiki/Kohn%E2%80%93Sham_equations#Kohn%E2%80%93Sham_potential).

If you know the answer, please let me know. Here is an example code which you can base your answer on.

```
import pyscf
from pyscf.pbc import gto, dft
from pyscf import data
import numpy as np
"""
This part of the code makes a cube unit cell and random coordinates for two carbon atoms. 
"""

cell = gto.Cell()

arr_R = np.random.rand(2,3)
arr_cell = np.eye(3)

cell.a = "\n".join([f"{ str(ai).strip('[]') }" for ai in arr_cell])
cell.atom = "\n".join([ f"C  { str(r).strip('[]') }" for r in arr_R])
cell.verbose = 4    
cell.basis = 'gth-szv'
cell.pseudo = 'gth-pade'
cell.build()

"""
This part of the code solves  KS eqns. Note that the conv_tol is quite low
"""

mf = dft.RKS(cell)
mf.conv_tol = 1e-3
mf.kernel()
```

**Comment by tberkel** [comment]
Yes, there are many ways to print Exc. Here are three of them (from a molecular DFT example):
```
import pyscf

mol = pyscf.M(
    atom = 'H 0 0 0; F 0 0 1.1',  # in Angstrom
    basis = '631g',
    symmetry = True,
)

mf = mol.KS()
mf.xc = 'b3lyp'

# Option 1
mf.verbose = 5  # or greater
mf.kernel()
# prints
# E1 = -149.144793099709  Ecoul = 55.221987813905166  Exc = -10.795600933355782 

# Option 2
mf.verbose = 4  # or greater
mf.analyze()
# prints
# **** SCF Summaries ****
# Total Energy =                        -100.388774493450526
# Nuclear Repulsion Energy =               4.329631725709090
# One-electron Energy =                 -149.144793099709005
# Two-electron Coulomb Energy =           55.221987813905166
# DFT Exchange-Correlation Energy =      -10.795600933355782 

# Option 3
print(mf.scf_summary['exc'])
```

**Comment by computative** [comment]
Thanks for your answer. Are you sure of that? How confident do you feel that this number is $E_{xc}$?

> Yes, there are many ways to print Exc. Here are three of them (from a molecular DFT example):
> 
> ```
> import pyscf
> 
> mol = pyscf.M(
>     atom = 'H 0 0 0; F 0 0 1.1',  # in Angstrom
>     basis = '631g',
>     symmetry = True,
> )
> 
> mf = mol.KS()
> mf.xc = 'b3lyp'
> 
> # Option 1
> mf.verbose = 5  # or greater
> mf.kernel()
> # prints
> # E1 = -149.144793099709  Ecoul = 55.221987813905166  Exc = -10.795600933355782 
> 
> # Option 2
> mf.verbose = 4  # or greater
> mf.analyze()
> # prints
> # **** SCF Summaries ****
> # Total Energy =                        -100.388774493450526
> # Nuclear Repulsion Energy =               4.329631725709090
> # One-electron Energy =                 -149.144793099709005
> # Two-electron Coulomb Energy =           55.221987813905166
> # DFT Exchange-Correlation Energy =      -10.795600933355782 
> 
> # Option 3
> print(mf.scf_summary['exc'])
> ```

**Comment by computative** [comment]
Thanks for your answer. Are you sure of that? How confident do you feel that this number is $E_{xc}$?

**Comment by tberkel** [comment]
Very confident.

**Comment by computative** [comment]
Thanks for your answer. The reason I'm asking is that the number you cite is always equal to the quantity called [`excsum` described in this thread](https://github.com/pyscf/pyscf/issues/2405). But as $E_{xc} \neq \int V_{xc} \rho dr$ either the other developer of yourself seem to be mistaken. Was I able to explain the concern?

**Comment by tberkel** [comment]
Agreed, $E_{xc} \neq \int d^3r V_{xc}(r) \rho(r)$ (i.e., these are not expected to be equal). I'm quite sure that `excsum` is collecting contributions to the integral that produces the exchange-correlation energy. It is not calculating $\int d^3r V_{xc}(r) \rho(r)$.

**Comment by sunqm** [comment]
The `exc` return by libxc is the XC energy per particle. However, `vxc` from libxc is not $\frac{\delta e_{xc}}{\delta \rho}$. It's actually $\frac{\delta e_{xc}}{\delta \rho} + e_{xc}$, not the usual vxc in literature. Please see libxc document for details.

**Comment by computative** [comment]
This reply makes me believe that 
`excsum` is $\int e_{xc} \rho dr = E_{xc}$ as tberkel said. Can you confirm sunqm?
`excsum` is not $\int \frac{\delta E_{xc}}{\delta \rho} \rho dr$, and the answer to this thread is false. 

If I have understood correctly, may [the other thread](https://github.com/pyscf/pyscf/issues/2405) be supported with an answer?

**Comment by computative** [comment]
It is absolutely correct as @tberkel says
