### ISSUE TITLE
pw_loop does not return hermitian matrix 

### ISSUE THREAD

**Issue by simonganne01** [pyscf/pyscf#2446]
Hello everyone. I am using the MDF class to calculate some integrals and a wierd thing occurred. When I constructed the Lpq matrix for the plane wave part of the DF, the returned matrix was not Hermitian on the Gamma point. I use the following code:

`for (LpqR_AFT, LpqI_AFT, p0, p1),(LrsR_AFT, LrsI_AFT, q0, q1)  \
                            in lib.izip(mydf.pw_loop(kpti_kptj=[kpti, kptj], q=q, max_memory=0.1*crpa._scf.max_memory),
                                        mydf.pw_loop(kpti_kptj=[-kpti, -kptj], q=q, max_memory=0.1*crpa._scf.max_memory)):
        Lpq_AFT.append((LpqR_AFT + LpqI_AFT*1.0j)*CoulG[None,p0:p1])
        Lrs_AFT.append((LrsR_AFT - LrsI_AFT*1.0j))`

Lpq_AFT is thus not hermitian with regard to the atomic orbitals. kpti and kptj were both the Gamma point when I interupted the program using my debugger. Can someone explain why this is not Hermitian because i expect it to be. Or if you can explain why I should not expect it to be Hermitian is good for me as well :)

**Comment by sunqm** [comment]
At one point after publishing the MDF paper, I realized that MDF does not guarantee hermitian (nor real) for gamma point, nor the symmetry between the "conjugated" k-points pairs. This issue can be somewhat interpreted in this way: The PW functions in MDF, if not enough to expand all AOs in the system, does not guarantee the same level of accuracy for different basis functions. This leads to small errors in permutation symmetry in integrals, and symmetry between k-points. One relevant comment in the code can be found https://github.com/pyscf/pyscf/blob/25eaa9572977b903de24d5c11ad345cecd744728/pyscf/pbc/df/mdf.py#L104

I guess this might be related to the problem you met.
