### ISSUE TITLE
DFT failure

### ISSUE THREAD

**Issue by noyerx** [pyscf/pyscf#245]
I was trying to run a simple DFT calculation that I found in the 'pySCF example':
```
from pyscf import gto, dft

'''                                                                                                                                            
A simple example to run DFT calculation.                                                                                                       
See also pyscf/dft/libxc.py and pyscf/dft/xcfun.py for the complete list of                                                                    
available XC functionals.                                                                                                                      
'''

mol = gto.Mole()
mol.build(
    atom = 'H 0 0 0; F 0 0 1.1',  # in Angstrom                                                                                                
    basis = '631g',
    symmetry = True,
)

mf = dft.RKS(mol)
#mf.xc = 'svwn' # shorthand for slater,vwn                                                                                                     
#mf.xc = 'bp86' # shorthand for b88,p86                                                                                                        
#mf.xc = 'blyp' # shorthand for b88,lyp                                                                                                        
#mf.xc = 'pbe' # shorthand for pbe,pbe                                                                                                         
#mf.xc = 'lda,vwn_rpa'                                                                                                                         
#mf.xc = 'b97,pw91'                                                                                                                            
#mf.xc = 'pbe0'                                                                                                                                
#mf.xc = 'b3p86'                                                                                                                               
#mf.xc = 'wb97x'                                                                                                                               
mf.xc = 'b3lyp'
mf.kernel()

# Orbital energies, Mulliken population etc.                                                                                                   
mf.analyze()
 
```
and here is the error messages:

> /export/zgid/yanbing/pyscf/pyscf/dft/numint.py:33: UserWarning: XC functional libraries (libxc or XCfun) are not available.
>   warnings.warn('XC functional libraries (libxc or XCfun) are not available.')
> Traceback (most recent call last):
>   File "dftTest.py", line 27, in <module>
>     mf.kernel()
>   File "/export/zgid/yanbing/pyscf/pyscf/scf/hf.py", line 1476, in kernel
>     return self.scf(dm0, **kwargs)
>   File "/export/zgid/yanbing/pyscf/pyscf/scf/hf.py", line 1470, in scf
>     conv_check=self.conv_check, **kwargs)
>   File "/export/zgid/yanbing/pyscf/pyscf/scf/hf.py", line 143, in kernel
>     vhf = mf.get_veff(mol, dm)
>   File "/export/zgid/yanbing/pyscf/pyscf/dft/rks.py", line 89, in get_veff
>     n, exc, vxc = ni.nr_rks(mol, ks.grids, ks.xc, dm)
>   File "/export/zgid/yanbing/pyscf/pyscf/dft/numint.py", line 667, in nr_rks
>     xctype = ni._xc_type(xc_code)
>   File "/export/zgid/yanbing/pyscf/pyscf/dft/numint.py", line 1853, in _xc_type
>     return self.libxc.xc_type(xc_code)
> AttributeError: 'module' object has no attribute 'xc_type'
>

**Comment by sunqm** [comment]
libxc or xcfun libraries are not installed in your system.

The simplest solution is to rebuild the package. You can completely remove the directory "/export/zgid/yanbing/pyscf/pyscf/lib/build" then rerun cmake, make etc. The build system should be able to solve the library installation dependency chain.

**Comment by noyerx** [comment]
I tried to rebuilt the package and it seems like the xcfun library is installed successfully:

> [  1%] Performing update step for 'libxcfun'
> [  2%] Performing configure step for 'libxcfun'
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /export/zgid/yanbing/pyscf/pyscf/lib/build/deps/src/libxcfun-build
> [  4%] Performing build step for 'libxcfun'
> [100%] Built target xcfun
> [  5%] Performing install step for 'libxcfun'
> [100%] Built target xcfun
> Install the project...
> -- Install configuration: "RELEASE"
> -- Up-to-date: /export/zgid/yanbing/pyscf/pyscf/lib/deps/lib/libxcfun.so.2.0.0
> -- Up-to-date: /export/zgid/yanbing/pyscf/pyscf/lib/deps/lib/libxcfun.so
> -- Up-to-date: /export/zgid/yanbing/pyscf/pyscf/lib/deps/include/xcfun.h
> [  7%] Completed 'libxcfun'
> [ 11%] Built target libxcfun
> [ 18%] Built target np_helper
> [ 39%] Built target cgto
> [ 55%] Built target cvhf
> [ 60%] Built target ao2mo
> [ 69%] Built target fci
> [ 71%] Built target mcscf
> [ 76%] Built target cc
> [ 78%] Built target icmpspt
> [ 79%] Built target shciscf
> [ 81%] Built target ri
> [ 82%] Built target hci
> [ 88%] Built target pbc
> [ 89%] Built target mbd
> [ 97%] Built target dft
> [ 98%] Built target xc_itrf
> [100%] Built target xcfun_itrf

But the problem still exist:

> /export/zgid/yanbing/pyscf/pyscf/dft/numint.py:33: UserWarning: XC functional libraries (libxc or XCfun) are not available.
>   warnings.warn('XC functional libraries (libxc or XCfun) are not available.')
> Traceback (most recent call last):
>   File "dftTest.py", line 27, in <module>
>     mf.kernel()
>   File "/export/zgid/yanbing/pyscf/pyscf/scf/hf.py", line 1476, in kernel
>     return self.scf(dm0, **kwargs)
>   File "/export/zgid/yanbing/pyscf/pyscf/scf/hf.py", line 1470, in scf
>     conv_check=self.conv_check, **kwargs)
>   File "/export/zgid/yanbing/pyscf/pyscf/scf/hf.py", line 143, in kernel
>     vhf = mf.get_veff(mol, dm)
>   File "/export/zgid/yanbing/pyscf/pyscf/dft/rks.py", line 89, in get_veff
>     n, exc, vxc = ni.nr_rks(mol, ks.grids, ks.xc, dm)
>   File "/export/zgid/yanbing/pyscf/pyscf/dft/numint.py", line 667, in nr_rks
>     xctype = ni._xc_type(xc_code)
>   File "/export/zgid/yanbing/pyscf/pyscf/dft/numint.py", line 1853, in _xc_type
>     return self.libxc.xc_type(xc_code)
> AttributeError: 'module' object has no attribute 'xc_type'
>

**Comment by noyerx** [comment]
Here is what I got:

> ldd /export/zgid/yanbing/pyscf/pyscf/lib/libxc_itrf.so
> 	linux-vdso.so.1 =>  (0x00007ffddefd2000)
> 	libxc.so.4 => /export/zgid/yanbing/pyscf/pyscf/lib/deps/lib/libxc.so.4 (0x00002b03d882e000)
> 	libgomp.so.1 => /usr/lib64/libgomp.so.1 (0x00002b03d8b57000)
> 	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b03d8d6c000)
> 	libc.so.6 => /lib64/libc.so.6 (0x00002b03d8f8a000)
> 	libm.so.6 => /lib64/libm.so.6 (0x00002b03d931e000)
> 	librt.so.1 => /lib64/librt.so.1 (0x00002b03d95a2000)
> 	/lib64/ld-linux-x86-64.so.2 (0x0000003b35400000)
> ldd /export/zgid/yanbing/pyscf/pyscf/lib/libxcfun_itrf.so
> 	linux-vdso.so.1 =>  (0x00007fff95fb1000)
> 	libxcfun.so.2.0.0 => /export/zgid/yanbing/pyscf/pyscf/lib/deps/lib/libxcfun.so.2.0.0 (0x00002b31c1668000)
> 	libgomp.so.1 => /usr/lib64/libgomp.so.1 (0x00002b31c1cf5000)
> 	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b31c1f0a000)
> 	libc.so.6 => /lib64/libc.so.6 (0x00002b31c2128000)
> 	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00002b31c24bc000)
> 	libm.so.6 => /lib64/libm.so.6 (0x00002b31c27c2000)
> 	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00002b31c2a47000)
> 	librt.so.1 => /lib64/librt.so.1 (0x00002b31c2c5d000)
> 	/lib64/ld-linux-x86-64.so.2 (0x0000003b35400000)
> ls /export/zgid/yanbing/pyscf/pyscf/lib/deps/lib
> libcint.so  libcint.so.3.0.13  libxcfun.so  libxcfun.so.2.0.0  libxc.la  libxc.so  libxc.so.4  libxc.so.4.0.1  pkgconfig

**Comment by sunqm** [comment]
In dftTest.py, before line 27 calling mf.kernel(), if you add
```
print(mf.ni.libxc)
print(dft.libxc.xc_type)
```
What do you get?

**Comment by noyerx** [comment]
Here is what I got:

> /export/zgid/yanbing/pyscf/pyscf/dft/numint.py:33: UserWarning: XC functional libraries (libxc or XCfun) are not available.
>   warnings.warn('XC functional libraries (libxc or XCfun) are not available.')
> Traceback (most recent call last):
>   File "dftTest.py", line 28, in <module>
>     print(mf.ni.libxc)
> AttributeError: 'SymAdaptedRKS' object has no attribute 'ni'
>

**Comment by sunqm** [comment]
What's the output of
```
python -c 'from pyscf.dft import libxc'
```

Is it nothing?

**Comment by noyerx** [comment]
It's:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/export/zgid/yanbing/pyscf/pyscf/__init__.py", line 49, in <module>
    numpy.__version__)
SystemError: You're using an old version of Numpy (1.4.1). It is recommended to upgrad numpy to 1.8.0 or newer. 
You still can use all features of PySCF with the old numpy by removing this warning msg. Some modules (DFT, CC, MRPT) might be affected because of the bug in old numpy.
```

**Comment by noyerx** [comment]
So I tried to run this code with a newer version of numpy (1.9.2) and still get the following error:

> Traceback (most recent call last):
>   File "dftTest.py", line 28, in <module>
>     print(mf.ni.libxc)
> AttributeError: 'SymAdaptedRKS' object has no attribute 'ni'

**Comment by sunqm** [comment]
You don't need to worry about the error. Just a test to identify the problem.

**Comment by noyerx** [comment]
Any idea how I could fix the problem?

**Comment by gkc1000** [comment]
Are you on OSX?

**Comment by noyerx** [comment]
Yes.

**Comment by gkc1000** [comment]
Did you set your DYLD_LIBRARY_PATH=(directory where libxc is)?
e.g. in .bashrc
export DYLD_LIBRARY_PATH=....

**Comment by noyerx** [comment]
No, I only have:
export PYTHONPATH=/export/zgid/yanbing/pyscf:$PYTHONPATH

**Comment by gkc1000** [comment]
Ok, set your DYLD_LIBRARY_PATH to where the libxc library is.

**Comment by noyerx** [comment]
Could you please let me know under which directory is the 'libxc' library? Is it under /pyscf/pyscf/lib/ ?
And  should I do for exampleL: " export DYLD_LIBRARY_PATH= (path) :$PYTHONPATH" like this?

**Comment by gkc1000** [comment]
Hi, on my system, it would be under /pyscf/pyscf/lib/deps/lib, so, try
export DYLD_LIBRARY_PATH=/export/zgid/yanbing/pyscf/pyscf/lib/deps/lib

But perhaps, first also check that
ls /export/zgid/yanbing/pyscf/pyscf/lib/deps/lib

shows libxc.dylib

**Comment by noyerx** [comment]
And I searched for` 'libxc.dylib'`, it does not exist in my entire `/export/zgid/yanbing/pyscf/ `directory at all.

**Comment by sunqm** [comment]
Also, what's the output of
```
python -c 'from pyscf.dft import libxc'
```
Don't worry about " AttributeError: 'SymAdaptedRKS' object has no attribute 'ni' ". It's irrelevant.

**Comment by noyerx** [comment]
Now python -c 'from pyscf.dft import libxc' does not gives any error messages. 
How can I ignore

>  'AttributeError: 'SymAdaptedRKS' object has no attribute 'ni''

 if the program is not running with this error?

**Comment by sunqm** [comment]
You should not get this error if you run your original script. Please post the error message of your new running. The error msg you posted was all from your early trial. It's very misleading.

**Comment by noyerx** [comment]
In fact, by running the script, I still got the error:

> /export/zgid/yanbing/pyscf/pyscf/dft/numint.py:33: UserWarning: XC functional libraries (libxc or XCfun) are not available.
>   warnings.warn('XC functional libraries (libxc or XCfun) are not available.')
> Traceback (most recent call last):
>   File "dftTest.py", line 28, in <module>
>     print(mf.ni.libxc)
> AttributeError: 'SymAdaptedRKS' object has no attribute 'ni'
> 

and the program just terminated due to this error.

**Comment by sunqm** [comment]
"print(mf.ni.libxc)" is the statement you added at some point during the discussion. It is not needed to run the dft method. The print statement can be removed.

The issue is " warnings.warn('XC functional libraries (libxc or XCfun) are not available.')"

If you can run "from pyscf.dft import libxc" without error, this warning msg should not be printed. The relevant code is  https://github.com/sunqm/pyscf/blob/master/pyscf/dft/numint.py#L25
It's strange that "python -c 'from pyscf.dft import libxc'" does not produce any error messages.

Could you please post the output of
```
python -v dftTest.py
```
It will output tons of messages.

**Comment by noyerx** [comment]
For some strange reason that the last time I tried `'python -c 'from pyscf.dft import libxc''` it does not give me any error message.
But now when I tried it again, the following error message shows up:
`python -c 'from pyscf.dft import libxc'`

> /export/zgid/yanbing/pyscf/pyscf/dft/numint.py:33: UserWarning: XC functional libraries (libxc or XCfun) are not available.
>   warnings.warn('XC functional libraries (libxc or XCfun) are not available.')
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ImportError: cannot import name libxc

**Comment by sunqm** [comment]
Did you modify any code in dft module? Do you have /export/zgid/yanbing/pyscf/pyscf/dft/libxc.py and /export/zgid/yanbing/pyscf/pyscf/dft/xcfun.py ?

**Comment by noyerx** [comment]
No, I never touched the source code. And yes, those two files are there.

**Comment by sunqm** [comment]
Which version are you using?
```
python -c 'import pyscf; print(pyscf.__version__)'
```

**Comment by noyerx** [comment]
1.5.3

**Comment by sunqm** [comment]
Could you post the output of
```
python -v -c 'from pyscf.dft import libxc'
```

**Comment by noyerx** [comment]
Here it is:
[err.txt](https://github.com/sunqm/pyscf/files/2572903/err.txt)

**Comment by sunqm** [comment]
Seems you didn't get ImportError this time?
Also, please use '-vv' for more python debug msg

**Comment by sunqm** [comment]
Anyway, let python print more debug messages. Hope it reveals more information.
```
python -vv dftTest.py
python -vv -c 'from pyscf.dft import libxc`
```

**Comment by noyerx** [comment]
Here are the messages:
[err_dftTest.txt](https://github.com/sunqm/pyscf/files/2573203/err_dftTest.txt)

and 
[err_libxc.txt](https://github.com/sunqm/pyscf/files/2573204/err_libxc.txt)

**Comment by noyerx** [comment]
HI,
I was just trying to build pyScf package on another computer cluster. 
When I go through all these:
```
$ sudo apt-get install python-h5py python-scipy cmake
$ git clone https://github.com/sunqm/pyscf
$ cd pyscf/pyscf/lib
$ mkdir build
$ cd build
$ cmake ..
```
and reach to the 
`$ make`
The following error messages shows up:

> [ 14%] Performing build step for 'libxc'
> Making all in build
> Making all in src
> libtool: compile:  /opt/cray/pe/craype/2.5.14/bin/cc -DHAVE_CONFIG_H -I. -I.. -g -O2 -MT references.lo -MD -MP -MF .deps/references.Tpo -c references.c  -fPIC -DPIC -o .libs/references.o
> libtool: compile:  /opt/cray/pe/craype/2.5.14/bin/cc -DHAVE_CONFIG_H -I. -I.. -g -O2 -MT special_functions.lo -MD -MP -MF .deps/special_functions.Tpo -c special_functions.c  -fPIC -DPIC -o .libs/special_functions.o
> libtool: compile:  /opt/cray/pe/craype/2.5.14/bin/cc -DHAVE_CONFIG_H -I. -I.. -g -O2 -MT bessel.lo -MD -MP -MF .deps/bessel.Tpo -c bessel.c  -fPIC -DPIC -o .libs/bessel.o
...

> libtool: link: (cd ".libs" && rm -f "libxc.so.4" && ln -s "libxc.so.4.0.1" "libxc.so.4")
> libtool: link: (cd ".libs" && rm -f "libxc.so" && ln -s "libxc.so.4.0.1" "libxc.so")
> libtool: link: ( cd ".libs" && rm -f "libxc.la" && ln -s "../libxc.la" "libxc.la" )
> libtool: link: /opt/cray/pe/craype/2.5.14/bin/cc -g -O2 -o .libs/xc-info xc-info.o  ./.libs/libxc.so -lm -Wl,-rpath -Wl,/global/homes/y/yanbingz/gitHub/pyscf/pyscf/lib/deps/lib
> /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: attempted static link of dynamic object `./.libs/libxc.so'
> Makefile:738: recipe for target 'xc-info' failed
> make[6]: *** [xc-info] Error 1
> Makefile:597: recipe for target 'all' failed
> make[5]: *** [all] Error 2
> Makefile:469: recipe for target 'all-recursive' failed
> make[4]: *** [all-recursive] Error 1
> Makefile:378: recipe for target 'all' failed
> make[3]: *** [all] Error 2
> CMakeFiles/libxc.dir/build.make:113: recipe for target 'deps/src/libxc-stamp/libxc-build' failed
> make[2]: *** [deps/src/libxc-stamp/libxc-build] Error 2
> CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/libxc.dir/all' failed
> make[1]: *** [CMakeFiles/libxc.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2
>
