### ISSUE TITLE
Calculating exchange integrals fails when only_dfj=True

### ISSUE THREAD

**Issue by jonas-greiner** [pyscf/pyscf#2456]
Hi everyone,
the following minimal example fails due to an assertion error:
```
from pyscf import gto, dft

mol = gto.M(
    atom="""
        O  0.00000000  0.00000000  0.00000000
        H -0.75390364  0.00000000 -0.58783729
        H  0.75390364  0.00000000 -0.58783729
    """
)

mf = dft.RKS(mol).density_fit(only_dfj=True).run()
vk = mf.get_k(mol=mol)
```
It should still be possible to get the regular exchange integrals which are also returned for `get_jk` if `with_j=True` and `with_k=True`. The issue appears to be in the following function:
https://github.com/pyscf/pyscf/blob/410d9608a73ad3a507b3008a6f68549288ebfc33/pyscf/df/df_jk.py#L133-L159

I would propose the following solution:
 ```
   def get_jk(self, mol=None, dm=None, hermi=1, with_j=True, with_k=True,
               omega=None):
        assert (with_j or with_k)
        if dm is None: dm = self.make_rdm1()
        if not self.with_df:
            return super().get_jk(mol, dm, hermi, with_j, with_k, omega)

        with_dfk = with_k and not self.only_dfj
        if with_j:
            if isinstance(self, scf.ghf.GHF):
                def jkbuild(mol, dm, hermi, with_j, with_k, omega=None):
                    vj, vk = self.with_df.get_jk(dm.real, hermi, with_j, with_k,
                                                self.direct_scf_tol, omega)
                    if dm.dtype == numpy.complex128:
                        vjI, vkI = self.with_df.get_jk(dm.imag, hermi, with_j, with_k,
                                                    self.direct_scf_tol, omega)
                        if with_j:
                            vj = vj + vjI * 1j
                        if with_k:
                            vk = vk + vkI * 1j
                    return vj, vk
                vj, vk = scf.ghf.get_jk(mol, dm, hermi, with_j, with_dfk,
                                        jkbuild, omega)
            else:
                vj, vk = self.with_df.get_jk(dm, hermi, with_j, with_dfk,
                                            self.direct_scf_tol, omega)
        else:
            vj = None
        if with_k and not with_dfk:
            vk = super().get_jk(mol, dm, hermi, False, True, omega)[1]
        return vj, vk
```
This change would still require that either the Coulomb or the exchange matrix are requested while ensuring the regular exchange matrix is returned whenever the corresponding density-fitted integrals are not available. I can open a PR if this behavior/fix is desired.

**Comment by susilehtola** [comment]
Please open up a PR, it is hard to see the modification from the above

**Comment by susilehtola** [comment]
What's the assertion error? I don't really follow your input
```
mf = dft.RKS(mol).density_fit(only_dfj=True).run()
vk = mf.get_k(mol=mol)
```
So you want to do RKS with RI-J, but use exact integrals for K?

**Comment by jonas-greiner** [comment]
Yes, I would expect the behavior to be the same as when I call the following:

`vk = mf.get_jk(mol=mol, with_j=True, with_k=True)`

In which case the exact integrals are returned because of these lines:
https://github.com/pyscf/pyscf/blob/410d9608a73ad3a507b3008a6f68549288ebfc33/pyscf/df/df_jk.py#L157-L158

But I get an assertion error when I just request exchange integrals.
