### ISSUE TITLE
GTO's+plane waves Like CP2K

### ISSUE THREAD

**Issue by simonganne01** [pyscf/pyscf#2461]
Since it is possible to import CP2K GTO basis sets, is t also possible to utelize these GTO's alongside plane waves like in CP2K?

**Comment by tberkel** [comment]
If you use FFTDF, then many of the integrals are done using a PW resolution
(called the GPW method in CP2K), but there is currently no native support
for using PWs as a primary basis set in PySCF.

**Comment by simonganne01** [comment]
Are there any plans for doing so in the future? (thanks for the fast response)

**Comment by fishjojo** [comment]
As far as I know, CP2K offers two methods: GPW and GAPW.
GPW is similar as the FFTDF in PySCF. GPW is implemented using a multigrid algorithm, and PySCF has similar implementations: https://github.com/pyscf/pyscf/blob/master/examples/pbc/27-multigrid.py, https://github.com/pyscf/pyscf/blob/master/examples/pbc/27-multigrid2.py
GAPW is roughly the [PAW](https://www.vasp.at/wiki/index.php/Projector-augmented-wave_formalism) formalism using Gaussian basis, and we don't have this in PySCF. For all-electron calculations, one can use the GDF in PySCF.
