### ISSUE TITLE
Trace of fock and dm not equal to dft electronic energy?

### ISSUE THREAD

**Issue by computative** [pyscf/pyscf#2463]
I am using dft in pbc and multiplying the fock matrix (from pyscf) with the density matrix (from pyscf) and taking the trace. The number is close to the electronic energy that pyscf reports (<2% deviation). I was expecting it to equal (within machine precision). Can you say which effect is causing it not to be equal?

Here is an example

```
import pyscf, copy
from pyscf.pbc import gto, dft
from pyscf import data
import numpy as np
"""
This part of the code makes a cube unit cell and random coordinates for two carbon atoms. 
"""

cell = gto.Cell()

R = np.random.rand(2,3)
A = np.eye(3)

cell.a = "\n".join([f"{ str(ai).strip('[]') }" for ai in A])
cell.atom = "\n".join([ f"C  { str(r).strip('[]') }" for r in R])
cell.verbose = 4
cell.basis = 'gth-szv'
cell.pseudo = 'gth-pade'
cell.build()

"""
This part of the code solves  KS eqns. Note that the conv_tol is quite low
"""

mf = dft.RKS(cell)
mf.conv_tol = 1e-3
mf.kernel()

print(f"{mf.energy_elec()[0] = }")

fock = mf.get_hcore() + mf.get_veff()
dm = mf.make_rdm1()

Tr_H_dot_rho = np.trace(np.dot(fock,dm))
print(f"{Tr_H_dot_rho = }")
```
I noticed that 'the discrepancy seen in the numbers that are printed above' is equal the 'difference between the expectation of the effective potential the sum of the coulomb and exc that are quoted by veff': 

```
>>> mf.energy_elec()[0] - Tr_H_dot_rho
1.676888858507517
>>> veff = mf.get_veff()
>>> veff.ecoul + veff.exc - np.trace(np.dot( veff, dm))
1.676888858507521
```

So even though the authors say [«Coulomb + XC functional»](https://github.com/pyscf/pyscf/blob/13b66276d78097fc6bb0b7eae5e401ef73fab4c5/pyscf/pbc/dft/rks.py#L44), we do not get the right answer

**Comment by tberkel** [comment]
As described in any introductory text on DFT or quantum chemistry (e.g., Szabo and Ostlund), the mean-field energy is not equal to Tr(fock * dm), which is the same as the sum of the MO energies. In PySCF, the correct evaluation of the mean-field energy is found in the `energy_elec()` function of the SCF methods.
