### ISSUE TITLE
Method used to obtain pyscf.pbc.grad.rhf.Gradients

### ISSUE THREAD

**Issue by computative** [pyscf/pyscf#2467]
Hello. I want to use pyscf for my paper where I calculate forces on the nuclei (and other things). I need to say _something_, even just a little concrete information about the evaluation of the gradients (ideally which equation is used).

I can see that [`pyscf.grad.rhf.kernel`](https://github.com/pyscf/pyscf/blob/13b66276d78097fc6bb0b7eae5e401ef73fab4c5/pyscf/scf/hf.py#L47) returns the sum of the [`pyscf.pbc.grad.rhf.grad_elec`](https://github.com/pyscf/pyscf/blob/13b66276d78097fc6bb0b7eae5e401ef73fab4c5/pyscf/pbc/grad/rhf.py#L32) and [`pyscf.pbc.grad.rhf.grad_nuc`](https://github.com/pyscf/pyscf/blob/13b66276d78097fc6bb0b7eae5e401ef73fab4c5/pyscf/pbc/grad/rhf.py#L134) methods. These methods again depend on a number of methods [inside this loop](https://github.com/pyscf/pyscf/blob/13b66276d78097fc6bb0b7eae5e401ef73fab4c5/pyscf/pbc/grad/rhf.py#L55):

- vpploc_part1_nuc_grad
- vpploc_part2_nuc_grad
- vppn1_nuc_grad
- extra_force
- some contractions of veff with rdm1

Do you know the equation for the these terms?

**Comment by fishjojo** [comment]
The first three together compute the force of the pseudo potential
`extra_force` is not used unless input by the user.
contractions between veff and density matrix computes the force of Coulomb energy and exchange-correlation energy
The detailed equations are complicated but it may be fine to just use the common equations in molecular DFT gradient calculations. 
I guess we should write a paper about this implementation in the future.

**Comment by computative** [comment]
Thanks for your answer. You said

> it may be fine to just use the common equations in molecular DFT gradient calculations

That's great. Can you cite a generic eqn in a paper/textbook that describes a general approach that pyscf uses to your liking?

**Comment by fishjojo** [comment]
I guess you can cite Eq. 18 in this paper https://www.sciencedirect.com/science/article/pii/000926149285009Y?via%3Dihub as a general formulation for Kohn-Sham DFT gradients.
If you utilized the code in pbc.grad.rhf for your research, you might also consider citing this paper https://www.nature.com/articles/s43588-023-00432-3, where the code was applied to real calculations for the first time.

**Comment by computative** [comment]
I will have a look
