### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_add_suffix'

### ISSUE THREAD

**Issue by Shahxad-Akram** [pyscf/pyscf#2473]
I'm working on a machine-learning project where I'm writing my custom code on top of PySCF to generate some features:

The following code works perfect for most of the time, I'd say 90% of times.

```
        MO = ao2mo.general(
            self.mf._eri, (self.mf.mo_coeff[:, self.ccsd.frozen :],) * 4, compact=False
        ).reshape(self.nmo, self.nmo, self.nmo, self.nmo)
```
But suddenly it starts to give me this error:

```
  File "/lustre/isaac/scratch/sakram/Research/DDQC/ddcc/ccsd_manager.py", line 339, in __init__
    MO = ao2mo.general(
         ^^^^^^^^^^^^^^
  File "/lustre/isaac/scratch/sakram/.conda/envs/main/lib/python3.12/site-packages/pyscf/ao2mo/__init__.py", line 309, in general
    return mod.general_iofree(eri_or_mol, mo_coeffs, intor, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/isaac/scratch/sakram/.conda/envs/main/lib/python3.12/site-packages/pyscf/ao2mo/outcore.py", line 675, in general_iofree
    general(mol, mo_coeffs, feri, dataname='eri_mo',
  File "/lustre/isaac/scratch/sakram/.conda/envs/main/lib/python3.12/site-packages/pyscf/ao2mo/outcore.py", line 217, in general
    intor, comp = gto.moleintor._get_intor_and_comp(mol._add_suffix(intor), comp)
                                                    ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_add_suffix'
```

I know it doesn't make any sense because it works most of the time.

**Additional Info:**

I'm trying to run KNNs with [faiss](https://github.com/facebookresearch/faiss) and during predictions, I'm getting the above error but the same code worked perfectly fine during the data generation.
One more thing this code is completely fine with smaller molecules but crashes for larger ones.

Another weird stuff: If I run the same molecule outside of faiss predictions it works fine.

I'm primarily dealing with coupled-cluster amplitudes. I know they're huge in number. But I have a powerful system with Nvidia h100 + 512GB memory.

**Comment by obackhouse** [comment]
That seems like your ERIs are becoming large enough in memory that they're stored on disk. If you want to make sure they're always on RAM, my solution is to set `mol.max_memory` to be very high. Otherwise, if you actually need them to be on disk when they exceed the default memory limit, then use `ao2mo.kernel(mf, ...)` instead of `ao2mo.general(mf._eri, ...)`.

**Comment by Shahxad-Akram** [comment]
@obackhouse Thank you; it worked perfectly. Could you please guide me on how to monitor this memory usage (whether it's on RAM or storage and how much it is using) within PySCF?

**Comment by obackhouse** [comment]
You can set the memory limit with the aforementioned `Mole` option, or with the respective config option. If you want to estimate the memory usage of the integrals themselves then you can just consider that the integrals have dimension 4 and 64 bits per element
```
nmo = mo_coeff[:, self.ccsd.frozen :].shape[1]
footprint_GB = (nmo ** 4) * 64 / 8e9
```
