### ISSUE TITLE
GLPT2 correlation energy in pyscf

### ISSUE THREAD

**Issue by dkhan42** [pyscf/pyscf#2479]
Hi all,
I was just wondering if its possible to calculate the Gorling Levy 2nd order perturbation theory correlation energy on Kohn-Sham orbitals including the single excitation contributions rather than just the MP2 correlation energy in pyscf?
Thanks!

**Comment by sunqm** [comment]
This feature is currently unavailable and is unlikely to be supported in the near future.

Feel free to reopen the issue if you would like to suggest adding this functionality to PySCF, and please add the "feature request" label.

**Comment by dkhan42** [comment]
Is there a way to add the single excitation contributions manually after calculating the MP2 correlation energy on Kohn-Sham orbitals?
