### ISSUE TITLE
Problem in MDF get_bands()

### ISSUE THREAD

**Issue by noyerx** [pyscf/pyscf#248]
When running the following KRHF calculation with the mixed density fitting:

```
...
kmf = pbcscf.KRHF(cell, cell.make_kpts([2,2,2])).mix_density_fit()
kmf.with_df.mesh = [10,10,10]
print(kmf.kernel())
...
e_kn_2 = kmf.get_bands(band_kpts)[0]
...
```

the following error was generated:

> Exception in thread Thread-18:
> Traceback (most recent call last):
>   File "/export/apps/Python/2.7.2-CentOS6.0/lib/python2.7/threading.py", line 552, in __bootstrap_inner
>     self.run()
>   File "/export/apps/Python/2.7.2-CentOS6.0/lib/python2.7/threading.py", line 505, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/export/zgid/yanbing/pyscf/pyscf/lib/misc.py", line 699, in qwrap
>     raise e
> RuntimeError: unable to create link (Links: Unable to initialize object)
> ...
> Exception in thread Thread-31:
> Traceback (most recent call last):
>   File "/export/apps/Python/2.7.2-CentOS6.0/lib/python2.7/threading.py", line 552, in __bootstrap_inner
>     self.run()
>   File "/export/apps/Python/2.7.2-CentOS6.0/lib/python2.7/threading.py", line 505, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/export/zgid/yanbing/pyscf/pyscf/lib/misc.py", line 699, in qwrap
>     raise e
> RuntimeError: unable to create link (Links: Unable to initialize object)
> ...

> Traceback (most recent call last):
>   File "c_mdf.py", line 96, in <module>
>     e_kn_2 = kmf.get_bands(band_kpts)[0]
>   File "/export/zgid/yanbing/pyscf/pyscf/pbc/scf/khf.py", line 562, in get_bands
>     fock = fock + self.get_veff(cell, dm_kpts, kpts=kpts, kpts_band=kpts_band)
>   File "/export/zgid/yanbing/pyscf/pyscf/pbc/scf/khf.py", line 502, in get_veff
>     vj, vk = self.get_jk(cell, dm_kpts, hermi, kpts, kpts_band)
>   File "/export/zgid/yanbing/pyscf/pyscf/pbc/scf/khf.py", line 493, in get_jk
>     exxdiv=self.exxdiv)
>   File "/export/zgid/yanbing/pyscf/pyscf/pbc/df/mdf.py", line 343, in get_jk
>     vk = mdf_jk.get_k_kpts(self, dm, hermi, kpts, kpts_band, exxdiv)
>   File "/export/zgid/yanbing/pyscf/pyscf/pbc/df/mdf_jk.py", line 77, in get_k_kpts
>     vk_kpts += df_jk.get_k_kpts(mydf, dm_kpts, hermi, kpts, kpts_band, None)
>   File "/export/zgid/yanbing/pyscf/pyscf/pbc/df/df_jk.py", line 153, in get_k_kpts
>     mydf.build(kpts_band=kpts_band)
>   File "/export/zgid/yanbing/pyscf/pyscf/pbc/df/df.py", line 541, in build
>     self._make_j3c(self.cell, self.auxcell, kptij_lst, cderi)
>   File "/export/zgid/yanbing/pyscf/pyscf/pbc/df/mdf.py", line 226, in _make_j3c
>     feri['j3c-kptij'] = feri['j3c-junk-kptij']
>   File "/export/apps/Python/2.7.2-CentOS6.0/lib/python2.7/site-packages/h5py/_hl/group.py", line 229, in __setitem__
>     h5o.link(obj.id, self.id, name, lcpl=lcpl, lapl=self._lapl)
>   File "h5o.pyx", line 187, in h5py.h5o.link (h5py/h5o.c:2862)
> RuntimeError: unable to create link (Links: Unable to initialize object)
>

**Comment by sunqm** [comment]
Fixed in commit 1f41ca243f4bc1257c2874cfe3bedde7b935eb6a
