### ISSUE TITLE
NumPy 2 causes integer overflows in gto.moleintor

### ISSUE THREAD

**Issue by chillenb** [pyscf/pyscf#2481]
Example:
```
from pyscf import gto
import numpy as np

large_molecule = [
    ('C', (0., 0., i*1.5)) for i in range(20)
]
mol = gto.M(atom=large_molecule, basis='aug-cc-pvdz')
print(mol.nao)

ints = mol.intor('int2e', aosym='s8')
```

Output:
```
460
/home/chillenb/mambaforge/envs/overflow/lib/python3.12/site-packages/pyscf/gto/moleintor.py:599: RuntimeWarning: overflow encountered in scalar multiply
  out = numpy.ndarray((nao_pair*(nao_pair+1)//2), buffer=out)
Traceback (most recent call last):
  File "/home/chillenb/src/pyscf-devel/overflow/overflow.py", line 10, in <module>
    ints = mol.intor('int2e', aosym='s8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chillenb/mambaforge/envs/overflow/lib/python3.12/site-packages/pyscf/gto/mole.py", line 3476, in intor
    return moleintor.getints(intor, self._atm, bas, env,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chillenb/mambaforge/envs/overflow/lib/python3.12/site-packages/pyscf/gto/moleintor.py", line 240, in getints
    return getints4c(intor_name, atm, bas, env, shls_slice, comp,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chillenb/mambaforge/envs/overflow/lib/python3.12/site-packages/pyscf/gto/moleintor.py", line 599, in getints4c
    out = numpy.ndarray((nao_pair*(nao_pair+1)//2), buffer=out)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: negative dimensions are not allowed
```

This happens because `nao` and `nao_pair` are 32-bit NumPy integers, and `nao_pair*(nao_pair+1)` causes an overflow. One solution is to cast to Python ints; another is to use 64-bit ints for ao_loc.

**Comment by chillenb** [comment]
Unfortunately, this behavior change in NumPy is, according to the developers, both permanent and [intentional](https://numpy.org/neps/nep-0050-scalar-promotion.html#nep50)


A big and inconvenient change to PySCF's ao_loc might be unavoidable.😔
If so, I'm more than willing to help with implementation, but it's not clear to me what the best solution is.

**Comment by chillenb** [comment]
Edit: I just saw your pull request fixing this issue. Thanks so much for doing that!

Casting to int definitely fixes this in principle. If there are lots of places in the code where int32s are multiplied by large numbers, so that manual casting would change a lot of lines, then I guess one could use 64 bit int arrays for ao loc in Python, and use ndarray.astype(np.int32) when calling C. Or use 64 bit everywhere since ao loc is usually short.

**Comment by sunqm** [comment]
Thank you for offering to help! However, I think it's better not to change the data type of ao_loc. It's used by other plugins and projects in their C extensions. Modifying it could introduce compatibility issues.
