### ISSUE TITLE
Becke radial integration scheme does not integrate numbers of electrons correctly

### ISSUE THREAD

**Issue by awvwgk** [pyscf/pyscf#2490]
From the available radial integration schemes the Becke one seems to not create a proper integration grid as the number of electrons is overestimated:

````python
from pyscf import dft, gto

mol = gto.M(atom="He")

for radi_method in (
   dft.radi.becke,
   dft.radi.treutler_ahlrichs,
   dft.radi.delley,
   dft.radi.gauss_chebyshev,
   dft.radi.mura_knowles,
):
   ks = dft.KS(mol)(xc="pbe", grids=dft.Grids(mol)(radi_method=radi_method), verbose=0)
   ks.kernel()
   rho = ks._numint.get_rho(mol, ks.make_rdm1(), ks.grids)
   nel = (rho * ks.grids.weights).sum()
   print(radi_method.__name__, nel)
````

Output:

````
becke 2.188070936036473
treutler_ahlrichs 1.9999999979072856
delley 1.9999999990380877
gauss_chebyshev 1.9999999994477295
mura_knowles 1.9999999997029547
````

cc Thijs @tvogels, Derk @derkkooi

**Comment by susilehtola** [comment]
Yes, Becke's scheme was pioneering but it is not very good; the Treutler-Ahlrichs grid is probably the best one. Note that we have a collection of reproducible DFT grids in https://github.com/wavefunction91/IntegratorXX/ and a high-performance quadrature implementation thereof exists in https://github.com/wavefunction91/GauXC

**Comment by awvwgk** [comment]
Thanks for the clarification. Closing this.

**Comment by tvogels** [comment]
I still believe there might be a problem here. It makes sense that some integration schemes are more efficient than others--they might provide better approximations with a lower number of evaluations. But the implementation of the Becke scheme in PySCF doesn't even converge to the right values as the number of evaluation points goes to infinity.

<img width="459" alt="image" src="https://github.com/user-attachments/assets/a90f09d6-3a68-4376-ac30-f811ef0b01cd">

You can also see the bias in the following experiment, where I use the radial integration schemes from PySCF to integrate uniform spheres of varying radius.

<img src="https://github.com/user-attachments/assets/b7b6642c-1ab2-4110-a2e7-f22100da9cf6" width="500">

I think the implementation is an incorrect interpretation of what Becke wrote in his paper (DOI:10.1063/1.454033). First of all, the function `numpy.polynomial.chebyshev.chebgauss` used in PySCF gives Gauss-Chebyshev quadrature of the *first* kind, and not the *second* kind, as specified in the paper. The quadrature points on the interval [-1, 1] should match those of the Treutler-Ahlrichs radi method. They are just transformed to the interval [0, inf) in a different way.

I think the correct implementation should look like:

```python
def corrected_becke(n, charge, *args, **kwargs):
    '''Becke, JCP 88, 2547 (1988); DOI:10.1063/1.454033'''
    if charge == 1:
        rm = radii.BRAGG[charge]
    else:
        rm = radii.BRAGG[charge] * .5

    # Points and weights for Gauss-Chebyshev quadrature points of the second kind
    # The weights are adjusted to integrate a function on the interval [-1, 1] with uniform weighting
    # instead of weighted by sqrt(1 - t^2) = sin(i pi / (n+1)).
    i = np.arange(n) + 1
    t = np.cos(i * np.pi / (n + 1))
    w = np.pi / (n + 1) * np.sin(i * np.pi / (n + 1))

    # Change of variables to map the domain to [0, inf)
    r = (1+t)/(1-t) * rm
    w *= 2/(1-t)**2 * rm

    return r, w
```

This corrected method approximates the volume of spheres much more accurately, and also converges to the right number of electrons

<img width="449" alt="image" src="https://github.com/user-attachments/assets/b64b4729-f891-4f5a-b653-21a2120f2047">

**Comment by tvogels** [comment]
I think the PR for this now merged, so should we close this?
