### ISSUE TITLE
Bugs in khf.get_fermi() and khf.get_bands()?

### ISSUE THREAD

**Issue by hungpham2017** [pyscf/pyscf#250]
Hello,

Apparently, there may be bugs in khf.get_fermi() and khf.get_bands() functions in **pyscf/pbc/scf/khf.py**
(I used PySCF 1.5.4)
1. get_fermi() always give the lowest eigenvalues as the Fermi level.
It can be fixed by transforming **mo_occ_kpts** into an array:
**line 167**: `nocc = np.count_nonzero(mo_occ_kpts != 0) `     
should be
`np.count_nonzero(np.asarray(mo_occ_kpts) != 0)`

2. khf.get_bands() gives huge eigenvalues in the example below.
I don't know where it goes wrong ...
The problem doesn't appear if KRKS is used instead of KHF. 

3. Also, KRKS needs to be called from dft modules: kks = dft.KRKS(cell, kpts)
if calling it from scf modules: kks = scf.KRKS(cell, kpts) , the kpts is not passed to the class.
It can be fixed by passing *args to the corresponding class:

in **pyscf/pbc/scf/__init__.py**

**line 72**: `return dft.KKS(cell)` should be `return dft.KKS(cell, *args)`
**line 88**: `return dft.KRKS(cell)` should be `return dft.KRKS(cell, *args)`

```
import numpy as np
from pyscf.pbc import gto, scf, dft
from functools import reduce

cell = gto.Cell()
cell.atom = [['H',[1.5,1.5,1.1]],['H',[1.5,1.5,1.9]]]
cell.basis = 'gth-szv'
cell.pseudo = 'gth-pade'
cell.a = np.eye(3)*3
cell.build()
nk = [1, 1, 2]
kpts = cell.make_kpts(nk)
khf = scf.KHF(cell,kpts)
ekpt = khf.run()

eFermi = khf.get_fermi()      # give the lowest eigenvalues
print(khf.mo_energy_kpts)

kpts_band = np.asarray([0, 0,  0.55415])
print(abs(kpts[1]-kpts_band).max())       # kpts[1] = kpts_band
print(np.asarray(khf.get_bands(kpts_band)[0]))     # give a huge number
print(np.asarray(khf.get_bands(kpts[1])[0]))
```

**Comment by tberkel** [comment]
Thanks for this bug report.

1.  I fixed this in 9dc4365f41efc844a118a8f86f4ba5507eda7970

2. This has to do with the handling of the divergence of the exchange potential, done using the `exxdiv` kwarg.  Using `None` or `ewald` (default) results in a potential that is discontinuous at G=0.  Instead, you can use `exxdiv='vcut_sph'`, which does a spherical truncation and leads to a continuous v(G) and well-defined band structure based on `get_bands()`.

3. This was fixed in d2cc80ca2b355796d337f4a25bb433d965e06291 -- however, even in the non-pbc code, it looks like the `__init__.py` file for the `scf` and `dft` modules sporadically passes `*args`, even though the classes never take an argument other than `mol`.  Unless @sunqm has a reason I don't know, we can clean up the `__init__.py` for both pbc and non-pbc `scf` and `dft` which may help catch errors like this in the future.

**Comment by sunqm** [comment]
I updated the get_fermi function in b108a12293fd57aac13811e1a12f91e7d23b077b. The linear dependence issue was considered.

**Comment by hungpham2017** [comment]
I have two follow-up questions about the use of exxdiv='vcut_sph' and exxdiv='ewald':

1. For exxdiv='ewald', the **get_k_kpts** function in pbc/df/df_jk.py will add a G0 correction to the **vk**.
However, I could not find similar treatment for **vk** if exxdiv='vcut_sph' is used. For exxdiv='vcut_sph', only the coulG kernel is modified in pbc/tools/pbc.py.

2. When computing the 2e integral as discussed in the equation (24) of _JCTC 2017, 13, 1209−1218_, the G0 singularity is simply removed. Does it cause an inconsistency with the Coulomb/exx computation in the mean-field calculation using exxdiv='vcut_sph'/'ewald'? and how does it affect the post hatree-fock calculation that requires these integrals? 

Thank you very much,
Hung

**Comment by gkc1000** [comment]
1. This is the correct behaviour. (I'm not sure what question you're asking
here).

2. The best way to think about exxdiv="anything other than None" is that
this a finite size correction to the exchange energy - it is derived using
the specific form of the exchange energy.
One does not need to use it, but it allows relatively small k-point meshes
to give "good" HF energies closer to the TDL.

In a post-HF calculation, the correlation contribution has a different q=0
finite size correction. We do not have a treatment for this in pyscf (this
is a research topic). So the only consistent way to handle this it to set
exxdiv=None for the correlation calculation.
One way to combine them is to do the HF calculation with exxdiv=None and
exxdiv="something else", obtain the HF finite size energy correction, and
add that to the correlation energy computed with exxdiv=None. This is a bit
like
doing separate CBS extrapolations for HF and the correlated parts of the
calculation.

**Comment by hungpham2017** [comment]
Thank you all for your insightful explanations and reference. It is much clearer now.
I am looking forward to seeing your paper on the topic.
Best,
Hung
