### ISSUE TITLE
Error of running SA-CASSCF

### ISSUE THREAD

**Issue by JunboLu** [pyscf/pyscf#2500]
Dear developers:
  I try to use pyscf to do SA-CASSCF. But I get an error:
Traceback (most recent call last):
  File "/mnt/sg001/home/fz_sustech_ljb/WORK/lujb/SA_CASSCF/Pr3+/CASSCF/input.py", line 137, in <module>
    solver.run(mo1)
  File "/mnt/sg001/home/fz_sustech_ljb/bin/pyscf-2.0.1/pyscf/lib/misc.py", line 512, in run
    self.kernel(*args)
  File "/mnt/sg001/home/fz_sustech_ljb/bin/pyscf-2.0.1/pyscf/mcscf/mc1step.py", line 812, in kernel
    _kern(self, mo_coeff,
  File "/mnt/sg001/home/fz_sustech_ljb/bin/pyscf-2.0.1/pyscf/mcscf/mc1step.py", line 349, in kernel
    e_tot, e_cas, fcivec = casscf.casci(mo, ci0, eris, log, locals())
  File "/mnt/sg001/home/fz_sustech_ljb/bin/pyscf-2.0.1/pyscf/mcscf/mc1step.py", line 834, in casci
    e_tot, e_cas, fcivec = casci.kernel(fcasci, mo_coeff, ci0, log)
  File "/mnt/sg001/home/fz_sustech_ljb/bin/pyscf-2.0.1/pyscf/mcscf/casci.py", line 546, in kernel
    e_tot, fcivec = casci.fcisolver.kernel(h1eff, eri_cas, ncas, nelecas,
  File "/mnt/sg001/home/fz_sustech_ljb/bin/pyscf-2.0.1/pyscf/mcscf/addons.py", line 1285, in kernel
    return numpy.einsum('i,i', numpy.array(es), weights), cs
  File "<__array_function__ internals>", line 5, in einsum
  File "/mnt/sg001/home/fz_sustech_ljb/bin/deepmd-kit-1.3.3/lib/python3.9/site-packages/numpy/core/einsumfunc.py", line 1350, in einsum
    return c_einsum(*operands, **kwargs)
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (49,)->(49,) (91,)->(91,)
  The input file looks like:

mol1 = gto.Mole()
mol1.atom = '''
Pr   0.0  0.0  0.0
'''

mol1.basis =  'def2tzvp'
mol1.charge = +3
mol1.symmetry = 0
mol1.verbose = 4
mol1.spin = 2
mol1.output = 'out.log'
mol1.build()

mf = scf.UHF(mol1).x2c()
mf.max_cycle = 1
mf.kernel()

mo_coeff = scf.chkfile.load('uo2.chk', 'scf/mo_coeff')
ma = mo_coeff[0]

solver = mcscf.CASSCF(mf, 7, 2)

solvers = []
solver1 = fci.direct_spin1.FCI(mol1)
solver1.spin = 0
solver1 = fci.addons.fix_spin(solver1,ss=0,shift=.1)
solver1.nroots = 28
solvers.append(solver1)

solver2 = fci.direct_spin1.FCI(mol1)
solver2.spin = 2
solver2 = fci.addons.fix_spin(solver2,ss=2,shift=.1)
solver2.nroots = 63
solvers.append(solver2)

mcscf.state_average_mix_(solver, solvers, np.ones(91)/91)
caslst = [28, 29, 30, 31, 33, 34, 35]
mo1 = mcscf.addons.sort_mo(solver,ma,caslst,1)

solver.run(mo1)

  Could anyone give a help?
  With my best regards,
  Junbo

**Comment by lzwlewis** [comment]
Hi,
Maybe you need to check `solver2.nroots` since there are at most 21 triplets for a trivalent Pr when the active space is spanned by the seven 4f orbitals, which is less than 63.

**Comment by JunboLu** [comment]
Thanks in advance! If I want to get the mrpt energy of each state, I need to do the nevpt2 for them. I tentatively write the script, and looks like:
#run SA-CASSCF
solver = mcscf.CASSCF(mf, 7, 2)
mycas.chkfile ='cas.chk'

solvers = []
solver1 = fci.direct_spin0.FCI(mol1)
solver1.spin = 0
solver1 = fci.addons.fix_spin(solver1,ss=0,shift=.1)
solver1.nroots = 28
solvers.append(solver1)

solver2 = fci.direct_spin1.FCI(mol1)
solver2.spin = 2
solver2 = fci.addons.fix_spin(solver2,ss=2,shift=.1)
solver2.nroots = 21
solvers.append(solver2)

mcscf.state_average_mix_(solver, solvers, np.ones(solver1.nroots+solver2.nroots)/(solver1.nroots+solver2.nroots))
caslst = [28, 29, 30, 31, 33, 34, 35]
mo1 = mcscf.addons.sort_mo(solver,ma,caslst,1)

solver.run(mo1)

#run CASCI followed by NEVPT2 with CASSCF orbitals
solver = mcscf.CASCI(mf, 7, 2)
solver.__dict__.update(scf.chkfile.load('cas.chk', 'mcscf'))
solver.fcisolver.nroots = 28
solver.fix_spin_(ss=0)
solver.kernel()

ci_nevpt_e1 = mrpt.NEVPT(mycas, root=0).kernel()
ci_nevpt_e2 = mrpt.NEVPT(mycas, root=1).kernel()
ci_nevpt_e3 = mrpt.NEVPT(mycas, root=2).kernel()
ci_nevpt_e4 = mrpt.NEVPT(mycas, root=3).kernel()
ci_nevpt_e5 = mrpt.NEVPT(mycas, root=4).kernel()
...
Is it right?

**Comment by lzwlewis** [comment]
My pleasure.
The `mycas` in your script was not explictly defined, so I'm not sure what is contained in `cas.chk`. If `mycas` is the same as 'solver', I think your script is seemed to be right

**Comment by JunboLu** [comment]
Thank you very much! If I calculate 4f^3 configuration, how many doublet and quartet states shall I use? For the quartet states, I do not know pyscf use what Ms.

**Comment by lzwlewis** [comment]
The number of multiplets can be calculated by Weyl formula. You may refer to (5:1) in page 234 of this book [https://link.springer.com/chapter/10.1007/978-3-642-58150-2_4](url).
For 4f^3 configuration, there are at most 112 doublets and 35 quartets. You can have a check.

**Comment by ZhebinGuan** [comment]
To build CASCI using converged CASSCF results, you should use the converged molecular orbital
```
mycasci.kernel(mycasscf.mo_coeff)
```
also see
[https://github.com/pyscf/pyscf/blob/master/examples/mrpt/41-for_state_average.py](https://github.com/pyscf/pyscf/blob/master/examples/mrpt/41-for_state_average.py)

And you should make sure `mycasci.nelecas` and `mycasci.fcisolver.spin` agree with the multiplicity you want.
