### ISSUE TITLE
Compilation issues with new mp functionalities in lib

### ISSUE THREAD

**Issue by jonas-greiner** [pyscf/pyscf#2503]
Hi everyone,
I am having issues compiling the mp dynamic library that was added through PR #2418. I assume these problems are likely compiler and BLAS/LAPACK distribution dependent. I am using gcc version 14.2.0 and OpenBLAS version 0.3.28. There appear to be multiple problems:

1. `pyscf/pyscf/lib/mp/mp2.c:513:9: error: implicit declaration of function 'dtrsm_'`
This can be fixed by adding the following code to `fblas.h` which was already suggested by @chillenb in PR #2418:
```
void dtrsm_(const char *side, const char *uplo, const char *transa, 
            const char *diag, const int *m, const int *n, const double *alpha,
            const double *a, const int *lda, const double *b, const int *ldb);
```

2. `pyscf/pyscf/lib/mp/mp2.c:492:16: error: implicit declaration of function 'floor'`
This can be fixed by adding `#include <math.h>` at the top of `mp2.c`.

3. `pyscf/pyscf/lib/mp/mp2.c:219:17: error: assignment to 'double **' from incompatible pointer type 'const double **'`
This error is due to the fact that the pointers returned by `_gen_ptr_arr` in lines 112 and 219 point to constant values while these are being assigned to pointers that are declared to point to non-constant values. Not sure if `parr_t2` couldn't just be declared as `const double **`?

**Comment by chillenb** [comment]
I got exactly the same errors with GCC 14.2.1 and MKL 2024.2.

Error 3 can be fixed by changing `const double **` ("pointer to pointer to const double") to `double **const` ("const pointer to pointer to double") everywhere.

**Comment by chillenb** [comment]
I was being silly about `double **const`. @jonas-greiner's solution works, is easier, and also preserves the constness of the ERIs. See #2511

**Comment by jonas-greiner** [comment]
Thanks for your work on the PR! I was hesitant to open one because I was a bit unsure about the changes fixing error 3 and how that affects the interface to Python.
