### ISSUE TITLE
dyall basis missing from public release channel

### ISSUE THREAD

**Issue by xubwa** [pyscf/pyscf#2516]
Hi all,
I was recently told that pyscf does not have dyall set included via conda channel and/or pip channel. I tested it myself and found it was true. Since I have little knowledge about the packaging and release process, could anyone kindly take some time to look at this issue?
Best regards,
Xubo

**Comment by hebrewsnabla** [comment]
Because the dyall-basis folder does not have a `__init__.py` or consist of dat files (like pople-basis).
