### ISSUE TITLE
Incorrect conjugation in 2RDM transformations

### ISSUE THREAD

**Issue by obackhouse** [pyscf/pyscf#2519]
PySCF typically uses the following conventions for DMs
```
dm1[p, q] = <q* p>
dm2[p, q, r, s] = <p* r* s q>
```

From Helgaker (3.2), when transforming operators under unitary $U$, the annihilation operator transforms under the conjugate $U^*$, and the creation operator transforms under $U$. This means that following the PySCF conventions, the 1RDM transforms as the Hamiltonian does i.e.
```python
dm1_ao = einsum("ij,pi,qj->pq", dm1_mo, c, c.conj())
```
but the 2RDM should transform as
```python
dm2_ao = einsum("ijkl,pi,qj,rk,sl->pqrs", dm2_mo, c.conj(), c, c.conj(), c)
```
whereas in PySCF the 2RDM is also assumed to transform as the Hamiltonian (the conjugations are reversed):
https://github.com/pyscf/pyscf/blob/2c7f7625fd2719b8f3e9715e40c3937cab65c06e/pyscf/cc/ccsd_rdm.py#L379-L381

This can be verified by trying to recover correlated energies using the RDMs in the AO basis via `ao_repr=True`, which fails, but works with the reverse transformation. See the following script for an example:
https://gist.github.com/obackhouse/855724a176c7f9cad580dc2d39e7c63d
We're aware in this case that the coefficients are not actually a unitary, but this is the best way I could find to show this as an issue in PySCF, and the issue seems to apply at least to the MO->AO transformation.

I am happy to fix but wanted to check if we are missing something first?

**Comment by sunqm** [comment]
Probably related to #1568
