### ISSUE TITLE
M1 Mac / Build from source PySCF / incompatible architecture (have (arm64), need (x86_64)

### ISSUE THREAD

**Issue by lionelalexandre** [pyscf/pyscf#2546]
@jamesETsmith, thank you for your reply. 

I have a Apple M1 Max. My suspicion is now that the error comes from having the M1 chip. 

1) I added the libomp file to the correct path `/usr/local/opt/libomp/lib/libomp.dylib` by  `ln -s /opt/homebrew/Cellar/libomp/15.0.4/lib/ /usr/local/opt/libomp/lib`, but now I receive another error (see picture). The error is: (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')).

<img width="1344" alt="Screenshot 2022-11-12 at 11 32 31 AM" src="https://user-images.githubusercontent.com/46899159/201484452-2cf277d0-bca6-4e90-a0e1-24255510cdb3.png">

2) When I ran `pip install git+https://github.com/pyscf/pyscf`, I receive the error:

<img width="1356" alt="Screenshot 2022-11-11 at 5 24 13 PM" src="https://user-images.githubusercontent.com/46899159/201439137-1dadfa30-9249-45c4-9d67-efe8fcd15181.png">

_Originally posted by @pwkj in https://github.com/pyscf/pyscf/issues/1511#issuecomment-1312237151_

**Comment by lionelalexandre** [comment]
I get an issue when launching PySCF installed from source on my Mac (M1), from :
$ python -c "from pyscf import gto"

I get :
pyscf plugins found in 
/Users/lioneltruflandier/pyscf-master/./pyscf
/Users/lioneltruflandier/opt/anaconda3/lib/python3.9/site-packages/pyscf
When PYTHONPATH is set, it is recommended to load these plugins through the environment variable PYSCF_EXT_PATH
Traceback (most recent call last):
  File "/Users/lioneltruflandier/pyscf-master/pyscf/lib/misc.py", line 97, in load_library
    return numpy.ctypeslib.load_library(libname, _loaderpath)
  File "/Users/lioneltruflandier/opt/anaconda3/lib/python3.9/site-packages/numpy/ctypeslib.py", line 149, in load_library
    return ctypes.cdll[libpath]
  File "/Users/lioneltruflandier/opt/anaconda3/lib/python3.9/ctypes/__init__.py", line 457, in __getitem__
    return getattr(self, name)
  File "/Users/lioneltruflandier/opt/anaconda3/lib/python3.9/ctypes/__init__.py", line 452, in __getattr__
    dll = self._dlltype(name)
  File "/Users/lioneltruflandier/opt/anaconda3/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/lioneltruflandier/pyscf-master/pyscf/lib/libnp_helper.dylib, 0x0006): tried: '/Users/lioneltruflandier/pyscf-master/pyscf/lib/libnp_helper.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64)))

Everything works fine when installed with pip but I am interested in implementing new functionalities on my fork of the package. After checking, I don't find any solution to this problem. Maybe this has already been resolved. Thank you very much for your precious help.
Lionel

**Comment by mkrompiec** [comment]
It looks like a conflict of compilers on your machine. Make sure all components of your toolchain (including your python) are either for arm64 or x86_64. Unfortunately, macos makes it very easy to mix these and until you try building something, everything works seamlessly due to emulation.

**Comment by lionelalexandre** [comment]
thank you ; that was the point! Had to clean my python env and make sure everything was built for arm.
