### ISSUE TITLE
How to solve the difficult in converge of molecules included heavy atoms

### ISSUE THREAD

**Issue by ZipengAn** [pyscf/pyscf#2553]
Hello, I’ve been working with PySCF to perform calculations on molecules containing heavy atoms, such as Sn(CH3)3. However, I’m encountering issues with convergence when using the B3LYP/def2-TZVPD level of theory. Could you provide some suggestions on how to address this problem, such as adjusting suitable parameters or methods?
Thank you very much for your help!

**Comment by jeanwsr** [comment]
level shift and soscf. See https://pyscf.org/user/scf.html#converging-scf-iterations

**Comment by ZipengAn** [comment]
> level shift and soscf. See https://pyscf.org/user/scf.html#converging-scf-iterations

Thanks for your reply, the issue has been resolved.
