### ISSUE TITLE
How to imply ECP to atom with empty basis?

### ISSUE THREAD

**Issue by ustcwdd** [pyscf/pyscf#2560]
Dear developers in Pyscf,
    When we do qmmm calculation, boundary region can be set with atoms without basis and with whole electrons capped by ECP. But when I want to realize it in pyscf, two questions are encountered. Firstly, how to set empty basis? It seems that I can do it without setting a basis set to these atoms; Secondly, when I don't set basis for these atoms, and test a right ECP, it will raise KeyError(symb). 
    I don't know how to deal with it. My code and error messages are in the attachment.
    Looking forward to your reply. Thanks a lot.
[ECP-empty-basis.txt](https://github.com/user-attachments/files/18140543/ECP-empty-basis.txt)

**Comment by jeanwsr** [comment]
I've tried similar thing before and my solution is to modify the ecp head from `nelec 10` to `nelec 0`.

Btw, defining atoms with empty basis does not meet your idea, as their nuc charge and electron number are not affected.
You need to follow the definition of ghost atoms (https://github.com/pyscf/pyscf/blob/master/examples/gto/03-ghost_atom.py) to make sure the nuc charge and electron number of the atom is zero.

**Comment by ustcwdd** [comment]
I have tried this schecule(ghost atoms with nelec 0 of ecp) in MRCC software earlier. It gives different energy compared with atoms capped with nelec 12 of ecp. But upon further reflection, this strategy should also be feasible. Thank you for your answer. Wish you smooth progress in your scientific research and everything go well with you.
