### ISSUE TITLE
Questions about dft.numint.eval_rho()

### ISSUE THREAD

**Issue by sehun1618** [pyscf/pyscf#2567]
Thanks for effort of PySCF team.

Recently, I've been trying to plot Density in realspace using the numint.eval_rho() function.

While plotting the density of He atoms, I noticed something strange.

I got the density matrix calculated with 100%PBE, 50%PBE and no XC and plotted the density on one axis with the functions numint.eval_ao and numint.eval_rho.

```python
mol = gto.M(
atom = """
He
""",
basis = 'augccpvtz'
)

mydft1 = dft.RKS(mol).density_fit()
mydft1.xc = 'PBE'
mydft1.grids.level = 9
mydft1.kernel()
dm1 = mydft1.make_rdm1()

mydft2 = dft.RKS(mol).density_fit()
mydft2.xc = '.5*PBE'
mydft2.grids.level = 9
mydft2.kernel()
dm2 = mydft2.make_rdm1()

mydft3 = dft.RKS(mol).density_fit()
mydft3.xc = ''
mydft3.grids.level = 9
mydft3.kernel()
dm3 = mydft3.make_rdm1()

def gen_coords_x(z_min, z_max, n_points):
    z = np.linspace(z_min, z_max, n_points)
    coords = np.zeros([z.shape[0], 3])
    coords[:, 0] = z
    return coords

x = gen_coords_x(-5,5,1001)

ao_x = numint.eval_ao(mol, x, deriv=0)
rho1_x = numint.eval_rho(mol, ao_x, dm1)
rho2_x = numint.eval_rho(mol, ao_x, dm2)
rho3_x = numint.eval_rho(mol, ao_x, dm3)

plt.plot(x[:,0], rho1_x, label = '100% PBE')
plt.plot(x[:,0], rho2_x, label = '50% PBE')
plt.plot(x[:,0], rho3_x, label = '0% PBE (0% XC)')
plt.xlim(-2,2)
plt.legend()
plt.show()
``` 

![image](https://github.com/user-attachments/assets/7f7f333a-ba7d-457d-be9e-06c315c82ee5)

As you can see in the graph, the peak of density varies depending on the percentage of PBE. 

I thought that when I integrated the density without XC over the whole space, the number of electrons coming out would seem insufficient compared to the density with 100% PBE. So I used the code below to compare the values.

```python
coords = mydft1.grids.coords
weights = mydft1.grids.weights

ao = numint.eval_ao(mol, coords)
rho1 = numint.eval_rho(mol, ao, dm1)
rho2 = numint.eval_rho(mol, ao, dm2)
rho3 = numint.eval_rho(mol, ao, dm3)

print('PBE      ',np.einsum('r,r', rho1, weights))
print('50% PBE  ',np.einsum('r,r', rho2, weights))
print('0% XC    ',np.einsum('r,r', rho3, weights))
``` 
| Functional | # of electrons |
|--------|--------|
| PBE | 1.999999997180982 |
| 50% PBE | 1.9999999665640233 |
| 0% XC | 1.9999998137042763 | 

Results show that the integral decreases as the percentage of XC decreases. 

I'm wondering if this is natural, or if there's something wrong with my code.

**Comment by sehun1618** [comment]
Thank you for your detailed response.

I understand that increasing the grid size to a larger one will further reduce the difference in electron count. 

![image](https://github.com/user-attachments/assets/0894a877-baf5-4d39-9400-57f1a24f56ab)

Nevertheless, the graph looks very unnatural, as if the amount of density itself decreases as the fraction of PBEs decreases.

Is there anything you can tell me about this?

**Comment by susilehtola** [comment]
Explanation was already above.

**Comment by MatthewRHermes** [comment]
The only reason it looks unnatural is that human eyes cannot see on the graph the regions where the green curve is higher than the orange and blue curves. There must be such regions, since the density integrates to the same number to within numerical tolerance. There is nothing _prima facie_ wrong with different functionals having different opinions on how tightly the density is localized around the nucleus.

**Comment by sehun1618** [comment]
@susilehtola @MatthewRHermes 

Thanks. I checked the entire space and found that there was no problem.
