### ISSUE TITLE
How to imply full ECP to atom with empty basis

### ISSUE THREAD

**Issue by ustcwdd** [pyscf/pyscf#2568]
In the last topic https://github.com/pyscf/pyscf/issues/2560#:~:text=with%20empty%20basis%3F-,%232560,-Closed, we talk about two way to set boundary region in qmmm. But ghost atoms with "nelec = 0" of ecp does not meet my needs. I still want to imply full ecp to real atoms with empty basis. 
Previously, I thought I can do it without setting a basis set to these atoms. But, from the source code, it will skips the basis set configuration. I'm not sure how it proceeds after skipping. If these way is not right, how can I set a empty basis set for atoms?
Looking forward to everyone's replies, and wish you all smooth scientific research.

**Comment by jeanwsr** [comment]
What do you mean by "full ecp"? Does this atom have electrons?

From my understanding of qmmm with an ecp region (https://doi.org/10.1021/acs.jctc.0c00067, etc.), the ecp region should not have electrons and nuc charges.

**Comment by ustcwdd** [comment]
It can also be setted with real atoms(not ghost atoms) with empty basis with setting "nelec = N" of ecp. N is the whole electrons of the real atoms. Like Li, N = 3. That means the nuc charges and electrons are not dealed with quantum mechanics and they all replaced by ecp. It can have similar results with your settings.

**Comment by jeanwsr** [comment]
Yeah, in principle the `nelec = N` approach is right. And I can confirm that it's the same as ghost atom when using HF. A minimal working example is
```
# no ghost atom
mol = gto.M(atom='''Ag0 .0 .0 .0; Ag1 .0 .0 1.0''',
basis={'Ag0': 'def2-svp'},
ecp = {'Ag0':'def2-svp',
'Ag1':gto.basis.parse_ecp(
'''
ECP
Ag nelec 47
Ag ul
2      14.2200000            -33.68992012
2       7.1100000             -5.53112021
Ag S
2      13.1300000            255.13936452
2       6.5100000             36.86612154
2      14.2200000             33.68992012
2       7.1100000              5.53112021
Ag P
2      11.7400000            182.18186871
2       6.2000000             30.35775148
2      14.2200000             33.68992012
2       7.1100000              5.53112021
Ag D
2      10.2100000             73.71926087
2       4.3800000             12.50211712
2      14.2200000             33.68992012
2       7.1100000              5.53112021
END
'''
)
},
spin=1, verbose=4)
mf = mol.UHF()
mf.init_guess='1e'
mf.kernel()

# ghost atom
mol = gto.M(atom='''Ag0 .0 .0 .0; X-Ag1 .0 .0 1.0''',
basis={'Ag0': 'def2-svp'},
ecp = {'Ag0':'def2-svp',
'X-Ag1':gto.basis.parse_ecp(
'''
ECP
Ag nelec 0
Ag ul
2      14.2200000            -33.68992012
2       7.1100000             -5.53112021
Ag S
2      13.1300000            255.13936452
2       6.5100000             36.86612154
2      14.2200000             33.68992012
2       7.1100000              5.53112021
Ag P
2      11.7400000            182.18186871
2       6.2000000             30.35775148
2      14.2200000             33.68992012
2       7.1100000              5.53112021
Ag D
2      10.2100000             73.71926087
2       4.3800000             12.50211712
2      14.2200000             33.68992012
2       7.1100000              5.53112021
END
'''
)
},
spin=1, verbose=4)
mf = mol.UHF()
mf.init_guess='1e'
mf.kernel()
```
The energy of this two UHF should be the same. Note that the default minao guess does not work for `nelec = N`, so switching to 1e guess is needed.

As for UKS, the energies will be different to some extent. And we can see there's a difference in total grid number, which may indicates the "no ghost atom" approach assigns grid on ecp region but "ghost atom" approach does not. I think it should have grids so "ghost atom" is right here.

**Comment by jeanwsr** [comment]
https://github.com/pyscf/pyscf/blob/3ac31c82a15c6f222d35b3b5f57e53899a50eb87/pyscf/dft/gen_grid.py#L197-L216

Maybe we should change this function to not assigning any grid for ghost atom. (The current behavior is that it's assigned a minimal grid)
```
atom Ag0 rad-grids = 95, ang-grids = [ 50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50
  50  50  50  50  50  50  50  50  50  50  50  86  86  86  86  86  86  86
  86  86  86  86  86  86  86  86 350 350 350 350 350 350 350 350 350 350
 350 434 434 434 434 434 434 434 434 434 434 434 434 434 434 434 434 434
 434 434 434 434 434 350 350 350 350 350 350 350 350 350 350 350 350 350
 350 350 350 350 350]
atom X-Ag1 rad-grids = 50, ang-grids = [ 50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50
  50  50  50  50  50  50  50  86  86  86  86  86  86 266 266 266 266 266
 266 266 302 302 302 302 302 302 302 302 302 302 302 302]
```
