### ISSUE TITLE
real-space electrostatic potential

### ISSUE THREAD

**Issue by freude** [pyscf/pyscf#258]
Is there a way I can compute a real-space electrostatic potential defined on a grid of a molecular ion? Using DFT and `numint` I see how to extract the electron density by `pyscf.dft.numint.eval_rho()` I have a hard time to find an analogous function for the electrostatic potential. Is there a way?

**Comment by sunqm** [comment]
The key function to generate basis to mimic delta function is gto.fakemol_for_charges
Here is a relevant example
https://github.com/pyscf/pyscf/blob/master/pyscf/qmmm/itrf.py#L101

**Comment by sunqm** [comment]
Here is a relevant example https://github.com/pyscf/pyscf/blob/master/examples/1-advanced/031-MEP.py
