### ISSUE TITLE
geometry optimization with pyberny + ddcosmo.py

### ISSUE THREAD

**Issue by jakobkraus** [pyscf/pyscf#260]
Hi,

I am not entirely sure if this is the best place to post this or if I should turn to the pyberny site, instead, but
I would be very grateful for your support.
If I start a single self-consistent DFT calculation including solvent effects, as treated by ddcosmo.py, everything is fine. However, if I try to combine a geometry optimization using pyberny with this calculation, it crashes for basis sets which are larger than 631gs, for both the Newton solver and the DIIS solver.
Then, I get error messages like:
"RuntimeError: The trust radius got too small, check forces? "    , or, alternatively,
"berny.Math.FindrootException".

Here is a small example for a script that crashes:

from __future__ import division
from pyscf import gto, dft
from pyscf.solvent import ddcosmo, ddpcm
from ase.io import read
from ase.atoms import Atoms
import numpy as np
from pyscf.data import radii
from berny import optimize
from pyscf.grad import uks
from pyscf.geomopt import *
import time

def ase2pyscf(ase_atoms):
        return [[atom.symbol, atom.position] for atom in ase_atoms]

t_start = time.time()

# System 
atoms= read('acetic_acid.xyz')
spin = 0
charge = 0
basis = '6311++gss'
xc = 'LDA,VWN'

mol = gto.M(atom=ase2pyscf(atoms), basis=basis,spin=spin,charge=charge) 
mol.verbose = 4

mf = dft.UKS(mol)
mf.xc = xc
mf.max_cycle = 300
mf.conv_tol = 1e-6
cm = ddcosmo.DDCOSMO(mol)

cm.eps = 78.4
cm.lmax = 10
cm.eta = 0.1
cm.lebedev_order = 89
cm.radii_table = radii.VDW
cm.verbose = 4
mf = ddcosmo.ddcosmo_for_scf(mf, cm)
mf.verbose = 4
mf.kernel()
optimize(mf)

If necessary, I can also provide the acetic_acid.xyz file. (I downloaded the acetic acid geometry from PUBCHEM as a .sdf file, opened it with ase-gui and saved it as a .xyz file.)

Thanks in advance,

Jakob Kraus

**Comment by sunqm** [comment]
We sometimes see this error when the initial geometry is bad. Solvent should not be reason of this error. It's helpful to see your initial geometry of acetic_aci.

@azag0 Any idea regards to this problem?

**Comment by azag0** [comment]
I can have a look when I have the initial geometry.

Are the implicit solvent gradients certainly correct?

**Comment by jakobkraus** [comment]
Hi

My initial geometry looks like this:

8

O     -0.30350000       1.28900000      -0.00020000        

O     -0.98000000      -0.88780000      -0.00020000       

C      1.37430000      -0.35160000      -0.00020000        

C     -0.09070000      -0.04960000       0.00060000       

H      1.83680000       0.05700000      -0.90210000       

H      1.84000000       0.06760000       0.89520000       

H      1.52070000      -1.43560000       0.00640000       

H     -1.25980000       1.50810000      -0.00080000

Thanks for your replies and your support!
