### ISSUE TITLE
What's the real meaning of the direct (dms, atm, bas, env, vhfopt=None, hermi=0, cart=False)? 

### ISSUE THREAD

**Issue by RockyZhangHKU** [pyscf/pyscf#278]
Hi, I am a new phd student for Quantum Chemistry and now focus on studying HF algorithm. Is there anyone can tell me that what's the real meaning of the fuction 
`direct(dms, atm, bas, env, vhfopt=None, hermi=0, cart=False) `
in the line 158 of `scf/_vhf.py` ?

**Comment by sunqm** [comment]
scf/_vhf.py is a wrapper to interface some C functions for J/K builder. Functions defined in this module are not supposed to be called directly. They may be changed constantly and there is no backward compatibility guaranteed.  Here is a better Python wrapper for J/K builder  https://github.com/pyscf/pyscf/blob/master/pyscf/scf/jk.py#L35

**Comment by RockyZhangHKU** [comment]
> scf/_vhf.py is a wrapper to interface some C functions for J/K builder. Functions defined in this module are not supposed to be called directly. They may be changed constantly and there is no backward compatibility guaranteed. Here is a better Python wrapper for J/K builder https://github.com/pyscf/pyscf/blob/master/pyscf/scf/jk.py#L35

**Comment by RockyZhangHKU** [comment]
> scf/_vhf.py is a wrapper to interface some C functions for J/K builder. Functions defined in this module are not supposed to be called directly. They may be changed constantly and there is no backward compatibility guaranteed. Here is a better Python wrapper for J/K builder https://github.com/pyscf/pyscf/blob/master/pyscf/scf/jk.py#L35

Hi, Thanks for your reply, I got it that the _vhf.py is a wrapper. Well, I still want to confirm the detailed meaning of the `direct` function That’s because I am debugging a similar hf algorithm code and there is a confusion about the function `get_jk(mol, dm, hermi=1, vhfopt=None)` in the following code. In the function `get_jk`, it seems that calling the `direct` function in the `_vhf.py` to create `vj` and `vk`. But I don't know why it uses this function to creat `vj` and `vk`.
 
`# Import the packages needed`
`import numpy`
`import scipy`
`from numpy.linalg import norm`
`from pyscf import gto, scf`
`from pyscf.scf import _vhf`

`# Calculate the nuclear repulsion energy`
`def energy_nuc(mol, charges=None, coords=None):`
   ` e_nuc = mol.energy_nuc()`
    `return e_nuc`

`# Calculate the electronic energy`
`def energy_elec(mol, dm=None, h1e=None, vhf=None):`
   ` if dm is None: dm = init_guess(mol)`
   ` if h1e is None: h1e = get_h(mol)`
   ` if vhf is None: vhf = get_veff(mol, dm)`
   ` e1 = numpy.einsum('ij,ji', h1e, dm).real`
   ` e_coul = numpy.einsum('ij,ji', vhf, dm).real * .5`
    `return e1+e_coul, e_coul`

`# Calculate the total energy`
`def energy_tot(mol, dm=None, h1e=None, vhf=None):`
    `e_tot = energy_elec(mol, dm, h1e, vhf)[0] + energy_nuc(mol)`
    `return e_tot.real`
`...`

`# Calculate the Coulomb matrix J and the Exchange matrix K from 2-electron integral`
`def get_jk_eri(mol, dm, hermi=1, vhfopt=None):`
    `dm = numpy.asarray(dm) `
   ` eri = integ_2e(mol)`
  `  nao = dm.shape[-1] `
   ` dms = dm.reshape(-1,nao,nao) `
    `if eri.dtype == numpy.complex128 or eri.size == nao**4: `
       ` eri = eri.reshape((nao,)*4)`
       ` vj = numpy.empty(dms.shape, dtype=eri.dtype) `
       ` vk = numpy.empty(dms.shape, dtype=eri.dtype) `
       ` for i, dmi in enumerate(dms):`
            `vj[i] = numpy.einsum('ijkl,ji->kl', eri, dmi) `
           ` vk[i] = numpy.einsum('ijkl,jk->il', eri, dmi) `
    `else:`
        `vj = numpy.empty_like(dms) `
        `vk = numpy.empty_like(dms)` 
        `for i, dmi in enumerate(dms):`
            `vj[i], vk[i] = _vhf.incore(eri, dmi.real, hermi=hermi)` 
           ` if dms.dtype == numpy.complex128:`
                `jk = _vhf.incore(eri, dmi.imag, hermi=0)` 
                `vj[i] += jk[0] * 1j` 
                `vk[i] += jk[1] * 1j`
    `return vj.reshape(dm.shape), vk.reshape(dm.shape)`
   
`# Calculate matrix J and matrix K from density matrix`
`def get_jk(mol, dm, hermi=1, vhfopt=None):`    
    `dm = numpy.asarray(dm, order='C')`  
    `nao = dm.shape[-1]`  
    `if dm.dtype == numpy.complex128:`  
        `dms = numpy.vstack((dm.real, dm.imag)).reshape(-1,nao,nao)` 
        `vj, vk = _vhf.direct(dms, mol._atm, mol._bas, mol._env,`   
                `vhfopt=vhfopt, hermi=0, cart=mol.cart)` 
        `vj = vj.reshape(2,-1,nao,nao)` 
        `vk = vk.reshape(2,-1,nao,nao)` 
        `vj = vj[0] + vj[1] * 1j` 
        `vk = vk[0] + vk[1] * 1j`
    `else:`
        `vj, vk = _vhf.direct(dm.reshape(-1,nao,nao), mol._atm, mol._bas, mol._env,`
                             `vhfopt=vhfopt, hermi=hermi, cart=mol.cart) `
    `return vj.reshape(dm.shape), vk.reshape(dm.shape)`

**Comment by gkc1000** [comment]
"direct" is building the J/K matrix in integral-direct fashion, i.e. the
integrals are computed on the fly and contracted with the DM. This is done
inside the C functions in libcvhf.
