### ISSUE TITLE
IndexError during the state_average calculation

### ISSUE THREAD

**Issue by jamcas** [pyscf/pyscf#292]
My input file:
import os
from pyscf import gto, scf, mcscf, dmrgscf, lib, mrpt, qmmm, tools
import sys
from pyscf.tools import molden
from pyscf import dft
import numpy

dmrgscf.settings.MPIPREFIX = 'mpirun -np 10'

os.system('date')

mol = gto.Mole()
mol.verbose = 4
mol.atom = open('aabb-omega.xyz').read()
mol.basis = 'Def2-SVP'
mol.spin = 1
mol.charge = -2
mol.max_memory = 60000
mol.build()

# dft
mf = dft.UKS(mol)
mf.max_cycle = 500
mf.xc = 'b3lyp'
mf.level_shift = 0.5
mf.__dict__.update(lib.chkfile.load('aabb-omega-scf.chk', 'scf'))

# dmrgscf
mc = mcscf.state_average_(dmrgscf.DMRGSCF(mf, 20, 21), [.5,.5])
mc.__dict__.update(lib.chkfile.load('/home/chenh/ly/pyscf-scratch/48489/tmp3b42rudz', 'mcscf'))
mc.max_cycle_macro = 1000
mc.conv_tol = 1e-4
mc.conv_tol_grad = 0.1
mc.fcisolver.memory = 60
mc.fcisolver.maxM = 50
mc.fcisolver.spin = 1
mc.fcisolver.scheduleMaxMs  = [50]
mc.fcisolver.scheduleSweeps = [0]
mc.fcisolver.scheduleTols = [1e-10]
mc.fcisolver.scheduleNoises = [0]
mc.kernel()
mc.analyze()

mo_coeff_nature, ci_nature, occ_nature = mc.cas_natorb(sort=True)
mcscf.chkfile.dump_mcscf(mc, mo_coeff=mo_coeff_nature, mo_occ=occ_nature)
molden.from_mo(mol, 'aabb-omega-point_charges-20o21e-state_average-1.molden', mo_coeff=mo_coeff_nature, ene=None, occ=occ_nature)

**The error:**
Traceback (most recent call last):
  File "aabb-omega-point_charges.py", line 75, in <module>
    mc.kernel()
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mcscf/mc1step.py", line 776, in kernel
    self._finalize()
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mcscf/addons.py", line 680, in _finalize
    old_finalize()
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mcscf/casci.py", line 804, in _finalize
    ss = self.fcisolver.spin_square(self.ci, self.ncas, self.nelecas)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mcscf/addons.py", line 668, in spin_square
    res = fcibase_class.spin_square(self, ci0[i], norb, nelec)
IndexError: invalid index to scalar variable.

**Comment by sunqm** [comment]
Does the example https://github.com/sunqm/pyscf/blob/master/examples/dmrg/01-dmrg_casscf_with_stackblock.py work on your computer?

**Comment by jamcas** [comment]
@sunqm ，yes,it does。When I use another method, it generates a new error. My pyscf version is 1.6.0
# dmrgscf
mc = dmrgscf.DMRGSCF(mf, 20, 21)
mc.state_average_([0.5,0.5])
mc.max_cycle_macro = 1000
mc.conv_tol = 1e-4
mc.conv_tol_grad = 0.1
mc.fcisolver.memory = 60
mc.fcisolver.maxM = 50
mc.fcisolver.spin = 1
mc.fcisolver.scheduleMaxMs  = [50]
mc.fcisolver.scheduleSweeps = [0]
mc.fcisolver.scheduleTols = [1e-10]
mc.fcisolver.scheduleNoises = [0]
mo = lib.chkfile.load('/home/chenh/ly/pyscf-scratch/66599/tmpiwvzbyqy', 'mcscf/mo_coeff')
mc.kernel(mo)
mc.analyze()

mo_coeff_nature, ci_nature, occ_nature = mc.cas_natorb(sort=True)
mcscf.chkfile.dump_mcscf(mc, mo_coeff=mo_coeff_nature, mo_occ=occ_nature)
molden.from_mo(mol, 'aabb-omega-point_charges-20o21e-state_average-2.molden', mo_coeff=mo_coeff_nature, ene=None, occ=_nature)

### Traceback (most recent call last):
  File "aabb-omega-point_charges.py", line 75, in <module>
    mc.kernel(mo)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mcscf/mc1step.py", line 776, in kernel
    self._finalize()
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mcscf/addons.py", line 680, in _finalize
    old_finalize()
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mcscf/casci.py", line 808, in _finalize
    for i, e in enumerate(self.e_cas):
TypeError: 'NoneType' object is not iterable

**Comment by jamcas** [comment]
I am very sorry that I have omitted some important information that caused the problem description not to be particularly detailed. I think this error  is caused by background charges:  

>>> from pyscf import gto, scf, mcscf, qmmm, dmrgscf
>>>import numpy
>>>mol = gto.M(atom="N 0 0 0; N 0 0 1", basis="ccpvdz")
>>> mf = scf.RHF(mol).run()
>>>mc = dmrgscf.DMRGSCF(mf, 4, 4)
>>> mc.state_average_([0.5, 0.5])
<pyscf.mcscf.mc1step.CASSCF object at 0x2b9da4d43470>
>>> numpy.random.seed(1)
>>> coords = numpy.random.random((5,3)) * 10
>>> charges = (numpy.arange(5) + 1.) * -.1
>>> mc = qmmm.mm_charge(mc, coords, charges)
>>> mc.run()
CASSCF energy = -108.765048441597
### Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/lib/misc.py", line 467, in run
    self.kernel(*args)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mcscf/mc1step.py", line 787, in kernel
    self._finalize()
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mcscf/addons.py", line 680, in _finalize
    old_finalize()
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mcscf/casci.py", line 825, in _finalize
    for i, e in enumerate(self.e_cas):
### TypeError: 'NoneType' object is not iterable
  
  And when i put  mc.state_average_([0.5, 0.5]) after  mc = qmmm.mm_charge(mc, coords, charges) , it can run normally. But if i use mc.analyze() another error will generate:
>>>mc = dmrgscf.DMRGSCF(mf, 4, 4)
>>> numpy.random.seed(1)
>>> coords = numpy.random.random((5,3)) * 10
>>> charges = (numpy.arange(5) + 1.) * -.1
>>> mc = qmmm.mm_charge(mc, coords, charges)
>>> mc.state_average_([0.5, 0.5])
<pyscf.qmmm.itrf.mm_charge.<locals>.QMMM object at 0x2b9da668d080>
>>> mc.run()
CASSCF energy = -108.765048441597
CASCI E = -108.765048441597  E(CI) = -5.35066686792943  S^2 = 0.0000000
CASCI energy for each state
  State 0 weight 0.5  E = -108.997867877111 S^2 = 0.0000000
  State 1 weight 0.5  E = -108.532229006083 S^2 = 0.0000000
<pyscf.qmmm.itrf.mm_charge.<locals>.QMMM object at 0x2b9da668d080>
>>> mc.analyze()
### Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mcscf/casci.py", line 91, in analyze
    casdm1a, casdm1b = casscf.fcisolver.make_rdm1s(civec, ncas, nelecas)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mcscf/addons.py", line 650, in make_rdm1s
    dm1s = fcibase_class.make_rdm1s(self, ci0[i], norb, nelec)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/dmrgscf/dmrgci.py", line 287, in make_rdm1s
    dm1, dm2 = self.make_rdm12(state, norb, nelec, link_index, **kwargs)
### TypeError: make_rdm12() takes 4 positional arguments but 5 were given

You can use the simple example above to run on your computer.

**Comment by sunqm** [comment]
Fixed in PR #296
