### ISSUE TITLE
[Bug] IAO does not span the occupied space

### ISSUE THREAD

**Issue by zhcui** [pyscf/pyscf#294]
Hi all,

The current IAO code has a bug, i.e. the trace of density matrix in IAO basis is not equal to the number of electrons in the system.  The IAO, from design, should span the occupied space. You can check the trace of `dm` in `02-pop_with_iao.py` example, which has error compared with nelectron.

The bug comes from a missing orthogonalization for the intermediate `ctild` (see equation (1) and Appendix C in IAO paper for details).  We only need to add one line to fix it, i.e.
`ctild = orth.vec_lowdin(ctild, s1)`

Best,
Zhihao

**Comment by gkc1000** [comment]
Please submit a pull request.

**Comment by zhcui** [comment]
Hi Garnet,

I have created a pull request, which fixes this issue and allows k point sampling for IAO.

Best,
Zhihao

**Comment by sunqm** [comment]
Fixed in PR #295
