### ISSUE TITLE
'LD_LIBRARY_PATH is not defined' when installing pyscf

### ISSUE THREAD

**Issue by ccullip** [pyscf/pyscf#300]
I'm attempting to install pyscf on Windows using `pip install pyscf`. However I keep getting this error: 
```  Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\CH\AppData\Local\Temp\pip-install-9rhdyw91\pyscf\setup.py", line 199, in <module>
        for x in blas_libraries]
      File "C:\Users\CH\AppData\Local\Temp\pip-install-9rhdyw91\pyscf\setup.py", line 199, in <listcomp>
        for x in blas_libraries]
      File "C:\Users\CH\AppData\Local\Temp\pip-install-9rhdyw91\pyscf\setup.py", line 140, in search_lib_path
        paths = os.environ.get(LD_LIBRARY_PATH, '').split(os.pathsep)
    NameError: name 'LD_LIBRARY_PATH' is not defined 
```

I tried setting both User and System variables for `LD_LIBRARY_PATH` to the directory where my `mkl_rt.dll` file is, although maybe this is not correct.
I was going to install using conda, but there aren't any packages available for Windows. Is it even possible to install pyscf in windows using pip? How would I go about fixing this? 

Python version: 3.6.8

**Comment by gkc1000** [comment]
Note, Windows is not an officially supported platform. However, Windows 10
has the Windows subsystem for Linux (WSL). PySCF and Anaconda can be
installed under that and should work, although file operations will be
slow. If you want a more performant PySCF you should think about using
Linux under a VM.

**Comment by sunqm** [comment]
In the relatively new pyscf releases, this runtime LD_LIBRARY_PATH should not be a problem anymore
