### ISSUE TITLE
ao to mo integral translation

### ISSUE THREAD

**Issue by rtransformation** [pyscf/pyscf#302]
I use the following methods to translate the ao two-electron integral to mo's

I_mo = np.einsum('pQRS, pP -> PQRS',
            np.einsum('pqRS, qQ -> pQRS',
            np.einsum('pqrS, rR -> pqRS',
            np.einsum('pqrs, sS -> pqrS', I, C), C), C), C)

where I is the spacial ao two-electron integrals got from mol.intor("int2e")
but the result seems inconsistent with the built-in function ao2mo's results

I_mo = ao2mo.restore(1, I, nmo).

where nmo is the dimension

where I'm wrong?

**Comment by tberkel** [comment]
`ao2mo.restore()` doesn't perform the AO to MO transformation, it only converts the given ERI array between different symmetries.  The built-in ao2mo function to perform the AO to MO transformation is `ao2mo.kernel()`, which may call `ao2mo.full()` to transform over all orbitals) or `ao2mo.general()` to transform over some.  Your test will pass if you compare with:
`I_mo_2 = ao2mo.kernel(I, C).reshape(nmo,nmo,nmo,nmo)`
