### ISSUE TITLE
PySCF EDIIS does not implement positivity condition

### ISSUE THREAD

**Issue by gkc1000** [pyscf/pyscf#308]
Hi: 

EDIIS implemented in 
https://github.com/pyscf/pyscf/blob/master/pyscf/scf/diis.py

does not correctly implement the positive mixing condition on the density matrices in the original EDIIS algorithm (ediis_minimize does not have any constraints). I believe Qiming might have told me this at some point, but I'd forgotten!

In principle this can be done by changing the call to scipy.optimize.minimize(...method='BFGS') to one of either SLSQP or COBYLA, although I do not know how they perform.

It would also be interesting to implement EDIIS allowing for fractional occupations in DFT (extended KS model) as suggested in the original EDIIS paper, which guarantees convergence see:

https://aip.scitation.org/doi/pdf/10.1063/1.1470195?class=pdf

**Comment by sunqm** [comment]
The implementation is not a direct linear parameterization. The positive definition condition is ensured by the function https://github.com/pyscf/pyscf/blob/master/pyscf/scf/diis.py#L118 . This trick follows Yang's work JCP, 132, 054109
