### ISSUE TITLE
FCI with periodic boundary condition?

### ISSUE THREAD

**Issue by yuanliu1** [pyscf/pyscf#315]
Hi all, I'm wondering if there are any way to do FCI for periodic boundary conditions with Pyscf?

**Comment by tberkel** [comment]
Yes, any post-HF method implemented in molecular PySCF can be used with
periodic boundary conditions, however only some have support for Brillouin
zone sampling.  In other words, you can always do Gamma-point calculations,
with a cell or supercell of your choosing.  An example showing how to
combine a periodic cell + HF with post-HF methods is here:
https://github.com/pyscf/pyscf/blob/master/examples/pbc/12-gamma_point_post_hf.py

**Comment by yuanliu1** [comment]
Thanks, Tim. I meant FCI with k-point sampling. Is it doable with pyscf?

**Comment by tberkel** [comment]
No, FCI with k-point symmetry is not implemented, but would be a welcome
contribution.

**Comment by sanshar** [comment]
Such calculations can be performed using Dice (it can do FCI calculations
with k-point symmetry). The code is currently not mature enough to put on
pyscf (that will happen in the coming month), but if you want to use it now
we can talk offline as to how to proceed.

Sandeep.

**Comment by bogdanoff** [comment]
> Yes, any post-HF method implemented in molecular PySCF can be used with periodic boundary conditions, however only some have support for Brillouin zone sampling. In other words, you can always do Gamma-point calculations, with a cell or supercell of your choosing.
I wonder if such Gamma-point calculations be extended to cyclic cluster model (https://doi.org/10.1002/jcc.23550)?

**Comment by tberkel** [comment]
With a quick skim, I don't exactly follow the technical details of the cyclic cluster model.  I would venture that it is not dissimilar from the use of a Coulomb interaction whose range is truncated to the Wigner-Seitz cell, as proposed for the exchange energy specifically by Sundararaman and Arias [here](https://journals.aps.org/prb/abstract/10.1103/PhysRevB.87.165122), and available in PySCF using the `exxdiv` keyword.  Beyond this, the integrals required for the CCM could almost surely be obtained from PySCF using various PBC tools and integral access functions; this is beyond the original question and so for now I am closing the issue.
