### ISSUE TITLE
asking for the code for finite temperature coupled cluster calculation

### ISSUE THREAD

**Issue by bsonghao** [pyscf/pyscf#316]
Hello,

    I am interested in the paper for  cc method at finite temperature
published on JCTC by your group. I wonder did that feature is included
at the PyScf package? 

Best regards

Songhao

**Comment by gkc1000** [comment]
Hi Songhao,
The code is still in a personal development branch because it is undergoing many changes. It will be pushed to the main branch later, maybe in 1.7 or 1.8. In the meantime contact Alec or me directly if you need some reference numbers.

**Comment by bsonghao** [comment]
rt

> Hi Songhao,
> The code is still in a personal development branch because it is undergoing many changes. It will be pushed to the main branch later, maybe in 1.7 or 1.8. In the meantime contact Alec or me directly if you need some reference numbers.

Dr Chan

I try to send you an email but I seems that the email address on your website in not correct. I would be appreciate if you could provide me your current email address.


Best regards

Songhao
