### ISSUE TITLE
bug in eval_ao() with Cartesian basis?

### ISSUE THREAD

**Issue by jhrmnn** [pyscf/pyscf#318]
I'm implementing evaluation of Cartesian GTOs in Pytorch, and using Pyscf's `eval_ao()` to check the correctness. I'm using `bas_ctr_coeff()` to get the normalized contraction coefficients, and from sunqm/libcint#22 I know that I need to multiply the `l > 1` shells with the diagonal of the overlap matrix. The diagonal has different entries for different angular momenta (e.g. `xx` vs `xy`) as it should. But I noticed that to get a match with `eval_ao()`, I need to devide the overlaps by the angular norms `Na = sqrt((2*lx-1)!!(2*ly-1)!!(2*lz-1)!!)`. This then makes the diagonal of the overlap matrix constant within a shell. But that means that the normalization is constant within a shell, but it shouldn't—different angular momenta should have different normalizations (differing precisely by `Na`). Is it possible that there is a bug in `eval_ao()` with Cartesian basis, in that it doesn't take the different normalizations of angular momenta into account?

**Comment by sunqm** [comment]
The cartesian basis in pyscf is not normalized to 1. To make eval_ao consistent with the convention in analytical integrals, the normalization coefficients Na was not applied.
```
import numpy as np
from pyscf import gto, dft
mol = gto.M(atom='H 0 0 0; H 0 0 1', basis='ccpvtz', cart=True)
grids = dft.gen_grid.Grids(mol).build()
ao = mol.eval_gto('GTOval', grids.coords)
s = np.einsum('pi,p,pj->ij', ao, grids.weights, ao)
print(abs(s - mol.intor('int1e_ovlp')).max())
```

**Comment by jhrmnn** [comment]
I see. Thanks for a quick reply!
