### ISSUE TITLE
pack_tril function supports dtype of int?

### ISSUE THREAD

**Issue by zhcui** [pyscf/pyscf#322]
Hi all,

Currently the `lib.pack_tril` function works only for double and complex, and the doc uses int array as an example, that will cause a core dump.

In my opinion, we should check/support the dtype for such case or change the example in the doc.

Best,
Zhihao

**Comment by gkc1000** [comment]
please modify the doc

**Comment by sunqm** [comment]
General datatype can be supported by these helper functions. I can fix the issue soon.

**Comment by gkc1000** [comment]
ok good will assign to you!
