### ISSUE TITLE
KeyError when trying to use PBE in an xc string?

### ISSUE THREAD

**Issue by stur86** [pyscf/pyscf#324]
I'm trying to do some test calculations with DFT. I manage to use PBE functionals in this way:

```
mf = dft.RKS(mol)
mf.xc = 'PBE'
mf.kernel()
```

but this fails:

```
mf = dft.RKS(mol)
mf.xc = '.5*PBE+.5*LDA'
mf.kernel()
```

and gives a `KeyError` saying PBE isn't found. Why is this happening? Shouldn't this be allowed, or is there some reason why it's barred?

**Comment by tberkel** [comment]
The `xc` attribute allows a few different styles of input.  For common XC functionals, the single string, such as `PBE`, specifies to use PBE exchange *and* PBE correlation.  Alternatively, a comma is used for custom XC functionals, e.g. `mf.xc = 'B88,LYP'` (B88 exchange and LYP correlation), which would be the same as `mf.xc = 'BLYP'`.  You can also customize the fraction of any exchange or correlation functional (as in your example), but naturally you will need to specify both an exchange and a correlation functional.  In other words, a comma will appear somewhere; without a comma, PySCF expects the `xc` string to be a common pre-coded choice.  

More documentation is available here:
https://sunqm.github.io/pyscf/dft.html#customizing-xc-functional
or in the PySCF tutorial:
https://github.com/nmardirossian/PySCF_Tutorial/blob/master/dev_guide.ipynb

**Comment by stur86** [comment]
Oh, okay, thanks! I thought without the comma it just interpreted it as same for both exchange and correlation.
