### ISSUE TITLE
Weight of k-points generated by cell.make_kpts()

### ISSUE THREAD

**Issue by yuanliu1** [pyscf/pyscf#325]
Hi, Are the k-points generated by `cell.make_kpts()` equally weighted? If not, is there a function to get their weights? Thanks.

**Comment by gkc1000** [comment]
Yes, they are equally weighted.

**Comment by tberkel** [comment]
Indeed, at the moment there is no support for sampling from the irreducible
Brillouin zone (to my knowledge).
