### ISSUE TITLE
printing RCISD wavefunction

### ISSUE THREAD

**Issue by mariomotta** [pyscf/pyscf#327]
Hello,
After running a RCISD calculation, it is possible to extract the RCISD amplitudes 
by the command cisdvec_to_amplitudes. How can one find out which electron 
configurations (i.e. string of occupied spin-up and spin-down orbitals) corresponds 
to the various amplitudes output by cisdvec_to_amplitudes?

In other words, how can one write the RCISD wavefunction in the form
n1 n2 ... nA    n1 n2 ... nB    x
where n1 ... nA, n1 ... nB are the occupied up, down orbitals
and x the amplitude of the corresponding configuration?

thanks,
Mario

**Comment by tberkel** [comment]
Hi Mario,

Someone will correct me if I'm wrong, but the three CI amplitudes returned by the function you point out are c0, c1, c2, which have shape (1,), (nocc,nvir), and (nocc,nocc,nvir,nvir).  Since it's a restricted implementation, the excitation indices presumably correspond to the spin-adapted excitations i.e. 
`|\Phi_i^a\rangle = E_{ia}|\Phi_0\rangle = 2^{-1/2}(a_{a,up}^\dagger a_{i,up} + a_{a,down}^\dagger a_{a,down})|\Phi_0\rangle`

So the wavefunction in the form you request (e.g. for a 10-elec system, 5 up, 5 down) would be
```
0 1 2 3 4 0 1 2 3 4 c0
...
0 1 2 4 7 0 1 2 4 7 c[3,2] # a = 2 is orbital nocc+2 = 7
...
0 2 4 8 13 0 2 4 8 13 c[1,3,3,8] # (a,b) = (3,8) is orbitals (8,13)
```

The one part I wasn't careful about here is the sign of the amplitudes.  I would also make sure to check that the norm is what you expect, using the CISD `dot()` function.

Alternatively, have you looked at the `to_fcivec()` function [here](https://github.com/pyscf/pyscf/blob/master/pyscf/ci/cisd.py#L246)?

**Comment by yangcal** [comment]
Hi Mario,

Based on the implementation, I think the CI amplitudes does not contain the pairity of the wfn in occupation basis. Someone please correct me if I'm wrong.

As Tim said, you can sue the to_fcivec() function to get the coefficients in FCI representation. For example, if we have 4 electrons with 2 up and 2 down,  we have 6 configs for each spin and the to_fcivec() functions returns a 6*6 normalized matrix, the two dimensions corresponds to the config for spin up and spin down respectively.  In the case of RCISD, only the diagonal elements are non-zero.

Also, pyscf.fci.cistring provides an easy way to retrieve the occupation basis.
`from pyscf.fci.cistring import make_strings`
`norb = 4`
`neleca = 2`
`print([bin(x) for x in make_strings(range(norb), neleca)])`
You'll get the occupation basis in binary format(1 for occupied and 0 for virtual, the rightest one is the lowest in energy). The order is consistent with the FCI coefficient matrix.

Hope it helps

**Comment by gkc1000** [comment]
We should put a note to add to the docstring the precise behaviour of the
function

**Comment by sunqm** [comment]
> Hi Mario,
> 
> Based on the implementation, I think the CI amplitudes does not contain the pairity of the wfn in occupation basis. Someone please correct me if I'm wrong.
> 
> As Tim said, you can sue the to_fcivec() function to get the coefficients in FCI representation. For example, if we have 4 electrons with 2 up and 2 down, we have 6 configs for each spin and the to_fcivec() functions returns a 6*6 normalized matrix, the two dimensions corresponds to the config for spin up and spin down respectively. In the case of RCISD, only the diagonal elements are non-zero.
> 
> Also, pyscf.fci.cistring provides an easy way to retrieve the occupation basis.
> `from pyscf.fci.cistring import make_strings`
> `norb = 4`
> `neleca = 2`
> `print([bin(x) for x in make_strings(range(norb), neleca)])`
> You'll get the occupation basis in binary format(1 for occupied and 0 for virtual, the rightest one is the lowest in energy). The order is consistent with the FCI coefficient matrix.
> 
> Hope it helps

A relevant function that transfers CISD amplitudes to string-based FCI coefficients https://github.com/pyscf/pyscf/blob/master/pyscf/ci/cisd.py#L246
Sign difference between determinants and diagram amplitudes are handled in this function

**Comment by mariomotta** [comment]
thanks everyone for the helpful advice,
I have been able to write the CISD wavefunction in CI representation.

best,
Mario

**Comment by tberkel** [comment]
Great Mario.  For posterity, could you tell us which solution you used and
then we can close the issue?  Thanks.

**Comment by mariomotta** [comment]
hi Tim,

sure, here is a complete example

import numpy         as np
from   pyscf         import gto,ao2mo,scf,cc,mp,mcscf
from   pyscf.scf     import _vhf
from   pyscf         import gto, scf, ci
from   scipy         import linalg as LA
from   pyscf.ci.cisd import  *
from   pyscf.fci     import cistring

def excitation_str(strng):
 strng_r = bin(strng)[-1:1:-1]
 ns      = len(strng_r)
 return "".join(" %3d" % (i+1) for (x,i) in zip(strng_r,range(ns)) if x ==
"1")

def string(xa,xb):
 ss  = ""
 for ia in xa: ss+=(" "+str(ia))
 ss += "  "
 for ib in xb: ss+=(" "+str(ib))
 ss += "  "
 return ss

mol    = gto.M(
 atom  = [['O', ( 0., 0.    , 0.   )],
          ['H', ( 0., -0.957, 0.987)],
          ['H', ( 0.,  0.957, 0.987)]],
 basis = 'sto-3g')
norb   = mol.nao_nr()
neleca = mol.nelectron//2
nelecb = neleca

mf        = scf.RHF(mol).run()
myci      = ci.CISD(mf)
ecisd,ci0 = myci.kernel()
cisdWFN   = to_fcivec(ci0,norb,(neleca,neleca))
na,nb     = cisdWFN.shape
c0,c1,c2  = cisdvec_to_amplitudes(ci0,myci.nmo,myci.nocc)
from pyscf.ci.cisd import  *

for ia in range(na):
 for ib in range(nb):
  if(np.abs(cisdWFN[ia,ib])>1e-4):
   xa = excitation_str(cistring.addr2str(norb,neleca,ia))
   xb = excitation_str(cistring.addr2str(norb,nelecb,ib))
   print(string(xa,xb)+' '+str(cisdWFN[ia,ib]))
