### ISSUE TITLE
Solvent Effect

### ISSUE THREAD

**Issue by lck982** [pyscf/pyscf#342]
Can PySCF include solvent effect? I saw it in pyscf/pyscf/solvent/, is this ready for real applications?

**Comment by sunqm** [comment]
Solvent module is mostly ready to use in pyscf-1.6.

It supports the frozen solvent and self-consistent solvent for ground state of SCF methods and MCSCF methods, and postHF methods with frozen solvent. Self-consistent solvent is available for post-HF but not optimized. You may find that it is hard to convergence self-consistent solvent for CCSD. TDDFT can be used with the solvent from ground state calculations. Self-consistent solvent for TDDFT was not implemented.

The memory usage was not optimized in current version. Depending on the physical memory on your machine, the problem size may be limited to ~1000 atoms which consumes ~ 20GB physical memory.

More examples can be found https://github.com/pyscf/pyscf/tree/master/examples/solvent

The default solvent is water. You may need to input dielectric constants of the solvent. Some can be found at https://github.com/pyscf/pyscf/blob/master/pyscf/solvent/ddcosmo.py#L44
