### ISSUE TITLE
Geometry optimization with symmetry turned on

### ISSUE THREAD

**Issue by nsblunt** [pyscf/pyscf#344]
Hi,

I've been using PySCF and geomeTRIC to do geometry optimization. My initial attempts at this didn't work, with the optimizer usually increasing the energy every iteration. The problem seems to be when symmetry is set True. i.e., taking the water trimer/CCSD case from geometric/examples:

from pyscf import gto, scf, cc
from pyscf.geomopt.geometric_solver import optimize

mol = gto.Mole()

mol.build(
atom = [
['O',(  0.8559100000,   -1.3823600000,    0.3174600000)],
['H',(  1.6752400000,   -1.8477400000,    0.4858000000)],
['H',(  1.1176100000,   -0.4684300000,    0.2057500000)],
['O',( -1.0986300000,   -0.8583700000,    2.1731900000)],
['H',( -0.4031000000,   -1.1460800000,    1.5818400000)],
['H',( -1.0851100000,    0.0968300000,    2.1128200000)],
['O',(  1.8644800000,    1.2201800000,    1.3331100000)],
['H',(  2.0104700000,    1.8829200000,    0.6580600000)],
['H',(  2.6420500000,    0.6632600000,    1.2947900000)], ],
basis = {'O': 'cc-pvdz', 'H': 'cc-pvdz'},
symmetry = True,
)

mycc = cc.CCSD(scf.RHF(mol))
mol1 = optimize(mycc)

This just increases the energy almost every iteration. If I remove the symmetry line then it works. If this is hard to fix, perhaps it could just throw an error for now?

Best,
Nick

**Comment by sunqm** [comment]
Bug fixed in commit 5de2156
