### ISSUE TITLE
FCIDUMP Files for PBC Systems issue

### ISSUE THREAD

**Issue by ramadugu** [pyscf/pyscf#346]
I am generating the fcidump files using the scf object (tools.fcidump.from_scf), the energy converged scf energy from psycf and Hands-QMC aren't matching for systems with PBC whereas molecular systems match perfectly. Not sure if the fcidump and 2e integral generation code has any issues, but thought I would mention.

For example in the case of diamond system:

PySCF SCF = -44.xx
HANDE-QMC SCF = -37.xx

**Comment by tberkel** [comment]
This probably has to do with the treatment of the G=0 divergence in the ERIs.  At the SCF level, the "best" treatment of this divergence is one where the Coulomb and exchange contributions are not calculated from a consistent set of ERIs.  This is because the G=0 divergence of the Coulomb term is canceled by the divergent electron-nuclear term, so it is neglected entirely.   However, the G=0 divergence of the exchange term is an integrable divergence which can be handled in various ways to more quickly approach the thermodynamic limit.  This choice is controlled by the `exxdiv` kwarg.

You should probably see agreement in the SCF if you turn off any special handling of the exchange divergence: `mf = scf.KRHF(cell, kpts, exxdiv=None)`.  Note that the PySCF default is `exxdiv='ewald'`.

**Comment by ramadugu** [comment]
If I used:
mf = scf.KRHF(cell, kpts, exxdiv=None)
and try to generate the fcidump file with the command:
tools.fcidump.from_scf(mf, 'diamondscfkp111exxdivnone.fcidump',tol=1e-15, float_format=' %.16g')

I get the following error:

Traceback (most recent call last):
  File "diamond_ase.py", line 49, in <module>
    tools.fcidump.from_scf(mf, 'diamondscfkp111exxdivnone.fcidump',tol=1e-15, float_format=' %.16g')
  File "/Users/sramadug/pyscf-1.6.1/pyscf/tools/fcidump.py", line 136, in from_scf
    h1e = reduce(numpy.dot, (mo_coeff.T, mf.get_hcore(), mo_coeff))
AttributeError: 'list' object has no attribute 'T'

But now, the SCF energy from PySCF (as captured in LOG file) matches the SCF energy from Hande-QMC (although the fcidump I used is older file generated with exxdiv='ewald') since I cannot get an FCIDUMP file to use with HANDE-QMC code.

So, the question:

Can I use the fcidump that is generated with exxdiv='ewald' for running FCI Quantum Monte Carlo with Hande-QMC? and use the SCF with exxdiv='None' to compare the SCF energies from the two codes?

**Comment by tberkel** [comment]
Oh sorry, it's probably getting hung up on k-points.  Use `scf.RHF(cell,
exxdiv=None)` instead, which I assume is the class you used before.

But also yes: for total energies, the best thing to do is combine the SCF
energy from an improved treatment of `exxdiv`, such as `ewald` or
`vcut_sph`, with the correlation energy calculated separately (at present,
the ERIs in the FCIDUMP should be the same, or very similar, whichever
`exxdiv` you choose for the SCF).

**Comment by ramadugu** [comment]
Sorry, but I have another issue if I submit the way you suggested.
mf=scf.RHF(cell, exxdiv='None')

Traceback (most recent call last):
  File "diamond_ase.py", line 49, in <module>
    tools.fcidump.from_scf(mf, 'diamondscfexxdivnone.fcidump',tol=1e-15, float_format=' %.16g')
  File "/Users/sramadug/pyscf-1.6.1/pyscf/tools/fcidump.py", line 138, in from_scf
    eri = ao2mo.full(mol, mo_coeff)
NameError: name 'mol' is not defined

**Comment by tberkel** [comment]
L138 is a bug that I'll fix, but should be unrelated to your question.
It's hard to give exact guidance without seeing your input script, but if
you take whichever script successfully produced an FCIDUMP for diamond, but
insert `exxdiv=None` when you instantiate the SCF class, then it *should*
work fine.

**Comment by ramadugu** [comment]
The input file. 
-----
"""
Take ASE Diamond structure, input into PySCF and run
"""
from ase.lattice import bulk
from pyscf import lib, tools
import numpy as np
from array import array
import pyscf.pbc.gto as pbcgto
from pyscf.pbc import gto, scf
import pyscf.pbc.dft as pbcdft
from pyscf.pbc.tools import pyscf_ase
import pyscf.lib
lib.num_threads(28)

import ase
import ase.lattice
from ase.lattice.cubic import Diamond


ase_atom=Diamond(symbol='C', latticeconstant=3.5668)
print(ase_atom.get_volume())

cell = pbcgto.Cell()
cell.verbose = 5
cell.output='diamondASEexxdivnone.log'
cell.atom=pyscf_ase.ase_atoms_to_pyscf(ase_atom)
cell.a=ase_atom.cell
cell.basis = 'gth-dzvp'
cell.pseudo = 'gth-pade'
cell.build()
mf = scf.RHF(cell, exxdiv='None')
mf.chkfile='diamond.chk'
mf.kernel()

tools.fcidump.from_scf(mf, 'diamondscfexxdivnone.fcidump',tol=1e-15, float_format=' %.16g')
-----

> if you take whichever script successfully produced an FCIDUMP for diamond, but
> insert `exxdiv=None` when you instantiate the SCF class, then it *should* work fine.

Unfortunately, this is not the case. I am using PySCF version 1.6.1. Please let me know what other details would you diagnose the problem. I will provide them in this ticket.

**Comment by tberkel** [comment]
Remove the single quotes surrounding None.  It must be Python's `None`,
i.e. the `NoneType`.  Then it works.  It's for a rather convoluted reason
that an invalid input for `exxdiv` raises the error you see, which I'll fix
soon.

**Comment by ramadugu** [comment]
thank you very much for correcting my silly mistake. I was able to generate the fcidump files and now the scf energy from PySCF and Hande-QMC match.
