### ISSUE TITLE
UMP2 -- cannot reshape array of size (nocca,nvira,nocca,nvira) into shape (nvira,nocca,nvira)

### ISSUE THREAD

**Issue by mariomotta** [pyscf/pyscf#347]
Greetings, 

I am trying to run unrestricted MP2 calculations, with 1-fold symmetry
(a script is below) but run in the following issue (basically a tensor of
shape (o,v,o,v) is reshaped into (v,o,v).

File "/pyscf_dev/pyscf/mp/ump2.py", line 67, in kernel
    eris_ovov = eris_ovov.reshape(nvira,nocca,nvira).transpose(1,0,2)
ValueError: cannot reshape array of size 144 into shape (6,2,6)

Can you please help me understanding the origin of this issue?

Thanks,
Mario

---------- 

import numpy as np
from   pyscf import gto,scf,mp
from   scipy import linalg as LA

mol = gto.M()
mol.nelectron     = 4
mol.spin          = 0
mol.incore_anyway = True

nb = 8
H0 = 0
S1 = np.eye(nb)
H1 = np.random.random((nb,nb))
L  = np.random.random((nb,nb,nb))
H1 = (H1+H1.T)/2.0
eri = np.einsum('prg,sqg->prqs',L,L)*0.01

mf            = scf.UHF(mol)
mf.energy_nuc = lambda *args: H0
mf.get_hcore  = lambda *args: H1
mf.get_ovlp   = lambda *args: S1
mf._eri       = eri
def get_jk_loc(mol=None,dm=None,hermi=None):
 vj = np.zeros((2,dm[0].shape[0],dm[0].shape[1]))
 vk = np.zeros((2,dm[0].shape[0],dm[0].shape[1]))
 for js in range(2):
  vj[js,:,:] = np.einsum('pqrs,qp->rs',eri,dm[js])
  vk[js,:,:] = np.einsum('pqrs,qr->ps',eri,dm[js])
 return vj,vk
mf.get_jk = get_jk_loc
E = mf.kernel()

from pyscf.mp import ump2
mu    = ump2.UMP2(mf)
mu.kernel(mu.ao2mo(mf.mo_coeff))
rr    = mu.make_rdm1()

**Comment by gkc1000** [comment]
There should be 4 arguments to reshape, not 3?

**Comment by gkc1000** [comment]
Oh, sorry, the integrals are being handled in a loop over one of the
occupied indices. So the issue must be the 1-fold symmetry.

**Comment by zhcui** [comment]
Hi Mario,

The shape of eris_ovov is (nocc_a*nvir_a, nocc_a,nvir_a). So the indexing: i*nvira:(i+1)*nvira for this object is equivalent as eri[i] for 1-fold symmetry.

We need to hack the function I think.

Best,
Zhihao

**Comment by yangcal** [comment]
Hi Mario,

As Garnet pointed out, the issue is related to the symmetry of the _eri. tensor. [https://github.com/sunqm/pyscf/blob/6ba52f91efc4c372028067d89a3410cbf6c4f744/examples/scf/40-customizing_hamiltonian.py#L42](url) pointed out the mf._eri only supports restored 4-fold or 8-fold _eri. If you try the restored 4 or 8 fold eri, UMP2 should run fine. 

If you have a "weird" system though, the _make_eris function needs to be rewritten. 

Best,
Yang

**Comment by tberkel** [comment]
It will be more expensive, but would GHF/GMP2 work?  At least
`_make_eris_incore` looks to support complex orbitals so presumably 1-fold
ERIs are okay?

**Comment by sunqm** [comment]
This bug should be solved in commit 1d54b6940
