### ISSUE TITLE
Error in mpicc

### ISSUE THREAD

**Issue by hungpham2017** [pyscf/pyscf#349]
Hello,

I ran [25-k_points_mpi_ccsd.py](https://github.com/pyscf/pyscf/blob/master/examples/pbc/25-k_points_mpi_ccsd.py)

and got this error message:

>  ecc, t1, t2 = kcc.kernel()
> 
> ******** <class 'pyscf.pbc.mpicc.kccsd_rhf.RCCSD'> ********
> CC2 = 0
> CCSD nocc = 4, nmo = 8
> max_cycle = 50
> direct = 1
> conv_tol = 1e-07
> conv_tol_normt = 1e-05
> diis_space = 6
> diis_start_cycle = 0
> diis_start_energy_diff = 1e+09
> max_memory 4000 MB (current use 381 MB)
> Attempting to use an MPI routine before initializing MPICH
> HDF5: infinite loop closing library
>       L,T_top,P,P,Z,FD,PL,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD,FD

what went wrong?
Thank you very much,
Hung

**Comment by gkc1000** [comment]
How did you run it (what was the command line?)

**Comment by gkc1000** [comment]
Any further news on this?

**Comment by hungpham2017** [comment]
Sorry for the late response.
I just found out that the problem was because of the improper installation of h5py parallel version.
This h5py release in conda-forge worked for me and the error message disappeared:

`conda install -c conda-forge h5py=2.9.0=mpi_mpich_h1032f3f_1001`

I lose the issue at the point and may open it again as soon as another problem pops up.
Thank you for your help

**Comment by hungpham2017** [comment]
I ran the [25-k_points_mpi_ccsd.py](https://github.com/pyscf/pyscf/blob/master/examples/pbc/25-k_points_mpi_ccsd.py) by:

`OMP_NUM_THREADS=4 mpirun -np 4 python 25-k_points_mpi_ccsd.py`

and got this:


> Traceback (most recent call last):
>   File "25-k_points_mpi_ccsd.py", line 53, in <module>
>     ecc, t1, t2 = kcc.kernel()
>   File "/home/gagliard/phamx494/pyscf_dev/pyscf/pbc/cc/kccsd_rhf.py", line 623, in kernel
>     return self.ccsd(t1, t2, eris, mbpt2=mbpt2)
>   File "/home/gagliard/phamx494/pyscf_dev/pyscf/pbc/cc/kccsd_rhf.py", line 646, in ccsd
>     verbose=self.verbose)
>   File "/home/gagliard/phamx494/pyscf_dev/pyscf/cc/ccsd.py", line 69, in kernel
>     t1new, t2new = mycc.update_amps(t1, t2, eris)
>   File "/home/gagliard/phamx494/pyscf_dev/pyscf/pbc/mpicc/kccsd_rhf.py", line 1162, in update_amps
>     return update_amps(self, t1, t2, eris, max_memory)
>   File "/home/gagliard/phamx494/pyscf_dev/pyscf/pbc/mpicc/kccsd_rhf.py", line 328, in update_amps
>     Foo = imdk.cc_Foo(cc,t1,t2,eris)
>   File "/home/gagliard/phamx494/pyscf_dev/pyscf/pbc/mpicc/kintermediates_rhf.py", line 97, in cc_Foo
>     Fki[ki] += einsum('klcd,ilcd->ki',Soovv,unpack_tril(t2,nkpts,ki,kl,kc,kconserv[ki,kc,kl]))
>   File "/home/gagliard/phamx494/pyscf_dev/pyscf/pbc/tools/tril.py", line 44, in unpack_tril
>     indices[:,2][not_tril] = ks[not_tril]
> IndexError: too many indices for array

There was a few bugs for if one uses python 3, for example:

1. [Import get_max_blocksize_from_mem](https://github.com/pyscf/pyscf/blob/master/pyscf/pbc/mpitools/mpi_helper.py#L15) . Should be:
`from .mpi_blksize import get_max_blocksize_from_mem`
2. [List index is a float](https://github.com/pyscf/pyscf/blob/master/pyscf/pbc/mpicc/kccsd_rhf.py#L1025). Should be:
`tril_shape = ((nkpts)*(nkpts+1))//2`

3. [List index is a float](https://github.com/pyscf/pyscf/blob/master/pyscf/pbc/tools/tril.py#L20) . Can be fixed by:
`return (kj*(kj+1))//2 + ki`



`

**Comment by gkc1000** [comment]
Xiao: can you take a look?

**Comment by xwang862** [comment]
Thanks @hungpham2017 for pointing out the issues. All three changes are included in this [pull request](https://github.com/pyscf/pyscf/pull/354).

**Comment by hungpham2017** [comment]
I forgot there is another bug:

The **unique_klist** in line [3036](https://github.com/pyscf/pyscf/blob/master/pyscf/pbc/mpicc/kccsd_rhf.py#L3036) of kccsd_rhf.py is not a list and doesn't have element index.
This can be fixed by converting **unique_klist** in line [3013](https://github.com/pyscf/pyscf/blob/master/pyscf/pbc/mpicc/kccsd_rhf.py#L3013)  to list:
`unique_klist = list(khelper.symm_map.keys())`

However, even if this is fixed, the same error before still appear:

> Traceback (most recent call last):
>   File "25-k_points_mpi_ccsd.py", line 53, in <module>
>     ecc, t1, t2 = kcc.kernel()
>   File "/home/gagliard/phamx494/pyscf_dev/pyscf/pbc/cc/kccsd_rhf.py", line 588, in kernel
>     return self.ccsd(t1, t2, eris, mbpt2=mbpt2)
>   File "/home/gagliard/phamx494/pyscf_dev/pyscf/pbc/cc/kccsd_rhf.py", line 611, in ccsd
>     verbose=self.verbose)
>   File "/home/gagliard/phamx494/pyscf_dev/pyscf/cc/ccsd.py", line 69, in kernel
>     t1new, t2new = mycc.update_amps(t1, t2, eris)
>   File "/home/gagliard/phamx494/pyscf_dev/pyscf/pbc/mpicc/kccsd_rhf.py", line 1162, in update_amps
>     return update_amps(self, t1, t2, eris, max_memory)
>   File "/home/gagliard/phamx494/pyscf_dev/pyscf/pbc/mpicc/kccsd_rhf.py", line 328, in update_amps
>     Foo = imdk.cc_Foo(cc,t1,t2,eris)
>   File "/home/gagliard/phamx494/pyscf_dev/pyscf/pbc/mpicc/kintermediates_rhf.py", line 97, in cc_Foo
>     Fki[ki] += einsum('klcd,ilcd->ki',Soovv,unpack_tril(t2,nkpts,ki,kl,kc,kconserv[ki,kc,kl]))
>   File "/home/gagliard/phamx494/pyscf_dev/pyscf/pbc/tools/tril.py", line 44, in unpack_tril
>     indices[:,2][not_tril] = ks[not_tril]
> IndexError: too many indices for array

As shown in the error message, it is in [tril.py](https://github.com/pyscf/pyscf/blob/master/pyscf/pbc/tools/tril.py)

I guess it needs some understanding about the KCCSD so I don't know how to fix it.
Thanks

**Comment by xwang862** [comment]
The issue should be fixed in pull request [#369](https://github.com/pyscf/pyscf/pull/369). Most of the errors were caused by python3/2 incompatibility (please check the pullreq description for details).

Right now the left IP/EA methods in [25-k_points_mpi_ccsd.py](https://github.com/pyscf/pyscf/blob/master/examples/pbc/25-k_points_mpi_ccsd.py) (`kcc.leaccsd` and `kcc.lipccsd`) still have problems. But if what you need are just `mpicc.KRCCSD` and its `eaccsd` and `ipccsd` methods, the code is good to go.

**Comment by hungpham2017** [comment]
It worked for me now except for kcc.leaccsd and kcc.lipccsd as you mentioned.
For now, I don't need them. Thank you very much for your help.
