### ISSUE TITLE
[Bug] PBC Gaussian density fitting error

### ISSUE THREAD

**Issue by zhutianyu1991** [pyscf/pyscf#351]
Hi,

I tried to run a KUHF calculation with GDF on NiO (script attached in the end) and found the result unreasonable with the newest version of PySCF (1.7.1, dev branch). The Coulomb energy before the first step is already wrong (hugely negative):
```
E1 = (-207.04191083733718-5.041242320816222e-15j)  E_coul = (-59690.45792242636-8.909573202319806e-15j)
init E= -60136.8594748064
```
While running with an older version 1.6a, I got more reasonable initial energy and the final result also looks correct:
```
E1 = (-207.04205342072396-4.96541211509103e-15j)  E_coul = (48.666098213393646+1.033424591200558e-18j)
init E= -397.73559675008
...
converged SCF energy = -368.770742845341
```
I also tried to read in the GDF integrals generated from PySCF 1.6a, and run KUHF using PySCF 1.7.1. The result is correct and consistent with PySCF 1.6a. So the problem should happen at the GDF part (?), where PySCF 1.6a drops more auxiliary basis functions than PySCF 1.7.1 due to linear dependency.

Is this error coming from the change of default threshold in GDF or the change of other pieces of code?

Thank you!
Tianyu

```
from pyscf.pbc import df, scf, gto
from pyscf.pbc.lib import chkfile
import numpy

cell         = gto.Cell()
cell.atom    = '''
Ni     0.000   0.000   0.000
Ni     4.170   4.170   4.170
O      2.085   2.085   2.085
O      6.255   6.255   6.255
'''
cell.basis   = 'gth-dzvp-molopt-sr'
cell.pseudo  = 'gth-pade'
cell.a       = [[4.170,2.085,2.085],[2.085,4.170,2.085],[2.085,2.085,4.170]]
cell.spin    = 0
cell.verbose = 5
cell.max_memory = 50000
cell.build()

gdf = df.GDF(cell, kpts=cell.make_kpts([3,3,3]))
gdf._cderi_to_save = 'gdf_ints_333.h5'
gdf.build()

kmf = scf.KUHF(cell, kpts = cell.make_kpts([3,3,3])).density_fit()
kmf.with_df = gdf
kmf.with_df._cderi = 'gdf_ints_333.h5'
dm = kmf.get_init_guess()

aoind = cell.aoslice_by_atom()
dm[0,:,aoind[0][2]:aoind[0][3], aoind[0][2]:aoind[0][3]] = 0
dm[0,:,aoind[1][2]:aoind[1][3], aoind[1][2]:aoind[1][3]] = 2 * dm[0,:,aoind[1][2]:aoind[1][3], aoind[1][2]:aoind[1][3]]

dm[1,:,aoind[0][2]:aoind[0][3], aoind[0][2]:aoind[0][3]] = dm[1,:,aoind[0][2]:aoind[0][3], aoind[0][2]:aoind[0][3]] * 2
dm[1,:,aoind[1][2]:aoind[1][3], aoind[1][2]:aoind[1][3]] = 0

kmf.chkfile = 'afm_gdf_333.chk'
kmf.kernel(dm)
print('S^2 = %s, 2S+1 = %s' % kmf.spin_square())
```

**Comment by sunqm** [comment]
I cannot reproduce this error as of the commit 702d304053cfdedca5a5859a01d895b19477da29 in dev branch. The initial Coulomb energy is 48.650381399 .

**Comment by gkc1000** [comment]
@zhutianyu1991 Did updating to the latest commit fix this?

**Comment by zhutianyu1991** [comment]
I still got the same error even using the commit @sunqm mentioned. Maybe the error is related to my Python packages or MKL?

**Comment by fishjojo** [comment]
I can reproduce Tianyu's error. The problem comes from the code that takes into account the k-point symmetry of the Coulomb metric integral, specifically:
`        # The k-point k' which has (k - k') * a = 2n pi. Metric integrals have the
        # symmetry S = S
        uniq_kptji_ids = kconserve_indices(-kpt)
        log.debug1("Symmetry pattern (k - %s)*a= 2n pi", kpt)
        log.debug1("    make_kpt for uniq_kptji_ids %s", uniq_kptji_ids)
        for uniq_kptji_id in uniq_kptji_ids:
            if not done[uniq_kptji_id]:
                make_kpt(uniq_kptji_id, cholesky_j2c)
        done[uniq_kptji_ids] = True

        # The k-point k' which has (k + k') * a = 2n pi. Metric integrals have the
        # symmetry S = S*
        uniq_kptji_ids = kconserve_indices(kpt)
        log.debug1("Symmetry pattern (k + %s)*a= 2n pi", kpt)
        log.debug1("    make_kpt for %s", uniq_kptji_ids)
        cholesky_j2c = conj_j2c(cholesky_j2c)
        for uniq_kptji_id in uniq_kptji_ids:
            if not done[uniq_kptji_id]:
                make_kpt(uniq_kptji_id, cholesky_j2c)
        done[uniq_kptji_ids] = True`
in pbc/df/df.py.
If I turn off the above code and compute Coulomb metric integral for each k point, the I can get the correct answer. @sunqm may have an idea what the problem is.

Xing

**Comment by yangcal** [comment]
Hi all,

After some test on MnO, I found that the source of the errors is from the reciprocal space grid(mydf.mesh) in computing J2C integral. The real space summation part preserves the both two types of periodic symmetry quite well but the reciprocal part breaks it. Once I increased the mesh, the periodic symmetry in J2c are well preserved(norm difference becomes 1e-16 while default mesh gives 1e-6 ) and gives correct coulomb energy. 

I think increasing the default mesh will fix this but since it has some system/basis dependence, adding some warning when periodic symmetry is broken might be useful to the users. @sunqm

**Comment by sunqm** [comment]
@yangcal could you test the system again using the latest commit? I suspect the error in j2c is caused by the inconsistency between the parity symmetry of mesh and parity symmetry in k-points. This problem is handled in the latest commit

**Comment by yangcal** [comment]
Hi Qiming,

The latest commit did fix the issue. MnO calculations now does not crash. However, when I try to increase the mesh from the current default [11,11,11] to [25,25,25], I see the SCF energy differs by almost 1 Hartree. Seems the integrals are not converged with the default mesh.

**Comment by yangcal** [comment]
> @yangcal could you test the system again using the latest commit? I suspect the error in j2c is caused by the inconsistency between the parity symmetry of mesh and parity symmetry in k-points. This problem is handled in the latest commit

**Comment by yangcal** [comment]
@sunqm  Can you explain the error measure in aft.estimate_eta_for_ke_cutoff and aft.estimate_ke_cutoff_for_eta? The non-convergence is mostly from the j2c integrals, but these functions does not seem to take any information on the auxiliary basis set.
