### ISSUE TITLE
UCCSD(T) potentai energy surface for Cr2

### ISSUE THREAD

**Issue by CyrusUmrigar** [pyscf/pyscf#363]
I am trying to calculate the potential energy surface of Cr_2 using
UCCSD(T) using the attached script.  However, I get a very discontinuous surface for UHF, UCCSD and UCCSD(T).  What am I doing wrong?
[Cr2.py.gz](https://github.com/pyscf/pyscf/files/3291996/Cr2.py.gz)

Thanks.

**Comment by gkc1000** [comment]
Fixed offline, closing issue.
