### ISSUE TITLE
Using Pyscf with Gen1Int

### ISSUE THREAD

**Issue by jhrmnn** [pyscf/pyscf#364]
Does anyone have experience with adding one-electron intagrals from [Gen1Int](https://gitlab.com/bingao/gen1int) to Pyscf? I want to do SCF calculations in an external electric field and Gen1Int is able to calculate the required `H_core` integrals (unlike Libcint, AFAIK). Before I'll try to figure out things myself (how to best share the same basis between Pyscf and Gen1Int, etc.), I'm wondering if perhaps someone already went through the effort.

**Comment by iliya-s** [comment]
Hi,

You can do any calculation in pyscf with a given set of integrals. Here's a code example in the documentation doing an scf calculation with the Hubbard model:
```
#!/usr/bin/env python
#
# Author: Qiming Sun <osirpt.sun@gmail.com>
#

import numpy
from pyscf import gto, scf, ao2mo

'''
Customizing Hamiltonian for SCF module.

Three steps to define Hamiltonian for SCF:
1. Specify the number of electrons. (Note mole object must be "built" before doing this step)
2. Overwrite three attributes of scf object
    .get_hcore
    .get_ovlp
    ._eri
3. Specify initial guess (to overwrite the default atomic density initial guess)

Note you will see warning message on the screen:

        Overwritten attributes  get_ovlp get_hcore  of <class 'pyscf.scf.hf.RHF'>

'''

mol = gto.M()
n = 10
mol.nelectron = n

mf = scf.RHF(mol)
h1 = numpy.zeros((n,n))
for i in range(n-1):
    h1[i,i+1] = h1[i+1,i] = -1.0
h1[n-1,0] = h1[0,n-1] = -1.0  # PBC
eri = numpy.zeros((n,n,n,n))
for i in range(n):
    eri[i,i,i,i] = 4.0

mf.get_hcore = lambda *args: h1
mf.get_ovlp = lambda *args: numpy.eye(n)
# ao2mo.restore(8, eri, n) to get 8-fold permutation symmetry of the integrals
# ._eri only supports the two-electron integrals in 4-fold or 8-fold symmetry.
mf._eri = ao2mo.restore(8, eri, n)

mf.kernel()

# If you need to run post-HF calculations based on the customized Hamiltonian,
# setting incore_anyway=True to ensure the customized Hamiltonian (the _eri
# attribute) to be used.  Without this parameter, some post-HF method
# (particularly in the MO integral transformation) may ignore the customized
# Hamiltonian if memory is not enough.
mol.incore_anyway = True
```
For your case you could probably get away with just overriding get_hcore, but getting all the integrals from one source would probably be better practice. A few more examples can be seen in the documentation in section 24.2 of the docs, "Customizing Hamiltonian".

Hope that helps.

Iliya
