### ISSUE TITLE
Brillouin zone sampling not converge w.r.t. # of k-points?

### ISSUE THREAD

**Issue by yuanliu1** [pyscf/pyscf#365]
Hi, I am having a strange problem in terms of converge a one-dimensional periodic system with respect to k-point sampling. As I increase the number of sampling k-points, the SCF energy doesn't seems to show convergence at all even up to 30 k-points. This is a 1D hydrogen chain with a 10-atom supercell and a H-H distance of 0.75 Angstrom. My input (for 3 k-points, other number of kpoints just change `kpts = cell.make_kpts([1,1,3])` line) and the final SCF energy vs. # of k-points are shown below. Results at other longer bond lengths also have similar issues. Are there anything obviously wrong in my input? Thanks.

<img width="784" alt="image" src="https://user-images.githubusercontent.com/18542998/59567693-db1d1880-903e-11e9-8fa6-8fcbce39d909.png">

```
#!/user/bin/env python
import numpy
from pyscf.pbc import gto, scf
cell = gto.M(
    atom = '''H .0	.0  0.00
              H .0	.0  0.75
              H .0	.0  1.50
              H .0	.0  2.25
              H .0	.0  3.00
              H .0	.0  3.75
              H .0	.0  4.50
              H .0	.0  5.25
              H .0	.0  6.00
              H .0	.0  6.75''',
    basis = 'sto-6g',
    a = [[20.0,0.,0.],[0.,20.0,0.],[0.,0.,7.50]],
    verbose=5)
kpts = cell.make_kpts([1,1,3])
kmf = scf.KUHF(cell, exxdiv=None)
kmf.kpts = kpts
#kmf = kmf.mix_density_fit() # only use it for all electron calculation
kmf = kmf.density_fit() # only use it for all electron calculation
ehf = kmf.kernel()
```

**Comment by zhcui** [comment]
Hi,

HF exchange energy is relatively hard to converge w.r.t. kpts. You can try `exxdiv='ewald'` to have better convergence w.r.t. kpts. Or you can try dft to check if the issue exists.

**Comment by yuanliu1** [comment]
Thanks. Indeed that is the problem. 'ewald' option is working well.

**Comment by tberkel** [comment]
The option ‘vcut_sph’ should provide exponential convergence (whereas
‘ewald’ is only power-law). However, ‘vcut_sph’ only works with plane-wave
based density fitting (FFTDF) which probably requires a large kinetic
energy cutoff if you are not using a pseudopotential.

**Comment by zhcui** [comment]
I somehow feel that even without `exxdiv` should be able to converge... The cell is large enough and 30 kpts should be very large as well.

**Comment by tberkel** [comment]
I agree that the convergence shown looks worse than "slow", and instead
looks like it's not going to converge.  Probably related to the fact that
it's 1D?

**Comment by yuanliu1** [comment]
Thanks for the 'vcut_sph' suggestion. Yes, I have similar feeling that the convergence is too bad for a cell of this size and number of kpoints... The discussion in a previous issue #250 is also very helpful.

**Comment by yangcal** [comment]
Hi Yuan,
For hydrogen chain system, you also need to make sure that you're converging to the same final state. I ran calculation using exxdiv=None for nkpts=3, 8 and 15, it seems some of them are converging to AFM phase some to PM phase. There will be energy differences in the these phases and they will also have different convergence rate to TDL. You might want to customize a initial guess for dm to seed SCF calculation.

**Comment by yuanliu1** [comment]
Thanks for the comment on AFM vs. PM phase. I also find this behavior at a slightly longer bond length.

**Comment by zhcui** [comment]
One good check is that you can start with a smaller unit cell (to avoid symmetry breaking), and try KRHF to test the convergence over k with exxdiv=None.

**Comment by yuanliu1** [comment]
Good idea, thanks.
