### ISSUE TITLE
PBC CISD fails to compute even for a minimal case

### ISSUE THREAD

**Issue by Simonsays095** [pyscf/pyscf#367]
I couldn't find any examples on how to use CISD with periodic boundary conditions, but below is my attempt to make it work based on how other PBC modules are used. I included the error it returns, as well. Either I am doing something wrong (for which more documentation/examples would be much appreciated) or there is an error in the program due to the fact that kmf.mo_coeffs is a list of mo coefficient arrays (in this case, a length-1 list), rather than a single array. This is in PySCF version 1.6.1 and python version 3.7.1. Thank you.

```
import numpy as np
from pyscf.pbc import gto, scf, ci

cell = gto.Cell()

cell.atom = [
    ['H',(0,0,0)],
    ['H',(1,0,0)]
]

cell.basis = 'STO-6G'
cell.dimension = 1
cell.a = np.eye(3)*2
cell.unit = 'A'
cell.spin = 0
cell.build()

kmf = scf.KRHF(cell).density_fit()
kmf.kpts = cell.make_kpts([1,1,1])
kmf.kernel()

mc = ci.CISD(kmf)
ecisd, civec = mc.kernel()
```
Full output, including the error:
```
converged SCF energy = -1.34277184093873
Traceback (most recent call last):
  File "kcisd_error.py", line 23, in <module>
    ecisd, civec = mc.kernel()
  File "pyscf/ci/cisd.py", line 880, in kernel
    return self.cisd(ci0, eris)
  File "pyscf/ci/cisd.py", line 883, in cisd
    eris = self.ao2mo(self.mo_coeff)
  File "pyscf/pbc/ci/cisd.py", line 35, in ao2mo
    eris = rccsd._make_eris_incore(self, mo_coeff, ao2mofn=ao2mofn)
  File "pyscf/cc/rccsd.py", line 252, in _make_eris_incore
    eris._common_init_(mycc, mo_coeff)
  File "pyscf/cc/ccsd.py", line 1199, in _common_init_
    self.mo_coeff = mo_coeff = _mo_without_core(mycc, mo_coeff)
  File "pyscf/mp/mp2.py", line 414, in _mo_without_core
    return mo[:,get_frozen_mask(mp)]
  File "pyscf/mp/mp2.py", line 235, in get_frozen_mask
    moidx = numpy.ones(mp.mo_occ.size, dtype=numpy.bool)
AttributeError: 'list' object has no attribute 'size'
```

**Comment by yangcal** [comment]
Hi,

Currently only Gamma point CISD is supported in pbc and you can specify it by calling pbc.scf.RHF without giving kpts, e.g:

kmf = scf.RHF(cell).density_fit()
kmf.kernel()
mc = ci.CISD(kmf)
ecisd, civec = mc.kernel()

**Comment by tberkel** [comment]
A lot of the code used for periodic ground-state and EOM-CCSD could be
modified to CISD if one were so inclined.  However, keep in mind that
periodic k-point sampled CISD is not so promising, due to its lack of size
extensivity.

**Comment by hungpham2017** [comment]
@tberkel: just a follow-up question, should both Gamma-point and k-point sampled CISD suffer from size-extensivity? or you mean since CISD is already not size-extensive so it is just not worth effort to implement a more complicated but not useful k-point sampling version of it? Thanks

**Comment by tberkel** [comment]
Yes, the thermodynamic limit of solids is reached equivalently by larger
supercells w/ Gamma-point sampling or with a minimal unit cell and
increasingly dense k-point sampling.  The latter is computationally more
efficient because it is aware of translational symmetry.  However, for
CISD, converging to the thermodynamic limit is not desirable bc the theory
is not size extensive.
