### ISSUE TITLE
time.clock() will not work in python3.8

### ISSUE THREAD

**Issue by lkwagner** [pyscf/pyscf#368]
Hi all, 

Python 3.8 will be released in a few months, and with it time.clock() will disappear. Also Python 3.7 throws bunches of warnings whenever I run pyscf. An easy fix which abandons python2 is to change all time.clock() calls to time.process_time(). I'm not sure if there is a cleaner fix which supports both 2.7 and 3.8.

What is the status on supporting python2? It will actually not be supported after January of this year. 

Thanks!

Lucas

**Comment by xwang862** [comment]
Thanks for pointing it out. I agree that `time.clock()` should be replaced by `process_time()` or `perf_counter()`. We can keep the backward compatibility for Python 2.7 with something like  
```
try:
   from time import process_time # or perf_counter
except ImportError:
   from time import clock as process_time
```

**Comment by sunqm** [comment]
It was handled in dev branch, not yet merged
https://github.com/sunqm/pyscf/blob/master/pyscf/lib/logger.py#L82

**Comment by lkwagner** [comment]
Great! Glad to see you're on top of things!
