### ISSUE TITLE
ThreadRuntimeError for CCSD calculations

### ISSUE THREAD

**Issue by jakobkraus** [pyscf/pyscf#372]
Hi everyone,

I have encountered some issues when using the ccsd functionality in combination with larger molecules.

The error looks like this:

Traceback (most recent call last):
  File "/sw/installed/pyscf/1.6.0-intel-2018a-Python-3.6.4/lib/python3.6/site- 
   packages/pyscf/ao2mo/outcore.py", line 322, in general
  async_write(icomp, row0, row1, outbuf)
  File "/sw/installed/pyscf/1.6.0-intel-2018a-Python-3.6.4/lib/python3.6/site-packages/pyscf/lib/misc.py", line 815, in async_fn
  self.handler.join()
  File "/sw/installed/pyscf/1.6.0-intel-2018a-Python-3.6.4/lib/python3.6/site-packages/pyscf/lib/misc.py", line 738, in join
  raise ThreadRuntimeError('Error on thread %s' % self)
 10 pyscf.lib.misc.ThreadRuntimeError: Error on thread <ThreadWithTraceBack(Thread-726, started 47291481048832)>

, whereas my run script looks like this:

28      sysname='ribose_after_run1'
 29     atoms = read(sysname+'_final_geometry.xyz')
 30     charge = 0
 31     spin = 0
 32     basis = 'aug-ccpVTZ'
 33     max_cycle = 300
 34     conv_tol = 1e-6
 35     verbose = 4
 36 
 37     
 38 
 39     
 41     [geo,nuclei,fod1,fod2,included] = xyz_to_nuclei_fod(atoms)
 42 
 43     mol = gto.M(atom=ase2pyscf(nuclei),spin=spin,charge=charge,basis=basis)
 44 
 45     mf = scf.UHF(mol)
 46     mf.verbose = verbose
 47     mf.max_cycle = max_cycle
 48     mf.conv_tol = conv_tol
 49 
 50     
 51     potentialenergy_hf = mf.kernel()
 52    
 53     potentialenergy_hf *= Ha

 88     cc = cc.UCCSD(mf)
 89     cc.verbose = verbose
 90     cc.conv_tol = conv_tol
 91     cc.max_cycle = max_cycle
 92     cc.direct = True
 93 
 94     start = time.time()
 95     cc.kernel()
 96     end = time.time()

The error is thrown after the RHF calculation is done. 
For some molecules I calculated, the error did not appear at all, whereas for others, it vanished if I set cc.direct = True. However, for some I have not found any solution, which is why I would be very grateful for any help and suggestions.

Have a nice day

Jakob

**Comment by sunqm** [comment]
What's the problem size?

Without using ao direct CC, all integrals and intermediates, roughly ~N^4*4 bytes, have to be saved on disk in the temporary folder. By default, the temporary folder is /tmp on most linux OS. It may not be big enough to hold the MO integrals.

**Comment by jakobkraus** [comment]
Thanks for the quick reply.

Ribose is a system with 80 electrons. However,  I thought that ao direct CC was already enabled by setting cc.direct = True in line 92 of my program.

**Comment by jakobkraus** [comment]
Update: using the pyscf example script  pyscf/examples/cc/15-incore_mo_ccsd_t.py instead of my script I posted here has been promising. However, I would also like to include the calculation of ionization potentials via ccsd.ipccsd(). Is it possible to combine the ipccsd functionality with the example script?

**Comment by sunqm** [comment]
cc.direct is the attribute to enable ao direct CC.

The error traceback does not show the reason of the error. I've improved the traceback and changes will be available in next release (pyscf 1.7).  My guess the problem here is out-of-disk error from h5py. 
88-electron molecule seems not a small system for CCSD, assuming the virtual space is roughly 10 times of the occupied space. So that's a system of ~500 orbitals. The requirement of disk space is roughly 200 GB. It should be not a big issue for most modern computers. The calculation here may write the temporary data to the /tmp directory under OS partition, which is typically ~50 GB space in total. It's recommended to assign a different scratch directory for temporary files. It's controlled the environment variable TMPDIR or PYSCF_TMPDIR.

**Comment by sunqm** [comment]
Example script pyscf/examples/cc/15-incore_mo_ccsd_t.py basically put all intermediate integral data in memory. ccsd.ipccsd() supports the same integral data structure. So you can add ccsd.ipccsd() in the code for IP. However, ipccsd (also eaccsd) will generate some intermediates at runtime. The intermediates will be written to disk. Currently, the code does not support to hold the intermediates data in memory. You may get a similar error like the one when you run regular CCSD. TMPDIR or PYSCF_TMPDIR trick is still needed to change the temporary location.

A tip in case useful, setting TMPDIR=/dev/shm will lead to temporary data dumped into memory. /dev/shm is a folder virtualized by physical memory. You can use this trick if you need better IO performance and you are sure memory is enough for this system. Then you don't need the intermediates or the tricks of example 15-incore_mo_ccsd_t.py .

**Comment by jakobkraus** [comment]
Thank you for your advice. I will test the TMPDIR=/dev/shm trick.
