### ISSUE TITLE
Error Registering ddcsomo gradients

### ISSUE THREAD

**Issue by WDerricotte** [pyscf/pyscf#375]
Hello PySCF Developers,

I am using PySCF in a part of my code to get the gradient with solvation effects using DDCOSMO, I call the solvent gradient using code that has the following structure:

```python
from pyscf import gto, scf, dft, grad, solvent,
scf_obj = scf.RHF(pymol) # Here pymol is a molecule string
solv_obj = scf_obj.DDCOSMO()
solv_obj.with_solvent.eps = eps # eps is a float defining the solvent dielectric 
E = solv_obj.scf()
grad = solv_obj.nuc_grad_method().kernel()
```

When I run the code I get the following message:

```
Error for registering ddcosmo gradients: 'str' object has no attribute 'Gradients'
```
However, despite this "error" the code continues to run and give me the solvent gradient. Is this some general warning or is this indicative that I have made an error in calling the solvent gradient? It honestly seems to work fine regardless of this error, the gradients are different from the gas phase and seems consistent with bulk solvent behavior in the few examples I've run.

**Comment by sunqm** [comment]
This is a bug when injecting DDCOSMO gradients class into a gradient object. It doesn't affect to apply nuc_grad_method to a solvent-scf object, which is the case of your code.

Injecting DDCOSMO gradients to gradient object seems not making too much sense. It has been removed in the latest update. You will not see the warning msg in future releases.

**Comment by WDerricotte** [comment]
Sounds good. Thank you so much for your response.
