### ISSUE TITLE
relativistic ECPs with spin-orbit component

### ISSUE THREAD

**Issue by mmorale3** [pyscf/pyscf#378]
A question for the PySCF team, are there plans to implement (or have someone already implemented) relativistic ECPs with a spin-orbit contribution, for example using Stuttgart's form? I am interested in both molecular and PBC calculations.

Miguel Morales
LLNL

**Comment by bogdanoff** [comment]
I certainly support this feature request.
There is a short description of SOC ECPs at [NWChem website](http://www.nwchem-sw.org/index.php?title=ECP).

**Comment by gkc1000** [comment]
Hi Miguel,
We do not currently support relativistic ECP's with spin-orbit coupling. If
people would really like this then please tag as a feature request and we
will look into it.

However, it what you actually want is a treatment of spin-orbit coupling
and scalar relativistic effects in a 2-component theory, the plan is to
include X2C with spin-orbit mean-field very soon. This was, for example,
used in Sandeep's paper J. Chem. Theory Comput. 2018 141 154-165, so the
code is there, just not yet pushed to the main branch. X2C for scalar
relativistic effects is already there. Sandeep should also comment if I did
not capture this correctly.
Garnet

**Comment by cuanto** [comment]
All electron relativistic 2C X2C with mean field spin-orbit is already in the main branch 

https://github.com/pyscf/pyscf/blob/master/pyscf/x2c/x2c.py#L30

however the module it is not imported in the __init__.py but it is easy to add it. Also althought not included for spin-compensated systems it is easy to add time reversal symmetry taking the function already included in the dhf.py file,

https://github.com/pyscf/pyscf/blob/master/pyscf/scf/dhf.py#L217

Even to my poor knowledge of relativistic theories you can easily add electron correlation based on the GHF versions of MP2,CCSD and CCSD(T) already include in pyscf, you can take a look at this at my repo for example,

https://github.com/cuanto/pyscf-scripts/blob/master/rel/2c-corr/ccsd.py

Please correct me if I am wrong with something !

Best,
Jose Luis

**Comment by gkc1000** [comment]
My understanding is that get_jk in the x2c module does not currently
include the spin-orbit terms (see docstring by get_jk), only the 1e part is
modified. The spin-orbit integrals are available but just not included in
the operator.

**Comment by cuanto** [comment]
Yes I forgot to comment that only the 1 electron part is included as it is tipically done in many papers, for a full description I think one has to swith to the four component module or include the integrals in the x2c.py module. Thanks for the correction !

**Comment by sanshar** [comment]
I was not aware that the 1-e SOC integrals were implemented in the x2c
module.
   Either way I can push code for generating X2C 1e-SOC integrals and
contributions from the 2-e SOC integrals at the mean field level. These are
the integrals derived in Zhendong Li papers. I will do that in the next
week or so. It is not easy to use these integrals with the ECPs though (as
far as I know).

Z. Li, Y. Xiao, and W. Liu. On the spin separation of algebraic
two-component relativistic Hamiltonians. The Journal of Chemical Physics,
137(5):154114, oct 2012.

Z. Li, Y. Xiao, and W. Liu. On the spin separation of algebraic
two-component relativistic Hamiltonians: Molecular properties. The Journal
of Chemical Physics, 141(5):54111, 2014.

Sandeep.

**Comment by zhendongli2008** [comment]
I have a local implementation of sf-X2C+SOMF with PYSCF some time ago.
If anyone is interested, please check
https://github.com/zhendongli2008/x2c_properties/blob/master/test.py

Best,
Zhendong Li


Sandeep Sharma <notifications@github.com> 于2019年7月12日周五 上午5:32写道：

> I was not aware that the 1-e SOC integrals were implemented in the x2c
> module.
> Either way I can push code for generating X2C 1e-SOC integrals and
> contributions from the 2-e SOC integrals at the mean field level. These are
> the integrals derived in Zhendong Li papers. I will do that in the next
> week or so. It is not easy to use these integrals with the ECPs though (as
> far as I know).
>
> Z. Li, Y. Xiao, and W. Liu. On the spin separation of algebraic
> two-component relativistic Hamiltonians. The Journal of Chemical Physics,
> 137(5):154114, oct 2012.
>
> Z. Li, Y. Xiao, and W. Liu. On the spin separation of algebraic
> two-component relativistic Hamiltonians: Molecular properties. The Journal
> of Chemical Physics, 141(5):54111, 2014.
>
> Sandeep.
>
>
> On Thu, Jul 11, 2019 at 7:52 PM Jose Luis Casals Sainz <

**Comment by gkc1000** [comment]
@zhendongli2008 @sanshar to follow up on this, I assume the next step is to add Zhendong's code for VsoDKH1contr to x2c, e.g. should this be added to a function like x2c_somf.get_jk?

**Comment by sanshar** [comment]
That is a good question, perhaps Qiming has some comments or suggestions. I
had hacked the fucking in the SHCI python file, but a more appropriate
place is probably in the x2c module.
   Also, the current implementation is rather memory intensive because it
stores all the soc two electron integrals (its about a factor of 9 more
expensive than the usual two-electron integrals) in memory and then
generates the 1 electron mf integrals by contracting the 2-electron
integrals with the density matrix.

Sandeep.

**Comment by sanshar** [comment]
Sorry, I meant

function*

Sandeep.

**Comment by lkwagner** [comment]
I'd like to echo the original request about implementing the spin-orbit ECPs. Do you have any pointers to what would need to be modified? It's only a one-body potential.

**Comment by sunqm** [comment]
SO-ECP is now available in dev branch. The SO-ECP integrals can be generated this way. https://github.com/pyscf/pyscf/blob/dev/examples/gto/20-soc_ecp.py

I believe the implementation of integrals is correct. But I'm not 100% sure the way I use the database https://people.clarkson.edu/~pchristi/reps.html is correct. It's highly appreciated if anyone can help to double-check the data in https://github.com/pyscf/pyscf/blob/dev/pyscf/gto/basis/crenbl.dat#L3404  and https://github.com/pyscf/pyscf/blob/dev/pyscf/gto/basis/crenbs.dat#L1132 and verify the mol.intor('ECPso') integrals against other implementations like NWChem.

**Comment by gkc1000** [comment]
@mmorale3 if you can help with generating some reference data so we can test our implementation that would be very helpful!

**Comment by bogdanoff** [comment]
I generated reference integrals for Zr atom with help of argos code from Columbus package. See [test_soc_ecp.tar.gz](https://github.com/pyscf/pyscf/files/3730211/test_soc_ecp.tar.gz). I had to tune  argos input heavily to match the pyscf AO order and normalization.

Pyscf is consistent with if the computed integrals multiplied by 2.
```
Im(SO:z)
argos                                       pyscf*2
    6    5      4.004200165114E-02          6    5      4.004201178292E-02
    8    6      1.065994721125E-02          8    6      1.065995011842E-02
    9    5     -1.065994721125E-02          9    5     -1.065995011842E-02
    9    8      2.873735658214E-03          9    8      2.873736493760E-03
   11    6      1.485249073287E-02         11    6      1.485249477763E-02
   11    9     -4.002749038439E-03         11    9     -4.002750200919E-03
   12    5     -1.485249073287E-02         12    5     -1.485249477763E-02
   12    8      4.002749038439E-03         12    8      4.002750200919E-03
   12   11      5.575365622742E-03         12   11      5.575367240081E-03
   14    6     -1.579111759614E-03         14    6     -1.579112173674E-03
   14    9      4.126620936954E-04         14    9      4.126622131903E-04
   14   12      5.752687595916E-04         14   12      5.752689258135E-04
   15    5      1.579111759614E-03         15    5      1.579112173674E-03
   15    8     -4.126620936954E-04         15    8     -4.126622131903E-04
   15   11     -5.752687595916E-04         15   11     -5.752689258135E-04
   15   14      6.553363510312E-05         15   14      6.553365316101E-05
   20   18     -1.394144392553E-03         20   18     -1.394140548061E-03
   21   17     -2.788288785106E-03         21   17     -2.788281096123E-03
   22   21     -2.976762752757E-03         22   21     -2.976754392401E-03
   23   20     -1.488381376378E-03         23   20     -1.488377196200E-03
   25   18      1.488381376378E-03         25   18      1.488377196200E-03
   25   23     -1.591726809454E-03         25   23     -1.591722259034E-03
   26   17      2.976762752757E-03         26   17      2.976754392401E-03
   26   22     -3.183453618907E-03         26   22     -3.183444518069E-03
   27   21      4.424117131574E-05         27   21      4.424106258230E-05
   27   26     -4.669576615223E-05         27   26     -4.669564882656E-05
   28   20      2.212058565787E-05         28   20      2.212053129115E-05
   28   25     -2.334788307612E-05         28   25     -2.334782441328E-05
   30   18     -2.212058565787E-05         30   18     -2.212053129115E-05
   30   23      2.334788307612E-05         30   23      2.334782441328E-05
   30   28     -3.777421600741E-07         30   28     -3.777413510841E-07
   31   17     -4.424117131574E-05         31   17     -4.424106258230E-05
   31   22      4.669576615223E-05         31   22      4.669564882656E-05
   31   27     -7.554843201482E-07         31   27     -7.554827021683E-07
   36   34      3.127972377112E-07         36   34      3.127972377112E-07
   37   33      6.255944754225E-07         37   33      6.255944754224E-07
   38   32     -9.383917225175E-07         38   32      9.383917131335E-07
```

**Comment by sunqm** [comment]
> I generated reference integrals for Zr atom with help of argos code from Columbus package. See [test_soc_ecp.tar.gz](https://github.com/pyscf/pyscf/files/3730211/test_soc_ecp.tar.gz). I had to tune argos input heavily to match the pyscf AO order and normalization.
> 
> Pyscf is consistent with if the computed integrals multiplied by 2.
> 
> ```
> Im(SO:z)
> argos                                       pyscf*2
>     6    5      4.004200165114E-02          6    5      4.004201178292E-02
>     8    6      1.065994721125E-02          8    6      1.065995011842E-02
>     9    5     -1.065994721125E-02          9    5     -1.065995011842E-02
>     9    8      2.873735658214E-03          9    8      2.873736493760E-03
>    11    6      1.485249073287E-02         11    6      1.485249477763E-02
>    11    9     -4.002749038439E-03         11    9     -4.002750200919E-03
>    12    5     -1.485249073287E-02         12    5     -1.485249477763E-02
>    12    8      4.002749038439E-03         12    8      4.002750200919E-03
>    12   11      5.575365622742E-03         12   11      5.575367240081E-03
>    14    6     -1.579111759614E-03         14    6     -1.579112173674E-03
>    14    9      4.126620936954E-04         14    9      4.126622131903E-04
>    14   12      5.752687595916E-04         14   12      5.752689258135E-04
>    15    5      1.579111759614E-03         15    5      1.579112173674E-03
>    15    8     -4.126620936954E-04         15    8     -4.126622131903E-04
>    15   11     -5.752687595916E-04         15   11     -5.752689258135E-04
>    15   14      6.553363510312E-05         15   14      6.553365316101E-05
>    20   18     -1.394144392553E-03         20   18     -1.394140548061E-03
>    21   17     -2.788288785106E-03         21   17     -2.788281096123E-03
>    22   21     -2.976762752757E-03         22   21     -2.976754392401E-03
>    23   20     -1.488381376378E-03         23   20     -1.488377196200E-03
>    25   18      1.488381376378E-03         25   18      1.488377196200E-03
>    25   23     -1.591726809454E-03         25   23     -1.591722259034E-03
>    26   17      2.976762752757E-03         26   17      2.976754392401E-03
>    26   22     -3.183453618907E-03         26   22     -3.183444518069E-03
>    27   21      4.424117131574E-05         27   21      4.424106258230E-05
>    27   26     -4.669576615223E-05         27   26     -4.669564882656E-05
>    28   20      2.212058565787E-05         28   20      2.212053129115E-05
>    28   25     -2.334788307612E-05         28   25     -2.334782441328E-05
>    30   18     -2.212058565787E-05         30   18     -2.212053129115E-05
>    30   23      2.334788307612E-05         30   23      2.334782441328E-05
>    30   28     -3.777421600741E-07         30   28     -3.777413510841E-07
>    31   17     -4.424117131574E-05         31   17     -4.424106258230E-05
>    31   22      4.669576615223E-05         31   22      4.669564882656E-05
>    31   27     -7.554843201482E-07         31   27     -7.554827021683E-07
>    36   34      3.127972377112E-07         36   34      3.127972377112E-07
>    37   33      6.255944754225E-07         37   33      6.255944754224E-07
>    38   32     -9.383917225175E-07         38   32      9.383917131335E-07
> ```

Thanks so much for the careful testing.

The factor of 2 was due to the convention of pyscf integrals in spherical GTO basis. Pyscf uses
```
u = mol.sph2spinor_coeff()
ints_spinor = einsum("sxy,spq,xpi,yqj->ij", lib.PauliMatrices, ints_sph, u.conj(), u)
```
to transform the integrals between the spinor basis and the spherical basis. Pauli matrix is used rather than the the spin operator. The SOC-ECP code was implemented to make the spinor basis integrals mol.intor("ECPso_spinor") produce the SOC Hamiltonian
```
H^{SO} = s dot U_ECP
```
The factor 1/2 in spin operator was added in ECPso_sph integrals.

Starting from commit 53025694c9cf928885501ca3be775a43663487f5, the factor 1/2 was removed from the integral ECPso_sph . When calling mol.intor("ECPso"), it evaluates <i| U_ECP |j>. The SOC Hamiltonian in spinor basis should scaled by 1/2
```
H_SO = .5 * mol.intor('ECPso_spinor')
```
See relevant the example
https://github.com/pyscf/pyscf/blob/master/examples/gto/20-soc_ao_integrals.py
