### ISSUE TITLE
Incompatibility with libxc master

### ISSUE THREAD

**Issue by susilehtola** [pyscf/pyscf#379]
Once #332 (which should now been ready to go) has been merged, someone should fix the compatibility of pyscf with libxc master, where mgga third derivatives have been added and so the calls look a bit different.

**Comment by sunqm** [comment]
Thanks for the new libxc library and the support of 3rd order mgga derivatives. PR #332 involves the updates of compiling prerequisite and library dependency. It will not be put in version 1.6. Updates will be considered in 1.7 release or later version.

**Comment by sunqm** [comment]
PR #332 is merged to dev branch. libxc-4.3.4 will be used in the 1.7 release
