### ISSUE TITLE
some problems about DFT-D3

### ISSUE THREAD

**Issue by hebrewsnabla** [pyscf/pyscf#385]
There's an error when using DFT-D3. My code is as follows,
```
from pyscf import gto, dft, dftd3

mol = gto.Mole()
mol.atom = '''H 0 0 0; H 0 0 0.6'''
mol.basis = 'cc-pvdz'
mol.output = '1.log'
mol.verbose = 9
mol.build()

mf = dft.RKS(mol)
mf.xc = 'HF'

mfd3 = dftd3.itrf.dftd3(mf)
#mfd3.version = 3
mfd3.kernel()
```

And the error message reads
```Traceback (most recent call last):
  File "testdftd3.py", line 17, in <module>
    mfd3.kernel()
  File "/home/wsr/pyscf/lib/misc.py", line 584, in aliased_fn
    return getattr(self, fname)(*args, **kwargs)
  File "/home/wsr/pyscf/scf/hf.py", line 1517, in scf
    self.dump_flags()
  File "/home/wsr/pyscf/dftd3/itrf.py", line 166, in dump_flags
    self.with_dftd3.dump_flags()
  File "/home/wsr/pyscf/dftd3/itrf.py", line 252, in dump_flags
    logger.info(mol, 'func', self.xc)
  File "/home/wsr/pyscf/lib/logger.py", line 131, in info
    flush(rec, msg, *args)
  File "/home/wsr/pyscf/lib/logger.py", line 110, in flush
    rec.stdout.write(msg%args)
```
And the output file ended at `** DFTD3 parameter **`. So it seems something goes wrong in `logger.info(mol, 'func', self.xc)`. I'm confused.

Btw, is it OK to modify `_DFTD3.version`? Since M06-L, etc. need `version=3`, it seems we cannot use M06-L-D3 in PySCF. Or is there any other way to implement M06-L-D3, etc.?

**Comment by sunqm** [comment]
It's a bug in printing function. Nothing wrong with the DFTD3 library or its version. It's fixed in latest updates

**Comment by hebrewsnabla** [comment]
Thank you.
My second question is:
Adding D3 to M06-L, M06-2X, etc., will trigger AssertionError in `assert(self.version in supported_versions)`, since `_DFTD3.version` is set to be `4`. Does it mean other versions, like 3, is not supported now, or we can manually modify `_DFTD3.version` in `itrf.py`?

**Comment by sunqm** [comment]
The interface supports all the versions that are available in the dftd3 library https://github.com/dftbplus/dftd3-lib/blob/master/lib/core.f90#L188 . In that library, one dft functional often has different ways of parameterization. The .version attribute is to switch to a different dftd3 parameterization. This is the table https://github.com/pyscf/pyscf/blob/master/pyscf/dftd3/itrf.py#L51 extracted from the core.f90 file. You can set _DFTD3.version for M06

**Comment by hebrewsnabla** [comment]
OK, thank you.
