### ISSUE TITLE
License and PySCF logo

### ISSUE THREAD

**Issue by Melisius** [pyscf/pyscf#388]
Hi,

I am collaborating in a project where we interface to PySCF. 
We would like include the PySCF logo in the Table of Content figure of the publication.

The license for PySCF is Apache 2.0, which states:

   6. Trademarks. This License does not grant permission to use the trade
      names, trademarks, service marks, or product names of the Licensor,
      except as required for reasonable and customary use in describing the
      origin of the Work and reproducing the content of the NOTICE file.

Is there a way to get access to the PySCF logo without violating the license for the PySCF software?

**Comment by gkc1000** [comment]
Hi Erik,

I'm not a lawyer, but I would think your use case falls under "reasonable
and customary use", since you are using the logo to represent the PySCF
program itself. Thanks for checking though.

Garnet

**Comment by gkc1000** [comment]
If there are no further issues, I am closing this comment.
