### ISSUE TITLE
Hardcoded functional lists still used in dev branch

### ISSUE THREAD

**Issue by susilehtola** [pyscf/pyscf#393]
As described in #332, functional names and ids should not be hardcoded in pyscf, as code duplication is bad and the tools exist to get the lists from libxc. If one wants to use a functional only recently available in libxc, using the functional should be as simple as linking pyscf to the newer version of libxc.

The hardcoded lists were removed in #332, but it appears that the code getting the list from libxc has been commented out and the hardcoded list put back in.

**Comment by gkc1000** [comment]
This is a reasonable possibility but would require some postprocessing of what libxc returns. For the time being, we've decided this list is still the simplest option, and if that changes we will reconsider.
