### ISSUE TITLE
Some issues with Davidson implementations for non-symmetric matrices

### ISSUE THREAD

**Issue by awhite862** [pyscf/pyscf#395]
I've noticed a couple of issues/possible bugs in two of the implementations of Davidson for non-symmetric matrices:

**pyscf/pyscf/lib/linalg_helper.py:davidson_nosym1**

- If a lower root, not represented in the guess, appears during the iteration, it disappears when the subspace is collapsed. The result is that the iteration will never converge in this situation. This appears to occur even when "SORT_EIG_BY_SIMILARITY = False"
- I'm not sure how the resulting eigenvectors are normalized. I don't see how they can be biorthogonalized, since the left eigenvectors aren't usually computed, but they aren't normalized to unity either. Some documentation on this would be helpful

**pyscf/pyscf/pbc/lib/linalg_helper.py:davidson**

If multiple roots are requested, each root is converged one-at-a-time, but in the final eigenvectors and eigenvalues only the last root is correct. The other roots are close to their converged value, but they have been slightly changed during the iteration for subsequent roots. This seems to be an issue even for very tight thresholds.

**Comment by gkc1000** [comment]
Can you post an example?

**Comment by verena-neufeld** [comment]
Hi @awhite862 , do you know whether this has been resolved?

**Comment by awhite862** [comment]
I'm not sure, but feel free to close the issue. The reason I never posted an example initially is because this came up while using a heavily modified (and now very outdated) version of PySCF. It is likely that #1654 has partially or totally resolved the issue.

**Comment by sunqm** [comment]
We can reopen the issue if the diagonalization code fails again.
