### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by drmcnelson** [pyscf/pyscf#397]
Make fails to connect with www.tddft.org, and ultimately, fails.   The site refuses incoming connections.

**Comment by sunqm** [comment]
In CMakeLists.txt file
https://github.com/pyscf/pyscf/blob/master/pyscf/lib/CMakeLists.txt#L149
https://github.com/pyscf/pyscf/blob/dev/pyscf/lib/CMakeLists.txt#L149

It often contains a backup download link nearby. You can try the other download URL.

**Comment by sunqm** [comment]
The same to issue #417
