### ISSUE TITLE
How to define omega in range-separated functionals?

### ISSUE THREAD

**Issue by tzyii** [pyscf/pyscf#398]
`from pyscf import gto, dft, scf, tools

mol = gto.Mole()
mol.atom = '''H 0 0 0; F 0 0 1.1'''

mol.basis = '6-31g**'
mol.charge = 0 
mol.spin = 0 
mol.output = 'neutral.log'
mol.verbose = 4 
mol.build()

mf = dft.RKS(mol)
mf.xc = 'wb97x'
mf.run()`

Is 'mf.omega = 0.25' right?

**Comment by sunqm** [comment]
In pyscf-1.6, setting mf.omega = 0.25 can change the range-separation parameter in Coulomb and exchange integrals only. The parameter in GGA functional is not updated accordingly. This problem is fixed in commit 6740f11 of dev branch, which will be available in 1.7 release.

**Comment by tzyii** [comment]
Thank you for your reply. Looking forward to the new release.

**Comment by sunqm** [comment]
Here are the examples

https://github.com/pyscf/pyscf/blob/dev/examples/dft/13-rsh_dft.py
