### ISSUE TITLE
[Question] Why the diagonal elements of overlap matrix are not 1.0 for 6d basis?

### ISSUE THREAD

**Issue by tzyii** [pyscf/pyscf#411]
`#INFO: **** input file is /scratch/a.py ****
from pyscf import gto, scf, dft, tools

mol = gto.Mole()
mol.verbose = 5
mol.cart = True
mol.atom = '''
C      -0.403890314    0.636558575    0.000098613
C       0.366091141   -0.697088426    0.000098613
C       1.906054051   -0.697088426    0.000098613
C       2.676035507    0.636558575    0.000098613
C       1.906054051    1.970205577    0.000098613
C       0.366091141    1.970205577    0.000098613
H      -1.543885189    0.636558575    0.000098613
H      -0.203906296   -1.684352948    0.000098613
H       2.476051489   -1.684352948    0.000098613
H       3.816030381    0.636558575    0.000098613
H       2.476051489    2.957470098    0.000098613
H      -0.203906296    2.957470098    0.000098613
'''
mol.basis = 'def2-svp'
mol.spin = 0
mol.symmetry = False
mol.build()

mf = dft.RKS(mol)
mf.xc = 'b3lypg'
print(mf.get_ovlp().diagonal())

#INFO: ******************** input file end ********************

System: uname_result(system='Linux', node='cluster', release='2.6.32-431.el6.x86_64', version='#1 SMP Sun Nov 10 22:19:54 EST 2013', machine='x86_64', processor='x86_64')  Threads 1
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]
numpy 1.15.4  scipy 1.2.1
Date: Tue Aug 27 17:54:26 2019
PySCF version 1.6.3
PySCF path  /home/abc/.local/opt/psi/envs/pyscf/lib/python3.7/site-packages/pyscf

[CONFIG] conf_file None
[INPUT] verbose = 5
[INPUT] max_memory = 4000 
[INPUT] num. atoms = 12
[INPUT] num. electrons = 42
[INPUT] charge = 0
[INPUT] spin (= nelec alpha-beta = 2S) = 0
[INPUT] symmetry False subgroup None
[INPUT] Mole.unit = angstrom
[INPUT] Cartesian GTO integrals (6d 10f)
[INPUT]  1 C     -0.403890314000   0.636558575000   0.000098613000 AA   -0.763242077825   1.202921368993   0.000186351562 Bohr
[INPUT]  2 C      0.366091141000  -0.697088426000   0.000098613000 AA    0.691811993120  -1.317306209744   0.000186351562 Bohr
[INPUT]  3 C      1.906054051000  -0.697088426000   0.000098613000 AA    3.601920135008  -1.317306209744   0.000186351562 Bohr
[INPUT]  4 C      2.676035507000   0.636558575000   0.000098613000 AA    5.056974207842   1.202921368993   0.000186351562 Bohr
[INPUT]  5 C      1.906054051000   1.970205577000   0.000098613000 AA    3.601920135008   3.723148949621   0.000186351562 Bohr
[INPUT]  6 C      0.366091141000   1.970205577000   0.000098613000 AA    0.691811993120   3.723148949621   0.000186351562 Bohr
[INPUT]  7 H     -1.543885189000   0.636558575000   0.000098613000 AA   -2.917520174982   1.202921368993   0.000186351562 Bohr
[INPUT]  8 H     -0.203906296000  -1.684352948000   0.000098613000 AA   -0.385327054514  -3.182965768824   0.000186351562 Bohr
[INPUT]  9 H      2.476051489000  -1.684352948000   0.000098613000 AA    4.679059184532  -3.182965768824   0.000186351562 Bohr
[INPUT] 10 H      3.816030381000   0.636558575000   0.000098613000 AA    7.211252303110   1.202921368993   0.000186351562 Bohr
[INPUT] 11 H      2.476051489000   2.957470098000   0.000098613000 AA    4.679059184532   5.588808506811   0.000186351562 Bohr
[INPUT] 12 H     -0.203906296000   2.957470098000   0.000098613000 AA   -0.385327054514   5.588808506811   0.000186351562 Bohr
[INPUT] ---------------- BASIS SET ---------------- 
[INPUT] l, kappa, [nprim/nctr], expnt,             c_1 c_2 ...
[INPUT] C
[INPUT] 0    0    [5    /1   ]  1238.4016938      0.0054568832082
                                186.29004992      0.040638409211
                                42.251176346      0.18025593888
                                11.676557932      0.46315121755
                                3.5930506482      0.44087173314
[INPUT] 0    0    [1    /1   ]  0.40245147363        1
[INPUT] 0    0    [1    /1   ]  0.13090182668        1
[INPUT] 1    0    [3    /1   ]  9.4680970621      0.038387871728
                                2.0103545142      0.21117025112
                                0.54771004707     0.51328172114
[INPUT] 1    0    [1    /1   ]  0.15268613795        1
[INPUT] 2    0    [1    /1   ]  0.8                  1
[INPUT] H
[INPUT] 0    0    [3    /1   ]  13.010701         0.019682158
                                1.9622572         0.13796524
                                0.44453796        0.47831935
[INPUT] 0    0    [1    /1   ]  0.12194962           1
[INPUT] 1    0    [1    /1   ]  0.8                  1

nuclear repulsion = 185.68028900987
number of shells = 54
number of NR pGTOs = 192
number of NR cGTOs = 120
basis = def2-svp
ecp = {}
CPU time:         0.54
[1.         1.         1.         1.         1.         1.
 1.         1.         1.         2.51327412 0.83775804 0.83775804
 2.51327412 0.83775804 2.51327412 1.         1.         1.
 1.         1.         1.         1.         1.         1.
 2.51327412 0.83775804 0.83775804 2.51327412 0.83775804 2.51327412
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         2.51327412 0.83775804 0.83775804
 2.51327412 0.83775804 2.51327412 1.         1.         1.
 1.         1.         1.         1.         1.         1.
 2.51327412 0.83775804 0.83775804 2.51327412 0.83775804 2.51327412
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         2.51327412 0.83775804 0.83775804
 2.51327412 0.83775804 2.51327412 1.         1.         1.
 1.         1.         1.         1.         1.         1.
 2.51327412 0.83775804 0.83775804 2.51327412 0.83775804 2.51327412
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.        ]
`

**Comment by sunqm** [comment]
Cartesian GTOs are not normalized to 1. Only spherical GTO basis and spinor basis are normalized.

**Comment by tzyii** [comment]
ok，thank you for your reply. I note this because other programs (stda and multiwfn) warn me the molden file from this example is problematic，as the trace of S*P is not equal to nelectron. By the way, the molden.py also has other problems when cartesian basis is used.

**Comment by sunqm** [comment]
The latest updated fixed the Cartesian basis normalization convention issue. If you the other problem you mentioned is the warning of shape inconsistency like
```
WARN: shapes (20,20) and (19,20) not aligned: 20 (dim 1) != 19 (dim 0)
```
It's also fixed in the latest commit

**Comment by tzyii** [comment]
Thanks. IMHO, the 45 line in molden.py need a cart=
mol.cart parameter or use mol.cart (drop the option) in order_ao_index function.

**Comment by sunqm** [comment]
Problem is fixed in the latest update.
