### ISSUE TITLE
Missing BLAS API packages

### ISSUE THREAD

**Issue by silverNitrateIon** [pyscf/pyscf#425]
Building fails for this project with the following error:

`-- A library with BLAS API not found. Please specify library location.
CMake Error at CMakeLists.txt:47 (message):
  A required library with BLAS API not found.

-- Configuring incomplete, errors occurred!
`

OS: Ubuntu LTS Bionic Beaver

Not entirely sure how to resolve this error. Any help would be great!

**Comment by gkc1000** [comment]
Do you have BLAS on your system? This is a prerequisite.

A simple way to resolve this is to use the Anaconda Python distribution,
then do "conda install pyscf".

**Comment by silverNitrateIon** [comment]
Great, thanks for this clarification. I will use the conda installation target instead of building from source.

**Comment by sunqm** [comment]
pyscf is available in pyscf channel

conda install -c pyscf pyscf

**Comment by bronze7** [comment]
Still facing this issue. conda install doesn't work either
