### ISSUE TITLE
Complex Fock Matrix in DFT Calculation

### ISSUE THREAD

**Issue by yangdatou** [pyscf/pyscf#426]
I tried to implement another real-time TDDFT within PySCF package, the get_veff method in KS classs may not be able to build Fock matrix from a complex density matrix.

Is it possible to let the KS.get_veff method accept complex density matrix? 

According to Lopata, Kenneth, and Niranjan Govind. JCTC 7.5 (2011): 1344-1355.,
a) the DFT XC terms are both real and symmetric and depend only on the real part of the density matrix
b) the exact exchange term is complex, Hermitian, and depends on the full complex density matrix.
c) the Coulomb term is a real-valued symmetric matrix which only depends on the real part of the complex density matrix.

**Comment by tberkel** [comment]
One option would be to use Generalized Kohn-Sham (`dft/gks.py`), which can
accept complex density matrices.

**Comment by yangdatou** [comment]
Thank you so much for your help

**Comment by yangdatou** [comment]
Hi, I tried functions in `dft/gks.py`, the methods inside would run with matrix of the shape (2*nbas, 2*nbas).

This may not be the best way to build complex Fock matrix for me.

```
from pyscf import gto, dft

mol = gto.M(
    atom = '''
  O     0.00000000    -0.00001441    -0.34824012
  H    -0.00000000     0.76001092    -0.93285191
  H     0.00000000    -0.75999650    -0.93290797
  ''',
    basis = '6-31g',
)

rks = dft.RKS(mol)
rks.xc = 'b3lyp'
rks.kernel()
rksdm = rks.make_rdm1()

gks = dft.GKS(mol)
gks.xc = 'b3lyp'
gks.get_veff(dm=rksdm, mol=gks.mol) # gks.get_veff(dm=rksdm)
```
P.S. There is something wrong in `gks. get_veff`, the line 35 
`if mol is None: mol = self.mol`
should be
`if mol is None: mol = ks.mol`

**Comment by zhcui** [comment]
If you just want to get a initial guess for GHF, you can do the following:

```
nao = mol.nao_nr()
dm0 = np.zeros((nao*2, nao*2))
dm0[:nao, :nao] = rksdm * 0.5 
dm0[nao:, nao:] = rksdm * 0.5 
```

**Comment by yangdatou** [comment]
Hi, what I want to do is building a `(nbas, nbas)`  complex fock matrix from a `(nbas, nbas)` complex density matrix. The `rks.get_veff` method may not support complex density matrix input. And the `gks.get_veff` method takes `(2*nbas, 2*nbas)` density matrix as input.

> I tried to implement another real-time TDDFT within PySCF package, the get_veff method in KS classs may not be able to build Fock matrix from a complex density matrix.
> 
> Is it possible to let the KS.get_veff method accept complex density matrix?
> 
> According to Lopata, Kenneth, and Niranjan Govind. JCTC 7.5 (2011): 1344-1355.,
> a) the DFT XC terms are both real and symmetric and depend only on the real part of the density matrix
> b) the exact exchange term is complex, Hermitian, and depends on the full complex density matrix.
> c) the Coulomb term is a real-valued symmetric matrix which only depends on the real part of the complex density matrix.

**Comment by yangdatou** [comment]
> If you just want to get a initial guess for GHF, you can do the following:
> 
> ```
> nao = mol.nao_nr()
> dm0 = np.zeros((nao*2, nao*2))
> dm0[:nao, :nao] = rksdm * 0.5 
> dm0[nao:, nao:] = rksdm * 0.5 
> ```

Hi, what I want to do is building a (nbas, nbas) complex fock matrix from a (nbas, nbas) complex density matrix. The rks.get_veff method may not support complex density matrix input. And the gks.get_veff method takes (2*nbas, 2*nbas) density matrix as input.

I tried to implement another real-time TDDFT within PySCF package, the get_veff method in KS classs may not be able to build Fock matrix from a complex density matrix.

Is it possible to let the KS.get_veff method accept complex density matrix?

According to Lopata, Kenneth, and Niranjan Govind. JCTC 7.5 (2011): 1344-1355.,
a) the DFT XC terms are both real and symmetric and depend only on the real part of the density matrix
b) the exact exchange term is complex, Hermitian, and depends on the full complex density matrix.
c) the Coulomb term is a real-valued symmetric matrix which only depends on the real part of the complex density matrix.

**Comment by yangdatou** [comment]
> If you just want to get a initial guess for GHF, you can do the following:
> 
> ```
> nao = mol.nao_nr()
> dm0 = np.zeros((nao*2, nao*2))
> dm0[:nao, :nao] = rksdm * 0.5 
> dm0[nao:, nao:] = rksdm * 0.5 
> ```

Hi, what I want to do is building a `(nbas, nbas)` complex fock matrix from a `(nbas, nbas) ` complex density matrix. The `rks.get_veff` method may not support complex density matrix input. And the `gks.get_veff` method takes `(2*nbas, 2*nbas)`  density matrix as input.

Is it possible to let the KS.get_veff method accept complex density matrix?

According to Lopata, Kenneth, and Niranjan Govind. JCTC 7.5 (2011): 1344-1355.,
a) the DFT XC terms are both real and symmetric and depend only on the real part of the density matrix
b) the exact exchange term is complex, Hermitian, and depends on the full complex density matrix.
c) the Coulomb term is a real-valued symmetric matrix which only depends on the real part of the complex density matrix.

**Comment by gkc1000** [comment]
Can you explain what your issue is with using a complex DM? You simply state that rks.get_veff may not support complex DM, but as far as I know, the Kohn-Sham methods already *do* accept hermitian density matrices with complex values. For example, the complex handling used to build veff can be seen in the pyscf.dft.numint module in the _dot_ao_dm function. The DMs are often complex values in PBC calculations.

**Comment by yangdatou** [comment]
> Can you explain what your issue is with using a complex DM? You simply state that rks.get_veff may not support complex DM, but as far as I know, the Kohn-Sham methods already _do_ accept hermitian density matrices with complex values. For example, the complex handling used to build veff can be seen in the pyscf.dft.numint module in the _dot_ao_dm function. The DMs are often complex valued in PBC calculations.

I am sorry for not offering enough details. With,
```
import numpy as np

from pyscf import gto, dft

mol = gto.M(
    atom = '''
  O     0.00000000    -0.00001441    -0.34824012
  H    -0.00000000     0.76001092    -0.93285191
  H     0.00000000    -0.75999650    -0.93290797
  ''',
    basis = '6-31g',
)

rks = dft.RKS(mol)
rks.xc = 'b3lyp'
rks.kernel()
rksdm = rks.make_rdm1()

rks.get_veff(dm=rksdm.astype(np.complex128))
```
I got,
```
---------------------------------------------------------------------------
UFuncTypeError                            Traceback (most recent call last)
<ipython-input-5-433152ef0d19> in <module>
     17 rksdm = rks.make_rdm1()
     18 
---> 19 rks.get_veff(dm=rksdm.astype(np.complex128))

~/anaconda3/lib/python3.7/site-packages/pyscf/dft/rks.py in get_veff(ks, mol, dm, dm_last, vhf_last, hermi)
    132                 vklr *= (alpha - hyb)
    133                 vk += vklr
--> 134         vxc += vj - vk * .5
    135 
    136         if ground_state:

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('complex128') to dtype('float64') with casting rule 'same_kind'
```
The same issue was mentioned by Koh in `pyscf/pyscf/rt/tdscf.py` line 18. I am trying to use proper functions provided by PySCF.

**Comment by sunqm** [comment]
This issue has been fixed
