### ISSUE TITLE
Degenerate states in Multiconfigurational and derivates

### ISSUE THREAD

**Issue by portega-usal** [pyscf/pyscf#430]
First of all, this is my first post in GitHub, so if there is anything wrong about format or else, just tell me. 

I have been using PySCF for a couple of months now, mainly devoted to multiconfigurational module, and specially interested in SHCI methods. I am trying to calculate PES of an oxygen molecule reacting with an organic fragment, and as many of you may know, the lower states of oxygen are a sigma triplet and a delta degenerate singlet. My problem here is that this program is identifying the singlet state as non-degenerate, so if I ask for two singlet states, it yields anothers state upper in energy, instead of giving the two-fold degenerate delta singlet.

My requests here is if someone could fix this treatment of degenerate states, in a similar way as other programs (Molcas for example) do, considering them as two different states although they have the same energy. This will help to plot energy surfaces, avoiding jump discontinuities when plotting different degenerate states that may break their symmetry along the reaction path.

Best regards,
Pablo

**Comment by jamesETsmith** [comment]
Hi Pablo,

Could you post a partial or complete input for your calculation?

Thanks,
James

**Comment by portega-usal** [comment]
`from pyscf import gto, scf, lib, tools, mcscf, mrpt, mp, cc, lo
import time
from pyscf.shciscf import shci
import re
import numpy
import functools
import os

f = open('energies_triplet_close.dat', 'w')
f.close()
f = open('energies_singlet_close.dat', 'w')
f.close()
f = open('energies_triplet_far.dat', 'w')
f.close()
f = open('energies_singlet_far.dat', 'w')
f.close()

# Initialize O2 molecule
b =  1.2
mol = gto.Mole()
mol.build(
verbose = 4,
output = 'scan_close.out',
atom = [
    ['O',(  0.000000,  0.000000, -b/2)],
    ['O',(  0.000000,  0.000000,  b/2)]],
basis = 'ccpvdz',
spin = 2
)

log = lib.logger.Logger(mol.stdout, 5)
cpu0 = time.clock(), time.time()
norb = 28 #ccpvdz
#norb = 92 # augccpvtz
#norb = 41 # anoroosdz
nelec = 16

uhf3 = scf.UHF(mol)
uhf3.scf()

ump2 = mp.UMP2(uhf3)

mch = mcscf.CASCI(uhf3, norb, nelec).as_scanner()
mch.fcisolver = shci.SHCI(mol)
mch.fcisolver.mpiprefix = 'mpirun -np 18'
mch.fcisolver.nroots = 1
mch.fcisolver.stochastic = True
mch.fcisolver.nPTiter = 100
mch.fcisolver.sweep_iter = [ 0, 3, 6 ]
#mch.fcisolver.sweep_iter = [ 0 ]
mch.fcisolver.DoRDM = True
#mch.fcisolver.sweep_epsilon = [ 1e-3 ]
mch.fcisolver.sweep_epsilon = [ 1e-3, 5e-4, 2e-4 ]
mch.fcisolver.epsilon2 = 1e-8
for i in [0.9,0.95,1.0,1.05,1.1,1.15,1.2,1.25,1.3,1.4,1.5,1.6,1.7,1.8,2.0,2.5,3.0,4.0,5.0]:
  new_coord = gto.Mole()
  new_coord.build(
  verbose = 0,
  atom = [
    ['O',(  0.000000,  0.000000, -i/2)],
    ['O',(  0.000000,  0.000000,  i/2)]],
  basis = 'ccpvdz',
  spin = 2
  )
  e_shci = mch(new_coord)

  uhf3 = scf.UHF(new_coord)
  uhf3.scf()  
  ump2 = mp.UMP2(uhf3)
  ump2.kernel()
  
  cpu0 = log.timer('2NP9 SHCI', *cpu0)
  
  with open('energies_triplet_close.dat', 'a') as f:
    #f.write('%4.3f %8.7f %8.7f %8.7f %8.7f \n' % (i,ump2.e_tot,e_shci[0],e_shci[1],e_shci[2]) )
    f.write('%4.3f %8.7f %8.7f %8.7f\n' % (i,uhf3.e_tot,ump2.e_tot,e_shci) )


# Initialize O2 molecule
b =  1.2
mol = gto.Mole()
mol.build(
verbose = 4,
output = 'scan_close.out',
atom = [
    ['O',(  0.000000,  0.000000, -b/2)],
    ['O',(  0.000000,  0.000000,  b/2)]],
basis = 'ccpvdz'
)

log = lib.logger.Logger(mol.stdout, 5)
cpu0 = time.clock(), time.time()
norb = 28 #ccpvdz
#norb = 92 # augccpvtz
#norb = 41 # anoroosdz
nelec = 16

uhf3 = scf.UHF(mol)
uhf3.scf()

ump2 = mp.UMP2(uhf3)

mch = mcscf.CASCI(uhf3, norb, nelec).as_scanner()
mch.fcisolver = shci.SHCI(mol)
mch.fcisolver.mpiprefix = 'mpirun -np 18'
mch.fcisolver.nroots = 3
mch.fcisolver.stochastic = True
mch.fcisolver.nPTiter = 100
mch.fcisolver.sweep_iter = [ 0, 3, 6 ]
#mch.fcisolver.sweep_iter = [ 0 ]
mch.fcisolver.DoRDM = True
#mch.fcisolver.sweep_epsilon = [ 1e-3 ]
mch.fcisolver.sweep_epsilon = [ 1e-3, 5e-4, 2e-4 ]
mch.fcisolver.epsilon2 = 1e-8
for i in [0.9,0.95,1.0,1.05,1.1,1.15,1.2,1.25,1.3,1.4,1.5,1.6,1.7,1.8,2.0,2.5,3.0,4.0,5.0]:
  new_coord = gto.Mole()
  new_coord.build(
  verbose = 0,
  atom = [
    ['O',(  0.000000,  0.000000, -i/2)],
    ['O',(  0.000000,  0.000000,  i/2)]],
  basis = 'ccpvdz',
  spin = 2
  )
  e_shci = mch(new_coord)

  uhf3 = scf.UHF(new_coord)
  uhf3.scf()  
  ump2 = mp.UMP2(uhf3)
  ump2.kernel()
  
  cpu0 = log.timer('2NP9 SHCI', *cpu0)
  
  with open('energies_singlet_close.dat', 'a') as f:
    f.write('%4.3f %8.7f %8.7f %8.7f %8.7f %8.7f \n' % (i,uhf3.e_tot,ump2.e_tot,e_shci[0],e_shci[1],e_shci[2]) )
    #f.write('%4.3f %8.7f %8.7f %8.7f\n' % (i,uhf3.e_tot,ump2.e_tot,e_shci) )


###REVERSO
  
# Initialize O2 molecule
b =  5.0
mol = gto.Mole()
mol.build(
verbose = 4,
output = 'scan_far.out',
atom = [
    ['O',(  0.000000,  0.000000, -b/2)],
    ['O',(  0.000000,  0.000000,  b/2)]],
basis = 'ccpvdz',
spin = 2
)

log = lib.logger.Logger(mol.stdout, 5)
cpu0 = time.clock(), time.time()
norb = 28 #ccpvdz
#norb = 92 # augccpvtz
#norb = 41 # anoroosdz
nelec = 16

uhf3 = scf.UHF(mol)
uhf3.scf()

ump2 = mp.UMP2(uhf3)

mch = mcscf.CASCI(uhf3, norb, nelec).as_scanner()
mch.fcisolver = shci.SHCI(mol)
mch.fcisolver.mpiprefix = 'mpirun -np 18'
mch.fcisolver.nroots = 1
mch.fcisolver.stochastic = True
mch.fcisolver.nPTiter = 100
mch.fcisolver.sweep_iter = [ 0, 3, 6 ]
#mch.fcisolver.sweep_iter = [ 0 ]
mch.fcisolver.DoRDM = True
#mch.fcisolver.sweep_epsilon = [ 1e-3 ]
mch.fcisolver.sweep_epsilon = [ 1e-3, 5e-4, 2e-4 ]
mch.fcisolver.epsilon2 = 1e-8
for i in [5.0,4.0,3.0,2.5,2.0,1.8,1.7,1.6,1.5,1.4,1.3,1.25,1.2,1.15,1.1,1.05,1.0,0.95,0.9]:
  new_coord = gto.Mole()
  new_coord.build(
  verbose = 0,
  atom = [
    ['O',(  0.000000,  0.000000, -i/2)],
    ['O',(  0.000000,  0.000000,  i/2)]],
  basis = 'ccpvdz',
  spin = 2
  )
  e_shci = mch(new_coord)

  uhf3 = scf.UHF(new_coord)
  uhf3.scf()  
  ump2 = mp.UMP2(uhf3)
  ump2.kernel()
  
  cpu0 = log.timer('2NP9 SHCI', *cpu0)
  
  with open('energies_triplet_far.dat', 'a') as f:
    #f.write('%4.3f %8.7f %8.7f %8.7f %8.7f \n' % (i,ump2.e_tot,e_shci[0],e_shci[1],e_shci[2]) )
    f.write('%4.3f %8.7f %8.7f %8.7f\n' % (i,uhf3.e_tot,ump2.e_tot,e_shci) )


# Initialize O2 molecule
b =  1.2
mol = gto.Mole()
mol.build(
verbose = 4,
output = 'scan_far.out',
atom = [
    ['O',(  0.000000,  0.000000, -b/2)],
    ['O',(  0.000000,  0.000000,  b/2)]],
basis = 'ccpvdz'
)

log = lib.logger.Logger(mol.stdout, 5)
cpu0 = time.clock(), time.time()
norb = 28 #ccpvdz
#norb = 92 # augccpvtz
#norb = 41 # anoroosdz
nelec = 16

uhf3 = scf.UHF(mol)
uhf3.scf()

ump2 = mp.UMP2(uhf3)

mch = mcscf.CASCI(uhf3, norb, nelec).as_scanner()
mch.fcisolver = shci.SHCI(mol)
mch.fcisolver.mpiprefix = 'mpirun -np 18'
mch.fcisolver.nroots = 3
mch.fcisolver.stochastic = True
mch.fcisolver.nPTiter = 100
mch.fcisolver.sweep_iter = [ 0, 3, 6 ]
#mch.fcisolver.sweep_iter = [ 0 ]
mch.fcisolver.DoRDM = True
#mch.fcisolver.sweep_epsilon = [ 1e-3 ]
mch.fcisolver.sweep_epsilon = [ 1e-3, 5e-4, 2e-4 ]
mch.fcisolver.epsilon2 = 1e-8
for i in [5.0,4.0,3.0,2.5,2.0,1.8,1.7,1.6,1.5,1.4,1.3,1.25,1.2,1.15,1.1,1.05,1.0,0.95,0.9]:
  new_coord = gto.Mole()
  new_coord.build(
  verbose = 0,
  atom = [
    ['O',(  0.000000,  0.000000, -i/2)],
    ['O',(  0.000000,  0.000000,  i/2)]],
  basis = 'ccpvdz',
  spin = 2
  )
  e_shci = mch(new_coord)

  uhf3 = scf.UHF(new_coord)
  uhf3.scf()  
  ump2 = mp.UMP2(uhf3)
  ump2.kernel()
  
  cpu0 = log.timer('2NP9 SHCI', *cpu0)
  
  with open('energies_singlet_far.dat', 'a') as f:
    f.write('%4.3f %8.7f %8.7f %8.7f %8.7f %8.7f \n' % (i,uhf3.e_tot,ump2.e_tot,e_shci[0],e_shci[1],e_shci[2]) )
    #f.write('%4.3f %8.7f %8.7f %8.7f\n' % (i,uhf3.e_tot,ump2.e_tot,e_shci) )


`

**Comment by jamesETsmith** [comment]
Hi @portega-usal, my guess is that this is coming from using $D_{2h}$ symmetry rather than $D_{\inf h}$ symmetry. This lower symmetry may be splitting those two states. Try the following:

```python
mc.fcisolver.useExtraSymm = True
```

See the source code for more details
https://github.com/pyscf/pyscf/blob/37fcb252a2259ddd41c96b6f104c3feb277ae73f/pyscf/shciscf/shci.py#L145-L147

You may also want to check that each of your Dice calculations are converged at the variational and PT stages at each step. Sometimes unsteadiness in dissociation curves like these can come from a few points in the curve not converging.

**Comment by portega-usal** [comment]
I added that option in the input, but the results are exactly the same. It is not really urgent, also, I think I obtained degenerate results for other calculations.

I will not spoil the issue anymore with partial results or hypothesis, I will try to find a solution and if I do, I will post it here.

**Comment by portega-usal** [comment]
I bring new results to test this issue. 

I am trying to follow an energy curve for the reaction H2+ (N+) --> (NH+) + H. I start with an hydrogen molecule, and I place the nitrogen cation at a long distance. This system has a triple degenerate triplet ground state, so I ask for three states in the multiconfigurational calculation. This is the result plot:

![Sin título](https://user-images.githubusercontent.com/57407499/69570814-ec405d00-0fc0-11ea-97a9-eb7d1b6f3d77.png)

The explanation for this process is, the nitrogen cation approaches the hydrogen molecule, and the minimum energy at the left is the reaction complex [NH2]+. Then, as this reaction is considered in astrochemical conditions, an hydrogen atom would be ejected from that minimum in dynamical conditions (non-equilibrium). Okay, these details are not relevant to the issue here.

The issue is that, as you can see, the programs seems to have some problems to identify the degenerate states on the right side, and it gives a triple-degenerate state only for some points. Most of the points jump to the next electronic state.

The input is this file:
https://codeshare.io/G8jmZA

I have tried with different basis sets and combinations of states but the results are mainly the same. 

Best regards

**Comment by xubwa** [comment]
Hey @portega-usal ,
I ran your input a bit and figured out a few potential problems.
1. The Hartree Fock reference might haven't converged, but this actually doesn't matter that much. To avoid this, you can do uhf=scf.newton(scf.UHF(new_coord)). FYI, I switched all the UHF in your input to RHF which will be by default converted to ROHF in pyscf, but this is only my personal preference.
2. I think when the atoms are far away, there are a few orbitals that become degenerate, and these orbitals don't interact very strong so that it is hard for SHCI to sample these configurations, the solution is to add these reference determinants manually. You can do 
`mch.fcisolver.dets = [[0,1,2,3,4,5,6,8],[0,1,2,3,4,5,6,10],[0,1,2,3,4,5,8,10]]`
From the calculation that I've done, it works well for i >= 3.0.
Best,
Xubo

**Comment by portega-usal** [comment]
@xubwa 

Could you send your input to me? I was not able to reproduce your calculation.

Thanks in advance

**Comment by xubwa** [comment]
@portega-usal 
I believe this is what I used as input.
[https://codeshare.io/24Ler8](https://codeshare.io/24Ler8)
I didn't use UHF as reference, I used ROHF instead, and didn't use the as_scanner function.

**Comment by verena-neufeld** [comment]
Dear @portega-usal , has this been resolved?

**Comment by verena-neufeld** [comment]
Thanks, @portega-usal, for posting this.
@portega-usal , @fishjojo , @sunqm , it seems that maybe this issue can be closed due to inactivity?
