### ISSUE TITLE
Localization saddle points of benzene in lo.Boys

### ISSUE THREAD

**Issue by 1234zou** [pyscf/pyscf#432]
I want to post two possible issues about the lo.Boys module.

The first issue is the Boys localized MOs of benzene at RHF/6-31G(d) contain three Pi C=C bonds (please see the attached file 
[ben_6-31Gd_loc_PySCF.zip](https://github.com/pyscf/pyscf/files/3819198/ben_6-31Gd_loc_PySCF.zip)
). This seems to be a saddle point of localization. To verify this, one can mix two orbitals 18 and 20 manually and then the target function value will further decrease. Moreover, one can repeat such simple mixing upon the other two Pi bonds.

The second issue is the difference between the following two ways of Boys localization:
(1) occ_loc_orb = lo.Boys(mol).kernel(mf.mo_coeff[:,occ_idx])
(2) occ_loc_orb = lo.Boys(mol, mf.mo_coeff[:,occ_idx]).kernel()
In (1) the kernel() will use exactly the input mf.mo_coeff as initial guess. However, in (2) the input mf.mo_coeff seems useless, and the localization procedure doesn't change (E.g. if I mix orbital 18 and 20, there is no change for the localization procedure). It seems that the localization code use PAO as initial guess, so any unitary rotation changes are useless.
This difference may make users confused.

Thanks anyone for making comments or offering suggestions.

**Comment by sunqm** [comment]
The input orbitals in (1) is used as initial guess. In (2) mf.mo_coeff[:,occ_idx] is used to define the space for localization only. The initial guess is controlled by the attribute .init_guess .
```
boys = lo.Boys(mol, mf.mo_coeff[:,occ_idx])
boys.init_guess = None
occ_loc_orb = boys.kernel()
```
should give exactly the same results as (1)

I added doc in boys localization code.
 https://github.com/pyscf/pyscf/blob/master/pyscf/lo/boys.py#L138

**Comment by 1234zou** [comment]
Thanks!
