### ISSUE TITLE
Transformed x2c dipole integrals

### ISSUE THREAD

**Issue by januseriksen** [pyscf/pyscf#437]
Hi all

Where/how can one access/compute transformed x2c dipole integrals in order to deal with the effect related to the picture change? As in Cheng & Gauss, JCP 135, 084114 (2011). I've noticed that analytical nuclear gradients have been implemented, but I'm too daft to locate the dipole integrals.

Cheers,
Janus

**Comment by sunqm** [comment]
PR #440 adds this functionality. dipole moment can be computed e.g. by
```
scf.RHF(mol).x2c().dip_moment()
```

More examples of picture change integrals can be found in https://github.com/pyscf/pyscf/blob/master/examples/x2c/10-picture_change.py

**Comment by januseriksen** [comment]
Cheers, Qiming, much appreciated. Will close.

/ Janus
