### ISSUE TITLE
Add Python 3.8 wheels to pypi

### ISSUE THREAD

**Issue by mtreinish** [pyscf/pyscf#438]
Python 3.8 was released on Oct 14, 2019  and many projects are starting to adopt it. It looks like the the python 3.8 trove classifier was added here in the 1.6.4 release. But there are no pyscf wheels built for python 3.8 hosted on pypi (probably because 1.6.4 was released prior to python 3.8). It would be good to upload python 3.8 wheels for the existing release or push the next release with python 3.8 wheels so that users running with python 3.8 do not need to build pyscf from source.

**Comment by sunqm** [comment]
One of the dependency h5py wheel is not available for python 3.8 on pypi. We will provide pyscf wheels when h5py wheel for python 3.8 is ready.

**Comment by h-larsson** [comment]
See https://github.com/h5py/h5py/issues/1410
