### ISSUE TITLE
Basis set inconsistency

### ISSUE THREAD

**Issue by ml-electron-project** [pyscf/pyscf#456]
Dear all,

We found the internal "6-311++G(3df,3pd)" basis show inconsistent value to one downloaded from the Basis Set Exchange.

(1)For example, when we set the basis by 
mol.basis="6-311+G(3df,3pd)"
and calculate Cl atom on PBE, the total energy is
-459.957818834042

(2)On the other hand, when we use the basis 6-311G++(3df,3pd) downloaded from Basis Set Exchange, 
-459.959248311567

When we conduct the same calculation on gaussian09, the total energy is -459.9592036.
So (2) seems to be correct.

The same problems occur to the atoms larger than Mg.
I am afraid that the internal basis file does not contain the basis for those atoms.

Best

**Comment by aikinogard** [comment]
`
from pyscf import dft
from pyscf import gto


def main():

  mol = gto.Mole()
  mol.verbose = 3

  mol.atom = '17'
  mol.charge = 0
  mol.spin = 1
  mol.basis = '6-311++G(3df,3pd)'
  mol.build()

  solver = dft.UKS(mol)
  solver.xc = 'pbe,pbe'
  
  solver.kernel()


if __name__ == '__main__':
  main()
`
This produced

> converged SCF energy = -459.957818834096  <S^2> = 0.75221594  2S+1 = 2.0022147

`
from pyscf import dft
from pyscf import gto


def main():

  mol = gto.Mole()
  mol.verbose = 3

  mol.atom = '17'
  mol.charge = 0
  mol.spin = 1
  mol.basis = open('6-311++g(3df,3pd).0.nw').read()
  mol.build()

  solver = dft.UKS(mol)
  solver.xc = 'pbe,pbe'
  
  solver.kernel()


if __name__ == '__main__':
  main()
`
> converged SCF energy = -459.95924831187  <S^2> = 0.75291807  2S+1 = 2.0029159

The basis function was downloaded from https://www.basissetexchange.org
[6-311++g(3df,3pd).0.nw.zip](https://github.com/pyscf/pyscf/files/3907998/6-311%2B%2Bg.3df.3pd.0.nw.zip)

**Comment by aikinogard** [comment]
I noticed that when we call `mol.basis = '6-311++G(3df,3pd)'`, https://github.com/pyscf/pyscf/blob/master/pyscf/gto/basis/pople-basis/6-311%2B%2BG.dat is used.

But for Cl, compared to `6-311++g(3df,3pd).0.nw`, it doesn't have D and F:

> Cl    D
>       3.0000                 1.000000
> Cl    D
>       0.7500                 1.000000
> Cl    D
>       0.1875                 1.000000
> Cl    F
>       0.7000000              1.0000000

Maybe we need a warning when desired basis set doesn't exist or shall we update the basis set files in pyscf?

**Comment by sunqm** [comment]
For 6-311++G(3df,3pd), the basis parser reads 3 files https://github.com/pyscf/pyscf/blob/master/pyscf/gto/basis/pople-basis/6-311%2B%2BG.dat
https://github.com/pyscf/pyscf/blob/master/pyscf/gto/basis/pople-basis/6-311G-polarization-3d.dat
https://github.com/pyscf/pyscf/blob/master/pyscf/gto/basis/pople-basis/6-311G-polarization-f.dat

The polarization-f functions for Na - Ar were missed.

Thanks for catching this issue. The basis data are updated in the latest commit

**Comment by aikinogard** [comment]
Thanks!
