### ISSUE TITLE
Cubegen make mistake when contain ECP

### ISSUE THREAD

**Issue by yangdatou** [pyscf/pyscf#457]
Dear developers,

The following code would build wrong cube file because of the ECP atom,
```
from pyscf import gto, scf
from pyscf.tools import cubegen

mol = gto.M(atom='''Ca 0.0000000, 0.000000, 0.00000000''',  basis='lanl2dz', ecp = 'lanl2dz')
mf = scf.RHF(mol).run()
# electron density
cubegen.density(mol, 'ca_den.cube', mf.make_rdm1())
```

This may be fixed by changing https://github.com/pyscf/pyscf/blob/04efa72e8f322133aff0628fd300a5b68509e300/pyscf/tools/cubegen.py#L258-L259
 to
```
    atmsym = mol.atom_symbol(ia)
    f.write('%5d%12.6f'% (pyscf.data.elements.charge(atmsym), 0.))
```

**Comment by sunqm** [comment]
Thanks for reporting the bug. Problem is fixed in the latest commit
