### ISSUE TITLE
MO integral with arbitrary functions 

### ISSUE THREAD

**Issue by MilaimKas** [pyscf/pyscf#458]
Dear all,

I would like to use the molecular orbitals (HF ones to begin with) for further calculations.
I am pretty new to pyscf but, as far as I understood, the mo_coeff can be extracted using myhf.mo_coeff. Then one can use the ao2mo module to calculate integrals in the AO basis set. 
I was wondering if it was also possible to evaluate an integral (simple overlap) with an arbitrary function, a plane wave type function for example.

Thank you for your help.

**Comment by xubwa** [comment]
Hey @MilaimKas ,
Usually, the ao integrals are computed first, then ao2mo is used to convert the ao integrals to mo integrals. And for doing arbitrary function, libcint which is the integral library that pyscf is using is a powerful engine and supports lots of integral, you can check whether the function you want is implemented. For examples of accessing libcint integrals via pyscf, you can visit https://github.com/pyscf/pyscf/blob/master/examples/gto/20-ao_integrals.py. Also in pyscf/gto/moleintor.py you can find which integrals are supported.

**Comment by MilaimKas** [comment]
Great! Thank you very much for your help !
