### ISSUE TITLE
TDDFT gives wrong symmetry representation

### ISSUE THREAD

**Issue by HansolP** [pyscf/pyscf#463]
I use pyscf 1.6.4v and find a trouble when using TDDFT with mol(symmtery=True)

The function analyze (@pyscf/tdscf/rhf.py) gives wrong symmetry representation for a given excitation.

It seems from 366th line in rhf.py
        x_sym = (orbsym[mo_occ==0,None] ^ orbsym[mo_occ==2]).ravel()
This code gives different order compared to "abs(x).argmax()" in 378th line rhf.py
So I think that
        x_sym = (orbsym[mo_occ==0,None] ^ orbsym[mo_occ==2]).T.ravel()
 is the right code for symmetry representation.

**Comment by sunqm** [comment]
Thanks for catching the bug. It's fixed in the latest update.


On Mon, Dec 09, 2019 at 11:09:24PM -0800, HansolP wrote:
> I use pyscf 1.6.4v and find a trouble when using TDDFT with mol(symmtery=True)
> 
> The function analyze (@pyscf/tdscf/rhf.py) gives wrong symmetry representation for a given excitation.
> 
> It seems from 366th line in rhf.py
>         x_sym = (orbsym[mo_occ==0,None] ^ orbsym[mo_occ==2]).ravel()
> This code gives different order compared to "abs(x).argmax()" in 378th line rhf.py
> So I think that
>         x_sym = (orbsym[mo_occ==0,None] ^ orbsym[mo_occ==2]).T.ravel()
>  is the right code for symmetry representation.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyscf/pyscf/issues/463

-- 
Dr. Qiming Sun
Principal Researcher, Tencent Quantum Laboratory
