### ISSUE TITLE
List does not have "/" error

### ISSUE THREAD

**Issue by btglau** [pyscf/pyscf#464]
https://github.com/pyscf/pyscf/blob/7b36f4654dedcf4502f8e0ce998d99ba5762f666/pyscf/pbc/df/aft.py#L319

Running, https://github.com/pyscf/pyscf/blob/master/examples/pbc/32-graphene.py, I get this error:

******** <class 'pyscf.pbc.df.aft.AFTDF'> ********
mesh = [30, 30, 40] (36000 PWs)
eta = 5.821445762846135
len(kpts) = 1
    kpts = [[0. 0. 0.]]
Traceback (most recent call last):
  File "./ceph/pyscf_16-10-2019_qcint-gcc/examples/pbc/32-graphene.py", line 54, in <module>
    e.append(mf.kernel())
  File "/mnt/home/blau/ceph/pyscf_16-10-2019_qcint-gcc/pyscf/lib/misc.py", line 586, in aliased_fn
    return getattr(self, fname)(*args, **kwargs)
  File "/mnt/home/blau/ceph/pyscf_16-10-2019_qcint-gcc/pyscf/scf/hf.py", line 1518, in scf
    self.build(self.mol)
  File "/mnt/home/blau/ceph/pyscf_16-10-2019_qcint-gcc/pyscf/pbc/scf/khf.py", line 481, in build
    self.check_sanity()
  File "/mnt/home/blau/ceph/pyscf_16-10-2019_qcint-gcc/pyscf/pbc/scf/khf.py", line 715, in check_sanity
    return KSCF.check_sanity(self)
  File "/mnt/home/blau/ceph/pyscf_16-10-2019_qcint-gcc/pyscf/pbc/scf/khf.py", line 466, in check_sanity
    self.with_df.check_sanity()
  File "/mnt/home/blau/ceph/pyscf_16-10-2019_qcint-gcc/pyscf/pbc/df/aft.py", line 318, in check_sanity
    if (cell.mesh[cell.dimension:]/(1.*meshz) > 1.1).any():
TypeError: unsupported operand type(s) for /: 'list' and 'float'

Which I fixed by changing

 if (cell.mesh[cell.dimension:]/(1.*meshz) > 1.1).any(): 

to

any([x/(1.*meshz) for x in cell.mesh[cell.dimension:]])

**Comment by sunqm** [comment]
Bryan, thanks for catching the bug. It's fixed in the latest update.

On Tue, Dec 10, 2019 at 07:22:22AM -0800, Bryan Lau wrote:
> https://github.com/pyscf/pyscf/blob/7b36f4654dedcf4502f8e0ce998d99ba5762f666/pyscf/pbc/df/aft.py#L319
> 
> Running, https://github.com/pyscf/pyscf/blob/master/examples/pbc/32-graphene.py, I get this error:
> 
> ******** <class 'pyscf.pbc.df.aft.AFTDF'> ********
> mesh = [30, 30, 40] (36000 PWs)
> eta = 5.821445762846135
> len(kpts) = 1
>     kpts = [[0. 0. 0.]]
> Traceback (most recent call last):
>   File "./ceph/pyscf_16-10-2019_qcint-gcc/examples/pbc/32-graphene.py", line 54, in <module>
>     e.append(mf.kernel())
>   File "/mnt/home/blau/ceph/pyscf_16-10-2019_qcint-gcc/pyscf/lib/misc.py", line 586, in aliased_fn
>     return getattr(self, fname)(*args, **kwargs)
>   File "/mnt/home/blau/ceph/pyscf_16-10-2019_qcint-gcc/pyscf/scf/hf.py", line 1518, in scf
>     self.build(self.mol)
>   File "/mnt/home/blau/ceph/pyscf_16-10-2019_qcint-gcc/pyscf/pbc/scf/khf.py", line 481, in build
>     self.check_sanity()
>   File "/mnt/home/blau/ceph/pyscf_16-10-2019_qcint-gcc/pyscf/pbc/scf/khf.py", line 715, in check_sanity
>     return KSCF.check_sanity(self)
>   File "/mnt/home/blau/ceph/pyscf_16-10-2019_qcint-gcc/pyscf/pbc/scf/khf.py", line 466, in check_sanity
>     self.with_df.check_sanity()
>   File "/mnt/home/blau/ceph/pyscf_16-10-2019_qcint-gcc/pyscf/pbc/df/aft.py", line 318, in check_sanity
>     if (cell.mesh[cell.dimension:]/(1.*meshz) > 1.1).any():
> TypeError: unsupported operand type(s) for /: 'list' and 'float'
> 
> Which I fixed by changing
> 
>  if (cell.mesh[cell.dimension:]/(1.*meshz) > 1.1).any(): 
> 
> to
> 
> any([x/(1.*meshz) for x in cell.mesh[cell.dimension:]])
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyscf/pyscf/issues/464

-- 
Dr. Qiming Sun
Principal Researcher, Tencent Quantum Laboratory
