### ISSUE TITLE
Accessing the density fitting coefficients of the auxiliary basis

### ISSUE THREAD

**Issue by manassharma07** [pyscf/pyscf#473]
I'm relatively new to PyScf. I've been reading the documentation extensively but haven't been able to figure out how to get the fitting coefficients of the auxiliary basis.
I ran a density fitting dft calculation but couldn't figure out how to get the fitted coefficients. I tried using mf.with_df.auxmol but couldn't find the relevant property.
I also couldn't figure out how to change or find out the metric used for density fitting.

**Comment by sunqm** [comment]
Density fitting coefficients were not computed in the code. The code to compute density fitting coefficients can be found in this example https://github.com/pyscf/pyscf/blob/master/examples/df/10-access_df_integrals.py

**Comment by manassharma07** [comment]
Thanks a lot!
That does the trick!

And I have to say, thank you for this amazing and easy to use library.
