### ISSUE TITLE
AFTDF and vcut_ws: error in krhf when casting complex to float

### ISSUE THREAD

**Issue by btglau** [pyscf/pyscf#474]
Hello,

I am running a NxNx1 calculation of graphene with the gth-pade pseudopotentials, AFTDF and vcut_ws, to test how it compares to GDF and ewald exxdiv. However, after the AFTDF finishes initializing, the krhf kernel terminates in the first step with this error. I have attached both the log and output file here.

*****************************************

Traceback (most recent call last):
  File "surf.py", line 165, in <module>
    mf.kernel()
  File "/mnt/home/blau/ceph/pyscf_16-10-2019_qcint-gcc/pyscf/lib/misc.py", line 586, in aliased_fn
    return getattr(self, fname)(*args, **kwargs)
  File "/mnt/home/blau/ceph/pyscf_16-10-2019_qcint-gcc/pyscf/scf/hf.py", line 1523, in scf
    conv_check=self.conv_check, **kwargs)
  File "/mnt/home/blau/ceph/pyscf_16-10-2019_qcint-gcc/pyscf/scf/hf.py", line 144, in kernel
    vhf = mf.get_veff(mol, dm)
  File "/mnt/home/blau/ceph/pyscf_16-10-2019_qcint-gcc/pyscf/pbc/scf/khf.py", line 565, in get_veff
    vj, vk = self.get_jk(cell, dm_kpts, hermi, kpts, kpts_band)
  File "/mnt/home/blau/ceph/pyscf_16-10-2019_qcint-gcc/pyscf/pbc/scf/khf.py", line 556, in get_jk
    exxdiv=self.exxdiv)
  File "/mnt/home/blau/ceph/pyscf_16-10-2019_qcint-gcc/pyscf/pbc/df/aft.py", line 462, in get_jk
    vk = aft_jk.get_k_kpts(self, dm, hermi, kpts, kpts_band, exxdiv)
  File "/mnt/home/blau/ceph/pyscf_16-10-2019_qcint-gcc/pyscf/pbc/df/aft_jk.py", line 208, in get_k_kpts
    make_kpt(kptj-kpti)
  File "/mnt/home/blau/ceph/pyscf_16-10-2019_qcint-gcc/pyscf/pbc/df/aft_jk.py", line 185, in make_kpt
    iLkR *= vkcoulG[p0:p1].reshape(1,nG,1)
TypeError: Cannot cast ufunc multiply output from dtype('complex128') to dtype('float64') with casting rule 'same_kind'

***********************

System: uname_result(system='Linux', node='worker1114', release='3.10.0-1062.9.1.el7.x86_64', version='#1 SMP Fri Dec 6 15:49:49 UTC 2019', machine='x86_64', processor='x86_64')  Threads 28
Python 3.7.3 (default, Jun 11 2019, 13:50:15)
[GCC 7.4.0]
numpy 1.16.4  scipy 1.3.0
Date: Thu Dec 26 22:16:20 2019
PySCF version 1.6.4
PySCF path  /mnt/home/blau/ceph/pyscf_16-10-2019_qcint-gcc/pyscf
GIT HEAD      ref: refs/heads/master
GIT master branch  a75bcf7966f0e9c0a30c188cc2a7f0bdf268b5e8

[ENV] PYSCF_MAX_MEMORY 512000
[ENV] PYSCF_TMPDIR /scratch
[CONFIG] conf_file None
[INPUT] verbose = 5
[INPUT] max_memory = 512000
[INPUT] num. atoms = 2
[INPUT] num. electrons = 8
[INPUT] charge = 0
[INPUT] spin (= nelec alpha-beta = 2S) = 0
[INPUT] symmetry False subgroup None
[INPUT] Mole.unit = angstrom
[INPUT]  1 C      0.000000000000   0.000000000000   0.000000000000 AA    0.000000000000   0.000000000000   0.000000000000 Bohr
[INPUT]  2 C      0.710140831103   1.230000000000   0.000000000000 AA    1.341971680656   2.324363133215   0.000000000000 Bohr
[INPUT] ---------------- BASIS SET ----------------
[INPUT] l, kappa, [nprim/nctr], expnt,             c_1 c_2 ...
[INPUT] C
[INPUT] 0    0    [4    /2   ]  4.3362376436      0.1490797872    0
                                1.2881838513      -0.0292640031    0
                                0.4037767149      -0.688204051    0
                                0.1187877657      -0.3964426906    1
[INPUT] 1    0    [4    /2   ]  4.3362376436      -0.0878123619    0
                                1.2881838513      -0.27755603    0
                                0.4037767149      -0.4712295093    0
                                0.1187877657      -0.4058039291    1

Ewald components = 0.132068034572349, -13.0453393072557, 57.044237761957
nuclear repulsion = 44.1309664892737
number of shells = 4
number of NR pGTOs = 32
number of NR cGTOs = 16
basis = gth-dzv
ecp = {}
CPU time:         7.47
lattice vectors  a1 [4.025915042, -2.324363133, 0.000000000]
                 a2 [4.025915042, 2.324363133, 0.000000000]
                 a3 [0.000000000, 0.000000000, 35.710648276]
dimension = 3
low_dim_ft_type = None
Cell volume = 668.338
rcut = 20.60710622719259 (nimgs = [6 6 1])
lattice sum = 363 cells
precision = 1e-08
pseudo = gth-pade
ke_cutoff = 257.0619664735998
    = [ 30  30 258] mesh (232200 PWs)
ew_eta = 0.705848
ew_cut = 9.301692117480476 (nimgs = [3 3 1])
28 threads
512000 memory assigned
/scratch scratch directory

******** <class 'pyscf.pbc.scf.khf.KRHF'> ********
method = KRHF-KSCF-RHF-SCF-RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-07
SCF conv_tol_grad = None
SCF max_cycles = 50
direct_scf = False
chkfile to save SCF result = /scratch/tmpf5epnaej
max_memory 512000 MB (current use 183 MB)

******** PBC SCF flags ********
N kpts = 9
kpts = [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 2.60114170e-01  4.50530959e-01  0.00000000e+00]
 [ 5.20228341e-01  9.01061918e-01  0.00000000e+00]
 [ 2.60114170e-01 -4.50530959e-01  0.00000000e+00]
 [ 5.20228341e-01  1.19979420e-17  0.00000000e+00]
 [ 7.80342511e-01  4.50530959e-01  0.00000000e+00]
 [ 5.20228341e-01 -9.01061918e-01  0.00000000e+00]
 [ 7.80342511e-01 -4.50530959e-01  0.00000000e+00]
 [ 1.04045668e+00  2.39958839e-17  0.00000000e+00]]
Exchange divergence treatment (exxdiv) = vcut_ws
DF object = <pyscf.pbc.df.aft.AFTDF object at 0x2aaac7610d68>

******** <class 'pyscf.pbc.df.aft.AFTDF'> ********
mesh = [ 30  30 258] (232200 PWs)
eta = 4.551202507206959
len(kpts) = 9
Set gradient conv threshold to 0.000316228
Big error detected in the electron number of initial guess density matrix (Ne/cell = 7.99978)!
  This can cause huge error in Fock matrix and lead to instability in SCF for low-dimensional systems.
  DM is normalized wrt the number of electrons 8.0
cond(S) = [5.40932176e+04 1.28162324e+06 1.28162324e+06 1.28162326e+06
 1.28162324e+06 2.54666127e+08 1.28162326e+06 2.54666129e+08
 1.28162324e+06]
Precomputing Wigner-Seitz EXX kernel
Nk = [3 3 1]
Lc = [12.07774513 12.07774513 35.71064828]
Rin = 6.0388725629526165
WS alpha = 0.827969119711863
kcell.mesh FFT = [120 120 352]
kcell kngs = 5068800
Finished precomputing

**Comment by sunqm** [comment]
It has been fixed in c003b9d
