### ISSUE TITLE
Use libxc's parsing routines instead of hardcoded lists

### ISSUE THREAD

**Issue by susilehtola** [pyscf/pyscf#48]
Hi,

I just had a look at https://github.com/sunqm/pyscf/blob/master/dft/libxc.py and noticed that you're using hardcoded functional lists.

However, libxc has had the functionality to parse functional keywords and id numbers for a long time: 
int   XC(functional_get_number)(const char *name);
char *XC(functional_get_name)(int number);

which implement the necessary functionality. I would recommend removing XC_CODES, XC_KEYS, LDA_IDS, GGA_IDS, etc from dft/libxc.py, and replacing them with the two above functionals.

The functions is_lda, is_gga and so on can be reimplemented by checking the functional family with 
  int   XC(family_from_id)(int id, int *family, int *number);
or by checking the func.info->family entry of 
  xc_func_type func;
that has been initialized to the used functional. The character of the functional (x, c, or xc) can be similarly checked from func.info->kind.

It doesn't really make sense to replicate this information, since that entails more maintenance. The stuff is already maintained within libxc, where it is always up to date.

Also, I don't see how you handle range separated hybrids. Are they not supported in pyscf?

**Comment by sunqm** [comment]
The functional list XC_CODES is hardcoded because it is designed to be hardcoded.   When you run in python shell, it's straightforward to check what has been supported by typing

>>> from pyscf import dft
>>> dft.lib<tab>.X<tab>_C<tab><enter>    # dft.libxc.XC_CODES
>>> dft.xcf<tab>.X<tab><enter>                 # dft.xcfun.XC_CODES

I don't see any other way more simple and consistent to do this in python shell.

What  is_lda, is_gga functions did is more than a single check for one functional ID, it is a part of the parser function parse_xc,  which allows you customizing functionals like ".218*HF + .073*LDA + .709*MPW91, .871*LYP + .129*VWN".  I don't know whether libxc has this feature in recent version.  But I'm sure it's not when I implemented the libxc.py interface.  They have to be there until I found better solution.

I agree LDA_IDS, GGA_IDS is duplication of XC(family_from_id) function.  I can reimplement it in the future when I optimize the DFT code.

Range separated hybrids are not coded in the dft module.  The required integrals should be all available.  Let me know if you need this functionality.  I can show you where to access the integrals or I can implement it in next release.

Qiming

**Comment by susilehtola** [comment]
So, this is already half-solved by #120, the only remaining issue is the handling of the functional list, i.e. the same issue as in Psi4 (psi4/psi4#793)

This could also be constructed by polling libxc which functionals are available. Maybe the easiest thing would be to add in a libxc function that dumps out a list of valid functional ids and keywords.

**Comment by theavey** [comment]
> Range separated hybrids are not coded in the dft module.

If range separated functionals don't work properly, an error or warning should be raised when they are called.

Also, I'm not sure if this is just unclear to me or generally unclear, but when using a XC functional, does it need to be listed twice and comma separated? Listing it twice gives a different energy.

    x_and_c = 'XC_LDA_XC_ZLP, XC_LDA_XC_ZLP'
    x_or_c = 'XC_LDA_XC_ZLP'
    mol = pyscf.gto.M(atom='H 0 0 0; H 0 0 1.2', basis='ccpvdz', symmetry=True)
    m_rks = dft.rks.RKS(mol)

    m_rks.xc = x_and_c
    m_rks.kernel()

    m_rks.xc = x_or_c
    m_rks.kernel()


> converged SCF energy = -1.74990822400141
> converged SCF energy = -1.10688299662763

**Comment by sunqm** [comment]
In the 1.4.* release,  there is no code to check whether an XC functional is range-separated functional.  So there is no way to assert the input.  Range separated functionals and relevant code are implemented in dev branch.  For example
https://github.com/sunqm/pyscf/blob/dev/examples/dft/33-nlc_functionals.py#L16

Depending on the type of functional, the input x_and_c  x_or_c are both supported.
When you input 'x,c', means x_and_c, where the first part (before comma) is X functional and the second part is C functional,  like  'LDA,VWN',  'LDA,P86', '0.5*HF+0.5*LDA,LYP'
When you input 'xc' without comma, it will treat the XC functional as X functional only. But some of the XC functional include both X and C like 'B3LYP'.  So you just need to input xc='b3lyp'.

Note the xc input parser does not prevent you input meaningless XC functional. For example, it allows you to specify xc='b3lyp,0.5*p86' which means b3lyp plus a few p86 C functional. If you input xc='b3lyp,b3lyp', it will compute the b3lyp twice.

**Comment by susilehtola** [comment]
This issue could probably be solved now much easier than before, since thanks to the Psi4 developers, libxc now has a working Python interface as shown in
https://gitlab.com/libxc/libxc/tree/master/pylibxc

**Comment by susilehtola** [comment]
The Python interface was included in libxc 4.1.0, but you can just update to the latest 4.3.4 release.

**Comment by susilehtola** [comment]
libxc 5 is out, including up to 4th derivatives for all functionals, meta-GGAs included.

**Comment by verena-neufeld** [comment]
Hi @susilehtola , has this been resolved?

**Comment by sunqm** [comment]
Using PR #2377, the XC list are now dynamically generated via the libxc library.
