### ISSUE TITLE
Tune DIIS example doesn't set diis_space

### ISSUE THREAD

**Issue by jamesETsmith** [pyscf/pyscf#493]
Hi All, I recently noticed that the example for tunning diis doesn't actually set the diis space size for the ADIIS class.

https://github.com/pyscf/pyscf/blob/1b6db6e6043fdcdd47b69d4e28d92c40efaec9d3/examples/scf/24-tune_diis.py#L32-L35

In line 34 above, the attribute should be set like `my_diis_obj.space = 12`. As written the diis space will default to 6. Is there a reason that the attribute for derived DIIS objects, like ADIIS, is named differently than for DIIS objects (where it's named `diis_space`)?

**Comment by jamesETsmith** [comment]
Hi, I don't think this should be closed. I think that we should change the `space` attribute of ADIIS (and other derived DIIS objects) to `diis_space` so they are consistent with the base DIIS object. I'm happy to make the changes, but before I do let me know if you agree or disagree.

**Comment by sunqm** [comment]
The attribute diis_space was used in the SCF class. The base DIIS class uses the name "space" https://github.com/pyscf/pyscf/blob/master/pyscf/lib/diis.py#L111 . I think that PR fixed the naming inconsistency. I updated the example in recent commits. Hope the change makes the DIIS example more clearly.

**Comment by jamesETsmith** [comment]
Oh I see, thanks @sunqm for clearing that up!
