### ISSUE TITLE
Nonadiabatic Couplings

### ISSUE THREAD

**Issue by arkajitmandal** [pyscf/pyscf#496]
Hi !
Is nonadiabatic couplings available ? If not it would be great to have them.

**Comment by gkc1000** [comment]
Currently under development.

**Comment by matthew-hennefarth** [comment]
SA-CASSCF NACs are currently available! Take a look at [`examples/nac/01-sacasscf_nac.py`](https://github.com/pyscf/pyscf/blob/master/examples/nac/01-sacasscf_nac.py).

**Comment by arkajitmandal** [comment]
Cool!!! 

Thanks a lot :)
