### ISSUE TITLE
dmrg-nevpt2 calculation not run

### ISSUE THREAD

**Issue by lqhenwunai** [pyscf/pyscf#499]
Dear all,

I am trying to run some dmrg-nevpt2 calculations. However, the nevpt2 does not run. The following is my input, I am not sure which part is wrong. Many thanks for your help.

mol.max_memory=10000
mol.charge=0
mol.spin=18  #molpro convention
mol.verbose=4
mol.symmetry='D2h'
mol.build()

hf=scf.RHF(mol).x2c()

hf.conv_tol=1e-6
hf.max_cycle=150
hf.level_shift=0.5
hf.diis_space=15
hf.irrep_nelec={'Ag':(17,14),'B3u':(9,6),'B2u':(9,6),'B1g':(3,2),'B1u':(16,13),'B2g':(8,6),'B3g':(8,6),'Au':(3,2)}
hf.kernel()

\#(hf, orb ele)
mycas=dmrgscf.DMRGSCF(hf,26,20)
mycas.frozen = 10
mycas.kernel()
#mycas.analyze()

mrpt.NEVPT(mycas).kernel()
\#mps_nevpt_e1 = mrpt.NEVPT(mycas).compress_approx(maxM=100).kernel()

and the end of output is:

macro iter 1 (21 JK  4 micro), CASSCF E = -22535.2751255222  dE = -0.024548862  S^2 = 90.0000000
               |grad[o]|=0.103  |grad[c]|= None  |ddm|=0.193
macro iter 2 (21 JK  4 micro), CASSCF E = -22535.2861976856  dE = -0.011072163  S^2 = 90.0000000
               |grad[o]|=0.0605  |grad[c]|= None  |ddm|=0.0829
macro iter 3 (21 JK  4 micro), CASSCF E = -22535.2914319729  dE = -0.0052342873  S^2 = 90.0000000
               |grad[o]|=0.0226  |grad[c]|= None  |ddm|=0.0522
macro iter 4 (20 JK  4 micro), CASSCF E = -22535.2953770112  dE = -0.0039450383  S^2 = 90.0000000
               |grad[o]|=0.00958  |grad[c]|= None  |ddm|=0.0396
macro iter 5 (13 JK  4 micro), CASSCF E = -22535.2955474676  dE = -0.00017045641  S^2 = 90.0000000
               |grad[o]|=0.00268  |grad[c]|= None  |ddm|=0.0126
macro iter 6 (9 JK  2 micro), CASSCF E = -22535.2955480554  dE = -5.8775913e-07  S^2 = 90.0000000
               |grad[o]|=0.000225  |grad[c]|= None  |ddm|=0.000964
macro iter 7 (6 JK  1 micro), CASSCF E = -22535.2955480863  dE = -3.0973752e-08  S^2 = 90.0000000
               |grad[o]|=6.09e-05  |grad[c]|= None  |ddm|=0.000173
1-step CASSCF converged in 7 macro (111 JK 23 micro) steps
CASSCF canonicalization
Density matrix diagonal elements [1.70479134 0.99850423 0.99850426 0.97200396 0.99996513 0.99996513
 0.99998595 0.99998595 0.99987663 0.99994253 0.99975008 0.9996039
 0.99977248 0.99977248 0.99972122 1.00318133 0.96530801 0.96530807
 0.16771685 0.03755914 0.03755917 0.09333411 0.03178561 0.03178547
 0.01444192 0.97987507]
CASSCF energy = -22535.2955480863
CASCI E = -22535.2955480863  E(CI) = -92.6048323106697  S^2 = 90.0000000

**Comment by jamesETsmith** [comment]
@lqhenwunai have you tried increasing the verbosity to 5? That might give you some helpful information. Could you also post a complete input so we can try to reproduce the error?

**Comment by lqhenwunai** [comment]
@jamesETsmith Thanks for your reply. 
Changing verbose to 5 seems not very helpful, though. The input file is as follows:

import os
import numpy as np
#import pyscf
from pyscf import gto, scf,symm,tools, mcscf,dmrgscf
from pyscf.gto.basis import parse_molpro
from pyscf.x2c import x2c
from pyscf import mrpt
from pyscf.dmrgscf import DMRGSCF


mol=gto.Mole()
#unit in angstrom
mol.atom='''Gd 0 0 1.428786
          Gd 0 0 -1.428786'''

input_name  = __file__
filename    = input_name[:-3]
output_name = filename+'.out'
mol.output=output_name

dirnow = os.path.realpath(os.path.join(__file__, '/public1/home/sc40147/projects/LaBasis/NWCHEM-format'))
basis_file_from_user = os.path.join(dirnow, 'cc-pvdz-x2c.dat')
mol.basis={'Gd':basis_file_from_user}



mol.max_memory=10000
mol.charge=0
mol.spin=18  #molpro convention
mol.verbose=5
mol.symmetry='D2h'
mol.build()

hf=scf.RHF(mol).x2c()
# Ag B3u B2u B1g B1u B2g B3g Au
#occ,17,9,9,3,16,8,8,3;closed,14,6,6,2,13,6,6,2;wf,128,4,18
hf.conv_tol=1e-6
hf.max_cycle=150
hf.level_shift=0.5
hf.diis_space=15
hf.irrep_nelec={'Ag':(17,14),'B3u':(9,6),'B2u':(9,6),'B1g':(3,2),'B1u':(16,13),'B2g':(8,6),'B3g':(8,6),'Au':(3,2)}
hf.kernel()

\#(hf, orb ele)
mycas=dmrgscf.DMRGSCF(hf,26,20)
mycas.frozen = 10
mycas.kernel()
\#mycas.analyze()


mrpt.NEVPT(mycas).kernel()

**Comment by jamesETsmith** [comment]
@lqhenwunai are there any error messages in your std error output? If you submitted this job to a cluster you might have a slurm output file. Have you been able to successfully run any NEVPT2 calculations?

**Comment by lqhenwunai** [comment]
@jamesETsmith 
 I got the following error in slurm output. 
 mrpt.NEVPT(mycas).kernel()
  File "/public1/home/sc40147/pyscf/pyscf/mrpt/nevpt2.py", line 683, in kernel
    raise NotImplementedError
NotImplementedError

But I can run the example input of /pyscf/examples/mrpt/02-cr2_nevpt2/cr2-scan.py. The cr2-1.5.out gives:
Nevpt2 Energy = -1.004139752832840
    CPU time for SC-NEVPT2   3407.87 sec, wall time    127.18 sec

**Comment by xubwa** [comment]
If you go to that line mentioned in the error information, you will find it is due to nevpt2 doesn't have fronzen core supported. Are you doing a frozen core casscf calculation before doing nevpt2? You might be able to fix that by removing the frozen core approximation.

**Comment by lqhenwunai** [comment]
@xubwa 
Thanks for your help. Yes, the frozen-core seems to be the error source. However, when I turn off the frozen core approximation, I got the following slurm error message:

ERROR: srun /public1/home/sc40147/block/mpi-block-1.5.3/block.spin_adapted dmrg.conf > dmrg.out 2>&1
overwrite output file: Gd2vdz.out
......production of RDMs took    3182.53 sec
......reading the RDM took        136.71 sec
Traceback (most recent call last):
  File "Gd2vdz.py", line 51, in <module>
    mrpt.NEVPT(mycas).kernel()
  File "/public1/home/sc40147/pyscf/pyscf/mrpt/nevpt2.py", line 751, in kernel
    norm_Sr   , e_Sr    = Sr(self, self.load_ci(), dms, eris)
  File "/public1/home/sc40147/pyscf/pyscf/mrpt/nevpt2.py", line 313, in Sr
    a16 = mc.fcisolver.nevpt_intermediate('A16',ncas,mc.nelecas,ci)
  File "/public1/home/sc40147/pyscf/pyscf/dmrgscf/dmrgci.py", line 679, in nevpt_intermediate
    executeBLOCK(self)
  File "/public1/home/sc40147/pyscf/pyscf/dmrgscf/dmrgci.py", line 930, in executeBLOCK
    raise err
subprocess.CalledProcessError: Command 'srun /public1/home/sc40147/block/mpi-block-1.5.3/block.spin_adapted dmrg.conf > dmrg.out 2>&1' returned non-zero exit status 134
srun: error: c7301: task 0: Exited with exit code 1

and the output shows that:
DMRG-NEVPT
    CPU time for 3pdm, 4pdm    158.46 sec, wall time   3334.12 sec
    CPU time for integral transformation     62.62 sec, wall time      3.24 sec
    CPU time for eri-4pdm contraction      0.00 sec, wall time      0.00 sec

ERROR: srun /public1/home/sc40147/block/mpi-block-1.5.3/block.spin_adapted dmrg.conf > dmrg.out 2>&1

Block  Copyright (C) 2012  Garnet K.-L. Chan
This program comes with ABSOLUTELY NO WARRANTY; for details see license file.
This is free software, and you are welcome to redistribute it
under certain conditions; see license file for details.
Reading input file
m_hf_occ_user integral
/tmp/24109
================
The Fiedler routine for finding the orbital ordering has already been run.
Using the reorder file /tmp/24109/node0//RestartReorder.dat
================
7 8 6 5 11 10 12 9 4 15 14 13 2 3 19 17 18 24 23 26 25 21 20 1 22 16

open orbs   :
closed orbs :
Initial HF occupancy guess: 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
Checking input for errors
Summary of input
----------------
Total number of orbitals                           :   26
Symmetry of the targeted wavefunctions             :   20:18:1
Number of wavefunctions targeted                   :   1
Symmetry of the molecule                           :   d2h
Irreducible representations of the orbitals        :   B2g  B3g  B3u  B2u  Au  B1g  B1u  Ag  Ag  B1u  B3g  B2g  B2u  B3u  Ag  B2u  B3u  B3g  B2g  B1g  Ag  B3u  B2u  Ag  Ag  B1u

Schedule
--------
Iter       : # States              Davidson_tol          Random_noise        
0          : 1000                  1.000000e-10          0.000000e+00
Maximum sweep iterations                           :   38

allocating 250000000 doubles
**** STACK MEMORY REMAINING ***** 2.000000000000 GB
Invalid calculation types
srun: error: c7301: task 0: Aborted

**Comment by jamesETsmith** [comment]
@lqhenwunai, are you sure that your machine has enough memory to handle the job you're trying to run? Can you test running on a node with more memory?

Another possibility could be that you're using x2c and I'm not sure if x2c + NEVPT2 is supported yet. Maybe try running without it.

**Comment by lqhenwunai** [comment]
@jamesETsmith Thanks for your reply. Yes I have 256Gb memory in total and I asked for 20 cores for my calculation with max_memory=10000. I will give it more memory, but it will take for quite a few hours. 

For the other question, I have modified the /pyscf/examples/mrpt/02-cr2_nevpt2/cr2-scan.py input to include the x2c hamiltonian. The calculation runs smoothly. 
Nevpt2 Energy = -1.002358495310894
    CPU time for SC-NEVPT2   3522.94 sec, wall time    130.83 sec

And if I understand correctly, once the the integrals have been decorated by x2c, the integrals should be fine to use by any methods, since methods like nevpt2 only deal with density matrices. Please correct me if I am wrong. 

Thanks again for your time.

Best,

**Comment by xubwa** [comment]
@lqhenwunai I think it would be fine to decorate methods by sfx2c and it doesn't change anything except the integral will be scalar relativistic, but I read your input, it is scf.RHF().x2c(), this is gonna decorate the method to a two component hf reference, this might not be able to work, you might need to do mf = scf.sfx2c1e(scf.RHF()) to get a scalar relativistic Hartree-Fock reference.

**Comment by lqhenwunai** [comment]
@xubwa Many thanks for your suggestion. But

I have also performed the x2c-nevpt2 calculation for the Cr2 calculation as mentioned some time earlier:
-----------------------------------
"For the other question, I have modified the /pyscf/examples/mrpt/02-cr2_nevpt2/cr2-scan.py input to include the x2c hamiltonian. The calculation runs smoothly.
Nevpt2 Energy = -1.002358495310894
CPU time for SC-NEVPT2 3522.94 sec, wall time 130.83 sec"
-------------------------------------
And I turn on the x2c by m = scf.RHF(mol).x2c(), in the same way as I did for the other case. 

Lastly,
1) The previous hf=scf.RHF(mol).x2c() calculation and the suggested hf = scf.sfx2c1e(scf.RHF(mol)) calculation give identical HF energy:
Gd2vdz.out:converged SCF energy = -22535.2698969315
Gd2vdz-x2c1e.out:converged SCF energy = -22535.2698969315

2) and in the /pyscf/examples/x2c/01-spin_free_x2c.py, it says:
"x2c1e is the same to the .x2c method in the current implementation

so I feel the x2c is capable to be run with nevpt2.

Thank you very  much.

**Comment by lqhenwunai** [comment]
I increased the memory to 20000, and got the same error.

**Comment by jamesETsmith** [comment]
Hm @lqhenwunai, that's good that `x2c()` works with the cr2 example thanks for trying that! I just looked closer at `pyscf/examples/dmrg` and there are several examples there showing `x2c()` + NEVPT2, sorry for not looking more carefully earlier. 

Two things about your memory tests, first, setting `max_memory=20000` only lets PySCF use 20GB of memory, which in my experience is pretty small. 

Second, from the errors you posted earlier, it looks like you are running out of memory during the block calculation so upping the memory in PySCF probably won't help alleviate any memory bottlenecks. There might be some tricks you can play with Block to increase the memory, but I think you need a node with more memory than 256 GB.

Here are some comments from a Cr2 example that say you need about 200GB and since your system is larger you probably need more.

https://github.com/pyscf/pyscf/blob/f5b7e8fff019c716b4b4ea9f20c91bb1694b8f5d/examples/dmrg/30-dmrg_casscf_nevpt2_for_Cr2.py#L8-L10

**Comment by lqhenwunai** [comment]
Dear @jamesETsmith 
Many thanks for your help. 

One last question, does "max_memory" control the total memory or the the memory allocated for each processor? 

And I wonder how much memory was given for the Nature Chem paper? 
"Electronic landscape of the P-cluster of nitrogenase as revealed through many-electron quantum wavefunction simulations"

**Comment by gkc1000** [comment]
When using MPI, Block uses distributed memory, so if you have many nodes,
the memory available to Block will scale with the number of nodes. I don't
know the precise amount of memory used for the P-cluster calculation, but
I'm guessing the largest calculation used a few Tb.

To enable the Cr2 calculation to run you can use a smaller M (e.g. 500).
Note that running DMRGSCF is quite expensive as many DMRG calculations have
to be completed; usually one can get the orbitals from a cheap DMRGSCF
(with small M) and then run a final DMRGCI (with large M). The input script
corresponds to the production runs used for the 2016 paper by Guo et al on
the Cr2 dimer and thus are probably not the best "small" case to run.

**Comment by lqhenwunai** [comment]
@gkc1000 
Many thanks. But I do not know much of parallel calculations. So I have to ask out IT engineers to help build the pyscf and block. However, we got some multi-node parallel issues and we need some help on it. 

First of all, we use slurm to manage the jobs. Part of our slurm script is:

\#SBATCH -N 1
\#SBATCH -n 1
\#SBATCH -c nthread

We have to use multi-thread to run the calculation parallelly. Setting up SBATCH -n 8 (for example) does not have pyscf/block function normally. 

Is that normal?

Secondly, we tried to run multi-node calculations. We write the script as:
\#SBATCH -N 4
\#SBATCH -n 4
\#SBATCH -c nthread

but it shows error messages indicating the multi-process run is failed. 

So does pyscf/block multi-process parallization? If so, how do we set up?

I don't know much of parallel calculations. Please tolerate my questions. 

Many thanks.

**Comment by sanshar** [comment]
Block should recognize the number of threads by the value of your
environment variable OMP_NUM_THREADS. You don't need to do anything special
in your batch file for number of threads. Batch file should just specify
the number of processors.
  Just make sure that numthreads x numprocs is equal to the number of
physical cores otherwise it can be inefficient.
  After the job is running, you should be able to use the "top" command to
see what cpu percentage each of the processors is using, this should be
roughly numthreads x 100.

Sandeep.

**Comment by lqhenwunai** [comment]
Dear @sanshar 
Thanks for your reply. But I did another 2 tests:

1)
I ran the /pyscf/examples/dmrg/01-dmrg_casscf_with_block.py, and the calculation finished normally. 
But when I add the sentence at the end of input:
mrpt.NEVPT(mc).kernel()

the calculation returns:
**** STACK MEMORY REMAINING ***** 2.000000000000 GB
you are running 10
Invalid calculation types
allocating 250000000 doubles
allocating 250000000 doubles
allocating 250000000 doubles
allocating 250000000 doubles
allocating 250000000 doubles
allocating 250000000 doubles
allocating 250000000 doubles
allocating 250000000 doubles
allocating 250000000 doubles
allocating 250000000 doubles
allocating 250000000 doubles
allocating 250000000 doubles
srun: error: c7403: tasks 0-19: Aborted
Traceback (most recent call last):
  File "dmrg_casscf_with_block.py", line 43, in <module>
    mrpt.NEVPT(mc).kernel()
  File "/public1/home/sc40147/pyscf/pyscf/mrpt/nevpt2.py", line 751, in kernel
    norm_Sr   , e_Sr    = Sr(self, self.load_ci(), dms, eris)
  File "/public1/home/sc40147/pyscf/pyscf/mrpt/nevpt2.py", line 313, in Sr
    a16 = mc.fcisolver.nevpt_intermediate('A16',ncas,mc.nelecas,ci)
  File "/public1/home/sc40147/pyscf/pyscf/dmrgscf/dmrgci.py", line 679, in nevpt_intermediate
    executeBLOCK(self)
  File "/public1/home/sc40147/pyscf/pyscf/dmrgscf/dmrgci.py", line 930, in executeBLOCK
    raise err
subprocess.CalledProcessError: Command 'srun /public1/home/sc40147/block/mpi-block-1.5.3/block.spin_adapted dmrg.conf > dmrg.out 2>&1' returned non-zero exit status 134

It is only N2 with vdz sets and a (8,8) active space. So I think the memory shouldn't be a problem.

2)And then I ran ~/pyscf/examples/dmrg/02-dmrg_nevpt2.py, I got the following error message:

  File "/public1/home/sc40147/pyscf/pyscf/dmrgscf/nevpt_mpi.py", line 431, in _write_integral_file
    nevpt_integral_mpi(sys.argv[1],sys.argv[2],sys.argv[3],sys.argv[4])
  File "/public1/home/sc40147/pyscf/pyscf/dmrgscf/nevpt_mpi.py", line 286, in nevpt_integral_mpi
    ncas, partial_core, partial_virt = _write_integral_file(mc_chkfile, nevpt_scratch, comm)
    raise RuntimeError('No job for this processor.  It may block MPI.COMM_WORLD.barrier')
    raise RuntimeError('No job for this processor.  It may block MPI.COMM_WORLD.barrier')
    raise RuntimeError('No job for this processor.  It may block MPI.COMM_WORLD.barrier')
  File "/public1/home/sc40147/pyscf/pyscf/dmrgscf/nevpt_mpi.py", line 431, in _write_integral_file
RuntimeError: No job for this processor.  It may block MPI.COMM_WORLD.barrier
RuntimeError: No job for this processor.  It may block MPI.COMM_WORLD.barrier
RuntimeError: No job for this processor.  It may block MPI.COMM_WORLD.barrier
    raise RuntimeError('No job for this processor.  It may block MPI.COMM_WORLD.barrier')
RuntimeError: No job for this processor.  It may block MPI.COMM_WORLD.barrier
srun: error: c7202: tasks 0-19: Exited with exit code 1
ERROR: srun /public1/home/sc40147/pyscf/pyscf/dmrgscf/nevpt_mpi.py /public1/home/sc40147/projects/Ln2/pyscf/casscf/cr2/test2/dmrg_nevpt2/mytest/scratch/1212/nevpt_perturb_integral /public1/home/sc40147/block/block-1.5.3/block.spin_adapted /public1/home/sc40147/projects/Ln2/pyscf/casscf/cr2/test2/dmrg_nevpt2/mytest/scratch/1212 /public1/home/sc40147/projects/Ln2/pyscf/casscf/cr2/test2/dmrg_nevpt2/mytest/scratch/1212
overwrite output file: fci_nevpt2.out
CI NEVPT = 0 0
overwrite output file: dmrg_nevpt2_slow.out
......production of RDMs took      91.06 sec
......reading the RDM took          0.01 sec
Traceback (most recent call last):
  File "dmrg_nevpt2.py", line 132, in <module>
    mps_nevpt_e1 = mrpt.NEVPT(mc,root=0).compress_approx(maxM=100).kernel()
  File "/public1/home/sc40147/pyscf/pyscf/mrpt/nevpt2.py", line 737, in kernel
    tol=self.tol)
  File "/public1/home/sc40147/pyscf/pyscf/dmrgscf/nevpt_mpi.py", line 254, in DMRG_COMPRESS_NEVPT
    raise err
subprocess.CalledProcessError: Command 'srun /public1/home/sc40147/pyscf/pyscf/dmrgscf/nevpt_mpi.py /public1/home/sc40147/projects/Ln2/pyscf/casscf/cr2/test2/dmrg_nevpt2/mytest/scratch/1212/nevpt_perturb_integral /public1/home/sc40147/block/block-1.5.3/block.spin_adapted /public1/home/sc40147/projects/Ln2/pyscf/casscf/cr2/test2/dmrg_nevpt2/mytest/scratch/1212 /public1/home/sc40147/projects/Ln2/pyscf/casscf/cr2/test2/dmrg_nevpt2/mytest/scratch/1212' returned non-zero exit status 1


Are those example inputs able to be run on your nodes?

Many thanks.

**Comment by verena-neufeld** [comment]
Hi @lqhenwunai , thanks for your question! Since it has been a while, I was wondering whether your question has been resolved since then?

**Comment by lqhenwunai** [comment]
Hi @verena-neufeld, Thanks for the reminder. The problem was not resolved, but I did not give more attempts on it since then. You may close the topic if necessary. 

Thanks again to everyone who offered the help.
