### ISSUE TITLE
vv10 being extremely slow

### ISSUE THREAD

**Issue by hongzhouye** [pyscf/pyscf#511]
Hi PySCF developers,

I found that PySCF's DFT module runs extremely slow when the non-local functional VV10 is used. The following example shows this issue:

```Python
from pyscf import gto, dft
import time

mol = gto.M(atom="O 0 0 0; H 0 0 1; H 0 1 0", basis="cc-pvdz")
ks = dft.RKS(mol)

t0 = time.time()
ks.xc = "wb97x"  # w/o nlc
ks.kernel()
t1 = time.time()
print("t (wb97x)   : %.6f" % (t1-t0))

t0 = time.time()
ks.xc = "wb97x-v" # w/ nlc
ks.nlc = "vv10"
ks.kernel()
t1 = time.time()
print("t (wb97x-v) : %.6f" % (t1-t0))
```

On my local machine (Macbook Pro, early 2015, 3.1 GHz Intel Core i7, 8 GB 1867 MHz DDR3), the output is something like
```
converged SCF energy = -76.394588798518
t (wb97x)   : 2.136731
converged SCF energy = -76.3863427184999
t (wb97x-v) : 205.826581
```
which is much slower compared to other packages. E.g., in Q-Chem the two times are `7.45 s (wb97x)` vs `12.05 s (wb97x-v)` (measured on a different Linux machine; but the small difference should make my point clear).

I verified that *>99%* of the time is spent in this block of the `get_veff` function in `pyscf/dft/rks.py`:
```Python
if ks.nlc != '':
            assert('VV10' in ks.nlc.upper())
            _, enlc, vnlc = ni.nr_rks(mol, ks.nlcgrids, ks.xc+'__'+ks.nlc, dm,
                                      max_memory=max_memory)
            exc += enlc
            vxc += vnlc
```

I could dig into the code more, but just wanted to make sure it is not an issue of my installation...

Thanks!

**Comment by gkc1000** [comment]
Hi - can you first check which grid is being used in Q-Chem vs. PySCF (i.e.
check the #grid points). VV10 involves a double grid integration, so
differences in grid size can make an enormous difference in time.

**Comment by hongzhouye** [comment]
@gkc1000 thanks for your quick response!
Following your suggestion, I checked the grids used by both. Q-Chem used 75302 for the regular part and SG-1 for VV10, while PySCF used both. I think this explains why PySCF being much slower.

I re-ran the code using by setting `nlcgrids.level = 0 ~ 3` and found the following:
```
# nlcgrids.level  time/s  edft
0  2.023   -76.3863509
1  13.905  -76.3863427
2  59.741  -76.3863427
3  205.826581  -76.3863427
```
which seems to suggest that the default `nlcgrids.level = 3` is an overkill for VV10?

Anyway, my original problem is solved. Thank you so much and have a nice day!

**Comment by gkc1000** [comment]
Yes, pyscf just uses the same default grid level for all functionals.
Probably we should change the defaults. Please re-open issue so we remember
to do this.

**Comment by hongzhouye** [comment]
No problem. Thank you again!

**Comment by sunqm** [comment]
Unlike other dft modules, vv10 was implemented in pure Python. Rewriting the function dft.numint._vv10nlc in C should be able to provide great speedup.

**Comment by sunqm** [comment]
Performance of vv10 is optimized in pyscf-1.7.1

**Comment by hongzhouye** [comment]
Thanks!

**Comment by susilehtola** [comment]
Sorry to comment on a closed bug, but... by the way, how is PySCF handling VV10? The right way is stated somewhat unclearly in the paper. The NLC grid is supposed to be used for **the whole 6D integral**, not just the inner 3D one. This may also result in speed differences.
