### ISSUE TITLE
pyscf.org documentation page at 1.5 version

### ISSUE THREAD

**Issue by xubwa** [pyscf/pyscf#512]
I noticed that the documentation on sunqm.github.io/pyscf is already at version 1.7, the documentation on pyscf.org is still at 1.5 version. Is this due to the 1.7 doc still needs some refinement or you guys forgot to update that?

**Comment by tberkel** [comment]
Correct, we are still working on a large re-write of the PySCF
documentation, which we hope to have ready soon.
