### ISSUE TITLE
scf.UHF fails to initialize a spin down one-electron atom

### ISSUE THREAD

**Issue by dr-kinder** [pyscf/pyscf#514]
This is probably a rare use case, but the problem may arise for other users.  The following script results in an IndexError:

```
from pyscf import scf, gto

bad_molecule = gto.Mole(atom='H', basis='sto3g', spin=-1, charge=0)
bad_molecule.build()
solver=scf.UHF(bad_molecule)
solver.kernel()
```

The script attempts to create a hydrogen atom with a `spin=-1` electron.  Line 892 of scf/uhf.py seems to be the source of the problem.  It assumes a single electron atom has a `spin=+1` electron.

**Comment by sunqm** [comment]
The problem was solved in PR 517
