### ISSUE TITLE
SOC support for SHCI

### ISSUE THREAD

**Issue by portega-usal** [pyscf/pyscf#521]
Greetings,

I am trying to calculate the spin-orbit coupling energy for the N+(3Pj) + H2  --> NH+  + H system, and, as you may know, there are some interest about getting accurate results on the nitrogen cation fine structure and the endothermicity of the reaction, which is known to be around a few meV, far below the chemical accuracy on quantum methods. 

For this purpose, I am trying to use Dice for a FCI calculation on the reactants part, with the nitrogen far from the hydrogen molecule. This way, I should get a 3Pj electronic state, which is decoupled in three fine-structure lines separated by 6 and 11 meV respectively. I have read on the Dice website about the doSOC feature, but I think that this interface is not completely finished in PySCF. I have checked the shci.py file, there is a doSOC function and a writeSOCintegrals function, around lines 1390-1550, but it is not working. It has something to do with the x2c module. 

As I have seen on the https://pubs.acs.org/doi/pdf/10.1021/acs.jctc.7b01019 Sharma publication, these kind of calculations have already been made. I would be grateful if you could implement this feature. 

Thanks in advance,
Pablo

**Comment by xubwa** [comment]
Hey you can try the shci-soc branch from my forked pyscf repository. There is a socutils.py file in the shciscf directory. That should include the fixed functionality for doing soc calculations.

**Comment by portega-usal** [comment]
> 
> 
> Hey you can try the shci-soc branch from my forked pyscf repository. There is a socutils.py file in the shciscf directory. That should include the fixed functionality for doing soc calculations.

I downloaded your version, but there must be a problem with compatibility. I have installed this version in a Python virtual environment, it yields this error:

>>> import pyscf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/portega/shci_soc/pyscf/pyscf/__init__.py", line 61, in <module>
    from pyscf import lib
  File "/home/portega/shci_soc/pyscf/pyscf/lib/__init__.py", line 24, in <module>
    from pyscf.lib import numpy_helper
  File "/home/portega/shci_soc/pyscf/pyscf/lib/numpy_helper.py", line 40, in <module>
    _np_helper = misc.load_library('libnp_helper')
  File "/home/portega/shci_soc/pyscf/pyscf/lib/misc.py", line 70, in load_library
    return numpy.ctypeslib.load_library(libname, _loaderpath)
  File "/usr/local/spack/opt/spack/linux-centos7-x86_64/gcc-4.9.4/py-numpy-1.15.2-plou4yql5tl5ikbbxoauiwjubfi6xcb7/lib/python3.7/site-packages/numpy/ctypeslib.py", line 155, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension

Best regards

**Comment by xubwa** [comment]
What if you try just put that societies file in that folder and when you call those soc related functions call them from socutils instead of from shci. It can write out the soc related one electron integrals. But the shortcut function dosoc is not useful right now, since there is no support for zdice right now in the shci module. You will need to prepare a input file, and call zdice directly.

?? Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by portega-usal** [comment]
I am no longer working on this project. I have seen some new features have been added to spin-orbit coupling related properties, for different states, but I did not really have time to check it out. I am sure that these new features will provide valuable resources for newcomers and maybe I have some opportunities to use it in the future.

Best regards,
Pablo
