### ISSUE TITLE
cubegen for unit cells

### ISSUE THREAD

**Issue by Simonsays095** [pyscf/pyscf#524]
Trying to create .cub files for periodic systems has a few issues. Among them:

- There is no way to currently create a .cub file using pbc_eval_gto since it defaults to eval_gto (and no PBC tag is added)
- Box margins for periodic systems should be determined wholly by the unit cell
- The symmetric mesh causes inconsistencies across periodic images.

I changed code in several places to get a functional version of what I am looking for, which may or may not be the best or cleanest way to go about it, but it works (I removed docstrings in code blocks for brevity):

# Change #<span></span>1: 
https://github.com/sunqm/pyscf/blob/2efe5942b60868857f58cd62c0538b0a896589f3/pyscf/tools/cubegen.py#L103-L144
- Added a margin argument to cubegen.orbital(...) so that a user can actually specify a margin manually.
- This change is separate from the rest, and isn't necessary (or even used) for periodic systems
```py
def orbital(mol, outfile, coeff, nx=80, ny=80, nz=80, resolution=RESOLUTION, margin=BOX_MARGIN):
    cc = Cube(mol, nx, ny, nz, resolution, margin)

    # Compute density on the .cube grid
    coords = cc.get_coords()
    ngrids = cc.get_ngrids()
    blksize = min(8000, ngrids)
    orb_on_grid = numpy.empty(ngrids)
    for ip0, ip1 in lib.prange(0, ngrids, blksize):
        ao = numint.eval_ao(mol, coords[ip0:ip1])
        orb_on_grid[ip0:ip1] = numpy.dot(ao, coeff)
    orb_on_grid = orb_on_grid.reshape(cc.nx,cc.ny,cc.nz)

    # Write out orbital to the .cube file
    cc.write(orb_on_grid, outfile, comment='Orbital value in real space (1/Bohr^3)')
    return orb_on_grid
```
# Change #<span></span>2:
https://github.com/sunqm/pyscf/blob/2efe5942b60868857f58cd62c0538b0a896589f3/pyscf/tools/cubegen.py#L204-L227
- Changed the `__init__` function for Cube objects to define the box, origin, and mesh symmetry differently for Cells
```py
    def __init__(self, mol, nx=80, ny=80, nz=80, resolution=RESOLUTION,
                 margin=BOX_MARGIN, origin=ORIGIN, extent=EXTENT):
        self.mol = mol
        coord = mol.atom_coords()

        from pyscf.pbc.gto import Cell
        # If the molecule is periodic, use lattice vectors as the box
        # and ignore magin, origin, and extent arguments
        if isinstance(mol, Cell):
            self.box = mol.lattice_vectors()
            box = numpy.diag(self.box)
            self.boxorig = (numpy.max(coord, axis=0) + numpy.min(coord, axis=0))/2 - box/2
        else:
            if extent is None:
                box = numpy.max(coord,axis=0) - numpy.min(coord,axis=0) + margin*2
                self.box = numpy.diag(box)
            else:
                self.box = numpy.diag(extent)

            if origin is None:
                self.boxorig = numpy.min(coord,axis=0) - margin
            else:
                self.boxorig = numpy.array(origin)

        if resolution is not None:
            nx, ny, nz = numpy.ceil(numpy.diag(self.box) / resolution).astype(int)
        self.nx = nx
        self.ny = ny
        self.nz = nz

        # Use an asymmetric mesh for tiling unit cells
        if isinstance(mol, Cell):
            self.xs = numpy.arange(nx) * box[0] / nx
            self.ys = numpy.arange(ny) * box[1] / ny
            self.zs = numpy.arange(nz) * box[2] / nz
        else:
            # .../(nx-1) to get symmetric mesh
            # see also the discussion https://github.com/sunqm/pyscf/issues/154
            self.xs = numpy.arange(nx) * box[0] / (nx - 1)
            self.ys = numpy.arange(ny) * box[1] / (ny - 1)
            self.zs = numpy.arange(nz) * box[2] / (nz - 1)
```
# Change #<span></span>3:
https://github.com/sunqm/pyscf/blob/8d29c05eca89c83d21edb6f935ea2aad79d6dbf2/pyscf/dft/numint.py#L47-L106
- Changed the feval of `eval_ao` to start with "PBC" if it is a unit cell. This, in particular, may have a better solution than checking for a Cell object directly. It may even be worth adding a periodic extension to numint, but I'll leave that up to you.
```py
def eval_ao(mol, coords, deriv=0, shls_slice=None,
            non0tab=None, out=None, verbose=None):
    comp = (deriv+1)*(deriv+2)*(deriv+3)//6
    if mol.cart:
        feval = 'GTOval_cart_deriv%d' % deriv
    else:
        feval = 'GTOval_sph_deriv%d' % deriv

    from pyscf.pbc.gto import Cell
    if isinstance(mol, Cell):
        feval = "PBC" + feval
    return mol.eval_gto(feval, coords, comp, shls_slice, non0tab, out=out)

```

**Comment by sunqm** [comment]
Thanks for the code patch and suggestions. It is added in PR #534
