### ISSUE TITLE
huge difference between PBC and OBC supercell EOM-CCSD calculations

### ISSUE THREAD

**Issue by wen-xl** [pyscf/pyscf#527]
I want to perform periodic EA-/IP-EOM-CCSD calculations on 1-dimensional systems.
I use a modified input of pyscf/examples/pbc/31-low_dimensional_pbc.py (attached below)
I extrapolate the bandgap from periodic calculations and molecular supercell calculations for TDL. 
Although the HF and CCSD energies are very similar for PBC and OBC supercell calculations, the EA/IP energies are very different. 
![image](https://user-images.githubusercontent.com/31773324/74991027-7ce4d880-540a-11ea-87ce-2cd753d3ac05.png)

Except for the problem in PBC EA/IP energies, I also observed the slow convergence of IP with respect to the GDF mesh while EA converges quickly.

For example, when I use the default mesh
`******** <class 'pyscf.pbc.df.df.GDF'> ********
mesh = [5, 39, 39] (7605 PWs)
1D:    DF           super-mole
HF: [-1.071132949181326, -1.3175357104055445]
IP:  [array([ 2.14043257,  2.69389773]), array([ 0.27091841,  0.4030913 ])]
EA: [array([ 1.03595685,  1.1087384 ]), array([ 0.18563385,  0.37320227])]`

As I increase the mesh on non-periodic directions, IP increases rapidly while EA doesn't.
`******** <class 'pyscf.pbc.df.df.GDF'> ********
mesh = [5, 99, 99] (49005 PWs)
1D:    DF           super-mole
HF: [-6.73982160108494, -1.3175357104055445]
IP:  [array([ 2.655768  ,  3.08199009]), array([ 0.27091841,  0.4030913 ])]
EA: [array([ 1.03595683,  1.10873831]), array([ 0.18563385,  0.37320227])]`

******** <class 'pyscf.pbc.df.df.GDF'> ********
`mesh = [5, 199, 199] (198005 PWs)
1D:    DF           super-mole
HF: [-10.985908689082191, -1.3175357104055432]
IP:  [array([ 3.04177582,  3.46799781]), array([ 0.27091841,  0.4030913 ])]
EA: [array([ 1.03595674,  1.10873824]), array([ 0.18563385,  0.37320227])]`

Am I doing the 1D periodic EA-/IP-EOM-CCSD calculations correctly?

The script I use:
`import time
import numpy
from pyscf import scf
from pyscf import cc
from pyscf.pbc import df as pdf
from pyscf.pbc import scf as pbchf
from pyscf.pbc import gto as pbcgto
from pyscf.pbc import tools
from pyscf.pbc import cc as pbccc

##################################################
#
# 1D PBC
#
##################################################

e = []
t = []
ip = []
ea = []
nkpts=10
L = 1.8 * 2
cell = pbcgto.Cell()
cell.build(unit = 'B',
           a = [[L,0,0],[0,4,0],[0,0,4]],
           atom = '''H 0 0 0; H 1.8 0 0''',
           dimension=1,
           verbose = 9,
           basis='sto6g')

t0 = time.time()
mf = pbchf.KRHF(cell).density_fit(auxbasis='weigend')
mf.kpts = cell.make_kpts([nkpts,1,1])
e.append(mf.kernel())
mycc = pbccc.KRCCSD(mf)
mycc.kernel()
eip, wip = mycc.ipccsd(nroots=2, kptlist=[0])
eea, wea = mycc.eaccsd(nroots=2, kptlist=[0])
ip.append(eip[0])
ea.append(eea[0])
t.append(time.time() - t0)

t0 = time.time()
mol = tools.super_cell(cell, [nkpts,1,1]).to_mol()
mf = scf.RHF(mol)
e.append(mf.kernel()/nkpts)
mycc = cc.RCCSD(mf)
mycc.kernel()
eip, wip = mycc.ipccsd(nroots=2)
eea, wea = mycc.eaccsd(nroots=2)
ip.append(eip)
ea.append(eea)
t.append(time.time() - t0)

print('1D:  DF       super-mole')
print(e)
print(ip)
print(ea)
`

**Comment by gkc1000** [comment]
Taking the TDL of a 1D system using the 3D periodic Coulomb interaction is
tricky. In general, this limit is only well-defined if you increase the k
mesh in *all 3 directions*, not just 1 direction. The alternative is to use
a truncated Coulomb interaction.

**Comment by sunqm** [comment]
The integral scheme for low-dimension systems was developed for ground state HF and correlation calculations. The ground state energy can be rapidly converged wrt the integration mesh. When applying to the procedure of ionization, fine-size error is significant due to the exchange term. It was found in both 1D and 2D cases. Nonetheless, in 2D, truncated Coulomb operator can be used and the error in exchange can be removed effectively. The library does not support truncated Coulomb for 1D because of numerical instability. Since the potential in EA is more or less the HF potential, the exchange issue matters less to EA.

We should probably clarify this for 1-D system at some places. @tberkel @gkc1000

**Comment by wen-xl** [comment]
Thanks for the reply! I have some follow-up questions:
1. What is the keyword for the truncated Coulomb interaction?
2. Can I avoid the finite-size error for IP by doing fake 1D calculations? Set cell.dimension=3, and set the cell length of the non-periodic directions to a large number (cell.a = [[L,0,0],[0,20,0],[0,0,20]])
3. Is it valid to extrapolate TDL from fake 1D calculations?

**Comment by sunqm** [comment]
1. By default, truncated Coulomb is enabled for 2D, **disabled** for 1D.
2. No. You'll get finite size error anyway. The fake 1D will not be that bad as the case of cell.dimension=1. dimension=1 has especially large error for IP. It is relatively smaller with 3D cell.
3. my understanding is yes.

**Comment by wen-xl** [comment]
Thanks so much!
