### ISSUE TITLE
inconsistencies in CCSD(T) between pbc and molecular codes

### ISSUE THREAD

**Issue by mmorale3** [pyscf/pyscf#528]
Hi,

I'm trying to perform ccsd(t) calculations with the pbc code and I'm obtaining results which are not consistent with the molecular cc code. Both v 1.6.1 and v 1.7 show the same behavior. 
This is a simple calculation that reproduces the problem:

#!/usr/bin/env python

import numpy
from pyscf.pbc import gto, scf

alat0 = 3.6
cell = gto.Cell()
cell.a = (numpy.ones((3,3))-numpy.eye(3))*alat0/2.0
cell.atom = (('C',0,0,0),('C',numpy.array([0.25,0.25,0.25])*alat0))
cell.basis = 'gth-dzvp'
cell.pseudo = 'gth-pade'
cell.mesh = [28]*3
cell.verbose = 5
cell.build()

kpts = cell.make_kpts([1,1,1])
mf = scf.RHF(cell,kpts,exxdiv=None).run()

from pyscf.pbc import cc
mycc = cc.RCCSD(mf).run()
et = mycc.ccsd_t()

from pyscf import cc as pbc_cc
pcc = pbc_cc.RCCSD(mf).run()
et = pcc.ccsd_t()

As you see below, the CCSD energies agree but the (T) corrections and the reported MP2 energies disagree. Since I'm setting exxdiv=None, I would expect both calculations to agree.
This is part of the output:

...
... scf output
...
Extra cycle  E= -7.62399482654968  delta_E= -6.22e-15  |g|= 2.74e-08  |ddm|= 3.99e-06
    CPU time for scf_cycle     31.01 sec, wall time      1.44 sec
    CPU time for SCF     31.01 sec, wall time      1.44 sec
converged SCF energy = -7.62399482654968
    CPU time for vj and vk      0.13 sec, wall time      0.00 sec
    CPU time for CCSD integral transformation     44.57 sec, wall time      1.55 sec
Ewald components = 2.81183965664179e-48, -1.21637741567603, 0.879404564754328

******** <class 'pyscf.pbc.cc.ccsd.RCCSD'> ********
CC2 = 0
CCSD nocc = 4, nmo = 26
max_cycle = 50
direct = 0
conv_tol = 1e-07
conv_tol_normt = 1e-05
diis_space = 6
diis_start_cycle = 0
diis_start_energy_diff = 1e+09
max_memory 4000 MB (current use 231 MB)
Init t2, MP2 energy = -0.170309679914063
    CPU time for init mp2      0.00 sec, wall time      0.00 sec
Init E(CCSD) = -0.170309679914064
cycle = 1  E(CCSD) = -0.200056135737642  dE = -0.0297464558  norm(t1,t2) = 0.0636392
    CPU time for CCSD iter      0.78 sec, wall time      0.03 sec
cycle = 2  E(CCSD) = -0.212185961198594  dE = -0.0121298255  norm(t1,t2) = 0.0367107
    CPU time for CCSD iter      0.78 sec, wall time      0.03 sec
cycle = 3  E(CCSD) = -0.227577945218905  dE = -0.015391984  norm(t1,t2) = 0.0241839
    CPU time for CCSD iter      0.59 sec, wall time      0.02 sec
cycle = 4  E(CCSD) = -0.229234294044501  dE = -0.00165634883  norm(t1,t2) = 0.0085054
    CPU time for CCSD iter      0.53 sec, wall time      0.02 sec
cycle = 5  E(CCSD) = -0.230442432353902  dE = -0.00120813831  norm(t1,t2) = 0.00283312
    CPU time for CCSD iter      0.56 sec, wall time      0.02 sec
cycle = 6  E(CCSD) = -0.230475158099897  dE = -3.2725746e-05  norm(t1,t2) = 0.000982603
    CPU time for CCSD iter      0.59 sec, wall time      0.02 sec
cycle = 7  E(CCSD) = -0.230632985005518  dE = -0.000157826906  norm(t1,t2) = 0.000332262
    CPU time for CCSD iter      0.94 sec, wall time      0.03 sec
cycle = 8  E(CCSD) = -0.230591203183969  dE = 4.17818215e-05  norm(t1,t2) = 9.30887e-05
    CPU time for CCSD iter      1.39 sec, wall time      0.05 sec
cycle = 9  E(CCSD) = -0.230584976826098  dE = 6.22635787e-06  norm(t1,t2) = 4.26756e-05
    CPU time for CCSD iter      0.90 sec, wall time      0.03 sec
cycle = 10  E(CCSD) = -0.230589569698882  dE = -4.59287278e-06  norm(t1,t2) = 2.43922e-05
    CPU time for CCSD iter      0.54 sec, wall time      0.02 sec
cycle = 11  E(CCSD) = -0.230589012715003  dE = 5.56983879e-07  norm(t1,t2) = 5.12861e-06
    CPU time for CCSD iter      0.53 sec, wall time      0.02 sec
cycle = 12  E(CCSD) = -0.230589218270292  dE = -2.05555289e-07  norm(t1,t2) = 1.68578e-06
    CPU time for CCSD iter      0.70 sec, wall time      0.02 sec
cycle = 13  E(CCSD) = -0.230589266251891  dE = -4.79815994e-08  norm(t1,t2) = 5.43912e-07
    CPU time for CCSD iter      0.60 sec, wall time      0.02 sec
    CPU time for CCSD      9.43 sec, wall time      0.33 sec
RCCSD converged
E(RCCSD) = -7.854584092801572  E_corr = -0.2305892662518915
    CPU time for vj and vk      0.06 sec, wall time      0.00 sec
    CPU time for CCSD integral transformation     27.83 sec, wall time      1.06 sec
Ewald components = 2.81183965664179e-48, -1.21637741567603, 0.879404564754328
max_memory 3758 MB (241 MB in use)
    CPU time for CCSD(T)      0.46 sec, wall time      0.03 sec
CCSD(T) correction = -0.00689181017731288

******** <class 'pyscf.cc.dfccsd.RCCSD'> ********
CC2 = 0
CCSD nocc = 4, nmo = 26
max_cycle = 50
direct = 0
conv_tol = 1e-07
conv_tol_normt = 1e-05
diis_space = 6
diis_start_cycle = 0
diis_start_energy_diff = 1e+09
max_memory 4000 MB (current use 241 MB)
    CPU time for vj and vk      0.12 sec, wall time      0.00 sec
Init t2, MP2 energy = -0.396738289302499
    CPU time for init mp2      0.00 sec, wall time      0.00 sec
Init E(CCSD) = -0.3967382893025
cycle = 1  E(CCSD) = 0.0663941422063007  dE = 0.463132432  norm(t1,t2) = 1.12301
    CPU time for CCSD iter     89.35 sec, wall time     15.85 sec
cycle = 2  E(CCSD) = -0.846608373581901  dE = -0.913002516  norm(t1,t2) = 2.34896
    CPU time for CCSD iter     88.05 sec, wall time     15.85 sec
cycle = 3  E(CCSD) = -0.259551247339063  dE = 0.587057126  norm(t1,t2) = 4.59654
    CPU time for CCSD iter     86.45 sec, wall time     15.87 sec
cycle = 4  E(CCSD) = -0.241708220653218  dE = 0.0178430267  norm(t1,t2) = 0.275822
    CPU time for CCSD iter     91.34 sec, wall time     16.13 sec
cycle = 5  E(CCSD) = -0.23789771593687  dE = 0.00381050472  norm(t1,t2) = 0.098972
    CPU time for CCSD iter     88.25 sec, wall time     15.88 sec
cycle = 6  E(CCSD) = -0.224882293243976  dE = 0.0130154227  norm(t1,t2) = 0.0568449
    CPU time for CCSD iter     83.77 sec, wall time     14.98 sec
cycle = 7  E(CCSD) = -0.231542196188261  dE = -0.00665990294  norm(t1,t2) = 0.0500854
    CPU time for CCSD iter     74.85 sec, wall time     14.57 sec
cycle = 8  E(CCSD) = -0.230604196056201  dE = 0.000938000132  norm(t1,t2) = 0.00898086
    CPU time for CCSD iter     82.57 sec, wall time     15.06 sec
cycle = 9  E(CCSD) = -0.230593686754625  dE = 1.05093016e-05  norm(t1,t2) = 9.96268e-05
    CPU time for CCSD iter     79.05 sec, wall time     14.80 sec
cycle = 10  E(CCSD) = -0.230590091467457  dE = 3.59528717e-06  norm(t1,t2) = 2.77278e-05
    CPU time for CCSD iter     76.47 sec, wall time     14.90 sec
cycle = 11  E(CCSD) = -0.230589679306322  dE = 4.12161135e-07  norm(t1,t2) = 7.70551e-06
    CPU time for CCSD iter     78.55 sec, wall time     14.62 sec
cycle = 12  E(CCSD) = -0.230589379047503  dE = 3.00258819e-07  norm(t1,t2) = 2.25684e-06
    CPU time for CCSD iter     77.59 sec, wall time     14.75 sec
cycle = 13  E(CCSD) = -0.2305891851637  dE = 1.93883803e-07  norm(t1,t2) = 1.54421e-06
    CPU time for CCSD iter     77.73 sec, wall time     14.51 sec
cycle = 14  E(CCSD) = -0.230589285143737  dE = -9.99800371e-08  norm(t1,t2) = 4.63825e-07
    CPU time for CCSD iter     90.71 sec, wall time     15.64 sec
    CPU time for CCSD   1164.73 sec, wall time    213.40 sec
RCCSD converged
E(RCCSD) = -7.854584111693417  E_corr = -0.2305892851437374
    CPU time for vj and vk      0.11 sec, wall time      0.00 sec
max_memory 3675 MB (324 MB in use)
    CPU time for CCSD(T)      0.35 sec, wall time      0.02 sec
CCSD(T) correction = -0.0118620397337214

Thanks!

**Comment by gkc1000** [comment]
I think this is because the "exxdiv" madelung constant term is *always*
added to the eri.mo_energies in pbc.cc.RCCSD. Otherwise,
it is often found that some occupied orbitals lie above the virtual
orbitals leading to nonsensical results in PT. The line where this is done
is:
line 60 in https://github.com/pyscf/pyscf/blob/master/pyscf/pbc/cc/ccsd.py
Try commenting it out.

**Comment by tberkel** [comment]
Agreed. You can see that this is the case because the MP2 energies also
disagree at the beginning of the CCSD iterations.

This behavior is being addressed in the dev branch.

**Comment by mmorale3** [comment]
This is the source of the discrepancy. Thanks for the quick response.
