### ISSUE TITLE
GW - test gives wrong values

### ISSUE THREAD

**Issue by mbarbry** [pyscf/pyscf#529]
Hi,

I wanted to give a try to the GW module of PySCF. However, running the test included in the file `pyscf/gw/gw.py` gives different results for the energies than the commented values in the code (line 400) which I assume are the reference values.

I attached the output I get from running `python gw.py`

[gw_output.txt](https://github.com/pyscf/pyscf/files/4242198/gw_output.txt)

Is the code outdated?

**Comment by tberkel** [comment]
The problem is with your DFT calc, not GW -- you can see in the output that
the numbers are way off, nelec integrates to 0.0, the SCF doesn't converge,
etc.  I would guess that your libxc is not properly
included/compiled/linked.

**Comment by sunqm** [comment]
Does the regular HF calculation give right result? I couldn't reproduce your test. The commit c3b3584e6690d27ff28efafbf106178dae6cd6d4 in your output seems not in the main branch.

**Comment by mbarbry** [comment]
Thanks for your comments.
I used the dev branch, may explain the commit that you saw.
I will check libxc, but I did not see any issue during the compilation, maybe a linking problem as you mentionned.

**Comment by sunqm** [comment]
I tried dev branch, couldn't reproduce the problem. Your output log looks like a problem associated to analytical integral or JK builder. Can you try cleaning up all compiled libraries, (inlcuding the depedent libraries, libcint, libxc, libxcfun) and test gw again?

**Comment by mbarbry** [comment]
I tried a clean installation and it work out. Probably I mess up somewhere the first time.
Thanks for your helps!

**Comment by gkc1000** [comment]
Note that another implementation of GW will soon be released.

**Comment by mbarbry** [comment]
Thanks for the info. Is it possible to have a look at this new version?

**Comment by gkc1000** [comment]
Yes, but we will push very soon anyways, I'll look into it.

**Comment by mbarbry** [comment]
Hi @gkc1000 ,

Any update on this new version of GW?
