### ISSUE TITLE
"NoneType is not subscriptable" error since pyscf 1.7.0

### ISSUE THREAD

**Issue by jakobkraus** [pyscf/pyscf#530]
Hi,

I am using pyscf as the basis of my FLO-SIC code (flosic_scf.py), in which I define a FLO-SIC object which inherits from the UHF class.

The class definition starts with:

class FLOSIC(uhf.UHF):
    def __init__(self, mol, xc, fod1, fod2, ldax=False, grid_level=3, calc_forces = False, debug=False,nuclei=None,l_ij=None,ods=None,fixed_vsic=None,num_iter=0,ham_sic='HOO',vsic_every=1, init_dm=None):
        uhf.UHF.__init__(self, mol)
        rks._dft_common_init_(self)
        
        # Give the input variables to the SIC object.
        self.mol = mol # Molecular geometry.
        self.xc = xc # Exchange-correlation functional
        self.fod1 = fod1 # FOD geometry for first spin channel.
        self.fod2 = fod2 # FOD geometry for second spin channel.
        self.nfod = [fod1.positions.shape[0],fod2.positions.shape[0]]
        self.nuclei = nuclei 
        self.ldax = ldax # If True, LDA exchange is used for FLO-SIC (debugging mainly).
        self.is_first = True # Used to determine which SCF cycle we are in.
        self.grid_level = grid_level # Grid level.
        self.grids.level = grid_level 
        self.calc_forces = calc_forces # Determines whether or not FOD forces are calculated in every step. Default: False.
        self.debug = debug # enable debugging output 		
        self.l_ij = l_ij # Lagrangian multiplier output 
        self.lambda_ij = [] # # Lagrangian multiplier matrix 
        self.ods = ods # orbital density scaling 
        
        # creation of an internal UKS object for handling FLO-SIC calculations.
        lib.logger.TIMER_LEVEL = 4
        mol.verbose = 0
        calc_uks = UKS(mol)
        calc_uks.xc = self.xc
        calc_uks.max_cycle = 0
        calc_uks.grids.level = grid_level
        
        # if an initial density matrix is given
        # initialize the subclass with it
        if init_dm is not None:
            calc_uks.kernel(init_dm)
        else:
            calc_uks.kernel()
        self.calc_uks = calc_uks
        .......

In pyscf 1.6.6 and older, no problem is encountered when creating an instance of the FLOSIC class.
However, simply switching to pyscf 1.7.0 generates the following error:

  File "/home/kraus/pyflosic/src/flosic_scf.py", line 285, in __init__
    calc_uks.kernel()
  File "/home/kraus/pyscf/pyscf/lib/misc.py", line 601, in aliased_fn
    return getattr(self, fname)(*args, **kwargs)
  File "/home/kraus/pyscf/pyscf/scf/hf.py", line 1636, in scf 
    self._finalize()
  File "/home/kraus/pyscf/pyscf/scf/uhf.py", line 834, in _finalize
    ss, s = self.spin_square()
  File "/home/kraus/pyscf/pyscf/scf/uhf.py", line 816, in spin_square
    mo_coeff = (self.mo_coeff[0][:,self.mo_occ[0]>0],
TypeError: 'NoneType' object is not subscriptable

Do you have any idea how I could make my code compatible with pyscf 1.7.0?
Thanks in advance for your time and help. Both is very much appreciated.

**Comment by sunqm** [comment]
1.7 make changes for the case max_cycle=0. It skips scf iterations. For a
quick fix of your code, you can set max_cycle=1. I'll fix the problem in
next updates.

**Comment by jakobkraus** [comment]
Thank you very much for the quick reply and solution

**Comment by BelugaHaechi** [comment]
Hello, I have been recently looking into this piece of code modified in commit 0a129c3.

Currently, the `kernel` function of the `scf.hf.SCF` class, which is internally called `scf`, reads as follows:
https://github.com/pyscf/pyscf/blob/c8a4215308657274f221937e5a8b8908a039c3a9/pyscf/scf/hf.py#L2024-L2045

I am wondering why do we avoid updating the attributes,
```
self.converged
self.mo_energy
self.mo_coeff
self.mo_occ
```
but ONLY update `self.e_tot`, **even if** `max_cycle > 0` **but** `self.mo_coeff is not None`?

I understand why this may be useful when `max_cycle <= 0`, but why do we still avoid updating the attributes when we are doing a full SCF calculation, albeit just with initial guess orbitals supplied?

**Comment by BelugaHaechi** [comment]
This extra `or self.mo_coeff is not None` gate was added in the above commit, and seems to be intended to fix this issue #530. I am wondering what the original motivation was.

Thank you for your attention to this matter.

**Comment by jeanwsr** [comment]
> Hello, I have been recently looking into this piece of code modified in commit [0a129c3](https://github.com/pyscf/pyscf/commit/0a129c320502cc5eb866e16011ad414320a7b07c).
> 
> Currently, the `kernel` function of the `scf.hf.SCF` class, which is internally called `scf`, reads as follows:
> 
> [pyscf/pyscf/scf/hf.py](https://github.com/pyscf/pyscf/blob/c8a4215308657274f221937e5a8b8908a039c3a9/pyscf/scf/hf.py#L2024-L2045)
> 
> Lines 2024 to 2045 in [c8a4215](/pyscf/pyscf/commit/c8a4215308657274f221937e5a8b8908a039c3a9)
>      if dm0 is None and self.mo_coeff is not None and self.mo_occ is not None: 
>          # Initial guess from existing wavefunction 
>          dm0 = self.make_rdm1() 
>   
>      if self.max_cycle > 0 or self.mo_coeff is None: 
>          self.converged, self.e_tot, \ 
>                  self.mo_energy, self.mo_coeff, self.mo_occ = \ 
>                  kernel(self, self.conv_tol, self.conv_tol_grad, 
>                         dm0=dm0, callback=self.callback, 
>                         conv_check=self.conv_check, **kwargs) 
>      else: 
>          # Avoid to update SCF orbitals in the non-SCF initialization 
>          # (issue #495).  But run regular SCF for initial guess if SCF was 
>          # not initialized. 
>          self.e_tot = kernel(self, self.conv_tol, self.conv_tol_grad, 
>                              dm0=dm0, callback=self.callback, 
>                              conv_check=self.conv_check, **kwargs)[1] 
>   
>      logger.timer(self, 'SCF', *cput0) 
>      self._finalize() 
>      return self.e_tot 
>  kernel = lib.alias(scf, alias_name='kernel') 
> 
> I am wondering why do we avoid updating the attributes,
> 
> ```
> self.converged
> self.mo_energy
> self.mo_coeff
> self.mo_occ
> ```
> 
> but ONLY update `self.e_tot`, **even if** `max_cycle > 0` **but** `self.mo_coeff is not None`?
> 
> I understand why this may be useful when `max_cycle <= 0`, but why do we still avoid updating the attributes when we are doing a full SCF calculation, albeit just with initial guess orbitals supplied?

if `max_cycle > 0` but `self.mo_coeff is not None`, `self.max_cycle > 0 or self.mo_coeff is None` will be True, so it goes to a normal update of these attributes.
