### ISSUE TITLE
Is the DFT-D3 interface broken?

### ISSUE THREAD

**Issue by proton-peter** [pyscf/pyscf#532]
Trying to run a DFT-D3 calculation with the current version from the master branch:

`  File "[...]/pyscf/dftd3/itrf.py", line 159, in dftd3
    with_dftd3 = DFTD3(scf_method.mol)
UnboundLocalError: local variable 'DFTD3' referenced before assignment`

Trying to run a DFT-D3 calculation with v1.7.0:

`  File "[...]/pyscf/dftd3/itrf.py", line 284, in kernel
    ctypes.c_char_p(func),
TypeError: bytes or integer address expected instead of str instance`

**Comment by fishjojo** [comment]
fixed in 7a87fc6
