### ISSUE TITLE
Orbital visualization of a gamma point calculation

### ISSUE THREAD

**Issue by btglau** [pyscf/pyscf#539]
I am looking for recommendations for programs that can visualize orbitals from a periodic calculation with pseudo potentials. I can visualize them via molden to jmol or avogadro, but it does not read the atomic number correctly. On the flipside, jmol will visualize orbitals from cube files but with no atoms, while avogadro does the opposite.

**Comment by zhcui** [comment]
You can try vesta (http://jp-minerals.org/vesta/en/) to visualize cube file.

**Comment by manassharma07** [comment]
You can try this tutorial: https://www.youtube.com/watch?v=SQuGdXXtaUE

In Jmol, you first load the structure using the load command. Then you can use the isosurface command to visualize the .cube file.

Alternatively, you can also try VESTA as already suggested.
