### ISSUE TITLE
Disagreement in qpwt between restricted and unrestricted IP/EA-EOM-CCSD codes

### ISSUE THREAD

**Issue by Samragni-93** [pyscf/pyscf#541]
Hi, 
I ran two separate calculations for the same molecule (Nitrogen molecule) using the restricted and unrestricted IP-EOM-CCSD codes. While the eigenvalues come out to be exactly the same, there is a difference in the qpwts (calculated from the eigenvectors) between the restricted and unrestricted codes. 

Also, I ran the same calculations using QChem and the qpwts match between their restricted and unrestricted codes and also with the unrestricted code in pyscf. 
Does this mean there is a bug in the restricted IP/EA-EOM-CCSD code?

Input for the unrestricted code 

`import numpy as np
  import pyscf.gto
  import pyscf.scf
  import pyscf.cc
  np.set_printoptions(linewidth=150, edgeitems=10, suppress=True)

  basis = 'aug-cc-pVDZ'
  print ("Basis set: ", basis)

  r = 1.098159

  mol = pyscf.gto.Mole()
  mol.verbose = 4
  mol.atom = [
      ['N', ( 0., 0.    , -r/2   )],
      ['N', ( 0., 0.    ,  r/2)],]
  mol.basis = {'N': basis}
  mol.build()

  mf = pyscf.scf.UHF(mol)
  mf.conv_tol = 1e-12
  mf.kernel()

  mycc = pyscf.cc.UCCSD(mf)
  mycc.ccsd()
  eip,cip = mycc.ipccsd(nroots=10)`

Differences in input for the restricted code 

`mf = pyscf.scf.RHF(mol)
  mf.conv_tol = 1e-12
  mf.kernel()

  mycc = pyscf.cc.RCCSD(mf)
  mycc.ccsd()
  eip,cip = mycc.ipccsd(nroots=5)`

![uccsd](https://user-images.githubusercontent.com/55956725/76033881-55623580-5f0b-11ea-9686-fd6cb1a75478.png)
![rccsd](https://user-images.githubusercontent.com/55956725/76033894-5dba7080-5f0b-11ea-914d-8683ff616d5d.png)

**Comment by sunqm** [comment]
I believe this is related to normalization. The r vectors in eom are not
normalized to a specific number. Not sure whether qpwt needs to be defined
on top of a "normalized" vector

**Comment by tberkel** [comment]
Correct, this is due to normalization.  Individually, the R vector normalization is not meaningful; only L and R together can be biorthonormalized for the calculation of observables.  However, a common choice is to normalize R to itself (and the L can be biorthonormalized against R if necessary).  To calculate the qpwt of this self-normalized R, you can do the following for restricted EOM:
```
e,v = mycc.ipccsd(nroots=1)
from pyscf.cc.eom_rccsd import vector_to_amplitudes_ip
r1,r2 = vector_to_amplitudes_ip(v, mycc.nmo, mycc.nocc)
rdotr = numpy.dot(r1, r1) + 2*numpy.dot(r2.ravel(), r2.ravel()) - numpy.dot(r2.ravel(), r2.transpose(1,0,2).ravel())
r1 /= numpy.sqrt(rdotr)
r2 /= numpy.sqrt(rdotr)
qpwt = numpy.dot(r1,r1)
```
@fishjojo @sunqm @xwang862 we should probably make this the default behavior in restricted EOM, so that R is always returned as normalized and the qpwts will match ...

**Comment by Samragni-93** [comment]
This makes perfect sense. Thank you.

**Comment by xwang862** [comment]
@tberkel I agree. And even better to give consistent weights with other packages like QChem.
