### ISSUE TITLE
Projections fail for basis sets with significant linear dependencies

### ISSUE THREAD

**Issue by susilehtola** [pyscf/pyscf#542]
The projection routines in `scf/addons.py` assume that the basis set is well-behaved, i.e. that the dense Cholesky solve can be done without problems. However, this assumption breaks down when significant linear dependencies are present.

Because the fix is non-trivial due to the way the code is organized, I am filing a ticket instead of a pull request.

**Comment by susilehtola** [comment]
The problem is that since the code does not assume a standard way of cleaning up linear dependencies, MO projections become problematic as the projection code does not have access to the orthogonalizing matrix `X` also called half-inverse overlap.

**Comment by sunqm** [comment]
The requirement of strict semi positive definite for overlap matrix is loosen a little bit in the relevant codes in commit ab699fb066f5237badb4e1f3b959ea418233ac53 . If the condition of positive definite was is met, the code will print a warning message then rollback to the regular linear equation solver.
