### ISSUE TITLE
issues about pyscf/block memory control 

### ISSUE THREAD

**Issue by lqhenwunai** [pyscf/pyscf#547]
Dear all,

I tried to run the example input of 
/pyscf/examples/dmrg/30-dmrg_casscf_nevpt2_for_Cr2.py

In the input I gave a total memory of 
mol.max_memory=220000 #we have 256G per node.

And the comment in the example input says it requires about 200G for memory. 

However, even with a single cpu to run the calculation, the slurm output gives:
`ERROR: srun /public1/home/sc40147/block/mpi-block-1.5.3/block.spin_adapted dmrg.conf > dmrg.out 2>&1
output file: cr2-1.50.out
......production of RDMs took    1826.54 sec
......reading the RDM took         26.81 sec
Traceback (most recent call last):
  File "Cr2.py", line 53, in <module>
    mrpt.NEVPT(mc).kernel()
  File "/public1/home/sc40147/pyscf/pyscf/mrpt/nevpt2.py", line 751, in kernel
    norm_Sr   , e_Sr    = Sr(self, self.load_ci(), dms, eris)
  File "/public1/home/sc40147/pyscf/pyscf/mrpt/nevpt2.py", line 313, in Sr
    a16 = mc.fcisolver.nevpt_intermediate('A16',ncas,mc.nelecas,ci)
  File "/public1/home/sc40147/pyscf/pyscf/dmrgscf/dmrgci.py", line 679, in nevpt_intermediate
    executeBLOCK(self)
  File "/public1/home/sc40147/pyscf/pyscf/dmrgscf/dmrgci.py", line 930, in executeBLOCK
    raise err
subprocess.CalledProcessError: Command 'srun /public1/home/sc40147/block/mpi-block-1.5.3/block.spin_adapted dmrg.conf > dmrg.out 2>&1' returned non-zero exit status 134`

The dmrg output returns:
`
processor: 0  numthrds: 1  node name: c7903.bscc-d
allocating 250000000 doubles
**** STACK MEMORY REMAINING ***** 2.000000000000 GB
you are running 10
Invalid calculation types
srun: error: c7903: task 0: Aborted`

And I watch the memory usage on the computing node during the calculation, and the memory usage seems to be limited up to 5GB.

2020-03-07 22:26:11
              total        used        free      shared  buff/cache   available
Mem:            251           3         231          13          15         232
Swap:             0           0           0

2020-03-07 22:36:12
              total        used        free      shared  buff/cache   available
Mem:            251           4         230          13          16         232
Swap:             0           0           0

2020-03-07 22:46:12
              total        used        free      shared  buff/cache   available
Mem:            251           4         229          13          17         231
Swap:             0           0           0

2020-03-07 22:56:12
              total        used        free      shared  buff/cache   available
Mem:            251           5         230          13          16         231
Swap:             0           0           0

I didn't go through the block code very carefully, but I notice the input.C file of block:
`
      m_memory = 2e9/sizeof(double); //about 2GB of memory by default
   
      else if (boost::iequals(keyword, "memory") || boost::iequals(keyword, "mem")) {
        if (tok.size() != 3) {
          pout << "keyword should be followed by a number (memory size) and either k, m or g"<<endl;
          pout << "error found in the following line"<<endl;
          pout << msg<<endl;
          abort();
        }
        m_memory = atoi(tok[1].c_str());

        if (boost::iequals(tok[2], "k"))
          m_memory *= 1e3/sizeof(double);
        else if (boost::iequals(tok[2], "m"))
          m_memory *= 1e6/sizeof(double);
        else if (boost::iequals(tok[2], "g")) {
          m_memory *= 1e9/sizeof(double);
`

It looks like the block will parse the pyscf input and look for the "memory" keyword and setup memory usage for block.

It seems to me that the input.C needs a third parameter ("k", "m" or "g") to determine the memory unit, otherwise the default memory (2GB) will be given to block.

However, the mol.max_memory=200 g (for instance) is not legal in pyscf. 

I tried to modify the default memory in input.C in both serial and mpi folders of block by
 m_memory = 2e11/sizeof(double); //set 200GB of memory

the dmrg.out returns:
`processor: 0  numthrds: 1  node name: c4910.bscc-d
allocating 25000000000 doubles
**** STACK MEMORY REMAINING ***** 200.000000000000 GB
you are running 10
Invalid calculation types
srun: error: c4910: task 0: Aborted`

I don't know what else I can do to fix the problem. I am not sure if it is about the memory usage or about the invalid calculation types, or anything else.

Many thanks for your help.

best,

**Comment by gkc1000** [comment]
There should be a file called "sth.conf" (e.g. dmrg.conf) in the scratch
directory. That contains the actual commands used by the DMRG program, can
you find it and copy it here?

I think it looks like Block is just finding that you have already produced
a "reorder" file without including a "restart" keyword in the input. One
solution is to delete the various files in the scratch space
projects/Ln2/test/test2/1node/1cpu/scratch/9941/node0
and try again.

**Comment by lqhenwunai** [comment]
@gkc1000 

Many thanks for your reply. I was trying to make my original post more readable and didn't realize you reply so fast. Many thanks!

Here is the dmrg.conf:
nelec 28
spin 0
irrep 1
schedule
0   1000  1.0000e-07  0.0000e+00
end
fullrestart
onedot
sym d2h
orbitals FCIDUMP
maxiter 38
sweep_tol 1.0000e-06
outputlevel 2
hf_occ integral
prefix  /public1/home/sc40147/projects/Ln2/test/test2/1node/1cpu/scratch/9941
restart_nevpt2_npdm

However, it is not in the scratch directory. (Will that matter?) In the folder where I submit my job, there is a scratch folder and a random-number folder, in this case folder 9941. the dmrg.conf is in the 9941 folder .

**Comment by hczhai** [comment]
Thanks for providing the dmrg.conf.
It looks like the block binary that you are using does not support "restart_nevpt2_npdm" calculation type. So it produces the error "Invalid calculation types".
I will look into it.

**Comment by lqhenwunai** [comment]
@hczhai Thanks, I am using block-1.5.3

**Comment by bogdanoff** [comment]
DMRG interface as it is now ignores the `mol.max_memory` (probably because Block 1.1 didn't have the memory keyword). One can set it directly `dmrgscf.DMRGCI(mol, maxM=myM, memory=mol.max_memory/1e-3)` or as property of a solver `mc.fcisolver.memory = mol.max_memory/1e-3`.If it should be the default, we can change it in one or two lines.

It is mentioned [here](https://sanshar.github.io/Block/with-pyscf.html#dmrg-nevpt2), that one should use [ serial Block](http://www.sunqm.net/pyscf/files/bin/block.spin_adapted-1.5.3-serial.gz) (or compile it without MPI) to run the compressed-MPS-perturber DMRG-NEVPT2 `mrpt.NEVPT(mc).compress_approx()`, which is the only option with Block-1.5.

**Comment by lqhenwunai** [comment]
@bogdanoff Thanks for your reply. 

In the latest try, I set up memory in the input file
`mc.fcisolver.memory=mol.max_memory/1000  #should be divided by 1000, rather than 0.001, right?`

and in the dmrgscf/settings.py, I set up the serial excutables:
`#BLOCKEXE = '/public1/home/sc40147/block/mpi-block-1.5.3/block.spin_adapted'`
`BLOCKEXE = '/public1/home/sc40147/block/block-1.5.3/block.spin_adapted`
`BLOCKEXE_COMPRESS_NEVPT = '/public1/home/sc40147/block/block-1.5.3/block.spin_adapted'`


However, the dmrg.out still reports the "invalid calculation type" error. 

The dmrg.conf is as following:
nelec 28
spin 0
irrep 1
schedule
0    600  1.0000e-07  0.0000e+00
end
fullrestart
onedot
sym d2h
orbitals FCIDUMP
maxiter 38
sweep_tol 1.0000e-06
outputlevel 2
hf_occ integral
prefix  /public1/home/sc40147/projects/Ln2/test/test2/1node/1cpu/scratch/152592
memory, 220, g
restart_nevpt2_npdm

**Comment by gkc1000** [comment]
Hi, did you compile these block executables yourself, or were they
downloaded from https://sanshar.github.io/Block/build.html?

**Comment by lqhenwunai** [comment]
@gkc1000 
Techniquely,  not myself, it is our IT department staff. I do not have the permission. They download the source code and compile. 

I believe they follow the following instruction:

1) copy the source code and rename it as mpi-block-*
2) compile the serial version. (I heard they had some struggle to link the proper libraries), make and compile
3) edit the makefile in the mpi-block directory, and set USE_MPI=yes, together with some other MPICC settings and library settings
4) setup the dmrgscf/settings. 

The attached files are serial and mpi makefiles. 

[Makefile-serial.txt](https://github.com/pyscf/pyscf/files/4315506/Makefile-serial.txt)
[Makefile-mpi.txt](https://github.com/pyscf/pyscf/files/4315507/Makefile-mpi.txt)

**Comment by bogdanoff** [comment]
Could you try to comment out `mrpt.NEVPT(mc).kernel()` and use the `mrpt.NEVPT(mc).compress_approx()`? I think the firs one is not available with block 1.5.

**Comment by lqhenwunai** [comment]
@bogdanoff 

Many thanks!

Now it seems the calculation finishes correctly. But where do I get the NEVPT2 energy?
The end of pyscf output is:

 CPU time for 1-step CASSCF    626.33 sec, wall time  13315.11 sec
CASSCF energy = -2099.30172698561
CASCI E = -2099.30172698561  E(CI) = -242.524220697645  S^2 = 0.0000000
Use compressed mps perturber as an approximation


and the end of dmrg output is:

Spin-orbital 2PDM trace = 755.999999999997
Spatial      2PDM trace = 378.000000000000
                         Elapsed Sweep CPU  Time (seconds): 36.950
                         Elapsed Sweep Wall Time (seconds): 38
                         Saving state /public1/home/sc40147/projects/Ln2/test/test2/1node/1cpu/scratch/88702/node0//statefile.0.tmp


                         BLOCK CPU  Time (seconds): 95.650
                         BLOCK Wall Time (seconds): 97.000

I didn't grep out the nevpt2 energy.

**Comment by bogdanoff** [comment]
@lqhenwunai 
It should be in the pyscf log. I run the `examples/dmrg/02-dmrg_nevpt2.py` and have output similar to the normal NEVPT2.
In my reply I forgot to have `.kernel()` at the end, so maybe the NEVPT2 didn't run. 
it should be `mrpt.NEVPT(mc).compress_approx().kernel()`.
You can optionally specify the `maxM` for NEVPT2. I don't know if it should be larger than for the DMRG itself or not.

**Comment by lqhenwunai** [comment]
@bogdanoff 
Sorry for the silly question, but I don't have the pyscf.log file. I only have the pyscf output cr2-1.50.out,  the dmrg.out and the slurm.out.

**Comment by bogdanoff** [comment]
@lqhenwunai 
Sorry for confusion, I have it in `cr2-1.50.out` which I referred to as log.

**Comment by lqhenwunai** [comment]
@bogdanoff 
Many thanks, but... I don't have nevpt2 energy either in the cr2-1.50.out.
The attached file is my output. 

For a quick view, the end of my output is:
i = 85  <i|F|i> =   4.23633206
i = 86  <i|F|i> =   9.95787480
    CPU time for 1-step CASSCF    612.79 sec, wall time  13398.57 sec
CASSCF energy = -2099.30172699348
CASCI E = -2099.30172699348  E(CI) = -242.524186146971  S^2 = 0.0000000
Use compressed mps perturber as an approximation


[cr2-1.50.txt](https://github.com/pyscf/pyscf/files/4327414/cr2-1.50.txt)

**Comment by hczhai** [comment]
(1) Check if there is any error message in `slurm.out`.
(2) Try if you can get the correct answer for this simple example:

```
    >>> from pyscf import gto, scf, mcscf, dmrgscf, mrpt
    >>> mol = gto.M(atom='C 0 0 0; C 0 0 1', basis='631g')
    >>> mf = scf.RHF(mol).run()
    >>> mc = dmrgscf.DMRGSCF(mf, 4, 4)
    >>> mc.kernel()
    -75.3374492511669
    >>> mrpt.NEVPT(mc).compress_approx().kernel()
    -0.10474250075684
```

(3) If you are using only one CPU, in `pyscf/dmrgscf/settings.py`, try if `MPIPREFIX = ''` works.

**Comment by lqhenwunai** [comment]
@hczhai

No, I cannot reproduce the simple calculation. Here is my output:

converged SCF energy = -75.1786268956198
CASSCF energy = -75.3374492510513
CASCI E = -75.3374492510513  E(CI) = -4.7617142418075  S^2 = 0.0000000
......production of RDMs took       0.59 sec
......reading the RDM took          0.01 sec
Traceback (most recent call last):
  File "simple.py", line 7, in <module>
    mrpt.NEVPT(mc).compress_approx().kernel()
  File "/public1/home/sc40147/pyscf/pyscf/mrpt/nevpt2.py", line 737, in kernel
    tol=self.tol)
  File "/public1/home/sc40147/pyscf/pyscf/dmrgscf/nevpt_mpi.py", line 211, in DMRG_COMPRESS_NEVPT
    logger.warn(mc, 'DMRG executable file for nevptsolver %s is the same '
  File "/public1/home/sc40147/pyscf/pyscf/lib/logger.py", line 125, in warn
    flush(rec, '\nWARN: '+msg+'\n', *args)
  File "/public1/home/sc40147/pyscf/pyscf/lib/logger.py", line 110, in flush
    rec.stdout.write(msg%args)
TypeError: not enough arguments for format string

And here is my input:
#!/usr/bin/env python
from pyscf import gto, scf, mcscf, dmrgscf, mrpt
mol = gto.M(atom='C 0 0 0; C 0 0 1', basis='631g')
mf = scf.RHF(mol).run()
mc = dmrgscf.DMRGSCF(mf, 4, 4)
mc.kernel()
mrpt.NEVPT(mc).compress_approx().kernel()

**Comment by lqhenwunai** [comment]
@hczhai

No, I cannot reproduce the simple calculation. Here is my output:

converged SCF energy = -75.1786268956198
CASSCF energy = -75.3374492510513
CASCI E = -75.3374492510513  E(CI) = -4.7617142418075  S^2 = 0.0000000
......production of RDMs took       0.59 sec
......reading the RDM took          0.01 sec
Traceback (most recent call last):
  File "simple.py", line 7, in <module>
    mrpt.NEVPT(mc).compress_approx().kernel()
  File "/public1/home/sc40147/pyscf/pyscf/mrpt/nevpt2.py", line 737, in kernel
    tol=self.tol)
  File "/public1/home/sc40147/pyscf/pyscf/dmrgscf/nevpt_mpi.py", line 211, in DMRG_COMPRESS_NEVPT
    logger.warn(mc, 'DMRG executable file for nevptsolver %s is the same '
  File "/public1/home/sc40147/pyscf/pyscf/lib/logger.py", line 125, in warn
    flush(rec, '\nWARN: '+msg+'\n', *args)
  File "/public1/home/sc40147/pyscf/pyscf/lib/logger.py", line 110, in flush
    rec.stdout.write(msg%args)
TypeError: not enough arguments for format string

And here is my input:
#!/usr/bin/env python
from pyscf import gto, scf, mcscf, dmrgscf, mrpt
mol = gto.M(atom='C 0 0 0; C 0 0 1', basis='631g')
mf = scf.RHF(mol).run()
mc = dmrgscf.DMRGSCF(mf, 4, 4)
mc.kernel()
mrpt.NEVPT(mc).compress_approx().kernel()

**Comment by bogdanoff** [comment]
@lqhenwunai 
It is a small bug in warning printout. 
For now set  `BLOCKEXE` to the parallel Block, and `BLOCKEXE_COMPRESS_NEVPT` to serial one.
Or remove `%s` two times in the text block close to line 211 in `pyscf/dmrgscf/nevpt_mpi.py`
