### ISSUE TITLE
Can't use dft in PySCF 1.7.1 on Mac OS Catalina

### ISSUE THREAD

**Issue by manassharma07** [pyscf/pyscf#553]
I recently formatted my Mac with a fresh install of Catalina.
Then installed Python 3.8.2, and used Pip to install PySCF 1.7.1.

However, my Python scripts using PySCF with xc functional defined using Libxc codes gives segmentation fault 11. 

If I use the functional names instead of codes, ex: 'GGA_X_B88', then I get Unknown XC functional error.

I tried downgrading to 1.7.0, but that doesn't even install due to BLAS library not found error.

On downgrading 1.6.6 I can run the SCF calculation, but however some of the features that I need are not available in that particular version.

The fact that the older version works, makes me think something went wrong later on.

Also, running `from pyscf.dft import libxc` gives the following error:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyscf/dft/libxc.py", line 34, in <module>
    _itrf = lib.load_library('libxc_itrf')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyscf/lib/misc.py", line 72, in load_library
    return numpy.ctypeslib.load_library(libname, _loaderpath)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/ctypeslib.py", line 157, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension`

however, running `from pyscf.dft import xcfun` gives no errors.

PySCF 1.7.0 worked fine on my Mojave install. 

Can you help me about what could be going wrong with Catalina?

**Comment by manassharma07** [comment]
After running some tests on a Catalina VM, I made the following observations regarding some compatibility issues:

For Python version 3.8.1, 3.8.2:   PySCF 1.7.0 won't install, and 1.7.1 installs but importing Libxc doesn't work

For Python 3.5.3 and 3.7.2: PySCF 1.7.0 works correctly with Libxc and PySCF 1.7.1  installs but can't import libxc

So, to conclude: 
On Catalina, PySCF 1.7.1 installs correctly but importing Libxc gives error.

I can't seem to understand what could be the issue.

**Comment by manassharma07** [comment]
Compiling PySCF 1.7.1 from scratch seems to work for now with Python 3.8.1 on macOS Catalina.

So, I guess there was some issue with the pip package.

**Comment by manassharma07** [comment]
I think someone fixed the issue in a new release of Pyscf made available on Pypi.org.
`Psycf 1.7.1.post1` from Pypi successfully installs using pip on Catalina with Python 3.8.2. And importing libxc is also successful.

**Comment by sunqm** [comment]
The wheels for osx were not properly compiled. They are updated on pypi now
