### ISSUE TITLE
Ghost atom with pbc / pp

### ISSUE THREAD

**Issue by btglau** [pyscf/pyscf#556]
Hello,

Both format_pseudo and format_basis in pbc.gto.cell:

https://github.com/pyscf/pyscf/blob/e56433a3585cd0dc7dd7584170d7edc035be2744/pyscf/pbc/gto/cell.py#L76

https://github.com/pyscf/pyscf/blob/e56433a3585cd0dc7dd7584170d7edc035be2744/pyscf/pbc/gto/cell.py#L127

Have not been updated to take advantage of the X- and GHOST- recognizing code in gto.mole:

https://github.com/pyscf/pyscf/blob/e56433a3585cd0dc7dd7584170d7edc035be2744/pyscf/gto/mole.py#L370

Specifically, lines 418-421: 
https://github.com/pyscf/pyscf/blob/e56433a3585cd0dc7dd7584170d7edc035be2744/pyscf/gto/mole.py#L418

I believe there should not be a problem with using ghost atoms and ecp / pp together?

I also believe that this line: https://github.com/pyscf/pyscf/blob/e56433a3585cd0dc7dd7584170d7edc035be2744/pyscf/pbc/gto/cell.py#L163

Should be using "stdsymb" and not "symb".

**Comment by sunqm** [comment]
The problem should be solved in commit 97008722ba492c9d60fa46535f156620355ae933
