### ISSUE TITLE
GW - no space left on device

### ISSUE THREAD

**Issue by mbarbry** [pyscf/pyscf#574]
Dear PySCF developpers,

I tried to run GW calculation with a relatively large molecule, but I got the following error
[pyscf-gw-err.txt](https://github.com/pyscf/pyscf/files/4394467/pyscf-gw-err.txt)

From what I can understand, pyscf tries to write a temporary file which is way too large (~800 GB). I tried to look at the code to find the option to control the size of this file but I could not understand how to do it. I attached the inputs I used 

[inputs.zip](https://github.com/pyscf/pyscf/files/4394489/inputs.zip)

My question is,

Does there is an option to control the size of this temporary file or is it a limitation of the current implementation?

Best regards,
Marc Barbry

**Comment by tberkel** [comment]
Hi Marc,

Simply put, you don't have the on-disk scratch space to run a molecule of this size using PySCF's current GW.  For this method, and many others, PySCF assumes that the 4-index 2-electron integrals (pq|rs) can be stored on disk (strictly speaking, the worst-case integrals for GW have one occupied index and three virtual indices, like (ov|vv).  As you saw, a molecule of the size you tried will require about 1TB of scratch space.

Table I of our most recent PySCF paper (https://arxiv.org/abs/2002.12531) shows that most beyond-mean-field methods can only handle about 1500 orbitals.

My group and @gkc1000 's group are both in the process of adding new GW implementations, with varying support for density-fitted integrals, which may help slightly with the accessible system sizes.  Primarily, these new implementations will be faster (lower scaling) than the current implementation.

**Comment by mbarbry** [comment]
Hi @tberkel,

Thank you for your clear answer.
I was not expecting that it would require so much disk space!

I look forward to trying this new implementation.
