### ISSUE TITLE
problem of installing block with pyscf  

### ISSUE THREAD

**Issue by Wei-TingChen777** [pyscf/pyscf#576]
Dear all,

I have two problem here. While import dmrg , it show that I don't have the library  'libicmpspt' in the line42 of dmrgscf/dmrgci.py.
And with python3.8 when I # the line42 of dmrgci.py , the error shows TypeError: a bytes like object is required , not 'str' 
Since I was told that  the dmrgci.py works for the python2.7 , I then tried  to install with python2.7 . The error got differently , it showed that

`block.spin_adapted-1.5.3: error while loading shared libraries: libboost_system.so.1.55.0: cannot open shared object file: No such file or directory`

Here is my installation steps.
install miniconda, create myenv, conda activate myenv , pip install pyscf , and copy the dmrgscf  folder from github(https://github.com/pyscf/pyscf/tree/master/pyscf) into the path-to-pyscf/pyscf ,
download the precompiled binary files through here for Block-1.5 (stackblock)
https://sanshar.github.io/Block/overview.html#use-block-with-pyscf-package
and modify the settings.py in the dmrgscf folder.
BLOCKEXE = '/home/wt07/block.spin_adapted-1.5.3'

Any suggestions?

Many thanks.

**Comment by gkc1000** [comment]
Have you checked hat libboost*** is in your LD_LIBRARY_PATH?

**Comment by Wei-TingChen777** [comment]
I have used the code
 export LD_LIBRARY_PATH="/home/wt07/boost_1_55_0/stage/lib:$LD_LIBRARY_PATH"
but it still gets the error when I execute the  block.spin_adapted-1.5.3.
(mE) [wt07@nano ~]$ ./block.spin_adapted-1.5.3 input2.dat > output2.dat
./block.spin_adapted-1.5.3: error while loading shared libraries: libboost_mpi.so.1.55.0: cannot open shared object file: No such file or directory

**Comment by Wei-TingChen777** [comment]
Sorry , I find out that there is really no libboost_mpi.so.1.55.0 file in the /home/wt07/boost_1_55_0/stage/lib

**Comment by gkc1000** [comment]
Did you resolve this? If so, I will close the issue.

**Comment by Wei-TingChen777** [comment]
Yes, I resolved this. Thank you very much
