### ISSUE TITLE
Advanced example 031-density.py does not output the density in the implied format

### ISSUE THREAD

**Issue by computative** [pyscf/pyscf#578]
Dear sir/madam,

I want to output the electron density of a 3-dimensional electronic state, and Qiming Sun kindly pointed out that advanced example 031 (https://github.com/pyscf/pyscf/blob/master/examples/1-advanced/031-density.py) shows how to do this.

The code indicates that the output should be a 3-dimensional array of the electron density, but the output is[, of course,] a 1-dimensional output. I have tried to change the array to a 3-dimensional array using numpy.array.reshape(), but that doesn't reshape the coordinates correctly.

Is there some way to reshape the 1-dimensional output be reshaped to a 3-dimensional array correctly? The source code seems to indicate that it isn't a bug.

Thank you for your time.

Kind regards,
Marius Jonsson

**Comment by fishjojo** [comment]
What do you mean by 3-dimensional electronic state?
The example computes the ccsd 1-electron density on a uniform grid, with rho[i] corresponding to grids[i].
