### ISSUE TITLE
seems some randomness in molecular orbital coefficients

### ISSUE THREAD

**Issue by jiachenchem** [pyscf/pyscf#580]
I am running following code to get molecular coefficients. And each run gives me either 0.33745244106197486 or -0.3374524410619699. I am baffled by this randomness. This will give a sign difference in some molecular orbital integrals. So, I think it is physical. Can you help me to understand this randomness? Appreciate it!

from pyscf import gto, scf
mol = gto.Mole()
mol.atom = [['O', [0, 0, 0]],
['H', [0.757, 0.586, 0.0]],
['H', [-0.757, 0.586, 0.0]]]
mol.spin = 0
mol.unit = 'Angstrom' # in Angstrom
mol.verbose = 6
mol.output = 'scf.out'
mol.basis = '6-31g'
mol.symmetry = False
mol.build()
mf = scf.RHF(mol)
mf.kernel()
print(mf.mo_coeff[3,6])

**Comment by gkc1000** [comment]
Hi Jia,

The orbitals, as eigenstates, are only defined up to a phase (and for real
orbitals only up to a sign). Eigenvalue routines will return different
phases based on small changes in the matrix on the level of
non-deterministic numerical rounding in multithreaded programs. If you want
to keep a consistent sign you have to do so manually (e.g. largest element
is +ve or by referring to a previous run).

Garnet

**Comment by jiachenchem** [comment]
Hi Garnet,

Thank you very much! I didn't know this before. This phase freedom will have an effect on the sign of CI coefficients and second-quantized Hamiltonian parameters. I finally found the root...
