### ISSUE TITLE
mo_coeff are the same for RHF and CASCI calculation even when mc.natorb = True

### ISSUE THREAD

**Issue by mintmemory** [pyscf/pyscf#581]
Hello,

I have tested CASCI calculations with different combinations of the mc.canonicalization and mc.natorb options (mc is a CASCI object). I compared mo_coeff from RHF and CASCI calculations. As far as I understand, mo_coeff of CASCI calculations for core, active, and virtual orbitals can be changed depending on the options. However, when mc.natorb = True and mc.canonicalization = False, mo_coeff are the same for RHF and CASCI calculations. This seemed weird since I was expecting that mo_coeff for the active orbitals should be changed. Did I miss or misunderstand something?

I used PySCF ver. 1.7.0, and the script I used is as below:

import numpy as np
import pyscf
from pyscf import scf, gto, mcscf, mrpt

# Test for a simple N2 molecule
mol = gto.M(
    atom = 'N 0 0 0; N 0 0 15.0',
    spin = 0)
mol.basis = 'ccpvdz'

# Run RHF calculation
myhf = scf.RHF(mol)
myhf.kernel()

# Run CASCI calculation.
num_act_e = 4
num_act_orb = 4
mc = mcscf.CASCI(myhf, num_act_orb, num_act_e)
# For easy comparison between HF and CASCI orbitals, I chosen active orbitals above core orbitals.
num_core_orb = mc.ncore
cas_list = np.linspace(num_core_orb, num_core_orb+num_act_orb-1, num_act_orb, dtype=int)
mo = mc.sort_mo(cas_list, base=0)

mc.canonicalization = False
mc.natorb = True

mc.kernel(mo);

# differences of the mo_coeff from the HF and CASCI are checked
core_diff = np.sum(np.abs(myhf.mo_coeff[:, :num_core_orb] - mc.mo_coeff[:, :num_core_orb]))
act_diff = np.sum(np.abs(myhf.mo_coeff[:, num_core_orb:num_core_orb+num_act_orb] - mc.mo_coeff[:, num_core_orb:num_core_orb+num_act_orb]))
virt_diff = np.sum(np.abs(myhf.mo_coeff[:, num_core_orb+num_act_orb:] - mc.mo_coeff[:, num_core_orb+num_act_orb:]))
print(f"core orb diff = {core_diff}")
print(f"active orb diff = {act_diff}")
print(f"virtual orb diff = {virt_diff}")

**Comment by bogdanoff** [comment]
Currently `mc.natorb` option is only used if `mc.canonicalization = True`. I also find it a bit confusing.

You should get what you want if you use `mc.cas_natorb_()` to set mc.mo_coeff to natural orbitals.
You also can get them with `nat_mo_coeff, nat_ci, nat_occ = mc.cas_natorb()` or 
`nat_mo_coeff, nat_ci, nat_occ = mcscf.addons.cas_natorb(mc)` functipns.

**Comment by wjeong2020** [comment]
Thank you, bogdanoff. I can get what I want as you suggested.

**Comment by sunqm** [comment]
> Currently `mc.natorb` option is only used if `mc.canonicalization = True`. I also find it a bit confusing.
> 
> You should get what you want if you use `mc.cas_natorb_()` to set mc.mo_coeff to natural orbitals.
> You also can get them with `nat_mo_coeff, nat_ci, nat_occ = mc.cas_natorb()` or
> `nat_mo_coeff, nat_ci, nat_occ = mcscf.addons.cas_natorb(mc)` functipns.

For some historical reason, the three attributes natorb, sorting_mo_energy, and canonicalization were introduced to transform the orbitals in different scenarios. I was pretty struggling with the treatment of them.

Generally, without enabling canonicalization, I don't want the orbitals to be changed unexpectedly.

**Comment by bogdanoff** [comment]
@sunqm,
I think in the most codes inactive and virtual orbitals are always canonicalized, and the options of canonical or natural orbitals exist for active space only.
I appreciate the importance of keeping orbitals unchanged for DMRG solver.
But initially I was expecting that `natorb = True` would give me the natural orbitals in active space.
Now it doesn't matter anymore :) .
