### ISSUE TITLE
incorrect atomic mass in pbc cell

### ISSUE THREAD

**Issue by yangcal** [pyscf/pyscf#582]
cell.atom_mass_list() is inherited from mole object. But atom charge in pbc is modified due to pseudopotential, not the "real" charge. Therefore this line ends up calling the wrong mass
https://github.com/pyscf/pyscf/blob/5468dd8788d86ddca58fa80e0d6b10fb1789b033/pyscf/gto/mole.py#L1777

**Comment by fishjojo** [comment]
shoud be fixed in ee16e2071d079e8ec5f09c2c5a8486b36b863471
please verify
