### ISSUE TITLE
Strange CC correlation energy when direct=True

### ISSUE THREAD

**Issue by ssnam92** [pyscf/pyscf#591]
When I tried to obtain a CCSD(T)/CBS with few basis sets, I found some strange trends on correlation energy;

aug-cc-pVDZ -5298.5412977457  -0.7318986520  -0.0319750321
aug-cc-pVTZ -5298.7273292231  -0.8647968762  -0.0467250656
aug-cc-pVQZ -5298.7415494852  -0.6952006944  -0.0413314163

Where the energies are HF, Ec(CCSD), and Ec(T). 
When basis increase from T to Q, |Ec| decreases dramatically.
I turned on a **direct** option.
The test system has 10 atoms, 49 occupied orbitals, 34 frozen orbitals, (i.e. 15 active occupied) and 151, 345, 641 virtual orbitals for D, T, and Q basis sets, respectively.
I set max_memory to 184320, and peak memory usage during Q basis calc was approx. 125GB.

I didn't compare with direct=False, but I tried **density fitting**.
I got the result

aug-cc-pVDZ -5297.1922485582  -0.7311091582  -0.0319500985
aug-cc-pVTZ -5298.7272007961  -0.8665516173  -0.0467431834
aug-cc-pVQZ -5298.7415026762  -0.9084953783  -0.0501521167

which makes sense. 
I tried to reproduce this phenomenon, but it seems this only appears when the system size is large.

Any help will be very appreciated.

**Comment by fishjojo** [comment]
can you share the input file?

**Comment by ssnam92** [comment]
Sure

from pyscf import gto,scf,lib,cc
lib.num_threads(16)
def get_mol(bas):
  mol = gto.Mole()
  mol.build(
    atom='''
C     -1.416896     0.946485     0.927520
C     -0.727402     0.061361     0.215895
C      0.727898    -0.058068     0.120184
C      1.417353    -0.943207    -0.591459
H     -2.494611     0.948938     0.929540
H     -0.903988     1.686100     1.522164
Br    -1.733497    -1.219989    -0.815684
Br     1.733951     1.224074     1.150633
H      2.495070    -0.945989    -0.593116
H      0.904423    -1.682504    -1.186477
''',
    verbose=0,
    basis = bas,
    max_memory=184320
    )
  return mol

for bas in [ 'aug-cc-pVDZ', 'aug-cc-pVTZ', 'aug-cc-pVQZ' ]:
  mol=get_mol(bas)
  myHF=scf.RHF(mol)
  myHF.conv_tol_grad=1e-6
  eHF=myHF.kernel()

  myCC=cc.CCSD(myHF)
  myCC.frozen=34
  myCC.direct=True
  eCC=myCC.kernel()[0]

  eCT=myCC.ccsd_t()
  print(f'{bas} {eHF:.10f} {eCC:.10f} {eCT:.10f}')

(Sorry but I don't know how to put my code neatly)
System and version info:

System: uname_result(system='Linux', node='b00', release='3.10.0-862.el7.x86_64', version='#1 SMP Fri Apr 20 16:44:24 UTC 2018', machine='x86_64', processor='x86_64')  Threads 16
Python 3.7.4 (default, Aug 13 2019, 20:35:49)
[GCC 7.3.0]
numpy 1.17.4  scipy 1.4.1
Date: Sat Apr 25 10:55:28 2020
PySCF version 1.7.1

Thanks

**Comment by fishjojo** [comment]
Setting `direct=False` gives the same numbers.
[qz.txt](https://github.com/pyscf/pyscf/files/4538193/qz.txt)

**Comment by ssnam92** [comment]
Then it's not because of the direct option.
But still, why two correlation energies with/without density fitting are so different?

**Comment by sunqm** [comment]
There are two possible reasons. First, the density fitting auxiliary basis might not be good enough. Second, the linear dependency due to diffused AO basis and larger basis set can cause larger numerical noise. I'd trust the direct=True results without density fitting.

**Comment by fishjojo** [comment]
fixed in 860c139
