### ISSUE TITLE
input with yaml or json config

### ISSUE THREAD

**Issue by sunqm** [pyscf/pyscf#593]
It would be helpful to provide input parser to parse yaml or json config, for high throughput data generation. A similar request was mentioned in #269. I think we can learn from Psi4's input language, and design something fitting better into the model of data generation pipeline. Let's set it a milestone in pyscf 2.0 design.

**Comment by chenpeizhi** [comment]
How about supporting [toml](https://github.com/toml-lang/toml)?

**Comment by sunqm** [comment]
This feature is implemented in another repo https://github.com/pyscf/pyscfcli
Let's discuss more in that repo

**Comment by sunqm** [comment]
> How about supporting [toml](https://github.com/toml-lang/toml)?

Toml is considered in https://github.com/pyscf/pyscfcli , although not utlizing all features of toml.
