### ISSUE TITLE
libsemiempirical.so documentation

### ISSUE THREAD

**Issue by notoriousntb** [pyscf/pyscf#597]
Hi, I am trying to go play around/test the am1 semi-empirical method - I understand this is still being tested . It calls for the 'libsemiempirical.so' library but there is no mention of this library on the pyscf documentation. Who should I contact to get a copy of the source code/documentation for this library? 

PS: This is my first time working with C libraries so I might have confused myself somewhere.

**Comment by gkc1000** [comment]
Did you build pyscf? It is built from the files in pyscf/lib/semiempirical.

**Comment by notoriousntb** [comment]
Thanks for the quick reply. That was indeed the case.

**Comment by dpadula85** [comment]
Sorry for writing here, I got the same problem with the library. I tried both installing through `pip` and compiling from source, the library is still missing, preventing from using AM1. Any suggestion?

I wrote more [here](https://github.com/pyscf/semiempirical/issues/2)
