### ISSUE TITLE
Non integer nuclear charge

### ISSUE THREAD

**Issue by MilaimKas** [pyscf/pyscf#601]
Hi,
I was wondering if it is possible to modify the nuclear charge of a given atom without changing the number of electrons, for example Z=8.4 instead for oxygen atoms. This "trick" is sometimes use to stabilize and obtain electronic resonances for unstable anion states.

**Comment by jamesETsmith** [comment]
Sorry @MilaimKas I don't think you can

**Comment by gkc1000** [comment]
There's no way to do this in the input. However, if you supply a custom
function for the 1-electron integrals, by scaling the nuclear-electron
integral, then it will work. This is pretty straightforward, see e.g.
https://github.com/pyscf/pyscf/blob/master/examples/gto/20-ao_integrals.py
for an example to call the nuclear-electron integral, and look inside
https://github.com/pyscf/pyscf/blob/master/examples/scf/40-customizing_hamiltonian.py
to see how you can customize the Hamiltonian.

**Comment by MilaimKas** [comment]
Thank you very much for your respond !
Scaling the nuclear-electron integral would imply the total nuclear charge of the molecule to be modified. Even though it would be nice to have control over the nuclear charge of individual atoms, this is already very useful.

**Comment by sunqm** [comment]
In relatively new release (>=1.7.1), there is a function created to handle MM particles. This might be even simpler to handle the non-integer nuclear charge
```
from pyscf.qmmm.mm_mole import create_mm_mol
mm_mol = create_mm_mol(coords_of_MM_particles, charges_of_MM_particles)
mol = pyscf.M(atom='...',...)
vmat = (mol + mm_mol).intor('int1e_nuc')
```
The relevant module is implemented here 
 https://github.com/pyscf/pyscf/blob/master/pyscf/qmmm/mm_mole.py
