### ISSUE TITLE
pip installation - ligomp conflict

### ISSUE THREAD

**Issue by mbarbry** [pyscf/pyscf#603]
Dear PySCF developers,

we are developing a program that depends on PySCF called [pynao](https://gitlab.com/mbarbry/pynao) (in fact we are spitting the nao code from PySCF repository https://github.com/cfm-mpc/pyscf/tree/nao2). When installing PySCF via pip, I get the following error when importing `pynao`

      File "/home/marc/anaconda3/lib/python3.7/site-packages/pynao/m_libnao.py", line 10, in <module>
        lib_sparsetools = CDLL("{}/libsparsetools.so".format(root))
      File "/home/marc/anaconda3/lib/python3.7/ctypes/__init__.py", line 364, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: /home/marc/anaconda3/lib/python3.7/site-packages/pyscf/lib/libgomp.so.1: version `GOMP_4.0' not
    found (required by /home/marc/anaconda3/lib/python3.7/site-packages/pynao/libsparsetools.so)

Our code needs also openmp for C and Fortran source compilation, and it seems that the `libgomp` library included with the PySCF wheel enter in conflict with the system one.

When installing PySCF via conda, such error does not occur. My questions are

* is it really necessary to include `libgomp` with pyscf wheel?
* if yes, how do you know how could I avoid such conflict between openmp libraries?

Best regards,
Marc Barbry

**Comment by sunqm** [comment]
Is the gomp provided by conda? If not, which OS and which version of gomp and pthread do you use?

**Comment by sunqm** [comment]
I removed libgomp from pyscf-1.7.2 wheels. Does it work in your box?

**Comment by mbarbry** [comment]
Hi,

When installing via conda, the libgomp is not included with pyscf.
Thanks for removing libgomp from the wheels, I will give it a try as soon as possible.

**Comment by mbarbry** [comment]
I'm still getting the issue with pyscf version 1.7.2
As you can see on the screenshot below, libgomp is still included in pyscf.

![Screenshot at 2020-05-15 07-55-31](https://user-images.githubusercontent.com/14218658/82062649-b4da7f80-96ca-11ea-8c4d-e6505c1d6797.png)

**Comment by sunqm** [comment]
In 1.7.2-2 build, libgomp was renamed to a random name. Hopefully it solves this issue.
