### ISSUE TITLE
Nuclear repulsion integral from a single atom

### ISSUE THREAD

**Issue by januseriksen** [pyscf/pyscf#608]
At the risk of inquiring about something trivial in ```moleintor```, how do I compute the nuclear attraction integral associated with a single atomic centre of a molecular system? I know how to get the full nuclear attraction via ```'int1e_nuc'```, but how do I compute the contributions from the individual nuclei (scaled by the appropriate nuclear charge)?

Cheers,
Janus

**Comment by gkc1000** [comment]
Either set up a fakemol with one atom, or call int1e_rinv w.r.t. a Gaussian
that is a distance A away (so you have inv(|r-A|)) and multiply by Z.

**Comment by januseriksen** [comment]
Got it, I figured out how to use ```mol.with_rinv_origin()``` to achieve what I needed. Thanks, Garnet.
