### ISSUE TITLE
Modifying/creating a new chk file

### ISSUE THREAD

**Issue by bsenjean** [pyscf/pyscf#612]
Dear PySCF developers,

I want to update a chk file with new MO coefficients that I generate with an external code. In the documentation, I could find how to restart and load from a chk point, but couldn't find how to rewrite a new one from an old one by just modifying some information.

Typically, I do a standard SCF calculation and I have then access to the wave function and molecular object, as well as to the associated chk file.

Then, I read new ```mo_coeff```, which I would like to set in the wavefunction object:

```
mf.mo_coeff = new_coeff
mf.chkfile = "new_chk_file"
# how to write it without doing an SCF calculation again ?
```

Finally, I want to create a new chk file which could be used latter on, either to restart the SCF calculation (and check that my transformation is correct and converges in one iteration) or into a post-SCF one. How to use it after generating it is clear in the documentation.

Thank you for your help !
Bruno

**Comment by shivupa** [comment]
Hi `pyscf.scf.chkfile.dump_scf` might help [here](https://sunqm.github.io/pyscf/_modules/pyscf/scf/chkfile.html#dump_scf) 
```
from pyscf.scf.chkfile import dump_scf
e_tot = 0.0 # just set e_tot to something so this can be written out
dump_scf(mol, "new_chk_file", e_tot, new_mo_energy, new_coeff,  new_mo_occ)
```
You might not care about the mo_energy or mo_occ so you could pass the old values there or just zeros in the correct shape. If you do care, you could create a new scf object using the new orbitals and run a zero iteration scf which should diagonalize the fock operator with the new orbitals according to #495. (This will create a new e_tot you could use too).

**Comment by sunqm** [comment]
There are various ways to load old scf results. I often use the python intrinsic
attribute __dict__

```
mf.__dict__.update(pyscf.scf.chkfile.load('old_chk_file', 'scf'))
```

If you just need to feed the old scf results into a new scf calculation

```
dm = mf.from_chk('old_chk_file')
mf.kernel(dm)
```

On Thu, May 14, 2020 at 10:07:29AM -0700, Bruno Senjean wrote:
> Dear PySCF developers,
> 
> I want to update a chk point with new MO coefficients that I generate with an external code. In the documentation, I could find how to restart and load from a chk point, but couldn't find how to rewrite a new one from an old one by just modifying some information.
> 
> Typically, I do a standard SCF calculation and I have then access to the wave function and molecular object, as well as to the associated chk file.
> 
> Then, I read new ```mo_coeff```, which I would like to set in the wavefunction object:
> 
> ```
> mf.mo_coeff = new_coeff
> mf.chkfile = "new_chk_file"
> # how to write it without doing an SCF calculation again ?
> ```
> 
> Finally, I want to create a new chk file which could be used latter on, either to restart the SCF calculation (and check that my transformation is correct and converges in one iteration) or into a post-SCF one. How to use it after generating it is clear in the documentation.
> 
> Thank you for your help !
> Bruno
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyscf/pyscf/issues/612

--

**Comment by bsenjean** [comment]
Thank you, ```dump_scf``` was what I was looking for ! I checked that my unitary transformation (dumped into a chk file) does lead to a SCF convergence with a single iteration  when loaded and run by PySCF again. So I guess it works fine.

Just for the record, I also tried the ```max_cycle = 0``` option like this:

```
def scf_from_pyscf():
    mol = gto.M(
          atom = """O 0. 0.00000 0.59372
          H 0. 0.76544 -0.00836
          H 0. -0.76544 -0.00836
         """,
          basis = "unc-sto-3g",
          symmetry = 0,
          spin = 0,
          charge = 0,
          verbose = 5,
          cart = True,
          output = "original.out")
    scf_wfn = scf.ROHF(mol)
    scf_wfn.kernel()
    return mol, scf_wfn # those are the molecular and wavefunction object of pyscf.

mol, scf_wfn = scp_from_pyscf()

# Read my new transformed coefficients:
scf_wfn.mo_coeff = new_coeff
mol.output = "restart.out"
scf_wfn.max_cycle = 0
scf_wfn.kernel()

e_tot = 0.0 # just set e_tot to something so this can be written out
dump_scf(mol, "new.chk", e_tot, scf_wfn.mo_energy, scf_wfn.mo_coeff,  scf_wfn.mo_occ)
dm = scf_wfn.init_guess_by_chkfile("new.chk")
scf_wfn.kernel(dm)
```

This gives me an output with the standard SCF, the max_cycle = 0 and the one which restart by reading the new.chk file.

Problem is: I get the iteration 0 of the standard SCF here, not the iteration 0 with my new coefficients. What I am doing wrong ?

**Comment by fishjojo** [comment]
In your second SCF calculation, you need to provide an initial guess for the density matrix.
```
scf_wfn.mo_energy = new_mo_energy                                           
scf_wfn.mo_coeff = new_coeff                                             
dm = scf_wfn.make_rdm1(mo_coeff = scf_wfn.mo_coeff, mo_occ = scf_wfn.mo_occ)    
scf_wfn.max_cycle = 0                                                           
scf_wfn.kernel(dm0 = dm)             
```

**Comment by bsenjean** [comment]
Fantastic. Thank you all for your help !
