### ISSUE TITLE
Preserving symmetry when running HF

### ISSUE THREAD

**Issue by louishamaide** [pyscf/pyscf#613]
Hi all, 
I am using PySCF to get the orbitals of the Fluorine atom (Z=9), among others. I noticed the orbitals where not spherically symmetric (the mo_coeff of my 2p-states where not the same in all three directions x, y, z). I therefore tried to modify the initial density matrix guess, as suggested in the following example file: "examples/scf/31-cr_atom_rohf_tune_init_guess.py"
, which can also be found here: https://github.com/pyscf/pyscf-doc/blob/master/examples/scf/31-cr_atom_rohf_tune_init_guess.py

The file uses Chromium as an example. I've changed the file to a solution where the input is the RHF orbitals of a Fluorine 1+ ion, plugged into a Fluorine atom with spin 1, since the outer subshell is 2p^5. This doesn't yield spherical symmetry... I have tried other things such as initial guess Fluorine 5+ plugged into Fluorine spin 5, which isn't a real occurring configuration, but does yield spherical symmetry. And since the alpha and beta energies are different I don't trust these results. Other ideas might involve complex solutions and superpositions of Slater determinants, any ideas?

Furthermore even without changing the initial guess this atom already yields symmetric states. Same goes for Chromium which uses charge 6 as an initial guess and spin 6 as the result: the initial guess is not necessary to obtain spherical symmetry. So I'm lacking proof of a case where this works.

Can somebody explain to me why this isn't yielding spherically symmetric results? The HF equations don't depend on m or s-quantum numbers, so I didn't expect these differences to appear. Any ideas how to get a spherically symmetric p-shell in Fluorine?

Thank you for your help!

**Comment by gkc1000** [comment]
The HF equations are non-linear and therefore the solutions will not always
respect the symmetry of the true Hamiltonian unless explicitly constrained.
In this case, there are 7 electrons in the p-shell and by default the
occupancy will be 2, 2, 1, breaking the spherical symmetry. To obtain a
spherical solution, you have to distribute an equal (fractional) number of
electrons in each p orbital. This can be done using the scf.addons.frac_occ
function as shown in:

https://github.com/pyscf/pyscf/blob/master/examples/scf/54-fractional_occupancy.py

**Comment by louishamaide** [comment]
> The HF equations are non-linear and therefore the solutions will not always respect the symmetry of the true Hamiltonian unless explicitly constrained. In this case, there are 7 electrons in the p-shell and by default the occupancy will be 2, 2, 1, breaking the spherical symmetry. To obtain a spherical solution, you have to distribute an equal (fractional) number of electrons in each p orbital. This can be done using the scf.addons.frac_occ function as shown in: https://github.com/pyscf/pyscf/blob/master/examples/scf/54-fractional_occupancy.py
> […](#)

Thank you gkc1000. Just to check I understand, does this also explain why when one runs a simple PySCF code such as:

`from pyscf import gto,scf
mol = gto.Mole()
mol.build(
    verbose = 5,
    output = None,
    symmetry = True,
    atom = [['Xe',(0, 0, 0)], ],
    basis = 'def2-qzvp',
    charge = 0,
    spin = 0,
)
mf = scf.HF(mol)
mf.kernel()
mf.analyze()`

for Xenon, it doesn't seem the symmetry is perfect either (ie orbitals 2, 3, 4 which seem to be the 2p states have slightly different coefficients, and same goes for 3d orbitals)?

**Comment by gkc1000** [comment]
In principle it's possible but I would expect a spherical solution for Xe.

Can you:
1. check for neon
2. Post your output for Xe

**Comment by louishamaide** [comment]
1/ For Neon I get symmetry. Here are the mo_coeff(): 
<img width="525" alt="image" src="https://user-images.githubusercontent.com/57094019/82262158-50345480-9958-11ea-9db3-16574a0c0bc4.png">
And the orbital energies are the same.

2/ For Xenon however here are the mo_coeff() (same code as Neon, but now visible differences for 2p states):
<img width="525" alt="image" src="https://user-images.githubusercontent.com/57094019/82262334-a1dcdf00-9958-11ea-84fc-eaa30fc2609d.png">
and
<img width="525" alt="image" src="https://user-images.githubusercontent.com/57094019/82263107-195f3e00-995a-11ea-85ff-d6b97c5628b4.png">
(Second image is MO#6 through MO#10, which seem to be the 3d states)
And the energies confirm the difference as well:
<img width="525" alt="image" src="https://user-images.githubusercontent.com/57094019/82263301-7ce96b80-995a-11ea-84fb-6042f27f635b.png">

(Differences appear for any noble gas bigger than Krypton (Xenon, Radon...).)

> In principle it's possible but I would expect a spherical solution for Xe. Can you: 1. check for neon 2. Post your output for Xe
> […](#)

**Comment by gkc1000** [comment]
Ok, this is because pyscf is setting the symmetry to Dinfh (as seen from
the labels) where px and py are in the same irrep but pz is not. Then
Hartree-Fock is finding a symmetry breaking solution. I'm curious if the
initial atomic guess is symmetric. Can you print out the mo coeffs for Xe
after 0 iterations?

**Comment by louishamaide** [comment]
Sorry gkc1000, after some searching I'm not sure how to print the mo_coeffs after 0 iterations. The scf.hf.kernel() uses a DM and I'm not quite certain how to get the mo_coeff from it, just from looking at how make_rdm1() and get_init_guess() work...

In any case, if I want to get a symmetric Xenon atom, can I use a different symmetry than Dinfh? I've tried D2h and D3h, to no avail. Also, how do I impose partial occupancy on all of the p shell electrons? For Fluorine using frac_occ() sets mo_occ=2/3 for 2p beta electrons, but I'd like 5/6 for all 2p electrons.

Thank you.

> Ok, this is because pyscf is setting the symmetry to Dinfh (as seen from the labels) where px and py are in the same irrep but pz is not. Then Hartree-Fock is finding a symmetry breaking solution. I'm curious if the initial atomic guess is symmetric. Can you print out the mo coeffs for Xe after 0 iterations?
> […](#)

**Comment by fishjojo** [comment]
You may try using the def2-qzvp ECP, or using other basis sets such as qzp.

**Comment by sunqm** [comment]
> Hi gkc1000, yes it seems the Dinfh is forcing the x-y occupancies and mo_coeffs to be the same. I've set max_cycle=0 in my HF, and the results (occupancy, mo_coeffs) came out symmetric for the initial guess.
> 
> Any ideas how to get spherical symmetry for Xe?
> 
> Thanks
> 
> Thank you.
> 
> > Ok, this is because pyscf is setting the symmetry to Dinfh (as seen from the labels) where px and py are in the same irrep but pz is not. Then Hartree-Fock is finding a symmetry breaking solution. I'm curious if the initial atomic guess is symmetric. Can you print out the mo coeffs for Xe after 0 iterations?
> > […](#)

I don't understand why this calculation breaks the degeneracy of relevant orbitals. Xe should be a very typical closed shell system. Do you get reasonable orbital degeneracy using HF?

**Comment by sunqm** [comment]
E.g.
```
mol.build( verbose = 4, output = None, symmetry = True,
          atom = [['Xe',(0, 0, 0)], ],
          ecp = 'stuttgart',
          basis = 'def2-qzvp', charge = 0, spin = 0, )
```
should give reasonable degeneracy.

**Comment by louishamaide** [comment]
Hi Qiming,

Thank you for your reply. You’re right that I get the right degeneracy this way, but it seems either the basis has changed or the coefficients have changed. I’m looking for a description of all orbitals, even core. Why are the results that appear very different? And should I trust these results for the core orbitals?

Thank you

On Jun 21, 2020, at 2:01 AM, Qiming Sun <notifications@github.com> wrote:

﻿

E.g.

mol.build( verbose = 4, output = None, symmetry = True,
          atom = [['Xe',(0, 0, 0)], ],
          ecp = 'stuttgart',
          basis = 'def2-qzvp', charge = 0, spin = 0, )


should give reasonable degeneracy.

**Comment by gkc1000** [comment]
With an ECP, the core orbitals are removed.

I don't have a good answer for why Xe breaks the degeneracy, one is a bit
at the mercy of the HF numerics, which can in principle converge to
nonsymmetric solutions. As I mentioned, one would have to enforce
specifically that the SO3 symmetry is kept during the numerical
optimization, and PySCF does not currently offer that. Some additional code
would have to be written. If you need this, this can be tagged as a feature
request.

**Comment by fishjojo** [comment]
The latest pyscf should support SO3 symmetry. But using def2-tzvp alone won't converge the symmetry adapted HF calculation. In the original paper of def2-tzvp and def2-qzvp, the basis for Xe was optimized along with an ECP, so it is not designed for all-electron calculation.
