### ISSUE TITLE
Warning "basis set is not loaded" is erroneosly printed for ghost atoms

### ISSUE THREAD

**Issue by bogdanoff** [pyscf/pyscf#617]
With the following example:

```
from pyscf import gto, scf

mol = gto.M(atom='''
ghost-O     0.0 0.0 0.0
O               0.0 0.0 1.0
            ''',
            basis="sto6g")

mol.build()
mf = scf.RHF(mol)
mf.kernel()
```

I get
> No basis found for atom GHOST-O

Message in the SCF block.

**Comment by manassharma07** [comment]
I also get this, but somehow the results are not affected by this. The error comes from line 840 in gto/mole.py

**Comment by fishjojo** [comment]
You can ignore this warning. The bases for ghost atoms are loaded.

**Comment by sunqm** [comment]
Basis sanity check was done when parsing the basis files or basis strings. The check in gto/mole.py L840 is not needed any more. The inaccurate error messge was removed.
