### ISSUE TITLE
Generating integrals using libcint

### ISSUE THREAD

**Issue by manassharma07** [pyscf/pyscf#619]
I could have asked this question in the `libcint`'s GitHub repo, but since I am using PySCF as an interface, I decided to ask here.

I am trying to generate an integral, using the method explained here: https://github.com/sunqm/libcint 

However, it requires me to edit a file `'auto_intor.cl'`. But I am not sure where to find it when I used `pip` to install PySCF. I tried finding it but couldn't.

Do I need to compile `libcint` manually and then use that when compiling PySCF manually? Or I can generate a new integral even if I installed PySCF from `pip`? 

I apologise beforehand if I am missing something obvious.

**Comment by gkc1000** [comment]
clone libcint from github

**Comment by manassharma07** [comment]
So, if I understand correctly, I clone `libcint` and perform the generation and then the existing PySCF should be able to detect the new integral automatically?

**Comment by sunqm** [comment]
You need to compile and install your local branch libcint and disable the
libcint auto compilation in pyscf. The offline installation might be relevant.
http://pyscf.org/pyscf/install.html#installation-without-network

On Tue, May 19, 2020 at 01:08:36PM -0700, Manas Sharma wrote:
> So, if I understand correctly, I clone `libcint` and perform the generation and then the existing PySCF should be able to detect the new integral automatically?
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyscf/pyscf/issues/619#issuecomment-631054266

--

**Comment by manassharma07** [comment]
@sunqm Thanks for clarifying.
