### ISSUE TITLE
TDDFT gradient failure

### ISSUE THREAD

**Issue by yangdatou** [pyscf/pyscf#622]
Dear Qiming,

I was trying to run the TDDFT gradient example in the 'pyscf/examples/grad',
```
yangjunjie@MacBookPro ~/opt/pyscf/examples/grad $ python 06-tddft_gradients.py
converged SCF energy = -76.0267656731182
Excited State energies (eV)
[ 9.15670551 10.92082304 11.76617866]
--------- TDHF gradients for state 1 ----------
         x                y                z
0 O     0.0000000000    -0.0000000000     0.1050660342
1 H    -0.0000000000     0.0715152399    -0.0525330171
2 H     0.0000000000    -0.0715152399    -0.0525330171
----------------------------------------------
converged SCF energy = -76.3875318134592
Traceback (most recent call last):
  File "06-tddft_gradients.py", line 27, in <module>
    mf._numint.libxc = dft.xcfun
AttributeError: module 'pyscf.dft' has no attribute 'xcfun'
```
I tried `python -c 'from pyscf.dft import libxc'` and it did not produce any error messages. However, with `python -c 'from pyscf.dft import xcfun'`, I got
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/yangjunjie/opt/pyscf/pyscf/dft/xcfun.py", line 32, in <module>
    _itrf = lib.load_library('libxcfun_itrf')
  File "/Users/yangjunjie/opt/pyscf/pyscf/lib/misc.py", line 69, in load_library
    return numpy.ctypeslib.load_library(libname, _loaderpath)
  File "/Users/yangjunjie/opt/anaconda3/lib/python3.7/site-packages/numpy/ctypeslib.py", line 152, in load_library
    return ctypes.cdll[libpath]
  File "/Users/yangjunjie/opt/anaconda3/lib/python3.7/ctypes/__init__.py", line 439, in __getitem__
    return getattr(self, name)
  File "/Users/yangjunjie/opt/anaconda3/lib/python3.7/ctypes/__init__.py", line 434, in __getattr__
    dll = self._dlltype(name)
  File "/Users/yangjunjie/opt/anaconda3/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/yangjunjie/opt/pyscf/pyscf/lib/libxcfun_itrf.dylib, 6): Library not loaded: libxcfun.2.0.0.dylib
  Referenced from: /Users/yangjunjie/opt/pyscf/pyscf/lib/libxcfun_itrf.dylib
  Reason: image not found
```

But I have the file `/Users/yangjunjie/opt/pyscf/pyscf/lib/libxcfun_itrf.dylib`. I installed PySCF by compiling core modules, during which I changed the URL from https://github.com/pyscf/pyscf/blob/7ba318ff7cae650b255d5c5b90ed550521d324f0/pyscf/lib/CMakeLists.txt#L151 to https://github.com/pyscf/pyscf/blob/7ba318ff7cae650b255d5c5b90ed550521d324f0/pyscf/lib/CMakeLists.txt#L153

**Comment by gkc1000** [comment]
It is complaining about libxcfun.2.0.0.dylib, can you check that it is in
that directory or in some place accessible via DYLD_LIBRARY_PATH?

**Comment by yangdatou** [comment]
There is no `libxcfun.2.0.0.dylib` in `/Users/yangjunjie/opt/pyscf/pyscf/lib`. But I can find it in `/Users/yangjunjie/opt/pyscf/pyscf/lib/deps/lib`. I added `/Users/yangjunjie/opt/pyscf/pyscf/lib/deps/lib` to `DYLD_LIBRARY_PATH` and the problem was fixed. 

Thank you very much for your help.

Is there a better way to do this?

**Comment by sunqm** [comment]
Either set DYLD_LIBRARY_PATH or add runtime path to the library
```
install_name_tool -add_rpath @loader_path//deps/lib /Users/yangjunjie/opt/pyscf/pyscf/lib/libxcfun_itrf.dylib
```

Setting DYLD_LIBRARY_PATH is more common.

On Sun, May 31, 2020 at 12:49:15PM -0700, Junjie, Yang wrote:
> There is no `libxcfun.2.0.0.dylib` in `/Users/yangjunjie/opt/pyscf/pyscf/lib`. But I can find it in `/Users/yangjunjie/opt/pyscf/pyscf/lib/deps/lib`. I added `/Users/yangjunjie/opt/pyscf/pyscf/lib/deps/lib` to `DYLD_LIBRARY_PATH` and the problem was fixed. 
> 
> Thank you very much for your help.
> 
> Is there a better way to do this?
> 
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyscf/pyscf/issues/622#issuecomment-636519709

--
