### ISSUE TITLE
Calculations stop for EA-EOM-CCSD! 

### ISSUE THREAD

**Issue by sarashaban** [pyscf/pyscf#625]
Hello pyscf developers,

(PySCF/1.6.3)

To do gap estimation, my periodic EA-EOD-CCSD calculations stop for higher k-points (such as 1x3x3 and 2x2x2) tested with different basis sets. System includes 2 tin and 4 oxygen atoms. 
I have decrease the fft mesh size even to [2,2,2](just for testing purpose) and no sucess was seen.

However, this line of ekip, wkip = mykcc.ipccsd(nroots=1, kptlist=[0]) can end without generating error. In the following, I add the main part of input and observed error lines. (just to note that for cell.basis = 'stuttgart_dz' and cell.ecp = 'stuttgart_dz' setting the program was ended even without generating error. 

I apprecite your time.

This is main part of input:
.
.
.

cell.verbose = 4
cell.mesh = [20,20,20]
cell.max_memory = 100000
#cell.precision = 1e-8
cell.build(None,None)

kpts = cell.make_kpts([2,2,2])
kmf = pbcscf.KRHF(cell, kpts).density_fit()

kmf.chkfile='0.chk'
kpoint_energy = kmf.kernel()
print(kpoint_energy)

mykcc = pbccc.KRCCSD(kmf)
mykcc.direct = True

print(mykcc.kernel())
kccsd_energy = mykcc.ccsd()[0]

ekip, wkip = mykcc.ipccsd(nroots=1, kptlist=[0])
ekea, wkea = mykcc.eaccsd(nroots=1, kptlist=[0])

the printed error lines are:

EOM root 0 E = -0.2720893397163592  qpwt = 0.938847
Numpy 1.16 has memory leak bug  https://github.com/numpy/numpy/issues/13808
It is recommended to downgrade to numpy 1.15 or older
WARNING!
  Very diffused basis functions are found in the basis set. They may lead to severe
  linear dependence and numerical instability.  You can set  cell.exp_to_discard=0.1
  to remove the diffused Gaussians whose exponents are less than 0.1.

/opt/ohpc/pub/easybuild/software/h5py/2.9.0-foss-2019a/lib/python3.7/site-packages/h5py-2.9.0-py3.7-linux-x86_64.egg/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  "Use dataset[()] instead.", H5pyDeprecationWarning)
Traceback (most recent call last):
  File "eom.py", line 100, in <module>
    ekea, wkea = mykcc.eaccsd(nroots=1, kptlist=[0])
  File "/opt/ohpc/pub/easybuild/software/PySCF/1.6.3-foss-2019a-Python-3.7.2/pyscf/pbc/cc/eom_kccsd_rhf_ea.py", line 105, in kernel
    adiag = diag(cc, kshift)
  File "/opt/ohpc/pub/easybuild/software/PySCF/1.6.3-foss-2019a-Python-3.7.2/pyscf/pbc/cc/eom_kccsd_rhf_ea.py", line 248, in diag
    cc.imds.make_ea(cc.ea_partition)
  File "/opt/ohpc/pub/easybuild/software/PySCF/1.6.3-foss-2019a-Python-3.7.2/pyscf/pbc/cc/kccsd_rhf.py", line 866, in make_ea
    self.Wvvvv = imd.Wvvvv(t1, t2, eris, kconserv, vvvv_dest)
  File "/opt/ohpc/pub/easybuild/software/PySCF/1.6.3-foss-2019a-Python-3.7.2/pyscf/pbc/cc/kintermediates_rhf.py", line 334, in Wvvvv
    Wabcd = _new(eris.vvvv.shape, t1.dtype, out)
AttributeError: '_ERIS' object has no attribute 'vvvv'

**Comment by xwang862** [comment]
Hi @sarashaban, this issue should have been fixed by pullreq #371. Can you update PySCF and rerun those calculations?

**Comment by sarashaban** [comment]
Dr. Wang,
Thank you som much for addressing. The issue was resolved. 

I also apprecite your response to my following concern. 


There are underlying HF calculations for hybrid functionals. For the finite size correction to the exchange energy I use probe-charge Ewald method. As hybrid functionals include screened exchange or exact exchange, do you think whether I can use TDL for an extrapolation of the correction to the HF exchange for the small isotropic k-point meshes ?
I am asking because you say that "exxdiv=ewald is the code to add the leading correction of Nk^{-1/3}." Do you consider this setting as the finite size correction to the exchange energy? 

(1) If so, extrapolation with the form Nk^{-1/3} of other properties obtained by hybrid functionals is meaningless in your scenario. 
But extrapolation for the correlation energy or EOM-CCSD gap according to your paper (J. Chem. Theory Comput. 2017, 13, 1209−1218) can be done. 
(2) Otherwise, why in your paper (PHYSICAL REVIEW B 101, 165138 (2020)) you have used TDL extrapolation ( Nk^{-1/3} ) for UHF and semilocal PBE?  

Also, I do not see any difference between 'exxdiv=ewald' and 'exxdiv=vcut_sph' results(gap). Do you think with a setting of 'exxdiv=None', I can fairly obtain correction by extrapolating?

**Comment by tberkel** [comment]
There are two separate questions and I'm not sure which you are asking
about, but I'll try to summarize.

- For periodic mean-field calculations with exchange (including HF or
hybrid DFT), then exxdiv=None will give total energies and band gaps that
have a (asymptotic) finite-size error that scales like Nk^{-1/3}.  Using
exxdiv='ewald' will give total energies and band gaps that have a
finite-size error that scales like Nk^{-1}.  (I would guess that the PRB
you reference used exxdiv=None for the UHF calculations and thus
extrapolated the gap using Nk^{-1/3}.

- For periodic IP/EA-EOM-CCSD (and generally all many-body methods), the
"ewald" (Madelung constant) correction is not so straightforward.  When
periodic CCSD band gaps are calculated with PySCF, they will have a
finite-size error that scales like Nk^{-1/3}.

**Comment by gkc1000** [comment]
Just to chime in quickly since the 2020 paper was one of ours: we
extrapolated HF etc. without the ewald correction, so as to get a rough
sense of when we might see the onset of  linearity w.r.t to N^{-1/3}
behaviour in CC, since we could only do 2 different k point sizes in CC.

**Comment by xwang862** [comment]
> Also, I do not see any difference between 'exxdiv=ewald' and 'exxdiv=vcut_sph' results(gap). Do you think with a setting of 'exxdiv=None', I can fairly obtain correction by extrapolating?

Do you mean exactly same results between `exxdiv='ewald'` and `exxdiv='vcut_sph'`? The two options give band gaps that converge a lot faster towards TDL than `exxdiv=None`, maybe their gaps are just close at a large k-mesh? 

> Do you have any documentation for twist averaging in PySCF?

I don't think we have specifically documented twist averaging. But it can easily achieved by providing different (scaled) k-centers to `cell.make_kpts()`. E.g. 
```
from pyscf.pbc import scf

# ... after constructing a cell
kmesh = [2, 2, 2]
kpts = cell.make_kpts(kmesh, scaled_center=[0.11, 0.22, 0.33])  
mymf = scf.KRHF(cell, kpts=kpts)
```

**Comment by sarashaban** [comment]
I apprecite all your quick and detaild responses.
 
I know GDF does not support exxdiv = 'vcut_sph' and   exxdiv=None is supported in GDF (sunqm).

But about the following classes of
pbcscf.KRHF(cell, kpts,exxdiv=None).density_fit()
pbcdft.KRKS(cell, kpts,exxdiv=None).density_fit()

I get warnnig a message of:  WARN: GDF does not support exxdiv none. exxdiv needs to be "ewald" or None


Could you please comment on it?

**Comment by gkc1000** [comment]
Can you dump your actual output (at least the beginning and end part)?

**Comment by sarashaban** [comment]
Professor Chan,
It is here:

******** <class 'pyscf.pbc.dft.krks.KRKS'> ********
method = KRKS-KRHF-KSCF-RHF-SCF-RHF
initial guess = minao
damping factor = 0
level_shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
diis_start_cycle = 1
diis_space = 8
SCF conv_tol = 1e-07
SCF conv_tol_grad = None
SCF max_cycles = 50
direct_scf = False
chkfile to save SCF result = 0.chk
max_memory 700000 MB (current use 83 MB)


******** PBC SCF flags ********
N kpts = 1
Exchange divergence treatment (exxdiv) = None
DF object = <pyscf.pbc.df.df.GDF object at 0x2ae2c9ffbf28>
XC functionals = pbe0
small_rho_cutoff = 1e-07
radial grids:
    Treutler-Ahlrichs (JCP 102, 346 (M4)) radial grids

becke partition: Becke, JCP, 88, 2547 (1988)
pruning grids: <function nwchem_prune at 0x2ae2be3ca840>
grids dens level: 3
symmetrized grids: False
atomic radii adjust function: <function treutler_atomic_radii_adjust at 0x2ae2be3ca7b8>

WARN: exxdiv None is not supported in DF or MDF

Set gradient conv threshold to 0.000316228
tot grids = 103082
cell vol = 510.318265  sum(weights) = 510.347828

WARN: GDF does not support exxdiv None. exxdiv needs to be "ewald" or None

**Comment by xwang862** [comment]
>WARN: exxdiv None is not supported in DF or MDF

>WARN: GDF does not support exxdiv None. exxdiv needs to be "ewald" or None

Is it possible that you provided a string `"None"` instead of a NoneType `None`? That would trigger the same warnings.

> But about the following classes of
pbcscf.KRHF(cell, kpts,exxdiv=None).density_fit()
pbcdft.KRKS(cell, kpts,exxdiv=None).density_fit()

The `__init__()` of class `KRKS` does not allow keyword argument `exxdiv`. But you can set it via
```
kmf = pbcdft.KRKS(cell, kpts).density_fit()
kmf.exxdiv = None
```

**Comment by sarashaban** [comment]
Thank you all again. 

This one did not generate warnings and goes well. Thanks.
kmf.exxdiv = None  

in older version, kmf.exxdiv = 'none', generates warning. 

@sunqm 1.7.1 (along with 1.6.3).

**Comment by sarashaban** [comment]
Dr Wang,

Do you consider these different scaled_centers, additional shifts of the k-mesh, (as the twist numbers) deliberatly? and they are related to the basis of the reciprocal lattice, since you have chosen (1/9,2/9,3/9); Thank you so much.

**Comment by tberkel** [comment]
There are many different methods for twist averaging, described throughout
the literature.  All correspond to different choices of the twist angles
(scaled_centers in Xiao's snippet), and so it's up to the user to choose
those twist angles.  One simple choice that PySCF could provide would be to
use `twist_angles = cell.make_kpts([8,8,8])` or some other dense but
uniform k-point mesh.

**Comment by verena-neufeld** [comment]
Hi @sarashaban , has this been resolved?

**Comment by sunqm** [comment]
Feel free to reopen the issue if this problem persists in the new releases.
