### ISSUE TITLE
No compatibility with recent versions of pyberny and geomeTRIC modules

### ISSUE THREAD

**Issue by alexmir18** [pyscf/pyscf#630]
Hi,
Not sure if this issue is specific to my environment, but when I install either pyberny or geomeTRIC (via pip install -U pyberny and pip install geometric, respectively) within conda environment, pyscf issues error related to logging. In case of geomeTRIC, it is "KeyError: formatters", while in case of pberny, it could not import "loggers". It appears that loggers.py is no longer a part of pyberny.
If there is no easy fix, I would appreciate if you suggest an alternative way to do geometry optimization in pyscf. Thanks!

**Comment by jamesETsmith** [comment]
Hi @alexmir18 I haven't seen either of these before, could you tell us what versions of PySCF, pyberney, and geomeTRIC you're using? Could you also provide a minimal input script that triggers this error along with the full error messages?

**Comment by alexmir18** [comment]
Thanks for the prompt reply. I use pySCF 1.7, pyberny 0.6.2, and geometric 0.9.7.1. In case of geomeTRIC, I was trying to execute the following script:
#!/usr/bin/env python3
from pyscf import gto, scf
from pyscf.geomopt import geometric_solver
from pdb import set_trace

mol = gto.M(atom='N 0 0 0; N 0 0 1.2', basis='ccpvdz')
mf = scf.RHF(mol)
conv_params = {
		'convergence_energy' : 1e-6, #Eh
		'convergence_grms'   : 3e-4, #Eh/Bohr
		'convergence_gmax'   : 4.5e-4, #Eh/Bohr
		'convergence_drms'   : 1.2e-3, #A
		'convergence_dmax'   : 1.8e-3, #A
		}
#set_trace()
opt = geometric_solver.GeometryOptimizer(mf).set(params=conv_params)
opt.max_cycle=100
opt.run()
mol_eq = opt.mol
print(mol_eq.atom_coords())
print(mf.kernel())
The error message is the following:
Traceback (most recent call last):
  File "./optimize.py", line 19, in <module>
    opt.run()
  File "/home/alexmir/pyscf_1.7/pyscf/lib/misc.py", line 482, in run
    self.kernel(*args)
  File "/home/alexmir/pyscf_1.7/pyscf/geomopt/geometric_solver.py", line 203, in kernel
    maxsteps=self.max_cycle, **self.params)
  File "/home/alexmir/pyscf_1.7/pyscf/geomopt/geometric_solver.py", line 148, in kernel
    constraints=constraints, **kwargs)
  File "/home/alexmir/miniconda3/envs/work/lib/python3.6/site-packages/geometric/optimize.py", line 1646, in run_optimizer
    logging.config.fileConfig(logIni,defaults={'logfilename': logfilename},disable_existing_loggers=False)
  File "/home/alexmir/miniconda3/envs/work/lib/python3.6/logging/config.py", line 76, in fileConfig
    formatters = _create_formatters(cp)
  File "/home/alexmir/miniconda3/envs/work/lib/python3.6/logging/config.py", line 109, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/home/alexmir/miniconda3/envs/work/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'

For pyberny, the relevant lines are:
from pyscf.geomopt.berny_solver import optimize
mol_eq = optimize(mf)

The error is:

Traceback (most recent call last):
  File "/home/alexmir/pyscf_1.7/pyscf/geomopt/berny_solver.py", line 22, in <module>
    from berny import Berny, geomlib, Logger, coords
ImportError: cannot import name 'Logger'

Thanks!

**Comment by alexmir18** [comment]
An update: after installing more recent geomeTRIC to 0.9.7.2 via conda, the problem disappeared. Looks like "pip install geometric" points to an outdated version, which is an issue with geometric.

**Comment by jamesETsmith** [comment]
Great, thanks for checking that. I can't reproduce your errors for either pyberny or geomeTRIC (using the versions you gave and both installed with pip) so I don't think it was a version problem with geomeTRIC. Maybe installing via conda changed some things under the hood, sometimes it's hard to tell. Either way, I'm glad it's working for you now.
