### ISSUE TITLE
excluding rotational modes for linear molecules

### ISSUE THREAD

**Issue by gkc1000** [pyscf/pyscf#633]
I think there is a small bug in https://github.com/pyscf/pyscf/blob/9cbad1cf84b2e3cd4b2c5dc41b0e0b4b238e0e2e/pyscf/hessian/thermo.py#L228

for linear molecules, it generates 3 rotational modes, which means when harmonic_analysis is called with exclude_rot=True, it will return the incorrect number of vibrational modes.

**Comment by sunqm** [comment]
Fixed in ead2836
