### ISSUE TITLE
Typos in mol.fromstring and mol.fromfile

### ISSUE THREAD

**Issue by alexmir18** [pyscf/pyscf#634]
Found several typos in those two routines. Should be "self" instead of "mol". In self.self_geom_, the first argument ('self') should be removed. PySCF version 1.7.

**Comment by sunqm** [comment]
Thanks for inspecting these functions. They were fixed in
adbdcbdd426356485d9a249d7461f668d19d6f9e

On Thu, Jun 11, 2020 at 09:28:51PM -0700, alexmir18 wrote:
> Found several typos in those two routines. Should be "self" instead of "mol". In self.self_geom_, the first argument ('self') should be removed. PySCF version 1.7.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyscf/pyscf/issues/634

--
