### ISSUE TITLE
Missing lattice vectors when cell is dumped into chkfile

### ISSUE THREAD

**Issue by xwang862** [pyscf/pyscf#636]
When PySCF dumps a `cell` into a chkfile, it will miss the information of lattice vectors if the `cell` is created from ASE (`pbc.tools.lattice.get_ase_atom`). This will cause problems when 
the chkfile is loaded for other calculations. For example, the following script prints nuclear energy from scratch and from a chkfile:

```
from pyscf.pbc import lib, gto, scf
from pyscf.pbc.tools import lattice, pyscf_ase

def main():
  enuc_scratch = run_from_scratch()
  enuc_chkfile = check_chkfile()
  print(f"energy_nuc from scratch:", enuc_scratch)
  print(f"energy_nuc from chkfile:", enuc_chkfile)

def check_chkfile():
  cell = lib.chkfile.load_cell("rhf.chk")
  enuc = cell.energy_nuc()
  return enuc

def run_from_scratch():
  ase_atom = lattice.get_ase_atom("C")
  
  cell = gto.Cell()
  cell.atom = pyscf_ase.ase_atoms_to_pyscf(ase_atom)
  cell.a = ase_atom.cell
  cell.unit = "B"
  cell.basis = "gth-szv"
  cell.pseudo = "gth-pade"
  cell.verbose = 1
  cell.build()

  rhf = scf.RHF(cell).density_fit()
  rhf.chkfile = "rhf.chk"
  rhf.kernel()

  enuc = cell.energy_nuc()
  return enuc

if __name__=="__main__":
  main()
```

This issue leads to a mismatch of nuclear energy:
```
energy_nuc from scratch: -12.787130063842156
energy_nuc from chkfile: 5.482034353995258
```
The reason is that ASE yields lattice vectors that is not json serializable, so lattice vectors (`cell.a`) are dropped during dumping. As a result, the reloaded `cell` is treated like a molecule.

Thank Brian Busemeyer for detecting the issue!

**Comment by fishjojo** [comment]
You simply need to use
`cell.a = ase_atom.cell[:]`
I'm not sure if a fix is needed...

**Comment by xwang862** [comment]
Thanks! This is way easier. I agree a fix is not needed. I will close it.
