### ISSUE TITLE
gradients and the PBC module?

### ISSUE THREAD

**Issue by mariomotta** [pyscf/pyscf#642]
hello -- is it possible to perform geometry optimizations / transition state searches in periodic systems with PySCF? I don't see any modules: is it right or am I missing something?

thanks,
Mario

**Comment by gkc1000** [comment]
Gradients are currently available w.r.t. the internal coordinates of the
atoms in the cell, but not w.r.t. the lattice parameters of the cell.

**Comment by yangcal** [comment]
Hi Mario, pyscf.pbc.geomopt module can do internal coordinates relaxation uses geomeTRIC library. Some notes to keep in mind is that the gradient module currently supports only FFTDF with no ewald correction(Unless range separated Coulomb is used, ewald corrections yields zero contribution to the nuclear gradient, so it's fine to  just do mf and geometric optimization with exxdiv=None).
