### ISSUE TITLE
Solving coupled T and Lambda equations

### ISSUE THREAD

**Issue by MilaimKas** [pyscf/pyscf#646]
Dear PySCF users,

I would like to self-consistency solve the CC equations with a potential that depends on the t and l amplitudes (expressed in MOs basis). The L and T equations are therefore coupled. 
The algorithm could look like this:

- Standard HF calculation
- initial guess for the t and l amplitudes
-----------
- calculate the effective fock matrix F'=diag(mo_ene)+ V(t,l)
- get L intermediates
- update l amplitudes
- (update F')
- get T intermediates
- update t amplitudes
- check for convergence
-----------  

As a first step, I would only solve the T1 and L1 equations (t2=l2=0). So far, I have tried to parse the effective fock matrix to the cc object: mycc._scf.get_fock = lambda *args: F' and solve the T and L equations using the ccn module. However, I got the following error message:

File "", line 419, in <module>
    ls = pyscf.ccn.cc.kernel_lambda_s(mycc, ts, tolerance=1e-10, maxiter=50)
File "/pyscf/ccn/cc.py", line 106, in kernel_lambda_s
    hamiltonian = eris_hamiltonian(cc.ao2mo())
File "/pyscf/cc/ccsd.py", line 1117, in ao2mo
    return _make_eris_incore(self, mo_coeff)
File "/pyscf/cc/ccsd.py", line 1264, in _make_eris_incore
    eris._common_init_(mycc, mo_coeff)
File "/pyscf/cc/ccsd.py", line 1216, in _common_init_
    fockao = mycc._scf.get_fock(dm=dm)
TypeError: <lambda>() got an unexpected keyword argument 'dm'

Note that I am not sure that the system of equations can indeed be solved self-consistency. Gradient method may be needed.

Thanks in advance for your help

**Comment by fishjojo** [comment]
your lambda function should be something like
`mycc._scf.get_fock = lambda *args, **kwargs : F'`

**Comment by MilaimKas** [comment]
Thank you for pointed that out.
I know get the following error message:

File "/pyscf/ccn/pyscf_helpers.py", line 159, in eris_hamiltonian
    raise ValueError("Unknown object: {}".format(eris))
ValueError: Unknown object: <pyscf.cc.ccsd._ChemistsERIs instance at 0x7efdcc5a4640>

Here is a the relevant part of the script I am using
`
# initialize t1 and l1
ts = np.zeros((nocc,nvir))
ls = np.zeros((nocc,nvir))

mf0 = scf.RHF(mol)
mycc = pyscf.cc.RCCSD(mf0)

# get effective Fock matrix 
F' = get_new_f(ts,ls)
# parse to mycc object
mycc._scf.get_fock = lambda *args, **kwargs: F'

# get new l1 and t1
ls = pyscf.ccn.cc.kernel_lambda_s(mycc, ts, tolerance=1e-10, maxiter=50)
Energy, ts = pyscf.ccn.cc.kernel_ground_state_s(mycc, tolerance=1e-10, maxiter=50)

`

**Comment by fishjojo** [comment]
You need eris computed from the cc.uccsd_slow or cc.gccsd modules, i.e.,
`mycc = pyscf.cc.GCCSD(mf0)`

**Comment by sunqm** [comment]
Here are some examples of CCSD(T) lambda using the "slow" implementation
https://github.com/pyscf/pyscf/blob/master/examples/cc/01-lambda.py
https://github.com/pyscf/pyscf/blob/master/examples/cc/01-density_matrix.py#L48

**Comment by MilaimKas** [comment]
Thank you very much for your help !
And sorry for the late reply.

Attempting to calculate the l amplitudes :
`pyscf.ccn.cc.kernel_lambda_s(mycc, ts, tolerance=1e-10, maxiter=50)`
using the initial guess `ts = np.zeros((nocc,nvir)),` results in the following error message:

  File "pyscf/ccn/cc.py", line 106, in kernel_lambda_s
    hamiltonian = eris_hamiltonian(cc.ao2mo())
  File "pyscf/cc/gccsd.py", line 267, in ao2mo
    return _make_eris_incore(self, mo_coeff)
  File "pyscf/cc/gccsd.py", line 350, in _make_eris_incore
    eris._common_init_(mycc, mo_coeff)
  File "pyscf/cc/gccsd.py", line 338, in _common_init_
    self.fock = reduce(np.dot, (mo_coeff.conj().T, fockao, mo_coeff))
ValueError: shapes (108,108) and (54,54) not aligned: 108 (dim 1) != 54 (dim 0)

**Comment by gkc1000** [comment]
Are you using a RHF reference and feeding it in? It is looking for a GHF
reference, I think.

**Comment by MilaimKas** [comment]
Indeed, I was using a RHF reference! I just realised than the eris, MOs and related properties are given in spin orbitals basis in GHF and gccsd, which explains why the dimension of the mo_coeff (108) is twice the dimension of the Fock matrix (54) ...

Expressing everything in spin orbital basis and using gccsd and ghf objects solves the issue (no error message).

However, there seems to be a problem when parsing the effective Fock matrix F' (hp) to the ccsd object. Starting with random t1 and l1 values and neglecting F', the energy converges to 0. However, when adding the following line: 
`mycc._scf.get_fock = lambda *args, **kwargs: hp` 
where 
`hp=np.diag(mf0mo_energy)`
, the HF energy is not recovered. Expressing hp in AOs basis with 
`np.einsum('pi,ij,qj->pq',mo_coeff,hp,mo_coeff.conj())`
did not solve the problem.

**Comment by MilaimKas** [comment]
Apologies: my last comment was a bit confusing ...

Here is my question: are the following lines of code correct in order to pass a given fock matrix to the cc object ?

`hp = np.diag(mf.mo_energy) # in MOs basis`
`hp = np.einsum('pi,ij,qj->pq',mo_coeff,hp,mo_coeff.conj()) # in AOs basis`
`mycc._scf.get_fock = lambda *args, **kwargs: hp` 

thank you for your help

**Comment by tberkel** [comment]
That looks right to me.  The CC code expects `get_fock` to return the Fock
matrix in the AO basis.  It will then use `mo_coeff`to transform to the MO
basis.  Not sure what you need, but `mo_coeff` can be provided as a `kwarg`
to the CC constructor, else it will use the one stored in the `mf` object
by default.  The relevant lines calling `get_fock` and transforming from AO
to MO basis are here:
https://github.com/pyscf/pyscf/blob/master/pyscf/cc/ccsd.py#L1285

**Comment by MilaimKas** [comment]
Thank you for your respond.
I am trying to understand how the ccn module works in order to solve the T1 and L1 equations given a effective Fock matrix. The later depends on the t1 and l1 amplitudes and therefore couples the T1 and L1 equations.

Using the simple script given below, I am getting `Ep = -2.6263 ...`. If Ep is define as the correlation energy, I was expecting to get `Ep = 0` (no correlation). 
Am I missing something here ? Maybe some deep understanding of how the CC equations work ... ?

`#!/usr/bin/python'
`# -*- coding: utf-8 -*-`

`import numpy as np`
`import pyscf `
`from pyscf import scf,gto,ao2mo,lib,ccn`
`from pyscf.ccn import cc`

`mol=gto.Mole()`

`mol.atom="""`
`O 0.000  0.000 0.0`
`H 0.757  0.586 0.0`
`H -0.757 0.586 0.0`
`"""`
`mol.basis={`
`'H': '6-31g',`
`'O': '6-31g',`
`}`

`mol.build()`
`mf0=scf.GHF(mol)`
`mf0.kernel()`

`mycc = pyscf.cc.GCCSD(mf0)`  

`hp = np.diag(mf0.mo_energy) # in MOs basis`
`hp = np.einsum('pi,ij,qj->pq',mf0.mo_coeff,hp,mf0.mo_coeff.conj()) # in AOs basis`

`mycc._scf.get_fock = lambda *args, **kwargs: hp   # pass the new one electron hamiltonian`
    
`Ep, ts = pyscf.ccn.cc.kernel_ground_state_s(mycc, tolerance=1e-10, maxiter=50)`

`print 'Ep = ',Ep`

**Comment by sunqm** [comment]
I think Ep is strictly 0 only in the case of unitary CCS. I'd expect a small non-zero Ep for regular CCS.
In your test case, I think Fock in AO basis should be calculated this way
```
s = mf0.get_ovlp()
hp = s.dot(mo_coeff).dot(np.diag(mf0.mo_energy)).dot(mo_coeff.conj().T).dot(s)
```

**Comment by MilaimKas** [comment]
Thank you very much for your help. It is working now.
I may have further questions while pursuing with this project, I will close the issue for now but reopen it in case.
