### ISSUE TITLE
Problem with CASSCF on Cu transition metal

### ISSUE THREAD

**Issue by StefanoBarison** [pyscf/pyscf#649]
Good morning,
I am experiencing an issue calculating the CASSF energy on an active space of the copper atom. 

With this code

```
import numpy as np
from   pyscf  import gto, scf, mcscf, symm
from pyscf  import fci

mol = gto.Mole()
mol.build(
    atom     = 'Cu',
    basis    = '6-31g',
    symmetry = 'Dooh',
    spin     = 3,
    verbose  = 0)

irr = {'A1g':(5,4),'A1u':(2,2),'E1ux':(2,2),'E1uy':(3,2),'E2gy':(1,1),'E1gy':(1,1),'E1gx':(1,1),'E2gx':(1,0)}

mf             = scf.ROHF(mol)
mf.irrep_nelec = irr
Eirr           = mf.kernel()
if(not mf.converged):
   mf   = scf.newton(mf)
   Eirr = mf.kernel(mf.mo_coeff,mf.mo_occ)
print("ROHF energy ",Eirr)
freeze = 9
na,nb  = (mol.nelectron+mol.spin)//2-freeze,(mol.nelectron-mol.spin)//2-freeze
mc = mcscf.CASSCF(mf,9,(na,nb))
print("CASSCF energy ",mc.kernel()[0])

h1e_cas,ecore = mc.get_h1eff()
h2e_cas       = mc.get_h2eff()

e, fcivec = fci.direct_spin1.kernel(h1e_cas,h2e_cas,9,(7,4),nroots=1,ecore=ecore,verbose=0)
print("Energy from Davidson diagonalization of CASCI matrix ",e)
H_fci = fci.direct_spin1.pspace(h1e_cas,h2e_cas,9,(7,4))[1]
e_all, v_all = np.linalg.eigh(H_fci)
print("Energy from numpy diagonalization of CASCI matrix ",np.min(e_all+ecore))

```

The output is 

```
ROHF energy  -1638.5538667142184
CASSCF energy  -1638.3668515012516
Energy from Davidson diagonalization of CASCI matrix  -1638.5302689863342
Energy from numpy diagonalization of CASCI matrix  -1638.5305132120347
```

So the CASSCF gives an energy that is higher than the mean field one.
This issue is present also with other bases (cc-pvdz as an example).
Even if I diagonalize the CASCI matrix 'by my hand' with Davidson or with numpy eigh() I have an energy which is higher than the HF one, but still different from the one given from CASSCF.

Is the CASSCF considering the wrong active space?

Moreover, I would like to ask:
- Is there a way to print out the Hamiltonian matrix for a CASCI calculation?
- is there a way to print out the CI configurations which correspond to its indexes?

Thank you very much.

**Comment by gkc1000** [comment]
It looks like you are doing CASSCF in only 9 orbitals for Cu. Maybe you
want to set mc.frozen=9 as well.

**Comment by StefanoBarison** [comment]
Thank you for the answer.
Unfortunately, this seems not to solve the issue. I've added mc.frozen=9 between the CASSCF declaration and the kernel call, so the new code is

```
import numpy as np
from   pyscf import gto, scf, mcscf, symm
from pyscf import fci

mol = gto.Mole()
mol.build(
    atom     = 'Cu',
    basis    = '6-31g',
    symmetry = 'Dooh',
    spin     = 3,
    verbose  = 0)

irr = {'A1g':(5,4),'A1u':(2,2),'E1ux':(2,2),'E1uy':(3,2),'E2gy':(1,1),'E1gy':(1,1),'E1gx':(1,1),'E2gx':(1,0)}

mf             = scf.ROHF(mol)
mf.irrep_nelec = irr
Eirr           = mf.kernel()
if(not mf.converged):
   mf   = scf.newton(mf)
   Eirr = mf.kernel(mf.mo_coeff,mf.mo_occ)
print("ROHF energy ",Eirr)
freeze = 9
na,nb  = (mol.nelectron+mol.spin)//2-freeze,(mol.nelectron-mol.spin)//2-freeze
mc = mcscf.CASSCF(mf,9,(na,nb))
mc.frozen=9
print("CASSCF energy ",mc.kernel()[0])

h1e_cas,ecore = mc.get_h1eff()
h2e_cas       = mc.get_h2eff()
e, fcivec = fci.direct_spin1.kernel(h1e_cas,h2e_cas,9,(7,4),nroots=1,ecore=ecore,verbose=0)
print("Energy from Davidson diagonalization of CASCI matrix ",e)
H_fci = fci.direct_spin1.pspace(h1e_cas,h2e_cas,9,(7,4))[1]
e_all, v_all = np.linalg.eigh(H_fci)
print("Energy from numpy diagonalization of CASCI matrix ",np.min(e_all+ecore))
```
but I get the same results as before.

To make my submission more complete I add my package version:

```
pyscf 1.7.3
numpy 1.18.1
scipy 1.4.1
```
Thank you very much again for your time.

**Comment by bogdanoff** [comment]
With `verbose  = 0` one gets a lot of useful information.
It turns out  that neither of HF calculations converge.
CASSCF targets E3gx state, irreps of active-space orbitals are: [11  2  3  0 10  0  6  7  5]. Is it what you want?
Once I comment `mf.irrep_nelec = irr` line, HF converges to -1638.5461589777535, CASSCF targets E2ux and converges to -1638.56088720442.
Forcing it with `mc.wfnsym = 'E2ux'` does the same.
CASSCF is not a black box, one should always check what are the orbitals and which state is obtained.

**Comment by StefanoBarison** [comment]
Thank you very much for the insights and the explanation.
Yes I was trying to force the system into a well defined irreducible representation.

I was wrong about 'E3gx' state, as you said the right symmetry to target is E2ux.

The only difference I get from your results is that without  `mf.irrep_nelec =irr `  with some fixed irr the SCF calculation does note converge, as putting `verbose = 4` indicates. Sometime I get your result and other times `-1638.5538667142184`.
It seems that ROHF continues shifting between these two states and sometimes tries to break the atomic symmetries to get an unphysical but lower energy.

However, it seems that CASSCF now gives lower energy than HF, so thank you and @gkc1000 very much.

**Comment by sunqm** [comment]
In dev branch (commit 169cf51a87a44b7722a481d3512abc1fbb9dc4da), you will be able to use SO3 symmetry for atoms
