### ISSUE TITLE
Memory issue for ED 

### ISSUE THREAD

**Issue by rezah** [pyscf/pyscf#653]
I get a memory error for large system sizes. Is there any compact form for `Haimiltinain:`

``
import numpy as np
import scipy.linalg as la
from pyscf import scf, gto, ao2mo, fci
from libdmet_solid.system import lattice
from libdmet_solid.dmet import Hubbard as dmet
from libdmet_solid.utils.misc import mdot
import math

np.set_printoptions(3, linewidth=1000, suppress=True)

LatSize = [2, 2]
ImpSize = [2, 2]
Lat = dmet.SquareLattice(*(LatSize+ImpSize))

nelec = 2
nao = nscsites = Lat.nscsites
nkpts = Lat.nkpts

g_int = -7.4
Ham = dmet.Ham(Lat, 2.0*g_int, obc=True) # OBC
H1 = +Ham.getH1()[0]
H2 = Ham.getH2()

print (H2)
cisolver = fci.direct_spin1.FCI()
cisolver.max_cycle = 100
cisolver.conv_tol = 1e-8
e, fcivec = cisolver.kernel(H1, H2, nao, (nelec//2, nelec//2)) 
print ("FCI energy:")
print ((e+4.*nelec)*0.5)

E_bonding=(e+4.*nelec)*0.5

N_e=20.0
N_dens=N_e/(LatSize[0]*LatSize[0])
E_fermi=math.pi*N_dens
print("g_int",  g_int)
print("Fermi_Energy",  E_fermi)
Eta=0.50 * math.log(2.0*abs(E_fermi/E_bonding))
print("Eta",  Eta)
E_unit=0.5*N_e*E_fermi
print("E_final",  E_bonding/E_unit)
``

**Comment by gkc1000** [comment]
Ok, this is related to libdmet, not PySCF. I will close this issue and sort it out elsewhere.
