### ISSUE TITLE
Is molecular orbital localization (eg pipek-mezey) implemented in relativistic calculations?

### ISSUE THREAD

**Issue by DanielBajac** [pyscf/pyscf#656]
I had some errors when I wanted to carry it out.

**Comment by sunqm** [comment]
No, it's not available for relativistic methods

On Mon, Jul 06, 2020 at 05:54:11AM -0700, DanielBajac wrote:
> I had some errors when I wanted to carry it out. 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyscf/pyscf/issues/656

--
