### ISSUE TITLE
Obtaining the density profile

### ISSUE THREAD

**Issue by mfkasim91** [pyscf/pyscf#657]
First, thanks for the PySCF, it is a great library!
I am trying to get the density profile after Full CI calculation, but I am not sure how to get it.
Based on the examples and my intuition, it should go like below (example of He electron density profile).

    import numpy as np
    import matplotlib.pyplot as plt
    from pyscf import gto, scf, fci
    from pyscf.dft import numint

    # solve with Full CI
    mol = gto.M(atom='He 0 0 0', basis="augccpv5z", spin=0)
    mf = scf.RHF(mol)
    mfene = mf.kernel()
    cisolver = fci.FCI(mol, mf.mo_coeff)
    eneci, cicoeff = cisolver.kernel()

    # get the density
    nelec = (1,1)
    dm = cisolver.make_rdm1(cicoeff, mf.mo_coeff.shape[1], nelec)
    npts = 1000
    xcoords = np.linspace(0, 3, npts)[:,None]
    ycoords = np.zeros(npts)[:,None]
    zcoords = np.zeros(npts)[:,None]
    coords = np.concatenate((xcoords, ycoords, zcoords), axis=-1)
    ao = numint.eval_ao(mol, coords)
    dens = numint.eval_rho(mol, ao, dm)

However, the `dens` does not look like the density I expect: (1) it is very far from the estimated He electron density profile from [here](https://en.wikipedia.org/wiki/Helium_atom#The_variational_method), and (2) the integral of the density is not close to 1

    print(np.sum(dens * 4*np.pi * xcoords*xcoords) * (xcoords[1]-xcoords[0])) # about 4.8e5, very far from 1

Did I do something wrong?

**Comment by gkc1000** [comment]
Hi, eval_rho requires the DM in the ao basis, while the DM you are
computing is in the MO basis (you can check by looking at the diagonal
elements, it will be very strongly diagonally dominant).

To get the DM in the MO basis you should use the line

dmao = np.dot(mf.mo_coeff, np.dot(dm, mf.mo_coeff.T))

**Comment by mfkasim91** [comment]
Thanks!
