### ISSUE TITLE
Are f_ia terms considered in CASCI-NEVPT2?

### ISSUE THREAD

**Issue by 1234zou** [pyscf/pyscf#662]
Are the f_ia terms of the (generalized-)Fock-operator considered in NEVPT2 implementation in PySCF?

In another word, is it meaningful or meaningless that I perform a CASCI-NEVPT2 or DMRGCI-NEVPT2 calculation without using CASSCF optimized orbitals?

**Comment by sunqm** [comment]
Are you referring to the h_ia term in Eq. (10) of https://aip.scitation.org/doi/10.1063/1.1515317 ? This is explicitly calculated.

You don't need to compute CASSCF orbitals first. We regularly performed CASCI/DMRG-CASCI followed by a CASCI-NEVPT2 calculation.
