### ISSUE TITLE
FCI solver for PBC systems?

### ISSUE THREAD

**Issue by NnktYoshioka** [pyscf/pyscf#664]
Hi, 

It is my pleasure of contacting pyscf developers for the first time.
I was wondering if you have any modules to execute FCI for pbc systems.
Simply applying the ordinary fci solver does not seem to be appropriate, and I would really appreciate if there is any way to run the calculation properly.

For example, I have tested something like the following, but obviously the fci solver does not work with periodic cells well...

```python
import pyscf.pbc.gto as pbcgto
from pyscf.pbc import df as pdf
from pyscf.pbc import scf as pbchf

L=3
cell = pbcgto.Cell()
cell.build(unit = 'B',
           a = [[L,0,0],[0,1,0],[0,0,1]],
           atom = 'H 0 0 0; H %.5f 0 0'%(L/2),
           dimension=1,basis="sto-3g")

nkpoints = 4
myhf = pbchf.KRHF(cell)
myhf.kpts = cell.make_kpts([nkpoints,1,1])
myhf.with_df = pdf.GDF(cell)
myhf.kernel()

from pyscf import fci
cisolver = fci.FCI(cell, myhf.mo_coeff[0])
cisolver.kernel()
```

**Comment by zhcui** [comment]
You can check issue #315.

**Comment by NnktYoshioka** [comment]
Thanks Zhihao, indeed my question is overlapping with this issue.
Using `pbchf.RHF` instead of `pbchf.KRHF` allowed me to run gamma-point simulation (correction of madelung constant required).
