### ISSUE TITLE
Cannot reproduce electrostatic potential

### ISSUE THREAD

**Issue by Edumars** [pyscf/pyscf#666]
Hello developers,
I wanted to calculate electrostatic potentials on a grid, and I found issue #258 and example 031-MEP.py discussing this calculation.
However, when I tried to benchmark the results of 031-MEP.py with Gaussian, I found that the potentials are different. The difference is not just a constant value (units), so I would like to know if I am missing some details in how to run this script.
I am attaching the values of the "MEP" variable from 031-MEP.py (grid_esp.grd), and the Gaussian output (imidazol.log). Gaussian relevant section is after "Electrostatic Properties (Atomic Units)", just at the end of the file.
Thanks a lot for this amazing software!

[ESP.zip](https://github.com/pyscf/pyscf/files/4944221/ESP.zip)

**Comment by sunqm** [comment]
The coordinates of the grids in 031-MEP.py are in the atomic unit. If they were scaled by a factor 1/0.53, the potential value shows a good match.

**Comment by Edumars** [comment]
Thanks a lot, that fixed the issue
