### ISSUE TITLE
NotImplementedError: Project initial guess from different system

### ISSUE THREAD

**Issue by jamcas** [pyscf/pyscf#668]
I followed this example https://github.com/pyscf/pyscf/blob/master/examples/mcscf/14-project_init_guess.py, but I got this error :
```
Traceback (most recent call last):
  File "1", line 30, in <module>
    mo = mcscf.project_init_guess(mc, mo_init_guess, mol1)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mcscf/addons.py", line 439, in project_init_guess
    raise NotImplementedError('Project initial guess from different system.')
NotImplementedError: Project initial guess from different system.

```

**Comment by fishjojo** [comment]
There is a typo. The first molecule should be O2

**Comment by sunqm** [comment]
In early version, pyscf supports to read density matrix from a completely different system. This feature was abandoned since version 1.5 if the two systems are too different.

**Comment by jamcas** [comment]
Ok, thanks for your reply!
