### ISSUE TITLE
Pyscf wfx format

### ISSUE THREAD

**Issue by Jeriimiah** [pyscf/pyscf#670]
Hi,

I'm trying to understand the pyscf wfx format.  I have this code here to generate the 

mol = gto.Mole()
mol.build(
    atom = '''H 0 0 0; H 0 0 0.7474''',  # in Angstrom
    basis = 'sto-3g')

myhf = scf.RHF(mol)
myhf.verbose = 0
myhf.kernel()

cisolver = fci.FCI(mol, myhf.mo_coeff)
cisolver = cisolver.kernel()
e, wfx = cisolver

I want to compare the wfx to a seperate quantum state vector. How would I go about changing the format for the wfx in order to find the fidelity between the wfx and my quantum state vector?

**Comment by sunqm** [comment]
wfx is stored in a 2D array, where the first axis corresponds to spin-up determinants and the second axis corresponds to spin-down determinants. https://github.com/pyscf/pyscf/blob/master/examples/fci/11-large_ci.py This example can help you idenitify the most significant determinants.
