### ISSUE TITLE
Bug in pbc.cc.eom_kccsd_rhf

### ISSUE THREAD

**Issue by yangcal** [pyscf/pyscf#677]
https://github.com/pyscf/pyscf/blob/119e86b5f5904551f29edee8ee09de02968ac60e/pyscf/pbc/cc/eom_kccsd_rhf.py#L718

in EOMEA, we have ka+kb = kshift+kj, therefore this line should be:
kb = kconserv[kj,ka,kshift]

**Comment by sunqm** [comment]
Good catch. Thanks!
