### ISSUE TITLE
Feature request: What is your opinion on IR and Raman intensities?

### ISSUE THREAD

**Issue by jakobkraus** [pyscf/pyscf#678]
Hi,

I've recently noticed the thermochemistry feature and it's a really useful tool, so thank you a lot!
I also saw the   
#dump('IR\n')
#dump('Raman\n')
comments, so I would like to ask if we can expect an additional code feature allowing for the calculation of IR and Raman intensities.
As someone who regularly cooperates with experimental physicists and chemists, I find these quantities very helpful at times, and would love to have them available in PySCF.
What is your current opinion on this?

Sincerely,

Jakob Kraus

**Comment by gkc1000** [comment]
Hi, I'm not sure what the question is precisely, is this a feature request?
Or are you asking if these are worthwhile to have?

**Comment by jakobkraus** [comment]
It's basically a feature request.

**Comment by sunqm** [comment]
IR is available https://github.com/pyscf/pyscf/blob/master/examples/hessian/10-thermochemistry.py

Raman is not available

**Comment by jakobkraus** [comment]
I am sorry, but I cannot find any existing code which could be responsible for the calculation of IR intensities, and the example you are pointing towards does not seem to calculate the IR intensities, either.
This is the output produced by running https://github.com/pyscf/pyscf/blob/master/examples/hessian/10-thermochemistry.py :

converged SCF energy = -75.9839484981055
Rotation constant  
(array([819.20368462, 437.4565388 , 285.17335217]), 'GHz')  
Zero-point energy  
(0.022172722144135463, 'Eh')  
Internal energy at 0 K  
(-75.96177577596137, 'Eh')  
Internal energy at 298.15 K  
(-75.95894200171998, 'Eh')  
Enthalpy energy at 298.15 K  
(-75.95799781716386, 'Eh')  
Gibbs free energy at 298.15 K  
(-75.97940894236406, 'Eh')  
Heat capacity at 298.15 K  
(9.536589391336595e-06, 'Eh/K')  

The only points where IR is currently mentioned in thermo.py are two comments, found in
1. line 108:      #TODO: IR intensity
2. line 371:       #dump('IR\n') (followed by line 372:  #dump('Raman\n'))

This seems to support my understanding that the calculation of IR intensities (as well as Raman intensities) has not been made available yet. 
By the way, I am very thankful for the time and effort you have already dedicated to responding to my request.

**Comment by sunqm** [comment]
Your observation is correct. Intensities for IR and Raman are not available.
Only the oscillation mode and their frequencies in IR are computed.

On Sun, Aug 30, 2020 at 07:42:56AM -0700, Jakob Kraus wrote:
> I am sorry, but I cannot find any existing code which could be responsible for the calculation of IR intensities, and the example you are pointing towards does not seem to calculate the IR intensities, either.
> This is the output produced by running https://github.com/pyscf/pyscf/blob/master/examples/hessian/10-thermochemistry.py :
> 
> converged SCF energy = -75.9839484981055
> Rotation constant  
> (array([819.20368462, 437.4565388 , 285.17335217]), 'GHz')  
> Zero-point energy  
> (0.022172722144135463, 'Eh')  
> Internal energy at 0 K  
> (-75.96177577596137, 'Eh')  
> Internal energy at 298.15 K  
> (-75.95894200171998, 'Eh')  
> Enthalpy energy at 298.15 K  
> (-75.95799781716386, 'Eh')  
> Gibbs free energy at 298.15 K  
> (-75.97940894236406, 'Eh')  
> Heat capacity at 298.15 K  
> (9.536589391336595e-06, 'Eh/K')  
> 
> The only points where IR is currently mentioned in thermo.py are two comments, found in
> 1. line 108:      #TODO: IR intensity
> 2. line 371:       #dump('IR\n') (followed by line 372:  #dump('Raman\n'))
> 
> This seems to support my understanding that the calculation of IR intensities (as well as Raman intensities) has not been made available yet. 
> By the way, I am very thankful for the time and effort you have already dedicated to responding to my request.
> 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyscf/pyscf/issues/678#issuecomment-683428892

--

**Comment by gkc1000** [comment]
There are plans to add this, maybe in the next release.

**Comment by jakobkraus** [comment]
Very nice, thank you all very much for your responses.

**Comment by sofroniewn** [comment]
Hi all, I was just wondering if there had been any progress on this feature?

I am a new PySCF user (and pretty new to computational chemistry overall), but I would also benefit from a simple API to access IR and Raman spectra too - it could be similar to the [ASE IR](https://wiki.fysik.dtu.dk/ase/ase/vibrations/infrared.html) and [Raman](https://wiki.fysik.dtu.dk/ase/ase/vibrations/raman.html) APIs. Thanks!!

**Comment by ajz34** [comment]
Hi~
I tried to add infrared intensity to `properties` extension and make a PR https://github.com/pyscf/properties/pull/1 for RHF/RKS/UHF/UKS methods. Raman has not been implemented.

**Comment by sofroniewn** [comment]
That worked great @ajz34 I just tried out your PR and it worked first time, giving values that look very reasonable - see my comment on the PR for more details.

I am also interested in vibrational circular dichroism (VCD) - see [this review](https://journals.sagepub.com/doi/pdf/10.1177/1934578X0800300322) for details on the calculation. Is that something you @ajz34 or others might be interested in adding too? (Similarly I would be interested in Raman Optical Activity (ROA) if Raman support is added).

Thanks again!

**Comment by sunqm** [comment]
Seems @ajz34 's PR solved the problem. I'll close this issue for now.
