### ISSUE TITLE
Typo in 'dump_thermo' function in thermo.py

### ISSUE THREAD

**Issue by jakobkraus** [pyscf/pyscf#682]
Hi,

I believe there is a typo in the 'dump_thermo' function in thermo.py:

`    dump('%-28s               %s\n'
         % ('Enthalpy [J/mol]', convert('H', keys[2:], 'Eh')))`
` dump('%-22s %.5f\n'
         % ('Entropy [Eh]', results['H_tot'][0]))`

The total enthalpy is displayed but misnamed as 'Entropy [Eh]'.

**Comment by sunqm** [comment]
Fixed in 61797bb95332f2d4dee62ac05609a9ac8e21abf3
