### ISSUE TITLE
Is it possible to run pbc.scf.KROHF with totally empty beta spin-orbitals?

### ISSUE THREAD

**Issue by kyasci** [pyscf/pyscf#686]
Hello,

Recently I began to calculate open-shell PBC systems with PySCF.
As a starting point, I chose H high-spin chain specified as

        mol = pbc.gto.Cell(                                                             
        atom='H 0 0 0;', 
        a=[[1, 0, 0], [0, 5, 0], [0, 0, 5]], 
        basis='6-31g', 
        spin=1,
        dimension=1, 
        )

I got `ValueError: max() arg is an empty sequence` when I tried to do SCF with `mf=pbc.scf.KROHF(mol,kpts=[[0., 0., 0.]]).density_fit()`, while corresponding `pbc.scf.ROHF` (Gamma point) finishes normally.

Apparently this error only occurs when the system has totally empty beta spin-orbitals.
I admit that such a calculation would be a rare case, but I still want to know whether it is possible or not.

Many thanks,
Kentaro

**Comment by sunqm** [comment]
Hi Kentaro, which version do you use? I'm using the 1.7.4 and I couldn't
reproduce the error you mentioned.

Qiming

On Fri, Aug 21, 2020 at 12:49:47AM -0700, Kentaro Yamamoto wrote:
> Hello,
> 
> Recently I began to calculate open-shell PBC systems with PySCF.
> As a starting point, I chose H high-spin chain specified as
> 
>         mol = pbc.gto.Cell(                                                             
>         atom='H 0 0 0;', 
>         a=[[1, 0, 0], [0, 5, 0], [0, 0, 5]], 
>         basis='6-31g', 
>         spin=1,
>         dimension=1, 
>         )
> 
> I got `ValueError: max() arg is an empty sequence` when I tried to do SCF with `mf=pbc.scf.KROHF(mol,kpts=[[0., 0., 0.]]).density_fit()`, while corresponding `pbc.scf.ROHF` (Gamma point) finishes normally.
> 
> Apparently this error only occurs when the system has totally empty beta spin-orbitals.
> I admit that such a calculation would be a rare case, but I still want to know whether it is possible or not.
> 
> Many thanks,
> Kentaro
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyscf/pyscf/issues/686

--

**Comment by kyasci** [comment]
Hi Qiming,

Thanks for checking this out. I'm using 1.7.4 as well.

Apparently `verbose=5` is the reason why I got `ValueError`.
The calculation goes well if `verbose` < 5.

Could you check if it's reproduced in your environment with the following code?

```python
#!/usr/bin/env python3
from pyscf.pbc import gto, scf


mol = gto.Cell(
    atom='H 0 0 0;',
    a=[[1, 0, 0], [0, 5, 0], [0, 0, 5]],
    basis='6-31g',
    spin=1,
    dimension=1,
    verbose=5,
    )
mol.build()
mf = scf.KROHF(mol, kpts=[0, 0, 0]).mix_density_fit()
print(mf.kernel())
```

I close this issue as I'm convinced that PySCF has been able to handle this calculation, but I'd appreciated it if you could explain  what would be the problem of `verbose=5` in this case.

Many thanks,
Kentaro

**Comment by kyasci** [comment]
Hello,

Sorry to bother you again, but I would like to ask you how we can calculate H chain with `pbc.scf.UHF`.
As mentioned above, `pbc.scf.ROHF` looks OK, but I get an error with `pbc.scf.KUHF`, which should be equivalent to `pbc.scf.KROHF` in this case. It works if I replace `atom='H 0 0 0;'` with `atom='Li 0 0 0;'`. The code to reproduce it is given as follows.

```python
#!/usr/bin/env python3
from pyscf.pbc import gto, scf


nk = [1, 1, 1]
mol = gto.Cell(
    atom='H 0 0 0;',
    a=[[2, 0, 0], [0, 10, 0], [0, 0, 10]],
    basis='6-31g',
    spin=1,
    dimension=1,
    )
mol.build()
kpts = mol.make_kpts(nk)
mf = scf.KUHF(mol, kpts).density_fit()
mf.kernel()
```
`IndexError` is expected to be raised. Tested version is 1.7.4.

Thanks,
Kentaro

**Comment by sunqm** [comment]
Problems were fixed in pyscf 2
