### ISSUE TITLE
Questions/comments regarding optimised source builds

### ISSUE THREAD

**Issue by glowthrower** [pyscf/pyscf#687]
Hi,

I have a couple of questions/comments regarding the process of building from source. They're not really "issues" but there doesn't seem to be a better place to post them. ;) I'm referring here to what seems to be the [canonical documentation](https://sunqm.github.io/pyscf/install.html).

#### Hardcoded CMAKE_BUILD_TYPE 

The docs mention the possibility to adjust optimisation flags by setting, e.g., `CMAKE_C_FLAGS`. It suggests that these are put into a config file, but as this is a CMake build, it seems reasonable to be able to adjust settings using just command line switches (e.g. `-DCMAKE_C_FLAGS=...`) or, alternatively, the CMake curses GUI (`ccmake`). I experimented with this, and noticed that the [main CMakefile](https://github.com/pyscf/pyscf/blob/master/pyscf/lib/CMakeLists.txt) file has the following lines:
```cmake
set(CMAKE_BUILD_TYPE RELWITHDEBINFO)
#set(CMAKE_BUILD_TYPE DEBUG)
```
May I suggest that this be done a bit more carefully? As `CMAKE_BUILD_TYPE` here is not set as a cache variable, it's problematic trying to override it from either command line or `ccmake` and the results may not be what the user expects. For example, suppose I set `-DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS_RELEASE="-Ofast -DNDEBUG" -DCMAKE_C_FLAGS="-march=native -mtune=native -funroll-loops -ftree-vectorize"` at configure time (which is a pretty reasonable thing to do for a production build, IMHO). If I then run a build, the intended change from the default release-mode `-O3` to `-Ofast` is quietly swallowed, in favour of the standard `CMAKE_C_FLAGS_RELWITHDEBINFO` settings, i.e. `-O2 -g -DNDEBUG`. For example:
```
[ 48%] Building C object vhf/CMakeFiles/cvhf.dir/rha_direct_dot.c.o
cd /home/my-username/repos/pyscf/pyscf/lib/build/vhf && /usr/bin/cc -Dcvhf_EXPORTS 
    -I/home/my-username/repos/pyscf/pyscf/lib/build/vhf -I/home/my-username/repos/pyscf/pyscf/lib/vhf 
    -I/home/my-username/repos/pyscf/pyscf/lib -I/home/my-username/repos/pyscf/pyscf/lib/deps/include 
    -I/usr/local/include -I/home/my-username/repos/pyscf/pyscf/lib/build  
    -Wall -march=native -mtune=native -funroll-loops -ftree-vectorize -O2 -g -DNDEBUG 
    -fPIC   -fopenmp -o CMakeFiles/cvhf.dir/rha_direct_dot.c.o   
    -c /home/my-username/repos/pyscf/pyscf/lib/vhf/rha_direct_dot.c
```
A naive user might try to just add `-Ofast` directly into `CMAKE_C_FLAGS`, e.g. `-DCMAKE_C_FLAGS="-Ofast -march=native -mtune=native -funroll-loops -ftree-vectorize`, but the end result would be build lines like:
```
... -Wall -Ofast -march=native -mtune=native -funroll-loops -ftree-vectorize -O2 -g -DNDEBUG ...
```
And according to the [GCC docs](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html), "[i]f you use multiple -O options, with or without level numbers, the last such option is the one that is effective." So the forced `RelWithDebugInfo` settings win again.

As far as I can see, the only way to actually get `-Ofast`, or even `-O3`, into the build process without modifying CMake files is to set `CMAKE_C_FLAGS_RELWITHDEBINFO` outright. This is likely to catch out inexperienced users who want optimisation but don't build with verbose output. 😄 

#### Sequential MKL libraries

Is there a particular reason why the docs explicitly recommend the use of the sequential Intel MKL libraries? (`-DBLA_VENDOR=Intel10_64lp_seq`?) The build process runs just fine with `-DBLA_VENDOR=Intel10_64lp`, and as far as I can see, linking/resolution goes against the threaded libraries rather than the sequential ones.

The only obvious reason I can think of would be if BLAS functions are being called inside an OpenMP-parallelised loop, and the intention is to avoid any kind of oversubscription due to nested parallelism. I've tried skimming through the code and it doesn't appear that this is the case, but it's highly possible that I'm missing something.

Thanks in advance for any feedback on the above!

**Comment by sunqm** [comment]
CMAKE_BUILD_TYPE was set to RELWITHDEBINFO because we prefer to compile the C extensions with `-O2 -g`. I canged the relevant settings in the latest commit. Using the latest updates, you can set this variable from command line.

BLAS functions was called under OMP threads in integral library and vhf module. It has to be set to sequential mode otherwise these modules can get a huge overhead from context switch.

**Comment by glowthrower** [comment]
Great, thanks for the response!
