### ISSUE TITLE
OpenAI Universe:  FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Saarulog** [pyscf/pyscf#692]
Hello,
I got the below error while trying to run the OpenAI Universe

--installed using -- pip install universe
--Window 10 Pro

thank you,
Saa

(universe) PS C:\Users\shama> cd .\universe\                                                                                                                                                                       (universe) PS C:\Users\shama\universe> pip install -e .                                                                                                                                                            Obtaining file:///C:/Users/shama/universe
Collecting autobahn>=0.16.0
  Using cached autobahn-20.7.1-py2.py3-none-any.whl (1.5 MB)
Collecting docker-py==1.10.3
  Using cached docker_py-1.10.3-py2.py3-none-any.whl (48 kB)
Collecting docker-pycreds==0.2.1
  Using cached docker_pycreds-0.2.1-py2.py3-none-any.whl (4.5 kB)
Collecting fastzbarlight>=0.0.13
  Using cached fastzbarlight-0.0.14.tar.gz (728 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\shama\Anaconda\envs\universe\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\shama\\AppData\\Local\\Temp\\pip-install-k804k5lg\\fastzbarlight\\setup.py'"'"'; __file__='"'"'C:\\Users\\shama\\AppData\\Local\\Temp\\pip-install-k804k5lg\\fastzbarlight\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\shama\AppData\Local\Temp\pip-pip-egg-info-8vnxqbun'
         cwd: C:\Users\shama\AppData\Local\Temp\pip-install-k804k5lg\fastzbarlight\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\shama\AppData\Local\Temp\pip-install-k804k5lg\fastzbarlight\setup.py", line 49, in <module>
        proc = subprocess.Popen(['ld', '-liconv'], stderr=subprocess.PIPE)
      File "C:\Users\shama\Anaconda\envs\universe\lib\subprocess.py", line 729, in __init__
        restore_signals, start_new_session)
      File "C:\Users\shama\Anaconda\envs\universe\lib\subprocess.py", line 1017, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by jamesETsmith** [comment]
Hi @Saarulog PySCF doesn't support Windows and your error doesn't seem to have anything to do with PySCF

**Comment by Saarulog** [comment]
thanks JamesETsmith. I think there is an issue with the fastzbarlight. The #691 is for PySCF. I'm not sure if that is the same issue as mine. what is the fastzbarlight?

**Comment by gkc1000** [comment]
fastzbarlight is not used by PySCF.

**Comment by Saarulog** [comment]
thanks again. Should I ignore the error and move on

**Comment by gkc1000** [comment]
This error is to do with OpenAI-Universe, but this is the pyscf
issues page. I have no idea what will happen with the other components of
OpenAI-Universe, I have never used it. Please raise this issue with them.

**Comment by Saarulog** [comment]
gkc1000, How do I raise the issue with them? is there a link?

**Comment by gkc1000** [comment]
https://github.com/openai/universe

I will close this issue.

**Comment by Saarulog** [comment]
thank you. New to this GitHub. might have placed my issue in wrong request
