### ISSUE TITLE
Why does orth_ao in the lo module first project the atomic basis?

### ISSUE THREAD

**Issue by btglau** [pyscf/pyscf#695]
I want to orthogonalize my mo_coeff matrix from a SCF calculation, i.e. find X s.t. X^{-1}C will orthogonalize FC=SCe. I was going to use the lowdin function as defined in the lo module. However, I see that there is an orth_ao method that is more fully featured, including automatically grabbing the overlap matrix for me. What I don't understand is why it will first project the original basis to a different atomic basis, as seen here:

https://github.com/pyscf/pyscf/blob/4bcb07d51703e3849c1796e620db85f471681568/pyscf/lo/orth.py#L283

Can someone offer an explanation as to the difference between the ortho_ao / lowdin functions?

**Comment by sunqm** [comment]
Code in lo module were first implemented to support population analysis.  The
pre_orth_ao projection is to transform basis functions to orbitals close to
"atomic orbitals". Some basis functions does not have AO characters. Lowdin
orthogonalization for these basis functions does not make much sense in
population analysis. You can skip the projection by passing
pre_orth_ao=np.eye(mol.nao) to the orth_ao functions.

On Thu, Sep 03, 2020 at 06:20:35PM -0700, Bryan Lau wrote:
> I want to orthogonalize my mo_coeff matrix from a SCF calculation. I was going to use the lowdin function as defined in the lo module. However, I see that there is an orth_ao method that is more fully featured, including automatically grabbing the overlap matrix for me. What I don't understand is why it will first project the original basis to a different atomic basis, as seen here:
> 
> https://github.com/pyscf/pyscf/blob/4bcb07d51703e3849c1796e620db85f471681568/pyscf/lo/orth.py#L283
> 
> Can someone offer an explanation as to the difference between the ortho_ao / lowdin functions?
> 
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyscf/pyscf/issues/695

--

**Comment by btglau** [comment]
That makes sense, thanks for the explanation!
