### ISSUE TITLE
No matching distribution found for mpi4pyscf

### ISSUE THREAD

**Issue by mariomotta314** [pyscf/pyscf#703]
Greetings,

I am trying to install mpi4pyscf using pip, as indicated in https://github.com/pyscf/mpi4pyscf.
The command `pip install mpi4pyscf` throws the following error:

ERROR: Could not find a version that satisfies the requirement mpi4pyscf (from versions: none)
ERROR: No matching distribution found for mpi4pyscf

Can you please help me understanding why? 
If useful, I use pip 20.0.2, python 3.7.6, mpi4py 3.0.3, pyscf 1.7.3 and macOS Catalina 10.15.6

regards,
Mario

**Comment by yangcal** [comment]
Hi Mario,

It appears mpi4pyscf was not released on PyPI, not sure why. In any case, it is a plugin that does not require compilation. If you clone it and add it to your PYTHONPATH, it should work.

Best,
Yang

**Comment by sunqm** [comment]
A temporary solution pip install git+https://github.com/pyscf/mpi4pyscf.git

**Comment by sunqm** [comment]
mpi4pyscf-0.3 is now available on pypi https://pypi.org/project/mpi4pyscf/

**Comment by sunqm** [comment]
mpi4pyscf-0.3 is now available on pypi https://pypi.org/project/mpi4pyscf/

**Comment by solo-cyber** [comment]
can anyone tell where exactly i have to add this.

**Comment by sunqm** [comment]
Does it work for you?
```
pip install git+https://github.com/pyscf/mpi4pyscf
```

**Comment by mariomotta** [comment]
hi Qiming,
The command *pip install git+https://github.com/pyscf/mpi4pyscf
<https://github.com/pyscf/mpi4pyscf>* works for me.
Many thanks, and happy new year!
mario
