### ISSUE TITLE
FCI not taking mf._eri in ao2mo when using RHF referencce

### ISSUE THREAD

**Issue by hongzhouye** [pyscf/pyscf#704]
It seems that line 155 in `pyscf/fci/__init__.py`:
```python
eri = ao2mo.kernel(mol, mo)
```
should be modified to
```python
eri = ao2mo.kernel(eri_ao, mo)
```
where `eri_ao` is defined previously in lines 128 -- 130. Otherwise `mf._eri` is not used and the ERI transform is always outcore.

**Comment by fishjojo** [comment]
Thanks. This has been fixed.
