### ISSUE TITLE
MCSCF dipole moment

### ISSUE THREAD

**Issue by jtraver70** [pyscf/pyscf#705]
Dear PySCF experts,

I am new to PySCF. I tried to compute the dipole moment (DM) and transition dipole moment (TDM) at the MCSCF level of theory. I followed the example provided. For a small molecule (CH4 in C1 symmetry, CASSCF(8e,8o)), I obtained almost the exactly same results (both DM and TDM)  as compared to those computed using molpro. However, when working on a large molecule (~140 atoms no symmetry), the DM results became very strange (at least compared to TDDFT). The computed DMs of all states (state-average CASSCF) are all very large, which is unreasonable. The CASSCF ground state DM is about 100 times larger than the HF and DFT values. This is a close-shell organic molecule. There is no multi-reference issue  for the ground state. The CASSCF ground state DM for sure is wrong. I am not sure where I made mistake. Any insight?

Thanks!

John

Here is the part of the relevant inputs

mc3 = mcscf.CASCI(mf, ncas, nelec)
mc3.fcisolver.nroots = 4
mc3 = mc3.state_average_([0.25,0.25,0.25,0.25)]
mc3.fix_spin_(ss=0)
mc3.__dict__.update(scf.chkfile.load('s1_00_4state.chk', 'mcscf'))
mc3.kernel()

print('  ')
print('**** Transition Dipole Moments **** ')

nstate=4

for ia in range(nstate):
    for ib in range(ia,nstate):
        t_dm = mc3.fcisolver.trans_rdm1(mc3.ci[ia], mc3.ci[ib], ncas, nelec)
        # Transform to AO representation  ncore:ncore+nelec
        mo_cas = mc3.mo_coeff[:,mc3.ncore:mc3.ncore+mc3.ncas]
        t_dm = numpy.einsum('pi,ij,qj->pq', mo_cas, t_dm, mo_cas)

        charge_center = (numpy.einsum('z,zx->x', mol.atom_charges(), mol.atom_coords())
                        / mol.atom_charges().sum())

          with mol.with_common_origin(charge_center):
           t_dip = numpy.einsum('xij,ji->x', mol.intor('int1e_r'), t_dm)
           print('Moment betwee ',ia,' and ',ib)
           print(t_dip)
           print('             ')

**Comment by gkc1000** [comment]
It looks like you are not using the full DM, only the active space. This
means the electronic charge is too small. I think the slice should be
mo_coeff[:,:mc3.ncore+mc3.ncas].

**Comment by jtraver70** [comment]
Thanks!

**Comment by jtraver70** [comment]
Hi 

I got an error when I used "mo_coeff[:,:mc3.ncore+mc3.ncas]". The error message looks like "

  File "test_09.py", line 66, in <module>
    t_dm_ao = numpy.einsum('pi,ij,qj->pq', mo_cas, t_dm, mo_cas)
  File "<__array_function__ internals>", line 6, in einsum
  File "/home/software/python-3.7.8B/lib/python3.7/site-packages/numpy/core/einsumfunc.py", line 1350, in einsum
    return c_einsum(*operands, **kwargs)"

Any suggestion? Thanks!

**Comment by gkc1000** [comment]
Print out the shapes of the mo_coeff and the trans_rdm to check. By the way
things are being called, I'm guessing the trans_rdm does not have the
"core" part of the DM (which is trivial in the MO representation, just an
identity of dimension ncorexncore). So you could do a direct sum with such
an identity before transformation, or you could transform the active space
DM by itself and then add on the core part of the DM in the AO basis.

**Comment by jtraver70** [comment]
Thanks for the explanation! I understand what's going on here, however, I am not sure how to achieve the suggested means to include the core contributions to the DM ( using PySCF less than about a week). Is it possible you can provide a sample of the input? Much appreciated!

**Comment by jtraver70** [comment]
Now I am able to extend the dimension of the density matrix in MO  (from mc3.fcisolver.trans_rdm1(mc3.ci[ia], mc3.ci[ib], ncas, nelec)) by appending a diagonal part corresponding to the core orbitals. By doing this, now the computed dipole moment seems normal, however, the transition dipole moment becomes very large!  Any insight?

I am also confused with the density matrix transformation using numpy.einsum('pi,ij,qj->pq', mo_cas, t_dm, mo_cas). This function transforms a density matrix in MO basis to a density matrix in AO basis. However, this transformation should involve the AO overlap, something like, DM_MO = transpose(mo_cas) * S * DM_AO * S * mo_cas. Does the numpy.einsum('pi,ij,qj->pq', mo_cas, t_dm, mo_cas) operation include the AO overlap contribution? Thanks!

**Comment by gkc1000** [comment]
Without more info from your script, I cannot deduce the problem, it would
seem like a bug in the script.

One does not need an overlap matrix to transform from the MO basis to the
AO basis. You need to know how the MOs are written as a linear combination
of AOs. That is what you are multiplying together in the einsum function.

**Comment by jtraver70** [comment]
My input looks like

charges = mol.atom_charges()
coords = mol.atom_coords()
nuc_charge_center = numpy.einsum('z,zx->x', charges, coords) / charges.sum()
mol.set_common_orig_(nuc_charge_center)
dip_ints = mol.intor('int1e_r')


nstate=4
for ia in range(nstate):
    for ib in range(ia,nstate):
        
        # Density Matrix in the active space
        t_dm = mc3.fcisolver.trans_rdm1(mc3.ci[ia], mc3.ci[ib], ncas, nelec)

        #  Density Matrix from the core orbitals
        t_dm_mo = [[0 for x in range(mc3.ncore+mc3.ncas)] for y in range(mc3.ncore+mc3.ncas)]
        
        # diagonal part
        for ir in range (mc3.ncore):
            t_dm_mo[ir][ir]=2.0
        
        # add the cas space DM
        for ir in range (mc3.ncore, mc3.ncore+mc3.ncas):
            for ic in range (mc3.ncore, mc3.ncore+mc3.ncas):
                t_dm_mo[ir][ic] = t_dm[ir-mc3.ncore][ic-mc3.ncore]
        
        # debugging
        for ir in range (mc3.ncore+mc3.ncas):
                    for ic in range (mc3.ncore+mc3.ncas):
                                    print(ir,ic,t_dm_mo[ir][ic])
        
        # Transform to AO representation  :ncore+nelec
        mo_cas = mc3.mo_coeff[:,:mc3.ncore+mc3.ncas]
        t_dm_ao = numpy.einsum('pi,ij,qj->pq', mo_cas, t_dm_mo, mo_cas)

        with mol.with_common_origin(nuc_charge_center):
           t_dip = numpy.einsum('xij,ji->x', dip_ints, t_dm_ao)
           print('Moment betwee ',ia,' and ',ib)
           print(t_dip)
           print('  ')

**Comment by fishjojo** [comment]
The ground-state AO density matrix (including the core part) can be computed by `mc.make_rdm1()`. Example in https://github.com/pyscf/pyscf/blob/master/examples/mcscf/15-transition_dm.py should give the transition density between CASCI states, where core density is not needed.

**Comment by jtraver70** [comment]
Thanks! For the transition dipole moment between the CASCI states one doesn't need the core part. For the dipole moment, is there a convenient way to generate the AO density matrix (including the core part) for a specific CASCI state? or Is the way I used to generate the the AO density matrix correct? (the input I posted earlier).

**Comment by fishjojo** [comment]
Following is kind of a hack to get the AO density for each CASCI state.
```
ncas = 4
ne = 4
mocore = mc.mo_coeff[:,:mc.ncore]
mocas = mc.mo_coeff[:,mc.ncore:mc.ncore+mc.ncas]
dm1 = numpy.dot(mocore, mocore.conj().T) * 2
istate = 1
casdm1 = mc.fcisolver._base_class.make_rdm1(mc.fcisolver, mc.ci[istate], ncas, ne)
dm1 = dm1 + reduce(numpy.dot, (mocas, casdm1, mocas.conj().T))
```

**Comment by jtraver70** [comment]
Thank you so much for this concise code! Fortunately, my lengthy input produced the same results! but yours is definitely a better choice!
