### ISSUE TITLE
Integrals of dot products of gradients -- which intor string?

### ISSUE THREAD

**Issue by glowthrower** [pyscf/pyscf#716]
A quick question. I need to calculate one-electron integrals of the form `\int \nabla\chi_i \dot \nabla\chi_j dr` -- that is, the integral of the dot product of the gradients of the (contracted Gaussian) AOs `\chi_i` and `\chi_j` -- and I'm not entirely sure which `intor` specifier to use.

I see that there is 'ipovlpip', which according to the libcint documentation should be something of the form `<nabla | nabla>`. Are the components of the output of this of the form `< d/dr_i | d/dr_j >`, i.e. integrals of products of partial derivatives over the two input AOs, or are the derivatives mixed or otherwise not what I expect?

Phrasing it differently, am I correct in thinking that I can achieve the integral form specified above by, e.g.,
```python
> ao_cross_grad = mol.intor('int1e_ipovlpip')
```
and then calculating the full integrals of the dot products as
```python
> ao_dot_grads = ao_cross_grad[[0, 4, 8]].sum(axis=0)
```

**Comment by fishjojo** [comment]
Yes, your code is right.
