### ISSUE TITLE
problems to run dmrg

### ISSUE THREAD

**Issue by jtraver70** [pyscf/pyscf#717]
I tried to run the DMRG-NEVPT2 example (nevpt2.py) provided by the pySCF code. I used the pre-compiled  block.spin_adapted-1.5.3 and block.spin_adapted-1.5.3-serial (https://sunqm.github.io/Block/build.html#) and modified the settings.py accordingly. The calculation failed at the DMRG-NEVPT step. The output files and the error messages are attached. 

I also compiled the Block code myself (gcc-4.9.2, boost-1-55, and openmpi-3.1.6). I saw the similar errors when running  the nevpt2.py example.

Could someone please give some suggestions? 

[nevpt2.err.log](https://github.com/pyscf/pyscf/files/5308865/nevpt2.err.log)
[fci_nevpt2.log](https://github.com/pyscf/pyscf/files/5308866/fci_nevpt2.log)
[dmrg.log](https://github.com/pyscf/pyscf/files/5308867/dmrg.log)
[dmrg_nevpt2_slow.log](https://github.com/pyscf/pyscf/files/5308868/dmrg_nevpt2_slow.log)

**Comment by fishjojo** [comment]
Can you post your input? Seems like the .chk file is missing in your calculation.

**Comment by jtraver70** [comment]
Thanks for the response! The input file is provided by the PySCF code. Here it is
[nevpt2.py.log](https://github.com/pyscf/pyscf/files/5344997/nevpt2.py.log)

**Comment by fishjojo** [comment]
Unfortunately, I'm not able to reproduce the error. What if you upgrade h5py and retry?

**Comment by jtraver70** [comment]
Thanks! I will try upgrade h5py

**Comment by jtraver70** [comment]
I updated h5py, and also used the latest pyscf-1.7.5. There is some progress. now at lease the dmrgscf.DMRGCI part finished smoothly. The program stopped at the mps_nevpt_e2 = mrpt.NEVPT(mc,root=1).compress_approx(maxM=100).kernel() part. The error message looks like "ERROR: srun /home/jt19/apps/pyscf/pyscf-1.7.5-gcc-4.9.2/pyscf/dmrgscf/nevpt_mpi.py /scr/jt19/nevpt2.4619157/80379/nevpt_perturb_integral /home/jt19/apps/Block/block.spin_adapted-1.5.3-serial /scr/jt19/nevpt2.4619157/80379 /scr/jt19/nevpt2.4619157/80379
Traceback (most recent call last):
  File "nevpt2.py", line 133, in <module>
    mps_nevpt_e1 = mrpt.NEVPT(mc,root=0).compress_approx(maxM=100).kernel()
  File "/home/jt19/apps/pyscf/pyscf-1.7.5-gcc-4.9.2/pyscf/mrpt/nevpt2.py", line 753, in kernel
    tol=self.tol)
  File "/home/jt19/apps/pyscf/pyscf-1.7.5-gcc-4.9.2/pyscf/dmrgscf/nevpt_mpi.py", line 250, in DMRG_COMPRESS_NEVPT
    raise err
  File "/home/jt19/apps/pyscf/pyscf-1.7.5-gcc-4.9.2/pyscf/dmrgscf/nevpt_mpi.py", line 247, in DMRG_COMPRESS_NEVPT
    subprocess.check_call(cmd, shell=True)
  File "/home/software/python-3.7.8B/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'srun /home/jt19/apps/pyscf/pyscf-1.7.5-gcc-4.9.2/pyscf/dmrgscf/nevpt_mpi.py /scr/jt19/nevpt2.4619157/80379/nevpt_perturb_integral /home/jt19/apps/Block/block.spin_adapted-1.5.3-serial /scr/jt19/nevpt2.4619157/80379 /scr/jt19/nevpt2.4619157/80379' returned non-zero exit status 127."

The output of the dmrgscf.DMRGCI part looks like "
WARN: Mulitple states found in CASCI solver. First state is used to compute the natural orbitals in active space.

FCI vector not available, call CASCI to update wavefunction
Natural occ [1.96428897 1.89469786 0.10763596 0.0333772 ]
Natural orbital (expansion on meta-Lowdin AOs) in CAS space
               #1        #2        #3        #4
  0 H 1s       0.42322  -0.45430   0.45003  -0.41015
  1 H 1s       0.41308  -0.16411  -0.18334   0.42422
  2 H 1s      -0.01624   0.41156  -0.40705   0.01161
  3 H 1s      -0.38728   0.31193   0.31332  -0.38946
  4 H 1s      -0.38728  -0.31193   0.31332   0.38946
  5 H 1s      -0.01624  -0.41156  -0.40705  -0.01161
  6 H 1s       0.41308   0.16411  -0.18334  -0.42422
  7 H 1s       0.42322   0.45430   0.45003   0.41015
<CAS-nat-orb|mo-hf>  3  3    0.99941286
<CAS-nat-orb|mo-hf>  4  4    0.99958494
<CAS-nat-orb|mo-hf>  5  5    0.99941286
<CAS-nat-orb|mo-hf>  6  6    0.99958494
CASCI state 0  E = -4.22363983079619  E(CI) = -3.16575400078438  S^2 = 0.0000000
CASCI state 1  E = -3.85792252232184  E(CI) = -2.80003669231003  S^2 = 0.0000000
Use compressed mps perturber as an approximation
DMRG-NEVPT
Canonicalize orbitals for root 0

ERROR: srun /home/jt19/apps/pyscf/pyscf-1.7.5-gcc-4.9.2/pyscf/dmrgscf/nevpt_mpi.py /scr/jt19/nevpt2.4619157/80379/nevpt_perturb_integral /home/jt19/apps/Block/block.spin_adapted-1.5.3-serial /scr/jt19/nevpt2.4619157/80379 /scr/jt19/nevpt2.4619157/80379

**Comment by verena-neufeld** [comment]
Hi @jtraver70 , thanks for having raised this issue. Has it been resolved now?

**Comment by sunqm** [comment]
I guess it's a problem of bash login/non-login shell initialization problem. The Python module was not properly loaded in the bash non-login shell. This is unlikely a bug in pyscf code.
