### ISSUE TITLE
TextIOWrapper objects are not serializable, preventing use of dask distributed and concurrent.futures

### ISSUE THREAD

**Issue by lkwagner** [pyscf/pyscf#720]
The code: 
```
import pyscf
import concurrent.futures

def runhf(mol):
    myhf = pyscf.scf.RHF(mol)
    myhf.kernel()
    return myhf.e_tot


def main():
    mol = pyscf.M(
        atom = 'H 0 0 0; F 0 0 1.1',  # in Angstrom
        basis = 'ccpvdz',
        symmetry = True,
    )

    with concurrent.futures.ProcessPoolExecutor(max_workers=2) as executor:
        d = executor.submit(runhf, mol)
        print("energy = ", d.result())


if __name__=="__main__":
    main()
```

Errors with `TypeError: cannot pickle '_io.TextIOWrapper' object.` 

If we instead do

```
import pyscf
import concurrent.futures

def runhf(mol):
    myhf = pyscf.scf.RHF(mol)
    myhf.kernel()
    return myhf.e_tot


def main():
    mol = pyscf.M(
        atom = 'H 0 0 0; F 0 0 1.1',  # in Angstrom
        basis = 'ccpvdz',
        symmetry = True,
        verbose=0
    )

    with concurrent.futures.ProcessPoolExecutor(max_workers=2) as executor:
        mol.stdout=None
        mol.output=None
        d = executor.submit(runhf, mol)
        print("energy = ", d.result())


if __name__=="__main__":
    main()
```

The code runs, but this seems to be a non-ideal solution to me.

**Comment by fishjojo** [comment]
pyscf will write results to either sys.stdout or a user defined file, and this should be done within each process. The following code should work.
```
import pyscf
import concurrent.futures

def runhf():
    mol = pyscf.M(
        atom = 'H 0 0 0; F 0 0 1.1',  # in Angstrom
        basis = 'ccpvdz',
        symmetry = True,
    )
    myhf = pyscf.scf.RHF(mol)
    myhf.kernel()
    return myhf.e_tot


def main():
    with concurrent.futures.ProcessPoolExecutor(max_workers=2) as executor:
        d = executor.submit(runhf)
        print("energy = ", d.result())

if __name__=="__main__":
    main()
```

**Comment by lkwagner** [comment]
I'm aware that will work, and understand the implementation. However, this implementation limits what you can do--for example, in our pyqmc implementation, we use the mol object as part of the wave function calculator object. This has to be communicated to potentially 1000's of workers. On a HPC system, you cannot have 1000's of workers grabbing the information from disk separately or they will throw you off the system. I can imagine similar applications that would encounter this. 

The Python standard library does provide the logging module: https://docs.python.org/3/library/logging.html which can be pickled/unpickled. Is there a reason this is not used?

**Comment by fishjojo** [comment]
The latest commit (cb6dfe4) should work. Please let me know if there are other problems.

**Comment by lkwagner** [comment]
Cool, thanks! I will check it out.

**Comment by sunqm** [comment]
> I'm aware that will work, and understand the implementation. However, this implementation limits what you can do--for example, in our pyqmc implementation, we use the mol object as part of the wave function calculator object. This has to be communicated to potentially 1000's of workers. On a HPC system, you cannot have 1000's of workers grabbing the information from disk separately or they will throw you off the system. I can imagine similar applications that would encounter this.
> 
> The Python standard library does provide the logging module: https://docs.python.org/3/library/logging.html which can be pickled/unpickled. Is there a reason this is not used?

When implementing logger module, my needs were a simple logger object working in local scope, side effects free, like regular Python objects. By that time, I don't know how to customize the builtin logging module properly. The builtin logging module seems too complicated to do the simple job.
