### ISSUE TITLE
damp has no effects in pbc kmf?

### ISSUE THREAD

**Issue by zhcui** [pyscf/pyscf#721]
Hi all,

I just find that the kmf.damp has no effects on the SCF loop in PBC. Is this a bug?
The line is here: https://github.com/pyscf/pyscf/blob/5796d1727808c4ab6444c9af1f8af1fad1bed450/pyscf/pbc/scf/khf.py#L152

But the damping factor is not used.

Best,
Zhihao

**Comment by gkc1000** [comment]
Haven't looked carefully, but v. likely just an omission. Look at the
molecular code and copy it into the pbc version and file a pull request.
