### ISSUE TITLE
What is the purpose of the "adjust phase" code in lo/orth and scf/hf?

### ISSUE THREAD

**Issue by btglau** [pyscf/pyscf#724]
I am referencing these two blocks of code:

https://github.com/pyscf/pyscf/blob/master/pyscf/lo/orth.py#L303
https://github.com/pyscf/pyscf/blob/master/pyscf/scf/hf.py#L1120

Explanation: I would like to use the 'lowdin' function from the lo module, as I also want the inverse transformation matrix X^{-1}, but I'm not sure if the phase need to be adjusted from the output of lowdin as well. The code that adjusts phase in lo/orth seems to be related to the one in scf/hf?

**Comment by tberkel** [comment]
I didn't write them, but I would guess it has to do with the fact that
certain quantities require a "consistent" choice of the phase of the
mean-field eigenvectors (which are of course only defined up to an
arbitrary phase, which is +/- 1 if the eigenvector is real).  Without
enforcing a convention, the eigenvectors will have a random phase when they
are returned by the eigensolver.  One example where this matters is in the
calculation of certain expectation values or matrix elements, such as the
transition dipole matrix.

**Comment by btglau** [comment]
I see now - both codes ensure that the largest coefficient is always positive. Thanks!
