### ISSUE TITLE
dfmp2 does not return t2 amplitudes (missing code)

### ISSUE THREAD

**Issue by btglau** [pyscf/pyscf#728]
Hello,

The kernel of dfmp2 is missing code to return t2 for the default value of WITH_T2 = True:
https://github.com/pyscf/pyscf/blob/master/pyscf/mp/dfmp2.py#L55

It just needs the lines from here:
https://github.com/pyscf/pyscf/blob/master/pyscf/mp/mp2.py#L50
https://github.com/pyscf/pyscf/blob/master/pyscf/mp/mp2.py#L68

With the replacement
`dtype=eris.ovov.dtype -> dtype=Lov.dtype`

**Comment by fishjojo** [comment]
Thanks. This has been fixed in 8ea7fe4

**Comment by btglau** [comment]
thank you!
