### ISSUE TITLE
XCFun commit in "Install without network" (manual) out of date

### ISSUE THREAD

**Issue by drewrisinger** [pyscf/pyscf#730]
The changelog says that XCFun has been updated to v2.1.0 as of pyscf v1.7.5: https://github.com/pyscf/pyscf/blob/bcdb399a24483bea383b6d826f70ab02fb1bf399/CHANGELOG#L11-L12

The manual (and website) still state that ``xcfun v1.x`` should be used: https://github.com/pyscf/pyscf/blob/bcdb399a24483bea383b6d826f70ab02fb1bf399/doc_legacy/source/install.rst#installation-without-network

**Comment by fishjojo** [comment]
Thanks. The latest docs are maintained in [here](https://github.com/pyscf/pyscf-doc). And the webpage is [here](http://pyscf.org/pyscf/index.html).

**Comment by drewrisinger** [comment]
I see. Thanks for updating that!
