### ISSUE TITLE
Large vacuum in 2D PBC calculations and computation time of hcore Hamiltonian

### ISSUE THREAD

**Issue by maxnus** [pyscf/pyscf#734]
I am interested in 2D systems with molecular substrates, such as the water-LiH(slab) system in the example file attached.
Using GDF, I generally find that very large vacuum sizes are needed to converge the total energy; 35A for the simple water<--8A-->LiH(1layer)  system in the example, exceeding what I would expect on grounds of how far the electron density reaches into the vacuum. Additionally, for smaller vacuums, the mean-field calculation often does not converge, i.e. large vacuums are needed even for test calculations. I think as a result of this large vacuum, the calulcation of the hcore Hamiltonian becomes expensive,
roughly half of the total time for the mean-field in the attached example. Since the general design of PySCF seems to be to recalculate `hcore` whenver needed, this can become also a big bottleneck in subsequent calculations; for example `_ChemistsERIs`
in MP2/CC calculations generally recompute the Fock and thus hcore matrix. In my application this becomes the main bottleneck, since the DF based AO2MO transformation is much faster. A similar incidence of "inopportunely spent computation time", although to a lesser extent, is the nuclear repulsion energy, which can often take a second or so to calculate in these 2D systems, but is recalculated every SCF cycle.

The purpose of this post is twofold: First, I would like understand if the requirement of large vacuums in 2D systems can be circumvented. Second, I would suggest implementing some kind of memoization for routines such as `get_hcore` or `energy_nuc`, possibly checking that relevant parameters have not changed to keep the objects as stateless as possible.

[example.txt](https://github.com/pyscf/pyscf/files/5371133/example.txt)

**Comment by fishjojo** [comment]
It depends on the diffuseness of the basis functions. If you set `cell.exp_to_discard=0.1`, which discards the basis functions with exponents smaller than 0.1, you would get
```
25.0         -80.870066   9.894
27.5         -80.870108   10.17
30.0         -80.870108   10.81
32.5         -80.870108   11.66
35.0         -80.870109   11.79
37.5         -80.870108   12.06
40.0         -80.870109   12.81
```
Also, by setting `cell.precision=1e-4`, you would expect energy change smaller than 1e-3 as converged.

**Comment by gkc1000** [comment]
You should see a much weaker dependence with a pure DFT functional - the
slow convergence is a feature of the exact exchange. It can be corrected by
using one or more of the exxdiv options e.g. exxdiv=ws.

If you are mainly doing surfaces in 2d with pure DFT and pseudopotentials
you can set cell.dim=2 and use FFTDF. This can be faster than GDF.

**Comment by Majokux** [comment]
Many thanks for the responses!

@fishjojo
The `exp_to_discard` helps a bit, I will keep it in mind - I assume a similar thing could be achieved by canonical orthogonalization and removing small eigenvalues of S?
If you don't mind, could you let me know what CPU and how many OpenMP threads you were using? With an Intel Xeon E5-2697 v4 and 36 threads my times for the HF are still twice as long, so I'm worried some of my libraries are not optimal.

@gkc1000
I am generally performing post-HF (CCSD) calculations afterwards, so DFT is not an option. `exxdiv = ewald` seems to be the default, which is what I am always using. I believe there is no inconsistency with the CCSD, since the later rebuilds the Fock matrix, i.e. uses non shifted orbital energies?
FFTDF always seems to be unfeasibly slow for me (even when reducing the vacuum size), again I might not be correctly linked to FFTW3 or what library is used here.

**Comment by tberkel** [comment]
The kinetic energy cutoff used for FFTDF is very conservative.  You could
try lowering it by hand, e.g. cell.ke_cutoff = 70 or 100, and doing some
testing to find the KE cutoff needed for your desired accuracy.
Alternatively, you could try Gaussian density fitting (GDF), which can be
faster, with only a small DF error.

**Comment by sunqm** [comment]
Setting explicitly `cell.dimension = 2` would lead to the best accuracy and performance for a 2D system. In this case, a reasonable vacuum size is still required. You would get a warning msg if the vacuum size is not big enough. GDF can be applied along with this setting, for both SCF and post-SCF method.

**Comment by verena-neufeld** [comment]
Hi @maxnus , has this been resolved?

**Comment by verena-neufeld** [comment]
@maxnus , thanks for posting this issue!
@maxnus, @fishjojo , @sunqm can we close this issue? It hasn't been active for a while.

**Comment by sunqm** [comment]
I think it can be closed. `cell.dimension=2` is the solution for this issue.
