### ISSUE TITLE
Can't Compile the latest PySCF(pyscf-1.7.5) 

### ISSUE THREAD

**Issue by leebo-2020** [pyscf/pyscf#738]
Dear developers of PySCF,
When i compile latest pyscf-1.7.5, i can't compile libxcfun, because libxcfun need higher cmake(3.14), however the cmkae version is 3.5.1 in our cluster, i responsed the issue with our administrator who reject my requirement. So, developers of pyscf can give a solution way? thanks all.

**Comment by fishjojo** [comment]
xcfun is not mandatory. you can try ` cmake -DBUILD_XCFUN=OFF`

**Comment by leebo-2020** [comment]
you mean that delete BUILD_XCFUN:BOOL=ON in CMakeCache.txt ?

**Comment by leebo-2020** [comment]
> 
> 
> xcfun is not mandatory. you can try ` cmake -DBUILD_XCFUN=OFF`

you mean that delete BUILD_XCFUN:BOOL=ON in CMakeCache.txt ?

**Comment by fishjojo** [comment]
No, just
```
 cd pyscf/lib
 mkdir build; cd build
 cmake -DBUILD_XCFUN=OFF ..
 make
```

**Comment by leebo-2020** [comment]
> 
> 
> No, just
> 
> ```
>  cd pyscf/lib
>  mkdir build; cd build
>  cmake -DBUILD_XCFUN=OFF ..
>  make
> ```

i try your method, but a new issue ocur : fatal error: XCFun/xcfun.h: No such file or directory

**Comment by leebo-2020** [comment]
> 
> 
> No, just
> 
> ```
>  cd pyscf/lib
>  mkdir build; cd build
>  cmake -DBUILD_XCFUN=OFF ..
>  make
> ```

i tried it according to your method, but a new issue occurs : fatal error: XCFun/xcfun.h: No such file or directory

**Comment by fishjojo** [comment]
I see. You can use pre-compiled libraries.
In the `lib` directory, run
`curl http://www.sunqm.net/pyscf/files/bin/pyscf-1.7.5-deps.tar.gz | tar xzf -`

**Comment by leebo-2020** [comment]
> 
> 
> I see. You can use pre-compiled libraries.
> In the `lib` directory, run
> `curl http://www.sunqm.net/pyscf/files/bin/pyscf-1.7.5-deps.tar.gz | tar xzf -`
> Then do the cmake and make as above.

Latest PySCF has been successfully installed, thank you again!

**Comment by leebo-2020** [comment]
> 
> 
> I see. You can use pre-compiled libraries.
> In the `lib` directory, run
> `curl http://www.sunqm.net/pyscf/files/bin/pyscf-1.7.5-deps.tar.gz | tar xzf -`
> Then do the cmake and make as above.

when i compile to use cmake -DBLA_VENDOR=Intel10_64lp_seq  -DBUILD_XCFUN=OFF .. , and then testing, occurs a error : Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so. . , but installation manual note that useing  cmake -DBLA_VENDOR=Intel10_64lp_seq can improve 10x sppeedup, so how solve this issue ?

**Comment by vamshimohank** [comment]
Try doing this before you run a calculation 
>> export LD_PRELOAD=$MKLROOT/lib/intel64/libmkl_avx.so:$MKLROOT/lib/intel64/libmkl_core.so

more on this is [here](http://pyscf.org/pyscf/install.html#using-optimized-blas) 

Regards
Vamshi

**Comment by leebo-2020** [comment]
> export LD_PRELOAD=$MKLROOT/lib/intel64/libmkl_avx.so:$MKLROOT/lib/intel64/libmkl_core.so

well, it's ok. thank you again

**Comment by sunqm** [comment]
xcfun can be switched off by
```
cmake -DENABLE_XCFUN=OFF ..
```

On Wed, Oct 14, 2020 at 11:58:43PM -0700, leebo-2020 wrote:
> > 
> > 
> > No, just
> > 
> > ```
> >  cd pyscf/lib
> >  mkdir build; cd build
> >  cmake -DBUILD_XCFUN=OFF ..
> >  make
> > ```
> 
> i tried it according to your method, but a new issue occurs : fatal error: XCFun/xcfun.h: No such file or directory
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyscf/pyscf/issues/738#issuecomment-708943508

--
