### ISSUE TITLE
Large memory cost for HF calculation.

### ISSUE THREAD

**Issue by zhigang90** [pyscf/pyscf#742]
Dear developers,

I updated to 1.7.5 recently and found that for a system with only 600 basis functions, over 120 GB memory is used during HF calculation. And for an even larger system, the job crashed with "segmentation fault" error. Is there any trick for HF calculation?

**Comment by jamesETsmith** [comment]
Can you please post your input for those two jobs along with the corresponding output?

**Comment by zhigang90** [comment]
> Can you please post your input for those two jobs along with the corresponding output?

[vdz.log](https://github.com/pyscf/pyscf/files/5392497/vdz.log)
[avdz.log](https://github.com/pyscf/pyscf/files/5392498/avdz.log)
[die.log](https://github.com/pyscf/pyscf/files/5392519/die.log)

I am enclosing three files. My input is generated by a script and it is a little bit complicated. I think the outputs are enough. They contain the input files. 
(1) a system with the cc-pvdz basis set. Large memroy (120GB + ) memory is used.
(2) the same system with the aug-cc-pvdz basis set. Surprisingly although it is larger than case (1), it needs very little memory, as a normal HF calculation.
(3) a larger system. The job died without any HF iteration.

**Comment by jamesETsmith** [comment]
@zhigang90 my first suggestion would be to set `mol.verbose=5` (or even 6) which may help identifying exactly where the jobs are failing. If you could trying rerunning them with this setting and posting the tail end of the output and then sharing it here that might be helpful.

From a first look at your outputs, in job 1 and 2 you're setting `mol.max_memory=250000` which is considerably more than you need as indicated by the current memory printed in the output which shows about 100 MB of memory is used for both. I would decrease these to something less than your available memory.

**Comment by fishjojo** [comment]
Because you set max_memory to 250 GB, which is enough for storing the 4-center integrals in memory (for 600 basis functions, you need about 120 GB), PySCF will store the 4-center integrals in memory.

**Comment by zhigang90** [comment]
@jamesETsmith   @fishjojo  Thank you James and Xing. I set the max_memory to 250 GB because I found that the third job cannot run with default memory settings. Now I have deleted the memory setting. The first two jobs are normal now, but the third job still dies. See the attached file please.

[die.log](https://github.com/pyscf/pyscf/files/5394850/die.log)

**Comment by gkc1000** [comment]
Unfortunately this is still not super useful. I don't know if there is a
more verbose level, maybe try verbose=9?

If that doesn't work, one will have to put print statements into the
pyscf.scf.hf.kernel() function to see where it is dying.

**Comment by zhigang90** [comment]
@gkc1000 Thank you! I have tried verbose=9 and no more information is printed out. Actually this is not the first time I met with such problem. I used to run the same job on the nodes equipped with the same hardwares, one was successful but another died.

**Comment by gkc1000** [comment]
So, this error seems to occur only on certain hardware - is this all with
the same libraries?

If you prepare the final geometry and input file, rather than the large
script, we can try running it to see if it dies.

**Comment by zhigang90** [comment]
@gkc1000 

I am enclosing the input and output files. 

[test.log](https://github.com/pyscf/pyscf/files/5394932/test.log)
[test.txt](https://github.com/pyscf/pyscf/files/5394933/test.txt)

**Comment by xubwa** [comment]
Although at first I feel suspicious about the user defined eig function, but I just tried to run a calculation with and without that user defined eig function, both at least finish the first iteration. Maybe you can provide the error information instead of only the log of your calculation. Sometimes the error information is printed elsewhere such as if you are using slurm, then it is printing normal output to screen or anywhere you redirect it to, but error information is printed to the slurm log file.
Xubo

**Comment by fishjojo** [comment]
The condition number of overlap matrix is about 2000, so there is no need to remove linear dependency. Each Fock build takes about half an hour on 28 CPU cores with 100 GB of memory. It seems that your calculation didn't pass through the first Fock build.

**Comment by sunqm** [comment]
Does the same input work on older version, like pyscf-1.7.4?
Are the dependent libraries and C extensions freshly compiled?

**Comment by zhigang90** [comment]
@xubwa No other error information is printed out. Only the 'segmentation fault' error.

**Comment by zhigang90** [comment]
@fishjojo I remove linear dependency since I use the same template for all jobs. I have tried to remove the remove dependency part. It still doesn't work.

**Comment by zhigang90** [comment]
@sunqm It works with 1.7.0a. I installed everything locally and freshly.

**Comment by zhigang90** [comment]
@sunqm @gkc1000 @fishjojo @jamesETsmith @xubwa 
Dear all, now everything is OK when I change Libcint to version 3.0.20. I used to use version 4.

**Comment by ndattani** [comment]
@zhigang90  in order to get this working, you downgraded form Libcint Version 4 to Version 3.0.20?
