### ISSUE TITLE
Active-active orbital rotations

### ISSUE THREAD

**Issue by portega-usal** [pyscf/pyscf#747]
Greetings,

I read this paper about CASSCF with SHCI in PySCF (https://doi.org/10.1021/acs.jctc.7b00900) and I would like to know how the fixed active space (named with aHCISCF notation) is obtained. I need to keep a fixed active space along a reaction path, so I need to disable inactive-active rotations and keep only active-active rotations. I would perform full-CI SHCI after that. 

Thanks in advance,
Pablo

**Comment by jamesETsmith** [comment]
Hi Pablo,

If we define `mc` as `mc = shci.SHCISCF`, you can set the `mc.frozen` attribute using a list of orbital indices that you want to freeze (i.e. not change). Then you can set `mc.internal_rotation=True` to perform the active-active rotations.

Be aware that optimizing active-active rotations tends to be numerically unstable and you should contain the number of MCSCF iterations (w/ `mc.max_cycle_macro`) to something small like 10-20 iterations.

**Comment by portega-usal** [comment]
Thanks for your answer, it seems to be working by now. Would it have any meaning if I create a macrocycle that optimizes first non-CAS orbitals, then CAS orbitals, and then check consistency with the previous step? I am using a (18e,23o) CAS in a molecule with ~60 electrons and ~150 orbitals. 

Up to this date, I had been using the mc.max_stepsize attribute. The other convergence parameters from both CASSCF and FCISolver, I don't really understand them, so I prefer to leave them as default.

PS: I tried to reach you by email, maybe you're not in Boulder anymore (it's the colorado.edu address). There's some additional info there about the molecule system and a pseudocode file with my previous methodology, which I used before your answer.

Best regards,
Pablo

**Comment by jamesETsmith** [comment]
Apologies for that @portega-usal, I've changed jobs and although I still have that email, I check it less regularly than I used to. I'll send you an email and we can continue this discussion that way. If you're satisfied that your original question is answered, you can close the issue.

**Comment by jamesETsmith** [comment]
If you're still hoping for further clarification, feel free to reopen.
