### ISSUE TITLE
Problems with the order of the localized orbitals.

### ISSUE THREAD

**Issue by DanielBajac** [pyscf/pyscf#752]
Hello. 
I'm having problems with the orbital's order of the Pipek-Mezey localization. The order of the orbitals are aprox. arbitrary. 
When I calculate two localizations with the same input, the order of the MOs are different. For example, in my .molden files the mo-4  and the mo-10 are different, but is the same in the mo 11. I need that the order of the MOs do not change. 
 How can I fix this change in the order of the MOs ?   (This is the .py program with which I calculate the localization.

[localiz_100.txt](https://github.com/pyscf/pyscf/files/5469742/localiz_100.txt)

**Comment by sunqm** [comment]
There is no way to preserve order in localization. You can find possible mapping
between the localized orbitals and MOs using function
pyscf.tools.mo_mapping.mo_1to1map

```
s = mo.T.dot(mol.intor('int1e_ovlp')).dot(local_orb)
mapping = np.array(pyscf.tools.mo_mapping.mo_1to1map(s))
local_orb[:,mapping[:,1]]
```
On Sat, Oct 31, 2020 at 01:05:15PM -0700, DanielBajac wrote:
> Hello. 
> I'm having problems with the orbital's order of the Pipek-Mezey localization. The order of the orbitals are aprox. arbitrary. 
> When I calculate two localizations with the same input, the order of the MOs are different. For example, in my .molden files the mo-4  and the mo-10 are different, but is the same in the mo 11. I need that the order of the MOs do not change. 
>  How can I fix this change in the order of the MOs ?   (This is the .py program with which I calculate the localization.
> 
> 
> [localiz_100.txt](https://github.com/pyscf/pyscf/files/5469742/localiz_100.txt)
> 
> 
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyscf/pyscf/issues/752

--

**Comment by DanielBajac** [comment]
Thanks a lot Mr. Sun.
Best regards
