### ISSUE TITLE
K-point HF method based on lattice sum example in pbc/41-pbc1d_real_space_sum.py

### ISSUE THREAD

**Issue by sharm608** [pyscf/pyscf#753]
Hi,

I am trying to do 1-d k-point HF calculations using the lattice sum approach based on the example pbc/41-pbc1d_real_space_sum.py. The kinetic matrices and the overlap matrices calculated from my 1d k point HF code match with the respective matrices produced from the normal pyscf KHF.py routine for different k points. However, the sum of the J and V_{ne} matrices do not match with KHF.py. 

I think the individual J and V_{ne} matrix will not match with the J and V_{ne} produced from the pyscf KHF.py because of the inclusion of the  G = 0 in pyscf KHF.py code but the sum of the two should converge to sum (J + V_{ne}) calculated from KHF.py. However, in my case, it is not matching.

Attached is the example of code that I am writing. In the code, I have used the density matrix calculated in KHF.py. 

Thank You
[example.txt](https://github.com/pyscf/pyscf/files/5470023/example.txt)

**Comment by sunqm** [comment]
ERI integrals are stored in chemist's convention, i.e. in eri[i,j,k,l] i and j
are bra and ket for one electron, k and l are bra and ket for another electron.
Your code does not have the right ordering of the four indices.

On Sat, Oct 31, 2020 at 05:32:11PM -0700, sharm608 wrote:
> Hi,
> 
> I am trying to do 1-d k-point HF calculations using the lattice sum approach based on the example pbc/41-pbc1d_real_space_sum.py. The kinetic matrices and the overlap matrices calculated from my 1d k point HF code match with the respective matrices produced from the normal pyscf KHF.py routine for different k points. However, the sum of the J and V_{ne} matrices do not match with KHF.py. 
> 
> I think the individual J and V_{ne} matrix will not match with the J and V_{ne} produced from the pyscf KHF.py because of the inclusion of the  G = 0 in pyscf KHF.py code but the sum of the two should converge to sum (J + V_{ne}) calculated from KHF.py. However, in my case, it is not matching.
> 
> Attached is the example of code that I am writing. In the code, I have used the density matrix calculated in KHF.py. 
> 
> Thank You
> [example.txt](https://github.com/pyscf/pyscf/files/5470023/example.txt)
> 
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyscf/pyscf/issues/753

--

**Comment by tberkel** [comment]
ERIs generally have 4 kpoints (one for each orbital) but one of them is
fixed by momentum conservation. So ERIs in PySCF are of dimension Nk^3
Nao^4.

**Comment by kirti215** [comment]
@tberkel thanks for the clarification but in that example it comes Nk^2Nao^4 and also can we get the Eri for eack k individually let say we have 10k in a Brilluoin zone can we get eri for them in G space from pyscf and then I think the dimension for each k should be Nao^4 for individual eri because I calculated the eri by gdf but on multiplying the eri with density matrix the coloumb matrix is coming correct but not the exchange matrix as I need to generate the fock using the eri can you please tell me if there is any way to do that.

Thanks in advance 

Kirti
