### ISSUE TITLE
Kernel restart

### ISSUE THREAD

**Issue by gaurabthapa** [pyscf/pyscf#755]
I am using Ubuntu subsystem in Windows to run PySCF module because it is not available for Windows. I downloaded qiskit module for my program, I am just running a qiskit program for VQE which is given in qiksit textbook "https://qiskit.org/textbook/ch-applications/vqe-molecules.html". However, every time I run the backend code, the kernel restarts. Any suggestions?

**Comment by gkc1000** [comment]
Without more detailed information, it's unclear that this is an issue of
pyscf, qiskit, or the ubuntu subsystem.

**Comment by verena-neufeld** [comment]
Hi @gaurabthapa , has this been resolved?
