### ISSUE TITLE
HF energy difference between old and new versions

### ISSUE THREAD

**Issue by y-yao** [pyscf/pyscf#761]
I reran a script for Cr2 in the cc-pvdz-dk basis with the x2c Hamiltonian using the latest version of pyscf and found that it gives slightly higher HF energies than we got with an older version of pyscf (more than one year ago). See data below for various geometries.
Any thoughts on what the reason could be would be appreciated.

New:
cr2-1.50.out:972:converged SCF energy = -2098.60241286689
cr2-1.55.out:844:converged SCF energy = -2098.59136668619
cr2-1.60.out:831:converged SCF energy = -2098.57365339832

Old:
cr2-1.50.out:1055:converged SCF energy = -2098.60243249516
cr2-1.55.out:1055:converged SCF energy = -2098.5913865761
cr2-1.60.out:999:converged SCF energy = -2098.57367352078

Here is the script:
```python
#!/usr/bin/env python
import os
import numpy
from pyscf import gto
from pyscf import scf

os.system("rm -rf /dev/shm/*")

ehf = []
emc = []

def run(b, dm):
    mol = gto.Mole()
    mol.verbose = 5
    mol.output = 'cr2-%3.2f.out' % b
    mol.atom = [
        ['Cr',(  0.000000,  0.000000, -b/2)],
        ['Cr',(  0.000000,  0.000000,  b/2)],
    ]
    mol.basis = 'ccpvdzdk'
    mol.symmetry = 1
    mol.build()
    mf = scf.sfx2c1e(scf.RHF(mol))
    mf.level_shift = .4
    mf.max_cycle = 100
    mf.conv_tol = 1e-9

    ehf.append(mf.scf(dm))  # do HF

    return mf.make_rdm1()

dm = None
for b in [1.50, 1.55, 1.60, 1.68, 1.80, 2.00, 2.25, 2.50, 2.75, 3.00, 3.25]:
    dm = run(b, dm)

```

**Comment by sunqm** [comment]
Hi Yuan,

I tested pyscf-1.6. It has the same results as the latest version. Pyscf-1.5
gives the one close to your old results. From 1.5 to 1.6, the treatment for
diffused functions in x2c is different.

Best,
Qiming

On Thu, Nov 12, 2020 at 07:53:09PM -0800, Yuan Yao wrote:
> I reran a script for Cr2 in the cc-pvdz-dk basis with the x2c Hamiltonian using the latest version of pyscf and found that it gives slightly higher HF energies than we got with an older version of pyscf (more than one year ago). See data below for various geometries.
> 
> New:
> cr2-1.50.out:972:converged SCF energy = -2098.60241286689
> cr2-1.55.out:844:converged SCF energy = -2098.59136668619
> cr2-1.60.out:831:converged SCF energy = -2098.57365339832
> 
> Old:
> cr2-1.50.out:1055:converged SCF energy = -2098.60243249516
> cr2-1.55.out:1055:converged SCF energy = -2098.5913865761
> cr2-1.60.out:999:converged SCF energy = -2098.57367352078
> 
> Here is the script:
> `#!/usr/bin/env python
> import os
> import numpy
> from pyscf import gto
> from pyscf import scf
> 
> os.system("rm -rf /dev/shm/*")
> 
> ehf = []
> emc = []
> 
> def run(b, dm):
>     mol = gto.Mole()
>     mol.verbose = 5
>     mol.output = 'cr2-%3.2f.out' % b
>     mol.atom = [
>         ['Cr',(  0.000000,  0.000000, -b/2)],
>         ['Cr',(  0.000000,  0.000000,  b/2)],
>     ]
>     mol.basis = 'ccpvdzdk'
>     mol.symmetry = 1
>     mol.build()
>     mf = scf.sfx2c1e(scf.RHF(mol))
>     mf.level_shift = .4
>     mf.max_cycle = 100
>     mf.conv_tol = 1e-9
> 
>     ehf.append(mf.scf(dm))  # do HF
> 
>     return mf.make_rdm1()
> 
> dm = None
> for b in [1.50, 1.55, 1.60, 1.68, 1.80, 2.00, 2.25, 2.50, 2.75, 3.00, 3.25]:
>     dm = run(b, dm)
> 
> `
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyscf/pyscf/issues/761

--

**Comment by y-yao** [comment]
Thanks Qiming!
Could you give more details on how things have changed with diffuse functions? Should I take it that the new energies are better than the old ones?

**Comment by sunqm** [comment]
when computing X matrix, basis are de-contracted and linear dependency may be found in these uncontracted basis functions. In old pyscf versions (< 1.6), some attempts are made to remove the linear dependency, including discarding smooth basis functions, or binding the most smooth basis to the less smooth basis. Although linear dependency is largely avoided with these attempts, it introduces uncertainty and reproducibility issue. In later versions, basis decontraction is carried out the regular way. All primitive GTOs are kept. Noticing that linear dependency is almost only associated to the matrix S in S^{-1/2}, a different strategy is used. The spirit of new strategy is basically to transform basis to the eigenvectors of S.  X matrix equations are solved with the new basis and finally x matrix is transformed back to regular AO basis. Linear dependency is removed when building the eigenvector basis of S.

In the code, these transformations are reformulated so as to remove some unnecessary forward and backward transformations.
