### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mganahl** [pyscf/pyscf#764]
Hi! just wanted to quickly ask where I can find the core code that runs the self consistency loop.
thanks!

**Comment by gkc1000** [comment]
Are you talking about HF, DFT, CC, MCSCF, etc etc ?

Assuming you are talking about self-consistency in Hartree-Fock for a
molecular system, then it is the function "kernel" in pyscf/scf/hf.py.
Generally "kernel" is the driver function within each module if there is
some such loop.

**Comment by tberkel** [comment]
For Hartree-Fock, the SCF loop is here (but of course many needed
quantities are computed elsewhere by functions called during SCF):
https://github.com/pyscf/pyscf/blob/master/pyscf/scf/hf.py#L49

**Comment by mganahl** [comment]
thanks for the quick reply. HF and DFT are sufficient. I found the HF cycle, but couldn't quite find the DFT one. Could you point me to this one as well? thanks!

**Comment by xubwa** [comment]
dft scf loops are identical with hf ones. The difference is dft objects use a different get_veff function.

**Comment by mganahl** [comment]
thanks, I jsut found it!
