### ISSUE TITLE
ao2mo for molecular orbitals

### ISSUE THREAD

**Issue by DanielBajac** [pyscf/pyscf#766]
Hello, I'm trying to calculate the next integral:  (ij|ab), where i,j,a,b are localized molecular orbitals(i,j: one different occupied orbitals in each and a,b: 3 different virtual orbitals in each). I've localized the orbitals with the _lo_ library, but I'm not sure about how to perform that integral. 

The ao2mo library is able to perform this integral? 

I think that a good possibility is with ao2mo.general(mol, [i,j,a,b], compact=False), but I have my doubts, because the ao2mo library is for "transform" ao to mo.

**Comment by tberkel** [comment]
Yes, `ao2mo` can do this.  See the examples in `examples/ao2mo`, for example
https://github.com/pyscf/pyscf/blob/master/examples/ao2mo/00-mo_integrals.py
https://github.com/pyscf/pyscf/blob/master/examples/ao2mo/10-diff_orbs_for_ijkl.py

**Comment by DanielBajac** [comment]
Hi Timothy, thank you for your answer. 

Ok, mi problem is that, when I fix i and j to be a single orbital, the next error arises: 
`    210     log = logger.new_logger(mol, verbose)
    211 
--> 212     nmoi = mo_coeffs[0].shape[1]
    213     nmoj = mo_coeffs[1].shape[1]
    214     nmok = mo_coeffs[2].shape[1]

IndexError: tuple index out of range`

mi code is (to make the idea clear)

`   ...: mol = gto.M(atom= ''' 
   ...:         H 
   ...: O   1 0.94820354 
   ...: O   2 1.3924894 1 102.35338342 
   ...: H   3 0.94820354 2 102.35338342 1 40.0 ''', basis = 'ccpvdz') 
   ...: mf = scf.RHF(mol).run()

mo_coeff = mf.mo_coeff
mol = mf.mol
i = mo_coeff[:,3]
j = mo_coeff[:,4]
a = mo_coeff[:,[10,11,12]] 
b = mo_coeff[:,[13,14,15]]

(ij,ab) = ao2mo.general(mol, [i,j,a,b], compact=False)
`
Where is my error? 
When I fixed i and j to contain two orbital (e.g i = mo_coeff[:,[3,4]] and j = mo_coeff[:,[5,6]] )  , this problem is fixed and the integral apears to be correct

**Comment by gkc1000** [comment]
replace i by [i], j by [j] etc.

**Comment by DanielBajac** [comment]
if I replace "i por [i], j por [j], etc." the error is: 
`AttributeError: 'list' object has no attribute 'dtype'`

if I fix the orbs like the example: https://github.com/pyscf/pyscf/blob /master/examples/ao2mo/10-diff_orbs_for_ijkl.py 

orb = (i, j, a, b) 

eri_mo = ao2mo.general(mol, orb, compact=False) 

the same error remains. 

However, if a fix i and j to contain two orbital in each one:

i = mo_coeff[:,[5,6]]
j = mo_coeff[:,[7,8]] 

the calculate of the integral appears to be alright and does not throw errors

**Comment by tberkel** [comment]
Try `np.array([i])` instead of [i].  The AttributeError is telling you that
you passed a `list` (namely `[i]`) but PySCF is expecting a numpy ndarray,
which you can tell because the AttributeError is looking for the `dtype`
attribute.  In general, if you want to use PySCF for custom calculations
and workflows, it will be useful to learn general principles of python for
scientific computing.

**Comment by DanielBajac** [comment]
`np.array([i])` didn't work either. 

But I find my error: the i and j must be defined like: 

```
i = mo_coeff[:,[5]]
j = mo_coeff[:,[6]] 
```

Thanks all of you for your contributions!
