### ISSUE TITLE
CCSD(T) for PBC systems.

### ISSUE THREAD

**Issue by Majokux** [pyscf/pyscf#776]
The energy of the (T) correction depends on the `exxdiv` treatment. There is an inconsistency in this regard between the fast and slow CCSD(T) code, see:

```
import numpy
from pyscf.pbc import gto, scf

cell = gto.M(
    a = 3.5667*numpy.asarray([
        [1.0, 1.0, 0.0],
        [0.0, 1.0, 1.0],
        [1.0, 0.0, 1.0],
        ])/2.0,
    atom = "C 0 0 0 ; C 0.25 0.25 0.25",
    basis = "gth-dzv",
    verbose = 0,
    precision = 1e-4,
    pseudo="gth-pade",
)

mf = scf.RHF(cell)
mf.kernel()

from pyscf.pbc import cc
mycc = cc.CCSD(mf)
mycc.kernel()
et = mycc.ccsd_t()
print("E(T) (fast) [htr] = %16.8g" % et)


from pyscf.cc import ccsd_t_slow
et_slow = ccsd_t_slow.kernel(mycc, mycc.ao2mo())
print("E(T) (slow) [htr] = %16.8g" % et_slow)
```

Which returns

```
E(T) (fast) [htr] =   -0.00054410117
E(T) (slow) [htr] =   -0.00080124578
```

If I understand correctly, `eris.fock` is generally the unmodified Fock matrix (not diagonal with exxdiv != None), whereas `eris.mo_energy` contains the shifted MO energies.
Is it indeed "better" to use the shifted MO energies for the perturbative treatment, in the sense that a faster convergence to the thermodynamic limit is observerd? In this case I would recommend changing line `mo_e = eris.fock.diagonal()` in `cc/ccsd_t_slow.py` to `eris.mo_energy`, to have consistent (T) corrections between the fast and slow code.

**Comment by sunqm** [comment]
cc.ccsd_t_slow was a legacy implementation comparing to the later pbc.ccsd_t code. The change you suggested does provide a more consistent treatment.
