### ISSUE TITLE
Examples about how to calculate wave function at given position

### ISSUE THREAD

**Issue by xlvector** [pyscf/pyscf#780]
Are there some examples about how to calculate psi (wave function) as given position (NElectron, 3)

**Comment by sunqm** [comment]
Examples of dumping to chgcar or cubgen format
https://github.com/pyscf/pyscf/blob/master/examples/tools/05-cubegen.py#L24
https://github.com/pyscf/pyscf/blob/master/examples/tools/06-chgcar.py#L21

You can trace to the code implementation if you need other format. The implementation is straightforward

**Comment by sunqm** [comment]
Values of orbitals at given postion can be evaluated
```
xyz = np.random.rand((100, 3))
np.einsum('pi,rp->ri', orbtial_coef, mol.eval_gto('GTOval', xyz))
```
There is no function to evaluate N-electron wavefunction

On Thu, Dec 10, 2020 at 04:30:58AM -0800, Xiang Liang wrote:
> Are there some examples about how to calculate psi (wave function) as given position (NElectron, 3)
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyscf/pyscf/issues/780

--
