### ISSUE TITLE
Bug for analytic gradient of rohf

### ISSUE THREAD

**Issue by zhangyingfeng1993** [pyscf/pyscf#786]
The results of the analytic gradient of ROHF are different from the numerical gradient：

analytic gradient：
converged SCF energy = -39.5193671077199
--------------- UHF gradients ---------------
         x                y                z
0 C     0.0018619970     0.0026332226     0.0045609505
1 H    -0.0099769471     0.0156624864    -0.0072499893
2 H    -0.0099773257    -0.0141097285     0.0099390113
3 H     0.0180922758    -0.0041859806    -0.0072499725
----------------------------------------------
numerical gradient：
 Cartesian Force (Hartrees/Bohr):
                   x               y               z
  C          -0.009958611    -0.014083909    -0.024395136
  H           0.012073121    -0.010780044     0.013492253
  H           0.012073476     0.017074103    -0.002589333
  H          -0.014187907     0.007789909     0.013492238

input  file:

from pyscf import gto, scf

mol = gto.M(
    atom = '''
 C              0.63540095    0.65803739   -0.00861418
 H              0.99205538   -0.35077261   -0.00861418
 H              0.99207379    1.16243558   -0.88226569
 H             -0.43459905    0.65805058   -0.00861418''',
    basis = 'def2-SVP',
    charge = 0,
    spin = 1
)

mf = scf.ROHF(mol)
mf.kernel()

from pyscf import grad
g = mf.Gradients()
g.kernel()

**Comment by sunqm** [comment]
Bug fixed
