### ISSUE TITLE
Strange changes in energy after natural orbit conversion in DMRG

### ISSUE THREAD

**Issue by jamcas** [pyscf/pyscf#789]
I want to do a DMRGCI from a converged DMRGSCF calculation(26o,24e),The results of DMRGSCF can be recovered well at the beginning, but the energy rises after being converted to natural orbits:

```
CASCI E = -2018.44685870163
...
FCI vector not available, call CASCI to update wavefunction
In Natural orbital, CASCI energy = -2018.4065691808948
```
I am worried that this may affact the subsequent calculation of NEVPT2.

**Comment by jamesETsmith** [comment]
@jamcas for approximate CI methods like DMRG the energy is _not_ invariant to the NO transformation so you will often see some change in energy afterward. That being said, if you use sufficiently large bond dimensions, i.e. the DMRG wave function is close to the exact CASCI wave function, this change in energy should be small (on the order of millihartrees or smaller in my experience). 

If you haven't already, I would check that your DMRGSCF energy is converged with respect to the bond dimension or at least close to converged.

**Comment by jamcas** [comment]
Thanks for your reply. So if I want to get a right NEVPT2 result, the sufficiently large bond dimensions should be used to get a accurate reference.  Should a sufficiently large M like DMRGCI be used for the subsequent three_pdm and NEVPT2 calculations?

**Comment by sunqm** [comment]
M for DMRGCI in some sense is only enough to converge two_pdm. A larger M is needed for three_pdm and all higher order pdms. I'll close this issue as it is silent for a while.
