### ISSUE TITLE
Saving UHF to Molden

### ISSUE THREAD

**Issue by ssnam92** [pyscf/pyscf#791]
Dear PySCF developers and users

I find out that problems can occur when one loads a UHF molden file generated with PySCF into Multiwfn.
For example, when I load a UHF wavefunction of CN molecule with Multiwfn:
```
Total/Alpha/Beta electrons:      7.0000      7.0000      0.0000
 Net charge:     6.00000      Expected multiplicity:    8
 Atoms:      2,  Basis functions:     60,  GTFs:    110
 This is unrestricted single-determinant wavefunction
 Orbitals from      1 to    60 are alpha, from     1 to     7 are occupied
 Orbitals from     61 to   120 are beta,  from    61 to    60 are occupied
```
giving strange multiplicity and occupation indices. (beta is missing)

The problem can be solved by removing `[MO]` on the Beta block of the molden file, or slightly change the source code `pyscf/tools/molden.py` 

```
    fout.write('[MO]\n')
```
into
```
    if spin == 'Alpha':
        fout.write('[MO]\n')
```
and I got the correct result
```
 Total/Alpha/Beta electrons:     13.0000      7.0000      6.0000
 Net charge:     0.00000      Expected multiplicity:    2
 Atoms:      2,  Basis functions:     60,  GTFs:    110
 This is unrestricted single-determinant wavefunction
 Orbitals from      1 to    60 are alpha, from     1 to     7 are occupied
 Orbitals from     61 to   120 are beta,  from    61 to    66 are occupied
```

I hope this might help someone.

**Comment by sunqm** [comment]
Thanks for the suggestion!

**Comment by johTin** [comment]
Hello [ssnam92](https://github.com/ssnam92) 
Can you please give some code use for generate molden file with UHF ?
How can you generate this infos 
Total/Alpha/Beta electrons:      7.0000      7.0000      0.0000
 Net charge:     6.00000      Expected multiplicity:    8
 Atoms:      2,  Basis functions:     60,  GTFs:    110
 This is unrestricted single-determinant wavefunction
 Orbitals from      1 to    60 are alpha, from     1 to     7 are occupied
 Orbitals from     61 to   120 are beta,  from    61 to    60 are occupied

Thanks for reply

**Comment by hebrewsnabla** [comment]
> Hello [ssnam92](https://github.com/ssnam92) Can you please give some code use for generate molden file with UHF ? How can you generate this infos Total/Alpha/Beta electrons: 7.0000 7.0000 0.0000 Net charge: 6.00000 Expected multiplicity: 8 Atoms: 2, Basis functions: 60, GTFs: 110 This is unrestricted single-determinant wavefunction Orbitals from 1 to 60 are alpha, from 1 to 7 are occupied Orbitals from 61 to 120 are beta, from 61 to 60 are occupied
> 
> Thanks for reply

This info is outputed by [Multiwfn](http://sobereva.com/multiwfn/) when loading molden files.
