### ISSUE TITLE
non-Hermitian eigenvalue problem in TDDFT with hybrid functional 

### ISSUE THREAD

**Issue by John-zzh** [pyscf/pyscf#796]
Hi, developers
 
I run into a problem when trying to access the (A+B) and (A-B) matrix-vector product function in RPA-TDDFT, I thought it should be something similar to the vind() function for A matrix in TDA-TDDFT. However, I cannot locate what I need. Then I tried to run a RPA-TDDFT calculation with a small methanol molecule, the I found PySCF actually use the Davidson algorithm to deal with the TDDFT, and it didn't converge even it hit the maximum subspace size. 

How PySCF implement the non-Hermitian eigenvalue problem (A-B)(A+B)|X+Y> = w^2|X-Y> ?

Thanks for help!

I attached the methanol case here:

**input:**
from pyscf import gto, scf, dft, tddft 
mol = gto.Mole() 
mol.build(atom = '\
C         -4.89126        3.29770        0.00029;\
O         -3.49307        3.28429       -0.00328;\
H         -5.28213        2.58374        0.75736;\
H         -5.28213        3.05494       -1.01161;\
H         -5.23998        4.31540        0.27138;\
H         -3.22959        2.35981       -0.24953', 
basis = 'def2-svp', symmetry = True) 
mol.verbose = 5
mf = dft.RKS(mol) 
mf.xc = 'pbe0'
mf.kernel() 
mytd = tddft.TDDFT(mf) 
mytd.kernel() 
mytd.analyze()

**output:**
..........
******** <class 'pyscf.tdscf.rks.TDDFT'> for <class 'pyscf.dft.rks.RKS'> ********
nstates = 3 singlet
wfnsym = None
conv_tol = 1e-09
eigh lindep = 1e-12
eigh level_shift = 0
eigh max_space = 50
eigh max_cycle = 100
chkfile = /var/folders/yv/2d0zlq3j1dq04l1tjz4qgg800000gn/T/tmpeyfwqvc2
max_memory 4000 MB (current use 0 MB)
..........
davidson 47 52  |r|= 0.0312  e= [0.26699315 0.32782097 0.33682026]  max|de|= 0.0316  lindep= 0.811
Old state -> New state
    2     ->     0 
    0     ->     1 
    1     ->     2 
root 2 converged  |r|= 1.32e-07  e= 0.3278209747804296  max|de|= -9.66e-11
davidson 48 53  |r|= 1.01  e= [0.06918574 0.26699315 0.32782097]  max|de|= -0.268  lindep= 0.838
Old state -> New state
    1     ->     0 
    2     ->     1 
    0     ->     2 
davidson 49 54  |r|= 0.0179  e= [0.26699315 0.32782097 0.33630222]  max|de|= 0.267  lindep= 0.822
    CPU time for TDDFT     19.87 sec, wall time      9.72 sec
Excited State energies (eV)
[7.26525375 8.92046309 9.15124956]

** Singlet excitation energies and oscillator strengths **
irreps of each MO [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0]
Excited State   1:    A      7.26525 eV    170.65 nm  f=0.0020
       9 -> 10        0.69777
       9 -> 11       -0.10518
..........

**Comment by tberkel** [comment]
I'm not sure why your calculation didn't converge, but just to answer a few
questions:
- The non-TDA code in PySCF works by finding eigenvalues of the
[[A,B],[-B,-A]] matrix (and not by reformulation with (A+B)(A-B) etc.).
- The matrix-vector vind() function for the above matrix is here:
https://github.com/pyscf/pyscf/blob/master/pyscf/tdscf/rhf.py#L886
- With this matrix-vector function, PySCF find eigenvalues with a
non-symmetric Davidson algorithm as can be seen in the call here:
https://github.com/pyscf/pyscf/blob/master/pyscf/tdscf/rhf.py#L978

**Comment by John-zzh** [comment]
Cool, thank you for such a quick reply!!
Now I know PySCF takes the [[A,B],[-B,-A]] as the whole matrix to solve the eigenvalue.
Is there any paper that the **davidson_nosym1** function coded from? or it is an unpublished mathmagic? I'm still learning all those things :)

**Comment by tberkel** [comment]
There may be some implementation tweaks in PySCF but the standard reference
for non-symmetric Davidson is this one:
https://www.sciencedirect.com/science/article/pii/002199918290119X

**Comment by John-zzh** [comment]
Thx! 
So, just double-check, we feed the vind() function with paired [X, Y] vectors, and it throws out [AX, BY]? (or [AX, -AY] as noted in the [https://github.com/pyscf/pyscf/blob/master/pyscf/tdscf/rhf.py#L886]?) I want AX and BY...

**Comment by tberkel** [comment]
It should take (X,Y) and return (AX+BY, -BX-AY).  If you want AX and BY
separately, it might be easiest to just use the get_ab() function and then
contract with X and Y on your own (as long as memory and cost are not major
bottlenecks for you).

**Comment by John-zzh** [comment]
Thanks for the above help!
I'm back again :)
So, to get the alpha tensor in the static polarizability problem
[[A B]  [X] = [P]
[B A]]  [Y]    [Q]
Where actually P = Q, then this equation falls back to (A+B)X=P, how to approach the function that takes X vectors as input and returns (A+B)X?  If I use get_ab()  to compute AX and BX separately then it seems wasteful.
I tried
**from pyscf.prop.polarizability.rhf import Polarizability**
**mf = dft.RKS(mol)**
 **spolar_vind = Polarizability(mf).gen_vind(mf, mo_coeff, mo_occ)** but seems not the one I want..

**Comment by tberkel** [comment]
Admittedly I don't exactly understand what your goal is, but based on what
you're requesting, a hacky way to compute (A+B)X would be pass (X,X) as the
argument to get_vind(), and only use the first "excitation" component of
the output vector.  In other words, if you pass (X,X), then the output
vector will be [(A+B)X, -(A+B)X]

**Comment by sunqm** [comment]
No api available to impose this symmetry. A dirty patch for polarizability
module should be working:
```
class Polarizability(pyscf.prop.polarizability.rhf.Polarizability):
    def gen_vind(self, mf, mo_coeff, mo_occ):
        get_vind = super().gen_vind(mf, mo_coeff, mo_occ)
        def get_vind_with_symmetry(mo1):
            v = get_vind(np.append(mo1, mo1))
            return v[:v.size//2]
        return get_vind_with_symmetry
```

On Sun, Feb 28, 2021 at 05:44:58PM -0800, John-zzh wrote:
> Thanks for the above help!
> I'm back again :)
> So, to get the alpha tensor in the static polarizability problem
> [[A B]  [X] = [P]
> [B A]]  [Y]    [Q]
> Where actually P = Q, then this equation falls back to (A+B)X=P, how to approach the function that takes X vectors as input and returns (A+B)X?  If I use get_ab()  to compute AX and BX separately then it seems wasteful.
> I tried
> **from pyscf.prop.polarizability.rhf import Polarizability**
> **mf = dft.RKS(mol)**
>  **spolar_vind = Polarizability(mf).gen_vind(mf, mo_coeff, mo_occ)** but seems not the one I want..
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyscf/pyscf/issues/796#issuecomment-787578813

--

**Comment by John-zzh** [comment]
Thanks to all PySCF developers and their generous help! 
We borrowed the matrix-vector functions (two-electron integral) to test our idea of semi-empirical preconditioning in the TDDFT eigenvalue problem. PySCF is a great platform to work with!
https://aip.scitation.org/doi/10.1063/5.0071013

**Comment by John-zzh** [comment]
Hi PySCFers, 
Another quick question: how to get the coulomb & exchange operator in TDDFT? I mean the function that returns (ia|jb)x and (ij|ab)x, where x is a vector. 
I know TDA_vind, hdiag = td.gen_vind(mf), where TDA_vind returns Ax. 
Thanks!

**Comment by sunqm** [comment]
A*x returns the summation of the two terms, as the implementation here https://github.com/pyscf/pyscf/blob/master/pyscf/tdscf/rhf.py#L137 .
