### ISSUE TITLE
Printfinal  energy after optimizing a geometry

### ISSUE THREAD

**Issue by Jean-Michel-M** [pyscf/pyscf#798]
Hi,

I perform a very simple calculation:
    mf = scf.RHF(mol)
    mc = mcscf.CASSCF(mf, 2, 2)
    mol_eq = optimize(mc, **conv_params,constraints='cons.txt')
the pyscf doc explains how to get the new geometry (print(mol_eq.atom._coords()) but it does not explain how to get the final energy. Does this mean that there is no other way than running a new mcscf calculation in the example above?

Thanks in advance.
Jean-Michel

**Comment by jamesETsmith** [comment]
@Jean-Michel-M, there are a couple of options to access the energy without having to rerun a CASSCF calculation at the final geometry. Strategy (1) and (2) dump the energy data to a text file (either the PySCF log or the geomeTRIC log _and_ xyz file). Strategy (3) keeps a running list of the energies at each geometry iteration and can be easily used later in the script.

```python
from pyscf import gto, scf, mcscf
from pyscf.geomopt.geometric_solver import optimize


# Strategy 1) Set verbose > 3 to see energies printed in log
mol = gto.M(atom="C 0 0 0; C 0 0 1", basis="ccpvdz", verbose=3, output="test.log")
mf = scf.RHF(mol).run()
mc = mcscf.CASSCF(mf, 8, 8).run()

# Strategy 2) Set the prefix to save data from geomeTRIC to its own file
opt_params = {
  "prefix": "_geom_data",
}

# Strategy 3) Create a callback to run every iteration and save energies
mcscf_energies = []
def cb(envs):
  mc = envs["g_scanner"].base
  mcscf_energies.append(mc.e_tot)

mol_eq = optimize(mc, opt_params, callback=cb)

print(mcscf_energies)
```

**Comment by Jean-Michel-M** [comment]
Hi,
Thank you for your quick answer nevertheless, I have still a question. 

When strategy 3 is followed, no mcscf.CASSCF card appears and I do not understand where the active space  is defined and and how to specify which which SCF calculation is used as initial guess of the MCSCF calculation.
Yours,
Jean-Michel

**Comment by jamesETsmith** [comment]
@Jean-Michel-M, the strategies are not mutually exclusive and the `mc` object we defined with `mc = mcscf.CASSCF(mf, 8, 8)` is still the one we use in strategy (3) so you still have the usual control over the SCF initial guess and the active space you choose. In strategy (3).
