### ISSUE TITLE
Some problematic results calculated from level-shift DFT

### ISSUE THREAD

**Issue by hoshishin** [pyscf/pyscf#799]
Hi PySCF devs, I used blyp functional to calculate a Cr atom (2S+1 = 7), with level_shift = 0.5, and I found that alpha electrons sit on 3d24s14p3, which is indicated by mo_occ, BUT the occupied d orbitals and virtual d orbitals have the same energy. I set the verbose = 6, the last cycle of SCF indicates that the alpha electrons sit on 3d54s1.

I'm confused about the results.

Thanks a lot!

**Comment by gkc1000** [comment]
Please post output. I am not sure, but my guess is level shift is being
applied to some initial guess classification of occ/virtuals.

**Comment by hoshishin** [comment]
Thank you, gkc! 

I used blyp functional to calculate a Cr atom (2S+1 = 7):
`
molu = gto.Mole()
molu.verbose = 6
molu.atom = 'Cr 0 0 0'
molu.spin=6
molu.basis = '6-31g'
molu.symmetry=False
molu.build()
mf = dft.UKS(molu)
mf.xc = 'blyp'
mf.level_shift=0.5
mf.kernel()
`

There should be 15 alpha electrons and 9 beta electrons.

Final alpha MO energy is 
![图片](https://user-images.githubusercontent.com/37256920/105432747-368b9f80-5c93-11eb-9f59-b141f76f55fd.png)
That's mean the 3d orbitals have 2 electrons, without breaking the symmetry, which I was confused about.

And the cycle before final step shows 3d orbitals are full occupied:
![图片](https://user-images.githubusercontent.com/37256920/105432756-3d1a1700-5c93-11eb-95f0-16ca7de897e1.png)


I'm puzzled about that.

Thanks a lot !

**Comment by zhcui** [comment]
The system has degenerate HOMO and LUMO, and therefore, the occupation number can be different among iterations.
You may try `mf = scf.addons.frac_occ_(mf)` to allow fractional occupation of degenrate d bands.

**Comment by sunqm** [comment]
If you can update your pyscf code to the latest commits on master branch, you
can enable symmetry, and set explicitly the occupancies for each orbital
following the example
https://github.com/pyscf/pyscf/blob/master/examples/scf/31-v_atom_rohf.py

On Thu, Jan 21, 2021 at 05:27:39PM -0800, hoshishin wrote:
> Thank you, gkc! 
> 
> I used blyp functional to calculate a Cr atom (2S+1 = 7):
> `
> molu = gto.Mole()
> molu.verbose = 6
> molu.atom = 'Cr 0 0 0'
> molu.spin=6
> molu.basis = '6-31g'
> molu.symmetry=False
> molu.build()
> mf = dft.UKS(molu)
> mf.xc = 'blyp'
> mf.level_shift=0.5
> mf.kernel()
> `
> 
> There should be 15 alpha electrons and 9 beta electrons.
> 
> Final alpha MO energy is 
> ![图片](https://user-images.githubusercontent.com/37256920/105432747-368b9f80-5c93-11eb-9f59-b141f76f55fd.png)
> That's mean the 3d orbitals have 2 electrons, without breaking the symmetry, which I was confused about.
> 
> And the cycle before final step shows 3d orbitals are full occupied:
> ![图片](https://user-images.githubusercontent.com/37256920/105432756-3d1a1700-5c93-11eb-95f0-16ca7de897e1.png)
> 
> 
> I'm puzzled about that.
> 
> Thanks a lot !
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyscf/pyscf/issues/799#issuecomment-765051595

--

**Comment by sunqm** [comment]
No matter whether level shift is added, scf will execute an extra step without any level shift to compute Fock matrix and molecular orbitals using the density matrix obtained in last step. The occupancy pattern is affected in this step. The recommended input is
```
from pyscf import gto, dft
molu = gto.Mole()
molu.verbose = 6
molu.atom = 'Cr 0 0 0'
molu.spin=6
molu.basis = '6-31g'
molu.symmetry=True
molu.build()
mf = dft.UKS(molu)
mf.xc = 'blyp'
mf.level_shift = 0.5
mf.irrep_nelec = {'s': (4,3), 'p':(6,6), 'd':(5,0)}
mf.kernel()
```
