### ISSUE TITLE
densities for DHF and GHF objects

### ISSUE THREAD

**Issue by AStegm** [pyscf/pyscf#801]
Currently no rdm for DHF and GHF objects is implemented and the program crashes.

I would prefer if either an error message was printed telling the user that it has not yet been implemented, or (much better) it was implemented.

**Comment by AStegm** [comment]
Sorry, it seems the issue is with pyscf.dft.numint.eval_rho, which crashes. It there a way to make it handle DHF or GHF density matrices?

**Comment by AStegm** [comment]
A possible solution for GHF objects might be something like this:

dm = np.asarray(dm)
nso = dm.shape[-1]
nao = nso // 2
dm_a = dm[...,:nao,:nao].real
dm_b = dm[...,nao:,nao:].real
dm = dm_a+dm_b

in the numint.eval_rho function.

**Comment by gkc1000** [comment]
The density in the GHF case is a spinor. So while that is creating a kind
of density it is not the actual 1-particle density, so this is not
the right code to put into pyscf itself, although if for your purposes this
is what you want, you should use it.

As should be clear, PySCF does not currently support GKS, DKS. This is
because the exchange-correlation functional gradient term is more
complicated for spinors and has not been implemented.

**Comment by AStegm** [comment]
Thank you for your answer.

Yes, that is true, that is only a very rough approximation for the one particle density matrix. It is actually used in `pyscf.dft.gks.get_veff`.

True, GKS and DKS is not supported at the moment. However, expected behaviour should be that density output should be supported for all methods (that includes DHF and GHF). Currently the go-to method for that is `numint.eval_rho(mol, ao, dm)` which is also what is used to generate density cube files.

So shouldn't there be a warning when `eval_rho` is called with a GHF or DHF density instead of a crash? Or should `eval_rho` be extended to allow plotting of these arguably valid densities?

**Comment by AStegm** [comment]
For DHF objects, a density can be used via:

dm = hf.make_rdm1(ao_repr=True)
n = dm.shape[1]	
dm_a = dm[0:n//2:2,0:n//2:2].real
dm_b = dm[1:n//2:2,1:n//2:2].real
dm = np.array([dm_a,dm_b])

Is this correct?

There is another issue, however:
Some densities are not normalized. I performed manual integration on single atoms and found densities that were not normalized to the total number of electrons for some atoms (for example Z=5). The issue persisted for UHF-X2C and DHF densities. If required, I'll post and example skript.

**Comment by sunqm** [comment]
Here is an example for the density of GKS and DKS at 
https://github.com/pyscf/pyscf/blob/master/examples/dft/31-xc_value_on_grid.py
