### ISSUE TITLE
O2 molecule electronic states (CASSCF/CASCI/other FCI solvers)

### ISSUE THREAD

**Issue by portega-usal** [pyscf/pyscf#803]
Greetings,

First of all, this may be a very naïve question and maybe I am missing out something in the documentation.

I am trying to obtain multistate potential energy curves with multireference methods, such as CASSCF, CASCI or SHCI, but I always have a problem involving state degeneracy.

For example, with this input I should obtain a double-degenerate delta singlet state for the oxygen molecule:

```
from pyscf import gto, scf, mcscf
mol = gto.M(atom="O 0 0 0; O 0 0 1.2", basis="ccpvdz")
mf = scf.RHF(mol).run()
ncas = 8
nelec_cas = 12
mc = mcscf.CASSCF(mf, ncas, nelec_cas)
mc.kernel()
mci = mcscf.CASCI(mf, ncas, nelec_cas)
mci.mo_coeff = mc.mo_coeff
mci.fcisolver.nroots = 2
mci.kernel()
```

These degenerate states have an energy of -149.71369601 Ha. The problem is that the program is jumping to the next state, at -149.67773309. How could I obtain multistate energies, taking into account degeneracy?

This calculation would not be the real problem, because we know that state is degenerate. But if I want to calculate the reaction path energy for those 2-fold states as they approach an ethylene molecule, they would be split-up and should be explicitely considered.

Thanks in advance!
Pablo Ortega

PS Update: I tried the same calculation, but using DMRGCI as fcisolver, and it did work. I would like to have a way to obtain the same result with CASCI anyway.

PS Update 2: I also used SHCI as fcisolver but it didn't work either.

**Comment by sunqm** [comment]
State-average casscf might be the right choice in this case. There are a few examples in examples/mcscf, like 15, 41

On Thu, Jan 21, 2021 at 10:13:12AM -0800, portega-usal wrote:
> Greetings,
> 
> First of all, this may be a very naïve question and maybe I am missing out something in the documentation.
> 
> I am trying to obtain multistate potential energy curves with multireference methods, such as CASSCF, CASCI or SHCI, but I always have a problem involving state degeneracy.
> 
> For example, with this input I should obtain a double-degenerate delta singlet state for the oxygen molecule:
> 
> ```
> from pyscf import gto, scf, mcscf
> mol = gto.M(atom="O 0 0 0; O 0 0 1.2", basis="ccpvdz")
> mf = scf.RHF(mol).run()
> ncas = 8
> nelec_cas = 12
> mc = mcscf.CASSCF(mf, ncas, nelec_cas)
> mc.kernel()
> mci = mcscf.CASCI(mf, ncas, nelec_cas)
> mci.mo_coeff = mc.mo_coeff
> mci.fcisolver.nroots = 2
> mci.kernel()
> ```
> 
> These degenerate states have an energy of -149.71369601 Ha. The problem is that the program is jumping to the next state, at -149.67773309. How could I obtain multistate energies, taking into account degeneracy?
> 
> This calculation would not be the real problem, because we know that state is degenerate. But if I want to calculate the reaction path energy for those 2-fold states as they approach an ethylene molecule, they would be split-up and should be explicitely considered.
> 
> Thanks in advance!
> Pablo Ortega
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyscf/pyscf/issues/803

--

**Comment by portega-usal** [comment]
I think I have found the solution. My mistake was that I did not know that fcisolver mixes spin states if spin attribute for gto.mol is set to 0 (singlet). Then, the state with -149.7136901 Ha is the ground state triplet and if I ask for 4 states, the singlet delta and singlet sigma are correct. 

Moreover, I did many tests, and I found that CASSCF and CASCI work always well, DMRG too, but SHCI has more convergence problems related to multistate. It is quite probable that I am not correctly setting some parameters, I will edit this with more info. I could also add some more examples to that examples/mcscf folder if it suits you, so maybe some people will find it useful in the future.

**Comment by portega-usal** [comment]
UPDATE:

I was trying to achieve agreement between conventional CASSCF/CASCI and other methods and I got pretty confused. Now that O2 molecule is solved, I bring another simple example, N+ cation. This atom has a triplet 3-fold degenerate ground state. So I try to reproduce these degenerate states, and I get this:

`mol = gto.M(atom="""
N 0.0 0.0 0.0  """,
basis="ccpvdz",
charge=1,
spin=0)
mf = scf.UHF(mol).run()
ncas = 14
nelec_cas = 6

###  Conventional CASSCF
mc = mcscf.CASSCF(mf, ncas, nelec_cas).state_average_(numpy.ones(3)/3)
mc.kernel()[0]
mci = mcscf.CASCI(mf, ncas, nelec_cas)
mci.fcisolver.nroots = 3
mci.kernel()[0]

### SHCI
mc = mcscf.CASSCF(mf, ncas, nelec_cas).state_average_(numpy.ones(3)/3)
mc.kernel()[0]
mci = mcscf.CASCI(mf, ncas, nelec_cas)
mci.mo_coeff = mc.mo_coeff
mci.fcisolver = dice.SHCI(mol2)
mci.fcisolver.mpiprefix = ' '
mci.fcisolver.nroots = 3
mci.fcisolver.sweep_iter = [ 0 , 2 , 4 ]
mci.fcisolver.sweep_epsilon = [ 1e-6 , 5e-7 , 1e-7 ]
mci.kernel()[0]

### DMRGCI

mol = gto.M(atom="""
N 0.0 0.0 0.0  """,
basis="ccpvdz",
charge=1,
spin=2)
mf = scf.UHF(mol).run()
ncas = 5
nelec_cas = 6
mc = mcscf.CASSCF(mf, ncas, nelec_cas).state_average_(numpy.ones(3)/3)
mc.kernel()[0]
mci = mcscf.CASCI(mf, ncas, nelec_cas)
mci.mo_coeff = mc.mo_coeff
mci.fcisolver = dmrgscf.DMRGCI(mol)
mci.fcisolver.nroots = 3
mci.kernel()[0]`

CASSCF/CASCI calculation yields a triplet 3-fold degenerate state at -53.95854168, so it does DMRGCI. But the problem comes for SHCI, which yields:

`
CASCI state 0  E = -53.9585416821417  E(CI) = -53.9585416821417  S^2 = 2.0000000
CASCI state 1  E = -52.9364286251108  E(CI) = -52.9364286251108  S^2 = 2.0000000
CASCI state 2  E = -52.9336658978863  E(CI) = -52.9336658978863  S^2 = 2.0000000
`

I am sure that these problems are very simple and probably I am wrong with something, but I can't figure it out.

Thanks in advance!

**Comment by jamesETsmith** [comment]
@portega-usal, sorry for the wait time on this issue. Are you still having trouble with this? If you are, can you share the Dice output from your SHCI calculation?

**Comment by portega-usal** [comment]
Yes, I think it was not solved yet, I attach the Dice output for the above SHCI calculation (mci.kernel()[0], in the SHCI section, so orbitals are already optimized). 

`
**************************************************************
Dice  Copyright (C) 2017  Sandeep Sharma
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.


Author:       Sandeep Sharma
Contributors: James E Smith, Adam A Holmes, Bastien Mussard
For detailed documentation on Dice please visit
https://sanshar.github.io/Dice/
Please visit our group page for up to date information on other projects
http://www.colorado.edu/lab/sharmagroup/
**************************************************************


**************************************************************
Input file  :
**************************************************************
#system
nocc 6
0 2 4 6 1 3 
orbitals ./FCIDUMP
nroots 3
#variational
schedule
0	1e-06
2	5e-07
4	1e-07
end
davidsonTol 5e-05
dE 1e-08
maxiter 10
#pt
nPTiter 0
epsilon2 1e-07
epsilon2Large 1000
targetError 0.0001
sampleN 200
#misc
noio
prefix /scratch/portega/pyscf/61375
DoRDM




**************************************************************
VARIATIONAL STEP  
**************************************************************
Iter Root       Eps1   #Var. Det.               Energy   #Davidson     Time(s)
   0    0    1.00e-06         260       -53.9571037931         22        0.01
   0    1    1.00e-06         260       -52.9014862069         22        0.01
   0    2    1.00e-06         260       -52.5812045995         22        0.01

   1    0    1.00e-06        6623       -53.9585409341         51        0.22
   1    1    1.00e-06        6623       -52.9363655218         51        0.22
   1    2    1.00e-06        6623       -52.9336499954         51        0.22

   2    0    5.00e-07       19627       -53.9585416821         13        0.73
   2    1    5.00e-07       19627       -52.9364286248         13        0.73
   2    2    5.00e-07       19627       -52.9336658966         13        0.73

   3    0    5.00e-07       20976       -53.9585416821          5        0.93
   3    1    5.00e-07       20976       -52.9364286252          5        0.93
   3    2    5.00e-07       20976       -52.9336658976          5        0.93


Performing final tight davidson with tol: 5e-05

Exiting variational iterations
Calculating RDM
-69.928169530676  15.969627848537
E from 2RDM: -53.958541682139
-67.9577259973789  15.0212973722253
E from 2RDM: -52.9364286251536
-68.9158794286828  15.9822135311057
E from 2RDM: -52.9336658975771
VARIATIONAL CALCULATION RESULT
------------------------------
Root             Energy     Time(s)
   0      -53.9585416821        1.97
   1      -52.9364286252        1.97
   2      -52.9336658976        1.97


Printing most important determinants
 Det     weight  Determinant string
State :0
   0     9.80198613e-01  2 2 a a 0   0 0 0 0 0   0 0 0 0 
   1    -1.24493078e-01  2 0 a a 2   0 0 0 0 0   0 0 0 0 
   2    -3.35152759e-02  2 0 a a b   0 0 a 0 0   0 0 0 0 
   3     3.14749156e-02  2 0 a a a   0 0 b 0 0   0 0 0 0 
   4     3.11695454e-02  2 a a a 0   0 0 0 0 b   0 0 0 0 
   5     3.07925073e-02  2 2 0 0 0   a a 0 0 0   0 0 0 0 
State :1
   0     6.83540971e-01  2 2 a 0 0   0 a 0 0 0   0 0 0 0 
   1    -6.83538158e-01  2 2 0 a 0   a 0 0 0 0   0 0 0 0 
   2    -8.87948852e-02  2 0 a 0 2   0 a 0 0 0   0 0 0 0 
   3     8.87943453e-02  2 0 0 a 2   a 0 0 0 0   0 0 0 0 
   4     8.81575380e-02  2 a 2 0 0   0 0 0 a 0   0 0 0 0 
   5    -8.81570344e-02  2 a 0 2 0   0 0 0 a 0   0 0 0 0 
State :2
   0    -9.39786059e-01  2 0 a a 2   0 0 0 0 0   0 0 0 0 
   1    -1.43256918e-01  2 0 a a b   0 0 a 0 0   0 0 0 0 
   2    -1.27024173e-01  2 2 a a 0   0 0 0 0 0   0 0 0 0 
   3     1.24154830e-01  2 0 a a a   0 0 b 0 0   0 0 0 0 
   4    -8.48857834e-02  2 a a a 0   0 0 0 b 0   0 0 0 0 
   5    -7.88523417e-02  2 2 0 a 0   0 a 0 0 0   0 0 0 0 
We cannot perform PT RDM with stochastic PT. Disabling RDM.

**************************************************************
PERTURBATION THEORY STEP  
**************************************************************
`

**Comment by jamesETsmith** [comment]
@portega-usal hmm I wonder if you're running into trouble because you're stuck in a particular symmetry sector. You could try specifying several determinants (one from each of the symmetry sector) by setting the `initialStates` attribute of your SHCI object. `initialStates` is a 2D list that should look something like the following (@xubwa correct me if I'm wrong):

```python
initialStates = [[0 2 4 6 1 3], [0 2 4 8 1 3], [0 2 4 10 1 3]]
```

Which will produce a Dice input with the following initial determinants:

```
...
nocc 
0 2 4 6 1 3
0 2 4 8 1 3
0 2 4 10 1 3
...
```

You'll want to have a look at the symmetry of the orbitals and excited states because in the example above I picked the determinant occupations randomly.

**Comment by portega-usal** [comment]
Ok, thanks for your answer, I will check it out today and I will post a reply with the final results.

Then, as far as I see, there is no way to automatically select the optimal states, right? I usually work with larger molecules with no symmetry, and this cherry-picking can become cumbersome. I will try to come up with other ideas anyway.

Best regards,
Pablo Ortega

**Comment by jamesETsmith** [comment]
@portega-usal, if they are all different symmetry groups you could also run three different SHCI calculations where each targets the lowest energy state in the specified symmetry groups. If you're working with larger systems without symmetry, this problem may not exist at all and you can run SHCI using and just specify the number of states you'd like. Symmetry tends to complicate the situation for small atoms and molecules and without it, these calculations might get easier.

**Comment by portega-usal** [comment]
I have used the initialStates keyword, and it totally fixed it, I obtained the three lower states I wanted. I guess that the difference between conventional or DMRG and SHCI solver is that the latter imposes a default configuration, if no determinant list is given. 

One last detail and we can close this thread. Is it possible to calculate a SHCISCF for many states with this?:

'''
mc = mcscf.CASSCF(mf, ncas, nelec_cas).state_average_(numpy.ones(3)/3)
mc.fcisolver = dice.SHCI(mol)
mc.fcisolver.mpiprefix = ' '
mc.fcisolver.nroots = 3
mc.fcisolver.sweep_iter = [ 0 , 2 , 4 ]
mc.fcisolver.sweep_epsilon = [ 1e-4 , 5e-5 , 1e-5 ]
mc.kernel()[0]
'''

I don't know if it is implemented for SHCI, it yields:

'''
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/programs/pyscf/pyscf/mcscf/mc1step.py", line 790, in kernel
    ci0=ci0, callback=callback, verbose=self.verbose)
  File "/home/programs/pyscf/pyscf/mcscf/mc1step.py", line 349, in kernel
    e_tot, e_cas, fcivec = casscf.casci(mo, ci0, eris, log, locals())
  File "/home/programs/pyscf/pyscf/mcscf/mc1step.py", line 812, in casci
    raise RuntimeError('Multiple roots are detected in fcisolver.  '
RuntimeError: Multiple roots are detected in fcisolver.  CASSCF does not know which state to optimize.
See also  mcscf.state_average  or  mcscf.state_specific  for excited states.
'''

Maybe it is not even necessary to use a state-averaged orbital optimization and we can only optimize orbitals for the ground state and then use CASCI/SHCI to calculate energy for 3-fold degenerate (these energies will be the same, but I need them all because they will split along a reaction path)

**Comment by jamesETsmith** [comment]
@portega-usal, it's definitely possible, you'll want to use `state_average_mix_`

https://github.com/pyscf/pyscf/blob/09eca1f689da405128c82026e9e76b29e944d187/pyscf/shciscf/examples/03_c2_diffsymm.py#L42-L56

**Comment by portega-usal** [comment]
Great, I finally got the degenerate states I needed. We can close this thread now. 

Thanks a lot (again) for your valuable help!

**Comment by jamesETsmith** [comment]
Happy to help!
