### ISSUE TITLE
SA-CASSCF calculation without mf input

### ISSUE THREAD

**Issue by MilaimKas** [pyscf/pyscf#805]
I am trying to calculate a SA-CASSCF potential energy curve for small diatomic open-shell systems. The CASSCF class needs the HF object as input. However for some geometries, the HF calculation may not converge (specially when looking at dissociation curves).   
My question is the following: is it possible to calculate a SA-CASSCF curve from an initial HF calculation (say at the minimum) without having to perform a HF calculation at each point ? 

Example:  doublet Pi states of OH  

```
mol.atom="""
O  0 0 0
H 0 0 0.9
"""
mol.nelectron = 9 
mol.charge=0 # charge
mol.spin=1 # spin
mol.build() # build mol object
mf=scf.ROHF(mol)
mf.kernel()    

weights = np.ones(2)/2
solver = fci.direct_spin1.FCI(mol)
solver.nroots = 2
solver.spin = 1
solver = fci.addons.fix_spin(solver, shift=.2, ss=1)  
mc = mcscf.CASSCF(mf, 6, 7)
mcscf.state_average_mix_(mc, [solver], weights)   
mo = mc.mo_coeff

for R in [0.9,2,5,8,10]:

    mol.atom="""
    O  0 0 0
    H 0 0 {}
    """.format(R)
    mol.build()

    solver = fci.direct_spin1.FCI(mol)
    solver.nroots = 2
    solver.spin = 1
    solver = fci.addons.fix_spin(solver, shift=.2, ss=1)
    mc = mcscf.CASSCF(mf, 6, 7)
    mcscf.state_average_mix_(mc, [solver], weights)
    mo = mcscf.project_init_guess(mc, mo)
    mc.kernel(mo)  
    mo = mc.mo_coeff
```

In this example, a initial HF calculation is performed at the minimum of the potential well, the initial guess being provided with no frozen orbital, no input from a HF calculation should be needed in the loop. 
Alternatively, would it be possible to use a mf object from a closed shell ion (instead of the neutral) as input for CASSCF ?

Also, as additional question: is it possible to perform a SA-CASCF calculation by including states with different number of electrons into the SA procedure ? (in my experience, this sometimes help the converges when dealing with anions). 
 `

**Comment by jamesETsmith** [comment]
@MilaimKas 

To answer your question about running only a single HF calculation, to the best of my knowledge the answer is no. However, you can make it a bit easier on yourself by using the scanner which uses previous MF and MCSCF results to help with convergence which can be difficult as you dissociate.

```python
import numpy as np
from pyscf import gto, scf, mcscf

# Mean Field
mol = gto.M(atom="O 0 0 0; H 0 0 0.9", basis="ccpvdz", spin=1, verbose=3)
mf = scf.ROHF(mol).run()

# SA-MCSCF
n_states = 2
weights = np.ones(n_states)/n_states
mc = mcscf.CASSCF(mf, 6, 7).state_average_(weights)
mc.kernel()
old_mo = mc.mo_coeff

# Use scanner so we leverage previous results
mc_scanner = mc.as_scanner()

for R in [0.9, 2.0, 5.0, 8.0, 10.0]:
    print("Running SA-MCSCF for O-H bondlength ", R)
    mol = gto.M(atom="O 0 0 0; H 0 0 {}".format(R), basis="ccpvdz", spin=1, verbose=3)
    mc_scanner(mol)
```

To answer your question about using a different number of electrons in your MF calc. That's definitely possible and somewhat common practice in active space calculations when generating initial guess orbitals is a challenge.

For your last question about mixing states with different electrons, you can by initializing your fcisolver object with different mols that have a different number of electrons.

**Comment by MilaimKas** [comment]
Thank you very much for your answer.
I did not know about the scanner function, this does indeed simplify the script.

Since you have answer all my questions, I will close this issue.
