### ISSUE TITLE
Strange results with XCFun 

### ISSUE THREAD

**Issue by theonov13** [pyscf/pyscf#809]
Hi everyone, 

we don't know if this is the correct place to push this, 
but we currently see some strange results for 
the H atom with the SCAN xc family 
using PySCF (master) with XCFun. 
We used an unpruned (75,302) grid and a 'cc-pvqz' basis set.

PySCF(master)+libxc(master)

LDA_X,LDA_C_PW :                -0.4785926097901295 Ha
PBE,PBE :                       -0.4998548375580568 Ha
MGGA_X_SCAN,MGGA_C_SCAN :       -0.5000927236540924 Ha
MGGA_X_RSCAN,MGGA_C_RSCAN :     -0.5000927231518122 Ha
MGGA_X_R2SCAN,MGGA_C_R2SCAN :   -0.5000927231520813 Ha

PySCF(master)+XCFun

SLATERX,PW92C :                 -0.47859271539387527 Ha 
PBE,PBE :                       -0.4998550223942305  Ha 
SCAN,SCAN :                     -0.23673750190235435 Ha 
RSCANX,RSCANC :                 -0.23673750190235426 Ha 
R2SCANX,R2SCANC :               -0.23673750190235435 Ha 

In contrast, LDA and PBE functionals give 
reasonable results with micro-Ha accuracy.

My colleague can reproduce these results. 

Is this an error in XCFun? 

Best, 
Sebastian (+Kai)

**Comment by kaitrepte** [comment]
Hi all,

I can reproduce this error. Is there a problem in XCFun? 

Best,
Kai

**Comment by fishjojo** [comment]
This is due to errors in xcfun v2.1.0. I'll update xcfun.

**Comment by theonov13** [comment]
Thank you for your quick response and for clarifying this issue. 
Let us know when the bug fix in XCfun is available,
such that we can try it and close this issue.

**Comment by fishjojo** [comment]
It's already been fixed. You can try the latest master branch.

**Comment by kaitrepte** [comment]
Hi there,

I checked with the new version of XCfun, and now I get consistent results:

SLATERX,PW92C : -0.4785927153938768 Ha 
PBE,PBE : -0.49985502239422586 Ha
SCAN,SCAN : -0.5000927236422149 Ha
RSCANX,RSCANC : -0.500092723615831 Ha
R2SCANX,R2SCANC : -0.5000927236161131 Ha

Thank you for fixing this. 

Best,
Kai

**Comment by theonov13** [comment]
Hi, 

thank you a lot. It works for me as well! 

SLATERX,PW92C : -0.4785927153938735 Ha 
PBE,PBE : -0.4998550223942193 Ha 
SCAN,SCAN : -0.5000927236422147 Ha 
RSCANX,RSCANC : -0.5000927236158311 Ha 
R2SCANX,R2SCANC : -0.5000927236161139 Ha 
R4SCANX,R4SCANC : -0.500092723616114 Ha 

Best, 
Sebastian
