### ISSUE TITLE
2-RDM for CASCI and CASSCF

### ISSUE THREAD

**Issue by jiangth1997** [pyscf/pyscf#811]
How can I obtain 2-RDM (two-particle reduced density matrix) for CASCI or CASSCF? It seems there are make_rdm2() functions for cc, ci, mp and fci modules, but no such function for mcscf module.

**Comment by ssnam92** [comment]
This might work:
```
from pyscf import lib,gto,scf,mcscf
import numpy as np

lib.num_threads(4)
mol=gto.M(atom='Be',basis='cc-pVDZ')
mf=scf.RHF(mol).run()
mc=mcscf.CASSCF(mf,2,2)
mc.kernel()
P1,P2=mcscf.addons.make_rdm12(mc)
print(np.shape(P1),np.shape(P2))
```

**Comment by jiangth1997** [comment]
Thank you! That seems exactly what I want.
