### ISSUE TITLE
The simplest example runs incorrectly (not converge)

### ISSUE THREAD

**Issue by Wang-Yao-USTC** [pyscf/pyscf#813]
Here is the log file:

[o2.log](https://github.com/pyscf/pyscf/files/5899308/o2.log)

Codes:

from pyscf import gto
from pyscf import scf

mol = gto.Mole()
mol.verbose = 5
mol.output = 'o2.log'
mol.atom = 'O 0 0 0; O 0 0 1.2'
mol.basis = 'ccpvdz'
mol.build()

m = scf.RHF(mol)
print('E(HF) = %g' % m.kernel())

==================================

Are there problems with my settings ? Thanks.

**Comment by tberkel** [comment]
O2 is an open shell ground-state triplet, so RHF is inappropriate.  UHF
should work fine.

**Comment by xubwa** [comment]
The output looks crazy, it shouldn't be a rhf/uhf issue, maybe the entire install failed.

**Comment by sunqm** [comment]
I cannot reproduce the error using the latest releases on conda or pypi.  You can consider to update the library with `pip install -U pyscf` or `conda update -c pyscf pyscf`
