### ISSUE TITLE
Importing pyscf.lib.logger breaks time reporting

### ISSUE THREAD

**Issue by mtreinish** [pyscf/pyscf#814]
Since https://github.com/pyscf/pyscf/commit/aec4b6f5125345afd26f263e7f8224505f451bfb whenever you import `pyscf.lib.logger` on python >=3.8 the reported time by anything that relies on system time no longer returns the correct time. You can see this most clearly with something like:

```python3
from datetime import date
print(date.today())
from pyscf.lib import logger
print(date.today())
```

The cause of this is that setting `time.time` to be `time.process_time` is incorrect and breaks any function that relies on getting system time (which includes most of the datetime module). Overriding members in a stdlib module have global impact and will break others code in unexpected ways.

**Comment by sunqm** [comment]
pyscf-2.0 will drop the legacy time.time statement. This is right now under the branch 2.0.

On Tue, Feb 02, 2021 at 05:09:04AM -0800, Matthew Treinish wrote:
> Since https://github.com/pyscf/pyscf/commit/aec4b6f5125345afd26f263e7f8224505f451bfb whenever you import `pyscf.lib.logger` on python >=3.8 the reported time by anything that relies on system time no longer returns the correct time. You can see this most clearly with something like:
> 
> ```python3
> from datetime import date
> print(date.today())
> from pyscf.lib import logger
> print(date.today())
> ```
> 
> The cause of this is that setting `time.time` to be `time.process_time` is incorrect and breaks any function that relies on getting system time (which includes most of the datetime module). Overriding members in a stdlib module have global impact and will break others code in unexpected ways.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyscf/pyscf/issues/814

--
