### ISSUE TITLE
Is there any way to pass parameters to libxc functionals via pyscf?

### ISSUE THREAD

**Issue by hebrewsnabla** [pyscf/pyscf#818]
Some libxc functionals, like TPSS, can accept parameters by
```
xc_func_set_ext_params(xc_func_type *p, double *ext_params);
```
which should be done before `_eval_xc`. See 'External parameters' in [libxc manual](https://www.tddft.org/programs/libxc/manual/libxc-5.1.x/)
but current `LIBXC_eval_xc` in `libxc_itrf.c` does not provide an option to do that. Hope there would be some way to modify these parameters via pyscf.

**Comment by susilehtola** [comment]
The long term solution would be to migrate PySCF to the official Libxc Python backend (pylibxc); there's no reason to duplicate the C wrapper code in PySCF.
