### ISSUE TITLE
numerical issue in pbc.SCF calculation

### ISSUE THREAD

**Issue by yangcal** [pyscf/pyscf#819]
Hi all, 

In a diamond cell with one atom slightly displace, the net forces on the two atoms are expected to add up to zero. But I've found this not to be numerically true sometimes. One example and output are attached below

Force on each atom are computed from both finite difference or analytical integrals and they seem to match well. But neither the FD force or the analytical force adds up to zero.

I think somewhere in pbc translational symmetry is broken, either in Vxc or integrals. This issue appeared sensitive to the numerical setting, eg, dft grid mesh, vxc type etc but I was not able to pin down where exactly the problem is. 

[Input: run.py](https://github.com/yangcal/debug_files/blob/main/pyscf_gradient/run.py)
[Output: out.dat](https://github.com/yangcal/debug_files/blob/main/pyscf_gradient/out.dat)

**Comment by sunqm** [comment]
The issue is likely caused by the non-orthogonal primitive cell. The nuclear gradients may need to include the response of crystal lattice. Unlike the cubic cell, the lattice in this case "feels" the nuclear force implicitly to preserve the hexagonal symmetry. This effect transfers to uniform grids, then the numerical integration on top of the grids. If you can write the lattice parameter as a function of the coordinates of either atom in the unit cell, I guess adding the derivative chain ~(d Exc / d grid) * (d grid / d lattice) * (d lattice / d X) may fix the error

**Comment by fishjojo** [comment]
Actually, the same error also appears in cubic cells. PBE seems to produce larger error than LDA.

**Comment by fishjojo** [comment]
```
from pyscf.pbc import scf, dft, gto, grad
import numpy as np
from pyscf.lib import logger
from pyscf import __config__
__config__.pbc_dft_rks_RKS_small_rho_cutoff = 1e-10
def gen_cell(atom):
    cell = gto.Cell()
    cell.atom = atom
    cell.basis = 'gth-szv'
    cell.pseudo = 'gth-pade'
    cell.a = '''
    3.370137329, 0., 0.
    0., 3.370137329, 0.
    0., 0., 3.370137329'''
    cell.unit = 'B'
    cell.verbose = 1
    cell.mesh = [28,]*3
    cell.build()
    return cell

xc = 'pbe'
if __name__ == '__main__':
    disp = 0.1
    atom_0 =  [["C", [0.0000000000, 0.0000000000, 0.0000000000 + disp]],
               ["C", [1.6850686645, 1.6850686645, 1.6850686645]]]
    cell = gen_cell(atom_0)
    kpts = cell.make_kpts([1,1,1])
    mf = dft.KRKS(cell, kpts, exxdiv=None)
    mf.xc = xc
    mf.conv_tol = 1e-14
    mf.conv_tol_grad = 1e-8
    e1 = mf.kernel()

    atom_c0_plus = [["C", [0.0000000000, 0.0000000000, 0.0000000000]],
                    ["C", [1.6850686645, 1.6850686645, 1.6850686645 - disp]]]
    cell_c0_plus = gen_cell(atom_c0_plus)
    mf = dft.KRKS(cell_c0_plus, kpts, exxdiv=None)
    mf.xc = xc
    mf.conv_tol = 1e-14
    mf.conv_tol_grad = 1e-8
    e2 = e_c0_plus = mf.kernel()

    print(e1-e2)
```
This may be related to the problem. When I use odd number of mesh points (e.g., 29), the energy difference between the two equivalent cells is around 1e-6. But if I use even number of mesh points (e.g., 28), the energy difference is around 1e-14.

**Comment by yangcal** [comment]
I do believe the error is somewhat related to the DFT mesh, but I think I remember seeing systems where even mesh points doesn't fix the issue(even up to very high mesh, eg, [40,40,40]).

**Comment by fishjojo** [comment]
The force of the `E_xc` part converges very slowly wrt the uniform grid size (the current pyscf default value is not enough). I think there may be some response term missing as the current implementation is based on the analytic formulation. Interestingly, the force computed by CP2K does not sum to zero either. But I think an error ~1e-4 should be acceptable.

**Comment by fishjojo** [comment]
The problem is that using atom centered basis with uniform grid makes Exc translationally variant.
