### ISSUE TITLE
open-shell TDDFT using ROKS

### ISSUE THREAD

**Issue by proexcuse** [pyscf/pyscf#826]
Hello,

I'm curious if I can conduct ROKS-TDDFT calculation for open-shell systems.

Thanks in advance.

**Comment by jamesETsmith** [comment]
@proexcuse, I don't think we do (I could be wrong though), but we definitely support UKS-TDDFT. See [`pyscf.tdscf`](https://github.com/pyscf/pyscf/tree/master/pyscf/tdscf) for more details.

**Comment by proexcuse** [comment]
Thank you for your reply.
