### ISSUE TITLE
6 hartrees higher for formamide

### ISSUE THREAD

**Issue by kuitpo** [pyscf/pyscf#827]
All using the coordinates for formamide below with PBE and def2-TZVP, these energies are returned:
PySCF:  -163.4903
Psi4:     -169.7770
Orca:    -169.7771
i.e. PySCF is more than 6 hartrees higher than Psi4 and Orca. This is taking all defaults with PySCF 1.7.5.1. Density fitting doesn't change this, and nor does changing initial guess to atom. SOSCF makes it one hartree worse.
Coordinates:

 C         0.000000000000      0.000000000000      0.000000000000
 N         1.356034398916      0.000000000000      0.000000000000
 O        -0.690465056250     -0.991175225175      0.000000000000
 H         1.874680453478      0.858243986157      0.000000000000
 H        -0.423361746994      1.018363682537      0.000000000000
 H         1.847592766362     -0.877450958324      0.000000000000

**Comment by jamesETsmith** [comment]
@kuitpo, thanks for using PySCF! In the future, it would be helpful if you could post an input file so we could have a record of all the settings you used.

I can't reproduce your results with PySCF 1.7.5.2, here is the input file I used:

```python
from pyscf import gto, dft

mol = gto.M(atom="""C 0.000000000000 0.000000000000 0.000000000000
N 1.356034398916 0.000000000000 0.000000000000
O -0.690465056250 -0.991175225175 0.000000000000
H 1.874680453478 0.858243986157 0.000000000000
H -0.423361746994 1.018363682537 0.000000000000
H 1.847592766362 -0.877450958324 0.000000000000""",
    basis="def2-TZVP",
    verbose=3,
    symmetry=True)
mf = dft.RKS(mol, xc="PBE").newton()
mf.kernel()
```

Here's the output:

```
converged SCF energy = -169.776920625
```

That energy is the same whether or not I use SOSCF. Try updating your PySCF version and use my input file to see if your problem persists.

**Comment by kuitpo** [comment]
My bad. Had 
gto.M(unit='au')
bohr rather than angstrom. Surprised it ran at all. 
Sorry to bother you with it.

**Comment by jamesETsmith** [comment]
No worries, happy to help!
