### ISSUE TITLE
latest pyscf support scf calculation under background charge?

### ISSUE THREAD

**Issue by leebo-2020** [pyscf/pyscf#828]
dear developers,
The latest pyscf support scf calculation under background charge? thank you.

**Comment by jamesETsmith** [comment]
@leebo-2020, yes it does, please see the example below:

https://github.com/pyscf/pyscf/blob/85addafa1697ad128d401922e123c66f85215daa/examples/qmmm/00-hf.py#L10-L33

Just to be sure I checked with my locally installed version (1.7.5.2) and the example runs without a problem. Searching for QMMM in the GitHub actions section also shows that the tests are working with the latest version of the master branch.
