### ISSUE TITLE
k2gamma unfolding for 3c2e-integrals

### ISSUE THREAD

**Issue by Majokux** [pyscf/pyscf#830]
I am trying to avoid the very long GDF setup times in supercell calculations, by performing a k2gamma-style unfolding of k-sampled, primitive cell 3c2e-integrals. I actually first tried this for the 4c2e-integrals, as shown in the function `k2gamma_4c2e`
in the code below and it seems to work fine.

I then try this for the 3c2e-integrals, as shown in `k2gamma_3c2e`, and obtain a set of complex 3c-integrals, which are different from the real set of 3c-integrals at the supercell Gamma-point. I think this is not a problem per se (except for the unfortunate factor of 2 in memory and runtime...), as long as the 4c integrals, contracted from the 3c integrals, are real and correct (which they seem to be in this example).

In order for the unfolded 3c->4c contraction to be correct for some k-point meshes, such as [1,2,3], I need to contract them
as `eri = einsum("Lji,Lkl->ijkl", j3c.conj(), j3c)` - this is NOT the same as `eri = einsum("Lij,Lkl->ijkl", j3c, j3c)`  (which I would think would be the correct way...), since the 3c integrals do not seem to have the symmetry (L|ij) = (L*|ji).

While the unfolding seems to work in this simple example, in more complex cases (a 2x2x2 supercell of SrTiO3), the final, contracted 4c integrals at the supercell Gamma-point appear to have significant imaginary elements of the order of 1e-3. In this case, I also find that post-HF calculations of a regular supercell calculation and a k-point sampled HF + k2gamma unfolding can differ significantly; and it does not seem to be a matter of choosing a smaller `cell.precision`. I think the unfolding of the 3c-integrals could be the origin of this inconsistency. 

I have multiple questions:
Is this unfolding of 3c integrals reasonable; are there errors or inconsistencies in my complex conjugations or contractions?
Would there be a way to not just get "equivalent" 3c-integrals, but actually the same, real 3c-integrals as the direct GDF of the supercell yields? I think this would avoid a lot of issues.
Are there other parameters I need to look out for, which could explain the energy difference between direct supercell post-HF and k2gamma unfolded supercell post-HF calculation?

Many thanks!

edit:
I noticed four different cases in `get_eri` in `pyscf/pbc/df/df_ao2mo`, where the contraction scheme of the 3c integrals seems to depend on all four k-points - these cases are basically ignored in my 3c -> unfolded 3c -> 4c workflow, could this be a problem? Or are the cases above the "else" just optimized contraction, avoiding complex arithmitic were unnecessary etc?

Code:
[k2gamma_3c.py.txt](https://github.com/pyscf/pyscf/files/6077901/k2gamma_3c.py.txt)

**Comment by zhcui** [comment]
Hi,

I took a look on your code, it seems that you did the transformation on Lij's i and j. But actually in order to get the same aux basis of the supercell, you need to do a transform on L as well. In your case, what you really get, is a set of gdf of the supercell basis expanded on a set of complex aux basis of the primitive cell (this is why your 3c integrals are complex, but after constructing 4c, you may get the correct 4c real integral).

I don't understand the difference in post-HF calculations, given that your supercell 4c ERIs are the same (unless the post-HF solutions breaks the symmetry).

get_eri in pyscf/pbc/df/df_ao2mo has several difference cases, but they are only for optimization (using some symmetry). This is not related to the problem in your code.

Best,
Zhihao

**Comment by Majokux** [comment]
Hi Zhihao,
Thanks for your reply! The unfolding of the auxiliary basis (as `j3c_sc = einsum("k...,kR->R...", j3c_sc, phase)`) indeed makes the 3c integrals real for this He-crystal test system (I also tried a Ne-crystal with the gth-dzvp basis to get some 3d functions and with kmesh [1,2,3] it's also rendered real...). They are still not identical to the auxiliary basis of the supercell GDF, but this might be just an ordering issue of the basis or similar, I don't think I need this identity.

Now going back to my pathological SrTiO3 case, it turns out that the c3-integrals are still *not* rendered real, even when transforming the auxiliary dimension. I don't have a good intuition as to why this might be the case. One thing I noticed is that for my simple test cases it does not matter if I transform the L with `phase` or `phase.conj()` -
for my SrTiO3 system, the result is different (but in both cases not real).

**Comment by zhcui** [comment]
Are you using gamma-centered kmesh?

**Comment by Majokux** [comment]
Yes indeed, just like in the example code.

**Comment by Majokux** [comment]
As a small update to this, if I use `cell.exp_to_discard = 0.1` (before I had it at `None`), the unfolded 3c integrals become real for my troublesome SrTiO3 case. HF energies are also very close to the supercell HF result, but, unfortunately, post-HF correlation energies are still very different (the k2gamma correlation energies are approx 0.2 Eh lower). Lowering `cell.precision` of both the k2gamma and supercell calculations from `1e-5` to `1e-8` does only lead to changes of the order of ~1mEh. I also loaded the supercell 3c integrals into my otherwise k2gamma calculation, and indeed it now reproduces the supercell correlation energies, showing that the difference must be entirely contained in the unfolded 3c-integrals.

I don't know if there are any numerically ill-conditioned steps, which could cause me problems... Should I perhaps try to not unfold "Lij" , but j3c and j2c individually, and then cholesky/eigen decompose j2c in the unfolded space before combining them to "Lij"? I noticed that the condition number of j2c is often ~1e14, but the CD does not fail. If I instead force it into the eigh branch to remove some linear dependency, in the end the unfolded 3c-integrals have significant imaginary parts again...

Also, @zhcui , if you don't mind me asking here, since it's tangentially related: why does the k2gamma routines in PySCF use the fock matrix to realize degenerate subspaces, whereas the code in your repo uses the density matrix? I have my k2gamma frequently hit the asserts `abs(f.imag).max() < 1e-4`.

**Comment by zhcui** [comment]
Using fock can keep some symmetry of the hamiltonian if hamiltonian has some additional symmetry information in the degenerate subspace.

**Comment by Majokux** [comment]
I have found the bug, and it's in my code:

```
def load_j3c(cell, gdf, kij):
    """Load 3c-integrals into memory"""
    nao = cell.nao_nr()
    naux = gdf.auxcell.nao_nr()
    j3c_kij = np.zeros((naux, nao, nao), dtype=np.complex)

    for lr, li, sign in gdf.sr_loop(kij, compact=False):
        assert (sign == 1)
        nauxk = lr.shape[0]
        assert nauxk <= naux
        j3c_kij[:nauxk] += (lr+1j*li).reshape(nauxk, nao, nao)

    return j3c_kij
 ```
 
The results of `sr_loop` are all just added on top of each other into the chunk `:nauxk` of `j3c_kij`; instead the mask must be moved forward by the blocksize each loop. This did bug did not manifest in my test systems, since `sr_loop` just returns the entire 3c integrals in a single loop in these cases.

Thanks for your help!
