### ISSUE TITLE
performance challenge at larger atom counts

### ISSUE THREAD

**Issue by kuitpo** [pyscf/pyscf#831]
Buying the "hotspots in C" argument for python, I would very much like to get PySCF into the ballpark of Orca performance for the problem described below. It looks like Orca reaches SCF convergence before PySCF has started SCF. Perhaps this is due to differences in grid setup, possibly pruning in particular.

Orca reaches SCF convergence even with VeryTightSCF in something like 12 hours on a single core (but the job then dies because of power failure, but sufficient information has been collected). PySCF reaches the second last line of its output quickly, but then takes 5 hours to output the last line 'tot grids = 11566774' and then executes without further output for another 8 hours before being cancelled. The difference in performance looks to be grid related. The grid options that Orca selected are largely the same as the PySCF defaults, with at least one possibly notable exception: the grid pruning option used. PySCF uses nwchem_prune and Orca uses '3 (G Style)'. Is this the source of the performance difference? If so, does this Orca grid option exist in PySCF, and if so, by what name?

On non-grid matters, have also tried letting the auxbasis default, and removing newton(), but these make no difference.

Files in the zip:  PySCF script, xyz coordinates, PySCF output, Orca output. 

Thanks in advance for considering this problem.

[performance_1_1.zip](https://github.com/pyscf/pyscf/files/6087727/performance_1_1.zip)

**Comment by sunqm** [comment]
Are you looking for the SG* pruning? Only SG1 pruning was implemented.
https://github.com/pyscf/pyscf/blob/master/pyscf/dft/gen_grid.py#L85

Grid scheme is definitely one source for slow performance. Sparsity in the
tensors might be another possible source that pyscf didn't explore. The
underlying C code
https://github.com/pyscf/pyscf/blob/master/pyscf/lib/vhf/nr_sgx_direct.c#L137
does not assume any sparsity.

On Thu, Mar 04, 2021 at 06:15:48PM -0800, kuitpo wrote:
> Buying the "hotspots in C" argument for python, I would very much like to get PySCF into the ballpark of Orca performance for the problem described below. Orca has reached SCF convergence even with VeryTightSCF in something like 12 hours on a single core (but the job then dies because of power failure, but sufficient information has been collected). PySCF reaches the second last line of its output quickly, but then takes 5 hours to output the last line 'tot grids = 11566774' and then executes without further output for another 8 hours before being cancelled. The difference in performance looks to be grid related. The grid options that Orca selected are largely the same as the PySCF defaults, with at least one possibly notable exception: the grid pruning option used. PySCF uses nwchem_prune and Orca uses '3 (G Style)'. Is this the source of the performance difference? If so, does this Orca grid option exist in PySCF, and if so, by what name?
> 
> On non-grid matters, have also tried letting the auxbasis default, and removing newton(), but these make no difference.
> 
> Relevant files including coordinates are attached as a zip file. Thanks in advance for considering this problem.
> 
> [performance_1_1.zip](https://github.com/pyscf/pyscf/files/6087727/performance_1_1.zip)
> 
> 
>   
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyscf/pyscf/issues/831

--

**Comment by kuitpo** [comment]
I am interested in the cpu and ram efficiency of non-hybrid methods such as the GGA PBE and particularly so in the meta-GGA r2SCAN (r2SCAN-3c). This paper speaks of 5-18 times improvement over CFMM in both these efficiencies for construction of the Coulomb Matrix. The new compression technique can be extended to accelerate the tensor contractions of DF. Would it be viable for PySCF to implement this technique?
"FAST COULOMB MATRIX CONSTRUCTION VIA COMPRESSING THE INTERACTIONS BETWEEN CONTINUOUS CHARGE DISTRIBUTIONS"
[](https://www.cc.gatech.edu/~echow/pubs/xing-chow-sisc-2019.pdf)

Also:
"A linear scaling hierarchical block low-rank representation of the electron repulsion integral tensor"
[](https://www.cc.gatech.edu/~echow/pubs/eri_h2_jcp.pdf)
