### ISSUE TITLE
Cannot import pyscf.geomopt.geometric_solver.optimize

### ISSUE THREAD

**Issue by jagunther** [pyscf/pyscf#834]
Running `import pyscf.geomopt.geometric_solver.optimize` in a jupyter notebook throws the following error for me:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-a780f519e4c8> in <module>
      1 from pyscf import gto, scf
----> 2 from pyscf.geomopt.geometric_solver import optimize
      3 
      4 mol = gto.M(atom='''
      5                 H

~/anaconda3/envs/qchem/lib/python3.7/site-packages/pyscf/geomopt/geometric_solver.py in <module>
     21 import tempfile
     22 import numpy
---> 23 import geometric
     24 import geometric.molecule
     25 #from geometric import molecule

~/anaconda3/envs/qchem/lib/python3.7/site-packages/geometric/__init__.py in <module>
      4 
      5 
----> 6 from . import molecule
      7 from . import optimize
      8 from . import engine

~/anaconda3/envs/qchem/lib/python3.7/site-packages/geometric/molecule.py in <module>
    441 try:
    442     import networkx as nx
--> 443     class MyG(nx.Graph):
    444         def __init__(self):
    445             super(MyG,self).__init__()

AttributeError: module 'networkx' has no attribute 'Graph'
```

I have pyscf 1.7.5.1, geometric 0.9.7.2 and networkx 2.3 installed.

Reinstalling the packages did not help. Since geometry optimizations with PyBerny work fine, this issue can be circumvented. I just wanted to point this out, in case I am not the only one with this error. If no one else has this issue then at least I know this is a problem on my end.

**Comment by shivupa** [comment]
This looks like a geometric issue or probably an issue with your networkx install. Are you able to run the following:
```
>>> import networkx as nx
>>> from networkx import Graph
```

**Comment by jagunther** [comment]
The second line fails again. Reinstalling in a new conda environment did it for me, so although I don't know what exactly the problem was, it's solved for me now.
