### ISSUE TITLE
(R)MP2 gradient inefficiency due to einsum implementation

### ISSUE THREAD

**Issue by ajz34** [pyscf/pyscf#835]
Hi devs!

When I try to calculate benzene (C6H6) gradient at MP2/cc-pVTZ level, I found default pyscf (obtained from pypi, where numpy/mkl from conda) often run in only one thread (100% CPU) where multiple threads available (e.g. 24 CPU).
This problem is probably from einsum function implementation. Algorithms are correct.

The possible solution will be stated in next reply.

The code to perform a gradient could be:
```python
from pyscf import gto, scf, mp, grad

mol = gto.Mole()
mol.atom = """
C   1.40000000   0.00000000   0.00000000
C   0.70000000   1.21243557   0.00000000
C  -0.70000000   1.21243557   0.00000000
C  -1.40000000   0.00000000   0.00000000
C  -0.70000000  -1.21243557   0.00000000
C   0.70000000  -1.21243557   0.00000000
H   2.49000000   0.00000000   0.00000000
H   1.24500000   2.15640326   0.00000000
H  -1.24500000   2.15640326   0.00000000
H  -2.49000000   0.00000000   0.00000000
H  -1.24500000  -2.15640326   0.00000000
H   1.24500000  -2.15640326   0.00000000
"""
mol.basis = "cc-pVTZ"
mol.max_memory = 20 * 1024
mol.build()

mf_scf = scf.RHF(mol).run()
mf_mp2 = mp.MP2(mol).run()
mf_grad = grad.mp2.Gradients(mf_mp2).run()
```

**Comment by sunqm** [comment]
You can try to compile the TBLIS interface when compiling the C extensions.  http://pyscf.org/pyscf/install.html#tblis

pyscf/pyscf/mp/mp2.py L191 can be replaced by lib.einsum. It can be faster than numpy einsum

L99 to L110 are memory bounded. lib.einsum is likely not helpful.

L96 in principle can be improved if the tblis plugins are compiled.

**Comment by ajz34** [comment]
Thanks!
For grad/mp2.py L96, actually I've tried out TBLIS. That is quite efficient 😄 (the compromise is to use pyscf from source but not pypi)
I found that numpy could be equally efficient if atomic basis is large, but the compromise is an explicit for loop, thus complexity of code is increased.
I just wonder in case of this situation, if you would perfer to change the code, or keep the code as it was 😂

**Comment by sunqm** [comment]
It'd be great if you can issue a PR for the optimization.

In the upcoming pyscf-2.0 release, the pyscf-TBLIS interface will be released as
a precompiled wheel. The tblis-optimized einsum will be available in pip. The
TBLIS functionalities can be turned on/off by setting in the code

pyscf.lib.numpy_helper.FOUND_TBLIS = True  # False

On Wed, Mar 10, 2021 at 06:36:04PM -0800, Zhenyu Zhu ajz34 wrote:
> Thanks!
> For grad/mp2.py L96, actually I've tried out TBLIS. That is quite efficient 😄 (the compromise is to use pyscf from source but not pypi)
> I found that numpy could be equally efficient if atomic basis is large, but the compromise is an explicit for loop, thus complexity of code is increased.
> I just wonder in case of this situation, if you would perfer to change the code, or keep the code as it was 😂 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyscf/pyscf/issues/835#issuecomment-796388194

--

**Comment by ajz34** [comment]
Wow, that sounds great! 🎉
