### ISSUE TITLE
Vxc matrix for small components in DKS

### ISSUE THREAD

**Issue by hoshishin** [pyscf/pyscf#839]
Dear developers,

If \vec{M}(\vec{r})= \sum_{i\in \rm{occ.}}\psi_i^{\dag}(\vec{r})\beta \vec{\Sigma}\psi_i(\vec{r}) , Why 
`matSS[idm] += _vxc2x2_to_mat(mol, ao[2:], weight, rho, vrho,
                                                 mask, shls_slice, ao_loc)`
and
`vmat[idm,n2c:,n2c:] = matSS[idm] * c1**2`
is plus not minus ?

Thanks a lot !

**Comment by sunqm** [comment]
vxc[n2c:,n2c:] holds integrals of small components for scalar potential
operator, similar to a regular 1-electron operator (e.g. V_ne the
nuclear-electron attraction).

On Thu, Mar 11, 2021 at 06:46:42PM -0800, hoshishin wrote:
> Dear developers,
> 
> If \vec{M}(\vec{r})= \sum_{i\in \rm{occ.}}\psi_i^{\dag}(\vec{r})\beta \vec{\Sigma}\psi_i(\vec{r}) , Why 
> `matSS[idm] += _vxc2x2_to_mat(mol, ao[2:], weight, rho, vrho,
>                                                  mask, shls_slice, ao_loc)`
> and
> `vmat[idm,n2c:,n2c:] = matSS[idm] * c1**2`
> is plus not minus ?
> 
> Thanks a lot !
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyscf/pyscf/issues/839

--

**Comment by hoshishin** [comment]
Thank you Qiming, but I'm still confused about that. In my view, vxc for small component  will be

(-1)\frac{\partial \epsilon}{\partial s}  \mu^{\dagger}  \sigma \nu

where,  \mu and \nu are both small component basis, and the (-1) exists because of the \beta matrix, so I think vxc about \frac{\partial \epsilon}{\partial s} should be negative.

Thanks alot!

**Comment by sunqm** [comment]
Vxc for small components were reimplemented in pyscf-2.1, along with the new non-collinear functional MCfun . This problem is fixed in PR #1256
