### ISSUE TITLE
Compiling problem (xcfun related)

### ISSUE THREAD

**Issue by shaoqx** [pyscf/pyscf#844]
My initial installation failed reporting errors about xcfun. After looking into issue #738. I manually installed xcfun with conda and tried to compile pyscf with:
```
cd pyscf/lib
mkdir build && cd build
cmake -DBUILD_XCFUN=OFF ..
make
```
But it still fails this time after printing
```
Scanning dependencies of target xcfun_itrf
[ 96%] Building C object dft/CMakeFiles/xcfun_itrf.dir/xcfun_itrf.c.o
/mypath/bin/pyscf/pyscf/lib/dft/xcfun_itrf.c:25:25: error: XCFun/xcfun.h: No such file or directory
...
make[2]: *** [dft/CMakeFiles/xcfun_itrf.dir/build.make:66: dft/CMakeFiles/xcfun_itrf.dir/xcfun_itrf.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:880: dft/CMakeFiles/xcfun_itrf.dir/all] Error 2
make: *** [Makefile:87: all] Error 2
```
Is the `-DBUILD_XCFUN=OFF` not turning all xcfun related steps off?

All the Best,
Qianzhen

**Comment by fishjojo** [comment]
If you don't want to use xcfun, then use
`cmake -DENABLE_XCFUN=OFF`.
`-DBUILD_XCFUN=OFF` only tells cmake to not compile the xcfun library, but the interface code in pyscf is still compiled by default. And if you don't have xcfun library installed, this will give you the header file not found error.

**Comment by shaoqx** [comment]
I see. Thank you!
