### ISSUE TITLE
SC-NEVPT2 tests

### ISSUE THREAD

**Issue by sunqm** [pyscf/pyscf#854]
Regarding to the PR #737 and #853 , are the negative values in the SC-NEVPT2 denominator an error?

**Comment by gkc1000** [comment]
Negative denominators are not an error, they are a sign of intruder states
nearby.

**Comment by pinskip** [comment]
There was a mistake which caused somewhat wrong results in two classes. It have created pull request #863 with a fix.

**Comment by sunqm** [comment]
Thanks for the careful comparison and the bugfix!
