### ISSUE TITLE
Segmentation fault in test pyscf/lib/gto/test/test_ecp.py

### ISSUE THREAD

**Issue by verena-neufeld** [pyscf/pyscf#866]
I am getting a segmentation fault when running the test pyscf/lib/gto/test/test_ecp.py. Is this a known issue? I noticed it when looking for the reason why PRs #860 and #861 were failing with segmentation faults. After having merged master in, PR #860 passes now (which I don't quite understand but it could have fixed some issue). I've started to look into the reason why this segmentation fault happens but didn't get anywhere concrete yet.

**Comment by sunqm** [comment]
bug fixed in f2e5dbf08
