### ISSUE TITLE
Build directory path is saved into the shared libraries

### ISSUE THREAD

**Issue by yurivict** [pyscf/pyscf#87]
Paths are hardcoded in the shared libraries, which they shouldn't be:
```
# strings /usr/local/lib/python2.7/site-packages/pyscf/lib/libcgto.so | grep work
/usr/local/lib/gcc5:/usr/ports/science/py-pyscf/work/pyscf-1.3.2/lib/deps/lib:/usr/ports/science/py-pyscf/work/pyscf-1.3.2/lib/deps/lib64:/usr/local/lib:/usr/local/lib64:/usr/ports/science/py-pyscf/work/pyscf-1.3.2/lib
```
- the temporary build directory /usr/ports/science/py-pyscf/work appears in the permanently installed libraries.

**Comment by sunqm** [comment]
Cmake by default build libraries with rpath.  You can skip this by specifying -DCMAKE_SKIP_RPATH=1 in cmdline for now.  I need to consider whether to change this in the future.

**Comment by yurivict** [comment]
```DCMAKE_SKIP_RPATH=1``` helps, but RPATH shouldn't be saved. Most cmake project don't do this by default.
