### ISSUE TITLE
Third derivatives of meta-GGAs missing for spin-polarized calculations

### ISSUE THREAD

**Issue by susilehtola** [pyscf/pyscf#877]
Comparing `libxc.py` and `xcfun.py`, it looks like third derivatives have been implemented in the libxc interface for spin-restricted calculations, but not spin-unrestricted calculations.

Looking at the code, adding in the missing third derivatives for spin-polarized calculations might be as easy as adding the missing entry for `deriv > 2` after https://github.com/pyscf/pyscf/blob/3e48389141e55c2253792d403f9b65cd173e8ba0/pyscf/dft/libxc.py#L1500

but it might need someone who is familiar with the indexing used in the code.

This might be a good addition to the 2.0 release, given that there doesn't seem to be an error check in that code! I would assume that anything requiring third derivatives will give different values in spin-restricted and spin-unrestricted calculations...

**Comment by sunqm** [comment]
If calling libxc 3rd order derivatives for spin-unrestricted calculations, the calculation will fail due to type error when accessing kxc. kxc was set to None in the libxc eval_xc function.

**Comment by susilehtola** [comment]
Yeah I noticed that MGGA support is missing for e.g. gradients, Hessians, and stability analysis, too..
