### ISSUE TITLE
DMRG with CheMPS2 documentation missing

### ISSUE THREAD

**Issue by JFurness1** [pyscf/pyscf#886]
I am trying to use the CheMPS2 library to power DMRG calculations from PySCF and am finding that the documentation is heavily focused to towards using Block, and doesn't adequately cover the differences for using CheMPS2 for me to be able to run it. I have built CheMPS2 and PyCheMPS2, and the library's tests complete successfully.

Documentation makes it clear that the `pyscf/dmrgscf/settings.py` file must be modified to select the DMRG library.

Looking in this I see two sections, one for BLOCK, then a smaller one for CheMPS2, seemingly requiring only one input apparently pointing to the compiled library. If I am understanding correctly, then for me this will be:

```python
PYCHEMPS2BIN = '/home/SOFTWARE/cheMPS2/PyCheMPS2/build/lib.linux-x86_64-3.7/PyCheMPS2.cpython-37m-x86_64-linux-gnu.so'
```

Then, turning my attention to `examples/dmrg/01-dmrg_casscf_with_block.py`, I assume this must be modified in some way to target CheMPS2 rather than BLOCK, but it is not clear how. I cannot find an equivalent example for CheMPS2, so I am left confused on how to run with this library.

Have I missed some documentation? Or could you please advise on how I can modify the example for use with CheMPS2?

**Comment by bogdanoff** [comment]
CheMPS2 interface is very basic, you can check how it works based on `pyscf/dmrgscf/test/test_chemps2_n2.py` test and the very end of the `pyscf/dmrgscf/chemps2.py` file. I also add a bit modified version of the latter here.

```
from pyscf import gto
from pyscf import scf
from pyscf import mcscf
from pyscf import dmrgscf

b = 1.4
mol = gto.Mole()
mol.build(
    verbose = 5,
    output = 'out-chemps2',
    atom = [['H', (0.,0.,i)] for i in range(8)],
    basis = {'H': 'sto-3g'},
    symmetry = True,
    symmetry_subgroup = 'D2h',
)
m = scf.RHF(mol)
m.scf()

mc = mcscf.CASSCF(m, 4, 4)
mc.fcisolver = dmrgscf.CheMPS2(mol)

# mc.fcisoverwfn_irrep = 0
# mc.fcisoverdmrg_states = [ 200 , 500 , 1000 , 1000 ]
# mc.fcisoverdmrg_noise = [ 1 , 1 , 1 , 0 ]
# mc.fcisoverdmrg_e_convergence = 1e-8
# mc.fcisoverdmrg_noise_factor = 0.03
# mc.fcisoverdmrg_maxiter_noise = 5
# mc.fcisoverdmrg_maxiter_silent = 100

emc_1 = mc.mc2step()[0]

mc = mcscf.CASCI(m, 4, 4)
mc.fcisolver = dmrgscf.CheMPS2(mol)
emc_0 = mc.casci()[0]

# Reference FCI calculations:

b = 1.4
mol = gto.Mole()
mol.build(
    verbose = 5,
    output = 'out-casscf',
    atom = [['H', (0.,0.,i)] for i in range(8)],
    basis = {'H': 'sto-3g'},
    symmetry = True,
)
m = scf.RHF(mol)
m.scf()

mc = mcscf.CASSCF(m, 4, 4)
emc_1ref = mc.mc2step()[0]

mc = mcscf.CASCI(m, 4, 4)
emc_0ref = mc.casci()[0]

print('CheMPS2-CI  = %.15g CASCI  = %.15g' % (emc_0, emc_0ref))
print('CheMPS2-SCF = %.15g CASSCF = %.15g' % (emc_1, emc_1ref))
```

**Comment by JFurness1** [comment]
Thank you. 

I had missed these examples, I can now run DMRG using CheMPS2.
