### ISSUE TITLE
Git history of extended projects is not forwarded to individual repositories

### ISSUE THREAD

**Issue by bogdanoff** [pyscf/pyscf#890]
I'm not sure if that is a real issue.
But I think at the moment it can be still fixed, as those repositories are not widely used yet.

With help of [git-filter-repo](https://github.com/newren/git-filter-repo) and cherry-pick I restored history for **dmrgscf** and **shciscf** for now, see
[https://github.com/bogdanoff/pyscf/tree/ext-dmrgscf](https://github.com/bogdanoff/pyscf/tree/ext-dmrgscf)
[https://github.com/bogdanoff/pyscf/tree/ext-shciscf](https://github.com/bogdanoff/pyscf/tree/ext-shciscf).
So these branches can be force-pushed to _pyscf/shciscf_ and _pyscf/dmrgscf_ without changing actual files but restoring the history from _pyscf/pyscf_.

If you think it is useful, I can do the same for other external modules too.

Addition:
To simplify things I also created forks
https://github.com/bogdanoff/dmrgscf and https://github.com/bogdanoff/shciscf .

**Comment by sunqm** [comment]
For sure it is useful to keep history. Would you please apply the same fixes for other repos?

**Comment by bogdanoff** [comment]
I created _history_ branches in the following repositories. New branches can be compared against master with and force-pushed.
* pyscf/dftd3
* pyscf/dmrgscf
* pyscf/fciqmc
* pyscf/icmpspt
* pyscf/nao
* pyscf/properties
* pyscf/pyscf-tblis
* pyscf/semiempirical
* pyscf/shciscf.

I prepared _history_ branches for the following repositories in my forks.
* pyscf/naive-hci
* pyscf/doci
* pyscf/cornell-shci.

Git commands should be something like this:
```
git clone git@github.com:pyscf/dftd3.git
cd dftd3
git diff history
```
If everything is fine, we can keep the original commits from external project
```
git checkout -b original
git push --set-upstream origin original
```
and do the nasty force push
```
git checkout master
git reset --hard history
git push -f origin
```

**Comment by sunqm** [comment]
Thank you for rebuilding the history and the instruction. All history were restored.
