### ISSUE TITLE
How can one get the occupied and virtual orbital indices from the output of the avas method?

### ISSUE THREAD

**Issue by PabloAMC** [pyscf/pyscf#894]
I intend to use avas method to select an active space, but the issue is that while internally avas computes and logs the virtual (`movir.shape[1]`) and occupied indices (`mocore.shape[1]`), see
https://github.com/pyscf/pyscf/blob/1de8c145abb3e1a7392df9118e8062e6fe6bde00/pyscf/mcscf/avas.py#L165
and 
https://github.com/pyscf/pyscf/blob/1de8c145abb3e1a7392df9118e8062e6fe6bde00/pyscf/mcscf/avas.py#L167
it does not return them. 
Is there a way I can recover them from `ncas, nelecas, mo`, the output of avas, without modifying the avas source code?

**Comment by fishjojo** [comment]
See examples in https://github.com/pyscf/pyscf/blob/master/examples/mcscf/43-avas.py
