### ISSUE TITLE
CASSCF Energy change between Version 1.6.6 and Version 1.7.5

### ISSUE THREAD

**Issue by HehnLukas** [pyscf/pyscf#908]
We recently installed v 1.7.5 on our system and I wanted to check that the CASSCF functionality remained the same. However, when I tested a very simple CASSCF calculation of an FE3+ Ion with an active space of 11 electrons and 12 orbitals, I get different results between the versions, despite using the exact same input. The UHF calculation I am using to base the CASSCF on starts with a different initial guess, which was also in the changelog, but converges on the same value. The CASSCF based on it, however, seems to be doing something a bit differently, as all the values are a bit different.

Basically, these are my results:
V 1.6.6: 
converged SCF energy = -1260.59051270702  <S^2> = 8.7512185  2S+1 = 6.0004061
CASSCF energy = -1260.66802556375

V 1.7.5
converged SCF energy = -1260.59051270701  <S^2> = 8.7512185  2S+1 = 6.0004061
CASSCF energy = -1260.6568519401

I am quite sure that the energy value of the older version is correct, as I have also done the same calculation in gaussian and gotten the same result as the old version. It does look like there is a bit of a plateau near 1260.65685 as also the V1.6.6 calculations DE gets close to the convergence criteria. 

I have found nothing in the changelog that would explain why the casscf is being handled differently in the new version.

**Comment by sunqm** [comment]
mcscf code basically was not updated in version 1.7.

With mol.verbose=4, the program can print more details of the mcscf optimization procedure. How many iterations does each version take? What is the earliest iteration you find the discrepancy?

**Comment by HehnLukas** [comment]
The discrepancy starts at the first iteration. The old version takes 27 macro iterations, and arrives at the correct result.  The new version only takes 15 iterations. As I mentioned, the old version gets close to the convergence criteria near the incorrect result from the new version, but manages to move past it. I suppose the changed initial guess for the UHF might lead to a slight change in orbitals in the UHF result, despite reaching the same energies? And this change is just the difference between getting stuck on the energy gradient plateau or not?
Here is the entire CASSCF output for each:

Old (1.6.6):
CASCI E = -1260.6149875982  S^2 = 8.7500000
Set conv_tol_grad to 0.000316228
macro iter 1 (21 JK  4 micro), CASSCF E = -1260.6230589926  dE = -0.0080713944  S^2 = 8.7500000
               |grad[o]|=0.182  |grad[c]|= 0.03036148034582199  |ddm|=0.00985
macro iter 2 (21 JK  4 micro), CASSCF E = -1260.63264320316  dE = -0.0095842106  S^2 = 8.7500000
               |grad[o]|=0.0846  |grad[c]|= 0.02432924428991468  |ddm|=0.00405
macro iter 3 (21 JK  4 micro), CASSCF E = -1260.63779140592  dE = -0.0051482028  S^2 = 8.7500000
               |grad[o]|=0.0381  |grad[c]|= 0.008664788644685593  |ddm|=0.000585
macro iter 4 (19 JK  4 micro), CASSCF E = -1260.6389241838  dE = -0.0011327779  S^2 = 8.7500000
               |grad[o]|=0.0141  |grad[c]|= 0.009877089053069277  |ddm|=0.00101
macro iter 5 (21 JK  4 micro), CASSCF E = -1260.64288962231  dE = -0.0039654385  S^2 = 8.7500000
               |grad[o]|=0.00238  |grad[c]|= 0.03764896965491646  |ddm|=0.00288
macro iter 6 (21 JK  4 micro), CASSCF E = -1260.64689163615  dE = -0.0040020138  S^2 = 8.7500000
               |grad[o]|=0.00701  |grad[c]|= 0.02806660194845578  |ddm|=0.0017
macro iter 7 (15 JK  4 micro), CASSCF E = -1260.64795262275  dE = -0.0010609866  S^2 = 8.7500000
               |grad[o]|=0.00303  |grad[c]|= 0.02285268891908047  |ddm|=0.00043
macro iter 8 (16 JK  4 micro), CASSCF E = -1260.6501477152  dE = -0.0021950924  S^2 = 8.7500000
               |grad[o]|=0.00278  |grad[c]|= 0.039049066956228035  |ddm|=0.00207
macro iter 9 (21 JK  4 micro), CASSCF E = -1260.65401005108  dE = -0.0038623359  S^2 = 8.7500000
               |grad[o]|=0.00399  |grad[c]|= 0.04807491890313109  |ddm|=0.00287
macro iter 10 (20 JK  4 micro), CASSCF E = -1260.65657020584  dE = -0.0025601548  S^2 = 8.7500000
               |grad[o]|=0.00488  |grad[c]|= 0.03542342722105583  |ddm|=0.00153
macro iter 11 (17 JK  4 micro), CASSCF E = -1260.65684844557  dE = -0.00027823973  S^2 = 8.7500000
               |grad[o]|=0.00219  |grad[c]|= 0.005588977977353016  |ddm|=0.000747
macro iter 12 (10 JK  2 micro), CASSCF E = -1260.65684999807  dE = -1.5524997e-06  S^2 = 8.7500000
               |grad[o]|=0.000231  |grad[c]|= 0.001180119546604894  |ddm|=6.98e-05
macro iter 13 (5 JK  1 micro), CASSCF E = -1260.65685044267  dE = -4.4460648e-07  S^2 = 8.7500000
               |grad[o]|=7.21e-05  |grad[c]|= 0.0012773565875196082  |ddm|=2.13e-05
macro iter 14 (4 JK  1 micro), CASSCF E = -1260.6568569472  dE = -6.5045244e-06  S^2 = 8.7500000
               |grad[o]|=8.13e-05  |grad[c]|= 0.005275926199960345  |ddm|=1.89e-05
macro iter 15 (6 JK  2 micro), CASSCF E = -1260.65699767054  dE = -0.00014072334  S^2 = 8.7500000
               |grad[o]|=0.000365  |grad[c]|= 0.004841471672782884  |ddm|=8.46e-05
macro iter 16 (21 JK  4 micro), CASSCF E = -1260.66120258425  dE = -0.0042049137  S^2 = 8.7500000
               |grad[o]|=0.00171  |grad[c]|= 0.033865371076891616  |ddm|=0.000981
macro iter 17 (21 JK  4 micro), CASSCF E = -1260.66608943373  dE = -0.0048868495  S^2 = 8.7500000
               |grad[o]|=0.00687  |grad[c]|= 0.02227783530433245  |ddm|=0.00139
macro iter 18 (20 JK  4 micro), CASSCF E = -1260.66797425497  dE = -0.0018848212  S^2 = 8.7500000
               |grad[o]|=0.00508  |grad[c]|= 0.01757669654838406  |ddm|=0.00115
macro iter 19 (16 JK  4 micro), CASSCF E = -1260.66802093246  dE = -4.6677491e-05  S^2 = 8.7500000
               |grad[o]|=0.000746  |grad[c]|= 0.0038373642556216586  |ddm|=0.000138
macro iter 20 (4 JK  1 micro), CASSCF E = -1260.66802267079  dE = -1.7383284e-06  S^2 = 8.7500000
               |grad[o]|=0.000125  |grad[c]|= 0.00237814992183392  |ddm|=6.45e-06
macro iter 21 (3 JK  1 micro), CASSCF E = -1260.66802376963  dE = -1.0988413e-06  S^2 = 8.7500000
               |grad[o]|=0.000104  |grad[c]|= 0.0018954749648721762  |ddm|=5.22e-06
macro iter 22 (3 JK  1 micro), CASSCF E = -1260.66802447273  dE = -7.0309716e-07  S^2 = 8.7500000
               |grad[o]|=7.91e-05  |grad[c]|= 0.0015195030428667917  |ddm|=4.28e-06
macro iter 23 (3 JK  1 micro), CASSCF E = -1260.66802492837  dE = -4.5564161e-07  S^2 = 8.7500000
               |grad[o]|=6.28e-05  |grad[c]|= 0.0012261772361484781  |ddm|=3.53e-06
macro iter 24 (3 JK  1 micro), CASSCF E = -1260.66802522783  dE = -2.99455e-07  S^2 = 8.7500000
               |grad[o]|=5.09e-05  |grad[c]|= 0.0009968202979168208  |ddm|=2.94e-06
macro iter 25 (3 JK  1 micro), CASSCF E = -1260.66802542777  dE = -1.999399e-07  S^2 = 8.7500000
               |grad[o]|=4.15e-05  |grad[c]|= 0.0008172416655599634  |ddm|=2.48e-06
macro iter 26 (3 JK  1 micro), CASSCF E = -1260.66802556375  dE = -1.3598924e-07  S^2 = 8.7500000
               |grad[o]|=3.42e-05  |grad[c]|= 0.000676787178512065  |ddm|=2.12e-06
macro iter 27 (1 JK  1 micro), CASSCF E = -1260.66802556375  dE = -4.5474735e-13  S^2 = 8.7500000
               |grad[o]|=2.85e-05  |grad[c]|= 1.6468224239433465e-06  |ddm|=1.24e-08
1-step CASSCF converged in 27 macro (339 JK 74 micro) steps
CASSCF canonicalization
Density matrix diagonal elements [1.99428267e+00 1.99428622e+00 1.99429792e+00 1.00135835e+00
 1.00166460e+00 1.00136256e+00 1.00233772e+00 1.00187848e+00
 1.90385231e-03 2.23224536e-03 2.19372069e-03 2.20166570e-03]
CASSCF energy = -1260.66802556375
CASCI E = -1260.66802556375  E(CI) = -87.9092283645355  S^2 = 8.7500000


New (1.7.5):
CASCI E = -1260.61498757866  S^2 = 8.7500000
Set conv_tol_grad to 0.000316228
macro iter 1 (21 JK  4 micro), CASSCF E = -1260.62258817908  dE = -0.0076006004  S^2 = 8.7500000
               |grad[o]|=0.182  |grad[c]|= 0.02866698295704086  |ddm|=0.00955
macro iter 2 (21 JK  4 micro), CASSCF E = -1260.6317083363  dE = -0.0091201572  S^2 = 8.7500000
               |grad[o]|=0.0882  |grad[c]|= 0.023933720153686878  |ddm|=0.00422
macro iter 3 (21 JK  4 micro), CASSCF E = -1260.63755820962  dE = -0.0058498733  S^2 = 8.7500000
               |grad[o]|=0.0419  |grad[c]|= 0.010071480594901169  |ddm|=0.000783
macro iter 4 (18 JK  4 micro), CASSCF E = -1260.63869128748  dE = -0.0011330779  S^2 = 8.7500000
               |grad[o]|=0.0158  |grad[c]|= 0.0039762232222423435  |ddm|=0.00101
macro iter 5 (19 JK  4 micro), CASSCF E = -1260.64038590752  dE = -0.00169462  S^2 = 8.7500000
               |grad[o]|=0.000786  |grad[c]|= 0.03354157219541263  |ddm|=0.00187
macro iter 6 (21 JK  4 micro), CASSCF E = -1260.64433151585  dE = -0.0039456083  S^2 = 8.7500000
               |grad[o]|=0.0057  |grad[c]|= 0.027305866253606502  |ddm|=0.00197
macro iter 7 (21 JK  4 micro), CASSCF E = -1260.64711662142  dE = -0.0027851056  S^2 = 8.7500000
               |grad[o]|=0.00629  |grad[c]|= 0.022619755399085548  |ddm|=0.00108
macro iter 8 (16 JK  4 micro), CASSCF E = -1260.64810813246  dE = -0.00099151104  S^2 = 8.7500000
               |grad[o]|=0.0024  |grad[c]|= 0.017998043639900655  |ddm|=0.0006
macro iter 9 (20 JK  4 micro), CASSCF E = -1260.65037048389  dE = -0.0022623514  S^2 = 8.7500000
               |grad[o]|=0.00288  |grad[c]|= 0.038069040630025926  |ddm|=0.00213
macro iter 10 (21 JK  4 micro), CASSCF E = -1260.65325679035  dE = -0.0028863065  S^2 = 8.7500000
               |grad[o]|=0.00407  |grad[c]|= 0.03608076575556534  |ddm|=0.00223
macro iter 11 (21 JK  4 micro), CASSCF E = -1260.65572987357  dE = -0.0024730832  S^2 = 8.7500000
               |grad[o]|=0.00448  |grad[c]|= 0.029448075692723247  |ddm|=0.00145
macro iter 12 (20 JK  4 micro), CASSCF E = -1260.65681827756  dE = -0.001088404  S^2 = 8.7500000
               |grad[o]|=0.00319  |grad[c]|= 0.02140682507387789  |ddm|=0.000943
macro iter 13 (11 JK  3 micro), CASSCF E = -1260.65685155113  dE = -3.3273575e-05  S^2 = 8.7500000
               |grad[o]|=0.000818  |grad[c]|= 0.0018355224280295543  |ddm|=0.000283
macro iter 14 (5 JK  1 micro), CASSCF E = -1260.65685186085  dE = -3.0972387e-07  S^2 = 8.7500000
               |grad[o]|=0.000114  |grad[c]|= 0.0009164512643802021  |ddm|=1.7e-05
macro iter 15 (4 JK  1 micro), CASSCF E = -1260.6568519401  dE = -7.9244046e-08  S^2 = 8.7500000
               |grad[o]|=4.96e-05  |grad[c]|= 0.0004664053789121825  |ddm|=6.81e-06
1-step CASSCF converged in 15 macro (260 JK 53 micro) steps
CASSCF canonicalization
Density matrix diagonal elements [1.99477088e+00 1.99477093e+00 1.99392427e+00 1.00262441e+00
 1.00262441e+00 1.00170802e+00 1.00170802e+00 1.00098957e+00
 4.82790728e-04 2.19682699e-03 2.09991858e-03 2.09994626e-03]
CASSCF energy = -1260.6568519401
CASCI E = -1260.6568519401  E(CI) = -87.975145412775  S^2 = 8.7500000

**Comment by ssh2** [comment]
@HehnLukas Have you tried running these calculations multiple times? We have observed that the CASSCF code in PySCF sometimes produces nondeterministic results. What you are seeing may not be related to a particular version, but may be a result of such nondeterministic behavior. 

My student is about to post a separate GitHub issue with a simple example of such reproducible nondeterministic behavior of the CASSCF code. This may or may not be linked to the problem that you're seeing, therefore we decided to post this as separate issue.

**Comment by ssh2** [comment]
See issue #912

**Comment by HehnLukas** [comment]
> @HehnLukas Have you tried running these calculations multiple times? We have observed that the CASSCF code in PySCF sometimes produces nondeterministic results. What you are seeing may not be related to a particular version, but may be a result of such nondeterministic behavior.
> 
> My student is about to post a separate GitHub issue with a simple example of such reproducible nondeterministic behavior of the CASSCF code. This may or may not be linked to the problem that you're seeing, therefore we decided to post this as separate issue.

I don't think this is the same problem for me, I ran it 3 times on both versions and each versions result was completely consistent, the results files were completely identical down to the last decimal point.

**Comment by HehnLukas** [comment]
I'm sorry for the delayed response, but it seems to not be related to the Problem in issue #912, as I now did 9 repetitions with each version and the result remained the same

**Comment by ssh2** [comment]
Have you tried starting from different guess orbitals? Sometimes using orbitals from a different method (like DFT) or a different reference electronic state helps. Following the discussion in #912 , it is possible that due to small differences in two versions the optimization paths of the two calculations diverge leading to two different results.

**Comment by bogdanoff** [comment]
@HehnLukas, i'd like to look closer into this problem. Ccould you please share your input?

**Comment by HehnLukas** [comment]
> @HehnLukas, i'd like to look closer into this problem. Ccould you please share your input?

Sorry, this is quite delayed. I have since moved on, and I assume it is just based on a somewhat different initial guess leading to a convergence at an energy plateau in the newer version, which by chance gets avoided in the old version. If you want to look into it further, my code is below, but I don't think it is necessarily worthwhile, and I have realised since that using an UHF calculation as a reference for a CAS is not particularily useful, as the beta mo_coeff just get dropped.

`from pyscf.scf import uhf,rhf,rohf
from pyscf import mcscf
from molecularData import Geometry
from PyGer import pyger
from pyscf.tools import mo_mapping

system = 'Fe'
geom = {'Fe' : Geometry()}

energy = {}

print('Calculation for {0}'.format(system))

mol = geom[system].mol


# SCF calculation
mf = uhf.UHF(mol)
mf.kernel()
E_SCF = mf.e_tot
    
energy[(system, 'SCF')] = E_SCF


# CASSCF
electrons = 11
orbitals = 12
mc = mcscf.CASSCF(mf,orbitals,electrons)
print(str(mc))
mc.kernel()`

with this code for the geometry (from molecularData):

`from abc import ABC, abstractmethod

from pyscf.gto import Mole

class _Geometry(ABC):
    """
    Abstract base class to handle functionality.
    """

    def __init__(self, basis, charge, spin, verbose, output):
        """
        Keywords:

        basis   (str) : PySCF basis string (e.g. 'def2-TZVP')
        charge  (int) : Total charge
        spin    (int) : Number of unpaired electrons, as per PySCF convention!
        verbose (int) : PySCF verbosity
        output  (str) : optional output file
        """
        mol = Mole()
        mol.atom = self._getAtom()
        mol.basis = basis
        mol.charge = charge
        mol.spin = spin
        mol.verbose = verbose
        if output is not None:
            mol.output = output
        mol.build()
        self.mol = mol
    
    @abstractmethod
    def _getAtom(self):
        """
        Keywords : None

        Returns (str) : atomic positions
        """
        return ''

class Geometry(_Geometry):

    def __init__(self, basis='def2-TZVP', charge=0, spin=0,
                 verbose=4, output=None):
        """
        Keywords:

        basis   (str)    : PySCF basis string (e.g. 'def2-TZVP')
        charge  (int)    : Total charge
        spin    (int)    : Number of unpaired electrons, as per PySCF convention!
        verbose (int)    : PySCF verbosity
        output  (str)    : optional output file
        """
        charge = 3
        spin = 5 
        super().__init__(basis, charge, spin, verbose, output)

    def _getAtom(self):
        return '''
        Fe    0.0000000    0.0000000    0.0000000
	'''`
