### ISSUE TITLE
Electron density betwenn a couple of molecular orbitals

### ISSUE THREAD

**Issue by DanielBajac** [pyscf/pyscf#909]
Hello everybody,

There is a way to calculate de electron density (rho)  between two MOs that one choose?
being 
\rho(r) = \psi_a^*(r)\psi_a(r) = \sum_i \sum_j C_{i,a}C_{j,a} \phi^*_i(r)\phi_j(r)

I know how to get the C_{i,a}, but not the corresponding \phi.

**Comment by tberkel** [comment]
One option would be to use tools.cubegen.  The \rho(r) that you want is
just the elementwise product of the cube formats of the individual MOs.

**Comment by DanielBajac** [comment]
Thanks for your answer. 
I've never use the cubegen file, but, in the example:

from pyscf import gto, scf
from pyscf.tools import cubegen
mol = gto.M(atom='''
            O 0.0000000, 0.000000, 0.00000000
            H 0.761561 , 0.478993, 0.00000000
            H -0.761561, 0.478993, 0.00000000''', basis='6-31g*')
mf = scf.RHF(mol).run()
cubegen.density(mol, 'h2o_den.cube', mf.make_rdm1())

If I use a particulas MO, por example: mf.mo_coeff[:,[2]], I have problems with the rdm1. 

IndexError: boolean index did not match indexed array along dimension 1; dimension is 1 but corresponding boolean dimension is 18.

How can I choose the MO I want?

**Comment by tberkel** [comment]
I’m suggesting to use orbital() not density(). You could create two cube
files for your two orbitals and then multiply them together by yourself
with another script. Or maybe you could modify/write your own functions
based on the code in cubegen to do this all at once.

**Comment by DanielBajac** [comment]
Thanks a lot Mr. Berkelbach. 
Your suggestions was very helpful
