### ISSUE TITLE
pip install error for windows 10

### ISSUE THREAD

**Issue by JoJofun** [pyscf/pyscf#910]
I am unable to install using pip on windows 10 and I get the following error when attempting to install
`ERROR: The tar file (C:\Users\USERNAME\AppData\Local\Temp\pip-unpack-z0rob7f6\pyscf-1.7.6.tar.gz) has a file (C:\Users\USERNAME\AppData\Local\Temp\pip-install-heyw42u9\pyscf_ad55fed7ff0e4999a16a50ee3a0ebca2\pyscf/agf2/aux.py) trying to install outside target directory (C:\Users\USERNAME\AppData\Local\Temp\pip-install-heyw42u9\pyscf_ad55fed7ff0e4999a16a50ee3a0ebca2)`
its something to do with aux.py
sorry im still new to github

**Comment by xubwa** [comment]
I don't think pyscf supports windows. You can try to do pip install on wsl (windows subsystem on linux) which usually works fine or just use a linux machine.

**Comment by hebrewsnabla** [comment]
Native windows is not supported. See #750
