### ISSUE TITLE
k-points calculation with custom GDF object

### ISSUE THREAD

**Issue by mariomotta** [pyscf/pyscf#913]
Greetings,

I would like to please ask a question regarding k-points calculations: I need to perform 
a calculation with k points, and with a custom GDF object. What I have is three-center 
integral, generated externally and stored as list of lists,
J = [[T[k][q] k in kpts] q in kpts]
where T[k][q] is a rank-3 tensor, of shape (aux,nao,nao)
I would like to save this list of lists to an h5 file, and use it to populate a GDF object, e.g.
a_gdf = df.GDF(cell)
a_gdf._cderi = 'myfile.h5'
Can anyone help me to achieve this goal?

**Comment by zhcui** [comment]
Hi Mario,

GDF object has two datasets, 'j3c', 'j3c-kptij'.
To do so, you probably need to first generate kij list:
```
from pyscf.pbc.lib.kpts_helper import unique, member
uniq_idx = unique(kpts)[1]
kpts = np.asarray(kpts)[uniq_idx]
kptij_lst = [(ki, kpts[j]) for i, ki in enumerate(kpts) for j in range(i+1)]
kptij_lst = np.asarray(kptij_lst)
f[''j3c-kptij'] = kptij_lst
```
Then 
```
for idx, (ki, kj) in enumerate(kptij_lst):
    i = member(ki, kpts)
    j = member(kj, kpts)
    f['j3c']['%d'%idx]['0'] = np.array(J[i][j])
```

Best,
Zhihao
