### ISSUE TITLE
Is the number of negative definite j3c elements in 2D systems independent of k-points?

### ISSUE THREAD

**Issue by Majokux** [pyscf/pyscf#914]
So for 2D periodic systems, the GDF decomposition leads to positive definite "j3c" and negative "j3c-" 3c-integrals.
First, for my understanding why are there negative definite elements? This corresponds to an attractive electron-electron interaction, correct?

To my actual question, if I access the 3c integrals via `sr_loop`, I first get the positive parts, then the negative.
Lets call the number of auxiliary basis functions corresponding to a positive sign npos and with negative sign nneg, such that naux =npos+nneg.
My question is, is it guaranteed that nneg is the same, for every pair of k-points ki,kj, which I put into `sr_loop`?
I believe naux itself can be k-points-pair dependent, due to linear dependence treatment, but is it expected to only affect npos?

Many thanks!

**Comment by sunqm** [comment]
Yes, it is always 1 for regular Coulomb kernel regardless of the k points. Here is the source of the negative value. https://github.com/pyscf/pyscf/blob/master/pyscf/pbc/tools/pbc.py#L330  . Only one element in G0_idx is set to negative value.

**Comment by Majokux** [comment]
This was helpful, thanks!
