### ISSUE TITLE
C60 benchmark: density fit HF slow

### ISSUE THREAD

**Issue by pedersor** [pyscf/pyscf#917]
Hi PySCF developers,

I am having trouble running HF with density fitting on the C60 benchmark (2-benchmark/c60.py). See my input/output attached. I am using a 16 core system and the recommend max_memory=40gb. I am using (freshly built) pyscf version 2.0.0a.

According to the docs (http://pyscf.org/pyscf/overview.html#benchmark), the 6-31G** calculation should only take ~317sec whereas each iteration is taking ~500+ sec for me. 
[c60_out.txt](https://github.com/pyscf/pyscf/files/6353112/c60_out.txt)

Thanks!
Ryan

**Comment by jamesETsmith** [comment]
Hi @pedersor, what compiler and BLAS distribution are you using? I'd be surprised if those really made up for the time discrepancy you're seeing, but it's a place to start.

**Comment by Majokux** [comment]
Your cpuinfo doesn't see your CPU model number, are you running in some kind of virtual environment?
Do you know your CPU or can post the output of `cat /proc/cpuinfo` (block for first core is enough)

For what it's worth, running the benchmark on a Xeon E5-2697 v4, which is  faster than the original benchmark CPU,
I get a initialization time of 271s and ~44s iterations for a total of 761s ... Has there been some performance regression?

**Comment by pedersor** [comment]
Hi @jamesETsmith, you were right it seems the blas distribution was the problem. I was not careful and the standard cblas library was being used (which clearly has terrible performance here!). Switching to openblas I obtain similar results to @Majokux (whose cpu is a bit better than mine), i.e. ~49s per iteration for a total of 836s.   

I agree though, the benchmark result still seems a bit distant.

**Comment by Majokux** [comment]
I think it may be good to keep this open, since there seems to have been a significant performance regression.
It might just be some tolerances which were tightened between version, but would be good to learn more.

**Comment by pedersor** [comment]
With direct_scf=False I get ~14s per iteration and ~437s total which seems more consistent with the benchmark results. 

It seems that direct_scf=True is the default even if enough memory is allotted (e.g. 40gb is plenty to store eris in memory for 6-31G** basis). Perhaps this wasn't always the case?

**Comment by sunqm** [comment]
The benchmark was generated with integral library qcint https://github.com/sunqm/qcint

**Comment by jamesETsmith** [comment]
For instructions on how to build PySCF from source with `qcint` instead of `libcint` see the docs [here](https://pyscf.org/install.html#using-optimized-integral-library).
