### ISSUE TITLE
What paper is the Ewald summation background is the cell.py file referencing? 

### ISSUE THREAD

**Issue by xmax1** [pyscf/pyscf#918]
https://github.com/pyscf/pyscf/blob/1de8c145abb3e1a7392df9118e8062e6fe6bde00/pyscf/pbc/gto/cell.py#L1010

For example, Line 733, 'Formulation of Martin, App. F2.' ... A reference for this paper would be really helpful! 

Thanks.

**Comment by xmax1** [comment]
Also this isn't really an issue, but I couldn't find the discussion section.

**Comment by tberkel** [comment]
"Martin" is referencing the book "Electronic Structure" by Richard Martin.
Elsewhere in the pbc code you may find references to "M&H" which is the
book "Ab initio molecular dynamics" by Marx and Hutter.

**Comment by xmax1** [comment]
Thanks!
