### ISSUE TITLE
density fit method has large I/O, and the speed with density fit is more than twice as slow as without density fit

### ISSUE THREAD

**Issue by leebo-2020** [pyscf/pyscf#924]
Dear developers,

when I use density fit method, I found large I/O and the temporary file up to 3.0G, this is normal?  the version of pyscf is 2.0a and the version qcint is v4.1.3. Further more, the speed with density fit is more than twice as slow as without density fit, I don't know what happened.

the input:

from time import time
from pyscf import gto, scf
mol = gto.Mole()
mol.atom = '''
O    0.000000000    0.000000000    0.000000000
H    0.960000000    0.000000000    0.000000000
H   -0.320454585    0.904935831    0.000000000
O    2.860000000    0.000000000    0.000000000
H    3.820000000    0.000000000    0.000000000
H    2.539545415    0.904935831    0.000000000
O    5.720000000    0.000000000    0.000000000
H    6.680000000    0.000000000    0.000000000
H    5.399545415    0.904935831    0.000000000
O    8.580000000    0.000000000    0.000000000
H    9.540000000    0.000000000    0.000000000
H    8.259545415    0.904935831    0.000000000
O   11.440000000    0.000000000    0.000000000
H   12.400000000    0.000000000    0.000000000
H   11.119545415    0.904935831    0.000000000
O   14.300000000    0.000000000    0.000000000
H   15.260000000    0.000000000    0.000000000
H   13.979545415    0.904935831    0.000000000
O   17.160000000    0.000000000    0.000000000
H   18.120000000    0.000000000    0.000000000
H   16.839545415    0.904935831    0.000000000
O   20.020000000    0.000000000    0.000000000
H   20.980000000    0.000000000    0.000000000
H   19.699545415    0.904935831    0.000000000
O   22.880000000    0.000000000    0.000000000
H   23.840000000    0.000000000    0.000000000
H   22.559545415    0.904935831    0.000000000
O   25.740000000    0.000000000    0.000000000
H   26.700000000    0.000000000    0.000000000
H   25.419545415    0.904935831    0.000000000
O   28.600000000    0.000000000    0.000000000
H   29.560000000    0.000000000    0.000000000
H   28.279545415    0.904935831    0.000000000
O   31.460000000    0.000000000    0.000000000
H   32.420000000    0.000000000    0.000000000
H   31.139545415    0.904935831    0.000000000
O   34.320000000    0.000000000    0.000000000
H   35.280000000    0.000000000    0.000000000
H   33.999545415    0.904935831    0.000000000
O   37.180000000    0.000000000    0.000000000
H   38.140000000    0.000000000    0.000000000
H   36.859545415    0.904935831    0.000000000
O   40.040000000    0.000000000    0.000000000
H   41.000000000    0.000000000    0.000000000
H   39.719545415    0.904935831    0.000000000
O   42.900000000    0.000000000    0.000000000
H   43.860000000    0.000000000    0.000000000
H   42.579545415    0.904935831    0.000000000
O   45.760000000    0.000000000    0.000000000
H   46.720000000    0.000000000    0.000000000
H   45.439545415    0.904935831    0.000000000
O   48.620000000    0.000000000    0.000000000
H   49.580000000    0.000000000    0.000000000
H   48.299545415    0.904935831    0.000000000
O   51.480000000    0.000000000    0.000000000
H   52.440000000    0.000000000    0.000000000
H   51.159545415    0.904935831    0.000000000
O   54.340000000    0.000000000    0.000000000
H   55.300000000    0.000000000    0.000000000
H   54.019545415    0.904935831    0.000000000
O   57.200000000    0.000000000    0.000000000
H   58.160000000    0.000000000    0.000000000
H   56.879545415    0.904935831    0.000000000
O   60.060000000    0.000000000    0.000000000
H   61.020000000    0.000000000    0.000000000
H   59.739545415    0.904935831    0.000000000
O   62.920000000    0.000000000    0.000000000
H   63.880000000    0.000000000    0.000000000
H   62.599545415    0.904935831    0.000000000
O   65.780000000    0.000000000    0.000000000
H   66.740000000    0.000000000    0.000000000
H   65.459545415    0.904935831    0.000000000
O   68.640000000    0.000000000    0.000000000
H   69.600000000    0.000000000    0.000000000
H   68.319545415    0.904935831    0.000000000
O   71.500000000    0.000000000    0.000000000
H   72.460000000    0.000000000    0.000000000
H   71.179545415    0.904935831    0.000000000
O   74.360000000    0.000000000    0.000000000
H   75.320000000    0.000000000    0.000000000
H   74.039545415    0.904935831    0.000000000
O   77.220000000    0.000000000    0.000000000
H   78.180000000    0.000000000    0.000000000
H   76.899545415    0.904935831    0.000000000
O   80.080000000    0.000000000    0.000000000
H   81.040000000    0.000000000    0.000000000
H   79.759545415    0.904935831    0.000000000
O   82.940000000    0.000000000    0.000000000
H   83.900000000    0.000000000    0.000000000
H   82.619545415    0.904935831    0.000000000
O   85.800000000    0.000000000    0.000000000
H   86.760000000    0.000000000    0.000000000
H   85.479545415    0.904935831    0.000000000
O   88.660000000    0.000000000    0.000000000
H   89.620000000    0.000000000    0.000000000
H   88.339545415    0.904935831    0.000000000
O   91.520000000    0.000000000    0.000000000
H   92.480000000    0.000000000    0.000000000
H   91.199545415    0.904935831    0.000000000
O   94.380000000    0.000000000    0.000000000
H   95.340000000    0.000000000    0.000000000
H   94.059545415    0.904935831    0.000000000
O   97.240000000    0.000000000    0.000000000
H   98.200000000    0.000000000    0.000000000
H   96.919545415    0.904935831    0.000000000
O  100.100000000    0.000000000    0.000000000
H  101.060000000    0.000000000    0.000000000
H   99.779545415    0.904935831    0.000000000
O  102.960000000    0.000000000    0.000000000
H  103.920000000    0.000000000    0.000000000
H  102.639545415    0.904935831    0.000000000
O  105.820000000    0.000000000    0.000000000
H  106.780000000    0.000000000    0.000000000
H  105.499545415    0.904935831    0.000000000
O  108.680000000    0.000000000    0.000000000
H  109.640000000    0.000000000    0.000000000
H  108.359545415    0.904935831    0.000000000
O  111.540000000    0.000000000    0.000000000
H  112.500000000    0.000000000    0.000000000
H  111.219545415    0.904935831    0.000000000
'''
mol.basis = '6-31g'
mol.build()
mf = scf.RHF(mol).density_fit()
mf.with_df.auxbasis = 'cc-pvdz-jkfit'
mf.with_df.build()
mf.conv_tol = 1.0e-6
#case-1 for DF
t1 = time()
mf.kernel()
t2 = time()
print('total time with DF with mf.with_df.build()')
print(t2 - t1)
#case-2 without DF
mf.with_df = False
t3 = time()
mf.kernel()
t4 = time()
print('total time without DF')
print(t4 - t3)

output :
total time with DF with mf.with_df.build()
489.68197679519653

total time without DF
181.9071900844574

thanks

**Comment by xubwa** [comment]
That should be normal, the 3gb tmp file should be storing the 3-index integrals.

**Comment by leebo-2020** [comment]
> 
> 
> That should be normal, the 3gb tmp file should be storing the 3-index integrals.

For density fit method, the large tmp file means that 2e-integrals not direct method but disk method, right? if it is disk, how to set direct?

**Comment by xubwa** [comment]
The stored quantity is the 3-index integral <ij|L) instead of the full 2e-integral <ij|kl>, thus it is a much smaller quantity and is usually affordable. I don't have any impression that direct df is in pyscf.

**Comment by leebo-2020** [comment]
> 
> 
> The stored quantity is the 3-index integral <ij|L) instead of the full 2e-integral <ij|kl>, thus it is a much smaller quantity and is usually affordable. I don't have any impression that direct df is in pyscf.

if switch off density fit, the tmp file is very small

**Comment by xubwa** [comment]
In your second run where you say you switch off density fitting, you are actually still using density fitting, you saved the time of constructing the 3-index integrals. But it shouldn't take that long, I ran that calculation and two run costs roughly the same time, perhaps your disk has very limited space or on some cluster, the tmp directory has high-performance io while the home directory doesn't. I also tried a conventional RHF calculation, and I do observe that HF is a few times faster than DFHF by a couple of times. DFHF costs 142.61s and converges with 7 iterations, HF costs 38.25s and converges with 9 iterations. If j is computed with DF and K is computed using conventional method, then it costs 31.28s and converges with 7 iterations. I guess it probably implies that the df-k is not quite efficient while df-j is probably fine.

**Comment by leebo-2020** [comment]
> 
> 
> In your second run where you say you switch off density fitting, you are actually still using density fitting, you saved the time of constructing the 3-index integrals. But it shouldn't take that long, I ran that calculation and two run costs roughly the same time, perhaps your disk has very limited space or on some cluster, the tmp directory has high-performance io while the home directory doesn't. I also tried a conventional RHF calculation, and I do observe that HF is a few times faster than DFHF by a couple of times. DFHF costs 142.61s and converges with 7 iterations, HF costs 38.25s and converges with 9 iterations. If j is computed with DF and K is computed using conventional method, then it costs 31.28s and converges with 7 iterations. I guess it probably implies that the df-k is not quite efficient while df-j is probably fine.

sorry, I missed mf.with_df = False

**Comment by ajz34** [comment]
I'm new to efficiently coding in python and is dealing with RI related codes, so I reach this post :joy:
I guess if set `mol.max_memory = 6*1024` before `mol.build()`, there could be virtually no disk-I/O for this system. But still, maybe 12GB spare memory should be given to run this job fully-incore. So make a comparason of I/O-free against disk-I/O is probably not difficult, if enough memory is available.

> the temporary file up to 3.0G

Maybe about 4.7 GB? This could be approximated by 520**2 * 4640 * 8 / 2 / 1024**3.

> I found large I/O

I guess time wasted because of I/O in PySCF somehow depends on `h5py`. I guess writing to disk is slow (however this is done when initializing `mf.with_df`, not in SCF runs), but reading is fast. My PC could process the whole Cholesky ERIs with just 1 second (my SATA disk bandwidth 6GB/s). So maybe 9 iterations means 9 sec reading Cholesky ERIs.

I agree with most conculsions of xubwa. In my understanding, constructing 3c2e-integrals are formally O(n^2*naux) which could be fast; however, after integral generation, Cholesky ERIs are constructed (formally O(n^2*naux^2)), and this takes some time before SCF iterations. RI exchange integrals (df-k) formally costs O(occ*n^2*naux) in SCF, or O(n^3*naux) in CP-SCF; so df-k wouldn't gain enough speed up if basis is small (such as 6-31G) in SCF, and even worse in CP-SCF. I guess that's why [RIJONX method](https://www.sciencedirect.com/science/article/pii/S0009261402010539) (RI-J and conventional K) exists.

So I agree that I/O deficiency of program is not the main problem, and instead df-k method itself.

What I'm not sure/understand at this point is that
- Is there anything to do with attribute `mf.opt` (if `mf` is conventional) or `mf.with_df._vjopt` (if `mf` is density fitting without df-k)? This specific system is long chain of waters, so importance of integral screening may be the dominant contribution to speedup than that of RI. If df-k would be evaluated, there's probably no integral screening.
- `pyscf.sgx` module handles df-k in RIJCOSX, which is principle O(N^3), one order faster than RI-JK or conventional JK. But in my testing it's somehow slower ...

**Comment by xubwa** [comment]
@ajz34 the df class secretly has its own max memory, which is 2gb. You can see that at the beginning of df/incore.py and df/outcore.py. The IO free calculation has almost no difference compared to disk calculation if what I did actually make it do calculations incore. For the sgx module, you can see discussions on issue #865. The default settings of sgx in pyscf is quite conservative. And optimizations are also in progress I guess.
@leebo-2020 Sorry, I didn't notice you requested on how to turn only dfj on. You just need to turn only_dfj on like this.
```
mf = scf.RHF(mol).density_fit()
mf.only_dfj=True
```

**Comment by verena-neufeld** [comment]
@leebo-2020 , thanks for posting this issue. Has it been resolved?

**Comment by sunqm** [comment]
df code should read the max_memory setting from Mole object in some ways. I checked the df module, it is passed to df.incore and outcore function. If it is limited by 2GB in other places, that looks like a bug. However, in most cases, the max_memory setting will not give noticeable impacts on performance. We can leave it as it is.
