### ISSUE TITLE
web pages are non available anymore

### ISSUE THREAD

**Issue by aolykhin** [pyscf/pyscf#936]
Hi, 

I'm just curious what happened to the pyscf web pages?  Many of them that were available in the past are down now, for example, https://pyscf.org/pyscf/_modules/pyscf/tools/fcidump.html

Such pages still pop up when making pyscf related requests in a browser.

Best, 
Alex

**Comment by fishjojo** [comment]
it has been moved to here
https://pyscf.org/pyscf_api_docs/pyscf.tools.html#module-pyscf.tools.fcidump

**Comment by tberkel** [comment]
To add to Xing's reply: the new PySCF documentation has a structure that is
different from the old one.  The User Guide and Developer Guide are
completely new.  The API is based on automated documentation from
docstrings in the source code.  Some helpful documentation has been
temporarily lost from the website in this transition.  We hope to move the
information into the User Guide, Developer Guide, and API as appropriate,
over time.  In the meantime, that module information can still be found
here: https://github.com/pyscf/pyscf.github.io/tree/master/source/modules
.  In cases where these files show "automodule" commands, the same
information should be currently found in the API section of the new
documentation (such as the fcidump docs that you requested and Xing linked
you to).

**Comment by aolykhin** [comment]
Thank you for your reply, it's helpful
