### ISSUE TITLE
Is that possible to print out electron-nucleus attraction integrals for each nucleus?

### ISSUE THREAD

**Issue by Nellatur** [pyscf/pyscf#937]
Hi,

  I am wondering if it is possible to print out electron-nucleus attraction integrals for each nucleus. 

  From 
https://github.com/pyscf/pyscf.github.io/blob/master/examples/gto/20-ao_integrals.py
  it seems 
v = mol.intor('int1e_nuc')
  is the sum over all nuclei, i.e., 
< mu| \sum_c Z_c /|r - R_c| | nu>
  
  Is that possible to print 
< mu| Z_c /|r - R_c| | nu>, for each Z_c?

  Thank you very much!

**Comment by ajz34** [comment]
I guess following code should work (with `v_atom` stores integrals for each nucleus):
```python
v = mol.intor("int1e_nuc")
v_atom = np.empty((mol.natm, mol.nao, mol.nao))
for c in range(mol.natm):
    with mol.with_rinv_as_nucleus(c):  # temporarily set center of 1/r to the coordinate of atom c
        v_atom[c] = - mol.atom_charge(c) * mol.intor("int1e_rinv")  # attraction, so actually <μ|-Z_c/r|ν>
```
To validate sum of contributions from all nucleus equals to total `int1e_nuc`:
```python
np.allclose(v_atom.sum(axis=0), v)  # should print True
```

**Comment by susilehtola** [comment]
I just want to follow the discussion since this is pretty much exactly what is needed to implement #566 .

**Comment by Nellatur** [comment]
> 
> 
> I guess following code should work (with `v_atom` stores integrals for each nucleus):
> 
> ```python
> v = mol.intor("int1e_nuc")
> v_atom = np.empty((mol.natm, mol.nao, mol.nao))
> for c in range(mol.natm):
>     with mol.with_rinv_as_nucleus(c):  # temporarily set center of 1/r to the coordinate of atom c
>         v_atom[c] = - mol.atom_charge(c) * mol.intor("int1e_rinv")  # attraction, so actually <μ|-Z_c/r|ν>
> ```
> 
> To validate sum of contributions from all nucleus equals to total `int1e_nuc`:
> 
> ```python
> np.allclose(v_atom.sum(axis=0), v)  # should print True
> ```

Thank you very much! I checked by comparing with another method, namely using psi4 but use ghost atom for all other atoms except a single one, obtained consistent results within 10^-8 a.u..
