### ISSUE TITLE
Negative sign missing in hdiag of tdscf code?

### ISSUE THREAD

**Issue by proexcuse** [pyscf/pyscf#944]
Hi,

I'm curious if the definition of hdiag in gen_tdhf_operation function in pyscf/tdscf/uhf.py should be modified as follows. 
Original:
hdiag = numpy.hstack((hdiag.ravel(), hdiag.ravel())
Modified
hdiag = numpy.hstack((hdiag.ravel(), -hdiag.ravel())
(Additional negative sign corresponding to [[A B] [-B -A]]  casida equation)

Not sure if I understand the code correctly, but the convergence rate of davidson may change (I don't think the resulting excitation energy and xy changes because the davidson function checks the convergence anyways)
I'd appreciate it if someone could help.

**Comment by sunqm** [comment]
You are right. The sign of hdiag is wrong
