### ISSUE TITLE
Obtaining the Slater determinant of a HF calculation

### ISSUE THREAD

**Issue by n-gao** [pyscf/pyscf#946]
Hi,

I was wondering whether there is an option to retrieve the matrix of molecular orbitals (which is then reduced by a determinant).
From my understanding, I should be able to retrieve a NxN matrix for a specific N-electron system.

I thought the following code would result in the molecular orbital matrix of oxygen with a random electron configuration:
```python
import numpy as np
from pyscf import gto, scf

mol = gto.Mole(atom=[
  ['O', (0, 0, 0)],
], basis='sto-6g', unit='bohr', spin=0, charge=0)
mol.build()

mean_field = scf.RHF(mol)
mean_field.kernel()

electrons = np.random.randn(8, 3)

ao = mol.eval_gto('GTOval_sph', electrons)
mo = ao @ mean_field.mo_coeff
print(mo.shape)
```
Result:
```
(8, 5)
```

However, isn't the matrix supposed to be a NxN matrix? I don't quite understand where the 5 comes from.

Thank you!

**Comment by fishjojo** [comment]
`eval_gto` evaluates the AOs on a grid. What you computed is MOs evaluated on 8 grid points.

**Comment by n-gao** [comment]
What I want is a function to retrieve the molecular orbitals for a given electron configurations. So I want a function that takes a 3N dimensional input and returns a NxN matrix.

**Comment by susilehtola** [comment]
The molecular orbitals are stored in mo_coeff. There are N occupied orbitals, and K-N unoccupied orbitals if you use a basis set expansion with K linearly independent functions. The full matrix is K x K.

You only get N x N in the rare special case of a minimal basis set, for which the calculation is inaccurate.

Sampling the orbitals at N points does not tell you much about the wave function, because of the wave particle duality.

**Comment by n-gao** [comment]
I know that sampling the N points does not tell one a lot about the wave function. Though, HF is often used as starting point in neural network based QMC methods like [FermiNet](https://arxiv.org/abs/1909.02487) or [PauliNet](https://arxiv.org/pdf/1909.08423.pdf).
While both networks only deploy slater determinants for spin up and down separately. In practice, one should be able to construct a whole NxN slater determinant with a neural network. 
 
As far as I know, sto-6g is a minimal basis set? Why aren't the molecular orbitals NxN? Is there a way to obtain the 3N->NxN function?

**Comment by tberkel** [comment]
Do you just want the scalar value of the Slater determinant evaluated at
the positions of all electrons? Or do you really want the NxN matrix whose
determinant gives the wavefunction?

**Comment by n-gao** [comment]
I am interested in the actual NxN matrices of molecular orbitals.

**Comment by susilehtola** [comment]
```
import numpy as np
from pyscf import gto, scf

mol = gto.Mole(atom=[
  ['O', (0, 0, 0)],
], basis='sto-6g', unit='bohr', spin=0, charge=0)
mol.build()

mean_field = scf.RHF(mol)
mean_field.kernel()
print(mean_field.mo_coeff.shape)
```
`mo_coeff` is a 5x5 matrix.

STO-6G is 2s1p for oxygen. This gives 5 spatial orbitals, or 10 spin-orbitals. Oxygen has 8 electrons; this means that you have 2 spin-orbitals that will be unoccupied; however, the 8 occupied spin-orbitals (4 spin-up and 4 spin-down in the present calculation) are each expanded in terms of the 5 basis functions.

Minimal basis sets are unreliable even at the Hartree-Fock level of theory.

**Comment by tberkel** [comment]
He doesn’t want the matrix of MOs coefficients in the basis of AOs, but
rather the matrix (at a specified set of electron coordinates) whose
determinant gives the value of the N-electron wavefunction, i.e. the matrix
here:
https://wikimedia.org/api/rest_v1/media/math/render/svg/343779d82465137a7292f331e1e8f178307ca60d

**Comment by susilehtola** [comment]
All the more reason not to restrict to a minimal basis set.

**Comment by n-gao** [comment]
The description of @tberkel is right. Is there a way to obtain this?

@susilehtola how does this relate to the size of the basis set? Shouldn't it always be a N-electron Slater determinant?

**Comment by susilehtola** [comment]
@n-gao one must not confuse the single-electron basis with the many-electron basis. The former determines the molecular orbitals, the latter determines the set of determinants you form from the given molecular orbitals. In principle, there should be an infinite number of molecular orbitals: the discrete set of bound orbitals, and an infinite number of unbound i.e. scattering states.

If you go to the complete one-electron basis set limit, your Hartree-Fock will become exact. However, Hartree-Fock is the simplest many-electron model; it still only contains the one determinant.

This code should be close to what you want. I've generalized it to UHF

```
import numpy as np
from math import sqrt
from pyscf import gto, scf

# Construct molecule: oxygen atom in triplet ground state                                                                                                                                     
mol = gto.Mole(atom=[
  ['O', (0, 0, 0)],
], basis='ccpvtz', unit='bohr', spin=2, charge=0)
mol.build()

# Get the Hartree-Fock reference                                                                                                                                                              
mean_field = scf.UHF(mol)
mean_field.kernel()

# Number of electrons                                                                                                                                                                         
nalpha, nbeta = mol.nelec

# Electronic coordinates                                                                                                                                                                      
electron_coordinates = np.random.randn(nalpha+nbeta, 3)

# Evaluate the molecular orbitals at the position                                                                                                                                             
ao_val = mol.eval_gto('GTOval_sph', electron_coordinates)
moalpha_val = ao_val @ mean_field.mo_coeff[0][:,:nalpha]
mobeta_val = ao_val @ mean_field.mo_coeff[0][:,:nbeta]
# Concatenate them to get spin orbitals: we first have the alpha                                                                                                                              
# electrons, then the beta electrons                                                                                                                                                          
mo_val = np.concatenate((moalpha_val, mobeta_val), axis=1)
print(mo_val)

# Value of the Hartree-Fock wave function is                                                                                                                                                  
wf_value = np.linalg.det(mo_val)/sqrt(np.math.factorial(nalpha+nbeta))

print('value of wave function is {}\n'.format(wf_value))
```

**Comment by eljost** [comment]
This is probably expected for two reasons

1.) If any of the electron coordinate triplets become accidentally (too) similar the determinant should (nearly) vanish ([Pauli exclusion principle](https://en.wikipedia.org/wiki/Pauli_exclusion_principle))
2.) You just evaluate the wavefunction (Slater determinant) for one set of electron coordinates. Usually the wavefunction is normalized, so the square of its absolute value equals 1 (see [wikipedia](https://de.wikipedia.org/wiki/Wellenfunktion#Ein_Teilchen_in_drei_Raumdimensionen)). And this implies integration over all possible electron coordinates.

**Comment by n-gao** [comment]
I am aware of these properties of a Slater determinant though I think there is something else going on here.

1) I tested a lot of different configurations and all seem to evaluate to 0.
2) As far as I know the wave function should be normalized, thus the `/sqrt(np.math.factorial(nalpha+nbeta))`

**Comment by susilehtola** [comment]
Well the spin functions are missing from the matrix. I'm not sure how they should be evaluated.

**Comment by tberkel** [comment]
I think you don't want the np.concatenate() step. For the wavefunction, you
could use the product of the determinants of spin up and spin down. So you
could make an (N/2)x(N/2) matrix for spin up and another one for spin down.

**Comment by n-gao** [comment]
Would that actually be the correct wave function? (As the off diagonal blocks of the Slater determinant would be empty)

**Comment by gkc1000** [comment]
Yes, if you are evaluating at coordinates with definite spin projections up or down, and use a UHF determinant, then some orbitals will have no coefficient on the coordinate with the opposite spin projection, giving 0 in the Slater matrix.
