### ISSUE TITLE
UHF Natural Orbitals

### ISSUE THREAD

**Issue by HehnLukas** [pyscf/pyscf#947]
Is there a way to get the UHF Natural Orbitals, as described in this paper: [UHF natural orbitals for defining and
starting MC-SCF calculations](https://doi.org/10.1063/1.454704)? (Equation 3 to be precise) I am not quite sure about the nomenclature, so maybe it is already implemented somehow, but I am not finding it?

[UHF natural orbitals for defining and.pdf](https://github.com/pyscf/pyscf/files/6509262/UHF.natural.orbitals.for.defining.and.pdf)

**Comment by susilehtola** [comment]
Well this is pretty easy to do yourself: just sum the density matrices together `P=Pa+Pb`, convert to the MO space (use e.g. the alpha orbitals, `Pmo = Ca.T @ S @ P @ S @ Ca`), diagonalize to get NOs and NOONs `noons, nos = numpy.linalg.eigh(Pmo)`, and rotate the MOs with the NO matrix `Ca = Ca @ nos`. However, we should have example code for doing this.

I just checked and it seems we are still also missing the examples for initializing CASSCF with MP2/CISD natural orbitals.

**Comment by HehnLukas** [comment]
Thank you very much, I will look into doing this by hand. If you do find a full example code, that would obviously be quite helpful, but this should be a good starting point for me.

**Comment by jamesETsmith** [comment]
@HehnLukas, we have the tools to do this already check out [this](https://pyscf.org/user/mcscf.html#casci) example.

**Comment by susilehtola** [comment]
Oh I missed that. Yeah, just replace RHF with UHF, remove the MP2 bit and run the code on `myhf`.

**Comment by HehnLukas** [comment]
@jamesETsmith Thank you very much, it looks like it works as expected. I did find a bug that I had to fix, but this might just be from the hacky way I had to implement it. So on our system, we only have pyscf v 1.7.5 installed, and it looks like the make_natural_orbitals function is more recent. Therefore, I just copied the code for that function into its own file, so this might have been the source.

Anyways, in case this is not the cause for the bug, the problem I encounter is when I give in an UHF object, it still sees it as an numpy array instead of a tuple, albeit one with 3 dimensions. So the change I made is the following:
`# Slight difference for restricted vs. unrestriced case
    # Edited from original, original in comment after:
    ndim = numpy.ndim(rdm1)
    if ndim==3:
        Dm = rdm1[0]+rdm1[1]
    elif ndim==2:
        Dm = rdm1
    # if isinstance(rdm1, tuple):
    #     Dm = rdm1[0]+rdm1[1]
    # elif isinstance(rdm1, numpy.ndarray):
    #     Dm = rdm1
    else:
        raise ValueError(
            f"\n\tThe rdm1 generated by method_obj.make_rdm1() was a {type(rdm1)}."
            "\n\tThis type is not supported, please select a different method and/or "
            "open an issue at https://github.com/pyscf/pyscf/issues"
        )
`

**Comment by jamesETsmith** [comment]
@HehnLukas thanks for raising this, I wrote some tests for these utilities so I'm curious how this got through them, but thanks for bringing it to our attention. I'll update the tests and the source code sometime this week.

**Comment by HehnLukas** [comment]
Thanks a lot James!
