### ISSUE TITLE
Basis for heavy atoms calculations

### ISSUE THREAD

**Issue by MrRobot2211** [pyscf/pyscf#948]
Hi! Iam having trouble identifying a basis suitable for HF on atoms heavier than Krypton. Could you tell me if there is one readily available with the library or should I import it from somewhere else.  I am interested in this specially because I am using the DeepQMC library that uses RHF to build the initial Ansatz.

**Comment by susilehtola** [comment]
The Karslruhe def2 basis sets are an easy choice; they have ECPs on heavy atoms and they are available for the chemically relevant periodic table. You may want to use the variants with a double set of polarization functions e.g. def2-TZVPP that are tailored for for post-Hartree-Fock calculations.

If you want to use correlation-consistent sets, the annoyance is that the sets for light atoms without ECPs are cc-pVXZ while the ones for heavy atoms are cc-pVXZ-PP; you will have to mix and match to achieve the same result.

**Comment by MrRobot2211** [comment]
A million thanks to you @susilehtola ,  worked like a charm.
