### ISSUE TITLE
Output of eval_rho2() as Gaussian cube files

### ISSUE THREAD

**Issue by exenGT** [pyscf/pyscf#950]
Hi,

Is there a way to convert the output arrays of the function eval_rho2() in pbc/dft/numint.py into 3D Gaussian Cube files for visualization?

**Comment by susilehtola** [comment]
If there is not, it would be easy to add. The cube file format is basically just a list of atoms and then the point by point values of the density.

**Comment by exenGT** [comment]
Thanks! The issue is that the arrays output by eval_rho2() are one-dimensional. I'm not very sure how to map them to 3D. Is there a mapping between the 1D arrays to 3D arrays?

**Comment by fishjojo** [comment]
```
from pyscf.tools import cubegen
nx, ny, nz = cell.mesh
cc = cubegen.Cube(cell, nx, ny, nz)
rho = rho.reshape(cc.nx,cc.ny,cc.nz)
cc.write(rho, "rho.cube", comment='Electron density in real space (e/Bohr^3)')
```

**Comment by exenGT** [comment]
Thanks @fishjojo !
