### ISSUE TITLE
Compare gradient rho by FFT vs. gradient rho in real space

### ISSUE THREAD

**Issue by exenGT** [pyscf/pyscf#951]
I would like to implement a function which calculates gradient rho using fast Fourier transform (FFT) (the so-called "spectral derivative"), and compare it with the gradient rho calculated in real space by eval_rho2(). I see that the first output of eval_rho2() is the 1D array representation of rho. How can I perform FFT (and inverse FFT) on this array in the pyscf framework? I would greatly appreciate your help if a minimal example could be provided.

**Comment by fishjojo** [comment]
I don't quite understand what you are going to compare. But the Fourier transform of rho can be obtained as follows: 
```
from pyscf.pbc import tools
rhoG = tools.fft(rhoR, cell.mesh)
```

**Comment by exenGT** [comment]
Thanks @fishjojo ! Perhaps I should explain my request more clearly. To calculate the gradient rho using FFT, we need to have something like this:
```
grad_rhoG = 1j * G * rhoG
grad_rhoR = tools.ifft(rhoG, cell.mesh)
```
I'm wondering how can we obtain `G`?

**Comment by fishjojo** [comment]
```
Gv = cell.get_Gv()
```
