### ISSUE TITLE
Discrepancy in CASCI gradient formula between literature and code

### ISSUE THREAD

**Issue by jiangth1997** [pyscf/pyscf#952]
I am trying to derive the energy gradient of CASCI based on RHF orbitals. In Y. Yamaguchi, et al., _A new dimension to quantum chemistry: Analytic derivative methods in ab initio molecular electronic structure theory_, I found a formula for CI wave function: 

<img src="https://latex.codecogs.com/gif.latex?\frac{\partial&space;E_\text{tot}}{\partial&space;x}&space;=&space;\sum_{pq}{h_{pq}^x&space;\gamma_{pq}}&space;&plus;&space;\frac{1}{2}\sum_{pqrs}{(pq|rs)^x&space;\gamma_{pqrs}}&space;&plus;&space;2\sum_{pq}{U_{pq}^x&space;I_{pq}}" title="\frac{\partial E_\text{tot}}{\partial x} = \sum_{pq}{h_{pq}^x \gamma_{pq}} + \frac{1}{2}\sum_{pqrs}{(pq|rs)^x \gamma_{pqrs}} + 2\sum_{pq}{U_{pq}^x I_{pq}}" />

where <img src="https://latex.codecogs.com/gif.latex?U_{pq}^x" title="U_{pq}^x" /> is defined as <img src="https://latex.codecogs.com/gif.latex?\frac{\partial&space;C_{\mu&space;p}}{\partial&space;x}=\sum_q{U_{qp}^x&space;C_{\mu&space;q}}" title="U_def" />, and <img src="https://latex.codecogs.com/gif.latex?I_{pq}=\sum_r{h_{pr}\gamma_{rq}}&plus;\sum_{rms}{\gamma_{mqrs}(pm|sr)}" title="I_{pq}" />. 

After solving <img src="https://latex.codecogs.com/gif.latex?U^x" title="U^x" /> with closed-shell CPHF equations, this formula becomes

<img src="https://latex.codecogs.com/gif.latex?\frac{\partial&space;E_\text{tot}}{\partial&space;x}&space;=&space;\sum_{pq}{h_{pq}^x&space;\gamma_{pq}}&space;&plus;&space;\frac{1}{2}\sum_{pqrs}{(pq|rs)^x&space;\gamma_{pqrs}}&space;&plus;&space;2\sum_{uo}{((I_{uo}&space;-&space;I_{ou})U_{uo}^x&space;-&space;I_{ou}S_{uo}^x)}&space;-&space;\sum_{(p,p')\in(c,c),(b,b),(d,d),(v,v)}{I_{pp'}S_{pp'}^x}&space;&plus;&space;\frac{1}{2}\sum_{(p,p')\in(c,c),(b,b),(d,d),(v,v)}{\frac{I_{pp'}-I_{p'p}}{\epsilon_{p'}-\epsilon_p}}&space;(B_{0,pp'}^x&space;&plus;&space;B_{0,p'p}^x&space;&plus;&space;2\sum_{uo}{U_{uo}^x&space;A_{pp',uo}}))&space;&plus;&space;2\sum_{(p,q)\in(c,b),(b,c),(d,v),(v,d)}{\frac{I_{pq}}{\epsilon_q-\epsilon_p}(B_{0,pq}^x&space;&plus;&space;\sum_{uo}{U_{uo}^xA_{pq,uo})}}" title="Force_literature" />

where <img src="https://latex.codecogs.com/gif.latex?A_{pq,rs}=2(pq|rs)&plus;2(pq|sr)-(ps|rq)-(pr|sq)" title="A_mat" />, and <img src="https://latex.codecogs.com/gif.latex?B_{0,pq}^x=F_{pq}^x-\epsilon_qS_{pq}^x-\frac{1}{2}\sum_{o'o''}{S_{o'o''}^xA_{pq,o'o''}}" title="B_mat" />. c,b,d,v,o,u are partitions of molecular orbitals as shown in the figure. 

<img src="https://user-images.githubusercontent.com/52944224/119354033-2bdf2680-bcd6-11eb-97ad-e2578d149399.jpg" width = "200" height = "300" alt="" align=center />

However, in `pyscf/grad/casci.py` in `pyscf-1.7.6`, the program somehow throws away <img src="https://latex.codecogs.com/gif.latex?\frac{1}{2}\sum_{(p,p')\in(c,c),(b,b),(d,d),(v,v)}{\frac{I_{pp'}-I_{p'p}}{\epsilon_{p'}-\epsilon_p}(B_{0,pp'}^x&space;&plus;&space;B_{0,p'p}^x&space;&plus;&space;2\sum_{uo}{U_{uo}^x&space;A_{pp',uo}}))}" title="thrown_term" />. As a result, the code is calculating the following formula

<img src="https://latex.codecogs.com/gif.latex?\frac{\partial&space;E_\text{tot}}{\partial&space;x}&space;=&space;\sum_{pq}{h_{pq}^x&space;\gamma_{pq}}&space;&plus;&space;\frac{1}{2}\sum_{pqrs}{(pq|rs)^x&space;\gamma_{pqrs}}&space;&plus;&space;2\sum_{uo}{((I_{uo}&space;-&space;I_{ou})U_{uo}^x&space;-&space;I_{ou}S_{uo}^x)}&space;-&space;\sum_{(p,p')\in(c,c),(b,b),(d,d),(v,v)}{I_{pp'}S_{pp'}^x}&space;&plus;&space;2\sum_{(p,q)\in(c,b),(b,c),(d,v),(v,d)}{\frac{I_{pq}}{\epsilon_q-\epsilon_p}(B_{0,pq}^x&space;&plus;&space;\sum_{uo}{U_{uo}^xA_{pq,uo})}}" title="Force_code" />

I don't know why that term can be neglected, because I can't prove that I matrix is symmetric in (c,c),(b,b),(d,d) and (v,v) region. Do anyone know why that term is thrown away?

**Comment by sunqm** [comment]
The CASCI gradients code was transformed from the naive implementation https://github.com/pyscf/pyscf/blob/master/pyscf/grad/test/test_casci.py#L22 . Does the naive code agree to your derivation?

**Comment by jiangth1997** [comment]
It took me a few days to read the code, but I verified that kernel() function in test_casci.py is equivalent with pyscf/grad/casci.py. 

In 187-188 line, the (c,c), (b,b), (d,d) and (v,v) blocks of <img src="https://latex.codecogs.com/gif.latex?U_{pq}^x" title="U_{pq}^x" /> are initialized as <img src="https://latex.codecogs.com/gif.latex?-\frac{1}{2}S_{pq}^x" title="-\frac{1}{2}S_{pq}^x" />. This is equivalent with neglecting <img src="https://latex.codecogs.com/gif.latex?\frac{1}{2}\sum_{(p,p')\in(c,c),(b,b),(d,d),(v,v)}{\frac{I_{pp'}-I_{p'p}}{\epsilon_{p'}-\epsilon_p}(B_{0,pp'}^x&space;&plus;&space;B_{0,p'p}^x&space;&plus;&space;2\sum_{uo}{U_{uo}^x&space;A_{pp',uo}}))}" title="thrown_term" />.

**Comment by jiangth1997** [comment]
> The CASCI gradients code was transformed from the naive implementation https://github.com/pyscf/pyscf/blob/master/pyscf/grad/test/test_casci.py#L22 . Does the naive code agree to your derivation?

However, I am unclear why we can directly neglect 
<img src="https://latex.codecogs.com/gif.latex?\frac{1}{2}\sum_{(p,p')\in(c,c),(b,b),(d,d),(v,v)}{\frac{I_{pp'}-I_{p'p}}{\epsilon_{p'}-\epsilon_p}(B_{0,pp'}^x&space;&plus;&space;B_{0,p'p}^x&space;&plus;&space;2\sum_{uo}{U_{uo}^x&space;A_{pp',uo}}))}" title="thrown_term" />. 

In other words, I think it's not straightforward why we can initialize (c,c), (b,b), (d,d) and (v,v) blocks (shadowed area below) of <img src="https://latex.codecogs.com/gif.latex?U_{pq}^x" title="Ux" /> are initialized as <img src="https://latex.codecogs.com/gif.latex?-\frac{1}{2}S_{pq}^x" title="-0.5Sx" />.  

![orbital_partition_shadowed_small](https://user-images.githubusercontent.com/52944224/120452412-c02b4680-c3c4-11eb-9da8-a217a1f26ec3.jpg)

Is it because Lagrangian matrix is symmetric in the shadowed area?
