### ISSUE TITLE
Periodic calculation of diamond C-vacancy with GDF fails in 2.0.0 vs 1.7.x

### ISSUE THREAD

**Issue by btglau** [pyscf/pyscf#953]
I am running a calculation of a 222 tiling of the primitive diamond supercell with a carbon vacancy. This calculation successfully completes with pyscf 1.7.x but now fails in 2.0.0. I believe the problem stems from this issue:
https://github.com/pyscf/pyscf/issues/843 where changes to GDF were made based upon the discrepancy between supercells built by hand and pyscf's tools.

In pyscf 2.0.0, GDF outputs a new error message that it did not in pyscf 1.7.x:
`DF metric linear dependency for kpt 0`
`cond = -1.704e+04, drop 143 bfns`
Which is triggered at this line: https://github.com/pyscf/pyscf/blob/master/pyscf/pbc/df/df.py#L218

Additionally, a colleague has found that using gth-szv or gth-dzv (rather than gth-dzvp in the MWE) or FFTDF will converge the SCF calculation.

This error is also present in a pristine supercell, i.e. without the C-vacancy. I have attached a MWE example that demonstrates this error, as well as the output. In both cases the initial energy is reasonable but immediately diverges on cycle 1.

[MWE-diamond_GR1.txt](https://github.com/pyscf/pyscf/files/6542171/MWE-diamond_GR1.txt)
[1026174_00-diamond_GR1.txt](https://github.com/pyscf/pyscf/files/6542169/1026174_00-diamond_GR1.txt)
[1026178_00-diamond_pristine.txt](https://github.com/pyscf/pyscf/files/6542170/1026178_00-diamond_pristine.txt)

**Comment by Majokux** [comment]
Interesting, do you also have the 1.7.x output, of the converging calculation?
Just to double check: You do not use exp_to_discard here, are you sure you didn't use it in the converging 1.7 calculations?

The linear dependency message is not necessarily an error - it just means that the auxiliary basis for the coulomb metric is overcomplete and some functions have to be removed; it is however weird that this message is only present in 2.0 and not 1.7, when you use the same input.

**Comment by btglau** [comment]
Hi Majokux,

I mentioned the linear dependency error because it did not show up in 1.7.x, so my hypothesis is that the bug fix to address Issue 843 changed the behaviour of GDF.

I have some updates:

1) The SCF calculation fails with a single primitive cell
2) It will also fail with a primitive cell and 222 kpoint sampling
3) Fails at hand built 222 supercell

All calculations above will converge with pyscf 1.7.x:

> commit 15957003aa26b165a823e7e2d0846a8564b2a10c
>Merge: 85237e8 4f38bfb
>Author: gkc1000 <gkc1000@gmail.com>
>Date:   Sat Dec 5 19:33:32 2020 -0800
>    Merge pull request #775 from susilehtola/lo_doc
>    Improve documentation of Pipek-Mezey

The 222 supercell energy per atom matches the 111 + 222 kpoint sampling.

I have attached the output files for 1.7.x below:
[1026368_MWE-diamond_GR1_222_mpty.txt](https://github.com/pyscf/pyscf/files/6547815/1026368_MWE-diamond_GR1_222_mpty.txt)
[1026369_MWE-diamond_GR1_111_222_mpty.txt](https://github.com/pyscf/pyscf/files/6547816/1026369_MWE-diamond_GR1_111_222_mpty.txt)
[1026370_MWE-diamond_GR1_111_mpty.txt](https://github.com/pyscf/pyscf/files/6547817/1026370_MWE-diamond_GR1_111_mpty.txt)

**Comment by tberkel** [comment]
If you do something like `GDF.exp_to_discard = 0.2`, do they all converge?
Others in the group have seen convergence problems due to linear
dependencies in the auxiliary basis. This won't explain what changed
between 1.7 and 2.0, but would at least start to pin down the problem.

**Comment by jamesETsmith** [comment]
I tried that for something similar to Bryan's GR1_222 example (and v2.0) and it didn't fix weird energies

**Comment by Majokux** [comment]
> Hi Majokux, thanks for your attention.
> 
> I mentioned the linear dependency error because it did not show up in 1.7.x, so my hypothesis is that the bug fix to address Issue 843 changed the behaviour of GDF.
> 
> I also do not use exp_to_discard.
> 
> I have some updates:
> 
> 1. The SCF calculation fails with a single primitive cell
> 2. It will also fail with a primitive cell and 222 kpoint sampling
> 3. Fails at hand built 222 supercell
> 
> All calculations above will converge with pyscf 1.7.x:
> 
> > commit [1595700](https://github.com/pyscf/pyscf/commit/15957003aa26b165a823e7e2d0846a8564b2a10c)
> > Merge: [85237e8](https://github.com/pyscf/pyscf/commit/85237e80ee965949ebbd12059b85c7777bb44ecb) [4f38bfb](https://github.com/pyscf/pyscf/commit/4f38bfba4c00bedba57139266600ba2174a1e58f)
> > Author: gkc1000 [gkc1000@gmail.com](mailto:gkc1000@gmail.com)
> > Date:   Sat Dec 5 19:33:32 2020 -0800
> > Merge pull request #775 from susilehtola/lo_doc
> > Improve documentation of Pipek-Mezey
> 
> The 222 supercell energy per atom matches the 111 + 222 kpoint sampling.
> 
> I have attached the output files for 1.7.x below:
> [1026368_MWE-diamond_GR1_222_mpty.txt](https://github.com/pyscf/pyscf/files/6547815/1026368_MWE-diamond_GR1_222_mpty.txt)
> [1026369_MWE-diamond_GR1_111_222_mpty.txt](https://github.com/pyscf/pyscf/files/6547816/1026369_MWE-diamond_GR1_111_222_mpty.txt)
> [1026370_MWE-diamond_GR1_111_mpty.txt](https://github.com/pyscf/pyscf/files/6547817/1026370_MWE-diamond_GR1_111_mpty.txt)
> 
> And the corresponding 2.0.0:
> [1026341_MWE-diamond_GR1_111_mpty.txt](https://github.com/pyscf/pyscf/files/6547833/1026341_MWE-diamond_GR1_111_mpty.txt)
> [1026342_MWE-diamond_GR1_111_222_mpty.txt](https://github.com/pyscf/pyscf/files/6547834/1026342_MWE-diamond_GR1_111_222_mpty.txt)
> [1026343_MWE-diamond_GR1_222_mpty.txt](https://github.com/pyscf/pyscf/files/6547835/1026343_MWE-diamond_GR1_222_mpty.txt)

Funky. Are you sure it has to do with #847 / #843 ? Since you don't use exp_to_discard, these changes should not affect you.

**Comment by tberkel** [comment]
Funky indeed! Failing on a single 2-atom primitive cell of diamond is
catastrophic ...

**Comment by btglau** [comment]
To confirm it's not a problem with my input file, you can run the example:

https://github.com/pyscf/pyscf/blob/master/examples/pbc/35-gaussian_density_fit.py

With the basis set to gth-dzvp, and it will fail. It successfully completes with 1.7.x.

**Comment by btglau** [comment]
And I can also confirm that with the default basis of `gth-dzv`, the default GDF will converge (the subsequent modifications of GDF do not converge, but at least get to the right ballpark of -10 Ha).

**Comment by btglau** [comment]
> Funky. Are you sure it has to do with #847 / #843 ? Since you don't use exp_to_discard, these changes should not affect you.

I'm not sure, and sorry if I'm prematurely pointing fingers. Between my version and 2.0.0, that was the only major change I could identify. I'll try pulling specific versions and seeing which particular commit causes the problem.

**Comment by Majokux** [comment]
No worries about pointing fingers, just trying to figure out where the behavior diverged.

If it is indeed #843 , it is almost certainly in `make_modrho_basis` in `pbc/df/df.py`.
I don't understand this function well enough, but one thing that comes to mind is line 88,
where `auxcell._env` has *not* been replaced with the copy introduced in #847, `_env` - I could see that this could lead to a different behaviour, even with exp_to_discard not set. It is almost certainly done on purpose this way (otherwise the changes to this function wouldn't do anything?).

So I guess one thing is to check is if we get the old behaviour back, if we replace `auxcell._env` with `_env` here.
And then the question is if the new behaviour is correct, and the sytem is really that linearly-dependent?

**Comment by fishjojo** [comment]
I have tried your original C-vacancy example, and it converges without any problem.
[C.txt](https://github.com/pyscf/pyscf/files/6549141/C.txt)
Can you provide the output file of a smaller failing example with mol.verbose set to 7? Thanks.

**Comment by btglau** [comment]
Hi fish, majo,

We've (tberkel and jamesETsmith) shifted focus of the source of the problem to libcint / qcint, where the latest version of qcint is what causes the problem (with dzvp, but not dzv). We don't know which version of qcint specifically, presumably between Dec 2020 and now.

**Comment by sunqm** [comment]
Can you try again with small max_memory? For example setting to 10 GB. I couldn't reproduce the problem in my environment.

**Comment by btglau** [comment]
Hi sunqm,

I ran with 10G of memory, but the SCF still will not converge.

[1027546_35-gaussian_density_fit_mwe_mpty_MAXMEM512G.txt](https://github.com/pyscf/pyscf/files/6555122/1027546_35-gaussian_density_fit_mwe_mpty_MAXMEM512G.txt)
[1027547_35-gaussian_density_fit_mwe_mpty_MAXMEM10G.txt](https://github.com/pyscf/pyscf/files/6555123/1027547_35-gaussian_density_fit_mwe_mpty_MAXMEM10G.txt)

My compilation environment is:
 1) cmake/3.19.1   2) gcc/7.4.0(default)   3) intel/mkl/2020

However, I have used these settings with 1.7.x without issue. 

Separately, I also found a bug in the example 35:
https://github.com/pyscf/pyscf/blob/master/examples/pbc/35-gaussian_density_fit.py#L94
Where RHF should be KRHF.

**Comment by verena-neufeld** [comment]
@btglau would you like to do a pull request for the bug in example 35 where this can be discussed further?

**Comment by susilehtola** [comment]
Yes, this might definitely arise from the same problem as #1018 i.e. wrong integrals from qcint.

Unfortunately, it appears that libcint and qcint don't have unit tests... Do any of the test builders use qcint?

**Comment by verena-neufeld** [comment]
@btglau , thanks for posting this issue! @btglau and @sunqm , has this been resolved?
