### ISSUE TITLE
Irrep of  operators in second quantization

### ISSUE THREAD

**Issue by martinanibbi** [pyscf/pyscf#957]
hello,

I would like to please ask a question about how PySCF handles symmetries: given a molecule with a well-defined symmetry group (e.g. H2O with C2v) and given a set of molecular orbitals p,r,q,s labeled by well-defined irreps (e.g. A1 or B1),  I would like to compute the irrep of the operators a^\dagger(p) a(r) and a^\dagger(p) a^\dagger(q) a(s) a(r) in second quantization.
Does PySCF offer a functionality to do that?

thanks,
Martina Nibbi

**Comment by jamesETsmith** [comment]
@martinanibbi here are a couple of options:

1. You can use the `label_orb_symm()` function from the symmetry module to get the irreps of all your orbitals

https://github.com/pyscf/pyscf/blob/0bc4b2037be70ec03f1272a73520735f18263492/pyscf/symm/addons.py#L58-L63

Then you can take the appropriate product by hand with a product table for your appropriate symmetry.

2. A more automated strategy, would be to use `get_wfnsym()` with your mean field object and just pass as `mo_occ`  an array where the four indices you're interested in are 1 and the rest of the values are 0. See the function for more details here:

https://github.com/pyscf/pyscf/blob/0bc4b2037be70ec03f1272a73520735f18263492/pyscf/scf/hf_symm.py#L331

**Comment by martinanibbi** [comment]
The second option is closer to what I was looking for, thank you very much!

**Comment by verena-neufeld** [comment]
Hi @martinanibbi , thanks for having raised this issue. Is it resolved and can it be closed?
