### ISSUE TITLE
<class 'pyscf.pbc.scf.hf.RHF'> does not have attributes  rsjk

### ISSUE THREAD

**Issue by verena-neufeld** [pyscf/pyscf#962]
When running example 35-gaussian_density_fit.py, I get the error or warning:
<class 'pyscf.pbc.scf.hf.RHF'> does not have attributes  rsjk

**Comment by tberkel** [comment]
That's not unique to example 35. Every PBC calculation starting in 2.0 has
that message since Qiming's implementation of exact 4-center periodic SCF
("RSJK").

**Comment by verena-neufeld** [comment]
Fair enough, thanks :). I guess it would be less confusing to not have this warning or write a different kind of warning if the warning is indeed deliberate.
