### ISSUE TITLE
Davidson for generalized eigenvalue problem

### ISSUE THREAD

**Issue by StefanoBarison** [pyscf/pyscf#965]
Good morning,

sorry to bother, but I have a question about a possible feature implemented in PySCF.
Does PySCF have an implementation of the Davidson diagonalization algorithm for generalized eigenvalue equations Hc=ESc? I saw that in the FCI module for ordinary eigenvalue equations (S = Id). Is that right or am I missing something? 

Looking forward to reading from you.

Regards,
Stefano Barison

**Comment by gkc1000** [comment]
Yes. The linalg routines are here:
https://github.com/pyscf/pyscf/blob/master/pyscf/lib/linalg_helper.py

and the corresponding generalized Davidson function is called dgeev (line 980)

**Comment by StefanoBarison** [comment]
Thank you very much for the help!

Best regards,
Stefano
