### ISSUE TITLE
Core orbitals in CASSCF calculation aren't frozen?

### ISSUE THREAD

**Issue by martinanibbi** [pyscf/pyscf#966]
Hello, 

During a CASSCF calculation I have noticed an unexpected behavior and I would like to please ask for clarification.
In particular, I have calculated the ground state energy of the CuH molecule through HF and CASSCF calculations (with a really small active space) and I would like to show the overlap matrix between the coefficient matrices of the HF and CASSCF simulations:

``` 
mol = gto.Mole() 
mol.build(atom     = [['Cu',(0,0,0)],['H',(0,0,1.46)]],
          basis    = '6-31g',
          symmetry = 'Coov',
          charge   = 0,
          spin     = 0,
          verbose  = 4)

mf      = scf.ROHF(mol)
E       = mf.kernel()
C_HF    = mf.mo_coeff
mf.stability()

freeze = 14
cas_space_symmetry = {'A1':2}

nact   = sum([cas_space_symmetry[k] for k in cas_space_symmetry.keys()])                   
na,nb  = (mol.nelectron+mol.spin)//2-freeze,(mol.nelectron-mol.spin)//2-freeze

mc     = mcscf.CASSCF(mf,nact,(na,nb))
mo     = mcscf.sort_mo_by_irrep(mc,mf.mo_coeff,cas_space_symmetry)
mc.fcisolver.wfnsym = 'A1'
E = mc.kernel()
if(not mc.converged):
   E = mc.kernel(mc.mo_coeff,mc.ci)

C_CASSCF = mc.mo_coeff
S        = mf.get_ovlp()
S_HF_CASSCF = np.einsum('pi,pq,qj->ij',C_HF,S,C_CASSCF)
for i in range(S_HF_CASSCF.shape[0]):
    for j in range(S_HF_CASSCF.shape[1]):
        print(i,j,S_HF_CASSCF[i,j])
``` 

Everything works fine and the final energies are reasonable, but the outcome of the overlap matrix S_HF_CASSCF surprised me.
I indeed expected a block matrix with identities corresponding to frozen orbitals (as they should not change during an active space calculation) but I have noticed that this is true only in approximation (and not a small one).

Here below you can read as an example the second row of the matrix S_HF_CASSCF corresponding to the second orbital of the molecule (which should be frozen):
``` 
-3.8552915745073375e-06   0.9999970055862905   0.002432044308920312   0.0   0.0   5.269156589579027e-05   6.262102902712177e-05   0.0   0.0   0.0   0.0   3.588307377061853e-06   0.0   0.0   0.00018327684867505516   -5.9073813126775745e-05   0.0   0.0   2.0679290735889366e-05   -5.280679823530671e-06   0.0   0.0   5.897061965298711e-06   3.259570609009943e-05   0.0   0.0   0.0   0.0   -0.00016917596551833947
``` 
As you can notice this is close to what I would expect (1 in second position and 0 elsewhere) but not as close as I thought.

If the outcome is correct (as well as the interpretation I have given to it) this would imply that the frozen orbitals aren't actually frozen as they change during an active space calculation... how could it be possible?

Thanks, 
Martina Nibbi

**Comment by xubwa** [comment]
CASSCF optimizes the orbitals, the core orbitals will sure change as the optimization going on. So what you see is what you are expected to see. If you want to freeze some core orbitals, then you can check out this example [https://github.com/pyscf/pyscf/blob/master/examples/mcscf/19-frozen_orbital.py](url), if you want to freeze all the inactive orbitals, then you are simply not optimizing the orbitals, then you should use CASCI instead.

**Comment by martinanibbi** [comment]
Hello, 
Thank you very much for your answer!
So, if I may ask for further clarification, does it mean that with CASSCF orbitals are all optimizable but those not belonging to the active space have a frozen population?
Otherwise, what distinguishes between active and not active orbitals?

thanks,
Martina

**Comment by Majokux** [comment]
Active orbitals are treated exactly, with a Full-CI solver (by default), i.e. their "motion" is fully correlated.
Inactive orbitals are only treated on the mean-field level, i.e. they are not correlated.
CASSCF optimizes the selection of active orbitals each iteration, based on a variational principle.
If you want to exclude some orbitals from this optimization, declare them as frozen (which is not the same as inactive - frozen orbitals are always inactive, but inactive orbitals are not by default frozen). If you don't want any orbital optimization, use CASCI.

**Comment by martinanibbi** [comment]
Thank you for your help, I was a bit confused about the meaning of frozen orbitals and active/inactive orbitals, as I thought frozen and inactive meant the same thing.
Now everything is a lot clearer, thank you very much!
