### ISSUE TITLE
dft.libxc.eval_xc returns Nan values with GGA pseudopotential

### ISSUE THREAD

**Issue by mbarbry** [pyscf/pyscf#968]
Dear PySCF developpers,

I'm trying to get the exchange correlation kernel for a GGA pseudopotential (GGA_X_ITYH_PBE). However, the returned Vxc arrays contains some Nan values.

The same code for a LDA,PZ pseudopotential for the same inputs works ok. Any idea what could be the reason that libxc return finite values for LDA pseudopotental and Nan for GGA pseudopotential for the same electron density?

**Comment by susilehtola** [comment]
That’s not a pseudopotential but an exchange correlation functional.

Which version of PySCF are you using? Which version of libxc?

Range separated functionals have had major work in libxc 5.1.x; your problem is likely caused by the use of an old version of PySCF.

**Comment by mbarbry** [comment]
Hi,

Thanks for the fast answer and sorry for the terminology error, my quantum chemistry is quite rusted.

I'm using PySCF version 2.0.0a  and libxc version is 5.1.2

To give a bit of context, I'm implementing a TDDFT code that uses PySCF (https://gitlab.com/mbarbry/pynao).
The code currently supports only LDA functionals and we are now trying to add GGA support.

**Comment by susilehtola** [comment]
Are you sure the NaNs don't arise from your code? Did you check that the density variables are okay? E.g. the density should be non-negative at every point etc.

If the input is okay, then the next step is to figure out what values of the density lead to NaNs for the functional.

**Comment by susilehtola** [comment]
Can you supply a PySCF example calculation that yields NaNs?

**Comment by mbarbry** [comment]
Hi,

I managed to reproduce the issue with a small script. However, the problem seems to occur randomly, i.e., with the same inputs, the number of Nan differs with different calls.

I included some comments in the script.
[check_eval_xc.tar.gz](https://github.com/pyscf/pyscf/files/6598310/check_eval_xc.tar.gz)


What I get on my computer, I will try on another one to check if the issue is reproducible.

![image](https://user-images.githubusercontent.com/14218658/120798893-4f0f9e80-c53e-11eb-892f-579c22682126.png)

**Comment by susilehtola** [comment]
I ran your input 40 times and didn't get a single NaN.

**Comment by mbarbry** [comment]
I have also difficulties reproducing it, but adding more data sets I could. I include below more datasets and the docker recipe I used for testing on my second computer (it takes a while to build).

[check_eval_xc.tar.gz](https://github.com/pyscf/pyscf/files/6598611/check_eval_xc.tar.gz)

![image](https://user-images.githubusercontent.com/14218658/120804370-d9f39780-c544-11eb-8aaa-8a450e2726ee.png)

**Comment by mbarbry** [comment]
Here is a lighter docker recipe. Let me know if you managed to reproduce the issue.

[Dockerfile.gga.minimal.zip](https://github.com/pyscf/pyscf/files/6599540/Dockerfile.gga.minimal.zip)

**Comment by susilehtola** [comment]
I get no errors for your larger test set.

**Comment by mbarbry** [comment]
Did you try with the docker image?

**Comment by mbarbry** [comment]
I also get the issue when installing pyscf via pip. In this case, it is pyscf version 1.7.6 

[Dockerfile.gga.minimal_pip.zip](https://github.com/pyscf/pyscf/files/6599912/Dockerfile.gga.minimal_pip.zip)

![Screenshot_2021-06-04_18-24-01](https://user-images.githubusercontent.com/14218658/120833418-108bdb00-c562-11eb-9350-989235160f20.png)

umhh, maybe something in the inputs is not right.

**Comment by susilehtola** [comment]
Yes, because the pip packages use an obsolete version of libxc

**Comment by mbarbry** [comment]
The issue does not seem to be related to the libxc version since it fails for both.
I can see in `eval_xc` that the Nan value come from the call `_itrf.LIBXC_eval_xc` in the `outbuf` array

If I look if the array is finite as done below

![image](https://user-images.githubusercontent.com/14218658/121022702-deb58700-c7a2-11eb-96e5-701559ac6303.png)


I get the following output

![image](https://user-images.githubusercontent.com/14218658/121023045-3227d500-c7a3-11eb-895b-ebd211bc36a5.png)


We can see that element 1, 3 and 4 in `outbuf` contains non-finite element.

I attached further charge densities, hopefully, someone can reproduce the issue.

[check_eval_more_dataset.tar.gz](https://github.com/pyscf/pyscf/files/6609164/check_eval_more_dataset.tar.gz)

**Comment by fishjojo** [comment]
I noticed that the `rho` in your script only contains the density, but for GGA functionals, you also need to pass the density gradients. So the correct `rho` should have the shape of (4, N).

**Comment by mbarbry** [comment]
Thanks a lot @fishjojo for noticing this. I was not aware of the shape requirement. I will try to correct this.
Maybe some check could be implemented in the `eval_xc` function?
