### ISSUE TITLE
Issues compiling current master branch from source

### ISSUE THREAD

**Issue by ssh2** [pyscf/pyscf#969]
Hi everyone,

I just tried compiling the current master branch source and I am getting the following compilation error: 

pyscf/lib/gto/ft_ao.c:138:18: error: ‘CART_MAX’ undeclared (first use in this function); did you mean ‘RAND_MAX’?
         int i_nx[CART_MAX], i_ny[CART_MAX], i_nz[CART_MAX];
                  ^~~~~~~~
                  RAND_MAX

Looks like CART_MAX definition was removed in 392b827491e7c0b9b13b1283a3deb97ab79e482f (PR #930). Defining CART_MAX solves the problem. I used GCC 7.3.0 for the compilation.

**Comment by fishjojo** [comment]
You probably need to upgrade libcint. Remove libcint in lib/deps and the
downloaded source in build/deps and recompile should work.

Alexander Sokolov ***@***.***>于2021年6月3日 周四上午9:25写道：

**Comment by ssh2** [comment]
Recompiling libcint solves the problem. Thanks!
