### ISSUE TITLE
Analyze function of TDDFT gives ???

### ISSUE THREAD

**Issue by HansolP** [pyscf/pyscf#976]
tddft.analyze() gives ??? for symmetry information.
Until the 1.7.4 version, it worked properly, but pyscf 1.7.6post1 version works weirdly.
Performing TDDFT for CO molecule with "mol.symm=True" option, I got below log.
----------------------------------
******** <class 'pyscf.tdscf.rks.TDDFTNoHybrid'> for <class 'pyscf.dft.rks_symm.SymAdaptedRKS'> ********
nstates = 10 singlet
wfnsym = None
conv_tol = 1e-09
eigh lindep = 1e-12
eigh level_shift = 0
eigh max_space = 50
eigh max_cycle = 100
chkfile = 👍 
max_memory 400000 MB (current use 355 MB)

Excited State energies (eV)
[ 8.2434532   8.2434532   9.65463504  9.86426254 10.18527347 10.18527462
 10.29198412 10.33232945 10.33232945 12.23372052]

 Singlet excitation energies and oscillator strengths 
Excited State   1:  **???**      8.24345 eV    150.40 nm  f=0.0876
       7 -> 8        -0.42822
       7 -> 9        -0.54806
Excited State   2:  **???**      8.24345 eV    150.40 nm  f=0.0876
       7 -> 8         0.54806
       7 -> 9        -0.42822
Excited State   3:   A1      9.65464 eV    128.42 nm  f=0.0150
       7 -> 10       -0.68228
       7 -> 11       -0.17205
Excited State   4:  **???**      9.86426 eV    125.69 nm  f=0.0000
       5 -> 9        -0.50000
       6 -> 8         0.50000
Excited State   5:  **???**     10.18527 eV    121.73 nm  f=0.0000
       5 -> 8         0.49988
       6 -> 9        -0.49988
---------------------------------------------------------

Thank you

**Comment by tberkel** [comment]
While I don't know the source of the change, I can confirm that this
behavior persists to the latest version 2.0.0a.

**Comment by fishjojo** [comment]
I guess this is too tight

    possible_sym = x_sym[(x > 1e-7) | (x < -1e-7)]

**Comment by tberkel** [comment]
At least for a CO molecule test I ran, it's the opposite, i.e., the
analysis finds that there are two possible symmetries (B1 or B2), so it
prints "???".

**Comment by sunqm** [comment]
It's due to high dimensional irreducible representations, as shown by @tberkel 's example. Current version does not support to purify the root of the degenerated irreps.  In the older versions, it maps to D2h symmetry and print out the symmetry under D2h irreps.

**Comment by verena-neufeld** [comment]
@HansolP , thanks for posting this issue. Has it been resolved?

**Comment by sunqm** [comment]
Solved by PR #2382
