### ISSUE TITLE
Get local part of pseudopotential in real space

### ISSUE THREAD

**Issue by exenGT** [pyscf/pyscf#978]
How do I get the local part of pseudopotentials V<sub>loc</sub>(**r**) in real space (**r** = (x, y, z)), for a periodic system?

**Comment by fishjojo** [comment]
https://github.com/pyscf/pyscf/blob/9291e74890069d522efdd1f0505c12e27530fa64/pyscf/pbc/gto/pseudo/pp.py#L229-L244

This gives you the local part of the GTH pseudopotential on a uniform grid.
