### ISSUE TITLE
Compiling with AMD AOCL?

### ISSUE THREAD

**Issue by btglau** [pyscf/pyscf#980]
Hello devs,

Can pyscf be compiled with the AMD equivalent of MKL, AOCL?

1) Are the AOCL libraries a drop in replacement for the functional that pyscf needs from other BLAS? I assume that to be the case, although the closed source bits of AOCL, such as LibM and amd_memcpy, look like they require changes to code.

2) Ideally, there would be a substitution for:

`cmake -DBLA_VENDOR=Intel10_64lp_seq ..`

however, CMake FINDBLAS does not seem to support AOCL yet, as I found a code in molcas' CMakeLists that addresses this issue:
https://github.com/Molcas/OpenMolcas/blob/master/CMakeLists.txt#L1271

**Comment by jamesETsmith** [comment]
Hey @btglau, you can try setting the path to your AOCL BLAS by setting some cmake variables in the `CMakeLists.txt` file. Check out these lines:

https://github.com/pyscf/pyscf/blob/9291e74890069d522efdd1f0505c12e27530fa64/pyscf/lib/CMakeLists.txt#L73-L85

**Comment by btglau** [comment]
My cluster department responded with:

"Considerable testing showed that AOCC/AOCL, at the current time, is not particularly performant compared to other options. The LAPACK implementation is incomplete, and still quite complicated to incorporate into your code. There is some drop-in support, but it's not always straightforward."

With the conclusion that compiling with MKL is the best practice as of now. I will update in the future if there is any progress with AMD's compilers.

**Comment by sunqm** [comment]
It's probably better to use MKL and the "famous" setting  `MKL_DEBUG_CPU_TYPE=5` for AMD cpu

https://www.pugetsystems.com/labs/hpc/How-To-Use-MKL-with-AMD-Ryzen-and-Threadripper-CPU-s-Effectively-for-Python-Numpy-And-Other-Applications-1637/

**Comment by jamesETsmith** [comment]
Just be aware that support for that env variable (`MKL_DEBUG_CPU_TYPE`) is being pulled for more recent versions of MKL (2020.1 and onward) see [here](https://danieldk.eu/Posts/2020-08-31-MKL-Zen.html) for more details. I've had pretty good luck with BLIS on AMD machines and it's a breeze to compile so I'd recommend it. Since it's only tangentially related to this issue, we can talk more about it offline if you're interested.
