### ISSUE TITLE
D3 and D4 empirical dispersion corrections

### ISSUE THREAD

**Issue by kjelljorner** [pyscf/pyscf#983]
I could not get the install of the [dftd3 extension](https://github.com/pyscf/dftd3) to work (MacOS). My suggestion would be to link to the new [dftd4 package](https://github.com/dftd4/dftd4) which is installable by conda. There is also a [Python interface](https://github.com/dftd4/dftd4/tree/main/python) that makes calculation of dispersion energies trivial. This is also installable via conda. I know that @awvwgk also has plans to make his [D3 calculator](https://github.com/awvwgk/simple-dftd3) available via this route as well.

**Comment by awvwgk** [comment]
Working on native support for PySCF in https://github.com/awvwgk/simple-dftd3/pull/17 now. The `dftd3.pyscf` module should be a drop-in replacement for `pyscf.dftd3.itrf`.

**Comment by sunqm** [comment]
The pyscf interfaces provided by dftd3 https://dftd3.readthedocs.io/en/latest/api/pyscf.html and dftd4 https://dftd4.readthedocs.io/en/latest/reference/pyscf.html are the recommended way to add dispersion corrections.
