### ISSUE TITLE
Failed CCSD calculation for H2 molecule

### ISSUE THREAD

**Issue by ddhawan11** [pyscf/pyscf#985]
Hi Developers,

I have been trying to run couple-cluster calculations using pyscf by passing the Hamiltonian for Hydrogen molecule in STO-6G basis in MO basis. It fails with the error: "assert(t2.dtype == numpy.double)".
I tried running FCI to make sure and that provides me with an absurd number. I have attached the files for reference. 

I tried using the same Hamiltonian with other packages and it works fine. 

I am attaching the files here for reference. 
[H2_sto-6g.tar.gz](https://github.com/pyscf/pyscf/files/6651153/H2_sto-6g.tar.gz)

Any help would be much appreciated!

**Comment by Majokux** [comment]
Can you add `print(type(t))` and `print(t.dtype)` (same for `v`) after you unpickled them and see what it prints?
PySCF will expect these to be double precision floating point numbers.

**Comment by ddhawan11** [comment]
Thanks, it seems like it won't take float128 but requires float64 only.

**Comment by sunqm** [comment]
For CCSD, pyscf/cc/rccsd.py. It's a pure python implementation.  You can remove these type assertions and change the lib.einsum to np.einsum in the code. Then ccsd can be solved with float128 or other data type
