### ISSUE TITLE
how to obtain spin-squared matrix?

### ISSUE THREAD

**Issue by mariomotta** [pyscf/pyscf#988]
Greetings,

The example
https://github.com/pyscf/pyscf/blob/master/examples/fci/15-FCI_hamiltonian.py
shows how to compute the Hamiltonian matrix H(a,b) = <a|H|b> in a space of Slater determinants.
Is there an analogous command (or any other way) to obtain 
the spin-squared matrix S(a,b) = <a|S**2|b> in a space of Slater determinants?

Thanks for the attention,
Mario

**Comment by fishjojo** [comment]
https://github.com/pyscf/pyscf/blob/9291e74890069d522efdd1f0505c12e27530fa64/pyscf/fci/spin_op.py#L180

This function may be useful for your problem. You may set fcivec to ones and do another contractions with the bra determinants.

**Comment by mariomotta** [comment]
Thank you very much,
the function you recommended works just as desired.
