### ISSUE TITLE
External stability analysis (UHF) returns wrong shape

### ISSUE THREAD

**Issue by HehnLukas** [pyscf/pyscf#997]
I have just recently started trying to implement the UHF stability analysis, and have had some problems with the external=True flag. I have not found any clear examples using it, so possibly I am just misunderstanding its purpose.

The behavior I would expect is the same as in lines 41-46 of this [example](https://github.com/pyscf/pyscf/blob/master/examples/scf/17-stability.py), just with this line 
`mo1 = mf.stability()[0]`
replaced by 
`mo1 = mf.stability(external=True)[1]`

However, this leads to an error, because the shape the external stability analysis returns (`np.shape(mf.stability(external=True)[1]`) is not the same as `np.shape(mf.mo_coeff)` or `np.shape(mf.stability(external=True)[0])`. In my case it is (606, 606), while the mo_coeffs and the  `np.shape(mf.stability(external=True)[0])` have the shape (2, 303, 303). 

In my tests, this has happened both with stable and unstable wavefunctions in UHF/UKS -> GHF/GKS analysis, I have not found any of my wavefunctions to be unstable in real -> complex stability analysis, so I can't say if that influences it.

I am using v1.7.5, but there aren't any updates to pyscf/pyscf/scf/stability.py since 1.7.2

Additionally, I very much think this feature request for stability analysis would be quite helpful: #873

**Comment by verena-neufeld** [comment]
I am not entirely sure, so if someone else could confirm that would be great, but I'd guess that for example when you do RHF stability analysis with `external=True`, you'll get MO coefficients for a UHF wavefunction out, which has a different shape. For UHF external stability analysis, this would be GHF?

**Comment by susilehtola** [comment]
If one gives you 2 x 303 x 303, this sounds like a UHF stability matrix with two channels each containing a 303 x 303 rotation matrix. 606 x 606 sounds like GHF.

**Comment by HehnLukas** [comment]
Ok I see, so this is the intended behavior. I apologize, I had not heard of GHF before.
